### DISCUSSION TITLE
can't enable admin api on docker deployment

### DISCUSSION THREAD

**Discussion by bdonfouet** [prometheus/prometheus#10069] [Q&A]
**What did you do?**
i've added the ​"--web.enable-admin-api" api in my docker-compose file
```
version: '3.7'

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /opt/prometheus/prometheus/config:/etc/prometheus/
      - /opt/prometheus/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=2y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.external-url=http://hostname:9090'
```
**What did you expect to see?**
Admin API to be enabled
**What did you see instead? Under which circumstances?**
after reload of prometheus, the admin api is not enabled, and the parameter seem to have been ignore.
here the output of docker inspect on the prometheus container after apllying change:
```
docker inspect prometheus_prometheus_1
[
    {
        "Id": "6280f488be2e4a7a46eec1a8a6ff16e8949bffcd24554fcc5d52edb46eb051b7",
        "Created": "2021-12-13T22:25:47.221756077Z",
        "Path": "/bin/prometheus",
        "Args": [
            "--config.file=/etc/prometheus/prometheus.yml",
            "--storage.tsdb.path=/prometheus",
            "--storage.tsdb.retention.time=2y",
            "--web.console.libraries=/usr/share/prometheus/console_libraries",
            "--web.console.templates=/usr/share/prometheus/consoles",
            "--web.enable-lifecycle",
            "--web.external-url=http://hostname:9090"
        ],
```
**Environment**

* System information:

Linux 4.9.0-16-amd64 x86_64
* Prometheus version:

prometheus, version 2.31.1 (branch: HEAD, revision: 411021ada9ab41095923b8d2df9365b632fd40c3)
  build user:       root@9419c9c2d4e0
  build date:       20211105-20:35:02
  go version:       go1.17.3
  platform:         linux/amd64

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
