### DISCUSSION TITLE
Prometheus with Influx v2

### DISCUSSION THREAD

**Discussion by malvinpatrick** [prometheus/prometheus#10085] [Q&A]
There's any integration for prometheus storage read ? I've read in update release, the "write" replace by telegraf service. How about the "read" ? Can I use InfluxDB 2 like 1.8 

```
remote_write:
  - url: "http://localhost:8086/api/v1/prom/write?db=prometheus&u=username&p=password" -> replace using telegraf service

remote_read:
  - url: "http://localhost:8086/api/v1/prom/read?db=prometheus&u=username&p=password"` -> how about this ?
```
