### DISCUSSION TITLE
Prometheus WAL files are not deleted and its size is 261GB now

### DISCUSSION THREAD

**Discussion by praveen5kgit** [prometheus/prometheus#10272] [Q&A] [answered]
Prometheus WAL files are not deleted since the Prometheus setup was done. I am using Prometheus version 2.26.0 and I have gone through the same issue in forums. It has been mentioned that it was fixed in version 2.11 but for me, the WAL files are not deleting even though I use version 2.26.0. In the prometheus.yml file, I have not set --storage.tsdb.retention.time and --storage.tsdb.wal-compression parameters. Because of these huge WAL files, whenever I restart Prometheus, it takes more than 2 hours to load all the segments. Please help me to find out if I am missing anything or it is a bug. Currently, the size of the WAL folder is 261GB. I have verified this below expression in Prometheus URL 
(time() - prometheus_tsdb_lowest_timestamp_seconds) / 86400 

Output: 

{instance="xxx.xx.xx:9090", job="prometheus"}      15.376041666666667

*** Prometheus version:**

prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64

*** Prometheus configuration file:**
```
Below is my prometheus.yml file. I have removed targets for security reasons. We have 50 plus targets configured.

# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  query_log_file: /etc/prometheus/query.log
  # scrape_timeout is set to the global default (10s).


# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       -  xx.xxx.xx:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/applicationrules/*.yml
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: [' xx.xxx.xx:9090',' xx.xxx.xx:9115']

  - job_name: 'redis'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
  

  - job_name: 'rabbitmq'
    static_configs:
  

  - job_name: 'elasticsearch'
    static_configs:
   
  - job_name: 'postgresql'
    static_configs:
 

  - job_name: 'kafka'
    static_configs:
  
  - job_name: 'zookeeper'
    static_configs:
  

  - job_name: 'jboss'
    static_configs:
 

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: xx.xxx.xx:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackboxtcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  xx.xxx.xx:9115  # The blackbox exporter's real hostname:port.

```

**Comment by praveen5kgit** [comment]
<!--

Prometheus WAL files are not deleted since the Prometheus setup was done. I am using Prometheus version 2.26.0 and I have gone through the same issue in forums. It has been mentioned that it was fixed in version 2.11 but for me, the WAL files are not deleting even though I use version 2.26.0. In the prometheus.yml file, I have not set --storage.tsdb.retention.time and --storage.tsdb.wal-compression parameters. Because of these huge WAL files, whenever I restart Prometheus, it takes more than 2 hours to load all the segments. Please help me to find out if I am missing anything or it is a bug. Currently, the size of the WAL folder is 261GB. I have verified this below expression in Prometheus URL 
(time() - prometheus_tsdb_lowest_timestamp_seconds) / 86400 

Output: 

{instance="xxx.xx.xx:9090", job="prometheus"}      15.376041666666667


* Prometheus version:

prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64


* Prometheus configuration file:
```
Below is my prometheus.yml file. I have removed targets for security reasons. We have 50 plus targets configured.

# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  query_log_file: /etc/prometheus/query.log
  # scrape_timeout is set to the global default (10s).


# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       -  xx.xxx.xx:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/applicationrules/*.yml
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: [' xx.xxx.xx:9090',' xx.xxx.xx:9115']

  - job_name: 'redis'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
  

  - job_name: 'rabbitmq'
    static_configs:
  

  - job_name: 'elasticsearch'
    static_configs:
   
  - job_name: 'postgresql'
    static_configs:
 

  - job_name: 'kafka'
    static_configs:
  
  - job_name: 'zookeeper'
    static_configs:
  

  - job_name: 'jboss'
    static_configs:
 

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: xx.xxx.xx:9115  # The blackbox exporter's real hostname:port.

  - job_name: 'blackboxtcp'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement:  xx.xxx.xx:9115  # The blackbox exporter's real hostname:port.

```
