### DISCUSSION TITLE
docker configuration and autodiscovery

### DISCUSSION THREAD

**Discussion by luvarqpp** [prometheus/prometheus#10409] [Q&A]
Hi,
**Some background:**
I have small deployment (bunch of applications, some CI/CD and deployment applications running in same docker). There is spawning new application for each branch I have in deployment git. They are accessible through traefik proxy.

**What is my plan:**
I have found that monitoring with prometheus can make use of auto discovery ([merge request](https://github.com/prometheus/prometheus/pull/8629/files), [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#docker_sd_config)). I would like to make prometheus automatically discover all newly spawned containers and start monitoring them.

**My issue:**
According documentation:

> This SD discovers "containers" and will create a target for each network IP and port the container is configured to expose.

I have problem that it will make prometheus scrape much more than I would like to scrape. Possibly creating unnecessary errors in logs and so on.

**Question:**
Is it possible somehow to filter/target running containers?

**Proposal/idea:**
Make use of [traefik way](https://doc.traefik.io/traefik/providers/docker/#port-detection). Example docker-compose config part:
```
version 3.6

services:
  some_static_service:
    image: serviceImage:0.1.22
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.somestaticservicehttp.rule=Host(`sss.example.com`,`www.sss.example.com`)"
      - "traefik.http.routers.somestaticservicehttp.entrypoints=web"
  ci_cd_service:
    image: gitlabJenkins:42.1.22
    ports:
      - '80:80'
      - '22:22'
      - '9091:9091'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.somestaticservicehttp.rule=Host(`cicd.example.com`,`www.cicd.example.com`)"
      - "traefik.http.routers.somestaticservicehttp.entrypoints=web"
      - "prometheus.enable=true"
      - "prometheus.metricsurl=:9091/actuator/prometheus"
  prometheus_service:
    image: prom/prometheus:v2.33.4
    ports:
      - '9090:9090'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./local/:/etc/prometheus:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

I hope that example is self-explanatory. If not, please ask for clarification.
Prerequirements, local folder called `local` does contain prometheus.yml. Extra hosts are added due to [scraping docker](https://docs.docker.com/config/daemon/prometheus/#configure-docker) itself (note that they are listening on local interface, but when adding extra host using host-gateway, there will be docker interface. i.e. 172.17.0.1 for example).
