### DISCUSSION TITLE
Drop go metrics

### DISCUSSION THREAD

**Discussion by scorpey** [prometheus/prometheus#10716] [Q&A]
Hi community.

Pls help drop go.* metrics
In JOB i write

```
  relabel_configs:
    - source_labels: [__name__]
      regex: (go.*)
      action: drop
```

but i find go metrics.

Thank you
