### DISCUSSION TITLE
alertmanager with web route prefix

### DISCUSSION THREAD

**Discussion by gdsotirov** [prometheus/prometheus#10845] [Q&A]
I have alertmanager configured with:

```
--web.listen-address=127.0.0.1:9089 --web.route-prefix="/alertmanager/"
```

as it is running behind a reverse proxy. And Prometheus configured like this:

```yaml
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "127.0.0.1:9089"
```

Firing of alerts fails with the following message in the log:

```
2022-06-09 11:43:18.135508 ts=2022-06-09T11:43:18.135Z caller=notifier.go:526 level=error component=notifier alertmanager=http://127.0.0.1:9089/api/v2/alerts count=1 msg="Error sending alert" err="bad response status 404 Not Found"
```

Because the URL should be `http://127.0.0.1:9089/alertmanager/api/v2/alerts` actually, but unfortunately I do not see a way to setup this in Prometheus configuration.

Is there are way to instruct Prometheus to fire alerts at the correct URL?
