### DISCUSSION TITLE
Duplicate metrics from kubernetes-service-endpoints for kube-state-metrics & node-exporters

### DISCUSSION THREAD

**Discussion by tomsucho** [prometheus/prometheus#10899] [Q&A]
Hi!
I deployed the stack via Helm: prometheus-community/kube-prometheus-stack
And I got service monitors for kube-state-metrics as well as node-exporters. These are working fine and get all the metrics, however I noticed that the generic auto-discovery also finds those two and scrapes them in addition with just different set of labels, through job="kubernetes-service-endpoints". This is strange as in my Prometheys cfg got this defined to only scrape things that have this annotation set explicitly on them:
```
- job_name: kubernetes-service-endpoints
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
```
and none of the 2 mentioned services have it set.
Wonder what could be causing this extra scraping through kubernetes-service-endpoints.
Cheers!
