### DISCUSSION TITLE
Prometheus Rules with addtional info

### DISCUSSION THREAD

**Discussion by linkafsar** [prometheus/prometheus#10941] [Q&A]
Hello,

Can you please let me know like if i configured the alerts via node exporter rules in prometheus that if my node is exceeded above 80 % i got an alert in % , but is it possible that if i also got additional info of node in same alert like Total RAM , Used RAM and Free RAM in MB or GB via alerts or rules or description annotations

**Comment by linkafsar** [comment]
alertname = NodeMemoryUsage
container = node-exporter
endpoint = metrics
instance = node1
job = node-exporter
severity = warning
Annotations
description = "Node memory VALUE = 69.49

for ex: 
if i want more values in description like that Total RAM: GB, Used RAM: , Free RAM: 
any suggestion helpful

**Comment by LeviHarrison** [comment]
You can use the [query](https://prometheus.io/docs/prometheus/latest/configuration/template_reference/#queries) function to include values of additional metrics like this:

```yml
groups:
  - name: test
    rules:
      - alert: test
        expr: up == 1
        for: 1s
        annotations:
          summary: '{{ $labels.instance }} {{ with query "prometheus_tsdb_blocks_loaded{instance=\"localhost:9090\", job=\"prometheus\"}" }}{{ . | first | value | humanize }}{{ end }}'
```

You can find more examples here: https://prometheus.io/docs/prometheus/latest/configuration/template_examples/
