### DISCUSSION TITLE
`scrape_config` can use "prefix set" inclusion/exclusion instead of regex

### DISCUSSION THREAD

**Discussion by Freyert** [prometheus/prometheus#10955] [Q&A]
## Proposal
**Use case. Why is this important?**
When I onboard a new prometheus exporter into a system, my team mates and I review the exposed metrics to determine which are valuable to retain and which should be dropped.

Prometheus metric names are usually prefixed with a "subsystem" that the metric belongs to. I find that during the metric selection process I usually select 2-3 metrics from each subsystem. The disparate subsystems with varying numbers of child metrics makes efficient regular expressions very difficult in my experience and I assume that most users in my situation concatenate all the metric names into a single regex using `|`. I expect this concatenated "monster regex" to be both time and space inefficient.

In my own experience the Go regex engine compiles `|` patterns into a loop over each pattern. So if we have to evaluate that loop over `N` metric names and there are `M` `|` patterns then the algorithm is `O(M*N)` to see if we should keep or drop a metric. There would also be I expect `O(M)` memory used to hold each of the patterns to match.

Set inclusion would require upfront time to compile the set data structure but should have be much more efficient per comparison.

Let's look at an example scrape config from [`Prometheus Trainings`](https://training.promlabs.com/training/relabeling/writing-relabeling-rules/keeping-and-dropping-objects)

```yaml
action: keep
source_labels: [__name__]
regex: '(api_|http_).*'
```

Regex works excellently because we want to keep all the metrics of these two subsystems, and drop the rest. What if there are many subsystems of `http` and you only want to select a handful of metrics?

```yaml
action: keep
source_labels: [__name__]
regex: '(api_|http_(headers_|(body_(bytes)).*' #not even sure this is a valid regex, but this is just for demonstration.
```

A more ergonomic (maybe) and performant (maybe) solution would be to use "prefix set inclusion" via a trie. 

```yaml
action: keep
source_labels: [__name__]
label_prefixes:
- api_*
- http_headers_*
- http_body_bytes_*
```

My actual case is even more extreme as I have about 15 different subsystems each containing one or two metrics that I want to keep. In my situation I would prefer just to explicitly list all the metrics I would like to keep and have prometheus compile it into an efficient prefix matching structure.

In my mind the situation here is similar to pattern matching URLs in a web framework or load balancer. Prefix matching is preferred due to efficiencies, but regex is great to have for captures and complex patterns.
