### DISCUSSION TITLE
Remote_write filtering based on metric values

### DISCUSSION THREAD

**Discussion by JWilson45** [prometheus/prometheus#10994] [Q&A]
I'm in the process of setting up a remote write stream to Kafka, but only want very specific data to be sent through. Ive been able to get most of the way there by filtering and dropping data that doesn't match my desired label but I want to go a step further.

My current config:
```
write_relabel_configs:
     - regex: 'probe_success'
       action: keep
       source_labels: [__name__]
```

I only want to send data to Kafka that is within a specific range. For example, probe_success from Prometheus blackbox exporter has a value that is either 0 or 1 to represent a probe passing or failing.

Is there a way to filter out all data that is passing where "value": "1" and only send data that is failing where "value": "0".

I'm not sure how to accomplish this as these values are not labels.
