### DISCUSSION TITLE
LabelKeep and LabelDrop Acting Based on Label Name rather than Label Value

### DISCUSSION THREAD

**Discussion by edwardcrupi** [prometheus/prometheus#10998] [Q&A]
### What did you do?

I tried to send metrics filtered by label using labelkeep or labeldrop

### What did you expect to see?

I expected to see my metrics filtered based on label value

### What did you see instead? Under which circumstances?

When using labelkeep nothing was being sent and when using labeldrop nothing was being dropped

### System information

Darwin arm64

### Prometheus version

```text
prometheus, version 2.37.0-rc.0 (branch: main, revision: 44fcf876caad9a5d28b92a728d2c98c34015d377)
  build user:       crupie@XK7G97TX5D
  build date:       20220708-03:18:53
  go version:       go1.18.1
  platform:         darwin/arm64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 2s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:

remote_write:
- url: my_target_remote_server
  write_relabel_configs:
    - regex: 'metrica_*|metricb.*'
      action: labelkeep
    - source_labels: [envType]
      regex: ‘SANDBOX’
      action: labelkeep
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'anz_go_job'
    metrics_path: 'ping_frenzy'
    static_configs:
    - targets: ["localhost:8000"]
```

### Remedy

We can fix this by referring to l.Value rather than l.Name in https://github.com/prometheus/prometheus/blob/44fcf876caad9a5d28b92a728d2c98c34015d377/model/relabel/relabel.go#L256 and https://github.com/prometheus/prometheus/blob/44fcf876caad9a5d28b92a728d2c98c34015d377/model/relabel/relabel.go#L262

**Comment by roidelapluie** [comment]
This works as documented:
> labelkeep: Match regex against all label **names**. Any label that does not match will be removed from the set of labels.


 Please try:

```
  write_relabel_configs:
    - source_labels: [__name__]
      regex: 'metrica_*|metricb.*'
      action: keep
    - source_labels: [envType]
      regex: ‘SANDBOX’
      action: keep
```
