### DISCUSSION TITLE
Relabeling: Using a labelname in a regex (to use the labelname's value)

### DISCUSSION THREAD

**Discussion by thernstig** [prometheus/prometheus#11481] [Ideas]
In relabeling config, let's say I have saved a value in a label like `__tmp_port`. I then want to match some port in Kubernetes service discovery 

```yaml
  relabel_configs:
    - source_labels: [ __meta_kubernetes_pod_container_port_number ]
      action: keep
      regex: ${__tmp_port}
```

If the value of `__meta_kubernetes_pod_container_port_number` and `__tmp_port` are both `8080`, it will keep this target. It could possibly be used in `replacement` as well.

Is this already possible somehow? Or would this be a good feature? It solves e.g. https://github.com/prometheus/prometheus/issues/3756
