### DISCUSSION TITLE
Why labels used by alertmanager don't accept UTF-8 encoded string?

### DISCUSSION THREAD

**Discussion by bo-er** [prometheus/prometheus#11684] [Q&A]
```
groups:
- name: example
  rules:

  # Alert for any instance that is unreachable for >5 minutes.
  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
     "级别": "严重"
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
```
Will there be any consequence if we allow a UTF-8 encoded string?
