### DISCUSSION TITLE
Prometheus remote write desired shards calculation wants to run more than configured max shards.

### DISCUSSION THREAD

**Discussion by kwenzh** [prometheus/prometheus#11773] [General]
prometheus alert: Prometheus remote write desired shards calculation wants to run more than configured max shards.

and restart prometheus , i can be recovery

max_over_time(prometheus_remote_storage_shards_desired{job="prometheus-k8s",namespace="monitoring"}[5m])
![image](https://user-images.githubusercontent.com/38367518/209491180-6f7c2a05-b5fc-4b02-9b07-59ea843b2abf.png)

remote config
```
remote_write:
- url: http://xxxxx.mimir.svc:80/api/v1/push
  remote_timeout: 30s
  follow_redirects: true
  queue_config:
    capacity: 5000
    max_shards: 500
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
  metadata_config:
    send: true
    send_interval: 1m
```
