### DISCUSSION TITLE
rate(go_memstats_alloc_bytes_total) result weird

### DISCUSSION THREAD

**Discussion by uoryon** [prometheus/prometheus#11886] [Q&A]
### What did you do?

I started a example prom-http program like this.

```
package main

import (
        "net/http"

        "github.com/prometheus/client_golang/prometheus/promhttp"
)

func main() {
        http.Handle("/debug/metrics", promhttp.Handler())
        http.ListenAndServe(":8888", nil)
}

```

Start a prometheus docker image to collect data, Use grafana to present the data.
The graph is weird.

![image](https://user-images.githubusercontent.com/1448098/197767295-ccb77ab5-7c4c-4aac-b31c-b5f5b259f8f8.png)

### What did you expect to see?

I think the data in the graph should a line, not like these, some pulses in it, and the pulse more higher.

### What did you see instead? Under which circumstances?

![image](https://user-images.githubusercontent.com/1448098/197767856-64e2c9b8-8774-4b52-a817-cdb819b4d12e.png)

### System information

Linux 4.14.81.bm.15-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'gateway'

    scrape_interval: 5s
    metrics_path: /debug/metrics

    static_configs:
      - targets: ['localhost:8888']
```
