### DISCUSSION TITLE
Prometheus报错：Out of order sample from remote write

### DISCUSSION THREAD

**Discussion by liufangpeng** [prometheus/prometheus#12064] [Q&A]
### What did you do?

```
  prometheus:
    image: prom/prometheus-test5:latest
    container_name: prometheus
    hostname: prometheus
    restart: always
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9090:9090"
    networks:
      - nightingale
    command:
      - "--enable-feature=remote-write-receiver"
      - "--query.lookback-delta=2m"
      - "--storage.tsdb.wal-compression"
      - "--log.level=debug"
```

### What did you expect to see?

。

### What did you see instead? Under which circumstances?

刚刚部署好Prometheus并无错误日志输出，运行一段时间之后突然容器日志里大批量的会刷这些日志，并且Prometheus里查询不到数据无法正常使用
```
ts=2023-03-02T10:46:58.404Z caller=write_handler.go:109 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"disk_inodes_used\", device=\"JuiceFS:juice\", fstype=\"fuse.juicefs\", ident=\"10.79.10.12\", mode=\"rw\", path=\"/var/lib/kubelet/pods/e3409740-980e-4389-aea8-503c2b8c17db/volumes/kubernetes.io~csi/pvc-1bd206e9-65e0-4e50-853b-4ca4d6c0abcb/mount\", product=\"devops-tool\", vpc=\"public\"}" timestamp=1677754012257
ts=2023-03-02T12:00:50.558Z caller=write_handler.go:109 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"disk_inodes_used\", device=\"JuiceFS:juice\", fstype=\"fuse.juicefs\", ident=\"10.79.10.12\", mode=\"rw\", path=\"/var/lib/kubelet/pods/9875042f-5b64-4604-bfbf-19a384ce7611/volumes/kubernetes.io~csi/pvc-100430c4-605b-4e45-b72e-f332919f81ff/mount\", product=\"devops-tool\", vpc=\"public\"}" timestamp=1677758443489
ts=2023-03-02T12:23:37.274Z caller=write_handler.go:109 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"disk_used\", device=\"JuiceFS:juice\", fstype=\"fuse.juicefs\", ident=\"10.79.10.12\", mode=\"rw\", path=\"/var/lib/kubelet/pods/9875042f-5b64-4604-bfbf-19a384ce7611/volumes/kubernetes.io~csi/pvc-100430c4-605b-4e45-b72e-f332919f81ff/mount\", product=\"devops-tool\", vpc=\"public\"}" timestamp=1677759810439
ts=2023-03-02T12:35:15.388Z caller=compact.go:519 level=info component=tsdb msg="write block" mint=1677749748962 maxt=1677751200000 ulid=01GTH536JJ37JVREHMQN5NK4J1 duration=13.034656377s
ts=2023-03-02T12:35:16.225Z caller=head.go:1219 level=info component=tsdb msg="Head GC completed" caller=truncateMemory duration=832.192859ms
ts=2023-03-02T12:35:16.225Z caller=checkpoint.go:100 level=info component=tsdb msg="Creating checkpoint" from_segment=0 to_segment=18 mint=1677751200000
ts=2023-03-02T12:35:47.832Z caller=head.go:1191 level=info component=tsdb msg="WAL checkpoint complete" first=0 last=18 duration=31.606785111s
ts=2023-03-02T12:59:36.405Z caller=compact.go:519 level=info component=tsdb msg="write block" mint=1677751200000 maxt=1677758400000 ulid=01GTH6FDZDDTERS40WB1J8ABBE duration=24.679446612s
ts=2023-03-02T12:59:37.031Z caller=head_read.go:131 level=debug component=tsdb msg="Looked up series not found"
ts=2023-03-02T12:59:37.031Z caller=head_read.go:131 level=debug component=tsdb msg="Looked up series not found"
ts=2023-03-02T12:59:37.031Z caller=head_read.go:131 level=debug component=tsdb msg="Looked up series not found"
ts=2023-03-02T12:59:37.031Z caller=head_read.go:131 level=debug component=tsdb msg="Looked up series not found"
```

### System information

Linux 3.10.0-1160.15.2.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'n9e'
    file_sd_configs:
    - files:
      - targets.json

  - job_name: 'idm-mq'
```

### Alertmanager version

```text
。
```

### Alertmanager configuration file

```yaml
。
```

### Logs

```text
。
```
