### DISCUSSION TITLE
"unsupported value type" on timestamp

### DISCUSSION THREAD

**Discussion by HacktopusX** [prometheus/prometheus#12061] [Q&A]
### What did you do?

I want to populate timestamp in the alerts
I used .StartsAt but it gives error

### What did you expect to see?

timestamp: "2022/08/12:16:42:13Z34444"

### Prometheus configuration file

```yaml
alerts.yml <<EOF
groups:
  - name: alerts
    rules:
    - alert: HostUnusualDiskReadRate
       expr: sum by (hostname) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk read rate 
      description: "Disk is probably reading too much data (> 100 MB/s)"
      Hostname: "{{ $labels.hostname }}"
      value: "{{ $value }}"
      timestamp: "{{ .startsAt }}"
```

I also used ```.StartsAt``` . same result

### Logs

 ts=2023-01-09T20:56:02.893Z caller=alerting.go:359 level=warn component="rule manager" alert="unsupported value type" msg="Expanding alert template failed" err="error executing template __alert_ContainerMemoryUsage: template: __alert_ContainerMemoryUsage:1:115: executing \"__alert_ContainerMemoryUsage\" at <.startsAt>: can't evaluate field startsAt in type struct { Labels map[string]string; ExternalLabels map[string]string; ExternalURL string; Value float64 }" data="unsupported value type"
