### DISCUSSION TITLE
Recording rules do not work anymore

### DISCUSSION THREAD

**Discussion by runningman84** [prometheus/prometheus#12075] [Q&A]
### What did you do?

We have rules like these:
`````
        - record: kube_pod_container_resource_requests_memory_bytes_recommendation_critical
          expr: round((2 * avg(quantile_over_time(.99,container_memory_working_set_bytes{container!="POD",container!=""}[3d])) by (container,pod,namespace)))
        - record: kube_pod_container_resource_requests_memory_bytes_recommendation_prod
          expr: round((1.5 * avg(quantile_over_time(.99,container_memory_working_set_bytes{container!="POD",container!=""}[3d])) by (container,pod,namespace)))
        - record: kube_pod_container_resource_requests_memory_bytes_recommendation_dev
          expr: round((1 * avg(quantile_over_time(.95,container_memory_working_set_bytes{container!="POD",container!=""}[3d])) by (container,pod,namespace)))
        - record: kube_pod_container_resource_limits_memory_bytes_recommendation_critical
          expr: 2 * kube_pod_container_resource_requests_memory_bytes_recommendation_critical
        - record: kube_pod_container_resource_limits_memory_bytes_recommendation_prod
          expr: 2 * kube_pod_container_resource_requests_memory_bytes_recommendation_prod
        - record: kube_pod_container_resource_limits_memory_bytes_recommendation_dev
          expr: 1.5 * kube_pod_container_resource_requests_memory_bytes_recommendation_dev
        - record: container_cpu_usage_irate
          expr: avg( irate(container_cpu_usage_seconds_total{container!="POD", container!=""}[5m]) ) by (container,pod,namespace)
        - record: kube_pod_container_resource_requests_cpu_cores_recommendation_critical
          expr: 1.5 * quantile_over_time(.99,container_cpu_usage_irate[3d])
        - record: kube_pod_container_resource_requests_cpu_cores_recommendation_prod
          expr: 1.5 * quantile_over_time(.99,container_cpu_usage_irate[3d])
        - record: kube_pod_container_resource_requests_cpu_cores_recommendation_dev
          expr: 1 * quantile_over_time(.95,container_cpu_usage_irate[3d])
`````
After some prometheus update they stopped working.

All expressions itself seem to work fine. 

Prometheus is configured using prometheus operator.

### What did you see instead? Under which circumstances?

There are no results for any of the recorded queries. 

### System information

does not matter

### Prometheus version

```text
2.39.1
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: monitoring/prometheus-operator-kube-p-prometheus
    prometheus_replica: prometheus-prometheus-operator-kube-p-prometheus-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: central-alertmanager-endpoint-proxy
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - monitoring
rule_files:
- /etc/prometheus/rules/prometheus-prometheus-operator-kube-p-prometheus-rulefiles-0/*.yaml
```

### Alertmanager version

```text
na
```

### Alertmanager configuration file

```yaml
na
```

### Logs

```text
na
```
