### DISCUSSION TITLE
Regex in alerting rule

### DISCUSSION THREAD

**Discussion by zbhavyai** [prometheus/prometheus#12419] [Q&A]
Hi,

Is it possible to use regex in **expr** in the prometheus alerting rule? For example, my metric name is `m_<SOMEID>_system_load`, where `SOMEID` is different for every deployment.

So, what should my `alerting_rules.yml` look like? The one which I have prints error in prometheus logs.

```
groups:
  - name: system_load_alerts
    rules:
      - alert: SystemLoad2
        expr: m_[A-Za-z0-9]+_system_load == 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'Load is 2'
          description: 'The metric indicates high capacity (value = 2) on the server.'
      - alert: SystemLoad3
        expr: m_[A-Za-z0-9]+_system_load == 3
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: 'Load is 3'
          description: 'The metric indicates high capacity (value = 3) on the server.'
```

Thank you in advance!

**Prometheus version** = `2.41.0`
**OS** = `PopOS`
