### DISCUSSION TITLE
Prometheus scraping over VPN

### DISCUSSION THREAD

**Discussion by maximinogomez** [prometheus/prometheus#12445] [General]
Hello,

I have Prometheus running on my local box(Mac OS) which is connected to my company VPN. In the prometheus.yml configuration we have defined service running inside our VPN. 
```
scrape_configs:
  - job_name: 'nash'
    metrics_path: '/metrics'
    params:
      api_key: ['d03efKfls25PwA']
    scrape_interval: 15s
    static_configs:
    - targets: ['abcops01:5200']
```
When we look into the Prometheus targets via Web client, we see the following error for this service.

`Get "http://abcops01:5200/metrics?api_key=d03efKfls25PwA": dial tcp: lookup abcops01 on [2001:558:feed::1]:53: no such host`

I am assuming this is because of the VPN. Should this work over the VPN or is this not possible. Thanks.
