### DISCUSSION TITLE
etc/prometheus/prometheus.yml: operation not permitted

### DISCUSSION THREAD

**Discussion by SarpongAbasimi** [prometheus/prometheus#12492] [Q&A]
### What did you do?

When starting up the prometheus container locally, I get the following error.

```text
ts=2023-06-23T19:18:52.158Z caller=main.go:
450 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" 
file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: operation not permitted"
```

This issues seems to have been going on for a while as seen here
https://github.com/prometheus/prometheus/issues/5976

Has a solution been for for the error?

This is the image being used

```
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
```

I have also tried this 

```
  prometheus:
    image: prom/prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
```

But I get the same error.

Expected Behaviour
Prometheus should start up without any hickups

Current Behaviour
Prometheus never starts up.

Possible Solution
Update the Dockerfile and take necessary steps to eliminate the permission denied issue.

### What did you expect to see?

A working prometheus container.

### What did you see instead? Under which circumstances?

```text
ts=2023-06-23T19:18:52.158Z caller=main.go:
450 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" 
file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: operation not permitted"
```

Current Behaviour
Prometheus never starts up.

### Prometheus version

```text
latest
```

### Logs

```text
ts=2023-06-23T19:18:52.158Z caller=main.go:
450 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" 
file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: operation not permitted"
```
