### DISCUSSION TITLE
Keep only certain metrics with remote_write

### DISCUSSION THREAD

**Discussion by ginkel** [prometheus/prometheus#13321] [Q&A]
Hi there,

I'd like to export a certain subset of my metrics from Prometheus to Grafana Mimir using Prometheus' `remote_write` feature. So far so good. Config looks like this:

```
remote_write:
- name: mimir
  url: "https://<mimir_fqdn>/api/v1/push"
  write_relabel_configs:
      - source_labels: ["__name__"]
        regex: ^(t_delay)$
        action: keep
  headers:
    X-Scope-OrgID: tenant
```

Unfortunately, no metrics show up in Mimir (but another remote write destination with different [drop] filtering works). Is the configuration I use to only keep metrics named `t_delay` correct?

Thanks,
Thilo
