### DISCUSSION TITLE
Environment variable as scrape target

### DISCUSSION THREAD

**Discussion by Depechie** [prometheus/prometheus#13381] [Q&A]
My current prometheus config looks like this

```
scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://host.docker.internal:5251/health
```

Now that we are able to use environment variables in the global section as external labels we can add something like

```
global:
  external_labels:
    service_url: ${SERVICE_URL}
```

This works, but can I also use that external label as variable for the `-targets` section in the `static_configs`?
