### DISCUSSION TITLE
Best practice for setting password for Prometheus and Node exporter?

### DISCUSSION THREAD

**Discussion by arijitdeltax** [prometheus/prometheus#13528] [Q&A]
As environment variables are disabled in Prometheus and Node Exporter containers, I am using the following method to set the password in the `web.yml` file:
```yaml
basic_auth_users:
    admin: $2b$12$hMf2lSsxfm0.i4a.1kVpSOVyBCfIB51VRjgBUyv7kdnyTlgWj81Ay
```

And to access the Node Exporter from Prometheus, I am using the following method to set the password in `prometheus.yml` file:
```yaml
scrape_configs:
  - job_name: "node-exporter"
    scheme: https
    basic_auth:
      username: admin
      password: <plain text password>
```

I will _have_ to commit both `web.yml` and `prometheus.yml` file to our code base.
1. I can commit `web.yml` file as the the password is hashed with bcrypt. (Good Luck to anyone who wants to Bruteforce it)
2. I **cannot** commit  `prometheus.yml` as it contains the password for my Node Exporters in _Plaintext_ !

Is there:
1. a way to _not_ put plaintext password to access the node exporters?
2. a better security practice overall?

I am deploying using docker compose.

Thank You :)
