### DISCUSSION TITLE
Missing data point of metrics which aggregated by recording rule

### DISCUSSION THREAD

**Discussion by LoremipsumSharp** [prometheus/prometheus#13605] [Q&A]
Environment Info:
![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/20240219194511.png)

I am trying to use recording rule to aggregate metric for improving the query performance, my rule configuration as follow:
```yaml
groups:
- name: qps_rules
  interval: 1m
  rules:
  - record: job:server_latency_milliseconds_count:rate3m
    expr: sum by(server_method,server_url_patterns,app_name) (rate(server_latency_milliseconds_count{env=~"env1|env2|env3"}[3m]))
```

>  the above group has above 8 rules,i just skip some other rule to keep simple

From the Prometheus UI, the groups take about 25s seconds each time to evaluate:

![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/20240219181507.png)

However, the chart of time series shows that there are some data points missing:

![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/20240219195236.png)

While if I use the back PromQL of recording rule to query, everything works fine:

![](https://raw.githubusercontent.com/LoremipsumSharp/Images/master/20240219195157.png)

I wonder if I miss something when define the recording rule or there is any misconfiguration I should check
