### DISCUSSION TITLE
The results calculated by irate are different.

### DISCUSSION THREAD

**Discussion by Mr-Lee-long** [prometheus/prometheus#13998] [Q&A]
### What did you do?

this is my expression: irate(node_cpu_seconds_total{cpu="0", env="product", instance="10.43.2.64", job="product_node-exporter", meta_consul_service_port="9100", mode="iowait", tags="kubernetes-nodes"}[1m])

i clicked the  execute button in the 30s, and i got three different trend results.
and  i only have one single data，no copy, no slave or multiple masters.

### What did you expect to see?

I think the result should be the same every time, or much the same。

### What did you see instead? Under which circumstances?

1、Most of the time like this.

<img width="1440" alt="WeChatWorkScreenshot_19b757ea-f243-4cb3-9f66-01ccaf6ae146" src="https://github.com/prometheus/prometheus/assets/33474337/57aa77b7-4bf9-4840-aec4-ed86bd16e8dc">

2、sometime like this.
<img width="1440" alt="WeChatWorkScreenshot_bacd4415-e4aa-4de2-9f5c-eb1b14021747" src="https://github.com/prometheus/prometheus/assets/33474337/e34288cb-b9c8-4aa3-9bd5-06429cae8e62">

3、and like this.
<img width="1440" alt="WeChatWorkScreenshot_6da18e3f-f74f-4889-ac4c-45a8e1ce4777" src="https://github.com/prometheus/prometheus/assets/33474337/5824552f-c14d-4f88-8b93-6b91e29dd1a8">

### System information

centos7.8  3.10.0-1160.99.1.el7.x86_64

### Prometheus version

```text
2.51.1
```

### Prometheus configuration file

```yaml
- job_name: '{{ ENV }}_node-exporter'
      scrape_interval: 30s
      honor_labels: true
      consul_sd_configs:
        - server: 'http://consul-svc.monitor.svc.cluster.local:8500'
          services: ["{{ ENV }}_node-exporter"]
      relabel_configs:
            - source_labels: [__meta_consul_tags]  #p05,kubenets_nodes
              separator: ;
              regex: \,(.*?)\,(.*)\,
              target_label: tags
              replacement: ${2}
              action: replace
            - source_labels: [__meta_consul_tagged_address]
              separator: ;
              regex: (.*)
              target_label: meta_consul_tagged_address
              replacement: ${1}
              action: replace
            - source_labels: [__meta_consul_metadata]
              separator: ;
              regex: (.*)
              target_label: meta_consul_metadata
              replacement: ${1}
              action: replace
            - source_labels: [__meta_consul_service_address]
              target_label: instance
            - source_labels: [instance]
              separator: ;
              regex: (xxx)
              action: drop
            - source_labels: [__meta_consul_service_metadata]
              separator: ;
              regex: (.*)
              target_label: meta_consul_service_metadata
              replacement: ${1}
              action: replace
            - source_labels: [__meta_consul_service_port]
              separator: ;
              regex: (.*)
              target_label: meta_consul_service_port
              replacement: ${1}
              action: replace
            - source_labels: [__meta_consul_service]
              separator: ;
              regex: (.+)-(.+)
              target_label: env
              replacement: ${1}
              action: replace
            - source_labels: [__meta_consul_service]
              separator: ;
              regex: (.+)_(.+)
              target_label: env
              replacement: ${1}
              action: replace
```
