### DISCUSSION TITLE
Directory name Error "Prmetheus" instead of Prometheus in Docker Image

### DISCUSSION THREAD

**Discussion by espyerx-x** [prometheus/prometheus#14123] [Q&A]
### What did you do?

**Command i run :**
_sudo docker run -p 9090:9090 -v promethus.yml:/etc/prometheus/prometheus.yml prom/prometheus_

### What did you expect to see?

Expected Result Was Docker Container must run upon executing this command:
_sudo docker run -p 9090:9090 -v promethus.yml:/etc/prometheus/prometheus.yml prom/prometheus_

### What did you see instead? Under which circumstances?

![image](https://github.com/prometheus/prometheus/assets/82972589/cefbecc4-e945-4b92-b08d-12efff9821b6)
**changed the Directory to prmethus and got it running**
Upon Investigating the issue found that in the latest **Docker image**  their are two promethus directories.
![image](https://github.com/prometheus/prometheus/assets/82972589/08a7c711-e504-4e22-bd81-90ae49fefeb6)
**Command i run :**
_sudo docker run -p 9090:9090 -v promethus.yml:/etc/prometheus/prometheus.yml prom/prometheus_

### Prometheus version

```text
prom/prometheus:latest
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: node_exporter
    static_configs:
      - targets: ['192.168.87.102:9100']
```
