### DISCUSSION TITLE
I need to see the logs to see the error of mikrotik snmp

### DISCUSSION THREAD

**Discussion by RandelMB** [prometheus/prometheus#14400] [General]
**This is the Original error that I want to identify with the logs**

![image](https://github.com/prometheus/prometheus/assets/120218426/eda0559b-1df0-40fd-b23f-59fd6499cdde)

I understand that to enable the logs I have to add this line **--log.level=debug** to the file **"prometheus.service"**

-----------------------------------prometheus.service---------------------------------------                                                                       
```
[Unit]
Description=Prometheus
Documentation=https://prometheus.io/docs/introduction/overview/
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
--config.file=/etc/prometheus/prometheus.yml \
--storage.tsdb.path=/var/lib/prometheus/ \
--web.console.templates=/etc/prometheus/consoles \
--web.console.libraries=/etc/prometheus/console_libraries
--log.level=debug

[Install]
WantedBy=multi-user.target
```
-------------------------------------------------------------------

I was also instructed to add the query_log_file in **"prometheus.yml"**
I use one and the other but the server crashes so I have commented with #
```
#  query_log_file: query.log
#  query_log_file: /etc/prometheus/query.log
```

----------------**"prometheus.yml"**------------------------------------------------------------
```

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
#  query_log_file: query.log
#  query_log_file: /etc/prometheus/query.log
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'Mikrotik-Snmp'
    static_configs:
      - targets:
        - 192.168.2.1  # Mikr1.
        - 172.16.0.1 # Mkr2.
    metrics_path: /snmp
    params:
#      auth: [public_v2]
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.
  # Global exporter-level metrics
  - job_name: 'snmp_exporter'
    static_configs:
      - targets: ['localhost:9116']
```
------------------------------------------------------------------------
