### DISCUSSION TITLE
promtool shows unexpected success

### DISCUSSION THREAD

**Discussion by H777K** [prometheus/prometheus#14508] [Q&A]
Hi,

i have created an alert rule with corresponding unit test. If I test the rule, promtool returns `success`, but i would not expect this, because the condition is not true for 15m.

If I have understood the documentation correctly, I would expect the following behavior:

- the value `1x4` is equal to `1 1 1 1 1`
- the value `_x5` is equal to `_ _ _ _ _`
- the evaluation_time always starts at minute `0`, so if i set this to `30m`, i need to have 31 values. Therefore the combination of `evaluation_time` and `for` will cause that the time period `30m-15m` is used to evaluate the rule?

Does anyone have an idea what i am doing wrong?

thanks :)

**flux-rules.yaml:**
```yaml
groups:
  - name: flux
    rules:
      - alert: FluxResourcesNotReady
        expr: |
          sum by (customresource_kind, name, exported_namespace) (gotk_resource_info{exported_namespace=~"flux-system", exported_ready="False"})
        for: 15m
        labels:
          group: flux
          severity: warning
        annotations:
          summary: "Flux - {{ $labels.customresource_kind }}/{{ $labels.name }} is not 100% ready for the last 10 minutes"
          description: "Run `kubectl -n {{ $labels.exported_namespace }} describe {{ $labels.customresource_kind }}/{{ $labels.name }}` to find out more."
```

**flux-rules-test.yaml:**

```yaml
rule_files:
  - flux-rules.yaml

evaluation_interval: 1m

tests:
  - interval: 1m
    input_series:
      - series: 'gotk_resource_info{exported_namespace="flux-system",exported_ready="True",customresource_kind="HelmRelease",name="myapp"}'
        values: "1x4 _x5 1x4 _x5 1x4 _x5 1"
      - series: 'gotk_resource_info{exported_namespace="flux-system",exported_ready="False",customresource_kind="HelmRelease",name="myapp"}'
        values: "_x5 1x4 _x5 1x4 _x5 1x4 0"
    alert_rule_test:
      - eval_time: "30m"
        alertname: FluxResourcesNotReady
        exp_alerts:
          - exp_labels:
              group: flux
              severity: warning
              customresource_kind: HelmRelease
              name: myapp
              exported_namespace: flux-system
            exp_annotations:
              description: Run `kubectl -n flux-system describe HelmRelease/myapp` to find out more.
              summary: Flux - HelmRelease/myapp is not 100% ready for the last 10 minutes
```
