### DISCUSSION TITLE
Use of plain text remote write username and password in prometheus yaml file

### DISCUSSION THREAD

**Discussion by Brij-code1** [prometheus/prometheus#14615] [Q&A]
### What did you do?

there is no option to hide the remote write useranem and password in prometheus yaml file

### What did you expect to see?

Option must be provided to hide the sensitive content in configuration file. 

### What did you see instead? Under which circumstances?

whole password character is visible to end user and every user. 

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 60s #Default is every 1 minute.
  evaluation_interval: 60s #The default is every 1 minute.
  scrape_timeout: 45s

  external_labels:
    cluster: prom-poc
    __replica__: prom_ha
remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: ???????????????????????
      password: ???????????????????????
```

### Alertmanager configuration file

```yaml
NA
```

### Logs

```text
NA
```
