### DISCUSSION TITLE
Global relabel_configs?

### DISCUSSION THREAD

**Discussion by samene** [prometheus/prometheus#14670] [Q&A]
**Use case:** 

I am using grafana mimir to analyze which metrics and series are not used in any dashboards. Surprisingly it gave me a huge list of metrics which are not used in any dashboards. So I would like to drop these metrics in prometheus itself using relabel_configs.

Now, i don't know which metric is coming from which job. Is it possible to configure prometheus in a way that it will drop these metrics from any scrape_config job. i.e like a global relabel_config?

For example:

```
metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'metric1|metric2|metric3'
    action: drop
```

I tried additionalScrapeConfig but it does not work since I need to specify some target or service discovery.

Is this possible? Any other way?
