### DISCUSSION TITLE
I'm using `static_configs` to add `labels` to `targets`, but not all data points are labelled correctly?

### DISCUSSION THREAD

**Discussion by erikschul** [prometheus/prometheus#15121] [Q&A] [answered]
This is my config:
```

scrape_configs:
  - job_name: nodes
    static_configs:
      - targets: ["10.123.0.10:9100"]
        labels:
          hostname: cp0
          node_type: cp
      - targets: ["10.123.0.20:9100"]
        labels:
          hostname: w0
          node_type: worker
```

In Grafana, when filtering on hostname

I get correct data historically:
<img width="283" alt="image" src="https://github.com/user-attachments/assets/fb812890-711a-475a-ad0b-4f6955de50c7">

but the most recent datapoint is labelled differently somehow:
<img width="208" alt="image" src="https://github.com/user-attachments/assets/cf2be1b1-a62d-4678-b850-517eea0ecbe3">

What am I doing wrong?
Or is this a bug in Prometheus or Grafana?
