### DISCUSSION TITLE
Remote Write Keep Multiple Source Label

### DISCUSSION THREAD

**Discussion by emreoztoprak** [prometheus/prometheus#15535] [Q&A]
Hi, I'm trying to send metrics from one Prometheus server to another. What I want to do, keep metrics from certain pods. Some metrics has pod_name label, some has pod label.

```yaml
write_relabel_configs:
- action: keep
  source_labels: [pod_name]
  regex: "foo.*"
- action: keep
  source_labels: [pod]
  regex: "foo.*"`
```

I tried this configuration but it only sends metric with pod_name labels not metrics with pod label. I also tried this but result is same.

```yaml
write_relabel_configs:
- action: keep
  source_labels: [pod_name, pod]
  regex: "foo.*"
```

Does anyone has any idea how to achieve this? TIA

**Comment by bwplotka** [comment]
:wave: Check e.g. this Grafana blog post that explains [`separator`](https://grafana.com/blog/2022/03/21/how-relabeling-in-prometheus-works/#:~:text=usually%20be%20shorter.-,source_labels%20and%20separator,-Let%E2%80%99s%20start%20off). You are probably looking for sth like

```yaml
write_relabel_configs:
- action: keep
  source_labels: [pod_name, pod]
  regex: "(;foo.*|foo.*;)"
```

Hope that helps (we can reopen if not), thanks! 🤗
