### DISCUSSION TITLE
Adding Scraper config: not a valid hostname error

### DISCUSSION THREAD

**Discussion by berkayalan** [prometheus/prometheus#15546] [Q&A]
Hi,

I want to add a scraper to my prometheus yaml files. This is coming from our uptime-kuma page. My configs are like here:

```
  - job_name: 'uptime'
    scrape_interval: 30s
    scheme: https
    metrics_path: '/metrics'
    static_configs:
      - targets: ["ourwebsite.tech"]
    basic_auth: 
      username: ""
      password: UPTIME_KUMA_API_KEY
```

But I got this error:

_file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: \"https://ourwebsite.tech/metrics\" is not a valid hostname"_

What am I doing wrong here? Btw I run this in AWS ECS.
