### DISCUSSION TITLE
Avoid duplicate / wrong discovered targets using dockerswarm_sd_configs

### DISCUSSION THREAD

**Discussion by ov-developer** [prometheus/prometheus#15808] [Q&A]
I'm running services in docker swarm and use `dockerswarm_sd_configs` to discover those services (and their single tasks) automatically. This works great so far.

Recently, I got the need to publish multiple ports for one service, which lead to the problem that I have a target for each of the ports.
But I don't provide metrics on each port.

Is anybody aware of any way to avoid the creation of a target for each published port? In general, I think the normal use case is, that one has only one metrics-endpoint per service.

In the example below, I found that even I publish three ports, I see only two targets in the discovery. I really don't understand the logic in the discovery.

Anyway: can it somehow be done using filters or relabeling? I couldn't find a solution myself but hope someone can help me out.

Thanks!

Service-Definition in compose-file which is deployed to swarm using `docker stack deploy`:
```
  myservice:
    image: myservice
    deploy:
      labels:
        prometheus.metrics: active
        prometheus.port: 9110
    ports:
      - target: 40002
        published: 40002
        mode: host
      - target: 50002
        published: 50002
        mode: host
      - target: 8080
        published: 8080
        mode: host
```

Prometheus-Configuration, which discovers and relabels. In fact, I don't provide metrics on any of the published ports at all:
```
- job_name: "docker-swarm-tasks"
  dockerswarm_sd_configs:
    - host: unix:///var/run/docker.sock
      role: tasks
  relabel_configs:
    # Only keep tasks that should be running.
    - source_labels: [ __meta_dockerswarm_task_desired_state ]
      regex: running
      action: keep
    # Only keep tasks that have `prometheus.metrics` activated via label.
    - source_labels: [ __meta_dockerswarm_service_label_prometheus_metrics ]
      regex: active
      action: keep
    # Use the nodes hostname as node label.
    - source_labels: [ __meta_dockerswarm_node_hostname ]
      target_label: node
    # Use a combination of different labels (that is also DNS-addressable) as an instance label.
    - source_labels: [ __meta_dockerswarm_service_name, __meta_dockerswarm_node_id, __meta_dockerswarm_task_id ]
      separator: .
      target_label: instance
    # Use the service labels that are prefixed with `prometheus.`. to allow generic overrides.
    - regex: __meta_dockerswarm_service_label_prometheus_(.+)
      action: labelmap
      replacement: $1
    # Set the port to scrape from the `prometheus.port` label if it exists.
    - source_labels: [__address__, __meta_dockerswarm_service_label_prometheus_port]
      target_label: __address__
      regex: '(.*):(\d+);(\d+)'
      replacement: "${1}:${3}"
```
