### DISCUSSION TITLE
Trivy Operator Dashboard in Grafana

### DISCUSSION THREAD

**Discussion by ivialex** [prometheus/prometheus#16062] [Q&A]
### Proposal

<div type='discussions-op-text'>

Hello,

I am following this link https://aquasecurity.github.io/trivy-operator/v0.18.1/tutorials/grafana-dashboard/ to integrate Trivy Operator with Grafana / Prometheus.

My stacks:

1. Azure Kubernetes Services Version: 1.31.3
2. Azure Managed Grafana
3. Azure Managed Prometheus
4. Trivy Operator (CHART trivy-operator-0.25.0 )

I am enabling serviceMonitor as:

```
serviceMonitor:
  # enabled determines whether a serviceMonitor should be deployed
  enabled: true
```

However, I think that `serviceMonitor ` in `trivy-operator` is not working with `apiVersion: azmonitoring.coreos.com/v1`. I would like to confirm if it works with my stacks described above or not. 

I tried to create custom `podMonitor `and `serviceMonitor `as this documentation: https://learn.microsoft.com/en-us/azure/azure-monitor/containers/prometheus-metrics-scrape-crd, but it not worked as well. 

Is there any workaround?

Thanks,
</div>

**Comment by machine424** [comment]
This looks more like a question for the `trivy-operator` community.
Regarding prometheus-operator, you can reach out to the community here https://kubernetes.slack.com/archives/CFFDS2Z7F

**Comment by MichelZ** [comment]
Just in case anyone needs this in the future, I was successful with a simple custom ServiceMonitor like this (trivy-operator `v0.31.0`):

```
apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/name: trivy-operator
  name: trivy-operator
  namespace: trivy-system
spec:
  endpoints:
    - honorLabels: true
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - trivy-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/name: trivy-operator
```
