### DISCUSSION TITLE
How do i add a label to all metrics that are sent out from remote write?

### DISCUSSION THREAD

**Discussion by majerus1223** [prometheus/prometheus#16349] [Q&A]
Looking to add a label named origin to all metrics that are sent out to remote write. How do i go about doing that? I have tried a bunch of things and cannot get something to work.

Thank you!

``` remoteWrite:
    - url: http://prometheus.domain.com/api/v1/write
      write_relabel_configs:
      - source_labels: []
        target_label: origin
        regex: .*
        replacement: fireCluster
        action: replace

**Comment by hamedrabah** [comment]
For native Prometheus configuration, no source labels or regex are needed to assign a constant:

```yaml
remote_write:
  - url: http://prometheus.domain.com/api/v1/write
    write_relabel_configs:
      - target_label: origin
        replacement: fireCluster
        action: replace
```

Your snippet mixes the Prometheus Operator/Helm field names with native Prometheus field names.

For kube-prometheus-stack values, use the Operator form under the Prometheus spec:

```yaml
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: http://prometheus.domain.com/api/v1/write
        writeRelabelConfigs:
          - targetLabel: origin
            replacement: fireCluster
            action: replace
```

Check the rendered Prometheus configuration after the Helm upgrade. The label is added only to samples sent through that remote-write queue; it is not stored on the local series.
