### DISCUSSION TITLE
Series with negative offset are continued with the last value up to 5min

### DISCUSSION THREAD

**Discussion by hagen1778** [prometheus/prometheus#9428] [Q&A]
**What did you do?**
I've started Prometheus 2.30.0 with flag `--enable-feature=promql-negative-offset` enabled and ran the following query:
```
demo_memory_usage_bytes offset -10m
```
**What did you expect to see?**
Time series shifted by 10m:
![image](https://user-images.githubusercontent.com/2902918/135623551-469bbde4-cdca-4118-bd08-9a7238bce895.png)

**What did you see instead? Under which circumstances?**
Time series are shifted by 10m. But additionally it has a 5min tail of data points repeating the last values:
![image](https://user-images.githubusercontent.com/2902918/135623395-af460e70-52c2-449b-9b45-1b7de36a83c4.png)
Apparently, this is happening due to staleness handling. I'm not sure if this behaviour is correct in this specific case, because without the negative offset metric will look like the following:
![image](https://user-images.githubusercontent.com/2902918/135623516-84fcaeff-8e6b-4d0f-8fb4-86466c7077dd.png)

**Environment**

* Prometheus version:

```
prometheus, version 2.30.0 (branch: HEAD, revision: 37468d88dce85ac507f3fb7864c7d1c078e3e27d)
  build user:       root@a4d266b51f6a
  build date:       20210914-09:34:40
  go version:       go1.17.1
  platform:         darwin/amd64
```

* Prometheus configuration file:
```
global:
  scrape_interval: 5s

scrape_configs:
 - job_name: 'demo'
   static_configs:
     - targets:
       - 'demo.promlabs.com:10000'
       - 'demo.promlabs.com:10001'
       - 'demo.promlabs.com:10002'

```
