### DISCUSSION TITLE
Passing configuration options in docker

### DISCUSSION THREAD

**Discussion by nhatfield** [prometheus/prometheus#9445] [Q&A]
Hello, 

How do I pass in config options to docker when I run the container? Im trying to set `--storage.tsdb.retention.time=90d`

**Comment by nhatfield** [comment]
Nevermind all you have to do is pass in the arguments. The one caveat is you need to pass in all args and not just the ones you want. Would be nice to move to an entrypoint model so it retains the defaults

**Reply by roidelapluie** [reply]
Can you please be more specific?

**Reply by azlux** [reply]
@roidelapluie A real entrypoint is here to prepare the run of a program.

Main usage is to read environment variable then prepare all parameter for your program. This was, when people want to change some parameters, they only need to add an Environnement variable.
See an exemple here : https://github.com/azlux/botamusique/blob/master/entrypoint.sh . I read the variable, then prepare my command to run. This way You can also manage all default values (like --config.file  --storage.tsdb.path --web.console.libraries --web.console.templates) without the need for the user to rewrite them all when they want to edit parameters.

**Comment by Raphasha27** [comment]
Pass config options to Prometheus in Docker using command-line arguments or environment variables:

**Option 1: Command-line args in docker run**

```bash
docker run -d \
  --name prometheus \
  -p 9090:9090 \
  -v /path/to/prometheus.yml:/etc/prometheus/prometheus.yml \
  prom/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.retention.time=30d \
  --storage.tsdb.retention.size=50GB \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.console.templates=/etc/prometheus/consoles \
  --web.enable-lifecycle
```

**Option 2: Docker Compose with command overrides**

```yaml
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:9090'
    ports:
      - "9090:9090"
```

**Option 3: Environment variables (limited support)**

```yaml
services:
  prometheus:
    image: prom/prometheus
    environment:
      - PROMETHEUS_CONFIG_FILE=/etc/prometheus/prometheus.yml
```

But most flags require `command:` args, not env vars. The key ones you'll likely want:

```bash
--storage.tsdb.retention.time=30d    # how long to keep data
--storage.tsdb.retention.size=50GB   # max disk usage for data
--web.enable-lifecycle                # enable /-/reload
--web.enable-admin-api                # enable admin endpoints
--log.level=info                      # debug/info/warn/error
--query.timeout=2m                    # max query execution time
--query.max-concurrency=20            # concurrent queries
```
