### DISCUSSION TITLE
Prometheus Screapes to Multiple Ports Of Pods

### DISCUSSION THREAD

**Discussion by biswa-r-singh** [prometheus/prometheus#9677] [Q&A]
PROMETHEUS SCRAPES ON MULTIPLE PORTS OF POD FOR UNKNOWN REASON. Please see the details of the issue.

Prometheus Scrape Configuration
=========================
```yaml
- job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
          action: replace
          target_label: __scheme__
          regex: (https?)
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_prometheus_io_port]
          action: replace
          target_label: __address__
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
```

Pod Definition
===========

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod 
  namespace: argo 
  annotations:
   prometheus.io/port: "8090"
   prometheus.io/scrape: "true"
spec:
  serviceAccount: argo 
  containers:
  - name: workflow
    image: ubuntu 
    command: ['bash','-c','sleep 10000']
    imagePullPolicy: IfNotPresent 
  imagePullSecrets:
  - name: regcred
 ``` 
    
tcptrack command output in testpod
===========================
10.198.22.240:51258 	10.198.40.143:7079 	CLOSED 10s 0 B/s
10.198.22.240:50354 	10.198.40.143:7079 	CLOSED 40s 0 B/s
10.198.22.240:33152 	10.198.40.143:4040 	ESTABLISHED 2s 0 B/s
10.198.22.240:47726 	10.198.40.143:8090 	ESTABLISHED 9s 0 B/s

10.198.22.240 = prometheus pod ip
10.198.40.143 = testpod ip 

Issue
====

Though the scrape config is expected to scrape on port 8090. I see prometheus tries to initiate scrape on ports like 7079, 4040, etc on
the test pod. Why its happening? Any insight?
