### DISCUSSION TITLE
Further generalizing http_sd configuration for truly generic discovery

### DISCUSSION THREAD

**Discussion by mrnetops** [prometheus/prometheus#9937] [Ideas]
Looking at the projects that are jumping into http_sd, I'm seeing some divergence in how folks are using it that seems to be handled in rewrite rules, when I think we can converge for truly generic service discovery

# fastly-exporter
* service ids for targets
* needing to reuse the http_sd_configs -> url because all of the services discovered are coming back to the same endpoint
```
relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: service
      - target_label: __address__
        replacement: 127.0.0.1:8080
```
# prometheus-vcd-sd
* __meta_vcd_network_internal -> __address__ relabel
* __meta_vcd_name -> instance
```
  relabel_configs:
  - source_labels: [__meta_vcd_network_internal]
    replacement: "${1}:9100"
    target_label: __address__
  - source_labels: [__meta_vcd_name]
    target_label: instance
    target_label: instance
```
# suggestions

* param field in http_sd output, similar to labels with key:value parameters that are used for the url.
* either make target optional, where if not present a single element array consisting of the http_sd_configs -> url hostname:port combination is used, or have a similar effect with a dedicated keyword (__url__?  http_sd_configs_url?)

Ideally we should have an interface that could be used generically without having to understand and map each individual http_sd implementation.

This would also hopefully be a step along the road to auto discovering service discovery endpoints, ala automatic service discovery on things like auto discovered kubernetes endpoints.

@roidelapluie ^
