### ISSUE TITLE
Sync repo settings with GitHub app

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#10091]
## Proposal

We can sync GitHub repo settings with `.github/settings.yml` using a [GitHub App](https://github.com/apps/settings).

This will allow us to keep some settings in sync between all projects, like "Automatically delete head branches".

Proposed first pass on settings:
```yaml
---
repository:
  delete_branch_on_merge: true
  enable_vulnerability_alerts: true
```

Other things like branch protection can be added later if we want.
