### ISSUE TITLE
Header for Oauth in targets

### ISSUE THREAD

**Issue by talset** [prometheus/prometheus#1010]
Some soft like Openshift provide metrics accessible through the openshit http api like. To collect metrics we need https (supported) and Oauth. But currently, we can't use Oauth.

To be able to use that, we have to add an header "Authorization: Bearer" like this : 
```bash
  curl -s -k https://<host>:<port>/metrics -H "Authorization: Bearer <token>"
```

Idea is to have header into targets declaration like : 
```yaml
# The targets specified by the target group.
targets:
  [ - '<host>' ]

# Labels assigned to all metrics scraped from the targets.
labels:
  [ <labelname>: <labelvalue> ... ]

header:
  [<headername>: <headervalue> ...]
```

Do you think it will be possible ?

Thanks,
