### ISSUE TITLE
Insecure certificate

### ISSUE THREAD

**Issue by talset** [prometheus/prometheus#1013]
Hi,

In my case i didn't have a valid certificate for my domain so when i try to get metrics with https on my openshift I have : 

```bash
Get https://10.0.0.254:8443/metrics: x509: cannot validate certificate for 10.0.0.254 because it doesn't contain any IP SANs 
```
In the kubernetes_sd_configs, we have the insecure flag, but i didn't find in the scrape_config part
Is it possible to have something like that ?

```yaml
  - job_name: 'openshift-metrics'
    scheme: https
    insecure: True

    target_groups:
      - targets: ['10.0.0.254:8443']

    bearer_token: '<token>'
```

Thanks,
