### ISSUE TITLE
Update Getting Started Guide with new UI

### ISSUE THREAD

**Issue by alisakotliarova** [prometheus/prometheus#10134]
I noticed a discrepancy in the UI when following along with the Getting Started Guide.  I found that this was not an issue when using the "Classic UI" so I imagine these instructions just need to be updated to correspond to the new UI.  I am new to Prometheus so I am not sure if there may be other discrepancies as well.

**What did you do?**

Follow along the [Getting Started tutorial](https://prometheus.io/docs/prometheus/latest/getting_started/#getting-started).

**What did you expect to see?**

In the [Using the expression browser section](https://prometheus.io/docs/prometheus/latest/getting_started/#using-the-expression-browser), it says 

> choose the "Console" view within the "Graph" tab

**What did you see instead? Under which circumstances?**

There is no "Console" view within the "Graph" tab.  However, there is if I select to go the the "Classic UI".

**Environment**

* System information:

	Darwin 20.6.0 x86_64

* Prometheus version:

	prometheus, version 2.30.3 (branch: non-git, revision: non-git)
        build user:       brew@BigSur
        build date:       20211007-01:13:43
        go version:       go1.17.1
        platform:         darwin/amd64

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
```
