### ISSUE TITLE
Docker SD missing service: and container: networking modes

### ISSUE THREAD

**Issue by KetchupBomb** [prometheus/prometheus#10141]
**What did you do?**
Using Docker Compose, I have two containers, summarized here:

```yaml
- container_name: mysql
  hostname: mysql
  image: mysql:5
  networks:
    private: {}

- container_name: exporter__mysql
  depends_on:
    - mysql
  image: prom/mysqld-exporter
  network_mode: service:mysql
```

My goal is to have a Pod-like ability to hit the `mysql` container on both ports 3306 (MySQL traffic), and 9104 (exporter traffic).

**What did you expect to see?**
That `exporter__mysql` would show up as discoverable within Prometheus's Service Discovery, which I could then further filter labels and select.

**What did you see instead? Under which circumstances?**
When I view all containers discovered by Prometheus using the Docker socket, it does not include the `exporter__mysql` container. I've tried both `network_mode: service:mysql`, as well as `network_mode: container:mysql` and neither work. If I move `exporter__mysql` to the `private` network in which `mysql` is running (`network: private`), then it shows up in Prometheus Docker socket discovery.

I thought I might be running into #7684, which indicates that containers need to expose ports:
> It looks like your services are not exporting any ports, which is why they do not appear in service discovery.

But I confirmed that the running container is exposing 9104 and that I could hit it using the `mysql` hostname:
```shell
$ docker inspect exporter__mysql | jq -r '.[].Config.ExposedPorts'
{
  "9104/tcp": {}
}

$ docker run -it --rm --net private alpine wget -qO- mysql:9104/metrics | wc -l
1920
```

**Environment**

* System information:

```shell
$ uname -srm
Linux 5.4.0-91-generic x86_64
```

* Prometheus version:

```shell
$ docker exec -it prometheus prometheus --version
prometheus, version 2.32.1 (branch: HEAD, revision: 41f1a8125e664985dd30674e5bdf6b683eff5d32)
  build user:       root@54b6dbd48b97
  build date:       20211217-22:08:06
  go version:       go1.17.5
  platform:         linux/amd64
```

* Prometheus configuration file:

```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker-containers'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Select containers whose name is prefixed by `exporter__`.
      - source_labels: [__meta_docker_container_name]
        regex: /exporter__.+ # For some reason, container names begin with a '/' character.
        action: keep
      # Create new label named 'container' with the value from the meta container name label.
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: /(.+)
```

Note: The above config works for other exporters which aren't tied to specific services. I am successfully running and scraping metrics for the Node and cAdvisor exporters. The issue is that the Docker socket service discovery is outright missing containers who share network namespaces with other containers.

* Logs:

No issues:
```
ts=2022-01-08T08:49:17.468Z caller=main.go:1129 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2022-01-08T08:49:17.469Z caller=main.go:1166 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=773.879µs db_storage=1.63µs remote_storage=1.563µs web_handler=679ns query_engine=1.434µs scrape=333.957µs scrape_sd=74.472µs notify=11.014µs notify_sd=6.806µs rules=1.385µs
```
