### ISSUE TITLE
Allow remote read without external labels

### ISSUE THREAD

**Issue by marcelo-giraldi** [prometheus/prometheus#10158]
## Proposal
**Use case. Why is this important?**
In our current setup, we have a unique Prometheus instance, no external_labels configured, and remote storage (InfluxDB) that already has months of data.

```
global:

  scrape_interval: 60s
  scrape_timeout: 30s

scrape_configs:
[...]
remote_write: 
  - url: xxx

remote_read: 
  - url: yyy
```

Now we need to set an external_label. However, when we do that, we can't retrieve data from remote_read (https://github.com/prometheus/prometheus/issues/7992).

It should have an option to ignore external_labels in remote_read in order to keep reading data that has already been written.
