### ISSUE TITLE
Error sending alert: http2: unsupported scheme

### ISSUE THREAD

**Issue by compilenix** [prometheus/prometheus#10160]
**What did you do?**
I've updated prometheus and alertmanager.

**What did you expect to see?**
alerts being sent to alertmanager.

**What did you see instead? Under which circumstances?**
no alerts are sent to alertmanager and and error logged by prometheus.

**Environment**
docker + docker-compose in an Ubuntu 20.04.3 LTS VM running on VMware vSphere ESXi.

There is a nginx installed on the Ubuntu host machine which provides https + reverse proxy for internal and external requests to service-name.domain.tld.

* System information:

	Linux 5.4.0-94-generic x86_64

* Prometheus version:

	from version v2.28.1 to v2.32.1

* Alertmanager version:

	from version v0.22.2 to v0.23.0

* Docker Compose file:
```
version: '3.7'

volumes:
  prometheus_data: {}

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.13.0/24

  front-tier:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.173.0/24

  back-tier:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.191.0/24

services:
  prometheus:
#   https://hub.docker.com/r/prom/prometheus/tags
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=200GB'
      - '--storage.tsdb.retention.time=5y'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.external-url=https://prometheus.domain.tld/'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--enable-feature=promql-at-modifier'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  alertmanager:
#   https://hub.docker.com/r/prom/alertmanager/tags
    image: prom/alertmanager:v0.23.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/etc/alertmanager/:/etc/alertmanager/
      - ./alertmanager/data/:/data/
    networks:
      - back-tier
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/data'
      - '--web.external-url=https://alertmanager.domain.tld/'
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
#  external_labels:
#      monitor: 'my-project'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alerts/*.yml'
  # - "first.rules"
  # - "second.rules"

# alert
alerting:
  alertmanagers:
  - scheme: http
    proxy_url: "https://alertmanager.domain.tld"
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    scrape_interval: 10s
    scrape_timeout: 9s
    static_configs:
      - targets: ['alertmanager:9093']
```

* Alertmanager configuration file:
```
# https://www.prometheus.io/docs/alerting/latest/configuration

global:
  smtp_smarthost: 'mailserver.domain.tld:25'
  smtp_from: 'alertmanager@domain.tld'
  smtp_hello: 'redacted.domain.tld'
  smtp_require_tls: false
  http_config:
    proxy_url: 'https://alertmanager.domain.tld'

templates:
  - '/etc/alertmanager/template/*.tmpl'

# A route block defines a node in a routing tree and its children.
#
# Every alert enters the routing tree at the configured top-level route, 
# which must match all alerts (i.e. not have any configured matchers). 
# It then traverses the child nodes. If continue is set to false, it stops 
# after the first matching child. 
# If continue is true on a matching node, the alert will continue matching 
# against subsequent siblings. 
# If an alert does not match any children of a node 
# (no matching child nodes, or none exist), the alert is handled based 
# on the configuration parameters of the current node.
route:

  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  #
  # To aggregate by all possible labels use the special value '...' as the sole label name, for example:
  # group_by: ['...']
  # This effectively disables aggregation entirely, passing through all
  # alerts as-is. This is unlikely to be what you want, unless you have
  # a very low alert volume or your upstream notification system performs
  # its own grouping.
  group_by: ['alertname', 'instance', 'service']

  # How long to initially wait to send a notification for a group of alerts. 
  # Allows to wait for an inhibiting alert to arrive or collect more initial 
  # alerts for the same group. (Usually ~0s to few minutes.)
  group_wait: 30s

  # How long to wait before sending a notification about new alerts that are 
  # added to a group of alerts for which an initial notification has 
  # already been sent.
  group_interval: 5m

  # How long to wait before sending a notification again if it has 
  # already been sent successfully for an alert.
  #repeat_interval: 8736h
  receiver: mail-alerts

  # Zero or more child routes.<LeftMouse>
  # 
  # Routing tree visulizer / debugger:
  # https://www.prometheus.io/webtools/alerting/routing-tree-editor/
  routes:
  - matchers:
      - 'severity="critical"'
      - 'alertname=~"HP_iLO_Unhealthy_Temparature|Temperature_RZ1|Temperature_RZ2|Temperature_RZ3|Temperature_USV_Room"'
    receiver: mail-alerts-critical-temperature
  - match:
      severity: critical
    receiver: mail-alerts-critical
  - match:
      severity: warning
    receiver: mail-alerts-warning
  - match:
      severity: test
    receiver: tils-test-mail
    repeat_interval: 3000m

# An inhibition rule mutes an alert (target) matching a set of matchers 
# when an alert (source) exists that matches another set of matchers. 
# Both target and source alerts must have the same label values for 
# the label names in the equal list.
#
# Semantically, a missing label and a label with an empty value 
# are the same thing. 
# Therefore, if all the label names listed in equal are missing from 
# both the source and target alerts, the inhibition rule will apply.
#
# To prevent an alert from inhibiting itself, an alert that matches 
# both the target and the source side of a rule cannot be inhibited 
# by alerts for which the same is true (including itself). 
# However, we recommend to choose target and source matchers 
# in a way that alerts never match both sides. 
# It is much easier to reason about and does not trigger this special case.
inhibit_rules:
  # We use this to mute any warning-level notifications if the same alert is 
  # already critical.
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    # Apply inhibition if the alertname is the same.
    # CAUTION: 
    #   If all label names listed in `equal` are missing 
    #   from both the source and target alerts,
    #   the inhibition rule will apply!
    equal: ['alertname', 'instance', 'service']

# Receiver is a named configuration of one or more notification integrations.
receivers:
  - name: 'mail-alerts'
    email_configs:
      - to: 'redacted@domain.tld'
        send_resolved: true
  - name: 'mail-alerts-critical'
    email_configs:
      - to: 'redacted@domain.tld'
        send_resolved: true
  - name: 'mail-alerts-critical-temperature'
    email_configs:
      - to: 'alerts-critical@domain.tld'
        from: 'redacted@domain.tld'
        send_resolved: true
  - name: 'mail-alerts-warning'
    email_configs:
      - to: 'redacted@domain.tld'
        send_resolved: true
  - name: 'tils-test-mail'
    email_configs:
     - to: 'redacted@domain.tld' 
```

* Logs:
** Alertmanager
```
alertmanager_1              | level=info ts=2022-01-13T10:52:01.667Z caller=main.go:225 msg="Starting Alertmanager" version="(version=0.23.0, branch=HEAD, revision=61046b17771a57cfd4c4a51be370ab930a4d7d54)"
alertmanager_1              | level=info ts=2022-01-13T10:52:01.667Z caller=main.go:226 build_context="(go=go1.16.7, user=root@e21a959be8d2, date=20210825-10:48:55)"
alertmanager_1              | level=info ts=2022-01-13T10:52:01.668Z caller=cluster.go:184 component=cluster msg="setting advertise address explicitly" addr=172.18.0.7 port=9094
alertmanager_1              | level=info ts=2022-01-13T10:52:01.671Z caller=cluster.go:671 component=cluster msg="Waiting for gossip to settle..." interval=2s
alertmanager_1              | level=info ts=2022-01-13T10:52:01.713Z caller=coordinator.go:113 component=configuration msg="Loading configuration file" file=/etc/alertmanager/config.yml
alertmanager_1              | level=info ts=2022-01-13T10:52:01.714Z caller=coordinator.go:126 component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config.yml
alertmanager_1              | level=info ts=2022-01-13T10:52:01.717Z caller=main.go:518 msg=Listening address=:9093
alertmanager_1              | level=info ts=2022-01-13T10:52:01.718Z caller=tls_config.go:191 msg="TLS is disabled." http2=false
alertmanager_1              | level=info ts=2022-01-13T10:52:03.672Z caller=cluster.go:696 component=cluster msg="gossip not settled" polls=0 before=0 now=1 elapsed=2.001061322s
alertmanager_1              | level=info ts=2022-01-13T10:52:11.674Z caller=cluster.go:688 component=cluster msg="gossip settled; proceeding" elapsed=10.002424442s
```

** Prometheus
```
prometheus_1                | ts=2022-01-12T14:02:20.367Z caller=main.go:171 level=info msg="Experimental promql-at-modifier enabled"
prometheus_1                | ts=2022-01-12T14:02:20.388Z caller=main.go:515 level=info msg="Starting Prometheus" version="(version=2.32.1, branch=HEAD, revision=41f1a8125e664985dd30674e5bdf6b683eff5d32)"
prometheus_1                | ts=2022-01-12T14:02:20.388Z caller=main.go:520 level=info build_context="(go=go1.17.5, user=root@54b6dbd48b97, date=20211217-22:08:06)"
prometheus_1                | ts=2022-01-12T14:02:20.388Z caller=main.go:521 level=info host_details="(Linux 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64 7388d9fb57e3 (none))"
prometheus_1                | ts=2022-01-12T14:02:20.388Z caller=main.go:522 level=info fd_limits="(soft=1048576, hard=1048576)"
prometheus_1                | ts=2022-01-12T14:02:20.388Z caller=main.go:523 level=info vm_limits="(soft=unlimited, hard=unlimited)"
prometheus_1                | ts=2022-01-12T14:02:20.399Z caller=web.go:570 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
prometheus_1                | ts=2022-01-12T14:02:20.420Z caller=main.go:924 level=info msg="Starting TSDB ..."
prometheus_1                | ts=2022-01-12T14:02:20.422Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
prometheus_1                | ts=2022-01-12T14:02:20.453Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1628877600000 maxt=1630627200000 ulid=01FEMSK0DPKSPK61B3N5NV81KW
prometheus_1                | ts=2022-01-12T14:02:20.472Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1630627200798 maxt=1632376800000 ulid=01FG95GBM38BPARV9N0KYM4W4C
prometheus_1                | ts=2022-01-12T14:02:20.487Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1632376800041 maxt=1634126400000 ulid=01FHX9SBN5YPSY96SHT79TC5N2
prometheus_1                | ts=2022-01-12T14:02:20.504Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1634126400238 maxt=1635876000000 ulid=01FKHE8NED6Z7C93GAATRBERZX
prometheus_1                | ts=2022-01-12T14:02:20.525Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1635876000053 maxt=1637625600000 ulid=01FN5JSJEB0H78ZT4SWX6RAC7N
prometheus_1                | ts=2022-01-12T14:02:20.537Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1637625600217 maxt=1639375200000 ulid=01FPSQB7WB1R16X4DZJTXQY5QA
prometheus_1                | ts=2022-01-12T14:02:20.545Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1639375200239 maxt=1641124800000 ulid=01FRDVWP47TH57SG8EMB9PT9NC
prometheus_1                | ts=2022-01-12T14:02:20.555Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641124800283 maxt=1641708000000 ulid=01FRZ7ZRC6NS8NXNVPT38T2XRJ
prometheus_1                | ts=2022-01-12T14:02:20.565Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641708000283 maxt=1641902400000 ulid=01FS51BDM8HAEJ11VM5YPADC22
prometheus_1                | ts=2022-01-12T14:02:20.578Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641967200250 maxt=1641974400000 ulid=01FS6R7WXGQAWGHR896BP9DYC1
prometheus_1                | ts=2022-01-12T14:02:20.592Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641974400250 maxt=1641981600000 ulid=01FS6Z3M5FS2Z37NHJ4755MR0Z
prometheus_1                | ts=2022-01-12T14:02:20.597Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641902400250 maxt=1641967200000 ulid=01FS6Z4FNG91MT4RD6NGPHV8Z9
prometheus_1                | ts=2022-01-12T14:02:20.604Z caller=repair.go:57 level=info component=tsdb msg="Found healthy block" mint=1641981600250 maxt=1641988800000 ulid=01FS75ZBE92JMGSDY3SD7VQB3S
prometheus_1                | ts=2022-01-12T14:02:25.347Z caller=head.go:488 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
prometheus_1                | ts=2022-01-12T14:02:25.806Z caller=head.go:522 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=459.603976ms
prometheus_1                | ts=2022-01-12T14:02:25.806Z caller=head.go:528 level=info component=tsdb msg="Replaying WAL, this may take a while"
prometheus_1                | ts=2022-01-12T14:04:40.966Z caller=head.go:564 level=info component=tsdb msg="WAL checkpoint loaded"
prometheus_1                | ts=2022-01-12T14:04:46.848Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17459 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:04:54.006Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17460 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:04:59.462Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17461 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:05:08.929Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17462 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:05:10.172Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17463 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:05:10.173Z caller=head.go:599 level=info component=tsdb msg="WAL segment loaded" segment=17464 maxSegment=17464
prometheus_1                | ts=2022-01-12T14:05:10.173Z caller=head.go:605 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=2m15.159957052s wal_replay_duration=29.20616551s total_replay_duration=2m44.825789043s
prometheus_1                | ts=2022-01-12T14:05:10.908Z caller=main.go:945 level=info fs_type=EXT4_SUPER_MAGIC
prometheus_1                | ts=2022-01-12T14:05:10.909Z caller=main.go:948 level=info msg="TSDB started"
prometheus_1                | ts=2022-01-12T14:05:10.909Z caller=main.go:1129 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus_1                | ts=2022-01-12T14:05:11.125Z caller=main.go:1166 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=216.873395ms db_storage=1.723µs remote_storage=1.968µs web_handler=680ns query_engine=1.303µs scrape=291.882µs scrape_sd=591.151µs notify=28.149µs notify_sd=16.694µs rules=212.727311ms
prometheus_1                | ts=2022-01-12T14:05:11.125Z caller=main.go:897 level=info msg="Server is ready to receive web requests."
prometheus_1                | ts=2022-01-12T14:06:21.791Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:07:36.787Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:08:51.787Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:10:06.786Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:10:39.063Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:11:14.319Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:11:21.788Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:11:54.068Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:12:29.319Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:12:36.787Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:12:36.790Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:13:09.064Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:13:44.319Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:13:51.788Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:13:51.791Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
prometheus_1                | ts=2022-01-12T14:14:24.064Z caller=notifier.go:526 level=error component=notifier alertmanager=http://alertmanager:9093/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://alertmanager:9093/api/v2/alerts\": http2: unsupported scheme"
```
