### ISSUE TITLE
promtool check config - Syntax Error - Matching against LABEL containing colon caracter.

### ISSUE THREAD

**Issue by xkilian** [prometheus/prometheus#10176]
**What did you do?**

check config
fails with the following error:
... yaml: line 7: mapping values are not allowed in this context

**What did you expect to see?**
Rule validated.

**What did you see instead? Under which circumstances?**

Compile the following a recording rule that matches a string in a label.

The string contains text TEXT: value.

**Environment**

* System information:

	Ubuntu Server 18.04LTS

* Prometheus version:

`prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64`

* Alertmanager version:

	N/A

* Prometheus configuration file:
```
groups:
  
  - name: recording_rules_stroboscope

    rules:
      - record: stroboscope::etat_sipproxy
        expr: (sipProxy{state=~".*PRI: Up.*" == bool 1)  without (state)
```
PRI: Up is considered invalid YAML by check config.

* Alertmanager configuration file:
```
N/A
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
