### ISSUE TITLE
Proposal: Dynamic targets for http_sd_configs 

### ISSUE THREAD

**Issue by rfratto** [prometheus/prometheus#10214]
## Proposal
I would like the ability to chain targets from `kubernetes_sd_configs` into `http_sd_configs`. This will enable discovering targets from environments where both the targets and the systems which expose targets change. 

### Background 
I'm currently working on support for [integrations](https://grafana.com/docs/agent/latest/configuration/integrations/) into Grafana Agent Operator. This works by deploying a few sets of Grafana Agent pods:

* DaemonSet for integrations which need to run on each node (like `node_exporter`) 
* Deployment for other integrations 
* StatefulSet for collecting metrics from integrations (to benefit from a persistent WAL) 

Integrations running in Grafana Agent get their own dedicated endpoint where metrics are exposed, such as `/integrations/node_exporter/metrics`. Grafana Agent v0.22.0 added an [API endpoint](https://grafana.com/docs/agent/latest/api/#integrations-sd-api) to discover the endpoints of all running integrations for a given agent. 

I need to be able to configure the Grafana Agent StatefulSet to invoke this new API endpoint to find targets for all running Grafana Agent pods. However, given how `http_sd_configs` works, I can only configure a static set of API endpoints. 

I initially [planned](https://github.com/grafana/agent/pull/1224/files#diff-e3389f04598a5a63177148b0bfde4d6448b55f207408340a25c1674b9f9cfda4R176) to work around this by implementing an API at the operator level which aggregates the results of the individual endpoints, but I believe it would be more generally useful to solve this at the SD level. 

### Implementation 
I propose being able to embed other SDs inside `http_sd_configs`: 

```yaml
scrape_configs:
- job_name: grafana-agent-pods
  http_sd_configs:
  - # configure http_sd_configs to find API endpoints from k8s 
    kubernetes_sd_configs: 
    - role: pod 
      selectors:
      - role: pod
        label: app=grafana-agent
    # configure API path to use for exposing targets 
    api_path: /agent/api/v1/integrations/metrics/sd
```

`http_sd_configs` would be extended to support any SD. Additionally, `relabel_configs` would be added to relabel discovered targets which hold endpoints.  

### Alternatives 
Users could write a new HTTP SD API which internally performs aggregation of the multiple API endpoints across their dynamic environment. This would require no changes to Prometheus today, but puts extra implementation burden on users. 

### Concerns 
This feels like a big shift from the existing HTTP SD mechanism. Maybe this should be its own discoverer (`dynamic_http_sd_configs`)? 

If `http_sd_configs` is used for this functionality, configuring an SD would need to be mutually exclusive with configuring `url`.
