### ISSUE TITLE
metrics drop based on label

### ISSUE THREAD

**Issue by mohan-nagandlla** [prometheus/prometheus#10255]
Hi Team,
I just want to drop the metrics from federation instnace
by enabling the relabel concept but its not success

the sample metrics is 
```
up{container="prometheus", exported_exported_exported_exported_instance="20.204.x.x:9090", exported_exported_exported_exported_job="aks-prometheus", exported_exported_exported_instance="20.204.x.x:9090", exported_exported_exported_job="aks-prometheus", exported_exported_instance="20.204x.x:9090", exported_exported_job="aks-prometheus", exported_instance="k8s-mohan-promethe-a72ee3683a050e.elb.us-east-2.amazonaws.com:9090", exported_job="aws-prometheus", instance="k8s-mohan-promethe-bba72ee3683a050e.elb.us-east-2.amazonaws.com:9090", job="aws-prometheus", namespace="prom-op", pod="prometheus-pro-kube-prometheus-stack-prometheus-0", prometheus="prom-op/pro-kube-prometheus-stack-prometheus", prometheus_replica="prometheus-pro-kube-prometheus-stack-prometheus-0", service="pro-kube-prometheus-stack-prometheus"}  
up{container="prometheus", endpoint="9090", exported_instance="20.x.x.x:9090, job="aws-prometheus", namespace="prom-op", pod="prometheus-pro-kube-prometheus-stack-prometheus-0", prometheus="prom-op/pro-kube-prometheus-stack-prometheus", prometheus_replica="prometheus-pro-kube-prometheus-stack-prometheus-0", service="pro-kube-prometheus-stack-prometheus"}
```

I don't want to see these metrics which is having more than one-time exported_exported_.* I need the metrics which contain only exported_instance label.

I have tries this 

```
- job_name: "aws-prometheus"
  metrics_path: '/federate'
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  params:
      'match[]':
        - '{job=~".*"}'
  relabel_configs:
    - source_labels: [__name__]
      regex: (exported_exported_.*)
      action: drop
  static_configs:
  - targets: ["k8s-mohan.prometheus.com"]
```
