### ISSUE TITLE
No systematic DNS resolution against targets

### ISSUE THREAD

**Issue by mveroone** [prometheus/prometheus#10299]
**What did you do?**
I have changed the DNS record of a target of a node_exporter job

**What did you expect to see?**
The polling switched to the new target as soon as the DNS replication is propagated to Prometheus

**What did you see instead? Under which circumstances?**
Prometheus kept polling the old IP until I restarted the prometheus daemon. (reload didn't help)

**Environment**
RHEL 7.9

* System information:

```
Linux 3.10.0-1160.31.1.el7.x86_64 x86_64
```

* Prometheus version:

```
prometheus, version 2.31.1 (branch: HEAD, revision: 411021ada9ab41095923b8d2df9365b632fd40c3)
  build user:       root@9419c9c2d4e0
  build date:       20211105-20:35:02
  go version:       go1.17.3
  platform:         linux/amd64
```

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
global:
  # nothing special
...
  - job_name: 'xxxxx-node'
    scrape_interval: 10s
    static_configs:
     - targets:
       - hostname.example.org:9100
...
```
