### ISSUE TITLE
Deleting target from Prometheus

### ISSUE THREAD

**Issue by cmonty14** [prometheus/prometheus#10301]
**What did you do?**
After deploying node exported on client the new target is available in Prometheus.
However the client has sent wrong hostname.
Therefore I stopped the relevant service _prometheus-node_exporter.service_ on client.

Then I executed this command on Prometheus server to delete time series of the relevant client:
`curl -s -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={instance="ldcits4.devsys.net:9100"}'`

**What did you expect to see?**
Client should be deleted in targets WebUI (http://vlcspsumamon.devsys.net:9090/targets)

**What did you see instead? Under which circumstances?**
The relevant client is still listed in targets.

**Environment**

* System information:

  Linux 5.3.18-59.40-default x86_64

* Prometheus version:

  prometheus, version 2.27.1 (branch: non-git, revision: non-git)
  build user:       abuild@lamb08
  build date:       20220119-00:54:39
  go version:       go1.16.13
  platform:         linux/amd64

* Alertmanager version:

  alertmanager, version 0.23.0 (branch: HEAD, revision: 61046b17771a57cfd4c4a51be370ab930a4d7d54)
  build user:       root@e21a959be8d2
  build date:       20210825-10:48:55
  go version:       go1.16.7
  platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s


# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  #- /etc/prometheus/rules/general-rules.yml
  #- /etc/prometheus/rules/prometheus-rules.yml
  - /etc/prometheus/rules/*.rules.yml


# Scrape configurations
scrape_configs:
  # --------------------
  # Monitor vlcspsumasrv.devsys.net
  # --------------------
  - job_name: 'mgr-server'
    static_configs:
      - targets:
        - vlcspsumasrv.devsys.net:9100 # Node exporter
        - vlcspsumasrv.devsys.net:5556 # Tomcat JMX
        - vlcspsumasrv.devsys.net:5557 # Taskomatic JMX
        - vlcspsumasrv.devsys.net:9800 # Uyuni server exporter
        labels: {}
      - targets:
        - vlcspsumasrv.devsys.net:80 # Message queue
        labels:
          __metrics_path__: /rhn/metrics
      - targets:
        - vlcspsumasrv.devsys.net:9187 # PostgresSQL
        labels:
          role: postgres


  # --------------------
  # Pushgateway configuration
  # --------------------
  - job_name: 'pushgateway'
    static_configs:
      - targets:
        - localhost:9091


  # --------------------
  # Auto discover clients of vlcspsumasrv.devsys.net
  # --------------------
  - job_name: 'mgr-clients'
    uyuni_sd_configs:
      - host: https://vlcspsumasrv.devsys.net
        username: admin
        password: <password>
```
