### ISSUE TITLE
EKS deployment of Prom: remote_write using sigv4 defaults to the wrong STS endpoint for private VPCs

### ISSUE THREAD

**Issue by jbehrends** [prometheus/prometheus#10308]
**What did you do?**
AWS:  Inside of a private VPC ( by default no outbound access, but has VPC PrivateLink endpoints configured for AWS services.) we've deployed Prometheus into and EKS cluster using the kube-prometheus-stack Helm chart. 

Configured prometheus to remote_write to a AWS Managed Prometheus endpoint using IaM Roles for Service Accounts as per the official documentation:  https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-onboard-ingest-metrics-new-Prometheus.html

**What did you expect to see?**
Expected to see prometheus server running in my EKS cluster and sending metrics to the AWS Managed Prometheus ingest endpoint.

**What did you see instead? Under which circumstances?**
The Prometheus server pod started up and its readiness check was in a failed state.  The readiness check which hits /-/ready was returning a 503 error.  Then after about 10 mins the pod would be restarted.

The server's pod logs showed the following right before it was restarted by Kubernetes:
```
ts=2022-02-16T21:13:29.514Z caller=main.go:1129 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2022-02-16T21:22:13.151Z caller=main.go:1155 level=error msg="Failed to apply configuration" err="could not get SigV4 credentials: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 209.54.180.124:443: connect: connection timed out"
```
Based on the Prometheus remote_write configuration (shown in the section below) the AWS authentication library used by Prometheus should have connected to the regional endpoint for STS (sts.us-east-1.amazonaws.com) vs the global endpoint (sts.amazonaws.com) for sigv4 authentication.  

I did find a workaround:
I ended up doing some research and found this document: https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#aws-sts
You can set the env var "**AWS_STS_REGIONAL_ENDPOINTS**" to the value "**regional**" which the AWS library Prometheus is using picks up and then connects to the correct endpoint.  

For reference, this is the value I had to pass the kube-prometheus-stack helm chart to fix the issue:
```
prometheus:
  prometheusSpec:
    containers:
      - name: prometheus
         env:
           - name: AWS_STS_REGIONAL_ENDPOINTS
              value: regional      
```

So I'm not sure if the AWS auth code can be updated to account for potentially choosing the sts endpoint? or maybe this needs to potentially be better documented?

It's also worth noting that it took just shy of ten minutes for this failure to show up in the logs, even with the log level set to debug.  See the timestamps in the logs below.

**Environment**

* Prometheus version:

prometheus, version 2.32.1 (branch: HEAD, revision: 41f1a8125e664985dd30674e5bdf6b683eff5d32)
  build user:       root@54b6dbd48b97
  build date:       20211217-22:08:06
  go version:       go1.17.5
  platform:         linux/amd64

* Prometheus configuration file:
```
remote_write:
- url: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-1234abcd-1234abcd-1-2-3/api/v1/remote_write
  remote_timeout: 30s
  sigv4:
    region: us-east-1
  queue_config:
    capacity: 2500
    max_shards: 200
    max_samples_per_send: 1000
```

* Logs:
```
ts=2022-02-16T21:13:29.514Z caller=main.go:1129 level=info msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
ts=2022-02-16T21:22:13.151Z caller=main.go:1155 level=error msg="Failed to apply configuration" err="could not get SigV4 credentials: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": dial tcp 209.54.180.124:443: connect: connection timed out"
```
