### ISSUE TITLE
__meta_puppetdb_title is truncated

### ISSUE THREAD

**Issue by thibautmery** [prometheus/prometheus#10319]
**What did you do?**

Hello,
I'm using puppetdb_sd_configs to get automatically exporter.
```
job_name: 'exporter'
    puppetdb_sd_configs:
    - url: http://puppetdb
      query: 'resources { type = "Prometheus::Scrape_job""}'
    scrape_interval: 30s
```

**What did you expect to see?**

I'm expected to get the real title of puppet ressources.
The expected label: 
`__meta_puppetdb_title: "fqdn:port"`

**What did you see instead? Under which circumstances?**

Get:
`__meta_puppetdb_title: "fqdn:"`

"port" is indeed a number, prometheus remove the end of the title (port)

**Environment**

* System information:

docker

* Prometheus version:

`quay.io/prometheus/prometheus:v2.33.3`

**Comment by roidelapluie** [comment]
I do not think we mangle what we receive back from the API. Do you have a sample JSON from your PuppetDB to help us debug this?

**Comment by thibautmery** [comment]
Yes I have (fqdn name of the server), I obsfuscate all data
```
{
  "tags": [
    "XXX",
    "XXX",
  ],
  "file": "/etc/pupp....",
  "type": "Prometheus::Scrape_job",
  "title": "fqdn:9301"
  "certname": "fqdn",
}

**Comment by roidelapluie** [comment]
Can we see your prometheus configuration? I suspect you might have relabel configs that remove the port.

**Comment by thibautmery** [comment]
I already check this, in fact we were not using puppetdb-sd, I wanted to try this. 

It's the first time I use `__meta_puppetdb_title`.

For the prometheus configuration of the job:
```
relabel_configs:
- source_labels:
    - __address__
    regex: "xxx"
    target_label: environment
    replacement: prod
  - source_labels:
    - __address__
    regex: "xxx"
    target_label: environment
    replacement: preprod
  - source_labels:
    - __address__
    regex: "xxx"
    target_label: environment
    replacement: dev
  - source_labels:
    - __address__
    regex: "xxx"
    target_label: environment
    replacement: uat
  - source_labels:
    - __meta_puppetdb_title
    regex: "(.+)"
    replacement: "$1"
    target_label: __address__
```

`__meta_puppetdb_title` is not use in any configuration file
