### ISSUE TITLE
prometheus crush when using azure_sd_configs

### ISSUE THREAD

**Issue by mbakish** [prometheus/prometheus#10325]
**What did you do?**
I have deployed prometheus on AKS with the following configuration:
chart kube-prometheus-stack version 19.1.0
```
      - job_name: 'xxx-exporter'
        azure_sd_configs:
          - subscription_id: xxx
            tenant_id: xxx
            client_id: xxx
            client_secret: xxx
            environment: AzurePublicCloud
            authentication_method: OAuth
            refresh_interval: 60s
            port: 8404
        relabel_configs:
          - source_labels: [ __meta_azure_machine_tag_xxx ]
            regex: true.*
            action: keep
          - source_labels: [ __meta_azure_machine_name ]
            target_label: instance
          - source_labels: [ __meta_azure_machine_private_ip ]
            regex: (.+)
            replacement: ${1}:8404
            target_label: __address__
```
I also tried updating to the latest prometheus version 

**What did you expect to see?**
I have other subscriptions with the same config that were able to scrape the VMs

**What did you see instead? Under which circumstances?**
Prometheus pods restarts with the following error 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfe4dbe]

goroutine 3716 [running]:
github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func1(0xc016abeeb0, 0xc00bb86c00, 0xc10dec4c00, 0xc0a2552000, 0x37af990, 0xc0b2adb6c0, 0x0, 0xc0621065a0, 0x93, 0xc0174a77d0, ...)
	/app/discovery/azure/azure.go:350 +0xb5e
created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
	/app/discovery/azure/azure.go:296 +0x645
```
**Environment**
       AKS 1.19

* Prometheus version:
	2.28.1
