### ISSUE TITLE
The Alertmanager received alert nearly a minute after the status of alert in Prometheus became firing

### ISSUE THREAD

**Issue by nic-chen** [prometheus/prometheus#10424]
**What did you do?**

I create an alerting rule for Prometheus like:

```yaml
global:
  scrape_interval: 1s     # By default, scrape targets every 15 seconds.
  evaluation_interval: 1s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - xxxxx:9093
```

```yaml
groups:
- name: alarm-status
  rules:
  - alert: alarm-status
    expr: sum(increase(apisix_http_status{code='403'}[30m])) BY (instance)>1
    labels:
      alarm: "alarm-status"
      instance: "{{$labels.instance}}"
    annotations:
      summary: 
      description: 
```

and configuration of Alertmanager like:

```yaml
global:
  resolve_timeout: 30s
route:
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 10s
  group_by: ['...']
  receiver: "xxxxxx"
  routes:
  - match:
      alarm: "alarm-status"
    receiver: "xxxxxx"
    repeat_interval: "5s"

receivers:
  - name: "xxxxxx"
    webhook_configs:
      ...
```

and then trigger an alert.

**What did you expect to see?**

The Alertmanager received alert  immediately after the status of alert in Prometheus became firing

**What did you see instead? Under which circumstances?**

The Alertmanager received alert nearly a minute after the status of alert in Prometheus became firing

**Environment**

* System information:

	docker

* Alertmanager version:

	0.23.0

* Prometheus version:

	2.31.0

Hi, Community 

Not every time there is a delay, sometimes it will be received immediately, and sometimes it will be delayed again.

Is this expected?

help needed, thanks!
