### ISSUE TITLE
Prometheus agent mode using more heap memory than regular mode.

### ISSUE THREAD

**Issue by srimuvva** [prometheus/prometheus#10431]
**What did you do?**
Configured the prometheus in agent mode.
**What did you expect to see?**
Expect to see less memory foot print compared to regular mode.
**What did you see instead? Under which circumstances?**
Rather we see agent mode using more memory than that of regular mode. After further debugging with go pprof we see remote.processExternalLabels is using more than 50% of the heap, which is not the case in regular mode.
```

(pprof) top
Showing nodes accounting for 776.43MB, 91.73% of 846.41MB total
Dropped 200 nodes (cum <= 4.23MB)
Showing top 10 nodes out of 45
      flat  flat%   sum%        cum   cum%
  428.31MB 50.60% 50.60%   428.31MB 50.60%  github.com/prometheus/prometheus/storage/remote.processExternalLabels
  110.50MB 13.06% 63.66%   539.43MB 63.73%  github.com/prometheus/prometheus/storage/remote.(*QueueManager).StoreSeries
   76.06MB  8.99% 72.65%    76.06MB  8.99%  github.com/prometheus/prometheus/model/labels.(*Builder).Labels
   53.34MB  6.30% 78.95%    53.34MB  6.30%  github.com/prometheus/prometheus/scrape.newScrapePool.func1
   38.77MB  4.58% 83.53%    38.77MB  4.58%  github.com/prometheus/prometheus/tsdb/agent.(*DB).gc
   29.01MB  3.43% 86.95%    29.01MB  3.43%  github.com/prometheus/prometheus/model/textparse.(*PromParser).Metric
   10.73MB  1.27% 88.22%    10.73MB  1.27%  github.com/prometheus/prometheus/scrape.(*scrapeCache).trackStaleness
   10.46MB  1.24% 89.46%    10.46MB  1.24%  github.com/golang/snappy.Encode
   10.25MB  1.21% 90.67%    10.25MB  1.21%  github.com/prometheus/prometheus/scrape.(*scrapeCache).addRef
       9MB  1.06% 91.73%        9MB  1.06%  github.com/prometheus/prometheus/tsdb/agent.seriesHashmap.Set

```
Below the heap foot print of the same for non agent mode for the exact same environment.
```
(pprof) top
Showing nodes accounting for 403.64MB, 74.21% of 543.94MB total
Dropped 149 nodes (cum <= 2.72MB)
Showing top 10 nodes out of 94
      flat  flat%   sum%        cum   cum%
  112.58MB 20.70% 20.70%   112.58MB 20.70%  github.com/prometheus/prometheus/pkg/labels.(*Builder).Labels
   83.06MB 15.27% 35.97%    83.06MB 15.27%  github.com/prometheus/prometheus/storage/remote.processExternalLabels
   42.01MB  7.72% 43.69%    42.01MB  7.72%  github.com/prometheus/prometheus/pkg/textparse.(*PromParser).Metric
   37.22MB  6.84% 50.53%    37.22MB  6.84%  github.com/prometheus/prometheus/scrape.newScrapePool.func1
   35.51MB  6.53% 57.06%    51.01MB  9.38%  github.com/prometheus/prometheus/tsdb.newMemSeries
   30.52MB  5.61% 62.67%    30.52MB  5.61%  github.com/prometheus/prometheus/tsdb/chunkenc.(*bstream).writeByte
   16.24MB  2.99% 65.66%    16.24MB  2.99%  github.com/prometheus/prometheus/scrape.(*scrapeCache).trackStaleness
   15.50MB  2.85% 68.51%    15.50MB  2.85%  github.com/prometheus/prometheus/tsdb/chunkenc.NewXORChunk
   15.50MB  2.85% 71.36%    15.50MB  2.85%  github.com/prometheus/prometheus/tsdb.newTxRing (inline)
   15.50MB  2.85% 74.21%    22.02MB  4.05%  github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk
```
**Environment**
Kubernetes
* System information:
Linux 3.10.0-1160.53.1.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.33.4 (branch: HEAD, revision: 83032011a5d3e6102624fe58241a374a7201fee8)
  build user:       root@d13bf69e7be8
  build date:       20220222-16:51:28
  go version:       go1.17.7
  platform:         linux/amd64
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
global:
  evaluation_interval: 1m
  external_labels:
    cluster_name: 172.16.20.154
    monitor: prometheus
  scrape_interval: 1m
  scrape_timeout: 10s
remote_write:
- url: http://thanos-receive:19291/api/v1/receive
scrape_configs:
- job_name: prometheus
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: external
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
  - action: keep
    regex: 9090
    source_labels:
    - __meta_kubernetes_pod_container_port_number
  scrape_interval: 10s
- honor_labels: true
  job_name: kafka-metrics
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: broker
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
  - action: keep
    regex: 5556
    source_labels:
    - __meta_kubernetes_pod_container_port_number
  scrape_interval: 30s
  scrape_timeout: 30s
- honor_labels: true
  job_name: linstor-metrics
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: linstor
    source_labels:
    - __meta_kubernetes_namespace
  - action: keep
    regex: .*-op-cs
    source_labels:
    - __meta_kubernetes_endpoints_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
  scrape_interval: 30s
  scrape_timeout: 30s
- honor_labels: true
  job_name: drbd-metrics
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: linstor
    source_labels:
    - __meta_kubernetes_namespace
  - action: keep
    regex: .*-op-ns-monitoring
    source_labels:
    - __meta_kubernetes_endpoints_name
  - action: keep
    regex: prometheus
    source_labels:
    - __meta_kubernetes_endpoint_port_name
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
  scrape_interval: 30s
  scrape_timeout: 30s
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: kubernetes-apiservers
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: default;kubernetes;https
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_name
    - __meta_kubernetes_endpoint_port_name
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: kubernetes-nodes
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics
    source_labels:
    - __meta_kubernetes_node_name
    target_label: __metrics_path__
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  job_name: kubernetes-nodes-cadvisor
  kubernetes_sd_configs:
  - role: node
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - replacement: kubernetes.default.svc:443
    target_label: __address__
  - regex: (.+)
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
    source_labels:
    - __meta_kubernetes_node_name
    target_label: __metrics_path__
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
- job_name: kubernetes-service-endpoints
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scrape
  - action: replace
    regex: (https?)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_scheme
    target_label: __scheme__
  - action: replace
    regex: (.+)
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_path
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels:
    - __address__
    - __meta_kubernetes_service_annotation_prometheus_io_port
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_service_name
    target_label: kubernetes_name
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_node_name
    target_label: kubernetes_node
- honor_labels: true
  job_name: prometheus-pushgateway
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - action: keep
    regex: pushgateway
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_probe
- job_name: kubernetes-services
  kubernetes_sd_configs:
  - role: service
  metrics_path: /probe
  params:
    module:
    - http_2xx
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_service_annotation_prometheus_io_probe
  - source_labels:
    - __address__
    target_label: __param_target
  - replacement: blackbox
    target_label: __address__
  - source_labels:
    - __param_target
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: kubernetes_name
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
  - action: replace
    regex: (.+)
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_path
    target_label: __metrics_path__
  - action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    source_labels:
    - __address__
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: kubernetes_namespace
  - action: replace
    source_labels:
    - __meta_kubernetes_pod_name
    target_label: kubernetes_pod_name
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
