### ISSUE TITLE
Alerts evaluation: resendDelay does not account for notifications send error

### ISSUE THREAD

**Issue by hagen1778** [prometheus/prometheus#10457]
**What did you do?**
I've started Prometheus configured with alerting rule which always fires and `-resendDelay=10m`. A couple of seconds later, I started Alertmanager for receiving the alerting notification from Prometheus. 

**What did you expect to see?**
The alert notification to be received by Alertmanager.

**What did you see instead? Under which circumstances?**
There was no active alerts in Alertmanager despite the fact that Prometheus was showing that alert is firing.
The notification was received only after `10m`, which is the value of `--resendDelay` flag.

I'd expect from Prometheus to check if alert notification was successfully sent before updating the `LastSentAt` field:
https://github.com/prometheus/prometheus/blob/c4f8020dca39f5f80c8f60c81460b1947ed02269/rules/alerting.go#L493

The check would allow delivering alerting notifications faster in case of unexpected network blips or service restarts.

**Environment**

* Prometheus version:

```
 ./prometheus --version
prometheus, version 2.33.5 (branch: HEAD, revision: 03831554a51946f28c7cdc6be7282c687092327b)
  build user:       root@964b35c53f1c
  build date:       20220308-16:43:08
  go version:       go1.17.8
  platform:         darwin/amd64
```

* Prometheus configuration file:
```
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093

rule_files:
  - rules.yml
 
....
```

rules.yml:
```
groups:
  - name: TestGroup
    rules:
      - alert: ExampleAlertAlwaysFiring
        expr: prometheus_config_last_reload_successful > 0
```
