### ISSUE TITLE
Observed "Error on ingesting out-of-order samples" & "duplicate sample for timestamp" errors

### ISSUE THREAD

**Issue by SiminMu** [prometheus/prometheus#10456]
**What did you do?**
I setup two prometheus services on two separate servers, one for client to scrap several targets(use agent mode) and another for remote write endpoint

**What did you expect to see?**
I expected to see no error about "out-of-order samples" or "duplicate sample for timestamp" as I manually checked the metrics of the targets and didn't see any duplicate sample(metric name + lables name + lables value) 

**What did you see instead? Under which circumstances?**
I saw a lot of error messages about "Error on ingesting out-of-order samples" & "duplicate sample for timestamp"

**Environment**

* System information:

	Linux 4.18.0-240.22.1.el8_3.x86_64 x86_64

* Prometheus version:

	both are v1.8.2-0.20220106152233-4727c41a4b32

* Alertmanager version:

	no alertmanager 

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    datacenter: gic-seli
    env: staging
    hostalias: frontend-110
    service: cos
remote_write:
  - url: "http://*.*.*.*:9090/api/v1/write"
    # authorization:
    #   credentials: ""
    queue_config:
      capacity: 2500
      max_shards: 100
      min_shards: 1
      max_samples_per_send: 500
      batch_send_deadline: 5s
      min_backoff: 1s
      max_backoff: 1m
scrape_configs:
  - job_name: prometheus-agent
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:9999']
  - job_name: blackbox_exporter
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:9997']
  - job_name: 'blackbox-[29475:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "29475:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[29477:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "29477:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[23767:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "23767:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[28324:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "28324:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[29478:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "29478:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[29524:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "29524:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[01923:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "01923:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[04050:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "04050:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[00573:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "00573:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[00624:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "00624:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[00610:22]-ssh'
    metrics_path: /probe
    params:
      module: [ssh]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "00610:22"
        labels:
          module: ssh
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: 'blackbox-[https://observer***]-http_2xx'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - "https://observer***"
        labels:
          module: http_2xx
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: 127.0.0.1:9997  # The blackbox exporter's real hostname:port.
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
  - job_name: cadvisor
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:9338']
  - job_name: ebpf-biolatency
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:9435']
  - job_name: node
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:9100']
  - job_name: cos-configd-8899
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:8899']
  - job_name: cos-envoy-public-8097
    metrics_path: "/stats/prometheus"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:8097']
  - job_name: cos-opa-public-8282
    metrics_path: "/metrics"
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^:]+):(\d+)?
        replacement: "23768:${2}"
        target_label: instance
    sample_limit: 15000
    static_configs:
      - targets: ['127.0.0.1:8282']
```

* Alertmanager configuration file:
no alertmanager 

* Logs:
* CLIENT SIDE:
```
Mar 16 08:49:53 23768[1679944]: ts=2022-03-16T07:49:53.524Z caller=dedupe.go:112 component=remote level=error remote_name=c70f5f url=http://*.*.*.*:9090/api/v1/write msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: duplicate sample for timestamp"
Mar 16 08:50:08 23768[1679944]: ts=2022-03-16T07:50:08.515Z caller=scrape.go:1564 level=warn component="scrape manager" scrape_pool=cadvisor target=http://127.0.0.1:9338/metrics msg="Error on ingesting out-of-order samples" num_dropped=151
Mar 16 08:50:23 23768[1679944]: ts=2022-03-16T07:50:23.518Z caller=scrape.go:1564 level=warn component="scrape manager" scrape_pool=cadvisor target=http://127.0.0.1:9338/metrics msg="Error on ingesting out-of-order samples" num_dropped=56
Mar 16 08:50:38 23768[1679944]: ts=2022-03-16T07:50:38.514Z caller=scrape.go:1564 level=warn component="scrape manager" scrape_pool=cadvisor target=http://127.0.0.1:9338/metrics msg="Error on ingesting out-of-order samples" num_dropped=52
Mar 16 08:50:53 23768[1679944]: ts=2022-03-16T07:50:53.512Z caller=scrape.go:1564 level=warn component="scrape manager" scrape_pool=cadvisor target=http://127.0.0.1:9338/metrics msg="Error on ingesting out-of-order samples" num_dropped=58
```
* ROMOTE SIDE:
```
ts=2022-03-16T05:51:51.968Z caller=write_handler.go:103 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"envoy_cluster_lb_subsets_removed\", datacenter=\"gic-seli\", env=\"staging\", envoy_cluster_name=\"cluster_cortex_query_frontend_http\", hostalias=\"frontend-110\", instance=\"23768:8097\", job=\"cos-envoy-public-8097\", service=\"cos\"}" timestamp=1647409911800
ts=2022-03-16T05:51:51.972Z caller=write_handler.go:103 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"envoy_cluster_outlier_detection_ejections_detected_success_rate\", datacenter=\"gic-seli\", env=\"staging\", envoy_cluster_name=\"cluster_jaeger_query_http\", hostalias=\"frontend-110\", instance=\"23768:8097\", job=\"cos-envoy-public-8097\", service=\"cos\"}" timestamp=1647409911800
ts=2022-03-16T05:51:52.557Z caller=write_handler.go:103 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"net_conntrack_dialer_conn_failed_total\", datacenter=\"gic-seli\", dialer_name=\"http_probe\", env=\"staging\", hostalias=\"frontend-110\", instance=\"23768:9997\", job=\"blackbox_exporter\", reason=\"unknown\", service=\"cos\"}" timestamp=1647409912516
ts=2022-03-16T05:51:53.521Z caller=write_handler.go:103 level=error component=web msg="Out of order sample from remote write" err="out of order sample" series="{__name__=\"container_blkio_device_usage_total\", datacenter=\"gic-seli\", device=\"/dev/dm-0\", env=\"staging\", hostalias=\"frontend-110\", id=\"/system.slice/cos-ebpf-exporter.service\", instance=\"23768:9338\", job=\"cadvisor\", major=\"253\", minor=\"0\", operation=\"Async\", service=\"cos\"}" timestamp=1647409893734
ts=2022-03-16T05:51:57.581Z caller=write_handler.go:103 level=error component=web msg="Out of order sample from remote write" err="out of order sample" series="{__name__=\"container_network_tcp6_usage_total\", datacenter=\"gic-seli\", env=\"staging\", hostalias=\"frontend-110\", id=\"/system.slice/cos-blackbox-exporter.service\", instance=\"23768:9338\", job=\"cadvisor\", service=\"cos\", tcp_state=\"close\"}" timestamp=1647409904926
```
