### ISSUE TITLE
azure_sd_configs causes throttling limit on the Azure subscription

### ISSUE THREAD

**Issue by mbakish** [prometheus/prometheus#10474]
**What did you do?**

I tired to use the azure_sd_configs to monitor VMs dynamically with the following configuration: 

```
      - job_name: 'xxx-exporter'
        azure_sd_configs:
          - subscription_id: xxx
            tenant_id: xxx
            client_id: xxx
            client_secret: xxx
            refresh_interval: 15s
            port: 8404
        relabel_configs:
          - source_labels: [ __meta_azure_machine_tag_xxx ]
            regex: true.*
            action: keep
          - source_labels: [ __meta_azure_machine_name ]
            target_label: instance
          - source_labels: [ __meta_azure_machine_private_ip ]
            regex: (.+)
            replacement: ${1}:8404
            target_label: __address__
```

**What did you expect to see?**

Monitoring the VMs without impact on Azure 

**What did you see instead? Under which circumstances?**

I was able to monitor but  had throttling issues in my Azure subscription caused by prometheus (I reached the throttling limit despite having a subscription with high limit)
If I calculate correctly 4*60*6 in six hours I should have seen 1440. However we got to over 600k requests. 
For now I stoped using this feature because it prevents me from doing other actions on the subscription 

**Environment**

* AKS 1.19
* Prometheus version: 2.33.3
