### ISSUE TITLE
Prometheus query_range is slow

### ISSUE THREAD

**Issue by zjutkz** [prometheus/prometheus#10505]
**What did you do?**
I am requesting Prometheus's `query_range` interface between 15 seconds and 25 seconds every minute, and the number of requests is about 200,000 to 300,000 every minute.

**What did you expect to see?**
Prometheus can return data smoothly. 

**What did you see instead? Under which circumstances?**
The interface of Prometheus sometimes returns data very slowly

**Environment**
Here is the yaml file of my Prometheus:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '29'
    meta.helm.sh/release-name: sunfire-prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: '2021-10-27T06:36:49Z'
  generation: 29
  labels:
    app: sunfire-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: sunfire-prometheus-0.1.0
    group: group1
    heritage: Helm
    release: sunfire-prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sunfire-prometheus
      group: group1
      release: sunfire-prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9090'
        prometheus.io/scheme: http
        prometheus.io/scrape: 'true'
      labels:
        app: sunfire-prometheus
        chart: sunfire-prometheus-0.1.0
        group: group1
        heritage: Helm
        release: sunfire-prometheus
    spec:
      containers:
        - args:
            - '--config.file=/etc/config/prometheus.yaml'
            - '--storage.tsdb.path=/prometheus-data'
            - '--web.enable-lifecycle'
            - '--storage.tsdb.retention.time=5m'
            - '--storage.tsdb.max-block-duration=5m'
            - '--storage.tsdb.min-block-duration=5m'
            - '--storage.tsdb.retention.size=2GB'
            - '--query.max-concurrency=4000'
            - '--web.max-connections=40000'
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PORT
              value: '9090'
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: GROUP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: 'metadata.labels[''group'']'
            - name: IDC
              value: center-idc
            - name: ROLE
              value: prometheus
            - name: HEALTH_CHECK_URL
              value: 'http://localhost:9090/-/healthy'
            - name: BRAIN_HB_URL
              value: 'http://sunfire-brain:28123/heartbeat'
          image: >-
            xxxxxx
          imagePullPolicy: Always
          name: sunfire-prometheus-group1
          ports:
            - containerPort: 9090
              protocol: TCP
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 17
            successThreshold: 8
            timeoutSeconds: 15
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
            - mountPath: /prometheus-data
              name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      volumes:
        - configMap:
            defaultMode: 420
            name: sunfire-prometheus-group1
          name: config-volume
        - emptyDir: {}
          name: storage-volume
```

* System information:

	
![image](https://user-images.githubusercontent.com/9446934/160815023-b40a1adf-9f50-40a4-8cc0-edb302ca8738.png)

* Prometheus version:

	![image](https://user-images.githubusercontent.com/9446934/160814948-96dc47bd-d551-446a-b571-5d571f6182ee.png)

* Alertmanager version:

	----

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  query_log_file: /prometheus/query.log
scrape_configs:
- job_name: pushgateway
  honor_labels: true
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_namespace]
    action: keep
    regex: default
  - source_labels: [__meta_kubernetes_pod_label_group]
    action: keep
    regex: group1
  - action: labeldrop
    regex: pushgateway
  - action: labeldrop
    regex: siteName  
```

* Alertmanager configuration file:
```
----
```

* Logs:
Here are some typical query logs:
```
{"error":"query was canceled in expression evaluation","httpRequest":{"clientIP":"172.17.0.42","method":"GET","path":"/api/v1/query_range"},"params":{"end":"2022-03-30T09:35:59.000Z","query":"jvm_threads_current{appName=\"sunfire-selfmonitor-reduce.url4625\", }","start":"2022-03-30T09:35:00.000Z","step":60},"stats":{"timings":{"evalTotalTime":5.672762408,"resultSortTime":0,"queryPreparationTime":5.464064693,"innerEvalTime":0,"execQueueTime":0.000004868,"execTotalTime":5.995925647}},"ts":"2022-03-30T09:35:22.686Z"}


{"error":"query was canceled in expression evaluation","httpRequest":{"clientIP":"172.17.0.126","method":"GET","path":"/api/v1/query_range"},"params":{"end":"2022-03-30T09:38:59.000Z","query":"jvm_memory_pool_bytes_max{appName=\"sunfire-selfmonitor-reduce.url1927\", pool=~\"Code Cache\"}","start":"2022-03-30T09:38:00.000Z","step":60},"stats":{"timings":{"evalTotalTime":3.5984797520000003,"resultSortTime":0,"queryPreparationTime":2.605931976,"innerEvalTime":0,"execQueueTime":0.911022524,"execTotalTime":5.196457487}},"ts":"2022-03-30T09:38:25.080Z"}


{"error":"query was canceled in expression evaluation","httpRequest":{"clientIP":"172.17.0.126","method":"GET","path":"/api/v1/query_range"},"params":{"end":"2022-03-30T09:38:59.000Z","query":"jvm_buffer_pool_used_bytes{appName=\"sunfire-selfmonitor-reduce.url132\", pool=~\"mapped\"} / jvm_buffer_pool_capacity_bytes{appName=\"sunfire-selfmonitor-reduce.url132\", pool=~\"mapped\"}","start":"2022-03-30T09:38:00.000Z","step":60},"stats":{"timings":{"evalTotalTime":3.5998245989999997,"resultSortTime":0,"queryPreparationTime":2.607460066,"innerEvalTime":0,"execQueueTime":0.910834909,"execTotalTime":5.20090463}},"ts":"2022-03-30T09:38:25.081Z"}

```

I get the CPU time of the program through pprof:

![profile001(1)](https://user-images.githubusercontent.com/9446934/160821010-51db8110-7efd-4032-a952-a75cc171c71b.png)
