### ISSUE TITLE
PV nodeAffinity conflict with Pods - AzureDisk persistent volume claim

### ISSUE THREAD

**Issue by uvaisibrahim** [prometheus/prometheus#10508]
**What did you do?**

I deployed prometheus statefulset in self managed kubernetes cluster(Not AKS) in Azure. The storage was configured as persistent volume claim. The storage class for PVC is given below.

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk-premium-zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_ZRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```

Statefulset got deployed successfully. But the pods are in pending state and never got scheduled to the nodes.

**What did you expect to see?**

The pods should get scheduled to nodes and start running.

**What did you see instead? Under which circumstances?**

The pods are continuing in pending state. On analysis understood that, whenever PVC is created in Azure as per the storage class the PVs are also created with nodeAffinity with certain labels given below.

```
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - westus2-1
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - westus2-2
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - westus2-3
      - matchExpressions:
        - key: topology.disk.csi.azure.com/zone
          operator: In
          values:
          - ""
 ```
As per my understanding, the pods are going to pending state because, the nodes dont have the above labels and hence when the pods scheduled to the nodes they never get the PV to mount.

When describing the pending pods getting the below messages.

```
Warning  FailedScheduling  <unknown>        0/9 nodes are available: 1 node(s) had taint {dedicated: storage}, that the pod didn't tolerate, 2 node(s) had taint {dedicated: telemetry}, that the pod didn't tolerate, 3 node(s) didn't match Pod's node affinity, 3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
```

_Please note the taint - toleration is working without any issues._

* Prometheus version: 2.25.2
