### ISSUE TITLE
OpenTelemetry looks not work with grpc and insecure.

### ISSUE THREAD

**Issue by vsxen** [prometheus/prometheus#10542]
prometheus-2.34.0
otelcol version 0.48.0

* Prometheus configuration file:
```
# prom 
tracing:
  endpoint: localhost:4317
  client_type: grpc
  insecure: true
  sampling_fraction: 1
```

* otel configuration file:
```
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: "localhost:14250"
    tls:
      insecure: true

  logging:
    loglevel: debug

service:
  pipelines:
    traces/1:
      receivers: [otlp]
      exporters: [jaeger]
```

* Logs:
```
ts=2022-04-06T07:19:20.113Z caller=tracing.go:64 level=error msg="OpenTelemetry handler returned an error" err="max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: first record does not look like a TLS handshake""
```

* otel log

```
2022-04-06T15:17:35.078+0800 warn zapgrpc/zapgrpc.go:191 [core] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: "\x16\x03\x01\x01\t\x01\x00\x01\x05\x03\x03P\xc7ǅSV\x95)\x15HXe\x96"" {"grpc_log": true}
2022-04-06T15:18:05.082+0800 warn zapgrpc/zapgrpc.go:191 [core] grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams received bogus greeting from client: "\x16\x03\x01\x01\t\x01\x00\x01\x05\x03\x03\xe3\x1a\x04\x15Lݤ\xb8\xd0\nw)\xf0"" {"grpc_log": true}
```
