### ISSUE TITLE
[Kubernetes] Namespace metadata added to scraped pods pre-ingestion

### ISSUE THREAD

**Issue by Whyeasy** [prometheus/prometheus#10567]
## Proposal
**Use case. Why is this important?**

I would like to be able to add namespace label values as a value to all scraped pods pre-ingestion. We have multiple teams in a single cluster where they control what gets deployed to their namespaces but we generate the namespaces for them. In this case we add some unique identifiers on the namespace so we know which team owns which namespace.

Now we would like at this identifier to all scraped pods pre-ingestion. I know this could be achieved with `kube-state-metrics` and some joins. But we rather have it at ingestion point so teams don't need to make an advanced query to get only metrics from their apps across namespaces.

**Comment by roidelapluie** [comment]
This sounds like you want target relabeling:

```
  kubernetes_sd_configs:
    relabel_configs:
      - target_label: namespace
        source_labels: __meta_kubernetes_namespace
```
