### ISSUE TITLE
Getting CPU spikes on 2.19.3

### ISSUE THREAD

**Issue by ayush-san** [prometheus/prometheus#10645]
### What did you do?

We are seeing CPU spikes and slow query execution when we load via grafana dashboards. Till now we were only using it for monitoring via grafana alerts. 

![image](https://user-images.githubusercontent.com/57655135/166132081-a3c6363c-20ea-4144-9a82-05d46a093655.png)

According to newrelic, memory is about 70-80% free

### What did you expect to see?

CPU spikes shouldn't happen

### What did you see instead? Under which circumstances?

Even with a single query, I am seeing CPU spikes. I am running it in docker on an m5.xlarge EC2 machine.

The series which I am querying have high cardinality, they are among the highest cardinality series ingested

I am attaching screenshots of the benchmark dashboard
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/57655135/166132267-30f0b347-238b-4586-a914-e690e1963511.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/57655135/166132271-1935adea-97f2-4079-8b4c-203f553cd437.png">

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/57655135/166132286-43ef5018-5d7e-4a32-8a3f-1087f413ab17.png">

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/57655135/166132292-05d3dd61-cdb3-4f55-87a5-57ae8f100e8f.png">

### System information

Linux 4.9.0-8-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6
```

### Prometheus configuration file

```yaml
#global config
global:
  scrape_interval:     5m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'telegraf'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['telegraf:9273']

  - job_name: 'monitoring-metric-collector'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    scrape_interval: 15s
    static_configs:
    - targets: ['monitoring-metrics-collector:8001']

  - job_name: 'aggregated-metric-collector'
    scrape_interval: 15s
    static_configs:
    - targets: ['aggregated-metrics-collector:8001']

  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']

remote_write:
  - url: http://remote_write:9090/api/v1/write
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
```

### Logs

```
level=info ts=2022-04-30T05:45:56.110Z caller=head.go:645 component=tsdb msg="Replaying WAL and on-disk memory mappable chunks if any, this may take a while"
level=info ts=2022-04-30T05:45:57.793Z caller=head.go:682 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2022-04-30T05:45:58.287Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=7731 maxSegment=7734
level=info ts=2022-04-30T05:45:58.816Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=7732 maxSegment=7734
level=info ts=2022-04-30T05:45:59.134Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=7733 maxSegment=7734
level=info ts=2022-04-30T05:45:59.134Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=7734 maxSegment=7734
level=info ts=2022-04-30T05:45:59.134Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=3.023948227s
level=info ts=2022-04-30T05:45:59.827Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
level=info ts=2022-04-30T05:45:59.827Z caller=main.go:695 msg="TSDB started"
level=info ts=2022-04-30T05:45:59.827Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2022-04-30T05:45:59.828Z caller=dedupe.go:112 component=remote level=info remote_name=94c0c2 url=http://172.31.118.81:9090/api/v1/write msg="Starting WAL watcher" queue=94c0c2
ts=2022-04-30T05:45:59.828Z caller=dedupe.go:112 component=remote level=info remote_name=94c0c2 url=http://172.31.118.81:9090/api/v1/write msg="Replaying WAL" queue=94c0c2
level=info ts=2022-04-30T05:45:59.828Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2022-04-30T05:45:59.828Z caller=main.go:646 msg="Server is ready to receive web requests."
ts=2022-04-30T05:46:12.053Z caller=dedupe.go:112 component=remote level=info remote_name=94c0c2 url=http://172.31.118.81:9090/api/v1/write msg="Done replaying WAL" duration=12.225549766s
level=info ts=2022-04-30T07:00:16.322Z caller=compact.go:495 component=tsdb msg="write block" mint=1651291200000 maxt=1651298400000 ulid=01G1WMA56ZD0Y0C05N98JM6PCV duration=4.195571528s
level=info ts=2022-04-30T07:00:17.197Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=266.076165ms
level=info ts=2022-04-30T07:00:18.521Z caller=head.go:869 component=tsdb msg="WAL checkpoint complete" first=7731 last=7732 duration=1.309271398s
level=info ts=2022-04-30T09:00:18.946Z caller=compact.go:495 component=tsdb msg="write block" mint=1651298400000 maxt=1651305600000 ulid=01G1WV5WFD14B9BCCM46XBW7D1 duration=6.805652591s
level=info ts=2022-04-30T09:00:20.018Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=426.295034ms
level=info ts=2022-04-30T09:00:25.553Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1651276800000 maxt=1651298400000 ulid=01G1WV64RTF42B2SGZ3A2FN91D sources="[01G1W6JPKA9APSGP9Q0FV7N1P9 01G1WDEDW5NKDTSZWF6A8TFAZJ 01G1WMA56ZD0Y0C05N98JM6PCV]" duration=4.918738151s
level=info ts=2022-04-30T09:00:40.631Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1651233600000 maxt=1651298400000 ulid=01G1WV6APY9GBMQWHH3NHFM20M sources="[01G1VHZQ609TNAV9WPVWPKCHDY 01G1W6JR66184W42MGR2BGHF7Z 01G1WV64RTF42B2SGZ3A2FN91D]" duration=13.913392203s
```
