### ISSUE TITLE
Error corrupt blocks "Invalid magic number: 0"

### ISSUE THREAD

**Issue by Nafalgar** [prometheus/prometheus#10679]
### What did you do?

Set up Prometheus in our AKS cluster using the kube-prometheus-stack, persisting using Azure File Shares (azurefile-csi PVC). 

Also using Thanos, Blackbox Exporter (however the error occured already prior to adding these two).

### What did you expect to see?

A prometheus instance that keeps doing just fine persisting data without invalid magic number 0 / corrupt blocks.

### What did you see instead? Under which circumstances?

After a while of running just fine (data gets persisted just fine), several errors occur about invalid block size and invalid magic number (cf. logs below).
The error keeps coming every minute, spamming the logs with the rules/corrupt blocks.
The issue can be 'fixed' by deleting the WAL and the block mentioned in the failing rules, however it returns after a while with a new corrupt block.

### System information

Linux 5.4.0-1074-azure x86_64

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Prometheus configuration file
The Helm chart default values (found here: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml) overridden with the following:

```yaml
prometheus:
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
    interval: 5s
  prometheusSpec:
    resources:
      requests:
        memory: 8Gi
    thanos:
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
    # Add Blackbox Exporter to check endpoints
    additionalScrapeConfigs:
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        # Add URLs as target parameter
        - targets:
          - <some target>
          - <some target>
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]    
        target_label: target
        # Ensure blackbox-exporter is reachable from Prometheus
      - target_label: __address__ 
        replacement: blackbox-exporter-prometheus-blackbox-exporter.monitoring:9115
    containers:
    - name: prometheus
      startupProbe: 
        timeoutSeconds: 30
        periodSeconds: 30
        successThreshold: 1
        failureThreshold: 10
      readinessProbe:
        timeoutSeconds: 30
        periodSeconds: 30
        failureThreshold: 10
    scrapeInterval: 30s
    retention: 14d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: azurefile-csi
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 100Gi
  serviceMonitor:
    interval: 30s
# Disable scheduling pods on virtual master node
prometheus-node-exporter:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: NotIn
            values:
            - "virtual-kubelet"

prometheusOperator:
  thanosImage:
    repository: quay.io/thanos/thanos
    version: v0.23.0
    tag: v0.23.0
```

### Alertmanager version
Possibly irrelevant:

```text
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```

### Logs

```text
ts=2022-05-11T08:50:04.590Z caller=compact.go:519 level=info component=tsdb msg="write block" mint=1652205600028 maxt=1652212800000 ulid=01G2S4Z39EAFZ6P8MCPG5775WK duration=4.992473716s
ts=2022-05-11T08:50:04.982Z caller=db.go:829 level=error component=tsdb msg="compaction failed" err="compact head: reloadBlocks blocks: corrupted block 01G2S4Z39EAFZ6P8MCPG5775WK: invalid magic number 0"
ts=2022-05-11T08:50:07.949Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=0 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[1d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[1d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[1d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:07.980Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=4 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[3d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[3d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[3d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:08.012Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=7 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:08.031Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=11 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:37.949Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=0 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[1d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[1d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[1d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:37.982Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=4 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[3d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[3d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[3d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:38.016Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=7 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:50:38.038Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=11 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:51:07.949Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=0 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[1d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[1d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[1d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[1d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:51:07.980Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=4 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\n  - ((sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.1\",scope=~\"resource|\",verb=~\"LIST|GET\"}[3d]))\n  or vector(0)) + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"0.5\",scope=\"namespace\",verb=~\"LIST|GET\"}[3d]))\n  + sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"5\",scope=\"cluster\",verb=~\"LIST|GET\"}[3d]))))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"LIST|GET\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"LIST|GET\"}[3d]))\nlabels:\n  verb: read\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:51:08.015Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate1d index=7 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate1d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[1d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:51:08.037Z caller=manager.go:636 level=warn component="rule manager" file=/etc/prometheus/rules/prometheus-prometheus-kube-prometheus-prometheus-rulefiles-0/monitoring-prometheus-kube-prometheus-kube-apiserver.rules-08368523-965d-43db-a603-0146aaa27202.yaml group=kube-apiserver.rules name=apiserver_request:burnrate3d index=11 msg="Evaluating rule failed" rule="record: apiserver_request:burnrate3d\nexpr: ((sum by(cluster) (rate(apiserver_request_duration_seconds_count{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\n  - sum by(cluster) (rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\",le=\"1\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  + sum by(cluster) (rate(apiserver_request_total{code=~\"5..\",job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d])))\n  / sum by(cluster) (rate(apiserver_request_total{job=\"apiserver\",verb=~\"POST|PUT|PATCH|DELETE\"}[3d]))\nlabels:\n  verb: write\n" err="expanding series: block: 01G2QQQTZJKBDH5776X03MX0B6: decode postings: invalid size"
ts=2022-05-11T08:51:10.237Z caller=compact.go:519 level=info component=tsdb msg="write block" mint=1652205600028 maxt=1652212800000 ulid=01G2S5134QT6T18MCT3680SNVH duration=5.254367615s
ts=2022-05-11T08:51:10.768Z caller=db.go:829 level=error component=tsdb msg="compaction failed" err="compact head: reloadBlocks blocks: corrupted block 01G2S5134QT6T18MCT3680SNVH: invalid magic number 0"
```
