### ISSUE TITLE
Prometheus Discovering Services with Consul: tls:Bad Certificate

### ISSUE THREAD

**Issue by sazonau** [prometheus/prometheus#10685]
### What did you do?

I want to make use of Consul with Prometheus. 

NodeExporter services running on several hosts are registered in the Consul Services.
I want to run Prometheus that will connect to Consul to discover the NodeExporter services.

Prometheus is running in Docker.

### What did you expect to see?

Connection to Consul is successful. 
Prometheus discover the NodeExporter services which can be seen from the Prometheus UI.

### What did you see instead? Under which circumstances?

Prometheus is not able to access Consul Services: **tls:Bad Certificate**

`caller=consul.go:513 level=error component="discovery manager scrape" discovery=consul msg="Error refreshing service" service=NodeExporter tags= err="Get \"https://consul.service.dc1.consul:8500/v1/health/service/NodeExporter?dc=dc1&stale=&wait=120000ms\": remote error: tls: bad certificate"`

At the same time when running the same manually with **curl** from the same Docker container with the same certificates: 

`curl -v -s -X GET "https://consul.service.dc1.consul:8500/v1/health/service/NodeExporter?dc=dc1&stale=&wait=120000ms" --key /secrets/consul.key --cert /secrets/consul.pem --cacert /secrets/cachain.pem`

I am able to get an expected output:

`[{"Node":{"ID":"e53188ef-16ec-xxxx-xxxx-xxxx","Node":"dc1-runner-dev-1.test.io","Address":"30.10.xx.xx","Datacenter":"dc1","TaggedAddresses":{"lan":"30.10.xx.xx","lan_ipv4":"30.10.xx.xx","wan":"30.10.xx.xx","wan_ipv4":"30.10.xx.xx"},"Meta":{"consul-network-segment":""},"CreateIndex":71388,"ModifyIndex":71391},"Service":{"ID":"dc1-runner-dev-1.test.io-NodeExporter","Service":"NodeExporter","Tags":["service=node_exporter","environment=dev","datacenter=dc1"]...`

What am I missing? Why it is working with **curl** but not with Prometheus?

### Prometheus version

```text
prometheus, version 2.31.1 (branch: master, revision: AlpineLinux)
  build user:       buildozer@build-3-15-x86_64
  build date:       20220415-06:40:44
  go version:       go1.17.9
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: "node_exporter"

    consul_sd_configs:
      - server: "consul.service.dc1.consul:8500"
        scheme: "https"
        datacenter: "dc1"
        services: [
          "NodeExporter"]

        tls_config:

          ca_file:   "/secrets/cachain.pem"
          cert_file: "/secrets/consul.pem"
          key_file:  "/secrets/consul.key"
```

### Logs

```text
ts=2022-05-11T15:45:25.824Z caller=main.go:406 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2022-05-11T15:45:25.825Z caller=main.go:444 level=info msg="Starting Prometheus" version="(version=2.31.1, branch=master, revision=AlpineLinux)"
ts=2022-05-11T15:45:25.826Z caller=main.go:449 level=info build_context="(go=go1.17.9, user=buildozer@build-3-15-x86_64, date=20220415-06:40:44)"
ts=2022-05-11T15:45:25.826Z caller=main.go:450 level=info host_details="(Linux 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64 f88c4ab48c19 (none))"
ts=2022-05-11T15:45:25.826Z caller=main.go:451 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2022-05-11T15:45:25.826Z caller=main.go:452 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2022-05-11T15:45:25.833Z caller=web.go:542 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2022-05-11T15:45:25.835Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2022-05-11T15:45:25.834Z caller=main.go:839 level=info msg="Starting TSDB ..."
ts=2022-05-11T15:45:25.842Z caller=head.go:479 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2022-05-11T15:45:25.842Z caller=head.go:513 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.28µs
ts=2022-05-11T15:45:25.842Z caller=head.go:519 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2022-05-11T15:45:25.843Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=6
ts=2022-05-11T15:45:25.846Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=6
ts=2022-05-11T15:45:25.849Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=6
ts=2022-05-11T15:45:25.850Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=6
ts=2022-05-11T15:45:25.851Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=6
ts=2022-05-11T15:45:25.852Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=5 maxSegment=6
ts=2022-05-11T15:45:25.853Z caller=head.go:590 level=info component=tsdb msg="WAL segment loaded" segment=6 maxSegment=6
ts=2022-05-11T15:45:25.853Z caller=head.go:596 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=195.193µs wal_replay_duration=10.979033ms total_replay_duration=11.207947ms
ts=2022-05-11T15:45:25.856Z caller=main.go:866 level=info fs_type=794c7630
ts=2022-05-11T15:45:25.856Z caller=main.go:869 level=info msg="TSDB started"
ts=2022-05-11T15:45:25.856Z caller=main.go:996 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2022-05-11T15:45:25.857Z caller=main.go:1033 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=1.329671ms db_storage=1.26µs remote_storage=1.8µs web_handler=530ns query_engine=1.27µs scrape=279.125µs scrape_sd=403.006µs notify=30.84µs notify_sd=19.441µs rules=1.73µs
ts=2022-05-11T15:45:25.857Z caller=main.go:811 level=info msg="Server is ready to receive web requests."
ts=2022-05-11T15:45:25.921Z caller=consul.go:513 level=error component="discovery manager scrape" discovery=consul msg="Error refreshing service" service=NodeExporter tags= err="Get \"https://consul.service.brain.consul:8500/v1/health/service/NodeExporter?dc=brain&stale=&wait=120000ms\": remote error: tls: bad certificate"
ts=2022-05-11T15:45:55.888Z caller=consul.go:513 level=error component="discovery manager scrape" discovery=consul msg="Error refreshing service" service=NodeExporter tags= err="Get \"https://consul.service.brain.consul:8500/v1/health/service/NodeExporter?dc=brain&stale=&wait=120000ms\": remote error: tls: bad certificate"
```
