### ISSUE TITLE
Configure __scrape_interval__ and __scrape_timeout__ through relabel don't seems to work

### ISSUE THREAD

**Issue by xenofree** [prometheus/prometheus#10691]
### What did you do?

I configure scrape_interval and timeout with consul_sd through relabel

```
      - source_labels: [__meta_consul_service_metadata_prometheus_scrape_interval]
        regex: '(.+)'
        target_label: __scrape_interval__

      - source_labels: [__meta_consul_service_metadata_prometheus_scrape_timeout]
        regex: '(.+)'
        target_label: __scrape_timeout__
```

### What did you expect to see?

Expect to have a 10s scrape_interval when i set `prometheus_scrape_interval: 10s` in consul

### What did you see instead? Under which circumstances?

Default scrape_interval and timeout is used

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: 'consul_sd'
    consul_sd_configs:
    - server: 'http://x.x.x.x:8500'
      refresh_interval: 10s
      tags:
      - 'prometheus_exporter'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

      - source_labels: [__meta_consul_service_metadata_prometheus_scrape_timeout]
        regex: '(.+)'
        target_label: __scrape_timeout__

      - source_labels: [__meta_consul_service_metadata_prometheus_scrape_interval]
        regex: '(.+)'
        target_label: __scrape_interval__
```
