### ISSUE TITLE
prometheus can not send firing alert to alertmanager

### ISSUE THREAD

**Issue by huangda2100** [prometheus/prometheus#10701]
### What did you do?

context: everytime when the system upgrades successfully, the system will generate 2 events: "server upgrade successfully" and "server upgrade report". Prometheus can pull the 2 events metric when they happen, and i can see the 2 metrics data in prometheus console, both of the metric data are just a point on the graph

### What did you expect to see?

i expect to see prometheus could send "server upgrade successfully" alert and "server upgrade report" alert to alertmanager

### What did you see instead? Under which circumstances?

what i see is prometheus only sends "server upgrade report" alert to alertmanager. i also can see "server upgrade successfully" alert has firing state on prometheus console, but "server upgrade successfully" is not sent to alertmanager.
since "server upgrade report" and "server upgrade successfully" are same type, even their config are same structure, I am really confused that why only  "server upgrade report" is sent to alertmanager. 

### System information

Linux 4.15.0-173-generic x86_64

### Prometheus version

```text
prometheus, version 2.30.0 (branch: HEAD, revision: 37468d88dce85ac507f3fb7864c7d1c078e3e27d)
  build user:       root@e913c65aa170
  build date:       20210914-09:49:24
  go version:       go1.17.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

// alerting rules
groups:
  - name: server_upgrade_succeed_rule_group
    rules:
      - alert: server_upgrade_succeed_rule_alert
        expr: SERVICE_UPGRADE_SUCCESS == 1
        for: 0s
        annotations:
          level: "info"
          category: "app_event"
          rule_id: "server_upgrade_succeed_rule"
          component_id: ""
          summary: "server upgrade successfully"
          description: "some desc"


groups:
  - name: server_upgrade_report_rule_group
    rules:
      - alert: server_upgrade_report_rule_alert
        expr: SERVICE_UPGRADE_REPORT == 1
        for: 0s
        annotations:
          level: "info"
          category: "app_event"
          rule_id: "server_upgrade_report_rule"
          component_id: ""
          summary: "server upgrade report"
          description: "some desc"

rule_files:
  - "/root/prom_rules/*_rules.yml"

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
```

### Alertmanager version

```text
alertmanager, version 0.23.0 (branch: HEAD, revision: 61046b17771a57cfd4c4a51be370ab930a4d7d54)
  build user:       root@e21a959be8d2
  build date:       20210825-10:48:55
  go version:       go1.16.7
  platform:         linux/amd64
```

### Alertmanager configuration file

```yaml
route:
  group_by: [ 'alertname', "controller_name" ]
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 87600h
  receiver: 'web.hook'
 - matchers:
    - alertname="server_upgrade_report_rule_alert"
    continue: true
    group_by:
    - alertname
    - controller_name
    - details
   - matchers:
    - alertname="server_upgrade_succeed_rule_alert"
    continue: true
    group_by:
    - alertname
    - controller_name
    - details
```
