### ISSUE TITLE
Failed to list *v1beta1.Ingress: the server could not find the requested resource

### ISSUE THREAD

**Issue by ispy1** [prometheus/prometheus#10711]
### What did you do?

Prometheus scrape k8s ingress metrics show this error  

> level=error ts=2022-05-18T13:29:59.322Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: the server could not find the requested resource"

k8s version
![1652880842(1)](https://user-images.githubusercontent.com/43496359/169051468-7b46ba67-6e76-4aa0-bf5f-53ab436e4018.jpg)

### What did you see instead? Under which circumstances?

when i use cluster-admin as  ClusterRole

> level=error ts=2022-05-18T13:29:59.322Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: the server could not find the requested resource"
clusterrolebinding
![image](https://user-images.githubusercontent.com/43496359/169052936-1ff9a91e-c151-4351-b942-ee537eefb23b.png)
sa
![image](https://user-images.githubusercontent.com/43496359/169054646-1a947a5d-c40d-44b3-866e-c29101ffcf25.png)

![image](https://user-images.githubusercontent.com/43496359/169053407-f6862450-4c80-4fb8-859d-ae3a3bc85c35.png)
![image](https://user-images.githubusercontent.com/43496359/169060399-bcbecedf-ef03-4e92-b8c9-dba3c43a3969.png)

if i use this prometheus as ClusterRole 
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-mon
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  - networking.k8s.io/v1
  resources:
    - ingresses
    - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-mon
```
it will be 
log
![image](https://user-images.githubusercontent.com/43496359/169057606-5722203f-09aa-4c80-9c3b-13bfc6f0b52b.png)
ClusterRole
![image](https://user-images.githubusercontent.com/43496359/169058074-680d4a23-cb12-4aff-ad8a-0212731e0bbd.png)

### System information

Linux 5.4.186-1.el7.elrepo.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.20.0 (branch: HEAD, revision: e5a06b483527d4fe0704b8fa3a2b475b661c526f)
  build user:       root@ac954b6d5c6e
  build date:       20200722-18:51:45
  go version:       go1.14.6
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 15s
rule_files: 
- /etc/prometheus/rule.yaml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.kube-mon:9093']
scrape_configs:
- job_name: 'kubernetes-ingresses'
  metrics_path: /probe
  params:
    module: [http_2xx]
  kubernetes_sd_configs:
  - role: ingress
```

### Logs

```text
log(ClusterRole:cluster-admin)
level=error ts=2022-05-18T13:30:03.040Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: the server could not find the requested resource"
level=error ts=2022-05-18T13:30:08.848Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth 

log(ClusterRole:prometheus)
level=error ts=2022-05-18T13:54:38.054Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:429: Failed to list *v1beta1.Ingress: ingresses.networking.k8s.io is forbidden: User \"system:serviceaccount:kube-mon:prometheus\" cannot list resource \"ingresses\" in API group \"networking.k8s.io\" at the cluster scope"
```
