### ISSUE TITLE
VMware exporter error

### ISSUE THREAD

**Issue by PierreNa** [prometheus/prometheus#10717]
### What did you do?

Hello team, I need some helps because it's impossible for me to scrape my vcenter and I don't understood.

my vmware config.yml :
```
default:
  vsphere_host: "fr-vcenter-vdi-01"
  vsphere_user: "administrator@vsphere.local"
  vsphere_password: "XXXXXXX"
  ignore_ssl: True
  specs_size: 5000
  fetch_custom_attributes: False
  fetch_tags: False
  fetch_alarms: True
  collect_only:
    vms: True
    vmguests: True
    datastores: True
    hosts: True
    snapshots: True
```
Pip list :

```
root@fs01m00prom01:~# pip3 list
Package           Version
----------------- --------------
attrs             21.4.0
Automat           20.2.0
certifi           2020.6.20
cffi              1.15.0
chardet           4.0.0
constantly        15.1.0
cryptography      37.0.2
httplib2          0.18.1
hyperlink         21.0.0
idna              2.10
incremental       21.3.0
pip               20.3.4
prometheus-client 0.0.19
pyasn1            0.4.8
pyasn1-modules    0.2.8
pycparser         2.21
pycurl            7.43.0.6
PySimpleSOAP      1.16.2
python-apt        2.2.1
python-debian     0.1.39
python-debianbts  3.1.0
pytz              2022.1
pyvmomi           7.0.3
PyYAML            6.0
reportbug         7.10.3+deb11u1
requests          2.25.1
service-identity  21.1.0
setuptools        52.0.0
six               1.16.0
Twisted           22.4.0
typing-extensions 4.2.0
urllib3           1.26.5
vmware-exporter   0.18.3
wheel             0.34.2
yamlconfig        0.3.1
zope.interface    5.4.0
```

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/32876811/169345705-3069d12b-2bc4-45ce-9ee2-927449be0bbf.png">

### What did you see instead? Under which circumstances?

Need to collect my vsphere info

### System information

Linux 5.10.0-13-amd64 x86_64

### Prometheus version

```text
root@fs01m00prom01:~# prometheus --version
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: "vcenter"
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 60s
    static_configs:
      - targets:
        - 'fr-vcenter-vdi-01.akawan.corp'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9272
```
