### ISSUE TITLE
Regex for remote_write does not work

### ISSUE THREAD

**Issue by beelesnik** [prometheus/prometheus#10751]
### What did you do?

I use prometheus v2.35.0 and remote_write mechanism to push metrics to the Newrelic.
One specific group of metrics has such remote-write configuration (changed some fields ):
```
      - url: someurl
        name: groupname
        bearerToken: mybearertoken
        writeRelabelConfigs:
          - sourceLabels: ['__name__']
            regex: ^metric_.*
            action: keep
```
and pushed to Newrelic any metric like: metric_1, metric_2, metric_11, metric_3 and so on.
It is too wide for me and I applied new config to get more strict set of metrics.
```
      - url: someurl
        name: groupname
        bearerToken: mybearertoken
        writeRelabelConfigs:
          - sourceLabels: ['__name__']
            regex: ^metric_1.*
            action: keep
```
I've applied new configuration but the set of metrics pushed to newrelic did not changed.
Looking in the prometheus config I see that my new regexp is in place and according to the logs new configuration file was applied.

### What did you expect to see?

Working new regexp for remote-write. In my case I expected to see that only metrics like metric_1,  metric_11 are pushed to Newrelic

### What did you see instead? Under which circumstances?

The set of pushed metrics are the same for different regexps.

### System information

Linux 5.4.0-1077-azure x86_64

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

**Comment by beelesnik** [comment]
I can say more.
If i create remote-write config for specific metrics group with fully incorrect mask, like:
```
      - url: someurl
        name: groupname
        bearerToken: mybearertoken
        writeRelabelConfigs:
          - sourceLabels: ['__name__']
            regex: tralalalala*
            action: keep
```
nothing happened after applying this config. The metrics starting with  metric_ still are pushed to Newrelic.

And final attempt to remove all remote_write configuration from prometheus finished with very strange result: all metrics are gone except specific metrics groups that are not affected by changing its regex parameter.
