### ISSUE TITLE
Kubernetes service discovery continues to scrape metrics from the IP of pods in an Error state

### ISSUE THREAD

**Issue by lwithers** [prometheus/prometheus#10755]
### What did you do?

We have configured Prometheus with Kubernetes service discovery. We have a job named `kubernetes-pods` which uses the `pod` role for service discovery.

We had a pod named `ibv-instructions-svc-111-4gvk8` running with pod IP `100.99.29.17` exposing metrics on port 8009 under the path `/metrics`. This pod failed (due to excess memory usage), and went into the `Error` state:

```
$ k get po -o wide
NAME                                  READY   STATUS    RESTARTS         AGE     IP                NODE   NOMINATED NODE   READINESS GATES
[…]
ibv-instructions-svc-111-4gvk8        0/1     Error     0                42h     100.99.29.17      kn5    <none>           <none>
ibv-instructions-svc-111-58gs5        1/1     Running   3 (22h ago)      42h     100.97.22.212     kn3    <none>           <none>
ibv-instructions-svc-111-7d28m        1/1     Running   0                42h     100.97.52.60      kn4    <none>           <none>
ibv-instructions-svc-111-ctwvv        1/1     Running   0                22h     100.112.31.6      kn2    <none>           <none>
```

After some time, this pod IP was re-used by another pod `admin-checks-3-p45lk` (actually in a different namespace, though that is not relevant for the ticket):

```
$ k get po -o wide --namespace admin
NAME                              READY   STATUS    RESTARTS   AGE   IP               NODE   NOMINATED NODE   READINESS GATES
[…]
admin-checks-3-m2mnr              1/1     Running   0          64m   100.97.96.24     kn7    <none>           <none>
admin-checks-3-p45lk              1/1     Running   0          64m   100.99.29.17     kn5    <none>           <none>
admin-checks-3-qpmg4              1/1     Running   0          65m   100.97.23.24     kn3    <none>           <none>
```

This new pod also exposes metrics on port 8009, under the same path `/metrics`.

### What did you expect to see?

We expected to no longer see any metrics from the pod `ibv-instructions-svc-111-4gvk8`, once it had entered an Error state. We did not expect to see it in the Targets view of the prometheus agent that is scraping it. 

### What did you see instead? Under which circumstances?

Metrics emitted by the new pod `admin-checks-3-p45lk` are visible, but a _copy_ of those metrics labelled as though they come from the old pod `ibv-instructions-svc-111-4gvk8` are also visible.

With our relabelling config (attached below) we see otherwise-duplicate metrics with the following labels:
- `{cluster_loc="stg1", instance="100.99.29.17:8009", job="kubernetes-pods", kubernetes_cluster="app-clusterx1.stg-ld5.gbr", kubernetes_namespace="docs", kubernetes_pod_name="ibv-instructions-svc-111-4gvk8", monitor="kubernetes", serviceName="ibv-instructions-svc"}`
- `{cluster_loc="stg1", instance="100.99.29.17:8009", job="kubernetes-pods", kubernetes_cluster="app-clusterx1.stg-ld5.gbr", kubernetes_namespace="admin", kubernetes_pod_name="admin-checks-3-p45lk", monitor="kubernetes", serviceName="admin-checks"}`

### System information

Kubernetes 1.22.5

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'kubernetes'
    cluster_loc: "{{cluster_loc}}"
    kubernetes_cluster: "{{cluster_name}}"

remote_write: [] # elided for brevity

scrape_configs:
# several elided for brevity

#
# Scrape from Kubernetes pods
#
- job_name: 'kubernetes-pods'
  label_limit: 100
  label_name_length_limit: 100
  label_value_length_limit: 2000

  # ask k8s for a list of pods
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  # Pod scraping config comes from annotations on the pod.
  #  • `prometheus.io/scrape`: Only scrape pods that have a value of `true`
  #  • `prometheus.io/path`: If the metrics path is not `/metrics` override this.
  #  • `prometheus.io/port`: If the metrics are exposed on a different port to the
  #    pod then set this appropriately.
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2

  # Add pod name and namespaces labels to the time series.
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name

  # Connect team used the "serviceName" label in some dashboards; keep it in case
  # it's useful elsewhere.
  - source_labels: [__meta_kubernetes_pod_label_serviceName]
    action: replace
    target_label: serviceName
```

**Comment by lwithers** [comment]
Please note: I don't believe this is necessarily a duplicate of #10257, because that is using the `endpoints` role and not the `pods` role.

As far as I can see, #10257 is being caused by the Endpoints object retaining a reference to the old pod IP, whereas this issue is because Prometheus is not considering the fact that the pod has exited (state `Error`) before it decides to scrape, and it just so happens to pick up some other unrelated pod that has since come along on the same virtual IP.

**Comment by lwithers** [comment]
I've captured the YAML for the pod, in case it's useful to see how to extract the status: [pod.yaml.gz](https://github.com/prometheus/prometheus/files/8780317/pod.yaml.gz)

**Comment by dgl** [comment]
The underlying reason here is actually very similar to #10257, pods are kept around after termination; this is dependent on kube-controller-manager GC flags and the amount of pod churn in the environment.

As mentioned in https://github.com/prometheus/prometheus/issues/10257#issuecomment-1046784527 for endpoints the desired behaviour can depend on the environment. Pods are similar to endpoints in this respect and there is a meta label available to relabel on ` __meta_kubernetes_pod_phase`.

A relabel like:

```yaml
- source_labels: [__meta_kubernetes_pod_phase]
  action: drop
  regexp: Failed|Succeeded
```

Would fix this (the pod yaml you provided -- thanks! -- shows `phase: Failed` for this case). It probably would make sense to suggest this in the Kubernetes example config.

**Comment by lwithers** [comment]
Thank you for the response.

I agree that it would be sensible to provide this in the example config, as we did use that as the starting basis for our own config. But it is rather surprising that we need to explicitly filter out pods in this status (I believe that it is only in Kubernetes v1.22 onwards that pods that have exited retain their original `IP` field value in the `Status` section — in earlier releases, the pod objects still existed but they had no `IP` value).

I have added the following `relabel_configs` entry to the job:

```yaml
  # Only scrape pods that are in the Running phase.
  #  https://github.com/prometheus/prometheus/issues/10755#issuecomment-1139248161
  #  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podstatus-v1-core
  #    Pending — not all containers running yet. Pod may not even be scheduled yet.
  #    Running — all containers created and at least one still running.
  #    Succeeded — all containers exited with status=0, pod will not restart.
  #    Failed — one or more containers exited with status≠0, pod will not restart.
  #    Unknown — we lost contact with the host's kubelet. We have seen this persist for
  #              days after a node machine dies.
  - source_labels: [__meta_kubernetes_pod_phase]
    action: keep
    regex: Running
```

I chose to only keep pods in the `Running` phase — each of the other phases I have observed to overlap with cases where I know metrics scraping would fail and I'd rather not have the error messages / metrics from Prometheus in this case. However, perhaps others may evaluate the trade-offs differently.

I've verified this on the cluster where we still have the same status as in the bug report and it does indeed just drop the one target that was being scraped erroneously.
