### ISSUE TITLE
Unable to start web listener

### ISSUE THREAD

**Issue by vmfrt** [prometheus/prometheus#10774]
### What did you do?

Run **prometheus** (Window version) by Command Line . It don't run successfully and give error "Unable to start Web Listener".

```
C:\Users\MyUser\Downloads\**prometheus-2.35.0.windows-amd64**>**prometheus.exe**
ts=2022-05-30T12:28:58.111Z caller=main.go:488 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2022-05-30T12:28:58.111Z caller=main.go:525 level=info msg="Starting Prometheus" version="(version=2.35.0, branch=HEAD, revision=6656cd29fe6ac92bab91ecec0fe162ef0f187654)"
ts=2022-05-30T12:28:58.112Z caller=main.go:530 level=info build_context="(go=go1.18.1, user=root@xxxxxx, date=20220421-09:49:03)"
ts=2022-05-30T12:28:58.112Z caller=main.go:531 level=info host_details=(windows)
ts=2022-05-30T12:28:58.113Z caller=main.go:532 level=info fd_limits=N/A
ts=2022-05-30T12:28:58.114Z caller=main.go:533 level=info vm_limits=N/A
ts=2022-05-30T12:28:58.116Z caller=web.go:541 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2022-05-30T12:28:58.118Z caller=main.go:775 **level=error msg="Unable to start web listener" err="listen tcp 0.0.0.0:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."**
```

### What did you expect to see?

It should run and Chia exporter (https://github.com/Chia-Network/chia-exporter) data should be fetch.

### What did you see instead? Under which circumstances?

ts=2022-05-30T12:28:58.118Z caller=main.go:775 **level=error msg="Unable to start web listener" err="listen tcp 0.0.0.0:9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted

### System information

windows 10

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@c512990b8858
  build date:       20220421-09:49:03
  go version:       go1.18.1
  platform:         windows/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```

### Alertmanager configuration file

```yaml
Not Used
```

### Logs

```text
has been Pasted at above
```
