### ISSUE TITLE
Remote write sigv4 authentication is not working

### ISSUE THREAD

**Issue by Alexhha** [prometheus/prometheus#10825]
### What did you do?

We use the following config with prometheus
```
remote_write:
  - url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-938...d3d/api/v1/remote_write
    sigv4:
      region: eu-west-1
```
It works fine until we have to explicitly enable IMDSv2 support. 

### What did you see instead? Under which circumstances?

After we enabled IMDSv2 support - prometheus fail to start with the error
```
ts=2022-06-06T16:22:34.776Z caller=main.go:1154 level=error msg="Failed to apply configuration" err="could not get SigV4 credentials: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

### System information

Linux 5.4.0-1075-aws x86_64

### Prometheus version

```text
prometheus, version 2.36.0 (branch: HEAD, revision: d48f381d9a4e68c83283ce5233844807dfdc5ba5)
  build user:       root@b3126bd1c115
  build date:       20220530-13:56:56
  go version:       go1.18.2
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  -
    url: https://aps-workspaces.eu-west-1.amazonaws.com/workspaces/ws-938...d3d/api/v1/remote_write
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    sigv4:
      region: eu-west-1
scrape_configs:
  - job_name: mothership
    static_configs:
    - targets: [ec2-18...13.compute-1.amazonaws.com:9100]
      labels:
        instance: pdn-mothership
        node_public_dns: ec2-18...13.compute-1.amazonaws.com
```

### Logs

```text
ts=2022-06-08T08:24:27.296Z caller=main.go:1112 level=error err="error loading config from \"/etc/prometheus/prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/prometheus.yml\")"
ts=2022-06-08T08:24:31.082Z caller=main.go:491 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2022-06-08T08:24:31.082Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.36.0, branch=HEAD, revision=d48f381d9a4e68c83283ce5233844807dfdc5ba5)"
ts=2022-06-08T08:24:31.082Z caller=main.go:540 level=info build_context="(go=go1.18.2, user=root@b3126bd1c115, date=20220530-13:56:56)"
ts=2022-06-08T08:24:31.082Z caller=main.go:541 level=info host_details="(Linux 5.4.0-1075-aws #80~18.04.1-Ubuntu SMP Mon May 23 20:32:04 UTC 2022 x86_64 87b301b58be2 (none))"
ts=2022-06-08T08:24:31.082Z caller=main.go:542 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2022-06-08T08:24:31.082Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2022-06-08T08:24:31.168Z caller=web.go:553 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2022-06-08T08:24:31.170Z caller=main.go:972 level=info msg="Starting TSDB ..."
ts=2022-06-08T08:24:31.171Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
ts=2022-06-08T08:24:31.173Z caller=head.go:493 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2022-06-08T08:24:31.173Z caller=head.go:536 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=5.021µs
ts=2022-06-08T08:24:31.173Z caller=head.go:542 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2022-06-08T08:24:31.173Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=6
ts=2022-06-08T08:24:31.176Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=1 maxSegment=6
ts=2022-06-08T08:24:31.177Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=2 maxSegment=6
ts=2022-06-08T08:24:31.179Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=3 maxSegment=6
ts=2022-06-08T08:24:31.179Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=4 maxSegment=6
ts=2022-06-08T08:24:31.180Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=5 maxSegment=6
ts=2022-06-08T08:24:31.180Z caller=head.go:613 level=info component=tsdb msg="WAL segment loaded" segment=6 maxSegment=6
ts=2022-06-08T08:24:31.180Z caller=head.go:619 level=info component=tsdb msg="WAL replay completed" checkpoint_replay_duration=43.316µs wal_replay_duration=6.74569ms total_replay_duration=6.811623ms
ts=2022-06-08T08:24:31.182Z caller=main.go:993 level=info fs_type=EXT4_SUPER_MAGIC
ts=2022-06-08T08:24:31.182Z caller=main.go:996 level=info msg="TSDB started"
ts=2022-06-08T08:24:31.182Z caller=main.go:1177 level=info msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
ts=2022-06-08T08:24:34.338Z caller=main.go:1203 level=error msg="Failed to apply configuration" err="could not get SigV4 credentials: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
ts=2022-06-08T08:24:34.339Z caller=main.go:831 level=info msg="Stopping scrape discovery manager..."
ts=2022-06-08T08:24:34.339Z caller=main.go:845 level=info msg="Stopping notify discovery manager..."
ts=2022-06-08T08:24:34.339Z caller=manager.go:951 level=info component="rule manager" msg="Stopping rule manager..."
ts=2022-06-08T08:24:34.339Z caller=manager.go:961 level=info component="rule manager" msg="Rule manager stopped"
ts=2022-06-08T08:24:34.339Z caller=main.go:882 level=info msg="Stopping scrape manager..."
ts=2022-06-08T08:24:34.339Z caller=main.go:841 level=info msg="Notify discovery manager stopped"
ts=2022-06-08T08:24:34.339Z caller=main.go:874 level=info msg="Scrape manager stopped"
ts=2022-06-08T08:24:34.339Z caller=manager.go:937 level=info component="rule manager" msg="Starting rule manager..."
ts=2022-06-08T08:24:34.339Z caller=main.go:827 level=info msg="Scrape discovery manager stopped"
ts=2022-06-08T08:24:34.341Z caller=notifier.go:599 level=info component=notifier msg="Stopping notification manager..."
ts=2022-06-08T08:24:34.341Z caller=main.go:1103 level=info msg="Notifier manager stopped"
ts=2022-06-08T08:24:34.341Z caller=main.go:1112 level=error err="error loading config from \"/etc/prometheus/prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"/etc/prometheus/prometheus.yml\")"
```

**Comment by alexqyle** [comment]
@Alexhha , were you running your prometheus server in container? I can only reproduce this when running prometheus server in container without setting network to host. The reason it failed in container is that request getting IMDSv2 token failed due to
> In a container environment, if the hop limit is 1, the IMDSv2 response does not return because going to the container is considered an additional network hop.

To verify it is the issue, you can try to execute `curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` under the environment prometheus server is running. In my case, the curl command timed out when getting token. Sigv4 code would call the same metadata endpoint to renew token before sending each signed requests.

The way to solve this issue is either using host network for container or set hop limit to 2.

Referrence:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#imds-considerations

**Comment by Alexhha** [comment]
> were you running your prometheus server in container?

correct, I'm using the following docker-compose
```
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.36.0
    container_name: prometheus
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
```

> The way to solve this issue is either using host network for container or set hop limit to 2.

got it, let me try
