### ISSUE TITLE
digitalocean_sd_configs Unable to authenticate you

### ISSUE THREAD

**Issue by rmalenko** [prometheus/prometheus#10856]
### What did you do?

I have got this error in DigitalOcean discovery

```
ts=2022-06-10T08:55:02.897Z caller=refresh.go:79 level=error component="discovery manager scrape" discovery=digitalocean msg="Unable to refresh target groups" err="error while listing droplets page 0: GET https://api.digitalocean.com/v2/droplets: 401 (request \"8c4d699e-65ea-43a4-a17c-15c235953b92\") Unable to authenticate you"
```
But I can get the correct response using this command, so we can expect the key is correct.

`curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer cce5eb9ba587f....." "https://api.digitalocean.com/v2/account"`

In my config, both variants of authentications aren't work

### What did you see instead? Under which circumstances?

```
ts=2022-06-10T08:55:02.897Z caller=refresh.go:79 level=error component="discovery manager scrape" discovery=digitalocean msg="Unable to refresh target groups" err="error while listing droplets page 0: GET https://api.digitalocean.com/v2/droplets: 401 (request \"8c4d699e-65ea-43a4-a17c-15c235953b92\") Unable to authenticate you"
```

### System information

Linux 5.4.0-107-generic x86_64

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@e59c79158868
  build date:       20220609-15:25:21
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  external_labels:
    monitor: digitalsilk
rule_files:
  - /opt/prometheus/etc/rules/redis_exporter_recording_rules.yaml

scrape_configs:

  - job_name: donodeexporter
    scrape_interval: 60s
    scrape_timeout: 15s
    digitalocean_sd_configs:
      - bearer_token: cce5eb9ba587f.....
#      - authorization:
#          credentials: cce5eb9ba587f.....
      - port: 9100
      - refresh_interval: 120s
```

### Logs

```text
ts=2022-06-10T08:55:02.897Z caller=refresh.go:79 level=error component="discovery manager scrape" discovery=digitalocean msg="Unable to refresh target groups" err="error while listing droplets page 0: GET https://api.digitalocean.com/v2/droplets: 401 (request \"8c4d699e-65ea-43a4-a17c-15c235953b92\") Unable to authenticate you"
```

**Comment by roidelapluie** [comment]
Your yaml config is incorrect

```yaml
 - job_name: donodeexporter
  scrape_interval: 60s
  scrape_timeout: 15s
  digitalocean_sd_configs:
    - authorization:
        credentials: cce5eb9ba587f.....
      port: 9100
      refresh_interval: 120s
```

**Comment by rmalenko** [comment]
Thank you.
Now, I have got the new error
```
ts=2022-06-10T09:49:12.612Z caller=scrape.go:1313 level=debug component="scrape manager" scrape_pool=donodeexporter target=http://68.183.59.194:80/metrics msg="Scrape failed" err="Get \"http://68.183.59.194:80/metrics\": context canceled"
```

**Comment by roidelapluie** [comment]
Mmh it's strange, did you add the port?

**Comment by rmalenko** [comment]
Yes, I have added port

```yaml
scrape_configs:

  - job_name: donodeexporter
    scrape_interval: 60s
    scrape_timeout: 15s
    digitalocean_sd_configs:
      - authorization:
          credentials: dop_v1_58f1e93....
        port: 9100
        refresh_interval: 120s
```        
But the target still has 80 port, instead 9100

`ts=2022-06-10T09:53:41.278Z caller=scrape.go:1313 level=debug component="scrape manager" scrape_pool=donodeexporter target=http://167.71.91.47:80/metrics msg="Scrape failed" err="Get \"https://167.71.91.47/metrics\": x509: cannot validate certificate for 167.71.91.47 because it doesn't contain any IP SANs"`

**Comment by rmalenko** [comment]
I have added relabel rules to narrow the number of instances for debugging. But suddenly I started to receive data. :)

```yaml
  - job_name: donodeexporter
    digitalocean_sd_configs:
      - bearer_token: 'dop_v1_58f...'
        port: 9100
    relabel_configs:
      - source_labels: [__meta_digitalocean_tags]
        regex: .*,monitoring_yes,.*
        action: keep
```
