### ISSUE TITLE
Kubernetes selector is not applied to all Discovery

### ISSUE THREAD

**Issue by shadowofs** [prometheus/prometheus#10861]
### What did you do?

To avoid watching all pods, I set up a discovery with pod selector:
```
scrape_configs:
- job_name: 'application-endpoints'
  scheme: http
  kubernetes_sd_configs:
    - role: endpoints
      selectors:
        - role:  pod
          label: bke.prometheus.stack/scrape=true
```
But the memory usage is still growing fast even with no pods selected. And pprof says 90% memory is used by pod watch :
![pprof002](https://user-images.githubusercontent.com/681144/173297558-3ddfebb5-1f21-412b-a91a-8ffd9a47934a.svg)

### What did you expect to see?

endpoint watcher should be started with specified selector

### What did you see instead? Under which circumstances?

The log says two endpoint watchers are started. But only one has selector, the other still watch all pods:
```
ts=2022-06-13T06:01:07.795Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:01:14.068Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector= podStoreSize=634177
ts=2022-06-13T06:01:17.795Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:01:24.085Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector= podStoreSize=633221
```

Log code: 
```
// File: discovery/kubernetes/kubernetes.go
// Run implements the discoverer interface.
func (d *Discovery) Run(ctx context.Context, ch chan<- []*targetgroup.Group) {
	d.Lock()
	namespaces := d.getNamespaces()

	switch d.role {
	case RoleEndpointSlice:...
	case RoleEndpoint:
		for _, namespace := range namespaces {
			e := d.client.CoreV1().Endpoints(namespace)
			elw := &cache.ListWatch{...}
			s := d.client.CoreV1().Services(namespace)
			slw := &cache.ListWatch{...}
			p := d.client.CoreV1().Pods(namespace)
			plw := &cache.ListWatch{...}
			eps := NewEndpoints(
				**log.With(d.logger, "role", "endpoint", "namespace", namespace, "selector", d.selectors.pod.label),**
				cache.NewSharedInformer(slw, &apiv1.Service{}, resyncPeriod),
				cache.NewSharedInformer(elw, &apiv1.Endpoints{}, resyncPeriod),
				cache.NewSharedInformer(plw, &apiv1.Pod{}, resyncPeriod),
			)
			d.discoverers = append(d.discoverers, eps)
			go eps.endpointsInf.Run(ctx.Done())
			go eps.serviceInf.Run(ctx.Done())
			go eps.podInf.Run(ctx.Done())
		}

// File: discovery/kubernetes/endpoints.go
// Run implements the Discoverer interface.
func (e *Endpoints) Run(ctx context.Context, ch chan<- []*targetgroup.Group) {
	defer e.queue.ShutDown()

	if !cache.WaitForCacheSync(ctx.Done(), e.endpointsInf.HasSynced, e.serviceInf.HasSynced, e.podInf.HasSynced) {...}

	go wait.Forever(func() {
		level.Error(e.logger).Log("podStoreSize", len(e.podStore.ListKeys()))
	}, time.Second*10)

	go func() {...}()

	// Block until the target provider is explicitly canceled.
	<-ctx.Done()
}
```

### System information

Darwin 21.3.0 x86_64

### Prometheus version

```text
prometheus, version 2.33.5 (branch: debug, revision: 5f04e7cfeb2f853add828d00996d1fbd8bebb712)
  build user:       root@leafboat-73776310
  build date:       20220610-10:51:33
  go version:       go1.17.8
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
    provider:         control-plane-collector-0
    vdc:              hl
    cluster:          brain
    physical_cluster: brain-hl
remote_write: 
  - url: http://telecaster.byted.org/api/prometheus/align
    write_relabel_configs:
    - action: replace
      replacement: bke.$1
      source_labels:
      - __name__
      target_label: __name__
scrape_configs:
- job_name: 'application-endpoints'
  scheme: http
  kubernetes_sd_configs:
    - role: endpoints
      selectors:
        - role:  pod
          label: bke.prometheus.stack/scrape=true # Avoid watch all pods
  relabel_configs:
    # Only match Service pod name equals with bke.prometheus.stack/port.name specified name
    - source_labels:  [__meta_kubernetes_endpoint_port_name, __meta_kubernetes_service_annotation_bke_prometheus_stack_port_name]
      action:         keep_if_equal
      regex:          (.+);(.+)
    - source_labels:  [__meta_kubernetes_pod_label_bke_prometheus_stack_scrape]
      action:         keep
      regex:          true
    - source_labels:  [__meta_kubernetes_service_annotation_bke_prometheus_stack_path]
      action:         replace
      target_label:   __metrics_path__
      regex:          (.+)
    - source_labels:  [__meta_kubernetes_service_annotation_bke_prometheus_stack_network_mode, __meta_kubernetes_pod_host_ip, __meta_kubernetes_pod_container_host_port]
      action:         replace
      regex:          host;(.*);(\d+)
      replacement:    $1:$2
      target_label:   __address__
    - action:         labelmap
      regex:          __meta_kubernetes_pod_label_(.+)
    - source_labels:  [__meta_kubernetes_namespace]
      action:         replace
      target_label:   namespace
    - source_labels:  [__meta_kubernetes_service_name,__meta_kubernetes_namespace]
      action:         replace
      regex:          (.*);(.*)
      target_label:   job
      replacement:    $1.$2.svc
```

### Logs

```text
ts=2022-06-13T06:00:37.793Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:00:47.794Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:00:54.033Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector= podStoreSize=634846
ts=2022-06-13T06:00:57.795Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:00:58.029Z caller=dedupe.go:112 component=remote level=info remote_name=da9692 url=http://telecaster.byted.org/api/prometheus/align msg="Done replaying WAL" duration=5m20.916768216s
ts=2022-06-13T06:01:04.052Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector= podStoreSize=634872
ts=2022-06-13T06:01:07.113Z caller=dedupe.go:112 component=remote level=info remote_name=da9692 url=http://telecaster.byted.org/api/prometheus/align msg="Remote storage resharding" from=1 to=2
ts=2022-06-13T06:01:07.795Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector="bke.prometheus.stack/scrape=true" podStoreSize=0
ts=2022-06-13T06:01:14.068Z caller=endpoints.go:145 level=error component="discovery manager scrape" discovery=kubernetes role=endpoint namespace= selector= podStoreSize=634177
```
