### ISSUE TITLE
Promtool unit test not deterministic

### ISSUE THREAD

**Issue by aiven-amartin** [prometheus/prometheus#10863]
### What did you do?

I have a promtool unit test file that spans over 7 days. ~ 1/15 runs of the unit test has `exp_alerts` fail to happen, while it appears using `promql_expr_test` that the values are correct. The other ~14/15 runs pass/behave as expected (initially detected by our ci pipeline, reproduced by running `while promtool test rules flaky_tests.yaml; do :; done`.
rules.yaml
```yaml
groups:
- interval: 30s
  name: recording_30s
  rules:
  - record: metric1:rate5m
    expr: (sum by (service_id,service_plan,tenant_id) (sum_over_time(metric1[290s]))) / 300
  - record: metric2:rate5m
    expr: (sum by (service_id,service_plan,tenant_id) (sum_over_time(metric2[290s]))) / 300
- interval: 3m
  name: alerts_3m
  rules:
  - alert: Metric1Critical
    annotations:
      description: Words
      summary: word
    expr: >
      abs(
        metric1:rate5m - on (service_id,tenant_id) avg_over_time(metric1:rate5m[7d:])
      ) / on (service_id,tenant_id) stddev_over_time(metric1:rate5m[7d:])
      > 3
    for: 5m
    labels:
      severity: critical
  - alert: Metric2Critical
    annotations:
      description: Words
      summary: word
    expr: >
      abs(
        metric2:rate5m - on (service_id,tenant_id) avg_over_time(metric2:rate5m[7d:])
      ) / on (service_id,tenant_id) stddev_over_time(metric2:rate5m[7d:])
      > 3
    for: 5m
    labels:
      severity: critical
```
flaky_tests.yaml
```yaml
rule_files:
  - ../rules/nodecom_redacted.yml

evaluation_interval: 5m

tests:
  - interval: 30s
    input_series:
      # 20160=7*24*60*2= 1w of 30s emission
      - series: "metric2{service_id='1', service_plan='service_plan', tenant_id='tenant', host='1'}"
        values: "95x5760 105x5760 100x8640 50+0x60 98x60"
      - series: "metric2{service_id='1', service_plan='service_plan', tenant_id='tenant', host='2'}"
        values: "100x20160 50+0x60 98x60"
      - series: "metric2{service_id='1', service_plan='service_plan', tenant_id='tenant', host='3'}"
        values: "100x20160 50+0x60 98x60"
      - series: "metric1{service_id='1', service_plan='service_plan', tenant_id='tenant', host='10'}"
        values: "6000+0x20160 0x20 6000+0x20"
      - series: "metric1{service_id='1', service_plan='service_plan', tenant_id='tenant', host='11'}"
        values: "6000+0x20160 6000+0x40"

    promql_expr_test:
      - expr: metric2:rate5m
        eval_time: 7d
        exp_samples:
          - labels: "metric2:rate5m{service_id='1', service_plan='service_plan', tenant_id='tenant'}"
            value: 10
      - expr: metric2:rate5m
        eval_time: 7d10m
        exp_samples:
          - labels: "metric2:rate5m{service_id='1', service_plan='service_plan', tenant_id='tenant'}"
            value: 5
      - expr: metric1:rate5m
        eval_time: 7d
        exp_samples:
          - labels: "metric1:rate5m{service_id='1', service_plan='service_plan', tenant_id='tenant'}"
            value: 400
      - expr: metric1:rate5m
        eval_time: 7d5m
        exp_samples:
          - labels: "metric1:rate5m{service_id='1', service_plan='service_plan', tenant_id='tenant'}"
            value: 200

    alert_rule_test:
      - eval_time: 0m
        alertname: Metric2Critical
        exp_alerts:

      - eval_time: 7d5m
        alertname: Metric2Critical
        exp_alerts:

      - eval_time: 7d30m
        alertname: Metric2Critical
        exp_alerts:
          - exp_labels:
              service_id: 1
              severity: critical
              tenant_id: tenant
            exp_annotations:
              description: Words
              summary: word

      - eval_time: 7d45m
        alertname: NodecomMessagesFromKafkaRateCritical
        exp_alerts:

      - eval_time: 0m
        alertname: Metric1Critical
        exp_alerts:

      - eval_time: 7d10m
        alertname: Metric1Critical
        exp_alerts:
          - exp_labels:
              service_id: 1
              severity: critical
              tenant_id: tenant
            exp_annotations:
              description: Words
              summary: word

      - eval_time: 7d20m
        alertname: Metric1Critical
        exp_alerts:

```

### What did you expect to see?

Unit tests always have the same result

### What did you see instead? Under which circumstances?

Exact same rules and unit test fails some percentage of the time. Seems a similar issue happened here: https://github.com/prometheus/prometheus/issues/7699.

### System information

Linux 5.17.7-200.fc35.x86_64 x86_64

### Prometheus version

```text
promtool, version 2.34.0 (branch: v2.34.0, revision: 881111fec4332c33094a6fb2680c71fffc427275)
  build user:       
  build date:       
  go version:       go1.17.8
  platform:         linux/amd64
```
