### ISSUE TITLE
Target endpoint replaced by hostname

### ISSUE THREAD

**Issue by AscarGb** [prometheus/prometheus#10872]
### What did you do?

1. running prometheus .\prometheus --config.file=prometheus.yml
2. running metrics on `http://localhost:9184`

### What did you expect to see?

- The target `http://localhost:9184/metrics` opens from targets page
- Metric works

### What did you see instead? Under which circumstances?

- The target replaced by `http://myhostname:9184/metrics` and it not opening
- Metric not working

If the url is changed to `http://localhost:9184/metrics`, then it opens

### System information

windows 10

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@03a139af4c85
  build date:       20220609-15:19:57
  go version:       go1.18.3
  platform:         windows/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'OpenTelemetryTest'
    scrape_interval: 1s # poll very quickly for a more responsive demo    
    static_configs:
      - targets: ['localhost:9184']
```
