### ISSUE TITLE
Prometheus discovery, discovers wrong target if it has annotations on both pod and service level

### ISSUE THREAD

**Issue by wiardvanrij** [prometheus/prometheus#10871]
### What did you do?

Let's say we have a deployment with a sidecar. We tell, via annotations, that it should scrape on container `foo` on port 9090.
Example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  annotations:
    prometheus.io/port: "9090"
    prometheus.io/scrape: "true"   
    prometheus.io/path: /stats/prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sample
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample
    spec:
      containers:
        - name: foo
          image: foo
          ports:
            - name: http
              containerPort: 9090          
        - name: bar
          image: bar
          ports:
            - name: http-bar
              containerPort: 8080
```

This works fine.

Now we add a service like so:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: sample
  namespace: istio-system
spec:
  ports:
  - name: http-bar
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sample
```

Due to the port, and setting the annotation to scrape this, I _assume_ it only would fetch metrics from our container `bar` 

The (relevant) scrape jobs:

```
  - job_name: 'kubernetes-service-endpoints'

    kubernetes_sd_configs:
      - role: endpoints

    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node
```

and 

```
  - job_name: 'kubernetes-pods'

    kubernetes_sd_configs:
      - role: pod

    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        action: replace
        regex: (https?)
        target_label: __scheme__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
        replacement: __param_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_phase]
        regex: Pending|Succeeded|Failed|Completed
        action: drop
```

### What did you expect to see?

job_name: 'kubernetes-pods' would fetch the `foo` container via port 9090
job_name: 'kubernetes-service-endpoints' would fetch the `bar` container via port 8080

### What did you see instead? Under which circumstances?

job_name: 'kubernetes-pods' fetches the `foo` container via port 9090 ✅ 
job_name: 'kubernetes-service-endpoints' fetch the `bar` container via port 8080 ✅ 
job_name: 'kubernetes-service-endpoints' tries to fetch the `foo` container via port 9090 but fails due to not having metrics there (path is wrong, see our deployment, which has a different path) 🔴  - Also it should not even try to fetch it, as it's not defined in our service to do so (that port is **not** in our service).

### System information

Kubernetes v1.21.5-eks

### Prometheus version

```text
chart: prometheus/prometheus
version: 15.6.0
```
