### ISSUE TITLE
msg="Out of order sample from remote write" err="out of bounds"

### ISSUE THREAD

**Issue by even0306** [prometheus/prometheus#10900]
### What did you do?

I added a monitoring device normally, using telegraf, and before that, there were another 10 telegraf pushing data normally

### What did you expect to see?

This device pushes data normally like the previous 10 devices

### What did you see instead? Under which circumstances?

Telegraf is pushing data normally, but prometheus is reporting an error, as shown in the figure. prometheus is installed inside the docker container, I checked the container time and the time of the telegraf machine, the time and timezone are correct
![image](https://user-images.githubusercontent.com/58162761/174831557-126eb821-d87f-4db9-833c-8c1c280b8757.png)

### System information

bitnami/prometheus docker image Linux 5.10.0-13-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f051ce0d6050
  build date:       20220620-13:21:35
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'n9e'
    file_sd_configs:
    - files:
      - targets.json
```

### Logs

![image](https://user-images.githubusercontent.com/58162761/174831557-126eb821-d87f-4db9-833c-8c1c280b8757.png)
