### ISSUE TITLE
Prometheus fails to start in Docker on M1 chips

### ISSUE THREAD

**Issue by kaylendog** [prometheus/prometheus#10912]
### What did you do?

1. Ran the following in console, as displayed on the Prometheus homepage (without `-d` specified to view output).
```bash
docker run --name prometheus -p 127.0.0.1:9090:9090 prom/prometheus
```

### What did you expect to see?

Prometheus should run as normal on other ARM architectures.

### What did you see instead? Under which circumstances?

Prometeus panics and faults with the following trace:
```
unexpected fault address 0xffff79775000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xffff79775000 pc=0x7c0f0]

goroutine 1 [running]:
runtime.throw({0x29754d7?, 0x1a?})
        /usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x4000a3f0a0 sp=0x4000a3f070 pc=0x48120
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:815 +0xa8 fp=0x4000a3f0d0 sp=0x4000a3f0a0 pc=0x5f468
runtime.memmove()
        /usr/local/go/src/runtime/memmove_arm64.s:86 +0x90 fp=0x4000a3f0e0 sp=0x4000a3f0e0 pc=0x7c0f0
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0xfffff9abbf02, 0xb}, 0x14, {0x32e2bf8, 0x400004d540})
        /app/promql/query_logger.go:123 +0x1b0 fp=0x4000a3f220 sp=0x4000a3f0e0 pc=0x1db4d30
main.main()
        /app/cmd/prometheus/main.go:597 +0x6108 fp=0x4000a3ff70 sp=0x4000a3f220 pc=0x1ed28f8
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x258 fp=0x4000a3ffd0 sp=0x4000a3ff70 pc=0x4a6f8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000a3ffd0 sp=0x4000a3ffd0 pc=0x7b734
```

I have tested the same `linux/arm64` architecture image on a non-Darwin VPS without any issue.

This may be an upstream issue with Go, but since I haven't had any issues with other Go-based software, I am reporting here first.

### System information

Darwin 21.5.0 arm64

### Prometheus version

As reported by `docker run prom/prometheus --version`
```text
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f219ccdc35c6
  build date:       20220620-13:09:09
  go version:       go1.18.3
  platform:         linux/arm64
```

### Prometheus configuration file

No config was specified to the volume mount of the container, so uses the [image default](https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus.yml).

```yaml

# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```

### Logs

```text
ts=2022-06-24T14:42:31.819Z caller=main.go:491 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2022-06-24T14:42:31.819Z caller=main.go:535 level=info msg="Starting Prometheus Server" mode=server version="(version=2.36.2, branch=HEAD, revision=d7e7b8e04b5ecdc1dd153534ba376a622b72741b)"
ts=2022-06-24T14:42:31.819Z caller=main.go:540 level=info build_context="(go=go1.18.3, user=root@f219ccdc35c6, date=20220620-13:09:09)"
ts=2022-06-24T14:42:31.819Z caller=main.go:541 level=info host_details="(Linux 5.10.47-linuxkit #1 SMP PREEMPT Sat Jul 3 21:50:16 UTC 2021 aarch64 46be6c94d498 (none))"
ts=2022-06-24T14:42:31.819Z caller=main.go:542 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2022-06-24T14:42:31.819Z caller=main.go:543 level=info vm_limits="(soft=unlimited, hard=unlimited)"
unexpected fault address 0xffff79775000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xffff79775000 pc=0x7c0f0]

goroutine 1 [running]:
runtime.throw({0x29754d7?, 0x1a?})
        /usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x4000a3f0a0 sp=0x4000a3f070 pc=0x48120
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:815 +0xa8 fp=0x4000a3f0d0 sp=0x4000a3f0a0 pc=0x5f468
runtime.memmove()
        /usr/local/go/src/runtime/memmove_arm64.s:86 +0x90 fp=0x4000a3f0e0 sp=0x4000a3f0e0 pc=0x7c0f0
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0xfffff9abbf02, 0xb}, 0x14, {0x32e2bf8, 0x400004d540})
        /app/promql/query_logger.go:123 +0x1b0 fp=0x4000a3f220 sp=0x4000a3f0e0 pc=0x1db4d30
main.main()
        /app/cmd/prometheus/main.go:597 +0x6108 fp=0x4000a3ff70 sp=0x4000a3f220 pc=0x1ed28f8
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x258 fp=0x4000a3ffd0 sp=0x4000a3ff70 pc=0x4a6f8
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000a3ffd0 sp=0x4000a3ffd0 pc=0x7b734

goroutine 50 [select]:
go.opencensus.io/stats/view.(*worker).start(0x40004d0000)
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x88
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xa8

goroutine 60 [select]:
github.com/prometheus/prometheus/util/logging.(*Deduper).run(0x4000174b00)
        /app/util/logging/dedupe.go:75 +0xb0
created by github.com/prometheus/prometheus/util/logging.Dedupe
        /app/util/logging/dedupe.go:61 +0x124

goroutine 99 [select]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0x40008d0780)
        /app/storage/remote/write.go:107 +0xac
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
        /app/storage/remote/write.go:99 +0x434
```
