### ISSUE TITLE
Memory build up

### ISSUE THREAD

**Issue by langecode** [prometheus/prometheus#10925]
### What did you do?

We are running Prometheus scraping a Kubernetes cluster with a rather high number of metrics. We are very well aware that this requires a hight amount of memory. However, what we see is that over a period say 10 hours there is a build up in memory consumption even if the retention is only set to 6 hours. What startles us a bit is that the memory consumption increases even long after retention should kick in. See the below graph. We have verified that retention is set on command line as expected.

![image](https://user-images.githubusercontent.com/5438266/176135214-ff544461-80ab-4f56-b158-b673be14d5fd.png)

### What did you expect to see?

We expected to see memory consumption stabilize after 6 hours and a bit.

### What did you see instead? Under which circumstances?

Memory consumption keeps increasing until we reach the limit.

### System information

Linux 5.4.0-109-generic x86_64

### Prometheus version

```text
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f051ce0d6050
  build date:       20220620-13:21:35
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster: prod3
    cluster_id: netic_prod3
    cluster_type: dedicated
    prometheus: netic-observability-system/oaas-observability
    prometheus_cluster: prod3/netic-oaas-prometheus
    prometheus_replica: prometheus-oaas-observability-0
    provider: netic
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
rule_files:
- /etc/prometheus/rules/prometheus-oaas-observability-rulefiles-0/*.yaml
scrape_configs:
...
remote_write:
- url: https://ingest.observability.netic.dk/api/prom/push
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [cluster_id, namespace]
    separator: _
    regex: (.*)
    target_label: namespace_id
    replacement: $1
    action: replace
  tls_config:
    ca_file: /etc/prometheus/secrets/netic-client-certificate/ca.crt
    cert_file: /etc/prometheus/secrets/netic-client-certificate/tls.crt
    key_file: /etc/prometheus/secrets/netic-client-certificate/tls.key
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  queue_config:
    capacity: 2500
    max_shards: 5
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500
```
