### ISSUE TITLE
Amount of data points returned by subquery depends on the query timestamp

### ISSUE THREAD

**Issue by r2k1** [prometheus/prometheus#10928]
### What did you do?

 ```
count_over_time(vector(0)[10s:1s])
```

### What did you expect to see?

I would expect to see consistent results regardless of the query timestamp.

### What did you see instead? Under which circumstances?

If I run the query in the Prometheus UI I see `10` as a result.
If I change the query evaluation time to a value finished at exact second (with no millisecond information) the result will be `11`.

I discovered the issue when tests using promtool showed a different result to what I observe in the UI.

### Prometheus version

```text
2.34.0
```

**Comment by r2k1** [comment]
Test for proomtool:
```yaml
tests:
  - interval: 1s
    input_series:
      - series: metric
        values: 0+1x60
    promql_expr_test:
      - expr: count_over_time(metric[10s:1s])
        eval_time: 10s
        exp_samples:
          - labels: ""
            value: 11
  - interval: 1s
    input_series:
      - series: metric
        values: 0+1x60
    promql_expr_test:
      - expr: count_over_time(metric[10s:1s])
        eval_time: 10s1ms
        exp_samples:
          - labels: ""
            value: 11
```

Result
```
Unit Testing:  test.yaml
  FAILED:
    expr: "count_over_time(metric[10s:1s])", time: 10s1ms,
        exp: {} 1.1E+01
        got: {} 1E+01
```

**Comment by dgl** [comment]
More minimal PromQL test case, pointing out this is just on the query side:

```yaml
tests:
  - promql_expr_test:
      - expr: count_over_time(vector(0)[1h:1m])
        eval_time: 1h
        exp_samples:
          - labels: ""
            value: 61
      - expr: count_over_time(vector(0)[1h:1m])
        eval_time: 1h1ms
        exp_samples:
          - labels: ""
            value: 60 # not 61
```

I think this is a manifestation of https://www.robustperception.io/promql-subqueries-and-alignment/ -- essentially subqueries are aligned in a way that's usually invisible to the user, but it's there as a performance optimisation. I'm not sure there's much we can do about this, PromQL unit tests by their nature expose some aspects of Prometheus's internals that would otherwise be well hidden...
