### ISSUE TITLE
prometheus lose some data points when prometheus collects kubelet cadvisor metrics

### ISSUE THREAD

**Issue by tb21434718** [prometheus/prometheus#10947]
### What did you do?

prometheus v2.36.2 lose some data points on collecting kubelet/cadvisor metrics when the auto-scaling controller querys data from the prometheus v2.36.2 and i start to create pods from 500 to 1000 pods

![image](https://user-images.githubusercontent.com/18215923/176842926-b90709f0-fedc-4179-8d5f-572019f18b98.png)
this problem will lead my auto-scaling controller can not query any data at some point in time

the up is normal,but the container_memory_working_set_bytes metric lose a data point 
![image](https://user-images.githubusercontent.com/18215923/176843185-0e00da4a-074c-41c0-89f3-655514b3cec4.png)
![image](https://user-images.githubusercontent.com/18215923/176843421-5c06498c-84b2-4cd1-851f-94bb998a4caf.png)
the scrap duuartion increased tenfold
![image](https://user-images.githubusercontent.com/18215923/176843512-a9089305-937b-4cf5-8f2a-eced79b0a5ad.png)

the cpu and memory  of prometheus is low 
![image](https://user-images.githubusercontent.com/18215923/176843481-8985d0d1-b054-46d5-bc7e-bc625b1323da.png)
![Uploading image.png…]()

### What did you expect to see?

i want to know what the problem is 
i can not get any useful info from prometheus and kubelet logs 

### What did you see instead? Under which circumstances?

i hope the prometheus does not lose the data point in this low cpu and memory
or i can know why this situations  occur from some logs 

### System information

Linux  4.18.0-147.5.1.6.h686.

### Prometheus version

```text
prometheus --version 2.36.2
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: dev-cluster
    prometheus: ers-manager/auto-scaling
    prometheus_replica: prometheus-autoscaling-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
rule_files:
- /etc/prometheus/rules/prometheus-auto-scaling-rulefiles-0/*.yaml
scrape_configs:
- job_name: serviceMonitor/ers-manager/kubelet/0
  honor_labels: true
  honor_timestamps: false
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics/cadvisor
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: kubelet
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: https-metrics
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Node;(.*)
    target_label: node
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
    separator: ;
    regex: Pod;(.*)
    target_label: pod
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: ${1}
    action: replace
  - source_labels: [__meta_kubernetes_service_label_k8s_app]
    separator: ;
    regex: (.+)
    target_label: job
    replacement: ${1}
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: https-metrics
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (container_(cpu_usage_seconds_total|memory_rss|memory_working_set_bytes))
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - ers-manager
```
