### ISSUE TITLE
Dynamic Relabel of Label Names

### ISSUE THREAD

**Issue by nikgrok** [prometheus/prometheus#1099]
Hey guys,

I seem to be having issues dynamically relabeling the the label name based on regex. I'm not sure if this was meant to be supported, but I hope we can works something out.

Example

```yaml
- source_labels: ['__meta_consul_tags']
      regex: 'SomeRegex'
      target_label:  '$1'
      replacement:   '$2'
```

Basically, we would like to give users the ability to put in a consul tag that we can transform into a label. 
Consul Tag: lbl-httpport-8080
Preferred Output: httpport="8080"
