### ISSUE TITLE
Why there are no alerts fired in this situation?

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [prometheus/prometheus#10990]
### What did you do?

I have some metrics named with `responseTime_.*`
The alert rule is 
```
groups:
- name: automatic_flow_control
  rules:
  - alert: automatic_flow_control
    expr: deriv(label_replace({__name__=~"responseTime_.*"}, "metricname", "$1", "__name__", "(.*)")[30s:1s])>0.1
    for: 1m
    labels:
      serverity: warn
      annotations:
      summary: gateway limitation alert has invoked
      value: "value= {{ $value }}"
```
and the alert is well reload in the prometheus:
![image](https://user-images.githubusercontent.com/58684828/177489646-aa527777-c20a-417d-96bc-8bfe1ee4375e.png)

By clicking the `expr` it redirect to the graph page and showing the result graph.
Although graph shows there is at least one metric which has time intervals greater than 1m for sure (see the green line)
![image](https://user-images.githubusercontent.com/58684828/177489579-f7abb1db-4930-421c-85c9-c1e05694ba2e.png)

The alert rule is always pending and refreshing its `Active Since` but never fire at all, which makes the `for 1m` situation never reached. No debug log showing in both prometheus's log or alertmanager's log.

### What did you expect to see?

Prometheus fire an alert

### What did you see instead? Under which circumstances?

my test case describe can be seen in [StackOverFlow](https://stackoverflow.com/questions/72878762/how-to-perform-a-proper-query-with-promql-to-get-an-increasing-rate-in-prometheu)

### System information

windows 10 for test client and centos 7 for prometheus server

### Prometheus version

```text
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f051ce0d6050
  build date:       20220620-13:21:35
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 192.168.24.201:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules/gateway_flow_automatic_rule.yml"
scrape_configs:
  - job_name: "webgateway"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.23.131:8004","192.168.24.201:8005","192.168.24.200:8005"]
      #- targets: ["192.168.23.131:8004"]
  - job_name: "machine_actuator"
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["192.168.23.131:13000"]
```
