### ISSUE TITLE
ExternalLabels should error or drop empty values

### ISSUE THREAD

**Issue by bboreham** [prometheus/prometheus#11024]
### What did you do?

Run `./prometheus --config.file ./documentation/examples/prometheus.yml`
with this addition to the config:
```
   evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
   # scrape_timeout is set to the global default (10s).
+  external_labels:
+    blank:
 
 # Alertmanager configuration
```

### What did you expect to see?

An warning and/or no `external_labels`.

This would be in line with the [docs](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels), which say:

> A label with an empty label value is considered equivalent to a label that does not exist.

### What did you see instead? Under which circumstances?

Prometheus reports this at `/config`:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    blank: ""
```

Worse, there is even a test to ensure it works:
https://github.com/prometheus/prometheus/blob/97d7e09e0b639efd3f9d69197df26e6b608e671c/config/config_test.go#L1668

### System information

Linux 5.4.0-72-generic x86_64

### Prometheus version

```text
prometheus, version 2.37.0-rc.0 (branch: main, revision: 1ba2bbc5fe6af8a0af8f8f489505fef2770701ea)
  build user:       vagrant@vagrant
  build date:       20220714-16:23:07
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  external_labels:
    blank:

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```
