### ISSUE TITLE
can not config altermanager with ‘https‘ mode

### ISSUE THREAD

**Issue by tangsun0** [prometheus/prometheus#11021]
### What did you do?

First I runned a altermanager  in 'http' . The prometheus can push alter to altermanager,and it can push to my another business.
Then I runned a  altermanager with 'https' mode. Made a prometheus config file and set the  scheme in altermanagers to 'https'  

### What did you expect to see?

I think the prometheus will push alter as I setted in http mode. 

### What did you see instead? Under which circumstances?

The promethues show errors.Just like  notifier.go:527  component=nodifier altermanager="http://localhost:9093/api/v2/alters" count=1 msg="Error send alter" err="bad response status 400 Bad Request"

### Prometheus version

```text
version 2.29.0-rc.2  linux amd64
```

### Prometheus configuration file

```yaml
altering:
   alertmanagers:
     - scheme: https
     - tls_config: 
         insecure_skip_verify: true
     static_configs: 
         - targets: [localhost:9093]
```

### Alertmanager version

```text
version v0.22.2 linux amd64
```

**Comment by roidelapluie** [comment]
Please use
```
alerting:
   alertmanagers:
     - scheme: https
       tls_config: 
         insecure_skip_verify: true
       static_configs: 
         - targets: [localhost:9093]
```

You have to many `-`, which makes them multiple alertmanager configs.
