### ISSUE TITLE
biz timestamp  not instead of promethus timestamps

### ISSUE THREAD

**Issue by foreverpersistence** [prometheus/prometheus#11031]
### What did you do?

step1:  create  my export with java client， 
output.  metrics with my timestamps

step2: config prometheus.yml .add job

step3.run  export and prometheus
step4. check export result  and. premetheus /api/v1/query result

### What did you expect to see?

1、exporter  result
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/47444541/179392113-425688f4-6a0c-40af-9291-b8a627df0337.png">

2、but promethues query /api/v1/query
<img width="671" alt="image" src="https://user-images.githubusercontent.com/47444541/179392169-3123237b-30cc-468a-b438-54b8b11bcbd1.png">

promethues not use my timestamps

### What did you see instead? Under which circumstances?

query /api/v1/query.  prometheus not use my timestamp .
<img width="671" alt="image" src="https://user-images.githubusercontent.com/47444541/179392203-dd6c60cd-e720-4310-9cde-067e7ea0ed49.png">

### System information

Darwin 20.3.0 x86_64

### Prometheus version

```text
prometheus version	2.37.0 / 2.36.2
Revision	b41e0750abf5cc18d8233161560731de05199330
Branch	HEAD
BuildUser	root@04e08efba15f
BuildDate	20220714-15:13:17
GoVersion	go1.18.4
```

### Prometheus configuration file

```yaml
global:
  # 采集间隔
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  # 计算报警和预聚合 间隔
  evaluation_interval: 10s

  # 采集超时 时间
  scrape_timeout: 10s


scrape_configs:
  

  - job_name: "myexportor"
    # honor_labels: true
    # honor_timestamps: false
    static_configs:
         # export address
      - targets: ['192.168.31.45:8082']
        labels:
          instance: exportor
```
