### ISSUE TITLE
_meta_dockerswarm_node_address is 0.0.0.0 in swarm leader

### ISSUE THREAD

**Issue by ahronhelfenstein** [prometheus/prometheus#11060]
### What did you do?

I configured the following to fetch the node information for all nodes. 
```
  - job_name: 'docker-exporter'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: __address__
        replacement: $1:9323
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__meta_dockerswarm_task_id]
        target_label: swarm_task_id
      - source_labels: [job]
        regex: "([^_]+)_.*"
        target_label: swarm_stack
      - source_labels: [job]
        regex: "[^_]+_(.*)"
        target_label: swarm_service
```

### What did you expect to see?

I have three nodes in my swarm stack and when fetching the node information, the leader has the _meta_dockerswarm_node_address as 0.0.0.0 and the other two nodes have the vm IP.  I'd like to have the real IP instead of 0.0.0.0. 

### What did you see instead? Under which circumstances?

Below a screenshot of my current data. 
![image](https://user-images.githubusercontent.com/6034925/180734596-08b44370-edf1-402f-b4f9-151fde692a8d.png)

### System information

Ubuntu 18.04.6 LTS

### Prometheus version

```text
prometheus, version 2.36.2 (branch: HEAD, revision: d7e7b8e04b5ecdc1dd153534ba376a622b72741b)
  build user:       root@f051ce0d6050
  build date:       20220620-13:21:35
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     60s  # Set the scrape interval. Default is every 1 minute.
  evaluation_interval: 60s  # Evaluate rules. The default is every 1 minute.
  scrape_timeout:      10s  # default 10s

scrape_configs:
   - job_name: 'docker-exporter'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: __address__
        replacement: $1:9323
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
      - source_labels: [__meta_dockerswarm_task_id]
        target_label: swarm_task_id
      - source_labels: [job]
        regex: "([^_]+)_.*"
        target_label: swarm_stack
      - source_labels: [job]
        regex: "[^_]+_(.*)"
        target_label: swarm_service
```

**Comment by hhromic** [comment]
We are also affected by this. Unfortunately, this is a long-standing known issue in Docker itself: https://github.com/moby/moby/issues/35437

A good summary explanation is in here: https://github.com/moby/moby/issues/35437#issuecomment-504104947

This bug has also been observed in other software such as:
* Portainer: https://github.com/portainer/portainer/issues/1127
* SwarmPit: https://github.com/swarmpit/swarmpit/issues/476
* Ansible: https://github.com/ansible/ansible/pull/53058

Two of the above have solved it locally with a rather simple workaound:
* SwarmPit: https://github.com/swarmpit/swarmpit/commit/38ffbe08e717d8620bf433c99f2e85a9e5984c32
* Ansible: https://github.com/ansible/ansible/pull/53930

Which looks [something like this](https://github.com/moby/moby/issues/35437#issuecomment-504134692):
```go
var node swarm.Node = ... // retrive info
var nodeIP string
if node.ManagerStatus != nil {
	nodeIP = strings.SplitN(node.ManagerStatus.Addr, ":", 2)[0]
} else {
	nodeIP = node.Status.Addr
}
```

If the Prometheus maintainers are okay with such a workaround, I could make a PR for Prometheus.

**Comment by hhromic** [comment]
As an alternative to modifying Prometheus, is to get the address from the `__meta_dockerswarm_node_manager_address` label when `__meta_dockerswarm_node_address` is `0.0.0.0` via relabelling (as shown in your screenshot).

**Comment by ahronhelfenstein** [comment]
Thanks for the insights @hhromic. For now, I'll use your idea to get the IP from __meta_dockerswarm_node_manager_leader  so.

**Comment by hhromic** [comment]
This is the relabelling configuration we are using successfully so far to scrape node exporters on the nodes:
```yaml
  - job_name: dockerswarm_node
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      # set target scrape configuration
      - source_labels:
          - __meta_dockerswarm_node_address
        target_label: __address__
        replacement: '$1:9100'
      - source_labels:
          - __meta_dockerswarm_node_manager_leader
          - __meta_dockerswarm_node_manager_address
        regex: 'true;(.+):[0-9]+'
        target_label: __address__
        replacement: '$1:9100'
```
Hope it serves for inspiration in your setup.
