### ISSUE TITLE
File SD fails to instrument itself for when an inotify watcher instance is unable to be created

### ISSUE THREAD

**Issue by ful09003** [prometheus/prometheus#11067]
### What did you do?

In our environment, we make considerable use of `file_sd` (many hundreds of individual file_sd configurations, in some cases) for Prometheus installed in a virtual machine.

A recent change to our virtual machine operating system introduced a subtle change wherein our 
 `fs.inotify.max_user_instances` kernel parameter was lowered (to 128); this prevents `fsnotify/fsnotify` from setting up a new watcher.

When watcher instances fail to create, scrape configs are potentially not created or updated which is no good :)

Steps to reproduce:

1) Deploy Prometheus to a virtual machine (container is probably also possible, but I've not tested that way) with an artificially limited kernel `fs.inotify.max_user_instances`
2) Create or update file_sd files in excess of the artificially low `fs.inotify.max_user_instances` ceiling
3) Observe triggering of [this code path](https://github.com/prometheus/prometheus/blob/main/discovery/file/file.go#L238-L241) in file.go

Alternatively:

1) Begin with an existing Prometheus using several `file_sd` and with `--web.enable-lifecycle`
2) Artificially limit `fs.inotiry.max_user_instances` e.g. `sudo sysctl fs.inotify.max_user_instances=4`
3) `curl -XPOST localhost:9090/-/reload` and observe the same file.go error path

### What did you expect to see?

I would expect Prometheus to instrument itself via a metric in such a way that this condition could be alerted on.

There **is** logging which ultimately helped our team identify the failure condition, however this would have been much more intuitive to see first as a metric. For environments which have lossy (or disabled) logging, this would have been a nightmare of an issue to triage.

### What did you see instead? Under which circumstances?

A metric to correspond to the exiting logging would have been great!

### System information

Linux 5.4.0-72-generic x86_64

### Prometheus version

```text
I have tested this on two versions so far:

prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64

prometheus, version 2.37.0 (branch: HEAD, revision: b41e0750abf5cc18d8233161560731de05199330)
  build user:       root@0ebb6827e27f
  build date:       20220714-15:13:18
  go version:       go1.18.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
Adapted from the quickstart, and with small modifications to e.g. job names to simulate our real environment:


scrape_configs:
- job_name: job1
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /opt/prom_configs/job1.json
    refresh_interval: 5m
- job_name: job2
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /opt/prom_configs/job2.json
    refresh_interval: 5m
- job_name: job3
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /opt/prom_configs/job3.json
    refresh_interval: 5m
- job_name: job4
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /opt/prom_configs/job4.json
    refresh_interval: 5m
```

(each job is just configured to scrape Prometheus itself, for simplicity)
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
ts=2022-07-27T21:51:22.537Z caller=file.go:239 level=error component="discovery manager scrape" discovery=file msg="Error adding file watcher" err="too many open files"
ts=2022-07-27T21:51:22.537Z caller=file.go:239 level=error component="discovery manager scrape" discovery=file msg="Error adding file watcher" err="too many open files"
ts=2022-07-27T21:51:22.538Z caller=file.go:239 level=error component="discovery manager scrape" discovery=file msg="Error adding file watcher" err="too many open files"
ts=2022-07-27T21:51:22.538Z caller=file.go:239 level=error component="discovery manager scrape" discovery=file msg="Error adding file watcher" err="too many open files"
```
```
