### ISSUE TITLE
[http_sd_configs] multiple URL support

### ISSUE THREAD

**Issue by hayk96** [prometheus/prometheus#11118]
## Proposal
**Use case. Why is this important?**

As the Prometheus server supports only one target URL for the `http_sd_configs` mechanism (see [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#http_sd_config)) it'll be better to pass multiple URLs like `file_sd_configs` mechanism supports.

I'm going to replace all `file_sd_configs` mechanisms with `http_sd_configs`. I have an HTTP endpoint that returns the same response as in the `/opt/us` directory files when I request the appropriate path.

**my_job with "file_sd_configs"**
This is `my_job` with the `file_sd_configs` mechanism
```
- job_name: 'my_job'
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  file_sd_configs:
    - files:
        - /opt/us/dc-a.yml
        - /opt/us/dc-b.yml
        - /opt/us/dc-c.yml
```

**my_job with "http_sd_configs"**
Here is my expectation of how should `my_job` be by using the `http_sd_config` mechanism with multiple URL support
```
- job_name: 'my_job'
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
    http_sd_configs:
      - url:
          - "http://my-http-endpoint:8080/us/regions/dc-a"
          - "http://my-http-endpoint:8080/us/regions/dc-b"
          - "http://my-http-endpoint:8080/us/regions/dc-c"
```

**Comment by roidelapluie** [comment]
you can do:

```
- job_name: 'my_job'
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
    http_sd_configs:
      - url: "http://my-http-endpoint:8080/us/regions/dc-a"
      - url: "http://my-http-endpoint:8080/us/regions/dc-b"
      - url: "http://my-http-endpoint:8080/us/regions/dc-c"
```
