### ISSUE TITLE
Desired shards increase and then drop, but no resharding

### ISSUE THREAD

**Issue by jakubgs** [prometheus/prometheus#11116]
### What did you do?

I'm running a setup with 1 Prometheus instance in each DC sending metrics to a Cortex cluster using remote write.
The Cortex cluster consists of 2 distributors and 3 ingesters, and has been stable for a while, but Prometheus upgrade to `2.37.0` appears to have destabilized things, at least that's my assumption, there is not exact correlation with the upgrade.

The issue is that I'm seeing the `prometheus_remote_storage_shards_desired` growing steadily to silly numbers(thousands) and then suddenly drop without explanation:

![image](https://user-images.githubusercontent.com/2212681/182917872-1ab628d9-8388-43b4-bcac-d45e8700d23a.png)

While the actual shards being used do not go down from the max of 20:

![image](https://user-images.githubusercontent.com/2212681/182917980-4da09d70-7efe-4ab2-a54a-61873130b169.png)

Meanwhile the cortex distributors are fine, and responding with 200s, some 400s scattered due to `sample-out-of-order` errors:

![image](https://user-images.githubusercontent.com/2212681/182918128-af35ec9f-c148-4d96-bc2e-e654079f8ca6.png)

### What did you expect to see?

I expected the desired shards to grow to some actual demand, but the number of pending samples is not growing:

![image](https://user-images.githubusercontent.com/2212681/182918205-c1945f9c-d48b-4095-8531-d3f85c1471a1.png)

Why would the desired shards keep growing and then suddenly drop?

### What did you see instead? Under which circumstances?

And in addition to that, I'd expect the actual shards used to go down once the desired shards drops to normal numbers below max, but it does not, it just stays on my max of 20.

### System information

Linux 5.4.0-104-generic x86_64

### Prometheus version

```text
prometheus, version 2.37.0 (branch: HEAD, revision: b41e0750abf5cc18d8233161560731de05199330)
  build user:       root@0ebb6827e27f
  build date:       20220714-15:13:18
  go version:       go1.18.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
remote_write:
  - url: 'http://10.10.0.136:9092/api/v1/push'
    name: 'master-01.do-ams3.metrics.hq'
    queue_config:
      capacity: 5000
      min_shards: 2
      max_shards: 20
      max_samples_per_send: 1000
      # WARNING: Disable retries by setting minimum too high.
      min_backoff: 30d
      max_backoff: 30d
      batch_send_deadline: 10s
  - url: 'http://10.10.0.73:9092/api/v1/push'
    name: 'master-02.do-ams3.metrics.hq'
    queue_config:
      capacity: 5000
      min_shards: 2
      max_shards: 20
      max_samples_per_send: 1000
      # WARNING: Disable retries by setting minimum too high.
      min_backoff: 30d
      max_backoff: 30d
      batch_send_deadline: 10s
```

**Comment by roidelapluie** [comment]
min_backoff: 30d seems really strange. I would suspect that this might block some shards.

**Comment by jakubgs** [comment]
I'm just trying to disable retries. Since there's no `max_retries` setting as it was removed in:

* https://github.com/prometheus/prometheus/pull/5649

I've requested a feature to disable retries, but no response so far:

* https://github.com/prometheus/prometheus/issues/11089

**Comment by bboreham** [comment]
Can we close this then, as "abnormal config gives abnormal behaviour" ?
Setting the min_backoff really high does not disable retries, but also I see that #11089 is not about retries as the code uses the word.

**Comment by jakubgs** [comment]
That's fine, our current setup works well, the settings I'm using are:
```
remote_write:
  - url: 'http://cortexbackend:9092/api/v1/push'
    name: 'cortex'
    queue_config:
      min_shards: 2
      max_shards: 200
      capacity: 2500
      max_samples_per_send: 2000
      batch_send_deadline: 6s
      min_backoff: 1s
      max_backoff: 1s
```
Maybe this will be helpful for someone.
