### ISSUE TITLE
Remote read support Matcher type like federation feature.

### ISSUE THREAD

**Issue by wangjc0216** [prometheus/prometheus#11136]
## Proposal

I hope remote read can support Matcher like federation . (sorry for my poor english)
It will help prometheus help route remote read better .

### use case

I use M3DB as Metric Storage. I want to disperse my read request to multiple M3Query instance to avoid single instance CPU resource  high .   some promql like:
```
feature_counter{cluster="A"}
feature_counter{cluster="B"}
```
I hope that  `feature_counter{cluster="A"}` req can route to M3Query A instance , `feature_counter{cluster="B"}` req can route to M3Query A instance and  `feature_counter` also can route to M3Query A. The configuration is like :
```
# cluster C will route to  m3queryC,cluster B will route to m3queryB,and other will route to m3queryA
remote_read:
  - url: "http://m3queryC:7201/api/v1/prom/remote/read"
    read_recent: true
    required_matchers: 
    -  '{cluster="C"}'
    
  - url: "http://m3queryB:7201/api/v1/prom/remote/read"
    read_recent: true
    required_matchers: 
    -  '{cluster="B"}'

  - url: "http://m3queryA:7201/api/v1/prom/remote/read"
    read_recent: true
    required_matchers: 
    -  '{cluster=!"B|C"}'
```
