### ISSUE TITLE
Duplicate Sample for TimeStamp errors when Remote Write from K6 to Prometheus to Mimir

### ISSUE THREAD

**Issue by perrinj3** [prometheus/prometheus#11157]
### What did you do?

We are using K6 to output to RemoteWrite to Prometheus and then Prometheus does a remotewrite to Mimir. 

### What did you expect to see?

Expect to see metrics created by K6 appearing in Mimir without any errors.

### What did you see instead? Under which circumstances?

Time series are created in Mimir but we get "duplicate sample for timestamp"  errors in the Prometheus log and the Mimir log

### System information

linux/amd64

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@e59c79158868
  build date:       20220609-15:25:21
  go version:       go1.18.3
  platform:         linux/amd64

Mimir, version 2.1.0 (branch: HEAD, revision: 840c686)
  go version:       go1.17.8
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
	  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
	  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
	  # scrape_timeout is set to the global default (10s).
	  external_labels:
	    cluster: demo
	    namespace: demo
	
	rule_files:
	  - /etc/prometheus/rules.yml
	
	scrape_configs:
	  - job_name: "OpenTel"
	    # metrics_path defaults to '/metrics'
	    # scheme defaults to 'http'.
	    scrape_interval: 1m
	    static_configs:
	    - targets: ["localhost:9099"]
	      labels:
	        pod: 'prom'
	        cluster: demo
	        namespace: demo
	    
	  - job_name: "OpenTel_Internals"
	    # metrics_path defaults to '/metrics'
	    # scheme defaults to 'http'.
	    scrape_interval: 1m
	    static_configs:
	    - targets: ["localhost:8888"]
	      labels:
	        pod: 'prom'
	        cluster: demo
	        namespace: demo
	  - job_name: 'demo/prometheus'
	    scrape_interval: 1m
	    # metrics_path defaults to '/metrics'
	    # scheme defaults to 'http'.
	    static_configs:
	      - targets: ['localhost:9090']
	        labels:
	          pod: 'prom'
	          cluster: demo
	          namespace: demo
	  - job_name: demo/mimir
	    static_configs:
	      - targets: [ 'localhost:8080' ]
	        labels:
	          pod: 'mimir'
	          cluster: demo
	          namespace: demo
	
	remote_write:
	  - url: http://localhost:9009/api/v1/push

	  # Add X-Scope-OrgID header so that Mimir knows what tenant the remote write data should be stored in.
	  # In this case, our tenant is "demo"
	    headers:
	      X-Scope-OrgID: demo



MIMIR config is

# Do not use this configuration in production.
	# It is for demonstration purposes only.
	multitenancy_enabled: false
	target: all,alertmanager,overrides-exporter
	
	blocks_storage:
	  backend: s3
	  s3:
	    endpoint: localhost:9000
	    bucket_name: mimir-blocks
	    access_key_id: mimir
	    secret_access_key: supersecret
	    insecure: true
	  bucket_store:
	    sync_dir: /data/tsdb
	  tsdb:
	    dir: /data/ingester
	
	compactor:
	  data_dir: /data/compactor
	  sharding_ring:
	    kvstore:
	      store: memberlist
	
	distributor:
	  ring:
	    instance_addr: 127.0.0.1
	    kvstore:
	      store: memberlist
	  instance_limits:
	    max_inflight_push_requests: 5048576000
	
	
	ruler:
	  rule_path: /data/ruler
	  alertmanager_url: http://127.0.0.1:8080/alertmanager

	  ring:
	    # Quickly detect unhealthy rulers to speed up the tutorial.
	    heartbeat_period: 2s
	    heartbeat_timeout: 10s
	
	activity_tracker:
	  filepath: /data/metrics-activity.log
	
	ruler_storage:
	  backend: s3
	  s3:
	    endpoint: localhost:9000
	    bucket_name: mimir-ruler
	    access_key_id: mimir
	    secret_access_key: 
	    insecure: true
	
	alertmanager:
	  data_dir: /data/alertmanager
	  fallback_config_file: /etc/alertmanager-fallback-config.yaml
	  external_url: http://localhost:9009/alertmanager

	
	alertmanager_storage:
	  backend: s3
	  s3:
	    endpoint: localhost:9000
	    bucket_name: mimir-alertmanager
	    access_key_id: mimir
	    secret_access_key: 
	    insecure: true
	
	ingester:
	  ring:
	    instance_addr: 127.0.0.1
	    kvstore:
	      store: memberlist
	    replication_factor: 1
	
	
	store_gateway:
	  sharding_ring:
	    replication_factor: 1
	
	server:
	  http_listen_port: 9009
	  grpc_server_max_send_msg_size: 5048576000
	  grpc_server_max_recv_msg_size: 5048576000
	  http_server_read_timeout: 5m
	
	  log_level: warn
	
	limits:
	  max_global_series_per_user: 150000000
	  max_global_series_per_metric: 150000000
	  ingestion_rate: 150000000
	
	
	frontend:
	  max_body_size: 5048576000
	  grpc_client_config:
	    max_recv_msg_size: 5048576000
	    max_send_msg_size: 5048576000
	
	frontend_worker:
	  grpc_client_config:
	    max_recv_msg_size: 5048576000
	    max_send_msg_size: 5048576000
	
	query_scheduler:
	  grpc_client_config:
	    max_recv_msg_size: 5048576000
	    max_send_msg_size: 5048576000
	
	querier:  
	  timeout: 10m
	  max_samples: 50000000000
```

### Logs

```text
Prometheus Error logs

ts=2022-08-11T03:04:01.327Z caller=dedupe.go:112 component=remote level=error remote_name=281482 url=http://localhost:9009/api/v1/push msg="non-recoverable error" count=113 exemplarCount=0 err="server returned HTTP status 400 Bad Request: user=anonymous: err: duplicate sample for timestamp. timestamp=2022-08-11T03:03:56.079Z, series={__name__=\"k6_data_received\", application=\"IB\", buildNumber=\"IB_40\", buildTool=\"K6\", cluster=\"demo\", environment=\"QA\", namespace=\"demo\", priority=\"High\", protocol=\"HTTP\", scenario=\"IBAPILogin\", squadName=\"CAT\", testName=\"IBLoadTest\"}"

**We also see errors in the Mimir log like this**
level=warn ts=2022-08-11T03:04:01.326799535Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=266.481µs err="rpc error: code = Code(400) desc = user=anonymous: err: duplicate sample for timestamp. timestamp=2022-08-11T03:03:56.079Z, series={__name__=\"k6_data_received\", application=\"IB\", buildNumber=\"IB_40\", buildTool=\"K6\", cluster=\"demo\", environment=\"QA\", namespace=\"demo\", priority=\"High\", protocol=\"HTTP\", scenario=\"IBAPILogin\", squadName=\"CAT\", testName=\"IBLoadTest\"}" msg=gRPC
level=error ts=2022-08-11T03:04:01.327048686Z caller=push.go:89 user=anonymous msg="push error" err="rpc error: code = Code(400) desc = user=anonymous: err: duplicate sample for timestamp. timestamp=2022-08-11T03:03:56.079Z, series={__name__=\"k6_data_received\", application=\"IB\", buildNumber=\"IB_40\", buildTool=\"K6\", cluster=\"demo\", environment=\"QA\", namespace=\"demo\", priority=\"High\", protocol=\"HTTP\", scenario=\"IBAPILogin\", squadName=\"CAT\", testName=\"IBLoadTest
```
