### ISSUE TITLE
Version 2.15 web dashboard serves on every IP in the system. yaml config ['10.8.0.1:9090'] doesn't work.

### ISSUE THREAD

**Issue by youtweakit** [prometheus/prometheus#11207]
### What did you do?

Hi, i need to serve a web interface of prometheus on exact ip address in my local area network, but it serves on every IP4 and IP6 on port 9090. Changing the prometheus.yaml from ['localhost:9090'] to, for example, ['10.8.0.1:9090'] doesn't work. May be these bug is solved in next versions but in mine(2.15) from ubuntu's 20.04  official repo it persists. 

### What did you expect to see?

I expect to see the prometheus.yaml configuring the behavior of prometheus web server.

### What did you see instead? Under which circumstances?

But changing the ip address in prometheus.yaml doesn't affect web server serving. It serves on ::9090.

### System information

Linux 5.4.0-124-generic x86_64

### Prometheus version

```text
prometheus, version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20200113-10:10:54
  go version:       go1.13.7
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: example
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.8.0.1:9093
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 10.8.0.1:9090
- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 10.8.0.1:9100
```
