### ISSUE TITLE
counter increases by 5 within a scrape interval - increase() shows 6

### ISSUE THREAD

**Issue by josh-m-sharpe** [prometheus/prometheus#11328]
### What did you do?

incremented a couter 5 times
built a graph of that counter
built a graph of increase(counter)[10s]

### What did you expect to see?

an increase of 5

### What did you see instead? Under which circumstances?

an increase of 6

![Prometheus_Time_Series_Collection_and_Processing_Server_and_Prometheus_Time_Series_Collection_and_Processing_Server](https://user-images.githubusercontent.com/39473/191359981-5e37dffd-d05f-4594-995b-2c068715bcad.png)

### System information

docker container prom/prometheus:v2.37.0

### Prometheus version

```text
2.37.0
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: nomad
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']
    consul_sd_configs:
    - server: '{{ env "attr.unique.network.ip-address" }}:8500'
      services: ['nomad','nomad-client']
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: .*,http,.*
        action: keep

  - job_name: prometheus
    metrics_path: /metrics
    consul_sd_configs:
    - server: '{{ env "attr.unique.network.ip-address" }}:8500'
      services: ['prometheus']

  - job_name: traefik
    metrics_path: /metrics
    consul_sd_configs:
    - server: '{{ env "attr.unique.network.ip-address" }}:8500'
      services: ['traefik']

  - job_name: statsd-exporter
    metrics_path: /metrics
    consul_sd_configs:
    - server: '{{ env "attr.unique.network.ip-address" }}:8500'
      services: ['statsd-exporter-service']
```
