### ISSUE TITLE
ec2_sd_configs: make 'region' available as a metadata label

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#11320]
## Scenario

Suppose you have a single scrape job that scrapes many EC2 accounts or regions, or combinations of account+region:

```
  - job_name: foo
    ec2_sd_configs:
      - access_key: AKIA.....
        secret_key: XXXX.....
        region: eu-west-1
      - access_key: AKIA.....
        secret_key: XXXX.....
        region: eu-west-2
      ...etc
    relabel_configs:
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance
      - source_labels: [__meta_ec2_owner_id]
        target_label: owner_id
      ...etc
```

Within the target relabelling config, it's easy to access the account ID (it's `__meta_ec2_owner_id`).  But there doesn't seem to be an item which identifies the region.

It would be very tedious to have to make duplicate scrape jobs for every region, which differ only in the one label they apply.

## Proposal

Option 1: set `__meta_ec2_region` in the target label set, to the region which was requested in the DescribeInstances API call (if any). That's a very simple change.

Option 2: I would also be quite happy if I could do something like this:

```
    ec2_sd_configs:
      - access_key: AKIA.....
        secret_key: XXXX.....
        region: eu-west-1
        labels:
          region: eu-west-1
      - access_key: AKIA.....
        secret_key: XXXX.....
        region: eu-west-2
        labels:
          region: eu-west-2
```

However, currently only static_configs and file_sd_configs permit applying additional labels to a group of targets in this way.  This is a more profound change across SD mechanisms, and IMO wouldn't be worth doing unless there were additional use cases that this would fix.

## Workaround

I discovered that the `private_dns_name` metadata usually is of the form `<foo>.<region>.compute.internal`, except for the us-east-1 region where it's `<foo>.ec2.internal`.

This is [documented](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-naming.html) to be the case for "the guest OS hostname", in either of the available formats.

Hence this appears to work:

```
      - source_labels: [__meta_ec2_private_dns_name]
        regex: '.*[.]ec2[.]internal'
        replacement: us-east-1
        target_label: region
      - source_labels: [__meta_ec2_private_dns_name]
        regex: '.*[.]([^.]+)[.]compute[.]internal'
        target_label: region
```

However it feels fragile to depend on this.
