### ISSUE TITLE
Prometheus in agent mode fails to send data to Thanos Receiver via remote_write way too often.

### ISSUE THREAD

**Issue by apoorva-marisomaradhya** [prometheus/prometheus#11359]
### What did you do?

Running Prometheus in k8s with agent mode enabled and have remote_write endpoint configured to receive metrics from prometheus. Running prometheus v2.36.2, with below remote_write configuration 

`prometheus.yml: |-
    global:
      external_labels:
        monitor: prometheus
        replica: '${HOSTNAME}'
        pod: '${HOSTNAME}'
      scrape_interval: 15s
    remote_write:
      - url: 'http://<thanos-receive-endpoint>:19291/api/v1/receive'
        queue_config:
          capacity: 6000
        
          # Maximum number of shards, i.e. amount of concurrency.
          max_shards: 1500
        
          # Minimum number of shards, i.e. amount of concurrency.
          min_shards: 1
        
          # Maximum number of samples per send.
          max_samples_per_send: 2000
        
          # Maximum time a sample will wait in buffer.
          batch_send_deadline: 5s
        
          # Initial retry delay. Gets doubled for every retry.
          min_backoff: 30ms
        
          # Maximum retry delay.
          max_backoff: 5s
        `

### What did you expect to see?

Prometheus to send data without any gap to remote_write endpoint.

### What did you see instead? Under which circumstances?

Metrics are been dropped after certain interval of time, with no log messages in prometheus. But, it recovers after a short interval by itself.

### Prometheus version

```text
prometheus v2.36.2
```

### Prometheus configuration file

```yaml
`prometheus.yml: |-
    global:
      external_labels:
        monitor: prometheus
        replica: '${HOSTNAME}'
        pod: '${HOSTNAME}'
      scrape_interval: 15s
    remote_write:
      - url: 'http://<thanos-receive-endpoint>:19291/api/v1/receive'
        queue_config:
          capacity: 6000
        
          # Maximum number of shards, i.e. amount of concurrency.
          max_shards: 1500
        
          # Minimum number of shards, i.e. amount of concurrency.
          min_shards: 1
        
          # Maximum number of samples per send.
          max_samples_per_send: 2000
        
          # Maximum time a sample will wait in buffer.
          batch_send_deadline: 5s
        
          # Initial retry delay. Gets doubled for every retry.
          min_backoff: 30ms
        
          # Maximum retry delay.
          max_backoff: 5s
        `
```
