### ISSUE TITLE
Prometheus can't scrape Virtual Machines generated from Flexible Virtual Machine Scale Sets using Azure Service Discovery 

### ISSUE THREAD

**Issue by wg125480** [prometheus/prometheus#11370]
### What did you do?

Prometheus pods generate an error when trying to scrape virtual machines that are managed by a Virtual Machine Scale Set (VMSS), deployed using the Flexible Orchestration Mode, using Azure Service Discovery.

This is hardly surprising, considering that Flexible mode is fairly new and some things haven't caught up.

I had originally thought this looked to be a permission issues, but on reread it appears as though the API is not supported.

### What did you expect to see?

I'd expect the discovery manager to successfully refresh the target groups when scanning for Virtual Machines that are spawned from a flexible VMSS.

### What did you see instead? Under which circumstances?

The following error is thrown: 
```
caller=refresh.go:99 level=error component="discovery manager scrape" discovery=azure msg="Unable to refresh target groups" err="could not get virtual machine scale set vms: could not list virtual machine scale set vms: compute.VirtualMachineScaleSetVMsClient#List: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"OperationNotAllowed\" Message=\"Operation 'VirtualMachineScaleSets.virtualMachines.GET' is not allowed on Virtual Machine Scale Set 'vmss-my-scale-set'.\""
```

### Prometheus version

v2.38.0

### Prometheus configuration file

```yaml
The prometheus config looks like:

- job_name: my job
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_azure_machine_private_ip]
    separator: ;
    regex: (.+)
    target_label: __address__
    replacement: ${1}:24231
    action: replace
  - source_labels: [__meta_azure_machine_tag_vm_tag]
    separator: ;
    regex: test_azure2
    replacement: $1
    action: keep
  azure_sd_configs:
  - environment: AzurePublicCloud
    port: 80
    subscription_id: <MYID>
    refresh_interval: 5m
    authentication_method: ManagedIdentity
    follow_redirects: true
    enable_http2: true
 ```
```
