### ISSUE TITLE
serverset_sd_configs is only scraping the first configured path

### ISSUE THREAD

**Issue by StephanErb** [prometheus/prometheus#1137]
I am running Prometheus 0.16.0rc2 and have the following config:

```yaml
  - job_name: 'aurora'
    metrics_path: /probe
    serverset_sd_configs:
    - servers:
      - 'one.zk.server:2181'
      - 'two.zk.server:2181'
      - 'three.zk.server:2181'
      paths:
      - '/aurora/myrole/test/service-1'
      - '/aurora/myrole/test/service-2'
    relabel_configs:
      ... 
```
* **Current behaviour**: Prometheus is only scraping one entry in the paths list. Whatever is listed first is scraped, all others are ignored. Multiple serversets are only scraped if one is specifying a root entry such as `/aurora`.

* **Expected behaviour**: All listed paths are scraped.

[I believe this code here might be the culprint](https://github.com/prometheus/prometheus/blob/facf60e0331977bc9245d54c0c1b6fee6df335b6/retrieval/discovery/serverset.go#L90)
