### ISSUE TITLE
Prometheus stopped closing opened sockets

### ISSUE THREAD

**Issue by TheFrenchGhosty** [prometheus/prometheus#11419]
### What did you see instead? Under which circumstances?

Prometheus seems to have stopped to close opened sockets. It keeps sockets opened, until, I'm guessing: midnight.

Problem of today: Prometheus used thousands of sockets until I stopped it.

![image](https://user-images.githubusercontent.com/47571719/194126264-a1d0fb7c-c54e-4ce2-943f-e3b602214851.png)

Problems of the last 24 hours: you can see a bump in sockets used yesterday, that goes back to normal at 00:00.

![image](https://user-images.githubusercontent.com/47571719/194126128-5045f51b-c45d-49c5-b92c-27dfbb070aa6.png)

### System information

Docker

### Prometheus version

```text
quay.io/prometheus/prometheus:v2.38.0
```

**Comment by roidelapluie** [comment]
Your prometheus configuration (without sensitive data) would help.

**Comment by TheFrenchGhosty** [comment]
@roidelapluie Here it is:

```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:[PORT]"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["localhost:[PORT]"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["localhost:[PORT]"]
```
