### ISSUE TITLE
Prometheus does not detect counter resets (using increase() or resets())

### ISSUE THREAD

**Issue by easimon** [prometheus/prometheus#11433]
### What did you do?

I have a counter like the following, scraped from a Shelly Plug, counting watthours. Whenever I unplug the Shelly (or on power outage), the counter starts with 0.

```
# HELP shelly_meter_power_watthours_total
# TYPE shelly_meter_power_watthours_total counter
shelly_meter_power_watthours_total{address="192.168.x.x",channel="0",firmwareVersion="20220809-124506/v1.12-g99f7e0b",mac="...",name="Schreibtisch",type="SHPLG-S",} 1010.4833333333333
```

The setup is young, so I never had a reset until now. 

I am displaying various `increase(...)`s in a grafana dashboard using a table, to measure consumption per device for 

- last 24h
- last 30d
- last 1y

Example query: 
```
sum by (name) increase(shelly_meter_power_watthours_total[1d])
```

### What did you expect to see?

According to the documentation, `increase()` detects counter resets (how?), so I had expected to see only positive values for increases. 

### What did you see instead? Under which circumstances?

When the counter resets, I see negative increase values, like the following, and resets don't seem to be detected. 

This simple dashboard shows (left to right)
```
shelly_meter_power_watthours_total{name="Schreibtisch"}
increase(shelly_meter_power_watthours_total{name="Schreibtisch"}[1h])
resets(shelly_meter_power_watthours_total{name="Schreibtisch"}[1h])
```

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/1749657/194618886-88056127-9724-4ddc-86ab-b41147af77d3.png">

### System information

Linux 5.19.13-100.fc35.x86_64

### Prometheus version

```text
Using Docker image quay.io/prometheus/prometheus:v2.39.0, output from docker log:

"Starting Prometheus Server" mode=server version=(version=2.39.0, branch=HEAD, revision=6d7f26c46ff70286944991f95d791dff03174eea)
build_context="(go=go1.19.1, user=root@bc053716806f, date=20221005-05:09:43)"
ts=2022-10-07T16:12:03.867Z caller=main.go:550 level=info host_details="(Linux 5.19.13-100.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Oct 4 16:05:25 UTC 2022 x86_64 6599c7622328 (none))"
fd_limits="(soft=1073741816, hard=1073741816)"
vm_limits="(soft=unlimited, hard=unlimited)"
```
```


### Prometheus configuration file

```yaml
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: prometheus
rule_files:
- /etc/prometheus/rules/*.yaml

scrape_configs:
- job_name: shelly-exporter
  honor_labels: false
  metrics_path: /prometheus
  scheme: http
  scrape_timeout: 20s
  static_configs:
    - targets:
      - shelly-exporter:8080
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_
