### ISSUE TITLE
Unable to Make Prometheus Read the web-config.yml for TLS Encryption (Error: unknown long flag '--web.config.file')

### ISSUE THREAD

**Issue by Andreas-Kreouzos** [prometheus/prometheus#11438]
### What did you do?

Hello I am following the [official documentation](https://prometheus.io/docs/guides/tls-encryption/) regarding the TLS encryption of Prometheus. My Spring Boot uses https endpoints and thus I want Prometheus to scrap them as is. I am following the instructions but I am having problem in configuring Prometheus to read my web-config.yml. Specifically the following command,

prometheus \
--config.file=/mnt/d/Projects/Msc-Thesis-Project/prometheus.yml \
--web.config.file=/mnt/d/Projects/Msc-Thesis-Project/web-config.yml \
--web.external-url=https://localhost:8443/

### What did you see instead? Under which circumstances?

Error parsing commandline arguments: unknown long flag '--web.config.file'
prometheus: error: unknown long flag '--web.config.file'

**Comment by adriancast** [comment]
same issue!

**Comment by Andreas-Kreouzos** [comment]
Hello there, since I wasn't able to find a solution to this day, I opened a HTTP port for my Promtheus to fetch metrics from my application.

**Comment by adriancast** [comment]
I finally got it running. Just in case someone has the same problem. Here is an example with a docker-compose:

```
  prometheus:
    image: adriancast/k-prometheus:latest
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.config.file=/etc/prometheus/web.yml'
    ports:
      - 9090:9090
```

Dockerfile of k-prometheus image:
```
FROM prom/prometheus:v2.40.2

COPY ./prometheus.yml /etc/prometheus/prometheus.yml
COPY ./web.yml /etc/prometheus/web.yml
```

To be honest I am not sure if I typed something wrong the first time. I got the same error as you but with this configuration is working as expected.

Good luck!
