### ISSUE TITLE
file_sd_config Error reading file" path=/xx/micros.json err="json: unknown field \"metrics_path

### ISSUE THREAD

**Issue by chinfeng2github** [prometheus/prometheus#11449]
### What did you do?

  **prometheus-cluster.yaml** 
```
#file_sd_configs jobs
  - job_name: 'file_sd'
    scrape_interval: 15s
    scrape_timeout: 10s
    #metrics_path: /metrics
    file_sd_configs:
    - files: ['/etc/prometheus/sd_conf/*.json']
      refresh_interval: 5s
```  

**nacos.json**
```
[
    {
	"metrics_path": "/nacos/actuator/prometheus",
        "targets": [
            "12.1.33.13:8848"
        ],
        "labels": {
            "node_name": "nacos",
            "idc": "RUC"
        }
    }
]
```

then got the error below:
prometheus    | ts=2022-10-12T08:17:48.342Z caller=file.go:337 level=error component="discovery manager scrape" discovery=file msg="Error reading file" path=/etc/prometheus/sd_conf/nacos.json err="json: unknown field \"metrics_path\""

### What did you expect to see?

metrics_path can be pasred correct

### What did you see instead? Under which circumstances?

---

### System information

docker

### Prometheus version

```text
lastest
2022-10-12 16:19:39
```

### Prometheus configuration file

```yaml
**prometheus-cluster.yaml** 

#file_sd_configs jobs
  - job_name: 'file_sd'
    scrape_interval: 15s
    scrape_timeout: 10s
    #metrics_path: /metrics
    file_sd_configs:
    - files: ['/etc/prometheus/sd_conf/*.json']
      refresh_interval: 5s
```  

**nacos.json**
```
[
    {
	"metrics_path": "/nacos/actuator/prometheus",
        "targets": [
            "12.1.33.13:8848"
        ],
        "labels": {
            "node_name": "nacos",
            "idc": "RUC"
        }
    }
]
```
```


### Alertmanager version

```text
----
```

### Alertmanager configuration file

```yaml
----
```

### Logs

```text
prometheus    | ts=2022-10-12T08:17:48.342Z caller=file.go:337 level=error component="discovery manager scrape" discovery=file msg="Error reading file" path=/etc/prometheus/sd_conf/nacos.json err="json: unknown field \"metrics_path\""
```
