### ISSUE TITLE
AWS Announcing an update to IAM role trust policy behavior

### ISSUE THREAD

**Issue by tomahkvt** [prometheus/prometheus#11441]
### What did you do?

AWS Announcing an update to IAM role trust policy behavior https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
AWS asks not to use self-referential role
I am using Prometheus 2.36.1.
I configurated AWS service discovery by using AWS role
Prometheus sd configuration You can see bellow
```
              - job_name: ec2
                ec2_sd_configs:
                  - region: "eu-west-1"
                    role_arn:  "arn:aws:iam::1111111111111111:role/prometheus"
                    port: 9100
                    filters:
                      - name: 'tag:Service'
                        values:
                          - 'EC2'
```
Role policy you can see below:
```
{
    "Statement": [
        {
            "Action": "ec2:Describe*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": "elasticloadbalancing:Describe*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": [
                "cloudwatch:ListMetrics",
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:Describe*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": "autoscaling:Describe*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Resource": "arn:aws:iam::1111111111111111:role/prometheus"
        }
    ],
    "Version": "2012-10-17"
}
```

This configuration works.
When I delete sts:AssumeRole in policy according to AWS recommendation I am getting the following error:

`_ts=2022-10-10T17:45:21.068Z caller=refresh.go:79 level=error component="discovery manager scrape" discovery=ec2 msg="Unable to refresh target groups" err="could not describe instances: AccessDenied: User: arn:aws:sts::1111111111111111:assumed-role/prometheus/1665456781035122187 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1111111111111111:role/prometheus\n\tstatus code: 403, request id: df8e811e-cb06-425e-aa04-6b0340da854f"_`

I have a question do you have plan update Prometheus to avoid action sts:AssumeRole usage?

### What did you expect to see?

I have a question do you have plan update Prometheus to avoid action sts:AssumeRole usage?

### What did you see instead? Under which circumstances?

When I delete sts:AssumeRole in policy according to AWS recommendation I am getting the following error:

`_ts=2022-10-10T17:45:21.068Z caller=refresh.go:79 level=error component="discovery manager scrape" discovery=ec2 msg="Unable to refresh target groups" err="could not describe instances: AccessDenied: User: arn:aws:sts::1111111111111111:assumed-role/prometheus/1665456781035122187 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1111111111111111:role/prometheus\n\tstatus code: 403, request id: df8e811e-cb06-425e-aa04-6b0340da854f"_`

### System information

Linux 5.4.209-116.367.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@e59c79158868
  build date:       20220609-15:25:21
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: ec2
                ec2_sd_configs:
                  - region: "eu-west-1"
                    role_arn:  "arn:aws:iam::1111111111111111:role/prometheus"
                    port: 9100
                    filters:
                      - name: 'tag:Service'
                        values:
                          - 'EC2'
```
