### ISSUE TITLE
relabel_configs: can not use <name> contain "-" in __param_<name>

### ISSUE THREAD

**Issue by pahla1** [prometheus/prometheus#11456]
### What did you do?

```
- job_name: "default"
    consul_sd_configs:
      - server: consul:8500
        datacenter: "dc1"
        tags:
          - prom.metrics=true
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_tags]
        regex: '.*,prom.metrics.path=([^,]+),.*'
        replacement: $1
        target_label: __metrics_path__
      - source_labels: [__meta_consul_tags]
        regex: '.*,prom.metrics.param.api-key=([^,]+),.*'
        replacement: $1
        target_label: __param_api-key
```

### What did you expect to see?

Expect prometheus set "api-key" query param to the extracted value from consul tags.

### What did you see instead? Under which circumstances?

The prometheus throw error:

```
level=error msg="Error loading config (--config.file=/local/prometheus.yml)" file=/local/prometheus.yml err="parsing YAML file /local/prometheus.yml: \"__param_api-key\" is invalid 'target_label' for replace action"

```

but when I remove the "-" from "api-key", everything works as expected.

### System information

Linux 5.4.0-113-generic #127-Ubuntu

### Prometheus version

```text
version=2.36.2, branch=HEAD, revision=d7e7b8e04b5ecdc1dd153534ba376a622b72741b
```
