### ISSUE TITLE
High cardinality counter metric in TSDB with low cardinality labels

### ISSUE THREAD

**Issue by mbrancato** [prometheus/prometheus#11458]
### What did you do?

I have a counter metric (e.g. `events_total`) being collected from a custom app. The prometheus config limits the labels collected.

The resulting metric has ~12 labels in prometheus, all of which are extremely low cardinality (normally 1 value) and static, one label (`service_id`) that is approximately 650 values, and another metric (`dataset`) that is related to the `service_id` but will only vary by about 3. So basically there are about 30 possible values for `dataset`, but for each `service_id` value, it will only be paired with at most 2-3 `dataset` values.

So the labels and number of values looks like:
- `__name__`: 1
- `container`: 1
- `job`: 1
- `service_id`: 650
- `dataset`: 30
- `namespace`: 1
- `prometheus`: 1

And this metric is being collected from thousands of pods, but the other high-cardinality labels like `pod` are dropped because pods are constantly rotating, leaving only approximately 12 labels like the labels above.

Prometheus is extremely slow returning these metrics, and will complain that it cannot load the metrics into memory even for a simple `sum()` over a small timeframes like 5 minutes.

### What did you expect to see?

I expect the total combination of label values to make the cardinality of the `events_total` metric be approximately 3000.

### What did you see instead? Under which circumstances?

Using `promtool tsdb analyze`, the output shows:

```
Highest cardinality labels:
31021 id
23975 name
16709 container_id
7544 uid
7402 pod
...
621 service_id

Highest cardinality metric names:
...
534322 events_total

```

Where `events_total` is basically the second highest cardinality metric name in the TSDB.

### System information

`Linux 5.10.90+ x86_64`

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@273d60c69592
  build date:       20221007-15:57:09
  go version:       go1.19.2
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: podMonitor/my-namespace/my-app/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - my-namespace
  scrape_interval: 30s
  metrics_path: /metrics/
  relabel_configs:
  - source_labels:
    - job
    target_label: __tmp_prometheus_job_name
  - action: drop
    source_labels:
    - __meta_kubernetes_pod_phase
    regex: (Failed|Succeeded)
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_app_name
    - __meta_kubernetes_pod_labelpresent_app_name
    regex: (my-app);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_label_workload
    - __meta_kubernetes_pod_labelpresent_workload
    regex: (my-app);true
  - action: keep
    source_labels:
    - __meta_kubernetes_pod_container_port_name
    regex: user-port
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_container_name
    target_label: container
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - target_label: job
    replacement: my-namespace/my-app
  - target_label: endpoint
    replacement: user-port
  - regex: __name__
    action: labeldrop
  - regex: endpoint
    action: labeldrop
  - regex: pod
    action: labeldrop
  - regex: instance
    action: labeldrop
  - regex: container_id
    action: labeldrop
  - regex: pod_ip
    action: labeldrop
  - regex: interface
    action: labeldrop
  - source_labels:
    - __address__
    target_label: __tmp_hash
    modulus: 1
    action: hashmod
  - source_labels:
    - __tmp_hash
    regex: 0
    action: keep
  metric_relabel_configs: []
```
