### ISSUE TITLE
add default sample_limit (and all other *_limit) to global

### ISSUE THREAD

**Issue by mblaschke-daimlertruck** [prometheus/prometheus#11494]
### Proposal

it's possible to set `global.scrape_interval` and `global.scrape_timeout` which acts as a default value for all scrapes.
please also add all limits eg `sample_limit` as `global.sample_limit` so it can act as default as well.

eg:
```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 20s
  
  body_size_limit: 10MB
  sample_limit: 20000
  label_limit: 20
  label_value_length_limit: 200
  target_limit: 100
```

if `sample_limit` set in scrape it should override the `global.sample_limit`.

related to https://github.com/prometheus-operator/prometheus-operator/issues/5119 (prometheus operator team is asking for this feature in prometheus server)
