### ISSUE TITLE
mac promethues health check api 404

### ISSUE THREAD

**Issue by vklonghml** [prometheus/prometheus#11492]
### What did you do?

curl -v -k "http://127.0.0.1:9090/-/healthy", failed with 404

### What did you expect to see?

200 return

### What did you see instead? Under which circumstances?

*   Trying 127.0.0.1:9090...
* Connected to 127.0.0.1 (127.0.0.1) port 9090 (#0)
> GET /-/healthy HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Vary: Origin
< X-Content-Type-Options: nosniff
< Date: Wed, 26 Oct 2022 03:01:59 GMT
< Content-Length: 19
<
404 page not found
* Connection #0 to host 127.0.0.1 left intact

### System information

Darwin 21.4.0 arm64

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@8b07537df0d3
  build date:       20221007-15:57:40
  go version:       go1.19.2
  platform:         darwin/amd64
```

### Prometheus configuration file

```yaml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MTk4MzYyOTMsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJtaW5pbyJ9.OhIR_9egYYTtmz06YeXdRUlBo7i2_GF4nwGbK7_vxHoJszIbDahMmQbtVvh7n-GW_pR1gN27HeAWhLEQ72-XQg
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['127.0.0.1:9000']
```

### Alertmanager version

```text
null
```

### Alertmanager configuration file

```yaml
null
```

### Logs

```text
null
```
