### ISSUE TITLE
HTTP2 does not work

### ISSUE THREAD

**Issue by cvetomir-todorov** [prometheus/prometheus#11536]
### What did you do?

I added OpenTelemetry Prometheus exporter to my .NET web application which uses HTTP2 and a self-signed TLS certificate.

Opening the `/metrics` in the browser succeeds and I can see my web app metrics there:
```
# TYPE http_server_duration_ms histogram
# UNIT http_server_duration_ms ms
# HELP http_server_duration_ms measures the duration of the inbound HTTP request
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="0"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="5"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="10"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="25"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="50"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="75"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="100"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="250"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="500"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="750"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="1000"} 0 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="2500"} 1 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="5000"} 1 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="7500"} 1 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="10000"} 1 1667584295233
http_server_duration_ms_bucket{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage",le="+Inf"} 1 1667584295233
http_server_duration_ms_sum{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage"} 1103.3289 1667584295233
http_server_duration_ms_count{http_flavor="2.0",http_host="localhost:31011",http_method="POST",http_scheme="https",http_status_code="200",http_target="/CecoChat.Contracts.Messaging.Send/SendMessage"} 1 1667584295233

# EOF
```

I am running prometheus via docker compose:
```yaml
version: '3'
networks:
  cecochat:
services:
  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: cecochat-prometheus
    hostname: prometheus
    networks: &networks
      - cecochat
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
```

The `prometheus.yml` looks like this:
```yaml
global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "cecochat"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    enable_http2: true
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:31001"
          - "localhost:31011"
```

### What did you expect to see?

I expected to see in Prometheus the same metrics I am able to see in the browser.

### What did you see instead? Under which circumstances?

Under all circumstances:
* I am not seeing the metrics
* I am seeing the following error: 
```
ts=2022-11-04T18:06:42.073Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=cecochat target=https://localhost:31011/metrics msg="Scrape failed" err="Get \"https://localhost:31011/metrics\": dial tcp 127.0.0.1:31011: connect: connection refused"
ts=2022-11-04T18:06:42.149Z caller=scrape.go:1328 level=debug component="scrape manager" scrape_pool=cecochat target=https://localhost:31001/metrics msg="Scrape failed" err="Get \"https://localhost:31001/metrics\": dial tcp 127.0.0.1:31001: connect: connection refused"
```
* Additionally I am seeing this message:
```
ts=2022-11-04T18:10:29.991Z caller=tls_config.go:195 level=info component=web msg="TLS is disabled." http2=false
```

### System information

Docker 20.10.21, Brave browser 1.45.118, Ubuntu 22.04.1, Linux 5.15.0-52-generic x86_64

### Prometheus version

```text
2.39.1
```
