### ISSUE TITLE
Relabeling: Using a labelname in a regex (to use the labelname's value)

### ISSUE THREAD

**Issue by thernstig** [prometheus/prometheus#11556]
### Proposal

In relabeling config, let's say I have saved a value in a label like `__tmp_port`. I then want to match some port in Kubernetes service discovery 

```yaml
  relabel_configs:
    - source_labels: [ __meta_kubernetes_pod_container_port_number ]
      action: keep
      regex: ${__tmp_port}
```

If the value of `__meta_kubernetes_pod_container_port_number` and `__tmp_port` are both `8080`, it will keep this target. It could possibly be used in `replacement` as well.

I would like to be able to use any existing `__` value in the regex, even the ones found from service discovery such as `__meta_kubernetes_pod_container_port_number`.

It solves e.g. https://github.com/prometheus/prometheus/issues/3756

**Comment by juliusv** [comment]
Since I'm reviewing #11564, I would like to understand a full use case example for this. Like, why would you put something into `__tmp_port` vs. just using a static value for the comparison? Referring to the linked issue, is it so you can compare an annotation label to a port label or something like that?

**Comment by thernstig** [comment]
The usage of `${__tmp_port}` was just to exemplify that I might have saved a _port_ from a previous step. This example is contrieved:

```yaml
metadata:
 annotations:            # containername:scheme:port:path:scrapespeed
   prometheus.io/scrape_1: "server:https:8585:/metrics:normal"
```

```yaml
  relabel_configs:
    - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape_1 ]
      action: replace
      target_label: __tmp_port
      regex: "[^:]+:[^:]+:([^:]+):[^:]+:[^:]+" 
    - source_labels: [ __meta_kubernetes_pod_container_port_number ]
      action: keep
      regex: ${__tmp_port}
```

So you are correct in your assumption this was about "comparing an annotation label to a port label" in this case.

But I do think the usage servers a great purpose for many other cases in servidce
