### ISSUE TITLE
Add relabel action inverse to drop 

### ISSUE THREAD

**Issue by Evedel** [prometheus/prometheus#11616]
### Proposal

# Problem

Want to propose a different approach to solve https://github.com/prometheus/prometheus/issues/3996.

This issue is known and multiple threads exist with people crafting workarounds.

The original issues showed an example config
```
metric_relabel_configs:
      - source_labels: ['__name__']
        regex: foo_total
        action: keep
      - source_labels: ['__name__']
        regex: bar_total
        action: keep
```
which is very human-readable but would result in a drop of all metrics.
For this particular case, the author proposed a workaround, which was effective and still easy to understand:
```
metric_relabel_configs:
      - source_labels: ['__name__']
        regex: '(foo_total|bar_total)'
        action: keep
```

<details>
  <summary>More complicated example </summary>
    We were configuring which metrics to send to the remote write destination. Still possible to overcome with the initially proposed workaround, but it is now much harder to reason with, fragile (notice now added union of `instance_3` and `job_name_1`).

    ```
    // what would be ideal to use
    write_relabel_configs:
          - source_labels: [prometheus_instance,job]
            regex: (instance_1|instance_2);job_name_1
            action: keep
          - source_labels: [prometheus_instance,recording_rule_group]
            regex: instance_3;recording_rule_group_1
            action: keep


    // what we ended up using
    write_relabel_configs:
          - source_labels: [prometheus_instance,job,recording_rule_group]
            regex: '(instance_1|instance_2|instance_3);(job_name_1|);(recording_rule_group_1|)'
            action: keep
          - source_labels: [prometheus_instance,job]
            regex: 'instance_3;job_name_1'
            action: drop
    ```
</details>

# Proposal

Add `action: append` (`action: keep_union`?) to relabel config, with the following logic:
- all other relabeling actions work as before (including drop on `drop` and `keep`)
- if relabeling config has `action: append` => the label set is dropped if none of `action: append` is satisfied
- this logic can be driven by adding temporary label `__meta_prometheus_model_relabel_append`
  - `__meta_prometheus_model_relabel_append = ""` => there were no `append` actions, relabel as usual
  - `__meta_prometheus_model_relabel_append = "true"` => append actions exist and at least one succeeded, "keep" label set
  - `__meta_prometheus_model_relabel_append = "false"` => append actions exist and none succeeded, "drop" label set

[PoC](https://github.com/Evedel/prometheus/blob/relabel-action-append-2/model/relabel/relabel.go#L244-L252)

**Comment by roidelapluie** [comment]
I would like to avoid changing the logic of relabel rules; which are ordered but independent. keep_union action seems confusing and by the name I can not tell how I could use multiple ones.

But, as an alternative, Prometheus supports the following:

```
metric_relabel_configs:
      - source_labels: ['__name__']
        target_label: __tmp_keep
        regex: foo_total
        replacement: yes
      - source_labels: ['__name__']
        target_label: __tmp_keep
        regex: bar_total
        replacement: yes
      - source_labels: [__tmp_keep]
        regex: yes
        action: keep
      - regex: __keep
        action: labeldrop
```
