### ISSUE TITLE
PromQL parser mistakingly interpreting UTF8 escape character

### ISSUE THREAD

**Issue by brancz** [prometheus/prometheus#11629]
### What did you do?

We use the PromQL parser in the [Parca](https://parca.dev/) project. We noticed something interesting when label values contained the `\x2d` value. Ultimately we noticed that the PromQL parser interprets this, not as the string value, but rather interprets the UTF-8 escape character, which in this case is the dash (`-`).

A resulting inconsistency can be triggered using the following config:

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          faulty_label: \x2d
```

Then query Prometheus, for example using the `prometheus_build_info` metric.

<img width="1406" alt="Screenshot 2022-11-25 at 17 18 20" src="https://user-images.githubusercontent.com/4546722/204024603-627160b3-4542-45d5-854f-5c51272753fd.png">

If we then use the UI to copy the label-matcher, and insert it into the query and query, however, we get an empty result.

<img width="1920" alt="Screenshot 2022-11-25 at 17 23 38" src="https://user-images.githubusercontent.com/4546722/204024704-aceb69ec-c35e-42ac-879d-1f21dc4d875f.png">

Only if we explicitly escape the label value do we get the result we were looking for with the previous query:

<img width="1920" alt="Screenshot 2022-11-25 at 17 24 17" src="https://user-images.githubusercontent.com/4546722/204024831-83e28088-d0bd-4e0d-bf87-6ab53b772937.png">

### What did you expect to see?

I expected one of the following two, for Prometheus' behavior to be consistent within itself:

* The PromQL parser retains the actual string literal and does not interpret the UTF-8 escape character.
* Table renders the label-value in its escaped form, the autocompletion suggests the label-value in its escaped form, and therefore copying the matcher by clicking on it in the table also uses the escaped form.

### What did you see instead? Under which circumstances?

Described in the first section.

### System information

Darwin 21.6.0 arm64

### Prometheus version

```text
$ ./prometheus --version
prometheus, version 2.40.3 (branch: HEAD, revision: 84e95d8cbc51b89f1a69b25dd239cae2a44cb6c1)
  build user:       root@692b092db288
  build date:       20221124-09:15:54
  go version:       go1.19.3
  platform:         darwin/arm64
```
```


### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          faulty_label: \x2d
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
n/a
```
