### ISSUE TITLE
proxy_write: Extended authentication support

### ISSUE THREAD

**Issue by metzgertie** [prometheus/prometheus#11626]
### Proposal

While setting up [Grafana Agent] on in a third-party environment, I stumbled on their support for proxy_write which mirrors prometheus. As Grafana simply mirrors the features in the agent in the upstream prometheus repository, I'm making the initial feature request here. 

The issue is, while setting up the agent I hit the proxy which requires a login.  Currently you need to pass the basic-auth login via URL which has some issues. To simplify the basic-auth login I would like to have the additional optional properties `username` and `password`. 

```yaml
proxy_url: https://some-proxy.internal.network
  # optional
  username: $some_proxy_user
  password: $some_proxy_password 
```

Thanks for all your work and consideration. 

[Grafana Agent]: https://github.com/grafana/agent
