### ISSUE TITLE
Unnecessary ipv6 dns lookup (AAAA)

### ISSUE THREAD

**Issue by dougEfresh** [prometheus/prometheus#11624]
### What did you do?

I disabled ipv6 via kernel flag `ipv6.disable=1`. However, Prometheus still does AAAA lookups for DNS names. This is a waste of resources and also fills up my DNS logs with NXDOMAIN queries (I use dnsmasq)

### What did you expect to see?

I expect to not see AAAA queries when ipv6 is disabled .

### What did you see instead? Under which circumstances?

If you use a hostname in your static_config yaml, a lookup for AAAA and A occurs. 

### System information

Linux 5.15.77-1-lts x86_64

### Prometheus version

```text
prometheus, version 2.40.2 (branch: tarball, revision: 2.40.2)
  build user:       someone@builder
  build date:       20221117-19:38:59
  go version:       go1.19.3
  platform:         linux/amd64

```
```


### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "files"
    file_sd_configs:
    - files:
      - 'static/*.yaml'
  - job_name: "node"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9100",  "ghost:9100" ]
```
```


### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```
