### ISSUE TITLE
Relabel labeldrop action part lable is not removed in kubernetes_sd_configs

### ISSUE THREAD

**Issue by eudore** [prometheus/prometheus#11667]
### What did you do?

use kubernetes_sd_configs discovery endpoint and node, labeldrop action not remove all regexp match labels.

Deploy configuration in prometheus configuration file.

kube version`Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compi
ler:"gc", Platform:"linux/amd64"}`

### What did you expect to see?

`kubernetes-cadvisor` job drop label `__meta_kubernetes_node_labelpresent_.*`.

`kubernetes-endpoints` job drop label `__meta_kubernetes_service_.*` and `__meta_kubernetes_pod_labelpresent_.*`.

### What did you see instead? Under which circumstances?

get targets `/api/v1/targets?state=active` response body:
```json
{
  "status": "success",
  "data": {
    "activeTargets": [
      {
        "discoveredLabels": {
          "__address__": "kubernetes.default.svc:443",
          "__meta_kubernetes_node_address_Hostname": "node1",
          "__meta_kubernetes_node_address_InternalIP": "10.0.16.2",
          "__meta_kubernetes_node_label_beta_kubernetes_io_arch": "amd64",
          "__meta_kubernetes_node_label_beta_kubernetes_io_os": "linux",
          "__meta_kubernetes_node_label_kubernetes_io_arch": "amd64",
          "__meta_kubernetes_node_label_kubernetes_io_hostname": "node1",
          "__meta_kubernetes_node_label_kubernetes_io_os": "linux",
          "__meta_kubernetes_node_labelpresent_beta_kubernetes_io_arch": "true",
          "__meta_kubernetes_node_labelpresent_beta_kubernetes_io_os": "true",
          "__meta_kubernetes_node_labelpresent_kubernetes_io_arch": "true",
          "__meta_kubernetes_node_labelpresent_kubernetes_io_hostname": "true",
          "__meta_kubernetes_node_labelpresent_kubernetes_io_os": "true",
          "__meta_kubernetes_node_labelpresent_node_kubernetes_io_exclude_from_external_load_balancers": "true",
          "__meta_kubernetes_node_labelpresent_node_role_kubernetes_io_control_plane": "true",
          "__meta_kubernetes_node_name": "node1",
          "__metrics_path__": "/api/v1/nodes/node1/proxy/metrics/cadvisor",
          "__scheme__": "https",
          "__scrape_interval__": "15s",
          "__scrape_timeout__": "10s",
          "instance": "node1",
          "job": "kubernetes-cadvisor",
          "node": "node1"
        },
        "labels": {
          "instance": "node1",
          "job": "kubernetes-cadvisor",
          "node": "node1"
        },
        "scrapePool": "kubernetes-cadvisor",
        "scrapeUrl": "https://kubernetes.default.svc:443/api/v1/nodes/node1/proxy/metrics/cadvisor",
        "globalUrl": "https://kubernetes.default.svc:443/api/v1/nodes/node1/proxy/metrics/cadvisor",
        "lastError": "",
        "lastScrape": "2022-12-03T13:58:23.720265736Z",
        "lastScrapeDuration": 0.09163899,
        "health": "up",
        "scrapeInterval": "15s",
        "scrapeTimeout": "10s"
      },
      {
        "discoveredLabels": {
          "__address__": "kubernetes.default.svc:443",
          "__meta_kubernetes_node_address_Hostname": "node1",
          "__meta_kubernetes_node_address_InternalIP": "10.0.16.2",
          "__meta_kubernetes_node_label_beta_kubernetes_io_arch": "amd64",
          "__meta_kubernetes_node_label_beta_kubernetes_io_os": "linux",
          "__meta_kubernetes_node_label_kubernetes_io_arch": "amd64",
          "__meta_kubernetes_node_label_kubernetes_io_hostname": "node1",
          "__meta_kubernetes_node_label_kubernetes_io_os": "linux",
          "__meta_kubernetes_node_name": "node1",
          "__metrics_path__": "/api/v1/nodes/node1/proxy/metrics/cadvisor",
          "__scheme__": "https",
          "__scrape_interval__": "15s",
          "__scrape_timeout__": "10s",
          "instance": "node1",
          "job": "kubernetes-cadvisor-succes",
          "node": "node1"
        },
        "labels": {
          "instance": "node1",
          "job": "kubernetes-cadvisor-succes",
          "node": "node1"
        },
        "scrapePool": "kubernetes-cadvisor-succes",
        "scrapeUrl": "https://kubernetes.default.svc:443/api/v1/nodes/node1/proxy/metrics/cadvisor",
        "globalUrl": "https://kubernetes.default.svc:443/api/v1/nodes/node1/proxy/metrics/cadvisor",
        "lastError": "",
        "lastScrape": "2022-12-03T13:58:23.84483725Z",
        "lastScrapeDuration": 0.108395637,
        "health": "up",
        "scrapeInterval": "15s",
        "scrapeTimeout": "10s"
      },
      {
        "discoveredLabels": {
          "__address__": "172.18.166.174:80",
          "__meta_kubernetes_endpoint_address_target_kind": "Pod",
          "__meta_kubernetes_endpoint_address_target_name": "metrics-proxy-5b8bfc7bf8-thvpg",
          "__meta_kubernetes_endpoint_node_name": "node1",
          "__meta_kubernetes_endpoint_port_name": "http",
          "__meta_kubernetes_endpoint_port_protocol": "TCP",
          "__meta_kubernetes_endpoint_ready": "true",
          "__meta_kubernetes_endpoints_label_app": "metrics-proxy",
          "__meta_kubernetes_endpoints_name": "metrics-proxy",
          "__meta_kubernetes_namespace": "kube-public",
          "__meta_kubernetes_pod_container_image": "nginx:1.22-alpine",
          "__meta_kubernetes_pod_container_name": "eudore-endpoint",
          "__meta_kubernetes_pod_controller_kind": "ReplicaSet",
          "__meta_kubernetes_pod_controller_name": "metrics-proxy-5b8bfc7bf8",
          "__meta_kubernetes_pod_host_ip": "10.0.16.2",
          "__meta_kubernetes_pod_ip": "172.18.166.174",
          "__meta_kubernetes_pod_label_app": "metrics-proxy",
          "__meta_kubernetes_pod_label_pod_template_hash": "5b8bfc7bf8",
          "__meta_kubernetes_pod_labelpresent_app": "true",
          "__meta_kubernetes_pod_labelpresent_pod_template_hash": "true",
          "__meta_kubernetes_pod_name": "metrics-proxy-5b8bfc7bf8-thvpg",
          "__meta_kubernetes_pod_node_name": "node1",
          "__meta_kubernetes_pod_phase": "Running",
          "__meta_kubernetes_pod_ready": "true",
          "__meta_kubernetes_pod_uid": "f5e65e1d-6329-4615-a115-3a6fc18b5ff3",
          "__meta_kubernetes_service_annotationpresent_kubectl_kubernetes_io_last_applied_configuration": "true",
          "__meta_kubernetes_service_annotationpresent_prometheus_io_port": "true",
          "__meta_kubernetes_service_annotationpresent_prometheus_io_probe": "true",
          "__meta_kubernetes_service_annotationpresent_prometheus_io_scrape": "true",
          "__meta_kubernetes_service_label_app": "metrics-proxy",
          "__meta_kubernetes_service_labelpresent_app": "true",
          "__meta_kubernetes_service_name": "metrics-proxy",
          "__metrics_path__": "/metrics",
          "__scheme__": "http",
          "__scrape_interval__": "15s",
          "__scrape_timeout__": "10s",
          "job": "kubernetes-endpoints"
        },
        "labels": {
          "instance": "172.18.166.174:80",
          "job": "kubernetes-endpoints"
        },
        "scrapePool": "kubernetes-endpoints",
        "scrapeUrl": "http://172.18.166.174:80/metrics",
        "globalUrl": "http://172.18.166.174:80/metrics",
        "lastError": "",
        "lastScrape": "2022-12-03T13:58:16.177871712Z",
        "lastScrapeDuration": 0.002578264,
        "health": "up",
        "scrapeInterval": "15s",
        "scrapeTimeout": "10s"
      },
      {
        "discoveredLabels": {
          "__address__": "172.18.166.189:9090",
          "__meta_kubernetes_endpoint_address_target_kind": "Pod",
          "__meta_kubernetes_endpoint_address_target_name": "prometheus-server-774869668-jm9t9",
          "__meta_kubernetes_endpoint_node_name": "node1",
          "__meta_kubernetes_endpoint_port_name": "http",
          "__meta_kubernetes_endpoint_port_protocol": "TCP",
          "__meta_kubernetes_endpoint_ready": "true",
          "__meta_kubernetes_endpoints_label_k8s_app": "prometheus-server",
          "__meta_kubernetes_endpoints_name": "prometheus-server",
          "__meta_kubernetes_namespace": "kube-public",
          "__meta_kubernetes_pod_container_image": "prom/prometheus:v2.40.5",
          "__meta_kubernetes_pod_container_name": "prometheus-server",
          "__meta_kubernetes_pod_controller_kind": "ReplicaSet",
          "__meta_kubernetes_pod_controller_name": "prometheus-server-774869668",
          "__meta_kubernetes_pod_host_ip": "10.0.16.2",
          "__meta_kubernetes_pod_ip": "172.18.166.189",
          "__meta_kubernetes_pod_label_k8s_app": "prometheus-server",
          "__meta_kubernetes_pod_label_pod_template_hash": "774869668",
          "__meta_kubernetes_pod_labelpresent_k8s_app": "true",
          "__meta_kubernetes_pod_labelpresent_pod_template_hash": "true",
          "__meta_kubernetes_pod_name": "prometheus-server-774869668-jm9t9",
          "__meta_kubernetes_pod_node_name": "node1",
          "__meta_kubernetes_pod_phase": "Running",
          "__meta_kubernetes_pod_ready": "true",
          "__meta_kubernetes_pod_uid": "bb2f981e-311a-46c8-b61d-d870483229d2",
          "__meta_kubernetes_service_annotationpresent_prometheus_io_port": "true",
          "__meta_kubernetes_service_annotationpresent_prometheus_io_scrape": "true",
          "__meta_kubernetes_service_label_k8s_app": "prometheus-server",
          "__meta_kubernetes_service_labelpresent_k8s_app": "true",
          "__meta_kubernetes_service_name": "prometheus-server",
          "__metrics_path__": "/metrics",
          "__scheme__": "http",
          "__scrape_interval__": "15s",
          "__scrape_timeout__": "10s",
          "job": "kubernetes-endpoints"
        },
        "labels": {
          "instance": "172.18.166.189:9090",
          "job": "kubernetes-endpoints"
        },
        "scrapePool": "kubernetes-endpoints",
        "scrapeUrl": "http://172.18.166.189:9090/metrics",
        "globalUrl": "http://172.18.166.189:9090/metrics",
        "lastError": "",
        "lastScrape": "2022-12-03T13:58:19.729223841Z",
        "lastScrapeDuration": 0.009500856,
        "health": "up",
        "scrapeInterval": "15s",
        "scrapeTimeout": "10s"
      }
    ],
    "droppedTargets": []
  }
}
```

### System information

Linux 3.10.0-1160.11.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.40.5 (branch: HEAD, revision: 44af4716c86138869aa621737139e6dacf0e2550)
  build user:       root@70f803b28803
  build date:       20221201-12:50:06
  go version:       go1.19.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  namespace: kube-public
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-endpoints'
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        regex: true
        action: keep
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
      - regex: __meta_kubernetes_(endpoints_labelpresent|service)_(.*)
        action: labeldrop
      - regex: __meta_kubernetes_pod_(labelpresent|annotation|annotationpresent|container_port)_(.*)
        action: labeldrop
    - job_name: 'kubernetes-cadvisor'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        target_label: __metrics_path__
        regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
      - regex: __meta_kubernetes_node_(annotation|labelpresent|annotationpresent)_(.*)
        action: labeldrop
    - job_name: 'kubernetes-cadvisor-succes'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        target_label: __metrics_path__
        regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
      - regex: __meta_kubernetes_node_labelpresent_(.*)
        action: labeldrop
      - regex: __meta_kubernetes_node_(annotation|labelpresent|annotationpresent)_(.*)
        action: labeldrop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: kube-public
  labels:
    name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: prometheus-server
  template:
    metadata:
      labels:
        k8s-app: prometheus-server
    spec:
      containers:
      - image: prom/prometheus:v2.40.5
        name: prometheus-server
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--storage.tsdb.retention=24h"
        - "--web.console.libraries=/usr/share/prometheus/console_libraries"
        - "--web.console.templates=/usr/share/prometheus/consoles"
        - "--web.enable-lifecycle"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/prometheus"
          name: data
        - mountPath: "/etc/prometheus"
          name: config-volume
      serviceAccountName: prometheus    
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        configMap:
          name: prometheus-configuration
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus-server
  namespace: kube-public
  labels:
    k8s-app: prometheus-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090 
  selector:
    k8s-app: prometheus-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics", "/metrics/cadvisor"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kube-public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kube-public
```
