### ISSUE TITLE
Prometheus scrape target URL incorrectly resolves localhost

### ISSUE THREAD

**Issue by thedeepc** [prometheus/prometheus#11722]
### What did you do?

Using VMWare, with two VMs running concurrently, such that:

- Virtual Machine 1: Running Prometheus, attempting to scrape target URL **https://localhost:8086** (attempting to scrape endpoint on same machine)
- Virtual Machine 2: Running DNS server with sample IP **12.34.56.78** (DNS requests are routed here from Virtual Machine 1)

With that setup, we checked on the Prometheus UI's **/targets?search=** endpoint to view the target to verify that the service was up (and being scraped).

### What did you expect to see?

We expected the scrape target URL **https://localhost:8086** to succeed, as our previous version of Prometheus (v2.35.0) was successful in the past (we recently upgraded to v2.39.1).

### What did you see instead? Under which circumstances?

We got the following error for the target scrape URL, with the service presenting as down:
`Get "http://localhost:8086/metrics": dial tcp: lookup localhost on 12.34.56.78:53: no such host`

### System information

Windows Server 2019

### Prometheus version

```text
prometheus, version 2.39.1 (branch: HEAD, revision: dcd6af9e0d56165c6f5c64ebbc1fae798d24933a)
  build user:       root@7c59f010d6a7
  build date:       20221007-16:03:13
  go version:       go1.19.2
  platform:         windows/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 1 minute. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 1 minute. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'bugreport'
    static_configs:
      - targets: ['localhost:8086']
```
