### ISSUE TITLE
TSDB: No warning or error when creating series collisions via metric relabeling

### ISSUE THREAD

**Issue by juliusv** [prometheus/prometheus#11725]
### What did you do?

Run Prometheus like this to drop the disambiguating `quantile` label from the `go_gc_duration_seconds` summary:

```
global:
  scrape_interval: 5s
    
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
  metric_relabel_configs:
  - action: keep
    source_labels: [__name__]
    regex: go_gc_duration_seconds
  - action: labeldrop
    target_label: quantile
```

For reference, the underlying metrics are:

```bash
# HELP go_gc_duration_seconds A summary of the pause duration of garbage collection cycles.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 6.6283e-05
go_gc_duration_seconds{quantile="0.25"} 7.8936e-05
go_gc_duration_seconds{quantile="0.5"} 0.000126586
go_gc_duration_seconds{quantile="0.75"} 0.000198849
go_gc_duration_seconds{quantile="1"} 0.000247392
go_gc_duration_seconds_sum 0.001408357
go_gc_duration_seconds_count 10
```

### What did you expect to see?

Some kind of warning about multiple series being mapped into one, like an out-of-order / duplicate timestamp ingestion error and / or a scrape failure.

### What did you see instead? Under which circumstances?

No error or warning. The first series is ingested (with the dropped label removed), but the others are not. Or at least they are not visible in queries. This way I can lose a bunch of series without ever knowing.

This is due to the fact that multiple series from one scrape are written to the same Appender, but that Appender does not compare timestamps within its own batched set of series, only with its own initial minimum valid time:

https://github.com/prometheus/prometheus/blob/c3fac587ef3c7d515e319844042ee0dddab54cbc/tsdb/head_append.go#L344

Maybe the Appender could be made to check samples within one append?

### System information

Linux 6.0.12-arch1-1 x86_64

### Prometheus version

```text
2.40.5
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s
    
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
  metric_relabel_configs:
  - action: keep
    source_labels: [__name__]
    regex: go_gc_duration_seconds
  - action: labeldrop
    target_label: quantile
```
