### ISSUE TITLE
Alerts are not closed at Opsgenie receiver

### ISSUE THREAD

**Issue by oalimerko** [prometheus/prometheus#11759]
### What did you do?

I am using AlertManager to send alerts to Opsgenie. If an alert is resolved on backend (prometheus/alertmanager),at Opsgenie the alert remains open.It looks like AlertManager wouldn’t send to Opsgenie any update/notification "Hey Opsgenie, alert is already resolved".I also tried the config `send_resolved: true` in alertmanager.yaml but did not help.

### What did you expect to see?

In case alert is resolved in prometheus,it should be closed at Opsgenie as well.

### What did you see instead? Under which circumstances?

**Alerts remain open at Opsgenie.**

How to reproduce?
Suppose you have the alerts rules below:
1. ContainerCpuUsage > 80 -->P4
2. ContainerCpuUsage > 90 -->P3
3. ContainerCpuUsage > 95 -->P2

- Stress CPU to reach 81% load,at this point you will get a P4 alert.
- Stress CPU further to reach 91% load,now you will get a P3 alert and the P4 still remains open.
- Stress CPU further to reach 96% load,now a P2 alert is fired.P3 & P4 remain open.
- Why P3 & P4 remain open it's clear.Because CPU reaches the 100% load step by step.In total are fired 3 alerts because CPU needs 10m to get from 1% load to 100%,the load is increased gradually and this is the reason why at 80% a P4 is fired,at 90% P3 and so on.

After P2 alert is fired,P3 and P4 are not anymore updated,so they are not getting any new notification/signal from alertmanager/prometheus.For P2 the counter is increased to 4 and for P3 & P4 counter remains 1.In other words,inhibit_rules prevents sending new notifications (emails, messages, etc) to recipients about the alerts, but does not inactive them.Therefore the counter for alerts P3 & P4 remains 1 but both alerts remain open.Until here all work as designed.

Return the CPU load back to normal.
- All alerts P2,P3,P4 are resolved in prometheus(not any more firing).
- P2 alert is always closed at Opsgenie.
- P3 alert sometimes get closed sometimes not.
- P4 alert for the most of the time remains open at Opsgenie.I have to close it manually.

**The issue is why not all alerts are cloed at Opsgenie if they are already resolved in prometheus?**

### System information

Linux 5.4.0-1091-azure x86_64

### Prometheus version

```text
Prometheus Version: 2.13.1
```

### Alertmanager version

```text
Alertmanager Version: 0.24.0
```

### Alertmanager configuration file

```yaml
Below are inhibit_rules i am using

"global":
  "resolve_timeout": "5m"
"inhibit_rules":
- "equal":
  - "namespace"
  - "alertname"
  "source_match":
    "severity": "critical"
  "target_match_re":
    "severity": "warning|info"
- "equal":
  - "namespace"
  - "alertname"
  "source_match":
    "severity": "warning"
  "target_match_re":
    "severity": "info"
"receivers":
- "name": "Opsgenie-Receiver"
  "opsgenie_configs":
  - "api_key": "xxx"
    "api_url": "https://opsgenie.example.com/"
    "send_resolved": true                             //Note this parameter
    "http_config":
      "proxy_url": "http://10.0.0.1"
    "responders":
    - "name": "Opsgenie-Receiver"
      "type": "team"
    priority: '{{ if eq .GroupLabels.severity "critical" }}P2{{ else if eq .GroupLabels.severity "high" }}P3{{ else if eq .GroupLabels.severity "error" }}P3{{ else if eq .GroupLabels.severity "alert" }}P3{{ else if eq .GroupLabels.severity "warning" }}P3{{ else if eq .GroupLabels.severity "info" }}P4{{ else if eq .GroupLabels.severity "information" }}P4{{ else }}P5{{ end }}'
  #"webhook_configs":
  #- "url": "http://10.0.0.1"
"route":
  "group_by":
  - "namespace"
  - "cluster"
  - "severity"
  "group_interval": "5m"
  "group_wait": "30s"
  "receiver": "Opsgenie-Receiver"
  "repeat_interval": "4h"
  "routes":
  - "match":
      "alertname": "Watchdog"
    "receiver": "Watchdog"
    "repeat_interval": "3m"
  - "match":
      "severity": "critical"
    "receiver": "Opsgenie-Receiver"
  - "match":
      "severity": "critical|warning"
    "receiver": "Opsgenie-Receiver"
```
```


### Logs

_No response_
