### ISSUE TITLE
BUG: nomad_sd_configs does not support "datacenter" key

### ISSUE THREAD

**Issue by devminded** [prometheus/prometheus#11776]
### What did you do?

Tried using `nomad_sd_configs` according to documentation at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#nomad_sd_config `prom/promtheus:latest` does not start with the following error:

```
$ promtool check config /local/prometheustest.yml
Checking /local/prometheustest.yml
  FAILED: parsing YAML file /local/prometheustest.yml: yaml: unmarshal errors:
  line 17: field datacenter not found in type nomad.plain
```

datacenter is missing in https://github.com/prometheus/prometheus/blob/49f775d8a0d76532fae36c0392d929bbf110577a/discovery/nomad/nomad.go#L76-L84

compared to consul.go https://github.com/prometheus/prometheus/blob/49f775d8a0d76532fae36c0392d929bbf110577a/discovery/consul/consul.go#L112-L121

### What did you see instead? Under which circumstances?

```
$ promtool check config /local/prometheustest.yml
Checking /local/prometheustest.yml
  FAILED: parsing YAML file /local/prometheustest.yml: yaml: unmarshal errors:
  line 17: field datacenter not found in type nomad.plain
```

### System information

Linux Ubuntu 22.04

### Prometheus version

```text
prometheus, version 2.41.0 (branch: HEAD, revision: c0d8a56c69014279464c0e15d8bfb0e153af0dab)
  build user:       root@d20a03e77067
  build date:       20221220-10:40:45
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090

- job_name: service-metrics
  sample_limit: 10000
  scheme: http
  nomad_sd_configs:
    - server: 'http://172.30.195.6:4646'
      datacenter: 'dc1'
```
