### ISSUE TITLE
Support tags filter on nomad service discovery

### ISSUE THREAD

**Issue by devminded** [prometheus/prometheus#11775]
### Proposal

Use the same way of filtering services by `tags` as we can do with consul_sd_configs.
This let's us have a single job "service-metrics" that auto-detects, filters and scrapes any service which are marked with `tags=prometheus,metrics` .
Should also be backported to LTS version.

```yaml
- job_name: service-metrics
  sample_limit: 10000
  scheme: http
  nomad_sd_configs:
    - server: 'http://127.0.0.1:4646'
      datacenter: 'dc1'
      tags: ['prometheus', 'metrics']  # like with consul_sd_configs
  relabel_configs:
  - source_labels: [__meta_nomad_service_id]
    target_label: 'serviceid'
  - source_labels: [__meta_nomad_dc]
    target_label: 'dc'
  - source_labels: [__meta_nomad_service]
    target_label: 'service'
  - source_labels: [__meta_nomad_tags]
    regex: '.*?,environment=(.*?),.*'
    target_label: 'environment'
  - source_labels: [__meta_nomad_tags]
    regex: '.*?,metrics-path=(.*?),.*'
    target_label: '__metrics_path__'
```
