### ISSUE TITLE
Remote write stop sending samples

### ISSUE THREAD

**Issue by shadowofs** [prometheus/prometheus#11784]
### What did you do?

I use a prometheus to collect metrics, and write to an OpenTSDB remote storage.
Then all the prometheus remote metrics stoped to grow.
It looks like #10264 , but I am very sure the patch is merged.

I got the stack [goroutine.txt](https://github.com/prometheus/prometheus/files/10319460/goroutine.txt)

### What did you see instead? Under which circumstances?

Logs like "Skipping resharding, last successful send was beyond threshold" repeated for a while, then no more remote write logs.

Prometheus remote write metrics stoped growing, apparently it's blocked somewhere.

### System information

Linux 5.4.143.bsk.3-amd64 x86_64

### Prometheus version

```text
Version	2.33.5
Revision	abe39ffbb022aed5606e15fd46d9541c822e354f
Branch	bytedance-dev
BuildUser	root@leafboat-73428968
BuildDate	20220609-13:02:08
GoVersion	go1.17.8
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    cluster: erica
    collector: ksm-collector-1
    physical_cluster: erica-hl
    vdc: hl
remote_write:
- url: http://telecaster.byted.org/api/prometheus/align
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [metric_prefix, __name__]
    separator: ;
    regex: (.+);(.+)
    target_label: __name__
    replacement: $1.$2
    action: replace
  - separator: ;
    regex: (metric_prefix|bke_prometheus_stack_scrape)
    replacement: $1
    action: labeldrop
  follow_redirects: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500
```

### Logs
ts=2022-12-19T10:20:30.668Z caller=dedupe.go:112 component=remote level=warn remote_name=f9aa52 url=http://telecaster.byted.org/api/prometheus/align msg="Skipping resharding, last successful send was beyond threshold" lastSendTimestamp=1671414921 minSendTimestamp=1671445220
