### ISSUE TITLE
Prometheus fetching data from exporter even http_sd end point is DOWN

### ISSUE THREAD

**Issue by BrivinTech** [prometheus/prometheus#11781]
### What did you do?

Run a prometheus server with http_sd targets.
Prometheus fetching the targets from http API and collecting the metrics using exporter for those metrics.
Now make down the http_sd end point API. 

But, still prometheus fetches the metrics from the old targets.

### What did you expect to see?

Prometheus should stop the metric collection since the http_sd endpoint is DOWN

### What did you see instead? Under which circumstances?

Prometheus still collecting the metric values for the old targets

### System information

Linux

### Prometheus version

```text
2.40.3
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 900s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'snmp_exporter'
    #scheme: https
    http_sd_configs:
    - url: https://localhost/webnms/api/v1/me/targets
      tls_config:
        insecure_skip_verify: true
    metrics_path: /snmp
    params:
      module: [pm_mib]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: _meta_snmp_exporter_port
      replacement: "9116"
    - source_labels: [_meta_ems_name,_meta_snmp_exporter_port]
      separator: ":"
      target_label: host
    - target_label: __address__
      source_labels: [host]
    - action: labeldrop
      regex: "_meta_.+"
    - action: labeldrop
      regex: "host"
```
