### ISSUE TITLE
`scrape_samples_scraped` missing HELP metadata

### ISSUE THREAD

**Issue by samjewell** [prometheus/prometheus#11884]
### What did you do?

I downloaded and ran the Prometheus binary with the default config to scrape itself.

I found that:
- I could graph `scrape_samples_scraped` at `/graph` endpoint
- But viewing the metrics metadata at `/api/v1/metadata` there was no entry for `scrape_samples_scraped`

I'm trying to both:
- Understand better what this metric is, and
- Help other users of Grafana to gain the same understanding.

Within Grafana you can typically see the HELP part of the metric-metadata on hover in the metrics browser:
![image](https://user-images.githubusercontent.com/2903904/214284449-a83dd69d-3fc3-4f14-8b3f-f8f0021b1904.png)

But for this metric, there's nothing useful:
![image](https://user-images.githubusercontent.com/2903904/214263887-87e63d97-511c-4da8-ada9-8bbadea6d2df.png)

I'm interested in this metric in particular because I think it can help diagnose problems with people setting their scrape_interval much smaller than they need (and shipping data far too frequently). For example, as described here:
https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/changing-scrape-interval/#grafana-agent

### What did you expect to see?

HELP metadata for this metric both on the /api/v1/metadata endpoint and in Grafana (on hover, in the metrics-browser).

### What did you see instead? Under which circumstances?

No metadata

### System information

Darwin 21.6.0 arm64

### Prometheus version

```text
prometheus, version 2.40.4 (branch: HEAD, revision: 414d31aee6586a5f29e755ae059b7d7131f1c6c8)
  build user:       root@45956a3006ca
  build date:       20221129-11:04:07
  go version:       go1.19.3
  platform:         darwin/arm64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: [ "localhost:9090" ]
```
