### ISSUE TITLE
Filterable Alert Routing

### ISSUE THREAD

**Issue by sinkingpoint** [prometheus/prometheus#11929]
### Proposal

Currently, Prometheus sends every alert that fires to every configured alertmanager. This works well in simple setups, but we currently operate large, multi-tenant Prometheus servers which opens us up to the situation wherein one tenant can overwhelm Alertmanager with a flood of alerts, degrading service for every other tenant. 

The traditional solution to this might be to shard Prometheus servers so that each Prometheus server gets a subset of tenants and map that to a separate Alertmanager. In our case however, our tenants are not _entirely_ disparate. They often share metrics in unpredictable ways. For example a platform team might export metrics about the platform that might be used by consumers of that platform. This makes a multi-Prometheus setup a lot more difficult to manage - we'd have to keep federation rules up to date, inevitably lagging behind teams who want to use a new metric and find it not federated into their instance.

What would be nicer would be to keep our monolithic Prometheus, but allow Prometheus to route alerts to different subsets of Alertmanagers based on some condition. Off the top of my head, this might look something like:

prometheus.yml:

```
  alertmanagers:
    # An empty "cluster" field would indicate the "default" cluster
  - scheme: https
    static_configs:
    - targets:
      - alertmanager-bouncer.svc.cfdata.org
  - scheme: https
    cluster: foo
    matchers:
      - some_label=foo
    static_configs:
    - targets:
      - alertmanager-foo.test.lol
    timeout: 30s
```

which would route alerts with the label `some_label=foo` to the foo cluster, and everything else to a default cluster. There's obviously other ways this might be accomplished (e.g. allowing alerts to specify a cluster themselves), but at least this way it would be an addition to the existing config schema and so would be a non breaking change.

I'm aware that Cortex does this with an "Alertmanager Distributer" (https://cortexmetrics.io/docs/proposals/scalable-alertmanager/) so this doesn't seem like too unique of a usecase. Maybe this logic could be in Prometheus itself?
