### ISSUE TITLE
Prometheus escape HTML tags for Telegram messenger

### ISSUE THREAD

**Issue by karabanov** [prometheus/prometheus#11955]
### What did you do?

Add alert rule:

```
  - alert: node_exporter down
    expr: up{job="node_exporter"} == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Сервер возможно недоступен"
      description: "<b>node_exporter</b> не отвечает больше 30 секунд - возможно сервер недоступен или экспортер сломался"
```

Add alert receiver:

```
receivers:
  # Default receiver
  - name: 'telegram'
    telegram_configs:
      - send_resolved: true
        api_url: https://api.telegram.org
        bot_token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
        chat_id: -xxxxxxxxxxxx
        message: '{{ template "telegram.mytemplate.message" . }}'
        parse_mode: 'HTML'
```

Add alert template:

```
{{ define "__alert_severity_prefix_title" -}}
    {{ if ne .Status "firing" -}}
    ✅ RESOLVED
    {{- else if eq .Labels.severity "critical" -}}
    ‼️  CRIT
    {{- else if eq .Labels.severity "warning" -}}
    ⚠️  WARN
    {{- else if eq .Labels.severity "info" -}}
    ℹ️  INFO
    {{- else -}}
    🔧 DEBUG
    {{- end }}
{{- end }}


{{ define "telegram.mytemplate.title" -}}
<b>{{ template "__alert_severity_prefix_title" . }} {{ .Labels.instance }}</b>
{{- end }}


{{ define "telegram.mytemplate.message" -}}
{{ range .Alerts }}
{{- if .Annotations.summary }}
{{ template "telegram.mytemplate.title" . }}
{{ .Annotations.summary }}
{{- end }}
{{- if .Annotations.description }}

{{ .Annotations.description }}

{{- end }}
{{- end }}
{{- end }}

```

### What did you expect to see?

In previous versions of Prometheus, alerts looked like this:

![telegram_normal_alert](https://user-images.githubusercontent.com/2456956/217648872-336a0e52-0f10-46de-b36e-b0b793568931.png)

### What did you see instead? Under which circumstances?

In the current version of Prometheus, alerts look like this:

![telegram_bad_alert](https://user-images.githubusercontent.com/2456956/217649030-e6a2d510-333a-4a8a-9730-d9ebf409e30f.png)

That is, HTML tags were escaped and transferred to Telegram as text

### System information

Linux 5.10.0-17-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

### Alertmanager version

```text
alertmanager, version 0.25.0 (branch: HEAD, revision: 258fab7cdd551f2cf251ed0348f0ad7289aee789)
  build user:       root@abe866dd5717
  build date:       20221222-14:51:36
  go version:       go1.19.4
  platform:         linux/amd64
```

### Logs

```text
prometheus         | ts=2023-02-08T21:02:05.980Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=node_exporter target="https://srv-test.xxxxxxxx.ru:55443/proxy?module=node_exporter" msg="Scrape failed" err="server returned HTTP status 502 Bad Gateway"
prometheus         | ts=2023-02-08T21:02:20.980Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=node_exporter target="https://srv-test.xxxxxxxx.ru:55443/proxy?module=node_exporter" msg="Scrape failed" err="server returned HTTP status 502 Bad Gateway"
alertmanager       | ts=2023-02-08T21:02:32.653Z caller=dispatch.go:163 level=debug component=dispatcher msg="Received alert" alert="node_exporter down[ea2a6da][active]"
prometheus         | ts=2023-02-08T21:02:35.980Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=node_exporter target="https://srv-test.xxxxxxxx.ru:55443/proxy?module=node_exporter" msg="Scrape failed" err="server returned HTTP status 502 Bad Gateway"
prometheus         | ts=2023-02-08T21:02:50.980Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=node_exporter target="https://srv-test.xxxxxxxx.ru:55443/proxy?module=node_exporter" msg="Scrape failed" err="server returned HTTP status 502 Bad Gateway"
alertmanager       | ts=2023-02-08T21:03:02.654Z caller=dispatch.go:515 level=debug component=dispatcher aggrGroup="{}/{instance!~\".*blabla.ru\",severity=~\"info|warning|critical\"}:{alertname=\"node_exporter down\", instance=\"srv-test.xxxxxxxx.ru\", job=\"node_exporter\", monitor=\"xxxxxxxx\", severity=\"critical\"}" msg=flushing alerts="[node_exporter down[ea2a6da][active]]"
alertmanager       | ts=2023-02-08T21:03:02.856Z caller=telegram.go:93 level=debug integration=telegram msg="Telegram message successfully published" message_id=31802 chat_id=-xxxxxxxxx
alertmanager       | ts=2023-02-08T21:03:02.856Z caller=notify.go:743 level=debug component=dispatcher receiver=telegram integration=telegram[0] msg="Notify success" attempts=1
prometheus         | ts=2023-02-08T21:03:05.979Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=node_exporter target="https://srv-test.xxxxxxxx.ru:55443/proxy?module=node_exporter" msg="Scrape failed" err="server returned HTTP status 502 Bad Gateway"
```
