### ISSUE TITLE
Prometheus encodes the colon character ':' from the target when constructing its scrape url

### ISSUE THREAD

**Issue by younesouhbi** [prometheus/prometheus#11956]
### What did you do?

I tried implementing a multiple target scrape as described in this documentation page: https://prometheus.io/docs/guides/multi-target-exporter/

The example in the documentation page uses the target http://prometheus.io as an example. However, in my case, I had something like http://example.com:8080, with the colon character present in order to specify a port to Blackbox Exporter

### What did you expect to see?

I expected the final url after all the transformations to have the colon in the target parameter. It should be: http://localhost:9115/probe?target=http://prometheus.io:8080&module=http_2xx

### What did you see instead? Under which circumstances?

http://localhost:9115/probe?target=http://prometheus.io%3A8080&module=http_2xx

### Prometheus version

Build version: 2.30.0

### Prometheus configuration file

```yaml
- job_name: "blackbox-exporter-rabbitmq"
      scrape_interval: 60s
      scrape_timeout: 59s
      metrics_path: /probe
      params:
        module: [tcp_connect]
        prefix: [rabbitmq]
      static_configs:
        - targets:
          - rabbitmq:5672
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115
```
