### ISSUE TITLE
When the mouse is placed in the labels column of the Target page, the "before relabeling" label cannot be displayed normally

### ISSUE THREAD

**Issue by iYerw** [prometheus/prometheus#11960]
### What did you do?

[Problems in video](https://www.awesomescreenshot.com/video/14701301?key=96f13438cdd12c47bfee8fbc0b95d86a)
The Targetsweb page cannot be displayed before relabeling

### What did you see instead? Under which circumstances?

容器镜像是  prom/prometheus:v2.42.0  

### Prometheus version

v2.42.0

### Prometheus configuration file

prometheus  config

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: kubernetes-node-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*):10250
    target_label: __address__
    replacement: ${1}:19100
    action: replace
  - source_labels: [__scheme__]
    separator: ;
    regex: (http|https)
    target_label: __scheme__
    replacement: http
    action: replace
  - source_labels: [__address__]
    separator: ;
    regex: (.*):19100
    target_label: instance
    replacement: ${1}
    action: replace
  kubernetes_sd_configs:
  - role: node
    kubeconfig_file: ""
    follow_redirects: true
```
