### ISSUE TITLE
Help/Description entry for recording rules

### ISSUE THREAD

**Issue by sayf-eddine-scality** [prometheus/prometheus#11969]
### Proposal

Today we have
- `HELP` entry for metrics
- `Description` and `Summary` for Alerting rules

But nothing for Recording rules, I think it will be beneficial to have/support a description entry for it

Example:
```
groups:
  - name: rules
    rules:
      - record: xxx:yyyy_yyy:zzzz
        expr: <PromQL expression>
        description: "foo bar"
```

This will help understanding the rule, generating automatic documentations etc
