### ISSUE TITLE
Remote_ Read is configured, but cannot read the metric written in influxDB

### ISSUE THREAD

**Issue by nsaikrishna15** [prometheus/prometheus#11968]
### What did you do?

I Have configured my opentelemetry collector to send span metrics to My remote InfluxDB, And configured this influxdb as remote_read in my prometheus. 

### What did you expect to see?

I expected to query this metrics from influxdb data on prometheus using remote_read and also I can use this prometheus endpoint as PROMETHEUS_SERVER_URL on jaeger so i can get SPM on jaeger.

### What did you see instead? Under which circumstances?

Here i am able to get the data initially from influx to prometheus and to jaeger monitoring dashboard. Now i am not getting that data, when i restart the prometheus deployment then i am able to get the data again. Why Do i need to restart the prometheus? I cannot see any error logs anywhere, 
tried read_recent: true flag also  But no use.

### System information

Kubernetes Version: v1.20.11

### Prometheus version

```text
prometheus:v2.24.0
Kubernetes Version: v1.20.11
```

### Prometheus configuration file

```yaml
remote_read:
- url: http://influxdb.monitoring.svc.cluster.local:8086/api/v1/prom/read?db=prometheus&u=user&p=password
  remote_timeout: 2m
  read_recent: true
```
