### ISSUE TITLE
Use strict YAML parsing for ruler config

### ISSUE THREAD

**Issue by wilguo** [prometheus/prometheus#11970]
### What did you do?

I created the following rule config (incorrect indentation on line 1):
```
  groups:
- name: Count greater than 5
  rules:
  - alert: CountGreaterThan5
    expr: ping_request_count > 5
     or: 10s
```

### What did you expect to see?

I expected prometheus rule validation to complain about invalid YAML. 

### What did you see instead? Under which circumstances?

Prometheus accepted the config and parsed it as 0 rule groups.

**Comment by wilguo** [comment]
I will be submitting a fix for this issue.

**Comment by roidelapluie** [comment]
I can not reproduce this.

**Comment by wilguo** [comment]
Hi Julien, were you able to see validation errors when using the ruler config above with wrong indentation? 

For me these were the steps I took to produce the error:
1. Followed this [guide](https://prometheus.io/docs/introduction/first_steps/) to set up prometheus
2. This is my `prometheus.yml` config
```
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```
3. This is my `rules.yml` config
```
  groups:
- name: Count greater than 5
  rules:
  - alert: CountGreaterThan5
    expr: ping_request_count > 5
     for: 10s
``` 
4. Ran `./prometheus --config.file=prometheus.yml` to start prometheus
5. Did not get any errors when starting up the server and saw this in the output
```
ts=2023-02-14T17:36:39.854Z caller=manager.go:974 level=info component="rule manager" msg="Starting rule manager..."
```

**Note:** 
When I tried doing the above steps but with this config instead (no rule group name)
```
groups:
- name:
  rules:
  - alert: CountGreaterThan5
    expr: ping_request_count > 5
     for: 10s
```
After starting the prometheus server, it would stop and give me the following errors in the logs
```
ts=2023-02-14T17:41:43.186Z caller=main.go:1197 level=info msg="Loading configuration file" filename=prometheus.yml
ts=2023-02-14T17:41:44.315Z caller=manager.go:1011 level=error component="rule manager" msg="loading groups failed" err="rules.yml: yaml: line 6: mapping values are not allowed in this context"
ts=2023-02-14T17:41:44.315Z caller=manager.go:1011 level=error component="rule manager" msg="loading groups failed" err="rules.yml: yaml: line 6: mapping values are not allowed in this context"
ts=2023-02-14T17:41:44.315Z caller=main.go:1223 level=error msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
ts=2023-02-14T17:41:44.315Z caller=main.go:852 level=info msg="Stopping scrape discovery manager..."
ts=2023-02-14T17:41:44.315Z caller=main.go:866 level=info msg="Stopping notify discovery manager..."
ts=2023-02-14T17:41:44.315Z caller=manager.go:988 level=info component="rule manager" msg="Stopping rule manager..."
ts=2023-02-14T17:41:44.315Z caller=manager.go:998 level=info component="rule manager" msg="Rule manager stopped"
ts=2023-02-14T17:41:44.337Z caller=main.go:1132 level=error err="error loading config from \"prometheus.yml\": one or more errors occurred while applying the new configuration (--config.file=\"prometheus.yml\")"
```

---

I also tested the config (with wrong indentation) using the unit tests in [`rulefmt_test.go`](https://github.com/prometheus/prometheus/blob/main/model/rulefmt/rulefmt_test.go) and the `errs` array was empty when calling `ParseFile()`
