### ISSUE TITLE
File discovery not remove targets sometimes

### ISSUE THREAD

**Issue by freesinger** [prometheus/prometheus#12007]
### What did you do?

I manage prometheus as a service in my ecs, config be like:
```service
[Unit]
Description=Prometheus Service
After=network.target network-online.target remote-fs.target nss-lookup.target

[Service]
ExecStart=/opt/prometheus/prometheus --config.file /etc/prometheus/prometheus.yml --web.enable-lifecycle --storage.tsdb.retention.time=30d --storage.tsdb.path=/mnt/prometheus/data
Restart=on-failure
RestartSec=60
StartLimitInterval=3600
StartLimitBurst=5
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
```

I use file discovery to manage targets for prometheus, however, when the file deleted in file discovery path, the targets turned to `DOWN` instead be removed.
T have tried `curl -X POST  http://localhost:9090/-/reload` and it not worked, but `systemctl restart prometheus` solved this problems and targets been removed after restart.

### What did you expect to see?

Targets should be removed after file deleted

### What did you see instead? Under which circumstances?

Targets turned into `DOWN` state, like this
![image](https://user-images.githubusercontent.com/20896930/220518198-2ca551d0-3b60-405b-97c7-b880f3e21d6b.png)

### System information

Linux 5.10.162-141.675.amzn2.x86_64

### Prometheus version

```text
prometheus, version 2.36.1 (branch: HEAD, revision: 3c0a100dec2950f23e91f7efbf8867750960807d)
  build user:       root@e59c79158868
  build date:       20220609-15:25:21
  go version:       go1.18.3
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 3.222.235.198:8012
rule_files:
  - "/etc/prometheus/rules/*.yml"
scrape_configs:
  - job_name: "nodes"
    file_sd_configs:
      - files:
        - "/etc/prometheus/nodes/*.yml"
        - "/etc/prometheus/metaservice/*.yml"
        refresh_interval: 2m
```

**Comment by freesinger** [comment]
Furthurmore, the `refresh_interval` in `file_sd_configs` seems not consistent with actual interval, I set `2m` in my config, after I update yaml file in `/etc/prometheus/nodes`, targets updated in seconds everytime.

**Comment by roidelapluie** [comment]
Hi freesinger,

Thank you for bringing this issue to our attention. Regarding the `refresh_interval` in `file_sd_configs`, I want to clarify that this interval is a fallback. By default, Prometheus uses inotify which notifies it instantly when there are changes in the target files. This is a feature and not a bug.

Regarding the issue of deleted files not being removed as targets, this could be a bug. I will take a look at the code to see if we are missing the deletion of files. In the meantime, you could try using `echo [] > targets.json` instead of `rm targets.json`. This will clear the contents of the `targets.json` file and will not result in a file deletion which may not be recognized by Prometheus.

Thank you for your contribution to the Prometheus project.

**Comment by freesinger** [comment]
@roidelapluie thanks for your answer.
I have tested and found it that the immediately reload could be the problem.
```shell
# hot reload config
pid=$(ps xu | grep prometheus | grep -v grep | awk '{print $2}')
if [ ! -z $pid ]; then
	curl -X POST http://127.0.0.1:9090/-/reload
fi
```
As you mentioned, `Prometheus uses inotify which notifies it instantly when there are changes in the target files`. Will this behavior lead inotify cannot notify the prometheus instance since I tell it to reload? Which contributes the ghost targets can only be removed by restart  promethesu process rather than hot reload.

**Comment by roidelapluie** [comment]
That is interesting, I will investigate.

**Comment by chrko** [comment]
It seems we are affected by this bug, too. We fixed our instances without restarting:

1. Placing a new file with the same name and `- targets: []` as content. Just an empty file was not enough.
2. Waiting (Kubernetes and) Prometheus getting aware of the "new" file.
3. Removing the file again.

We're currently running Prometheus v2.31.0 in Kubernetes. The affected instance have only file base SD like the following:
```yaml
  - job_name: 'blackbox-reachable-page'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
    - files:
      - ./scrapejobs/blackbox-2xx_*.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox-exporter.diagnostics:9115
```

The files are a config map mounted as a volume.
