### ISSUE TITLE
Remote Write - Data Lost

### ISSUE THREAD

**Issue by NiclasPe** [prometheus/prometheus#12029]
### What did you do?

I have an Local Prometheus Instance Running on docker. (The Server has 8gb of RAM Prometheus uses 2-4 GB) Its Collection Logs from an Kubernetes Cluster using Federation and Prometheus Operator, around 15 Windows Machines over Windows Exporter  and also 15 Linux Machines with Node Exporter. 
Now i want to wirite my Data to an remote Grafana Mimir running on an Server in the Datacenter. 
In front of Mimir is running an nginx reverse Proxy an LB. (Also all Docker) 
The Remote Wirte works, but in Mimir Datapoints are Missing, witch destroys my Dashboard. I Uploades 2 Example Pictures here

### What did you expect to see?

I expect to see the Same Graph on both Instances

### What did you see instead? Under which circumstances?

Local Prometheus
![Local Prometheus](https://user-images.githubusercontent.com/52936786/221914980-da831de4-e0b7-4eb1-b86b-5ceab43adb4b.png)
Mimir:
![221914985-870a2efc-5228-4ac9-af67-085265361cc0](https://user-images.githubusercontent.com/52936786/221918732-59d950e5-db52-4c98-854f-79f79f2a1c80.png)

### System information

Linux 5.15.0-60-generic x86_64

### Prometheus version

```text
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64

(All Containers are Latest Version)
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitoring: 'xxx'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'alert.rules'
  - /etc/prometheus/rules/*.yaml

# alert
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    static_configs:
    - targets: ['pushgateway:9091']

  - job_name: 'uptime-kuma'
    scrape_interval: 30s
    scheme: http
    basic_auth:
      username: 'xxx'
      password: 'xxx'
    static_configs:
    - targets: ['uptime-kuma:3001']

  - job_name: 'federate'
    scrape_interval: 8s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__!=""}'

    static_configs:
      - targets:
        - 'x.x.x.x:9090'


  - job_name: 'windows_linux_hosts'
    scrape_interval: 15s
    basic_auth:
      username: 'xxx'
      password: 'xxx'
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
    - files:
      - 'targets.json'





remote_write:
  - url: https://mimir.my-domain.org/api/v1/push
    basic_auth:
      username: xxx
      password: "xxx"
```
