### ISSUE TITLE
Incorrect metrics when using remote write when compared to scraping directly

### ISSUE THREAD

**Issue by fbongiovanni29** [prometheus/prometheus#12025]
### What did you do?

We're migrating to remote write via prometheus agent and expect to see the same or at least similar results when compared to our previous scraping method. 

Our remote write config is currently as it looks below, although I've tried tweaking the configuration dozens of times to no success:
```
remote_write:
- url: **********
  remote_timeout: 30s
  send_exemplars: true
  send_native_histograms: true
  follow_redirects: true
  enable_http2: true
  queue_config:
    capacity: 25000
    max_shards: 100
    min_shards: 1
    max_samples_per_send: 10000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 15s
    max_samples_per_send: 500
```

The grafana dashboards below represent what we're seeing on a health check. The old scrape looks like what we'd expect from a health check as it's a consistent up/down pattern. The remote write looks like there is something incorrect with it but I'm not quite sure what.

Remote write (incorrect):
<img width="1652" alt="Screen Shot 2023-02-27 at 1 48 05 PM" src="https://user-images.githubusercontent.com/2322727/221655243-9b379432-5854-4b02-895f-dd7c6521062f.png">

Old scraping (correct):
<img width="1659" alt="Screen Shot 2023-02-27 at 1 48 37 PM" src="https://user-images.githubusercontent.com/2322727/221655351-b9e8f0c8-44b9-4efa-a6f4-1d0e5274f32d.png">

### What did you expect to see?

Grafana dashboards look the same or at least more similar to what they looked like when we were scraping data.

### What did you see instead? Under which circumstances?

When using remote write, the dashboards do not look similar and appear to be incorrect.

### System information

Linux 5.4.228-131.415.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.40.6 (branch: HEAD, revision: e1506e7be89e4ce346851bf6bd2b024b70fb7cb1)
  build user:       root@f4224a878a14
  build date:       20221209-12:48:27
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
remote_write:
- url: **********
  remote_timeout: 30s
  send_exemplars: true
  send_native_histograms: true
  follow_redirects: true
  enable_http2: true
  queue_config:
    capacity: 25000
    max_shards: 100
    min_shards: 1
    max_samples_per_send: 10000
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 15s
    max_samples_per_send: 500
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
ts=2023-02-27T18:18:44.136Z caller=main.go:187 level=info msg="Experimental agent mode enabled."
ts=2023-02-27T18:18:44.137Z caller=main.go:556 level=info msg="Starting Prometheus Agent" mode=agent version="(version=2.40.6, branch=HEAD, revision=e1506e7be89e4ce346851bf6bd2b024b70fb7cb1)"
ts=2023-02-27T18:18:44.137Z caller=main.go:561 level=info build_context="(go=go1.19.4, user=root@f4224a878a14, date=20221209-12:48:27)"
ts=2023-02-27T18:18:44.137Z caller=main.go:562 level=info host_details="(Linux 5.4.228-131.415.amzn2.x86_64 #1 SMP Tue Dec 20 12:51:02 UTC 2022 x86_64 prometheus-server-7bb886f969-zhbql (none))"
ts=2023-02-27T18:18:44.137Z caller=main.go:563 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-02-27T18:18:44.137Z caller=main.go:564 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-02-27T18:18:44.139Z caller=web.go:559 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2023-02-27T18:18:44.140Z caller=main.go:1048 level=info msg="Starting WAL storage ..."
ts=2023-02-27T18:18:44.141Z caller=tls_config.go:232 level=info component=web msg="Listening on" address=[::]:9090
ts=2023-02-27T18:18:44.141Z caller=tls_config.go:235 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2023-02-27T18:18:44.143Z caller=db.go:337 level=info msg="replaying WAL, this may take a while" dir=data-agent/wal
ts=2023-02-27T18:18:44.145Z caller=db.go:388 level=info msg="WAL segment loaded" segment=0 maxSegment=0
ts=2023-02-27T18:18:44.145Z caller=main.go:1069 level=info fs_type=XFS_SUPER_MAGIC
ts=2023-02-27T18:18:44.145Z caller=main.go:1072 level=info msg="Agent WAL storage started"
ts=2023-02-27T18:18:44.145Z caller=main.go:1197 level=info msg="Loading configuration file" filename=/etc/config/prometheus.yml
ts=2023-02-27T18:18:44.147Z caller=dedupe.go:112 component=remote level=info remote_name=cab497 url=********************/api/v1/write msg="Starting WAL watcher" queue=cab497
ts=2023-02-27T18:18:44.147Z caller=dedupe.go:112 component=remote level=info remote_name=cab497 url=********************/api/v1/write msg="Starting scraped metadata watcher"
ts=2023-02-27T18:18:44.147Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-02-27T18:18:44.147Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-02-27T18:18:44.148Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-02-27T18:18:44.148Z caller=kubernetes.go:326 level=info component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
ts=2023-02-27T18:18:44.148Z caller=main.go:1234 level=info msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml totalDuration=2.851226ms db_storage=419ns remote_storage=431.561µs web_handler=248ns query_engine=194ns\
 scrape=229.326µs scrape_sd=1.016356ms notify=833ns notify_sd=3.865µs rules=163ns tracing=2.801µs
ts=2023-02-27T18:18:44.148Z caller=main.go:978 level=info msg="Server is ready to receive web requests."
ts=2023-02-27T18:18:44.224Z caller=dedupe.go:112 component=remote level=info remote_name=cab497 url=********************/api/v1/write msg="Replaying WAL" queue=cab497
ts=2023-02-27T18:18:50.447Z caller=dedupe.go:112 component=remote level=info remote_name=cab497 url=********************/api/v1/write msg="Done replaying WAL" duration=6.297764008s
```
