### ISSUE TITLE
Prometheus not honoring drop of ALERTS and ALERTS_FOR_STATE metrics

### ISSUE THREAD

**Issue by JDA88** [prometheus/prometheus#12026]
### What did you do?

Drop `ALERTS_FOR_STATE` and `ALERTS` metrics at the `remote_write` or the `scrape_configs` level

### What did you expect to see?

Successful drop of those metrics

### What did you see instead? Under which circumstances?

No matter what I try both metrics are still there and sent to the remote write

### System information

Windows 2019

### Prometheus version

```text
Prometheus 2.40.7
```

### Prometheus configuration file

```yaml
remote_write:

  write_relabel_configs:

  - source_labels: [__name__]
    regex: 'ALERTS_FOR_STATE|ALERTS|'
    action: drop


scrape_configs:
  - job_name: 'prometheus'

    - source_labels: [__name__]
      regex: 'ALERTS_FOR_STATE|ALERTS|'
      action: drop
```
