### ISSUE TITLE
Remote Write how to enable https with TLS

### ISSUE THREAD

**Issue by wenlive** [prometheus/prometheus#12109]
### What did you do?

I build a adapter just like promscale to suit prometheus remote storage.
I can use prometheus-remote /write /read to send data to postgresql or query from it without TLS. But it don't work when set tls_config for remote write/read.
Got error like this
```
ts=2023-03-09T02:32:28.585Z caller=dedupe.go:112 component=remote level=error remote_name=659059 url=http://localhost:9201/write msg="non-recoverable error" count=5 exemplarCount=0 err="server returned HTTP status 400 Bad Request: Client sent an HTTP request to an HTTPS server."
ts=2023-03-09T02:33:28.595Z caller=dedupe.go:112 component=remote level=error remote_name=659059 url=http://localhost:9201/write msg="non-recoverable error" count=5 exemplarCount=0 err="server returned HTTP status 400 Bad Request: Client sent an HTTP request to an HTTPS server."
```
I think this is because my adapteruses use `server.ListenAndServeTLS` when TLS config is set. But prometheus tsdb component always send http request.

tls_config  does not contain the scheme option，how to configuration it correctly?

my config yml
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    scheme : "https"
    static_configs:
      - targets: ["localhost:9090"]
remote_write:
  - url: "http://localhost:9201/write"
    tls_config:
      ca_file: "xxxx"
      cert_file: "xxxx"
      key_file: "xxxx"
    enable_http2: true
remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true
    tls_config:
      ca_file: "xxxx"
      cert_file: "xxxx"
      key_file: "xxxx"
    enable_http2: true
```

### What did you expect to see?

prometheus with tls sent an https request instead of http

### What did you see instead? Under which circumstances?

using the yml above it promethesu can't work with a https adapter Server

### System information

Linux 5.15.90.1-microsoft-standard-WSL2 x86_64

### Prometheus version

```text
prometheus, version 2.37.6 (branch: HEAD, revision: 8ade24a23af6be0f35414d6e8ce09598446c29a2)
  build user:       root@5f96027a7c3e
  build date:       20230220-09:36:40
  go version:       go1.19.6
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    scheme : "https"

    static_configs:
      - targets: ["localhost:9090"]
    # tls_config:
    #   ca_file: "xx"
    #   cert_file: "xx"
    #   key_file: "xx"
    #   min_version: "TLS10"
remote_write:
  - url: "http://localhost:9201/write"
    # scheme : "https"
    tls_config:
      ca_file: "xx"
      cert_file: "xx"
      key_file: "xx"
    enable_http2: true
      # min_version: "TLS10"
remote_read:
  - url: "http://localhost:9201/read"
    read_recent: true
    # scheme : "https"
    tls_config:
      ca_file: "xx"
      cert_file: "xx"
      key_file: "xx"
    enable_http2: true
      # min_version: "TLS10"
```

### Alertmanager version

```text
NONE
```

### Alertmanager configuration file

```yaml
NONE
```

### Logs

```text
NONE
```
