### ISSUE TITLE
We are experiencing a widespread issue with Prometheus to Alertmanager communication. Whenever an Alertmanager pod restarts, server logs 503 error to that individual pod. Other AM pods receive the alerts until they get restarted.

### ISSUE THREAD

**Issue by kirankh7** [prometheus/prometheus#12104]
### What did you do?

We are using Istio mesh to connect Prometheus to Alertmanager. Whenever an Alertmanager pod gets restarted, we get the following error. If we restart the Prometheus server error goes away, and able to establish a new connection to Alertmanager. Looks like Prometheus is caching these IPs, not getting fully closed.

To reproduce this issue, you can delete random alertmanager pod and you will see 
`err="server returned HTTP status 503 Service Unavailable"`

### What did you expect to see?

We expect the server to close the connection rather than keep it open as we run alertmanager in a cluster, and those alertmanager pods could get restarted anytime. 

```
    alerting:
      alert_relabel_configs:
      - action: labeldrop
        regex: replica
        replacement: $1
        separator: ;
      alertmanagers:
        - static_configs:
          - targets:
            - am-0.monitoring.svc.cluster.local:9093
            - am-1.monitoring.svc.cluster.local:9093
            - am-2.monitoring.svc.cluster.local:9093
```

### What did you see instead? Under which circumstances?

n/a

### System information

Linux chronicle-server-0 5.4.228-132.418.amzn2.x86_64 #1 SMP Wed Jan 25 23:14:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Prometheus version

```text
Prometheus Version: 2.42.0
Istio Version: v1.17
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 20s
  evaluation_interval: 1m
alerting:
  alert_relabel_configs:
    - separator: ;
      regex: replica
      replacement: $1
      action: labeldrop
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - alertmanager-0.alertmanager-headless.servicename.svc.cluster.local:9093
            - alertmanager-1.alertmanager-headless.servicename.svc.cluster.local:9093
            - alertmanager-2.alertmanager-headless.servicename.svc.cluster.local:9093
rule_files:
  - /etc/config/recording_rules.yml
  - /prometheus/alerting_rules.yml
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - server-0.server-headless.servicename.svc.cluster.local:9090
          - server-1.server-headless.servicename.svc.cluster.local:9090
  - job_name: alertmanager
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets:
          - alertmanager-0.alertmanager-headless.servicename.svc.cluster.local:9093
          - alertmanager-1.alertmanager-headless.servicename.svc.cluster.local:9093
          - alertmanager-2.alertmanager-headless.servicename.svc.cluster.local:9093
```

### Alertmanager version

```text
Alertmanager Version: 0.25.0
Istio Version: v1.17
```

### Alertmanager configuration file

```yaml
global:
  resolve_timeout: 1m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: web.hook
  group_by:
    - '...'
  continue: false
  routes:
    - receiver: reciver-name
      match:
        sr: "true"
      continue: false
      repeat_interval: 364d1h
  group_wait: 1s
  group_interval: 5m
  repeat_interval: 1h
receivers:
  - name: web.hook
    webhook_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
          enable_http2: true
        url: http://endpointurl:8003/
        max_alerts: 0
templates: []
```

### Logs

```text
ts=2023-03-07T21:34:40.312Z caller=scrape.go:1351 level=debug component="scrape manager" scrape_pool=alertmanager target=http://am-0.monitoring.svc.cluster.local:9093/metrics msg="Scrape failed" err="server returned HTTP status 503 Service Unavailable"
```
```

**Comment by roidelapluie** [comment]
Thank you for sharing the issue you are facing while connecting Prometheus to Alertmanager. 

Prometheus is not caching the IPs of the Alertmanager pods, it keeps the tcp connection alive, which is leading to the error when a pod gets restarted. One solution to this issue is to switch to using service discovery instead of relying on static_configs. 

I recommend using either dns_sd_configs or kubernetes_sd_configs for this purpose. Please find below the examples to configure Prometheus with these service discovery mechanisms:

### Kubernetes_sd_configs

```yaml
- job_name: alertmanager
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - monitoring
    selector:
      matchLabels:
        app: alertmanager
```

### dns_sd_configs

```yaml
- job_name: alertmanager
  dns_sd_configs:
  - names:
    - alertmanager-0.alertmanager-headless.servicename.svc.cluster.local:9093,
    - alertmanager-1.alertmanager-headless.servicename.svc.cluster.local:9093,
    - alertmanager-2.alertmanager-headless.servicename.svc.cluster.local:9093
    type: 'A'
    port: 9093
  relabel_configs:
  - source_labels: [__meta_dns_name]
    action: replace
    target_label: alertname
```

Please note that you would need to adjust the values in these examples based on your specific configuration, such as the namespaces, service names or DNS name.

Importantly, this applies to both scrape_configs and alerting. Both support service discovery.
