### ISSUE TITLE
Configuration field retention not found in type config.plain

### ISSUE THREAD

**Issue by jingslunt** [prometheus/prometheus#12139]
### What did you do?

set 
storage:
  tsdb:
    retention:
      time: 6553500

### What did you expect to see?

Configuration has something about retention time

### What did you see instead? Under which circumstances?

# ./promtool check config  prometheus.yml
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
  line 6: field retention not found in type config.plain

### System information

Linux 3.10.0-1062.12.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.42.0 (branch: HEAD, revision: 225c61122d88b01d1f0eaaee0e05b6f3e0567ac0)
  build user:       root@c67d48967507
  build date:       20230201-07:53:32
  go version:       go1.19.5
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
storage:
  tsdb:
    retention:
      time: 999999
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~".+"}'
        - '{__name__=~"job:.*"}'
    file_sd_configs:
      - files:
        - ./servers.yaml
rule_files:
  - "rules/*.rules"
```

### Alertmanager version

```text
none
```

### Alertmanager configuration file

```yaml
none
```
