### ISSUE TITLE
Spliting "for" into "active_for" and "inactive_for" to replace "keep_firing_for"

### ISSUE THREAD

**Issue by bo-er** [prometheus/prometheus#12219]
### Proposal

I have recently encountered network problems in production environments when using Prometheus and alertmanager, which leads to flappy alerts. The solution is to set a longer "for" value like several minutes, however, the price we pay is that once an abnormal situation occurs, prometheus waits 5 minutes before sending an alert. 
A solution to this is to split the "for" into "active_for" and "inactive_for". In my case I will just leave the "active_for" to be 10s, meaning that an alert is immediately sent when a promQL expression holds, meanwhile, "inactive_for" is set to 5min so that when the network is slow or disconnected for a short time, prometheus doesn't falsely send a resolved alert.

```
- alert: mysql_service_down
          expr: mysql:up == 0
          active_for: 10s
          inactive_for: 5m
          labels:
            level: CRITICAL
          annotations:
            detail: |
                Database is out of service
```

I think this proposal is better than the "keep_firing_for" solution.
