### ISSUE TITLE
Alert expression return no datapoints but alert firing periodically 

### ISSUE THREAD

**Issue by RainbowHerbicides** [prometheus/prometheus#12260]
### What did you do?

We have 4 instances of Prometheus servers that scrape similar set of targets (2 per location). Team had defined alert which have next expression:
```
name: replicator_no_replicated_events
expr: sum by (env,job) (irate(replicator_events_sum{env=~"(live1.*)|(live3)|(live4)|(live5)", job="kafka-journal-replicator-rbow"}[2m]))==0
for: 3m
```
and it was placed on all servers in the same manner via automatic pipeline (all configuration files are 1:1 copy of each other with exception of proxy servers). Hardware configuration is same per location.

### What did you expect to see?

1. Alert to be triggered if alert expression with return any datapoints == 0
2. Alert expression will return datapoints either via `promtool` request, or via `/graph`, or via `/query_range` API call for defined duration

Or opposite of mentioned above - no alert, since no datapoints present (or comply with `for` clause)

### What did you see instead? Under which circumstances?

On 3 servers out of 4 - I receive expected result (no alert, since there is no datapoints present that comply with alert expression). 1 produce really strange results:
1. No datapoints returned for expression `sum by (env,job) (irate(replicator_events_sum{env=~"(live1.*)|(live3)|(live4)|(live5)", job="kafka-journal-replicator-rbow"}[2m]))==0` for any period of time via any means of querying data
2. Expression `ALERTS_FOR_STATE{alertname="replicator_no_replicated_events"}` or `ALERTS{alertname="replicator_no_replicated_events"}` return datapoints and even trigger alert

This behaviour is only true for 1 server out of 4. `scrape_duration_seconds` is pretty much the same for all 4 servers (range between 4 - 9 seconds)

### System information

Linux 3.10.0-1160.62.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.37.6 (branch: HEAD, revision: 8ade24a23af6be0f35414d6e8ce09598446c29a2)
  build user:       root@5f96027a7c3e
  build date:       20230220-09:36:40
  go version:       go1.19.6
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 1m
  evaluation_interval: 1m
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 30s
    api_version: v2
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - <ip>:9093
      - <ip>:9093
      - <ip>:9093
      - <ip>:9093
rule_files:
- /etc/prometheus/alerts/*
- /etc/prometheus/generated_alerts/*
- /etc/prometheus/record_rules/*
scrape_configs:
- job_name: live1gcp_kubernetes_app_gcp
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{job=~"..*"}'
  scrape_interval: 1m
  scrape_timeout: 45s
  metrics_path: /federate
  scheme: http
  follow_redirects: true
  enable_http2: true
  metric_relabel_configs:
  - source_labels: [pod]
    separator: ;
    regex: (.*)
    target_label: alias
    replacement: $1
    action: replace
  - separator: ;
    regex: ^pod$
    replacement: $1
    action: labeldrop
  - separator: ;
    regex: ^service$
    replacement: $1
    action: labeldrop
  - source_labels: [namespace]
    separator: ;
    regex: ^(.+?)-.*$
    target_label: env
    replacement: ${1}
    action: replace
  - separator: ;
    regex: ^namespace$
    replacement: $1
    action: labeldrop
  - separator: ;
    regex: ^endpoint$
    replacement: $1
    action: labeldrop
  - separator: ;
    regex: ^prometheus_replica$
    replacement: $1
    action: labeldrop
  static_configs:
  - targets:
    - <some_random_url>
```

### Logs

```text
No anomalies even with DEBUG level
```
