### ISSUE TITLE
Native histogram federation not working

### ISSUE THREAD

**Issue by kaber2** [prometheus/prometheus#12305]
### What did you do?

I've added native histograms to some code of mine. The code is running on 40 servers, each one is running a prometheus instance which is scraped by a master server. "--enable-feature" native-histograms is enabled on all instances.

On each instance, I can see the values of the native histogram being properly ingested by prometheus. However on the master instance I can only see the values ingested locally, the entire series are missing for all servers being scraped. All other series from these servers is present.

### What did you expect to see?

Full time series from all servers being scrapped.

### What did you see instead? Under which circumstances?

Only locally ingested data present.

### System information

Linux 6.1.12-zen1+ #19 ZEN SMP PREEMPT Wed Mar 15 19:32:47 CET 2023 x86_64 x86_64 x86_64 GNU/Linux

### Prometheus version

```text
prometheus, version 2.44.0-rc.0 (branch: HEAD, revision: d70688038e5d444ab8beac53722df15d244038e4)
  build user:       root@c3e52c6dd464
  build date:       20230426-09:46:54
  go version:       go1.20.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
This is from the master server. As mentioned, each target node does have the data available, so I assume the problem is not on their side. 

  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job=~".*"}'

    static_configs:
      - targets:
        [...]
```
