### ISSUE TITLE
Log output doesn't need to be UTC

### ISSUE THREAD

**Issue by raxidex** [prometheus/prometheus#12347]
### What did you do?

Hello all.

I understand that the collected data is in UTC (https://prometheus.io/docs/introduction/faq/#can-i-change-the-timezone-why-is-everything-in-utc and https://github .com/prometheus/prometheus/issues/500), but I don't see why the logs need to be too.

I believe it is because of this line: https://github.com/prometheus/prometheus/blob/3c4802635d05af47ddf7358c0c079961b011c47b/documentation/examples/custom-sd/adapter-usage/main.go#L256

I'm asking this because I live in a country that is UTC -3, and the logs are being collected with the wrong time.

I'm using prometheus from helm kube-prometheus-stack, but I think the issue is in the prometheus binary itself.

I mounted a volume by creating an /etc/localtime with:
```
prometheus:
   prometheusSpec:
     volumeMounts:
       - name: tz-config
         mountPath: /etc/localtime
     volumes:
       - name: tz-config
         hostPath:
           path: /usr/share/zoneinfo/America/Sao_Paulo
```
Inside the pod the time was correct, but in the logs it still appeared with UTC.

Thanks in advance, Marcelo.

### What did you expect to see?

The timestamp in the logs in the correct timezone

### What did you see instead? Under which circumstances?

The timestamp is in UTC

### System information

BusyBox v1.34.1 (2022-10-25 00:07:12 UTC) multi-call binary.

### Prometheus version

```text
prometheus --version
prometheus, version 2.40.5 (branch: HEAD, revision: 44af4716c86138869aa621737139e6dacf0e2550)
  build user:       root@70f803b28803
  build date:       20221201-12:50:06
  go version:       go1.19.3
  platform:         linux/amd64
```
