### ISSUE TITLE
Remote read step hints appear inconsistent / difficult to use for subqueries

### ISSUE THREAD

**Issue by jlamillan** [prometheus/prometheus#12348]
### What did you do?

Remote read `ReadHints.StepMs` appears to be inconsistent for subqueries in terms of whether it represents the step for the inner _range query_, the outer _subquery_, or is coming from somewhere else e.g.

| PromQL        | Hints.StepMs           |  Hints.RangeMs          |
| ------------- |:-------------:|:-------------:|
| sum_over_time(up{}[15m:1m])[60m:10m]     | 60000Ms / 1m | 0Ms |
| sum_over_time(up{}[15m:1m])[60m:]   | 60000Ms / 1m | 0Ms |
| sum_over_time(up{}[15m])[60m:10m]     | 600000Ms / 10m | 900000Ms / 15m |
| sum_over_time(up{}[15m])[60m:]    | 20000Ms / 20s | 900000Ms / 15m |

Having access to the entire query, scrap config, and global settings, I can deduce what the step represents and where it originated from. However I do not have enough context at the storage layer to do the same. 

### What did you expect to see?

As a remote-read implementer, I would like to know the step of the _subquery_. I would also like to know whether the `hints.step` represents the _range query_ or the _subquery_ in order to fetch the correct resolution from the backend metric store.

### What did you see instead? Under which circumstances?

It does not appear that I can safely use the `ReadHints.StepMs` to determine the appropriate resolution to fetch from the metric store.

For example, the difference between the first and second subqueries below is that the _second_ explicitly sets a resolution of `1m` of the inner range query (rather than leaving it to the default, which is _also 1m_). Yet, from the perspective of the `ReadRequest` handler, this minor (noop) change results in an order of magnitude difference in the value of `ReadHints.StepMs` storage layer sees. 

_Default step range query of 1m results in Query.Hints.Step=10m_
```
> sum_over_time(up{}[15m])[60m:10m]
|---- prompb.ReadRequest  ==>> Query.Hints.Func=sum_over_time, Query.StartTime=2023-05-10 10:05:00, Query.EndTime=2023-05-10 11:20:00, Query.Hints.Step=10m
```
_Explicitly set step range query to 1m, overrides step of outer query results in Query.Hints.Step=1m_
```
> sum_over_time(up{}[15m:1m])[60m:10m]
|---- prompb.ReadRequest  ==>> Query.Hints.Func=sum_over_time, Query.StartTime=2023-05-10 10:00:00, Query.EndTime=2023-05-10 11:20:00, Query.Hints.Step=1m
```

### Prometheus version

```text
Prometheus, version v2.43.0
go.buf.build/protocolbuffers/go/prometheus/prometheus, version v1.3.8
google.golang.org/protobuf, version v1.30.0
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 20s
  evaluation_interval: 20s
remote_write:
  - url: http://localhost:9900/write # Custom remote-writer implementation 
remote_read:
  - url: http://localhost:9900/read # Custom remote-writer implementation 
    read_recent: true
scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets:
        - localhost:9090 # Prometheus itself 
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_
