### ISSUE TITLE
Prometheus doesnot log any error when service discovery file is not present at startup

### ISSUE THREAD

**Issue by PaurushGarg** [prometheus/prometheus#12356]
### What did you do?

Ran Prometheus with the attached configuration to scrape targets using `file_sd_configs`. I forgot to place the ecs_sd_target.json file at Prometheus startup and noticed that Prometheus didn't log any messages that indicate the sd_file was missing. I was also running Prometheus with log level mode as debug. 

Upon triaging noticed that, the intent of code [here](https://github.com/prometheus/prometheus/blob/3c4802635d05af47ddf7358c0c079961b011c47b/discovery/file/file.go#L343) might be to log message if the sd_file is not present, but its not getting logged - as upon absence of sd_file the listFiles() [here](https://github.com/prometheus/prometheus/blob/3c4802635d05af47ddf7358c0c079961b011c47b/discovery/file/file.go#L338) doesn't return any path and hence code doesn't enter [this](https://github.com/prometheus/prometheus/blob/3c4802635d05af47ddf7358c0c079961b011c47b/discovery/file/file.go#L338) for loop. However, Prometheus does log error message when the path is not watchable, but does not log message if `sd_file` is missing in that path.

Similarly, also found if the `sd_file` is not empty but the `targetgroups` is not present inside the `sd_file`, the Prometheus does not log the message intended [here](https://github.com/prometheus/prometheus/blob/3c4802635d05af47ddf7358c0c079961b011c47b/discovery/file/file.go#L412), b/c code doesn't evaluate this condition as tg==nil. 

### What did you expect to see?

I expected to see some logs printed out to indicate if `sd_file` is missing.

### What did you see instead? Under which circumstances?

I didn't see any logs regarding this - and usual operation.

### System information

macos ventura arm64

### Prometheus version

```text
2.43.0
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    file_sd_configs:
    - files:
        - 'ecs_sd_target.json'
```
