### ISSUE TITLE
Unable to mount multiple volumes using prometheus statefulset.

### ISSUE THREAD

**Issue by rajani-konreddy** [prometheus/prometheus#12360]
### What did you do?

When we are trying to create separate volume for data and backup using Prometheus statefulset.

Prometheus stateful set spec:
![image](https://github.com/prometheus/prometheus/assets/104550831/4c921dc2-1eb3-4b22-ad6a-978ca26fa945)

### What did you expect to see?

Should be able to mount multiple volumes with Statefulset

### What did you see instead? Under which circumstances?

It is throwing below an error. 

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Prometheus.spec.storage): unknown field "volumeClaimTemplates" in com.coreos.monitoring.v1.Prometheus.spec.storage

### Prometheus configuration file

```yaml
volumeMounts:
    - name: prometheus-data
      mountPath: /data
      subPath: prometheus-db
    - name: prometheus-backup
      mountPath: /prometheus
    command:
    - "/opt/myaddition.sh"
  storage:
    volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        resources:
          requests:
            storage: {{ .Values.Prometheus.cluster_1_deploy.spec.data.storage }}
        volumeMode: Filesystem
        storageClassName: {{ .Values.Prometheus.cluster_1_deploy.spec.data.storageClassName }}
   - metadata:
        name: prometheus-backup
      spec:
        resources:
          requests:
            storage: {{ .Values.Prometheus.cluster_1_deploy.spec.backup.storage }}
        volumeMode: Filesystem
        storageClassName: {{ .Values.Prometheus.cluster_1_deploy.spec.backup.storageClassName }}
```
