### ISSUE TITLE
Support service discovery for the PVE platform

### ISSUE THREAD

**Issue by Zheaoli** [prometheus/prometheus#12388]
### Proposal

The PVE platform is one of the most popular KVM platforms for multiple OS like Linux, Windows, etc. FYI https://pve.proxmox.com/wiki/Main_Page

We can support service for this platform. 

I propose to add `pve_sd_config` field in configuration file like below.

```yaml
pve_sd_config:
  api_endpoint_address: "endpoint for pve server"
  api_endpoint_port: "endpoint port for pve server"
  api_endpoint_user: "user for pve server"
  api_endpoint_password: "password for pve server"
  api_ssl_verify: "verify ssl certificate, bool"
  api_timeout: "timeout for api requests, int"
  api_ssl_pem: "path to ssl pem file"
  exclude_vms: "list of vms to exclude from monitoring"
  include_vms: "list of vms to include in monitoring"
```

If this proposal has been accepted, I would like take handle to maintain the code and PR
