### ISSUE TITLE
Prometheus err message :     get segment range: segments are not sequential

### ISSUE THREAD

**Issue by tobythom** [prometheus/prometheus#12407]
### What did you do?

Upgrade Cloud Environment with new AMI ID of the application and restarted the Prometheus. 

During upgrade , we backup and restore Prometheus data folder in EBS so that we have data retention after Disaster Recovery/Upgrade

### What did you expect to see?

After Upgrade/DR, all processes was started, expected Prometheus service to work as it is. 

### What did you see instead? Under which circumstances?

Prometheus service was not working .

From the logs ,we are getting   opening storage failed: get segment range: segments are not sequential

ls -lah var/opt/prometheus/data/wal:
total 207M
76M -rw-r--r-- 1 root root 76M Mar 8 19:07 00000002
128M -rw-r--r-- 1 root root 128M Mar 8 19:07 00000001
832K -rw-r--r-- 1 root root 832K Mar 8 19:07 00000772
32K -rw-r--r-- 1 root root 31K Mar 8 19:07 00000775
832K -rw-r--r-- 1 root root 832K Mar 8 19:07 00000774
4.0K drwxr-xr-x 2 root root 4.0K Mar 8 19:07 checkpoint.00000771
832K -rw-r--r-- 1 root root 832K Mar 8 19:07 00000773
/Data/DRFresh/var/opt/prometheus/data/wal/checkpoint.00000771:
total 32K
32K -rw-r--r-- 1 root root 32K Mar 8 19:07 00000000 

### System information

Linux 10.21.20.12

### Prometheus version

```text
Version	2.26.0
Revision	3cafc58827d1ebd1a67749f88be4218f0bab3d8d
Branch	HEAD
BuildUser	root@a67cafebe6d0
BuildDate	20210331-11:56:23
GoVersion	go1.16.2
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 30s
  evaluation_interval: 5m
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    path_prefix: /health/
    timeout: 30s
    api_version: v2
    static_configs:
    - targets:
      - localhost:9010
rule_files:
- /var/opt/prometheus/rules/*.yaml
- /var/opt/prometheus/mgmtrules/*.yaml
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /var/opt/prometheus/targets/*.json
    refresh_interval: 5m
  static_configs:
  - targets:
    - localhost:9090
```

### Alertmanager version

```text
NA
```

### Alertmanager configuration file

```yaml
NA
```

### Logs

```text
May 25 22:27:38 prom_startup.pl[20535]: Starting prometheus..[/var/opt/prometheus/prometheus --config.file=/var/opt/prometheus/devicehm.yml --storage.tsdb.path=/var/opt/prometheus/data --web.listen-address=127.0.0.1:9090 --web.enable-admin-api --log.level=debug --storage.tsdb.retention.size 1.25GB --query.lookback-delta=360s]
level=info ts=2023-05-25T22:27:38.117Z caller=main.go:418 msg="Starting Prometheus" version="(version=2.26.0, branch=HEAD, revision=3cafc58827d1ebd1a67749f88be4218f0bab3d8d)"
level=info ts=2023-05-25T22:27:38.117Z caller=main.go:423 build_context="(go=go1.16.2, user=root@a67cafebe6d0, date=20210331-11:56:23)"
level=info ts=2023-05-25T22:27:38.117Z caller=main.go:424 host_details="(Linux 5.10.110-yocto-standard #1 SMP PREEMPT Wed Oct 5 22:09:26 UTC 2022 x86_64 (none))"
level=info ts=2023-05-25T22:27:38.117Z caller=main.go:425 fd_limits="(soft=1024, hard=4096)"
level=info ts=2023-05-25T22:27:38.117Z caller=main.go:426 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2023-05-25T22:27:38.120Z caller=web.go:540 component=web msg="Start listening for connections" address=127.0.0.1:9090
level=info ts=2023-05-25T22:27:38.120Z caller=main.go:795 msg="Starting TSDB ..."
level=info ts=2023-05-25T22:27:38.121Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1670905814378 maxt=1672617600000 ulid=01GNRDM1ERBHWW1SA85FX24Y89
level=info ts=2023-05-25T22:27:38.121Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1672617614381 maxt=1674367200000 ulid=01GQCJ4YXZG757CESD5WJ7RDQZ
level=info ts=2023-05-25T22:27:38.121Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1674367200000 maxt=1676116800000 ulid=01GS0FTSS8B3FWESEYZJF98ER8
level=info ts=2023-05-25T22:27:38.121Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2023-05-25T22:27:38.121Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1676116800000 maxt=1677866400000 ulid=01GTMMEX0D48QC04QEKS2A92XJ
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1677866400000 maxt=1678060800000 ulid=01GTTDVGDKHJNAQ2RMCDXVQ1EK
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1678060800000 maxt=1678255200000 ulid=01GV07848ATWYAPWG0VRP27CDS
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1678276801000 maxt=1678284000000 ulid=01GV0VSD6ZHRBAWGA513RACFAK
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1678284000000 maxt=1678291200000 ulid=01GV12N4EZZ8BPSMEN22RPWDPT
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1678255201000 maxt=1678276800000 ulid=01GV12Q12K5H2K9DX9JH8H4KX6
level=info ts=2023-05-25T22:27:38.122Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1678291200000 maxt=1678298400000 ulid=01GV19GVQ09TPB6P5G1SZHA55H
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:668 msg="Stopping scrape discovery manager..."
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:682 msg="Stopping notify discovery manager..."
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:704 msg="Stopping scrape manager..."
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:678 msg="Notify discovery manager stopped"
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:664 msg="Scrape discovery manager stopped"
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:698 msg="Scrape manager stopped"
level=info ts=2023-05-25T22:27:38.122Z caller=manager.go:934 component="rule manager" msg="Stopping rule manager..."
level=info ts=2023-05-25T22:27:38.122Z caller=manager.go:944 component="rule manager" msg="Rule manager stopped"
level=info ts=2023-05-25T22:27:38.122Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2023-05-25T22:27:38.122Z caller=main.go:872 msg="Notifier manager stopped"
level=error ts=2023-05-25T22:27:38.122Z caller=main.go:881 err="opening storage failed: get segment range: segments are not sequential"
```
