### ISSUE TITLE
client_allowed_sans is not working

### ISSUE THREAD

**Issue by duj4** [prometheus/prometheus#12400]
### What did you do?

I tried to enable client_allowed_sans in web-config.file so that in mTLS it could verify the client hostname.

### What did you expect to see?

I hope this could work.

### What did you see instead? Under which circumstances?

Prometheus complained error as below:
msg="Unable to parse configuration" err="yaml: unmarshal errors:\n line 8: field client_allowed_sans not found in type web.TLSStruct".

### System information

Linux 4.18.0-425.19.2.el8_7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.44.0
  build user: root@739e8181c5db
  build date: 20230514-06:18:11
  go version: go1.20.4
  platform: linux/amd64
  tags: netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
web-config.yml:
tls_server_config:
  cert_file: <path-to-cert>
  key_file: <path-to-key>

  client_allowed_sans:
  - <client_hostname>

  client_auth_type: RequireAndVerifyClientCert
  client_ca_file: <path-to-ca>
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
msg="Unable to parse configuration" err="yaml: unmarshal errors:\n line 8: field client_allowed_sans not found in type web.TLSStruct".
```
