### ISSUE TITLE
The rewriting of __scrape_interval__ in relabel_configs does not take effect but uses the global __scrape_interval__ configuration

### ISSUE THREAD

**Issue by mao9085** [prometheus/prometheus#12449]
### What did you do?

Prometheus version：prometheus-2.43.0.linux-amd64
prometheus-2.30.0.rc.linux-amd64

My prometheus.yml configs：
```
relabel_configs:
      - target_label: __scrape_interval__
        replacement: 44s
```

### What did you expect to see?

I want to be able to rewrite the __scrape_interval__ tag in the relabel_configs configuration

### What did you see instead? Under which circumstances?

After the above configuration, the overwritten __scrape_interval__ does not take effect and instead uses the __scrape_interval__ configuration in global. I don't know why, I saw the https://github.com/prometheus/prometheus/releases/tag/v2.30.0-rc.0 version has support for supporting __scrape_interval__ rewrite.

### System information

Centos7

### Prometheus version

```text
prometheus-2.43.0.linux-amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s
  scrape_timeout: 5s
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['ip:9093']
rule_files: [rules/*.yml]

scrape_configs:
  - job_name: blackbox_http_2xx
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - 'http://www.baidu.com'
        labels:
          blackboxId: '1'
          urlhash: http://www.baidu.com
          systemId: a26607d749f645baa242e25cd3642e01
          groupId: UUID
          scrape: 16s
    relabel_configs:
      - target_label: __scrape_interval__
        replacement: 44s
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'ip:9098'
```
