### ISSUE TITLE
host_networking_host in Docker SD doesn't work 

### ISSUE THREAD

**Issue by BeniaminK** [prometheus/prometheus#12444]
### What did you do?

I tried service discovery for Docker containers that run in the `host` network type, thus I used:

```yaml
scrape_configs:
- job_name: docker_sd
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
    - host_networking_host: localhost
```

However I cannot run the prometheus, because of the error:

### What did you expect to see?

Running prometheus instance that discovers containers and the address of ones that use the `host` network is replaced to `host_networking_host` value (`localhost` in this sample case, which is default, but it can be any other name)

### What did you see instead? Under which circumstances?

```
caller=main.go:468 level=error msg="Error loading config (--config.file=prometheus.yml)" file=/home/beniamin/workspace_docker/prometheus-grafana/prometheus.yml err="parsing YAML file prometheus.yml: host missing"
```

### System information

Linux 5.15.0-71-generic x86_64

### Prometheus version

```text
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
```

### Prometheus configuration file

```yaml
scrape_configs:
- job_name: docker_sd
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
    - host_networking_host: localhost
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
caller=main.go:468 level=error msg="Error loading config (--config.file=prometheus.yml)" file=/home/beniamin/workspace_docker/prometheus-grafana/prometheus.yml err="parsing YAML file prometheus.yml: host missing"
```
```

**Comment by bboreham** [comment]
Thank you for a very clear issue report, with all sections answered.

You have given two Docker SD configurations, one of which has only `host`, and one has only `host_networking_host`. 
The error message is telling you the latter is not valid.

Suggest you meant this:
```
scrape_configs:
- job_name: docker_sd
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      host_networking_host: localhost
```

I.e. remove the `-` from the line with `host_networking_host`.

(I have no idea whether this will work, just trying to explain the error you got).
