### ISSUE TITLE
use federate got error:  append failed expected label name got invalid

### ISSUE THREAD

**Issue by tanxiao1990** [prometheus/prometheus#12460]
### What did you do?

When using the prometheus federation method to collect other prometheus instances, 1 of them reports an error ,else all fine

when i delete the      params: 'match[]':   Configuration item ,it work fine ,but nothing will be collected 

### What did you expect to see?

collect success

### What did you see instead? Under which circumstances?

![image](https://github.com/prometheus/prometheus/assets/38320121/f110b449-e715-4e3b-964b-db4a541e006b)

### System information

centos7.4

### Prometheus version

```text
2.40.7
```

### Prometheus configuration file

```yaml
- job_name: 'federate'
    scrape_interval: 60s
    scrape_timeout: 40s
    honor_labels: true
    honor_timestamps: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="cadvisor"}'
        - '{job="etcd"}'
        - '{job="kube-apiserver"}'
        - '{job="kube-scheduler"}'
        - '{job="kube-state-metrics"}'
        - '{job="kubelet"}'        
    static_configs:
      - targets:
        - '192.168.1.1:30006'
```
