### ISSUE TITLE
Request: support backreferences in relabel_config regex's

### ISSUE THREAD

**Issue by lukeyeager** [prometheus/prometheus#12483]
### Proposal

In a `relabel_config`, the `regex` field supports any valid RE2 regular expression ([docs](https://github.com/prometheus/prometheus/blob/v2.44.0/docs/configuration/configuration.md#relabel_config)). RE2 regexp's don't support backreferences:
> RE2 disallows PCRE features that cannot be implemented efficiently using automata. (The most notable such feature is backreferences.) In return for giving up these difficult to implement (and often incorrectly used) features, RE2 can provably analyze the regular expressions or the automata.
> https://swtch.com/~rsc/regexp/regexp3.html

Because these are not supported, my prometheus.yml is currently very verbose. I would like to request that prometheus use a different regexp library for parsing these regexes which supports backreferences, possibly behind a build-time or run-time flag to opt-in to using this alternate library. Would you be willing to look at such a PR?

Here is my use-case. I am using [snmp-exporter](https://github.com/prometheus/snmp_exporter) to monitor a PDU with multiple outlets. Each outlet may be used to power a different server. In my `http_sd_config` (which I've simplified to a `static_config` in the example below for legibility), I know which port goes to which host, so I would like to provide a `host` label. Currently, this is the best way I've found to do that:
```yaml
  - job_name: pdu-exporter
    metrics_path: /snmp
    static_configs:
      - targets: [ pdu01 ]
        labels:
          host_for_o8: compute0001
          host_for_o16: compute0002
          host_for_o24: compute0003
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __param_module
        replacement: mymodule
      - target_label: __address__
        replacement: 'snmp-exporter:9116'
    metric_relabel_configs:
      - { source_labels: [ outletId, host_for_o1 ], regex: "1;(.+)", target_label: host }
      - { source_labels: [ outletId, host_for_o2 ], regex: "2;(.+)", target_label: host }
...
      - { source_labels: [ outletId, host_for_o48 ], regex: "48;(.+)", target_label: host }
      - action: labeldrop
        regex: "host_for_o\\d+"
```
If backreferences were supported, here is one way I could collapse those 48 relabel_configs into a single one instead:
```yaml
...
    static_configs:
      - targets: [ pdu01 ]
        labels: { outlets_to_ports: "8=compute0001,16=compute0002,24=compute0003" }
...
    metric_relabel_configs:
      - source_labels: [ outletId, outlet_to_ports ]
        regex: "(?P<outlet>\\d+);.*\\b(?P=outlet)=([a-z0-9]+)\\b.*"
        replacement: "$3"
        target_label: host
      - action: labeldrop
        regex: "outlet_to_ports"
```
This particular example is not terrifically painful since my workaround only requires 48 lines of generated code. But it is one real-world, concrete case where backreferences would be convenient. Perhaps others will chime in with their own use-cases for how PCRE features would be helpful.

**Comment by opserva** [comment]
Use case: SNMP exporter scraping interfaces: by using backreference, we would be able to use metrics_relabel functions that match ifname against a string listing all interfaces to monitor. Simpel regex to create (.+);.*\1+ for the source labels ifname and __interfaces_to_monitor.

**Comment by h0tbird** [comment]
I was also thinking something along the lines of...
```yaml
# If prometheus.io/keep-regex is specified, use it to keep metrics
- source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_keep_regex, __name__]
  separator: ";"
  regex: "(.*);\\1"
  action: keep
```
...although, I'm not sure if I'm thinking this right or if there is already an alternative for this.
