### ISSUE TITLE
scrapePool.Sync performance regression with native histograms

### ISSUE THREAD

**Issue by milesbxf** [prometheus/prometheus#12481]
### What did you do?

We recently upgraded from v2.39.1 to v2.44.0 and enabled native histograms (`--enable-feature=native-histograms`) on a pretty sizeable instance (~50M time series) and noticed some severe scrape performance regressions that meant we had to roll back.

### What did you see instead? Under which circumstances?

Note on graphs below: we restarted prometheus-services-0 at 08:31 UTC. It finished replaying the WAL and came online at 08:51 UTC.

* Sample ingestion on the upgraded node decreased by about 45% and we were missing a lot of metrics:
<img width="790" alt="Screenshot 2023-06-21 at 16 01 52" src="https://github.com/prometheus/prometheus/assets/8912725/19560584-88b8-4254-bdff-cb009fdedddf">

* Targets page showed multiple minutes between scrapes of most pods (explaining the decrease in sample ingestion), despite our scrape interval being correctly set to 15 seconds
* The scrapes themselves were completing successfully - there were no reported HTTP errors or timeouts
* prometheus_target_sync_length_seconds increased in all quantiles - e.g. 0.9 went from around 18 seconds to having spikes of 280+

<img width="1296" alt="Screenshot 2023-06-21 at 16 05 54" src="https://github.com/prometheus/prometheus/assets/8912725/f626b19c-b9ba-4a98-a5d3-ab6a37f01994">

Here are two pprof 30s CPU profiles comparing the two versions running at the same time (let me know if there's an easier way to share these):
* [prometheus-v2.39.1](https://www.dropbox.com/s/5tfh09tjm8nf0vv/prometheus-v2.39.1?dl=0)
* [prometheus-v2.44.0-native-histograms](https://www.dropbox.com/s/aw6jvi2zpatemnu/prometheus-v2.44.0-native-histograms?dl=0)

The one experiment we've tried is running v2.44.0 without native histograms support. This has reduced the target sync latency. Here is prometheus-services-1:
* 12:22 - upgraded to 2.44.0 **with native histograms enabled**
* 12:41 - WAL replay finishes, target sync latency increases
* 13:38 - restarted with native histograms **disabled**
* 14:04 - WAL replay finishes

<img width="1296" alt="Screenshot 2023-06-21 at 16 11 59" src="https://github.com/prometheus/prometheus/assets/8912725/ebde932c-6ba8-4941-bb44-f7b8842677ea">

Also worth noting that reported CPU usage with native histograms enabled actually _drops_:
<img width="1558" alt="Screenshot 2023-06-21 at 16 21 00" src="https://github.com/prometheus/prometheus/assets/8912725/8eb2b5b9-158f-4b84-8564-35a0a82cf520">

<img width="1558" alt="Screenshot 2023-06-21 at 16 22 11" src="https://github.com/prometheus/prometheus/assets/8912725/ab7e21d3-50ee-4707-80fa-2b9e72c5c989">

Other environment details to note:
* We're not actually exporting any native histograms from services yet, but lots of classic histograms
* The majority of our exporters only return text/plain data even if OpenMetrics/proto accept headers are given

Let me know if there's any more info I can provide

### System information

quay.io/prometheus/busybox image

### Prometheus version

```text
prometheus --version
prometheus, version 2.44.0 (branch: HEAD, revision: 1ac5131f698ebc60f13fe2727f89b115a41f6558)
  build user:       root@739e8181c5db
  build date:       20230514-06:18:11
  go version:       go1.20.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 30s
  external_labels:
    cell: hub
    prometheus_replica: prometheus-services-0
    prometheus_shard: services
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - alertmanager
rule_files:
- /etc/prometheus/alerts/runbooks/*.rules
- /etc/prometheus/alerts/*.rules
- /etc/prometheus/rules/*.rules
- /etc/prometheus/alerts/runbooks/*.yaml
- /etc/prometheus/alerts/*.yaml
- /etc/prometheus/rules/*.yaml
scrape_configs:
- job_name: prometheus-disk-monitor
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^go_.+
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: ^http_.+
    replacement: $1
    action: drop
  - source_labels: [__name__]
    separator: ;
    regex: ^process_.+
    replacement: $1
    action: drop
  static_configs:
  - targets:
    - localhost:9100
- job_name: prometheus
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: prometheus
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_label_prometheus_shard]
    separator: ;
    regex: services
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: ^prometheus|http|rules$
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_name, __meta_kubernetes_pod_container_port_number]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: instance
    replacement: $1:$2
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: node
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: (.*)
    target_label: port
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_controller_name]
    separator: /
    regex: (.*)
    target_label: job
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_monzo_system]
    separator: ;
    regex: (.*)
    target_label: monzo_system
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_monzo_component]
    separator: ;
    regex: (.*)
    target_label: monzo_component
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_phase]
    separator: ;
    regex: (.*)
    target_label: phase
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
- job_name: kubernetes-pods
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  authorization:
    type: Bearer
    credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: false
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape, __meta_kubernetes_pod_label_io_gmon_routing_name]
    separator: ;
    regex: ^true;.+$
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_node_name]
    separator: ;
    regex: (.*)
    target_label: node
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_code_owner]
    separator: ;
    regex: (.*)
    target_label: code_owner
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_monzo_system]
    separator: ;
    regex: (.*)
    target_label: monzo_system
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_monzo_component]
    separator: ;
    regex: (.*)
    target_label: monzo_component
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_phase]
    separator: ;
    regex: (.*)
    target_label: phase
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: (.*)
    target_label: app
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_component]
    separator: ;
    regex: (.*)
    target_label: component
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
    separator: /
    regex: (.*)
    target_label: job
    replacement: $1
    action: replace
  metric_relabel_configs:
  - source_labels: [le]
    separator: ;
    regex: ^([0-9]+)$
    target_label: le
    replacement: ${1}.0
    action: replace
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
storage:
  exemplars:
    max_exemplars: 100000
```

### Logs

```text
No relevant logs found
```

**Comment by bboreham** [comment]
If you have lots of pods, where you have this relabel rule to drop most of them:
```
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    separator: ;
    regex: prometheus
    replacement: $1
    action: keep
```

I believe it will be a lot more efficient to use a label selector, i.e.

```
  kubernetes_sd_configs:
  - role: pod
    selectors:
      label: "app=prometheus"
```

For the second kubernetes_sd_configs you could say:
```
  - role: pod
    selectors:
      label: "io_gmon_routing_name"
```
to fetch only those pods that have this label, because otherwise you will drop them in the `^true;.+$` regex match.
(spell it correctly - those underscores may be replacements for `.` or `/`.)

**Comment by milesbxf** [comment]
> If you have lots of pods, where you have this relabel rule to drop most of them:
> 
> ```
>   relabel_configs:
>   - source_labels: [__meta_kubernetes_pod_label_app]
>     separator: ;
>     regex: prometheus
>     replacement: $1
>     action: keep
> ```
> 
> I believe it will be a lot more efficient to use a label selector, i.e.
> 
> ```
>   kubernetes_sd_configs:
>   - role: pod
>     selectors:
>       label: "app=prometheus"
> ```
> 
> For the second kubernetes_sd_configs you could say:
> 
> ```
>   - role: pod
>     selectors:
>       label: "io_gmon_routing_name"
> ```
> 
> to fetch only those pods that have this label, because otherwise you will drop them in the `^true;.+$` regex match. (spell it correctly - those underscores may be replacements for `.` or `/`.)

Didn't know this was possible, neat - we'll give that a go and report back. There's around 10k pods so it is quite a sizeable set

**Comment by bboreham** [comment]
So memory dropped and then very quickly came back again to where it was before?

**Comment by bboreham** [comment]
BTW the reason I was talking about selectors is the "stringlabels" change in 2.43/44 made SD a bit worse on dropped targets (possibly a lot worse depending on your labels and annotations).
I created a separate issue to document that point: #12482

**Comment by milesbxf** [comment]
Quick update here: we had some trouble getting the K8s SD selectors working in production. Everything looked fine in our staging environments, but Prometheus scraped a much larger set of targets than we expected, and we're still trying to work out why. We changed relabel_configs from:
```
relabel_configs:
      - action: keep
        regex: ^true;.+$
        separator: ;
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - __meta_kubernetes_pod_label_io_gmon_routing_name
```

to:
```
relabel_configs:
      - action: keep
        regex: ^true$
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
```

and updated `kubernetes_sd_configs`:

```
kubernetes_sd_configs:
      - role: pod
        selectors:
        - label: io-gmon/routing-name
          role: pod
```

In other news, we've found that scrapePool.Sync performance was already getting quite bad for us in v2.39.1 before the upgrade (though 2.44/native histograms seems to have made it much worse) - it's telling that overnight (when number of K8s targets is lower) it only takes 3-4s, and during the day (when there are more pods) we're seeing 18s. This manifests as larger gaps between scrapes than we'd like (scrape_interval is 15s, we're seeing up to 30s).

I did wonder if K8s API LIST latency could be contributing here - according to the Prometheus client metrics it's taking around 6s on average, which is slow, but not the full picture.

<img width="1921" alt="Screenshot 2023-06-23 at 18 03 40" src="https://github.com/prometheus/prometheus/assets/8912725/742933e2-d2b7-4bf0-8442-9140d8845c79">

We'll continue to investigate why selectors didn't work for us, and if we can get it working. In the meantime, a few more questions:
* a brief scan of the profile suggests that we're spending a sizeable proportion of time in processing labels. Should we expect stringlabels to help us here (bar the issue with dropped targets you mentioned above)?
* why does latency in (*scrapePool).Sync cause such a big gap between scrapes? _Is_ it even the cause here, or should we look somewhere else? Is there some kind of lock contention between the two?
* Besides getting the selectors working, are there any other optimisations we could be making? Are we going to need to look at splitting up this scraping job across multiple Prometheis (is that still the right plural?)?

Thanks for your help so far 🙇 if you think there's a potential further opportunity to optimise (*scrapePool).Sync and can point me in the right direction, I'm happy to have a crack at contributing an optimisation
