### ISSUE TITLE
alertmanager.url must be a public url (not just a container name)

### ISSUE THREAD

**Issue by casertap** [prometheus/prometheus#1250]
Using prometheus with alertmanager to monitor containers is great.
The problem is that the alertmanager.url option in the command:
````
prometheus:
    image: prom/prometheus
    links:
        - cadvisor
        - promalertmgr
        - wpprog
        - wptrad
        - mysql
    ports:
        - "127.0.0.1:9090:9090"
    expose:
        - "9090"
    command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://myhosturl:9093
    env_file:
        - './.env'
    volumes:
        - ./alert.rules:/etc/prometheus/alert.rules:ro
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
````
needs to be the host url.
This is problematic because the port 9093 which also serve the dashboard needs to be public on the host machine.

This could be so much better if we could use the /etc/hosts created by docker to point to the alermanager container within the private network of docker.

this way the command will look like such:
````
command: "-config.file=/etc/prometheus/prometheus.yml -alertmanager.url=promalertmanager:9093"
````
Then the promalertmanager will be:
```
promalertmgr:
    image: prom/alertmanager
    ports:
        - "127.0.0.1:9093:9093"
    expose:
        - "9093"
    command: "-config.file=/alertmanager.conf"
    volumes:
        - ./alertmanager.conf:/alertmanager.conf:ro
    env_file:
        - './.env'
````
The important part here is that 9093 is expose only to 127.0.0.1.
This means nobody can see the dashboard of alertmanager from the outside.

I will need to create a ssh tunnel to see this dashboard and I will be very happy with that.

I have open some issues about that but did not get much answers:
https://github.com/prometheus/alertmanager/issues/141 
https://github.com/prometheus/alertmanager/issues/164
