### ISSUE TITLE
Meilisearch bearer authorization

### ISSUE THREAD

**Issue by konstantin83** [prometheus/prometheus#12517]
### What did you do?

Hi! Thanks for such a great software!

I'm trying to monitor Meiliearch with Grafana via Prometheus.

Prometheus frontend shows configuration as following:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: meilisearch
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  authorization:
    type: Bearer
    credentials: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:7700
```

But "Targets" page in Prometheus shows that Meilisearch refused the connection:
![prom](https://github.com/prometheus/prometheus/assets/13274062/558c94cc-3c89-4946-a220-8960c1dce14d)

Meilisearch was started with this command:
`./meilisearch --master-key fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM --experimental-enable-metrics`

What am I doing wrong?

### What did you expect to see?

I expected to see Melisearch target at the state of "Up"

### What did you see instead? Under which circumstances?

![prom](https://github.com/prometheus/prometheus/assets/13274062/558c94cc-3c89-4946-a220-8960c1dce14d)

### System information

Linux 5.19.0-46-generic x86_64

### Prometheus version

```text
prometheus, version 2.45.0 (branch: HEAD, revision: 8ef767e396bf8445f009f945b0162fd71827f445)
  build user:       root@920118f645b7
  build date:       20230623-15:09:49
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:                                                                                                                      
  scrape_interval:     15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'meilisearch'

    scrape_interval: 5s
#    bearer_token: 'fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM'
    authorization:
      credentials: 'fvZJKS6DtD4ZAJSaUN8j37ksdkOhE6L69qwtD8Af5XM'
    static_configs:
      - targets: ['localhost:7700']
```
