### ISSUE TITLE
field linode_sd_configs not found in type config.ScrapeConfig

### ISSUE THREAD

**Issue by benbro** [prometheus/prometheus#12526]
### What did you do?

Added 'linode_sd_configs' to the 'node' job in /etc/prometheus/prometheus.yml
I'm using the Prometheus package from the Debian 12 repository.
The same config worked when I've installed Prometheus manually on Ubuntu 22.04.

### What did you expect to see?

Linode service discovery

### What did you see instead? Under which circumstances?

```
Error loading config (--config.file=/etc/prometheus/prometheus.yml)
file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors
field linode_sd_configs not found in type config.ScrapeConfig
```

### System information

Linux 6.1.0-9-amd64 x86_64

### Prometheus version

```text
prometheus, version 2.42.0+ds (branch: debian/sid, revision: 2.42.0+ds-5+b5)
  build user:       team+pkg-go@tracker.debian.org
  build date:       20230518-08:49:35
  go version:       go1.19.8
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'example'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
    linode_sd_configs:
      - authorization:
          credentials: '<my linode access token>'
```
