### ISSUE TITLE
KeepEqual/DropEqual should compare Regex.String instead of instance values

### ISSUE THREAD

**Issue by mattdurham** [prometheus/prometheus#12534]
### What did you do?

Using a relabel config with keepequal/dropequal compares instance var instead of string value.

https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go#L134 should be `c.Regex.String() != DefaultRelabelConfig.Regex.String()` and not `c.Regex != DefaultRelabelConfig.Regex`

### What did you see instead? Under which circumstances?

KeepEqual doesn't work if we the regex is the same string but different instance.

### Prometheus configuration file

```yaml
relabel_configs:
            - source_labels: [label_1]
              action: keepequal
              target_label: label_2
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_
