### ISSUE TITLE
Promtool building TSDB from Openmetrics file but grafana doesnt show

### ISSUE THREAD

**Issue by radiorz** [prometheus/prometheus#12545]
### What did you do?

https://serverfault.com/questions/1136605/promtool-tsdb-create-blocks-from-openmetrics-doesnt-show

### What did you expect to see?

Expect grafana show the value in graph

### What did you see instead? Under which circumstances?

not data

### Prometheus version

```text
prometheus, version 2.45.0 (branch: HEAD, revision: 8ef767e396bf8445f009f945b0162fd71827f445)
  build user:       root@858b3920627f
  build date:       20230623-15:18:12
  go version:       go1.20.5
  platform:         windows/amd64
  tags:             builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "codelab-monitor"
scrape_configs:
```
