### ISSUE TITLE
Expand environment variables in relabel_configs

### ISSUE THREAD

**Issue by GiedriusS** [prometheus/prometheus#12563]
### Proposal

Use case: make Prometheus scrape only local pods in Kubernetes i.e. pods running on the same host as the Prometheus pod. It's not easy to do that without hacks at the moment. Sysdig has this hack:

https://docs.sysdig.com/en/docs/sysdig-monitor/integrations/integration-library/prometheus-integrations/knative/

```
  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_host_ip]
    regex: __HOSTIPS__
```

Some middle layer replaces `__HOSTIPS__` with the host IP. Another user wandering about the same use-case: https://www.reddit.com/r/kubernetes/comments/yre79j/prometheus_scrape_pods_only_on_the_current_node/

This could be exposed to k8s pods through:

```
  env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
```

Now it is just needed to be able to use environment variables in relabel_configs. The only problem that I can think of is how to handle `${}` inside the regular expression because these characters mean something different inside `[]` in a regex.
