### ISSUE TITLE
ServiceMonitor and scrape_classic_histograms parameter

### ISSUE THREAD

**Issue by mkovsher** [prometheus/prometheus#12606]
### Proposal

Add [scrape_classic_histograms](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config) parameter to [ServiceMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor) or ability to combine ServiceMonitor and helm [additionalScrapeConfigs:](https://github.com/prometheus-community/helm-charts/blob/eae39d7447cfaeaf9aa00b8aec942ebce879861b/charts/kube-prometheus-stack/values.yaml#L3241C32-L3241C32) section.

Expect:
```
scrape_configs:
- job_name: serviceMonitor/mimir/grafana-mimir-alertmanager/0
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  scrape_classic_histograms: true                     <-------------------------
```

Why:
Prometheus has enabled `native-histograms` feature.
I tried to add `scrape_classic_histograms: true` to the jobs in the `additionalScrapeConfigs:` section in Helm chart (48.1.1).
I don't have ability to define this parameter for ServiceMonitor.

Got error, because Prometheus-operator has already added an entry with the same name based on Mimir ServiceMonitor:
`failed to reload config: couldn't load configuration (--config.file="/etc/prometheus/config_out/prometheus.env.yaml"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: found multiple scrape configs with job name "serviceMonitor/mimir/grafana-mimir-alertmanager/0"`
