### ISSUE TITLE
Document OTLP ingestion endpoint

### ISSUE THREAD

**Issue by arukiidou** [prometheus/prometheus#12642]
### Proposal

- reopened #10547

- Support [OTLP（OpenTelemetry Protocol）](https://opentelemetry.io/docs/specs/otlp/) ingestion.
  -  [x] implement #12571 
  -  [x] add docs #12643 
  -  [ ] writing the guide with examples prometheus/docs#2382

- relates #12633

**Comment by prathamesh-sonpatki** [comment]
@jesusvazquez Can I take this up?

**Comment by gouthamve** [comment]
@prathamesh-sonpatki https://github.com/prometheus/prometheus/pull/12643

Could you take up the task of writing the guide with examples? I'll be happy to guide you.

**Comment by prathamesh-sonpatki** [comment]
Sure, let me go through #12643 and get back to you if I have any questions.

**Comment by arukiidou** [comment]
## client-side(opentelemetry-go)

[MrAlias](https://github.com/MrAlias) has a good example.

https://github.com/MrAlias/otel-otlp-metric-example/blob/main/main.go

## server-side

### docker compose.yml

```
services:
  prom:
    restart: always
    image: quay.io/prometheus/prometheus@sha256:8a1275e99ced4e896279845af495e00fb68708e56d9a857f56f459fa6261a6ec
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=otlp-write-receiver'
    ports:
      - '9090:9090'
    configs:
      - source: prometheus
        target: /etc/prometheus/prometheus.yml
        mode: 440

configs:
  prometheus:
    file: ./prometheus.yml
```

### prometheus.yml

```
storage:
  tsdb:
    # A 10min time window is enough because it can easily absorb retries and network delays.
    out_of_order_time_window: 10m

remote_write:
  - url: http://localhost:9090/api/v1/otlp/v1/metrics
    queue_config:
      capacity: 1000000
      batch_send_deadline: 10s
      max_samples_per_send: 1000
      max_shards: 3
    remote_timeout: "30s"
    follow_redirects: true
```
