### ISSUE TITLE
Include an /etc/os-release file in the Docker Hub images

### ISSUE THREAD

**Issue by vincent-olivert-riera** [prometheus/prometheus#12656]
### Proposal

When trying to use the `prom/prometheus` images from Docker Hub in GitHub Actions, there are some basic actions that require the `/etc/os-release` file to exist.

For instance, since the `prom/prometheus` images do not have that file, trying to run this checkout step fails:

```
jobs:
  build:
    runs-on: ubuntu-latest
    container: prom/prometheus
    steps:
      - uses: actions/checkout@v3
```

And it fails like this:

```
Run actions/checkout@v3
  with:
    repository: MyOrg/MyRepo
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
    set-safe-directory: true
/usr/bin/docker exec  ef36e43ecfc45b1e393b5fc7a9753217a84bfd16fd425f1175bb1aa72ede1785 sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: unable to start container process: exec /__e/node16/bin/node: no such file or directory: unknown
```

It would be nice if you could include an `/etc/os-release` file in your Docker Hub images so they can be used in GitHub Actions.
