### ISSUE TITLE
Thanos + Prometheus Operator Database from Local to S3

### ISSUE THREAD

**Issue by antikilahdjs** [prometheus/prometheus#12672]
### What did you do?

1. Install the helm using the normal way
2. Configure S3 miniO as bucket
3. I have the Prometheus CRD and I configured the Thanos Sidecar
4.  Everything works perfectly and the remote_write has been configured to sent all data to S3

### What did you expect to see?

My locally database of prometheus is too large and for this reason I installed thanos, of course to improve the performance too. I dont know if is possible or if thanos will do that but my database have the same size. The retain has been configured in my Receiver too

### What did you see instead? Under which circumstances?

The Prometheus as Operator with 100gb of Database as local and I would like to understand if possible remove local database or decrease the retain and search all query to the S3

### System information

Linux 4.18.0-305.el8.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.34.0 (branch: HEAD, revision: 881111fec4332c33094a6fb2680c71fffc427275)
  build user:       root@121ad7ea5487
  build date:       20220315-15:18:00
  go version:       go1.17.8
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.34.0
    prometheus: k8s
  name: k8s
  namespace: kubesphere-monitoring-system
spec:
  additionalScrapeConfigs:
    key: prometheus-additional.yaml
    name: additional-scrape-configs
  affinity: {}
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: kubesphere-monitoring-system
        port: web
  evaluationInterval: 1m
  image: 'prom/prometheus:v2.34.0'
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.34.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  query:
    maxConcurrency: 1000
  remoteWrite:
    - url: >-
        http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive
  replicas: 2
  resources:
    requests:
      cpu: 2
      memory: 8Gi
  retention: 90d
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  scrapeInterval: 1m
  secrets:
    - kube-etcd-client-certs
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  shards: 2
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 400Gi
  thanos:
    objectStorageConfig:
      key: objstore.yml
      name: thanos-stack-objstore-secret
    version: v0.31.0
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: monitoring
  version: v2.34.0
```

### Logs

```text
ts=2023-08-10T15:07:28.582Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=4 to=7

 ts=2023-08-10T15:08:08.612Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=7 to=10

 ts=2023-08-10T15:08:14.310Z caller=api.go:1496 level=error component=web msg="error writing response" bytesWritten=0 err="write tcp 10.233.108.156:9090->10.233.69.180:56574: write: broken pipe"

 ts=2023-08-10T15:08:18.740Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=10 to=4

 ts=2023-08-10T15:08:28.742Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=4 to=6

 ts=2023-08-10T15:08:38.582Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=6 to=8

 ts=2023-08-10T15:08:58.567Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=8 to=11

 ts=2023-08-10T15:09:23.492Z caller=api.go:1496 level=error component=web msg="error writing response" bytesWritten=0 err="write tcp 10.233.108.156:9090->10.233.69.180:57016: write: broken pipe"

 ts=2023-08-10T15:09:28.775Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=11 to=4

 ts=2023-08-10T15:09:48.638Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=4 to=6

 ts=2023-08-10T15:09:58.568Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=6 to=8

 ts=2023-08-10T15:10:18.600Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=8 to=11

 ts=2023-08-10T15:10:38.715Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=11 to=4

 ts=2023-08-10T15:10:58.578Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=4 to=6

 ts=2023-08-10T15:11:18.563Z caller=dedupe.go:112 component=remote level=info remote_name=51677b url=http://thanos-stack-receive.kubesphere-monitoring-system:19291/api/v1/receive msg="Remote storage resharding" from=6 to=9

 ts=2023-08-10T15:11:22.154Z caller=compact.go:519 level=info component=tsdb msg="write block" mint=1691668800000 maxt=1691676000000 ulid=01H7FZCBPFMBHKTFTWK6057XDZ duration=11m21.818574851s

 ts=2023-08-10T15:11:38.873Z caller=head.go:840 level=info component=tsdb msg="Head GC completed" duration=12.43414237s

 ts=2023-08-10T15:11:39.407Z caller=api.go:1496 level=error component=web msg="error writing response" bytesWritten=0 err="write tcp 10.233.108.156:9090->10.233.69.180:57382: write: broken pipe"

 ts=2023-08-10T15:11:39.930Z caller=checkpoint.go:98 level=info component=tsdb msg="Creating checkpoint" from_segment=34748 to_segment=34760 mint=1691676000000
```
