### ISSUE TITLE
adding an option to multiple resource_group when use scrape_config 

### ISSUE THREAD

**Issue by yahavvidaa** [prometheus/prometheus#12719]
### Proposal

Hey Masters :) 
i face an issue today that i wish to mention more than 1 resource_group to scrape with my azure_sd_config and i couldn't 
it looks like this : 

```
    azure_sd_configs:
    - authentication_method: "ManagedIdentity"
      subscription_id: "XXXX"
      resource_group: "RG-prod-eu"
      ## i was think to use it like this but it dosent let me refresh the prom configuration without a yaml error 
      #- "RG-prod-eu"
      # - "RG-prod-na"
      refresh_interval: "600s"
      port: 9100
    relabel_configs:
      -  source_labels: ["__meta_azure_machine_size"]
         target_label: "type"
         #replacement: "__meta_azure_machine_size"
      -  source_labels: ["__meta_azure_machine_location"]
         target_label: "region"
      -  source_labels: ["__meta_azure_machine_name"]
         target_label: "name"
```
         
  And thank you all for this such great Prometheus community , you are the best !

**Comment by roidelapluie** [comment]
What about you do something like this?

```
    azure_sd_configs:
    - authentication_method: "ManagedIdentity"
      subscription_id: "XXXX"
      resource_group: "RG-prod-eu"
      refresh_interval: "600s"
      port: 9100
    - authentication_method: "ManagedIdentity"
      subscription_id: "XXXX"
      resource_group: "RG-prod-na"
      refresh_interval: "600s"
      port: 9100
    relabel_configs:
      -  source_labels: ["__meta_azure_machine_size"]
         target_label: "type"
         #replacement: "__meta_azure_machine_size"
      -  source_labels: ["__meta_azure_machine_location"]
         target_label: "region"
      -  source_labels: ["__meta_azure_machine_name"]
         target_label: "name"
```

Which can be shortened to:

```
    azure_sd_configs:
    - &az
      authentication_method: "ManagedIdentity"
      subscription_id: "XXXX"
      resource_group: "RG-prod-eu"
      refresh_interval: "600s"
      port: 9100
    - <<: *az
      resource_group: "RG-prod-na"
    relabel_configs:
      -  source_labels: ["__meta_azure_machine_size"]
         target_label: "type"
         #replacement: "__meta_azure_machine_size"
      -  source_labels: ["__meta_azure_machine_location"]
         target_label: "region"
      -  source_labels: ["__meta_azure_machine_name"]
         target_label: "name"
```
