### ISSUE TITLE
RuleManager's storage of alert state (QueryforStateSeries) doesn't take into account file or group name

### ISSUE THREAD

**Issue by jacksontj** [prometheus/prometheus#12714]
### What did you do?

As an example I created the following 2 files:

### alert_example.rule
```yaml
# example from https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
groups:
- name: example
  rules:
  - alert: testAlert
    expr: prometheus_build_info == 1
    for: 10m
    labels:
      severity: page
    annotations:
      summary: Example alert
```

### alert_example_dupe.rule
```yaml
# example from https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
groups:
- name: example
  rules:
  - alert: testAlert
    expr: prometheus_build_info != 1
    for: 15m
    labels:
      severity: page
    annotations:
      summary: Example alert
```

### What did you expect to see?

While working on some alerting issues I noticed that the mechanism that RuleManager uses to store alerts across restarts (initially added https://github.com/prometheus/prometheus/pull/4061) does not take into consideration filename or groupname. This means if you have 2 alerts with the same name their state is intermingled (which is incorrect). This can actually happen even if there is a single file -- as long as the alerts have the same `name` attribute (of which there are no checks/controls against).

This breaks the expected behavior that I as the user expect the alert state to be restored to what it was prior to restart.

### What did you see instead? Under which circumstances?

After restart I generally see both with the same state (one of them seemingly at random?); but from looking at the code it seems that this is non-deterministic behavior (as its effectively just a race condition for the RuleManager writing the state out to the appender.
