### ISSUE TITLE
Prometheus and promtool to validate basic_auth elements in configuration yaml

### ISSUE THREAD

**Issue by wasim-nihal** [prometheus/prometheus#12750]
### Proposal

Currently, the validation of basic auth in prometheus configuration is limited to below points:

- It makes sure that `password` and `password_file` are not specified together in the configuration yaml.

There is no validation to check if basic_auth is specified and whether the user has configured its username or the password (or password_file).

**Example Configuration (where password configuration in basic auth is missing):**
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
    basic_auth:
      username: testuser
```

**promtool output:**
```
$ ./promtool check config prometheus.yaml
Checking prometheus.yaml
 SUCCESS: prometheus.yaml is valid prometheus config file syntax
```

**Proposed additional validations:**

- if basic_auth is specified, then make sure that username is configured.
- if basic_auth is specified, then make sure atlease one of password or password_file is configured

This would help users in minimizing the authorization issues due to such configuration errors.

@roidelapluie, **if you think this feature would be of help, I would like to submit PR for the above proposed changes.**
