### ISSUE TITLE
Promteheus HA different metrics

### ISSUE THREAD

**Issue by zelanastasia** [prometheus/prometheus#12751]
### What did you do?

Hello, we use HA prometheus with two servers. 
The problem is we get different metrics in dashboards from this two servers. 
And we also scrape metrics from k8s, and some pods are not scraping because of error `context deadline exceeded`
Its differents pods on each server. In prometheus logs we dont see any of errors. How is that possible? What we can do for debug this?

### What did you see instead? Under which circumstances?

We dont get right mertrics.

### System information

Linux 5.15.0-58-generic x86_64

### Prometheus version

```text
prometheus, version 2.40.7 (branch: HEAD, revision: ab239ac5d43f6c1068f0d05283a0544576aaecf8)
  build user:       root@afba4a8bd7cc
  build date:       20221214-08:49:43
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
#
# This file is managed by ansible. Please don't edit it by hand or your changes would be overwritten.
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 30s
  scrape_interval: 30s
  scrape_timeout: 15s

  external_labels:
    null




rule_files:
  - /etc/prometheus/rules/*.rules

  - job_name: 'k8s_pods'
    scrape_interval: 5m
    scrape_timeout: 1m
    kubernetes_sd_configs:
      - role: pod
        api_server: https://x.x.x.x:6443
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: "/etc/prometheus/kubernetes_bearer_token"
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: (.+):(?:\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_pod_node_name
```

### Alertmanager version

```text
alertmanager, version 0.24.0 (branch: HEAD, revision: f484b17fa3c583ed1b2c8bbcec20ba1db2aa5f11)
  build user:       root@265f14f5c6fc
  build date:       20220325-09:31:33
  go version:       go1.17.8
  platform:         linux/amd64
```
