### ISSUE TITLE
Wrong documentation for http_sd_config / authorization / type

### ISSUE THREAD

**Issue by vladvasiliu** [prometheus/prometheus#12762]
### What did you do?

Configured `http_sd_config` with Bearer authorization type. Didn't specify `authorization.type` since docs say it defaults to `Bearer`. The `Authorization` header value is missing the type; it contains only the `authorization.credentials` string.

Manually adding `authorization.type: Bearer` works.

### What did you expect to see?

List of discovered targets.

### What did you see instead? Under which circumstances?

No targets and HTTP 401 in server logs.

### System information

Linux 6.2.0-1010-aws aarch64

### Prometheus version

```text
prometheus, version 2.46.0 (branch: HEAD, revision: cbb69e51423565ec40f46e74f4ff2dbb3b7fb4f0)
  build user:       root@42454fc0f41e
  build date:       20230725-12:37:33
  go version:       go1.20.6
  platform:         linux/arm64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
- job_name: gate-icmp
  http_sd_configs:
  - authorization:
      credentials: super_secret_token
    refresh_interval: 3600s
    url: https://some.protected.url.com/prom_sd
```

### Alertmanager version

```text
n/a
```

### Alertmanager configuration file

```yaml
n/a
```

### Logs

```text
prometheus[5970]: ts=2023-08-28T14:31:06.951Z caller=refresh.go:80 level=error component="discovery manager scrape" discovery=http config=gate-icmp msg="Unable to refresh target groups" err="server returned HTTP status 401 Unauthorized"
```
