### ISSUE TITLE
Prometheus using stale alertmanager pods

### ISSUE THREAD

**Issue by Evesy** [prometheus/prometheus#12799]
### What did you do?

Alertmanager statefulset was rolled out bringing up pods with new IP's. Prometheus fails to discover these new pod IP's and continues using the old IPs which no longer exist

### What did you expect to see?

Prometheus service discovery should update the alertmanager IPs

### What did you see instead? Under which circumstances?

```
k get pods -n istio-system -l app=prometheus-alertmanager -o wide
NAME                        READY   STATUS    RESTARTS   AGE   IP               NODE                                                  NOMINATED NODE   READINESS GATES
prometheus-alertmanager-0   1/1     Running   0          16h   10.194.90.236    gke-delivery-platform-normal-20220831-fe7b3a8a-gr39   <none>           <none>
prometheus-alertmanager-1   1/1     Running   0          16h   10.194.105.121   gke-delivery-platform-normal-20220831-6749e4f8-9l9p   <none>           <none>
prometheus-alertmanager-2   1/1     Running   0          16h   10.194.36.86     gke-delivery-platform-normal-20220831-bf31c081-d54p   <none>           <none>
```

<img width="348" alt="image" src="https://github.com/prometheus/prometheus/assets/17579850/db6cc1ec-9e86-4f1d-aef1-05214c774f3b">

### System information

Linux 5.15.109+ x86_64

### Prometheus version

```text
prometheus, version 2.43.0 (branch: HEAD, revision: edfc3bcd025dd6fe296c167a14a216cab1e552ee)
  build user:       root@8a0ee342e522
  build date:       20230321-12:56:07
  go version:       go1.19.7
  platform:         linux/amd64
  tags:             netgo,builtinassets
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  query_log_file: /dev/stdout
  external_labels:
    environment: prod
    origin_prometheus: collector01
alerting:
  alertmanagers:
  - authorization:
      type: Bearer
      credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
    follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: istio-system
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      separator: ;
      regex: prometheus-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      separator: ;
      regex: http-frontend
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: pod
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
```

### Alertmanager version

```text
alertmanager, version 0.25.0 (branch: HEAD, revision: 258fab7cdd551f2cf251ed0348f0ad7289aee789)
  build user:       root@abe866dd5717
  build date:       20221222-14:51:36
  go version:       go1.19.4
  platform:         linux/amd64
```

### Alertmanager configuration file

```yaml
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
  telegram_api_url: https://api.telegram.org
  webex_api_url: https://webexapis.com/v1/messages
route:
  receiver: default-receiver
  group_by:
  - alertname
  - source
  - origin_prometheus
  continue: false
  routes:
  - receiver: blackhole
    match:
      alertname: QuietHours
    continue: false
  - receiver: blackhole
    match:
      alertname: OfficeHours
    continue: false
  - receiver: blackhole
    match:
      alertname: LowTrafficHours
    continue: false
  - receiver: default-receiver
    match:
      alertname: CloudSQLMaintenanceScheduled
    continue: false
    repeat_interval: 30d
  - receiver: default-receiver
    match:
      alertname: GocdPipelineRerun
    continue: false
    repeat_interval: 60d
  - receiver: default-receiver
    match:
      alertname: NewGkeVersionAvailable
    continue: false
    repeat_interval: 3d
  - receiver: blackhole
    match:
      alertname: KubernetesMasterRecentlyUnavailable
    continue: false
  - receiver: blackhole
    match:
      alertname: NodeUnready
    continue: false
  - receiver: blackhole
    match:
      receiver: blackhole
    continue: false
  group_wait: 30s
  group_interval: 10m
  repeat_interval: 1d
inhibit_rules:
- source_matchers:
  - severity="critical"
  target_matchers:
  - severity=~"(info|warning)"
  equal:
  - alertname
- source_matchers:
  - alertname="QuietHours"
  target_matchers:
  - alertname=~"(ApplicationHigh.*LogRate|ServiceNotUpdatedRecently|ServiceForwardingIncorrectRequestId)"
- source_matchers:
  - alertname="LowTrafficHours"
  target_matchers:
  - alertname="NginxRequestImbalance"
- source_matchers:
  - alertname="ServiceHighErrorRate"
  target_matchers:
  - alertname=~"(ApplicationHigh.*LogRate)"
  equal:
  - source
- source_matchers:
  - alertname="ContainerFrequentlyRestarting"
  target_matchers:
  - alertname="ContainerRestarted"
  equal:
  - source
- source_matchers:
  - alertname="ContainerFrequentlyUnready"
  target_matchers:
  - alertname="ContainerFrequentlyRestarting"
  equal:
  - source
- source_matchers:
  - alertname="ContainerOOM"
  target_matchers:
  - alertname="ContainerRestarted"
  equal:
  - source
- source_matchers:
  - alertname="ContainerOOM"
  target_matchers:
  - alertname="NodeKernelOOMKillerInvoked"
  equal:
  - node
- source_matchers:
  - alertname=~"(PodFailed|PodPending|ReplicaSetNoReplicas|ContainerRestarted|ContainerFrequentlyRestarting|ContainerFrequentlyUnready)"
  target_matchers:
  - alertname="ScrapeTargetDown"
  equal:
  - source
- source_matchers:
  - alertname="ServiceLikelyUnmaintained"
  target_matchers:
  - alertname="ServiceNotUpdatedRecently"
  equal:
  - source
- source_matchers:
  - alertname="PersistentVolumeUsageCritical"
  target_matchers:
  - alertname="PersistentVolumeUsageHigh"
  equal:
  - source
- source_matchers:
  - alertname="KubernetesMasterRecentlyUnavailable"
  target_matchers:
  - source=~"(platform-cold-start|cert-manager|sweepr|platform-dashboard|skippr|pokr|shippr-cli-api|testyomesh)"
- source_matchers:
  - alertname="NodeUnready"
  target_matchers:
  - alertname="ContainerRestarted"
  equal:
  - node
- source_matchers:
  - alertname="KafkaConsumerStopped"
  target_matchers:
  - alertname="KafkaConsumerHighLag"
  equal:
  - source
  - topic
- source_matchers:
  - alertname="ScheduledTaskFailed"
  target_matchers:
  - alertname="PodFailed"
  equal:
  - source
- source_matchers:
  - alertname="NginxReloadFailed"
  target_matchers:
  - alertname="NginxEmergencyLog"
  equal:
  - source
- source_matchers:
  - alertname="CloudflareAnomalyRequestCount"
  target_matchers:
  - alertname="CloudflareAnomalyRequestBytesCount"
  equal:
  - host
receivers:
- name: default-receiver
  webhook_configs:
  - send_resolved: true
    http_config:
      authorization:
        type: Bearer
        credentials: <secret>
      follow_redirects: true
      enable_http2: true
    url: http://app.skippr.svc.cluster.local/api/alertmanager
    max_alerts: 0
- name: blackhole
templates: []
time_intervals:
- name: business_hours
  time_intervals:
  - times:
    - start_time: "08:00"
      end_time: "18:00"
    weekdays: ['monday:friday']
    location: Europe/London
- {name: out_of_hours, time_intervals: [{weekdays: [saturday, sunday]}, {times: [
        {start_time: "00:00", end_time: "08:00"}, {start_time: "18:00", end_time: "23:59"}],
      weekdays: ['monday:friday'], location: Europe/London}]}
- {name: low_traffic_hours, time_
```

### Logs

```text
ts=2023-09-06T07:34:57.031Z caller=notifier.go:532 level=error component=notifier alertmanager=http://10.194.65.248:9093/api/v2/alerts count=11 msg="E
rror sending alert" err="Post \"http://10.194.65.248:9093/api/v2/alerts\": dial tcp 10.194.65.248:9093: i/o timeout"
ts=2023-09-06T07:34:57.031Z caller=notifier.go:532 level=error component=notifier alertmanager=http://10.194.57.150:9093/api/v2/alerts count=11 msg="E
rror sending alert" err="Post \"http://10.194.57.150:9093/api/v2/alerts\": context deadline exceeded"
ts=2023-09-06T07:34:57.031Z caller=notifier.go:532 level=error component=notifier alertmanager=http://10.194.36.67:9093/api/v2/alerts count=11 msg="Er
ror sending alert" err="Post \"http://10.194.36.67:9093/api/v2/alerts\": context deadline exceeded"
```
```

**Comment by davidhwang-anthropic** [comment]
I'm also seeing this issue.

Prometheus
```
alerting:
        alertmanagers:
          - apiVersion: v2
            name: alertmanager-main
            namespace: monitoring
            port: web
```

Status:
![image](https://github.com/prometheus/prometheus/assets/123105146/2b385b96-5374-49ab-bb94-8a9ca943442b)

```
kubectl get endpoints alertmanager-main -n monitoring -oyaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.25.0
  name: alertmanager-main
  namespace: monitoring
subsets:
  - addresses:
      - ip: 10.11.139.140
        nodeName: ip-10-11-213-252.ec2.internal
        targetRef:
          kind: Pod
          name: alertmanager-main-1
          namespace: monitoring
          resourceVersion: "5478041181"
          uid: 00419950-1303-49d2-8be3-3d7671dfa41a
      - ip: 10.11.140.232
        nodeName: ip-10-11-237-228.ec2.internal
        targetRef:
          kind: Pod
          name: alertmanager-main-0
          namespace: monitoring
          resourceVersion: "5806275316"
          uid: 352db99a-022e-43a0-ba52-8b0accb59df2
      - ip: 10.14.158.78
        nodeName: ip-10-14-28-154.ec2.internal
        targetRef:
          kind: Pod
          name: alertmanager-main-2
          namespace: monitoring
          resourceVersion: "5870076890"
          uid: a29a9d8e-1b35-4cdc-9402-e324ca7efc6c
    ports:
      - name: reloader-web
        port: 8080
        protocol: TCP
      - name: web
        port: 9093
        protocol: TCP
```

Alertmanager recent restarts, and indeed alertmanager-main-0 and alertmanager-main-2 are the ones that recently restarted.
```
kubectl get pod -n monitoring | rg alertmanager
alertmanager-main-0                           2/2     Running                  1 (2d17h ago)   2d18h
alertmanager-main-1                           2/2     Running                  1 (12d ago)     12d
alertmanager-main-2                           2/2     Running                  1 (20h ago)     25h
```
