### ISSUE TITLE
Historical metrics data suddenly cannot search via API

### ISSUE THREAD

**Issue by saika0721** [prometheus/prometheus#12970]
### What did you do?

From Grafana, create Prometheus data sources and pointing to it.
Grafana cannot search historical data

From prometheus graphs, I can view those metrics data

### What did you expect to see?

Expected historical metrics data can be viewable via Grafana

### What did you see instead? Under which circumstances?

Able to see all metrics days.
Currently metrics data keep for 30 days.

### System information

Ubutunu K8s

### Prometheus version

```text
Prometheus v2.45.0
```

### Prometheus configuration file

```yaml
prometheus.yml: |-
    global:
      scrape_interval: 60s
      scrape_timeout: 30s
      evaluation_interval: 60s

    storage:
      tsdb:
        out_of_order_time_window: 24h

    remote_write:
      - url: "https://prom-wins.infra.net:9390/api/v1/write"
        basic_auth:
          username: promadmin
          password: nZMNxH3R2zZkWbpf
        queue_config:
          capacity: 10000
          max_shards: 200
          min_shards: 5
          max_samples_per_send: 2000
        tls_config:
          insecure_skip_verify: true
          cert_file: /etc/prometheus/certs/prometheus.crt
          key_file: /etc/prometheus/certs/prometheus.key
          ca_file: /etc/prometheus/certs/prometheus-ca.crt

  prometheus-https.yml: |-
    tls_server_config:
      cert_file: /etc/prometheus/certs/prometheus.crt
      key_file: /etc/prometheus/certs/prometheus.key
```

### Alertmanager version

```text
N/A, using Grafana
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
ts=2023-10-12T08:22:01.592Z caller=main.go:578 level=info msg="Starting Prometheus Server" mode=server version="(version=2.45.0, branch=HEAD, revision=8ef767e396bf8445f009f945b0162fd71827f445)"
ts=2023-10-12T08:22:01.592Z caller=main.go:583 level=info build_context="(go=go1.20.5, platform=linux/amd64, user=root@920118f645b7, date=20230623-15:09:49, tags=netgo,builtinassets,stringlabels)"
ts=2023-10-12T08:22:01.592Z caller=main.go:584 level=info host_details="(Linux 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 prometheus2-599d887464-djhfr (none))"
ts=2023-10-12T08:22:01.592Z caller=main.go:585 level=info fd_limits="(soft=1048576, hard=1048576)"
ts=2023-10-12T08:22:01.592Z caller=main.go:586 level=info vm_limits="(soft=unlimited, hard=unlimited)"
ts=2023-10-12T08:22:01.634Z caller=web.go:562 level=info component=web msg="Start listening for connections" address=0.0.0.0:9390
ts=2023-10-12T08:22:01.635Z caller=main.go:1019 level=info msg="Starting TSDB ..."
ts=2023-10-12T08:22:01.636Z caller=tls_config.go:274 level=info component=web msg="Listening on" address=[::]:9390
ts=2023-10-12T08:22:01.637Z caller=tls_config.go:310 level=info component=web msg="TLS is enabled." http2=true address=[::]:9390
ts=2023-10-12T08:22:02.707Z caller=db.go:930 level=info component=tsdb msg="Found and deleted tmp block dir" dir=data/01HAC17E5HVRSWWZW252VQWNJH.tmp-for-creation
ts=2023-10-12T08:22:02.720Z caller=db.go:930 level=info component=tsdb msg="Found and deleted tmp block dir" dir=data/01HAC17FCHVH6RRZF08P9V4M2K.tmp-for-creation
ts=2023-10-12T08:22:02.734Z caller=db.go:930 level=info component=tsdb msg="Found and deleted tmp block dir" dir=data/01HAC17HKMRW49HR9P3CCKCZQ7.tmp-for-creation
ts=2023-10-12T08:37:25.936Z caller=head.go:676 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=2m13.298015773s
ts=2023-10-12T08:37:25.936Z caller=head.go:684 level=info component=tsdb msg="Replaying WAL, this may take a while"
ts=2023-10-12T08:37:25.970Z caller=head.go:755 level=info component=tsdb msg="WAL segment loaded" segment=0 maxSegment=265
ts=2023-10-12T08:37:25.988Z caller=db.go:898 level=warn component=tsdb msg="Encountered WAL read error, attempting repair" err="read records: corruption in segment data/wal/00000001 at 32768: unexpected non-zero byte in padded page"
ts=2023-10-12T08:37:25.988Z caller=wlog.go:387 level=warn component=tsdb msg="Starting corruption repair" segment=1 offset=32768
ts=2023-10-12T08:37:25.997Z caller=wlog.go:395 level=warn component=tsdb msg="Deleting all segments newer than corrupted segment" segment=1
ts=2023-10-12T08:37:28.914Z caller=wlog.go:417 level=warn component=tsdb msg="Rewrite corrupted segment" segment=1
ts=2023-10-12T08:37:28.990Z caller=db.go:902 level=info component=tsdb msg="Successfully repaired WAL"
ts=2023-10-12T08:37:28.995Z caller=main.go:1040 level=info fs_type=fe534d42
ts=2023-10-12T08:37:28.995Z caller=main.go:1043 level=info msg="TSDB started"
```
