### ISSUE TITLE
prometheus-k8s pod always "Received SIGTERM”, but the assigned node is healthy.

### ISSUE THREAD

**Issue by sanmv** [prometheus/prometheus#12976]
### What did you do?

Prometheus-k8s-0 in kubernetes cluster restarts frequently 

### What did you see instead? Under which circumstances?

The container log is as follows:
> ts=2023-10-13T01:36:37.231Z caller=main.go:1179 level=info msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=103.701544ms db_storage=2.765µs remote_storage=3.357µs web_handler=651ns query_engine=2.865µs scrape=408.217µs scrape_sd=8.813162ms notify=33.182µs notify_sd=1.673796ms rules=77.048118ms tracing=9.928µs
ts=2023-10-13T01:36:37.231Z` caller=main.go:910 level=info msg="Server is ready to receive web requests."
 ts=2023-10-13T01:46:18.416Z` caller=main.go:776 level=warn msg="Received SIGTERM, exiting gracefully..."
 ts=2023-10-13T01:47:19.049Z caller=main.go:799 level=info msg="Stopping scrape discovery manager..."
ts=2023-10-13T01:47:19.049Z caller=main.go:813 level=info msg="Stopping notify discovery manager..."
ts=2023-10-13T01:47:19.049Z caller=main.go:835 level=info msg="Stopping scrape manager..."
ts=2023-10-13T01:47:19.049Z caller=main.go:795 level=info msg="Scrape discovery manager stopped"
ts=2023-10-13T01:47:19.049Z caller=main.go:809 level=info msg="Notify discovery manager stopped"
ts=2023-10-13T01:47:19.052Z caller=klog.go:116 level=error component=k8s_client_runtime func=ErrorDepth msg="pkg/mod/k8s.io/client-go@v0.22.7/tools/cache/reflector.go:167: Failed to watch *v1.Service: Get \"https://10.233.0.1:443/api/v1/namespaces/default/services?allowWatchBookmarks=true&resourceVersion=98805610&timeout=7m16s&timeoutSeconds=436&watch=true\": context canceled"
ts=2023-10-13T01:47:21.910Z caller=manager.go:946 level=info component="rule manager" msg="Stopping rule manager..."
ts=2023-10-13T01:47:21.910Z caller=main.go:829 level=info msg="Scrape manager stopped"
ts=2023-10-13T01:48:01.021Z caller=manager.go:956 level=info component="rule manager" msg="Rule manager stopped"
ts=2023-10-13T01:48:02.257Z caller=notifier.go:600 level=info component=notifier msg="Stopping notification manager..."
ts=2023-10-13T01:48:02.257Z caller=main.go:1068 level=info msg="Notifier manager stopped"
ts=2023-10-13T01:48:02.257Z caller=main.go:1080 level=info msg="See you next time!"

### Prometheus version

```text
prometues:v.2.34.0
```

### Prometheus configuration file

```yaml
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"monitoring.coreos.com/v1","kind":"Prometheus","metadata":{"annotations":{},"creationTimestamp":"2023-06-07T01:27:29Z","generation":2,"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.34.0"},"name":"k8s","namespace":"kubesphere-monitoring-system","resourceVersion":"135757","uid":"b00c9fd1-89b2-4a55-ae8a-a9240c24c771"},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/monitoring","operator":"Exists"}]},"weight":100}]},"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus"}},"namespaces":["kubesphere-monitoring-system"],"topologyKey":"kubernetes.io/hostname"},"weight":100}]}},"alerting":{"alertmanagers":[{"name":"alertmanager-main","namespace":"kubesphere-monitoring-system","port":"web"}]},"evaluationInterval":"1m","image":"prom/prometheus:v2.34.0","nodeSelector":{"kubernetes.io/os":"linux"},"podMetadata":{"labels":{"app.kubernetes.io/component":"prometheus","app.kubernetes.io/instance":"k8s","app.kubernetes.io/name":"prometheus","app.kubernetes.io/part-of":"kube-prometheus","app.kubernetes.io/version":"2.34.0"}},"podMonitorNamespaceSelector":{},"podMonitorSelector":{},"query":{"maxConcurrency":1000},"replicas":2,"resources":{"limits":{"cpu":"4","memory":"6Gi"},"requests":{"cpu":"200m","memory":"400Mi"}},"retention":"7d","ruleNamespaceSelector":{},"ruleSelector":{"matchLabels":{"prometheus":"k8s","role":"alert-rules"}},"scrapeInterval":"1m","secrets":["kube-etcd-client-certs"],"securityContext":{"fsGroup":0,"runAsNonRoot":false,"runAsUser":0},"serviceAccountName":"prometheus-k8s","serviceMonitorNamespaceSelector":{},"serviceMonitorSelector":{},"storage":{"volumeClaimTemplate":{"spec":{"resources":{"requests":{"storage":"20Gi"}},"storageClassName":"rook-ceph-block"}}},"tolerations":[{"effect":"NoSchedule","key":"dedicated","operator":"Equal","value":"monitoring"}],"version":"v2.34.0"}}
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.34.0
  name: k8s
  namespace: kubesphere-monitoring-system
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - preference:
            matchExpressions:
              - key: node-role.kubernetes.io/monitoring
                operator: Exists
          weight: 100
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: prometheus
                app.kubernetes.io/instance: k8s
                app.kubernetes.io/name: prometheus
                app.kubernetes.io/part-of: kube-prometheus
            namespaces:
              - kubesphere-monitoring-system
            topologyKey: kubernetes.io/hostname
          weight: 100
  alerting:
    alertmanagers:
      - name: alertmanager-main
        namespace: kubesphere-monitoring-system
        port: web
  evaluationInterval: 1m
  image: 'prom/prometheus:v2.34.0'
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: k8s
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: kube-prometheus
      app.kubernetes.io/version: 2.34.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  query:
    maxConcurrency: 1000
  replicas: 2
  resources:
    limits:
      cpu: '4'
      memory: 6Gi
    requests:
      cpu: 200m
      memory: 400Mi
  retention: 7d
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  scrapeInterval: 1m
  secrets:
    - kube-etcd-client-certs
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi
        storageClassName: rook-ceph-block
  tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
      value: monitoring
  version: v2.34.0
```
