### ISSUE TITLE
Native histograms: error on ingesting out-of-order exemplars

### ISSUE THREAD

**Issue by krajorama** [prometheus/prometheus#12971]
### What did you do?

Scraping native histogram and classic histogram of the same metrics. And also having exemplars.

### What did you expect to see?

In a certain case, I expected to see two exemplars for both the classic and native histograms.

### What did you see instead? Under which circumstances?

Two exemplars seen for the classic histogram:

![exemplar1](https://github.com/prometheus/prometheus/assets/13435893/6eb35e42-e9cf-41f7-b2d6-243eecab12f5)
![exemplar2](https://github.com/prometheus/prometheus/assets/13435893/d42fa060-3293-44ac-b293-fb89f475e8a7)

Only one seen for 
![native-exemplar](https://github.com/prometheus/prometheus/assets/13435893/f386a70a-a316-40a5-b98d-94b449c5c679)

Also in the logs we get many of 
```
ts=2023-10-12T12:07:37.089Z caller=scrape.go:1744 level=warn component="scrape manager" 
  scrape_pool=histograms target=http://10.132.57.12:80/metrics 
  msg="Error on ingesting out-of-order exemplars" num_dropped=15
```

### System information

image: prom/prometheus:v2.47.0

### Prometheus version

```text
ts=2023-10-12T12:23:35.170Z caller=main.go:583 level=info msg="Starting Prometheus Server" mode=server version="(version=2.47.0, branch=HEAD, revision=efa34a5840661c29c2e362efa76bc3a70dccb335)"
ts=2023-10-12T12:23:35.170Z caller=main.go:588 level=info build_context="(go=go1.21.0, platform=linux/amd64, user=root@409eb5e6b30c, date=20230906-10:20:07, tags=netgo,builtinassets,stringlabels)"
ts=2023-10-12T12:23:35.171Z caller=main.go:589 level=info host_details="(Linux 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 efe41e303c55 (none))"

Features:
`enable-feature=promql-at-modifier,exemplar-storage,native-histograms`

Also in scrape:
`scrape_classic_histograms: true`
```

### Prometheus configuration file

```yaml
global:
        scrape_interval: 15s
    remote_write:
        - headers:
            X-Scope-OrgId: "***"
          send_exemplars: true
          send_native_histograms: true
          url: http://***.svc.cluster.local./api/prom/push
    scrape_configs:
        - job_name: histograms
          kubernetes_sd_configs:
            - role: pod
          metric_relabel_configs:
            - action: keep
              regex: cortex_request_duration_seconds.*
              source_labels:
                - __name__
          relabel_configs:
            - action: keep
              regex: .*-metrics
              source_labels:
                - __meta_kubernetes_pod_container_port_name
            - action: drop
              regex: ""
              source_labels:
                - __meta_kubernetes_pod_label_name
            - action: drop
              regex: Succeeded|Failed
              source_labels:
                - __meta_kubernetes_pod_phase
            - action: drop
              regex: "false"
              source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape
            - action: replace
              regex: (https?)
              replacement: $1
              source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scheme
              target_label: __scheme__
            - action: replace
              regex: (.+)
              replacement: $1
              source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_path
              target_label: __metrics_path__
            - action: replace
              regex: (.+?)(\:\d+)?;(\d+)
              replacement: $1:$3
              source_labels:
                - __address__
                - __meta_kubernetes_pod_annotation_prometheus_io_port
              target_label: __address__
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_param_(.+)
              replacement: __param_$1
            - action: labelmap
              regex: __meta_kubernetes_pod_label_prometheus_io_label_(.+)
            - action: labelmap
              regex: __meta_kubernetes_pod_annotation_prometheus_io_label_(.+)
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_label_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              separator: ':'
              source_labels:
                - __meta_kubernetes_pod_name
                - __meta_kubernetes_pod_container_name
                - __meta_kubernetes_pod_container_port_name
              target_label: instance
            - action: keep
              regex: ***
              source_labels:
                - __meta_kubernetes_namespace
            - replacement: dev-us-central-0
              target_label: cluster
            - replacement: nativehistogram
              target_label: prometheus_job
          scrape_classic_histograms: true
```

### Logs

```text
ts=2023-10-12T12:07:37.089Z caller=scrape.go:1744 level=warn component="scrape manager" 
  scrape_pool=histograms target=http://10.132.57.12:80/metrics 
  msg="Error on ingesting out-of-order exemplars" num_dropped=15
```
```
