### ISSUE TITLE
remote_write: Headers are not sent

### ISSUE THREAD

**Issue by zalintyre** [prometheus/prometheus#13030]
### What did you do?

I started prometheus with --enable-feature=agent. I configured custom headers with the remote_write configuration, but they are not sent with the request.

### What did you expect to see?

The custom headers being sent.

### What did you see instead? Under which circumstances?

```
POST / HTTP/1.1
Host: localhost:8888
User-Agent: Prometheus/2.42.0+ds
Content-Length: 4889
Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXX
Content-Encoding: snappy
Content-Type: application/x-protobuf
X-Prometheus-Remote-Write-Version: 0.1.0
```

### System information

Linux 6.1.0-rpi4-rpi-v6 armv6l

### Prometheus version

```text
prometheus/stable,now 2.42.0+ds-5 armhf
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    instance: 'hallway'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']

remote_write:
  - url: http://localhost:8888
    basic_auth:
      username: "XXXX"
      password: "XXXX"
    headers:
      "X-Scope-OrgID": "1"
      "A": "B"
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_
