### ISSUE TITLE
Workload identity support in Prometheus

### ISSUE THREAD

**Issue by rakshith210** [prometheus/prometheus#13061]
### Proposal

Currently, Prometheus supports basic auth, authorization headers, sigv4, azuread and oauth2 based authentication for remote write. Though these authentication mechanisms work for most of the scenarios, there are some Kubernetes scenarios where users would want to restrict the access to credential and secret to one pod or few pods in the Kubernetes cluster. It is in this case, workload identity would be the preferred and secure choice of authentication method. 

Workload identity leverages native Kubernetes components like [Service Account](https://kubernetes.io/docs/concepts/security/service-accounts/) and uses the token generated by the Service Account to authenticate with external identity providers like AWS IAM,  Azure Entra(previously known as Azure AD), GCP IAM and many more. This enables users to allow their Kubernetes cluster to interact with services/components behind different identity providers in a secure and seamless manner. 

In Prometheus remote write, adding workload identity support would help users to provide another secure path, especially for users running workloads in Kubernetes, to push Prometheus to different remote storage behind identity providers. My proposal is to expose another config block(`workload_identity`) and implement identity client for different identity providers based on the values provided. Here is an excerpt of the configuration I was thinking:

```
remote_write:
  url: <remote-endpoint-url>
  workload_identity:
    token_file_path: <path of the projected service account token file>  
    azuread:
    [Azure Entra related fields]
    gcp:
    [GCP IAM related fields]
    sigv4:
    [AWS IAM related fields]
```

Reference: [ServiceAccount token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#serviceaccount-token-volume-projection)
