### ISSUE TITLE
Empty activeAlertmanagers list

### ISSUE THREAD

**Issue by zoglam** [prometheus/prometheus#13064]
### What did you do?

Empty activeAlertmanagers list after executing reload method (0.001...5 sec)
1 Run prometheus with params (go run cmd/prometheus/main.go --config.file=config.yaml --web.enable-lifecycle)
config.yaml:
```yaml
alerting:
  alertmanagers:
  - http_sd_configs:
    - refresh_interval: 20s
      url: http://xxx/
    timeout: 1m
```
2 make request ```curl -sXPOST http://localhost:9090/-/reload```
3 and then you can try to open ```curl -s http://localhost:9090/api/v1/alertmanagers```
4 Output will be empty. looks like:
```{ "status": "success", "data": { "activeAlertmanagers": [], "droppedAlertmanagers": [] } }```
5 Only after executing peace of code prometheus will update the content of config.
Also reproduced on the main branch. refs:
https://github.com/prometheus/prometheus/blob/main/notifier/notifier.go#L310
^
https://github.com/prometheus/prometheus/blob/main/discovery/legacymanager/manager.go#L229-L255
^
https://github.com/prometheus/prometheus/blob/main/discovery/legacymanager/manager.go#L97

as a result, prometheus has a time window from 0.0001 to 5 seconds when downtime is possible

### What did you expect to see?

```{ "status": "success", "data": { "activeAlertmanagers": [<<<filled data>>>], "droppedAlertmanagers": [] } }```

### What did you see instead? Under which circumstances?

```{ "status": "success", "data": { "activeAlertmanagers": [], "droppedAlertmanagers": [] } }```

### System information

Linux 6.1.0-1012-oem x86_64

### Prometheus version

```text
prometheus, version 2.41.0 (branch: HEAD, revision: 3a097eb28e93d03b8af68bf8d0f4266e81be67d8)
  build user:       root@runner-375ab436-project-7748-concurrent-0bmfc7
  build date:       20230706-12:16:34
  go version:       go1.19.10
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
alerting:
  alertmanagers:
  - http_sd_configs:
    - refresh_interval: 20s
      url: http://xxx
    timeout: 1m
```
