### ISSUE TITLE
Support for specifying HTTP headers in scrape configs

### ISSUE THREAD

**Issue by gviczai** [prometheus/prometheus#13098]
### Proposal

Yes, I know that there are 3 separate closed issues regarding this feature. However I have a use-case, which adds some extra icing to this cake:
The official advice to add extra headers to a scrape request is to use a small proxy server, which handles this task.
My problem is, that in a complex dockerized environment when the proxy server becomes unavailable for some unfortunate reasons, Prometheus gladly reports that the backend service is down.  (The "up" metrics became 0 if the scraper can't access the target URL, which in this case the proxy url and not the "real" one.) Thus one cannot check the availability of the target service, just the availability of the target service AND the proxy service together.
IMHO adding headers to a request is neither requires a huge programming effort, nor it is a cpu-consuming runtime taks.
The scraper config already has username/password setting capability, which uses standard Authorization header, so technically speaking it is already there in the source code...
I think using a workaround as the official solution and maintaining a separate proxy server and keeping its config in sync with the prometheus config just because prometheus lacks this arbitrary header setting feature is a bit messy practice, violates the KISS and SSOT system design paradigms.

**Comment by gviczai** [comment]
https://github.com/prometheus/prometheus/issues/1724

**Comment by roidelapluie** [comment]
There is an open PR for this in prometheus common but no real interest. Please share your feedback on the pr

**Comment by roidelapluie** [comment]
https://github.com/prometheus/common/pull/416

**Comment by gviczai** [comment]
Thanks, actually, because you referenced #416 here, this issue automatically appeared on the timeline of #416, so I think I have nothing left to do. :)

I just add some additional related issues I found meanwhile:
https://discuss.prometheus.io/t/http-host-header-in-scrape-target/1214
https://github.com/prometheus/prometheus/pull/13009
(These two are closely related to each other as well, they both about setting the "Host" header, which is a fairly common problem.)

**Comment by k0ste** [comment]
My Prometheus 2.53.1 have a `http_headers` field with null value. I don't see anything in source code or documentation about it. Anybody know how-to use it (possibility)?

My current scrape configuration is:
```yaml
- job_name: prometheus
  scheme: https
  http_headers: null         <----- what is this?
  relabel_configs:
  - regex: __address__
    replacement: nb_fqdn
    action: labelmap
  - source_labels: [__address__]
    regex: ^(.*)(.example.local)$
    target_label: __address__
    replacement: $1.observability.example.com
    action: replace
```

What I want, is remove DNS dependency. From HTTP SD we already have IP address and 'Host' header to make a proper HTTP query. Something like

```yaml
- job_name: prometheus
  scheme: https
  relabel_configs:
  - regex: __address__
    replacement: nb_fqdn
    action: labelmap
  - source_labels: [__address__]
    regex: ^(.*)(.example.local)$
    target_label: __http_header_host__
    replacement: $1.observability.example.com
    action: replace
  - source_labels: [__meta_netbox_primary_ip]
    regex: (.*)
    target_label: __address__
    replacement: $1
    action: replace
```

**Comment by bboreham** [comment]
> a http_headers field with null value

Perhaps fixed by https://github.com/prometheus/common/pull/655.

@k0ste please open a new issue for your separate request about relabeling.

>  I think I have nothing left to do.

@gviczai can this issue be closed then?

**Comment by Masterwow3** [comment]
Thank you, it works for me (`http_headers`).
@k0ste here is an example:

````yml
  - job_name: 'my-job'
    scheme: https
    metrics_path: '/metrics'
    http_headers:
      my-custom-header: 
        values:
          - 'my-header-value'
    static_configs:
    - targets:
      - 'myservice.com:443'
````
