### ISSUE TITLE
Unable to Get the metrics in Grafana

### ISSUE THREAD

**Issue by varagur** [prometheus/prometheus#13101]
### What did you do?

Am able to scrape the metrics and able to see it using curl command curl http://localhost:port/metrics. But unable to see in Grafana , we don't see any errors in console we see the service as up . what could be the issue ?

### What did you expect to see?

na

### What did you see instead? Under which circumstances?

na

### System information

SUSE Linux Enterprise Server 12 (x86_64)

### Prometheus version

```text
prometheus-2.33.5
```

### Prometheus configuration file

```yaml
- job_name: 'xx'
    scrape_interval: xx
    scrape_timeout: xx
    static_configs:
      - targets: ['xx']
```

### Alertmanager version

```text
na
```

### Alertmanager configuration file

```yaml
na
```

### Logs

```text
na
```
