### ISSUE TITLE
Out of order sample from remote write With Telegraf outputs.http Output

### ISSUE THREAD

**Issue by skinfrakkiirid** [prometheus/prometheus#13104]
### What did you do?

I have configured remote write for Prometheus. However a lot of my metrics are not showing up. I see in journalctl -u prometheus the following:

caller=write_handler.go:109 level=error component=web msg="Out of order sample from remote write" err="out of order sample from remote write" err="out of order sample" series="

This happens with several metrics

### What did you expect to see?

The metrics within Prometheus

### What did you see instead? Under which circumstances?

Metrics missing

### System information

Linux 4.18.0-372.26.1.el8_6.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.41.0 (branch: HEAD, revision: c0d8a56c69014279464c0e15d8bfb0e153af0dab)
  build user:       root@d20a03e77067
  build date:       20221220-10:40:45
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    honor_timestamps: true

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```
