### ISSUE TITLE
Problems with kubernetes example

### ISSUE THREAD

**Issue by katcipis** [prometheus/prometheus#1312]
Im having some trouble following the kubernetes example, more specifically on the relabel part:

https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml#L25-L33

Any of these relabel rules results on the following error on startup:

```
Jan 12 17:15:05 monitoring docker[6082]: prometheus, version 0.16.1 (branch: stable, revision: 968ee35)
Jan 12 17:15:05 monitoring docker[6082]: build user:       @84057be02ab6
Jan 12 17:15:05 monitoring docker[6082]: build date:       20160111-15:30:09
Jan 12 17:15:05 monitoring docker[6082]: go version:       1.5.1
Jan 12 17:15:05 monitoring systemd[1]: prometheus.service: Main process exited, code=exited, status=1/FAILURE
Jan 12 17:15:05 monitoring systemd[1]: prometheus.service: Unit entered failed state.
Jan 12 17:15:05 monitoring systemd[1]: prometheus.service: Failed with result 'exit-code'.
Jan 12 17:15:05 monitoring docker[6082]: time="2016-01-12T17:15:05Z" level=info msg="Loading configuration file /prometheus/cfg/prometheus.yml" source="main.go:196"
Jan 12 17:15:05 monitoring docker[6082]: time="2016-01-12T17:15:05Z" level=error msg="Couldn't load configuration (-config.file=/prometheus/cfg/prometheus.yml): relabel configuration requires a regular expression" source="main.go:208"
```

Im using the latest prometheus image at docker hub. Am I doing something wrong ?

**Comment by jimmidyson** [comment]
Sorry, looks like we've got examples out of sync with releases - in this case sensible defaults for relabel regexes to reduce verbosity of config. The syntax in the example requires master. You can use `prom/prometheus:master` & that should work.

**Comment by fabxc** [comment]
New default values were introduced in master. Please check the same file at
the 0.16.1 tag, which is the version you are running.

The example should be in sync with the code, the latest Docker tag points
to the last release.

**Comment by katcipis** [comment]
Using the prometheus:master image made everything work fine, thanks @jimmidyson. Now im having other problem.

Im trying to scrap information from my RabbitMQ instance, that is running inside k8s. I added the exporter on the same pod as the rabbit and exported the container port.

rc file:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.5.4-management
        name: rabbitmq
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-vol
        ports:
        - containerPort: 5672
          name: service
        - containerPort: 15672
          name: management
      - image: kbudde/rabbitmq-exporter
        name: rabbitmq-exporter
        volumeMounts:
        - mountPath: /var/lib/rabbitmq-exporter
          name: rabbitmq-vol
        ports:
        - containerPort: 9090
          name: exporter
      volumes:
        - name: rabbitmq-vol
          persistentVolumeClaim:
           claimName: rabbitmq
```

svc file:

```
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - port: 5672
      name: service
      targetPort: service
      protocol: TCP
    - port: 9090
      name: exporter
      targetPort: exporter
      protocol: TCP
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: rabbitmq
```

Then I check the running service, the endpoint is there:

```
Name:			rabbitmq
Namespace:		default
Labels:			name=rabbitmq
Selector:		app=rabbitmq
Type:			ClusterIP
IP:			10.100.200.148
Port:			service	5672/TCP
Endpoints:		10.244.50.21:5672
Port:			exporter	9090/TCP
Endpoints:		10.244.50.21:9090
Session Affinity:	None
No events.
```

Using the default configuration, found on the docs, I got no data (and no warning or error on the logs). If I configure prometheus to manually scrap the endpoint **10.244.50.21:9090**, it works, so it is not connectivity.

I thought I could have missed the annotation, but when I tried to create it I got the error:

```
root@195da9ce6e6b:/harbor/data# kubectl -s http://10.4.2.134:8080 annotate svc rabbitmq prometheus.io/scrape="true"
error: --overwrite is false but found the following declared annotation(s): 'prometheus.io/scrape' already has a value (true)
```

So my rabbitmq svc is already annotated. Here is my whole config (<master-ip> is where the address of the master would be, im working with ip right now, not DNS):

```
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
        external_labels:
          monitor: 'core'
      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 5s
          scrape_timeout: 10s
          target_groups:
            - targets: ['127.0.0.1:9100']
        - job_name: 'k8s-cluster'
          scrape_interval: 5s
          scrape_timeout: 10s
          kubernetes_sd_configs:
          - api_servers:
            - 'http://<master-ip>:8080'
            bearer_token_file: bearer_token
            kubelet_port: 10255
            in_cluster: true
          relabel_configs:
          - source_labels: [__meta_kubernetes_role]
            action: keep
            regex: (?:apiserver|node)
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - source_labels: [__meta_kubernetes_role]
            action: replace
            target_label: kubernetes_role
        # Scrape config for service endpoints.
        #
        # The relabeling allows the actual service scrape endpoint to be configured
        # via the following annotations:
        #
        # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
        # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
        # to set this to `https` & most likely set the `tls_config` of the scrape config.
        # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
        # * `prometheus.io/port`: If the metrics are exposed on a different port to the
        # service then set this appropriately.
        #
        - job_name: 'kubernetes-service-endpoints'
          kubernetes_sd_configs:
          - api_servers:
            - 'http://<master-ip>:8080'
            bearer_token_file: bearer_token
            kubelet_port: 10255
            in_cluster: true
          relabel_configs:
          - source_labels: [__meta_kubernetes_role, __meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: endpoint;true
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
            action: replace
            target_label: __scheme__
            regex: (https?)
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)(?::\d+);(\d+)
            replacement: $1:$2
          - action: labelmap
            regex: __meta_kubernetes_service_label_(.+)
          - source_labels: [__meta_kubernetes_role]
            action: replace
            target_label: kubernetes_role
          - source_labels: [__meta_kubernetes_service_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            action: replace
            target_label: kubernetes_name
```

Any idea of what I may be doing wrong ?
