### ISSUE TITLE
Prometheus remote write receiver is receiving duplicate data

### ISSUE THREAD

**Issue by zibinli** [prometheus/prometheus#13125]
### What did you do?

 After reporting only one sequence at 11:04:25, it stopped reporting, and the query end shows this data for the subsequent 5 minutes.

### What did you expect to see?

Only the data corresponding to the timestamp should be displayed, it should not default to using the data from the last point.

### What did you see instead? Under which circumstances?

 After reporting only one sequence at 11:04:25, it stopped reporting, and the query end shows this data for the subsequent 5 minutes.

### Prometheus version

```text
prometheus, version 2.47.2 (branch: HEAD, revision: 3f3172cde1ee37f1c7b3a5f3d9b031190509b3ad)
  build user:       root@79f2ad339b75
  build date:       20231012-16:07:10
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

storage:
  tsdb:
    out_of_order_time_window: 60m
```
