### ISSUE TITLE
openstack_sd_config: be able to pass a list of regions

### ISSUE THREAD

**Issue by bmm-alc** [prometheus/prometheus#13140]
### Proposal

From the documentation, in `openstack_sd_config` there is a parameter `region` which is a string. 

**Issue**: When one have several region in different zone in the world this is cumbersome to replicate all this. Perhaps passing a clouds.yml with all regions would do the trick also.

**Improvement**: would be great to have a parameter `regions` that  would take a list of regions (as does ansible).

**Comment by roidelapluie** [comment]
How does that map in the API?

**Comment by bmm-alc** [comment]
Hi @roidelapluie 

Sorry, I don't get your question (I'm not developer), could you explain what do you expect from me ?

Thanks

**Comment by beorn7** [comment]
Hello from the bug scrub!

We need some input from an Openstack expert here.

Generally, we have the problem of unmaintained SD mechanisms in Prometheus. We would welcome Openstack experts to help and become maintainers of the relevant part of the code. Then it would be possible to tackle requests like this.

**Comment by paulojmdias** [comment]
The `Region` field is a string under https://pkg.go.dev/github.com/gophercloud/gophercloud/v2#EndpointOpts. Supporting this may only create a client per `region`, however, I don't know if that makes sense the effort but let the maintainers discuss this.

@bmm-alc You can make your `openstack_sd_configs` have one SD config per region. This is already the current and suggested behavior for multiple SDs like GCE and AWS.

```yaml
openstack_sd_configs:
  - all_tenants: true
    domain_name: domamin1
    identity_endpoint: https:/localhost:5000
    password: password
    port: 8080
    project_name: project1
    refresh_interval: 15s
    region: Region1
    role: instance
    tls_config:
      insecure_skip_verify: true
    username: username
  - all_tenants: true
    domain_name: domamin1
    identity_endpoint: https:/localhost:5000
    password: password
    port: 8080
    project_name: project1
    refresh_interval: 15s
    region: Region2
    role: instance
    tls_config:
      insecure_skip_verify: true
    username: username
```
