### ISSUE TITLE
Unable To Start Prometheus Services On Linux WSL

### ISSUE THREAD

**Issue by Mukesh-Lekhrajani** [prometheus/prometheus#13162]
### What did you do?

Hello,

I installed Prometheus by looking at the steps mentioned in - 

https://www.linkedin.com/pulse/how-install-prometheus-ubutnu-2004-shubham-sahu/

and now, I am trying to start the Prometheus service - by using the 2 commands below :

sudo systemctl daemon-reload
sudo systemctl start prometheus

### What did you expect to see?

the Prometheus service should start and the below link should work : 

http://localhost:9090/

### What did you see instead? Under which circumstances?

it is producing an error -

waiver@DESKTOP-EGS7FV2:/usr/share$ sudo systemctl daemon-reload
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

waiver@DESKTOP-EGS7FV2:/usr/share$ sudo systemctl start prometheus
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

### System information

Ubuntu 22.04.1 LTS

### Prometheus version

```text
waiver@DESKTOP-EGS7FV2:/usr/share$ prometheus --version
prometheus, version 2.48.0 (branch: HEAD, revision: 6d80b30990bc297d95b5c844e118c4011fad8054)
  build user:       root@26117804242c
  build date:       20231116-04:35:21
  go version:       go1.21.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```

### Alertmanager version

```text
alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo
```
