### ISSUE TITLE
Missing metadata (Help and Type) in a receiver Prometheus UI (get the data by remote write)

### ISSUE THREAD

**Issue by yoavim86** [prometheus/prometheus#13163]
### What did you do?

1. Executed Node exporter (docker)
2. Prometheus A which collects the metrics from the node exporter and sends the data by remote write to Prometheus B (docker)
3. Prometheus B which gets data from Prometheus A by remote write (docker)

All of them executed  locally on my laptop 

### What did you expect to see?

When I'm observing the metrics in Prometheus B I would expect to see the metric Help and the metric Type (the node exporter metrics), as I can see in Prometheus A. 

The image is from A (with the Help and Type):

![Uploading image.png…]()

### What did you see instead? Under which circumstances?

I don't see the Help and the Type of the metrics in the UI of Prometheus B (the one who get the data by remote write)

![Uploading image.png…]()

### System information

Darwin 22.6.0 arm64

### Prometheus version

```text
prometheus-2.47.0.darwin-amd64
```

### Prometheus configuration file

```yaml
# Prometheus A (prometheus-a.yml)
global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node Exporter's address

remote_write:
  - url: "http://my-prometheusB:9090/api/v1/write"
```
