### ISSUE TITLE
Azure SD stopped working for VMSS instances after upgrade from 2.41 > 2.48

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/prometheus#13245]
### What did you do?

Azure SD stopped working for VMSS instances after upgrade from 2.41 > 2.48.

```
  - job_name: tmp
    azure_sd_configs:
      - subscription_id: 'xxx-xxx-xxx-xxx'
        authentication_method: ManagedIdentity
        resource_group: 'xxx'
        proxy_from_environment: true
```
It was working fine with 2.41 for both VM and VMSS instances but after upgrade it is discovering only regular VMs.
Any instance within VM Scaling Set is not discovered and the error is returned (as many errors as VMSS you have): 

```
ts=2023-12-04T17:19:13.235Z caller=azure.go:391 level=warn component="discovery manager scrape" 
discovery=azure config=tmp msg="Network interface does not exist" 
name=/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachineScaleSets/nomad-main-xxx-vmss/virtualMachines/282/networkInterfaces/primary.nic 
err="network interface does not exist"
```

Moreover, I checked the resource in error by following the path `/subscriptions/xxx-xxx-xxx-xxx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachineScaleSets/nomad-main-xxx-vmss/virtualMachines/282/networkInterfaces/primary.nic` and there is no problem to see it.

### What did you expect to see?

Azure SD working as previously.

### What did you see instead? Under which circumstances?

Missing VMSS instances in Targets. Only VMs are present.
