### ISSUE TITLE
Scraping samples with out_of_order_time_window results in "too old sample"

### ISSUE THREAD

**Issue by Evynglais** [prometheus/prometheus#13272]
### What did you do?

Our setup exposes 'old' samples parsed from Java Flight Recorder events, using the event timestamp as the timestamp of the sample. None of the exposed metrics are more than 1 minute old. Currently, we have one Java application reporting data; however, the intention is to have many.

I've configured `out_of_order_time_window` to a positive value -- I've tried 1m, 5m, 1d, and 365d.

### What did you expect to see?

The metrics accepted into Prometheus, so long as the sample timestamp is within the following region:

`Sample Timestamp >= TSDB.maxTime - out_of_order_time_window`

As per [the documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tsdb).

### What did you see instead? Under which circumstances?

The target is reported as `down` with the error: `too old sample`.

This is the same result regardless of the `out_of_order_time_window` chosen.

### System information

Docker Desktop on Windows 11

### Prometheus version

```text
prometheus, version 2.48.0 (branch: HEAD, revision: 6d80b30990bc297d95b5c844e118c4011fad8054)
  build user:       root@26117804242c
  build date:       20231116-04:35:21
  go version:       go1.21.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s

storage:
  tsdb:
    out_of_order_time_window: 5m
    
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: localhost
    metrics_path: '/metrics'
    scrape_timeout: 15s
    scrape_interval: 15s
    basic_auth:
      username: [username]
      password: [password]
    static_configs:
    - targets: [URL]
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
No logs output during target scrape failure.
```
