### ISSUE TITLE
getting error while saving prometheus.yaml

### ISSUE THREAD

**Issue by aliiraza4064** [prometheus/prometheus#13306]
### What did you do?

I deployed my node_exporter on a URL on ``mon.example.net/nodexpo`` and when I reloaded my service getting error that hostname is not correct.
I've many nodes to scrap data each node also have docker and cAdvisor running on it. I'm also new to Prometheus. I need to run this on Production.

### What did you see instead? Under which circumstances?

```
 prometheus.service - Prometheus
     Loaded: loaded (/etc/systemd/system/prometheus.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-12-18 13:12:37 UTC; 34s ago
    Process: 3897 ExecStart=/usr/local/bin/prometheus --config.file /etc/prometheus/prometheus.yml --storage.tsdb.path /var/lib/prometheus/ --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries (code=exited, status=2)
   Main PID: 3897 (code=exited, status=2)
        CPU: 56ms

Dec 18 13:12:37 prom1 systemd[1]: Started Prometheus.
Dec 18 13:12:37 prom1 prometheus[3897]: ts=2023-12-18T13:12:37.787Z caller=main.go:482 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: \"mon.example.net/nodexpo\" is not a valid hostname"
Dec 18 13:12:37 prom1 systemd[1]: prometheus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 18 13:12:37 prom1 systemd[1]: prometheus.service: Failed with result 'exit-code'.

```

### System information

Linux 6.2.0-1018-azure x86_64

### Prometheus version

```text
prometheus, version 2.45.1 (branch: HEAD, revision: c62de5d1075d9c24a281b4b719f124f14e730fa5)
  build user:       root@827ead67e852
  build date:       20230929-21:10:51
  go version:       go1.20.8
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 10s
  external_labels:
    monitor: 'prometheus'


scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['x.x.x.x:9100', 'mon.example.net/nodexpo']  # Use the service name or IP of your Node Exporter container

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['x.x.x.x:8080']  # Use the service name or IP of your cAdvisor container

  - job_name: 'docker'
    static_configs:
      - targets: ['x.x.x.x:9323']  # Use the service name or IP of your cAdvisor container
```

**Comment by aliiraza4064** [comment]
location /nodexpo {
        proxy_pass http://localhost:8090/metrics;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
    }

also this is my nginx configuration.

**Comment by machine424** [comment]
A simple search in the code:

https://github.com/prometheus/prometheus/blob/5d5303c746a4609520cd3d910fd445596fb86522/config/config.go#L1008C2-L1014

And the doc also mentions that https://prometheus.io/docs/prometheus/latest/configuration/configuration/#host

(IMHO, this type of support question is better suited for Slack. Let's reserve GitHub issues for reporting bugs and suggesting new features)

**Comment by aliiraza4064** [comment]
> A simple search in the code:
> 
> https://github.com/prometheus/prometheus/blob/5d5303c746a4609520cd3d910fd445596fb86522/config/config.go#L1008C2-L1014
> 
> And the doc also mentions that https://prometheus.io/docs/prometheus/latest/configuration/configuration/#host
> 
> (IMHO, this type of support question is better suited for Slack. Let's reserve GitHub issues for reporting bugs and suggesting new features)

I don't think their are any resource available. That shows how to expose node_exporter through reverse proxy. if any please mention.

**Comment by roidelapluie** [comment]
You should use metrics_path.

Here's how your updated configuration could look:

```yaml
- job_name: 'node'
  metrics_path: '/nodexpo'
  static_configs:
    - targets: ['mon.example.net']
```


You could also use a fancier version to keep the other target, using relabeling :

```yaml
- job_name: 'node'
  relabel_configs:
    - source_labels: [__address__]
      regex: 'mon\.example\.net(.*)'
      target_label: __metrics_path__
      replacement: '$1'
    - source_labels: [__address__]
      regex: 'mon\.example\.net(.*)'
      replace: mon.example.net
  static_configs:
    - targets: ['x.x.x.x:9100', 'mon.example.net/nodexpo']
```
