### ISSUE TITLE
Prometheus component huge resource utilization

### ISSUE THREAD

**Issue by b0kky** [prometheus/prometheus#13317]
### What did you do?

Hello prometheus team! We faced with problem with prometheus component in grafana-agent app. 
Using remote-write and victoria-metrics cluster as endpoint. 

```
VM1 with grafana agent: Linux test-agent38 6.0.7-301.fc37.x86_64
Fedora:37 with 2 CPU\2 RAM

Main fs dev: /dev/nvme0n1p3 with btrfs

Grafana-agent: version: 38.1

Tuned agent remote-write config (other settings as an early posted config)
    remote_write:
    - queue_config:
        capacity: 5000
        max_samples_per_send: 1000
        max_shards: 100
        min_backoff: 30s
        max_backoff: 60s
      remote_timeout: 30s
      url: http://172.18.200.55:7480/insert/0/prometheus/api/v1/write
```

Got this error:
```
ts=2023-12-21T09:17:43.683261954Z caller=dedupe.go:112 agent=prometheus instance=7e9527f8948db1b008afdfc2db12c2c4 component=remote level=warn remote_name=7e9527-2a7f5b url=https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write\": context deadline exceeded"
```
while remote-write endpoint is available.

So curl working from host and from the container. curl'ed with  test insert, and got 204 (expected):
```
curl -d "GOOG,1.23,4.56,NYSE" 'https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/import/csv?format=2:metric:ask,3:metric:bid,1:label:ticker,4:label:market'

< HTTP/2 204 
< date: Thu, 21 Dec 2023 09:26:40 GMT
< vary: Accept-Encoding
< x-server-hostname: vm-cluster-victoria-metrics-cluster-vminsert-8884b95b5-vjgzr
< strict-transport-security: max-age=15724800; includeSubDomains
```
Attempts to change  queue_config, were not successfully, after some time, prometheus component return error. 

Also create a bug in grafana-agent project  https://github.com/grafana/alloy/issues/295

### What did you expect to see?

Remote write working without  errors

### What did you see instead? Under which circumstances?

Errors:
```
ts=2023-12-21T09:17:43.683261954Z caller=dedupe.go:112 agent=prometheus instance=7e9527f8948db1b008afdfc2db12c2c4 component=remote level=warn remote_name=7e9527-2a7f5b url=https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage/insert/0/prometheus/api/v1/write\": context deadline exceeded"
```

### System information

6.0.7-301.fc37.x86_64 Fedora:37

### Prometheus version

```text
prometheus component version 2.47.2
```

### Prometheus configuration file

```yaml
metrics:
  configs:
  - name: grafana-agent
    scrape_configs:
    - docker_sd_configs:
      - host: unix:///run/docker.sock
        host_networking_host: 127.0.0.1
        refresh_interval: 60s
      job_name: docker
      relabel_configs:
      - source_labels:
        - __meta_docker_container_label_com_docker_compose_project
        target_label: pod
      - replacement: ${HOSTNAME}
        source_labels:
        - instance
        target_label: namespace
      - source_labels:
        - __meta_docker_container_name
        target_label: container
      - source_labels:
        - __meta_docker_container_label_com_docker_compose_project
        target_label: compose_project
      - source_labels:
        - __meta_docker_container_label_com_docker_compose_service
        target_label: compose_service
      - action: keep
        regex: .+
        source_labels:
        - __meta_docker_container_label_prometheus_job
      - action: replace
        regex: (.+)
        replacement: $1
        source_labels:
        - __meta_docker_container_label_prometheus_job
        target_label: job
      - action: replace
        regex: (.+)
        replacement: $1
        source_labels:
        - __meta_docker_container_label_prometheus_path
        target_label: __metrics_path__
      - action: replace
        regex: (.+)
        replacement: $1
        source_labels:
        - __meta_docker_container_label_prometheus_scheme
        target_label: __scheme__
      - regex: ([^:]+).*;(\d+)
        replacement: $1:$2
        separator: ;
        source_labels:
        - __address__
        - __meta_docker_container_label_prometheus_port
        target_label: __address__
      - regex: (.+);[^:]+:(\d+)
        replacement: $1:$2
        separator: ;
        source_labels:
        - __meta_docker_container_label_prometheus_host
        - __address__
        target_label: __address__
      - regex: ^([^:]+);([^:])+$
        replacement: $1
        separator: ;
        source_labels:
        - __meta_docker_container_label_prometheus_host
        - __address__
        target_label: __address__
      - regex: (.+)
        replacement: $1
        source_labels:
        - __meta_docker_container_label_prometheus_scrape_timeout
        target_label: __scrape_timeout__
      - regex: (.+)
        replacement: $1
        source_labels:
        - __meta_docker_container_label_prometheus_scrape_interval
        target_label: __scrape_interval__
      tls_config:
        insecure_skip_verify: true
  global:
    external_labels: {}
    remote_write:
    - queue_config:
        capacity: 5000
        max_samples_per_send: 1000
        max_shards: 100
        min_backoff: 30s
        max_backoff: 60s
      remote_timeout:30s
      url: http://172.18.200.126:7480/insert/0/prometheus/api/v1/write
      write_relabel_configs:
      - replacement: ${GA_METRICS_REMOTE_WRITE_WRITE_RELABEL_CONFIG_REPLACEMENT}
        source_labels:
        - __address__
        target_label: ${GA_METRICS_REMOTE_WRITE_WRITE_RELABEL_CONFIG_TARGET_LABEL}
      - replacement: ${GA_METRICS_REMOTE_WRITE_WRITE_RELABEL_CONFIG_REPLACEMENT}
        source_labels:
        - __address__
        target_label: cluster
    scrape_interval: 1m
```

### Logs

```text
ts=2023-12-20T21:07:32.018835803Z caller=dedupe.go:112 agent=prometheus instance=7e9527f8948db1b008afdfc2db12c2c4 component=remote level=warn remote_name=7e9527-2a7f5b url=https://metrics.sto-aws-stage.itrf.tech/insert/0/prometheus/api/v1/write msg="Failed to send batch, retrying" err="Post \"https://metrics.sto-aws-stage.itrf.tech/insert/0/prometheus/api/v1/write\": context deadline exceeded"
```
