### ISSUE TITLE
Metric being reported with wrong labels

### ISSUE THREAD

**Issue by jademcosta** [prometheus/prometheus#13322]
### What did you do?

Queryed Prometheus and other types of metric systems that receive remote-write from different instances of Prometheus (both reading the same scrape targets).

### What did you see instead? Under which circumstances?

We have a bunch of microservices here on the company. For some time I've been receiving reports from people being alerted on metrics that their services doesn't expose.

This week I finally got to see the problem. A metric from another service got reported for a brief moment as being from a service it isn't from.

So, the service `M` reported this metric (picture 1). I'm 100% sure that this service doesn't report this metric. It is reported **only** by the `P` service (picture 2).

This is a hard to catch bug given the randomness it happens, and given our large amount of data.

We have a setup where 1 "regular" (server) Prometheus instance gets data and ingest. Later a Thanos sidecar sends this data to an S3 bucket. The error appeared there.

We have another Prometheus running in "agent" mode, sending metrics into Victoriametrics. The same error showed there. Given that, my guess is that the problem is somewhere on the "scraping path" or the "WAL path" (I don't know if both versions of Prometheus share any part of the WAL logic.

As it is something that started to show up only this year, I believe it started around version `2.40.4`. We're currently at the `2.47.2` (we used the most recent but had to rollback given a new `warning` message in queries breaking one internal integration of ours).

Another thing that caught my attention is that the `instance` label is correct. The IP address of the wrongly-reported metric is from `M` service.

One more information: we have Prometheus "server" configured in HA, and both instances had the same problem.

Last information is that all instances hold a pretty high number of metrics. I'm talking about 400Gb+ instances.

Does anyone faced something like this recently?

Picture 1:
![picture1](https://github.com/prometheus/prometheus/assets/999803/6db56cfc-3a5a-41d7-a4d3-db572b30a461)

Picture 2:
![picture2](https://github.com/prometheus/prometheus/assets/999803/e6b8a96d-f1b2-4da8-882c-41f5321e71f6)

### System information

Linux 5.10.198-187.748.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.47.2 (branch: HEAD, revision: 3f3172cde1ee37f1c7b3a5f3d9b031190509b3ad)
  build user:       root@79f2ad339b75
  build date:       20231012-16:07:10
  go version:       go1.21.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
Sending here just the job that is the one doing the scrapes:

job_name: '<REMOVED>'
  kubernetes_sd_configs:
  - role: pod
  scheme: https
  honor_labels: true
  sample_limit: 600000
  bearer_token_file: <REMOVED>
  tls_config:
    <REMOVED>
  relabel_configs:
  # This rule exists just to add a label to all metrics
  - action: replace
    source_labels: [__address__]
    regex: .*
    replacement: <REMOVED>
    target_label: <REMOVED>
  - source_labels: [__meta_kubernetes_pod_label_<REMOVED>]
    regex: (<REMOVED>|<REMOVED>)
    action: drop
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_high_latency]
    regex: '.+'
    action: drop
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: ^(https?)$
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - source_labels: [__meta_kubernetes_namespace]
    action: drop
    regex: '<REMOVED>'
  - source_labels: [__meta_kubernetes_namespace]
    action: drop
    regex: 'kube-system'
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_label_<REMOVED>]
    action: replace
    target_label: service
  - source_labels: [__meta_kubernetes_pod_label_<REMOVED>]
    action: replace
    target_label: tier
  - action: labeldrop
    regex: __meta_kubernetes_pod_label_<REMOVED>
  metric_relabel_configs:
  <Here we just have a bunch of drops for high-cardinality metrics>
```

**Comment by roidelapluie** [comment]
Can we please have the command line flags you use, to know which experimental features you are using? Thanks

**Comment by jademcosta** [comment]
Sure.

For the agent:

```
--config.file=/etc/prometheus/prometheus.yml \
  --enable-feature=agent \
  --storage.agent.path=/prometheus \
  --storage.agent.retention.min-time="10m" \
  --storage.agent.retention.max-time="20m" \
  --storage.agent.wal-truncate-frequency="10m" \
  --web.enable-admin-api \
  --web.enable-lifecycle \
  --log.level="info" \
  --log.format="json" \
  --web.listen-address=":9090" \
  --enable-feature=auto-gomaxprocs  &
```

For the server:

```
--config.file=/etc/prometheus/prometheus.yml \
  --storage.tsdb.no-lockfile \
  --storage.tsdb.path=/prometheus \
  --web.console.libraries=/usr/share/prometheus/console_libraries \
  --web.console.templates=/usr/share/prometheus/consoles \
  --web.enable-admin-api \
  --web.enable-lifecycle \
  --web.enable-remote-write-receiver \
  --log.level="info" \
  --log.format="json" \
  --storage.tsdb.min-block-duration="2h" \
  --storage.tsdb.max-block-duration="2h" \
  --storage.tsdb.retention.time="2d" \
  --query.max-concurrency=20 \
  --query.timeout=2m \
  --web.external-url="<REMOVED>" \
  --enable-feature=auto-gomaxprocs  \
  --enable-feature=memory-snapshot-on-shutdown &
```

**Comment by AlexandreGuidin** [comment]
Hey, any update on this?

**Comment by jademcosta** [comment]
I think a coworker of mine found the problem.
We had the same IP being used for different pods. This led to the case where the label `__address__` is the same for different pods, which might be the cause for the metrics to get mixed.

Do you know if this is something that would happen if 2 targets have the same IP/`__address__`, @roidelapluie ?

**Comment by sthomson-wyn** [comment]
We are also experiencing this issue

- Pod A runs, ends up in "Completed" state (pod still exists with ip, but is not running)
- k8s schedules Pod B, running with that same ip
- metrics scraped from pod B incorrectly have labels from pod A assigned to them

Here is our config for this particular job

```
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              metric_relabel_configs: []

              relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: kubernetes_namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: kubernetes_pod_name
```

Is something obviously wrong there, or is this a prometheus bug?

**Comment by chlunde** [comment]
We're also seeing the same issue in a cluster with very frequent IP recycling.

https://docs.aws.amazon.com/eks/latest/best-practices/vpc-cni.html
> When a Pod is deleted, VPC CNI places the Pod’s IP address in a 30-second cool down cache. The IPs in a cool down cache are not assigned to new Pods. When the cooling-off period is over, VPC CNI moves Pod IP back to the warm pool. The cooling-off period prevents Pod IP addresses from being recycled prematurely and allows kube-proxy on all cluster nodes to finish updating the iptables rules.

I suspect it's just a race condition between the service discovery, scraping and pod start/stops. I'm not sure what Prometheus could do here, except look at the latency between service dicscovery updating/canceling scraping scheduling. (Doing a "final scrape" for stopped pods is also very valuable to not loose any data, so looking at the phase for pods and avoiding terminating pods will cause other issues)

In our cluster, we can use a query like this to detect fast IP changes:
`count(count(up{job="kubernetes-pods"}) by (instance, pod)) by (instance)>1`

We'll try to increase subnet size to see if the issue is resolved.

**Comment by alexgreenbank** [comment]
Hello from the bug scrub.

We are not sure whether this is a bug or expected behaviour given the quick recycle/reuse times of pod IP addresses.

Ping @brancz for thoughts?

**Comment by amanpruthi** [comment]
We are facing this issue even when the pod spun up 4 mins late with the same ip on eks. 
This issue was fixed when the completed cronjob pod was deleted.
Is this a bug in kubernetes_sd_config ?

**Comment by nantiferov** [comment]
Seems we're observing similar issue with Prometheus 3.3.1

serviceMonitor created by https://github.com/spotahome/redis-operator creates scrape job using `kubernetes_sd`.

And while documentation promises `Kubernetes SD configurations allow retrieving scrape targets from Kubernetes' REST API and **always staying synchronized with the cluster state**.`, pod labels aren't updated.

Basically redis-operator updates `redisfailovers-role` label on each pod according to its role atm: master/replica. And while labels are correct on the pod level, Prometheus reports both of them replicas:

Relabeling configuration:
```yaml
spec:
  endpoints:
    - port: http-metrics
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_label_redisfailovers_role
          targetLabel: redis_role
```

Pods labels:
```
$k get pods -owide | grep foo42
rfr-foo42-0                                         3/3     Running   1 (3h38m ago)   3h39m   x.x.x.x     node-x   <none>           <none>
rfr-foo42-1                                         3/3     Running   3 (3h39m ago)   31d     x.x.x.x  node-y   <none>           <none>

$k describe pod rfr-foo42-0 |grep role
                  redisfailovers-role=slave

$k describe pod rfr-foo42-1 |grep role
                  redisfailovers-role=master
```

Results from status discovery and metrics itself: Both pods have same `redis_role`.
Restart of Prometheus helps, but it's quickly gets out of sync with changes.

I'll try to update Prometheus to latest version, but I don't have high hopes.
**UPD:** Updated to latest 3.5.0, no changes, labels still stale.

P.S. Restart of Prometheus fixes the issue, but only until next change in Pod labels.

**Comment by ikonst** [comment]
I've also spotted this seldomly happening: metrics from new pod (with same IP) being labeled with old pod's labels.

This can be probably worked around with `honor_labels: true` and assigning labels in service code, but it's clearly suboptimal and contradicts [official guidance](https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels).
```golang
prometheus.DefaultRegisterer = prometheus.WrapRegistererWith(prometheus.Labels{
	"abc": os.Getenv("K8S_LABEL_ABC"),
        // ...
}, prometheus.DefaultRegisterer)
```

From the docs:

> It’s not for an application to say where it fits in your label taxonomy, that’s for the person running the Prometheus server to configure and different people monitoring the same application may give it different names.

Potential compromise would be for the service code to attach only a `__meta_kubernetes_pod_uid`, label, which wouldn't necessarily require Prometheus to honor it, but would cause the metrics to be dropped (or be queued for an SD update, if that's possible, though of course the SD update might never come).

P.S. can `keepequal` do the trick?
```yaml
relabel_configs:
  - source_labels: [ __meta_kubernetes_pod_uid ]
    target_label: __meta_kubernetes_pod_uid
    action: keepequal
```

**Comment by roidelapluie** [comment]
The root cause is probably the throttling mechanisms in Prometheus's service discovery and scrape management.

There are two layers of throttling that delay target updates. First, the discovery manager batches all service discovery updates and sends them at most once every 5 seconds (hardcoded) (from the code: _Some discoverers send updates too often, so we throttle these with the ticker._).
Second, the scrape manager has its own reload throttle (default 5 seconds, configurable via the hidden flag `--scrape.discovery-reload-interval`). Even after receiving discovery updates, the scrape manager waits for the next ticker cycle before calling `sp.Sync()` to stop old targets and start new ones.

This creates a race condition when Kubernetes recycles pod IPs quickly. When Pod A terminates and Pod B immediately gets the same IP address, the discovery update can be delayed by up to ~10s (In practice I think 5 s). During this window, Pod A's scrape target continues running. When it scrapes the recycled IP address, it receives Pod B's metrics but applies Pod A's labels, resulting in the incorrect labeling reported in this issue.


One fix would be to make discovery updates throttling configurable or even affected by `--scrape.discovery-reload-interval` ?

Note: The throttling exists for legitimate performance reasons - to prevent excessive CPU usage and system churn in large, dynamic environments. The trade-off is that the current design prioritizes system stability over label correctness during rapid IP recycling, which are a small subset of all the environments Prometheus monitors.

**Comment by roidelapluie** [comment]
Additionally, for the specific case of CronJob pods mentioned in the comments, the issue can be mitigated with relabeling configuration. Prometheus discovers all pods regardless of phase, so Completed/Succeeded pods remain as scrape targets until they're deleted from Kubernetes. When their IPs are reused, you end up with two targets trying to scrape the same IP.

You can drop Completed/Succeeded pods from discovery using:

```yaml
relabel_configs:
  - source_labels: [__meta_kubernetes_pod_phase]
    action: drop
    regex: (Pending|Succeeded|Failed)
```

This prevents the scenario where a Completed CronJob pod's target continues scraping a recycled IP that now belongs to a new Running pod.

**Comment by ikonst** [comment]
Am I correct to understand that a cooldown of >10s for IP recycling is supposed to mitigate this as well?

**Comment by roidelapluie** [comment]
Yes but you might need :

```
relabel_configs:
  - source_labels: [__meta_kubernetes_pod_phase]
    action: drop
    regex: (Pending|Succeeded|Failed)
```

as well, WDYT?
