### ISSUE TITLE
Prometheus Scrape Fails with HTTP 406 Error

### ISSUE THREAD

**Issue by HamishWa** [prometheus/prometheus#13369]
### What did you do?

I attempted to configure Prometheus to scrape metrics from a target using the following configuration:

scrape_configs:
  - job_name: "My Job HTTPS Metrics"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: "username"
      password: "password"

    file_sd_configs:
      - files:
          - "/path/to/your/targets.yml"
        refresh_interval: 10m

I used the curl command to check the target and received a successful response with HTTP status 200. 

### What did you expect to see?

I expected Prometheus to successfully scrape metrics from the target specified in the configuration.

### What did you see instead? Under which circumstances?

server returned HTTP status 406 

### System information

Linux 5.4.0-169-generic x86_64

### Prometheus version

```text
prometheus, version 2.49.0-rc.0 (branch: HEAD, revision: c4c8d59c14ea558a4878fb014cc954347c317978)
  build user:       root@e59256874f10
  build date:       20231212-11:17:29
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
prometheus.yml:
---------------
scrape_configs:
  - job_name: "My Job HTTPS Metrics"
    scheme: "https"
    tls_config:
      insecure_skip_verify: true
    basic_auth:
      username: "username"
      password: "password"

    file_sd_configs:
      - files:
          - "/path/to/your/targets.yml"
        refresh_interval: 10m


targets.yml:
------------
- targets: ['192.168.0.184:8502']
  labels:
    __metrics_path__: '/your-metrics-path'
    job: 'Your Job Name'
    bv_server: 'your-server-name'
    name: your_target_name
    env: your_environment
```

### Logs

```text
Jan 03 11:14:15 development prometheus[4048]: ts=2024-01-03T03:14:15.475Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool="Scrape Pool Name" target=https://your-target-url/your-metrics-path msg="Scrape failed" err="server returned HTTP status 406 "
```
