### ISSUE TITLE
Multiple relabeling rules on same source labels are mutually exclusive

### ISSUE THREAD

**Issue by syalioune** [prometheus/prometheus#13379]
### What did you do?

I was trying to make [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics), [fluxcd](https://github.com/fluxcd/flux2) and [Google Managed Prometheus](https://github.com/GoogleCloudPlatform/prometheus) work together. This involves configuring a `metricRelabeling` in order to reduce metric ingestion costs in GCP.

I configured the following `metricRelabeling` :

```yaml
- action: keep
  regex: gotk_resource_info
  source_labels: [__name__]
- action: keep
  regex: kube_daemonset_.+
  source_labels: [__name__]
```

### What did you expect to see?

I expected prometheus metric with name `gotk_resource_info` being kept as nothing (to the best of my knowledge) in the documentation suggests the **cumulative** relabeling rules action is a `Logical conjunction (AND)`.

### What did you see instead? Under which circumstances?

Prometheus metric with name `gotk_resource_info` is dropped because it does not match the regex `kube_daemonset_.+`.

Reproductible with [Online relabeler](https://relabeler.promlabs.com/)

- Relabeling rules
```yaml
- action: keep
  regex: gotk_resource_info
  source_labels: [__name__]
- action: keep
  regex: kube_daemonset_.+
  source_labels: [__name__]
```
- Object labels
```yaml
__name__: "gotk_resource_info"
```

![image](https://github.com/prometheus/prometheus/assets/6144741/cfd18565-eed0-4b98-b0a6-f72c200ff299)

To make it work, I have to configured it as such

- Relabeling rules
```yaml
- action: keep
  regex: gotk_resource_info|kube_daemonset_.+
  source_labels: [__name__]
```
- Object labels
```yaml
__name__: "gotk_resource_info"
```

![image](https://github.com/prometheus/prometheus/assets/6144741/a14faf57-66e7-411e-9273-fecbc6d18ceb)

I believe it's calling for either :
- A documentation improvement to explicitly state the current logic behavior (i.e. cumulative rules action is a `Logical conjunction (AND)`).
- An improvement if a `Logical disjunction (OR)` is something acceptable and/or expected

I'm happy to implement either one but looking for maintainer/community guidance.

This logic seems to be implemented here https://github.com/prometheus/prometheus/blob/main/model/relabel/relabel.go#L231-L239

### System information

Docker image gcr.io/distroless/static-debian11

### Prometheus version

```text
prometheus, version 2.41.0-gmp.4 (branch: , revision: 61b965d07b232bb240b307ece1c0dd5d1dca1b9e-modified)
  build user:
  build date:       2023-10-12T14:09:40+00:00
  go version:       go1.20.10
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
N/A
```

**Comment by bboreham** [comment]
This is working as defined.

The [documentation](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) says "keep: Drop targets for which regex does not match the concatenated source_labels."

Feel free to submit a PR which makes the documentation clearer.

**Comment by swc-jk** [comment]
I was also looking for a solution to this without having to have a super long regex and came up with this solution:

```yml
- job_name: my-job
  metric_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'container_cpu_usage_seconds_total'
      target_label: remote_write
      replacement: true
    - source_labels: [ __name__ ]
      regex: 'container_memory_working_set_bytes'
      target_label: remote_write
      replacement: true
```
This will add label `remote_write` to the metric with name in `regex`

Then in remote write config
```yml
  remoteWrite:
  - url: http://url.com
    write_relabel_configs:
    - source_labels: [remote_write]
      regex: true
      action: keep
```

**Comment by bboreham** [comment]
For the record, the super long regex would look like:

```
  remoteWrite:
  - url: http://url.com
    write_relabel_configs:
    - source_labels: [ __name__ ]
      regex: 'container_cpu_usage_seconds_total|container_memory_working_set_bytes'
      action: keep
```

This is much more efficient, although harder to manage at scale.

I'm going to close this now as nothing seems likely to move on the original complaint.
