### ISSUE TITLE
URL Params in additional scrape configs seem to be encoded

### ISSUE THREAD

**Issue by Breee** [prometheus/prometheus#13388]
### What did you do?

I have a metrics endpoint  `https://example.com/prometheus/metrics?token=xxxxx`  that takes a url param "token" 

```
- job_name: my-job
  static_configs:
  - targets:
    - "example.com"
  scheme: https
  metrics_path: /prometheus/metrics
  scrape_interval: 15s
  honor_labels: true
  params:
      token: ["${MY_TOKEN}"]
```

### What did you expect to see?

- Correctly scraped metrics

### What did you see instead? Under which circumstances?

- In the prometheus UI it's displayed correctly (Also if i click the link in the UI everything is fine) 
- prometheus returns "server returned HTTP status 404 Not Found" and the target is DOWN

My assumption is that the whole URL including parameters is encoded, which would lead to scraping `https://example.com/prometheus/metrics%3token=xxxxx`

### System information

k8s pod

### Prometheus version

```text
Prometheus 2.43.1
```

### Prometheus configuration file

```yaml
- job_name: my-job
  static_configs:
  - targets:
    - "example.com"
  scheme: https
  metrics_path: /prometheus/metrics
  scrape_interval: 15s
  honor_labels: true
  params:
      token: ["${MY_TOKEN}"]
```
