### ISSUE TITLE
prometheus use remote-read sometimes output warn log "Evaluating rule failed"

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#13406]
### What did you do?

1. use prometheus scrape telegraf target, collect cpu usage
2. use prometheus-center remote-read prometheus and config alert rules
3. prometheus-cener config evaluation_interval 1m and create cpu usage alert rule 
4. prometheus-center sometimes output warn log "Evaluating rule failed"

### What did you expect to see?

prometheus-center work well and doesn't output any warn log

### What did you see instead? Under which circumstances?

cpu usage alert rule like below:
```
      - alert: SystemCpuIowaitHigh
        annotations:
          description: '{{ $labels.kubernetes_cluster_name }}集群{{ $labels.host }}节点CPU等待IO率为{{ $value }}%'
          summary: 管理节点CPU等待IO率超过25%
        expr: cpu_usage_iowait{host!~".*(storage|compute).*"} > 25
        for: 5m
        labels:
          cn_name: 管理节点CPU等待IO高
          service: system
          severity: critical
```

prometheus-center warn log like below:
```
ts=2024-01-16T05:25:59.395Z caller=manager.go:680 level=warn component="rule manager" file=/etc/prometheus-rules/platform-alerts-rules.yml group=platform-alerts name=SystemCpuIowaitHigh index=16 msg="Evaluating rule failed" rule="alert: SystemCpuIowaitHigh\nexpr: cpu_usage_iowait{host!~\".*(storage|compute).*\"} > 25\nfor: 5m\nlabels:\n  cn_name: 管理节点CPU等待IO高\n  service: system\n  severity: critical\nannotations:\n  description: '{{ $labels.kubernetes_cluster_name }}集群{{ $labels.host }}节点CPU等待IO率为{{\n    $value }}%'\n  summary: 管理节点CPU等待IO率超过25%\n" err="vector contains metrics with the same labelset after applying alert labels"
ts=2024-01-16T06:09:59.515Z caller=manager.go:680 level=warn component="rule manager" file=/etc/prometheus-rules/platform-alerts-rules.yml group=platform-alerts name=SystemCpuIowaitHigh index=16 msg="Evaluating rule failed" rule="alert: SystemCpuIowaitHigh\nexpr: cpu_usage_iowait{host!~\".*(storage|compute).*\"} > 25\nfor: 5m\nlabels:\n  cn_name: 管理节点CPU等待IO高\n  service: system\n  severity: critical\nannotations:\n  description: '{{ $labels.kubernetes_cluster_name }}集群{{ $labels.host }}节点CPU等待IO率为{{\n    $value }}%'\n  summary: 管理节点CPU等待IO率超过25%\n" err="vector contains metrics with the same labelset after applying alert labels"
ts=2024-01-16T06:11:59.388Z caller=manager.go:680 level=warn component="rule manager" file=/etc/prometheus-rules/platform-alerts-rules.yml group=platform-alerts name=SystemCpuIowaitHigh index=16 msg="Evaluating rule failed" rule="alert: SystemCpuIowaitHigh\nexpr: cpu_usage_iowait{host!~\".*(storage|compute).*\"} > 25\nfor: 5m\nlabels:\n  cn_name: 管理节点CPU等待IO高\n  service: system\n  severity: critical\nannotations:\n  description: '{{ $labels.kubernetes_cluster_name }}集群{{ $labels.host }}节点CPU等待IO率为{{\n    $value }}%'\n  summary: 管理节点CPU等待IO率超过25%\n" err="vector contains metrics with the same labelset after applying alert labels"
ts=2024-01-16T06:28:59.507Z caller=manager.go:680 level=warn component="rule manager" file=/etc/prometheus-rules/platform-alerts-rules.yml group=platform-alerts name=SystemCpuIowaitHigh index=16 msg="Evaluating rule failed" rule="alert: SystemCpuIowaitHigh\nexpr: cpu_usage_iowait{host!~\".*(storage|compute).*\"} > 25\nfor: 5m\nlabels:\n  cn_name: 管理节点CPU等待IO高\n  service: system\n  severity: critical\nannotations:\n  description: '{{ $labels.kubernetes_cluster_name }}集群{{ $labels.host }}节点CPU等待IO率为{{\n    $value }}%'\n  summary: 管理节点CPU等待IO率超过25%\n" err="vector contains metrics with the same labelset after applying alert labels"
```

### System information

k8s env and use prometheus image

### Prometheus version

```text
prometheus, version 2.48.0 (branch: HEAD, revision: 6d80b30990bc297d95b5c844e118c4011fad8054)
  build user:       root@26117804242c
  build date:       20231116-04:35:21
  go version:       go1.21.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     1m
  evaluation_interval: 1m
  scrape_timeout:      1m
  external_labels:
    env: region-stackdev

alerting:
  alert_relabel_configs:
  - source_labels: [env]
    regex: (.+)
    target_label: env
  alertmanagers:
  - basic_auth:
      username: admin
      password: 123456
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - monitoring
    relabel_configs:
    - action: keep
      source_labels:
      - __meta_kubernetes_service_name
      regex: alertmanager
    - action: keep
      source_labels:
      - __meta_kubernetes_endpoint_port_name
      regex: http-metrics

rule_files:
- /etc/prometheus-rules/*.yml
remote_write:
- url: "http://localhost:9201/write"
  name: prometheus-alert
  write_relabel_configs:
  - source_labels: [__name__]
    regex: '(up)'
    action: keep

scrape_configs:
- job_name: 'prometheus-stackdev-manager'
  basic_auth:
    username: admin
    password: 123456
  static_configs:
  - targets:
    - prometheus:9090
    labels:
      kubernetes_cluster_name: stackdev-manager
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: '(.+)'
    action: drop

remote_read:
- url: "http://prometheus:9090/api/v1/read"
  name: stackdev-manager
  basic_auth:
    username: admin
    password: 123456
  read_recent: true
  remote_timeout: 1m
  filter_external_labels: false
```
