### ISSUE TITLE
kubernetes_sd_configs kubeconfig_file does not work well

### ISSUE THREAD

**Issue by honza801** [prometheus/prometheus#13418]
### What did you do?

I have a kubernetes cluster of 3 nodes v1.27.2, 1 standalone monitoring node with docker 24.0.7.

There are some issues using `kubeconfig_file`.

My kube config file
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJT...
    server: https://172.16.3.5:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: prometheus-scraper
    namespace: default
  name: prometheus-scraper@kubernetes
current-context: prometheus-scraper@kubernetes
kind: Config
preferences: {}
users:
- name: prometheus-scraper
  user:
    token: eyJhbGciOiJS...
```

### What did you expect to see?

I expect to see all kubernetes metrics in prometheus database.

### What did you see instead? Under which circumstances?

It not clear to me, why i have to configure `tls_config.insecure_skip_verify: true`? There is certainly a `certificate-authority-data` configuration present, so tls should be just fine. But insted following error appears when `tls_config.insecure_skip_verify: true` is missing

```
prometheus  | ts=2024-01-17T17:34:48.689Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool=kubernetes-apiservers target=https://172.16.3.5:6443/metrics msg="Scrape failed" err="Get \"https://172.16.3.5:6443/metrics\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
```

The second problem is, prometheus does not handle the kubernetes configuration correctly. For unknown reason the scrape ends with:  

```
prometheus  | ts=2024-01-17T17:36:18.653Z caller=scrape.go:1274 level=debug component="scrape manager" scrape_pool=kubernetes-apiservers target=https://172.16.3.5:6443/metrics msg="Scrape failed" err="server returned HTTP status 403 Forbidden"
```

Using `curl` with configuration from the kubernetes configuration file works fine

```
# curl -k -H 'Authorization: Bearer eyJhbGciOiJS...' https://172.16.3.5:6443/metrics -i
HTTP/2 200 
audit-id: ec8c01b6-a130-407e-bb4f-f53f4df84236
cache-control: no-cache, private
content-type: text/plain; version=0.0.4; charset=utf-8
x-kubernetes-pf-flowschema-uid: 564d9e76-5d04-4714-bc93-ba3f606e1d38
x-kubernetes-pf-prioritylevel-uid: c03af8e9-3053-4154-afed-685f9ed418fe
date: Wed, 17 Jan 2024 17:48:53 GMT

# HELP aggregator_discovery_aggregation_count_total [ALPHA] Counter of number of times discovery was aggregated
# TYPE aggregator_discovery_aggregation_count_total counter
aggregator_discovery_aggregation_count_total 476251
...
`````

### System information

Kubernetes Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}

### Prometheus version

```text
Docker image prom/prometheus:v2.49.0
```

### Prometheus configuration file

```yaml
- job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        kubeconfig_file: /home/.kube/config
    scheme: https
    tls_config:
      insecure_skip_verify: true
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https
```
