### ISSUE TITLE
Web UI Targets repeatedly incorrectly defaults scrape pool

### ISSUE THREAD

**Issue by DazWilkin** [prometheus/prometheus#13413]
### What did you do?

I have 27 active targets.

Usually, I can browse these through the Web UI (Service Discovery | Targets) without issue.

However, when I deploy a specific `ScrapeConfig` (part of Prometheus Operator), the Web UI Targets page incorrectly (!) applies the target to the Scrape Pool filter and, even with `http://localhost:9490/targets?search=&scrapePool=`, the page repeatedly defaults to the specific `ScrapeConfig` as the filtered scrape pool.

```bash
curl --silent localhost:9490/api/v1/targets | jq -r '.data.activeTargets|length'
27
```
The Service Discovery page *always* reports the correct list.

The Target page reports the correct list **until** I apply the Target-problem-causing `ScrapeConfig` to the cluster.

Before applying the Target-problem-causing `ScrapeConfig`:

![image](https://github.com/prometheus/prometheus/assets/1022400/47bc7782-2669-4f21-bdd1-5da46e847c40)

I can refresh the page repeatedly without issue.

If I manually filter by a scrape pool, the results are filtered correctly **and** the URL is revised to include the filter.

However, if I apply the Target-problem-causing `ScrapeConfig`:

Upon refresh (`http://localhost:9490/targets?search=&scrapePool=`), the filter is applied (without specifying it):

![image](https://github.com/prometheus/prometheus/assets/1022400/5e550cb6-9166-4576-8b79-d89d42936b0e)

Note that the URL contains an empty `scrapepool=` and yet the UI defaults to the `koyeb-operator` and, even if I "Clear Selection to see the entire list upon refreshing the page, it will revert to the unspecified filter:

![image](https://github.com/prometheus/prometheus/assets/1022400/9c349b3a-af99-4f10-8e23-8f038cbe2cd0)

As soon as I delete the `koyeb-operator` `ScrapeConfig`, the behavior corrects itself.

The `ScrapeConfig`:
```YAML
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: koyeb-operator
spec:
  staticConfigs:
    - labels:
        job: koyeb-operator
      targets:
        - 10.0.1.1:8080
```

This is just a UI issue but, it threw me for a while yesterday because I was trusting the Targets page, hadn't noticed the scrape pool filtering and incorrectly assumed that the Targets weren't being correctly scraped.

### What did you expect to see?

I expect the Web UI Targets to list all targets unless specifically requested (URL or UI) to not do so.

### What did you see instead? Under which circumstances?

See above.

### System information

Linux 5.15.0-1052-realtime x86_64

### Prometheus version

```text
Build Information
Version	2.47.2
Revision	3f3172cde1ee37f1c7b3a5f3d9b031190509b3ad
Branch	HEAD
BuildUser	root@79f2ad339b75
BuildDate	20231012-16:07:10
GoVersion	go1.21.3
```

**Comment by DazWilkin** [comment]
[config](https://gist.github.com/DazWilkin/a8ea5fd43ddad26d25d609391a87f4ea) was too long to include inline.

**Comment by DazWilkin** [comment]
The behavior applies to Chrome, Firefox and Edge.

None of the browsers reports console errors.

The issue is reproducible.

I've realized that the issue arises if I create 3 `ScrapeConfig`'s ... the third `ScrapeConfig` breaks the behavior. If I delete the third `ScrapeConfig`, correct behavior returns. If I recreate the third `ScrapeConfig`, the issue recurs.

API responses before deploying the Target-problem-causing `ScrapeConfg` (TPCSC):

URL: `http://localhost:9490/targets?search=`

APIs:

1. `http://localhost:9490/api/v1/scrape_pools`

```JSON
{
    "status": "success",
    "data": {
        "scrapePools": [
             "scrapeconfig/test/koyeb-sd",
            "scrapeconfig/test/koyeb-sd-metrics",
            "serviceMonitor/monitoring/alertmanager-main/0",
            "serviceMonitor/monitoring/alertmanager-main/1",
            "serviceMonitor/monitoring/blackbox-exporter/0",
            "serviceMonitor/monitoring/coredns/0",
            "serviceMonitor/monitoring/grafana/0",
            "serviceMonitor/monitoring/kube-apiserver/0",
            "serviceMonitor/monitoring/kube-controller-manager/0",
            "serviceMonitor/monitoring/kube-scheduler/0",
            "serviceMonitor/monitoring/kube-state-metrics/0",
            "serviceMonitor/monitoring/kube-state-metrics/1",
            "serviceMonitor/monitoring/kubelet/0",
            "serviceMonitor/monitoring/kubelet/1",
            "serviceMonitor/monitoring/kubelet/2",
            "serviceMonitor/monitoring/node-exporter/0",
            "serviceMonitor/monitoring/prometheus-adapter/0",
            "serviceMonitor/monitoring/prometheus-k8s/0",
            "serviceMonitor/monitoring/prometheus-k8s/1",
            "serviceMonitor/monitoring/prometheus-operator/0"
        ]
    }
}
```

2. `http://localhost:9490/api/v1/targets?state=active`

27 `activeTagets`

After deploying the TPCSC:

URL: `http://localhost:9490/targets?search=`

APIs:

1. `http://localhost:9490/api/v1/scrape_pools`

```JSON
{
    "status": "success",
    "data": {
        "scrapePools": [
            "scrapeconfig/test/koyeb-operator",
            "scrapeconfig/test/koyeb-sd",
            "scrapeconfig/test/koyeb-sd-metrics",
            "serviceMonitor/monitoring/alertmanager-main/0",
            "serviceMonitor/monitoring/alertmanager-main/1",
            "serviceMonitor/monitoring/blackbox-exporter/0",
            "serviceMonitor/monitoring/coredns/0",
            "serviceMonitor/monitoring/grafana/0",
            "serviceMonitor/monitoring/kube-apiserver/0",
            "serviceMonitor/monitoring/kube-controller-manager/0",
            "serviceMonitor/monitoring/kube-scheduler/0",
            "serviceMonitor/monitoring/kube-state-metrics/0",
            "serviceMonitor/monitoring/kube-state-metrics/1",
            "serviceMonitor/monitoring/kubelet/0",
            "serviceMonitor/monitoring/kubelet/1",
            "serviceMonitor/monitoring/kubelet/2",
            "serviceMonitor/monitoring/node-exporter/0",
            "serviceMonitor/monitoring/prometheus-adapter/0",
            "serviceMonitor/monitoring/prometheus-k8s/0",
            "serviceMonitor/monitoring/prometheus-k8s/1",
            "serviceMonitor/monitoring/prometheus-operator/0"
        ]
    }
}
```

2. `http://localhost:9490/api/v1/targets?state=active&scrapePool=scrapeconfig/test/koyeb-operator`

As before, after deleting the `koyeb-operator` `ScrapeConfig`, behavior ... corrects.

**Comment by DazWilkin** [comment]
The following script should (!?) generate targets that will break the `Targets` page:

```bash
NAMESPACE="13413"

kubectl create namespace ${NAMESPACE}

for NAME in "a" "b" "c"
do
  echo "
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: ${NAME} 
spec:
  staticConfigs:
  - targets:
    - localhost:8080
" | kubectl apply --filename=- --namespace=${NAMESPACE}
done
```
Then either `/targets?search=` or `/targets?search=&scrapePool=` should display only 1 target because the scrape bools dropdown has been set (incorrectly)

Deleting any `ScrapeConfig` will revert to the expected behavior.

Recreating the `ScrapeConfig` will revert to the broken behavior.

**Comment by Mert18** [comment]
This annoying issue still persists.

**Comment by machine424** [comment]
From https://github.com/prometheus/prometheus/issues/13323

Here is how to reproduce this without the need of prom operator.
Run
```
./prometheus --web.enable-lifecycle
```

with the following config:

<details>

<summary>config</summary>

```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - prometheus:9090
- job_name: node_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: SRV-Insurgentes
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.2.1:9182
- job_name: SRV-Diaz_Ordaz
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.76.1:9182
- job_name: SRV-Hipodromo
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.4.1:9182
- job_name: SRV-Baja_Mil
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.35.1:9182
- job_name: SRV-ENS-AV.Juárez
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.160.1:9182
- job_name: SRV-ENS-AV.Guadalupe
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.161.1:9182
- job_name: SRV-ENS-AV.Mision
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.163.1:9182
- job_name: SRV-ENS-AV.Coral
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.164.1:9182
- job_name: SRV-Brazil
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.19.1:9182
- job_name: SRV-Madero
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.44.1:9182
- job_name: SRV-Zaragoza
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.47.1:9182
- job_name: SRV-Calle_Esmeralda
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.165.1:9182
- job_name: SRV-Pedro_Loyola
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.166.1:9182
- job_name: SRV-ENS-Reforma_9na
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.96.1:9182
- job_name: SRV-Vista_Hermosa
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.116.1:9182
- job_name: SRV-Rio_Fuerte
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.123.1:9182
- job_name: SRV-Lazaro_Cardenas
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.170.1:9182
- job_name: SRV-Gonzalez
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.5.1:9182
```

</details>

Check out the targets page. Everything seems ok.

Then add:

```
- job_name: SRV-TTTT
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - 192.168.55.1:9182
```

at the end of the config file and run 
```
curl -X POST localhost:9090/-/reload
``` 
and go to the targets page to see the same issue described above.
