### ISSUE TITLE
Federate include timestamp of metrics

### ISSUE THREAD

**Issue by bck01215** [prometheus/prometheus#13441]
### Proposal

Currently when using /federate on a prometheus endpoint, I get the granularity of data equal to that of the scrape interval of the prometheus scraping that endpoint. In the prometheus (prometheus1) being scraped, it could be scraping two endpoints (1 at a 15s interval and another at 30s).  If the prometheus (prometheus2) scraping prometheus1 is at an interval greater than 15s data is lost.
<details>
<summary>Example configs:</summary>

```yaml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus2"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "federate"
    scrape_interval: 30s
    honor_labels: true
    params:
      "match[]":
        - '{__name__="example_metric"}'
    metrics_path: "/federate"
    static_configs:
      - targets: ["prometheus1:9090"]
```
```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus1"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "gateway"
    static_configs:
      - targets: ["sample_target:9091"]
```
in this example the data of example metric in prometheus2 is a granularity of 15s instead of 5s
</details>
