### ISSUE TITLE
Kubernetes SD discovery selectors do not work as expected

### ISSUE THREAD

**Issue by xdrus** [prometheus/prometheus#13525]
### What did you do?

I want to deploy an OTEL agent (specifically [ADOT](https://github.com/aws-observability/aws-otel-collector) that uses Prometheus discovery in a DaemonSet mode on Kubernetes. My use-case is monitoring of Kubernetes data plane components (kubelet, cAdvisor, node-exporter, cni, kube-proxy, etc - mostly other daemonSets) in a huge cluster (3-5K nodes). To optimise collector performance I want to use `selectors` to filter out everything that is not on a particular node. According to [documentation](https://github.com/prometheus/prometheus/tree/main/discovery#other-implementation-considerations) it is a way to improve performance:
> SDs are intended to dump all possible targets. ... For large deployments where you are only interested in a small proportion of the returned targets, this may cause performance issues. If this occurs it is acceptable to also offer filtering via whatever mechanisms the SD exposes. ... Keep in mind that this is a performance optimisation, it should be possible to do the same filtering using relabelling alone. As with SD generally, we do not invent new ways to filter targets (that is what relabelling is for), merely offer up whatever functionality the SD itself offers.

Without it, collectors start consuming a lot of memory and CPU on each node, keeping a copy of all pods/nodes/etc on each DS instance. 

Kubernetes service discovery documentation says that:
> The endpoints role supports pod, service and endpoints selectors. The **pod role supports node selectors** when configured with `attach_metadata: {node: true}`.

Based on that I expect that I can use selector with node name to discover only pods on the node:
```yaml
- job_name: kubernetes-local-pods
  kubernetes_sd_configs:
    - role: pod
      attach_metadata:
        node: true
      selectors:
         - role: node
          label: "kubernetes.io/hostname=$K8S_NODE_NAME=$K8S_NODE_NAME"
```

### What did you expect to see?

I expect that by filtering out PODs by node name or IP i can drastically improve performance of each collector.

### What did you see instead? Under which circumstances?

However, pod role *doesn't* really support node's selector:
```
* error decoding 'receivers': error reading configuration for "prometheus": prometheus receiver failed to unmarshal yaml to prometheus config: pod role supports only pod selectors
```

And looking through test and code it's obvious that it doesn't:

https://github.com/prometheus/prometheus/blob/6feffeb92e36b064a53d2283e50d6db355c95cb0/config/testdata/kubernetes_selectors_pod.bad.yml#L4-L6

https://github.com/prometheus/prometheus/blob/6feffeb92e36b064a53d2283e50d6db355c95cb0/config/config_test.go#L1708-L1711

https://github.com/prometheus/prometheus/blob/6feffeb92e36b064a53d2283e50d6db355c95cb0/discovery/kubernetes/kubernetes.go#L205-L212

https://github.com/prometheus/prometheus/blob/6feffeb92e36b064a53d2283e50d6db355c95cb0/discovery/kubernetes/kubernetes.go#L558-L587

### System information

ADOT Collector version: v0.36.0

**Comment by xdrus** [comment]
Just for reference, I was able to filter out by node name using fields selector instead, i.e.
```
kubernetes_sd_configs:
  - role: pod
    selectors:
      - role: pod
        field: "spec.nodeName=$K8S_NODE_NAME"
```

However it worth fixing documentation (or better adding pod role to label selectors for other use-cases, for example AZ sharding).
