### ISSUE TITLE
`promtool check service-discovery` always waits for full timeout period

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#13538]
### What did you do?

1. Create a prometheus.yml with a mixture of service discovery jobs: some quick (e.g. using static_configs or file_sd_configs), and some slow and expensive (e.g. using some slow API)
2. Use `promtool check service-discovery prometheus.yml fast_job`

Concrete reproducer using a non-existent IP address to give a timeout:

```
scrape_configs:
  - job_name: fast_job
    static_configs:
      - targets: ['localhost:9090']

  - job_name: slow_job
    http_sd_configs:
      - url: http://1.2.3.4/nonexistent
```

Execute `time /opt/prometheus/promtool check service-discovery promtest.yml fast_job`

### What did you expect to see?

Given that promtool check service-discovery *requires* you to provide a job name, then if you select `fast_job` only the fast_job service discovery should be performed, so the response should come back quickly.

### What did you see instead? Under which circumstances?

The response is very slow:

```
root@prometheus:~# time /opt/prometheus/promtool check service-discovery promtest.yml fast_job
[
  {
    "discoveredLabels": {
      "__address__": "localhost:9090",
      "__metrics_path__": "/metrics",
      "__scheme__": "http",
      "__scrape_interval__": "1m",
      "__scrape_timeout__": "10s",
      "job": "fast_job"
    },
    "labels": {
      "__address__": "localhost:9090",
      "__metrics_path__": "/metrics",
      "__scheme__": "http",
      "__scrape_interval__": "1m",
      "__scrape_timeout__": "10s",
      "instance": "localhost:9090",
      "job": "fast_job"
    }
  }
]
real	0m30.107s       <<<<< NOTE
user	0m29.601s
sys	0m0.161s
```

~~It seems that `promtool check service-discovery <job>` is performing discovery for *all* the jobs in the configuration, and then returning just the selected job.~~ promtool is waiting for its default 30 second timeout window, even though the service discovery has completed successfully.

### System information

Linux 5.4.0-162-generic x86_64

### Prometheus version

```text
prometheus, version 2.45.2 (branch: HEAD, revision: 3d6b7e665928a78c4a18675802436fe92f3f4e04)
  build user:       root@3b1b6808f1b0
  build date:       20231219-14:07:38
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: fast_job
    static_configs:
      - targets: ['localhost:9090']

  - job_name: slow_job
    http_sd_configs:
      - url: http://1.2.3.4/nonexistent
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```

**Comment by candlerb** [comment]
You're right! Comment out slow_job, and we still get:

```
# time /opt/prometheus/promtool check service-discovery promtest.yml fast_job
[
  {
    "discoveredLabels": {
      "__address__": "localhost:9090",
      "__metrics_path__": "/metrics",
      "__scheme__": "http",
      "__scrape_interval__": "1m",
      "__scrape_timeout__": "10s",
      "job": "fast_job"
    },
    "labels": {
      "__address__": "localhost:9090",
      "__metrics_path__": "/metrics",
      "__scheme__": "http",
      "__scrape_interval__": "1m",
      "__scrape_timeout__": "10s",
      "instance": "localhost:9090",
      "job": "fast_job"
    }
  }
]
real	0m30.112s
user	0m29.773s
sys	0m0.152s
```

But where does the 30 seconds timeout come from? global scrape_interval and evaluation_interval default to 1m, scrape_timeout defaults to 10s. Some SD mechanisms have a default refresh_interval of 30s (but static_configs does not).

**Comment by candlerb** [comment]
Another data point. Suppose I change promtest.yml as follows:

```
scrape_configs:
  - job_name: fast_job
    file_sd_configs:
      - files:
          - promtest.yml
```

This is intentionally wrong, because promtest.yml is not structured for use as a targets file.

I get the error about the invalid format of promtest.yml immediately:

```
# time /opt/prometheus/promtool check service-discovery promtest.yml fast_job
level=error msg="Error reading file" path=promtest.yml err="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!map into []*targetgroup.Group"
```

... but it still takes 30 seconds before the command completes.

Even more weirdly, running this under strace:

```
# strace -ttt -f /opt/prometheus/promtool check service-discovery promtest.yml fast_job 2>ert
# grep "cannot unmarshal" ert | wc -l
6328
```

There are literally *thousands* of attempts to write this error message.

This makes me wonder if it's something to do with my environment (e.g. apparmor). I'm running prometheus inside an lxd container; the outer host is Ubuntu 20.04.6 with lxd 5.20-51a2393
