### ISSUE TITLE
Wrong timestamp can break entire tsdb

### ISSUE THREAD

**Issue by timur-ND** [prometheus/prometheus#13573]
### What did you do?

It looks like we found some kind of critical vulnerability related to timestamp. One of the servers sent the metric through the Prometheus agent with an incorrect timestamp **timestamp=4039374839932** (Wednesday, January 1, 2098 4:33:59 AM) . This happened because the ntp service displayed the wrong time (in fact it was a CMOS battery issue). Therefore, the agent sent the metric with this timestamp. Because of this, there was an "out of bounds" error in the logs. It looks like there is no way to block metrics with the wrong timestamp and the only thing left is to delete the entire tsdb. Deleting via curl or promtool is not helped.
Steps how we fixed it:
1. Stop prometheus
2. Add this config to prometheus.yml
`storage:
  tsdb:
    out_of_order_time_window: 75y`
3. Start prometheus
4. Check logs, find broken metrics in prometheus logs
5. Stop prometheus, fix metrics
6. Delete out_of_order_time_window parameter
7. Drop entire tsdb and start prometheus

### What did you expect to see?

Somehow block these metrics (with incorrect timestamp) or delete it via promtool/curl. After this, such metrics will not hit and break the entire database.

### What did you see instead? Under which circumstances?

1. Error "out of bound" for all targets, for instance:
`ts=2024-02-12T15:41:56.168Z caller=scrape.go:1350 level=warn component="scrape manager" scrape_pool=http-targets target=http://mydb-test-gc1:9104/metrics msg="Appending scrape report failed" err="out of bounds"`
2 Error
`msg="Error on ingesting samples that are too old or are too far into the future"`
3 Current max timestamp is equal to wrong timestamp (approx)
![image](https://github.com/prometheus/prometheus/assets/60424981/657d3775-c7a2-4890-8238-3c8a2cb00ba8)

### System information

Linux 5.14.0-331.el9.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.47.0 (branch: HEAD, revision: efa34a5840661c29c2e362efa76bc3a70dccb335)
  build user:       root@409eb5e6b30c
  build date:       20230906-10:20:07
  go version:       go1.21.0
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval:    15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 10s
  external_labels:
    prometheus: main
  # scrape_timeout is set to the global default (10s).
# Alertmanager configuration
alerting:
  alert_relabel_configs:
    - source_labels: [prometheus]
      regex: (.*)
      target_label: prometheus
  alertmanagers:
  - static_configs:
      - targets: ['*****:9093']
      - targets: ['*****:9093']
      - targets: ['*****:9093']

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.rule"

#Write to VictoriaMetrics
remote_write:
  - url: https://<victoria_metrics1>/api/v1/write
    basic_auth:
      username: *****
      password: *****
    queue_config:
      capacity: 50000
      max_samples_per_send: 25000
      max_shards: 35
    metadata_config:
      send_interval: 45s
      max_samples_per_send: 25000
  - url: https://<victoria_metrics2>/api/v1/write
    basic_auth:
      username: ******
      password: ******
    queue_config:
      capacity: 50000
      max_samples_per_send: 25000
      max_shards: 35
    metadata_config:
      send_interval: 45s
      max_samples_per_send: 25000

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'http-targets'
    scrape_interval: 20s
    scrape_timeout: 10s
    scheme: http
    http_sd_configs:
      - url: "*****"
        basic_auth:
          username: *****
          password: *****
    relabel_configs:
      - source_labels: [__app_name]
        target_label: job
        regex: (^\S+$)
      - source_labels: [__metrics_path]
        target_label: __metrics_path__
        regex: (^\S+$)
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: "monitoring_agent_check_errors"
        action: drop
  - job_name: ... # other scrape jobs, nothing interesting here
 

Also command line flags:
            "Cmd": [
                "--config.file=/etc/prometheus/prometheus.yml",
                "--storage.tsdb.path=/prometheus",
                "--storage.tsdb.retention=90d",
                "--storage.tsdb.retention.size=6000GB",
                "--web.listen-address=0.0.0.0:9090",
                "--log.level=info",
                "--web.enable-admin-api",
                "--web.enable-lifecycle",
                "--web.external-url=https://******",
                "--web.console.libraries=/usr/share/prometheus/console_libraries",
                "--web.console.templates=/usr/share/prometheus/consoles",
                "--web.enable-remote-write-receiver"
```

### Logs

```text
Errors regarding wrong timestamp

2024-02-12T15:35:09.472954+00:00 my-host docker/prometheus/a731f7ee2b1a/prom/prometheus:v2.47.0[3286185]: ts=2024-02-12T15:35:09.472Z caller=write_handler.go:132 level=error component=web msg="Out of order sample from remote write" err="duplicate sample for timestamp" series="{__name__=\"scrape_samples_scraped\", city=\"Johannesburg\", state=\"maintenance\", country=\"South Africa\", env=\"prod\", hostname=\"broken-host\", instance=\"127.0.0.1:35807\", job=\"prometheus\", prometheus_agent=\"true\", role=\"edge\", "}" timestamp=4039374839411
```
