### ISSUE TITLE
add support for http2 over tcp aka h2c

### ISSUE THREAD

**Issue by rgl** [prometheus/prometheus#13594]
### Proposal

While trying to play with opentelemetry by running prometheus with the experimental `--enable-feature=otlp-write-receiver` cli argument and the following [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) configuration (notice the tls.insecure usage):

```
exporters:
  otlp/prometheus:
    # NB the API is at, e.g., http://prometheus:9090/api/v1/otlp/v1/metrics
    endpoint: prometheus:9090
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true
```

opentelemetry-collector-contrib complained that it cannot connect to prometheus because prometheus does not support http2 over tcp (aka h2c). this was somewhat unexpected in the sense that while trying out new protocols it's generally easier to poke them using wireshark without the tls layer in the way, but it seems there is no way to do that in prometheus.

since the https://pkg.go.dev/golang.org/x/net/http2/h2c library already exists, can we have that option, to enable http2 over tcp? if there is no objection, I can try to create a PR for adding this.
