### ISSUE TITLE
Update oauth2 options description

### ISSUE THREAD

**Issue by vvyushmanov** [prometheus/prometheus#13603]
### Proposal

Currently, the documentation states:

"OAuth 2.0 authentication using the *_client credentials_* grant type. "
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#oauth2

But, in reality, it is possible to set up "password credentials" grant type as well, like this:

```yaml
    oauth2:
        client_id: prometheus_client
        client_secret: randomstringthatissecret
        scopes:
          - scope1
          - scope2
          - ...
        token_url: https://example.com/idms/token
        endpoint_params:
          grant_type: 'password'
          username: 'prometheus@eaxmple.com'
          password: 'verystrongpassword'
```

This is not obvious, took some trial and error and a suggestion mentioned here:
https://github.com/prometheus/blackbox_exporter/issues/829

My suggestion is to update the oauth2 section of the documentation to clearly describe the use case for the `password` grant type.
