### ISSUE TITLE
Proposal: keepsubstring/dropsubstring relabel action

### ISSUE THREAD

**Issue by SamuelBoerlin** [prometheus/prometheus#13664]
### Proposal

Hi 👋 

I'm proposing two new `relabel_action`s: `keepsubstring` and `dropsubstring`.
They work the same as `keepequal` and `dropequal` except that they check whether the concatenated `source_labels` is  a substring of the concatenated `target_labels` instead of checking for equality.

My use case for this would be to filter metrics by a label value. Consider the following `relabel_config`:
```yaml
metric_relabel_configs:
  - action: keepsubstring
    source_labels:
      - __name__
    target_labels:
      - metrics_keep_list
  - action: labeldrop
    regex: "metrics_keep_list"
```
with the label `metrics_keep_list="my_metric_1,my_metric_2"` obtained from docker service discovery (`__meta_docker_container_label_metrics_keep_list`). A metric named e.g. "my_metric_3" would be dropped as it is not contained in the `metrics_keep_list` label value.

I'd like to configure metrics scraping entirely through container labels and while it is already possible to create a metrics scrape target from a container and its labels via `docker_sd_config`, there is currently no way to filter the scraped metrics by the means of labels, as far as I can tell.

Supporting regex backreferences as proposed in https://github.com/prometheus/prometheus/issues/12483 would also solve this, as would the original suggestion in https://github.com/prometheus/prometheus/issues/11556. However, this solution might be simpler as it would be nearly identical to PR https://github.com/prometheus/prometheus/pull/11564.
