### ISSUE TITLE
metric name include histogram error

### ISSUE THREAD

**Issue by manas-rust** [prometheus/prometheus#13660]
### What did you do?

```
curl -s http://localhost:9090/metrics | ./promtool check metrics
echo $?
```

### What did you expect to see?

0

### What did you see instead? Under which circumstances?

prometheus_target_scrapes_exceeded_native_histogram_bucket_limit_total metric name should not include type 'histogram'

![image](https://github.com/prometheus/prometheus/assets/28502216/347f161b-e86c-45e2-b4e3-bbf55cd70eeb)

### System information

Linux 6.7.5-200.fc39.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.50.0 (branch: main, revision: bf2658bec1e2ec5d6e13a7bde129efcb94eaeda7)
  build user:       username@localhost.localdomain
  build date:       20240228-09:22:09
  go version:       go1.21.7
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:8090']
```
