### ISSUE TITLE
"increase" not working for backfilled data

### ISSUE THREAD

**Issue by klausenbusk** [prometheus/prometheus#13747]
### What did you do?

1. Ran `./promtool tsdb dump-openmetrics --match='node_network_transmit_bytes_total{instance=~".*\\.mirror\\.pkgbuild\\.com",device=~"en.*"}' --match='pdns_auth_udp_queries{instance=~".*\\.mirror\\.pkgbuild\\.com"}' /var/lib/prometheus/data/ > openmetrics` on our primary (private) Prometheus instance (`promtool, version 2.50.1 (branch: main, revision: eea6ab1cdd24ec69c94ba4b0d165030c89860c8b)`)
2. Created new blocks from said dump with `promtool tsdb create-blocks-from openmetrics openmetrics data --max-block-duration 168h` (`promtool, version 2.50.1 (branch: tarball, revision: 2.50.1)`)
3. Stopped our "public" Prometheus instance
4. Added the new blocks
5. Started our "public" Prometheus instance again

### What did you expect to see?

The queries to behave the same way as on our primary (private) Prometheus instance.

### What did you see instead? Under which circumstances?

The `increase` query function is behaving vastly different on our "public" Prometheus instance.

For the `node_network_transmit_bytes_total{instance=~".*\\.mirror\\.pkgbuild\\.com",device=~"en.*"}` query, the result is the same.

Primary (private) Prometheus instance:
![image](https://github.com/prometheus/prometheus/assets/1080056/aa457a66-8bf2-497b-bc70-6862001a8327)

"Public" Prometheus instance:
![image](https://github.com/prometheus/prometheus/assets/1080056/fc16ba7e-a4a7-4dc3-a4a0-21fcad9bd726)

---

For the `increase(node_network_transmit_bytes_total{instance=~".*\\.mirror\\.pkgbuild\\.com",device=~"en.*"}[30d])` query, the result is vastly different.

Primary (private) Prometheus instance:
![image](https://github.com/prometheus/prometheus/assets/1080056/7eeea6df-92e6-471b-8d24-e20cdb6f4bc4)

"Public" Prometheus instance:
![image](https://github.com/prometheus/prometheus/assets/1080056/9062df21-a982-4f19-98a8-c3f04e222d8d)

### System information

Linux 6.7.9-arch1-1 x86_64

### Prometheus version

```text
prometheus, version 2.50.1 (branch: tarball, revision: 2.50.1)
  build user:       someone@builder
  build date:       20240226-14:24:15
  go version:       go1.22.0
  platform:         linux/amd64
  tags:             unknown
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['10.0.0.38:9100']
        labels:
          instance: "seoul.mirror.pkgbuild.com"
      - targets: ['10.0.0.39:9100']
        labels:
          instance: "sydney.mirror.pkgbuild.com"
      - targets: ['10.0.0.27:9100']
        labels:
          instance: "america.mirror.pkgbuild.com"
      - targets: ['10.0.0.26:9100']
        labels:
          instance: "asia.mirror.pkgbuild.com"
      - targets: ['10.0.0.28:9100']
        labels:
          instance: "europe.mirror.pkgbuild.com"
      - targets: ['10.0.0.43:9100']
        labels:
          instance: "london.mirror.pkgbuild.com"

  - job_name: 'powerdns'
    static_configs:
      - targets: ['10.0.0.27:8081']
        labels:
          instance: "america.mirror.pkgbuild.com"
      - targets: ['10.0.0.26:8081']
        labels:
          instance: "asia.mirror.pkgbuild.com"
      - targets: ['10.0.0.28:8081']
        labels:
          instance: "europe.mirror.pkgbuild.com"
      - targets: ['10.0.0.43:8081']
        labels:
          instance: "london.mirror.pkgbuild.com"
      - targets: ['10.0.0.38:8081']
        labels:
          instance: "seoul.mirror.pkgbuild.com"
      - targets: ['10.0.0.39:8081']
        labels:
          instance: "sydney.mirror.pkgbuild.com"
```

### Alertmanager version

```text
N/A
```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
N/A
```
