### ISSUE TITLE
Generate wrong alerts when upgrading Prometheus from 2.33.5 to 2.50.0

### ISSUE THREAD

**Issue by zhaojinxin409** [prometheus/prometheus#13839]
### What did you do?

I create a alert rule, but it generates alerts' project label is not `less`
```
(max_over_time(app:container:kube_pod_container_status_terminated_reason_error{namespace!~".*(test|dev).*",project="lees"}[5m] offset 5m)) > 0
```

### What did you expect to see?

Generate the alerts with `project=less`

####  What i saw

The Prometheus ALERTS metrics:
![image](https://github.com/prometheus/prometheus/assets/5874804/cf25f4e6-c6aa-496f-82b0-0fae97efaaf1)

The alert rule query result of the same time:
![image](https://github.com/prometheus/prometheus/assets/5874804/c154c1bd-84b4-458d-82d2-27f361fa66e4)

#### How to reproduce

it happens occasionally, haven't found the way to reproduce.

#### Other information

I have two Prometheus of v2.33.5 and v2.50.0, the v2.33.5 works as expected while the v2.50.0 is not.

### Prometheus version

```text
Prometheus 2.50.0
```

### Prometheus configuration file

```yaml
alert:容器实例异常退出-cdn1s9mrjlj070sa9c40
expr:(max_over_time(app:container:kube_pod_container_status_terminated_reason_error{namespace!~".*(test|dev).*",project="lees"}[5m] offset 5m)) > 0
labels:
   category: app
   severity: serious
   source: x
```

### Logs

```text
No related logs
```
