### ISSUE TITLE
url parameter configuration via annotations not working for kubernetes service discovery based scrape job 

### ISSUE THREAD

**Issue by cerberus20** [prometheus/prometheus#13857]
### What did you do?

Below is my scrape job:

      - job_name: 'kube-pods'
  
        kubernetes_sd_configs:
          - role: pod
  
        metric_relabel_configs:
          - action: keep
            regex: (my_metric)
            source_labels:
            - __name__
          - action: labeldrop
            regex: (app|app_kubernetes_io_managed_by|app_kubernetes_io_name|chart|heritage|pod_template_hash)
  
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

Annotation used in target deployment pod:

prometheus.io/param_oldest: "900"

Note: Other prometheus annotations like scheme, path and port are working fine

Discovered labels screenshot for the target which require the oldest param to fetch metrics:
<img width="967" alt="image" src="https://github.com/prometheus/prometheus/assets/119214363/d4b21979-4cf2-45ea-b49f-8c7e525d6b55">

### What did you expect to see?

**We expected parameters specified via annotation : param_<param_name>: <param_value> to be appended to scrape url** making url for path: "/metrics" equal to http://address:port/metrics?<param_name>=<param_value>

### What did you see instead? Under which circumstances?

param annotations didn't do anything, prometheus still scraped upto path annotation like : http://address:port/metrics  but not http://address:port/metrics?<param_name>=<param_value>

### System information

Linux 5.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.35.0 (branch: HEAD, revision: 6656cd29fe6ac92bab91ecec0fe162ef0f187654)
  build user:       root@cf6852b14d68
  build date:       20220421-09:53:42
  go version:       go1.18.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
- job_name: 'kube-pods'
  
        kubernetes_sd_configs:
          - role: pod
  
        metric_relabel_configs:
          - action: keep
            regex: (my_metric)
            source_labels:
            - __name__
          - action: labeldrop
            regex: (app|app_kubernetes_io_managed_by|app_kubernetes_io_name|chart|heritage|pod_template_hash)
  
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - action: labelmap
            regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
            replacement: __param_$1
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
```
