### ISSUE TITLE
Aggregate rule is causing incorrect sum aggregations

### ISSUE THREAD

**Issue by kul** [prometheus/prometheus#13903]
### What did you do?

Applied following addition rules,
```yaml
  - name: agg-recording-rules
    groups:
      - name: agg-rules
        rules:
          - record: my_requests_drop_opt0_total
            expr: sum without (colo, instance, job, service) (my_requests_drop_total)
```

### What did you expect to see?

I was expecting more or less the same `rate` and `increase` calculation over both original and recorded metric.

### What did you see instead? Under which circumstances?

With less load (i.e. instances emitting the metrics) , the rate and increase was in line. For example the cardinality of the original metrics (my_requests_drop_total) at a point in time typically were 38k.

 However with increased load i.e cardinality of 200k , the aggregation rules gave strange results eg. here is how the rate looked 
<img width="1781" alt="image" src="https://github.com/prometheus/prometheus/assets/1580309/8b0fcf38-47f2-48a6-8cef-258c65f6ed58">
<img width="1771" alt="image" src="https://github.com/prometheus/prometheus/assets/1580309/10c0d0cb-c953-487f-86d0-976824e63abe">

### Prometheus version

```text
kube-prometheus-stack-35.5.78
```
