### ISSUE TITLE
discovery(scaleway): instances without private IPs are not added to the target lists

### ISSUE THREAD

**Issue by Heyoxe** [prometheus/prometheus#13940]
### What did you do?

We are using Scaleway instances with routed IPs. Due to how routed IPs work, [those instances have no private IPs](https://www.scaleway.com/en/docs/compute/instances/api-cli/using-routed-ips/#routed-ips-overview).
The documentation says that the Scaleway SD uses the public IPv4 address by default. We have relabelled the instances to use their public IPv4 instead.

### What did you expect to see?

We expect our instances with routed IPs to show up in Scaleway's service discovery with their public IP as addresses.

### What did you see instead? Under which circumstances?

Instances with routed IPs (and therefor no private IPs) are not listed at all.

### System information

Linux 5.15.150.1-microsoft-standard-WSL2 x86_64

### Prometheus version

```text
prometheus, version 2.51.2 (branch: main, revision: b938bbc11169dc224c103bec32a55daad0f3f34e)
  build user:       root@desktop
  build date:       20240416-17:19:29
  go version:       go1.22.0
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: scaleway
    scaleway_sd_configs:
      - role: instance
        project_id: 11111111-1111-1111-1111-111111111111
        access_key: SCWXXXXXXXXXXXXXXXXX
        secret_key: 11111111-1111-1111-1111-111111111111

    relabel_configs:
      - source_labels: [ __meta_scaleway_instance_public_ipv4 ]
        replacement: "${1}:9090"
        target_label: __address__
```
