### ISSUE TITLE
Unable to add namespace in nomad_sd_configs

### ISSUE THREAD

**Issue by helioascorreia** [prometheus/prometheus#13988]
### What did you do?

I'm trying to get the nomad_sd_configs working with a custom namespace.
If I don't specify it works with the default. But if I try to use a custom (or if I put the default like the exame) it gives and error

# Discover Nomad services to scrape.
  - job_name: "nomad_sd"
    nomad_sd_configs:
      - namespace: 'default'
      - server: 'http://localhost:4646'
      

    relabel_configs:
      - source_labels: ["__meta_nomad_service"]
        target_label: job

### What did you see instead? Under which circumstances?

Here is the log

2024-04-24T14:26:40.184Z [prometheus] ts=2024-04-24T14:26:40.184Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=nomad config=nomad_sd msg="Unable to refresh target groups" err="Get \"http://localhost:4646/v1/services?namespace=default®ion=global&stale=\": dial tcp [::1]:4646: connect: connection refused"

My guest is the namespace=default®ion=global, was to be  namespace=default&region=global

**Comment by roidelapluie** [comment]
It looks like the issue isn't with the namespace setting itself, but rather a connection problem. The error message showing "connection refused" suggests that Prometheus can't connect to your Nomad server at localhost:4646...

**Comment by helioascorreia** [comment]
You were right, it was the problem of the ip, sorry

**Comment by helioascorreia** [comment]
I've tried this again, the issue continues...

```
- job_name: nomad_sd
    nomad_sd_configs:
      - server: http://999.9.99.99:4646 <--- in my code I have the real ip
    relabel_configs:
      - source_labels:
          - __meta_nomad_service
        target_label: job
```

with this code this works, but if I add the namespace


```
- job_name: nomad_sd
    nomad_sd_configs:
      - namespace: development
      - server: http://999.9.99.99:4646 <--- in my code I have the real ip
    relabel_configs:
      - source_labels:
          - __meta_nomad_service
        target_label: job
```

this will give this error

ts=2024-06-26T09:31:38.558Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=nomad config=nomad_sd msg="Unable to refresh target groups" err="Get \"http://localhost:4646/v1/services?namespace=development®ion=global&stale=\": dial tcp [::1]:4646: connect: connection refused"

it loses the ip and defaults to localhost

If I put the default namespace it loses the ip too
```
- job_name: nomad_sd
    nomad_sd_configs:
      - namespace: default
      - server: http://999.9.99.99:4646 <--- in my code I have the real ip
    relabel_configs:
      - source_labels:
          - __meta_nomad_service
        target_label: job
```

ts=2024-06-26T09:31:38.558Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=nomad config=nomad_sd msg="Unable to refresh target groups" err="Get \"http://localhost:4646/v1/services?namespace=default®ion=global&stale=\": dial tcp [::1]:4646: connect: connection refused"
