### ISSUE TITLE
Malformed JSON in query API result, 2.52-rc.0 regression

### ISSUE THREAD

**Issue by baryluk** [prometheus/prometheus#14040]
### What did you do?

`$ curl 'http://localhost:19092/api/v1/query?query=process_cpu_seconds_total&time=1714716585.782'; echo`

`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"process_cpu_seconds_total","instance":"localhost:19092","job":"prometheus"},"value":[1714716585.782,"0.29"]}{"metric":{"__name__":"process_cpu_seconds_total","job":"a","instance":"baz:20702"},"value":[1714716585.782,"2125535.148752446"]}]}}`

Notice a missing comma between array elements.

### What did you expect to see?

`$ curl 'http://localhost:19091/api/v1/query?query=process_cpu_seconds_total&time=1714716585.782'; echo`

`{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"process_cpu_seconds_total","job":"a","instance":"baz:20702"},"value":[1714716585.782,"23600372.135197595"]},{"metric":{"__name__":"process_cpu_seconds_total","instance":"localhost:19092","job":"prometheus"},"value":[1714716585.782,"1.2"]}]}}`

### What did you see instead? Under which circumstances?

See above.

It looks like there are missing comas.

Works fine in 2.51.2

### System information

Linux amd64

### Prometheus version

```text
prometheus, version 2.52.0-rc.0 (branch: HEAD, revision: f170a014f31cc97d2aba47cc769e846c68f8545d)
  build user:       root@969a4b73703c
  build date:       20240430-12:21:35
  go version:       go1.22.2
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:19091"]

  - job_name: "a"
    static_configs:
      - targets:
        - "baz:20702"
```
