### ISSUE TITLE
remote write: all samples lost when server returns 500

### ISSUE THREAD

**Issue by koly23** [prometheus/prometheus#14126]
### What did you do?

1. In the same kubernetes cluster, there are two pods: one is prometheus, another is prometheus-agent
2. prometheus-agent scrapes samples and send data to prometheus
3. we don't know how to reproduce this error in our environment. However if data sent by prometheus-agent contains duplicated labels, this error would occur.

Besides:
1. The prometheus server returns 500 for duplicated labels, then the agent keeps retrying forever, which prevents sending the new samples to prometheus server. Then all samples are lost after several hours. [source codes](https://github.com/prometheus/prometheus/blob/release-2.51/storage/remote/queue_manager.go#L1670)
2. Duplicated labels should not be a Recoverable Error. It shoule return 400
3. Can prometheus log the samples for all kinds of error? [source codes](https://github.com/prometheus/prometheus/blob/release-2.51/storage/remote/write_handler.go#L133)
4. To prevent agent retrying forever, can prometheus set maximum number of retries on prometheus server? prometheus-agent sets the retry numbers to request header, but it is not used by the server. [source codes](https://github.com/prometheus/prometheus/blob/release-2.51/storage/remote/client.go#L214)
5. Because just part of the samples are incorrect, is it possible to save the correct part?

### What did you expect to see?

No error in the logs. Samples saved.

### What did you see instead? Under which circumstances?

No samples are saved.

Error in prometheus-agent log:
ts=2024-05-11T08:42:01.235Z caller=dedupe.go:112 component=remote level=warn remote_name=prometheus-k8s-0 url=https://prometheus-k8s-0.monitoring:9091/api/v1/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: label name \"prometheus\" is not unique: invalid sample"
ts=2024-05-11T08:42:02.749Z caller=dedupe.go:112 component=remote level=warn remote_name=prometheus-k8s-0 url=https://prometheus-k8s-0.monitoring:9091/api/v1/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: label name \"service\" is not unique: invalid sample"
ts=2024-05-11T08:42:02.798Z caller=dedupe.go:112 component=remote level=warn remote_name=prometheus-k8s-0 url=https://prometheus-k8s-0.monitoring:9091/api/v1/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: label name \"resourceType\" is not unique: invalid sample"
ts=2024-05-11T08:42:02.851Z caller=dedupe.go:112 component=remote level=warn remote_name=prometheus-k8s-0 url=https://prometheus-k8s-0.monitoring:9091/api/v1/write msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: label name \"namespace\" is not unique: invalid sample"

Error in prometheus log(we modify the codes to log the incorrect samples):
ts=2024-05-11T08:42:26.603Z caller=write_handler.go:134 level=error component=web msg="unknown error from remote write" err="label name \"resourceId\" is not unique: invalid sample" series="{__name__=\"ovs_vswitchd_interface_resets_total\", clusterName=\"clustertest150\", clusterRegion=\"region0\", clusterZone=\"zone1\", container=\"kube-rbac-proxy\", endpoint=\"ovs-metrics\", hostname=\"20230428-wangbo-dev16\", if_name=\"veth99fa6555\", instance=\"[10.253.58.238:9983](http://10.253.58.238:9983/)\", job=\"net-monitor-vnet-ovs\", namespace=\"net-monitor\", pod=\"net-monitor-vnet-ovs-66bdz\", prometheus=\"monitoring/agent-0\", prometheus_replica=\"prometheus-agent-0-0\", resourceId=\"port-naqoi5tmkg5lrt0ubw\", resourceId=\"blb-74se39mqa9k3\", resourceType=\"Port\", resourceType=\"BLB\", rs_ip=\"10.0.0.3\", service=\"net-monitor-vnet-ovs\", service=\"net-monitor-vnet-ovs\", subnet_Id=\"snet-ztojflwrnd08xf5idw\", vip=\"11.4.2.64\", vpc_Id=\"vpc-6ss1uz29ctpfv0eqbj\", vpcid=\"11.4.2.64\"}" timestamp=1715349156000
ts=2024-05-11T08:42:26.603Z caller=write_handler.go:76 level=error component=web msg="Error appending remote write" err="label name \"resourceId\" is not unique: invalid sample"
ts=2024-05-11T08:42:26.967Z caller=write_handler.go:134 level=error component=web msg="unknown error from remote write" err="label name \"service\" is not unique: invalid sample" series="{__name__=\"rest_client_request_size_bytes_bucket\", clusterName=\"clustertest150\", clusterRegion=\"region0\", clusterZone=\"zone1\", container=\"kube-scheduler\", endpoint=\"https\", host=\"[127.0.0.1:6443](http://127.0.0.1:6443/)\", instance=\"[10.253.58.236:10259](http://10.253.58.236:10259/)\", job=\"scheduler\", le=\"262144\", namespace=\"kube-scheduler\", pod=\"kube-scheduler-20230428-wangbo-dev14\", prometheus=\"monitoring/agent-0\", prometheus_replica=\"prometheus-agent-0-0\", resourceType=\"NETWORK-HOST\", service=\"scheduler\", service=\"net-monitor-vnet-ovs\", verb=\"POST\"}" timestamp=1715349164522
ts=2024-05-11T08:42:26.967Z caller=write_handler.go:76 level=error component=web msg="Error appending remote write" err="label name \"service\" is not unique: invalid sample"
ts=2024-05-11T08:42:27.091Z caller=write_handler.go:134 level=error component=web msg="unknown error from remote write" err="label name \"prometheus_replica\" is not unique: invalid sample" series="{__name__=\"workqueue_work_duration_seconds_sum\", clusterName=\"clustertest150\", clusterRegion=\"region0\", clusterZone=\"zone1\", endpoint=\"https\", instance=\"[21.100.10.52:8443](http://21.100.10.52:8443/)\", job=\"metrics\", name=\"ResourceSyncController\", namespace=\"service-ca-operator\", pod=\"service-ca-operator-645cfdbfb6-rjr4z\", prometheus=\"monitoring/agent-0\", prometheus_replica=\"prometheus-agent-0-0\", prometheus_replica=\"prometheus-agent-0-0\", service=\"metrics\"}" timestamp=1715349271085
ts=2024-05-11T08:42:27.091Z caller=write_handler.go:76 level=error component=web msg="Error appending remote write" err="label name \"prometheus_replica\" is not unique: invalid sample"

### System information

kubernetes environment

### Prometheus version

```text
v2.51
```

### Prometheus configuration file

```yaml
prometheus-agent remote-write config:
global:
  evaluation_interval: 30s
  scrape_interval: 5m
  scrape_timeout: 1m
  external_labels:
    clusterName: clustertest150
    clusterRegion: region0
    clusterZone: zone1
    prometheus: ccos-monitoring/agent-0
    prometheus_replica: prometheus-agent-0-0
  keep_dropped_targets: 1
...
remote_write:
- url: https://prometheus-k8s-0.monitoring:9091/api/v1/write
  remote_timeout: 30s
  name: prometheus-k8s-0
  write_relabel_configs:
  - target_label: __tmp_cluster_id__
    replacement: 713c30cb-81c3-411d-b4dc-0c775a0f9564
    action: replace
  - regex: __tmp_cluster_id__
    action: labeldrop
  bearer_token: XDFSDF...
  tls_config:
    insecure_skip_verify: true
  queue_config:
    capacity: 10000
    min_shards: 1
    max_shards: 500
    max_samples_per_send: 2000
    batch_send_deadline: 10s
    min_backoff: 30ms
    max_backoff: 5s
    sample_age_limit: 5m
```
