### ISSUE TITLE
wrong /-/healthy response when storage is not available

### ISSUE THREAD

**Issue by mhristof** [prometheus/prometheus#14150]
### What did you do?

Setup an ec2 instance with an ebs volume attached to it under `/data` and spin up prometheus storing data under `/data`.

When i force unmount/remove teh ebs volume, the logs show failure to write the data

```
s=2024-05-27T13:46:30.892Z caller=scrape.go:1351 level=error component="scrape manager" scrape_pool=ec2 target=http://10.25.1.152:9100/metrics msg="Scrape commit failed" err="write to WAL: log samples: create new segment file: open /prometheus/wal/00000529: input/output error"
```

but the health endpoint is reporting healthy 
```
root@prometheus-ha /]# curl localhost:9090/-/healthy
Prometheus Server is Healthy.
[root@prometheus-ha /]# curl localhost:9090/-/ready
Prometheus Server is Ready.
```

### What did you expect to see?

I'd expect to see some kind of failure in the health/ready endpoints as the system is not able to store the data 

### What did you see instead? Under which circumstances?

Health/ready endpoints return 200

### System information

Linux 6.1.90-99.173.amzn2023.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.48.1 (branch: HEAD, revision: 63894216648f0d6be310c9d16fb48293c45c9310)
  build user:       root@87b7551daa13
  build date:       20240110-00:22:12
  go version:       go1.20.13
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
--
global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    replica: i-1234

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "ec2"
    ec2_sd_configs:
      - region: "ap-northeast-1"
        port: 9100
      - region: "ap-east-1"
        port: 9100
    relabel_configs:
    - source_labels: [__meta_ec2_private_ip]
      replacement: '${1}:9100'
      target_label: __address__
    - source_labels: [__meta_ec2_tag_Name]
      target_label: instance
    - source_labels: [__meta_ec2_tag_Environment]
      target_label: environment
    - source_labels: [__meta_ec2_instance_id]
      target_label: instance_id
    - source_labels: [__meta_ec2_availability_zone_id]
      target_label: availability_zone_id


  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets:
        - 'localhost:9091'
        - 'pushgateway:9091'


rule_files:
  - '/etc/prometheus/rule_directory/*.yml'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
```

### Logs

```text
s=2024-05-27T13:46:30.892Z caller=scrape.go:1351 level=error component="scrape manager" scrape_pool=ec2 target=http://10.25.1.152:9100/metrics msg="Scrape commit failed" err="write to WAL: log samples: create new segment file: open /prometheus/wal/00000529: input/output error"
```
```
