### ISSUE TITLE
Prometheus remote_write server returned x-protobuf is not supported

### ISSUE THREAD

**Issue by sentaycan** [prometheus/prometheus#14163]
### What did you do?

Hi All,

I am working on sending data from prometheus to opensearchusing remote_write in k8s 
Below is the remote write configuration defined in configMap (k8s).

```
    remoteWrite: 
    - url: "https://domain.io/backend/prometheus-metrics/_doc"
    remote_timeout: 30s
    headers:
      Content-Type: "application/json"
    queue_config:
      capacity: 10000
      max_shards: 10
      min_shards: 2
      max_samples_per_send: 5000
      batch_send_deadline: 30m
      min_backoff: 50ms
      max_backoff: 1s
    basic_auth:
      username: 'admin'
      password: 'admin'
```

**But ım getting the following error.**

`ts=2024-05-29T12:13:29.967Z caller=dedupe.go:112 component=remote level=error remote_name=9463ac url=https://domain.io/backend/prometheus-metrics/_doc msg="non-recoverable error" count=2000 exemplarCount=0 err="server returned HTTP status 406 Not Acceptable: {\"error\":\"Content-Type header [application/x-protobuf] is not supported\",\"status\":406}"`

**When I typed **write** instead of **_doc**, I got the following error.**
`
err=“server returned HTTP status 405 Method Not Allowed: {\”error\“:\”Incorrect HTTP method for Uri [/write] and method [POST], allowed: [DELETE, GET, HEAD, PUT]\“,\”status\“:405}”**`

### What did you see instead? Under which circumstances?

Can anyone please help?
