### ISSUE TITLE
Prometheus alerting endpoints not updated when using kubernetes_sd_config

### ISSUE THREAD

**Issue by m0untains** [prometheus/prometheus#14165]
### What did you do?

We deploy Prometheus+Alertmanagers in Kubernetes, using the `kube-prometheus-stack` helm chart, with a fairly standard configuration. We noticed recently that when an alertmanager pod was restarted, the new pod endpoint was not reflected in the alertmanager destinations. Thus Prometheus kept trying to send alerts to an old/invalid pod address. Interestingly, the alertmanagers are also part of the scrape config, and the scrape configuration _was_ correctly updated (so Prometheus began scraping the new alertmanager for metrics, but still sent notifications to the old pod indefinitely).

Unfortunately this behavior does not reproduce on-demand.

Initially I thought this might be related to https://github.com/prometheus/prometheus/issues/11305, however I believe this is a similar but separate issue.

### What did you expect to see?

I expected the downstream alertmanager endpoints to update to the new pod ip address, like the scrape targets did.

### What did you see instead? Under which circumstances?

The destination alertmanager endpoints did not change, so Prometheus continued to try and send alerts to a non-existent pod.

### Prometheus version

```text
Build Information
version	2.51.2
revision	b4c0ab52c3e9b940ab803581ddae9b3d9a452337
branch	HEAD
buildUser	root@b63f02a423d9
buildDate	20240410-14:05:54
goVersion	go1.22.2
```

### Prometheus configuration file

```yaml
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: prometheus-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http-web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - prometheus
```

### Logs

```text
ts=2024-05-29T18:52:46.753Z caller=notifier.go:549 level=error component=notifier alertmanager=http://10.10.89.249:9093/api/v2/alerts count=41 msg="Error sending alert" err="Post \"http://10.10.89.249:9093/api/v2/alerts\": context deadline exceeded"

repeated in the logs over and over.
```
