### ISSUE TITLE
How to use optional HTTP URL parameters.

### ISSUE THREAD

**Issue by andriisoldatenko** [prometheus/prometheus#1417]
I try to use different versions of using this `params` in `prometheus.yml` and it is not working for me :(
My `prometheus.yml` looks like:
```
global:
  scrape_interval:     1s # By default, scrape targets every 15 seconds.
  evaluation_interval: 1s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'example-random'
    metrics_path: /api/metrics
    params:
      format: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s
    scrape_timeout: 1s

    target_groups:
      - targets: ['localhost:3000']
        labels:
          group: 'production'
```
Also I can't find any tests.
```
# Optional HTTP URL parameters.
params:
  [ <string>: [<string>, ...] ]
```

I see only this error:
```
➜  prometheus-0.17.0rc2.darwin-amd64  ./prometheus -config.file=/Users/andrii/workspace/demon/prometheus/prometheus.yml -log.level "error"
prometheus, version 0.17.0rc2 (branch: release-0.17, revision: 667c221)
  build user:       fabianreinartz@macpro
  build date:       20160205-13:34:21
  go version:       1.5.3
ERRO[0000] Couldn't load configuration (-config.file=/Users/andrii/workspace/demon/prometheus/prometheus.yml): yaml: unmarshal errors:
  line 18: cannot unmarshal !!str `prometheus` into []string  source=main.go:213
```
Do you have ideas how to fix it?
