### ISSUE TITLE
Inconsistent query results

### ISSUE THREAD

**Issue by xucq07** [prometheus/prometheus#14196]
### What did you do?

I conducted a query.
![9aab359b-fad5-461c-b7bf-a61c60b5d57d](https://github.com/prometheus/prometheus/assets/99275967/e5c8f136-7fd5-4fff-91e7-7128c6b207ef)

### What did you see instead? Under which circumstances?

The same query graphhas data, but table has no data.
I really don't know what caused this.

![9aab359b-fad5-461c-b7bf-a61c60b5d57d](https://github.com/prometheus/prometheus/assets/99275967/78b6dea1-e4be-481d-ac27-dc093e229163)

### System information

Linux 6.1.84-99.169.amzn2023.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.45.4 (branch: HEAD, revision: dff334450260a50c47b4b4274c3edc6bfb866c60)
  build user:       root@6b005e74c4f5
  build date:       20240318-10:58:43
  go version:       go1.21.8
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
- job_name: cloudwatch-exporter
    scrape_interval: '2m'
    static_configs:
      - targets:
        - 'localhost:9106'
        labels:
          csp: 'aws'
```
