### ISSUE TITLE
sync data\chunks_head: Incorrect function when replaying WAL

### ISSUE THREAD

**Issue by bladedeyna** [prometheus/prometheus#14331]
### What did you do?

Have a strange issue that seems to occur when Prometheus is restarted in a Windows Nanoserver container then attempts to replay its WAL data from persisted storage. I wonder if there is a missing dependency in Windows Nanoserver that Prometheus requires?

Repro steps
1. Prometheus was up and running and scraping data
2. Closed down prometheus (scaling container down to 0)
3. Review persisted storage
![image](https://github.com/prometheus/prometheus/assets/24935514/ea88da1b-74a8-4ac1-819d-85fb59777997)
4. Restart prometheus (scaling container from 0 to 1)
5. Prometheus fails to start with attached logs

**Prometheus custom windows container dockerfile**
```
FROM mcr.microsoft.com/windows/nanoserver:ltsc2019 as installer

ADD https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.windows-amd64.zip /prometheus.zip
RUN mkdir Prometheus
RUN tar -xf /prometheus.zip --strip-components=1 -C /Prometheus

RUN mkdir config

WORKDIR "C:\Prometheus"

EXPOSE 9090

ENTRYPOINT prometheus.exe --enable-feature=otlp-write-receiver --config.file C:\config\prometheus.yml
```

### What did you expect to see?

Prometheus can restart and pick up where it left off

### What did you see instead? Under which circumstances?

Prometheus fails to start with attached logs

### System information

Windows Container in Docker Swarm (Windows Nanoserver LTSC 2019)

### Prometheus version

```text
version=2.52.0, branch=HEAD, revision=879d80922a227c37df502e7315fad8ceb10a986d)
go=go1.22.3
platform=windows/amd64
user=root@d289228da197
date=20240508-21:58:53
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 25s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: <redacted>
    static_configs:
      - targets: ['<redacted>:80']

  - job_name: docker
    static_configs:
      - targets: ['192.168.244.240:9323']

  - job_name: c01host
    static_configs:
      - targets: ['192.168.244.240:9182']

  - job_name: c02host
    static_configs:
      - targets: ['192.168.244.245:9182']

  - job_name: c03host
    static_configs:
      - targets: ['192.168.244.166:9182']
```

### Logs

```text
ts=2024-06-21T12:28:32.215Z caller=main.go:181 level=info msg="Experimental OTLP write receiver enabled"
ts=2024-06-21T12:28:32.220Z caller=main.go:573 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2024-06-21T12:28:32.220Z caller=main.go:617 level=info msg="Starting Prometheus Server" mode=server version="(version=2.52.0, branch=HEAD, revision=879d80922a227c37df502e7315fad8ceb10a986d)"
ts=2024-06-21T12:28:32.220Z caller=main.go:622 level=info build_context="(go=go1.22.3, platform=windows/amd64, user=root@d289228da197, date=20240508-21:58:53, tags=builtinassets,stringlabels)"
ts=2024-06-21T12:28:32.220Z caller=main.go:623 level=info host_details=(windows)
ts=2024-06-21T12:28:32.220Z caller=main.go:624 level=info fd_limits=N/A
ts=2024-06-21T12:28:32.220Z caller=main.go:625 level=info vm_limits=N/A
ts=2024-06-21T12:28:32.235Z caller=web.go:568 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2024-06-21T12:28:32.239Z caller=main.go:1129 level=info msg="Starting TSDB ..."
ts=2024-06-21T12:28:32.240Z caller=tls_config.go:313 level=info component=web msg="Listening on" address=[::]:9090
ts=2024-06-21T12:28:32.240Z caller=tls_config.go:316 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2024-06-21T12:28:32.252Z caller=dir_locker.go:77 level=warn component=tsdb msg="A lockfile from a previous execution already existed. It was replaced" file=C:\Prometheus\data\lock
ts=2024-06-21T12:28:32.276Z caller=head.go:616 level=info component=tsdb msg="Replaying on-disk memory mappable chunks if any"
ts=2024-06-21T12:28:32.276Z caller=head.go:703 level=info component=tsdb msg="On-disk memory mappable chunks replay completed" duration=0s
ts=2024-06-21T12:28:32.276Z caller=head.go:711 level=info component=tsdb msg="Replaying WAL, this may take a while"
panic: sync directory: sync data\chunks_head: Incorrect function.

goroutine 465 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x4e5f520, 0xc000118c18})
/app/tsdb/head_append.go:1493 +0x5c
github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).WriteChunk(0xc0004a80f0, 0x2, 0x1903a81c84e, 0x1903aaa8636, {0x4ea02f0, 0xc000b40000}, 0x0, 0x4771fa0)
/app/tsdb/chunks/head_chunks.go:442 +0x151
github.com/prometheus/prometheus/tsdb.(*memSeries).mmapChunks(0xc00054c630, 0xc0004a80f0)
/app/tsdb/head_append.go:1475 +0xc5
github.com/prometheus/prometheus/tsdb.(*walSubsetProcessor).processWALSamples(0xc00052b8f0, 0xc000193808, 0xc0009d6060, 0xc0009d6090)
/app/tsdb/head_wal.go:594 +0x48d
github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x0?)
/app/tsdb/head_wal.go:104 +0x45
created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL in goroutine 287
```
