### ISSUE TITLE
[agent] metrics reported by prometheus in agent mode break meta monitoring

### ISSUE THREAD

**Issue by michael-doubez** [prometheus/prometheus#14349]
### What did you do?

* Install a Prometheus in agent mode and write metring to endpoint.
* Prometheus agent is gathering its own metrics
* Prometheus at endpoint applies alert rules as described in [documentation](https://github.com/prometheus/prometheus/blob/c5040c5ea9e70b6525cd6942fb26a1bdb32510d6/documentation/prometheus-mixin/alerts.libsonnet#L92)

### What did you expect to see?

No Prometheus alerts triggered by Prometheus agent metamonitoring rules in respect to general Prometheus rules.

### What did you see instead? Under which circumstances?

 A `PrometheusNotConnectedToAlertmanagers` alert is triggered because `prometheus_notifications_alertmanagers_discovered 0` is collected on prometheus in agent mode

I didn't expect this metric to be published because prometheus in agent mode doesn't apply alert rules and doesn't have notifications. This causes a alert to be triggered for a prometheus instance who cannot have a alertmanager and I have add to tag prometheus in agent mode to add a UNLESS clause in alert rules.

### System information

Linux 3.10.0-1160.119.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.52.0 (branch: HEAD, revision: 879d80922a227c37df502e7315fad8ceb10a986d)
  build user:       root@1b4f4c206e41
  build date:       20240508-21:56:43
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
- alert: PrometheusNotConnectedToAlertmanagers
    expr: prometheus_notifications_alertmanagers_discovered < 1
    for: 10m
    labels:
      severity: warning
      chain: monitoring
      service: Prometheus
    annotations:
      description: Prometheus {{ $labels.instance }} is not connected to any Alertmanagers
```

### Logs

```text
Prometheus in namespace exposes :

prometheus_notifications_alertmanagers_discovered{app_kubernetes_io_component="server", app_kubernetes_io_name="prometheus", instance="...", job="kubernetes-service-endpoints", ...} 0

Generates alert:

ALERTS{alertname="PrometheusNotConnectedToAlertmanagers", alertstate="firing", app_kubernetes_io_component="server", app_kubernetes_io_name="prometheus", job="kubernetes-service-endpoints", ..., service="Prometheus", severity="warning"} 1
```
