### ISSUE TITLE
External_labels not being honoured

### ISSUE THREAD

**Issue by johnmalone** [prometheus/prometheus#1437]
Hi,

I tried out 0.17.0rc2 and discovered that our external_labels settings were no longer appearing in our metrics.

Top of prometheus.yml:

 
```
global:
  scrape_interval: 60s
  evaluation_interval: 60s
  scrape_timeout: 30s
  external_labels:
    env: "dev"
    region: "eu-west-1"

```

We've been on an old version for a while so I had to update "labels" to external_labels above and I've tried 17.0rc1 and 16.2 and my custom labels don't seem to appear anywhere. Is there something else I need to do to get my labels back?

Thanks

John
