### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by lcbluestorm** [prometheus/prometheus#1438]
the prometheus.yml configuration is:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'codelab-monitor'


rule_files:
  - "recoding.rules"
  - "alert.rules"


scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    scrape_timeout: 3s

    target_groups:
      - targets: ['localhost:19089']
        labels:
          group: 'self'
- job_name: 'article_service'

    scrape_interval: 5s
    scrape_timeout: 3s
    target_groups:
      - targets: ['localhost:9711']
        labels:
          group: 'articleService-test'
```
But, there is a error like that:
<img width="1151" alt="2016-03-01 5 53 43" src="https://cloud.githubusercontent.com/assets/7836449/13423568/974de31c-dfd6-11e5-923a-9c8902cd4491.png">
