### ISSUE TITLE
Prometheus stucks on protection from Host Header Injection

### ISSUE THREAD

**Issue by rus-99-pk** [prometheus/prometheus#14421]
### What did you do?

**I configured NGINX that:**
```
    if ($host != $server_name) {
        return 444;
    }
    if ($http_host != $server_name) {
        return 444;
    }
```

**And configured Prometheus on this target:**
`https://$server_name/mntr`

1) If i'll try to run curl on this target, everything will be ok, and i'll get application metrics.
2) If i'll try to reload Prometheus config, i'll get it in a Error column: `Get "https://$server_name:443/mntr EOF`
![изображение](https://github.com/prometheus/prometheus/assets/93255418/4c1352d0-1af7-4d38-9336-35b1b1db39b1)

**I looked NGINX logs, and saw this:**
`"GET /mntr HTTP/1.1" 444 0 "-" "Prometheus/2.30.0" "-"`

**If i'll try to comment that NGINX block:**
`"GET /mntr HTTP/1.1" 200 0 "-" "Prometheus/2.30.0" "-"`

I think, that's a bug. What request does Prometheus?

### What did you expect to see?

I expected to see this answer from NGINX:  `"GET /mntr HTTP/1.1" 200 0 "-" "Prometheus/2.30.0" "-"`

### What did you see instead? Under which circumstances?

I got: `"GET /mntr HTTP/1.1" 444 0 "-" "Prometheus/2.30.0" "-"`

When i configured my NGINX from Host Header Injection.

### System information

Linux 4.15.0-20-generic x86_64

### Prometheus version

```text
prometheus, version 2.30.0 (branch: HEAD, revision: 37468d88dce85ac507f3fb7864c7d1c078e3e27d)
  build user:       root@e913c65aa170
  build date:       20210914-09:49:24
  go version:       go1.17.1
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
prometheus.yml:
  - job_name: federate
    honor_labels: true
    file_sd_configs:
    - files:
      - scrape/*.yml
    tls_config:
      ca_file: /etc/prometheus/cert.pem
    scheme: https

scrape/federate/targets.yml:
- targets:
  - $server_name
  labels:
    cluster: $server_name
    __metrics_path__: /mntr
```
