### ISSUE TITLE
Not enough memory resources

### ISSUE THREAD

**Issue by Akinnagbe** [prometheus/prometheus#14428]
### What did you do?

Run prometheus.exe command and it was pulling metrics. Suddenly it stopped, and trying to bring it back up failed. The server has 18GB free space with 8GB RAM

### What did you expect to see?

Logs that prometheus is running

### What did you see instead? Under which circumstances?

level=error err="opening storage failed: mmap files: mmap, size 176509308: MapViewOfFile: Not enough memory resources are available to process this command."

Saw the above while trying to restart the promethues command

### System information

windows intel 64bits

### Prometheus version

```text
prometheus-2.52.0.windows-386
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  #evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    #  - targets: ["localhost:9090"]
  # - job_name: "demo"
  #   static_configs:
  #   - targets:
  #     - demo.promlabs.com:10000
  #     - demo.promlabs.com:10001
  #     - demo.promlabs.com:10002

  - job_name: "ussd"
    scheme: http
    static_configs:
      - targets: ["localhost:80"]
    metrics_path: /metrics
  
  # - job_name: "win-exporter"
    # scheme: http
    # static_configs:
      # - targets: ["localhost:9115"]
    # metrics_path: /metrics
```

### Logs

```text
ts=2024-07-05T21:03:45.333Z caller=main.go:573 level=info msg="No time or size retention was set so using the default time retention" duration=15d
ts=2024-07-05T21:03:45.333Z caller=main.go:617 level=info msg="Starting Prometheus Server" mode=server version="(version=2.52.0, branch=HEAD, revision=879d80922a227c37df502e7315fad8ceb10a986d)"
ts=2024-07-05T21:03:45.333Z caller=main.go:619 level=warn msg="This Prometheus binary has not been compiled for a 64-bit architecture. Due to virtual memory constraints of 32-bit systems, it is highly recommended to switch to a 64-bit binary of Prometheus." GOARCH=386
ts=2024-07-05T21:03:45.333Z caller=main.go:622 level=info build_context="(go=go1.22.3, platform=windows/386, user=root@d289228da197, date=20240508-21:56:42, tags=builtinassets,stringlabels)"
ts=2024-07-05T21:03:45.334Z caller=main.go:623 level=info host_details=(windows)
ts=2024-07-05T21:03:45.334Z caller=main.go:624 level=info fd_limits=N/A
ts=2024-07-05T21:03:45.334Z caller=main.go:625 level=info vm_limits=N/A
ts=2024-07-05T21:03:45.352Z caller=web.go:568 level=info component=web msg="Start listening for connections" address=0.0.0.0:9090
ts=2024-07-05T21:03:45.353Z caller=main.go:1129 level=info msg="Starting TSDB ..."
ts=2024-07-05T21:03:45.354Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1719830597621 maxt=1719856800000 ulid=01J1R8E59BGAJ8GR64AMBG0VAP
ts=2024-07-05T21:03:45.354Z caller=tls_config.go:313 level=info component=web msg="Listening on" address=[::]:9090
ts=2024-07-05T21:03:45.354Z caller=tls_config.go:316 level=info component=web msg="TLS is disabled." http2=false address=[::]:9090
ts=2024-07-05T21:03:45.354Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1719856807629 maxt=1719921600000 ulid=01J1T67G8Y95NW2H1SQ2F9A1GX
ts=2024-07-05T21:03:45.355Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1719921607625 maxt=1719986400000 ulid=01J1W4109RQYYEKAHNCGE148Y1
ts=2024-07-05T21:03:45.355Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1719986407629 maxt=1720051200000 ulid=01J1Y1TTHT0Y7GW7VQ0MTQ6B31
ts=2024-07-05T21:03:45.356Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1720051207628 maxt=1720116000000 ulid=01J1ZZM2AV2EVH4FM0QNVDZ1RS
ts=2024-07-05T21:03:45.357Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1720180807641 maxt=1720188000000 ulid=01J21PHRV3SEMV6Z41FJ67KCAB
ts=2024-07-05T21:03:45.357Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1720188007636 maxt=1720195200000 ulid=01J21XDJCR1QXTESNWHJ6Q1FBY
ts=2024-07-05T21:03:45.358Z caller=repair.go:56 level=info component=tsdb msg="Found healthy block" mint=1720116007628 maxt=1720180800000 ulid=01J21XDKTK85Q9F6PND56TYXYY
ts=2024-07-05T21:03:45.383Z caller=main.go:988 level=info msg="Stopping scrape discovery manager..."
ts=2024-07-05T21:03:45.384Z caller=main.go:1002 level=info msg="Stopping notify discovery manager..."
ts=2024-07-05T21:03:45.384Z caller=manager.go:163 level=info component="rule manager" msg="Starting rule manager..."
ts=2024-07-05T21:03:45.385Z caller=main.go:984 level=info msg="Scrape discovery manager stopped"
ts=2024-07-05T21:03:45.386Z caller=manager.go:177 level=info component="rule manager" msg="Stopping rule manager..."
ts=2024-07-05T21:03:45.387Z caller=manager.go:187 level=info component="rule manager" msg="Rule manager stopped"
ts=2024-07-05T21:03:45.386Z caller=main.go:998 level=info msg="Notify discovery manager stopped"
ts=2024-07-05T21:03:45.388Z caller=main.go:1039 level=info msg="Stopping scrape manager..."
ts=2024-07-05T21:03:45.389Z caller=notifier.go:623 level=info component=notifier msg="Stopping notification manager..."
ts=2024-07-05T21:03:45.389Z caller=main.go:1261 level=info msg="Notifier manager stopped"
ts=2024-07-05T21:03:45.389Z caller=main.go:1031 level=info msg="Scrape manager stopped"
ts=2024-07-05T21:03:45.390Z caller=main.go:1270 level=error err="opening storage failed: mmap files: mmap, size 176509308: MapViewOfFile: Not enough memory resources are available to process this command."
```
