### ISSUE TITLE
duplicate rule(s) found

### ISSUE THREAD

**Issue by wrizyy450** [prometheus/prometheus#14520]
### What did you do?

Run the following command to check the alarm rule configuration file：**promtool check rules test.rules**

### What did you see instead? Under which circumstances?

**The following is the content of my profile：(The alert and labels of the two alarm rules are identical, but the expr is different)**
```
groups:
- name: TendisAlert
  rules:

  - alert: TestAlert
    expr: up{project="redis",instance="10.0.0.1:6379"} == 0
    labels:
      severity: P1
      job_name: test
    annotations:
      description: 'this is a alert test'

  - alert: TestAlert
    expr: up{project="redis",instance="10.0.0.2:6379"} == 0
    labels:
      severity: P1
      job_name: test
    annotations:
      description: 'this is a alert test
```'
**An error was reported during check：**
```
Checking test.rules
  FAILED:
lint error 1 duplicate rule(s) found.
Metric: TestAlert
Label(s):
        job_name: test
        severity: P1
Might cause inconsistency while recording expressions
```
**I have checked the previous issues about this problem, but I do have such configuration requirements, and cannot solve this problem by modifying alert and labels. However, if I ignore this error directly, I can successfully load this configuration, and no exceptions are found through testing. Now I want to know if this configuration has any real effects, such as triggering some hidden logic.**

### System information

_No response_

### Prometheus version

```text
We used the following two versions and both encountered this problem：

prometheus, version 2.48.1 (branch: HEAD, revision: 63894216648f0d6be310c9d16fb48293c45c9310)
  build user:       root@71f108ff5632
  build date:       20231208-23:33:22
  go version:       go1.21.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels

prometheus, version 2.45.0 (branch: HEAD, revision: 8ef767e396bf8445f009f945b0162fd71827f445)
  build user:       root@920118f645b7
  build date:       20230623-15:09:49
  go version:       go1.20.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```
