### ISSUE TITLE
Custom labels are getting lost in scrape_configs.

### ISSUE THREAD

**Issue by wumindc** [prometheus/prometheus#14578]
### What did you do?

I'm using file_sd_configs to dynamically get the scraping clients, and my client file defines 4 standard labels as follows:

Reading path: /etc/prometheus/scrape_configs/devops/HfEC.json

```shell
[{
  "targets": ["192.168.0.11:9100"],
  "labels": {
    "bizFlag": "GS",
    "host": "Server-0.58",
    "atMobiles": "1xxxxx7",
    "type": "NODE_EXPORTER"
  }
}]
```

My rule configuration is as follows:
```shell
groups:
- name: Server Resource Monitoring
  rules:
  - alert: High Memory Usage
    expr: 100 - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100 > 90
    for: 5m  # Alert duration, the alert will be sent to the alertmanager only if it exceeds this duration
    labels:
      severity: Average
      tplFlag: Memory
    annotations:
      summary: "{{ $labels.instance }} has high memory usage, please handle it ASAP!"
      description: "Memory usage exceeds 90%, current usage is {{ $value }}%."

  - alert: Server Down
    expr: up == 0
    for: 3m
    labels:
      severity: High
      tplFlag: NodeClient
    annotations:
      summary: "{{ $labels.instance }} is down, please handle it ASAP!"
      description: "The server has been down for more than 3 minutes, current status is {{ $value }}."

  - alert: High CPU Load
    expr: 100 - (avg by (instance, job) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
    for: 5m
    labels:
      severity: Average
      tplFlag: CPU
    annotations:
      summary: "{{ $labels.instance }} has high CPU usage, please handle it ASAP!"
      description: "CPU usage exceeds 90%, current usage is {{ $value }}%."

  - alert: Disk IO Performance
    expr: avg(irate(node_disk_io_time_seconds_total[1m])) by(instance, job) * 100 > 90
    for: 5m
    labels:
      severity: Warning
      tplFlag: Disk
    annotations:
      summary: "{{ $labels.instance }} has high disk IO usage, please handle it ASAP!"
      description: "Disk IO usage exceeds 90%, current usage is {{ $value }}%."

  - alert: Network Inflow
    expr: (sum(rate(node_network_receive_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance, job)) / 100 > 102400
    for: 5m
    labels:
      severity: Warning
      tplFlag: Network
    annotations:
      summary: "{{ $labels.instance }} has high network inflow, please handle it ASAP!"
      description: "Network inflow exceeds 100MB for 5 minutes, current usage is {{ $value }}."

  - alert: Network Outflow
    expr: (sum(rate(node_network_transmit_bytes_total{device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])) by (instance, job)) / 100 > 102400
    for: 5m
    labels:
      severity: Warning
      tplFlag: Network
    annotations:
      summary: "{{ $labels.instance }} has high network outflow, please handle it ASAP!"
      description: "Network outflow exceeds 100MB for 5 minutes, current usage is {{ $value }}."

  - alert: High TCP Connections
    expr: node_netstat_Tcp_CurrEstab > 10000
    for: 10m
    labels:
      severity: Average
      tplFlag: Network
    annotations:
      summary: "High TCP_ESTABLISHED connections!"
      description: "TCP_ESTABLISHED connections exceed 10000, current count is {{ $value }}."

  - alert: Disk Capacity
    expr: 100 - (node_filesystem_free_bytes{mountpoint!~"/boot|/run.*|/var.*", fstype=~"ext4|xfs"} / node_filesystem_size_bytes{mountpoint!~"/boot|/run.*|/var.*", fstype=~"ext4|xfs"} * 100) > 90
    for: 10m
    labels:
      severity: High
      tplFlag: Disk
    annotations:
      summary: "{{ $labels.mountpoint }} partition has high disk usage, please handle it ASAP!"
      description: "Disk partition usage exceeds 90%, current usage is {{ $value }}%."
```
However, when the CPU alert is triggered, the labels are not included, while other alerts have them. During testing, I also found that the TCP alert includes the labels.

![image](https://github.com/user-attachments/assets/42864402-5e34-4313-95a0-062a4de717e2)

### What did you expect to see?

I hope my alert messages can correctly include the custom labels.

### What did you see instead? Under which circumstances?

However, when the CPU alert is triggered, the labels are not included, while other alerts have them. During testing, I also found that the TCP alert includes the labels.

![image](https://github.com/user-attachments/assets/42864402-5e34-4313-95a0-062a4de717e2)

### System information

Linux 3.10.0-1160.99.1.el7.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.52.0 (branch: HEAD, revision: 879d80922a227c37df502e7315fad8ceb10a986d)
  build user:       root@1b4f4c206e41
  build date:       20240508-21:56:43
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/rules/devops/*.yml

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "sd"
    basic_auth:
      username: ***
      password: ***
    file_sd_configs:
      - files:
          - /etc/prometheus/scrape_configs/devops/*.json
          - /etc/prometheus/scrape_configs/custom/*.json
```

### Alertmanager version

```text
alertmanager, version 0.26.0 (branch: HEAD, revision: d7b4f0c7322e7151d6e3b1e31cbc15361e295d8d)
  build user:       root@df8d7debeef4
  build date:       20230824-11:11:58
  go version:       go1.20.7
  platform:         linux/amd64
  tags:             netgo
```

### Alertmanager configuration file

```yaml
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:11100/api/alarm/prometheus/push'
        send_resolved: true
        http_config:
          basic_auth:
            username: ***
            password: ***
inhibit_rules:
  - source_match:
      severity: 'Disaster'
    target_match:
      severity: 'Warning'
    equal: ['alertname', 'dev', 'instance']
```
