### ISSUE TITLE
Attributes ignored when pushing data through OTLP endpoint 

### ISSUE THREAD

**Issue by marcoboi** [prometheus/prometheus#14580]
### What did you do?

I have an OpenTelemetry collector gathering kubelet metrics.
The metrics have attributes attached.
The Collector pushes data to Prometheus through the `api/v1/otlp` endpoint.
See [this post](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34075#issuecomment-2262904739) for full setup and Collector configuration.

### What did you expect to see?

I would expect the metrics attributes to be available as labels in Prometheus, so that I can partition the data using those attributes.

### What did you see instead? Under which circumstances?

The metrics gathered by the Collector are available through the Prometheus UI but no labels are attached to them.

### Prometheus version

```text
Helm chart:

  - name: prometheus
    version: 25.17.0
    repository: https://prometheus-community.github.io/helm-charts
```

### Prometheus configuration file

```yaml
prometheus:
  configmapReload:
    prometheus:
      enabled: false
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-pushgateway:
    enabled: false

  server:
    extraFlags:
      - "enable-feature=exemplar-storage"
      - "enable-feature=otlp-write-receiver"
    global:
      scrape_interval: 10s
      scrape_timeout: 5s
      evaluation_interval: 30s
    persistentVolume:
      enabled: false
    service:
      servicePort: 9090
```

**Comment by marcoboi** [comment]
It seems the [same issue](https://github.com/kubeflow/spark-operator/issues/1404) has already been reported.

**Comment by marcoboi** [comment]
There's a [PR open](https://github.com/kubeflow/spark-operator/pull/1520) to solve the issue for over one year.

**Comment by marcoboi** [comment]
I found a way to circumvent the problem, but I do not fully understand what the underlying problem is.
To get the attributes to attach to the metrics as labels, the following block needs to be added to the OpenTelemetry collector pipeline:
```
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["namespace"], resource.attributes["k8s.namespace.name"])
              - set(attributes["container"], resource.attributes["k8s.container.name"])
              - set(attributes["pod"], resource.attributes["k8s.pod.name"])
              - set(attributes["pod_id"], resource.attributes["k8s.pod.uid"])
              - set(attributes["node"], resource.attributes["k8s.node.name"])
              - set(attributes["app"], resource.attributes["k8s-app"])
```

This _processor_ maps the attributes from the Otel format to a format Prometheus understands.

I am not sure if the underlying issue is the nesting of the attributes or the fact that the original attributes are separated by a dot (which Prometheus does not support).
I would appreciate the help of the Prometheus community on that topic if anyone has more background.

The manifest of a full working Collector is attaches in the [original Otel ticket](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34075#issuecomment-2262904739).

**Comment by bboreham** [comment]
Are they Resource attributes?
See #14200. 

Likely duplicate of #13192.

**Comment by ArthurSens** [comment]
The new `otlp` configuration options that were added in #14200 are only available in Prometheus 2.54, which was released last week.

The chart you're using still needs to add support for that. You can see the chart repository here: https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

Please open an issue in their repository requesting this feature... or even better, if you're comfortable with helm templates you can also open a PR implementing your request :)

**Comment by bboreham** [comment]
To illustrate, the Prometheus config goes in an `otlp` section at top level, and might look like this:
```
global:
  scrape_interval: 15s
  scrape_timeout: 15s

otlp:
  promote_resource_attributes: ["env", "service.name"]

storage:
  tsdb:
    out_of_order_time_window: 10m
```
