### ISSUE TITLE
promtool says config is valid when it isn't

### ISSUE THREAD

**Issue by davidmankin** [prometheus/prometheus#1458]
`promtool` told me that this (snippet of) config was valid but Prometheus crashed trying to read it.
```yml
    relabel_configs:
   - source_labels: [__address__]
      #regex: "(.+):10255"
      target_label: node
      # replacement: "${1}"
```
Promtool says SUCCESS
```
$ promtool check-config prometheus-config/prometheus.yml
Checking prometheus-config/prometheus.yml
  SUCCESS: 0 rule files found
```

Prometheus crashes:
```
time="2016-03-03T19:21:53Z" level=error msg="Couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): relabel configuration requires a regular expression" source="main.go:208"
```

Further it would be useful if the error message explained specifically that it was a 'regex' field that was missing on line 92.
