### ISSUE TITLE
[Error] Setup prometheus to scrap ms instances from Eureka SD

### ISSUE THREAD

**Issue by ungaratto93** [prometheus/prometheus#14632]
### What did you do?

Scrap metrics from ms registered on eureka sd
I'm trying catch prometheus data from a ms registered with a random port in eureka sd.

### What did you expect to see?

Connection success in eureka rest api

### What did you see instead? Under which circumstances?

`2024-08-08 22:44:06 ts=2024-08-09T01:44:06.202Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=eureka config=eureka-discovery msg="Unable to refresh target groups" err="Get \"http://localhost:8081/eureka/apps\": dial tcp [::1]:8081: connect: connection refused"`

### Prometheus version

```text
prometheus, version 2.53.1 (branch: HEAD, revision: 14cfec3f6048b735e08c1e9c64c8d4211d32bab4)
  build user:       root@9f8e5b6970da
  build date:       20240710-10:16:27
  go version:       go1.22.5
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
  - job_name: eureka-discovery
    eureka_sd_configs:
    - server: http://localhost:8081/eureka

    relabel_configs:
    - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_service]
      target_label: service
    - source_labels: [__meta_instance]
      target_label: instance
    - source_labels: [__meta_port]
      target_label: port
```

### Logs

```text
2024-08-08 22:44:06 ts=2024-08-09T01:44:06.202Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=eureka config=eureka-discovery msg="Unable to refresh target groups" err="Get \"http://localhost:8081/eureka/apps\": dial tcp [::1]:8081: connect: connection refused"
```
