### ISSUE TITLE
Prometheus scrape config does not support recognizing IPv6 addresses.

### ISSUE THREAD

**Issue by xiaoyuan2019** [prometheus/prometheus#14656]
### What did you do?

Prometheus automatically discovers the metrics interfaces exposed by microservices based on the __meta_kubernetes_pod_annotation_prometheus_io_scrape label in the microservice configuration. It uses relabeling to rewrite the address label, using the address and __meta_kubernetes_service_annotation_prometheus_io_port source metrics, with the regular expression: "([^:]+)(?::\d+)?;(\d+)". However, this expression can only recognize IPv4 addresses and not IPv6 addresses, leading to incorrect monitoring of the metrics interfaces of the monitoring objects on the prometheus-status-targets page. It needs to be able to identify IP addresses from the following four types of strings: [2001:cafe:42::13b]:9003, 2001:cafe:42::13b, 192.165.1.1:10088, 1.1.1.1.
![image](https://github.com/user-attachments/assets/914f59ea-525a-4a16-9033-9e44c30cd550)

### What did you expect to see?

Prometheus scrape config can automatically recognize IPv4 and IPv6 addresses using regular expressions, and can combine the address metrics into the correct value.

### What did you see instead? Under which circumstances?

Unable to correctly identify IP addresses from the four types of strings and unable to concatenate the port from __meta_kubernetes_service_annotation_prometheus_io_port, resulting in all microservice monitoring objects being in an abnormal state.
![image](https://github.com/user-attachments/assets/450a3869-9091-4a55-93c6-d55b233c3439)
![image](https://github.com/user-attachments/assets/ef910a4d-109b-4307-940d-fefdd9cbeb83)

### System information

Linux 4.19.113-300.el7.x86_64 x86_64

### Prometheus version

```text
version	2.51.0
revision	c05c15512acb675e3f6cd662a6727854e93fc024
branch	HEAD
buildUser	root@b5723e458358
buildDate	20240319-10:54:45
goVersion	go1.22.1
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 30s
alerting:
  alertmanagers:
  - basic_auth:
      username: alertmanager
      password: <secret>
    follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets:
      - '[2002:db8:0:1::103]:9093'
      labels:
        instance: '[2002:db8:0:1::103]:9093'
        node_ip: 2002:db8:0:1::103
rule_files:
- /etc/prometheus/alert_rules/*.yml
scrape_configs:
- job_name: pushgateway
  honor_labels: true
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 30s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: pushgateway
    password: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - '[2002:db8:0:1::103]:9091'
    labels:
      instance: '[2002:db8:0:1::103]:9091'
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /prometheus/metrics
  scheme: https
  enable_compression: true
  basic_auth:
    username: prometheus
    password: <secret>
  tls_config:
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - '[2002:db8:0:1::101]:8081'
    labels:
      instance: 2002:db8:0:1::103:19090
      node_ip: 2002:db8:0:1::103
- job_name: django
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 2m
  scrape_timeout: 1m
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /ksops/api/v1/metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: ksops
    password: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - '[2002:db8:0:1::101]:10010'
    labels:
      instance: '[2002:db8:0:1::101]:10010'
      node_ip: 2002:db8:0:1::101
- job_name: alertmanager
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: alertmanager
    password: <secret>
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - '[2002:db8:0:1::103]:9093'
    labels:
      instance: '[2002:db8:0:1::103]:9093'
      node_ip: 2002:db8:0:1::103
- job_name: redis_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/redis_exporter.json
    refresh_interval: 30s
- job_name: mysql_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: mysql
    password: <secret>
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/mysql_exporter.json
    refresh_interval: 30s
- job_name: process_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 50s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: process
    password: <secret>
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/process_exporter.json
    refresh_interval: 30s
- job_name: es_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/es_exporter.json
    refresh_interval: 30s
- job_name: etcd_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/etcd_exporter.json
    refresh_interval: 30s
- job_name: kafka_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/kafka_exporter.json
    refresh_interval: 30s
- job_name: rabbitmq_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/rabbitmq_exporter.json
    refresh_interval: 30s
- job_name: consul_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/consul_exporter.json
    refresh_interval: 30s
- job_name: mongo_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/mongo_exporter.json
    refresh_interval: 30s
- job_name: clickhouse_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/clickhouse_exporter.json
    refresh_interval: 30s
- job_name: jaeger_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/jaeger_exporter.json
    refresh_interval: 30s
- job_name: yunproxy_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/yunproxy_exporter.json
    refresh_interval: 30s
- job_name: loki_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/loki_exporter.json
    refresh_interval: 30s
- job_name: promtail_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/promtail_exporter.json
    refresh_interval: 30s
- job_name: docker_cadvisor
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/docker_cadvisor.json
    refresh_interval: 30s
- job_name: docker_minio
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /minio/v2/metrics/node
  scheme: http
  enable_compression: true
  authorization:
    type: Bearer
    credentials: <secret>
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/docker_minio.json
    refresh_interval: 30s
- job_name: node_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 50s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: node
    password: <secret>
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/node_exporter.json
    refresh_interval: 30s
- job_name: kubewps_exporter
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 50s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: kubewps
    password: <secret>
  follow_redirects: true
  enable_http2: true
  file_sd_configs:
  - files:
    - /etc/prometheus/kubewps_exporter.json
    refresh_interval: 30s
- job_name: cluster16:etcd
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  tls_config:
    ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
    cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
    key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - '[2002:db8:0:1::101]:2379'
    - '[2002:db8:0:1::102]:2379'
    - '[2002:db8:0:1::103]:2379'
    labels:
      app: etcd-k8s
- job_name: cluster16:kubernetes-apiservers
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  tls_config:
    ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
    cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
    key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - api_server: https://[2002:db8:0:1::101]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::102]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::103]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
- job_name: cluster16:kubernetes-nodes-kubelet
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: https
  enable_compression: true
  tls_config:
    ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
    cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
    key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  kubernetes_sd_configs:
  - api_server: https://[2002:db8:0:1::101]:6443
    role: node
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::102]:6443
    role: node
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::103]:6443
    role: node
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
- job_name: cluster16:kubernetes-service-endpoints
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    separator: ;
    regex: (http?)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    separator: ;
    regex: (\d+(\.\d+){3}|[a-z\d]+(:[a-z\d]*){1,7});(\d+)
    target_label: __address__
    replacement: '[$1]:$2'
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(. +)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - api_server: https://[2002:db8:0:1::101]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::102]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::103]:6443
    role: endpoints
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
- job_name: cluster16:kubernetes-services
  honor_timestamps: true
  track_timestamps_staleness: false
  params:
    module:
    - http_2xx
  scrape_interval: 1m
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /probe
  scheme: http
  enable_compression: true
  tls_config:
    ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
    cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
    key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - api_server: https://[2002:db8:0:1::101]:6443
    role: service
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::102]:6443
    role: service
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::103]:6443
    role: service
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
- job_name: cluster16:kubernetes-pods
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 1m
  scrape_timeout: 50s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  basic_auth:
    username: pushgateway
    password: <secret>
  tls_config:
    ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
    cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
    key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_label_fullname]
    separator: ;
    regex: (.*)
    target_label: app
    replacement: $1
    action: replace
  - source_labels: [release]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - api_server: https://[2002:db8:0:1::101]:6443
    role: pod
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::102]:6443
    role: pod
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
  - api_server: https://[2002:db8:0:1::103]:6443
    role: pod
    kubeconfig_file: ""
    tls_config:
      ca_file: /etc/kubernetes/cluster16/ssl/ca.pem
      cert_file: /etc/kubernetes/cluster16/ssl/admin.pem
      key_file: /etc/kubernetes/cluster16/ssl/admin-key.pem
      insecure_skip_verify: true
    follow_redirects: true
    enable_http2: true
```

**Comment by Superbasil3** [comment]
Hello, I encountered the same issue, and I was able to go arroud by adding a step before the block you showed : 
# If __address__ is ipv6, update ipv6 adress with []
```yaml
  - source_labels: [__address__]
    regex: '([0-9a-fA-F:]+:[0-9a-fA-F:]+)'
    action: replace
    target_label: __address__
    replacement: '[$1]'
```

And then it the block you showed, I update the regex to add a block that matches a block with [] arround
```yaml
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+|\[[^\]]*\])(?::\d+)?;(\d+)
    replacement: $1:$2
```

I wasn't able to come with a satisfying regex that match ipv4, FQDN, ipv6 AND ipv6 with bracket.

Hopes this helps you anyway.

**Comment by beorn7** [comment]
Hello from the bug scrub!

We believe this just needs better regexps and is not a bug in Prometheus itself. See also https://github.com/prometheus/prometheus/issues/14641 . 
@krajorama will have a closer look to verify.

**Comment by krajorama** [comment]
I did play around with this  a little locally (outside k8s) and seems like @Superbasil3 's suggestion to have an additional regex before concatenating with the port number should work,
```yaml
      - source_labels: [__address__]
        target_label: __address__
        regex: '([0-9a-fA-F:]+:[0-9a-fA-F:]+)'
        replacement: '[$1]'
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        target_label: __address__
        regex: '([^;]+);(\d+)'
        replacement: '$1:$2'
```
Where the first replace adds the brackets if needed and the second adds the port if needed.
