### ISSUE TITLE
Prometheus targets show 1/0 for all targets

### ISSUE THREAD

**Issue by jsalatiel** [prometheus/prometheus#14686]
### What did you do?

I have installed kube-prometheus-stack using argocd and everything seems to be working just fine, except that in the prometheus targets ui, all targets show as 1/0.

All the rules are being evaluated just fine and the alerts are being trigerred as expected.

### What did you expect to see?

Targets should reflect the correct up/total_expected

### What did you see instead? Under which circumstances?

![image](https://github.com/user-attachments/assets/c4b6cd85-7649-49be-8e3f-47977da0ad0b)

### System information

x86_64

### Prometheus version

```text
Build Information
version	2.54.0
revision	5354e87a70d3eb26b81b601b286d66ff983990f6
branch	HEAD
buildUser	root@68a9e2472a68
buildDate	20240809-11:36:32
goVersion	go1.22.6
```

### Prometheus configuration file

```yaml
Branch:
HEAD
BuildDate:
20240228-11:51:20
BuildUser:
root@22cd11f671e9
GoVersion:
go1.21.7
Revision:
0aa3c2aad14cff039931923ab16b26b7481783b5
Version:
0.27.0
```

As mentioned,  rules appear being processed.
![image](https://github.com/user-attachments/assets/a557f886-759d-4a2b-88a3-ea199e9e019d)

Also the alerts seem to be triggering:
![image](https://github.com/user-attachments/assets/236c925f-5ceb-4a2b-84a6-cb6ec3f3e715)
