### ISSUE TITLE
Error opening React index.html: open web/ui/static/react/index.html: no such file or directory

### ISSUE THREAD

**Issue by gywndi** [prometheus/prometheus#14720]
### What did you do?

When I build and use prometheus, an "Error opening React index.html: open web/ui/static/react/index.html: no such file or directory" error appears.
This does not occur in pre-built versions. And the version I built is 130MB, and the pre-built version is 134MB, so there is a difference in capacity, as below.
```
## prometheus-2.54.0
-rwxrwxr-x  1 sdc sdc 130M  8월 23 16:42 prometheus

## prometheus-2.54.0 (pre-built)
-rwxr-xr-x 1 sdc sdc 134M  8월  9 20:38 prometheus
```

I built it with make build, as written in the README.
```
make build  
```

Are there any differences in options between the build method of the pre-built version and the way I build it?
This has never happened before. I don't know why. Is there a separate tag option when building?

### What did you expect to see?

.

### What did you see instead? Under which circumstances?

.

### System information

Linux 3.10.0-1160.95.1.el7.x86_64

### Prometheus version

```text
.
```

### Prometheus configuration file

```yaml
.
```

### Alertmanager version

```text
.
```

### Alertmanager configuration file

```yaml
.
```

### Logs

```text
.
```

**Comment by gywndi** [comment]
It seems that the ```builtinassets```  tag is not applied properly during make build.

This tag is defined in “.promu.yml” as follows, but it is not applied properly when I build with ```make build```.
```
build:
.. skip ..
    tags:
        all:
            - netgo 
            - builtinassets 
            - stringlabels 
```
Is there any way to make promu build with that tag option?

If I build as shown below, it's been built with a version that does not cause related issues.
```
go build -tags netgo,builtinassets,stringlabels ./cmd/prometheus 
go build -tags netgo,builtinassets,stringlabels ./cmd/promtool 
```

**Comment by gywndi** [comment]
I modified ```.promu.yml``` as follow, it works well.
Does promu recognize the tags item properly? Or is the promu version I'm using different?
```
#######################
## Before
#######################
build:
    tags:
        all:
            - netgo 
            - builtinassets 
            - stringlabels 

#######################
## After
#######################
    flags: -a -tags netgo,builtinassets,stringlabels
#    tags:
#        all:
#            - netgo 
#            - builtinassets 
#            - stringlabels 
```
