### ISSUE TITLE
Scrape with Prometheus operator result in random 503

### ISSUE THREAD

**Issue by CJsPod** [prometheus/prometheus#14869]
### What did you do?

We are using kube-prometheus-stack and have ServiceMonitor defined for various services. 

```yaml
Name:         pg-grafana-pg-metrics
Namespace:    user-grafana
Labels:       app.kubernetes.io/component=metrics
              app.kubernetes.io/name=pg-grafana-pg-metrics
Annotations:  argocd.argoproj.io/sync-wave: 15
              argocd.argoproj.io/tracking-id: user-grafana:monitoring.coreos.com/ServiceMonitor:user-grafana/pg-grafana-pg-metrics
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Spec:
  Endpoints:
    Path:    /metrics
    Port:    http-patroni
    Scheme:  http
  Selector:
    Match Labels:
      App:  pg-grafana-pg-metrics
---
Name:         pg-keycloak-db-pg-metrics
Namespace:    security
API Version:  monitoring.coreos.com/v1
Kind:         ServiceMonitor
Spec:
  Endpoints:
    Path:    /metrics
    Port:    http
    Scheme:  https
    Tls Config:
      Ca File:               /etc/prometheus/istio-certs/root-cert.pem
      Cert File:             /etc/prometheus/istio-certs/cert-chain.pem
      Insecure Skip Verify:  true
      Key File:              /etc/prometheus/istio-certs/key.pem
    enableHttp2:             false
    Path:                    /metrics
    Port:                    http-patroni
    Scheme:                  https
    Tls Config:
      Ca File:               /etc/prometheus/istio-certs/root-cert.pem
      Cert File:             /etc/prometheus/istio-certs/cert-chain.pem
      Insecure Skip Verify:  true
      Key File:              /etc/prometheus/istio-certs/key.pem
  Selector:
    Match Labels:
      App:  pg-keycloak-db-pg-metrics
```

### What did you expect to see?

Every time when we roll new nodes or when postgres pods are recreated, prometheus should be able to scrape the targets.

### What did you see instead? Under which circumstances?

Every time when we roll new nodes or when Postgres pods are recreated, we see 503 Error in Prometheus Target status for random Postgres pods. upon restart of Prometheus pods it gets fixed and we see healthy target status Postgres pods. Verified that all the targets details are correct, and services are working. Also, On doing curl to Postgres pod scrape endpoint from Prometheus pod I can see the metric, but the Prometheus target status still shows 503 until we restart Prometheus.

### Prometheus version

```text
prometheus, version 2.54.1
kube-prometheus-stack - 62.3.1
```
