### ISSUE TITLE
Nomad scraper (`nomad_sd_config`) ignores `tls_config` section

### ISSUE THREAD

**Issue by tomklosinski** [prometheus/prometheus#14964]
### What did you do?

I have a Nomad server running on https with self-signed certificate, and I've tried to scrape metrics from it using `nomad_sd_config`.

### What did you expect to see?

Working `nomad_sd_configs` with `tls_config`.

### What did you see instead? Under which circumstances?

No matter what I put into `tls_config` (whether it's the `ca:` with content, `ca_file:` with path, or `insecure_skip_verify: true`), it always gets ignored, and Prometheus prints following log message:
```
ts=2024-09-23T08:13:26.476Z caller=refresh.go:71 level=error component="discovery manager scrape" discovery=nomad config=nomad-service-discovery msg="Unable to refresh target groups" err="Get \"https://nomad.service.consul:4646/v1/services?namespace=default&region=global&stale=\": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

If I instead add the CA cert to the system trust store (`/etc/ssl/certs`), then I get following error:
```
ts=2024-09-23T09:33:14.168Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=nomad config=nomad-service-discovery msg="Unable to refresh target groups" err="Get \"https://nomad.service.consul:4646/v1/services?namespace=default&region=global&stale=\": remote error: tls: certificate required"
```

It now gets the CA cert but complains about missing client certificate. Which proves that Prometheus is basically ignoring `tis_config` section for `nomad_sd_configs`. 

Of course testing the connection with curl works fine.

### System information

Linux 6.5.0-1025-azure x86_64

### Prometheus version

```text
prometheus, version 2.54.1 (branch: HEAD, revision: e6cfa720fbe6280153fab13090a483dbd40bece3)
  build user:       root@812ffd741951
  build date:       20240827-10:56:41
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
- job_name: nomad-service-discovery
    nomad_sd_configs:
      - server: "https://nomad.service.consul:4646"
    scheme: "https"
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/client.crt
      key_file: /etc/prometheus/client.key
    relabel_configs:
      - source_labels: ['__meta_nomad_tags']
        regex: '.*,prometheus(.*?),.*'
        action: keep
      - source_labels: ['__meta_nomad_namespace']
        regex: '(.*)'
        target_label: 'nomad_namespace'
        replacement: '$1'
```

**Comment by tomklosinski** [comment]
PS. I've tested `v2.55.0-rc.0` and `v3.0.0-beta.0` - the same result.

**Comment by tomklosinski** [comment]
And of course testing the connection with `curl` works fine:
```
# curl --cacert ca.crt --key client.key --cert client.crt https://nomad.service.consul:4646/
<a href="/ui/">Temporary Redirect</a>.
```

**Comment by machine424** [comment]
I believe, `nomad_sd_configs` should be aligned with `job_name`.
the `tls_config` you're setting (the one that's aligned with `job_name`) is for the scraping phase.
You should set `tls_config` inside `nomad_sd_config` so the certs are used during the discovery phase.
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#nomad_sd_config

**Comment by tomklosinski** [comment]
So it should be added twice? Like this:

```
  - job_name: nomad-service-discovery
    nomad_sd_configs:
      - server: "https://nomad.service.consul:4646"
        tls_config:
          ca_file: /etc/prometheus/ca.crt
          cert_file: /etc/prometheus/client.crt
          key_file: /etc/prometheus/client.key
          insecure_skip_verify: true
    scheme: "https"
    tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/client.crt
      key_file: /etc/prometheus/client.key
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: ['__meta_nomad_tags']
        regex: '.*,prometheus(.*?),.*'
        action: keep
      - source_labels: ['__meta_nomad_namespace']
        regex: '(.*)'
        target_label: 'nomad_namespace'
        replacement: '$1'
```
