### ISSUE TITLE
Error on ingesting out-of-order samples in prometheus 2.54.0 and 2.54.1

### ISSUE THREAD

**Issue by Kejzin** [prometheus/prometheus#14973]
### What did you do?

Deployed a Prometheus using latest helm-chart (kube prometheus stack 62.7.0) with additional scrape config for cadvisor.

### What did you expect to see?

No Errors.

### What did you see instead? Under which circumstances?

"Error on ingesting out-of-order samples" Error is log messages from prometheus agent

Also, with scrape interval raised from 15s to 60s problems seem to be solved. I don't think that switching to 60s actually solves the problem, rather masking it. 

### System information

k8s 

### Prometheus version

```text
prometheus version 2.54.1
```

### Prometheus configuration file

```yaml
additional-scrape-config 

-  job_name: kubernetes-nodes-cadvisor
  kubernetes_sd_configs:
    - role: node
  relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - replacement: kubernetes.default.svc:443
      target_label: __address__
    - regex: (.+)
      replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      source_labels:
        - __meta_kubernetes_node_name
      target_label: __metrics_path__
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
{"caller":"scrape.go:1751","component":"scrape manager","level":"warn","msg":"Error on ingesting out-of-order samples","num_dropped":253,"scrape_pool":"kubernetes-nodes-cadvisor","target":"<target>","ts":"2024-09-24T15:04:19.353Z"}
```
