### ISSUE TITLE
Query UI breaks with web.external-url

### ISSUE THREAD

**Issue by smlx** [prometheus/prometheus#14995]
### What did you do?

Started Prometheus v3.0.0-beta.0 docker image with `--web.external-url=/prometheus/` behind a Caddy proxy.

### What did you expect to see?

I expected the Query UI to work just as it does in v2.

### What did you see instead? Under which circumstances?

A blank white screen in the browser. Inspecting the source of the page I saw references to paths without the `/prometheus/` prefix:
```html
    <title>Prometheus Time Series Collection and Processing Server</title>
    <script type="module" crossorigin src="/assets/index-28nLCCdU.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-DONe6kwV.css">
```

I also saw errors in the browser network tab due to failure to load those assets, which is not surprising since they don't have the `/prometheus` prefix.

Manually adding the prefix to those paths (e.g. `/prometheus/assets/index-DONe6kwV.css`) allowed me to see the CSS that the page was trying to load.

### System information

Linux 6.1.0-25-amd64 x86_64

### Prometheus version

```text
prometheus, version 3.0.0-beta.0 (branch: HEAD, revision: 91608c002f08039c7c0f5a3fbebaf2cf78c3b1f2)
  build user:       root@9c2eedf0b49d
  build date:       20240910-19:09:35
  go version:       go1.23.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
---
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  metrics_path: /prometheus/metrics
  static_configs:
  - targets:
    - prometheus:9090
```

### Logs

```text
I didn't see any logs for the failing web requests.
```
