### ISSUE TITLE
Namespaces filter not working

### ISSUE THREAD

**Issue by nar-git** [prometheus/prometheus#15028]
### What did you do?

We have a Prometheus server running in our EKS cluster with below scrape configuration. The namespace filter is not working and all namespace metrics are scraping

```
global:
  evaluation_interval: 1m
  scrape_interval: 30s
  scrape_timeout: 10s
  keep_dropped_targets: 1
scrape_configs:
- honor_labels: false
  job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names: ['amazon-cloudwatch',  'kube-system']
  relabel_configs:
  - action: replace
    source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
```

### What did you expect to see?

Prometheus scrape metrics of only amazon-cloudwatch and kube-system namespaces

### What did you see instead? Under which circumstances?

Namespaces filter not working, we see all namespaces metrics scraped and available in our servers.

### System information

Linux 5.10.224-212.876.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.54.1 (branch: HEAD, revision: e6cfa720fbe6280153fab13090a483dbd40bece3)
  build user:       root@812ffd741951
  build date:       20240827-10:56:41
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```
