### ISSUE TITLE
multitarget: Error on ingesting samples with different  value but same timestamp

### ISSUE THREAD

**Issue by JohnVillalovos** [prometheus/prometheus#15154]
### What did you do?

Setup prometheus to scrape using multi-target mode. Getting error about, "Error on ingesting samples with different value but same timestamp".

I'm confused because all the values appear to be different to me.

### What did you expect to see?

No error, scrape successful.

### What did you see instead? Under which circumstances?
```
ts=2024-10-12T21:22:26.629Z caller=scrape.go:1754 level=warn component="scrape manager"
scrape_pool=shelly target="http://example.com:9264/shelly?target=shelly-ppu-01.example.com"
msg="Error on ingesting samples with different value but same timestamp" num_dropped=3
```

**msg="Error on ingesting samples with different value but same timestamp"**

### Prometheus version

```text
prometheus, version 2.54.1 (branch: HEAD, revision: e6cfa720fbe6280153fab13090a483dbd40bece3)
  build user:       root@812ffd741951
  build date:       20240827-10:56:41
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: shelly
    static_configs:
      - targets:
          - shelly-ppu-01.example.com
    metrics_path: /shelly
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: example.com:9264  # The Shelly exporter's real hostname:port.
```

### Logs

```text
$ curl 'http://example.com:9264/shelly?target=shelly-ppu-01.example.com'
# HELP shelly_voltage Last measured voltage in Volts
shelly_voltage 118.0
# HELP shelly_watts Last measured instantaneous active power (in Watts) delivered to the attached load
shelly_watts 1.9
# HELP shelly_current Last measured current in Amperes
shelly_current 0.062
# HELP shelly_output Switch is on (True) or off (False)
shelly_output True
# HELP shelly_src Switch source identifier
shelly_src shellyplugus-xxxxxxx
# HELP shelly_temperature_c Switch temperature in celsius
shelly_temperature_c 47.7
# HELP shelly_id Id of the Switch component instance
shelly_id 1
```
