### ISSUE TITLE
Kube-state-metrics data collected by prometheus outside the cluster was discarded

### ISSUE THREAD

**Issue by gssjl2008** [prometheus/prometheus#15152]
### What did you do?

Due to some historical reasons, my prometheus is deployed outside the k8s cluster. I have multiple k8s clusters, and each cluster deploys kube-state-metrics. I use static_configs to collect metric data from different clusters. The configuration is as follows。

**This issue was not triggered when I used version 2.44**

### What did you see instead? Under which circumstances?

What can prometheus configure to optimize this problem

### Prometheus version

```text
❯ ./prometheus --version
prometheus, version 2.52.0 (branch: HEAD, revision: 879d80922a227c37df502e7315fad8ceb10a986d)
  build user:       root@1b4f4c206e41
  build date:       20240508-21:56:43
  go version:       go1.22.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
- job_name: global-kube-state-metrics
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
    - targets:
      - 10.29.14.212:30897
      labels:
        cluster: global

another one，
```yaml
scrape_configs:
- job_name: k8s-18-86-kube-state-metrics
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  enable_http2: true
  static_configs:
    - targets:
      - 10.29.18.87:31770
      labels:
        cluster: k8s-18-86
```
I add a label cluster to each cluster to distinguish,
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

```text
But my prometheus will discard some data,like this， 

ts=2024-10-11T03:14:31.016Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=global-kube-state-metrics target=http://10.29.14.212:30897/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
ts=2024-10-11T03:15:01.015Z caller=scrape.go:1738 level=warn component="scrape manager" scrape_pool=global-kube-state-metrics target=http://10.29.14.212:30897/metrics msg="Error on ingesting samples with different value but same timestamp" num_dropped=1
```
