### ISSUE TITLE
metric relabeling won't work if the target label is  __name__ 

### ISSUE THREAD

**Issue by mostafashr** [prometheus/prometheus#15155]
### What did you do?

I have a scrape job :
```- job_name: "sql_exporter"
    scrape_interval: 1m
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:9237"]
        labels:
          instance: "sql_exporter"
    metric_relabel_configs:
      - action: replace
        source_labels: [col]
        target_label: __name__
        replacement: "${1}"
        separator: ""
        # regex: "(.*)"```














### What did you expect to see?

the promehtous server should put metric name "col" to __name__ and output the result but it completely remove the metrics.

### What did you see instead? Under which circumstances?

metric is completely removed and won't save . if i change the replacement to simple string like "test" metric name become testand also if i change the target to any other lable other than __name__ it will work but __name__  won't work and metric won't get stored at all

### System information

Linux 5.15.0-105-generic x86_64

### Prometheus version

```text
prometheus, version 2.54.1 (branch: HEAD, revision: e6cfa720fbe6280153fab13090a483dbd40bece3)
  build user:       root@812ffd741951
  build date:       20240827-10:56:41
  go version:       go1.22.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
inside docker
```

### Prometheus configuration file

```yaml
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  scrape_timeout: 60s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "docker-host-alpha"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  - "recording_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "sql_exporter"
    scrape_interval: 1m
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:9237"]
        labels:
          instance: "sql_exporter"
    metric_relabel_configs:
      - action: replace
        source_labels: [col]
        target_label: __name__
        replacement: "${1}"
        separator: ""
        # regex: "(.*)"
```

### Alertmanager version

```text
not used
```

### Alertmanager configuration file

```yaml
not used
```

### Logs

```text
no error log or anything related
```
