### ISSUE TITLE
Alert Firing State not persisted at restart

### ISSUE THREAD

**Issue by euniceek** [prometheus/prometheus#15175]
## Steps to reproduce
- Create a rule group namespace with the following content:
```
groups:
- interval: 30s
  name: test
  rules:
  - expr: vector(1) > 0
    record: recording_rule_test
  - alert: alerting_rule_test
    expr: recording_rule_test > 300
    for: 300s
```
- Restart the ruler containing this rule group when the alert is in firing state.

## Manual Testing Result
1. We have an alert `alerting_rule_test` that is always firing.  
2. Restarted ruler 3 times at ~`12:34`, `13:11`, `13:41`.
3. The firing alert goes back to pending for 5 minutes each time. (`for` set to 5 min) 

![image](https://github.com/user-attachments/assets/319b7151-378b-45fd-babe-99b66d1cfc67)

## Testing in code
I added a [unit test here](https://github.com/euniceek/prometheus/commit/d25a6cf86110f31bb8f95ba3cd1aefadc613e73c) that mimics this. 
1. Set alerts to firing state
2. Simulate ruler restart and restore state
3. Assert alert rules are back in pending state instead of firing
    a. `firing alert should still be in firing state after restart` Fails
    b. `SHOULDN'T PASS: firing alert should be in pending state after restart` Passes
 

### What did you expect to see?

I expect the alert to stay in `firing` state regardless of restarts. 
It will be good to persist the firing state at restart as there are cases where customers expect firing state for long periods of time

### What did you see instead? Under which circumstances?

Currently if a ruler has an alerting rule in `firing` state and then Prometheus restarts, the alert will return to the pending state. We lose the state for firing alerts and have to wait for the pending period again.
