### ISSUE TITLE
http_sd_configs if label containing hyphen, prometheus can't refresh config

### ISSUE THREAD

**Issue by cylonchau** [prometheus/prometheus#15174]
### What did you do?

I use http_sd_configs to management some targets, but access some metrics need pass contain "-" http param, if the HTTP API return labels contain __param_xxx-xxx, then prometheus unable to refresh target groups.

The HTTP API return data format:

```json
[{
    "targets": [
      "www.text.com:443"
    ],
    "labels": {
      "__metrics_path__": "/ph/v1/proxy",
      "__param_bearer": "daskjdlasjdlasjdlasjdlasjdlaDDDDDDDDDDDDDDDDDDDDDDSDjlkjdlskfjlsdfjldsjfkldsf.fdslfjldsfjlkdsjfjdsklfjdsjfldsfjkdsjflkdsjfkldsklfdslfjdskjflkdsfkldsfkldslkf.12312lshfsfygufjhglkj1p2uiolkhgjkdfhgdfhgjkdfgjkdfhghdfjkfjgk",

# if param contain "-", err="\"__param_ignore-tls\" is not a valid label name"

      "__param_host": "10.1.12.112",
      "__param_ignore-tls": "yes",
      "__param_module": "tcp",
      "__param_path": "/metrics",
      "__param_port": "443",
      "__param_schema": "https",
      "__scheme__": "https",
      "__scrape_interval__": "30s",
      "__scrape_timeout__": "10s",
      "app": "mob",
      "instance": "10.1.12.112"
    }
  },
  {
    "targets": [
      "www.text.com:443"
    ],
    "labels": {
      "__metrics_path__": "/metrics",
      "__param_module": "http",
      "__param_target": "10.0.0.1",
      "__scheme__": "http",
      "__scrape_interval__": "30s",
      "__scrape_timeout__": "10s",
      "adas": "sdf12",
      "dad": "dgfgdfg",
      "gfdg": "gdfg",
      "instance": "10.0.0.1"
    }
  },
  {
    "targets": [
      "localhost:9200"
    ],
    "labels": {
      "__metrics_path__": "/metrics",
      "__param_module": "tcp",
      "__param_target": "10.0.0.1",
      "__scheme__": "http",
      "__scrape_interval__": "30s",
      "__scrape_timeout__": "10s",
      "adas": "sdf12",
      "dad": "dgfgdfg",
      "gfdg": "gdfg",
      "instance": "10.0.0.1"
    }
  },
  {
    "targets": [
      "localhost:9200"
    ],
    "labels": {
      "__metrics_path__": "/metrics",
      # "_" is passed
      "__param_igonor_tls": "yes",
      "__param_module": "tcp",
      "__param_target": "10.0.0.1",
      "__scheme__": "http",
      "__scrape_interval__": "30s",
      "__scrape_timeout__": "10s",
      "adas": "sdf12",
      "dad": "dgfgdfg",
      "gfdg": "gdfg",
      "instance": "10.0.0.1"
    }
  }
]
```

### What did you see instead? Under which circumstances?

To access some metrics pass the parameter need is "-" param, like following config. this config source from https://github.com/rokett/Citrix-NetScaler-Exporter

```yaml
scrape_configs:
  - job_name: 'netscaler'
    metrics_path: /netscaler
    static_configs:
      - targets:
        - 'https://netscaler.domain.tld'
        - 'https://netscaler-2.domain.tld'
    params:
      ignore-cert: ["yes"] # Generally this option should not be used.  Only use it if you truly trust the endpoint and know it is secure.  You may need a different job block for where you want to ignore certs.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9280  # The exporter's real hostname:port.
```

But "-" param is can worked at static job, can't work http_sd_configs 

### System information

Debian11,12; Redhat 7

### Prometheus version

```text
Any prometheus 2.x, I have tried prometheus 2.28.0, 2.44.0, 2.54.1; 2.54.1 is latest stable version.
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 100s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 5s
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'prometheus1'
    http_sd_configs:
    - url: 'http://10.0.0.1:8899/app/dc123'
      refresh_interval: 30s
```

### Logs

```text
ts=2024-09-29T19:56:55.225Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:57:25.219Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:57:55.223Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:58:25.225Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:58:55.219Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:59:25.233Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T19:59:55.236Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:00:25.219Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:00:55.228Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:01:25.229Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:01:55.225Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:02:25.221Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:02:55.231Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:03:25.229Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
ts=2024-09-29T20:03:55.222Z caller=refresh.go:90 level=error component="discovery manager scrape" discovery=http config=prometheus1 msg="Unable to refresh target groups" err="\"__param_ignore-tls\" is not a valid label name"
```
