### ISSUE TITLE
Not showing "goyacc not installed so skipping"  when goyacc is not installed in pc

### ISSUE THREAD

**Issue by farhan294sha** [prometheus/prometheus#15189]
### What did you do?

when I try to test with makefile i run the command "make test"
![image](https://github.com/user-attachments/assets/7dc942f8-fc02-4d0f-bda0-39d5c0053d3f)

it try to access the goyacc even its not installed in my pc 

![image](https://github.com/user-attachments/assets/d29b874d-54ef-4cb8-ad98-a1f7a18056c6)

it has added if block to cheak the goyacc is installed or not

### What did you expect to see?

"goyacc not installed so skipping"

To install: \"go install golang.org/x/tools/cmd/goyacc@$(GOYACC_VERSION)\" or run \"make install-goyacc\""

### What did you see instead? Under which circumstances?

![image](https://github.com/user-attachments/assets/3e398b90-9403-45d2-9b60-a65f4a60dfb3)

### System information

Linux 5.15.153.1-microsoft-standard-WSL2 x86_64

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
```
