### ISSUE TITLE
TLS config not respected for kubernetes_sd_config targets

### ISSUE THREAD

**Issue by rossigee** [prometheus/prometheus#15204]
### What did you do?

I have three K8S clusters which I am trying to gather metrics for using a single Prometheus instance.

Apparently, it should be possible to use the ['kubernetes_sd_config'](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) to specify TLS settings per target, so I mounted the TLS certs/creds for each cluster into the pod and defined a scrape rule in the config like this...

```yaml
        - job_name: 'kubernetes-apiservers'
          kubernetes_sd_configs:
          - role: endpoints
            api_server: https://k8s-api.alpha.lan:6443
            authorization:
              credentials_file: /tls-alpha/token
            tls_config:
              ca_file: /tls-alpha/ca.crt
          - role: endpoints
            api_server: https://k8s-api.bravo.lan:6443
            authorization:
              credentials_file: /tls-bravo/token
            tls_config:
              ca_file: /tls-bravo/ca.crt
          - role: endpoints
            api_server: https://k8s-api.charlie.lan:6443
            authorization:
              credentials_file: /tls-charlie/token
            tls_config:
              ca_file: /tls-charlie/ca.crt
          scheme: https
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

```

### What did you expect to see?

I am expecting to see metrics from each of the three clusters being ingested.

### What did you see instead? Under which circumstances?

I get a TLS error for all three endpoints...

```
Get "https://10.188.0.11:6443/metrics": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

However, if I copy one of the `tls_config` and `authorization` sections from one of the targets up alongside the `scheme: https` line (so it applies to all targets), then the endpoint for which the certificate is correct then goes green (metrics collected successfully). But the other two are still failing.

So, it appears that the `tls_config` and `authorization` sections, when added to the individual 'sd_config' targets, are not being respected.

P.S. I know I could just create separate jobs per cluster, but that's not what I'm talking about here. This is either a bug (it would seem to me), or I'm trying to do something this mechanism wasn't intended to support, in which case the documentation needs some clarification to avoid other people assuming it could/should be done this way too.

### System information

Kubernetes 1.13.1 (vanilla)

### Prometheus version

```text
quay.io/prometheus/prometheus:v2.55.0
```
