### ISSUE TITLE
Memory leak with simple instance prometheus-0.17.0.linux-amd64

### ISSUE THREAD

**Issue by hvnsweeting** [prometheus/prometheus#1526]
I'm running a single instance of prometheus-0.17.0.linux-amd64, with below config:

```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    target_groups:
      - targets: ['localhost:9090']
  - job_name: 'prometheus_system'
    scrape_interval: 5s
    target_groups:
      - targets: ['localhost:9100']
rule_files:
  - 'alert.rules'
```

rules:
```
# cat alert.rules
ALERT memfree_alert_hvn
IF node_memory_MemFree > 10000000

ALERT free_disk
IF (node_filesystem_avail{mountpoint="/", device="/dev/disk/by-label/DOROOT"} / node_filesystem_size * 100) < 20
```

I ran it with this command:

```
./prometheus -config.file=config.yml -alertmanager.url=http://localhost:9093
```
This is graph that show the process leaked memory

<img width="1412" alt="prom_memleak" src="https://cloud.githubusercontent.com/assets/1000665/14276330/750f3750-fb48-11e5-994f-ddc7c8976968.png">
