### ISSUE TITLE
dockerswarm_sd_configs - is it possible to remove targets that no longer satisfy filtering rules? 

### ISSUE THREAD

**Issue by francescor** [prometheus/prometheus#15324]
### What did you do?

I have a dockerswarm_sd_configs set keep only targets with `__meta_dockerswarm_task_desired_state` set to `running`, and it works fine, but when I surf the prometheus GUI I see 
![image](https://github.com/user-attachments/assets/dbff16a6-b45c-4adf-aa84-3c61dda054ef)

and the presence of those 33.200 targets (no longer running, but in shutdown) generate a lot of noise (the service discovery web page is 240Megabytes!)

### What did you see instead? Under which circumstances?

I would like a way to remove that noise

### System information

docker swarm with Ubuntu 22.04.4 LTS nodes

### Prometheus version

```text
image: quay.io/prometheus/prometheus:v2.32.1
```

### Prometheus configuration file

```yaml
- job_name: 'docker_tasks'
    dockerswarm_sd_configs:
      - host: http://dockersocket.backplane:2375
        role: tasks
    relabel_configs:
      #
      # Make sure that the running state filter is applied first. This is crucial because Prometheus processes relabel_configs sequentially.
      #
      # Only keep containers that should be running.
      # filtering out any stopped or inactive tasks.
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus.enable` label.
      - source_labels: [__meta_dockerswarm_service_label_prometheus_enable]
        regex: true
        action: keep
      # Use the swarm service name as Prometheus job label.
      - source_labels: [__meta_dockerswarm_service_name]
        target_label: job
      # constructs the instance label by combining the service name and the task slot, which helps in identifying individual tasks within a service.
      - source_labels: [__meta_dockerswarm_service_name, __meta_dockerswarm_task_slot]
        regex: "([^;]+);(.*)"
        replacement: $1.$2
        target_label: instance
      # Scraping metrics via a certain network only
      - source_labels: [__meta_dockerswarm_network_name]
        regex: backplane.*
        action: keep
      # Adding a docker_node label to the targets
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: docker_node
      # modifies the target address for scraping by replacing the default address with the service's specified Prometheus
      # port, ensuring that Prometheus scrapes metrics from the correct endpoint
      - source_labels: [__address__, __meta_dockerswarm_service_label_prometheus_port]
        regex: "([^:]+):[^;]+;(.*)"
        replacement: $1:$2
        target_label: __address__
```
```


### Alertmanager version

_No response_

### Alertmanager configuration file

_No response_

### Logs

_No response_
