### ISSUE TITLE
Relabel config with __param containing dot can not be matched

### ISSUE THREAD

**Issue by basos9** [prometheus/prometheus#15370]
### What did you do?

have a relabel config like
```
scrape_configs:
 -  job: "job1"
    metrics_path: /some/endpoint
    params:
      "a.dotty.par":
        - something

    relabel_configs:

      - source_labels: ["__param.a.dotty.par"]
        regex: something
        target_label: app
        replacement: "coolapp"
```

### What did you expect to see?

A target label `app=coolapp`

### What did you see instead? Under which circumstances?

An error 
```
caller=main.go:482 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: yaml: line 125: found unknown escape character"
```

NOTE: This could be easily supported without adding support for dot character in labels if the __param namespace transliterates dots and other non label characters to _ (underscores). So in this example the __param would be 
```
      - source_labels: ["__param_a_dotty_par"]
        regex: something
```

Meanwhile a **hacky** approach is to define a temp label without dots. But this seems really **awkward**.
```
      - action: labelmap
        regex: "__param_(([^.]+)\\.?)+"
        replacement: "__tmp_parm_${2}"
      - source_labels: ["__tmp_parm_par"]
        regex: something
        target_label: app
        replacement: coolapp
```

### System information

2.45.0, Docker prometheus `FROM prom/prometheus:latest` 

### Prometheus version

```text
prometheus-staging-1  | ts=2024-11-11T10:05:53.174Z caller=main.go:578 level=info msg="Starting Prometheus Server" mode=server version="(version=2.45.0, branch=HEAD, revision=8ef767e396bf8445f009f945b0162fd71827f445)"
```

**Comment by basos9** [comment]
Yes in 3.0.0-rc.1 it accepts  the config
```
   relabel_configs:

      - source_labels: ["__param.a.dotty.par"]
        regex: something
        target_label: app
        replacement: "coolapp"

```
