### ISSUE TITLE
Issue with using Prometheus as OpenTelemetry Trace Exporter Backend

### ISSUE THREAD

**Issue by Jatinzorro** [prometheus/prometheus#15418]
### What did you do?

I'm trying to use Prometheus as the backend for OpenTelemetry traces, but I am encountering issues. I'm using the OpenTelemetry Java Agent and configured it to export traces via OTLP, however, I'm unable to see any traces or metrics in Prometheus.

The configuration works as expected when sending traces to Grafana Tempo or Jaeger, but Prometheus is not showing any data. There are no visible errors in the OpenTelemetry Java Agent logs, so I'm unsure what the issue might be.

OpenTelemetry Instrumentation for java Configuration:

```
java -javaagent=opentelemetry-javaagent.jar \
-Dotel.traces.exporter=otlp \
-Dotel.resource.attributes=service.name=test \
-Dotel.javaagent.debug=true \
-Dotel.exporter.otlp.endpoint=10.x.x.x:9090/api/v1/otlp/v1/metrics \
-Dotel.logs.exporter=none \
-Dotel.metrics.exporter=none \
-Dotel.exporter.otlp.protocol=http/protobuf

```

Issue:

- I don't see any metrics or traces in Prometheus, even though the setup works fine with other backends like Grafana Tempo and Jaeger.
- There are no issues or errors appearing in the OpenTelemetry Java Agent logs.
- Prometheus is not showing any data when I query for traces or metrics.

### What did you see instead? Under which circumstances?

Could you please guide me on the next steps to observe traces in Prometheus? I’ve followed the documentation, but still can’t see any data. Am I overlooking something in my configuration? Are there any additional settings or steps that I should apply to enable trace/metric ingestion into Prometheus?

### System information

Linux 6.8.0-1018-aws x86_64

### Prometheus version

```text
prometheus, version 3.0.0 (branch: HEAD, revision: c5d009d57fcccb7247e1191a0b10d74b06295388)  build user:       root@aa286d0eb00a
  build date:       20241114-16:40:43  go version:       go1.23.3
  platform:         linux/amd64  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
otlp:
  translation_strategy: NoUTF8EscapingWithSuffixes
  # Recommended attributes to be promoted to labels
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name

storage:
  tsdb:
    out_of_order_time_window: 30m
```
