### ISSUE TITLE
Prometheus 3.0.0 OOMing after WAL replay

### ISSUE THREAD

**Issue by cxdy** [prometheus/prometheus#15433]
### What did you do?

Initially, I thought this was an issue on my end, because I mistakenly upgraded from Prometheus v2.54.1 to Prometheus 3.0.0 (skipping Prometheus 2.55.0, [which was called out in the migration guide](https://prometheus.io/docs/prometheus/3.0/migration/#tsdb-format-and-downgrade)).

Going off of that thought, I decided to do the following:
- Delete my existing TSDB (dev env, don't care)
- Uninstall Prometheus v3.0.0
- Install Prometheus v2.54.1
- Update to Prometheus v2.55.1
- Update to Prometheus v3.0.0

Unfortunately, the behavior persisted, so it can't have been the breaking TSDB change.

After all of that, I started running `pprof` against the heap, and found that `slog` was using a large amount of memory.

pprof for Prometheus v3.0.0:
```console
~# go tool pprof -top http://localhost:9090/prometheus/prometheus/debug/pprof/heap | head -n 20
Fetching profile over HTTP from http://localhost:9090/prometheus/prometheus/debug/pprof/heap
Saved profile in /root/pprof/pprof.prometheus.alloc_objects.alloc_space.inuse_objects.inuse_space.1063.pb.gz
File: prometheus
Type: inuse_space
Time: Nov 21, 2024 at 12:22am (UTC)
Showing nodes accounting for 25187.56MB, 97.01% of 25963.43MB total
Dropped 601 nodes (cum <= 129.82MB)
      flat  flat%   sum%        cum   cum%
13262.16MB 51.08% 51.08% 13262.16MB 51.08%  log/slog/internal/buffer.(*Buffer).WriteString (inline)
 8913.35MB 34.33% 85.41%  8913.35MB 34.33%  log/slog/internal/buffer.(*Buffer).Write (inline)
 1339.76MB  5.16% 90.57%  1339.76MB  5.16%  github.com/prometheus/prometheus/model/labels.(*Builder).Labels
  425.86MB  1.64% 92.21%  1716.61MB  6.61%  github.com/prometheus/prometheus/storage/remote.(*QueueManager).StoreSeries
  340.18MB  1.31% 93.52%   340.18MB  1.31%  github.com/prometheus/prometheus/tsdb/index.(*MemPostings).Delete.func1 (inlin
e)
  296.58MB  1.14% 94.66%   296.58MB  1.14%  github.com/klauspost/compress/flate.(*dictDecoder).init (inline)
  221.89MB  0.85% 95.52%   221.89MB  0.85%  github.com/prometheus/prometheus/tsdb.(*seriesHashmap).set
  172.58MB  0.66% 96.18%   459.49MB  1.77%  github.com/prometheus/prometheus/tsdb.(*stripeSeries).getOrSet
  169.53MB  0.65% 96.84%   509.70MB  1.96%  github.com/prometheus/prometheus/tsdb.(*Head).gc
   31.57MB  0.12% 96.96%   328.15MB  1.26%  github.com/klauspost/compress/flate.NewReaderOpts
    7.60MB 0.029% 96.99% 22321.83MB 85.97%  github.com/prometheus/prometheus/rules.(*Group).Eval.func1
    4.50MB 0.017% 97.00%   332.65MB  1.28%  github.com/klauspost/compress/gzip.NewReader (inline)
    1.50MB 0.0058% 97.01%   712.55MB  2.74%  github.com/prometheus/prometheus/scrape.(*scrapeLoop).run
    0.50MB 0.0019% 97.01%  6056.14MB 23.33%  github.com/prometheus/prometheus/rules.(*AlertingRule).Eval
```

pprof for Prometheus v2.54.1
```console
~# go tool pprof -top http://localhost:9090/prometheus/prometheus/debug/pprof/heap | head -n 20
Fetching profile over HTTP from http://localhost:9090/prometheus/prometheus/debug/pprof/heap
Saved profile in /root/pprof/pprof.prometheus.alloc_objects.alloc_space.inuse_objects.inuse_space.002.pb.gz
File: prometheus
Type: inuse_space
Time: Nov 21, 2024 at 12:23am (UTC)
Showing nodes accounting for 9960.11MB, 95.07% of 10477.14MB total
Dropped 558 nodes (cum <= 52.39MB)
      flat  flat%   sum%        cum   cum%
 1800.33MB 17.18% 17.18%  1800.33MB 17.18%  github.com/prometheus/prometheus/model/labels.(*Builder).Labels
  869.15MB  8.30% 25.48%  1032.15MB  9.85%  github.com/prometheus/prometheus/tsdb.newMemSeries (inline)
  772.45MB  7.37% 32.85%   815.20MB  7.78%  github.com/prometheus/prometheus/tsdb.(*headAppender).Append
     768MB  7.33% 40.18%      768MB  7.33%  github.com/klauspost/compress/zstd.(*fastBase).ensureHist (inline)
  750.62MB  7.16% 47.35%   750.62MB  7.16%  github.com/prometheus/prometheus/model/labels.(*ScratchBuilder).Labels
  702.07MB  6.70% 54.05%   702.07MB  6.70%  github.com/prometheus/prometheus/tsdb/chunkenc.NewXORChunk (inline)
  695.47MB  6.64% 60.69%   695.47MB  6.64%  github.com/prometheus/prometheus/scrape.(*scrapeCache).addRef (inline)
  410.46MB  3.92% 64.60%   410.46MB  3.92%  github.com/prometheus/prometheus/scrape.(*scrapeCache).trackStaleness (inline)
  380.95MB  3.64% 68.24%  1371.14MB 13.09%  github.com/prometheus/prometheus/storage/remote.(*QueueManager).StoreSeries
  339.90MB  3.24% 71.48%   339.90MB  3.24%  github.com/klauspost/compress/flate.(*dictDecoder).init (inline)
  287.01MB  2.74% 74.22%   292.53MB  2.79%  github.com/prometheus/prometheus/tsdb.(*memSeries).mmapChunks
  265.73MB  2.54% 76.76%   265.73MB  2.54%  github.com/prometheus/prometheus/tsdb/index.(*MemPostings).Delete.func1 (inline)
  240.51MB  2.30% 79.05%  1181.59MB 11.28%  github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk
  239.01MB  2.28% 81.34%   239.01MB  2.28%  github.com/prometheus/prometheus/tsdb/chunkenc.(*XORChunk).Appender
```

As you can see, `slog` is using a significant amount of memory comparatively. Both of these Prometheus instances are exactly the same, except for the version. Same scrape targets, same scrape jobs, same recording and alerting rules being evaluated.

### What did you see instead? Under which circumstances?

After the WAL replayed, I had roughly 10 to 15 minutes before the prometheus process would be oom killed. Additionally, I noticed that `/var/lib/prometheus/prometheus_query.log` was growing at exponential rates (1GB per 2s - using `watch`). The highest I saw it was 1.1TB, which is obviously quite concerning. When testing earlier in the week when I skipped v2.55.1, I noticed the same behavior. 

### System information

Linux 5.10.0-33-amd64 x86_64

### Prometheus version

```text
prometheus, version 3.0.0 (branch: HEAD, revision: c5d009d57fcccb7247e1191a0b10d74b06295388)
  build user:       root@aa286d0eb00a
  build date:       20241114-16:40:43
  go version:       go1.23.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
alerting:
  alertmanagers:
  - path_prefix: /prometheus/alertmanager
    scheme: https
    static_configs:
    - targets:
      - $REDACTED:9999
global:
  external_labels:
    datacenter: $REDACTED
    domain: $REDACTED
    replica: prometheus
  query_log_file: /var/lib/prometheus/prometheus_query.log
  scrape_interval: 30s
remote_write:
- queue_config:
    batch_send_deadline: 5s
    capacity: 5000
    max_samples_per_send: 1000
    max_shards: 2000
  tls_config:
    cert_file: /etc/prometheus/$REDACTED.crt
    key_file: /etc/prometheus/$REDACTED.key
  url: $REDACTED
  write_relabel_configs:
  - action: labeldrop
    regex: replica
rule_files:
- /etc/prometheus/rules/infra/common/*.yaml
- /etc/prometheus/rules/infra/datacenter/$REDACTED/*.yaml
scrape_config_files:
- /etc/prometheus/scrape_config_files/*.yaml
tracing:
  client_type: grpc
  endpoint: localhost:4317
  insecure: true
  sampling_fraction: 1.0
```
