### ISSUE TITLE
always_scrape_classic_histograms is not hot reloadable

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#15464]
### What did you do?

I prepared configuration like below and run Prometheus with flag `--enable-feature=native-histograms --web.enable-lifecycle`.

```
# my global config
global:
  scrape_interval: 5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    always_scrape_classic_histograms: false
    metric_relabel_configs:
    - action: keep
      source_labels: ['__name__']
      regex: (prometheus_http_request_duration_seconds_count)|(prometheus_http_request_duration_seconds_sum)
    static_configs:
      - targets: ["localhost:9090"]
```

With `always_scrape_classic_histograms` set to false, I expect I cannot store any metrics in TSDB as those metrics exist in classic histograms only.

Then I edited the `always_scrape_classic_histograms` config to `true` and used `curl -X POST localhost:9090/-/reload` to hot reload the config. 

### What did you expect to see?

`prometheus_http_request_duration_seconds_count` and `prometheus_http_request_duration_seconds_sum` should be able to be scraped and appear when I query using Prometheus UI.

### What did you see instead? Under which circumstances?

I am able to see `always_scrape_classic_histograms: true` picked up in the Prometheus UI configuration page. However, I didn't see `prometheus_http_request_duration_seconds_count` and `prometheus_http_request_duration_seconds_sum` actually getting scraped 

### Prometheus version

```text
Prometheus 3.0. I also tested Prometheus 2.52.0 and 2.55.0. Same issue
```
