### ISSUE TITLE
idelta is returning wrong results

### ISSUE THREAD

**Issue by felix021** [prometheus/prometheus#15481]
### What did you do?

Take `process_cpu_seconds_total{instance="localhost:9090", job="prometheus"}` as example:

Query for:
- `idelta(process_cpu_seconds_total{instance="localhost:9090",job="prometheus"}[10s])`
- `process_cpu_seconds_total{instance="localhost:9090", job="prometheus"} - process_cpu_seconds_total{instance="localhost:9090", job="prometheus"} offset 10s`

### What did you expect to see?

The two queries should return the same result

### What did you see instead? Under which circumstances?

idelta returned wrong results:

![image](https://github.com/user-attachments/assets/c5e73c71-18ea-40d9-a21f-c736dc5c8102)

### System information

Linux 5.4.119-19-0009.11 x86_64

### Prometheus version

```text
prometheus, version 2.41.0 (branch: HEAD, revision: c0d8a56c69014279464c0e15d8bfb0e153af0dab)
  build user:       root@d20a03e77067
  build date:       20221220-10:40:45
  go version:       go1.19.4
  platform:         linux/amd64
```

### Prometheus configuration file

```yaml
global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - /prometheus/rules/*.rules

# 采集配置
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'localhost:19001']
```
