### ISSUE TITLE
Dropped sample for series that was not explicitly dropped via relabelling

### ISSUE THREAD

**Issue by juliocleal14** [prometheus/prometheus#15574]
### What did you do?

I have around 20 different environments running the prometheus-agent as HA sharing the same prometheus configuration.

In only one of these environments we are receiving a log of errors `Dropped sample for series that was not explicitly dropped via relabelling`

When I see the metric `prometheus_remote_storage_samples_dropped_totalal` I only receive the reason `unintentionally_dropped_series`

Looking at [the code](https://github.com/prometheus/prometheus/blob/main/storage/remote/queue_manager.go#L696-L753) this happen in the Append function when the queue is being fulled

I'm not sure if this is a bug, but at least for me it is not clear why this reason happens (I cannot find any unit test this) 

### What did you expect to see?

I expect to see more clear what happens when I receive this reason in the dropped sample.

### What did you see instead? Under which circumstances?

I see nothing, any log, any error in the prometheus remote process.

### System information

Linux 5.10.228-219.884.amzn2.x86_64 x86_64

### Prometheus version

```text
prometheus, version 2.51.0 (branch: HEAD, revision: c05c15512acb675e3f6cd662a6727854e93fc024)
  build user:       root@b5723e458358
  build date:       20240319-10:54:45
  go version:       go1.22.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels:
    replica: "prometheus-agent-1"
    monitor: "prometheus"
    environment: "prod"
    stack_id: "green"
    label1: "value1"
    country: "br"
    aws_region: "aws_region"
    account: "br"

scrape_configs:

  - job_name: 'thanos-sidecar'
    metrics_path: /metrics
    static_configs:
      - targets:
        - localhost:10902
        labels:
          label1: value1
          kubernetes_pod_name: prometheus-agent-1

  - job_name: 'kafka'
    scrape_interval: 130s
    scrape_timeout: 120s
    metrics_path: /metrics
    ec2_sd_configs:
    - region: aws-region
      port: 5556
    relabel_configs:
      - source_labels: [__meta_ec2_tag_SERVICE]
        regex: kafka
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        regex: ^value1$
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        target_label: label1
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance
      - source_labels: [__meta_ec2_tag_ENV]
        target_label: environment
      - source_labels: [__meta_ec2_tag_STACK]
        target_label: stack_name
      - source_labels: [__meta_ec2_tag_SERVICE]
        target_label: service
      - source_labels: [__meta_ec2_tag_SQUAD]
        target_label: squad
      - source_labels: [__meta_ec2_tag_STACK_ID]
        target_label: stack_id

  - job_name: 'kafka-data'
    scrape_interval: 130s
    scrape_timeout: 120s
    metrics_path: /metrics
    ec2_sd_configs:
    - region: aws-region
      port: 5556
    relabel_configs:
      - source_labels: [__meta_ec2_tag_SERVICE]
        regex: kafka-data
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        regex: ^value1$
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        target_label: label1
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance
      - source_labels: [__meta_ec2_tag_ENV]
        target_label: environment
      - source_labels: [__meta_ec2_tag_STACK]
        target_label: stack_name
      - source_labels: [__meta_ec2_tag_SERVICE]
        target_label: service
      - source_labels: [__meta_ec2_tag_SQUAD]
        target_label: squad
      - source_labels: [__meta_ec2_tag_STACK_ID]
        target_label: stack_id

  - job_name: 'kafka-node-exporter'
    scrape_interval: 35s
    metrics_path: /metrics
    ec2_sd_configs:
    - region: aws-region
      port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_SERVICE]
        regex: kafka
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        regex: ^value1$
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        target_label: label1
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance
      - source_labels: [__meta_ec2_tag_ENV]
        target_label: environment
      - source_labels: [__meta_ec2_tag_STACK]
        target_label: stack_name
      - source_labels: [__meta_ec2_tag_SERVICE]
        target_label: service
      - source_labels: [__meta_ec2_tag_SQUAD]
        target_label: squad
      - source_labels: [__meta_ec2_tag_STACK_ID]
        target_label: stack_id
    metric_relabel_configs:
      - source_labels: [__name__]
        action: drop
        regex: ^go_.+$

  - job_name: 'kafka-data-node-exporter'
    scrape_interval: 35s
    metrics_path: /metrics
    ec2_sd_configs:
    - region: aws-region
      port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_SERVICE]
        regex: kafka-data
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        regex: ^value1$
        action: keep
      - source_labels: [__meta_ec2_tag_label1]
        target_label: label1
      - source_labels: [__meta_ec2_private_ip]
        target_label: instance
      - source_labels: [__meta_ec2_tag_ENV]
        target_label: environment
      - source_labels: [__meta_ec2_tag_STACK]
        target_label: stack_name
      - source_labels: [__meta_ec2_tag_SERVICE]
        target_label: service
      - source_labels: [__meta_ec2_tag_SQUAD]
        target_label: squad
      - source_labels: [__meta_ec2_tag_STACK_ID]
        target_label: stack_id

  - job_name: 'istio-sidecar'
    kubernetes_sd_configs:
    - role: pod
      selectors:
        - role: "pod"
          label: "sidecar.istio.io/inject=true"
    scheme: http
    metrics_path: "/stats/prometheus"
    honor_labels: true
    sample_limit: 600000
    relabel_configs:
    - source_labels: [__address__]
      action: replace
      regex: ([^:]+):(\d+)
      replacement: '${2}'
      target_label: __port__
    - source_labels: [__port__]
      regex: 15090
      action: keep
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_label_istio]
      regex: ".+"
      action: drop
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_label_name]
      action: replace
      target_label: service
    - source_labels: [__meta_kubernetes_pod_label_tier]
      action: replace
      target_label: tier
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_name
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)

  # Fetches istio ingress metrics
  - job_name: 'istio-ingress'
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_label_istio]
      action: replace
      target_label: istio
    - source_labels: [__meta_kubernetes_pod_label_app]
      action: replace
      target_label: service
    - source_labels: [__address__]
      target_label: tier
      replacement: "critical"
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_name
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    metric_relabel_configs:
    # Refactor Istio TLS Cipher from the label name to a label
    - source_labels: [__name__]
      regex: 'envoy_listener_ssl_ciphers_(.*)'
      target_label: cipher
      replacement: "${1}"
    - source_labels: [__name__]
      regex: 'envoy_listener_ssl_ciphers_(.*)'
      target_label: __name__
      replacement: 'envoy_listener_ssl_ciphers'
    - source_labels: [__name__, listener_address]
      regex: 'envoy_listener_ssl_ciphers;.+'
      target_label: listener_address
      replacement: ""
    # Refactor Istio TLS Version from the label name to a label
    - source_labels: [__name__]
      regex: 'envoy_listener_ssl_versions_(.*)'
      target_label: version
      replacement: "${1}"
    - source_labels: [__name__]
      regex: 'envoy_listener_ssl_versions_(.*)'
      target_label: __name__
      replacement: 'envoy_listener_ssl_versions'
    - source_labels: [__name__, listener_address]
      regex: 'envoy_listener_ssl_versions;.+'
      target_label: listener_address
      replacement: ""

  # Fetches istio control plane metrics
  - job_name: 'istiod'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istiod;http-monitoring
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_label_istio]
      action: replace
      target_label: service
    - source_labels: [__address__]
      target_label: tier
      replacement: "critical"
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_name
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)

  - job_name: 'kubernetes-pods-high-metrics'
    kubernetes_sd_configs:
    - role: pod
      selectors:
      - role: "pod"
        label: "service-name in (service1, service2, service3)"
    scheme: https
    honor_labels: true
    sample_limit: 1690000
    scrape_interval: 60s
    bearer_token_file: /var/run/secrets/prometheus/bearer_token
    tls_config:
      insecure_skip_verify:  true
      cert_file: /etc/prometheus/prometheus_cert.pem
      key_file: /etc/prometheus/prometheus_key.pem
    relabel_configs:
    - action: replace
      source_labels: [__address__]
      regex: .*
      replacement: value1
      target_label: label1
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_high_latency]
      regex: '.+'
      action: drop
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: ^(https?)$
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [__meta_kubernetes_namespace]
      action: drop
      regex: 'databases'
    - source_labels: [__meta_kubernetes_namespace]
      action: drop
      regex: 'kube-system'
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
    - source_labels: [__meta_kubernetes_pod_label_name]
      action: replace
      target_label: service
    - source_labels: [__meta_kubernetes_pod_label_tier]
      action: replace
      target_label: tier
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_name
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    metric_relabel_configs:

    - source_labels: [__name__,endpoint]
      action: replace
      target_label: endpoint
      regex: ^services_http_endpoint_logical_.+;(.+api\/render\/pay\/).+$
      replacement: $1

...


remote_write:
  - url: http://victoria-metrics-insert.namespace.svc.cluster.local:8480/insert/0/prometheus/api/v1/write
    queue_config:
      max_samples_per_send: 2000
      capacity: 10000

      max_shards: 30

      max_backoff: 3s
      retry_on_http_429: true
    write_relabel_configs:
      - regex: "(replica)"
        action: labeldrop
```
