### ISSUE TITLE
Use job and __param_<name> labels cause double instance in report

### ISSUE THREAD

**Issue by stimg** [prometheus/prometheus#1567]
v. 0.17.0
Using config like this 
```
[{
	"targets": ["192.168.0.2"],
	"labels": {
		"job": "my_job",
		"__param_module": "my_module",
	}
}]
```
in the targets file "my_job.json'" cause creation of two instances with the same parameters in the same job in the Prometheus metrics report. Workaround: delete `job` label.

**Comment by brian-brazil** [comment]
Can you share your `prometheus.yml`?

**Comment by stimg** [comment]
```
global:
   scrape_interval:     15s # By default, scrape targets every 15 seconds.
   evaluation_interval: 15s # By default, scrape targets every 15 seconds.

rule_files:
   - 'rules/*.rule'
   - 'rules/s3/*.rule'

scrape_configs:
...
  - job_name: 'dns_exporter_snmp'
    file_sd_configs:
    - names: ['/opt/prometheus/tgroups/snmp*_targets.json']
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*?)(:80)?
        target_label: __param_address
        replacement: ${1}
      - source_labels: [__param_address]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 10.200.18.51:9116  # SNMP exporter.
```
UPDATE: despite I delete `job` label, Prometheus creates two jobs for the target:
1. `job_name: dns_exporter_snmp` 
2. `job_name: my_job`
