### ISSUE TITLE
Prometheus not respecting Memory requests and limits. 

### ISSUE THREAD

**Issue by akshaysgithub** [prometheus/prometheus#15704]
### What did you do?

I installed Prometheus via Helm-chart. Disabled a lot of extra options like alert-manager, policy-reports, grafana, etc. I only want to run Prometheus for Kiali. I even created a Dedicated Node with 64GB memory and 8 cores. Unfortunately, Prometheus keeps making insane Memory requests, like 150GB, 200GB.... That's causing the pod to get OOMKIlled. 

Why is Prometheus requesting more memory than the limits already mentioned in helm-chart. If not, what's the point of adding limits overall. 

Helm-chart config deployed via Argo:
```
grafana:
  enabled: false
alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-pushgateway:
  enabled: false
additionalServiceMonitors: []
podSecurityPolicy:
  enabled: false
server:
  enabled: true
  service:
    servicePort: 9090
    targetPort: 9090
    name: prometheus
    retention: "12h"
  persistentVolume:
    enabled: true
    size: 20Gi
  resources:
    limits:
      memory: "60Gi"
    requests:
      memory: "46Gi"
  defaultFlagsOverride:
    - "--storage.tsdb.retention.time=12h"
    - "--config.file=/etc/config/prometheus.yml"
    - "--storage.tsdb.path=/data"
    - "--web.console.libraries=/etc/prometheus/console_libraries"
    - "--web.console.templates=/etc/prometheus/consoles"
    - "--web.enable-lifecycle"
  tolerations:
    - key: "prometheus-only"
      operator: "Equal"
      value: "present"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                  - prometheus-node-pool
  fullnameOverride: "prometheus"
  global:
    scrape_interval: 3m
    evaluation_interval: 3m
hostPort: null
```

### What did you see instead? Under which circumstances?

Pod getting OOMKIlled

### System information

Google GKE node

### Prometheus version

```text
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: istio-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: istio
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.27.0
      helm:
        releaseName: prometheus
```

### Alertmanager version

```text
Disabled
```

### Alertmanager configuration file

```yaml
Disabled
```

### Logs

```text
Nothing different here. Pod is getting killed by Kubelet due to memory requests.
```
