### ISSUE TITLE
Docker Swarm Service Discovery does not work with HTTP

### ISSUE THREAD

**Issue by BaseCrusher** [prometheus/prometheus#15727]
### What did you do?

Hello everyone

I was trying to use the Docker Swarm Service Discovery as documented [here](https://prometheus.io/docs/guides/dockerswarm/) and [here](https://github.com/prometheus/prometheus/blob/release-3.0/documentation/examples/prometheus-dockerswarm.yml).
Prometheus itself is running on the Swarm in a Container. According to the comments on the example configuration file, you can either use the UNIX socket or HTTP. Using the socket everything works, as long as the container has read rights on the socket. But when I try to use the HTTP endpoint instead, I get a 404 error.

I than shelled into the prometheus container performed a "wget host.docker.internal:9323/metrics" and i do get the metrics from the docker engine. So I strongly assume, that Prometheus is not accessing the correct path.

Here are my configuration files.
```
/etc/docker/deamon.json

{
  "metrics-addr": "0.0.0.0:9323",
  "experimental" : true
}
```

### What did you expect to see?

When using the HTTP endpoint, it should get the metrics.

### What did you see instead? Under which circumstances?

Error on fetching the metrics.

`level=ERROR source=refresh.go:90 msg="Unable to refresh target groups" component="discovery manager scrape" discovery=dockerswarm config=docker err="error while listing swarm nodes: Error response from daemon: 404 page not found"`

### System information

Docker Image: prom/prometheus:v3.0.1

### Prometheus version

```text
3.0.1
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Create a job for Docker daemons.
  - job_name: 'docker'
    dockerswarm_sd_configs:
      - host: "http://host.docker.internal" #unix:///var/run/docker.sock
        role: nodes
        port: 9323
    relabel_configs:
      # Fetch metrics on port 9323.
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      # Set hostname as instance label
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
```

### Alertmanager version

```text
-
```

### Alertmanager configuration file

```yaml
-
```

### Logs

```text
level=ERROR source=refresh.go:90 msg="Unable to refresh target groups" component="discovery manager scrape" discovery=dockerswarm config=docker err="error while listing swarm nodes: Error response from daemon: 404 page not found"
```
