### ISSUE TITLE
fallback_scrape_protocol should be configurable in globals

### ISSUE THREAD

**Issue by WojciechKuk** [prometheus/prometheus#15830]
### What did you do?

I added `fallback_scrape_protocol` config line in globals:
```
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  fallback_scrape_protocol: PrometheusText1.0.0
```

### What did you expect to see?

Should be possible to use `fallback_scrape_protocol` in globals (just like i.e. `scrape_interval`). Especially if you have a long-standing prometheus cluster with many different clients (different discovery types, different yaml generation tools), it's hard, to maintain it on every scrape job level.

### What did you see instead? Under which circumstances?

on Prometheus 3.0.1
```
global:
  evaluation_interval: 60s
  scrape_interval: 60s
  fallback_scrape_protocol: PrometheusText1.0.0
```
ends with error: `**field fallback_scrape_protocol not found in type config.plain**`

### Prometheus version

```text
prometheus, version 3.0.1 (branch: HEAD, revision: 1f56e8492c31a558ccea833027db4bd7f8b6d0e9)
  build user:       root@9c13055ffc3c
  build date:       20241128-17:20:55
  go version:       go1.23.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml

```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
