### ISSUE TITLE
Allow relative URL in web.external-url

### ISSUE THREAD

**Issue by malcolmr** [prometheus/prometheus#1583]
I'm serving Prometheus behind a reverse-proxy under a `/prometheus` path, so in 0.16, I'd set `web.external-url` to `/prometheus`.

0.18 complains about that:

```
ERRO[0000] invalid Prometheus URL: /prometheus           source=main.go:65
```

Is it intended that `web.external-url` must be an absolute URL? (As `/foo` is a valid path-absolute relative URL.)

The help reads: "The URL under which Prometheus is externally reachable (for example, if Prometheus is served via a reverse proxy). Used for generating relative and absolute links back to Prometheus itself. If the URL has a path portion, it will be used to prefix all HTTP endpoints served by Prometheus. **If omitted, relevant URL components will be derived automatically**."

It seems like either the validation is too strict, or that last sentence is (now) incorrect.

**Comment by grobie** [comment]
That field expects an absolute URL. The highlighted sentence means if that parameter is not set at all, a default will be chosen, which uses `/` as path.

Is it not an option to use `--web.external-url http://$(hostname):9090/prometheus`?

**Comment by chancez** [comment]
I'm running into this myself because I'm running prometheus in Kubernetes and attempting to access it locally via `kubectl proxy`, which in effect, opens up a proxy locally to access my service under `http://127.0.0.1:8001/api/v1/proxy/namespaces/default/services/prometheus/`. I'd rather not change the hostname since that messes with other stuff. Being able to avoid the redirect prometheus does for external-url would be nice as well. 

My main issue is that I need to be able to specify the prefix so this doesn't happen when I try to access it via chrome:
```
http://127.0.0.1:8001/static/js/graph_template.handlebar?_=1461656431100 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by malcolmr** [comment]
I have added the hostname (and implicitly port), and it works fine, though I do have to make sure to omit it when I'm running locally, which is a bit of a pain (because the port is different behind the proxy).

I guess this is perhaps a feature request to revert to the behaviour (unexpectedly?) permitted in 0.16.

**Comment by grobie** [comment]
I'm open for allowing relative URLs as well.

**Comment by aaskey** [comment]
Is this problem fixed? This actually effects Prometheus functionality when deployed under Kubernetes. When using kubectl as proxy, the following link http://localhost:8080/api/v1/proxy/namespaces/default/services/prometheus/graph has no query interface. Only the Add Graph button is shown.

**Comment by tylux** [comment]
@chancez I know this is old but did you figure out the issue of /graph not loading correctly with that 404 error?

**Comment by thenayr** [comment]
@tylux It won't.  

If you are accessing it through Kubernetes my best advice is to run `kubectl port-forward ....` to access the Prometheus web-ui through localhost,  or to setup a single static DNS entry that you access your Prometheus web-ui through.

**Comment by tylux** [comment]
this particular instance is not inside Kubernetes, it is a standalone Prometheus box that is being proxy_passed from a Nginx box 

been using the following snippet from https://github.com/prometheus/prometheus/issues/2193 and it mostly works other than that 404 on "static/js/graph_template.handlebar?_=1461656431100" resource on the /graphs page.

```
location /prometheus/ {
        proxy_set_header Accept-Encoding "";
        proxy_pass http://<real-prometheus-host>:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        sub_filter_types text/html;
        sub_filter_once off;
        sub_filter '="/' '="/prometheus/';
        sub_filter '="/static/' '="/static/prometheus/';
    }
```

**Comment by discordianfish** [comment]
Can we maybe be a bit smarter about figuring out the web root ourselves?
At least for path in the served HTML we should be able to read the requested path from request.URL, right? You still need to configure `-web.external-url` for links in alerts though. Not sure if it makes sense for that to support relative URLs.

**Comment by montanaflynn** [comment]
We are also trying to set up a portal to prometheus web UI from behind an nginx reverse proxy. 

Where do we set the config? I couldn't find any examples of setting these fields in the docs.

```
- "-web.external-url=..."
- "-web.route-prefix=/"
```

**Comment by linusguan** [comment]
@montanaflynn You set them as arguments when you run Prometheus, if you get it to work, do you mind sharing your settings?

**Comment by discordianfish** [comment]
I can't figure out how this is suppose to work either. I'm using the kubernetes api proxy and if I don't set external-url, it can't load the js files for /graph. If I set it to something (and break alternative ways to access this), that gets added additionally to the path prefix in the request. Unless I miss something, I believe external-url isn't doing what was intended.

I believe we could make this work for 90% of users without rewriting requests or flags in prometheus. From what I can tell, *something* in prometheus is already using the request path to figure out url prefixes. This is /graph snippet without external-url set:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Prometheus Time Series Collection and Processing Server</title>
    <link rel="shortcut icon" href="/api/v1/namespaces/default/services/prometheus/proxy/static/img/favicon.ico?v=3afb3fffa3a29c3de865e1172fb740442e9d0133">
    <script src="/api/v1/namespaces/default/services/prometheus/proxy/static/vendor/js/jquery.min.js?v=3afb3fffa3a29c3de865e1172fb740442e9d0133"></script>
    <script src="/api/v1/namespaces/default/services/prometheus/proxy/static/vendor/bootstrap-3.3.1/js/bootstrap.min.js?v=3afb3fffa3a29c3de865e1172fb740442e9d0133"></script>

    <link type="text/css" rel="stylesheet" href="/api/v1/namespaces/default/services/prometheus/proxy/static/vendor/bootstrap-3.3.1/css/bootstrap.min.css?v=3afb3fffa3a29c3de865e1172fb740442e9d0133">
    <link type="text/css" rel="stylesheet" href="/api/v1/namespaces/default/services/prometheus/proxy/static/css/prometheus.css?v=3afb3fffa3a29c3de865e1172fb740442e9d0133">

    <script>
      var PATH_PREFIX = "";
```

As you see, the path are prefixed properly, this is why without setting anything, everything except the graph ui works. There I get this error: `Failed to load :8001/static/js/graph_template.handlebar?v=3afb3fffa3a29c3de865e1172fb740442e9d0133&_=1499178246922`. That's because we load this from js here: https://github.com/prometheus/prometheus/blob/master/web/ui/static/js/graph.js#L885 - and PATH_PREFIX isn't set.

Now setting `external-url` breaks everything because, while it fixes loading the handlebar template, it get added to the html links *additionally to the correct, automatic prefixes*.

The only thing I need to figure out to fix this is how the correct prefixing works.. I'm pretty surprised and have no idea yet..

**Comment by discordianfish** [comment]
Hope not the k8s apiserver proxy is doing this?

**Comment by linusguan** [comment]
@discordianfish I think even if you set the correct prefix by setting `- "-web.external-url=..."
- "-web.route-prefix=/" `, the /graph part is still not going to work, there is a temporary solution in another thread using nginx with custom rewrite rules.

**Comment by fabxc** [comment]
@discordianfish oh yea, proxy fiddles around with your HTML IIRC.

**Comment by discordianfish** [comment]
That would explain all my and probably lot of other people' confusion. If it's really that and nothing on the prometheus side, it's impossible to fix this without introducing yet another flag which only sets a prefix for things we load in js..

**Comment by thenayr** [comment]
No, this isn't the Kube Proxy fault.  Other software does this perfectly fine (see Grafana etc.)

**Comment by discordianfish** [comment]
@thenayr Do you know how this is suppose to work? We might lack some understanding how web applications handle this in general. I've opened https://github.com/kubernetes/kubernetes/issues/48503 to clarify the apiserver proxy's behavior.

**Comment by thenayr** [comment]
@discordianfish I would model after what Kibana does for `server.basePath`.  

A few references:

https://www.elastic.co/guide/en/kibana/current/development-basepath.html
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/kibana-image/run.sh#L22

**Comment by discordianfish** [comment]
This looks pretty much like what external-url is doing, no? If I set that, I get the prefix twice. Once due the prefixing and then something else (kube api's proxy or something in the 'middleware'). Either way, I still don't understand what is prefixing the URLs in the prometheus html when external-url is not set.

**Comment by thenayr** [comment]
Here's one example of where a script is being loaded over absolute path instead of external-url:

![Graph page](http://i.imgur.com/GbIFCUZ.png)

This is pulled in via [ajax here](https://github.com/prometheus/prometheus/blob/6a767b736be5cd4ddf72a8bc6024ac8115713e7d/web/ui/static/js/graph.js#L884-L898)

**Comment by discordianfish** [comment]
I know, as I said: We can fix that by setting the prefix path, but that also prefixes the HTML. In this specific case we would need to prefix the ajax stuff but not the HTML. But first we need to understand what is going on here and I don't have time for that deep dive right now. I've opened https://github.com/kubernetes/kubernetes/issues/48503 and hope to get some clarification on the proxy behavior.

**Comment by thenayr** [comment]
Understood.

Dug a bit into the k8s proxy code and it looks like the following happens:

URL's that aren't "proxy aware" aka don't include the k8s proxy path (/api/v1/proxy...) in them will be rewritten to include them,  [as seen here](https://github.com/vishh/kubernetes/blob/2788b470597719a574ffe092819401814587b074/pkg/util/proxy/transport.go#L187-L230 )

URL's that already include the proxy path are deemed "proxy aware" and will not be rewritten [as seen here](https://github.com/vishh/kubernetes/blob/2788b470597719a574ffe092819401814587b074/pkg/util/proxy/transport.go#L139-L142)

**Comment by brancz** [comment]
External URL is what is used to render links in the HTML. And route prefix sets the routes the actual http routes are registered to. As the kube proxy strips the prefix of /v1/proxy/.../graph the request ends up being /graph. If I understand the problem correctly solution here is that you need to set external URL to the full proxy URL and route prefix to just "/" as described above. This is solved in the new alertmanager UI, and would cause breaking changes to the Prometheus UI if we introduce it in the same way in the Prometheus UI in the same way.

**Comment by discordianfish** [comment]
As @thenayr figured out, all we need to do is support relative URLs. The apiserver proxy will detect them as already prefixed and leave them alone.

**Comment by sylr** [comment]
FWIW I've been able to setup (after a lot of efforts) something pretty decent.

Network flow :

 - internet
   - nginx ingress controller (https://prometheus.company.com/[prometheus-server]/graph)
     - oauth2_proxy (http://prometheus-company-com-oauth2-proxy:4180/[prometheus-server]/graph)
       - nginx reverse proxy (http://localhost:18080/prometheusX/graph)
         - prometheus-server-[k8s-euw-dev]  (http://prometheus-server-k8s-euw-dev.monitoring.svc.cluster.local/graph)
         - prometheus-server-[k8s-euw-test] (http://prometheus-server-k8s-euw-dev.monitoring.svc.cluster.local/graph)
         - prometheus-server-[k8s-euw-prod] (http://prometheus-server-k8s-euw-dev.monitoring.svc.cluster.local/graph)

prometheus-company-com-oauth2-proxy deployment :

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  generation: 3
  labels:
    app: prometheus-company-com-oauth2-proxy
  name: prometheus-company-com-oauth2-proxy
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-company-com-oauth2-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-company-com-oauth2-proxy
    spec:
      containers:
      - image: sylvainlectra/oauth2-proxy:0.12
        imagePullPolicy: IfNotPresent
        name: oauth2-proxy
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: oauth2-proxy-config-volume
      - image: nginx:1.13
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-company-com-oauth2-proxy-conf
        name: oauth2-proxy-config-volume
      - configMap:
          defaultMode: 420
          name: prometheus-company-com-nginx-conf
        name: nginx-config-volume
      - configMap:
          defaultMode: 420
          name: prometheus-company-com-oauth2-proxy-conf
        name: config-volume
```

ingress prometheus-company-com-oauth2-proxy

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  generation: 4
  name: prometheus-company-com-oauth2-proxy
  namespace: monitoring
spec:
  rules:
  - host: prometheus.company.com
    http:
      paths:
      - backend:
          serviceName: prometheus-company-com-oauth2-proxy
          servicePort: 4180
        path: /
  tls:
  - hosts:
    - prometheus.company.com
    secretName: wildcard-company-com-tls
```

oauth2_proxy conf (interesting bits):

```
http_address = "0.0.0.0:4180"
upstreams = [
    "http://localhost:18080/"
]
```

nginx reverse proxy conf:

```
server {
    listen *:18080;
    resolver 10.200.0.10 valid=10s;

    location ~* ^/(?<cluster>k8s[a-z0-9-]+) {
        rewrite ^/k8s[a-z0-9-]+/?$       /$cluster/graph    redirect;
        rewrite ^/k8s[a-z0-9-]+/(.*)$    /$1                break;
        proxy_pass http://prometheus-server-$cluster.monitoring.svc.cluster.local:80;

        sub_filter_types text/html;
        sub_filter_once off;
        sub_filter 'var PATH_PREFIX = "";' 'var PATH_PREFIX = "/$cluster";';
        sub_filter '="/' '="/$cluster/';
    }
}
```

Hope it helps.

Cheers.

**Comment by aduzsardi** [comment]
It's working like this without any issues

`/path/to/prometheus --config.file="config.yml" --storage.tsdb.path="./data" --web.listen-address="127.0.0.1:9090" --web.external-url="http://MY_REVERSE_PROXY_DNS/prometheus/" --web.route-prefix="/"`

`/path/to/alertmanager --config.file="config.yml" --storage.path="./data" --web.external-url="http://MY_REVERSE_PROXY_DNS/alertmanager/" --web.route-prefix="/" --web.listen-address="127.0.0.1:9093" --mesh.listen-address=""`

**Nginx config**

```
server {
  listen 80 default_server;

  location /alertmanager/ {
    proxy_pass http://127.0.0.1:9093/;
  }

  location /prometheus/ {
    proxy_pass http://127.0.0.1:9090/;
  }

  location /grafana/ {
    proxy_pass http://127.0.0.1:3000/;
  }

  location / {
    try_files $uri $uri/ =404;
  }

}
```
Hopefully this helps somebody :)

**Comment by RKdev** [comment]
I've been having the same issue. Web UI comes up via `kubectl proxy`, but the `Graph` button does nothing.
Not sure if this is a clue or not, but when I check Command Line Flags in the ui `--web.external-url` is empty
![external_url_missing](https://user-images.githubusercontent.com/3794297/39736435-8e5d5b00-5245-11e8-83ad-90e214f2b692.PNG)

**Comment by rafaelmagu** [comment]
I'm not unsure if it's entirely related, but if I don't provide `--web.external-url` when starting Prometheus, it appears to ignore `--web.route-prefix`.

**Comment by rafaelmagu** [comment]
To better illustrate my comment, I have HAproxy on a bastion, with path-based routing for different backend services. For Prometheus, any request starting with `/prometheus` gets sent to the Prometheus backend, without rewrites.

The source for `/prometheus/graph` is rendered without the route prefix:

![image](https://user-images.githubusercontent.com/197444/41133961-0b2edc30-6b1e-11e8-96d3-f217c0c69e32.png)

If I add `--web.external-url=http://anything/prometheus` to the command line and change `--web.route-prefix` to `/`, I'll get a 404 for `/static` content. If I then change my HAproxy config to drop `/prometheus` from the URLs before sending the requests to the backend, it works:

![image](https://user-images.githubusercontent.com/197444/41134041-89dbe30c-6b1e-11e8-9c19-012e11290caa.png)

**Note**: by `anything`, I really do mean `anything`, even an invalid FQDN works with `--web.external-url`.

Alertmanager does not present this behaviour at all. Setting **only** `--web.route-prefix=/alertmanager` and configuring HAproxy to not rewrite URLs for the Alertmanager backend works as intended.

(I realise Alertmanager is more of a single page app, so this would not be an issue anyway)

**Comment by rafaelmagu** [comment]
With `--web.external-url=.../prometheus` and `--web.route-prefix=/prometheus`, the page renders correctly without rewrites from HAproxy.

**Comment by deveshmehta** [comment]
Thanks Rafael for the details.

I tried your suggestion given above but the issue still persist and it lost some more bit.
![image](https://user-images.githubusercontent.com/9815653/41147973-a6af2238-6aff-11e8-95ed-2732b1f2aef4.png)

I am running the Prometheus behind the NGINX proxy server. The issue is when I access the Prometheus directly over private IP it works as expected -   http://<Private IP>:9090. 

But when I try to access it via reverse proxy then under Graph tab while loading the metrics I am getting error - Error loading available metrics!

![](https://files.slack.com/files-pri/T10AE7GPJ-FB4K5L13R/image.png)

NGINX proxy config. 

       location /prometheus/ {
         #auth_basic off;
         proxy_set_header Accept-Encoding "";
         proxy_pass http://<IP Address>:9090/;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;

         #sub_filter_types text/html;
         sub_filter_once off;
         sub_filter '="/' '="/prometheus/';
         sub_filter '="/static/' '="/static/prometheus/';
         sub_filter 'var PATH_PREFIX = "";' 'var PATH_PREFIX = "/prometheus";';
       }

NGINX reverse proxy logs

<Prometheus Private IP> - testuser [08/Jun/2018:08:18:54 +0000] "GET /prometheus/graph HTTP/2.0" 200 5343 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-"
<Prometheus Private IP> - testuser [08/Jun/2018:08:18:54 +0000] "GET /prometheus/static/js/graph/graph_template.handlebar?v=cd5e2fe68741a60ba90b80fbc161d0581be9e8bd&_=1528445934437 HTTP/2.0" 200 6343 "https://www.awstest-dev.testcloud.uk/prometheus/graph" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-"
**<Prometheus Private IP> - testuser [08/Jun/2018:08:18:54 +0000] "GET /prometheus/api/v1/query?query=time()&_=1528445934438 HTTP/2.0" 404 69 "https://www.awstest-dev.testcloud.uk/prometheus/graph" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-"**
**<Prometheus Private IP> - testuser [08/Jun/2018:08:18:54 +0000] "GET /prometheus/api/v1/label/__name__/values?_=1528445934439 HTTP/2.0" 404 69 "https://www.awstest-dev.testcloud.uk/prometheus/graph" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-"**

Its working local url -  curl http://<Private IP>:9090/api/v1/label/__name__/values?_=1528379332787
Url through reverse proxy - https://www.awstest-dev.testcloud.uk/prometheus/graph

Could you please suggest any solution for it.

Thanks in advance

**Comment by thxCode** [comment]
Follow @sylr 's comment, using nginx as proxy, without setting `--web.external-url` and `--web.route-prefix`:

**Comment by bapiraju** [comment]
Thanks Rafael, Removed /prometheus from my vhost and it finally worked!

**Comment by jranson** [comment]
@thenayr and @discordianfish are completely correct -- simply using relative URL references throughout the project will transparently solve any and all pathing issues with Zero configuration.  It is meant exactly for these situations. Even 302 Redirects support relative paths since 2014 (for the `/` -> `./graph` redirect). Requiring an explicit configuration to ensure compatibility with a reverse proxy goes against every best practice and we should fix this. Will take a stab at it shortly!

**Comment by shinebayar-g** [comment]
Following examples doesn't work properly.
https://prometheus.io/docs/guides/basic-auth/
https://prometheus.io/docs/guides/tls-encryption/

nginx config
```nginx
server {
        listen 80;
        server_name mydomain.com;
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location /prometheus {
                proxy_pass http://127.0.0.1:9090/;
        }
}
```
prometheus docker compose config

```yml
version: '3.2'
services:
  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://mydomain.com/prometheus
      - --web.route-prefix=/
```

and if I go to `http://mydomain.com/prometheus` it redirects to `http://mydomain.com`
if I go to `http://mydomain.com/prometheus/graph` it redirects to `http://mydomain.com/graph` which returns 404 by nginx. Anyone could fix the examples?

**Comment by sanmai** [comment]
Instructions [from this document](https://prometheus.io/docs/guides/tls-encryption/) do actually work.

You should check if you browser happen to cache the redirect, which sometimes happen with this setup.

**Comment by C-Duv** [comment]
> With `--web.external-url=http://anything/prometheus` and `--web.route-prefix=/prometheus`, the page renders correctly without rewrites from HAproxy.

Thanks I've solved my issue running a Docker container Prometheus via `docker-compose` behind Træfik on `http://example.com/prometheus-ui`.

With the following `docker-compose.yml` (NB: with this configuration, the `/prometheus-ui` string could be in a `.env` file (or other way to set environment variables) for better dynamism):

```Yaml
version: "3.7"

services:
    prometheus:
         command:
             - "--web.listen-address=0.0.0.0:9090"
             - "--web.external-url=http://dummy.invalid/prometheus-ui"
             - "--web.route-prefix=/prometheus-ui"
         image: prom/prometheus:v2.24.0
         labels:
             - "traefik.enable=true"
             - "traefik.docker.network=prometheus_net"
             # Router (my Træfik HTTP entrypoint is named "web"):
             - "traefik.http.routers.to-prometheus-prod.entrypoints=web"
             - "traefik.http.routers.to-prometheus-prod.rule=Host(`example.com`) && PathPrefix(`/prometheus-ui`)"
             # Service:
             - "traefik.http.services.prometheus-prod.loadbalancer.server.port=9090"
             - "traefik.http.services.prometheus-prod.loadbalancer.server.scheme=http"
```

I used `http://dummy.invalid` in the `--web.external-url` option because then I'm pretty sure it will never be mistaken as an existing URL.
