### ISSUE TITLE
The container name does not match the actual one

### ISSUE THREAD

**Issue by mike9421** [prometheus/prometheus#15848]
### What did you do?

1. Scrape metrics by `kubernetes_sd_configs`
2. Read the value of the `__meta_kubernetes_pod_container_name` label in the metric as the `container_name`.

### What did you expect to see?

The meaning understood from the [document](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod) is: __meta_kubernetes_pod_container_name: Name of the container the target address points to.

The instance should point to the container I defined (named http-server), which means the`container_name` should be "http-server".

### What did you see instead? Under which circumstances?

However, the actual `container_name` value is the name of the init-container (i.e., init-sysctl).

### System information

Kubernetes 1.17 (This issue should be unrelated to the environment.)

### Prometheus version

```text
v0.54.1
```

### Prometheus configuration file

```yaml
prometheus:
    config:
      scrape_configs:
        - job_name: 'scrape-prometheus-open-metrics'
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - default
              selectors:
                - role: pod
                  field: spec.nodeName=$KUBE_NODE_NAME
          scrape_interval: 15s
          scrape_timeout: 15s
          metrics_path: /openMetrics
          scheme: http
          relabel_configs:
          - source_labels: [__address__]
            target_label: __address__
            regex: ([^:]+)(?::\d+)?
            replacement: $$1:26666
            action: replace
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
