### ISSUE TITLE
Failed get prometheus namespace label

### ISSUE THREAD

**Issue by orakhada** [prometheus/prometheus#16015]
### What did you do?

I added to prometheus.yml from prometheus as below, but I can't get label from namespace, is there a way to recommend it?
```
    - job_name: kubernetes-namespaces
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_namespace_label_(.+)]
        target_label: namespace_label
```

### What did you see instead? Under which circumstances?

prometheus

### Prometheus version

```text

```

### Prometheus configuration file

```yaml

```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
