### ISSUE TITLE
potential concurrency risks in `DiscoveredLabels` update

### ISSUE THREAD

**Issue by mike9421** [prometheus/prometheus#16019]
### What did you do?

1. Use Prometheus to scrape metrics from pods (with multiple containers) in the cluster. (Prometheus will update `DiscoveredLabels`, see [target sync code](https://github.com/prometheus/prometheus/blob/e6cfa720fbe6280153fab13090a483dbd40bece3/scrape/scrape.go#L505)
2. Read the values of `DiscoveredLabels`. Concurrency problems may occur at this time (e.g., 1. [prometheus api](https://github.com/prometheus/prometheus/blob/e6cfa720fbe6280153fab13090a483dbd40bece3/web/api/v1/api.go#L378) and [read value](https://github.com/prometheus/prometheus/blob/e6cfa720fbe6280153fab13090a483dbd40bece3/web/api/v1/api.go#L1069); 2. [OTel reads this value for use](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/37268) ). 
3. Occasional changes in `DiscoveredLabels` when the pod is running normally.

The following is a process example diagram.

![Image](https://github.com/user-attachments/assets/8c83a8c9-7b93-4fc2-9440-8c118f43d956)

### What did you expect to see?

No concurrency risk

### What did you see instead? Under which circumstances?

Occasional changes in `DiscoveredLabels` when the pod is running normally.

### System information

any OS

### Prometheus version

```text
the latest version will also have such problems
```

### Prometheus configuration file

```yaml
scrape_configs:
        - job_name: 'scrape-prometheus-open-metrics'
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names:
                  - default
              selectors:
                - role: pod
                  field: spec.nodeName=$KUBE_NODE_NAME
          scrape_interval: 10s
          scrape_timeout: 10s
          metrics_path: /openMetrics
          scheme: http
          relabel_configs:
          - source_labels: [__address__]
            target_label: __address__
            regex: ([^:]+)(?::\d+)?
            replacement: $$1:26666
            action: replace
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
