### ISSUE TITLE
UI error for service-discovery view when setting per target job-labels and droppedTargets is not empty (prometheus >=  3.0)

### ISSUE THREAD

**Issue by TheMeier** [prometheus/prometheus#16065]
### What did you do?

When configuring service discovery with a custom, per-target job label and the SD contains drop targets the web-view for service-discovery shows an error:
```
Error showing target pools
Error: Received target information for an unknown scrape pool, likely the list of scrape pools has changed. Please reload the page.
```

I think the cause of this is the code in https://github.com/prometheus/prometheus/blob/main/web/ui/mantine-ui/src/pages/service-discovery/ServiceDiscoveryPoolsList.tsx#L114-L117

because the job label value is used as key for a map access when they keys in the map are the configurations job_name.

Example setup:
prometheus.yml
```yaml
scrape_configs:
- job_name: ok
  honor_labels: true
  file_sd_configs:
  - files:
    - ./target_ok.json
- job_name: fail
  honor_labels: true
  file_sd_configs:
  - files:
    - ./target_fail.json
  relabel_configs:
    - action: drop
      source_labels: [dropme]
      regex: "true"
```

target_ok.json
```json
[
  {
    "labels": {
      "foo": "bar"
    },
    "targets": [
      "localhost:9100"
    ]
  }
]
```

target_fail.json
```json
[
  {
    "labels": {
      "foo": "bar",
      "job": "failure"
    },
    "targets": [
      "localhost:9100"
    ]
  },
  {
    "labels": {
      "foo": "bar",
      "job": "failure",
      "dropme": "true"
    },
    "targets": [
      "localhost:9101"
    ]
  }
]
```

Result:
http://localhost:9090/service-discovery?pool=ok  NO FAILURE
http://localhost:9090/service-discovery?pool=fail   ERROR

### What did you expect to see?

No error message in both cases

### What did you see instead? Under which circumstances?

![Image](https://github.com/user-attachments/assets/13211e5f-255e-4bd5-8ca2-bee9e2e9e820)

for http://localhost:9090/service-discovery?pool=fail

### System information

Linux 6.12.15-200.fc41.x86_64 x86_64

### Prometheus version

```text
prometheus, version 3.2.0 (branch: HEAD, revision: bf7ec404b2a4933a81b0ffe2baba32b92d471655)
  build user:       root@793dd0d4a527
  build date:       20250217-18:43:06
  go version:       go1.23.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
scrape_configs:
- job_name: ok
  honor_labels: true
  file_sd_configs:
  - files:
    - ./target_ok.json
- job_name: fail
  honor_labels: true
  file_sd_configs:
  - files:
    - ./target_fail.json
  relabel_configs:
    - action: drop
      source_labels: [dropme]
      regex: "true"
```
