### ISSUE TITLE
OTLP Receiver: Out of order target_info samples

### ISSUE THREAD

**Issue by jameshartig** [prometheus/prometheus#16063]
### What did you do?

Enabled otlp with `--web.enable-otlp-receiver` and submitted OTLP metrics across multiple batches to `/api/v1/otlp/v1/metrics` with the following attributes:
```
service.name: yb-collector
net.host.name: 10.21.200.10
service.instance.id: 10.21.200.10:7000
net.host.port: 7000
http.scheme: http
```

### What did you expect to see?

I expected not to see any ERROR logs and I didn't expect to see any `target_info` metrics since I specified all attributes in the config to be promoted. There's also no way for me to configure the otlp receiver to disable target_info metrics.

### What did you see instead? Under which circumstances?

Instead I see 2 ERROR logs with every push specifically with the `target_info`:

```
time=2025-02-20T20:45:35.827Z level=ERROR source=write_handler.go:306 msg="Out of order sample from remote write" component=web err="out of order sample" series="{__name__=\"target_info\", http_scheme=\"http\", instance=\"10.21.200.10:7000\", job=\"yb-collector\", net_host_name=\"10.21.200.10\", net_host_port=\"7000\"}" timestamp=1740084335531
time=2025-02-20T20:45:35.881Z level=ERROR source=write_handler.go:306 msg="Out of order sample from remote write" component=web err="out of order sample" series="{__name__=\"target_info\", http_scheme=\"http\", instance=\"10.21.200.10:7000\", job=\"yb-collector\", net_host_name=\"10.21.200.10\", net_host_port=\"7000\"}" timestamp=1740084335531
```

### Prometheus version

```text
prometheus, version 3.2.0 (branch: HEAD, revision: bf7ec404b2a4933a81b0ffe2baba32b92d471655)
  build user:       root@runner-2qmmjann-project-28301003-concurrent-0
  build date:       20250219-04:19:18
  go version:       go1.23.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
otlp:
  # Recommended attributes to be promoted to labels.
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
    - net.host.name
    - net.host.port
    - http.scheme
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
