### ISSUE TITLE
Configuration issues regarding the prometheus rule_files field for helm installation

### ISSUE THREAD

**Issue by pptfz** [prometheus/prometheus#16071]
I installed prometheus through helm
prometheus versionn is 3.1.0
```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install [RELEASE_NAME] prometheus-community/prometheus
```

`kubectl get cm prometheus-server -o yaml`
```
prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    rule_files:
    - /etc/config/recording_rules.yml
    - /etc/config/alerting_rules.yml
    - /etc/config/rules
    - /etc/config/alerts
 ```

Check the cm mounted to prometheus-server. By default, the rule_files field has four configurations.
`/etc/config/recording_rules.yml` is a preconfiguration file used for common queries as well as complex queries
`/etc/config/alerting_rules.yml` is the file that defines alarm rules
So what are the roles of `/etc/config/rules` and `/etc/config/alerts` , which I think are files and not directories

My question
If you configure alarm rules, what is the difference between `/etc/config/alerting_rules.yml` and `/etc/config/alerts`
If you configure pre-query rules, what is the difference between `/etc/config/alerting_rules.yml` and `/etc/config/rules`
Not sure which file to use in which scenario, please

![Image](https://github.com/user-attachments/assets/5400f7e4-74b1-43f1-8b3d-a4aeda13e6f2)
