### ISSUE TITLE
WAL truncation failure caused by "unexpected non-zero byte in padded page" error causing corrupt database and data loss

### ISSUE THREAD

**Issue by steinwelberg** [prometheus/prometheus#16074]
### What did you do?

We have a remote setup where we have a number of Prometheus instances in agent mode writing to a single prometheus instance. We have now lost our metrics data a couple of times due to the fact that a WAL segment got corrupted, which causes compaction to fail and the WAL archives to grow indefinitely. After a reboot of the Prometheus pod, it starts to replay the WAL and when it encounters the corrupt segment it will delete all segments before the corrupted one meaning we loose all our historic metrics.

I could not find anything that explains what caused the underlying error `unexpected non-zero byte in padded page` that causes the WAL compaction to fail.

Logs: [Explore-logs-2025-02-25 15_39_24.json](https://github.com/user-attachments/files/18966628/Explore-logs-2025-02-25.15_39_24.json)

### What did you expect to see?

I would expect that the WAL compaction would not fail due to an unexpected non-zero byte in padded page, but that it can recover itself from such an error without loosing all data.

### What did you see instead? Under which circumstances?

As mentioned above, we see that WAL compaction starts to fail and keeps failing. Meaning that the folder contains the WAL will keep growing.

### System information

Linux 6.6.43-flatcar x86_64

### Prometheus version

```text
prometheus, version 3.1.0 (branch: HEAD, revision: 7086161a93b262aa0949dbf2aba15a5a7b13e0a3)
  build user:       root@74c225e2044f
  build date:       20250102-13:52:43
  go version:       go1.23.4
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
prometheus:
      agentMode: false

      prometheusSpec:
        secrets:
        - prometheus-etcd-servicemonitor
        scrapeClasses:
        - name: defaultScrapeClass
          default: true
          relabelings:
          - action: replace
            replacement: ${clusterName}
            targetLabel: cluster

        externalLabels: null
        replicas: 1

        retention: 14d
        retentionSize: 450GB

        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: hdd
              resources:
                requests:
                  storage: 550Gi
              accessModes:
              - ReadWriteOnce

        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false

        enableRemoteWriteReceiver: true
        remoteWrite: null # setup mtls proxy
        containers:
        - name: envoy
          image: envoyproxy/envoy:v1.33-latest@sha256:56da5afd7df364350ff92de4fb49a9b09957c17295f2899f0a31cd12c28770c2
          ports:
          - containerPort: 8443
          volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy/envoy.yaml
            subPath: envoy.yaml
          - name: envoy-certs
            mountPath: /etc/envoy/tls
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
        volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: envoy-certs
          secret:
            secretName: prometheus-remote-write-secret

      service:
        annotations:
          loadbalancer.openstack.org/hostname: prometheus.infra.<REDACTED>
          external-dns.alpha.kubernetes.io/hostname: prometheus.<REDACTED>
          external-dns.alpha.kubernetes.io/target: <REDACTED>

        type: LoadBalancer
        loadBalancerSourceRanges:
        - <REDACTED>

        reloaderWebPort: 8080
        port: 9090

        additionalPorts:
        - name: push-http
          port: 443
          targetPort: 8443
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text
Logs are attached as file: https://github.com/user-attachments/files/18966628/Explore-logs-2025-02-25.15_39_24.json
```
