### ISSUE TITLE
Questions about changing time zones using helm installation

### ISSUE THREAD

**Issue by pptfz** [prometheus/prometheus#16152]
`Chart.yaml`
```
cat Chart.yaml
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus/prometheus
apiVersion: v2
appVersion: v3.1.0
dependencies:
- condition: alertmanager.enabled
  name: alertmanager
  repository: https://prometheus-community.github.io/helm-charts
  version: 1.13.*
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.28.*
- condition: prometheus-node-exporter.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.43.*
- condition: prometheus-pushgateway.enabled
  name: prometheus-pushgateway
  repository: https://prometheus-community.github.io/helm-charts
  version: 2.16.*
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
keywords:
- monitoring
- prometheus
kubeVersion: '>=1.19.0-0'
maintainers:
- email: gianrubio@gmail.com
  name: gianrubio
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: miroslav.hadzhiev@gmail.com
  name: Xtigyro
- email: naseem@transit.app
  name: naseemkullah
- email: rootsandtrees@posteo.de
  name: zeritti
name: prometheus
sources:
- https://github.com/prometheus/alertmanager
- https://github.com/prometheus/prometheus
- https://github.com/prometheus/pushgateway
- https://github.com/prometheus/node_exporter
- https://github.com/kubernetes/kube-state-metrics
type: application
version: 26.1.0
```

edit `values.yaml`
```
server:
  ## Prometheus server container name
  ##
  name: server

......

  ## Additional server container environment variables
  ##
  ## You specify this manually like you would a raw deployment manifest.
  ## This means you can bind in environment variables from secrets.
  ##
  ## e.g. static environment variable:
  ##  - name: DEMO_GREETING
  ##    value: "Hello from the environment"
  ##
  ## e.g. secret environment variable:
  ## - name: USERNAME
  ##   valueFrom:
  ##     secretKeyRef:
  ##       name: mysecret
  ##       key: username
  env: 
    - name: TZ
      value: "Asia/Shanghai"
```

![Image](https://github.com/user-attachments/assets/d5ab1212-d4b5-4e1d-8b29-ebd9e3c292ee)

update install
```
helm upgrade --install prometheus -n monitor --create-namespace .
```

The environment variable has taken effect
```
$ kubectl exec -it prometheus-server-744b8ff58b-w4bb7 -c prometheus-server -- env |grep TZ
TZ=Asia/Shanghai
```

Wanted to change to UTC8 but did not take effect
```
$ kubectl exec -it prometheus-server-744b8ff58b-w4bb7 -c prometheus-server -- date
Fri Feb 28 06:46:29 UTC 2025
```

prometheus doesn't support changing the time zone in a pod with environment variables or is there something wrong with my approach
I asked chatgpt, another way is through init container, is that OK
