### ISSUE TITLE
“PrometheusDuplicateTimestamps” duplicate metric issue when collecting Issue

### ISSUE THREAD

**Issue by 95jinhong** [prometheus/prometheus#16201]
### What did you do?

I updated to EKS version 1.32 and configured Prometheus version 3.2.0 through kube-prometheus-stack Chart.

I am using fluent-bit 3.2.6 to send Kafka messages to promethues output when publishing and collecting metrics through servicemonitor and loading them into prometheus.

After updating, I keep getting the following error.
```
time=2025-03-12T06:16:47.395Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.37.49:2021/metrics num_dropped=11970
time=2025-03-12T06:16:57.270Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.54.195:2021/metrics num_dropped=5969
time=2025-03-12T06:17:08.242Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.47.125:2021/metrics num_dropped=18003
```

My prometheus configuration is the same as before, and my fluent-bit configuration is the same, so why am I getting this error?

### What did you expect to see?

Metrics collected via servicemonitor are loaded into prometheus normally, and prometheus does not leave the above WARN logs.

### What did you see instead? Under which circumstances?

When metrics are collected through servicemonitor, you will see a corresponding warning log.
And the corresponding alert noise was generated by prometheus.

- alertname : PrometheusDuplicateTimestamps
```
rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{job="prometheus-prometheus",namespace="monitoring"}[5m]) > 0
```

<img width="1672" alt="Image" src="https://github.com/user-attachments/assets/2454bd69-792d-49ab-973f-98c1313e7a69" />

### System information

EKS 1.32 / Amazon Linux 2

### Prometheus version

```text
Version : 3.2.0
Revsion : bf7ec404b2a4933a81b0ffe2baba32b92d471655
BuildDate : 20250217-18:43:06
Goversion : go1.23.6
```

### Prometheus configuration file

```yaml
## prometheus rule spec

global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
- job_name: serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0
  honor_timestamps: false
  track_timestamps_staleness: false
  scrape_interval: 30s
  scrape_timeout: 30s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name, __meta_kubernetes_service_labelpresent_app_kubernetes_io_name]
    separator: ;
    regex: (ddocdoc-metric);true
    replacement: $1
    action: keep


## servicemonitor spec

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ddocdoc-metric-metric
spec:
  endpoints:
  - honorLabels: false
    honorTimestamps: false
    interval: 30s
    path: /metrics
    port: tcp
    scrapeTimeout: 30s
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
    - ddocdoc-metric
  selector:
    matchLabels:
      app.kubernetes.io/name: ddocdoc-metric
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text
## prometheus log

time=2025-03-12T06:28:57.356Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.54.195:2021/metrics num_dropped=17934
time=2025-03-12T06:29:08.238Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.47.125:2021/metrics num_dropped=18030
time=2025-03-12T06:29:17.398Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.37.49:2021/metrics num_dropped=11998
time=2025-03-12T06:29:27.269Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.54.195:2021/metrics num_dropped=5979
time=2025-03-12T06:29:38.238Z level=WARN source=scrape.go:1884 msg="Error on ingesting samples with different value but same timestamp" component="scrape manager" scrape_pool=serviceMonitor/ddocdoc-metric/ddocdoc-metric-metric/0 target=http://172.31.47.125:2021/metrics num_dropped=18036
```
