### ISSUE TITLE
Prometheus dropping series unexpectedly in remote_write

### ISSUE THREAD

**Issue by harry671003** [prometheus/prometheus#16255]
### What did you do?

I have configured a Prometheus server (v3.2.1) to remote_write to a Cortex cluster. Several times there were instances where the Prometheus server will get into a bad state where it doesn't sent any samples for some timeseries.

The series is present in Prometheus but is not sent to Cortex. This is evident when I query both of them separately.

#### Prometheus result
Query: `prometheus_http_requests_total{code!="200"}`
![Image](https://github.com/user-attachments/assets/e06e2d5f-1a1a-4a76-b099-6a7d7d2567fd)

#### Cortex Result
Query: `prometheus_http_requests_total{code!="200"}`
![Image](https://github.com/user-attachments/assets/5fcaa165-4edf-462d-98d3-ca20c93d61de)

I've narrowed down the issue to the following logs in Prometheus.
```
time=2025-03-21T03:50:39.469Z level=INFO source=queue_manager.go:709 msg="Dropped sample for series that was not explicitly dropped via relabelling" component=remote remote_name=5cd4b5 url=<Cortex URL> ref=21931
```

I took a quick look at the code. This seems to be a bug in Prometheus where it cannot find the series ID in the queue_manager.
https://github.com/prometheus/prometheus/blob/3d603d19575ef20ced7e3a2293b7bf10ce359d54/storage/remote/queue_manager.go#L705

I don't know if it's relevant to this issue. I saw Prometheus server getting OOM killed before this happened. But it doesn't always happen after an OOM.

### What did you expect to see?

Prometheus shouldn't unexpectedly drop series.

### What did you see instead? Under which circumstances?

Prometheus should send all the series in remote write.

### System information

Linux 5.10.234-225.895.amzn2.x86_64 x86_64

### Prometheus version

```text
$ prometheus --version
prometheus, version 3.2.1 (branch: HEAD, revision: 804c49d58f3f3784c77c9c8ec17c9062092cae27)
  build user:       root@42fd9529152a
  build date:       20250226-09:19:49
  go version:       go1.23.6
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  evaluation_interval: 1m
runtime:
  gogc: 50
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: kube-state-metrics
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: sharded-kube-state-metrics
    replacement: $1
    action: keep
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: (kube_pod_info)
    replacement: $1
    action: keep
  kubernetes_sd_configs:
  - role: endpoints
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
remote_write:
- url: <cortex>
  remote_timeout: 30s
  write_relabel_configs:
  - source_labels: [__replica__]
    separator: ;
    regex: ^.*(server-.*)$
    target_label: __replica__
    replacement: $1
    action: replace
  protobuf_message: prometheus.WriteRequest
  follow_redirects: true
  enable_http2: false
  queue_config:
    capacity: 10000
    max_shards: 50
    min_shards: 1
    max_samples_per_send: 2000
    batch_send_deadline: 30s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 2000
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml
N/A
```

### Logs

```text
"time=2025-03-21T03:00:02.923Z level=INFO source=compact.go:591 msg=""write block"" component=tsdb mint=1742515201728 maxt=1742522400000 ulid=01JPVA9DDWJ38KEGYKP3JG711D duration=302.616924ms ooo=false"
"time=2025-03-21T03:00:02.940Z level=INFO source=head.go:1371 msg=""Head GC completed"" component=tsdb caller=truncateMemory duration=13.187926ms"
"time=2025-03-21T03:00:02.941Z level=INFO source=checkpoint.go:100 msg=""Creating checkpoint"" component=tsdb from_segment=86 to_segment=87 mint=1742522400000"
"time=2025-03-21T03:00:03.363Z level=INFO source=head.go:1333 msg=""WAL checkpoint complete"" component=tsdb first=86 last=87 duration=422.589249ms"
"time=2025-03-21T03:43:40.637Z level=WARN source=main.go:282 msg=""Unknown option for --enable-feature"" option=expand-external-labels"
"time=2025-03-21T03:43:40.637Z level=INFO source=main.go:228 msg=""Experimental memory snapshot on shutdown enabled"""
"time=2025-03-21T03:43:40.637Z level=WARN source=main.go:282 msg=""Unknown option for --enable-feature"" option=auto-gomemlimit"
"time=2025-03-21T03:43:40.637Z level=INFO source=main.go:237 msg=""Experimental per-step statistics reporting"""
"time=2025-03-21T03:43:40.638Z level=INFO source=main.go:687 msg=""Starting Prometheus Server"" mode=server version=""(version=3.2.1, branch=HEAD, revision=804c49d58f3f3784c77c9c8ec17c9062092cae27)"""
"time=2025-03-21T03:43:40.638Z level=INFO source=main.go:692 msg=""operational information"" build_context=""(go=go1.23.6, platform=linux/amd64, user=root@42fd9529152a, date=20250226-09:19:49, tags=netgo,builtinassets,stringlabels)"" host_details=""(Linux 5.10.234-225.895.amzn2.x86_64 #1 SMP Tue Feb 11 11:40:46 UTC 2025 x86_64 query-correctness-prometheus-server-0 (none))"" fd_limits=""(soft=1048576, hard=1048576)"" vm_limits=""(soft=unlimited, hard=unlimited)"""
"time=2025-03-21T03:43:40.639Z level=INFO source=main.go:768 msg=""Leaving GOMAXPROCS=16: CPU quota undefined"" component=automaxprocs"
"time=2025-03-21T03:43:40.639Z level=INFO source=query_logger.go:85 msg=""These queries didn't finish in prometheus' last run:"" component=activeQueryTracker queries=""[{\""query\"":\""-bottomk without () (time(), {__name__=\\\""kube_pod_info\\\"",created_by_kind=\\\""DaemonSet\\\"",pod!=\\\""ebs-csi-node-z4qcw\\\""})\"",\""timestamp_sec\"":1742528600},{\""query\"":\""bottomk without () (time(), {__name__=\\\""kube_pod_info\\\"",created_by_kind=\\\""DaemonSet\\\"",pod!=\\\""ebs-csi-node-xcrwg\\\""})\"",\""timestamp_sec\"":1742528599},{\""query\"":\""-bottomk without () (time(), {__name__=\\\""kube_pod_info\\\"",created_by_kind=\\\""DaemonSet\\\"",pod!=\\\""ebs-csi-node-8vffd\\\""})\"",\""timestamp_sec\"":1742528600},{\""query\"":\""-bottomk without () (time(), {__name__=\\\""kube_pod_info\\\"",created_by_kind=\\\""DaemonSet\\\"",pod!=\\\""kube-proxy-7gfpl\\\""})\"",\""timestamp_sec\"":1742528599},{\""query\"":\""bottomk without () (time(), {__name__=\\\""kube_pod_info\\\"",created_by_kind=\\\""DaemonSet\\\"",pod!=\\\""ebs-csi-node-x9ddd\\\""})\"",\""timestamp_sec\"":1742528601}]"""
"time=2025-03-21T03:43:40.642Z level=INFO source=web.go:654 msg=""Start listening for connections"" component=web address=0.0.0.0:9090"
"time=2025-03-21T03:43:40.642Z level=INFO source=main.go:1228 msg=""Starting TSDB ..."""
"time=2025-03-21T03:43:40.644Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1741895455092 maxt=1742018400000 ulid=01JPCQC3VEBMM3PT7PBH4ZJZ8A"
"time=2025-03-21T03:43:40.644Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742018401728 maxt=1742212800000 ulid=01JPJGRQDTM97DGGBSS467E46N"
"time=2025-03-21T03:43:40.644Z level=INFO source=tls_config.go:347 msg=""Listening on"" component=web address=[::]:9090"
"time=2025-03-21T03:43:40.644Z level=INFO source=tls_config.go:350 msg=""TLS is disabled."" component=web http2=false address=[::]:9090"
"time=2025-03-21T03:43:40.646Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742212801728 maxt=1742407200000 ulid=01JPRA59KTYSEEA6AB2N9J5NNS"
"time=2025-03-21T03:43:40.647Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742407201728 maxt=1742472000000 ulid=01JPT7YSYXTQKZ8JDJT8PMB1XV"
"time=2025-03-21T03:43:40.648Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742493601728 maxt=1742500800000 ulid=01JPTNP7NN8BTY5YGJ5Q3B3W88"
"time=2025-03-21T03:43:40.649Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742500801728 maxt=1742508000000 ulid=01JPTWHYY6MTWXJT59AK3HBWA5"
"time=2025-03-21T03:43:40.651Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742472001728 maxt=1742493600000 ulid=01JPTWHZP28JF6DCYYMGPMZNG0"
"time=2025-03-21T03:43:40.652Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742508001728 maxt=1742515200000 ulid=01JPV3DP5YHHWT493PE221SDSW"
"time=2025-03-21T03:43:40.653Z level=INFO source=repair.go:54 msg=""Found healthy block"" component=tsdb mint=1742515201728 maxt=1742522400000 ulid=01JPVA9DDWJ38KEGYKP3JG711D"
"time=2025-03-21T03:43:40.653Z level=WARN source=dir_locker.go:76 msg=""A lockfile from a previous execution already existed. It was replaced"" component=tsdb file=/data/lock"
"time=2025-03-21T03:43:40.811Z level=INFO source=head.go:628 msg=""Replaying on-disk memory mappable chunks if any"" component=tsdb"
"time=2025-03-21T03:43:40.811Z level=INFO source=head.go:637 msg=""Chunk snapshot is enabled, replaying from the snapshot"" component=tsdb"
"time=2025-03-21T03:43:40.899Z level=INFO source=head_wal.go:1667 msg=""chunk snapshot loaded"" component=tsdb dir=/data/chunk_snapshot.000072.0008978432 num_series=12682 duration=87.85565ms"
"time=2025-03-21T03:43:40.899Z level=INFO source=head.go:667 msg=""Chunk snapshot loading time"" component=tsdb duration=88.011992ms"
"time=2025-03-21T03:43:40.918Z level=INFO source=head.go:715 msg=""On-disk memory mappable chunks replay completed"" component=tsdb duration=18.89737ms"
"time=2025-03-21T03:43:40.918Z level=INFO source=head.go:723 msg=""Replaying WAL, this may take a while"" component=tsdb"
"time=2025-03-21T03:43:41.051Z level=INFO source=head.go:760 msg=""WAL checkpoint loaded"" component=tsdb"
"time=2025-03-21T03:43:41.324Z level=INFO source=head.go:795 msg=""WAL segment loaded"" component=tsdb segment=88 maxSegment=91"
"time=2025-03-21T03:43:41.842Z level=INFO source=head.go:795 msg=""WAL segment loaded"" component=tsdb segment=89 maxSegment=91"
"time=2025-03-21T03:43:42.032Z level=INFO source=head.go:795 msg=""WAL segment loaded"" component=tsdb segment=90 maxSegment=91"
"time=2025-03-21T03:43:42.032Z level=INFO source=head.go:795 msg=""WAL segment loaded"" component=tsdb segment=91 maxSegment=91"
"time=2025-03-21T03:43:42.032Z level=INFO source=head.go:832 msg=""WAL replay completed"" component=tsdb checkpoint_replay_duration=133.504971ms wal_replay_duration=980.865649ms wbl_replay_duration=170ns chunk_snapshot_load_duration=88.011992ms mmap_chunk_replay_duration=18.89737ms total_replay_duration=1.221332779s"
"time=2025-03-21T03:43:42.116Z level=INFO source=main.go:1249 msg=""filesystem information"" fs_type=EXT4_SUPER_MAGIC"
"time=2025-03-21T03:43:42.116Z level=INFO source=main.go:1252 msg=""TSDB started"""
"time=2025-03-21T03:43:42.116Z level=INFO source=main.go:1437 msg=""Loading configuration file"" filename=/etc/config/prometheus.yml"
"time=2025-03-21T03:43:42.149Z level=INFO source=watcher.go:225 msg=""Starting WAL watcher"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write queue=5cd4b5"
"time=2025-03-21T03:43:42.149Z level=INFO source=metadata_watcher.go:90 msg=""Starting scraped metadata watcher"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write"
"time=2025-03-21T03:43:42.149Z level=INFO source=watcher.go:277 msg=""Replaying WAL"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write queue=5cd4b5"
"time=2025-03-21T03:43:42.149Z level=INFO source=kubernetes.go:323 msg=""Using pod service account via in-cluster config"" component=""discovery manager scrape"" discovery=kubernetes config=kube-state-metrics"
"time=2025-03-21T03:43:42.150Z level=INFO source=main.go:1486 msg=""Completed loading of configuration file"" db_storage=883ns remote_storage=32.8121ms web_handler=428ns query_engine=1.233µs scrape=48.458µs scrape_sd=457.845µs notify=1.094µs notify_sd=903ns rules=176.53µs tracing=6.676µs filename=/etc/config/prometheus.yml totalDuration=33.904832ms"
"time=2025-03-21T03:43:42.150Z level=INFO source=main.go:1213 msg=""Server is ready to receive web requests."""
"time=2025-03-21T03:43:42.150Z level=INFO source=manager.go:175 msg=""Starting rule manager..."" component=""rule manager"""
"time=2025-03-21T03:43:47.770Z level=INFO source=watcher.go:522 msg=""Done replaying WAL"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write duration=5.621042809s"
"time=2025-03-21T03:50:39.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:51:54.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:53:09.468Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:54:09.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:55:09.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:56:24.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:57:39.468Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T03:58:54.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T04:00:09.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T04:01:24.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"
"time=2025-03-21T04:02:39.469Z level=INFO source=queue_manager.go:709 msg=""Dropped sample for series that was not explicitly dropped via relabelling"" component=remote remote_name=5cd4b5 url=https://aps-workspaces.us-east-1.amazonaws.com/workspaces/<WS>/api/v1/remote_write ref=21931"```
