### ISSUE TITLE
AWS SD options does not support External ID

### ISSUE THREAD

**Issue by mohag** [prometheus/prometheus#16314]
### Proposal

[AWS recommends that roles use an external ID](https://aws.amazon.com/blogs/security/how-to-use-external-id-when-granting-access-to-your-aws-resources/) to avoid accidentally granting access to the wrong account.

When configuring ec2_sd or other AWS discovery configs, no option for specifying the external ID when assuming the role exists. (`external_id` is what I would suggest for it). This makes it impossible to use roles configured to require external IDs with Prometheus.

Affected discovery plugins:
* ec2_sd
* lightsail_sd

Other affected configs:
* alertmanager_config
* remote_write

**Comment by bboreham** [comment]
Hello from the bug-scrub!  We are awaiting a volunteer to do the work.

Would you be able to give an example of how the new config would look?  This might make it easier to see what is required.

**Comment by mohag** [comment]
It would have an external_id field alongside role_arn, access_key and secret_key. (It is only meaningful if there is a role specified)

(The docs does not have an example to tweak) (And I don't want to risk leaking account IDs)

Random example from internet tweaked:
```
# AWS Region Configuration
region: "us-west-2"
endpoint: "https://ec2.us-west-2.amazonaws.com"

# AWS Authentication (using role ARN in this example)
role_arn: "arn:aws:iam::123456789012:role/PrometheusServiceDiscovery"
external_id: "my external id for role here"

refresh_interval: 300s
port: 9100  # Default port for node_exporter

# EC2 Instance Filters
filters:
  - name: "tag:Environment"
    values: ["production"]
  - name: "instance-state-name"
    values: ["running"]
  - name: "tag:Service"
    values: ["web", "api"]
  - name: "vpc-id"
    values: ["vpc-0abc123def456789"]

follow_redirects: true
enable_http2: true
```

(That is for ec2_sd, but anywhere that role_arn for AWS is present should have it) (and role_arn should be present anywhere that AWS API creds are configured)
