### ISSUE TITLE
Add series: out-of-order series added with label set  Error

### ISSUE THREAD

**Issue by UmfintechWtc** [prometheus/prometheus#16399]
### What did you do?

i add hostname and ip to discovery default label。
```golang
	scrapeLabels := []labels.Label{
		{Name: model.JobLabel, Value: cfg.JobName},
		{Name: model.ScrapeIntervalLabel, Value: cfg.ScrapeInterval.String()},
		{Name: model.ScrapeTimeoutLabel, Value: cfg.ScrapeTimeout.String()},
		{Name: model.MetricsPathLabel, Value: cfg.MetricsPath},
		{Name: model.SchemeLabel, Value: cfg.Scheme},
		{Name: model.InstanceHostname, Value: lb.Labels()[len(lb.Labels())-2].Value},
		{Name: model.InstanceIPAddress, Value: lb.Labels()[len(lb.Labels())-1].Value},
	}
```

### What did you expect to see?

normal 

### What did you see instead? Under which circumstances?

This abnormal phenomenon occurs after running for a period of time, possibly 5 or 9 hours after startup. It was normal before this period of time. And not all metrics throw this exception, only a few metrics throw exceptions, like **node_arp_entries** metric.

![Image](https://github.com/user-attachments/assets/be97e085-d44b-4261-aa46-3323f898d828)

### System information

Linux 4.19.0-372.26.6.el8.x86_64

### Prometheus version

```text
prometheus, version 3.0.1 (branch: HEAD, revision: 1f56e8492c31a558ccea833027db4bd7f8b6d0e9)
  build user:       root@9c13055ffc3c
  build date:       20241128-17:20:55
  go version:       go1.23.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'upn'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
        - "/opt/app/mascloud/ansible/prometheus/cmd/prometheus/tcp.yaml"
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
  - job_name: 'upn1'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    file_sd_configs:
      - files:
        - "/opt/app/mascloud/ansible/prometheus/cmd/prometheus/tcp1.yaml"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115


# /opt/app/mascloud/ansible/prometheus/cmd/prometheus/tcp.yaml
- labels:
  targets:
  - prometheus-dc01:9090


# /opt/app/mascloud/ansible/prometheus/cmd/prometheus/tcp1.yaml
- labels:
  targets:
  - prometheus-dc02:9090
```

### Alertmanager version

```text
not use
```

### Alertmanager configuration file

```yaml
not use
```

### Logs

```text
time=2025-04-04T09:50:17.929+08:00 level=ERROR source=db.go:1103 msg="compaction failed" component=tsdb err="add series: out-of-order series added with label set \"{__name__=\\\"node_arp_entries\\\", device=\\\"eth0\\\", hostname=\\\"xxx:9100R\\\", instance=\\\"xxx:9100\\\", ip=\\\"xxx\\\", job=\\\"xxx\\\", plat=\\\"xxx\\\", res_pool=\\\"xxx\\\"}\", last label set \"{__name__=\\\"node_arp_entries\\\", device=\\\"eth0\\\", hostname=\\\"xxx:9100R\\\", instance=\\\"xxx:9100\\\", ip=\\\"xxx\\\", job=\\\"xxx\\\", plat=\\\"xxx\\\", res_pool=\\\"xxx\\\"}\""
time=2025-04-04T09:51:28.300+08:00 level=ERROR source=db.go:1103 msg="compaction failed" component=tsdb err="add series: out-of-order series added with label set \"{__name__=\\\"node_arp_entries\\\", device=\\\"eth0\\\", hostname=\\\"xxx:9100R\\\", instance=\\\"xxx:9100\\\", ip=\\\"xxx\\\", job=\\\"xxx\\\", plat=\\\"xxx\\\", res_pool=\\\"xxx\\\"}\", last label set \"{__name__=\\\"node_arp_entries\\\", device=\\\"eth0\\\", hostname=\\\"xxx:9100R\\\", instance=\\\"xxx:9100\\\", ip=\\\"xxx\\\", job=\\\"xxx\\\", plat=\\\"xxx\\\", res_pool=\\\"xxx\\\"}\""
```
