### ISSUE TITLE
label_join Allows Invalid Label Names in Prometheus 3.x

### ISSUE THREAD

**Issue by satjd** [prometheus/prometheus#16479]
### What did you do?

When creating labels with invalid names, Prometheus 3.x silently accepts them while 2.x properly rejects them with an error.

# Steps to Reproduce
Query: 
```promql
label_join(up, "~invalid", "-", "job")
```
## Execute above query in Prometheus 2.x
Error returns as expected: `Error executing query: invalid destination label name in label_join(): ~invalid`

![Image](https://github.com/user-attachments/assets/66eb99dd-5273-48f8-9e0d-0516728af26b)

## Execute above query in Prometheus 3.x
Query succeeds and returns a time series with the invalid label name *~invalid*.

![Image](https://github.com/user-attachments/assets/10bd1e5a-ff59-4165-95c4-d701b7b76d74)

### What did you expect to see?

Both versions should reject invalid label names per [Prometheus Label Naming Convention](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels):

> Labels may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*

### What did you see instead? Under which circumstances?

Query response from Prometheus 3.x succeeds and returns a time series with the invalid label name *~invalid*.

### System information

Darwin 24.3.0 arm64

### Prometheus version

```text
prometheus, version 3.3.0 (branch: HEAD, revision: 3c49e69330ceee9c587a1d994c78535695edff16)
  build user:       root@8e0258c9b91c
  build date:       20250415-13:35:09
  go version:       go1.24.1
  platform:         darwin/arm64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9092"]
       # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        labels:
          app: "prometheus"
```
