### ISSUE TITLE
Increased amount of writes to remote write

### ISSUE THREAD

**Issue by lukas-unity** [prometheus/prometheus#16486]
### What did you do?

From discussion in: https://cloud-native.slack.com/archives/C167KFM6C/p1745434739403739

We're recently upgraded to Prometheus (3.2.1 and later to 3.3) and we're seeing significantly increased samples per seconds/write throughout to our remote write backend (Mimir 2.15) 

Our samples per second are 30% higher and data write throughput is around 50% higher, than it was with 2.55

<img width="742" alt="Image" src="https://github.com/user-attachments/assets/95ed7c07-170f-4c3d-a091-0da674b323d7" />

Our remote write config is just this:

```
        remoteWrite:
        - url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push
          headers:
            X-Scope-OrgID: "our-tenant-prd"
          queueConfig:
            sampleAgeLimit: 600s
```

Sorry, if this has been reported by someone else. 

### What did you expect to see?

Similar samples per second and write throughput 

### What did you see instead? Under which circumstances?

Much higher samples per second and write throughput 

### Prometheus version

```text
prometheus, version 3.3.0 (branch: HEAD, revision: 3c49e69330ceee9c587a1d994c78535695edff16)
  build user:       root@b362765c931d
  build date:       20250415-13:32:00
  go version:       go1.24.1
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
remote_write:
- url: http://mimir-distributor.monitoring.svc.cluster.local:8080/api/v1/push
  remote_timeout: 30s
  headers:
    X-Scope-OrgID: our-tenant-prd
  protobuf_message: prometheus.WriteRequest
  follow_redirects: true
  enable_http2: true
  queue_config:
    capacity: 10000
    max_shards: 50
    min_shards: 1
    max_samples_per_send: 2000
    batch_send_deadline: 5s
    min_backoff: 100ms
    max_backoff: 1s
    sample_age_limit: 10m
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 2000
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
