### ISSUE TITLE
Alert has "firing" state despite the zero value of the expression

### ISSUE THREAD

**Issue by bakwc** [prometheus/prometheus#16543]
### What did you do?

Configured alert using following rule:

```
      - alert: xxxxxxx
        expr: 1 - clamp_max(((sum(rate(metric_name{label_one="value_one", label_two!="value_two"}[5m])) * 300) or 0), 1)
        for: 60m
        labels:
          severity: page
          alert_service: xxxxxx
        annotations:
          summary: "xxxxxx"
          description: "xxxxxxx"
```

### What did you expect to see?

When the value of expr is equal to zero - alert not firing, existing alert is auto-resolve.

### What did you see instead? Under which circumstances?

Alert is firing, despite the expression is equals to zero.

When going to `/api/v1/alerts` for my alert I see a following:
```
{
  "labels": {
    "alert_service": "xxxxxx",
    "alertname": "xxxxxx",
    "severity": "page"
  },
  "annotations": {
    "description": "xxxxxx",
    "summary": "xxxxx"
  },
  "state": "firing",
  "activeAt": "2025-05-02T13:43:47.970738249Z",
  "value": "0e+00"
}
```

 * it is firing despite **expression value equals to zero**
 * I have checked in grafana the value of expresion is zero
 * I have checked in prometheus link from alert (https://my-prometheus/graph?g0.expr=xxxxxxxx), and the value is zero.
 * I waited for a few hours after value become zero, and it's still firing, so it's probably not related to `for: 60m`

### Prometheus version

```text
version 2.38.0
```

### Prometheus configuration file

```yaml

```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text

```
