### ISSUE TITLE
False alert: mysqld.service is active but absent() triggers

### ISSUE THREAD

**Issue by jarvisbot01** [prometheus/prometheus#16627]
### What did you do?

I configured an alert in Prometheus to notify me if MariaDB is down using the following rule:

```bash
bat /etc/prometheus/rules/alert.rules.yml:
```

```yml
groups:
  - name: Alerts of MariaDB
    rules:
      - alert: MariaDB service not running
        expr: absent(node_systemd_unit_state{state="active",name="mysqld.service"}) == 1
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.name }} in instance {{ $labels.instance }} is not running"
          description: "The service {{ $labels.name }} has not been executed for more than 15 seconds."
```

### What did you expect to see?

I expected the alert to trigger only when the mysqld.service is not active (i.e., the MariaDB systemd service is not running).
When the service is running, the alert should remain inactive.

### What did you see instead? Under which circumstances?

Even though the mysqld.service is running (confirmed via systemctl and Prometheus query), the alert still fires incorrectly.

I verified that the following query returns a valid result:

```bash
absent(node_systemd_unit_state{name="mysqld.service",state="active"}) == 1
```

```bash
{name="mysqld.service", state="active"}
```

```bash
systemctl is-active mysqld
active
```

However, is still evaluated as true, and the alert is triggered even though the service is clearly active.

```bash
Service mysqld.service in instance localhost is not running
```

### System information

Linux 6.12.22+bpo-amd64 x86_64

### Prometheus version

```text
prometheus, version 3.4.0 (branch: HEAD, revision: 546b1d242e209ed4228aa01a248dbf3e41e573ea)
  build user:       root@b1749ffe17d4
  build date:       20250517-06:54:08
  go version:       go1.24.3
  platform:         linux/amd64
  tags:             netgo,builtinassets,stringlabels
```

### Prometheus configuration file

```yaml
# my global config
global:
  scrape_interval: 10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  query_log_file: /etc/prometheus/query.log

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "/etc/prometheus/rules/alert.rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"

    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "nginx-prometheus-exporter"

    static_configs:
      - targets: ["localhost:9113"]

  - job_name: "mysqld_exporter"

    static_configs:
      - targets: ["localhost:9104"]

  - job_name: "cavdisor"

    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8081"]
```

### Alertmanager version

```text
alertmanager, version 0.28.1 (branch: HEAD, revision: b2099eaa2c9ebc25edb26517cb9c732738e93910)
  build user:       root@fa3ca569dfe4
  build date:       20250307-15:05:18
  go version:       go1.23.7
  platform:         linux/amd64
  tags:             netgo
```

### Alertmanager configuration file

```yaml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telepush'

receivers:
  - name: 'telepush'
    webhook_configs:
      - url: 'https://telepush.dev/api/inlets/alertmanager/xxxxxx'
```

### Logs

```text
Prometheus logs

time=2025-05-22T17:14:39.084Z level=INFO source=main.go:674 msg="No time or size retention was set so using the default time retention" duration=15d
time=2025-05-22T17:14:39.084Z level=INFO source=main.go:725 msg="Starting Prometheus Server" mode=server version="(version=3.4.0, branch=HEAD, revision=546b1d242e209ed4228aa01a248dbf3e41e573ea)"
time=2025-05-22T17:14:39.084Z level=INFO source=main.go:730 msg="operational information" build_context="(go=go1.24.3, platform=linux/amd64, user=root@b1749ffe17d4, date=20250517-06:54:08, tags=netgo,builtinassets,stringlabels)" host_details="(Linux 6.12.22+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.12.22-1~bpo12+1 (2025-04-25) x86_64 jarvis (none))" fd_limits="(soft=65536, hard=65536)" vm_limits="(soft=unlimited, hard=unlimited)"
time=2025-05-22T17:14:39.085Z level=INFO source=main.go:806 msg="Leaving GOMAXPROCS=1: CPU quota undefined" component=automaxprocs
time=2025-05-22T17:14:39.086Z level=INFO source=web.go:656 msg="Start listening for connections" component=web address=0.0.0.0:9090
time=2025-05-22T17:14:39.087Z level=INFO source=main.go:1266 msg="Starting TSDB ..."
time=2025-05-22T17:14:39.093Z level=INFO source=head.go:657 msg="Replaying on-disk memory mappable chunks if any" component=tsdb
time=2025-05-22T17:14:39.093Z level=INFO source=head.go:744 msg="On-disk memory mappable chunks replay completed" component=tsdb duration=1.851µs
time=2025-05-22T17:14:39.094Z level=INFO source=head.go:752 msg="Replaying WAL, this may take a while" component=tsdb
time=2025-05-22T17:14:39.096Z level=INFO source=tls_config.go:347 msg="Listening on" component=web address=[::]:9090
time=2025-05-22T17:14:39.097Z level=INFO source=tls_config.go:350 msg="TLS is disabled." component=web http2=false address=[::]:9090
time=2025-05-22T17:14:39.097Z level=INFO source=head.go:825 msg="WAL segment loaded" component=tsdb segment=0 maxSegment=0 duration=3.045278ms
time=2025-05-22T17:14:39.097Z level=INFO source=head.go:862 msg="WAL replay completed" component=tsdb checkpoint_replay_duration=22.206µs wal_replay_duration=3.064468ms wbl_replay_duration=143ns chunk_snapshot_load_duration=0s mmap_chunk_replay_duration=1.851µs total_replay_duration=3.13312ms
time=2025-05-22T17:14:39.102Z level=INFO source=main.go:1287 msg="filesystem information" fs_type=EXT4_SUPER_MAGIC
time=2025-05-22T17:14:39.102Z level=INFO source=main.go:1290 msg="TSDB started"
time=2025-05-22T17:14:39.102Z level=INFO source=main.go:1475 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
time=2025-05-22T17:14:39.106Z level=INFO source=main.go:1514 msg="updated GOGC" old=100 new=75
time=2025-05-22T17:14:39.106Z level=INFO source=main.go:1524 msg="Completed loading of configuration file" db_storage=1.289µs remote_storage=1.345µs web_handler=557ns query_engine=15.399µs scrape=301.755µs scrape_sd=103.646µs notify=128.814µs notify_sd=74.75µs rules=2.32776ms tracing=6.063µs filename=/etc/prometheus/prometheus.yml totalDuration=3.360957ms
time=2025-05-22T17:14:39.106Z level=INFO source=main.go:1251 msg="Server is ready to receive web requests."
time=2025-05-22T17:14:39.106Z level=INFO source=manager.go:175 msg="Starting rule manager..." component="rule manager"

Alertmanager logs

time=2025-05-22T17:13:42.082Z level=INFO source=main.go:191 msg="Starting Alertmanager" version="(version=0.28.1, branch=HEAD, revision=b2099eaa2c9ebc25edb26517cb9c732738e93910)"
time=2025-05-22T17:13:42.082Z level=INFO source=main.go:192 msg="Build context" build_context="(go=go1.23.7, platform=linux/amd64, user=root@fa3ca569dfe4, date=20250307-15:05:18, tags=netgo)"
time=2025-05-22T17:13:42.101Z level=INFO source=cluster.go:185 msg="setting advertise address explicitly" component=cluster addr=10.46.0.5 port=9094
time=2025-05-22T17:13:42.114Z level=INFO source=cluster.go:674 msg="Waiting for gossip to settle..." component=cluster interval=2s
time=2025-05-22T17:13:42.143Z level=INFO source=coordinator.go:112 msg="Loading configuration file" component=configuration file=/etc/alertmanager/alertmanager.yml
time=2025-05-22T17:13:42.144Z level=INFO source=coordinator.go:125 msg="Completed loading of configuration file" component=configuration file=/etc/alertmanager/alertmanager.yml
time=2025-05-22T17:13:42.150Z level=INFO source=tls_config.go:347 msg="Listening on" address=[::]:9093
time=2025-05-22T17:13:42.150Z level=INFO source=tls_config.go:350 msg="TLS is disabled." http2=false address=[::]:9093
time=2025-05-22T17:13:44.115Z level=INFO source=cluster.go:699 msg="gossip not settled" component=cluster polls=0 before=0 now=1 elapsed=2.000969648s
time=2025-05-22T17:13:52.118Z level=INFO source=cluster.go:691 msg="gossip settled; proceeding" component=cluster elapsed=10.003915385s
```

**Comment by beorn7** [comment]
It makes more sense to ask questions like this via our [community channels](https://prometheus.io/community) rather than in a GitHub issue. We use GitHub issues for bug reports and feature requests only.

**Comment by ghost** [comment]
> Hi there,
> 
> Just to clarify: the `absent()` function checks whether a time series exists at all. In your alert expression, if the series `node_systemd_unit_state{...}` is entirely missing, `absent(...) == 1` will evaluate to `true` and fire the alert.
> 
> However, the `node_systemd_unit_state` metric itself _does_ exist even when the service is inactive — it simply returns `0` instead of `1`. So if the exporter is emitting that metric, the `absent()` expression will not fire — even if the service is stopped.
> 
> My suspicion is that `node_exporter` isn't collecting `node_systemd_unit_state` at all in your setup — possibly due to lack of DBus access, or AppArmor restrictions.
> 
> Could you please share the logs of your `node_exporter` container or service? That would help confirm whether the systemd collector is working correctly.

You're right, just removed the absent() function part and set equal to zero, now works as expected, sorry for this dummy issue.

Here is the complete snippet:

```
- name: Alertas de MariaDB
    rules:
      - alert: Servicio MariaDB no en ejecución
        expr: node_systemd_unit_state{state="active",name="mariadb.service"} == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "El servicio {{ $labels.name }} en la instancia {{ $labels.instance }} no se está ejecutando"
          description: "El servicio {{ $labels.name }} lleva más de 15 segundos sin ejecutarse."
```
