### ISSUE TITLE
relabel_config support regex capture groups replace string with others

### ISSUE THREAD

**Issue by seaurching** [prometheus/prometheus#16646]
### Proposal

I have a configuration like this.
```     
    - action: replace
      regex: yunikorn_(.*)_queue_app
      replacement: $1
      sourceLabels:
      - __name__
```
The `$1` capture groups content is `kcde.scheduler`, I hope replace the string `.` to string `-` with regex like bash-shell's schema `"${the//./-}"`.
Can support this?
