### ISSUE TITLE
relabel_configs don't have any effect

### ISSUE THREAD

**Issue by ariel-rivo** [prometheus/prometheus#16749]
### What did you do?

```yaml
      relabel_configs:
      - source_labels: ["topic"]
        regex: "__amazon_msk_canary"
        action: drop
```

### What did you expect to see?

A metric without `__amazon_msk_canary` topics

### What did you see instead? Under which circumstances?

A metric with `__amazon_msk_canary` topics included

### System information

eks

### Prometheus version

```text
Build information
version	3.4.1
revision	aea6503d9bbaad6c5faff3ecf6f1025213356c92
```

### Prometheus configuration file

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  evaluation_interval: 15s
  external_labels:
    cluster: devtest
    prometheus: monitoring/kube-prometheus-stack-prometheus
    prometheus_replica: prometheus-kube-prometheus-stack-prometheus-0
runtime:
  gogc: 75
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: kube-prometheus-stack-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http-web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      enable_http2: true
      namespaces:
        own_namespace: false
        names:
        - monitoring
rule_files:
- /etc/prometheus/rules/prometheus-kube-prometheus-stack-prometheus-rulefiles-0/*.yaml
scrape_configs:
- job_name: msk
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
  convert_classic_histograms_to_nhcb: false
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  metric_name_validation_scheme: utf8
  metric_name_escaping_scheme: allow-utf-8
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [topic]
    separator: ;
    regex: __amazon_msk_canary
    replacement: $1
    action: drop
  static_configs:
  - targets:
    - b-1:11001
    - b-2:11001
storage:
  tsdb:
    outofordertimewindow: 0
```

### Alertmanager version

```text

```

### Alertmanager configuration file

```yaml

```

### Logs

```text
time=2025-06-18T15:17:17.204Z level=DEBUG source=manager.go:297 msg="Starting provider" component="discovery manager scrape" provider=static/6 subs=map[msk:{}]
```
