### ISSUE TITLE
relabel_config: how to replace value?

### ISSUE THREAD

**Issue by hryamzik** [prometheus/prometheus#1717]
My ```service``` label contains URL. I'd like to replace it with a host name:

```yml
      - source_labels: ['service']
        regex: '^https?://(\\w)+.*'
        target_label: 'service_nice'
        replacement: '$1'
```

But no new labels appear. What am I doing wrong?
