### ISSUE TITLE
Prometheus gets 503 when scraping target behind haproxy

### ISSUE THREAD

**Issue by quolix** [prometheus/prometheus#1741]
**What did you do?**
**What did you expect to see?**
**What did you see instead? Under which circumstances?**

We run pushgateway on mesos, and put it behind haproxy. curl and chrome can fetch the URL http://pushgateway.corp.quobyte.com:80/metrics with no problems (that's the one displayed in /targets), but prometheus shows a "server returned HTTP status 503 Service Unavailable" in /targets.

I'll dig deeper when I find time, but I thought I'll document the issue for others. 

**Environment**

* System information:

	Linux 3.10.0-327.18.2.el7.x86_64 x86_64

* Prometheus version: 

	0.19.2 / 23ca13c

* Prometheus configuration file:
```
scrape_configs:
  - job_name: "pushgateway"
    target_groups:
      - targets:
        - pushgateway.corp.quobyte.com
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
