### ISSUE TITLE
One scrape target is still marked as UP even though it's not been scraped for over a week

### ISSUE THREAD

**Issue by banks** [prometheus/prometheus#1776]
**Note** restarting the host "fixed" this issue, but I thought I'd report it in case it's useful for debugging as there is clearly a bug somewhere to get into this state.

**What did you do?**

We have 2 prometheus servers with same scrape config scraping from several hundred nodes each with a telegraf instance exposing metrics.

**What did you expect to see?**

The same number of "UP" scrape targets on each prometheus server.

**What did you see instead? Under which circumstances?**

One server had one fewer target for a week.

After diffing the `up` query responses I found the target in question and then looked at it's status on the `/status` page:

![image](https://cloud.githubusercontent.com/assets/120915/16491165/b9f429c8-3ed4-11e6-90d0-45c72b8a929b.png)

I't not been scraped for over a week but is still "UP"

Indeed if I look at any of it metrics on a graph, they just stopped being collected 10 days ago. 
![image](https://cloud.githubusercontent.com/assets/120915/16491299/5484e16c-3ed5-11e6-8b04-a852ea341c2d.png)

Note that the target in question is UP and being correctly scrape by the secondary prometheus host the whole time.

I can also curl the scrape endpont from the prometheus host just fine:

```
paul@prometheus.0 ~ $curl -v -o /dev/null http://172.18.12.185:9126/metrics
* Hostname was NOT found in DNS cache
*   Trying 172.18.12.185...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 172.18.12.185 (172.18.12.185) port 9126 (#0)
> GET /metrics HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 172.18.12.185:9126
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 1682046
< Content-Type: text/plain; version=0.0.4
< Date: Thu, 30 Jun 2016 14:26:45 GMT
<
{ [data not shown]
100 1642k  100 1642k    0     0  14.2M      0 --:--:-- --:--:-- --:--:-- 14.3M
* Connection #0 to host 172.18.12.185 left intact
```

So prometheus instance seems to just be stuck on this scrape and not trying at all. To confirm, restarting the prometheus process in question "fixed" it.

**Environment**

* System information:

	Linux 3.13.0-74-generic x86_64

* Prometheus version: 

```
prometheus, version 0.18.0 (branch: release-0.18, revision: f12ebd6)
  build user:       root@ebaf628123aa
  build date:       20160418-08:20:43
  go version:       go1.5.4
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    target_groups:
      - targets:
          - prometheus.0.dblayer.com:9090
          - prometheus.1.dblayer.com:9090
        labels:
          scrape_host: prometheus.0

  - job_name: 'discovered'
    file_sd_configs:
      - names:
        - /opt/prometheus/conf.d/*.yml
```

files in `/opt/prometheus/conf.d` just list hosts updated from a cron script that queries Chef server.

* Logs:
I didn't see anything obviously relevant there were a bunch of messages 
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
