### ISSUE TITLE
Federate endpoint returns empty response for query

### ISSUE THREAD

**Issue by svenmueller** [prometheus/prometheus#1811]
**What did you do?**

When i call endpoint `/federate?match[]={__name__%3D~"^monitor%3A.*"}` i get an empty response (status code `200`).

**What did you expect to see?**
The endpoint should return values having label starting with "monitor". Another query shows that the external label is set (see label external "monitor")

```
# TYPE node_netstat_IpExt_InBcastOctets untyped
node_netstat_IpExt_InBcastOctets{job="node",instance="xyz:9100",monitor="codelab-monitor"} 0 1468426209014
# TYPE node_vmstat_nr_written untyped
node_vmstat_nr_written{instance="xyz:9100",job="node",monitor="codelab-monitor"} 1.4616345e+07 1468426209014
# TYPE node_netstat_TcpExt_TCPOFOMerge untyped
node_netstat_TcpExt_TCPOFOMerge{job="node",instance="xyz:9100",monitor="codelab-monitor"} 1 1468426208080
```

**What did you see instead? Under which circumstances?**
Instead of values having label "monitor" i get an empty response with status code `200`.

**Environment**

* System information:

	Linux 3.13.0-91-generic x86_64

* Prometheus version: 

	prometheus, version 0.20.0 (branch: master, revision: aeab25c)
  build user:       root@77050118f904
  build date:       20160616-08:38:14
  go version:       go1.6.2

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/rules/sample.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
      
  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'node'
    scrape_interval: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.yaml
```

Any idea why the query doesn't match anything?
