### ISSUE TITLE
Non negligible divergence between recorded metric and original expression

### ISSUE THREAD

**Issue by noushi** [prometheus/prometheus#1832]
**What did you do?**
To speed up console node list, I created a record rule:
```
node:cpu_iowait:cur_avg = 100 * (avg without(cpu, mode) (irate(node_cpu{mode='iowait'}[5m])))
```

**What did you expect to see?**
I expected the recorded metric to be almost identical to the original expression. 

**What did you see instead? Under which circumstances?**
Instead, graphing 
```
abs(100 * (avg without(cpu, mode) (irate(node_cpu{mode='iowait'}[5m]))) - node:cpu_iowait:cur_avg)
```
shows a divergence of more than 20% on multiple occasions:
![prom_divergence_between_cpu_iowait_recorded_and_original-15m_window png](https://cloud.githubusercontent.com/assets/4186288/16979381/a99a3ed0-4e58-11e6-84b7-e392f82297cb.png)
![prom_divergence_between_cpu_iowait_recorded_and_original-6h_window](https://cloud.githubusercontent.com/assets/4186288/16979380/a993c7da-4e58-11e6-94c9-67678fb8ffe2.png)

DISCLAIMER: The server showing the highest divergence is one our most busiest.

**Environment**

* System information:

```
$ uname -srm
Linux 3.19.0-61-generic x86_64`
```

* Prometheus version: 
I'm using a Docker container.

From `/status`:
```
Version 	0.20.0
Revision 	aeab25c
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

rule_files:
   - rules/node_speedup.rules

scrape_configs:

  - job_name: 'node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        <node_list>
        ...
```

* Logs:

I didn't see any relevant entries.
