### ISSUE TITLE
[Feature]  can we partition nodes when monitor kubernetes nodes? 

### ISSUE THREAD

**Issue by liuguoming** [prometheus/prometheus#1880]
**What did you do?**
monitoring part of all nodes of kubernetes

**What did you expect to see?**
just monitoring  some nodes of kubernetes nodes, not all of them.

there are 3 nodes under my k8s.  I just want to monitor one of them. 
but there's no item to config that.

* Prometheus configuration file:
```

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'k8s-cluster'
    scheme: https
    kubernetes_sd_configs:
      - api_servers:
        - 'http://localhost:8080'
        in_cluster: false
        role: node
    tls_config:
      insecure_skip_verify: true

```
