### ISSUE TITLE
No way to use anchors in YAML config file 

### ISSUE THREAD

**Issue by atombender** [prometheus/prometheus#1884]
It's desirable to reuse configuration to avoid duplication (which can lead to drift or copy/paste mistakes). For example, this ought to be possible:

```yaml
_:
  k8s_tls_config: &k8s_tls_config
    # This TLS & bearer token file config is used to connect to the actual scrape
    # endpoints for cluster components. This is separate to discovery auth
    # configuration (`in_cluster` below) because discovery & scraping are two
    # separate concerns in Prometheus.
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    # FIXME: Kubelet runs with a self-signed cert, so we have to skip verification
    insecure_skip_verify: true

# ...

scrape_configs:
- job_name: 'kubernetes-cluster'
  tls_config: *k8s_tls_config
```

However, this will cause Prometheus to reject the config file:

```
time="2016-08-10T17:57:14Z" level=error msg="Couldn't load configuration (-config.file=/var/prometheus/prometheus.yml): unknown fields in config: _" source="main.go:218" 
```

I don't see any non-schema-validated key where I can attach dummy anchors. In the absence of this, I propose that it ignore keys starting with `_`, for example.

(Is there a hacky workaround I use in the meantime, however?)

**Comment by fabxc** [comment]
I never used it myself but could writing it out in the first occurence work and then referencing it in subsequent ones?

Personally, I'd strongly recommend letting configuration management handle that though.

**Comment by atombender** [comment]
Maybe I can define the name in the first job and then refer to the anchor in subsequent jobs (is that what you meant?). Didn't occur to me because I — probably wrongly! — assumed anchors were scoped by nesting level.

I'm using Kubernetes configmaps, which don't have any templating support, and it's nice to be able to write YAML without templating, given that it actually has this kind of macro support.

**Comment by atombender** [comment]
So that seemed to work:

```yaml
  - job_name: 'kubernetes-cluster'
    tls_config: &k8s_tls_config
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true

  - job_name: 'kubernetes-apiserver'
    tls_config: *k8s_tls_config
```

That doesn't let me use the `<<` syntax anywhere, so I can't do this:

```yaml
_:
  kubernetes_target: &kubernetes_target
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: true

# ...

scrape_configs:
- <<: *kubernetes_target
  job_name: 'kubernetes-cluster'
```

As you probably know, `<<` merges the anchor into the parent key.
