### ISSUE TITLE
Kubernetes: Memory usage continually increases. Process enters crash recovery loop.

### ISSUE THREAD

**Issue by fluxrad** [prometheus/prometheus#1885]
### Summary
3 million series appear to exhaust memory on a 32GB m4.2xlarge

I'm attempting to use Prometheus to monitor a 68 node kubernetes cluster, with node-exporter and kubernetes scrape configs. When I scrape container-level metrics from the `node` role, I notice that the number of series begins to approach ~3 million around 24 hours. At this point, the process is killed by the kernel with an OOM error. Prometheus is running on a 32GB (AWS: m4.2xlarge) machine with no resource limits:

```yaml
# Prometheus pod spec
    spec: 
      containers: 
      - image: prom/prometheus:latest
        imagePullPolicy: Always
        name: prometheus
        args:
          - -config.file=/prometheus-config/config/prometheus.yml
          - -storage.local.memory-chunks=10000000
          - -storage.local.max-chunks-to-persist=5000000
          - -alertmanager.url=http://alertmanager.kube-system.svc.cluster.local:9093
        volumeMounts:
          - name: prometheus-persistent-storage
            mountPath: /prometheus
          - name: prometheus-config
            mountPath: /prometheus-config
```

After approximately 24 hours, the kernel OOM kills the prometheus docker process, at which point the docker container enters a crash loop trying to recover metrics.

```
# Capture from `journalctl`
Aug 11 13:56:37 <redacted> kernel: Out of memory: Kill process 2464 (prometheus) score 1975 or sacrifice child
Aug 11 13:56:37 <redacted> kernel: Killed process 2464 (prometheus) total-vm:32158388kB, anon-rss:32083796kB, file-rss:0kB, shmem-rss:0kB
```

The only recovery mechanism from here is to clear storage and restart prometheus. Both `storage.local.memory-chunks` and `storage.local.max-chunks-to-persist` flags seem to have no impact on how quickly the process runs out of memory, or how much memory prometheus consumes overall.

By my calculations 3 million series should consume somewhere between 6-9 million chunks in memory, or 6-9GB. Assuming overhead for queries and general memory consumption, memory usage should still be well under the 32GB provided by the machine. Is this assumption accurate? If so, where is the rest of the memory going? I've mitigated the issue by dropping all container-level metrics from kubernetes node scrapes.

### Prometheus memory-hungry config:

```yaml
# Prometheus config
rule_files:
  - <redacted>

scrape_configs:
- job_name: 'prometheus'

  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s

  static_configs:
    - targets: ['localhost:9090']

- job_name: 'kubernetes-apiserver'

  scheme: https
  tls_config:
    blah

  kubernetes_sd_configs:
  - api_servers:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    role: apiserver

  relabel_configs:
  - source_labels: [__meta_kubernetes_role]
    action: keep
    regex: apiserver
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__meta_kubernetes_role]
    action: replace
    target_label: kubernetes_name


- job_name: 'kubernetes-nodes'
  # This job seems to scrape the lion's share of series

  scheme: https
  tls_config:
    blah

  kubernetes_sd_configs:
  - api_servers:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    role: node

  relabel_configs:
  - source_labels: [__meta_kubernetes_role]
    action: keep
    regex: node
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__meta_kubernetes_role]
    action: replace
    target_label: kubernetes_name

- job_name: 'kubernetes-service-endpoints'

  kubernetes_sd_configs:
  - api_servers:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    role: endpoint

  relabel_configs:
  - source_labels: [__meta_kubernetes_role, __meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: endpoint;true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: (.+)(?::\d+);(\d+)
    replacement: $1:$2
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_role]
    action: replace
    target_label: kubernetes_role
  - source_labels: [__meta_kubernetes_service_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name

- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - api_servers:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_role, __meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: pod;true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: (.+)(?::\d+);(\d+)
    replacement: $1:$2
  - source_labels: [__meta_kubernetes_role]
    action: replace
    target_label: kubernetes_role
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_role]
    action: replace
    target_label: kubernetes_role
  - source_labels: [__meta_kubernetes_pod_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_name
  - source_labels: [__meta_kubernetes_pod_address]
    action: replace
    target_label: kubernetes_address
  - source_labels: [__meta_kubernetes_pod_container_name]
    action: replace
    target_label: kubernetes_container_name
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: replace
    target_label: kubernetes_container_port_name
```

### Host information

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=1010.5.0
VERSION_ID=1010.5.0
BUILD_ID=2016-05-26-2225
PRETTY_NAME="CoreOS 1010.5.0 (MoreOS)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
```

We do perform a number of production deploys per day, which I expect will contribute significantly to unique time-series metrics coming from the hosts themselves as containers come and go. Even so, I'd expect to be able to handle a week's worth of metrics.

At this point, I'm uncertain how to tell whether or not we have a configuration issue, or whether or not 3 million series simply won't fit onto a 32GB machine. I'm hoping someone can advise.

- What's the unique number of series (ballpark) that should reasonably be expected to fit on a 32GB machine? I've read issues #1836 and #455 but the numbers don't seem to fit with the experience above. 

- When does prometheus purge series from memory to live on disk exclusively? Do series data for old containers stay in memory until they're purged by the default retention policy, or are they eventually evicted to disk first?

Thanks very much for your help.
