### ISSUE TITLE
Kubernetes Q: Use "node_exporter" vs. scrape the node api?

### ISSUE THREAD

**Issue by dstroot** [prometheus/prometheus#1886]
The example prometheus kubernetes config will scrape nodes using the config below, but there is also the "node_exporter" which will expose node metrics.  I am confused as to what overlap (if any) there is and what is the best approach?  Use both or one vs the other?  Thanks!

Note - using config from the docs: https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml

snippet:
```
- job_name: 'kubernetes-nodes'

  # Default to scraping over https. If required, just disable this or change to
  # `http`.
  scheme: https

  # This TLS & bearer token file config is used to connect to the actual scrape
  # endpoints for cluster components. This is separate to discovery auth
  # configuration (`in_cluster` below) because discovery & scraping are two
  # separate concerns in Prometheus.
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    # If your node certificates are self-signed or use a different CA to the
    # master CA, then disable certificate verification below. Note that
    # certificate verification is an integral part of a secure infrastructure
    # so this should only be disabled in a controlled environment. You can
    # disable certificate verification by uncommenting the line below.
    #
    # insecure_skip_verify: true
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  kubernetes_sd_configs:
  - api_servers:
    - 'https://kubernetes.default.svc'
    in_cluster: true
    role: node

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
```
