### ISSUE TITLE
Zookeeper treecache may end up in a state where it no longer receives updates

### ISSUE THREAD

**Issue by StephanErb** [prometheus/prometheus#1895]
**What did you do?**
We have setup our Prometheus server to perform service discovery using [zookeeper server sets](https://prometheus.io/docs/operating/configuration/#<serverset_sd_config).

**What did you expect to see?**
Prometheus view of the available targets is in sync with what is written in Zookeeper. This has been working as expected for months without any issues.

**What did you see instead? Under which circumstances?**
During a network problem or short zookeeper downtime, Prometheus ended up in a state where it was no longer notified by changes performed in Zookeeper. This resulted in Prometheus not scraping all intended targets.

The prometheus log contained the following log message:

```
time="2016-07-26T04:19:33Z" level=info msg="Failed to set previous watches: write tcp 10.x.x.60:50016->10.x.x.1:2182: write: broken pipe" source="treecache.go:31"
```

Restarting the Prometheus server 'fixed' the issue. After the restart, Prometheus has correctly discovered the current cluster state and has been properly receiving all Zookeeper update since then.

The root cause seems to be related to the used zookeeper go library.  Other users of the same library report similar issues (https://github.com/wvanbergen/kafka/issues/76). In particular, they report that this merged pull request (https://github.com/samuel/go-zookeeper/pull/87) could help to prevent the issue. Bumping the vendored library version within the Prometheus might therefore be a good idea.

**Environment**
- Zookeeper: 3.3.5
- Prometheus version: 0.20.0
- Prometheus configuration file:

```
scrape_configs:  
  - job_name: 'aurora'
    metrics_path: /metrics
    serverset_sd_configs:
    - servers:
      - '10.x.x.1:2182'
      - '10.x.x.2:2182'
      - '10.x.x.3:2182'
      paths:
      - '/aurora'
```
