### ISSUE TITLE
Monitoring Kubernetes using Prometheus

### ISSUE THREAD

**Issue by aktarali** [prometheus/prometheus#1911]
Hi;

I am running a Prometheus instance external to the Kubernetes cluster. I am trying to use  this instance to scrape Kubernetes cluster. Here is my prometheus.yaml file:

```
global:
  scrape_interval: "15s"     # By default, scrape targets every 15 seconds.
  evaluation_interval: "15s" # By default, evaluate rules every 15 seconds.

scrape_configs:
- job_name: "prometheus"
  scrape_interval: "15s"
  metrics_path: "/metrics"
  target_groups:
    - targets: ["localhost:9090"]
    - targets: ["192.168.1.31:9100"]
    - targets: ["node6.crmld.com:9110"]

#Kubernetes
- job_name: "K8s Cadvisor"
 scrape_interval: "15s"
 metrics_path: "/metrics"
 target_groups:
   - targets: ["http://node6.crml.com:4001"] #Cadvisor

- job_name: "K8s APIserver"
 scrape_interval: "15s"
 metrics_path: "/metrics"
 target_groups:
   - targets: ["http://node6.crml.com:8888"] #APIserver

- job_name: "K8s Kublet"
  kubernetes_sd_configs:
    - api_servers: 'http://node6.crml.com:8888'
  relabel_configs:
    - source_labels: ["__meta_kubernetes_role"]
      action: "keep"
      regex: "node"
```

I keep getting the following errors:

```
Aug 19 17:15:41 node1 prometheus: time="2016-08-19T17:15:41+01:00" level=error msg="Couldn't load configuration (-config.file=/opt/prometheus/prometheus.yml): \"http://node6.crmld.com:4001/metrics\" is not a valid hostname" file=main.go line=177
Aug 19 17:15:41 node1 prometheus: time="2016-08-19T17:15:41+01:00" level=error msg="Note: The configuration format has changed with version 0.14. Please see the documentation (http://prometheus.io/docs/operating/configuration/) and the provided configuration migration tool (https://github.com/prometheus/migrate)." file=main.go line=178
```

However, when I use my browser to go to http://http://node6.crmld.com:4001/metrics I can see all the metrics.

Can someone please help, its probably something quite simple?

Thanks
Ali.
