### ISSUE TITLE
Question: Configure Prometheus to scrape metrics from k8s nginx-containers with nginx-exporter

### ISSUE THREAD

**Issue by Blasterdick** [prometheus/prometheus#2009]
Can't get how to scrape pod-level labels only for pods with openresty and [nginx-exporter](https://github.com/discordianfish/nginx_exporter) containers deployed (port 9113). 

Now I have default config, where job 'kubernetes-service-endpoints' scrapes metrics from nginx-exporter out-of-box, but I can't get how to scrape labels, such as pod_name, etc.

  ```
  - job_name: 'kubernetes-service-endpoints'
      scheme: http
      kubernetes_sd_configs:
      - api_servers:
        - 'https://kubernetes.default.svc'
        in_cluster: true
        role: endpoint
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_service_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
```

Also, I have such a job:

```
    - job_name: 'kubernetes-nginx-exporter'
      static_configs:
        - targets: ['nginx-exporter.default.svc.cluster.local:9113']
```

Which scrapes no container or pod labels at all (eventually?) 

Thanks in advance for any kind of help.
