### ISSUE TITLE
Make external labels available in federation matchers

### ISSUE THREAD

**Issue by h0tbird** [prometheus/prometheus#2046]
**What did you do?**
I am experimenting with horizontal scalability, sharding and multiple cross-federated servers.

**What did you expect to see?**
External labels in federation matchers.

**What did you see instead? Under which circumstances?**
No external labels in federation matchers. Always.

In a multiple cross-federated setup external labels are not on every time series so those can be used to filter some targets.

Find below a sample setup which will use the requested feature:
```
global:
 external_labels:
  shard: 0
 scrape_interval: 15s
 scrape_timeout: 10s
 evaluation_interval: 10s

rule_files:
 - /etc/prometheus/recording.rules
 - /etc/prometheus/alerting.rules

alerting:
 alert_relabel_configs:
 - source_labels: [shard]
   action: replace
   replacement: 'all'
   target_label: shard

scrape_configs:

 - job_name: 'federate'
   honor_labels: true
   metrics_path: /federate
   params:
    match[]:
     - '{shard=~"1|2"}'
   static_configs:
    - targets:
      - 'master-0:9090'
      - 'master-1:9090'
      - 'master-2:9090'

 - job_name: 'node'
   file_sd_configs:
    - files:
      - /etc/prometheus/targets/node.yml
   relabel_configs:
   - source_labels: [__address__]
     modulus: 3
     target_label: __tmp_hash
     action: hashmod
   - source_labels: [__tmp_hash]
     regex: ^0$
     action: keep
```
