### ISSUE TITLE
Average value not calculated right?

### ISSUE THREAD

**Issue by slavede** [prometheus/prometheus#2051]
**What did you do?**
Tried to get average value

**What did you expect to see?**
Correctly calculated value

**What did you see instead? Under which circumstances?**
Wrong value

**Environment**
![current_val](https://cloud.githubusercontent.com/assets/2838038/19040398/2a1a64de-8984-11e6-8268-9fecb2caaf6e.png)
![avg](https://cloud.githubusercontent.com/assets/2838038/19040399/2a3cf3f0-8984-11e6-98b1-3b15f61f78b1.png)

* System information:

Linux 2.6.32-358.el6.x86_64 x86_64

* Prometheus version: 

  build user:       root@3e392b8b8b44
  build date:       20160916-11:36:30
  go version:       go1.6.3

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9091']


```

* Alertmanager configuration file:
```
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

Similar question here:
http://stackoverflow.com/questions/39831998/how-does-prometheus-db-calculate-average-value
