### ISSUE TITLE
Increase issue

### ISSUE THREAD

**Issue by slavede** [prometheus/prometheus#2052]
**What did you do?**
Tried to get increase over one minute.

**What did you expect to see?**
Increase values

**What did you see instead? Under which circumstances?**
I've got No datapoints found

![image](https://cloud.githubusercontent.com/assets/2838038/19071388/28b44996-8a30-11e6-82e2-72bbe3d58cc8.png)

**Environment**

* System information:

    Linux 2.6.32-358.el6.x86_64 x86_64

* Prometheus version: 

prometheus, version 1.1.3 (branch: master, revision: ac374aa6748e1382dbeb72a00abf47d982ee8fff)
  build user:       root@3e392b8b8b44
  build date:       20160916-11:36:30
  go version:       go1.6.3

* Alertmanager version:

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     60s # By default, scrape targets every 60 seconds.
  evaluation_interval: 60s # By default, scrape targets every 60 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    # scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9091']


```

* Alertmanager configuration file:
```
```

* Logs:
```
```

Should not I see jumps where value increased? Instead I've got "No datapoints found"
