### ISSUE TITLE
Prometheus 1.2.0 suddenly stops scraping targets

### ISSUE THREAD

**Issue by svenmueller** [prometheus/prometheus#2068]
**What did you do?**
Since upgrading from version 1.1.3 to version 1.2.0, Prometheus stops scraping *all* targets (node, prometheus) after some time. After restarting prometheus, it works properly for some time, but then it stops scraping all targets again.

**What did you expect to see?**
All targets should be in state "UP" and last scrape time should be less then 5 seconds (for node targets).

**What did you see instead? Under which circumstances?**
Targets show "UNKNOWN" instead of "UP".

**Environment**

* System information:

Linux 3.13.0-95-generic x86_64

* Prometheus version: 

prometheus, version 1.2.0 (branch: master, revision: 522c93361459686fe3687f5ffe68c2ee34ea5c8e)
  build user:       root@c8088ddaf2a8
  build date:       20161007-12:53:55
  go version:       go1.6.3

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      hostname: 'my-hostname'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/rules/*.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']


  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'node'
    scrape_interval: 5s
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/*.yaml

    relabel_configs:
      - source_labels: [__address__]
        regex: (.*):9100
        replacement: ${1}
        target_label: instance
      - source_labels: [instance]
        regex: .*\.([\w,-]+)\.ct-app\.com
        replacement: ${1}
        target_label: region
      - source_labels: [instance]
        regex: (\w+).*
        replacement: ${1}
        target_label: customer
      - source_labels: [instance]
        regex: .*-(dev|stage|prod)-.*
        replacement: ${1}
        target_label: environment
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets: # Target to probe
        - www.domain.de
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox:9115  # Blackbox exporter.
```

**Comment by grobie** [comment]
Anything in the log files?

**Comment by brian-brazil** [comment]
Can you grab a goroutine dump when this happens?

http://localhost:9090/debug/pprof/goroutine?debug=2

**Comment by svenmueller** [comment]
Hi,

The prometheus instance just stopped scraping again all targets. Here are the resquested resources:

full log: https://gist.github.com/svenmueller/f96bece4f7852e6d5e20be87d858b552
gorouting dump: https://gist.github.com/svenmueller/223e903ac7703354364d9cef824f6541

--Sven

**Comment by juliusv** [comment]
First of all, I see multiple problems in your log file:

- Prometheus does crash recovery (meaning it didn't shut down correctly): https://gist.github.com/svenmueller/f96bece4f7852e6d5e20be87d858b552#file-gistfile1-txt-L54
- then, it gets killed because the system is out of memory: https://gist.github.com/svenmueller/f96bece4f7852e6d5e20be87d858b552#file-gistfile1-txt-L841
- then it does crashrecovery again: https://gist.github.com/svenmueller/f96bece4f7852e6d5e20be87d858b552#file-gistfile1-txt-L1427

Most relevant however, it looks like your storage is sometimes throttled:

https://gist.github.com/svenmueller/f96bece4f7852e6d5e20be87d858b552#file-gistfile1-txt-L11

This means that targets will not get their samples stored anymore (at least intermittently), as the storage applies backpressure. If it's a new target, that will also cause it to stay in `UNKNOWN` state.

Looking at this part of the goroutine dump, the fact that it just says `[select]` and not `[select, xxx minutes]` means that Prometheus has just about being throttled, so that seemed to be the problem at the time you took the stacktrace:

https://gist.github.com/svenmueller/223e903ac7703354364d9cef824f6541#file-gistfile1-txt-L293-L297

You can also see that scrapers for your targets are in principle running:

https://gist.github.com/svenmueller/223e903ac7703354364d9cef824f6541#file-gistfile1-txt-L407-L429

But because the storage cannot keep up (probably disk IO problems?), it would hit this branch and not count the targets as scraped at all:

https://github.com/prometheus/prometheus/blob/master/retrieval/scrape.go#L430

Are you seeing the `prometheus_target_skipped_scrapes_total` counter metric going up?

I'm not sure if 1.2.0 changed relevant storage stuff, or whether it just so happens that something caused your storage to get overloaded around the same time...

**Comment by marcbradshaw** [comment]
I am seeing similar issues, I see a bunch of these errors in log

@4000000057fb08421a02beac time="2016-10-09T23:17:12-04:00" level=error msg="Error refreshing service list: Unexpected response code: 500 (rpc error: rpc error: fail
ed to get conn: rpc error: lead thread didn't get connection)" source="consul.go:127" 
@4000000057fb08421a09ac1c time="2016-10-09T23:17:12-04:00" level=error msg="Error refreshing service prom_node_exporter: Unexpected response code: 500 (rpc error: r
pc error: failed to get conn: rpc error: lead thread didn't get connection)" source="consul.go:218" 

followed by 

@4000000057fb087b3a033fec time="2016-10-09T23:18:09-04:00" level=warning msg="Storage has entered rushed mode." chunksToPersist=402607 maxChunksToPersist=524288 max
MemoryChunks=1048576 memoryChunks=1132516 source="storage.go:1587" urgencyScore=0.8005142211914062

**Comment by marcbradshaw** [comment]
dump https://gist.github.com/marcbradshaw/9f83c6e3bc6e359850c7b2f880fd6fd2

**Comment by svenmueller** [comment]
Hi,

After switching back to version 1.1.3, prometheus keeps scraping the targets properly again.

**Comment by beorn7** [comment]
I think I found the issue.

PR imminent.

**Comment by klausenbusk** [comment]
I think I have the same issues.
Prometheus 1.2.0 hasn't scrapped anything for 8 hours after throttling:
```
Oct 10 06:32:04 foo docker[24097]: time="2016-10-10T06:32:04Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=27008 maxChunksToPersist=524288 maxToleratedMemChunks=165000 memoryChunks=165042 source="storage.go:888"
```
Metrics from Prometheus: http://sprunge.us/ZVLI
Log file: http://sprunge.us/iMOM (sorry for all the json error, need to fix that).
prometheus.yml
```
scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spconnect'
    scrape_interval: 30s
    file_sd_configs:
      - files: ["/etc/prometheus/foo.json"]

  - job_name: "coreos"
    file_sd_configs:
      - files: ["/etc/prometheus/node_exporter.json"]
```
Prometheus is started as:
```
/bin/prometheus -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/var/lib/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -storage.local.memory-chunks 150000
```

Please say if you need more info.
Prometheus is running in a Debian Jessie Docker (1.10.3) container on a CoreOS 1122.2.0 stable on a DigitalOcean 2GB ram  node.
