### ISSUE TITLE
bad counter increase query result

### ISSUE THREAD

**Issue by NoumanSaleem** [prometheus/prometheus#2108]
<img width="1440" alt="screen shot 2016-10-20 at 12 07 57 pm" src="https://cloud.githubusercontent.com/assets/694071/19599534/0b20133c-9756-11e6-8db2-7dd0a7137833.png">

**What did you do?**
Ran a query to determine the increase in a counter for the last hour.

**What did you expect to see?**
The result to equal the `counter (now) - counter (offset 1hr)`

**What did you see instead? Under which circumstances?**
A value greater than the counter's current value.

**Environment**
- System information: 
  Linux 3.13.0-93-generic x86_64
- Prometheus version: 
  prometheus, version 1.1.1 (branch: master, revision: 24db241bd556fd45854dd310692ac291de7d24e1)
  build user:       root@90d3f69e2d67
  build date:       20160907-09:42:10
  go version:       go1.6.3
- Prometheus configuration file:

```
global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'service'
    consul_sd_configs:
    - server: 172.17.42.1:8500
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: ',((api|data)-service),'
        action: keep
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'
        target_label: __address__
      - source_labels: [__meta_consul_service]
        target_label: name
      - source_labels: [__meta_consul_tags]
        target_label: tags
```
