### ISSUE TITLE
Scraping in HTTPS return 404

### ISSUE THREAD

**Issue by commarla** [prometheus/prometheus#2126]
**What did you do?**
My team developed a service using the node.js library to export a /metrics.
I added it in my configuration.

**What did you expect to see?**
A correct scrape of this endpoint.
The /metrics page is displayed well (with a 200 return code) when I click on it from the targets page in prometheus.

**What did you see instead? Under which circumstances?**
A 404 Error `server returned HTTP status 404 Not Found` in the targets page.

**Environment**
- System information:

`Linux 3.16.0-4-amd64 x86_64`
- Prometheus version: 

```
prometheus, version 1.2.1 (branch: master, revision: dd66f2e94b2b662804b9aa1b6a50587b990ba8b7)
  build user:       root@fd9b0daff6bd
  build date:       20161010-15:58:23
  go version:       go1.7.1
```
- Prometheus configuration file:

```
  - job_name: 'my-job'
    scheme: https
    scrape_interval: 5s
    scrape_timeout: 3s
    static_configs:
      - targets: ['my-url:443']
```
- Logs:
  I see nothing revelant in the logfiles.
