### ISSUE TITLE
Alert can't be sent to alertmanager

### ISSUE THREAD

**Issue by zybjcdl** [prometheus/prometheus#2160]
I have setup prometheus and alertmanager in k8s environment. 
I can see alert show up in prometheus alert page, but in alertmanager page, I can't see any alert show up.  I am using image: quay.io/prometheus/alertmanager:latest

The prometheus page I visit is 
https://9.30.99.224/api/v1/proxy/namespaces/monitoring/services/prometheus/alerts
The alertmanager page is:
https://9.30.99.224/api/v1/proxy/namespaces/monitoring/services/alertmanager/#/alerts

Here is the prometheus command line flag:
alertmanager.url=http://localhost:8080/api/v1/proxy/namespaces/monitoring/services/alertmanager/

Here is alertmanager.yml file:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    app: alertmanager
  ports:
  - port: 9093 # the port that this service should serve on
    targetPort: 9093  # port on container
----
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: quay.io/prometheus/alertmanager:latest
        args:
          - '-config.file=/etc/alertmanager/config.yml'
          - '-storage.path=/alertmanager'
        ports:
        - name: alertmanager
          containerPort: 9093
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          #mountPath: /prometheus
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager
      - emptyDir: {}
        name: alertmanager
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |
    global:
      resolve_timeout: 5m
      # The smarthost and SMTP sender used for mail notifications.
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'zybjcdl@gmail.com'
      smtp_auth_username: '*****'
      smtp_auth_password: '****'
 route:
  receiver: default

 receivers:
   - name: default
     email_configs:
     - to: 'zybjcdl@gmail.com'
```
