### ISSUE TITLE
Can not see relabeled labels in queries

### ISSUE THREAD

**Issue by widgetpl** [prometheus/prometheus#2170]
**What did you expect to see?**
relabeled labels in queries

**What did you see instead? Under which circumstances?**
can not see relabeled labels in queries

* Prometheus version: 

	`quay.io/prometheus/prometheus:v1.3.0`

* Prometheus configuration file:
```
    - job_name: 'kubernetes-service-endpoints'
      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_label: [__meta_kubernetes_pod_host_ip]
        action: replace
        target_label: host_ip
      - source_labels: [__meta_kubernetes_service_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
```

During quierying i can not see relabeled labels in job configuration, f.e querying `node_load1` i get:

```
node_load1{app="node-exporter",instance="10.116.166.4:9100",job="kubernetes-service-endpoints",kubernetes_name="node-exporter",name="node-exporter"}	3.21
node_load1{app="node-exporter",instance="10.116.171.30:9100",job="kubernetes-service-endpoints",kubernetes_name="node-exporter",name="node-exporter"}	2.87
node_load1{app="node-exporter",instance="10.116.179.11:9100",job="kubernetes-service-endpoints",kubernetes_name="node-exporter",name="node-exporter"}	4.37
node_load1{app="node-exporter",instance="10.116.135.29:9100",job="kubernetes-service-endpoints",kubernetes_name="node-exporter",name="node-exporter"}	2.13
```

so i don't see my label:

```
- source_label: [__meta_kubernetes_pod_host_ip]
        action: replace
        target_label: host_ip
```
