### ISSUE TITLE
DNS lookup error in docker-compose

### ISSUE THREAD

**Issue by sigoden** [prometheus/prometheus#2214]
prometheus fail to dail server with name domain in docker-compose.

when navigate to `http://<promdash_host>/targets` page, it show errors: `
Get http://nodeexporter:9100/metrics: dial tcp 127.0.53.53:9100: getsockopt: connection refused
`

I ping the server  `docker-compose exec prometheus ping nodeexporter`, it works
```
PING nodeexporter (172.19.0.2): 56 data bytes
64 bytes from 172.19.0.2: seq=0 ttl=64 time=0.101 ms
64 bytes from 172.19.0.2: seq=1 ttl=64 time=0.077 ms
^C
--- nodeexporter ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.077/0.089/0.101 ms
```

this is my docker-compose.yaml file
```
version: "2.0"
services:
    nodeexporter:
        image: prom/node-exporter
        ports: 
            - '9100:9100'
    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./data/prom:/prometheus
        command:
            - '-config.file=/etc/prometheus/prometheus.yml'
            - '-storage.local.path=/prometheus'
        ports:
            - '9090:9090'
        depends_on:
            - nodeexporter
```

this is my prometheus.ymal file
```
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'saas'
scrape_configs:
    - job_name: 'default'
      static_configs:
          - targets: ['localhost:9090', 'nodeexporter:9100']
```
