### ISSUE TITLE
targets from consul never show up after upgrade to 1.4

### ISSUE THREAD

**Issue by onorua** [prometheus/prometheus#2220]
**What did you do?**
We have a server which was upgraded couple of hours ago, it got all the data loaded, but apparently did not do anything useful since that moment. 

When I press targets on GUI, it doesn't see anything, downgrade to 1.3.1 made the trick. I've checked and it seems no major changes to consul autodiscovery happened. 

**What did you expect to see?**
Smooth upgrade, restart, load files and continue to scrape 

**Environment**

* System information:
```
Linux 4.4.0-45-generic x86_64
```

* Prometheus version: 
```
prometheus, version 1.4.0 (branch: master, revision: ecad074e46ef60536722c5b01e6c5277f2b50a3d)
  build user:       root@5fb8bc2a8e57
  build date:       20161125-12:45:05
  go version:       go1.7.3
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'cloud'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Auto-discovery via consul tags by Registrator
  - job_name: 'consul-services'

    consul_sd_configs:
    - server: 'consul:8500'
      scheme: 'http'

    relabel_configs:
    - source_labels: [ '__meta_consul_tags' ]
      action: keep
      regex: .*exporter.*
    - source_labels: [ '__meta_consul_address', '__meta_consul_service_port' ]
      action: replace
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [ '__meta_consul_service' ]
      action: keep
      regex: (.+)
      replacement: $1
      target_label: __name__
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: (.*):(.*):(.*)
      replacement: $2
      target_label: container_name
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: (.*):(.*):(.*)
      replacement: $1
      target_label: host_name
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: .*-(\w*)-(\w*)-(\d*):(.*):(.*)
      replacement: $1
      target_label: colo
```

* Logs:
```
time="2016-11-25T13:53:49Z" level=info msg="All requests for rebuilding the label indexes queued. (Actual processing may lag behind.)" source="crashrecovery.go:529"
time="2016-11-25T13:53:49Z" level=warning msg="Crash recovery complete." source="crashrecovery.go:152"
time="2016-11-25T13:53:49Z" level=info msg="1657859 series loaded." source="storage.go:359"
time="2016-11-25T13:53:49Z" level=info msg="Starting target manager..." source="targetmanager.go:63"
time="2016-11-25T13:53:49Z" level=info msg="Listening on :9090" source="web.go:248"
time="2016-11-25T13:54:25Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-11-25T13:55:27Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1m1.956668514s." source="persistence.go:573"
```
and it was checkpointing all the time about once per minute.
