### ISSUE TITLE
prometheus skips scrapes due to throttling 

### ISSUE THREAD

**Issue by onorua** [prometheus/prometheus#2222]
**What did you do?**
Actually our prometheus got updated to version 1.4 which did not work well (https://github.com/prometheus/prometheus/issues/2220), so we rolled back to version 1.3.1, and this issue started to happen. 

**What did you expect to see?**
Don't skip scrapes every 2 hours or so. 

**What did you see instead? Under which circumstances?**
<img width="957" alt="screen shot 2016-11-26 at 6 32 48 pm" src="https://cloud.githubusercontent.com/assets/407040/20645098/ccff81dc-b406-11e6-8afd-49eeeaefab0c.png">

**Environment**
we run prometheus with following flags:
```
/bin/prometheus -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -storage.local.retention=193h -storage.local.chunk-encoding-version=1 -storage.local.memory-chunks=3145728 -alertmanager.url=http://alertmanager:9093
```
config follows, we don't do anything fancy, it is just a DO machine which was working fine for like a months until that upgrade happened. 

* System information:
`Linux 4.4.0-45-generic x86_64`

* Prometheus version: 
```
prometheus, version 1.3.1 (branch: master, revision: be476954e80349cb7ec3ba6a3247cd712189dfcb)
  build user:       root@37f0aa346b26
  build date:       20161104-20:24:03
  go version:       go1.7.3
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'cloud'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Auto-discovery via consul tags by Registrator
  - job_name: 'consul-services'

    consul_sd_configs:
    - server: 'consul:8500'
      scheme: 'http'

    relabel_configs:
    - source_labels: [ '__meta_consul_tags' ]
      action: keep
      regex: .*exporter.*
    - source_labels: [ '__meta_consul_address', '__meta_consul_service_port' ]
      action: replace
      regex: (.+)(?::\d+);(\d+)
      replacement: $1:$2
      target_label: __address__
    - source_labels: [ '__meta_consul_service' ]
      action: keep
      regex: (.+)
      replacement: $1
      target_label: __name__
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: (.*):(.*):(.*)
      replacement: $2
      target_label: container_name
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: (.*):(.*):(.*)
      replacement: $1
      target_label: host_name
    - source_labels: [ '__meta_consul_service_id' ]
      action: replace
      regex: .*-(\w*)-(\w*)-(\d*):(.*):(.*)
      replacement: $1
      target_label: colo
```

* Logs:
```
time="2016-11-27T00:58:34Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=447275 maxChunksToPersist=524288 maxMemoryChunks=3145728 memoryChunks=3169371 source="storage.go:1607" urgencyScore=0.8531093597412109
time="2016-11-27T00:59:56Z" level=info msg="Completed maintenance sweep through 1616945 in-memory fingerprints in 54m39.960566695s." source="storage.go:1180"
time="2016-11-27T01:03:34Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-11-27T01:03:35Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=524468 maxChunksToPersist=524288 maxToleratedMemChunks=3460300 memoryChunks=3152841 source="storage.go:908"
time="2016-11-27T01:04:53Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1m18.770319321s." source="persistence.go:573"
time="2016-11-27T01:09:53Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-11-27T01:11:14Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1m21.390220948s." source="persistence.go:573"
time="2016-11-27T01:16:14Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-11-27T01:17:35Z" level=info msg="Done checkpointing in-memory metrics and chunks in 1m21.080615741s." source="persistence.go:573"
time="2016-11-27T01:22:15Z" level=info msg="Storage does not need throttling anymore." chunksToPersist=510456 maxChunksToPersist=524288 maxToleratedMemChunks=3460300 memoryChunks=3145729 source="storage.go:916"
```

I'll do `/debug/pprof/goroutine?debug=2` as soon as I've get this happening the time I'll be online, but as it is holidays, it is getting tricky.
