### ISSUE TITLE
State: DOWN,  Error: context deadline exceeded

### ISSUE THREAD

**Issue by dakala** [prometheus/prometheus#2224]
**What did you do?**

The metrics endpoint of my web application seems to be working. I can curl it and get good data. I've added my configuration to prometheus.yml

**What did you expect to see?**

I expect to see the metrics Prometheus has scrapped.

**What did you see instead? Under which circumstances?**

When I view the Prometheus targets page, my endpoint is listed but it's reported as down with the error, "context deadline exceeded".

**Environment**

* System information:

	Darwin 15.6.0 x86_64

* Prometheus version:

	prometheus, version 1.3.1 (branch: master, revision: be476954e80349cb7ec3ba6a3247cd712189dfcb)
  build user:       root@37f0aa346b26
  build date:       20161104-20:27:37
  go version:       go1.7.3

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"
  - 'prometheus.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'my-job'
    scrape_interval: 20s
    static_configs:
      - targets: ['test-site.dev']
        labels:
          group: 'my-job-test'

  - job_name:       'example-random'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'

      - targets: ['localhost:8082']
        labels:
          group: 'canary'
```

Thanks for the attention.
