### ISSUE TITLE
Prometheus adds default http port to the Host header when querying targets. 

### ISSUE THREAD

**Issue by ddewaele** [prometheus/prometheus#2226]
**What did you do?**

Added a static config to monitor a webapp exposing a prometheus endpoint
```
    static_configs:
      - targets: ['someServer:80']
        labels:
          group: 'monitoring'
```

**What did you expect to see?**

The target is sitting behind a reverse proxy (haProxy) and we cannot access the target directly.
haProxy expected to see a `Host` header like this : 

```
Host : someServer
```

**What did you see instead? Under which circumstances?**

But instead saw was this : 

```
Host : someServer:80
```

Although this does not violate the http spec, the spec does allow for default http ports (80 / 443) to be stripped from the Host header. (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23).

We needed to modify our haProxy configuration so that it properly matched incoming http requests from prometheus.
