### ISSUE TITLE
federation is failing with `http: multiple response.WriteHeader calls` error

### ISSUE THREAD

**Issue by onorua** [prometheus/prometheus#2237]
**What did you do?**
Tried to increase amount of nodes for our prometheus more than 300 and decided to use federation 

**What did you expect to see?**
Seamless and working solution 

**What did you see instead? Under which circumstances?**
Some broken graphs, nothing is actually working

**Environment**

* System information:
`Linux prometheus-sfo2-prod-02 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

* Prometheus version: 
```
prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  scrape_timeout: 30s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'bhss'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Auto-discovery via consul tags by Registrator
  - job_name: 'federate'
    scrape_interval: 30s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="consul-services"}'

    static_configs:
      - targets:
        - 'prometheus1:9090'
```

* Logs:
on federation server everything seems to be fine:
```
time="2016-12-01T01:50:56Z" level=info msg="9757 series loaded." source="storage.go:359"
time="2016-12-01T01:50:56Z" level=info msg="Starting target manager..." source="targetmanager.go:63"
time="2016-12-01T01:50:56Z" level=info msg="Listening on :9090" source="web.go:248"
time="2016-12-01T01:59:31Z" level=info msg="Completed maintenance sweep through 13306 in-memory fingerprints in 8m33.461796469s." source="storage.go:1180"
time="2016-12-01T02:00:56Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-12-01T02:01:19Z" level=info msg="Done checkpointing in-memory metrics and chunks in 22.858885958s." source="persistence.go:573"
```

on federated server (the one which scrapes everything):
```
time="2016-12-01T01:30:49Z" level=info msg="Listening on :9090" source="web.go:248"
time="2016-12-01T01:30:49Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=1138834 maxChunksToPersist=2572864 maxMemoryChunks=2572864 memoryChunks=2925866 source="storage.go:1607" urgencyScore=1
time="2016-12-01T01:30:54Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=1137413 maxChunksToPersist=2572864 maxToleratedMemChunks=2830150 memoryChunks=2920720 source="storage.go:908"
time="2016-12-01T01:40:49Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-12-01T01:42:50Z" level=info msg="Done checkpointing in-memory metrics and chunks in 2m0.862111955s." source="persistence.go:573"
time="2016-12-01T01:44:40Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:45:11Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:45:44Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:46:13Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:46:45Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:47:16Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:47:59Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:48:28Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:48:58Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:49:29Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:49:57Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:52:42Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:52:50Z" level=info msg="Checkpointing in-memory metrics and chunks..." source="persistence.go:549"
time="2016-12-01T01:53:12Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:53:42Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:54:52Z" level=info msg="Done checkpointing in-memory metrics and chunks in 2m2.181545716s." source="persistence.go:573"
time="2016-12-01T01:55:34Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:56:04Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:56:34Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:57:04Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:57:34Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:58:04Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
time="2016-12-01T01:58:34Z" level=error msg="http: multiple response.WriteHeader calls\n" source="<autogenerated>:38"
```
