### ISSUE TITLE
Graph/query dialbox is dead in v1.4.1

### ISSUE THREAD

**Issue by theonlydoo** [prometheus/prometheus#2243]
**What did you do?**
Upgraded to 1.4.1
**What did you expect to see?**
A query interface
**What did you see instead? Under which circumstances?**
No query interface
**Environment**
Debian jessie, go 1.7.1
* System information:

`Linux 3.16.0-4-amd64 x86_64`

* Prometheus version: 

```
root@prometheus:~ $ prometheus -version
prometheus, version 1.4.1 (branch: HEAD, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root
  build date:       20161202-10:30:48
  go version:       go1.7.1
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  scrape_timeout:       15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'mon'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/rules/rules.system"
  - "/etc/prometheus/rules/rules.batchprom"
  - "/etc/prometheus/rules/rules.cassandra"
  - "/etc/prometheus/rules/rules.front"
  - "/etc/prometheus/rules/rules.kafka"
  - "/etc/prometheus/rules/rules.apps"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['127.0.0.1:9090']


### Infrastructure autoconf ###

scrape_configs:

  - job_name: 'node_exporter'
    scrape_interval: 30s
    file_sd_configs:
      - files:
```
