### ISSUE TITLE
Prometheus not returning all metrics

### ISSUE THREAD

**Issue by simonaws** [prometheus/prometheus#2258]
**What did you do?**
We are running prometheus and using blackbox exporter to ping  60+ targets and HTTP request + 10 web api targets. 

**What did you expect to see?**
count(probe_success{job="blackbox"}) returns a different count every time executed in prom UI. It seems that prometheus is not returning all scrapes.

Should we expect to see count(probe_success{job="blackbox"}) equal to the number of targets in our config file for that job?

**What did you see instead? Under which circumstances?**
We want the query count(probe_success{job="blackbox_icmp"}== 1) to return the number of targets up and  count(probe_success{job="blackbox_icmp"}== 0) to return the number of targets down but these queries result in different answers every time.

**Environment**

* System information:
Linux 3.10.0-327.36.1.el7.x86_64 x86_64

* Prometheus version: 
prom/prometheus:v1.2.1

* Prometheus configuration file:
```
  
rule_files:
  - '/prometheus/alert.rules'

scrape_configs:

  ###############
  - job_name: 'prometheus'
    scrape_interval: 20s
    static_configs:
      - targets: ['prometheus:9090']
    relabel_configs:
      - source_labels: [__metrics_path__ ]
        regex: .*
        replacement:   '/prometheus/metrics'
        target_label:  __metrics_path__

  #############
  - job_name: 'blackbox_icmp'
    scrape_interval: 20s
    metrics_path: /probe
    params:
      module: [icmp] 
    file_sd_configs:
    - files: ['targets/blackbox-ping.json']
      refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: __param_target
        replacement: ${1}
      - target_label: __address__
        replacement: blackbox:9115


   ###############
  - job_name: 'blackbox_http'
    scrape_interval: 20s
    metrics_path: /probe
    file_sd_configs:
    - files: ['targets/blackbox-http.json']
      refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__blackbox_module]
        target_label: __param_module
      - target_label: __address__
        replacement: blackbox:9115

  ###############
  - job_name: 'node-exporter'
    scrape_interval: 1m
    file_sd_configs:
    - files: ['targets/node-exporter.json']
      refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__, __node_exporter_port]
        separator:     ':'
        target_label: __address__


insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
