### ISSUE TITLE
Target "prometheus" in docker image is always DOWN

### ISSUE THREAD

**Issue by goofansu** [prometheus/prometheus#2260]
**What did you do?**

`docker run -p 9090:9090 prom/prometheus:latest`

**What did you expect to see?**

The state of target "prometheus" should be "UP".

**What did you see instead? Under which circumstances?**

The state of target "prometheus" is "DOWN".

**Environment**

* System information:

	Darwin 15.6.0 x86_64

* Prometheus version: 

        prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
          build user:       root@e685d23d8809
          build date:       20161128-09:59:22
          go version:       go1.7.3

* Logs:
```
time="2016-12-07T08:38:18Z" level=info msg="Starting prometheus (version=1.4.1, branch=master, revision=2a89e8733f240d3cd57a6520b52c36ac4744ce12)" source="main.go:77"
time="2016-12-07T08:38:18Z" level=info msg="Build context (go=go1.7.3, user=root@e685d23d8809, date=20161128-09:59:22)" source="main.go:78"
time="2016-12-07T08:38:18Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:250"
time="2016-12-07T08:38:19Z" level=info msg="Loading series map and head chunks..." source="storage.go:354"
time="2016-12-07T08:38:19Z" level=info msg="0 series loaded." source="storage.go:359"
time="2016-12-07T08:38:19Z" level=info msg="Starting target manager..." source="targetmanager.go:63"
time="2016-12-07T08:38:19Z" level=info msg="Listening on :9090" source="web.go:248"
time="2016-12-07T08:39:19Z" level=info msg="Completed maintenance sweep through 3 in-memory fingerprints in 30.00262488s." source="storage.go:1180"
time="2016-12-07T08:39:59Z" level=info msg="Completed maintenance sweep through 3 in-memory fingerprints in 30.004019298s." source="storage.go:1180"
```

FYI, the endpoint is like http://d101b017c30f:9090/metrics, the `d101b017c30f` is the container ID.

**Comment by brancz** [comment]
Posting your config would be helpful, but I'm guessing the target you actually want is `localhost:9090`, I don't think the container id resolves to anything from within the container.

**Comment by goofansu** [comment]
I'm just use the default config in docker, I copied it from http://localhost:9090

``` yaml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
```
