### ISSUE TITLE
Recycled IP causes wrong metrics

### ISSUE THREAD

**Issue by NoumanSaleem** [prometheus/prometheus#2262]
**What did you do?**
During a load test, we had new instances launch which were given IPs previously seen and scraped by Prometheus.

Our scrape configuration uses Consul and assigns the `name` label to `__meta_consul_service`. The issue is that the name label was not updated to reflect the new service running at that scrape target, and caused inconsistencies in metrics.

**What did you expect to see?**
Not sure, maybe the name label to be updated? I guess I'm not 100% positive this issue resides with Prometheus, or possibly Consul was at fault for not updating the service. Just wanted to open this issue in case others had encountered this.

**Environment**
- System information: 
  Linux 3.13.0-93-generic x86_64
- Prometheus version: 
  prometheus, version 1.1.1 (branch: master, revision: 24db241bd556fd45854dd310692ac291de7d24e1)
  build user:       root@90d3f69e2d67
  build date:       20160907-09:42:10
  go version:       go1.6.3
- Prometheus configuration file:

```
global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'service'
    consul_sd_configs:
    - server: 172.17.42.1:8500
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: ',((api|data)-service),'
        action: keep
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'
        target_label: __address__
      - source_labels: [__meta_consul_service]
        target_label: name
      - source_labels: [__meta_consul_tags]
        target_label: tags
```
