### ISSUE TITLE
Federating: any way of disabling smartness of adding instance/job entirely?

### ISSUE THREAD

**Issue by EdSchouten** [prometheus/prometheus#2329]
We want to configure a set of Prometheus instances to federate for multiple purposes:

- Running Prometheus with short-term retention for the bulk of metrics,
- Provide separate Prometheus instances for long-term retention for selected data.
- Provide separate Prometheus instances that only contain data for a given customer, so that customers can explore the data freely.

What we've observed is that Prometheus doesn't seem to provide an easy way of scraping another Prometheus instance and leaving all of the labels in its original form. It always tries to add 'instance' and 'job'. The 'honor_labels' flag doesn't help here entirely, as it only determines how to deal with conflicts -- not when one of those labels was absent on the original dataset. We have some aggregated rules that don't have job/instance set, meaning these labels still get added when federating. Right now we're working around by adding this:

```
  # Set instance and job to placeholder markers before scraping.
  relabel_configs:
  - replacement: quxquxqux
    target_label: instance
  - target_label: job
  # Remove the placeholders if still present.
  metric_relabel_configs:
  - replacement: ''
    regex: quxquxqux
    source_labels: [instance]
    target_label: instance
```

Unfortunately, this approach has the downside of also partially messing up built-in metrics like `up`, `scrape_duration_seconds`, etc.

My question is, are there any plans on improving this in future versions of Prometheus? Are there any proposals for the desired way of doing this? Is there any way we can help out?
