### ISSUE TITLE
EC2 Discovery dropped all EC2 targets when AWS EC2 API respond 503.

### ISSUE THREAD

**Issue by WeiBanjo** [prometheus/prometheus#2335]
**What did you do?**
When AWS EC2 API has issues, Prometheus server loses EC2 targets.

**What did you expect to see?**
Prometheus should keep stale EC2 targets, when EC2 API call fails.

**What did you see instead? Under which circumstances?**
Prometheus dropped all EC2 targets when EC2 API respond 503

**Environment**

* System information:

```
$ uname -srm
Linux 3.10.0-327.4.4.el7.x86_64 x86_64
```

* Prometheus version: 

```
$ prometheus -version
prometheus, version 1.4.1 (branch: master, revision: 2a89e8733f240d3cd57a6520b52c36ac4744ce12)
  build user:       root@e685d23d8809
  build date:       20161128-09:59:22
  go version:       go1.7.3
```

* Prometheus configuration file:
```
global:
  scrape_interval: 600s

scrape_configs:
  - job_name: 'prod-exporter'
    scrape_interval: 30s
    scrape_timeout: 30s
    scheme: 'https'
    ec2_sd_configs:
      - region: us-east-1
        port: 8100
        refresh_interval: 600s
    relabel_configs:
      - source_labels: [__meta_ec2_public_ip]
        regex: .+
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: prod-.*
        action: keep
      - source_labels: [__address__]
        modulus: 2
        target_label: __tmp_hash
        action: hashmod
      - source_labels: [__tmp_hash]
        regex: ^1$
        action: keep
      - source_labels: [__meta_ec2_private_ip]
        regex: (.*)
        replacement: ${1}:8100
        action: replace
        target_label: __address__
      - source_labels: [__meta_ec2_tag_Name]
        action: replace
        target_label: hostname
```

* Logs:
```
prometheus[15492]: time="2017-01-10T20:41:48Z" level=error msg="could not describe instances: Unavailable: Tags could not be retrieved.\n\tstatus code: 503, request id: REQUEST_ID" source="ec2.go:116"
prometheus[15492]: time="2017-01-10T20:41:49Z" level=error msg="could not describe instances: Unavailable: Tags could not be retrieved.\n\tstatus code: 503, request id: REQUEST_ID" source="ec2.go:116"
```
