### ISSUE TITLE
request - support scrape_interval override in relabel_configs

### ISSUE THREAD

**Issue by cameronbraid** [prometheus/prometheus#2353]
In kubernetes/openshift, I would like to be able to use annotations on my pods that define the scrape_interval

i.e. I would like to do something like this in the relabel config :
```
 - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape_interval]
    action: replace
    regex: (.+)
    target_label: __scrape_interval__
    replacement: $1
```

Then I could use annotations on pods/deployment configs such as : 

```
 annotations:
   prometheus.io/port: '8081'
   prometheus.io/path: '/prometheus'
   prometheus.io/scrape_interval: '5m'
```
