### ISSUE TITLE
Relabeling with multiple target files broken in 1.5.0

### ISSUE THREAD

**Issue by joe-pll** [prometheus/prometheus#2377]
Hi, first of all thank you for your job, I really appreciate it.

## Config
I have this Prometheus configuration and as target, for simplicity, there are three different files, corresponding to three different jobs, in the blackbox targets' directory.  
```yaml
global:
  scrape_interval: 10s
  evaluation_interval: 10s
 
rule_files: 
 - /etc/prometheus/rules/recording/*.rules
 - /etc/prometheus/rules/alerting/*.rules
 
 
scrape_configs:
 - job_name: 'override-exporters'
   scrape_interval: 5s
 
   file_sd_configs:
     - files:
       - '/etc/prometheus/targets/exporters/*.yml'
 
 - job_name: 'override-blackbox'
   scrape_interval: 10s
   metrics_path: /probe
   file_sd_configs:
     - files:
         - '/etc/prometheus/targets/blackbox/*.yml'
   relabel_configs:
     - source_labels: [module]
       target_label: __param_module
     - source_labels: [module, __address__]
       regex: ^[http|tcp].*;(.*):(.*)$
       target_label: __param_target
       replacement: ${1}:${2}
     - source_labels: [module, __address__]
       regex: ^icmp;(.*):?.*
       target_label: __param_target
       replacement: ${1}
     - source_labels: [__param_target]
       regex: ^(.*):(.*)
       target_label: remote_address
       replacement: ${1}
     - source_labels: [__param_target]
       regex: ^([^:]*)$
       target_label: remote_address
       replacement: ${1}
     - source_labels: [host]
       target_label: instance
     - source_labels: []
       target_label: module
       replacement: ""
     - source_labels: []
       target_label: host
       replacement: ""
     - source_labels: []
       regex: .*
       target_label: __address__
       replacement: '<link_to_the_blackbox_exporter>:9115'
```

In the directory **/etc/prometheus/targets/blackbox/** there are the following files. In my configuration each file represents a job hence, all the targets for a job are in the same file.  
**job_http.yml** 
```yaml
- labels:
    host: host1
    job: blackbox-http
    module: http_get_5s
  targets:
  - 1.1.1.1:8080
```  

**job_ping.yml**
```yaml
- labels:
    host: host1
    job: blackbox-ping
    module: icmp
  targets:
  - 1.1.1.1
```  

**job_ssh.yml**
```yaml
- labels:
    host: host1
    job: blackbox-ssh
    module: tcp
  targets:
  - 1.1.1.1:22
```

## Problem
I was using the version **v1.4.0** and everything was fine; the files were loaded correctly and the relabeling didn't have problems.  
After the upgrade to **v1.5.0** the relabeling for all the targets of the **first file only** (first file in alphabetical order) is not replacing the labels correctly.  
The label **remote_address** is rewritten as **<link_to_the_blackbox_exporter>** and not with the address **1.1.1.1** as it should be; in addition the relabel works only for the first 2/3 seconds after Prometheus startup. But I repeat, this bad behavior happens only for the targets of the first file; the relabeling for the other files keeps working.

When I unify all the targets from all the files in an unique one everything works fine.  
Furthermore when Prometheus loads the files, the first one is loaded immediately the others, instead, are shown in the interface only after the first scrape of a random target of the first file.

The log in debug mode doesn't give any other information.

Giuseppe

**Comment by jeinwag** [comment]
I'm also experiencing some very wird relabeling issues when using Consul service discovery with multiple servers, e.g.:
```
- job_name: cadvisor
  consul_sd_configs:
     - server: consul.dc1
       services: [ cadvisor ]
     - server: consul.dc2
       services: [ cadvisor ]
   relabel_configs:
      - source_labels: ['__meta_consul_node','__meta_consul_dc']
        regex:         '(.*?);(.*)'
        target_label:  'instance'
        replacement:   '$1.$2'
```
After a couple of scrapes some of the instance labels will only contain '.dc1' or '.dc2', the node name is missing. Then the __meta_consul_node is missing from the "before relabeling" popup, too.

It looks like these issues are caused by the changes to the relabeling logic in 6c07453ec1ca1612be466e4c40d30cd0fd314304.
