### ISSUE TITLE
Kubernetes discovery is reporting pods that are long gone

### ISSUE THREAD

**Issue by checketts** [prometheus/prometheus#2398]
**What did you do?**
Navigating to the `/targets` page for Prometheus when running the Kubernetes discovery and viewing the `kubernetes-pods` job.

**What did you expect to see?**
I expected to see just pods that existed

**What did you see instead? Under which circumstances?**
I am instead seeing that 2 pods are listed as target that haven't existed for over 1 month (showing just one in the screenshot).

I'm unable to locate the pods using `kubectl` or any other means. There are 2 current pods from the same deployment that are being tracked, so the 2 old ones are from a previous version of the deployment.

![image](https://cloud.githubusercontent.com/assets/416063/22649172/0e5b914e-ec37-11e6-9829-43ab28c46970.png)

**Environment**
Prometheus is running in s Kubernetes Pod using Kubernetes Discovery

* System information:

`Linux 4.4.0-45-generic x86_64`

* Prometheus version: 

```
prometheus, version 1.5.0 (branch: master, revision: d840f2c400629a846b210cf58d65b9fbae0f1d5c)
  build user:       root@a04ed5b536e3
  build date:       20170123-13:56:24
  go version:       go1.7.4
```

* Prometheus configuration file:
```
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: (.+):(?:\d+);(\d+)
    replacement: ${1}:${2}
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_annotation_appVersion]
    action: replace
    target_label: app_version
```

* Logs:
```
time="2017-02-06T06:50:44Z" level=info msg="Starting prometheus (version=1.5.0, branch=master, revision=d840f2c400629a846b210cf58d65b9fbae0f1d5c)" source="main.go:75"
time="2017-02-06T06:50:44Z" level=info msg="Build context (go=go1.7.4, user=root@a04ed5b536e3, date=20170123-13:56:24)" source="main.go:76"
time="2017-02-06T06:50:44Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:248"
time="2017-02-06T06:50:44Z" level=info msg="Loading series map and head chunks..." source="storage.go:373"
time="2017-02-06T06:50:44Z" level=info msg="0 series loaded." source="storage.go:378"
time="2017-02-06T06:50:44Z" level=info msg="Listening on :9090" source="web.go:259"
time="2017-02-06T06:50:44Z" level=info msg="Starting target manager..." source="targetmanager.go:61"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
time="2017-02-06T06:50:44Z" level=info msg="Using pod service account via in-cluster config" source="kubernetes.go:94"
```
