### ISSUE TITLE
No metric "prometheus_local_storage_ingested_samples_total" for other Jobs exept Promeheus itself

### ISSUE THREAD

**Issue by olisolis** [prometheus/prometheus#2442]
**What did you do?**
Configured Prometheus, that takes the metrics from itself (localhost) and cadvisor.

**What did you expect to see?**
Metric "prometheus_local_storage_ingested_samples_total" for all job, hier for job "docker-hosts"
"prometheus_target_interval_length_seconds_count" --> same

**What did you see instead? Under which circumstances?**
Metric "prometheus_local_storage_ingested_samples_total" exists only for job "prometheus"
"prometheus_target_interval_length_seconds_count" --> same

_Execute of Prometheus query_:
prometheus_target_interval_length_seconds_count{instance="localhost:9090",interval="15s",job="prometheus"} --> metric only for instance="localhost:9090" (no such metric for target in "docker-hosts")

prometheus_local_storage_ingested_samples_total{instance="localhost:9090",job="prometheus"} --> metric olny for instance="localhost:9090" (no such metric for target in "docker-hosts")

**Environment**
Linux 4.1.12-61.1.18.el7uek.x86_64 x86_64
Prometheus Version: 1.5.2
Docker Version: 1.13.1, Cadvisor Version: 0.24.1-ae6934c

* System information:

Linux 4.1.12-61.1.18.el7uek.x86_64 x86_64

* Prometheus version: 

1.5.2

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-hosts'

    static_configs:
      - targets: ['dockerhosts:9090']
        labels:
          group: 'dockers'
# 
# TARGETS FOR BOTH JOBS UP
#
```
