### ISSUE TITLE
can prometheus get multi values in rules file?

### ISSUE THREAD

**Issue by tailnode** [prometheus/prometheus#2496]
**What did you do?**
for example, i use this rule
```
ALERT test
  IF go_memstats_alloc_bytes > 1 and go_goroutines > 2 
  ANNOTATIONS {
    currentValue = "{{ $value }}",
  }
```

**What did you expect to see?**
 i want get the values of `go_memstats_alloc_bytes ` and `go_goroutines `, and write them into annotations

**What did you see instead? Under which circumstances?**
{{ $value }} is value of `go_memstats_alloc_bytes `

**Environment**

* System information:

	Linux 4.4.0-62-generic x86_64

* Prometheus version: 

prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5

* Prometheus configuration file:
```
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules/*.rules
#- rules/wanglei.rules
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
```
sorry for my bad english, i am not native speaker. thanks very much.
