### ISSUE TITLE
Kuberenetes SD scrapes all service ports, not just the one annotated

### ISSUE THREAD

**Issue by drewhemm** [prometheus/prometheus#2507]
I created an OpenShift Kubernetes service and annotated it as follows:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    router: router
  name: router
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 443-tcp
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 1936-tcp
    port: 1936
    protocol: TCP
    targetPort: 1936
  selector:
    router: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
I expected to see in the Prometheus targets a single entry per scrape port per pod/container. Instead I see one target for each pod/container port, even though only 9101 is annotated. Even creating a separate service that lists only the scrape port:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9101"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    router: router
  name: router-exporter
spec:
  ports:
  - name: exporter
    port: 9101
    protocol: TCP
    targetPort: 9101
  selector:
    router: router
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
Prometheus still tries to scrape from every port open to the pod/container.

I'm running OpenShift Enterprise 3.4 with Kubernetes version 1.4.0 and Prometheus version 1.5.2

* System information:
Linux 3.10.0-514.6.1.el7.x86_64 x86_64

* Prometheus configuration file:
```
- job_name: 'openshift-service-endpoints'

    scheme: http

    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    kubernetes_sd_configs:
    - role: endpoints
      api_server: https://kubernetes.default.svc
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      target_label: __address__
      regex: (.+)(?::\d+)?:(\d+)
      replacement: $1:$2
    - action: labelmap:
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: kubernetes_name
```
