### ISSUE TITLE
Context Deadline Exceeded

### ISSUE THREAD

**Issue by SRAM85** [prometheus/prometheus#2546]
**What did you do?**
 Using JMX_exporter to push metrics from baremetal serves to prometheus which is hosted in another baremetal server. we graph the metrics in grafana.

**What did you expect to see?**
Up and running targets with metrics information being scrapped

**What did you see instead? Under which circumstances?**
Targets for some jobs are up but the targets for jobs scrapping kafka metrics is down with "CONTEXT DEADLINE EXCEEDED" . i am not able to see metrics in grafana. Increasing the number of chunks or the memory of the jmx-exporter did not help. Restarting Prometheus did not help

**Environment**

* System information:

Linux 3.10.0-327.10.1.el7.x86_64 x86_64

* Prometheus version: 

prometheus-1.5.2.linux-amd64

* Prometheus configuration file:

```yml
global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'codelab-monitor'
  - job_name: 'Infrastructure_PROD_DFW'
    static_configs:
    - targets: ['bm1:10001','bm2:10001','bm3:10001','bm4:10001','bm5:10001','bm6:10001']
  
  - job_name: 'Infrastructure_PROD_DAL'
    static_configs:
    - targets: ['bm7:10001','bm8:10001','bm9:10001','bm10:10001','bm11:10001','bm12:10001']

  - job_name: 'Burrow'
    static_configs:
    - targets: ['bm13:9091'] 
```

* Logs:

context deadline exceeded

**Comment by juliusv** [comment]
`context deadline exceeded` indicates an timeout error pulling from the JMX exporter. Can you reach the `/metrics` endpoint on your JMX exporter successfully manually? Can you also reach it from the same machine that Prometheus runs on? How long does it take to load?

**Comment by SRAM85** [comment]
I am able to reach the endpoint /metrics and it takes like 5s -10s to load.

**Comment by juliusv** [comment]
@SRAM85 The default scrape timeout is 10 seconds - maybe sometimes it takes longer than that and that is the problem? You could try increasing it:

```yml
global:
  scrape_timeout: 30s
  ...
```

(or per scrape config)
