### ISSUE TITLE
Switch kubelet scraping to http and port 10255

### ISSUE THREAD

**Issue by JorritSalverda** [prometheus/prometheus#2613]
Since kubernetes version 1.6 the encrypted kubelet metrics endpoint on port 10250 requires authorization which makes it unusable, see https://github.com/prometheus/prometheus/issues/2606 and https://github.com/kubernetes/kubernetes/issues/11816#issuecomment-293550482. This is done to beef up security for communication to the kubelet.

The metrics endpoint will keep being available over http on port 10255 according to the kubernetes ticket.

A viable workaround is to rewrite the endpoint in relabel_configs like below:

```
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - source_labels: [__address__]
        action: replace
        target_label: __address__
        regex: ([^:;]+):(\d+)
        replacement: ${1}:10255
      - source_labels: [__scheme__]
        action: replace
        target_label: __scheme__
        regex: https
        replacement: http
```

It would be nice though to switch to the 10255 port in the Prometheus code though. Unfortunately currently the nodeSpec doesn't expose that port anywhere, so until that's there the workaround works fine. Perhaps add it to your kubernetes config example?
