### ISSUE TITLE
no label attached for metrics

### ISSUE THREAD

**Issue by reachlin** [prometheus/prometheus#2633]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
defined labels for a static_configs

**What did you expect to see?**
labels attached to metrics scraped

**What did you see instead? Under which circumstances?**
no labels defined by me, only default labels

**Environment**

* System information:

	run in a docker

* Prometheus version: 

```
lincai@pdbuddy:~/go/src/github.ibm.com/alchemy-containers/armada-ops-prom2graphite$ docker exec -it prometheus prometheus -version
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@1a01c5f68840
  build date:       20170210-16:23:28
  go version:       go1.7.5
```

* Alertmanager version:

	n/a

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prom2graphite'
    static_configs:
      - targets: ['ip:9102']
      - labels:
          group: 'g1'

```

* Alertmanager configuration file:
```
n/a
```

* Logs:
```
n/a
```
