### ISSUE TITLE
remote_write not working on armv7

### ISSUE THREAD

**Issue by vpetersson** [prometheus/prometheus#2663]
**What did you do?**

Trying to get `remote_write` to work.

**What did you expect to see?**

The config below works just fine on x86, but doesn't seem to work on ARM.

**What did you see instead? Under which circumstances?**

It appears as Prometheus chokes on the `remote_write` directive on ARM.

If I remove that stanza, the config loads just fine.

```
./promtool check-config /etc/prometheus.yml
Checking /etc/prometheus.yml
  FAILED: yaml: unmarshal errors:
  line 30: cannot unmarshal !!map into []*config.RemoteWriteConfig
```

**Environment**

Prometheus-1.6.1.linux-armv7

* System information:

Linux 4.4.48 armv7l

* Prometheus version: 

```
prometheus, version 1.6.1 (branch: master, revision: 4666df502c0e239ed4aa1d80abbbfb54f61b23c3)
  build user:       root@ca1b452514b7
  build date:       20170419-13:53:08
  go version:       go1.8.1
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'foobar-test'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'test'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:8000']

remote_write:
    url: "http://localhost:1234/receive"
```

Sample remote_write as per [this documentation](https://github.com/prometheus/prometheus/tree/master/documentation/examples/remote_storage/remote_storage_adapter).
