### ISSUE TITLE
Remote read/write interfaces use Snappy when they probably shouldn't

### ISSUE THREAD

**Issue by engelrob** [prometheus/prometheus#2692]
**What did you do?**

I implemented a remote_read interface for Prometheus in Java.

**What did you expect to see?**

I expected to receive Protobuf-encoded [remote ReadRequests](https://github.com/prometheus/prometheus/blob/master/storage/remote/remote.proto) from Prometheus, but instead...

**What did you see instead? Under which circumstances?**

Instead of the protobuf binary format, Prometheus' remote read requests are Snappy-compressed data.

First, this is not stated in the Content-type, which says "application/x-protobuf" indicating that it is protobuf binary format, not Snappy.

Second, I am currently not aware of any Java implementation of the Snappy codec that can successfully decode golang-snappy encoded data (I tried both [xerial-snappy](https://github.com/xerial/snappy-java) and [dain/snappy](https://github.com/dain/snappy) and could not make it decompress the golang-snappy encoded data).

* Prometheus version: 

	1.6.1

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

remote_read:
  - url: "http://localhost:9201/read"
```
