### ISSUE TITLE
Relabelling the address of a TargetGroup from k8s namespace, results in duplication of metrics 

### ISSUE THREAD

**Issue by ionutvilie** [prometheus/prometheus#2761]
**What did you do?**

replace the __address__ label using a group regex where port is optional from data received from kubernetes_sd_configs 

related to this: https://github.com/prometheus/prometheus/pull/2434 

**What did you expect to see?**
one metric with the label address changed

**What did you see instead? Under which circumstances?**

i am seeing the targets reported correctly, the metric however depending on how many regex groups i use it is doubled or tripled

**Environment**

* System information:

`Linux 3.13.0-85-generic x86_64`

* Prometheus version: 
```
prometheus, version 1.5.2 (branch: master, revision: bd1182d29f462c39544f94cc822830e1c64cf55b)
  build user:       root@a8af9200f95d
  build date:       20170210-14:41:22
  go version:       go1.7.5
```
I have checked new versions release notes and nothing seems to be related to any regex fix.
From my point of view is not relevant to update to the newer version.

* Prometheus configuration file:
```
############################################################
# Configuration for K8S cluster 'mcc1-test'
############################################################
  ################################################
  # Configuration for foo services
  ################################################
  - job_name: 'foo-mcc1-test'

    scrape_interval: 15s
    metrics_path: /.well-known/metrics

    proxy_url: 'https://proxy-k8s-001-test1-mcc-gb-lon1.metroscales.io:30040'

    kubernetes_sd_configs:
    - role: pod
      api_server: 'api-foo.io'
      basic_auth:
        username: foo
        password: bar

    relabel_configs:
    # Drop target which should not be monitored
    - source_labels: [__meta_kubernetes_namespace]
      action: drop
      regex: default|kube-system|foo-monitoring
      target_label: __meta_kubernetes_namespace
    # Add foo_labels
    - source_labels: [__meta_kubernetes_pod_label_vertical]
      action: replace
      regex: (.+)
      replacement: ${1}
      target_label: foo_vertical
    - source_labels: [__meta_kubernetes_pod_label_stage]
      action: replace
      regex: (.+)
      replacement: ${1}
      target_label: foo_stage
    - source_labels: [__meta_kubernetes_pod_label_service]
      action: replace
      regex: (.+)
      replacement: ${1}
      target_label: foo_service
    ## below one triples the metric (one IP) 3 hostnames  
    # - source_labels: [__address__,__meta_kubernetes_pod_host_ip]
    #   separator: ;
    #   action: replace
    #   regex: ([\.0-9]+)(?:(:[0-9]+)?);([\.0-9]+)
    #   replacement: ${3}${2}
    #   target_label: __address__
    ## below one was inserted to trace the bug  
    # - source_labels: [__meta_kubernetes_pod_name]
    #   action: replace
    #   regex: (.+)
    #   target_label: testxxx
    ## below one doubles the metric (one IP) 2 hostnames  
    # - source_labels: [__meta_kubernetes_pod_host_ip, __meta_kubernetes_pod_container_port_number]
    #   action: replace
    #   target_label: __address__
    #   regex: (.*);(.*)
    #   replacement: $1:$2
```

* Screen Shot:

insert Prometheus and Alertmanager logs relevant to the issue here
<img src="https://h6ppsg.bn1302.livefilestore.com/y4m3YQo47WXbfrZrX_g8iw55-XJGkVrD34oiLX0unc0JnW64x-wQm7GqEOlU__XJg5ZOhKteYdQJSYlhKAHwJ86-sIzBX2z64tnZSQD1QiCDtn8gJ_y2N4ROWCXD4Drcgih2vn5zGB5Q07t-BiWp5TMY7aWkbvaTI9nyZDZj5ytYCh1q8KSVKpR5Sqe8jnvtBsuWlSGBfXpsdd05EGqmItixw?width=1908&height=549&cropmode=none" width="1908" height="549" />

<img src="https://h6pssg.bn1302.livefilestore.com/y4mH0VZ_1zocCKUPEvwpDAhxpMuXAN2VGhzAx5i6vdpquui9vfOJnh90hTOKcLSmpCppOI6_16CLYJk_IEAcikc9A7p4GjvzsZT6lVaYXTOkORH7yLIA29_2-88RE7b8mhjb9Gz_Lvi3oQw9p-4R1CBubh8fHh6cl0CGQj8v_6nZ-f5FXsbsWmIZxcUTbjRMD8zixI3mtmanSu9jFDmjeQhWA?width=1899&height=403&cropmode=none" width="1899" height="403" />
