### ISSUE TITLE
Configuration Help - No timeseries returned

### ISSUE THREAD

**Issue by jpatwary** [prometheus/prometheus#2767]
**What did you do?**
 I have four instances running on Amazon EC2. I ssh'd into one of my Amazon EC2 instances and set up the following configuration in prometheus.yml using the access and secret access keys I got from my AWS Iam role with EC2ReadOnly permissions attached.

**What did you expect to see?**
I expect to see all four of my EC2 instances up and running under [consoles/prometheus.html](url) with the timeseries tables returned. 

**What did you see instead? Under which circumstances?**
Three out of my four EC2 instances are labeled as _No_ under the _Up_ column in the table. There are no _Ingested samples_, _time series_, or _memory_ listed for any of them. The fourth EC2 instance (the one I connected to and installed and configured prometheus on) is labled as _Yes_ under _Up_ and does have _Memory_ specified, but _Ingested Samples_ and _Time Series_ are left as blank. If I click on any of these instances, there is no time series returned in any of the data. 

I'm not getting data returned for my EC2 instances (though I am getting data and timeseries returned for my localhost). Any help on this matter is greatly appreciated!

* Prometheus configuration file:
```
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
    ec2_sd_configs:
      - region: us-east-1
        access_key: ACCESS_KEY
        secret_key: SECRETY_ACCESS_KEY
        port: 9100
```
~
~
