### ISSUE TITLE
failed to reload config: couldn't load configuration open /etc/prometheus/prometheus.yml: no such file or directory

### ISSUE THREAD

**Issue by titansmc** [prometheus/prometheus#2773]
For this POST reload to work, I have to go to the container, and do an "ls" from command line and then it works

**What did you do?**

xemacs@samaruc ~ $ curl -k  -X POST https://prometheus.test.mydomain.com/-/reload

**What did you expect to see?**
xemacs@samaruc ~ $ curl -k  -X POST https://prometheus.test.mydomain.com/-/reload
xemacs@samaruc ~ $ 

**What did you see instead? Under which circumstances?**
failed to reload config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: no such file or directory
**Environment**
latest docker images
* System information:

	insert output of `uname -srm` here
/etc/prometheus # uname -srm
Linux 4.4.0-78-generic x86_64

* Prometheus version: 

/etc/prometheus # prometheus -version
prometheus, version 1.6.3 (branch: master, revision: c580b60c67f2c5f6b638c3322161bcdf6d68d7fc)
  build user:       root@a6410e65f5c7
  build date:       20170522-09:15:06
  go version:       go1.8.1
/etc/prometheus # 

* Alertmanager version:

/alertmanager # alertmanager -version
alertmanager, version 0.6.2 (branch: master, revision: b011c0a32ce887c1a10f7d34d52fd8cce485c1cf)
  build user:       root@e3ca4de32142
  build date:       20170509-08:56:14
  go version:       go1.8.1
/alertmanager # 

* Prometheus configuration file:
```
deploy@dock-test01:/nfs/prometheus_monitoring$ cat prometheus/prometheus.yml 
# my global config
global:
  scrape_interval:     30s # By default, scrape targets every 15 seconds.
  evaluation_interval: 30s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'dock-test'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  - "host.rules"
#  - "container.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_timeout: 30s
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'mysqld-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.mysqld-exporter'
      type: 'A'
      port: 9104

  - job_name: 'postgres-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.postgres-exporter'
      type: 'A'
      port: 9187

```

* Alertmanager configuration file:
```
global:
    smtp_smarthost: smtp.gmail.com:587
    smtp_from: alertmanager@test.mydomain.com
route:
    receiver: 'mail-test'
    group_wait: 10s

receivers:
    - name: 'mail-test'
      email_configs:
      - to: jandres@mydomain.com
        from: alertmanager@test.mydomain.com
        smarthost: smtp.gmail.com:587
        auth_username: "asdf@gmail.com"
        auth_identity: "asdf@gmail.com"
        auth_password: "asdf"
      

```

* Logs:
```
time="2017-05-26T07:16:29Z" level=error msg="Error reloading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): scrape timeout greater than scrape interval for scrape config with job name \"prometheus\"" source="main.go:179" 
time="2017-05-26T07:17:44Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:251" 
time="2017-05-26T07:17:44Z" level=error msg="Error reloading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: no such file or directory" source="main.go:179" 
time="2017-05-26T07:18:06Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:251" 
time="2017-05-26T07:18:06Z" level=error msg="Error reloading config: couldn't load configuration (-config.file=/etc/prometheus/prometheus.yml): open /etc/prometheus/prometheus.yml: no such file or directory" source="main.go:179" 
time="2017-05-26T07:18:41Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:251" 

```
