### ISSUE TITLE
Prometheus alert.rules are not loading in 0.16.2

### ISSUE THREAD

**Issue by tsrinath1986** [prometheus/prometheus#2790]
Hi,
i installed prometheus on ubuntu 16.04 using apt. alertmanager installed from git.
when i write alert.rules and include in /etc/prometheus/prometheus.yml i am getting error after restarting service.
![1](https://cloud.githubusercontent.com/assets/29095217/26669844/fdc5a4b4-46cc-11e7-9e39-1aae08c114df.png)
* Prometheus version: 
prometheus, version 0.16.2

	insert output of `prometheus -version` here
prometheus, version 0.16.2+ds (branch: debian/sid, revision: 0.16.2+ds-1ubuntu1)
* Alertmanager version:
0.7.0-rc.0 / 2017-05-19
	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'BrandWizard'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"
#    - "alerts.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    scrape_timeout: 10s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    target_groups:
      - targets: ['localhost:9090','localhost:8080']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    target_groups:
      - targets: ['localhost:9100']
      - targets: ['stage.brandwizard.net:9100']

```

* Alertmanager configuration file:
```
route:
  group_by: [Alertname]
# send all notifications to me.
  receiver: Admin-Alerts

receivers:
- name: Admin-Alerts
  email_configs:
  - to:xyz@gmail.com
    from: abc@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: "abc@gmail.com"
    auth_identity: "abc@gmail.com"
    auth_password: <hidden>
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
time="2017-06-01T00:13:41-07:00" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:196"
time="2017-06-01T00:13:41-07:00" level=error msg="Error loading rules, previous rule set restored: error parsing /etc/prometheus/alert.rules: parse error at line 3, char 4: alert summary missing" source="manager.go:336"
prometheus, version 0.16.2+ds (branch: debian/sid, revision: 0.16.2+ds-1ubuntu1)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20160408-04:15:29
  go version:       go1.6
