### ISSUE TITLE
Kubernetes SD; Support external name services

### ISSUE THREAD

**Issue by Chronojam** [prometheus/prometheus#2791]
This is a proposal to add support for external name services to the Kubernetes SD

Given the following kubernetes service configuration:
```
kind: Service
apiVersion: v1
metadata:
  name: my-service
  annotations:
    "prometheus.io/scrape": "true"
spec:
  type: ExternalName
  externalName: my.service.example.com
```
and an endpoint discoverer:
```
kubernetes_sd_configs:
  - role: endpoints
```
I think the Kubernetes SD should create 1 scrape per DNS type
I dont think there is any need to support other types than A/AAAA and SRV (similar to the dns discoverer)?

my.service.example.com:AAAA => 10.0.0.1
my.service.example.com:SRV1  => 10.0.0.1:8080
my.service.example.com:SRV2  => 10.0.0.2:8080

for each endpoint discovered, we should attach a __meta_kubernetes_service_dnstype label with 
 type ("AAAA"/"SRV")

**Comment by brian-brazil** [comment]
How are you envisioning scraping these?

This sounds more like a load balancer rather than the individual targets we'd want to scrape.

**Comment by Chronojam** [comment]
An example might be an external etcd cluster (which ive just grabbed from the clustering guide);

```
$ dig +noall +answer SRV _etcd-server._tcp.example.com
_etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra0.example.com.
_etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra1.example.com.
_etcd-server._tcp.example.com. 300 IN  SRV  0 0 2380 infra2.example.com.
```

I might setup my service like this
```
kind: Service
apiVersion: v1
metadata:
  name: my-external-etcd
  annotations:
    "prometheus.io/scrape": "true"
spec:
  type: ExternalName
  externalName: _etcd-server-ssl._tcp.example.com
```
Then the created job would monitor each record there (like the DNS discoverer does)

Job: my-external-etcd
  endpoint:  infra0.example.com:2380/metrics
  endpoint:  infra1.example.com:2380/metrics
