### ISSUE TITLE
Hide consul token on UI page

### ISSUE THREAD

**Issue by roman-vynar** [prometheus/prometheus#2792]
Currently, when you go to Status->Configuration page on UI, you will see that password field in basic_auth section is hidden by `<hidden>`. However, consul token is not.
For example:
```
  - job_name: dev
    scheme: https
    basic_auth:
      username: prom
      password: <hidden>
    consul_sd_configs:
      - server: consul.example.com:8500
        token: 140ddb9e-d1a9-45d2-a182-dcb9ed89fed2
        datacenter: us-west-1
        scheme: https
        services: [ consul ]
```
I would have sent a PR but I couldn't find where 😇
