### ISSUE TITLE
Secrets are not obfuscated on 2.0.0-alpha.2

### ISSUE THREAD

**Issue by gianrubio** [prometheus/prometheus#2798]
**What did you do?**

Opened the prometheus configuration page 

**What did you expect to see?**

Obfuscated the basic auth password

**What did you see instead? Under which circumstances?**

The secret are not obfuscated 

![screen shot 2017-06-02 at 11 08 21](https://cloud.githubusercontent.com/assets/5694860/26719296/3ff57bfe-4784-11e7-98e7-23fe9c444b5c.png)

* Prometheus version: 

2.0.0-alpha.2

* Prometheus configuration file:

```
- job_name: monitoring/graylog/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
  metrics_path: /api/plugins/org.graylog.plugins.metrics.prometheus/metrics
  basic_auth:
    username: |
      prometheus
    password: <hidden>
      534jk5h43klrjdskjfhdskfj
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: graylog-metrics
  - action: keep
    source_labels:
    - __meta_kubernetes_namespace
    regex: logging
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: graylog-metrics
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: graylog-metrics
```
