### ISSUE TITLE
DNS SD: If all targets disappear, Prometheus keeps them.

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#2799]
**What did you do?**

Configured a job with dns_sd_configs. At some point, the DNS entry disappeared completely:
```
$ dig +short SRV all.telemetry.xxx.srv.s-cloud.net
$
```

**What did you expect to see?**

The targets should disappear from Prometheus.

**What did you see instead? Under which circumstances?**

The targets were kept by Prometheus, appearing on the targets page as down, `up==0` etc., triggering corresponding alerts 

**Environment**

* System information:

Linux 3.16.7-<elided> x86_64

* Prometheus version: 

prometheus, version 1.6.0 (branch: master, revision: 10f645382988add09c8e3420d0d7ff2dc4d36a29)
  build user:       root@0816a56aa81c
  build date:       20170414-18:36:18
  go version:       go1.8.1

* Alertmanager version:

n/a

* Prometheus configuration file:
```
[...]
- job_name: xxx
  dns_sd_configs:
  - names:
    - all.telemetry.xxx.srv.s-cloud.net
    refresh_interval: 10s
[...]
```

* Alertmanager configuration file:
n/a

* Logs:
n/a
