### ISSUE TITLE
prometheus not showing expressions after running node_exporter

### ISSUE THREAD

**Issue by tsrinath1986** [prometheus/prometheus#2804]
Hi,
Below is my issue details.

Prometheus version : 1.6.3
Node_exporter version : 0.13.0
Os : ubuntu 14.04

prometheus.yml config :
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"
    - "alert.rules"
 # A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090','localhost:8080']
```
installation:
Downloaded from official site binary package.
~/Prometheus/server - prometheus files
~/Prometheus/node_exporter - node files

Running node_exporter:
~/Prometheus/node_exporter#./node_exporter
result:
INFO[0000] Starting node_exporter (version=0.13.0, branch=master, revision=006d1                                                                                        c7922b765f458fe9b92ce646641bded0f52)  source=node_exporter.go:135
INFO[0000] Build context (go=go1.7.3, user=root@75db7098576a, date=20161126-13:1                                                                                        1:09)  source=node_exporter.go:136
INFO[0000] No directory specified, see --collector.textfile.directory  source=te                                                                                        xtfile.go:57
INFO[0000] Enabled collectors:                           source=node_exporter.go                                                                                        :155
INFO[0000]  - loadavg                                    source=node_exporter.go                                                                                        :157
INFO[0000]  - time                                       source=node_exporter.go                                                                                        :157
INFO[0000]  - uname                                      source=node_exporter.go                                                                                        :157
INFO[0000]  - entropy                                    source=node_exporter.go                                                                                        :157
INFO[0000]  - filesystem                                 source=node_exporter.go                                                                                        :157
INFO[0000]  - netstat                                    source=node_exporter.go                                                                                        :157
INFO[0000]  - stat                                       source=node_exporter.go                                                                                        :157
INFO[0000]  - vmstat                                     source=node_exporter.go                                                                                        :157
INFO[0000]  - textfile                                   source=node_exporter.go                                                                                        :157
INFO[0000]  - conntrack                                  source=node_exporter.go                                                                                        :157
INFO[0000]  - diskstats                                  source=node_exporter.go                                                                                        :157
INFO[0000]  - filefd                                     source=node_exporter.go                                                                                        :157
INFO[0000]  - hwmon                                      source=node_exporter.go                                                                                        :157
INFO[0000]  - mdadm                                      source=node_exporter.go                                                                                        :157
INFO[0000]  - meminfo                                    source=node_exporter.go                                                                                        :157
INFO[0000]  - sockstat                                   source=node_exporter.go                                                                                        :157
INFO[0000]  - netdev                                     source=node_exporter.go                                                                                        :157
INFO[0000] Listening on :9100                            source=node_exporter.go                                                                                        :176

Running prometheus:
~/Prometheus/server#./prometheus -config.file=prometheus.yml
Result:
INFO[0001] Starting prometheus (version=1.6.3, branch=master, revision=c580b60c67f2c5f6b638c3322161bcdf6d68d7fc)  source=main.go:88
INFO[0001] Build context (go=go1.8.1, user=root@a6410e65f5c7, date=20170522-09:15:06)  source=main.go:89
INFO[0001] Loading configuration file prometheus.yml     source=main.go:251
INFO[0001] Loading series map and head chunks...         source=storage.go:421
INFO[0001] 0 series loaded.                              source=storage.go:432
INFO[0001] Starting target manager...                    source=targetmanager.go:61
INFO[0001] Listening on :9090                            source=web.go:259
INFO[0301] Checkpointing in-memory metrics and chunks...  source=persistence.go:633
INFO[0301] Done checkpointing in-memory metrics and chunks in 94.323395ms.  source=persistence.go:665
INFO[0601] Checkpointing in-memory metrics and chunks...  source=persistence.go:633
INFO[0601] Done checkpointing in-memory metrics and chunks in 101.176111ms.  source=persistence.go:665

http://localhost:9090/graph
eg: node_cpu like expressions are not showing.
targets showing - up

then i used apt to install prometheus. from apt i am able to install 1.6.2 version and node_exporter working.

the Issue is in 1.6.2 alert.rules are not working
error - "summary missing "
prometheus excited with status code 1

alertmanager.yml config:
```
route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: $GMAIL_ACCOUNT
    from: $GMAIL_ACCOUNT
    smarthost: smtp.gmail.com:587
    auth_username: "$GMAIL_ACCOUNT"
    auth_identity: "$GMAIL_ACCOUNT"
    auth_password: "$GMAIL_AUTH_TOKEN"
```
alert.rules
```
ALERT InstanceDown
  IF up == 0
  FOR 5m
  LABELS { severity = "page" }
  ANNOTATIONS {
    summary = "Instance {{ $labels.instance }} down",
    description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.",
  }
```
in latest version 1.6.3 node_exporter is not working.(not showing expressions like node_cpu etc)

i want to configure prometheus with node_exporter,graphana and mysql_exporter.
when apache,mysql and instance down i want to get an alert.
Any suggestions to resolve the issue.
