### ISSUE TITLE
Incorrect CPU statistics for mode "iowait"

### ISSUE THREAD

**Issue by ArmanArbab** [prometheus/prometheus#2856]
**What did you do?**

Attempt to show the percent of time spent, at a particular instant, in a particular mode by the cpu (or rather, the average of all the cpus)

**What did you expect to see?**

Values for each mode under 100%, with the values of all modes summed together equaling 100% when summed.

**What did you see instead? Under which circumstances?**
Unreasonable values for the "iowait" mode. Below are a few queries I executed and their associated outputs: *Whether I specify either one of my two instances, "\*\*:9100" or "\*\*\*:9100", or neither (and thus take the average over both instances), the queries and their associated results/graphs are almost identical.

Time spent in "idle mode" looks reasonable: 

"(avg  by (mode) (rate(node_cpu{mode="idle"}[5m])) * 100)"

1.) ![screen shot 2017-06-16 at 9 55 52 am](https://user-images.githubusercontent.com/20038104/27236560-4fd9e838-527a-11e7-8c76-d660d089c71c.png)

Time spent in "iowait" mode does not- values graphed are almost exclusively above 100%, which should not be possible:

"(avg  by (mode) (rate(node_cpu{mode="iowait"}[5m])) * 100)"

2.) ![screen shot 2017-06-16 at 9 56 28 am](https://user-images.githubusercontent.com/20038104/27236566-557b624e-527a-11e7-90b5-351bfa835d37.png)

The time spent in all modes, except for "iowait", is reasonable/correct:

"(avg  by (mode) (rate(node_cpu{}[5m])) * 100)"

3.) ![screen shot 2017-06-16 at 9 57 01 am](https://user-images.githubusercontent.com/20038104/27236580-5c7c9a9a-527a-11e7-822d-a67eed7122e3.png)

I noticed that the "iowait" mode was also the only mode which had any counter resets. Perhaps this is related to the unreasonable values in the second screenshot (though my impression was that the "rate()" function was supposed to automatically handle counter resets):

"avg by (mode) (resets (node_cpu{}[5m])) "

4.) ![screen shot 2017-06-16 at 9 57 47 am](https://user-images.githubusercontent.com/20038104/27236579-5c7ad264-527a-11e7-8dd4-dd25ead5bbe2.png)

A closer inspection of query in the second screenshot reveals that most CPUs have reasonable/ostensibly correct values, while a couple of cpus are responsible for the high error:

"(avg  by (mode, cpu) (rate(node_cpu{mode="iowait"}[5m])) * 100)"

5.) ![screen shot 2017-06-16 at 10 05 21 am](https://user-images.githubusercontent.com/20038104/27236910-c1f48b84-527b-11e7-8775-b43ddb635e2f.png)
6.) ![screen shot 2017-06-16 at 10 05 53 am](https://user-images.githubusercontent.com/20038104/27236912-c1ff7f44-527b-11e7-88ea-5bdcb87d7006.png)
7.) ![screen shot 2017-06-16 at 10 06 10 am](https://user-images.githubusercontent.com/20038104/27236913-c2030d76-527b-11e7-957b-c8cd8c65f1b8.png)
8.) ![screen shot 2017-06-16 at 10 06 22 am](https://user-images.githubusercontent.com/20038104/27236914-c20589fc-527b-11e7-916f-2b4a52e63337.png)
9.) ![screen shot 2017-06-16 at 10 16 34 am](https://user-images.githubusercontent.com/20038104/27237197-06f34a4e-527d-11e7-88f1-e4a37ca05fb8.png)

Note that when changing the mode to "idle" (or any other mode for that matter), no CPUs have unreasonable values:

"(avg  by (mode, cpu) (rate(node_cpu{mode="idle"}[5m])) * 100)"

10.) ![screen shot 2017-06-16 at 10 15 32 am](https://user-images.githubusercontent.com/20038104/27237171-ee223796-527c-11e7-8ec1-e10bba1d279c.png)
11.) ![screen shot 2017-06-16 at 10 15 58 am](https://user-images.githubusercontent.com/20038104/27237172-ee32baa8-527c-11e7-88e3-5b6a2970467c.png)
12.) ![screen shot 2017-06-16 at 10 16 16 am](https://user-images.githubusercontent.com/20038104/27237170-ee1eae96-527c-11e7-81ce-ea14ec7c3040.png)

A similar pattern emerges when inspecting the counter resets of iowait counter for each CPU (almost all have a value of zero, while a few, not necessarily the same ones that have unreasonably high values, in the screenshots above, have non zero values for the number of counter resets):

"avg by (mode, cpu) (resets (node_cpu{mode="iowait"}[5m])) "

13.) ![screen shot 2017-06-16 at 10 10 04 am](https://user-images.githubusercontent.com/20038104/27237041-63e4e22c-527c-11e7-8fc0-d37a7f400b25.png)
14.) ![screen shot 2017-06-16 at 10 10 22 am](https://user-images.githubusercontent.com/20038104/27237040-63df41fa-527c-11e7-83f7-b70a05f2fc8f.png)
15.) ![screen shot 2017-06-16 at 10 18 08 am](https://user-images.githubusercontent.com/20038104/27237222-2e70704c-527d-11e7-9f47-e8c3c11421a2.png)

Again, there are no counter resets for the "idle" mode (or any other mode for that matter, except for "iowait". Refer to screenshot 4):

"(avg  by (mode, cpu) (resets(node_cpu{mode="idle}[5m]))

16.) ![screen shot 2017-06-16 at 10 19 21 am](https://user-images.githubusercontent.com/20038104/27237273-5af4278a-527d-11e7-837e-d98e792e1b0e.png)

A quick side note, - changing "rate" to "irate" does not result in reasonable values for the "iowait" mode:

"(avg  by (mode) (irate(node_cpu{}[5m])) * 100)"

17.) ![screen shot 2017-06-16 at 10 29 23 am](https://user-images.githubusercontent.com/20038104/27237643-cb4a1228-527e-11e7-8121-5f7de6d61e40.png)

**Environment**

A prometheus server running on a CentOS7 VM, collecting statistics from 2 instances, each a server running Node Exporter on CentOS7.

* System information:

	Linux 3.10.0-514.10.2.el7.x86_64 x86_64

* Prometheus version: 

	prometheus, version 1.7.0 (branch: master, revision: bfa37c8ee39d11078662dce16c162a61dccf616c)
  build user:       root@7a6329cc02bb
  build date:       20170607-09:43:48
  go version:       go1.8.3

* Prometheus configuration file:
```
See attached file (Github doesn't support .yml, so I attached a .txt instead)

[prometheus-config.txt](https://github.com/prometheus/prometheus/files/1081534/prometheus-config.txt)


# my global config
global:
  scrape_interval:     2s # Set the scrape interval to every 2 seconds. Default is every 1 minute.
  evaluation_interval: 2s # Evaluate rules every 2 seconds. The default is every 1 minute.
  scrape_timeout: 2s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'falconMonitoring'

    static_configs:
      - targets: ['**:9100', '***:9100']
        labels:
          group: 'falcon'
                         

```
