### ISSUE TITLE
1.6.1 becomes unresponsive when fails to describe EC2 instances when using auto discovery

### ISSUE THREAD

**Issue by damienmarshall** [prometheus/prometheus#2876]
**What did you do?**
I'm running Prometheus in a docker container on Ubuntu 16.04.02 on AWS using EC2 Auto discovery feature. Every few days I see the following errors in logs, after which CPU usage appears to spike and Prometheus appears to crash, requiring a restart

**Environment**
AWS

* System information:

Linux 4.4.0-1020-aws x86_64

* Prometheus version: 

1.6.1 (have since upgrade to 1.7.1 to see if this helps)

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "host.rules"
  - "containers.rules"
- job_name: node_exporter
    scrape_interval: 20s
    ec2_sd_configs:
      - region: us-east-1
        access_key: <key>
        secret_key: <key>
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
        action: replace
      - source_labels: [__meta_ec2_tag_monitored]
        target_label: instance
        regex: '(fals.*)'
        replacement: '${1}'
        action: drop
```

* Logs:
```
time="2017-06-24T03:43:02Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:42:59Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:43:20Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:43:39Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:43:26Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:45:43Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:46:03Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
time="2017-06-24T03:45:22Z" level=error msg="could not describe instances: RequestError: send request failed\ncaused by: Post https://ec2.us-east-1.amazonaws.com/: dial tcp: i/o timeout" source="ec2.go:116" 
```
