### ISSUE TITLE
Unable to start Prometheus v2.0.0-alpha.3 in Docker container

### ISSUE THREAD

**Issue by anirbanroydas** [prometheus/prometheus#2878]
**What did you do?**
I started prometheus using docker by writing a docker-compose.yml file.

```
version: "3"

services:

  prometheus:
    image: prom/prometheus:v2.0.0-alpha.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ~/prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-storage.local.target-heap-size=524288000'
    restart: unless-stopped
    networks:
      - monitor-backend-dev
    labels:
      io.aroyd.service.name: "prometheus"
      io.aroyd.service.group: "monitoring"
      io.aroyd.service.title: "flitch"

networks:
  monitor-backend-dev:
    driver: bridge
  monitor-frontend-dev:
    driver: bridge
```

**What did you expect to see?**
A successful docker-compose up

**What did you see instead? Under which circumstances?**
Container restarting since restart condition was unless-stopped.

When I checked the logs, I saw the following:
```
sudo docker logs <container_id>
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
```

**Environment**
```
docker version info
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:10:36 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

* System information:

```
Linux 3.13.0-119-generic x86_64
```

* Prometheus version: 

Used docker, so its mentioned in the docker-compose.yml pasted above.

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  # evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #     monitor: 'docker-host-fire'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
# rule_files:
#   - "targets.rules"
#   - "host.rules"
#   - "containers.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'node-exporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  # - job_name: 'cadvisor'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['cadvisor:8080']
```

* Logs: Docker container logs
```
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
prometheus: error: unknown short flag '-c'
```
