### ISSUE TITLE
how to automate  add the new Node Exporters to the targets array of prometheus.yml

### ISSUE THREAD

**Issue by bdonth** [prometheus/prometheus#2881]
i have basic prometheus.yml file in my environment i.e ..

   ```
 ###
    apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: prometheus-core
    data:
      prometheus.yml: |
        global:
          scrape_interval: 10s
          scrape_timeout: 10s
          evaluation_interval: 10s
    
        rule_files:
          - '/etc/prometheus-rules/*.rules'
    
        scrape_configs:
           # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
          - job_name: 'prometheus'
    
            # Override the global default and scrape targets from this job every 5 seconds.
            scrape_interval: 5s
    
            # metrics_path defaults to '/metrics'
            # scheme defaults to 'http'.
    
            static_configs:
              - targets: ['localhost:9090'] 
```

Now if i get any new Nodes in my environment, my prometheus.yml file should get automatically updated my targets section like below i.e.

  ```
  ###
    apiVersion: v1
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      name: prometheus-core
    data:
      prometheus.yml: |
        global:
          scrape_interval: 10s
          scrape_timeout: 10s
          evaluation_interval: 10s
    
        rule_files:
          - '/etc/prometheus-rules/*.rules'
    
        scrape_configs:
           # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
          - job_name: 'prometheus'
    
            # Override the global default and scrape targets from this job every 5 seconds.
            scrape_interval: 5s
    
            # metrics_path defaults to '/metrics'
            # scheme defaults to 'http'.
    
            static_configs:
              - targets: ['localhost:9090','12.10.17.6:9100','12.10.17.19:9100'] 
```

Can any one suggest how i achieve this ?
