### ISSUE TITLE
Kubernetes 1.7.0 requires cAdvisor changes

### ISSUE THREAD

**Issue by unixwitch** [prometheus/prometheus#2916]
In Kubernetes 1.7.0, Kubelet no longer reports cAdvisor metrics on its /metrics endpoint; you have to scrape cAdvisor instead, on port 4194.  This is apparently intentional, and means the provided kubernetes_sd_configs example doesn't work any more.   (Well, it works, but it doesn't return container metrics, which makes it rather less useful than it should be.)

We observed this with an old config that looks like this:

```
- job_name: 'kubernetes-nodes-torchbox-staging'
[...]

  kubernetes_sd_configs:
  - role: node
    api_server: "https://apiserver.whatever:8443"
    [...]

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
```

Because kubernetes_sd_configs picks up the Kubelet port from the Node definition in apiserver, which is 10250 for us, it doesn't scrape port 4194 and therefore doesn't get the cAdvisor metrics.

We fixed this by adding a separate job to scrape port 4194:

```
- job_name: 'kubernetes-cadvisor-torchbox-staging'
  kubernetes_sd_configs:
  - role: node
    [...]

  relabel_configs:
  - source_labels: [__meta_kubernetes_node_address_InternalIP]
    target_label: __address__
    regex: (.*)
    replacement: $1:4194
```

However, looking at the [current version](https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml) of the example, it's now scraping Kubelet using the apiserver proxy.  I assume this was changed to allow scraping nodes without requiring direct access to internal IP addresses.  Unfortunately I don't know how to fix this to scrape cAdvisor as well, or if that's even possible.  Obvious endpoints like `/proxy/cadvisor` don't work and documentation on the proxy endpoints seems hard to find.

In any case, the example config should probably be updated to scrape the new endpoint somehow.

(ref: kubernetes/kubernetes#48483)

**Comment by grobie** [comment]
I'd vote to start splitting the kubernetes example file by version as I know many companies who are (several) minor versions behind.

**Comment by unixwitch** [comment]
Okay, the cAdvisor endpoint is `/api/v1/proxy/nodes/<node>:4194/metrics`.  So the example config could look like this:

```
- job_name: 'kubernetes-cadvisor'

  scheme: https
  
  tls_config:
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  
  kubernetes_sd_configs:
  - role: node
  
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/proxy/nodes/${1}:4194/metrics
```

Should I open a PR, or would that be pointless if this will be rewritten anyway?

**Comment by juliusv** [comment]
@unixwitch I think @grobie's proposal makes sense to split this up into different configs for different Kubernetes versions (we can start with 1.6 vs. 1.7), but otherwise I think a PR sounds great.

**Comment by unixwitch** [comment]
PR at https://github.com/prometheus/prometheus/pull/2918

**Comment by allistera** [comment]
Does this require a change to the ClusterRole when rbac is enabled? 

Changing to use `/api/v1/proxy/nodes/<node>:4194/metrics` starts to return a 403 - Forbidden from the nodes. 

My ClusterRole is the same one from `documentation/examples/rbac-setup.yml`:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
```

**Comment by JorritSalverda** [comment]
I've just fixed the same issue by moving the `/proxy/` part of the path behind instead of in front of the node name, like so:

```
-        replacement: /api/v1/proxy/nodes/${1}:4194/metrics
+        replacement: /api/v1/nodes/${1}:4194/proxy/metrics
```

This makes the `- nodes/proxy` resource in the `ClusterRole` apply to the request and let it through.

It might make sense to leave the kubernetes-nodes job as is without the cadvisor port and add the following separate job to scrape the cadvisor metrics:

```
    - job_name: 'kubernetes-cadvisor'

      scheme: https

      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}:4194/proxy/metrics
```
