### ISSUE TITLE
Docker instance won't scrape

### ISSUE THREAD

**Issue by MihaMarkic** [prometheus/prometheus#2936]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
Run prometheus as docker instance.

**What did you expect to see?**
Scrapes running.

**What did you see instead? Under which circumstances?**
No scrapes are run, both prometheus and mine target are listed as unknown.
Note that service of mine (airpoll) is very simple.

**Environment**
Ubuntu/docker 17.05.0-ce

* System information:

	Linux 4.4.0-83-generic x86_64

* Prometheus version: 

	1.7.1

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
scrape_configs:
  # Scrape Prometheus itself every 5 seconds.
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Scrape the Node Exporter every 5 seconds.
  - job_name: 'airpoll'
    scrape_interval: 5s
    static_configs:
      - targets: ['airpoll:1234']
```

* Logs:
```
airprometheus_1  | time="2017-07-12T08:46:08Z" level=warning msg="Flag -storage.local.memory-chunks is deprecated. Its value 2500 is used to override -storage.local.target-heap-size to 7680000." source="config.go:317"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Starting prometheus (version=1.7.1, branch=master, revision=3afb3fffa3a29c3de865e1172fb740442e9d0133)" source="main.go:88"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Build context (go=go1.8.3, user=root@0aa1b7fc430d, date=20170612-11:44:05)" source="main.go:89"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Host details (Linux 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 953a61dde346 (none))" source="main.go:90"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Loading configuration file /etc/prometheus/prometheus.yml" source="main.go:252"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Loading series map and head chunks..." source="storage.go:428"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="0 series loaded." source="storage.go:439"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Starting target manager..." source="targetmanager.go:63"
airprometheus_1  | time="2017-07-12T08:46:08Z" level=info msg="Listening on :9090" source="web.go:259"
airprometheus_1  | time="2017-07-12T08:46:09Z" level=warning msg="Storage has entered rushed mode." chunksToPersist=0 memoryChunks=0 source="storage.go:1867" urgencyScore=1
airprometheus_1  | time="2017-07-12T08:46:09Z" level=error msg="Storage needs throttling. Scrapes and rule evaluations will be skipped." chunksToPersist=0 memoryChunks=0 source="storage.go:1007" urgencyScore=1
```
