### ISSUE TITLE
Recording rule and adhoc query produce different (floating point) result

### ISSUE THREAD

**Issue by StephanErb** [prometheus/prometheus#2951]
**What did you do?**
Define an aggregation rule for an expensive query. 

```
job:azure_costs_eur:sum =
    sum(azure_costs_eur)
```

The underlying data looks something like this (simplified label set). Please note the large number of digits.
```
azure_costs_eur{resourcegroup="first-resource-group", category="vms"} 100.000049858328046624874
azure_costs_eur{resourcegroup="other-resource-group", category="network"} 0.00002994732437320617
```

The metric has lots of dimensions:
```
count(azure_costs_eur)
694
```

The metric has not changed within the last hour:
```
sum(increase(azure_costs_eur[1h]))
0
```

**What did you expect to see?**
The underlying metric consists of several very slow moving counters. I therefore expect that the aggregation rule and the adhoc query produce the same results. 

**What did you see instead? Under which circumstances?**

Plotting the adhoc query produces a flat line where as plotting the aggregated timeseries produces a non-linear one.

<img width="624" alt="prom-adhoc" src="https://user-images.githubusercontent.com/483730/28229541-6f69b096-68e3-11e7-8ee4-0205c46d0766.png">
<img width="930" alt="prom-rule" src="https://user-images.githubusercontent.com/483730/28229540-6f698652-68e3-11e7-856e-b6f9f0f3d89f.png">

The actual difference is small but still noticeable. 
<img width="743" alt="prod-diff" src="https://user-images.githubusercontent.com/483730/28229539-6f64ba3c-68e3-11e7-8557-dd748c0c4c89.png">

Looking at the data this probably boils down to rounding errors in floating point math. But why does it differ for the recording rule and the adhoc query?

**Environment**

* System information:

	Linux 3.16.0-4-amd64 x86_64

* Prometheus version: 

    prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
        build user:       root@0aa1b7fc430d
        build date:       20170612-11:44:05
        go version:       go1.8.3

* Prometheus configuration file:
```
global:
  evaluation_interval: 15s

  - job_name: azure-cost
    scrape_interval: 1m
    scrape_timeout: 1m
    serverset_sd_configs:
    - servers:
      - 10.x.x.5:2181
      - 10.x.x.6:2181
      - 10.x.x.7:2181
      paths:
      - /path/to/exporter/
      timeout: 30s
    relabel_configs:
     ....
```
* Used exporter https://github.com/blue-yonder/azure-cost-mon
