### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by Cplo** [prometheus/prometheus#2953]
**What did you do?**
Run Prometheus on k8s

**What did you expect to see?**
No more crash

**What did you see instead? Under which circumstances?**
This is happening in both k8s clusters when running for a few days

**Environment**

* System information:

	uname -srm
Linux 4.4.64-1.el7.elrepo.x86_64 x86_64

* Prometheus version: 
prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3

* Alertmanager version:

	N/A

* Prometheus configuration file:
```
**prometheus.yml**
global:
  scrape_interval: 1m
  scrape_timeout: 30s
  evaluation_interval: 1m
  external_labels:
    monitor: tos-monitor
rule_files:
- /etc/alert.rules
- /etc/recording.rules
scrape_configs:
- job_name: k8s-apiservers
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: https://10.10.10.1
    role: endpoints
    tls_config:
      ca_file: /srv/kubernetes/ca.crt
      cert_file: /srv/kubernetes/kubecfg.crt
      key_file: /srv/kubernetes/kubecfg.key
      insecure_skip_verify: false
    namespaces:
      names: []
  tls_config:
    ca_file: /srv/kubernetes/ca.crt
    cert_file: /srv/kubernetes/kubecfg.crt
    key_file: /srv/kubernetes/kubecfg.key
    insecure_skip_verify: false
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    separator: ;
    regex: default;kubernetes;https
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_label_component]
    separator: ;
    regex: (.+)
    target_label: tos_component
    replacement: kube-apiserver
    action: replace
- job_name: k8s-kubelet
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: https://10.10.10.1
    role: node
    tls_config:
      ca_file: /srv/kubernetes/ca.crt
      cert_file: /srv/kubernetes/kubecfg.crt
      key_file: /srv/kubernetes/kubecfg.key
      insecure_skip_verify: false
    namespaces:
      names: []
  tls_config:
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: []
    separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
- job_name: k8s-service-endpoints
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: https://10.10.10.1
    role: endpoints
    tls_config:
      ca_file: /srv/kubernetes/ca.crt
      cert_file: /srv/kubernetes/kubecfg.crt
      key_file: /srv/kubernetes/kubecfg.key
      insecure_skip_verify: false
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    separator: ;
    regex: (https?)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - source_labels: []
    separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
- job_name: k8s-services
  params:
    module:
    - http_2xx
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /probe
  scheme: http
  kubernetes_sd_configs:
  - api_server: https://10.10.10.1
    role: service
    tls_config:
      ca_file: /srv/kubernetes/ca.crt
      cert_file: /srv/kubernetes/kubecfg.crt
      key_file: /srv/kubernetes/kubecfg.key
      insecure_skip_verify: false
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: []
    separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - source_labels: []
    separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
- job_name: k8s-pods
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: https://10.10.10.1
    role: pod
    tls_config:
      ca_file: /srv/kubernetes/ca.crt
      cert_file: /srv/kubernetes/kubecfg.crt
      key_file: /srv/kubernetes/kubecfg.key
      insecure_skip_verify: false
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - source_labels: []
    separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace
```
```
**recording.rules**
kubelet:node:cpu:usage{} = sum(rate(container_cpu_usage_seconds_total{id="/"}[5m])) BY (kubernetes_io_hostname) / sum(machine_cpu_cores) BY (kubernetes_io_hostname) * 100
kubelet:node:mem:usage{} = sum(container_memory_working_set_bytes{id="/"}) BY (kubernetes_io_hostname) / sum(machine_memory_bytes) BY (kubernetes_io_hostname) * 100
kubelet:namespace:cpu:usage{} = sum(rate(container_cpu_usage_seconds_total[5m])) BY (namespace) / scalar(sum(machine_cpu_cores)) * 100
kubelet:namespace:cpu:used{} = sum(rate(container_cpu_usage_seconds_total[5m])) BY (namespace)
kubelet:namespace:mem:usage{} = sum(container_memory_working_set_bytes) BY (namespace) / scalar(sum(machine_memory_bytes)) * 100
kubelet:namespace:mem:used{} = sum(container_memory_working_set_bytes) BY (namespace)
kubelet:namespace:network_received:used{} = sum(rate(container_network_receive_bytes_total[5m])) BY (namespace)
kubelet:namespace:network_sent:used{} = -sum(rate(container_network_transmit_bytes_total[5m])) BY (namespace)
kubelet:pod:cpu:used{} = sum(rate(container_cpu_usage_seconds_total[5m])) BY (pod_name, namespace, kubernetes_io_hostname)
kubelet:pod:mem:used{} = sum(container_memory_working_set_bytes) BY (pod_name, namespace, kubernetes_io_hostname)
kubelet:pod:network:received:used{} = sum(rate(container_network_receive_bytes_total[5m])) BY (pod_name, namespace, kubernetes_io_hostname)
kubelet:pod:network:sent:used{} = -sum(rate(container_network_transmit_bytes_total[5m])) BY (pod_name, namespace, kubernetes_io_hostname)
kubelet:node:update_latency_count:rate{} = rate(kubelet_node_status_update_latency_microseconds_count[5m])
kubelet:node:filesystem:usage{} = container_fs_usage_bytes{id="/"} / container_fs_limit_bytes{id="/"} * 100
kubelet:k8s_container:cpu:used{} = sum(rate(container_cpu_usage_seconds_total[5m])) BY (container_name, pod_name, namespace, kubernetes_io_hostname)
kubelet:docker_container:cpu:used{} = sum(rate(container_cpu_usage_seconds_total{id!="/",name!="",namespace=""}[5m])) BY (name)
kubelet:k8s_container:mem:used{} = sum(container_memory_working_set_bytes) BY (namespace, pod_name, container_name, kubernetes_io_hostname)
kubelet:k8s_container:mem:usage{} = sum(container_memory_working_set_bytes{container_name!="",container_name!="POD"}) BY (namespace, pod_name, container_name, kubernetes_io_hostname) / sum(container_spec_memory_limit_bytes) BY (namespace, pod_name, container_name, kubernetes_io_hostname) * 100
kubelet:docker_container:mem:used{} = sum(container_memory_working_set_bytes{id!="/",name!="",namespace=""}) BY (name)
kubelet:k8s_container:network_received:used{} = sum(rate(container_network_receive_bytes_total[5m])) BY (container_name, pod_name, namespace, kubernetes_io_hostname)
kubelet:k8s_container:network_sent:used{} = sum(rate(container_network_transmit_bytes_total[5m])) BY (container_name, pod_name, namespace, kubernetes_io_hostname)
kubelet:docker_container:network_received:used{} = sum(rate(container_network_receive_bytes_total{id!="/",name!="",namespace=""}[5m])) BY (name)
kubelet:docker_container:network_sent:used{} = sum(rate(container_network_transmit_bytes_total{id!="/",name!="",namespace=""}[5m])) BY (name)
kubelet:container:cpu_usage{} = sum(rate(container_cpu_usage_seconds_total[5m])) BY (container_name, pod_name, namespace, kubernetes_io_hostname)
kubelet:container:mem_usage{} = sum(container_memory_working_set_bytes) BY (container_name, pod_name, namespace, kubernetes_io_hostname)
apiserver:request_count:rate{} = sum(rate(apiserver_request_count[5m])) BY (instance)
apiserver:latency_histogram_quantile{quantile="0.99"} = histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH"}[10m])) WITHOUT (instance, node, resource)) / 1000000
apiserver:latency_histogram_quantile{quantile="0.9"} = histogram_quantile(0.9, sum(rate(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH"}[10m])) WITHOUT (instance, node, resource)) / 1000000
apiserver:latency_histogram_quantile{quantile="0.5"} = histogram_quantile(0.5, sum(rate(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH"}[10m])) WITHOUT (instance, node, resource)) / 1000000
apiserver:etcd_access_latency{quantile="0.99"} = etcd_request_latencies_summary{quantile="0.99"} / 1000000
apiserver:etcd_access_latency{quantile="0.9"} = etcd_request_latencies_summary{quantile="0.9"} / 1000000
apiserver:etcd_access_latency{quantile="0.5"} = etcd_request_latencies_summary{quantile="0.5"} / 1000000
node_exporter:node_cpu_use:percent{} = 100 * (1 - avg(rate(node_cpu{mode="idle"}[5m])) BY (instance))
node_exporter:node_mem_use:percent{} = 100 * (1 - (node_memory_MemFree + node_memory_Cached + node_memory_Buffers) / (1 + node_memory_MemTotal))
node_exporter:node_disk_use:percent{} = 100 * (1 - node_filesystem_free{device=~"/dev.*",mountpoint!~"/etc.*|/run.*"} / (1 + node_filesystem_size))
node_exporter:node_swapmem_use:percent{} = 100 * (node_memory_SwapTotal - node_memory_SwapFree) / (node_memory_SwapTotal + 1)
kubestate:pod:running_count:percent{} = kubelet_running_pod_count * scalar(count(kube_node_status_capacity_pods)) / scalar(sum(kube_node_status_capacity_pods)) * 100
```

* Alertmanager configuration file:
N/A

* Logs:
```
prometheus nodeA
panic: runtime error: integer divide by zero
goroutine 925330 [running]:
github.com/prometheus/prometheus/storage/local/chunk.doubleDeltaEncodedChunk.Add(0xc48584cc00, 0x237, 0x400, 0x15d43080e84, 0x7ff8000000000001, 0xc448fdf801, 0x1000000027489f0, 0xc4392c23f0, 0xc457f9b840, 0x15d4954)
　　/go/src/github.com/prometheus/prometheus/storage/local/chunk/doubledelta.go:86 +0xf78
github.com/prometheus/prometheus/storage/local/chunk.(doubleDeltaEncodedChunk).Add(0xc4c86369e0, 0x15d43080e84, 0x7ff8000000000001, 0xc457f9b780, 0x4107fd, 0xc44df7e1c8, 0xc48ccbdb40, 0x0) :39 +0x75
github.com/prometheus/prometheus/storage/local/chunk.(Desc).Add(0xc499b25d40, 0x15d43080e84, 0x7ff8000000000001, 0xc4a08c6400, 0x453cc0, 0xc4a08c6400, 0x1b7fd00, 0xc48ccbdb58)
　　/go/src/github.com/prometheus/prometheus/storage/local/chunk/chunk.go:142 +0x53 github.com/prometheus/prometheus/storage/local.(*memorySeries).add(0xc4392c23f0, 0x15d43080e84, 0x7ff8000000000001, 0xc4392c23f0, 0x0, 0x0)
　　/go/src/github.com/prometheus/prometheus/storage/local/series.go:226 +0x109 github.com/prometheus/prometheus/storage/local.(*MemorySeriesStorage).Append(0xc42045c000, 0xc43132d480, 0x0, 0x0)
　　/go/src/github.com/prometheus/prometheus/storage/local/storage.go:953 +0x324 github.com/prometheus/prometheus/storage.Fanout.Append(0xc420400020, 0x2, 0x2, 0xc43132d480, 0x19da820, 0xc457f9ba00)
/go/src/github.com/prometheus/prometheus/storage/storage.go:60 +0x66 github.com/prometheus/prometheus/storage.(Fanout).Append(0xc420400440, 0xc43132d480, 0x27489f0, 0xc448fdf8c0) :3 +0x69
github.com/prometheus/prometheus/retrieval.(countingAppender).Append(0xc48f9a79c0, 0xc43132d480, 0xc457f9ba78, 0xc448fdf9a8)
　　/go/src/github.com/prometheus/prometheus/retrieval/target.go:261 +0x48 github.com/prometheus/prometheus/retrieval.ruleLabelsAppender.Append(0x2695400, 0xc48f9a79c0, 0xc46fed7230, 0xc43132d480, 0x0, 0x0)
　　/go/src/github.com/prometheus/prometheus/retrieval/target.go:201 +0x1af github.com/prometheus/prometheus/retrieval.(ruleLabelsAppender).Append(0xc48f9a79e0, 0xc43132d480, 0x0, 0x0) :35 +0x69
github.com/prometheus/prometheus/retrieval.(*scrapeLoop).append(0xc488c3d9d0, 0xc49b094000, 0x22a, 0x330, 0x2e80ac07, 0x2759c20, 0xc49b094000)
　　/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:520 +0x2ec github.com/prometheus/prometheus/retrieval.(scrapeLoop).run(0xc488c3d9d0, 0xdf8475800, 0x6fc23ac00, 0x0)
　　/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:430 +0x614 created by github.com/prometheus/prometheus/retrieval.(*scrapePool).reload.func1
　　/go/src/github.com/prometheus/prometheus/retrieval/scrape.go:195 +0x82
```
```
prometheusNodeB
panic: runtime error: integer divide by zero
goroutine 1614997 [running]: 
github.com/prometheus/prometheus/storage/local/chunk.doubleDeltaEncodedChunk.Add(0xc488f93400, 0xbe, 0x400, 0x15d3c097f3a, 0x0, 0x0, 0xc4a2597b88, 0x42a15f, 0x1b86de0, 0xc4a2597b98)   
　　/go/src/github.com/prometheus/prometheus/storage/local/chunk/doubledelta.go:86 +0xf78 
github.com/prometheus/prometheus/storage/local/chunk.(doubleDeltaEncodedChunk).Add(0xc43613ec40, 0x15d3c097f3a, 0x0, 0xc4a2597bb0, 0x1543cc2, 0xc490fe8680, 0x1b86de0, 0xc490fe8680) :39 +0x75 
github.com/prometheus/prometheus/storage/local/chunk.(Desc).Add(0xc490fe8680, 0x15d3c097f3a, 0x0, 0x0, 0x14, 0x3, 0xc448f73520, 0xc494c67980)   
　　/go/src/github.com/prometheus/prometheus/storage/local/chunk/chunk.go:142 +0x53 
github.com/prometheus/prometheus/storage/local.(*memorySeries).add(0xc425876a80, 0x15d3c097f3a, 0x0, 0xc425876a80, 0x0, 0x0)      
　　/go/src/github.com/prometheus/prometheus/storage/local/series.go:226 +0x109   
github.com/prometheus/prometheus/storage/local.(MemorySeriesStorage).Append(0xc420786000, 0xc47e5dfc20, 0x0, 0x0) /go/src/github.com/prometheus/prometheus/storage/local/storage.go:953 +0x324 github.com/prometheus/prometheus/storage.Fanout.Append(0xc4201c32c0, 0x2, 0x2, 0xc47e5dfc20, 0x0, 0x0) /go/src/github.com/prometheus/prometheus/storage/storage.go:60 +0x66   
github.com/prometheus/prometheus/storage.(Fanout).Append(0xc4201c3c40, 0xc47e5dfc20, 0x0, 0x0) :3 +0x69 
github.com/prometheus/prometheus/rules.(Group).Eval.func1(0xc46bb9e8b0, 0x1af9836, 0x9, 0xc42015eaa0, 0x15d3c097f3a, 0x26a2d40, 0xc420c20ba0) 
　　/go/src/github.com/prometheus/prometheus/rules/manager.go:296 +0x23a created by github.com/prometheus/prometheus/rules.(Group).Eval            
　　/go/src/github.com/prometheus/prometheus/rules/manager.go:315 +0x138

```
