### ISSUE TITLE
splitting kubernetes service ip with regex

### ISSUE THREAD

**Issue by bahho** [prometheus/prometheus#2971]
[NOTICE]: <> (If your question is around usage and not a bug in Prometheus please use: https://groups.google.com/forum/#!forum/prometheus-users)

**What did you do?**
I have pods with jmx-exporter. I would like to scrape only the exposed ports. 
I do use the annotation "prometheus.io/port" but to be that only the exposed port is scraped in case some pods/services dont have the annotation.  To do so I am trying to replace the ports in the addresses that I get from the service endpoints. 

I have multiple ports exposed in the pods so that with the below config I get endpoints in prometheus like 
`
http://10.131.0.2:1111
http://10.131.0.2:2222
http://10.131.0.2:3333
http://10.131.0.2:4444
`
 
I would like to split up the pod IP and append the port number I would like to scrape. 

I don't seem to  be able to make use of the regexes...

What I need is something like 
```
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: functioning regex 
        replacement:  ${1}:2222
 ```
where ${1} is the service IP and 2222 is the port I want.

Can anybody help me with that?

 
**Environment**
OpenShift 

* Prometheus version: 

	1.6.2

 
* Prometheus configuration file:
```
    - job_name: 'kubernetes-test'
      kubernetes_sd_configs:
      - role: endpoints

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement:  
 
```
