### ISSUE TITLE
Prometheus 2.0.0-beta.0 gaps in metrics

### ISSUE THREAD

**Issue by hanikesn** [prometheus/prometheus#2982]
I'm running the prometheus 2.0.0-beta.0 in our kubernetes 1.7.1 cluster and it's having trouble with gaps in the metrics which are scraped from cadvisor. Prometheus 1 .7.0 scrapes them fine:

2.0.0-beta.0
![prometheus2](https://user-images.githubusercontent.com/630711/28517440-af2a09a0-7064-11e7-810d-df8deb52c40d.png)

1.7.0
![promtheus](https://user-images.githubusercontent.com/630711/28517439-abcefee6-7064-11e7-9b06-d6a23797b843.png)

Scrape rule:
```
- job_name: kubernetes-cadvisor
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: node
    namespaces:
      names: []
```

There's nothing suspicious in the logs.
