### ISSUE TITLE
Metrics not collected when there are bogus characters on /metrics page

### ISSUE THREAD

**Issue by ajardan** [prometheus/prometheus#2983]
**What did you do?**
Collecting metrics from traefik proxy

**What did you expect to see?**
metrics to be saved in prometheus 

**What did you see instead? Under which circumstances?**
no metrics were collected when there were bogus charactes in /metrics page

(see https://github.com/containous/traefik/issues/1821)
**Environment**

* System information:

Linux 3.10.0-514.21.1.el7.x86_64 x86_64

* Prometheus version: 

	prometheus, version 1.6.1 (branch: master, revision: 4666df502c0e239ed4aa1d80abbbfb54f61b23c3)
  build user:       root@7e45fa0366a7
  build date:       20170419-14:32:22
  go version:       go1.8.1

* Prometheus configuration file:
```
global:
  scrape_interval:     30s
  evaluation_interval: 30s

  labels:
    cluster: swarm
    replica: "1"

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-swarm'

rule_files:
  - "alert.rules_nodes"
  - "alert.rules_tasks"
  - "alert.rules_service-groups"
  - job_name: 'load-balancer'
    dns_sd_configs:
    - names:
      - 'tasks.load-balancer'
      type: 'A'
      port: 9080```

* Logs:
```
unfortunately, there's nothing in the logs```
