### ISSUE TITLE
Use Kubernetes annotations to configure kubernetes_sd

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#2989]
I propose that we take advantages of kubernetes annotations to configure scraping per pod/service:

```
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: foo
  labels:
    app: foo
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: '/metrics'
      labels:
        app: foo
    spec:
      containers:
      - name: foo
        image: foo:latest
        ports:
        - containerPort: 8080
```
