### ISSUE TITLE
Feature Request: Global Configuration for Scrape Configs

### ISSUE THREAD

**Issue by agolomoodysaada** [prometheus/prometheus#2999]
**What did you do?**
Tried to add azure_sd_configs in `global` block to reuse in multiple scrape jobs.

**What did you expect to see?**
It works! I don't have to rewrite all my configurations in every job block.

**What did you see instead? Under which circumstances?**
Unsupported feature

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version: 1.7

* Prometheus configuration file:

Current configuration file

```yml
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: <service1>
    azure_sd_configs:
      - subscription_id: <...>
        client_id: <...>
        client_secret: <...>
        tenant_id: <...>
        refresh_interval: <...>
    relabel_configs:
      # ...common relabeling configs
      - source_labels: [__meta_azure_machine_name]
        target_label: instance
      - source_labels: [__meta_azure_machine_resource_group]
        target_label: resource_group
      - source_labels: [__meta_azure_machine_location]
        target_label: location
      # ...specific relabeling configs
      # ...
  - job_name: <service2>
    azure_sd_configs:
      - subscription_id: <...>
        client_id: <...>
        client_secret: <...>
        tenant_id: <...>
        refresh_interval: <...>
    relabel_configs:
      # ...common relabeling configs
      - source_labels: [__meta_azure_machine_name]
        target_label: instance
      - source_labels: [__meta_azure_machine_resource_group]
        target_label: resource_group
      - source_labels: [__meta_azure_machine_location]
        target_label: location
      # ...specific relabeling configs
      # ...
  - job_name: <service3>
    azure_sd_configs:
      - subscription_id: <...>
        client_id: <...>
        client_secret: <...>
        tenant_id: <...>
        refresh_interval: <...>
    relabel_configs:
      # ...common relabeling configs
      - source_labels: [__meta_azure_machine_name]
        target_label: instance
      - source_labels: [__meta_azure_machine_resource_group]
        target_label: resource_group
      - source_labels: [__meta_azure_machine_location]
        target_label: location
      # ...specific relabeling configs
      # ...
```

Desired configuration file
```yml
global:
  scrape_interval: 5s
  scrape_configs:
    - azure_sd_configs:
      - subscription_id: <...>
        client_id: <...>
        client_secret: <...>
        tenant_id: <...>
        refresh_interval: <...>
    - relabel_configs:
    # ...common relabeling configs

scrape_configs:
  - job_name: <service1>
    azure_sd_configs:
      - global.scrape_configs.azure_sd_configs
        # ...specific overrides
        refresh_interval: <...>
    relabel_configs:
      - global.scrape_configs.relabel_configs
        # ...specific overrides
      - source_labels: [__meta_azure_machine_name]
        regex:  'service1.*'
        action: keep
  - job_name: <service2>
    azure_sd_configs:
      - global.scrape_configs.azure_sd_configs
        # ...specific overrides
        refresh_interval: <...>
    relabel_configs:
      - global.scrape_configs.relabel_configs
        # ...specific overrides
      - source_labels: [__meta_azure_machine_name]
        regex:  'service2.*'
        action: keep
  - job_name: <service3>
    azure_sd_configs:
      - global.scrape_configs.azure_sd_configs
        # ...specific overrides
        refresh_interval: <...>
    relabel_configs:
      - global.scrape_configs.relabel_configs
        # ...specific overrides
      - source_labels: [__meta_azure_machine_name]
        regex:  'service3.*'
        action: keep

```
