### ISSUE TITLE
Bug in ConsulSD when using multiple jobs in same config.

### ISSUE THREAD

**Issue by civik** [prometheus/prometheus#3007]
**What did you do?**

Added multiple jobs, both using ConsulSD.

For example:

       - job_name: 'myconsuljob1'
          scrape_interval: 1m
          scrape_timeout: 55s
          consul_sd_configs:
          - server: 'my1.foo.com:8500'
          ...

       - job_name: 'myconsuljob2'
          scrape_interval: 1m
          scrape_timeout: 55s
          consul_sd_configs:
          - server: 'my2.foo.com:8500'

**What did you expect to see?**

Both jobs would discover properly

**What did you see instead? Under which circumstances?**

Only 1st ConsulSD job in the config seems to work - if I switch the order in the config-it will give me the other set of discovered hosts.  If I change one of the target consul servers, it seems to discover both until the Prometheus server gets restarted, then it reverts back to only discovering the first job in the config.

**Environment**

* System information:

Linux 3.10.0-514.21.1.el7.x86_64 x86_64

* Prometheus version: 

1.7.1

* Prometheus configuration file:
```
    global:
      scrape_interval: 60s
      scrape_timeout: 55s
      evaluation_interval: 55s
      external_labels:
        k8s_datacenter: xxx
        k8s_cluster: xxx

    rule_files:
    - "/etc/config/*.rule"

    scrape_configs:
    - job_name: ingress-check
      metrics_path: /probe
      params:
        module:
        - http_2xx
      relabel_configs:
      - regex: (.*)(:80)?
        replacement: ${1}
        source_labels:
        - __address__
        target_label: __param_target
      - regex: (.*)
        replacement: ${1}
        source_labels:
        - __param_target
        target_label: instance
      - regex: .*
        replacement: blackbox-prod:9115
        source_labels: []
        target_label: __address__
      static_configs:
      - labels:
          sourceenv: xx1
          sourcesvc: ingress
        targets:
        - https://xxx/
      - labels:
          sourceenv: xx2
          sourcesvc: ingress
        targets:
        - https://xxx/
      - labels:
          sourceenv: xx1
          sourcesvc: consul
        xxfooxxs:
        - http://xx11001.xxfooxx.com:8500/v1/status/leader
        - http://xx11002.xxfooxx.com:8500/v1/status/leader
        - http://xx11003.xxfooxx.com:8500/v1/status/leader
      - labels:
          sourceenv: xx2-prod
          sourcesvc: consul
        xxfooxxs:
        - http://xx21001.xxfooxx.com:8500/v1/status/leader
        - http://xx21002.xxfooxx.com:8500/v1/status/leader
        - http://xx21003.xxfooxx.com:8500/v1/status/leader
      - labels:
          sourceenv: xx1-prod
          sourcesvc: etcd
        targets:
        - http://10.XX.XX.XXX:2379/health
        - http://10.XX.XX.XXY:2379/health
        - http://10.XX.XX.XXZ:2379/health
      - labels:
          sourceenv: xx2-prod
          sourcesvc: etcd
        targets:
        - http://10.XX.XX.XXX:2379/health
        - http://10.XX.XX.XXY:2379/health
        - http://10.XX.XX.XXZ:2379/health

    - job_name: 'xx2-federate'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
        - '{job="kubernetes-apiservers"}'
        - '{job="kubernetes-service-endpoints"}'
        - '{job="kubernetes-pods"}'
        - '{job="kubernetes-nodes"}'
      static_configs:
        - targets:
          - 'prometheus.us-central-1xx2.core'

    - job_name: 'xx1-federate'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      honor_labels: true
      metrics_path: '/federate'
      scheme: https
      params:
        'match[]':
        - '{job="kubernetes-apiservers"}'
        - '{job="kubernetes-service-endpoints"}'
        - '{job="kubernetes-pods"}'
        - '{job="kubernetes-nodes"}'
      static_configs:
        - targets:
          - 'prometheus.us-central-1xx1.core'

    - job_name: 'k8s-metal-xx2'
      scrape_interval: 2m
      scrape_timeout: 115s
      consul_sd_configs:
      - server: 'xx21002.xxfooxx:8500'
        services: ['nomad-client']
        scheme: http
      relabel_configs:
      - source_labels: [__meta_sd_consul_tags]
        separator:     ','
        regex:         label:([^=]+)=([^,]+)
        target_label:  ${1}
        replacement:   ${2}
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):(4646)'
        target_label:  '__address__'
        replacement:   '${1}:9101'

    - job_name: 'k8s-metal-xx1'
      scrape_interval: 2m
      scrape_timeout: 115s
      consul_sd_configs:
      - server: 'xx11003.xxfooxx:8500'
        services: ['nomad-client']
        scheme: http
      relabel_configs:
      - source_labels: [__meta_sd_consul_tags]
        separator:     ','
        regex:         label:([^=]+)=([^,]+)
        target_label:  ${1}
        replacement:   ${2}
      - source_labels: ['__address__']
        separator:     ':'
        regex:         '(.*):(4646)'
        target_label:  '__address__'
        replacement:   '${1}:9101'

```

**Comment by krasi-georgiev** [comment]
DIBS
any idea if this has been already fixed or has an open PR?

**Comment by civik** [comment]
Let me know if you need any additional data.  Currently still exhibiting this problem.  Config above only will load the hosts in the first SD job.

I'm basically repurposing another consul service that has the hosts I want, and relabeling to change the port to node_ex port.  Thats pretty much the only out of the ordinary thing I'm doing.

**Comment by krasi-georgiev** [comment]
@civik have you checked it against the dev-2.0 branch ? 
I think this will be reales soon and if it works well there than it might be better to just wait.

Otherwise if any of the maintainers confirms it is ok to fix in this branch I can work on it.

**Comment by grobie** [comment]
@krasi-georgiev I'm reasonably sure the bug is specific to the consul sd implementation and hasn't been fixed in dev-2.0. Please feel free to give it a shot here, we'll release Prometheus v1.8 before the big 2.0 release. I'd love to review a PR to fix this bug (mention me in the PR in case you're able to find and fix it).

**Comment by krasi-georgiev** [comment]
@civik @grobie I am not able to replicate the issue, my setup works and prometheus finds both jobs every time. Tested against `v1.7.1` and `master`

It seems there is something different in your setup so let me know what you think is different and I will keep trying. 
Maybe try stripping down your config and maybe something in the file config is confusing the parsing.

I used Docker and this my setup:
```
#create a network so that the containers can talk to each other
docker network create x

#start 2 independent consult servers
docker run -d --name consul --net=x -p 8500:8500 consul agent -dev -client=0.0.0.0 -bind=0.0.0.0
docker run -d --name consul1 --net=x -p 8501:8500 consul agent -dev -client=0.0.0.0 -bind=0.0.0.0

#connect one exporter to each consult server
docker run -d --net=x -p 9107:9107 prom/consul-exporter -consul.server=consul:8500
docker run -d --net=x  -p 9108:9107 prom/consul-exporter -consul.server=consul1:8500

#start one registrator for each consul server to register the exporters and 
#than in the prometheus config set to scrape only the `consul-exporter` containers
docker run -d --net=x --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip="127.0.0.1" consul://consul:8500
docker run -d --net=x --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip="127.0.0.1" consul://consul1:8500
```


config
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: myconsuljob1
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: my1.foo.com:8500
    tag_separator: ','
    scheme: http
    services:
    - consul-exporter
- job_name: myconsuljob2
  scrape_interval: 5s
  scrape_timeout: 4s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: my2.foo.com:8501
    tag_separator: ','
    scheme: http
    services:
    - consul-exporter
```

my1.foo.com and my1.foo.com are pointing to the local consul docker containers at 127.0.0.1

**Comment by civik** [comment]
I just stripped my config down to the bare minimum. This is my current running config.  I did try it without the relabels but that also didnt help.

```
scrape_configs:
- job_name: k8s-metal-1
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 50s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: 10.6.5.10:8500
    tag_separator: ','
    scheme: http
    services:
    - nomad-client
  relabel_configs:
  - source_labels: [__address__]
    separator: ':'
    regex: (.*):(4646)
    target_label: __address__
    replacement: ${1}:9101
    action: replace
- job_name: k8s-metal-2
  honor_labels: true
  scrape_interval: 1m
  scrape_timeout: 50s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: 10.7.5.10:8500
    tag_separator: ','
    scheme: http
    services:
    - nomad-client
  relabel_configs:
  - source_labels: [__address__]
    separator: ':'
    regex: (.*):(4646)
    target_label: __address__
    replacement: ${1}:9101
    action: replace
```

Some possible idiosyncrasies:
- Consul 7.x in a 3 node cluster
- Deploying with Helm
- Consul running on a remote host
- Consul running on same PORT (8500), but on different SERVERS

just spitballin' here...
