### ISSUE TITLE
Slow connection leak (v2 beta 0)

### ISSUE THREAD

**Issue by aecolley** [prometheus/prometheus#3039]
**What did you do?**
Left prometheus running with 700 monitor targets (scrape intervals variously 1m or 2m; scrape timeout 20s) for a week.

**What did you expect to see?**
process_open_fds (of prometheus itself) plateauing at about 1000.

**What did you see instead? Under which circumstances?**
process_open_fds increased from 1325 to 12531 over 5 days. At the end of that time, prometheus had multiple established TCP connections open to some monitor targets. Specifically, 485 targets had 1 connection; 36 targets had 30-40 open connections each; and 3 targets had 392 open connections each. These are counts taken using `ss` on the prometheus host.

I haven't yet established a cause, but there's an odd correlation with the value of the `Content-Type` header in the response from the monitor targets. All of the 1-connection targets say "Content-Type: text/plain; version=0.0.4; charset=UTF-8"; all of the 30-connection targets say "Content-Type: application/octet-stream"; and all of the 392-connection targets say "Content-Type: text/plain; version=0.0.4".

The 3 392-connection targets are two `pushgateway` servers and one `node_exporter` server.

**Environment**

* System information:

	`uname -srm`: Linux 3.10.0-514.21.2.el7.x86_64 x86_64

* Prometheus version: 

	prometheus, version 2.0.0-beta.0 (branch: tripadvisor/releng-2.0.0, revision: tr-prometheus-2.0.0-0.3.el7)
	build user:       mockbuild
	build date:       20170726-18:54:10
	go version:       go1.8.3

Yes, this is a private build forked from the 2.0.0-beta.0 release tag. I'm trying to reproduce it using the official release binary in a dev environment. I'm filing this bug report early in case others see the same thing.

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 20s
  evaluation_interval: 1m
[...]
scrape_configs:
- job_name: target_with_1_conn_each
  scrape_interval: 2m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /path/to/generated_target_list.json
    refresh_interval: 1h
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: collectd_exporter
    replacement: $1
    action: drop
- job_name: target_with_30_conns_each
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /path/to/targetlist.yml
    refresh_interval: 1h
[...]
- job_name: node
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9100
    labels:
      instance: myhostname:9100
- job_name: pushgateway
  scrape_interval: 1m
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /path/to/pushgateway.yml
    refresh_interval: 1h
[...]
```

* Logs:

nothing seems to correlate
