### ISSUE TITLE
gce_sd has full url in zone meta data

### ISSUE THREAD

**Issue by mkm85** [prometheus/prometheus#3042]
**What did you do?**
I created a gce sd config like

```
scrape_configs:
  - job_name: 'nodes'
    gce_sd_configs:
      - project: 'project'
        port: 9100
        zone: 'asia-southeast1-a'
    relabel_configs:
      - source_labels: ['__meta_gce_zone']
        target_label: region
        regex: '(.*)-[a-z]'
```
and started prometheus, then I can see that the __meta_gce_zone contains much more than just the zone, it contains an url which ends with the zone"

This is also a problem for '__meta_gce_network' and '__meta_gce_subnetwork'

**What did you expect to see?**

Labels: region="asia-southeast1"

**What did you see instead? Under which circumstances?**
Labels: region="https://www.googleapis.com/compute/v1/projects/project/zones/asia-southeast1"

**Environment**
```
Version	1.7.1
Revision	3afb3fffa3a29c3de865e1172fb740442e9d0133
Branch	master
BuildUser	root@0aa1b7fc430d
BuildDate	20170612-11:44:05
GoVersion	go1.8.3
```
Running on google compute engine (GCE) in a docker container. It's the official 1.7.1 docker image

* System information:
Linux 4.10.0-30-generic x86_64
