### ISSUE TITLE
openstack-sd unsupported protocol scheme 

### ISSUE THREAD

**Issue by luchetto81** [prometheus/prometheus#3066]
Dear All,

I'm deploying Prometheus via docker mounting the config file inside the container.
The `static_configs` are working fine. 

When I try to use the openstack autodiscovery
I got an error that is related to a not supported protocol schema but I'm explicitly writing ```http://``` or ```https://``` before the endpoint.
Another error which is appearing the the missing password or tocken which as well I'm giving.
Below there are the logs and my config file.

Thanks so much in advance for any help. 

* System information:

```
# docker --version
Docker version 1.12.6, build 78d1802
```

* Prometheus version: 

```
prom/prometheus     v1.7.1              4da113bb6ae3        9 weeks ago         74.49 MB
```

* Prometheus configuration file:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'

    metrics_path: '/prometheus'

    static_configs:
      - targets: ['X.X.X.X:8080']

  - job_name: 'Openstack'

    #scheme: 'https'

    openstack_sd_configs:
      - region: '<RegionName>'
      - identity_endpoint: 'https://<whatever>:<anynumber>/v2.0'
      - username: '<myusername>'
      - password: '<mypassword>'
      - project_id: '<mytenant_id>'
      - project_name: '<mytenant_name>'
```

* Logs:
```
time="2017-08-14T12:54:53Z" level=info msg="Listening on :9090" source="web.go:259"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Get /: unsupported protocol scheme """ source="openstack.go:99"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Get /: unsupported protocol scheme """ source="openstack.go:99"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Get /: unsupported protocol scheme """ source="openstack.go:99"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Get /: unsupported protocol scheme """ source="openstack.go:99"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Exactly one of PasswordCredentials and TokenCredentials must be provided" source="openstack.go:99"
time="2017-08-14T12:54:53Z" level=error msg="could not create OpenStack session: Get /: unsupported protocol scheme """ source="openstack.go:99"
```

**Comment by luchetto81** [comment]
I think I found the error the right configuration was:
```
openstack_sd_configs:
      - region: '<RegionName>'
        identity_endpoint: 'https://<whatever>:<anynumber>/v2.0'
        username: '<myusername>'
        password: '<mypassword>'
        project_id: '<mytenant_id>'
        project_name: '<mytenant_name>'
```
