### ISSUE TITLE
Discover k8s ingress

### ISSUE THREAD

**Issue by bechtoldt** [prometheus/prometheus#3071]
It'd be great to have automatic discovery of ingress resources based on annotations like for services, pods, endpoints, etc. for blackbox checks and similar:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myservice
  annotations:
    prometheus.io/probe: 'true'
    prometheus.io/module: http_4xx_ssl
spec:
  tls:
...
```

Right now ingress doesn't seem to be implemented yet at all.

**Comment by matthiasr** [comment]
A Ingress object does not carry any information on how to actually reach
the hostnames it declares, especially since there are many ways to
implement and run an ingress controller.

How would you resolve the ingress you posted to a set of IP/port pairs?

/MR

**Comment by bechtoldt** [comment]
hmm, are you sure? does prometheus need to know how the hostnames/etc. are implemented? If this information isn't available via API yet, why not provide that via (ingress) annotations?


The following example is valid and contains the data you mentioned:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: basic-auth
    ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - prometheus.main.test.example.com
      secretName: cluster-cert-tls
  rules:
    - host: prometheus.main.test.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: prometheus
            servicePort: 9090
```

**Comment by brancz** [comment]
As you already mentioned this specifically requires the blackbox exporter as well, which makes me feel like a higher level abstraction needs to come into play here. FWIW we have plans of integrating blackbox exporter support into the [Prometheus Operator](https://github.com/coreos/prometheus-operator) for exactly this reason.

**Comment by matthiasr** [comment]
Prometheus tries to be more specific than "this hostname, just pick any IP". You can still do it (just directly configure it as an endpoint).

However, as @brancz says this is stringing quite a lot of things together. Even if Prometheus were to ingest the ingress host names as a target, it _also_ needs to know how you set up the blackbox exporter and a way to pass the module on to the exporter, so this spans many more layers than "just" adding a service discovery. It would also need to be dangerously complex so it works for everyone.

What you want to achieve is already possible with a little scripting and tying things together:

1. use kubectl to get all ingresses, process, write a target list for `file_sd`
2. configure a job to read from that, relabel to bend the scrape through your blackbox exporter, wherever it runs
3. there is no 3.

Building this into Prometheus for _all_ cases would need so many knobs that configuring it would be just as complex as integrating this way for _your_ case, so I would rather not go down this route.

**Comment by bechtoldt** [comment]
> You can still do it (just directly configure it as an endpoint).

Would you be so kind to give me a code example?

> Even if Prometheus were to ingest the ingress host names as a target, it also needs to know how you set up the blackbox exporter

what? what do you mean with "set up"?

> and a way to pass the module on to the exporter,

relabelling, using an annotation as source label? 

> It would also need to be dangerously complex so it works for everyone.

I'd totally agree if you were right. For now I don't see that complexity. I might be overlooking something.

> What you want to achieve is already possible with a little scripting and tying things together:

Actually I am looking for autodiscovery instead of static target configuration :)

**Comment by matthiasr** [comment]
> Would you be so kind to give me a code example?

You can use a [static config](https://prometheus.io/docs/operating/configuration/#<static_config>) or a [file sd config](https://prometheus.io/docs/operating/configuration/#<file_sd_config>) where the `target` in the file is just the domain in question.

> what? what do you mean with "set up"?

Where is blackbox exporter running? what port is it on? which modules are configured?



Actually, going back, maybe I misread what you want. If the ingress discovery were to emit one target per rule, with appropriate meta-labels, you could then do all the relabelling on top. Nevertheless, in the absence of a built-in discovery you can run a little sidecar that queries the Kubernetes API (or calls out to kubectl) and emits these targets-per-rule. This could also help flesh out the interface (label names and such) and help come up with a good configuration example.

**Comment by discordianfish** [comment]
I really like the idea to expose the ingress. There wouldn't be much to set up, that could be done with relabling like it is for other 'roles'. This can both be used for configuring any kind of exporter that take URLs as parameters, not only the blackbox-exporter. You might even just want to use that to access something behind an internal LB for some weird enterprisy reasons.
I'm happy to provide a full example how configuration and relabling would look like if you're open to discuss that.

**Comment by grobie** [comment]
Sure, as long as describe the use case for ingress discovery clearly in the
docs, I don't see a good argument against such a contribution.

**Comment by matthiasr** [comment]
SGTM, I retract my objections.

**Comment by discordianfish** [comment]
## User case
- I want to monitor my ingress via a blackbox-exporter
- I want to access a exporter via TLS verifying public chain (hench need to
  connect to FQDN)
- I want to access a exporter which only can be reached via an ingress

## Implementation
- Add role = ingress to kubernetes SD
- SD returns ingress host in address label
- as well as additional labels:
  - ingress\_name
  - ingress\_schema
  - ingress\_host
  - ingress\_path
- Since a ingress can contain multiple hosts, the SD may return multiple targets 
  for a single ingress

## Config example
```
scrape_configs:
  - job_name: 'kubernetes-ingresses'

    metrics_path: /probe
    params:
      module: [http_2xx]

    kubernetes_sd_configs:
      - role: ingress

    relabel_configs:
      - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
        replacement: ${1}://${2}/${3}
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_ingress_name]
        target_label: kubernetes_name
```
