### ISSUE TITLE
Prometheus metrics path with probe not working with grafana

### ISSUE THREAD

**Issue by iloayuil** [prometheus/prometheus#3075]
It might be that I'm doing it wrong, but I want to add the probe path as a metrics path in the Prometheus configuration, something like:
```
   - job_name: 'kubernetes-service-endpoints'
      scheme: http

      kubernetes_sd_configs:
        - role: endpoints
          api_server: "http://10.132.7.201:8081"

      relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_service_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
```
but grafana service endpoints report error:"**text format parsing error in line 1: invalid metric name**", you can see the full information from the graph below.
![11](https://user-images.githubusercontent.com/4462994/29300321-54e7c3a2-81a7-11e7-93e9-54bd02ef36ee.png)

I have jumped the authentication of grafana, So this problem has nothing to do with authorization. 

So, where can I see the metics file of grafana?
