### ISSUE TITLE
HTTP API to add job/target into configuration

### ISSUE THREAD

**Issue by jindov** [prometheus/prometheus#3088]
This is my scenario:

I have a web service cluster (scale in/out by demand) so I want to add instances to prometheus configuration dynamically. The solution I firstly think is a trigger, I an instance add to cluster, it will call a http api of prometheus to add a itself to job and target configuration.
example:
My exist config:
```
- job_name: 'cadvisor'
    scrape_interval: 6s
    static_configs:
      - targets: ['data01:8000','data02:8000']
```
then I scale out my cluster and want to add new instances to `targets`: data03, data04...

I find in document page but there's nothing information about this. I think this should be a good feature.
PS:  I want monitor cadvisor metrics
Thanks
