### ISSUE TITLE
selective metric drop with relabel config

### ISSUE THREAD

**Issue by lastsky** [prometheus/prometheus#3092]
node_systemd_unit_state is [expensive_metric](https://github.com/prometheus/prometheus/blob/master/config/testdata/conf.good.yml#L108) so I spent about 4h for googling and testing different configs and trying to create rule:

keep:
```
node_systemd_unit_state{name="nginx.service",state="active"} 1
node_systemd_unit_state{name="sshd.service",state="active"} 1
```

drop all others:

```
<...>
node_systemd_unit_state{name="nginx.service",state="deactivating"} 0
node_systemd_unit_state{name="nginx.service",state="failed"} 0
node_systemd_unit_state{name="nginx.service",state="inactive"} 0
node_systemd_unit_state{name="systemd-logind.service",state="active"} 1
node_systemd_unit_state{name="systemd-logind.service",state="deactivating"} 0
node_systemd_unit_state{name="systemd-logind.service",state="failed"} 0
node_systemd_unit_state{name="systemd-logind.service",state="inactive"} 0
<...>
```

* Prometheus version: 

`version 1.7.1`

* Prometheus configuration file:

```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    file_sd_configs:
        - files:
            - '/etc/prometheus/file_sd_configs/*.yml'

rule_files:
    - '/etc/prometheus/rules/*.conf'
```

not working strings:

```
- metric_relabel_config:
    - source_labels: [__name__, name, state]
      regex: node_systemd_unit_state;nginx.service;active
      relabel_action: keep

    - source_labels: [__name__, name, state]
      regex: node_systemd_unit_state;sshd.service;active
      relabel_action: keep

   - source_labels: [__name__]
     regex: node_systemd_unit_state
     relabel_action: drop
```
target sources for selective label drop:

```
# cat /etc/prometheus/file_sd_configs/hardware.yml 
- targets:
    - "10.137.161.82:9100"
    - "10.137.161.83:9100"
    - "10.137.161.84:9100"
    - "10.137.161.85:9100"
  labels:
    job: node
```

I'd tested about ~20 examples, and after `time curl -XDELETE -g 'http://localhost:9090/api/v1/series?match[]=node_systemd_unit_state'` I see them in prometheus again. If prometheus starts, of course.

Would you like to explain where I should insert metric_relabel_config? to prometheus.yml or to static configs? Please add working example to docs.

Tired. Thanks.
