### ISSUE TITLE
Get the clusterIP from service via kubernetes_sd meta label

### ISSUE THREAD

**Issue by talset** [prometheus/prometheus#3110]
**Environment**

Kubernetes v1.5.4+coreos.0"

* Prometheus version:

quay.io/prometheus/prometheus:v2.0.0-beta.0

* Prometheus configuration file:
```
    - job_name: 'kube-state-metrics'
      kubernetes_sd_configs:
      - role: service

      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_label_k8s_app]
        action: keep
        regex: prometheus;kube-state-metrics
```

**Question**

When I use `role: service` it use by default the  `svc.Name+"."+svc.Namespace+".svc"` (https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/service.go#L153) as address. Since we are not using skydns in our k8s cluster we would like to use the service ip / ClusterIP directly.

As the same way you get the port from spec (https://github.com/prometheus/prometheus/blob/master/discovery/kubernetes/service.go#L152), is it possible to get the clusterIP (when it is present) and export it as metalabel `__meta_kubernetes_service_clusterIP` to prometheus ?
