### ISSUE TITLE
Support regex-less relabling

### ISSUE THREAD

**Issue by discordianfish** [prometheus/prometheus#3117]
Hi,

not feeling too strongly about it but definitely a nice to have which arguably would be less complex to manage as a a user than the regex we have right now. It think I never had an actual need for an regex.

We should support `action: replace` without a regex, which would simply make all labels available in the replacement. This could be look like this:

```
- action: replace
  target_label: new_label
  replacement: "foo/${__meta_foo}/${__address__}/bla/${__meta_bar}"
```

Alternatively we could keep source_labels and just map them 1:1 to position args in replacement:

```
- action: replace
  source_labels: [ __meta_foo, __address__, __meta_bar ]
  target_label: new_label
  replacement: "foo/${1}/${2}/bla/${3}"
```

Might need to be a new action though since the current behavior is different.
Feel free to close this if it seems out of scope but I believe it makes one of the most mind bending parts of the prometheus config much easier to understand.

**Comment by brian-brazil** [comment]
The question I would ask is what does this allow that relabelling already doesn't?

I've seen very few cases where such syntactic sugar would help, and having more than one way to do things is rarely a win for users. Particularly for something like relabelling.

**Comment by grobie** [comment]
Heh, funny, we just ran into a limitation of relabel rules (as mentioned in #2545) which could be solved by interpolation of labels in other fields. This would make it possible to configure k8s discovery only with relabel rules.

```yaml
- action: keep
  source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_ports] # comma separated list of ports for example
  regex: "(^|,){{ __meta_kubernetes_pod_container_port_number }}($|,)"
- action: replace
  source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
  target_label: __address__
  regex: '(.+?)(?::\d+)?;(\d+)'
  replacement: $1:$2
```

The second rule could then also be rewritten as follows, close to @discordianfish suggestion:

```yaml
- action: replace
  target_label: __addess__
  replacement: {{ __meta_kubernetes_pod_ip }}:{{ __meta_kubernetes_pod_container_port_number }}
```
