### ISSUE TITLE
[BUG]: Prometheus does not write tags into influxdb if retention policy is set to default

### ISSUE THREAD

**Issue by varaga** [prometheus/prometheus#3131]
Hi There,

     I'm using Prometheus for scraping targets from a remote java process. This remote java process runs a prometheus agent (JMX Exporter).

         All metrics scrapped and are stored in influxdb. 
1. **The problem is that these metrics are stored directly as 'measurements' in the influx db store and the fields of the metrics or stored as field key/values in the influxdb**
2. **I'm sensing that the problem is due to retention policy set as 'default' through prometheus config file.**
Prometheus version: 1.2.3
InfluxDb version: 1.2.x
    
     I don't see tags for these metrics. Is there a mapping between the labels/configuration versus the data model in influxdb ? How to set this ?

     Request you to throw some light on this. Please be noted that I raised this as a question in the users community and there was no response.

      The influxdb integration is through the following configuration:
```
        /prometheus/prometheus -config.file /prometheus/{{config}}.yaml
         -storage.remote.influxdb-url http://influxdb-host:8086
         -storage.remote.influxdb.username test
        -storage.remote.influxdb.database test
        -storage.remote.influxdb.retention-policy default
        -storage.local.engine none
```
     and the prometheus config file as below:
 ```
scrape_configs:
 - job_name: 'runner'
 serverset_sd_configs:
 - servers:
 - 'z.internal:2181'
 paths:
 - '/discovery/announcer/runner'
 relabel_configs:
 - source_labels:
 - '__meta_serverset_endpoint_host_prometheusjmxexporter'
 - '__meta_serverset_endpoint_port_prometheusjmxexporter'
 action: replace
 target_label: __address__
 regex: (..*);(..*)
 replacement: $1:$2
 - source_labels:
 - '__meta_serverset_path'
 regex: '/.*/(.*[^/])/(.*[^/])/(.*[^/])/(.*[^/])'
 target_label: serverset
 replacement: $1/$2/$3
 - source_labels:
 - 'serverset'
 regex: '^(.*[^/])/(.*[^/])/(.*[^/])$'
 target_label: role
 replacement: $1
 - source_labels:
 - 'serverset'
 regex: '^(.*[^/])/(.*[^/])/(.*[^/])$'
 target_label: environ
 replacement: $2
 - source_labels:
 - 'serverset'
 regex: '^(.*[^/])/(.*[^/])/(.*[^/])$'
 target_label: application
 replacement: $3
 - source_labels:
 - '__meta_serverset_shard'
 target_label: shard
```
