### ISSUE TITLE
Trying to reload prometheus with the API return 403 Forbidden

### ISSUE THREAD

**Issue by JrCs** [prometheus/prometheus#3157]
**What did you do?**
Reloading prometheus configuration with the API using a command like:
```bash
curl -X POST http://prometheus.service.cs:9090/-/reload
```

**What did you expect to see?**
Expecting configuration reload

**What did you see instead? Under which circumstances?**
I receive a 403 Forbidden

**Environment**
Prometheus container

* System information:
```
Linux 4.12.10-coreos x86_64
```

* Prometheus version:
```
prometheus, version 2.0.0-beta.2 (branch: HEAD, revision: a52f082939a566d5269671e98be06fc6bdf61d09)
  build user:       root@41a0740ea598
  build date:       20170818-08:16:50
  go version:       go1.8.3
```

* Prometheus configuration file:
```
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'prometheus-cer69'

rule_files:
  # - '/config/alert.rules'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  # Prometheus himself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
```
