### ISSUE TITLE
Alerts are not recovered,but endsAt field shows a valid time.

### ISSUE THREAD

**Issue by empo007** [prometheus/prometheus#3231]
**What did you do?**

**What did you expect to see?**
Alert rule is defined as following:
```
ALERT UNDO_DATAFILE_AUTOEXTENSIBLE
  IF ora_tbs_datafile_autoextensible{contents="UNDO"} == 1 or ora_tbs_tempfile_autoextensible == 1
  LABELS {severity="low"}
  ANNOTATIONS {description="UNDO tablespace datafile {{$labels.file_name}} is autoextensible", summary="UNDO DATAFILE AUTOEXTENSIBLE"}
```
the alert should never ends. all time series are here:
```
{
    "metric": {
        "__name__": "ora_tbs_tempfile_autoextensible",
        "architectureId": "5973850a9932f56315ff080d",
        "architectureName": "datalab00023",
        "cdbClusterId": "11888",
        "cdbName": "cdbbi",
        "file_id": "89",
        "file_name": "+DATA01/CDBBI/54EBF0F97B4A0A06E0534146020A4BDD/TEMPFILE/temp.3414.950058183",
        "hostname": "dggbidlab02-or",
        "instance": "10.2.70.65:11554",
        "ipAddress": "10.2.70.65",
        "job": "ora-space-from-consul",
        "monType": "pdb",
        "pdbId": "12031857",
        "pdbName": "datalab00023",
        "promName": "P2",
        "sid": "cdbbi2",
        "tablespace_name": "TEMP",
        "tenantName": "huawei",
        "userId": "qWX490206"
    },
    "values": [
        [
            1506688215.781,
            "1"
        ],
        [
            1506688230.781,
            "1"
        ],
        [
            1506688245.781,
            "1"
        ],
        [
            1506688260.781,
            "1"
        ],
        [
            1506688275.781,
            "1"
        ],
        [
            1506688290.781,
            "1"
        ],
        [
            1506688305.781,
            "1"
        ],
        [
            1506688320.781,
            "1"
        ],
        [
            1506688335.781,
            "1"
        ],
        [
            1506688350.781,
            "1"
        ],
        [
            1506688365.781,
            "1"
        ],
        [
            1506688380.781,
            "1"
        ],
        [
            1506688395.781,
            "1"
        ],
        [
            1506688410.781,
            "1"
        ],
        [
            1506688425.781,
            "1"
        ],
        [
            1506688440.781,
            "1"
        ],
        [
            1506688455.781,
            "1"
        ],
        [
            1506688470.781,
            "1"
        ],
        [
            1506688485.781,
            "1"
        ],
        [
            1506688500.781,
            "1"
        ],
        [
            1506709815.781,
            "1"
        ],
        [
            1506709830.781,
            "1"
        ],
        [
            1506709845.781,
            "1"
        ],
        [
            1506709860.781,
            "1"
        ],
        [
            1506709875.781,
            "1"
        ],
        [
            1506709890.781,
            "1"
        ],
        [
            1506709905.781,
            "1"
        ],
        [
            1506709920.781,
            "1"
        ],
        [
            1506709935.781,
            "1"
        ],
        [
            1506709950.781,
            "1"
        ],
        [
            1506709965.781,
            "1"
        ],
        [
            1506709980.781,
            "1"
        ],
        [
            1506709995.781,
            "1"
        ],
        [
            1506710010.781,
            "1"
        ],
        [
            1506710025.781,
            "1"
        ],
        [
            1506710040.781,
            "1"
        ],
        [
            1506710055.781,
            "1"
        ],
        [
            1506710070.781,
            "1"
        ],
        [
            1506710085.781,
            "1"
        ],
        [
            1506710100.781,
            "1"
        ],
        [
            1506731415.781,
            "1"
        ],
        [
            1506731430.781,
            "1"
        ],
        [
            1506731445.781,
            "1"
        ],
        [
            1506731460.781,
            "1"
        ],
        [
            1506731475.781,
            "1"
        ],
        [
            1506731490.781,
            "1"
        ],
        [
            1506731505.781,
            "1"
        ],
        [
            1506731520.781,
            "1"
        ],
        [
            1506731535.781,
            "1"
        ],
        [
            1506731550.781,
            "1"
        ],
        [
            1506731565.781,
            "1"
        ],
        [
            1506731580.781,
            "1"
        ],
        [
            1506731595.781,
            "1"
        ],
        [
            1506731610.781,
            "1"
        ],
        [
            1506731625.781,
            "1"
        ],
        [
            1506731640.781,
            "1"
        ],
        [
            1506731655.781,
            "1"
        ],
        [
            1506731670.781,
            "1"
        ],
        [
            1506731685.781,
            "1"
        ],
        [
            1506731700.781,
            "1"
        ]
    ]
}
```
**What did you see instead? Under which circumstances?**
```
{
    "labels": {
        "alertname": "UNDO_DATAFILE_AUTOEXTENSIBLE",
        "architectureId": "5973850a9932f56315ff080d",
        "architectureName": "datalab00023",
        "cdbClusterId": "11888",
        "cdbName": "cdbbi",
        "file_id": "89",
        "file_name": "+DATA01/CDBBI/54EBF0F97B4A0A06E0534146020A4BDD/TEMPFILE/temp.3414.950058183",
        "hostname": "dggbidlab02-or",
        "instance": "10.2.70.65:11554",
        "ipAddress": "10.2.70.65",
        "job": "ora-space-from-consul",
        "monType": "pdb",
        "monitor": "P2",
        "pdbId": "12031857",
        "pdbName": "datalab00023",
        "promName": "P2",
        "severity": "low",
        "sid": "cdbbi2",
        "tablespace_name": "TEMP",
        "tenantName": "huawei",
        "userId": "qWX490206"
    },
    "annotations": {
        "description": "UNDO tablespace datafile +DATA01/CDBBI/54EBF0F97B4A0A06E0534146020A4BDD/TEMPFILE/temp.3414.950058183 is autoextensible",
        "summary": "UNDO DATAFILE AUTOEXTENSIBLE"
    },
    "startsAt": "2017-09-29T20:30:42.044+08:00",
    **"endsAt": "2017-09-29T20:36:42.047+08:00"**,
    "generatorURL": "http://dggge2mwc8008:8999/graph?g0.expr=ora_tbs_datafile_autoextensible%7Bcontents%3D%22UNDO%22%7D+%3D%3D+1+or+ora_tbs_tempfile_autoextensible+%3D%3D+1\\u0026g0.tab=0"

it shows that alert ends at 2017-09-29T20:36:42.047+08:00 which is not true
```
**Environment**

* System information:

Linux 2.6.32-573.el6.x86_64 x86_64

* Prometheus version:

prometheus, version 1.6.3 (branch: master, revision: c580b60c67f2c5f6b638c3322161bcdf6d68d7fc)
  build user:       root@a6410e65f5c7
  build date:       20170522-09:15:06
  go version:       go1.8.1

* Alertmanager version:

	insert output of `alertmanager -version` here (if relevant to the issue)

* Prometheus configuration file:
```
global:
  evaluation_interval: 2m
  external_labels: {monitor: P2}
  scrape_interval: 180s
  scrape_timeout: 60s
remote_write:
- url: http://10.3.154.94:9990/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;MySQL
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9990/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;OS
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9993/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;redis
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9992/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;mongodb
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9991/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;oraCrs
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9991/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;cdb
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9991/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;pdb
    source_labels: [remoteWrite, monType]
- url: http://10.3.154.94:9991/PromReceiver
  write_relabel_configs:
  - action: keep
    regex: tokafka;11gdb
    source_labels: [remoteWrite, monType]
rule_files: [alert_rules/*.rules]
scrape_configs:
- job_name: P2
  metric_relabel_configs:
  - action: drop
    regex: go_.*
    source_labels: [__name__]
  scrape_interval: 180s
  scrape_timeout: 60s
  static_configs:
  - labels: {hostname: dggge2mwc8008}
    targets: ['10.3.154.140:8999']
- consul_sd_configs:
  - datacenter: zkzone-prod1
    server: 10.3.154.140:8500
    services: ['P2-MySQL-6000-1000', 'P2-mongodb-6000-1000', 'P2-redis-6000-1000','P2-oraCrs-6000-1000', 'P2-cdb-6000-1000', 'P2-pdb-6000-1000', 'P2-11gdb-6000-1000',
 'P2-MySQL-6000-2000', 'P2-mongodb-6000-2000', 'P2-redis-6000-2000','P2-oraCrs-6000-2000', 'P2-cdb-6000-2000', 'P2-pdb-6000-2000', 'P2-11gdb-6000-2000',
 'P2-MySQL-6000-3000', 'P2-mongodb-6000-3000', 'P2-redis-6000-3000','P2-oraCrs-6000-3000', 'P2-cdb-6000-3000', 'P2-pdb-6000-3000', 'P2-11gdb-6000-3000',
 'P2-MySQL-6000-6004', 'P2-mongodb-6000-6004', 'P2-redis-6000-6004','P2-oraCrs-6000-6004', 'P2-cdb-6000-6004', 'P2-pdb-6000-6004', 'P2-11gdb-6000-6004']
  job_name: overwritten-from-consul
  metric_relabel_configs:
  - regex: redis_up|redis_replication_backlog_bytes|redis_cluster_messages_received_total|redis_cluster_messages_sent_total|redis_cluster_size|redis_connections_received_total|redis_evicted_keys_total|redis_expired_keys_total|redis_memory_max_bytes|redis_memory_used_bytes|redis_net_input_bytes_total|redis_net_output_bytes_total|redis_keyspace_hits_total|redis_keyspace_misses_total
    replacement: tokafka
    source_labels: [__name__]
    target_label: remoteWrite
  - regex: mysql_up|mysql_global_status_uptime|mysql_global_status_threads_connected|mysql_global_status_threads_running|mysql_slave_status_slave_io_running|mysql_slave_status_slave_sql_running|mysql_slave_status_seconds_behind_master|mysql_slave_status_last_errno|mysql_global_variables_read_only|mysql_global_variables_gtid_mode|node_filesystem_size|node_filesystem_avail
    replacement: tokafka
    source_labels: [__name__]
    target_label: remoteWrite
  - regex: mongodb_mongod_replset_member_health|mongodb_mongod_replset_member_state|mongodb_mongod_replset_member_optime_date
    replacement: tokafka
    source_labels: [__name__]
    target_label: remoteWrite
  - action: drop
    regex: go_.*
    source_labels: [__name__]
  - action: drop
    regex: mysql_perf_schema.*
    source_labels: [__name__]
  relabel_configs:
  - action: replace
    regex: (.*);(.*)
    replacement: ${1}:${2}
    separator: ;
    source_labels: [__meta_consul_service_address, __meta_consul_service_port]
    target_label: __address__
  - action: replace
    regex: (?i).*,hostname=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: hostname
  - action: replace
    regex: (?i).*,ipAddress=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: ipAddress
  - action: replace
    regex: (?i).*,userId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: userId
  - action: replace
    regex: (?i).*,dbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbName
  - action: replace
    regex: (?i).*,instanceName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceName
  - action: replace
    regex: (?i).*,monType=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: monType
  - action: replace
    regex: (?i).*,promName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: promName
  - action: replace
    regex: (?i).*,tenantName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: tenantName
  - action: replace
    regex: (?i).*,eMail=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: eMail
  - action: replace
    regex: (?i).*,instanceId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceId
  - action: replace
    regex: (?i).*,poolId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: poolId
  - action: replace
    regex: (?i).*,sid=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: sid
  - action: replace
    regex: (?i).*,cdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbName
  - action: replace
    regex: (?i).*,cdbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbClusterId
  - action: replace
    regex: (?i).*,dbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbClusterId
  - action: replace
    regex: (?i).*,architectureId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureId
  - action: replace
    regex: (?i).*,architectureName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureName
  - action: replace
    regex: (?i).*,pdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbName
  - action: replace
    regex: (?i).*,pdbId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbId
  - action: replace
    regex: (?i).*,clusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: clusterId
  - action: replace
    regex: (?i).*,targetPort=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: targetPort
  - action: replace
    regex: (?i).*,serviceName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: serviceName
  scrape_interval: 180s
  scrape_timeout: 60s
- consul_sd_configs:
  - datacenter: zkzone-prod1
    server: 10.3.154.140:8500
    services: ['P2-cdbsp-6000-1000', 'P2-pdbsp-6000-1000', 'P2-11gdbsp-6000-1000', 'P2-cdbsp-6000-2000', 'P2-pdbsp-6000-2000', 'P2-11gdbsp-6000-2000','P2-cdbsp-6000-3000', 'P2-pdbsp-6000-3000', 'P2-11gdbsp-6000-3000', 'P2-cdbsp-6000-6004', 'P2-pdbsp-6000-6004', 'P2-11gdbsp-6000-6004']
  job_name: ora-space-from-consul
  metric_relabel_configs:
  - action: drop
    regex: go_.*
    source_labels: [__name__]
  relabel_configs:
  - action: replace
    regex: (.*);(.*)
    replacement: ${1}:${2}
    separator: ;
    source_labels: [__meta_consul_service_address, __meta_consul_service_port]
    target_label: __address__
  - action: replace
    regex: (?i).*,hostname=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: hostname
  - action: replace
    regex: (?i).*,ipAddress=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: ipAddress
  - action: replace
    regex: (?i).*,userId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: userId
  - action: replace
    regex: (?i).*,dbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbName
  - action: replace
    regex: (?i).*,instanceName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceName
  - action: replace
    regex: (?i).*,monType=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: monType
  - action: replace
    regex: (?i).*,promName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: promName
  - action: replace
    regex: (?i).*,tenantName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: tenantName
  - action: replace
    regex: (?i).*,eMail=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: eMail
  - action: replace
    regex: (?i).*,instanceId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceId
  - action: replace
    regex: (?i).*,sid=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: sid
  - action: replace
    regex: (?i).*,cdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbName
  - action: replace
    regex: (?i).*,cdbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbClusterId
  - action: replace
    regex: (?i).*,dbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbClusterId
  - action: replace
    regex: (?i).*,architectureId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureId
  - action: replace
    regex: (?i).*,architectureName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureName
  - action: replace
    regex: (?i).*,pdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbName
  - action: replace
    regex: (?i).*,pdbId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbId
  - action: replace
    regex: (?i).*,clusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: clusterId
  scrape_interval: 360m
  scrape_timeout: 60s
- consul_sd_configs:
  - datacenter: zkzone-prod1
    server: 10.3.154.140:8500
    services: ['P2-OS-6000-1000','P2-OS-6000-2000','P2-OS-6000-3000','P2-OS-6000-6004']
  job_name: OS-from-consul
  metric_relabel_configs:
  - action: drop
    regex: go_.*
    source_labels: [__name__]
  relabel_configs:
  - action: replace
    regex: (.*);(.*)
    replacement: ${1}:${2}
    separator: ;
    source_labels: [__meta_consul_service_address, __meta_consul_service_port]
    target_label: __address__
  - action: replace
    regex: (?i).*,hostname=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: hostname
  - action: replace
    regex: (?i).*,ipAddress=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: ipAddress
  - action: replace
    regex: (?i).*,userId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: userId
  - action: replace
    regex: (?i).*,dbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbName
  - action: replace
    regex: (?i).*,instanceName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceName
  - action: replace
    regex: (?i).*,monType=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: monType
  - action: replace
    regex: (?i).*,promName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: promName
  - action: replace
    regex: (?i).*,tenantName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: tenantName
  - action: replace
    regex: (?i).*,eMail=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: eMail
  - action: replace
    regex: (?i).*,instanceId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: instanceId
  - action: replace
    regex: (?i).*,sid=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: sid
  - action: replace
    regex: (?i).*,cdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbName
  - action: replace
    regex: (?i).*,cdbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: cdbClusterId
  - action: replace
    regex: (?i).*,dbClusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: dbClusterId
  - action: replace
    regex: (?i).*,architectureId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureId
  - action: replace
    regex: (?i).*,architectureName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: architectureName
  - action: replace
    regex: (?i).*,pdbName=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbName
  - action: replace
    regex: (?i).*,pdbId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: pdbId
  - action: replace
    regex: (?i).*,clusterId=([^,]+),.*
    replacement: ${1}
    source_labels: [__meta_consul_tags]
    target_label: clusterId
  scrape_interval: 20s
  scrape_timeout: 10s

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
