### ISSUE TITLE
Alertmanager relabel config not being honoured

### ISSUE THREAD

**Issue by loverend** [prometheus/prometheus#3239]
**What did you do?**
I have two alertmanagers set in my config, and I am trying to send only certain alerts to each:

```
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
      relabel_configs:
        - action: drop
          source_labels: [secure]
          regex: yes 
    - static_configs:
      - targets:
        - localhost:9095
```

**What did you expect to see?**
I would expect to alerts with the label {secure="yes"} to be dropped for target localhost:9093.

**What did you see instead? Under which circumstances?**
All alerts, including ones with {secure="yes"}, were sent to both alertmanagers.

If I set the relabel config under `alert_relabel_configs` all alerts with {secure="yes"} are dropped, but the docs suggest that I should be able to set different `relabel_configs` for each alertmanager.

Here is the config when dropping {secure="yes"} for both alertmanagers:
```
alerting:
  alert_relabel_configs:
    - action: drop
      source_labels: [secure]
      regex: yes
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
    - static_configs:
      - targets:
        - localhost:9095
```

**Environment**

* System information:

```
$ uname -srm
Linux 4.10.0-35-generic x86_64
```

* Prometheus version:

```
$ ./prometheus -version
prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
  build user:       root@0aa1b7fc430d
  build date:       20170612-11:44:05
  go version:       go1.8.3
```

* Prometheus configuration file:
```
global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
- alerts

scrape_configs:
  - job_name:       'test 1'
    static_configs:
      - targets: ['localhost:8080']
    relabel_configs:
      - replacement: 'device1'
        target_label: instance
  - job_name:       'test 2'
    static_configs:
      - targets: ['localhost:8080']
    relabel_configs:
      - replacement: 'device2'
        target_label: instance

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
      relabel_configs:
        - action: drop
          source_labels: [secure]
          regex: yes
    - static_configs:
      - targets:
        - localhost:9095
```

Alerts file:
```
ALERT test_alert_1
  IF up{instance="device1"} == 0
  LABELS { secure = "yes" }
  ANNOTATIONS {
    description = "{{ $labels.instance }} is currently unreachable",
  }

ALERT test_alert_2
  IF up{instance!="device1"} == 0
  LABELS { secure = "no" }
  ANNOTATIONS {
    description = "{{ $labels.instance }} is currently unreachable",
  }
```
