### ISSUE TITLE
Cant load ingress jobs

### ISSUE THREAD

**Issue by felixPG** [prometheus/prometheus#3254]
**What did you do?**
Put a job for monitoring ingress in kubernetes

**What did you expect to see?**
Monitoring ingress object expected

**What did you see instead? Under which circumstances?**
Prometheus does not find ingress object
```
time="2017-10-06T09:51:42Z" level=info msg="Loading configuration file /etc/config/prometheus.yml" source="main.go:248"
time="2017-10-06T09:51:42Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/etc/config/prometheus.yml): Unknown Kubernetes SD role \"ingress\"" source="main.go:150"
```
**Environment**
K8s 1.7.5

* Prometheus version:
last charts version from stable repository stable/prometheus

* Prometheus configuration file:
```
      # Example scrape config for probing ingresses via the Blackbox Exporter.
      - job_name: 'kubernetes-ingresses'

        metrics_path: /probe
        params:
          module: [http_2xx]

        kubernetes_sd_configs:
          - role: ingress

        relabel_configs:
          - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
            regex: (.+);(.+);(.+)
            replacement: ${1}://${2}${3}
            target_label: __param_target
          - target_label: __address__
            replacement: blackbox-exporter.example.com:9115
          - source_labels: [__param_target]
            target_label: instance
          - action: labelmap
            regex: __meta_kubernetes_ingress_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_ingress_name]
            target_label: kubernetes_name

```
