### ISSUE TITLE
Prometheus not updating service discovery from Consul

### ISSUE THREAD

**Issue by zemek** [prometheus/prometheus#3314]
**What did you do?**
We configured 2 Prometheus servers in HA (running same config) to discover targets using Consul.

**What did you expect to see?**
Both Prometheus servers to scrape all of the targets that are registered in Consul

**What did you see instead? Under which circumstances?**
At first it was fine, but when we had more instances spin up, only one Prometheus server started scraping the new targets. Here is a graph:
<img width="1649" alt="screen shot 2017-10-18 at 2 10 34 pm" src="https://user-images.githubusercontent.com/12466173/31743092-b053f42e-b40e-11e7-81a2-4d128e51d46d.png">
`rate(prometheus_target_interval_length_seconds_count{interval='15s'}[5m])*15`
`prometheus_sd_consul_rpc_duration_seconds{quantile='0.5', call="service"}`

Sending a SIGHUP to the bad Prometheus server ended up resolving the issue. I don't think this would be caused by config since there weren't any changes, and it did initially get the full list of hosts.

**Environment**

* System information:
```
	Linux 4.4.0-97-generic x86_64
```
* Prometheus version:
```
prometheus, version 2.0.0-rc.1 (branch: HEAD, revision: 5ab8834befbd92241a88976c790ace7543edcd59)
  build user:       root@1f56dd8b6f7b
  build date:       20171017-12:34:15
  go version:       go1.9.1
```
* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

rule_files:
  - /etc/prometheus/recording_rules/*.yml
  - /etc/prometheus/alerting_rules/*.yml

scrape_configs:
  - job_name: 'node_exporter'
    consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['node_exporter']
    relabel_configs: &DEFAULT_RELABEL
      - source_labels: [__meta_consul_tags]
        regex: '.*,host=([^,]+),.*'
        replacement: '${1}'
        target_label: 'host'
      - source_labels: [__meta_consul_tags]
        regex: '.*,role=([^,]+),.*'
        replacement: '${1}'
        target_label: 'role'
  - job_name: 'statsd_exporter'
    consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['statsd_exporter']
    relabel_configs: *DEFAULT_RELABEL
  - job_name: 'self'
    consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['prometheus']
    relabel_configs: *DEFAULT_RELABEL
  - job_name: 'alertmanager'
    consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['alertmanager']
    relabel_configs: *DEFAULT_RELABEL

alerting:
  alertmanagers:
    - consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['alertmanager']
```

* Logs:
```
level=info ts=2017-10-17T22:13:21.658938785Z caller=main.go:216 msg="Starting prometheus" version="(version=2.0.0-rc.1, branch=HEAD, revision=5ab8834befbd92241a88976c790ace7543edcd59)"
level=info ts=2017-10-17T22:13:21.658993398Z caller=main.go:217 build_context="(go=go1.9.1, user=root@1f56dd8b6f7b, date=20171017-12:34:15)"
level=info ts=2017-10-17T22:13:21.659010138Z caller=main.go:218 host_details="(Linux 4.4.0-97-generic #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017 x86_64 ip-10-1-30-199 (none))"
level=info ts=2017-10-17T22:13:21.661576149Z caller=main.go:315 msg="Starting TSDB"
level=info ts=2017-10-17T22:13:21.661590711Z caller=targetmanager.go:68 component="target manager" msg="Starting target manager..."
level=info ts=2017-10-17T22:13:21.661548832Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-10-17T22:13:21.850824129Z caller=main.go:327 msg="TSDB started"
level=info ts=2017-10-17T22:13:21.850877412Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config.yml
level=info ts=2017-10-17T22:13:21.852601767Z caller=main.go:371 msg="Server is ready to receive requests."
level=info ts=2017-10-18T20:13:18.182409504Z caller=main.go:394 msg="Loading configuration file" filename=/etc/prometheus/config.yml
```
