### ISSUE TITLE
Can I use prometheus to read another prometheus data?

### ISSUE THREAD

**Issue by songjiayang** [prometheus/prometheus#3348]
I guess `remote_read ` is the key word, So I do a test, there are my configs

prometheus1: (slave node)
```
scrape_configs:
  - job_name: 'prometheus1'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
```

prometheus 2:  (master node)
```
scrape_configs:
  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9091']

remote_read:
  - url: 'http://localhost:9090/api/v1/read'
    remote_timeout: 8s
```

I want prometheus2's query can list prometheus1's  data, but it not.

My question is that `remote_read` is the right way and how to config it?
