### ISSUE TITLE
External labels hide metrics on the remote read endpoint

### ISSUE THREAD

**Issue by kkohtaka** [prometheus/prometheus#3359]
**What did you do?**

I tried the remote read API with the following master and slave configurations.

master (listening localhost:9090):

```yml
global:
  external_labels:
    role: master

remote_read:
- url: http://localhost:9091/api/v1/read

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
```

slave (listening localhost:9091):

```yml
global:
  external_labels:
    role: slave

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9091
```

Then, I ran a PromQL on the master Prometheus.

**What did you expect to see?**

We should get metrics ingested by both the master and the slave.

**What did you see instead? Under which circumstances?**

By running a query such as `up{job="prometheus"}`, I got only metrics ingested by the master.

```
$ curl -s 'http://localhost:9090/api/v1/query?query=up\{job="prometheus"\}' | jq .data.result[].metric
{
  "__name__": "up",
  "instance": "localhost:9090",
  "job": "prometheus"
}
```

**NOTE**: If we stop using the external labels on master Prometheus, the query shows both metrics by the master and the slave.

```yml
global:
  # external_labels:
  #   role: master

remote_read:
- url: http://localhost:9091/api/v1/read

scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
```

```
$ curl -s 'http://localhost:9090/api/v1/query?query=up\{job="prometheus"\}' | jq .data.result[].metric
{
  "__name__": "up",
  "instance": "localhost:9090",
  "job": "prometheus"
}
{
  "__name__": "up",
  "instance": "localhost:9091",
  "job": "prometheus",
  "role": "slave"
}
```

**Environment**

* System information:

    Darwin 16.7.0 x86_64

* Prometheus version:

    prometheus, version 2.0.0-rc.2 (branch: master, revision: 7aa2930ac592f7ac94b7dc76669bf33b217fce4c)
      build user:       kkohtaka@sirius.local
      build date:       20171026-14:49:58
      go version:       go1.8.3

**Comment by kkohtaka** [comment]
Matchers for external labels are always added to a remote read query. Is that a correct behaviour?

https://github.com/prometheus/prometheus/blob/master/storage/remote/read.go#L70

**Comment by brian-brazil** [comment]
This behaviour is correct and intended, as the data in the slave Prometheus does not have a role=master label and thus does not match the query `up`.

For this sort of setup to work your slaves need to have the same external labels as the master, plus an extra label to distinguish the slaves.

**Comment by kkohtaka** [comment]
Thanks, I confirmed that I can fetch both metrics from the master and the slave by using the following configurations.

master:
```
global:
  external_labels:
    cluster: foo
...
```

slave:
```
global:
  external_labels:
    cluster: foo
    slave: 'true'
...
```

```
$ curl -s 'http://localhost:9090/api/v1/query?query=up\{job="prometheus"\}' | jq .data.result[].metric     
{
  "__name__": "up",
  "instance": "localhost:9090",
  "job": "prometheus"
}
{
  "__name__": "up",
  "instance": "localhost:9091",
  "job": "prometheus",
  "slave": "true"
}
```

I understand the current behaviour and design but I don't know if they are the best. Adding the same external labels as the master to the slave seems unnecessarily large requirement because external labels are not only used for remote endpoints but also federations and alertmanagers.
