### ISSUE TITLE
Scraping both file_sd_configs and dns_sd_configs scrapes only dns

### ISSUE THREAD

**Issue by theonlydoo** [prometheus/prometheus#3365]
**What did you do?**

```yaml

- job_name: 'foobar'
  scrape_interval: 30s
  file_sd_configs:
    - files:
      -  /etc/prometheus/config/_p_foobar_s__foobar/_p_foobar_s__foobar.json

- job_name: 'servdisc'
  scrape_interval: 30s
  dns_sd_configs:
    - names:
      - _supporthttp._tcp.barfoo-foobar.tld.

```
**What did you expect to see?**

Scraping on both targets

**What did you see instead? Under which circumstances?**

only scraping on dns_sd_configs

**Environment**

* System information:

	 `Linux 4.9.0-3-amd64 x86_64` / debian stretch

* Prometheus version:

```
$ prometheus --version
prometheus, version 1.8.0 (branch: HEAD, revision: 3569eef8b1bc062bb5df43181b938277818f365b)
  build user:       root@bd4857492255
  build date:       20171006-22:12:46
  go version:       go1.9.1
```

* Prometheus configuration file:

```yaml

scrape_configs:

  - job_name: 'foobar'
    scrape_interval: 30s
    file_sd_configs:
      - files:
        -  /etc/prometheus/config/_p_foobar_s__foobar/_p_foobar_s__foobar.json

  - job_name: 'servdisc'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
        - _supporthttp._tcp.barfoo-foobar.tld.

```

the content of the json is :

```json
[{
    "labels": {
        "env": "prod",
        "group": "foo_bar_service",
        "service_type": "webservice"
    },
    "target": [
        "foo01.tld:7646",
        "foo02.tld:7646",
        "foo03.tld:7646",
        "foo04.tld:7646"
    ]
}]
```
if I completely disable dns_sd_configs it is scraped again

![](https://dooby.fr/y/a4u8tdf)

**Comment by cstyan** [comment]
@theonlydoo I tried this out on `2.0.0` and wasn't able to reproduce the issue you're seeing. Can you try upgrading and confirm/deny that you still see the issue. My DNS setup wasn't entirely working (connection refused to the dns resolved address) but it's finding the target, as you can see below.

Targets:
![2017-12-04-165702_477x357_scrot](https://user-images.githubusercontent.com/3246492/33584485-7cfe8780-d914-11e7-97a2-6846eed464b3.png)

Config:
![2017-12-04-165702_477x357_scrot](https://user-images.githubusercontent.com/3246492/33584482-74b3c46e-d914-11e7-8d8c-fa058649aa2f.png)

**Comment by krasi-georgiev** [comment]
@theonlydoo 
I did a big refactoring of the SD Service discovery if you want to give it a try and report if the bug is still there.

Here is a link to download an executable for Linux 64bit
https://github.com/krasi-georgiev/prometheus/releases/download/v2.0.0-beta.x/prometheus

**Comment by theonlydoo** [comment]
@krasi-georgiev thank's for the link, I've tried it out : 
![](https://dooby.fr/y/rngpafh)
not doing so well
vs the same config on a stable release (2.0, built on 08/11/2017) :
![](https://dooby.fr/y/7uxh6na)

and still no file_sd scraping, for information here is a sanitized configfile :

```yaml
# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s
  scrape_timeout:       15s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'foobar'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['127.0.0.1:9090']


### Infrastructure autoconf ###

scrape_configs:



  - job_name: 'foobarbaz'
    scrape_interval: 30s
    file_sd_configs:
      - files:
        -  /etc/prometheus/config/_p_foobarbaz_s__foobarstats/_p_foobarbaz_s__foobarstats.json


  - job_name: 'servdisc'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
        - _supporthttp._tcp.foobarbaz.sd.
```

as you can see, I've got both dns_sd and file_sd but only dns_sd is handled in both cases, even though promtool fully validates this config

**Comment by krasi-georgiev** [comment]
@theonlydoo is this a copy/paste error you you really have 2 x `scrape_configs:` blocks?
I think this is what is causing your issue.

**Comment by theonlydoo** [comment]
@krasi-georgiev I have 2 scrape configs, but the first one is not read by prom. I've removed it, and still no file_sd_configs enabled

@cstyan I've tried to remove the `.` at the end of my internal tld in the config : still the same.

File permissions are OK, if I disable the dns_sd_config, I do not see any file_sd with this config. This is weird, since I've tried this simple config :


```yaml
scrape_configs:
  - job_name: 'node_exporter'
    scrape_interval: 30s
    file_sd_configs:
      - files:
        -  /etc/prometheus/config/_p_node_exporter_s__cassandra_log/_p_node_exporter_s__cassandra_log.json



  - job_name: 'servdisc'
    scrape_interval: 30s
    dns_sd_configs:
      - names:
        - _supporthttp._tcp.foobar.sd.

```
it starts and validate, but I have no file_sd job

If I move /etc/prometheus/config/_p_node_exporter_s__cassandra_log/_p_node_exporter_s__cassandra_log.json, it doesnt raises an error (so the file is not watched, as I do not see it while I do a `lsof -p $(pidof prometheus)`

and if I append a new file_sd who doesnt exist at all, promtool refuses to validate the configuration and prometheus refuses to start.
