### ISSUE TITLE
Add Dockerfile environment variables to control CMD arguments

### ISSUE THREAD

**Issue by dsvensson** [prometheus/prometheus#3385]
**What did you do?**

Started prometheus under docker-compose.

**What did you expect to see?**

Nothing.

**What did you see instead? Under which circumstances?**

Lots of log INFO's that I want to hide.

**Environment**

prom/prometheus docker container.

* System information:

	docker

* Prometheus version:

	2.0.0-rc2
* Logs:

```
prometheus_1  | level=info ts=2017-10-31T22:19:06.761671514Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0-rc.2, branch=master, revision=3701a827cf5da595bd2366dad6e1b3c979a1009c)"
```

Turns out Prometheus doesn't support adapting command line arguments based on Docker environment variables, which requires copying the whole ENTRYPOINT/CMD from the prom/prometheus Dockerfile:

```
ENTRYPOINT [ "/bin/prometheus" ]
CMD        [ "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles" ]
```

...and pasteing into `docker-compose.yml`, with `--log.level=warn` added:

```
    prometheus:
      image: prom/prometheus:master
      entrypoint:
        - "/bin/prometheus"
        - "--log.level=warn"
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/prometheus"
        - "--web.console.libraries=/usr/share/prometheus/console_libraries"
        - "--web.console.templates=/usr/share/prometheus/consoles"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
```

Ideally this would be possible to either override via Docker environment variables.

Here is how log.level can be overridden for Grafana in `docker-compose.yml`:
```
    grafana:
      image: grafana/grafana
      environment:
        GF_LOG_CONSOLE_LEVEL: warn
      depends_on:
        - prometheus
      links:
        - prometheus
      ports:
        - 3000:3000
```

Maybe something like:
```
    prometheus:
      image: prom/prometheus:master
      environment:
        PROM_LOG_LEVEL: warn
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
```

Which would synthesize a `--log.level=warn` command line argument from a wrapper entrypoint script that traps PROM_ environment variables. This would not require any modifications to Prometheus itself, and would not add any extra way of configuring Prometheus. Just exposing control over the command line to `docker-compose.yml`.
