### ISSUE TITLE
Prometheus 2.0: spurious errors in consul service discovery

### ISSUE THREAD

**Issue by thesamet** [prometheus/prometheus#3413]
**What did you do?**
Start prometheus

**What did you expect to see?**
No errors in the logs

**What did you see instead? Under which circumstances?**
From time to time prometheus would print a log message indicating that it failed fetching service information from consul. There is little impact, since it does seem to be able to connect to it at start time.

**Environment**
Prometheus 2.0.0-rc2 on Linux. Service discovery using consul.

* System information:

        Linux 4.4.0-57-generic x86_64
	
* Prometheus version:
```prometheus, version 2.0.0-rc.2 (branch: HEAD, revision: ce63a5a8557bb33e2030a7756c58fd773736b592)
  build user:       root@a6d2e4a7b8da
  build date:       20171025-18:42:54
  go version:       go1.9.1
```

* Alertmanager version:
Not installed.

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: consul
    consul_sd_configs:
    - server: consul:8500
      services:
      - myservice
    relabel_configs:
    - source_labels: ["__meta_consul_address", "__meta_consul_service_port"]
      separator: ":"
      target_label: __address__
      regex: "(.*):9(.*)"
      replacement: "$1:19$2"
    - source_labels: ["__meta_consul_service"]
      target_label: job
    - source_labels: ["__meta_consul_tags"]
      regex: ".*(prod|stage).*"
      target_label: env
```

* Logs:
```
level=error ts=2017-11-04T19:20:21.399644298Z caller=consul.go:283 component="target manager" discovery=consul msg="Error refreshing service" service=trends err="Get http://consul:8500/v1/catalog/service/trends?index=9598981&wait=30000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
level=error ts=2017-11-04T19:20:21.399854827Z caller=consul.go:186 component="target manager" discovery=consul msg="Error refreshing service list" err="Get http://consul:8500/v1/catalog/services?index=9598981&wait=30000ms: net/http: request canceled (Client.Timeout exceeded while awaiting headers)"
```
