### ISSUE TITLE
2.0.0-rc.3 - unknown fields in alertmanager config: static_config"

### ISSUE THREAD

**Issue by dR3b** [prometheus/prometheus#3428]
I am aware of how to fix this problem, but these are the settings in the "Default" configuration.

**What did you do?**
```
wget https://github.com/prometheus/prometheus/releases/download/v2.0.0-rc.3/prometheus-2.0.0-rc.3.linux-amd64.tar.gz
tar xf prometheus-2.0.0-rc.3.linux-amd64.tar.gz
cd prometheus-2.0.0-rc.3.linux-amd64
./prometheus --config.file="prometheus.yml"
```
**What did you see instead? Under which circumstances?**
```
level=info ts=2017-11-08T06:30:18.281802915Z caller=main.go:215 msg="Starting Prometheus" version="(version=2.0.0-rc.3, branch=HEAD, revision=8a9b32d0eb5be05a8066492e8a75c18b90e2d6ff)"
level=info ts=2017-11-08T06:30:18.281898923Z caller=main.go:216 build_context="(go=go1.9.2, user=root@f25dd60e77b3, date=20171104-20:31:56)"
level=info ts=2017-11-08T06:30:18.281946227Z caller=main.go:217 host_details="(Linux 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 XXX (none))"
level=info ts=2017-11-08T06:30:18.284090913Z caller=web.go:380 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2017-11-08T06:30:18.284091223Z caller=main.go:314 msg="Starting TSDB"
level=info ts=2017-11-08T06:30:18.284124087Z caller=targetmanager.go:69 component="target manager" msg="Starting target manager..."
level=info ts=2017-11-08T06:30:18.29104953Z caller=main.go:326 msg="TSDB started"
level=info ts=2017-11-08T06:30:18.29111071Z caller=main.go:394 msg="Loading configuration file" filename=prometheus.yml
level=error ts=2017-11-08T06:30:18.291462737Z caller=main.go:356 msg="Error loading config" err="couldn't load configuration (--config.file=prometheus.yml): unknown fields in alertmanager config: static_config"

```

**Environment**

* System information:
    Linux 4.13.11-1-ARCH x86_64

* Prometheus version:
    2.0.0-rc.3

* Prometheus configuration file: **Default!**
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_config:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
```
