### ISSUE TITLE
Expensive recording rules cause high memory/malloc use in 2.0.0

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#3450]
**What did you do?**

Have some recording rules that require a large amount of data to evaluate.

**What did you expect to see?**

Moderate heap use/growth.

**What did you see instead? Under which circumstances?**

Large heap use/growth.

**Environment**

This recording rule requires about 12k metrics, which is admittedly expensive, but the heap grows to 10-15GB.

```yaml
groups:
- name: recordings/recording.rules
  rules:
  - record: gitaly:grpc_server_handled_total:error_avg_rate12h
    expr: avg(rate(grpc_server_handled_total{grpc_code!="OK"}[12h])) BY (job, grpc_method,
      environment)
```

* System information:

	insert output of `uname -srm` here

* Prometheus version:

```
prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2
```

See attached pprof [heap.svg.gz](https://github.com/prometheus/prometheus/files/1457998/heap.svg.gz).
