### ISSUE TITLE
`promtool update rules` discards comments

### ISSUE THREAD

**Issue by vthriller** [prometheus/prometheus#3475]
**What did you do?**

`promtool update rules rulefile`

**What did you expect to see?**

Given the following `rulefile`:

```
# Lorem ipsum

ALERT Foo
  # whatever
  IF bar > 0
  or rate(baz [1m]) > 0 # because reasons
  #or quux > 0 # FIXME
  LABELS { severity = "crit" }
```

I expected to see the output silimlar to this:

```yaml
# Lorem ipsum
groups:
- # whatever
  name: test
  rules:
  - alert: Foo
    expr: |
      bar > 0
      or rate(baz[1m]) > 0 # because reasons
      #or quux > 0 # FIXME
    labels:
      severity: crit
```

(or `#or quux` to be on the same level as `labels:` or whatever)

**What did you see instead? Under which circumstances?**

```yaml
groups:
- name: test
  rules:
  - alert: Foo
    expr: bar > 0 or rate(baz[1m]) > 0
    labels:
      severity: crit
```

**Environment**

* System information: (irrelevant)

* Prometheus version:

```
promtool, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2
```

* Alertmanager version: (irrelevant)

* Prometheus configuration file: (irrelevant)

* Alertmanager configuration file: (irrelevant)

* Logs: (none)
