### ISSUE TITLE
[Feature request] Function or API to get metric meta information

### ISSUE THREAD

**Issue by jiming** [prometheus/prometheus#3481]
For example the metric in https://prometheus.io/docs/prometheus/latest/querying/operators/

When execute the api or function, it can return
```yaml

http_errors:
  type: Counter
  labels:
    method:
      - GET
      - POST
    code:
      - 200
      - 300
      - 400
      - 404
      - 500

```

And go further, when execute the api of function with label name, it only return the exists values of label. For example, I execute the api with parameters `http_errors` and `method`, it returns

```yaml
GET
POST
```
