### ISSUE TITLE
operation was canceled during DNS lookup with remote_write

### ISSUE THREAD

**Issue by errordeveloper** [prometheus/prometheus#3510]
**What did you do?**

With Prometheus v2.0.0 on Kubernetes I've set `global: { scrape_inteval: 5s }` and enabled `remote_write` and `remote_read`, with `scrape_confgs` previosly used with v1.7.1.

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information: GKE

* Prometheus version: `prometheus/prom:v2.0.0`

* Prometheus configuration file:

```
        global:
          scrape_interval: 5s
        remote_write:
          - url: 'https://cloud.weave.works/api/prom/push'
            basic_auth:
              password: <secret>
        remote_read:
          - url: 'https://cloud.weave.works/api/prom/read'
            basic_auth:
              password: <secret>
        scrape_configs: <ommited>
```

* Logs:

I see the following line repeated very frequently.

```
evel=warn ts=2017-11-24T12:41:28.49545111Z caller=queue_manager.go:485 component=remote msg="Error sending samples to remote storage" count=100 err="Post https://cloud.weave.works/api/prom/push: dial tcp: lookup cloud.weave.works on 10.59.240.10:53: dial udp 10.59.240.10:53: operation was canceled"
```
