### ISSUE TITLE
Prometheus UI doesn't show metrics read from remote storage in the drop down

### ISSUE THREAD

**Issue by imransm** [prometheus/prometheus#3560]
**What did you do?**
Set up pg_prometheus, pg_prometheus_adapter with prometheus. Configured for remote_read and remote_write config.yml
Followed instructions from : https://github.com/timescale/prometheus-postgresql-adapter
**What did you expect to see?**
Expected the remotely read metrics to show up in Prometheus UI. Only scraped metrics show up in the UI. Even in the Grafana integration with prometheus, only scraped metrics show up in auto complete.
**What did you see instead? Under which circumstances?**
Metrics read from remote storage don't show up. However, executed query to fetch metric using query editor. Results show up. The drop down doesn't show this metric at all.
**Environment**
Mac OS X 
* System information:

	Darwin 16.7.0 x86_64

* Prometheus version:

	prometheus, version 2.0.0 (branch: master, revision: 607a6756172618ef199bf63f5413e68587f458da)

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      source: 'codelab-monitor'

remote_write:
  - url: "http://172.17.0.3:9201/write"
    remote_timeout: 60s
remote_read:
  - url: "http://172.17.0.3:9201/read"
    remote_timeout: 60s
    read_recent: false

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'my_job'
    honor_labels: true
    scrape_interval: 60s
    scrape_timeout: 30s
    
    static_configs:
      - targets:
         - 'docker.for.mac.localhost:9091'

```
