### ISSUE TITLE
Floating point issues in expression browser Y-axis labels

### ISSUE THREAD

**Issue by snaix** [prometheus/prometheus#3595]
**What did you do?**
Just show some float number in prometheus
**What did you expect to see?**
a correct scale in Graph
**What did you see instead? Under which circumstances?**
a wrong scale with wrong/duplicated number
**Environment**
Windows 10
* System information:
Microsoft Windows [Version 10.0.16299.98]

* Prometheus version:
2.0
prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:19:19
  go version:       go1.9.2

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'test.com:8500'
        services: ['prom_exporter']

```

the scale in prometheus:
![image](https://user-images.githubusercontent.com/6660768/34107744-49a2b224-e438-11e7-9347-89c0d76d1cbf.png)
the same graph in grafana
![image](https://user-images.githubusercontent.com/6660768/34107748-4cfcdb66-e438-11e7-9cb2-1775554ae59d.png)
