### ISSUE TITLE
Storage slow down within 2h range

### ISSUE THREAD

**Issue by pborzenkov** [prometheus/prometheus#3604]
**What did you do?**
I have a Prometheus instance that's configured to federate a lot of metrics from 2 other instances (~190000 samples each). I know that this isn't a way federation is supposed to be used, but still I want to share the behaviour I observe.

**What did you expect to see?**
scrape_duration_seconds doesn't change considerably with time

**What did you see instead? Under which circumstances?**
I see scrape_duration_seconds increases gradually within 2h window and then drops to the original value (obviously, after new TSDB block is started). See attached screenshot.

![screen shot 2017-12-20 at 14 43 41 1](https://user-images.githubusercontent.com/434254/34205771-d263cff0-e594-11e7-9c1e-94da8d2e563f.png)

**Environment**

* System information:
Linux 4.13.0-17-generic x86_64

* Prometheus version:
prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

```
# vim: set shiftwidth=2 tabstop=2 expandtab:

global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 30s

rule_files:
  - '/etc/prometheus/config/*.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'federate'
    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~"[a-zA-Z].*"}'

    static_configs:
      - targets:
        - '<redacted>'
        - '<redacted>'

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "<redacted>"
```

Is this an expected behaviour? A set of metrics doesn't change with time, so I expected TSDB to perform equally well regardless of the actual file size. If this is an expected behaviour, please just close the issue and sorry for the noise.
