### ISSUE TITLE
send firing and resolved status alert to alertmanager in loop

### ISSUE THREAD

**Issue by yylt** [prometheus/prometheus#3606]
**What did you do?**
i create an scrape job which to collect information from an unreachable node , and prometheus send alerts to alertmanager 

**What did you expect to see?**
prometheus send firing statue alert or nothing to alertmanager always , and will never send resolved status alert to alertmanager.

**What did you see instead? Under which circumstances?**
in fact , what i see is same to this issue
https://github.com/prometheus/alertmanager/issues/952

**Environment**
prometheus  v1.8.2 
alertmanage  v0.11.0

* System information:

	linux- 3.10.0

* Prometheus configuration file:
prometheus -alertmanager.url=http://alertmanager-service:9093 -web.listen-address=:9091 -config.file=/etc/prometheus/prometheus.yaml
```
global:
    scrape_interval: 1m
    scrape_timeout: 55s
    evaluation_interval: 1m
scrape_configs:
- job_name: test
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
     - 1.2.3.4:90
 
```

* Alertmanager configuration file:
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal ['alertname', 'service']

* Logs:
