### ISSUE TITLE
The status of federation target is DOWN

### ISSUE THREAD

**Issue by ahrtr** [prometheus/prometheus#3609]
I setup a prometheus instance successfully,  and I can get all the metrics as expected using the following two links,
http://10.136.4.67:8080/metrics
http://10.136.4.67:8080/federate?match[]={endpoint=%22http-metrics%22}

Afterwards, I setup another prometheus instance, which tried to scrape metrics from the above prometheus instance, the configuration file is as below, 

```
global:
  scrape_interval:     15s 

scrape_configs:
  - job_name: 'federate'
    scrape_interval: 30s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{endpoint="http-metrics"}'

    static_configs:
      - targets:
        - '10.136.4.67:8080'
```

The second prometheus instance was successfully started using the following command, 
`docker run -d --env http_proxy=http://www-proxy.mycompany.com:80 --env https_proxy=http://www-proxy.mycompany.com:80 -p 9090:9090 -v `pwd`/prometheus.yml:/etc/prometheus/prometheus.yml  prom/prometheus:v2.0.0`

I could open the UI of the second prometheus instance, but I did not see any metrics which were available on the target instance, and the status of the target prometheus instance displayed on the targets page (as below) was DOWN.  
`http://<IP_ADDRESS_OF_SECOND_PROMETHEUS>:9090/targets`

I am pretty sure that:
    1. The first prometheus instance is always UP;
    2. The two servers on which the two prometheus instances were deployed are always connectable.

What did I miss? 

Both prometheus instances were deployed on Oracle Linux Server release 7.3.
