### ISSUE TITLE
Configuring Prometheus for multiple Kubernetes Clusters

### ISSUE THREAD

**Issue by NayabZehra** [prometheus/prometheus#3612]
**What did you do?**
I am trying to configure Prometheus for multiple Kubernetes Cluster and running prometheus outside the cluster.
I have used the configurations provided here [https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml](url)

* Prometheus configuration file:

```YAML
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'kubernetes-cadvisor'
    scrape_interval: 5s
    scheme: https
    basic_auth:
      username: xxx
      password: 'xxx'
    tls_config:
      insecure_skip_verify: true
    kubernetes_sd_configs:
    - api_server: &api_servers 'https://cluster01'
      role: node
      basic_auth:
        username: xxx
        password: 'xxx'
      tls_config:
        insecure_skip_verify: true
    - api_server: &api_servers 'https://cluster02'
      role: node
      basic_auth:
        username: xxx
        password: 'xxx'
      tls_config:
        insecure_skip_verify: true
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: cluster01 or cluster02
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
```

**What did you expect to see?**
As you can see that in the relabeling configs i need to provide the api_server address and port but there is no meta label provided for api_server. so i cant provide the api_server address to the __address__ label.

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	Prometheus Host : Linux 4.4.0-104-generic x86_64
        Kubernetes Host : Linux 3.10.0-693.5.2.el7.x86_64 x86_64

* Prometheus version:

	v1.8.0
