### ISSUE TITLE
promtool command for dynamic retention

### ISSUE THREAD

**Issue by gouthamve** [prometheus/prometheus#3628]
This would be a simple tool that hits the right endpoints based on a simple config-file that looks like this:

```yaml
# The frequency at which tombstone cleanup needs to be run.
# This means the /clean_tombstones endpoint is hit every 1h
cleanup_interval: 1h
# The frequency at which the deletes need to be run.
# This means that the /delete_series endpoint is hit every 5mins for the below deletes.
delete_interval: 5m

deletes:
  - queries:
      - {__name__=~"job1_.*"}
      - {job="tempJob"}
    retention: 10h # The retention time of every series that matches the above queries.
```

@brian-brazil Are you ok with including this in promtool?
