### ISSUE TITLE
prometheus docker does crash Exited (1) when insecure_skip_verify is set to true

### ISSUE THREAD

**Issue by arunvsankar** [prometheus/prometheus#3657]
**What did you do?**

I am trying to integrate jenkins with prometheus. I installed a prometheus plugin in jenkins. The jenkins has an invalid certificate. 
![image](https://user-images.githubusercontent.com/30663327/34596189-01cf8d4e-f19b-11e7-9df5-bad11c5337ea.png)

I see the docker image does not start but fails with exit(1) status code.

```
- job_name: 'jenkins'
  metrics_path: '/prometheus'
  scrape_interval: 15s
  scheme: https
  static_configs:
     - targets: ['ci-tools.******.com']
      insecure_skip_verify: true
      tls_config:
          ca_file: /etc/ssl/certs/ca-certificates.crt
```

**What did you expect to see?**
**What did you see instead? Under which circumstances?**
In order to skip the verification, I tried to add  insecure_skip_verify as true in prometheus.yml file and start the docker container on prometheus. 
When i restart the prometheus  docker image, the container does not start but throws an Exited(1) and would not start

9f26831ba90d        prom/prometheus                                         "/bin/prometheus -sto"   10 weeks ago        Exited (1) 4 seconds ago                             prometheus

**Environment**
I use a RHEL

* System information:

Linux 4.4.0-97-generic x86_64

* Prometheus version:

	prom/prometheus                                        latest              03f045a7680f       

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
