### ISSUE TITLE
recording rules omit without clause

### ISSUE THREAD

**Issue by intenseFrog** [prometheus/prometheus#3704]
**What did you do?**

  We defined some recording rules to speed up our dashboard 

**What did you expect to see?**

Rules should be reflected as defined 
```
groups:
  - name: container
    rules:
    - record: container:mem:sum
      expr: container_memory_usage_bytes
  - name: pod
    rules:
    - record: pod:mem:sum
      expr: sum without()(container:mem:sum{pod_name=~".+"})
```

**What did you see instead? Under which circumstances?**

  without clause in the second rule was omitted
![in fact](https://user-images.githubusercontent.com/2656704/35128339-ec6053c8-fc6a-11e7-8a54-1d322cf647d7.png)

**Environment**

* System information:

	`4.4.111-boot2docker`

* Prometheus version:

	`prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2`

* Prometheus configuration file:
Will provide them if necessary.

* Logs:
Will provide them if necessary.
