### ISSUE TITLE
Scrape over TCP 

### ISSUE THREAD

**Issue by tormath1** [prometheus/prometheus#3727]
Hi everyone,

I am wondering if it could be a nice idea to scrape over `TCP` scheme instead of `https` / `https` exposed endpoints. I am sure you have your reasons to not implement this ! 

A use case: services not exposed over HTTP and you do not want to push on a a `Push Gateway`. 

We could have a `docker-compose` configuration like:

```yaml
...
service1:
  networks:
    - prometheus-network
...
```

and `prometheus.yaml`

```yaml
...
scrape_configs:
  ...
  scheme: tcp
  ...
```

Thanks in advance for your answer 😄
