### ISSUE TITLE
read label value index: invalid checksum

### ISSUE THREAD

**Issue by tinytub** [prometheus/prometheus#3734]
**What did you do?**
get all labels by api   `/api/v1/label/__name__/values`  and got error

I use 6 server to make a cluster
1 center server use to proxy all query request to backend server
others do scrape jobs

my prome02,prome03 server got the  invalid checksum error

prome02 sample append
![image](https://user-images.githubusercontent.com/1871460/35369187-d000b392-01c1-11e8-83ee-fc7a3e18c3df.png)
prome03 sample append
![image](https://user-images.githubusercontent.com/1871460/35369214-e884d4ac-01c1-11e8-9ac0-754eb8e0f135.png)

the high light line is the error folder.
![image](https://user-images.githubusercontent.com/1871460/35369403-b418117e-01c2-11e8-92b5-3361a1ae1cd1.png)

**What did you expect to see?**
get all labels with no error

**What did you see instead? Under which circumstances?**

```
{
  "status": "error",
  "errorType": "execution",
  "error": "block: 01C4HGBJWVNH2HACQ8T941R3YV: read label value index: invalid checksum"
}
```

**Environment**

* System information:

Linux 2.6.32-696.3.2.el6.v6.2.x86_64 x86_64

* Prometheus version:

prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2

* Prometheus configuration file:

```
# center server only do remote_read

remote_read:
  - url: "http://prome01:9090/api/v1/read"
    remote_timeout: 300s
  - url: "http://prome02:9090/api/v1/read"
    remote_timeout: 300s
  - url: "http://prome03:9090/api/v1/read"
    remote_timeout: 300s
  - url: "http://prome04:9090/api/v1/read"
    remote_timeout: 300s
  - url: "http://prome05:9090/api/v1/read"
    remote_timeout: 300s
```

```
#backend server do scrape job,and use hashmod.

scrape_configs:
  - job_name: 'wonder-transfer'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
       - targets:
          - 'k12735v:6061'
          ...
          ...
          - 'k4645v:6061'
    metric_relabel_configs:
    - source_labels: [bid]
      modulus:       5 
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^4$  
      action:        keep
    - target_label: instance
      replacement: Transfer
```
