### ISSUE TITLE
parse error in expression in alert rule

### ISSUE THREAD

**Issue by pznamensky** [prometheus/prometheus#3761]
**What did you do?**
Pasted correct PromQL expression into alerting rule
The rule looks like:
```
groups:
- name: MySweetGroup
  rules:
  - alert: MySweetRule
    expr: max(allocation_memory)  by (exported_job) / max(allocation_memory_limit) by (exported_job) > 0.8
    for: 5m
    labels:
      severity: info
    annotations:
      summary: Oops
```

**What did you expect to see?**
Working alert

**What did you see instead? Under which circumstances?**
Prometheus error:
```
caller=manager.go:479 component="rule manager" msg="loading groups failed" err="group \"MySweetGroup\", rule 0, \"MySweetRule\": could not parse expression: parse error at char 52: unexpected <by> in aggregation, expected \")\""
```

* Prometheus version:
```
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2
```
