### ISSUE TITLE
heavy memory usage

### ISSUE THREAD

**Issue by tonobo** [prometheus/prometheus#3774]
The prometheus server is currently allocating the whole series of 30GB in memory. By just putting hardware on it, its back again and faster than before ;D. But in general its not an option :smile:

**What did you do?**

Queries, often! 

**Environment**

* System information:

```
level=info ts=2018-01-31T19:11:46.652846354Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
level=info ts=2018-01-31T19:11:46.65287715Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
level=info ts=2018-01-31T19:11:46.6528934Z caller=main.go:227 host_details="(Linux 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 node3 (none))"
level=info ts=2018-01-31T19:11:46.652904858Z caller=main.go:228 fd_limits="(soft=1048576, hard=1048576)"
```

* Prometheus configuration file:
```yaml
alerting:
    alertmanagers:
    -   static_configs:
        -   targets:
            -  localhost:9095
global:
    evaluation_interval: 15s
    scrape_interval: 15s
rule_files:
- /etc/prometheus/git_rules.d/*.yml
scrape_configs:
-   file_sd_configs:
    -   files:
        - /etc/prometheus/*.json
    honor_labels: true
    job_name: metrics
    scrape_interval: 2s
    scrape_timeout: 1s
```

* Logs:

![image](https://user-images.githubusercontent.com/6775896/35639023-1d5b002e-06b9-11e8-838f-90dbb6636ac8.png)

![image](https://user-images.githubusercontent.com/6775896/35639049-395d4b74-06b9-11e8-9771-0fd271b3fa2c.png)

![image](https://user-images.githubusercontent.com/6775896/35639125-6e4d6242-06b9-11e8-9bf4-435577b37b96.png)

![image](https://user-images.githubusercontent.com/6775896/35639176-a31354d2-06b9-11e8-9c10-99f214993033.png)

**Comment by krasi-georgiev** [comment]
yes the promql defenetely needs optimising and there is already an idea to use streaming.
https://github.com/prometheus/prometheus/issues/3690
Might be best to close this one and subscribe to the discussions there.

I am also trying few things, but this will take time.

**Comment by brian-brazil** [comment]
There's in sufficient information here to know if anything is wrong. What is your ingestion rate and what sort of queries are you using? In particular are they pulling in hours or days of data?

**Comment by tonobo** [comment]
99,5% of the queries are just pulling the last 5 minutes of data. Also no complex aggregations are performed. There is no mentionable cpu load

**Comment by brian-brazil** [comment]
What about the other .5%? What is your ingestion rate? There's still insufficient information to know if this is unexpected.

Can you run this dashboard against your Prometheus: https://grafana.com/dashboards/3834

**Comment by tonobo** [comment]
![image](https://user-images.githubusercontent.com/6775896/35645131-40b0b61a-06cb-11e8-84d2-40eebc2caa3a.png)

**Comment by brian-brazil** [comment]
It looks like you have some expensive rules that are taking too long to evaluate, 2.1 will show you how long each rule is taking so you can pinpoint which rule it is in particular. That may be what's pulling in all the data.

**Comment by tonobo** [comment]
Thanks a lot. Great support guys.

![image](https://user-images.githubusercontent.com/6775896/35649959-e14e0136-06da-11e8-8bda-b243045fcc31.png)

**Comment by tonobo** [comment]
Ive done futher investigations. The rule evalutation time is around 20s, but the memory seems to be allocated for multiple minutes.

```yaml
record: statistic_cpu_intensive
expr: avg(avg_over_time(cpu_percent[12h]))
  BY (domain) > 95
```

I know the query needs to load all memory series, but it wouldn't scale well if this would be done fully in memory. E.g PostgreSQL allows to configure a memory limit, larger memory allocations will trigger disk based aggregations.
