### ISSUE TITLE
Unable to load all the rules with * wildcard in a Directory

### ISSUE THREAD

**Issue by Neru007** [prometheus/prometheus#3786]
**What did you do?** Trying to load the rules configuration from a directory with *.rules

**What did you expect to see?** Expected that all the rules file should get loaded

**What did you see instead? Under which circumstances?** Prometheus unable to load the configuration and getting error "failed to reload config: one or more errors occurred while applying the new configuration (--config.file=/opt/config/prometheus.yml)"

**Environment** RHEL 7.3

* System information:

	Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)
  build user:       root@615b82cb36b6
  build date:       20171108-07:11:59
  go version:       go1.9.2

* Alertmanager version:

alertmanager, version 0.11.0 (branch: HEAD, revision: 30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:8080

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
   - '/etc/autoscale/*.rules'
   - "system.rules"
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
