### ISSUE TITLE
cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs even when server_name passed

### ISSUE THREAD

**Issue by vbasavani** [prometheus/prometheus#3790]
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 15s

# Alertmanager configuration
#alerting:
#  alertmanagers:
#  - static_configs:
#    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
      api_server: 'https://api.internal.example.com'
      basic_auth:
        username: 'admin'
        password: 'password'
      tls_config:
        ca_file: '/opt/prometheus-2.1.0.linux-amd64/ca.crt'
        server_name: kubernetes
        insecure_skip_verify: false
    scheme: https
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_namespace,__meta_kubernetes_pod_label_name]
      separator: '/'
      target_label: job
    - source_labels: [__meta_kubernetes_pod_node_name]
      target_label: node
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
      api_server: 'https://api.internal.example.com'
      basic_auth:
        username: 'admin'
        password: 'password'
      tls_config:
        ca_file: '/opt/prometheus-2.1.0.linux-amd64/ca.crt'
        server_name: kubernetes
        insecure_skip_verify: false
    scheme: https
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
```
I am getting the below error.
```
Get https://x.x.x.x:10250/metrics: x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
```
and the kubernetes cluster is running on aws using kops and the certificate has subject CN=kubernetes
can anybody help me on how to resolve this issue?
