### ISSUE TITLE
Results are nondeterministic for regex __name__ queries

### ISSUE THREAD

**Issue by fmoessbauer** [prometheus/prometheus#3794]
**What did you do?**

Use regex query on medium time ranges (e.g. 1 week):
`{__name__=~"mem_(active|buffers|cached|free|inactive).*", host="kronos"}`

**What did you expect to see?**

All matching series for the selected time range. If executed multiple times, I expect to see the same results (roughly, if range is up to now). The results should be deterministic.

**What did you see instead? Under which circumstances?**

Some series are missing for some timesteps. If I repeat the query multiple times, the results are nondeterministic. Sometimes all series are shown, sometimes not. Which series are fully shown also changes (see pictures). Prometheus retention is: `--storage.tsdb.retention=1d`

![prometheus-01](https://user-images.githubusercontent.com/9655545/35779952-433f673e-09d5-11e8-9f46-cc341531899d.png)

![prometheus-02](https://user-images.githubusercontent.com/9655545/35779958-53eade74-09d5-11e8-9aed-1b0616e7b074.png)

![prometheus-03](https://user-images.githubusercontent.com/9655545/35779959-5628da74-09d5-11e8-914d-17c35c5da37d.png)

**Environment**

* System information:

`Linux 4.13.0-25-generic x86_64`

* Prometheus version:

```
prometheus, version 2.1.0 (branch: master, revision: 460fe4dd0c352577395391ed861cec1b7d7d2312)
  build user:       root@94e5fb29216a
  build date:       20180202-18:18:34
  go version:       go1.9.2
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090', 'collectd-exporter:9103']

  - job_name: 'linux-server'
    scrape_interval: 60s
    static_configs:
      - targets:
        - '192.168.2.xx:xxxx'

# [...]

rule_files:
  - alert-rules/*.rule

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
  - url: "http://prom-io:9201/write"

# Remote read configuration (for InfluxDB only at the moment).
remote_read:
  - url: "http://prom-io:9201/read"
```

* Logs:

Probably related (appears a few times, but not time correlated to the issue)
```
level=error ts=2018-02-04T16:37:34.24095367Z caller=engine.go:527 component="query engine" msg="error selecting series set" err="error sending request: context canceled"
```
