### ISSUE TITLE
Prometheus 2.x inconsistent results through the time

### ISSUE THREAD

**Issue by onorua** [prometheus/prometheus#3799]
**What did you do?**
I do query:
```
curl 'http://prometheus-nodes-ca-ovh.afdevops.com:9090/api/v1/query?query=packetsByRange&start=2018-01-31T00:48:48Z&end=2018-01-31T01:18:48Z&step=30m'
```

**What did you expect to see?**
I expect result to be consistent, values should be either exists or does not exists all the time, because  `start` and `stop` times never changed in the query.

**What did you see instead? Under which circumstances?**
I've got following:
```
MBP13:ansible-prometheus onorua$ curl 'http://prometheus-nodes-ca-ovh.afdevops.com:9090/api/v1/01-31T01:18:48Z&step=30m'e&start=2018-01-31T00:48:48Z&end=2018-0
{"status":"success","data":{"resultType":"vector","result":[]}}
MBP13:ansible-prometheus onorua$ curl 'http://prometheus-nodes-ca-ovh.afdevops.com:9090/api/v1/01-31T01:18:48Z&step=30m'e&start=2018-01-31T00:48:48Z&end=2018-0
{"status":"success","data":{"resultType":"vector","result":[]}}
MBP13:ansible-prometheus onorua$ curl 'http://prometheus-nodes-ca-ovh.afdevops.com:9090/api/v1/01-31T01:18:48Z&step=30m'e&start=2018-01-31T00:48:48Z&end=2018-0
{"status":"success","data":{"resultType":"vector","result":[]}}
MBP13:ansible-prometheus onorua$ curl 'http://prometheus-nodes-ca-ovh.afdevops.com:9090/api/v1/01-31T01:18:48Z&step=30m'e&start=2018-01-31T00:48:48Z&end=2018-0
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"packetsByRange","cluster":"checker-ny-1","colo":"checker","colo_type":"ny","container_name":"node-exporter","h":"23b6789","host_name":"abhi-checker-ny-1","host_type":"abhi-checker-ny","instance":
 ...
```
Important thing is, this metric is not regular, there is some tool Im not aware of which has metrics for 5 minutes and then 5 minutes there is no metrics:
<img width="1244" alt="screen shot 2018-01-31 at 5 33 12 pm" src="https://user-images.githubusercontent.com/407040/35802599-69f2d5b0-0a79-11e8-9616-ac51aa4f1975.png">

**Environment**
dockerized Prometheus 2.1.0

* System information:
```
root@prometheus-nodes-ca-ovh:~# uname -srm
Linux 4.8.0-42-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
  build user:       root@6e784304d3ff
  build date:       20180119-12:01:23
  go version:       go1.9.2
```

* Prometheus configuration file:
```
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=31d'
      - '--web.enable-admin-api'
      - '--storage.tsdb.max-block-duration=1d'
      - '--storage.tsdb.min-block-duration=2h'
```

config:
```
global:
  scrape_interval: 30s
  scrape_timeout: 20s
  evaluation_interval: 30s
  external_labels:
    prometheus: node
alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: localhost:8500
      tag_separator: ','
      scheme: http
      services:
      - alertmanager
    scheme: http
    timeout: 10s
rule_files:
- /etc/prometheus/hss_recording.rules.yml
- /etc/prometheus/hss_alert.rules.yml
- /etc/prometheus/comscore_alert.rules.yml
- /etc/prometheus/css_alert.rules.yml
- /etc/prometheus/prometheus_alert.rules.yml
- /etc/prometheus/satellite_alert.rules.yml
- /etc/prometheus/efk_alert.rules.yml
- /etc/prometheus/recording.rules.yml
- /etc/prometheus/consul.rules.yml
- /etc/prometheus/storage_alert.rules.yml
- /etc/prometheus/bastion_alert.rules.yml
scrape_configs:
- job_name: efk-services
  scrape_interval: 30s
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  consul_sd_configs:
  - server: localhost:8500
    tag_separator: ','
    scheme: http
    services:
    - node-exporter
```

* Logs:
nothing related to this
