### ISSUE TITLE
Remote Storage Queue won't flush

### ISSUE THREAD

**Issue by fmoessbauer** [prometheus/prometheus#3809]
**What did you do?**

Update prometheus to commit 404b306fb9d5c0976cc83f0dff39254c0918493e

**What did you expect to see?**

Remote storage working properly.

**What did you see instead? Under which circumstances?**

Writes to the remote storage are not flushed. The remote_storage_queue fills up until no more elements fit in and then samples are dropped.

This is probably related to PR #3731 

![remote-storage-queue-annotate](https://user-images.githubusercontent.com/9655545/35919684-298513b4-0c16-11e8-8868-f5f8821ee666.png)

**Environment**

* System information:

`Linux 4.13.0-25-generic x86_64`

* Prometheus version:

```
prometheus, version 2.1.0 (branch: master, revision: 404b306fb9d5c0976cc83f0dff39254c0918493e)                                            
  build user:       root@3dc6e252e6c2                                
  build date:       20180207-10:31:30                                
  go version:       go1.9.2
```

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 15s

    static_configs:
      - targets: ['localhost:9090', 'collectd-exporter:9103']

  - job_name: 'linux-server'
    scrape_interval: 60s
    static_configs:
      - targets:
        - '192.168.2.xx:xxxx'

# [...]

rule_files:
  - alert-rules/*.rule

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093

# Remote write configuration (for Graphite, OpenTSDB, or InfluxDB).
remote_write:
  - url: "http://prom-io:9201/write"

# Remote read configuration (for InfluxDB only at the moment).
remote_read:
  - url: "http://prom-io:9201/read"
```

* Logs:
```
level=warn ts=2018-02-07T13:55:17.944112632Z caller=queue_manager.go:225 component=remote msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
```
