### ISSUE TITLE
Prometheus 2.2.0-rc.1 alerts does not support advanced yaml anchor syntax

### ISSUE THREAD

**Issue by freznicek** [prometheus/prometheus#3889]
**What did you do?**

I failed to use [advanced yaml anchor syntax](https://en.wikipedia.org/wiki/YAML#Advanced_components) in prometheus alert definition.

Why I want that? I want to reduce alert definition duplications.

This prometheus alert rule yaml fails to parse due to strict field existence rules:

```yaml
.comm-labels: &comm-labels
  team: xxxxxxxxxxxx@yyyyyyyyyyyy.cz
  severity: critical
  #pager: pagerduty

groups:
- name: dns_resolve_error
  rules:

  # Aserver application
  # -------------------------------------------------------------------------
  - alert: AServerDNSResolveError
    expr: increase(errors_total{app="aserver",type="DNSResolveError"}[2m]) > 10
    for: 4m
    labels:
      <<: *comm-labels
    annotations:
      title: Pod {{$labels.namespace}}/{{$labels.instance}}, locality {{$labels.locality}} sees {{ $value }} DNSResolveError[s] for host {{$labels.remote_app}}
      description: Aserver detected more than 10 DNSResolveError issues per 2 minutes (lasts for at least 4 minutes)
      playbook: howto/k8s-dns-failures.md

  # BServer application
  # -------------------------------------------------------------------------
  - alert: BServerDNSResolveError
    expr: increase(errors_total{app=~"bserver.*",type=~"DNSResolveError|YError"}[2m]) > 10
    for: 4m
    labels:
      <<: *comm-labels
    annotations:
      title: Pod {{$labels.namespace}}/{{$labels.instance}}, locality {{$labels.locality}} sees {{ $value }} DNSResolveError[s] for host {{$labels.remote_app}}
      description: BServer detected more than 10 DNSResolveError issues per 2 minutes (lasts for at least 4 minutes)
      playbook: howto/k8s-dns-failures.md
```

Promtool alert checker says:
```
$ promtool check rules /tmp/prometheus_alert_1.yaml
Checking /tmp/prometheus_alert_1.yaml
  FAILED:
unknown fields in config_file: .comm-labels
```

**What did you expect to see?**

I'd like to see prometheus supporting `<<: *` syntax.
Moreover Prometheus should define which fields are ignored, for instance the way as gitlab-ci.yml does (ignores everything strating with dot).

**What did you see instead? Under which circumstances?**

Above alert not valid:
```
$ promtool check rules /tmp/prometheus_alert_1.yaml
Checking /tmp/prometheus_alert_1.yaml
  FAILED:
unknown fields in config_file: .comm-labels
```

**Environment**

* System information:
        multiple specs:
          Linux 4.6.0-0.bpo.1-amd64 x86_64
          Linux 4.11.12-100.fc24.x86_64 x86_64

* Prometheus version:

```
* prometheus docker image: prom/prometheus:v2.2.0-rc.1

$ promtool --version
promtool, version 2.2.0-rc.0 (branch: HEAD, revision: 1fe05d40e4b2f4f7479048b1cc3c42865eb73bab)
  build user:       root@f7abb25edc70
  build date:       20180213-11:40:47
  go version:       go1.9.2

```

* Prometheus configuration file:
Sorry cannot disclose this at this point.

* Logs:
```
$ promtool check rules /tmp/prometheus_alert_1.yaml
Checking /tmp/prometheus_alert_1.yaml
  FAILED:
unknown fields in config_file: .comm-labels
```
