### ISSUE TITLE
printf query on resolved alert not showing current state

### ISSUE THREAD

**Issue by ojle** [prometheus/prometheus#3906]
I have following alert rule:

```
groups:
- name: loadavg
  rules:
  - alert: HighLoadAvg
    expr: ((system_load5 / count without (cpu, mode) (cpu_usage_idle{cpu!="cpu-total"})) > 1.3)
    for: 2m
    labels:
      severity: warning
    annotations:
      description : 'load average: {{ printf `system_load1{instance="%s"}` $labels.instance | query | first | value }}, {{ printf `system_load5{instance="%s"}` $labels.instance | query | first | value }}, {{ printf `system_load15{instance="%s"}` $labels.instance | query | first | value }}'
```
When triggered I get in email current load stats:
```WARNING - load average: 4.16, 3.54, 2.25```
When resolved I also get current load stats:
```OK - load average: 1.19, 2.64, 2.79```

If I try similar rule for disk space, ie.
```
description : 'disk space: {{ $labels.path }} {{ printf `disk_used_percent{path="/tmp",server="%s"}` $labels.server | query | first | value | humanize }}%'
```
I only get current stat when alert is triggered, ie.
```WARNING - disk space: /tmp 82.72%```
and then
```OK - disk space: /tmp 82.72%```

Am I missing something here?
How/why is the query on resolved alert for system_load being evaluated?

running prometheus 2.0.0
