### ISSUE TITLE
__param_match[] available in relabeling

### ISSUE THREAD

**Issue by skpenpen** [prometheus/prometheus#3926]
**What did you do?**

Try to use relabelling to populate the parameter "match[]" for federation

**What did you expect to see?**

The "__param_match[]" populate from value from consul tag "param"

**What did you see instead? Under which circumstances?**

failed to reload config: couldn't load configuration (--config.file=/prometheus/conf/prometheus-smhg-mutu.yml): parsing YAML file /prometheus/conf/prometheus.yml: "__param_match[]" is invalid 'target_label' for replace action                                                                                                                    

**Environment**

* System information:

Linux 3.10.0-693.11.1.el7.x86_64 x86_64

* Prometheus version:

	2.1.0

* Prometheus configuration file:
```
relabel_configs:
  - source_labels: ['__meta_consul_tags']
      regex: '.*;params=([^;]*).*'
      target_label: '__param_match[]'
```

* Logs:
```
err="couldn't load configuration (--config.file=/prometheus/conf/prometheus.yml): parsing YAML file /prometheus/conf/prometheus.yml: \"__param_match[]\" is invalid 'target_label' for replace action"
```
