### ISSUE TITLE
proxy_url available for relabelling

### ISSUE THREAD

**Issue by skpenpen** [prometheus/prometheus#3927]
**What did you do?**

Try to use relabelling to populate the target parameter "proxy_url"
But it cant be done, you cant override it via relabelling, there is no possibility to do so.
Can you make it append ?

**What did you expect to see?**

The "proxy_url" populate from value from consul tag "proxy"

**What did you see instead? Under which circumstances?**

nothing                                                                                                             

**Environment**

* System information:

Linux 3.10.0-693.11.1.el7.x86_64 x86_64

* Prometheus version:

	2.1.0

* Prometheus configuration file:
```
relabel_configs:
  - source_labels: ['__meta_consul_tags']
      regex: '.*;proxy=([^;]*).*'
      target_label: '__proxy_url'
```

* Logs:
```
nothing
```
