### ISSUE TITLE
The value of $value will not change when recovery occurs.

### ISSUE THREAD

**Issue by zhou-mfk** [prometheus/prometheus#3986]
Hi
    I have a confusion about the variable {{$value}} in the promethues alert rule.
   When a monitoring item is restored, I always get the correct value. The value of the {{$value}} variable represents the alarm at firing time.

**Environment**

* System information:

	Linux 3.10.0-514.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.2.1 (branch: HEAD, revision: 
        bc6058c81272a8d938c05e75607371284236aadc)
        build user:       root@149e5b3f0829
        build date:       20180314-14:15:45
        go version:       go1.10

* Alertmanager version:
alertmanager, version 0.11.0 (branch: HEAD, revision: 30dd0426c08b6479d9a26259ea5efd63bc1ee273)
  build user:       root@3e103e3fc918
  build date:       20171116-17:43:56
  go version:       go1.9.2

* Prometheus configuration file:
```
Prometheus rules config
- alert: App_Close_Wait_GT_500
    expr: appstatus_appclosewait > 500
    for: 1m
    labels:
      alert_type: app
      monitor: appstatus_appclosewait
      serverity: critical
      current_value: '{{ $value }}'
    annotations:
      description: '{{$labels.instance }} of group {{ $labels.group }}'
      recovery: 'Recovery! Host {{ $labels.instance }} current value: {{ $value }} Project Name is {{ $labels.name }} CloseWait less than 500'
      summary: 'Host {{ $labels.host }} Project Name is {{ $labels.name }} CloseWait current value is: {{ $value }} more than 500'

```
The warning message I received is as follows.
![image](https://user-images.githubusercontent.com/15190461/37640510-e7922d7e-2c50-11e8-8ae6-82febd19d867.png)

At this point, {{$value}} is normal.

However, when recovery, the value of {{$value}} is not updated, 
The recovery email is as follows
![image](https://user-images.githubusercontent.com/15190461/37640583-4826b9f2-2c51-11e8-9131-84523c0d058e.png)

Can you tell me how to get the correct value in the alarm?

Thanks!
