### ISSUE TITLE
Kubernetes ingress discovery does not set address label for ingresses without host 

### ISSUE THREAD

**Issue by Mattias-** [prometheus/prometheus#4008]
**What did you do?**
Configured discovery of kubernetes ingresses.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-ingress
  namespace: monitoring-prometheus
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    prometheus.io/probe: "true"
spec:
  rules:
    - http:
        paths:
          - path: /alertmanager
            backend:
              serviceName: alertmanager
              servicePort: http
    - http:
        paths:
          - path: /alertmanager
            backend:
              serviceName: alertmanager
              servicePort: http
      host: alertmanager.local
```

**What did you expect to see?**
All annotated ingresses to show up as targets that can be successfully scraped.

**What did you see instead? Under which circumstances?**
No target label is set for ingresses that hasn't specified a host and the scraping fail.
![image](https://user-images.githubusercontent.com/1002805/37869690-84d0d0fe-2fbc-11e8-991b-5a89781d73cc.png)

![image](https://user-images.githubusercontent.com/1002805/37869760-fc310b40-2fbd-11e8-8291-abcc7cd6747b.png)

**Environment**

* System information:

`Linux 4.9.64 x86_64`

* Prometheus version:

`2.2.1` docker image

* Prometheus configuration file:
```
    - job_name: 'kubernetes-ingresses'

      metrics_path: /probe
      params:
        module: [http_2xx]

      kubernetes_sd_configs:
      - role: ingress

      relabel_configs:
      - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_ingress_scheme,__address__,__meta_kubernetes_ingress_path]
        regex: (.+);(.+);(.+)
        replacement: ${1}://${2}${3}
        target_label: __param_target
      - source_labels: [__meta_kubernetes_ingress_scheme,__meta_kubernetes_ingress_path]
        regex: (.+);(.+)
        replacement: ${1}://xx${2}
        target_label: mylabel
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_ingress_name]
        target_label: kubernetes_name
```
