### ISSUE TITLE
Data was changed when I refresh the Graph 

### ISSUE THREAD

**Issue by lwhile** [prometheus/prometheus#4053]
**What did you do?**
I viewed the metrics at the build in web graph

**What did you expect to see?**
I want the Prometheus to give me correct data

**What did you see instead? Under which circumstances?**
The graph's history data was changed when I refresh it

**Environment**

* System information:

	```Darwin 17.4.0 x86_64```

* Prometheus version:

```
prometheus, version 2.2.1 (branch: HEAD, revision: 
bc6058c81272a8d938c05e75607371284236aadc)
build user:       root@149e5b3f0829
build date:       20180314-14:21:40
go version:       go1.10      
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     1s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: '{my_job}'

    static_configs:
      - targets: ['localhost:20120']
    metrics_path: '/{mypath}'
```
 
![image](https://user-images.githubusercontent.com/13641863/38411214-27e25fc8-39b9-11e8-812c-790970bc8903.png)

After clicking several times of Execute button 

![image](https://user-images.githubusercontent.com/13641863/38411248-38a4c3fa-39b9-11e8-8c96-ea71fdf177ab.png)

Once again

![image](https://user-images.githubusercontent.com/13641863/38411268-4a9e880c-39b9-11e8-9e9e-a1f175a31963.png)
