### ISSUE TITLE
Support remote_read shard remote storage

### ISSUE THREAD

**Issue by Wing924** [prometheus/prometheus#4062]
We need horizontal partition the storage backend in case the metrics are too huge that one storage can't handle. Currently, we can use remote read feature to archive this function by set multiple remote read endpoints. But remote read function send queries to all backends even if we know in advance that backend don't have matched metrics.
I suggest add a shard option for better perforamnce.

For example, we have 2 backends, one stores production metrics the other stores development metrics.
```yaml
remote_read:
# only contains metrics with {env="prod"}
- url: http://prod-backend/api/v1/read
  shards:
    env: 
    - prod
# only contains metrics with {env="stg"} or {env="dev"}
- url: http://devel-backend/api/v1/read
  shards:
    env:
    - stg
    - dev 
```

* If a query have `{env="prod"}` we can skip `devel-backend`
* If a query have `{env!="prod"}` we can skip `prod-backend`
* If a query have `{env=~"stg|dev"}` we can skip `prod-backend`
* If a query have `{env=~".*notexist.*"}` we can skip both
* If a query don't have have `env` label,  we can query both backends like current implementation.
