### ISSUE TITLE
Race when reloading the config

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/prometheus#4067]
**What did you do?**
 - started prometheus to scrape itself - 
`go run --race main.go  uname_default.go fdlimits_default.go --storage.tsdb.min-block-duration=5m --storage.tsdb.max-block-duration=15m --config.file=../../promBench.yml`
 - wait few seconds until prometheus registeres all targets and starts scraping.
 - in a separate terminal run `watch -n 1 killall -1 main` to keep reloading the config file

```
==================
WARNING: DATA RACE
Read at 0x00c420013838 by goroutine 14:
  github.com/prometheus/prometheus/scrape.(*scrapePool).appender()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:404 +0x262
  github.com/prometheus/prometheus/scrape.(*scrapePool).(github.com/prometheus/prometheus/scrape.appender)-fm()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:171 +0x41
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).report()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:991 +0x207
  github.com/prometheus/prometheus/scrape.(*scrapeLoop).run()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:720 +0xbf7

Previous write at 0x00c420013838 by goroutine 86:
  github.com/prometheus/prometheus/scrape.(*scrapePool).reload()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:214 +0x1b2
  github.com/prometheus/prometheus/scrape.(*Manager).ApplyConfig()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/manager.go:104 +0x392
  github.com/prometheus/prometheus/scrape.(*Manager).ApplyConfig-fm()
      /home/krasi/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:306 +0x4b
  main.reloadConfig()
      /home/krasi/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:606 +0x2eb
  main.main.func14()
      /home/krasi/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:450 +0x57e
  github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1()
      /home/krasi/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x34

Goroutine 14 (running) created at:
  github.com/prometheus/prometheus/scrape.(*scrapePool).sync()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:312 +0x589
  github.com/prometheus/prometheus/scrape.(*scrapePool).Sync()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/scrape.go:270 +0x74d
  github.com/prometheus/prometheus/scrape.(*Manager).reload()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/manager.go:170 +0x30d
  github.com/prometheus/prometheus/scrape.(*Manager).Run()
      /home/krasi/src/github.com/prometheus/prometheus/scrape/manager.go:69 +0x5c
  main.main.func12()
      /home/krasi/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:425 +0xc7
  github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run.func1()
      /home/krasi/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:38 +0x34

Goroutine 86 (running) created at:
  github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group.(*Group).Run()
      /home/krasi/src/github.com/prometheus/prometheus/vendor/github.com/oklog/oklog/pkg/group/group.go:37 +0x10b
  main.main()
      /home/krasi/src/github.com/prometheus/prometheus/cmd/prometheus/main.go:581 +0x95f3
==================
```

* Prometheus version:
2.2
* Prometheus configuration file:

```
global:
  scrape_interval:     500ms # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus1'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus3'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus4'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus5'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus6'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus7'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus8'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus9'
    static_configs:
      - targets: ['localhost:9090']

```
