### ISSUE TITLE
v1.Pod: User \"kubernetes\" cannot list pods at the cluster scope

### ISSUE THREAD

**Issue by kongsys** [prometheus/prometheus#4081]
## Proposal
**Use case. Why is this important?**
prometheus access k8s, get error , prometheus use bearer token file
service-account.name is prometheus not Kubernetes ,and prometheus run in ec2

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	
Linux 4.4.53-1.el7.centos.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.2.1

* Alertmanager version:

	not yet use Altermanager

* Prometheus configuration file:
```
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
  - job_name: "consul-prometheus"
    consul_sd_configs:
      - server: "172.31.13.134:8500"
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*prometheus-target.*
        action: keep
  - job_name: "kubernetes-apiservices"

    kubernetes_sd_configs:
    - role: endpoints
      #api_server: https://172.31.12.82:6443
      api_server: https://172.31.12.82:6443
      bearer_token_file: /mnt/disk0/prometheus-2.2.1.linux-amd64/token
      tls_config:
        insecure_skip_verify: true
        cert_file: /mnt/disk0/prometheus-2.2.1.linux-amd64/kubernetes.pem
        key_file: /mnt/disk0/prometheus-2.2.1.linux-amd64/key.pem

    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https
```

* Logs:
```
level=error ts=2018-04-12T12:34:52.639922534Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:268: Failed to list *v1.Endpoints: User \"kubernetes\" cannot list endpoints at the cluster scope. (get endpoints)"
level=error ts=2018-04-12T12:34:52.639971823Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:269: Failed to list *v1.Service: User \"kubernetes\" cannot list services at the cluster scope. (get services)"
level=error ts=2018-04-12T12:34:52.640026257Z caller=main.go:216 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:270: Failed to list *v1.Pod: User \"kubernetes\" cannot list pods at the cluster scope. (get pods)"
```
