### ISSUE TITLE
Stale issue when federate from other Prometheus

### ISSUE THREAD

**Issue by dmitriy-lukyanchikov** [prometheus/prometheus#4082]
## Proposal
remove timestamp from federated metrics

## Bug Report
**What did you do?**
I have 2 prometheus servers A and B. Server B configured to federate from server A.
On server A i have metric with couple of labels inside file, it look like this `server_labels{dc="fr",env="prod"} 1`
I use it in group_left query

then i run query to see metric labels changes in time on graph from Server B that do federation

**What did you expect to see?**
i expected to see different metric labels on graph, and see changes of labels

**What did you see instead? Under which circumstances?**
many-to-many error. Investigation confermed that its a stale issue because all federated values have timestamp and prometheus wait exactly 5 minutes before make decision that this metric are not exist. This was the cause that for period of 5-6 minutes tehre is two copy of metric with different labels.
from Server A (that actually collect metrics from nodes) query work perfectly.
All federated metrics looks like this `server_labels{dc="fr",env="prod"} 1 1523536675185`

**Environment**

VMs on Digital Ocean

* System information:

Linux 4.4.0-119-generic x86_64

* Prometheus version:

both prometheus servers are 2.1.0

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     60s # By default, scrape targets every 15 seconds.
  evaluation_interval: 60s # By default, scrape targets every 15 seconds.
  scrape_timeout: 50s
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
#  - "lr_recording.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  # Auto-discovery via consul tags by Registrator


  - job_name: 'federate_lr_metrics_node'
    scrape_interval: 60s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__="server_labels"}'


    static_configs:
      - targets:
        - 'server_ip:9090'
```
