### ISSUE TITLE
GC drops all the series from the head-block every 2 hours

### ISSUE THREAD

**Issue by semyonslepov** [prometheus/prometheus#4115]
## Bug Report
**What did you do?**

Normal Prometheus operation with ~1000000 series in the head block

**What did you expect to see?**

Smooth operation with all the data available ~99.99% of time.
Some percentage of time-series being dropped from the head block on every GC execution but not all of them.

**What did you see instead? Under which circumstances?**

It seems that every 2 hours all the series are dropped from the head block and then restored in ~10 minutes.
This event coincides with the GC execution.
Time-series data from time to time becomes unavailable during this "drop-restore" period.
Relevant metrics:

![prometheus_tsdb_head_series_created_total](https://user-images.githubusercontent.com/27204211/39298256-fa9c81e6-4945-11e8-8187-59215970556e.png)
![prometheus_tsdb_head_series_removed_total](https://user-images.githubusercontent.com/27204211/39298257-faba31f0-4945-11e8-8a08-58b0bc12be2f.png)
![prometheus_tsdb_head_series](https://user-images.githubusercontent.com/27204211/39298258-fadbb4d8-4945-11e8-95a8-390b239e3009.png)

And it happens every 2 hours:

![series_removed_12h](https://user-images.githubusercontent.com/27204211/39298344-302c1038-4946-11e8-8d83-38a218cdcf0a.png)

**Environment**

* System information:

`Linux 4.9.91-40.57.amzn1.x86_64 x86_64`

* Prometheus version:

```
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    account: aws_account_name
    monitor: prometheus-stack
    region: eu-west-1
scrape_configs:
- job_name: node_exporter
  scrape_interval: 30s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - ip-10-58-130-116:9100
  relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(.*)$
    target_label: tier
    replacement: p4
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: .*
    target_label: tier
    replacement: p4
    action: replace
- job_name: prometheus-server
  scrape_interval: 30s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - ip-10-58-130-116:9090
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: .*
    target_label: tier
    replacement: p4
    action: replace
- job_name: federate_lts
  honor_labels: true
  params:
    match[]:
    - '{job=~"[a-z].*",job!="federate_lts"}'
  scrape_interval: 1h
  scrape_timeout: 2m
  metrics_path: /federate
  scheme: http
  static_configs:
  - targets:
    - internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090
```

* Logs:
```
level=info ts=2018-04-26T03:00:00.789789541Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1524700800000 maxt=1524708000000
level=info ts=2018-04-26T03:00:20.711380725Z caller=head.go:348 component=tsdb msg="head GC completed" duration=2.95190116s
level=info ts=2018-04-26T03:00:22.715362637Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.003904086s
level=info ts=2018-04-26T03:00:23.670799123Z caller=compact.go:393 component=tsdb msg="compact blocks" count=3 mint=1524679200000 maxt=1524700800000
level=warn ts=2018-04-26T03:07:03.171395946Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=11585
level=warn ts=2018-04-26T04:06:50.777899371Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=26652
level=info ts=2018-04-26T05:00:00.789822667Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1524708000000 maxt=1524715200000
level=info ts=2018-04-26T05:00:20.636595412Z caller=head.go:348 component=tsdb msg="head GC completed" duration=2.961173699s
level=info ts=2018-04-26T05:00:22.712209338Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=2.07554931s
level=warn ts=2018-04-26T05:07:02.716418894Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=14158
level=warn ts=2018-04-26T06:06:50.703605369Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=21808
level=info ts=2018-04-26T07:00:00.789336883Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1524715200000 maxt=1524722400000
level=info ts=2018-04-26T07:00:17.381170201Z caller=head.go:348 component=tsdb msg="head GC completed" duration=2.120526312s
level=info ts=2018-04-26T07:00:19.36616827Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=1.984937139s
level=warn ts=2018-04-26T07:07:02.628056348Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=10883
level=warn ts=2018-04-26T08:06:50.339291254Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=40776
level=info ts=2018-04-26T09:00:00.79663534Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1524722400000 maxt=1524729600000
level=info ts=2018-04-26T09:00:17.869411821Z caller=head.go:348 component=tsdb msg="head GC completed" duration=2.191874292s
level=info ts=2018-04-26T09:00:19.864876385Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=1.995408902s
level=info ts=2018-04-26T09:00:20.843168795Z caller=compact.go:393 component=tsdb msg="compact blocks" count=3 mint=1524700800000 maxt=1524722400000
level=warn ts=2018-04-26T09:07:02.5320854Z caller=scrape.go:932 component="scrape manager" scrape_pool=federate_lts target="http://internal-prometheu-Internal-94VCZL74ZSUN-1346284009.eu-west-1.elb.amazonaws.com:9090/federate?match%5B%5D=%7Bjob%3D~%22%5Ba-z%5D.%2A%22%2Cjob%21%3D%22federate_lts%22%7D" msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=45838
```
