### ISSUE TITLE
K8s SD: Targets are not updated

### ISSUE THREAD

**Issue by beorn7** [prometheus/prometheus#4124]
## Bug Report
**What did you do?**

Scaled new K8s pods up, scaled old ones down.

**What did you expect to see?**

Old pods disappear from targets, new ones show up.

**What did you see instead? Under which circumstances?**

Prometheus doesn't see the new pods, tries to scrape the old ones.

**Environment**

* System information:

	Linux 4.4.10+soundcloud x86_64

* Prometheus version:

	most recently investigated version is revision 2be543e65ac2587ac46d87fef759d80bfb1c68f5 (in the release-2.2 branch). However, the same happened in all 2.2 releases, most notably also before the grand K8s SD refactoring of #4117 .

* Prometheus configuration file:

See the various comments below.

**Comment by beorn7** [comment]
This issue is seen in production at SoundCloud. I'm still working on reproducing it with a minimal setup.

In particular, this issue can __not__ be reproduced with the following setup (cf. https://github.com/prometheus/prometheus/pull/4117#issuecomment-384909820 ):

@krasi-georgiev wrote: "using the configs below seems to work as expected with minikube. 
When scaling up and down the deployment pods the  targets list get updated properly in the prometheus GUI."

```
global:
  scrape_interval:     500ms

scrape_configs:
- job_name: 'kubernetes-pods'
  tls_config:
    insecure_skip_verify: true
  
  kubernetes_sd_configs:
  - api_server: https://192.168.99.101:8443
    role: pod
    namespaces:
      names:
      - default
    tls_config:
      ca_file: /home/krasi/.minikube/ca.crt
      cert_file: /home/krasi/.minikube/client.crt
      key_file: /home/krasi/.minikube/client.key
```

```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

**Comment by beorn7** [comment]
Here is the job config that creates the problem:

```yaml
- job_name: myjob
  kubernetes_sd_configs:
  - api_server: https://api.mycluster.k8s.example.org
    role: pod
    tls_config:
      ca_file: "/srv/prometheus/k8s-certificates/mycluster/ca.crt"
      cert_file: "/srv/prometheus/k8s-certificates/mycluster/client.crt"
      key_file: "/srv/prometheus/k8s-certificates/mycluster/client.key"
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    regex: ".+;(?:[0-9]+,?)+|;"
  - action: keep
    source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_label_system
    regex: ".+;myjob|;"
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scheme
    target_label: __scheme__
    regex: "(https?)"
  - source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_path
    target_label: __metrics_path__
    regex: "(.+)"
  - source_labels:
    - __address__
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    target_label: __address__
    regex: "(.+?)(?::\\d+)?;(\\d+)"
    replacement: "$1:$2"
  - target_label: cluster
    replacement: mycluster
  - source_labels:
    - __meta_kubernetes_pod_label_system
    target_label: system
  - source_labels:
    - __meta_kubernetes_pod_label_env
    target_label: env
  - source_labels:
    - __meta_kubernetes_pod_label_component
    target_label: component
  - source_labels:
    - __meta_kubernetes_pod_label_version
    target_label: version
  - source_labels:
    - __meta_kubernetes_pod_label_track
    target_label: track
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: instance
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
```

**Comment by beorn7** [comment]
My general thoughts:

- The config per se seems sane, as it works on 1.8/2.0.
- The problem seems to be a missed update, as a SIGHUP gets it unstuck.
- Perhaps it makes a difference if the Prometheus server is in-cluster or not (assuming that @krasi-georgiev 's test config uses an in-cluster Prometheus).
- Another possible explanation for difficulties to reproduce: Perhaps this is a racey thing (not as in a data race detectable by the Go race detector, but in the more general meaning: it only happens now and then if the timing of events are "right"). @krasi-georgiev what happens if you let your test setup run for a longer time with continues scaling up and down?

**Comment by krasi-georgiev** [comment]
my Prometheus is running on the  local machine(bare metal) and the k8s minikube runs in a VM so it is the same as your setup. 
Now trying with your config and will try scaling up and down continuously.

**Comment by krasi-georgiev** [comment]
here is the minimal deployment that works with this config, but still works as expected on my setup so will keep digging.

```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template: 
    metadata:
      labels:
        app: nginx
        system: myjob
      annotations:
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
```
