### ISSUE TITLE
Can't add labels for alert rules at group level

### ISSUE THREAD

**Issue by ahrtr** [prometheus/prometheus#4139]
We defined lots of alert rules, which can be classified as a couple of groups.  We need to send alerts of each group to a different target (pagerDuty service).  So the plan is to add a different label for each group, i.e., group1, group2, group3, etc. 

But currently we have to add the label to each alert rule. It would be better if we can set the label to the group instead of each alert rule. What we want is something as below,

```
groups:
- name: alert rules for group1
  labels:
      service: group1
  rules:

  - alert: group1_rule1
    expr: xxxxxx
    for: 10m
    labels:
      severity: critical
    annotations:
      description: ""
      summary: xxxxxx

  - alert: group1_rule2
    expr: xxxxxx
    for: 10m
    labels:
      severity: critical
    annotations:
      description: ""
      summary: xxxxxx
```
