### ISSUE TITLE
Prometheus does not reload certificates on config reload

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#4155]
## Proposal

When rolling out now SSL private keys or keychain, a SIGHUP in not enough to make Prometheus rename the new ones.

## Bug Report
**What did you do?**

Change private key or key chain and SIGHUP prometheus

**What did you expect to see?**

Prometheus updates private key/keychain

**What did you see instead? Under which circumstances?**

Prometheus uses the old keys/keychain

* Prometheus version:

	2.2.1

**Comment by brian-brazil** [comment]
Would you mind checking this on master? The code has changed recently.

**Comment by roidelapluie** [comment]
I can not reproduce this

**Comment by roidelapluie** [comment]
(even in 2.0.0 and 2.2.1). I dont know what happened

**Comment by brian-brazil** [comment]
Thanks for the followup.

**Comment by roidelapluie** [comment]
This is driving me crazy.

- It works on my machine
- It does not work on my 2 prod prometheus servers

**Comment by brian-brazil** [comment]
Could you be bind mounting files rather than directories?

**Comment by roidelapluie** [comment]
Nope, here it is:

When the target is in a static_config in the prometheus.yml, SIGHUP is sufficient.

When the target is in a file_sd config, then restart is needed.

**Comment by roidelapluie** [comment]
Now I will try with 2.3.0

**Comment by roidelapluie** [comment]
Still the case.

It looks like we do not re-read the certificates when there is just file_sd in the job. When I add  a static_config and a file_sd, certificate is reloaded.

**Comment by roidelapluie** [comment]
@brian-brazil Could you be bind mounting files rather than directories?

What do you mean?

**Comment by roidelapluie** [comment]
Screenshot: One job with sd_file and one with sd_static.

sd_static reloaded the cert, sd_file did not. The target and CA is the same.

![foo](https://user-images.githubusercontent.com/291750/41470731-ce2993ae-70b1-11e8-9f39-63c233391ce5.png)

**Comment by brian-brazil** [comment]
No, you want to bind mount directories. Bind mounts are tied to inodes, so if you replace the file with a new one any bind mounts won't get updated.

**Comment by roidelapluie** [comment]
well we do not bind anything.

**Comment by brian-brazil** [comment]
When you are changing the files, are you changing the filenames in the config file - or just the ca/keys on disk but with the same filenames?

**Comment by roidelapluie** [comment]
We have that either when we change the CA **OR** when we change the CA _and_ add a new target.

**Comment by roidelapluie** [comment]
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scheme: https
    tls_config:
      cert_file: cert.pem
      key_file: key.pem
      ca_file: tls/ca.pem
    file_sd_configs:
          - files:
                    - tls_sql-agent_*.yml
```


tls_sql-agent_1.yml
```
- targets:                                                                                                                                
  - 127.0.0.1:9100
```
