### ISSUE TITLE
Active alerts don't take into account templated labels

### ISSUE THREAD

**Issue by FreGalle** [prometheus/prometheus#4169]
## Bug Report
**What did you do?**

I'm using the following alert, note the dynamic `severity` label:

```
- alert: DiskUsageHigh
    expr: (1 - node_filesystem_avail{fstype!="rootfs",mountpoint!="",mountpoint!~"/(run|var).*"} / node_filesystem_size) * 100 > 85
    labels:
      severity: '{{ if gt $value 90.0 }}critical{{ else }}warning{{ end }}'
    annotations:
      summary: 'Disk usage threshold reached'
      description: 'Disk usage of device {{ $labels.device }} on {{ $labels.instance }} (mounted at {{ $labels.mountpoint }}) is at {{ $value|humanize }}%'
```

**What did you expect to see?**

I would expect to see the severity label change as soon as this alert's value reaches 90. It doesn't, which I think can be attributed to the way in which [active alerts are checked and updated](https://github.com/prometheus/prometheus/blob/986674a7902108acb5a863c20496aab03d4f147f/rules/alerting.go#L237-L246).

In addition to the alert's value and annotations, wouldn't it make sense to also replace its labels to account for the possibly dynamic rule labels?

This used to work pre-v2.

**What did you see instead? Under which circumstances?**

The alert kept its `warning` severity label and never escalated to the proper receivers configured to act on `critical` alerts.

**Environment**

* Prometheus version:
```
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```

* Alertmanager version:

```
alertmanager, version 0.14.0 (branch: HEAD, revision: 30af4d051b37ce817ea7e35b56c57a0e2ec9dbb0)
  build user:       root@37b6a49ebba9
  build date:       20180213-08:16:42
  go version:       go1.9.2
```
