### ISSUE TITLE
[v2.2.0-rc.0] Prometheus reporting 171% available disk space

### ISSUE THREAD

**Issue by robertofabrizi** [prometheus/prometheus#4198]
## Bug Report
**What did you do?**
Deployed Prometheus, logged into Grafana, and noticed that the available disk space exceeds 100%

![prombug](https://user-images.githubusercontent.com/6720929/40605404-91c99fd8-6262-11e8-98ac-932fbf25dad4.PNG)

**What did you expect to see?**
A value lower or at most equal to 100%

**What did you see instead? Under which circumstances?**
171%, every time

**Environment**
CentOS 7.4, latest Docker version.

* System information:

Linux 3.10.0-693.11.6.el7.x86_64 x86_64

* Prometheus version:

v2.2.0-rc.0

* Alertmanager version:

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.dockerd-exporter'
      type: 'A'
      port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100
```

* Alertmanager configuration file:

* Logs:
