### ISSUE TITLE
scraping should not be effected when reloading Prometheus without change any config

### ISSUE THREAD

**Issue by codwu** [prometheus/prometheus#4214]
## Bug Report
**What did you do?**

reload Prometheus without change any config
```
curl -X POST http://localhost:9090/-/reload
```

**What did you expect to see?**
there is no effect on target scraping

**What did you see instead? Under which circumstances?**
scrape interval become longer than I configured
![default](https://user-images.githubusercontent.com/12193868/40949508-f62e969c-68a0-11e8-9139-1346579bd3f2.PNG)

**Environment**

* System information:

```
Linux 3.10.0-229.el7.x86_64 x86_64
```

* Prometheus version:

```
prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10
```

* Prometheus configuration file:
```

global:
  scrape_interval:     30s 
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

rule_files:

scrape_configs:
  - job_name: 'prometheus1'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus2'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'prometheus3'
    static_configs:
      - targets: ['localhost:9090']

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2018-06-05T01:10:15.681143246Z caller=main.go:220 msg="Starting Prometheus" version="(version=2.2.1, branch=HEAD, revision=bc6058c81272a8d938c05e75607371284236aadc)"
level=info ts=2018-06-05T01:10:15.681218089Z caller=main.go:221 build_context="(go=go1.10, user=root@149e5b3f0829, date=20180314-14:15:45)"
level=info ts=2018-06-05T01:10:15.681243105Z caller=main.go:222 host_details="(Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 centos7b (none))"
level=info ts=2018-06-05T01:10:15.681261809Z caller=main.go:223 fd_limits="(soft=1024, hard=4096)"
level=info ts=2018-06-05T01:10:15.683833415Z caller=main.go:504 msg="Starting TSDB ..."
level=info ts=2018-06-05T01:10:15.684348421Z caller=web.go:382 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-06-05T01:10:15.688001338Z caller=main.go:514 msg="TSDB started"
level=info ts=2018-06-05T01:10:15.688036386Z caller=main.go:588 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-06-05T01:10:15.689628626Z caller=main.go:491 msg="Server is ready to receive web requests."
level=info ts=2018-06-05T01:13:01.657278126Z caller=main.go:588 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-06-05T01:13:34.633327981Z caller=main.go:588 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-06-05T01:14:02.592713121Z caller=main.go:588 msg="Loading configuration file" filename=prometheus.yml
level=info ts=2018-06-05T01:14:23.356799561Z caller=main.go:588 msg="Loading configuration file" filename=prometheus.yml

```
