### ISSUE TITLE
Timezone function

### ISSUE THREAD

**Issue by allangood** [prometheus/prometheus#4227]
## Proposal
A function to return the current timezone offset value (-3, -4, +6, so on) on the Prometheus server.

I'm trying to implement something similar as posted here: https://www.robustperception.io/combining-alert-conditions/

The main idea is to be notified about non critical (warning) alerts only during work hours. Same way many others monitoring/alert systems do (Nagios, Zabbix, etc).

Using the **hours()** function is the closest way to archive this feature, but the lack of the timezone offset information (and mainly the daylight savings information) make it very difficult, since I need to manually change the rule every time the daylight saving begins or it ends.

Using the same example of the blog, but with the "timezoneoffset()" value this problem can be solved:
```
groups:
- name: test.rules
  rules:
  - alert: LatencyTooHigh
    expr: job:request_latency_seconds:mean5m{job="myjob"} > 0.5 and ON() ( hour() + timezoneoffset() ) > 9 < 17
```

## Bug Report
Accordingly to https://prometheus.io/docs/prometheus/latest/querying/functions/
There is no timezone offset information available.

**What did you expect to see?**
Timezone offset information

**What did you see instead? Under which circumstances?**
No timezone offset information

**Environment**
All

* System information:

All

* Prometheus version:

All
