### ISSUE TITLE
Gaps in recording rules series, but data is available when querying the rule expression

### ISSUE THREAD

**Issue by dannyk81** [prometheus/prometheus#4229]
## Bug Report
**What did you do?**

Defined a Recording Rule:
```
record: namespace_node_pod:container_cpu_usage_seconds_total:sum_rate2m
expr: sum
  by(job, namespace, kubernetes_io_hostname, pod_name) (rate(container_cpu_system_seconds_total{image!="",job="kubernetes-nodes",name=~"^(?:^k8s_.*)$"}[2m])
  + rate(container_cpu_user_seconds_total{image!="",job="kubernetes-nodes",name=~"^(?:^k8s_.*)$"}[2m]))
```

**What did you expect to see?**

Expected to see continuous graphs from the recording rule, in the same way as I see when querying the underlying expression directly.

**What did you see instead? Under which circumstances?**

Instead I see mostly gaps with no data on some series of the recording rule (I did find that all the gaps are for series of a specific `kubernetes_io_hostname`) but when querying the record expression above for the same data I get the results and there are no gaps.

1) Result from querying the recording rule
Query: 
```
namespace_node_pod:container_cpu_usage_seconds_total:sum_rate2m{pod_name="mcrouter-856429244-zkcl2"}
```
![image](https://user-images.githubusercontent.com/24274156/41045853-427ba3ba-6977-11e8-8455-71f314e95955.png)

2) Result from querying the recording rule expression directly (using same `pod_name` label selection)
Query: 
```
sum
  by(job, namespace, kubernetes_io_hostname, pod_name) (rate(container_cpu_system_seconds_total{image!="",job="kubernetes-nodes",name=~"^(?:^k8s_.*)$",pod_name="mcrouter-856429244-zkcl2"}[2m])
  + rate(container_cpu_user_seconds_total{image!="",job="kubernetes-nodes",name=~"^(?:^k8s_.*)$",pod_name="mcrouter-856429244-zkcl2"}[2m]))
```
![image](https://user-images.githubusercontent.com/24274156/41045975-7ff14894-6977-11e8-9f12-585ad0d4bf8e.png)

**Environment**

* System information:

	`Linux 4.14.32-coreos x86_64`

* Prometheus version:

```
	prometheus, version 2.2.1 (branch: HEAD, revision: 		bc6058c81272a8d938c05e75607371284236aadc)
  		build user:       root@149e5b3f0829
  		build date:       20180314-14:15:45
  		go version:       go1.10
```

* Alertmanager version:

	`N/A`

* Prometheus configuration file:

I pasted below the `kubernetes-nodes` job configuration (as seen in the Prometheus UI), as this is where these metrics are coming from.
```
- job_name: kubernetes-nodes
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  kubernetes_sd_configs:
  - api_server: null
    role: node
    namespaces:
      names: []
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_node_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_node_name]
    separator: ;
    regex: (.+)
    target_label: instance
    replacement: ${1}
    action: replace
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: container_tasks_state|container_memory_failures_total|container_last_seen|container_fs_.*|container_spec_.*
    replacement: $1
    action: drop
```

* Alertmanager configuration file:
```
N/A
```

* Logs:

I reviewed the logs we have from Prometheus over the last few days and there was nothing except the occasional `WAL truncation completed`, `head GC completed` and `compact blocks` msgs, like so:

```
June 6th 2018, 11:00:43.080 | level=info ts=2018-06-06T15:00:43.080034702Z caller=head.go:357 component=tsdb msg="WAL truncation completed" duration=4.93668698s

June 6th 2018, 11:00:38.143 | level=info ts=2018-06-06T15:00:38.143190144Z caller=head.go:348 component=tsdb msg="head GC completed" duration=1.796350616s

June 6th 2018, 11:00:00.127 | level=info ts=2018-06-06T15:00:00.127434106Z caller=compact.go:393 component=tsdb msg="compact blocks" count=1 mint=1528286400000 maxt=1528293600000
```
