### ISSUE TITLE
Prometheus does not respect scheme config for the alertmanger.

### ISSUE THREAD

**Issue by liquidgecka** [prometheus/prometheus#4252]
Using the following config:

```
alerting:
  alertmanagers:
    - scheme: https
    - basic_auth:
        username: "user"
        password: "pass"
    - static_configs:
      - targets: ["alertmanager.example.com"]
```

I see the following logs:

```
Jun 11 16:03:13 prometheus.aws-us-west-2 prometheus[1782]: level=error ts=2018-06-11T16:03:13.619243596Z caller=notifier.go:473 component=notifier alertmanager=http://alertmanager.example.com/api/v1/alerts count=0 msg="Error sending alert" err="bad response status 400 Bad Request"
```

Note that https is not respected when generating the alertmanager URL. This is on prometheus 2.3.0 (as well as 2.2.1) running on Ubuntu 16.04 LTS `Linux 4.4.0-1031-aws x86_64`
