### ISSUE TITLE
2.3.0 # Optional namespace discovery, only picking up the last namespace in yaml array.

### ISSUE THREAD

**Issue by Misterhex** [prometheus/prometheus#4269]
## Bug Report
Upgraded from 2.2.1 to 2.3.0

**What did you expect to see?**
Optional namespace discovery still continue to pick up all namespaces provided.

**What did you see instead? Under which circumstances?**
Optional namespace discovery only seems to pick up the last namespace in namespace arrays.

```
- job_name: 'kubernetes-service-endpoints'
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
      - logging
```

**Environment**
Prometheus v2.3.0
