### ISSUE TITLE
Prometheus configuration reloads slowly

### ISSUE THREAD

**Issue by lyonssp** [prometheus/prometheus#4301]
## Bug Report
I'm reloading Prometheus configurations through a continuous deployment process using ansible.  I'm finding that configurations take such a long time to reload that what seem like sensible timeout thresholds are consistently passed by the reload process.  

What are some factors that could be causing the significant reload times?

**What did you do?**
`curl -X POST localhost:9090/-/reload`

**What did you expect to see?**
Expected Prometheus to reload my configuration in < 90s

**What did you see instead? Under which circumstances?**
Prometheus seems to take ~2.5 minutes to reload the configuration. 

**Environment**

Prometheus is deployed using docker with the configuration mounted from the file system to 
/etc/prometheus/prometheus.yml.  I am loading a new file to the local filesystem and almost immediately triggering a reload of the prometheus configuration via lifecycle APIs.

Containers aren't rebooted frequently.

* System information:
Linux 4.4.0-1057-aws x86_64

* Prometheus version:

prometheus, version 2.2.1
  build date:       20180314-14:15:45
  go version:       go1.10

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 30s

alerting:
  alertmanagers:
  - file_sd_configs:
    - files:
      - /etc/prometheus/alertmanagers.yml

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: us-east-1 
      port: 9100
      access_key: <redacted>
      secret_key: <redacted>
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: <redacted>
      port: 9100
      access_key: <redacted>
      secret_key: <redacted>
     relabel_configs: <redacted>

  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: <redacted>
      port: 9100
      access_key: <redacted>
      secret_key: <redacted>
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: <redacted>
      port: 9090
      access_key: <redacted>
      secret_key: <redacted>
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: <redacted>
      port: 9090
      access_key: <redacted>
      secret_key: <redacted>
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    ec2_sd_configs:
    - region: <redacted>
      port: 9090
      access_key: <redacted>
      secret_key: <redacted>
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    kubernetes_sd_configs:
    - role: pod
      api_server: <redacted>
    bearer_token: <redacted>
    scheme: https
    relabel_configs: <redacted>
 
  - job_name: '<redacted>'
    kubernetes_sd_configs:
    - role: pod
      api_server: <redacted>
    bearer_token: <redacted>
    scheme: https
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    kubernetes_sd_configs:
    - role: pod
      api_server: <redacted>
    bearer_token: <redacted>
    scheme: https
    relabel_configs: <redacted>

  - job_name: '<redacted>'
    kubernetes_sd_configs:
    - role: pod
      api_server: <redacted>
    bearer_token: <redacted>
    scheme: https
    relabel_configs: <redacted>
 
  - job_name: '<redacted>'
    static_configs:
    - targets: ['<redacted>']

  - job_name: '<redacted>'
    static_configs:
    - targets: ['<redacted>']
```

* Logs:
No relevant logs available
