### ISSUE TITLE
Expose containerPort as __meta label for marathon_sd_config

### ISSUE THREAD

**Issue by bforbis** [prometheus/prometheus#4310]
I would like to build out a `marathon_sd_config` that can scape a Marathon DC/OS cluster for all instances of a particular docker image that I have built and handed off as a tool to other users to deploy themselves within the cluster.

The problem is that this docker image has more than one port, so there is not an easy deterministic way for me to find which port is the port it is serving metrics from. It seems that the recommended way is for users to set a `portDefinitions` or `portMappings` label in their marathon app definition and then prometheus should filter on these labels using `relabel_configs`, however that relies on the users deploying that docker image to follow a standard labeling convention. This means if a user doesn't follow this convention, my discovery will fail to work.

On the other hand, if the app's container port was exposed as a __meta label (which I know is always set to 8080), I could just filter on that information.

```
relabel_configs:
- source_labels: [__meta_marathon_image, __meta_marathon_container_port ]
  regex: myImageName;8080
  action: keep
```
