### ISSUE TITLE
Kubernetes ingress discovery sets invalid scheme

### ISSUE THREAD

**Issue by nailgun** [prometheus/prometheus#4327]
## Bug Report
**What did you do?**
I have a single ingress object with multiple backends. One is https, second is http.

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/path: healthz
  name: web-v1
  namespace: myns
spec:
  rules:
  - host: api.smp.io
    http:
      paths:
      - backend:
          serviceName: web-v1
          servicePort: 80
        path: /apps/v1/
  - host: smp.ingress.svc.cluster.local
    http:
      paths:
      - backend:
          serviceName: web-v1
          servicePort: 80
        path: /apps/v1/
  tls:
  - hosts:
    - api.smp.io
    secretName: api.smp.io-tls
```

**What did you expect to see?**
api.smp.io - httpS
smp.ingress.svc.cluster.local - http

Ingress controller (in my case - nginx) works this way.

**What did you see instead? Under which circumstances?**
Prometheus sets `__meta_kubernetes_ingress_scheme` to https for both backends.

**Environment**

* System information: GKE cluster
* Prometheus version: v2.3.1
* Prometheus configuration file:
```yaml
    # Scrape config for probing ingresses via the Blackbox Exporter
    - job_name: ingress
      kubernetes_sd_configs:
      - role: ingress

      metrics_path: /probe
      params:
        module: [http_2xx]

      scrape_timeout: 30s

      relabel_configs:
      - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_probe]
        action: drop
        regex: false
      - source_labels: [__meta_kubernetes_ingress_path]
        action: drop
        regex: /.well-known/acme-challenge
      - source_labels: [__meta_kubernetes_ingress_scheme, __address__, __meta_kubernetes_ingress_path, __meta_kubernetes_ingress_annotation_prometheus_io_path]
        regex: (.+);(.+);(.+);(.*)
        replacement: ${1}://${2}${3}${4}
        target_label: __param_target
      - source_labels: [__meta_kubernetes_ingress_annotation_prometheus_io_blackbox_module]
        action: replace
        target_label: __param_module
      - target_label: __address__
        replacement: blackbox-exporter
      - source_labels: [__param_target]
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_ingress_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_ingress_name]
        action: replace
        target_label: kubernetes_ingress_name
```

**Resolution**

I found issue here https://github.com/prometheus/prometheus/blob/6eab4bbca1672d9e929f6fc4826c6c658ac076d5/discovery/kubernetes/ingress.go#L179-L194

Actually it should check if `rule.Host` is in one of `ingress.Spec.TLS` configs.

I'm going to send a PR if project maintainer will confirm that this should be fixed. For now I just override `__meta_kubernetes_ingress_scheme` in config:

```yaml
      - source_labels: [__address__]  # fix the bug
        regex: smp.ingress.svc.cluster.local
        replacement: http
        target_label: __meta_kubernetes_ingress_scheme
```
