### ISSUE TITLE
kuernetes_sd_configs kubernetes-nodes server returned HTTP status 403 Forbidden

### ISSUE THREAD

**Issue by xikunyang** [prometheus/prometheus#4379]
I configure prometheus for kubernetes, but I suffer an error on kubernetes-nodes.
![image](https://user-images.githubusercontent.com/36947547/42677308-f31a66a4-86ad-11e8-9f8d-a8753e90c417.png)

My prometheus.yml:

```
- job_name: 'kubernetes-nodes'
    scheme: https
    kubernetes_sd_configs:
    - role: node
      api_server: "https://api_server_ip:6443"
      tls_config:
        ca_file: /opt/prometheus-2.2.1.linux-amd64/kubernetes/ca.crt
      bearer_token_file: /opt/prometheus-2.2.1.linux-amd64/kubernetes/token

    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: api_server_ip:6443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics
```

The rbac clusterrole for prometheus:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "nodes/proxy"]
  verbs: ["get", "watch", "list"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
roleRef:
  kind: ClusterRole
  name: prometheus
  apiGroup: rbac.authorization.k8s.io
```

prometheus.log doesn't show any relate error message.
