### ISSUE TITLE
Grafana and Prometheus doesn't present haproxy result

### ISSUE THREAD

**Issue by rlinux57** [prometheus/prometheus#4429]
Hi,

I am using haproxy_exporter in prometheus and add prometheus as a datasource in grafana and the haproxy plugin using prometheus as a datasource in order to fetch haproxy stats and shown in grafana server. And i am not able to get the output on prometheus as well as grafana `No datapoints found. `. But when i used curl command, It gives me actual output:

`curl http://localhost:9101/metrics`
```
# TYPE haproxy_up gauge
haproxy_up 1
```

**Environment**

* System information:

	`Linux 2.6.32-754.2.1.el6.x86_64 x86_64`

* Prometheus version:

	`prometheus, version 2.3.2`

* Prometheus configuration file:
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
#  - job_name: 'haproxy'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
#    metrics_path: 
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'haproxy'
    static_configs:
      - targets: ['localhost:9101']
        labels:
          instance: haproxy
```
Prometheus gives following log when it is runnning:
* Logs:
```
level=warn ts=2018-07-27T13:03:49.526337583Z caller=scrape.go:948 component="scrape manager" scrape_pool=haproxy target=http://localhost:9101/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=263
```
