### ISSUE TITLE
Azure discovery panics since #4202

### ISSUE THREAD

**Issue by sylr** [prometheus/prometheus#4447]
I ran prometheus:master in my azure based kubernetes cluster to test https://github.com/prometheus/prometheus/pull/4202

Here the error I got:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x895413]

goroutine 126 [running]:
github.com/prometheus/prometheus/discovery/azure.mapFromVM(...)
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:436
github.com/prometheus/prometheus/discovery/azure.(*azureClient).getVMs(0xc428bc2000, 0xc42788b6b0, 0x24, 0xc42788b6e0, 0x24, 0xc42788b650)
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:357 +0x2b3
github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh(0xc426ac2cc0, 0xc427392570, 0x0, 0x0)
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:240 +0x31e
github.com/prometheus/prometheus/discovery/azure.(*Discovery).Run(0xc426ac2cc0, 0x1ebcfa0, 0xc420082fc0, 0xc42368dbc0)
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:134 +0xbb
created by github.com/prometheus/prometheus/discovery.(*Manager).startProvider
        /go/src/github.com/prometheus/prometheus/discovery/manager.go:133 +0x116
```

**Comment by brian-brazil** [comment]
@johscheuer  Could you take a look please.

Can you share the relevant bit of your config please?

**Comment by sylr** [comment]
```yaml
- job_name: azure
  scrape_interval: 30s
  scrape_timeout: 20s
  metrics_path: /metrics
  scheme: http
  azure_sd_configs:
  - port: 9100
    subscription_id: XXXXXXXXXXXXXXXXXXXXXXXX
    tenant_id: XXXXXXXXXXXXXXXXXXXXXXXX
    client_id: XXXXXXXXXXXXXXXXXXXXXXXX
    client_secret: <secret>
    refresh_interval: 5m
  relabel_configs:
  - source_labels: [__meta_azure_machine_tag_prometheus_io_scrape]
    separator: ;
    regex: '[Tt]rue'
    replacement: $1
    action: keep
  - separator: ;
    regex: __meta_azure_(machine_(name|location|resource_group))
    replacement: ${1}
    action: labelmap
```
