### ISSUE TITLE
Promtool 2.3.2 fails if adding sample_limit in "global" section

### ISSUE THREAD

**Issue by identificator1** [prometheus/prometheus#4466]
promtool, version 2.3.2
If to add sample_limit in global section
```
  prometheus.yml:
    global:
      sample_limit: 50000
  - job_name: 'my_job'
...
```
 it fails:
`promtool we get an error: field sample_limit not found in type config.plain`

Running promtheus:
`load configuration (--config.file=/etc/prometheus/prometheus.yml): parsing YAML file /etc/prometheus/prometheus.yml: unknown fields in global config: sample_limit"`

If to add in scrape_configs section in job - works fine.
```
scrape_configs:
 - job_name: 'my_job'
   sample_limit: 5000
```
