### ISSUE TITLE
Support optional ConfigMap volumes for alerting rules

### ISSUE THREAD

**Issue by sl4dy** [prometheus/prometheus#4480]
## Proposal
**Support optional ConfigMap volumes for alerting rules**

We provide ConfigMaps with alerting rules in Helm chart of particular application. However, we need to make Prometheus aware of such ConfigMaps prior to creating the particular Helm chart containing the given ConfigMap. I have tried to mark the ConfigMap volume as optional:

```
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-server-conf
        - name: rules-volume
          configMap:
            name: prometheus-rules
        - name: component-rules-volume
          configMap:
            name: component-rules
            optional: true
```

However Prometheus fails to start:

```
level=error ts=2018-07-25T09:56:53.963527236Z caller=manager.go:479 component="rule manager" msg="loading groups failed" err="read /etc/prometheus-rules/vertica-monitoring-rules.yaml: is a directory" level=error ts=2018-07-25T09:56:53.963723232Z caller=main.go:607 msg="Failed to apply configuration" err="error loading rules, previous rule set restored"
```

It would be great if Prometheus can ignore the file if it is directory - caused by the optional parameter in the volume.
