### ISSUE TITLE
Add hidden labels for outgoing alerts

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#4490]
As part of the alerts metrics relabelling,

I would like to have access to a hidden field

__for

which would be the "for" clause of the alert.

Then I can do:

```
alert_relabel_configs:
- source_labels: [__for]
  target_labels: backlog
```

**Comment by roidelapluie** [comment]
The challenge will be that that __for duration: should it part of the fingerprint of the labelset they correspond to ?

**Comment by roidelapluie** [comment]
some of our notifiers are graphing the alerts and other promql that we pass as annotations; but getting the "for" information once for all the alerts would be a nice shortcut versus needed to ensure that he "for" label is aligned with the "for" duration of the alert. I propose a hidden label by default so that people who have no interest in that are not affected.

**Comment by roidelapluie** [comment]
```
  - alert: Degraded availability
    expr: avg_over_time(probe_success[2m]) < 1
    for: 5m
    labels:
      recipient: circuit
      env: monit
      priority: P1
      alertid: "DCX-002"
      title: Limited Service Availability
    annotations:
      availability_graph_promql: 100*avg_over_time(probe_success{ {{"{{range $k, $v := $labels}}{{$k}}=\"{{$v}}\",{{end}}"}} }[$interval])
      availability_graph_title: Service Availability
      availability_graph_min: 0
      availability_graph_y_label: "%"
      availability_graph_fill: yes
      resp_graph_promql: count_values("code",max_over_time(probe_http_status_code{ {{"{{range $k, $v := $labels}}{{$k}}=\"{{$v}}\",{{end}}"}} }[$interval]))
      resp_graph_title: Return codes
      http_graph_promql: avg_over_time(probe_http_duration_seconds{ {{"{{range $k, $v := $labels}}{{$k}}=\"{{$v}}\",{{end}}"}} }[$interval])
      http_graph_title: HTTP Probe duration/phase
      http_graph_y_label: "seconds"
      http_graph_min: 0
      description: The URL {{"{{ $labels.target}}"}} is not reachable from DCX ({{"{{ $value | humanize }}%"}} available).
      resolved_description: The URL {{"{{ $labels.target}}"}} is now reachable from DCX.
```
