### ISSUE TITLE
Data loss in grafana dashboard on prometheus safe reload

### ISSUE THREAD

**Issue by ijonsnow** [prometheus/prometheus#4519]
## Proposal
**Use case. Why is this important?**
We find data point loss in grafana dashboards and prometheus dashboard after normal reload of the prometheus. 

Note: we did not have this issue in 1.7 or 1.8 prometheus versions.

*Nice to have' is not a good use case :)*

## Bug Report
**What did you do?**
On reloading Prometheus with below approaches. Data loss in Prometheus dashboard / Grafana

> curl -X POST http://localhost:9090/-/reload
> sudo service prometheus reload
> kill -HUP 31763

**What did you expect to see?**
Reload of prometheus with new configs or rules to be reflected.

**What did you see instead? Under which circumstances?**
Data loss point in grafana.

**Environment**
Ubuntu envirnoment 14.04

* System information:
$uname -srm
Linux 3.13.0-135-generic x86_64

* Prometheus version:
prometheus, version 2.1.0 (branch: HEAD, revision: 85f23d82a045d103ea7f3c89a91fba4a93e6367a)
 build user:       root@6e784304d3ff
 build date:       20180119-12:01:23
 go version:       go1.9.2

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
 global:
  scrape_interval:     1m 
  evaluation_interval: 1m 
  external_labels:
    datacenter: node
    metrics: node

rule_files:
 - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: 'ec2-details'
    ec2_sd_configs:
      - region: region
        port: port_number
        refresh_interval: 300s
    relabel_configs:
      - source_labels: [__meta_ec2_tag_env]
        regex: prod
        action: keep
      - source_labels: [__meta_ec2_instance_state]
        regex: running
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_pod]
        target_label: pod
      - source_labels: [__meta_ec2_tag_service]
        target_label: service
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(ALERTS|node_cpu|node_disk_bytes_read|node_disk_bytes_written|node_disk_io_time_ms|node_disk_read_time_ms|node_disk_write_time_ms|node_disk_reads_completed|node_disk_writes_completed|node_filefd_allocated|node_filefd_maximum|node_filesystem_avail|node_filesystem_free|node_filesystem_size|node_load1|node_load15|node_load5|node_memory_Active|node_memory_Buffers|node_memory_Cached|node_memory_Inactive|node_memory_MemFree|node_memory_MemTotal|node_memory_SwapCached|node_memory_SwapFree|node_memory_SwapTotal|node_network_receive_bytes|node_network_receive_drop|node_network_receive_errs|node_network_receive_packets|node_network_transmit_bytes|node_network_transmit_drop|node_network_transmit_errs|node_network_transmit_packets|node_procs_blocked|node_procs_running)'
        action: keep

remote_read:
 - url: "http://influx-endpoint/read"
   remote_timeout: 5m
remote_write:
 - url: "http://influx-endpoint/write"
```

* Alertmanager configuration file:
NA , since its prometheus related query

* Logs:
Am experiencing the weird issue after Prometheus upgrade from 1.7 to 2.1 also tried on 2.3.
Still issue is being experienced.
