### ISSUE TITLE
caller=scrape.go:819 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="appending scrape report failed" err="out of bounds"

### ISSUE THREAD

**Issue by forging2012** [prometheus/prometheus#4601]
## Bug Report

I run Prometheus docker images:
docker run -d --restart=always -p 9090:9090 -v /root/prometheus:/etc/prometheus --network host prom/prometheus

http://192.168.2.201:9090/targets
State is UP. But 
/graph?g0.range_input=1h&g0.expr=go_info&g0.tab=1  ... 
all query is 'no data'.
The logs as follower.

* System information:

```
/bin $ uname -srm
Linux 3.10.0-862.11.6.el7.x86_64 x86_64
```

* Prometheus version:
```
/bin $ ./prometheus --version
prometheus, version 2.4.0 (branch: HEAD, revision: 068eaa5dbfce6c08f3d05d3d3c0bfd96267cfed2)
  build user:       root@d84c15ea5e93
  build date:       20180911-10:46:37
  go version:       go1.10.3
```

* Prometheus configuration file:
```
[root@c1 prometheus]# cat prometheus.yml 
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
# The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
- job_name: 'prometheus'

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  - targets: ['localhost:9090']
```

* Logs:
```

level=warn ts=2018-09-12T14:58:59.219122999Z caller=scrape.go:1059 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=467
level=warn ts=2018-09-12T14:58:59.219187881Z caller=scrape.go:819 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="appending scrape report failed" err="out of bounds"

level=warn ts=2018-09-12T14:59:14.219637321Z caller=scrape.go:1059 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=490
level=warn ts=2018-09-12T14:59:14.220047581Z caller=scrape.go:819 component="scrape manager" scrape_pool=prometheus target=http://localhost:9090/metrics msg="appending scrape report failed" err="out of bounds"



```
