### ISSUE TITLE
scraping metrics from URL requiring basic authentication

### ISSUE THREAD

**Issue by alfonz19** [prometheus/prometheus#4604]
## Bug Report
**What did you do?**
I tried to configure scrape config using metrics resource requiring basic auth

**What did you expect to see?**

working prometheus.

**What did you see instead? Under which circumstances?**

actually nothing. I'd at least expect log message with http 403 or something

**Environment**
linux

* System information:

Linux 4.16.11-100.fc26.x86_64 x86_64

* Prometheus version:

prometheus, version 2.2.1 (branch: HEAD, revision: bc6058c81272a8d938c05e75607371284236aadc)
  build user:       root@149e5b3f0829
  build date:       20180314-14:15:45
  go version:       go1.10

* Alertmanager version:

no idea what alertmanager is and where to find it.

* Prometheus configuration file:
```
...
- job_name: 'spring'
    metrics_path: '/actuator/prometheus'
#    basic_auth:
#      username: 'monitoring'
#      password: 'Eg1zbt83R7'
    static_configs:
      - targets: ['monitoring:Eg1zbt83R7@localhost:8080']
...
```

* Alertmanager configuration file:
```
no idea what alertmanager is and where to find it.
```

* Logs:
```
no idea where prometheus logs are, unable to find them anywhere in system neither their location mentioned in documentation.
```
