### ISSUE TITLE
Prometheus not scraping all subdomains correctly?

### ISSUE THREAD

**Issue by augmenter** [prometheus/prometheus#4646]
Prometheus 2.3.2 (tried 2.4.2 which did not scrape any of the below).

I have 3 identical jobs, all connecting to a working product but a different instance.
See configuration below to see Job settings.
- Job1 works perfectly
- Job2 shows up as 'UP' in the Targets GUI, but data does not show in Graph Gui.
- Job3 is the scrape data from Job3 downloaded by hand and saved to a local server as a .txt file, it works perfectly and the data gets scraped.

Job1 and Job2 both return the same headers on request, and both are HTTPS with a valid certificate. This cant be a format issue in the metric, as job3 is verbatim txt copy of job2, and it works?

Prometheus seems to not scrape subdomains unless they are www. ?
This my only reasoning that I was able to do.

When changing Job1 from www. to bo. subdomain, it stops scraping as well.

## Proposal
This should just work.

* System information:

	Windows 10
* Prometheus version:

	prometheus, version 2.3.2 (branch: HEAD, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       root@5258e0bd9cc1
  build date:       20180712-14:13:08
  go version:       go1.10.3

* Prometheus configuration file:
```
  - job_name: 'job1'
    scheme: https
    static_configs:
      - targets: ['www.example.com']
    metrics_path: '/prom/?txt'  
  - job_name: 'job2'
    scheme: https
    static_configs:
      - targets: ['api.example2.com']
    metrics_path: '/prom/?txt'    
  - job_name: 'job3'
    scheme: http
    static_configs:
      - targets: ['test.ddev']
    metrics_path: '/ca_prom_tmp.txt'     
```
