### ISSUE TITLE
is there a example which include from install prometheus to alertmanager 

### ISSUE THREAD

**Issue by wanghonglei5181** [prometheus/prometheus#4666]

**Comment by c2c-engg-20170100** [comment]
Theses guide include steps to makes prometheus up and running and configure alertmanger
1. Clone the git repository which includes shell script for installing Prometheus, exporters, etc.
i.e. `git clone https://github.com/in4it/prometheus-course.git`
Then in script folder there are scripts.
Run 1-install.sh script by command `./1-install.sh` which installs prometheus, `./2-node-exporter.sh` to add node exporter 
so that we can check the cpu usage of node , `./4-install-alertmanager.sh` to apply alert ,  and `./5-install-mailserver.sh` to fire a mail when cpu usage excceds.
2. Create an alertmanager file in location /etc/alertmanager/alertmanager.yml

```
global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@click2cloud.net'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  repeat_interval: 1h
  receiver: operations-team

receivers:
- name: 'operations-team'
  email_configs:
  - to: 'apurva.dhoble@click2cloud.net'
```

3.Restart alertmanager by running `service alertmanager restart`  and `service alertmanager status` 

4. Apply alerting rules creating /etc/prometheus/alert.rules
groups:

```
groups:
- name: example
  rules:
  - alert: cpuUsage
    expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{job='node_exporter' ,mode="idle"}[5m])) * 100) > 95

    labels:
      severity: critical
    for: 1m
    annotations:
      summary: 'Machine under heavly load'
```

5. Change configuaration in /etc/prometheus/prometheus.yml

```
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

rule_files:
  - "/etc/prometheus/alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.3.141:9100']    # target should be other machine to check cpu usage
```

	  
6. Restart the prometheus by running `service prometheus restart` and `service prometheus status`.
7. Configuration for alertmanager completes here now exceed the cpuusage by running command `yes > /dev/null &`
If you check the cpu usage using top command cpu will excced upto 100%

![image](https://user-images.githubusercontent.com/50102846/60339246-e02a8200-99c5-11e9-8d15-0681ef331b1f.png)

As cpu excceds its level to 100% the email will be fired on the email id mentioned in /etc/alertmanager/alertmanager.yml

![image](https://user-images.githubusercontent.com/50102846/60339283-fa646000-99c5-11e9-80b4-3e4ac3b0e290.png)

 And by executing the query the graph changes after every 1 min

![image](https://user-images.githubusercontent.com/50102846/60339408-4f07db00-99c6-11e9-926e-28315e978ab1.png)
