### ISSUE TITLE
kubernetes  Failed to list *v1.Endpoints: Get https://xxxx:6443/api/v1/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority"

### ISSUE THREAD

**Issue by xiaoxi1989** [prometheus/prometheus#4678]
## Bug Report
**What did you do?**
configuration in outside kubernetes cluster

```yaml
- job_name: 'kubernetes-service-endpoints'

 
  kubernetes_sd_configs:
  - role: endpoints
    api_server: https://xxxx(outside cluster):6443
    tls_config:
      insecure_skip_verify: true
    bearer_token: xxxx
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name
```

**What did you expect to see?**
it can get entpoints info.

**What did you see instead? Under which circumstances?**
```
level=error ts=2018-09-29T12:31:02.230105551Z caller=main.go:234 component=k8s_client_runtime err="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:286: Failed to list *v1.Endpoints: Get https://xxxxxx:6443/api/v1/endpoints?limit=500&resourceVersion=0: x509: certificate signed by unknown authority"
```

**Environment**
* System information:
Darwin 17.3.0 x86_64

* Prometheus version:
prometheus, version 2.4.2 (branch: HEAD, revision: c305ffaa092e94e9d2dbbddf8226c4813b1190a0)
  build user:       root@dcde2b74c858
  build date:       20180921-07:27:12
  go version:       go1.10.3
