### ISSUE TITLE
consul-sd started failing with 2.4.3

### ISSUE THREAD

**Issue by davidkarlsen** [prometheus/prometheus#4703]
## Bug Report
**What did you do?**
Upgrade from v2.4.2 to v2.4.3

**What did you expect to see?**
That consul sd kept on working

**What did you see instead? Under which circumstances?**
The targets found through consul disappeared

**Environment**

* System information:
N/A

* Prometheus version:
v2.4.3

* Prometheus configuration file:
```
 - job_name: 'consul'
    consul_sd_configs:
      - server: 'alp-aot-ccm02.unix.cosng.net:8500'
        datacenter: 'production'
    metric_relabel_configs:
      - source_labels: [container_label_container_group]
        target_label: container_group
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*prom_monitored.*
        action: keep
      - source_labels: [__meta_consul_service]
        target_label: job 
      - source_labels: [__meta_consul_tags]
        regex: .*,alias-([^,]+),.*
        replacement: '${1}'
        target_label: alias
      - source_labels: [__meta_consul_tags]
        regex: .*,metrics_path=([^,]+),.*
        replacement: '${1}'
        target_label: __metrics_path__
      - source_labels: [__meta_consul_tags]
        regex: .*,finodsgroup=([^,]+),.*
        replacement: '${1}'
        target_label: finodsgroup
      - source_labels: [__meta_consul_tags]
        regex: .*,container_group=([^,]+),.*
        replacement: '${1}'
        target_label: container_group
```
