### ISSUE TITLE
Prometheus doesn't appear to actually scrape pushgateway

### ISSUE THREAD

**Issue by sdazzo** [prometheus/prometheus#4709]
## Bug Report
**What did you do?**
We have a set of ephemeral batch jobs that push their metrics to a pushgateway (v0.5.2). The jobs successfully push to the pushgateway and we can see them on the pushgateway gui and when we scrape the endpoint manually (localhost:9091/metrics).

**What did you expect to see?**
We expected prometheus (v2.4.0) to scrape the pushgateway.

**What did you see instead? Under which circumstances?**
Nothing.

**Environment**
Prometheus/alertmanager/pushgateway all on the same host.

* System information:
```
Linux 4.14.67-66.56.amzn1.x86_64 x86_64
```
* Prometheus version:
```
prometheus, version 2.4.0 (branch: HEAD, revision: 068eaa5dbfce6c08f3d05d3d3c0bfd96267cfed2)
  build user:       root@d84c15ea5e93
  build date:       20180911-10:46:37
  go version:       go1.10.3
```
* Pushgateway version:
```
pushgateway, version 0.5.2 (branch: HEAD, revision: 231071b3e0a57b58df717bba5f4e5d88cac95389)
  build user:       root@c95e387ff56a
  build date:       20180615-16:11:56
  go version:       go1.10.3
```
* Prometheus configuration file:
```
global:
  scrape_interval:     60s
  evaluation_interval: 60s

  external_labels:
      monitor: 'prometheus-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
    scheme: http
    timeout: 10s

rule_files:
  - "rules/*"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cloudwatch'
    static_configs:
      - targets: ['localhost:9273']

  - job_name: 'newrelic'
    scrape_timeout: 30s
    static_configs:
      - targets: ['localhost:9126']

  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['localhost:9091']
```

* Logs:
I see no relevant messages or errors in prometheus log with debug on regarding pushgateway or scraping.
