### ISSUE TITLE
How to config alert that can immediately trigger to firing states

### ISSUE THREAD

**Issue by pulord** [prometheus/prometheus#4724]
## Bug Report
**What did you do?**
want config an alert which can immediately trgger and send to alertmanager

**What did you expect to see?**
alretmanager receive alert immediately

**What did you see instead? Under which circumstances?**
sometime works,but Sometimes not works

**Environment**
docker
* Prometheus version:

> root@prometheus-76f4b8668c-28qc6:/# prometheus --version
prometheus, version 2.4.0-rc.0 (branch: master, revision: d075d78bfd5d37cc48ed1e2543dcc615e4b8642b)
  build user:       putaohong@putaohodeMBP719.frontnode.net
  build date:       20180907-06:58:06
  go version:       go1.11

* Alertmanager version:

> root@alertmanager-5664c7dc9c-9xskx:/# alertmanager --version
alertmanager, version 0.15.0-rc.2 (branch: master, revision: 4208663af3850b2ac07d53e6c3152058eb4a815e)
  build user:       root@7964facceeb6
  build date:       20180612-09:21:34
  go version:       go1.9.1

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 30s


# A scrape configuration for running Prometheus on a Kubernetes cluster.
# This uses separate scrape configs for cluster components (i.e. API server, node)
# and services to allow each to use different authentication configs.
#
# Kubernetes labels will be added as Prometheus labels on metrics via the
# `labelmap` relabeling action.
#
# If you are using Kubernetes 1.7.2 or earlier, please take note of the comments
# for the kubernetes-cadvisor job; you will need to edit or remove this job.



alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager.infra:9093"]

rule_files:
  - "/etc/prometheus/alert-rule.yml"
  - "/etc/prometheus/record-rule.yml"

  - job_name: "nginx-exporter"
    scrape_interval: 15s
    honor_labels: true
    static_configs:
      - targets: ['k8s-dev-db.yingmi-inc.com:10201']
```
```
groups:
  - name: Prod-Alerts
    rules:
    - alert: Http-Request-Status-Code-500
      expr: nginx_http_request_status_seconds{status_code="500",interface_name!~".*/check(/)?$"} >= 1
      labels:
        severity: High
        current_value: "{{ $value }}"
        standard_value: "0"
        interface_name: '{{ $labels.interface_name }}'
        group_tag_one: "{{ $labels.interface_name }}"
        service: "{{ $labels.service }}"
        cluster: "{{ $labels.cluster }}"
        http_x_request_id: "{{ $labels.http_x_request_id }}"
        grafana_url: "http://ymon.yingmi-inc.com/d/ElRrXkOiz/error-list?orgId=1"
      annotations:
        summary: "The request status code of {{ $labels.cluster }},{{ $labels.interface_name }} is 500"
        description: "{{ $labels.interface_name }} is 500"
```

* Grafana Query:
```
nginx_http_request_status_seconds{status_code="500",interface_name!~".*/check(/)?$"} >= 1
```
![image](https://user-images.githubusercontent.com/15811706/46786819-97b03300-cd68-11e8-96c3-b31a407ccccc.png)

**I can find promethues stored the metrics，but i can‘t find interrelated alerts for them**
** sometimes its works **
![image](https://user-images.githubusercontent.com/15811706/46787452-34270500-cd6a-11e8-9abc-f9ed681ea688.png)

** Expect **

- How to set an alert than can immediately trigger
- How can slove this problem( sometime works, sometime not works)
