### ISSUE TITLE
dns discovery should expose the resolved name of each record

### ISSUE THREAD

**Issue by depeele** [prometheus/prometheus#4726]
## Proposal
For DNS discovery, when multiple records are returned, currently the `name` entry of each record is ignored, losing information that would be very useful in relabeling.

For example, using a prometheus configuration like:
```yml
scrape_configs:
  - job_name: 'controller'
    dns_sd_configs:
    - names:
      - 'tasks.controller'
      type: 'A'
```

In a setup where a DNS query for A records with the name `tasks.controller` returns:
```
Name:      tasks.controller
Address 1: 192.168.0.1 controller-1
Address 2: 192.168.0.2 controller-2
Address 3: 192.168.0.3 controller-3
```

All metrics for `controller` jobs will be given an `instance` label assigned the value of the IP address, which in many cases is ephemeral (e.g. docker swarm where the next time the service is restarted or scaled, the IP address may change).
Currently, during relabeling, the only information to work with is the IP address and the `__meta_dns_name`, which is set to the name specified for lookup, in this case `tasks.controller`.

If the `name` entry of each record (e.g. `controller-1`, `controller-2`, `controller-3`) were made available as additional metadata during relabeling, perhaps something like `__meta_dns_host`, it would be easy to add relabelling to associate metrics with a particular instance of a service.

```yml
scrape_configs:
  - job_name: 'controller'
    dns_sd_configs:
    - names:
      - 'tasks.controller'
      type: 'A'
    relabel_configs:
      - source_labels: [__meta_dns_host]
        target_label: instance
```

## Changes
This seems like it would be a simple change to the `refresh()` function in `discovery/dns/dns.go`.

Remembering the `addr.Target` for `SRV`, and `addr.Hdr.Name` for `A` and `AAAA` records, a new `__meta_dns_host` entry could be included in the generated `Targets`.
