### ISSUE TITLE
Proposal: A way to determine rule group order for important rule groups

### ISSUE THREAD

**Issue by SpencerMalone** [prometheus/prometheus#4727]
## Proposal
**Use case. Why is this important?**
We have some core rule groups that help define common functionality to be shared between services. This gives us a shared place to have and work with our core common rules. For example: 

All of our web apps use traefik, we can create one set of rules for defining a web application's general availability that takes in a service specification, and each service can define their own alerting level for their specific service. It'd be nice to tweak these core rulesets for everyone involved, but as is, either we have a single very large ruleset for everyone, or accept that sometimes data will be out of order if the rules are loaded in the wrong order, or have rule duplication all over the place.

My yaml example that we do right now and accept that order will be wrong sometimes. Ours is a little more complicated with two or three layers of dependent rules in the general ruleset before we get a service specific definition, but you get the idea:

```
## General Ruleset
# This is incase we swap our LB stack for our apps, we want to be able to keep the old rules without changing a bunch
  - record: web_requests
    expr: traefik_requests_total

  - record: service:slo_errors_per_request:ratio_rate5m
    expr: |
      sum(rate(web_request_errors[5m])) by (service)
      /
      sum(rate(web_requests[5m])) by (service)
```

And then a specific service might say...
```
  - alert: myservice_error_rate
    expr: service:slo_errors_per_request:ratio_rate5m{service="myservice.com/"} > (14.4*0.001)
    labels:
      alertroute: my-route
      severity: production
```
in it's own unique rule group.

My thought is maybe we could do a numerical system on rule groups, with the default being the first run alongside things w/ an order of `1`? Ex:

```
groups:
- name: thishappensfirst.rules
   order: 1
   rules: ...
- name: thishappenssecond.rules
   order: 2
   rules: ...
- name: thishappensfirstbydefault.rules
   rules: ...
```
