### ISSUE TITLE
Expected different result from count()

### ISSUE THREAD

**Issue by codesome** [prometheus/prometheus#4735]
## Bug Report
**What did you do?**
Spin up prometheus (with config at the end). All the targets are down.

```
up{instance="localhost:9100",job="node_exporter",test="tst"} 0
up{instance="localhost:9998",job="dummy2",test="tst"} 0
up{instance="localhost:9999",job="dummy",test="tst"} 0
```

Ran the query `count(up{test=~".*tst.*"} == 1) by (test)`

**What did you expect to see?**
A series/sample with count (value) as 0.

**What did you see instead? Under which circumstances?**
`No data` as output. This happens only when all the `up` series are `0`.
This comes as `nil` in the code, hence any expression including that part becomes `nil` and interferes with alerting too. For example an alerting rule with `count(up{test=~".*tst.*"} == 1) by (test) == 0` would never fire.

* Prometheus version:

	master @ 3e6b9d4 (post 2.4.3)

* Prometheus configuration file:
```
global:
  scrape_interval:     5s
  evaluation_interval: 30s

scrape_configs:
- job_name: node_exporter
  static_configs:
  - targets: ['localhost:9100']
    labels:
      test: tst
- job_name: dummy
  static_configs:
  - targets: ['localhost:9999']
    labels:
      test: tst
- job_name: dummy2
  static_configs:
  - targets: ['localhost:9998']
    labels:
      test: tst
```
