### ISSUE TITLE
Please implement scraping via HTTPS (SSL/TLS)

### ISSUE THREAD

**Issue by stapelberg** [prometheus/prometheus#474]
For a small distributed application that I intend to monitor, we’re using HTTPS (with real certificates, so certificate verification is not an issue) and basic authentication instead of a separate private network, mostly because the setup should stay simple and the application runs on multiple different servers, distributed over the internet.

Therefore, could you please add a configuration option to the `JobConfig` proto message? I’m using SRV record resolving, so I’d like to see e.g. a `schema` key which defaults to `http`, but can be set to `https`.

**Comment by beorn7** [comment]
Makes sense. Thanks for the input.

**Comment by juliusv** [comment]
@stapelberg I guess then you'll also need to be able to configure the username/password for the basic auth, so that the final URL will be something like `<scheme>://<username>:<password>@<SRV host:port>/<metrics path>`?

**Comment by stapelberg** [comment]
Indeed, yes. For now, I’ve just set up a couple of static targets, but being able to specify userinfo and scheme would be great :).

**Comment by juliusv** [comment]
Cool, already started coding it. There are just some remaining code hygiene issues I need to figure out before doing a PR.

**Comment by m13** [comment]
+1
(A document about best security practices should be also amazing)

**Comment by stapelberg** [comment]
From my POV, this issue is done. Prometheus 0.14.0 allows me to use the following config:

```
- job_name: robustirc
  scheme: https
  basic_auth:
    username: 'robustirc'
    password: 'secret'
  dns_sd_configs:
  - names:
    - '_robustirc._tcp.robustirc.net'
  relabel_configs:
  - source_labels: ['__address__']
    regex:         '(.+)\.robustirc\.net:[0-9]+'
    target_label:  'instance'
    replacement:   '$1'
```

**Comment by juliusv** [comment]
Indeed, thanks for pointing that out! Closing this issue.

**Comment by fnkr** [comment]
Here is another example with a static scrape config:

```
# https://prometheus:foo@myservice.example.com/prometheus_exporter
scrape_configs:
  - job_name: My Service
    scrape_interval: 1s
    metrics_path: /prometheus_exporter
    scheme: https
    basic_auth:
      username: prometheus
      password: foo
    static_configs:
      - targets: ['myservice.example.com']
```
