### ISSUE TITLE
High Resource Utilisation on Prometheus

### ISSUE THREAD

**Issue by vaibhavkhurana2018** [prometheus/prometheus#4740]
## Proposal
**Use case. Why is this important?**

The prometheus app is crashing at regular intervals. 

## Bug Report
**What did you do?**
I'm running prometheus inside kubernetes cluster, but the prometheus-app keeps on crashing as the utilisation exceeds the node resources. 

prometheus deployment config:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: null
  generation: 1
  labels:
    name: prometheus-app
  name: prometheus-app
  selfLink: /apis/extensions/v1beta1/namespaces/monitoring/deployments/prometheus-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: prometheus-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: prometheus-app
        restart: 24th-sept
    spec:
      containers:
      - args:
        - --storage.tsdb.retention=120d
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/data
        image: prom/prometheus:v2.4.2
        imagePullPolicy: IfNotPresent
        name: prometheus-app
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus
          name: config-volume
        - mountPath: /data
          name: data-volume
      dnsPolicy: Default
      nodeSelector:
        node-role.kubernetes.io/node-ops: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus-app
      serviceAccountName: prometheus-app
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: prometheus.yml
            path: prometheus.yml
          name: prometheus-app-config
        name: config-volume
      - name: data-volume
        persistentVolumeClaim:
          claimName: prod-prometheus-app-datastore
status: {}
```

**What did you see instead? Under which circumstances?**
The app is crashing at regular intervals. From the grafana dashboard, i can see that the memory and CPU utilisation exceeds to the poing that node goes off OOM. 

NOTE: There is only prometheus pod running on the node. 

**Environment**

* System information:
    v1.8.1+coreos.0 
     Its an EC2 instance(r4.xlarge), with 4vCPU, and 30.5 GiB RAM.

* Prometheus version:

	v4.2.2, docker image: prom/prometheus:v4.2.2

* Prometheus configuration file:

```
# We point this to the statsd-exporter
global:
  scrape_interval: 30s
  external_labels:
    monitor: 'prod-api'
scrape_configs:
  - job_name: statsd-exporter
    scrape_interval: 30s
    honor_labels: true
    scrape_timeout: 25s
    static_configs:
      - targets: ["statsd-exporter.test.vpc:9102"]
  - job_name: statsd-exporter-gateway
    scrape_interval: 30s
    honor_labels: true
    scrape_timeout: 25s
    static_configs:
      - targets: ["statsd-exporter-gw.test.vpc:9102"]
  - job_name: pod-scraper
    kubernetes_sd_configs:
      - role: pod
    # Prometheus collects metrics from pods with "prometheus.app/scrape: true" label.
    # Prometheus gets 'hello_requests_total{status="500"} 1'
    # from hello:8000/metrics and adds "job" and "instance" labels, so it becomes
    # 'hello_requests_total{instance="10.16.0.10:8000",job="hello",status="500"} 1'.
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_app_scrape]
        regex: true
        action: keep
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: k8s_pod
        action: replace
  - job_name: 'prometheus-self'
    scrape_interval: 15s
    static_configs:
        - targets: ['localhost:9090']
```

![screen shot 2018-10-15 at 5 11 38 pm](https://user-images.githubusercontent.com/42436930/46948997-86836100-d09d-11e8-9b0d-db3c5c38eff0.png)

![screen shot 2018-10-15 at 5 11 20 pm](https://user-images.githubusercontent.com/42436930/46948998-871bf780-d09d-11e8-95dc-3409c6e2ffb8.png)

Kindly suggest any solution to limit the utilization/ If i am doing anything wrong in the setup.
