### ISSUE TITLE
Prometheus Alerting on Pods with HTTPS Scheme

### ISSUE THREAD

**Issue by spirrello** [prometheus/prometheus#4741]
## Bug Report
**What did you do?**

Apply a job to monitor pods over HTTP and HTTPS.

**What did you expect to see?**

To be able to monitor pods with HTTP and HTTPS endpoints without alerting when pods are up.

**What did you see instead? Under which circumstances?**

All pods that are using HTTPS for a metric endpoint are in an Up state but are alerting as down as well.

**Environment**

* System information:

uname -srm
Linux 4.4.0-116-generic x86_64

* Prometheus version:

prometheus, version 2.3.2 (branch: HEAD, revision: 71af5e29e815795e9dd14742ee7725682fa14b7b)
  build user:       root@5258e0bd9cc1
  build date:       20180712-14:02:52
  go version:       go1.10.3

* Prometheus configuration file:
```

    - job_name: 'kubernetes-pods'

      kubernetes_sd_configs:
      - role: pod
      tls_config:
        insecure_skip_verify: true

      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (.+)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
```

* Logs:

No logs indicating these pods are down.

Screenshots:

<img width="1416" alt="scrape-down" src="https://user-images.githubusercontent.com/7174260/46966997-38f6fc00-d07d-11e8-8b0b-39eb3fe03b84.png">

<img width="1100" alt="scrape-up" src="https://user-images.githubusercontent.com/7174260/46967041-5926bb00-d07d-11e8-9329-75a8d0ff58b1.png">
