### ISSUE TITLE
[Proposal] Allow to use evaluation_interval for alert FOR calculation

### ISSUE THREAD

**Issue by dmajere** [prometheus/prometheus#4744]
## Allow to use evaluation_interval for alert FOR calculation

It's a common problem to find a right value for alerts **FOR** parameter.
In general you want your alert rule to be evaluated for N evaluation periods, so you have to manually calculate FOR: N * evaluation_interval, which is error prone due to possible changes of a prometheus server that would lead to necessity to change [possibly] every alert rule configuration.
It would be great to have an ability to specify evaluation_interval based evaluation as a value for **FOR**.
For example: 

```
 - alert: AlertName
    expr: job:metric > 0.1
    for: 5 * config:evaluation_interval
    annotations:
      summary: my alert rule
```
