### ISSUE TITLE
unittest does not work with complex expressions

### ISSUE THREAD

**Issue by mbeltre** [prometheus/prometheus#4749]
## Bug Report
**What did you do?**
I have the following rules file:
```
groups:
  - name: test
    rules:
      - alert: TestAlertComplex
        annotations:
          description: Complex alert test
          summary: Really complex expression
        expr: ceil(sum(rate(my_metric_count[5m]))) > 1
        for: 1m
        labels:
          namespace: dev
```

And the following unit test file
```
rule_files:
  - rules.yml

tests:
  - interval: 5m
    input_series:
      - series: my_metric_count
        values: 600
  
    alert_rule_test:
      - eval_time: 5m
        alertname: TestAlertComplex
        exp_alerts: 
          - exp_labels:
              namespace: dev
```

**What did you expect to see?**
I was expecting the `TestAlertComplex` to be triggered in this case.

**What did you see instead? Under which circumstances?**
```
Unit Testing:  alert_tests.yml
    alertname:TestAlertComplex, time:5m0s,
        exp:"[Labels:{alertname=\"TestAlertComplex\", namespace=\"dev\"} Annotations:{}]",
        got:"[]"
```
**Environment**

* System information:
   - Darwin 17.7.0 x86_64

* Prometheus version:

```
prometheus, version  (branch: master, revision: c4a6acf )
  build user:
  build date:
  go version:       go1.11.1```

**Comment by simonpasquier** [comment]
I'm not super familiar with this new feature but I suspect that the problem is because the metric doesn't increase. If I change the input series to this, the alert fires:

```yaml
  - interval: 1m
    input_series:
      - series: my_metric_count
        values: 600 1000 12300 12312312 12313132132
```

cc @codesome
