### ISSUE TITLE
Prometheus cannot start if local host name contains whitespace

### ISSUE THREAD

**Issue by jdickey** [prometheus/prometheus#4773]
## Proposal

It's fairly common on Macs (at least) to have spaces embedded in the host name. During system setup, mine got set as "Jeff's iMac", for example; I've seen this on many other Macs with many other people over the years. I would expect that a significant number of your candidate users are on Macs, at least for development; therefore, as things now stand, they cannot even run the [_Getting Started_](https://prometheus.io/docs/prometheus/latest/getting_started/) tutorial.

I believe it's unreasonable to expect people to change hostnames on systems they've been using, often for years, for the convenience of one software system, no matter how potentially useful.

**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

Nowhere that I saw on the main Prometheus Web page does it indicate that Macs are not supported; indeed, your [_Download_](https://prometheus.io/download/) page includes tarballs for Darwin (Mac), Linux, and Windows. In the absence of documentation indicating otherwise, a reasonable user would expect the basic function of the system to be identical across all three systems. It clearly is not, which is *mind-boggling* for such an apparently mature package.

## Bug Report
**What did you do?**

As laid out in the [_Getting Started_](https://prometheus.io/docs/prometheus/latest/getting_started/) tutorial, I created (and copied) the example `prometheus.yml` file, and then ran

```
/tmp/q % prometheus --config.file=prometheus.yml
parse external URL "": parse http://Jeff's iMac:9090/: invalid character " " in host name
/tmp/q %
```

**What did you expect to see?**

I expected that the Prometheus server would start accepting connections on http://localhost:9090 as described in the tutorial.

**What did you see instead? Under which circumstances?**

The error message quoted above: `parse external URL "": parse http://Jeff's iMac:9090/: invalid character " " in host name`

**Environment**

* System information:

	insert output of `uname -srm` here

	`Darwin 17.7.0 x86_64`

* Prometheus version:

	insert output of `prometheus --version` here

```
	  prometheus, version 2.4.3 (branch: non-git, revision: non-git)
	  build user:       brew@HighSierra-2.local
	  build date:       20181004-10:23:00
	  go version:       go1.11.1
```

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

Not known.

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

No logs separate from error output quoted above found on system.
