### ISSUE TITLE
Panic using Azure service discovery

### ISSUE THREAD

**Issue by mblaschke** [prometheus/prometheus#4779]
## Bug Report
Panic using Azure service discovery

**Environment**

* System information:
Linux 4.15.0-1021-azure x86_64
Docker version 18.06.1-ce, build e68fc7a

* Prometheus version:
image: prom/prometheus:v2.4.3

* Prometheus configuration file:
```
  - job_name: 'azurerm-vm-node'
    scrape_interval: 1m
    azure_sd_configs:
    - subscription_id: aaaaa
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9100
    - subscription_id: bbbbb
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9100
    - subscription_id: ccccc
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9100
    - subscription_id: ddddd
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9100
    relabel_configs:
    - source_labels: [__meta_azure_machine_location]
      target_label: location
    - source_labels: [__meta_azure_machine_name]
      target_label: nodename
    - source_labels: [__meta_azure_machine_os_type]
      target_label: os
    - source_labels: [__meta_azure_machine_resource_group]
      target_label: resourcegroup
    - source_labels: [__meta_azure_machine_tag_owner]
      target_label: team
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/aaaaa/.*"
      target_label: "environment"
      replacement: "aaaaa"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/bbbbb/.*"
      target_label: "environment"
      replacement: "bbbbb"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/ccccc/.*"
      target_label: "environment"
      replacement: "ccccc"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/ddddd/.*"
      target_label: "environment"
      replacement: "ddddd"

  - job_name: 'azurerm-vm-wmi'
    scrape_interval: 1m
    azure_sd_configs:
    - subscription_id: aaaaa
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9182
    - subscription_id: bbbbb
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9182
    - subscription_id: ccccc
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9182
    - subscription_id: ddddd
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9182
    relabel_configs:
    - source_labels: [__meta_azure_machine_location]
      target_label: location
    - source_labels: [__meta_azure_machine_name]
      target_label: nodename
    - source_labels: [__meta_azure_machine_os_type]
      target_label: os
    - source_labels: [__meta_azure_machine_resource_group]
      target_label: resourcegroup
    - source_labels: [__meta_azure_machine_tag_owner]
      target_label: team
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/aaaaa/.*"
      target_label: "environment"
      replacement: "aaaaa"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/bbbbb/.*"
      target_label: "environment"
      replacement: "bbbbb"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/ccccc/.*"
      target_label: "environment"
      replacement: "ccccc"
    - source_labels: [__meta_azure_machine_id]
      regex: "/subscriptions/ddddd/.*"
      target_label: "environment"
      replacement: "ddddd"

```

* Logs:
```
level=info ts=2018-10-24T06:03:43.686740841Z caller=main.go:564 msg="TSDB started"
level=info ts=2018-10-24T06:03:43.686811045Z caller=main.go:624 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-10-24T06:03:43.693751524Z caller=main.go:650 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-10-24T06:03:43.693789126Z caller=main.go:523 msg="Server is ready to receive web requests."
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8e80c8]

goroutine 1615 [running]:
github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh.func2(0xc02106a870, 0xc006b24fc0, 0xc00050a840, 0x3e, 0xc0294336b0, 0xa5, 0xc0206f29f0, 0xc, 0xc022aba340, 0x39, ...)
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:322 +0x588
created by github.com/prometheus/prometheus/discovery/azure.(*Discovery).refresh
        /go/src/github.com/prometheus/prometheus/discovery/azure/azure.go:282 +0x674
```
