### ISSUE TITLE
promtool unittests fail with rate() & time()

### ISSUE THREAD

**Issue by sbueringer** [prometheus/prometheus#4817]
## Bug Report
**What did you do?**

I executed promtool in a dir with the following 2 files:
````
promtool test rules *.test.yaml
````
github.rules
````
groups:
- name: thanos-compact
  rules:
  - alert: ThanosCompactBucketOperationsFailed
    expr: rate(thanos_objstore_bucket_operation_failures_total{app="thanos-compact"}[5m]) > 0.01
    labels:
      severity: warning
      tenant: "{{$labels.tenant}}"
    annotations:
      summary: Thanos Compact bucket operations are failing
      impact: Long term storage queries will be slower and Minio fills up
      action: Check {{ $labels.kubernetes_pod_name }} pod logs in {{ $labels.kubernetes_namespace}} namespace
  - alert: ThanosCompactNotRunIn24Hours
    expr: (time() - max(thanos_objstore_bucket_last_successful_upload_time{app="thanos-compact"}) ) /60/60 > 24
    labels:
      severity: warning
      tenant: "{{$labels.tenant}}"
    annotations:
      summary: Thanos Compaction has not been run in 24 hours
      impact: Long term storage queries will be slower and Minio fills up
      action: Check {{ $labels.kubernetes_pod_name }} pod logs in {{ $labels.kubernetes_namespace}} namespace
````
github.rules.test.yaml
````

rule_files:
- github.rules

tests:

- interval: 1m
  input_series:
  - series: 'thanos_objstore_bucket_operation_failures_total{app="thanos-compact",tenant="i13as",kubernetes_namespace="monitoring",kubernetes_pod_name="thanos-compact-0"}'
    values: '0+0x10 1+1x5'
  - series: 'thanos_objstore_bucket_last_successful_upload_time{app="thanos-compact",tenant="i13as",kubernetes_namespace="monitoring",kubernetes_pod_name="thanos-compact-0"}'
    values: '1531152794+0x20'

  alert_rule_test:
  - alertname: ThanosCompactBucketOperationsFailed
    eval_time: 11m
    exp_alerts:
      - exp_labels:
          severity: warning
          tenant: i13as
          app: thanos-compact
          kubernetes_namespace: monitoring
          kubernetes_pod_name: thanos-compact-0
        exp_annotations:
          action: "Check thanos-compact-0 pod logs in monitoring namespace"
          impact: "Long term storage queries will be slower and Minio fills up"
          summary: "Thanos Compact bucket operations are failing"
  - alertname: ThanosCompactNotRunIn24Hours
    eval_time: 10m
    exp_alerts:
      - exp_labels:
          severity: warning
          tenant: i13as
          app: thanos-compact
          kubernetes_namespace: monitoring
          kubernetes_pod_name: thanos-compact-0
        exp_annotations:
          action: "Check thanos-compact-0 pod logs in monitoring namespace"
          impact: "Long term storage queries will be slower and Minio fills up"
          summary: "Thanos Compact bucket operations are failing"
````

**What did you expect to see?**

I expected the unit test to succeed.

**What did you see instead? Under which circumstances?**

The unit test failed.

**Environment**

Linux Fedora with promtool 2.5.0-rc2

* Logs:
```
Unit Testing:  github.rules.test.yaml
  FAILED:
    alertname:ThanosCompactNotRunIn24Hours, time:10m0s, 
        exp:"[Labels:{alertname=\"ThanosCompactNotRunIn24Hours\", app=\"thanos-compact\", kubernetes_namespace=\"monitoring\", kubernetes_pod_name=\"thanos-compact-0\", severity=\"warning\", tenant=\"i13as\"} Annotations:{action=\"Check thanos-compact-0 pod logs in monitoring namespace\", impact=\"Long term storage queries will be slower and Minio fills up\", summary=\"Thanos Compact bucket operations are failing\"}]", 
        got:"[]"
    alertname:ThanosCompactBucketOperationsFailed, time:11m0s, 
        exp:"[Labels:{alertname=\"ThanosCompactBucketOperationsFailed\", app=\"thanos-compact\", kubernetes_namespace=\"monitoring\", kubernetes_pod_name=\"thanos-compact-0\", severity=\"warning\", tenant=\"i13as\"} Annotations:{action=\"Check thanos-compact-0 pod logs in monitoring namespace\", impact=\"Long term storage queries will be slower and Minio fills up\", summary=\"Thanos Compact bucket operations are failing\"}]", 
        got:"[]"
```

**Comment by johannesfrey** [comment]
Just to verify that `rate` is correctly evaluated in the unit tests I used following values:
```
  - series: 'thanos_objstore_bucket_operation_failures_total{app="thanos-compact",tenant="c01p005",kubernetes_namespace="monitoring",kubernetes_pod_name="thanos-compact-0"}'
    values: '0+1x10'
```
So the initial values seem to be wrong, in order to trigger the alert.

**Comment by sbueringer** [comment]
What kind of information is needed?

**Comment by sbueringer** [comment]
@simonpasquier I retested it with promtool 2.7.2. The first test (ThanosCompactBucketOperationsFailed) now works. The second one for the Alert ThanosCompactNotRunIn24Hours still doesn't work. I'm not sure what more information you need?

I expected the the time() function to resolve to some value during the unit test and then the rule should lead to an alert and a successful test.

**Comment by codesome** [comment]
I will take a look at it in the coming few days, not sure how I missed it.

**Comment by karlem** [comment]
I have the same issue. `time()` function does not actually returns the actual time during test.
Is there any update on this issue?

**Comment by SleepyBrett** [comment]
I'm getting what looks like a similar issue in promtool 

```
promtool, version 2.11.1 (branch: master, revision: d77f2aa29ccf5dbab92e36311d207e4e6c80a19f)
  build user:       u01f@M00972942.nordstrom.net
  build date:       20190716-19:54:21
  go version:       go1.12.6
```

rules.yaml
```
groups:
  - name: test
    rules:
      - alert: etcd_Test
        expr: (etcd_disk_wal_fsync_duration_seconds_bucket) > 0
        labels:
          severity: "warning"
          team: "platform"
        annotations:
          summary: "fired"
          description: "{{ $labels.instance }} {{ $labels.le }} - {{ $value }}"
      - alert: etcd_TestRate
        expr: rate(etcd_disk_wal_fsync_duration_seconds_bucket[1m]) > 0
        labels:
          severity: "warning"
          team: "platform"
        annotations:
          summary: "fired"
          description: "{{ $labels.instance }} {{ $labels.le }} - {{ $value }}"
```

test.yaml
```
rule_files:
  - rules.yaml

evaluation_interval: 10m

tests:
  - interval: 15s
    input_series:
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.001", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.002", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.004", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.008", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.016", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.032", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.064", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.128", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.256", instance="172.16.194.33"}'
        values: '0+0x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="0.512", instance="172.16.194.33"}'
        values: '100+5x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="1.024", instance="172.16.194.33"}'
        values: '200+5x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="2.048", instance="172.16.194.33"}'
        values: '300+5x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="4.096", instance="172.16.194.33"}'
        values: '400+5x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="8.192", instance="172.16.194.33"}'
        values: '500+5x40'
      - series: 'etcd_disk_wal_fsync_duration_seconds_bucket{le="+inf", instance="172.16.194.33"}'
        values: '600+5x40'
    alert_rule_test:
      - eval_time: 8m
        alertname: etcd_Test
        exp_alerts:
          - exp_labels:
              severity: warning
              team: platform
              status: true
            exp_annotations:
              summary: "fired"
              description: "{{ $labels.instance }} {{ $labels.le }} - {{ $value }}"
      - eval_time: 8m
        alertname: etcd_TestRate
        exp_alerts:
          - exp_labels:
              severity: warning
              team: platform
              status: true
            exp_annotations:
              summary: "fired"
              description: "{{ $labels.instance }} {{ $labels.le }} - {{ $value }}"
```
