### ISSUE TITLE
promtool test rules: off-by-one bug for functions applied to range vectors

### ISSUE THREAD

**Issue by bititanb** [prometheus/prometheus#4874]
## Bug Report
**What did you do?**

`promtool test rules test.yml`

**What did you expect to see?**

```
    FAILED   # our alerts shouldn't trigger
```

**What did you see instead?**

```
    SUCCESS
```

**Under which circumstances?**

```yaml
alerts.yml:

  - alert: SumOfInstanceStatusesOver1m
    expr: sum_over_time(up[1m]) == 2    # in prom expression browser this evaluates to 1

  - alert: SumOfInstanceStatusesOver2m
    expr: sum_over_time(up[2m]) == 3    # and this evaluates to 2 for '1 1 1' series
```
```yaml
test.yml:

          - series: 'up{job="node_exporter", instance="localhost:9100"}'
            values: '1+0x6 0 0 0 0 0 0 0 0' # 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0

          - eval_time: 5m
            alertname: SumOfInstanceStatusesOver1m # this shouldn't trigger normally
            exp_alerts:
                - exp_labels:
                      instance: localhost:9100
                      job: node_exporter
          - eval_time: 5m
            alertname: SumOfInstanceStatusesOver2m # this shouldn't too
            exp_alerts:
                - exp_labels:
                      instance: localhost:9100
                      job: node_exporter
```

**Environment**

* System information:

```
Linux 4.15.0-36-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.5.0
(branch: promtool-issue-4838, revision: 30540d48301b9881c8ab66c3c6204f9aee49aa4b)
  build user:       root@prometheus
  build date:       20181116-12:12:49
  go version:       go1.10.4
```

* Promtool version:

```
promtool, version 2.5.0
(branch: promtool-issue-4838, revision: 30540d48301b9881c8ab66c3c6204f9aee49aa4b)
  build user:       root@prometheus
  build date:       20181112-09:53:36
  go version:       go1.10.1
```

* alerts and tests configuration files:

Modified example configs from docs:
https://gist.github.com/bititanb/1164058e966f1faf5b2aa4bdc3454249/revisions

**More:**

Same thing happens at least with `deriv()` function. `deriv(up[1m])` works in tests but in prometheus expression browser it is kind of not a valid expression at all, as it always returns `no datapoints found`. Looks like `deriv(up[1m])` just should be `deriv(up[2m])` and `sum_over_time(up[1m])` should be `sum_over_time(up[2m])` and so forth in tests.

Thanks. /CC @codesome
