### ISSUE TITLE
Need a way to treat `params` as a list for scrape definitions

### ISSUE THREAD

**Issue by hehnope** [prometheus/prometheus#4885]
## Proposal
The primary use case is when combining `blackbox_exporter` and `dns_sd_config`; the `__address__`.

Another use case is if you're working with `cloudwatch_exporter` and specifying the `region` via HTTP param. If you have presence in more than one region, then you need a scrape definition for each region; instead, it's just "nicer" to create a list of http `params` that are scraped and treated as a single scrape definition based on the `params`.

## Example
```
  - job_name: 'http-2xx'
    dns_sd_configs:
    - names:
        - "some_endpoint"
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [http_2xx]
```

I initially tried to use:

```
params:
    target: [system1,system2,system3]
```

So, the idea is that:
1. `dns_sd_configs` is used to get the actual endpoint for `blackbox_exporter`.
2. Since you can send `target` to specify the host; then the idea is to just send that as an HTTP param.

I tried to combine both `dns_sd_configs` and `static_configs` but from what I can tell they both use `__address__` and so `dns_sd_config` will end up getting overwritten and vice-versa. So, the idea is that instead to allow a way to "iterate" a param in `params` instead of combing both. Please note, I tried this and it does not work. 

For example, if you use the following static config:
```
  - job_name: 'just-a-test'
    static_configs:
      - targets: ['localhost:33235']
    metrics_path: /probe
    params:
      targets: ['asdf', '123', '456']
```

Setup a nc: `nc -nl 33235` and wait for prometheus to scrape you'll see:
```
# nc -nl 33235
GET /probe?targets=asdf&targets=123&targets=456 HTTP/1.1
Host: localhost:33235
User-Agent: Prometheus/2.4.0
Accept: text/plain;version=0.0.4;q=1,*/*;q=0.1
Accept-Encoding: gzip
X-Prometheus-Scrape-Timeout-Seconds: 30.000000
```

It would be nice to instead have prometheus iterate through the array and treat each one as a single request. Of course, I imagine changing the current functionality may cause breakage; so an alternative would also be ideal.

**Comment by simonpasquier** [comment]
With blackbox_exporter, the service discovery usually discover the endpoints to probe and the address of the exporter is set via relabeling so I don't see the need for this use case. See https://github.com/prometheus/blackbox_exporter#prometheus-configuration. I'm not sure about what is missing for cloudwatch_exoprter either.

**Comment by solvaholic** [comment]
@simonpasquier in [that example](https://github.com/prometheus/blackbox_exporter/tree/1647e37e6c66884f0b981d0b3d63409450811231#prometheus-configuration) we would list the hosts and services we're monitoring under `static_configs` `targets` and specify our scrape target under `relabel_configs`.

<details>

> ```
> scrape_configs:
>   - job_name: 'blackbox'
>     metrics_path: /probe
>     params:
>       module: [http_2xx]  # Look for a HTTP 200 response.
>     static_configs:
>       - targets:
>         - http://prometheus.io    # Target to probe with http.
>         - https://prometheus.io   # Target to probe with https.
>         - http://example.com:8080 # Target to probe with http on port 8080.
>     relabel_configs:
>       - source_labels: [__address__]
>         target_label: __param_target
>       - source_labels: [__param_target]
>         target_label: instance
>       - target_label: __address__
>         replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
> ```

</details>

I'm new to Prometheus. I find that unintuitive and difficult to read: Use `relabel_configs` to specify the actual scrape target and to pass each of the discovered or listed `targets` as a parameter. Nonetheless I think I see why we should do it this way for `blackbox_exporter` and other exporters that have 1:many relations to the hosts or services we're monitoring.

@hehnope can you use [that method](https://github.com/prometheus/blackbox_exporter/tree/1647e37e6c66884f0b981d0b3d63409450811231#prometheus-configuration) to achieve your desired result?:

```
scrape_configs:
- job_name: 'http_2xx'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - asdf
      - 123
      - 456
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:33235  # The exporter's real hostname:port.
```

If not then please explain more about why it won't work for you.
