### ISSUE TITLE
Prometheus should fail if Azure authentication parameters are missing

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#4900]
Follow up of #4590

Prometheus starts with the following configuration snippet but the Azure SD mechanism will fail to run (log: `"Unable to refresh during Azure discovery" err="could not create Azure client: parameter 'clientID' cannot be empty"`). It would be better for Prometheus to fail hard.

```yaml
- job: azure
  azure_sd_configs:
  - subscription_id: xxx
```
