### ISSUE TITLE
Scrape target returns Empty body/Content-Lenght: 0, but no target error is raised

### ISSUE THREAD

**Issue by zstyblik** [prometheus/prometheus#4937]
## Proposal

Prometheus should raise/show error for targets which return either empty body or `Content-Lenght: 0`. Such condition doesn't seem like a valid state to me. Also, it'd help to identify targets which don't produce metrics for one reason or another(I guess counter to this is "add alert rule which is going to check whether metrics X is present").
 
I remember I had to deal with validation error due to missing `\n` at the end of metrics list, but that seems to be gone now. Could it be regression? Could it be a new bug? It could be a new 

## Bug Report
**What did you do?**

Hooked up Prometheus to consul. However, one of the scrape targets returns 200 OK, empty body and `Content-Lenght: 0` due to bug in the code. However, this is not related to consul as the same can be observed with static targets as well.

**What did you expect to see?**

Scrape target down/scrape error.

**What did you see instead? Under which circumstances?**

Target is being reported as UP, no errors are being show in Web UI.

**Environment**

* System information:

        Linux 3.10.0-862.2.3.el7.x86_64 x86_64

* Prometheus version:

        Observerd at prom/prometheus:v2.4.x and prom/prometheus:v2.5.0

* Prometheus configuration file:
```
---
global:
  scrape_interval: 10s
  evaluation_interval: 1m
  external_labels:
    environment: abc

rule_files:
  - /prometheus/rules/*.yml

scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'file-service-discovery'
  file_sd_configs:
    - files:
      - /prometheus/service-discovery/*.json
      refresh_interval: 1m

- consul_sd_configs:
  - allow_stale: true
    refresh_interval: 30s
    server: 1.2.3.4:8500
    services: [some_service]
  job_name: some_service
```
