### ISSUE TITLE
Promtool: label not found when not included in group by clause

### ISSUE THREAD

**Issue by mwalters-workmarket** [prometheus/prometheus#4946]
Minimal example:

rules.yaml:
```
groups:
  - name: MyAlert
    rules:
    - alert: MyAlert
      expr: min(abc) by (service_name) == 0
      for: 1m
      annotations:
        summary: "service {{ $labels.service_name }} on instance {{ $labels.instance }} is unhealthy"
```

test.yaml:
```
rule_files:
  - rules.yaml
evaluation_interval: 1m
tests:
  - interval: 1m
    input_series:
      - series: 'abc{service_name="service_one", instance="localhost:9090"}'
        values: '0+0x1'
    alert_rule_test:
      - alertname: MyAlert
        eval_time: 1m
        exp_alerts:
          - exp_labels:
              service_name: "service_one"
            exp_annotations:
              summary: "service service_one on instance localhost:9090 is unhealthy"
```

when I execute `promtool test rules test.yaml`
I expect to see output:

```
Unit Testing: test.yaml
  SUCCESS
```

But the actual output is:
```
Unit Testing:  test.yaml
  FAILED:
    alertname:MyAlert, time:1m0s, 
        exp:"[Labels:{alertname=\"MyAlert\", service_name=\"service_one\"} Annotations:{summary=\"service service_one on instance localhost:9090 is unhealthy\"}]", 
        got:"[Labels:{alertname=\"MyAlert\", service_name=\"service_one\"} Annotations:{summary=\"service service_one on instance  is unhealthy\"}]"

```

in the annotation.summary, promtool didn't resolve `{{ $labels.instance }}` properly
