### ISSUE TITLE
count() should result in 0 if no timeseries found

### ISSUE THREAD

**Issue by sgeisbacher** [prometheus/prometheus#4982]
## Proposal
**Use case. Why is this important?**
for dynamic metrics, like **node_exporter**s _node_filesystem*_ where for each mountpoint that metrics increase, i use count() in alert-rules like here:
```
count(node_filesystem_avail_bytes{instance="nas.example.com",mountpoint=~"/srv/nas/(backups|files)"}) < 2
```
to get notified when one of them is not mounted anymore.
it works perfectly if one is missing as count() then returns 1 and the rule fires. but it does not fire if both are missing because than count() returns _no data_
the **workaround** is to additionally check with _absent()_ but it's on the one hand annoying to double-check on each rule and on the other hand count should be able to "count" zero timeseries too:
```
count(node_filesystem_avail_bytes{instance="nas.example.com",mountpoint=~"/srv/nas/(backups|files)"}) < 2
 or absent(node_filesystem_avail_bytes{instance="nas.example.com",mountpoint=~"/srv/nas/(backups|files)"})
```

## Bug Report
**What did you do?**
used count(...) in alert rules to get notified on missing metrics
**What did you expect to see?**
count(...) should return 0 if there is no result
**What did you see instead? Under which circumstances?**
count(...) returns _no data_ if there are no metrics and so alert-rule does not fire (rule: count(...) < 2)
* System information:
`Linux 4.14.70-v7+ armv7l`
* Prometheus version:
`prometheus 2.4.2`
* Alertmanager version:
`alertmanager, version 0.15.2`
* Alertmanager configuration file:
```
  - alert: important_nas_mounts_missing
    expr: count(node_filesystem_avail_bytes{instance="nas.example.com",mountpoint=~"/srv/nas/(backups|files)"}) < 2
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: IMPORTANT NAS MOUNTS MISSING
      description: 'backups or files mount on nas.example.com missing'
```
