### ISSUE TITLE
Alert rules parser breaks on valid input

### ISSUE THREAD

**Issue by RichiH** [prometheus/prometheus#5047]
I just broke Prometheus at 35C3 with the following rule:

````
  - alert: APHighAssociations                       
    expr: {__name__=~"AP_Data_radio._Clients"} > 150                                                                                                           
    for: 15m                                        
    labels:                                         
      severity: sev3                                
    annotations:                                    
      summary: "AP {{ $labels.host }} has more than 150 clients"
      description: "AP {{$labels.host}} has had more than 150 clients for 15 minutes."
````

It works when expanding on the regex:
````
  - alert: APHighAssociations
    expr: (AP_Data_radio0_Clients > 150) or (AP_Data_radio1_Clients > 150)
    for: 15m
    labels:
      severity: sev3
    annotations:
      summary: "AP {{ $labels.host }} has more than 150 clients"
      description: "AP {{$labels.host}} has had more than 150 clients for 15 minutes."

````

Verified with 2.6.0
