### ISSUE TITLE
cmd option "-rules.alert.resend-delay" is ignored

### ISSUE THREAD

**Issue by zuzzas** [prometheus/prometheus#5048]
## Bug Report
**What did you do?**

I've set the `--rules.alert.resend-delay=30s` option.

**What did you expect to see?**

I've expected to see alerts POST's going at 30 seconds interval.

**What did you see instead? Under which circumstances?**

Alerts were sent at 1 minute intervals, instead of 30s. When I set it to 29s, they were sent a 30s interval. I guess, it's related to `evaluation_interval`, but I haven't been able to confirm that in source code.

Here are the relevant Wireshark captures at `--rules.alert.resend-delay` set to 30 and 29 seconds respectively:
* http://screenshot.flant.ru/zuzzas/8d/88/8d885506ee859a43473b3ab39d52fcb52cd2756e.png
* http://screenshot.flant.ru/zuzzas/37/92/3792e787e51bf101f4cf838b487faf06e92e3ae2.png

**Environment**

* System information:

	Linux kube-a-1 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Prometheus version:

	Prometheus v2.6.0

* Prometheus configuration file:
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
  external_labels:
    prometheus: kube-prometheus/main
    prometheus_replica: prometheus-main-0
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: prometheus_replica
    replacement: $1
    action: labeldrop
  alertmanagers:
  - kubernetes_sd_configs:
    - api_server: null
      role: endpoints
      namespaces:
        names:
        - kube-prometheus
    scheme: http
    path_prefix: /
    timeout: 10s
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: proxy
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: http
      replacement: $1
      action: keep
```
Everything else is a bit confidential.
