### ISSUE TITLE
cannot find target_goup[s in config.plain

### ISSUE THREAD

**Issue by amiiy** [prometheus/prometheus#5051]
## Proposal
**Use case. Why is this important?**

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I downloaded last version of prometheous from official site and extracted `tar -xvzf ~/Downloads/node_exporter-0.11.0.linux-amd64.tar.gz` then I run node_exporter in background (not in init) and that running ok on port 9100 as default, but after editing prometheus.yml file and adding below sections:
```
scrape_configs:
  - job_name: "node"
    scrape_interval: "15s"
    target_groups:
    - targets: ['localhost:9100']
```
it's throw error and say cannot fine the `target_goups` in type `config.plain`.
my machine is arch linux and updated.

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:
.
* Alertmanager version:

```
prometheus, version 2.6.0 (branch: HEAD, revision: dbd1d58c894775c0788470944b818cc724f550fb)
  build user:       root@bf5760470f13
  build date:       20181217-15:14:46
  go version:       go1.11.3
```
* Prometheus configuration file:
```

# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: "node"
    scrape_interval: "15s"
    target_groups:
    - targets: ['localhost:9100']

```
tail prometheous.log 
```
level=info ts=2018-12-30T08:52:24.25859707Z caller=main.go:466 msg="Stopping scrape manager..."
level=info ts=2018-12-30T08:52:24.258607975Z caller=main.go:440 msg="Notify discovery manager stopped"
level=info ts=2018-12-30T08:52:24.258626726Z caller=web.go:429 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-12-30T08:52:24.259101221Z caller=main.go:426 msg="Scrape discovery manager stopped"
level=info ts=2018-12-30T08:52:24.259715512Z caller=manager.go:664 component="rule manager" msg="Stopping rule manager..."
level=info ts=2018-12-30T08:52:24.259734239Z caller=manager.go:670 component="rule manager" msg="Rule manager stopped"
level=info ts=2018-12-30T08:52:24.260075771Z caller=notifier.go:521 component=notifier msg="Stopping notification manager..."
level=info ts=2018-12-30T08:52:24.260098103Z caller=main.go:615 msg="Notifier manager stopped"
level=info ts=2018-12-30T08:52:24.260112794Z caller=main.go:460 msg="Scrape manager stopped"
level=error ts=2018-12-30T08:52:24.260185854Z caller=main.go:624 err="error loading config from \"prometheus.yml\": couldn't load configuration (--config.file=\"prometheus.yml\"): parsing YAML file prometheus.yml: yaml: unmarshal errors:\n  line 24: field target_groups not found in type config.plain"
```
