### ISSUE TITLE
field kubernetes_sd_configs not found in type config.plain

### ISSUE THREAD

**Issue by quanvuminh** [prometheus/prometheus#5053]
## Bug Report
**What did you do?**

Tried to use Kubernetes SD with Prometheus outside of the K8s cluster
**What did you expect to see?**

It works!

**What did you see instead? Under which circumstances?**

`promtool` failed to parse configuration

**Environment**

* System information:

	Linux 4.9.0-6-amd64 x86_64

* Prometheus version:

	prometheus, version 2.3.2+ds (branch: debian/sid, revision: 2.3.2+ds-1~bpo9+1)
             build user:       pkg-go-maintainers@lists.alioth.debian.org
             build date:       20180805-18:46:45
             go version:       go1.10.3

* Prometheus configuration file:

```
scrape_configs:
- job_name: kubernetes-nodes
  kubernetes_sd_configs:
  - api_server: https://apiserver:6443
    role: node
    tls_config:
      ca_file: "/etc/kubernetes/pki/ca.crt"
      cert_file: "/etc/kubernetes/pki/apiserver-prometheus-client.crt"
      key_file: "/etc/kubernetes/pki/apiserver-prometheus-client.key"
      insecure_skip_verify: true
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: apiserver:6443
  - source_labels:
    - __meta_kubernetes_node_name
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics
  scheme: https
  tls_config:
    ca_file: "/etc/kubernetes/pki/ca.crt"
    cert_file: "/etc/kubernetes/pki/apiserver-prometheus-client.crt"
    key_file: "/etc/kubernetes/pki/apiserver-prometheus-client.key"
    insecure_skip_verify: true
```

* Logs:

```shell
# promtool check config /etc/prometheus/prometheus.yml.k8s
Checking /etc/prometheus/prometheus.yml.k8s
  FAILED: parsing YAML file /etc/prometheus/prometheus.yml.k8s: yaml: unmarshal errors:
  line 3: field kubernetes_sd_configs not found in type config.plain
```
