### ISSUE TITLE
prometheus consul_sd_configs  msg="append failed" err="\"INVALID\" is not a valid start token"

### ISSUE THREAD

**Issue by zjBrian** [prometheus/prometheus#5085]
prometheus version:   prometheus-2.6.0-rc.0.linux-amd64.tar.gz
consul version:  consul_1.4.0_linux_amd64.zip
os  : contos 7

#cat prometheus.yml
```
  - job_name: 'consul-prometheus' 
    consul_sd_configs:
      - server: '10.252.252.107:8500'
        services: []
```

error logs:
level=warn ts=2019-01-09T03:21:21.305552906Z caller=scrape.go:835 component="scrape manager" scrape_pool=consul-prometheus target=http://10.252.252.102:9999/metrics msg="append failed" err="\"INVALID\" is not a valid start token"

picture:
![image](https://user-images.githubusercontent.com/46511222/50874931-00a75580-1401-11e9-9257-69bdcaaed467.png)

How can I solve this problem!!!
