### ISSUE TITLE
scrape target not honoring https scheme

### ISSUE THREAD

**Issue by ev1lm0nk3y** [prometheus/prometheus#5108]
## Bug Report
**What did you do?**
Attempt to scrape a Kubernetes API endpoint using scheme `https` and a `bearer_token`. 

**What did you expect to see?**
A successful scrape over https, like `https://<api_endpoint_ip_address>:443/...`, not `http://<api_endpoint_ip_address>:443/...`

**What did you see instead? Under which circumstances?**
A scrape error for the `airflow-metrics` target, while the `federated_prometheus` target has no problems.
```
Get http://<api_endpoint_ip_address>:443/api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```
curl commands to validate the issue
Works:
```
curl -k https://<api_endpoint_ip_address>:443/api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics/ -H "Authorization: Bearer ${TOKEN}"
```

Doesn't Work:
```
$ curl -k http://<api_endpoint_ip_address>:443/api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics/ -H "Authorization: Bearer ${TOKEN}"

curl: (56) Recv failure: Connection reset by peer
```

**Environment**

* System information:
for local testing `Darwin 17.7.0 x86_64`
usually I'm running prometheus in a GKE cluster running node and master versions 1.11.5

* Scrape Target GKE master version:
airflow cluster: 1.9.7
federated GKE cluster: 1.11.5

* Prometheus version:
v2.4.0 on the GKE cluster
v2.6.1 locally

* Prometheus configuration file:
This is a sample configuration that I'm running locally that shows the 2 different scrape targets with similar configurations. The same error is seen both locally and in GKE.
```
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
- job_name: airflow-metrics
  honor_labels: true
  metrics_path: /api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics
  scheme: https
  params:
    match[]:
      - '{__name__=~"airflow.*"}'
  static_configs:
  - targets:
    - <api_endpoint_ip_address>
  bearer_token: <blah>
  tls_config:
    insecure_tls_verify: true
- job_name: federated_prometheus
  honor_labels: true
  static_configs:
    - targets:
      - <gke_api_endpoint_ip>
  scrape_interval: 60s
  scrape_timeout: 60s
  params:
    match[]:
      - '{namespace="default"}'
  metrics_path: /api/v1/namespaces/default/services/prometheus:9090/proxy/federate
  scheme: https
  bearer_token: <blah>
  tls_config:
    insecure_skip_verify: true
```

* Logs:
```
12:06 $ prometheus --log.level=debug 
level=info ts=2019-01-17T17:06:50.679835Z caller=main.go:243 msg="Starting Prometheus" version="(version=2.6.1, branch=non-git, revision=non-git)"
level=info ts=2019-01-17T17:06:50.68023Z caller=main.go:244 build_context="(go=go1.11.4, user=brew@HighSierra-2.local, date=20190116-23:28:29)"
level=info ts=2019-01-17T17:06:50.680255Z caller=main.go:245 host_details=(darwin)
level=info ts=2019-01-17T17:06:50.680276Z caller=main.go:246 fd_limits="(soft=256, hard=unlimited)"
level=info ts=2019-01-17T17:06:50.680294Z caller=main.go:247 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-01-17T17:06:50.680886Z caller=main.go:561 msg="Starting TSDB ..."
level=info ts=2019-01-17T17:06:50.681758Z caller=web.go:429 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-01-17T17:06:51.003115Z caller=main.go:571 msg="TSDB started"
level=info ts=2019-01-17T17:06:51.003168Z caller=main.go:631 msg="Loading configuration file" filename=prometheus.yml
level=debug ts=2019-01-17T17:06:51.00729Z caller=manager.go:213 component="discovery manager scrape" msg="Starting provider" provider=string/0 subs=[airflow-metrics]
level=debug ts=2019-01-17T17:06:51.00772Z caller=manager.go:213 component="discovery manager scrape" msg="Starting provider" provider=string/1 subs=[federated_prometheus]
level=info ts=2019-01-17T17:06:51.007758Z caller=main.go:657 msg="Completed loading of configuration file" filename=prometheus.yml
level=info ts=2019-01-17T17:06:51.007773Z caller=main.go:530 msg="Server is ready to receive web requests."
level=debug ts=2019-01-17T17:06:51.007784Z caller=manager.go:231 component="discovery manager scrape" msg="discoverer channel closed" provider=string/0
level=debug ts=2019-01-17T17:06:51.007835Z caller=manager.go:231 component="discovery manager scrape" msg="discoverer channel closed" provider=string/1
level=debug ts=2019-01-17T17:07:06.926837Z caller=scrape.go:825 component="scrape manager" scrape_pool=airflow-metrics target="https://<api_endpoint_ip_address>:443/api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics?match%5B%5D=%7B__name__%3D~%22airflow.%2A%22%7D" msg="Scrape failed" err="Get http://<api_endpoint_ip_address>:443/api/v1/namespaces/default/services/<service>:8080/proxy/admin/metrics/?match%5B%5D=%7B__name__%3D~%22airflow.%2A%22%7D: net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x15\\x03\\x01\\x00\\x02\\x02\""
^Clevel=warn ts=2019-01-17T17:07:16.21424Z caller=main.go:405 msg="Received SIGTERM, exiting gracefully..."
```
