### ISSUE TITLE
promtool convert alert rules  don't respect the go template

### ISSUE THREAD

**Issue by DreamRivulet** [prometheus/prometheus#5121]
**What did you do?**
I use the promtool to convert old 1.8 version alert rules to new yaml format.  

**What did you expect to see?**
template like `{{ var }}` should not be split into multi-line. 

**What did you see instead? Under which circumstances?**
template `{{ var }}` are split like:
```
..., This is a alert template {{ var 
  }}
```
when string is long.

**Environment**

* System information:

	Linux 4.4.0-130-generic x86_64

* Prometheus version:
```
  promtool, version 2.5.0 (branch: HEAD, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       root@578ab108d0b9
  build date:       20181106-11:40:44
  go version:       go1.11.1

```

**Comment by brian-brazil** [comment]
Does this change the resulting output label?

**Comment by DreamRivulet** [comment]
yes, the alert template will not work when span newlines, see: [go template]( https://golang.org/pkg/text/template/).

**Comment by DreamRivulet** [comment]
It's better that promtool can respect the go template when converting alert rules into yaml format, i see promtool uses https://github.com/go-yaml/yaml to do the marshal, but i didn't find any place which will split the string into multi-lines.

**Comment by simonpasquier** [comment]
Can you share the original alert rule file?

**Comment by DreamRivulet** [comment]
```

## alert.rules ##
  ALERT WorkerFailedAlert
    IF changes(worker_fail_count [300m]) > 3
    LABELS {
      severity = "warning",
      workerID = "{{ $labels.workerID }}",
      alert_key = "This is a test to prove that promtool fails , {{ $labels.workerID }}"
    }
```
Above is a simple old format alert rules, you can use the promtool to convert it, then you will get following output:

```
groups:
- name: test.rules
  rules:
  - alert: WorkerFailedAlert
    expr: changes(worker_fail_count[5h]) > 3
    labels:
      alert_key: This is a test to prove that promtool fails , {{ $labels.workerID
        }}
      severity: warning
      workerID: '{{ $labels.workerID }}'
```
