### ISSUE TITLE
500 Server Error when select series

### ISSUE THREAD

**Issue by yeya24** [prometheus/prometheus#5133]
## Bug Report
**What did you do?**

In the web UI, I search some metrics of prometheus such as prometheus_build_info or some other metrics of prometheus It returns a 500 error.
But when I search the metrics from influxdb(through remote read), I can get the correct metrics.

**What did you expect to see?**

I can see the correct metrics in the console

**What did you see instead? Under which circumstances?**
![_ _20190124152030](https://user-images.githubusercontent.com/25150124/51661413-c8e90200-1feb-11e9-83f8-50b2f2253412.png)

**Environment**

* System information:

Linux 3.10.0-862.14.4.el7.x86_64 x86_64

* Prometheus version:
I tested in prometheus 2.4.0 and prometheus 2.5.0, all met the same problem
* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
remote_read:
  - url: "http://192.168.200.31:8086/api/v1/prom/read?db=stress"
```

* Logs:
```
level=error ts=2019-01-24T06:37:01.016535242Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:02.308943035Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:42.932953428Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:43.200055227Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:43.436832374Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:43.67769608Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:37:43.908430309Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
level=error ts=2019-01-24T06:39:00.73227196Z caller=engine.go:498 component="query engine" msg="error selecting series set" err="server returned HTTP status 500 Internal Server Error"
```
