### ISSUE TITLE
Prometheus generated too many same files when do compaction

### ISSUE THREAD

**Issue by eahydra** [prometheus/prometheus#5137]
## Proposal
**Use case. Why is this important?**
Prometheus generated too many same files when do compaction.

## Bug Report
**What did you do?**
I have got alert  that disk space cost 90%, and found that the prometheus tsdb used too many space.
There are many same files but different parent directory name, and the meta.json have the same text.

**What did you expect to see?**
Don't generate so many same files

**What did you see instead? Under which circumstances?**
Too many same files when compaction.

**Environment**

* System information:

	the internal version but based on CentOS 7

* Prometheus version:
	prometheus, version 2.5.0 (branch: release/20181129-11-33, revision: 67dc912ac8b24f94a1fc478f352d25179c94ab9b)
  build user:       admin@rs7h13559.et2sqa
  build date:       20181129-03:34:17
  go version:       go1.11

* Prometheus configuration file:
```
global:
  scrape_interval:     30s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'inspector'
  scrape_interval: 30s
  scheme: http
  metrics_path: "/metrics"
  static_configs:
      - targets: ["target1:8070", "target2:8070"]

```

* Logs:

Lost the logs
