### ISSUE TITLE
CPU usage skyrocketed after update from 2.3 to 2.6

### ISSUE THREAD

**Issue by rsommer** [prometheus/prometheus#5162]
## Bug Report
Today I updated from prometheus 2.3 to prometheus 2.6. After installation, cpu usage skyrocketed on both nodes (ha-setup).

**What did you expect to see?**
Nearly the same CPU usage as with 2.3

**What did you see instead? Under which circumstances?**
CPU usage increased from 5% to 70%

**Environment**

* System information:

	Linux 4.9.0-8-amd64 x86_64

* Prometheus version:

	prometheus, version 2.6.0+ds (branch: debian/sid, revision: 2.6.0+ds-1)
          build user:       pkg-go-maintainers@lists.alioth.debian.org
          build date:       20181219-15:52:20
          go version:       go1.10.4

* Prometheus configuration file:
```
global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'infrastructure'
      environment: 'production'
      replica: 'prom02'

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
        - targets: ['localhost:9090']

    file_sd_configs:
        - files:
            - '/etc/prometheus/*.json'
          refresh_interval: 1m

  - job_name: 'slow'
    scrape_interval: 1m
    scrape_timeout: 45s
    file_sd_configs:
        - files:
            - '/etc/prometheus/slow/*.json'
          refresh_interval: 1m
```

There are currently 642 targets configured via file_sd.
![node-monitoring](https://user-images.githubusercontent.com/178013/52046647-807b9800-2547-11e9-8dc9-1ca7a08be8e2.png)
