### ISSUE TITLE
prometheus still send alert to alertmanager/api/v1

### ISSUE THREAD

**Issue by ArcherLinXin** [prometheus/prometheus#5167]
log is : caller=notifier.go:481 component=notifier alertmanager=http://*******/api/v1/alerts

**Comment by roidelapluie** [comment]
Alertmanager v2 api is still fairly new and still has a few bugs.

I think it is safer to keep using v1 for the moment

**Comment by simonpasquier** [comment]
For the record you can always set Prometheus to use the v2 api using `relabel_configs` like this:

```yaml
alerting:
  alertmanagers:
    relabel_configs:
      replacement: "/api/v2/alerts"
      target_label: __alerts_path__
   ...
```

As for when/if we switch Prometheus to the v2 API by default, this is a good question...
