### ISSUE TITLE
Rule evaluation failure after reload with newly added rules

### ISSUE THREAD

**Issue by jsravn** [prometheus/prometheus#5193]
## Bug Report
**What did you do?**

1. `docker run -p 9090:9090 prom/prometheus:v2.7.1`
2. Edit `/etc/prometheus/prometheus.yml`, enable the `- "first_rules.yml"` file.
3. Create `/etc/prometheus/first_rules.yml`:
```yaml
groups:       
- name: testgroup
  rules:      
  - record: test            
    expr: 22222         
    labels:             
      instance: my-second
```
4. Reload prometheus - `kill -SIGHUP 1`. Everything is fine.
5. Update `/etc/prometheus/first_rules.yml`:
```yaml
groups:       
- name: testgroup
  rules:      
  - record: test            
    expr: 11111         
    labels:             
      instance: my-first
  - record: test         
    expr: 22222          
    labels:              
      instance: my-second
```
6. Reload prometheus - `kill -SIGHUP 1`.
7. Wait for the next rule evaluation. An error is produced:
```
level=info ts=2019-02-08T10:28:36.906865554Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-02-08T10:28:36.907330758Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=warn ts=2019-02-08T10:28:43.395453805Z caller=manager.go:514 component="rule manager" group=testgroup msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1
```
8. Data for the `instance: my-second` rule is missing at that timestamp.

**What did you expect to see?**

I expected to see no errors, and data for `instance: my-second` at the evaluation time. Although they have the same identifier `test`, they should be unique time series as they have different labels.

**What did you see instead? Under which circumstances?**

Log error, and missing data for the `instance: my-second` rule at the evaluation time.

**More details**

* This only happens when the recording rule identifier matches, and the new rule is prepended before the other ones.
* All the subsequent recording rules with the same identifier fail in the next rule evaluation. After that, they succeed.

**Environment**

docker container

* System information:

```
/prometheus $ uname -srm
Linux 4.20.6-arch1-1-ARCH x86_64
```

* Prometheus version:

```
/prometheus $ prometheus --version
prometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5
```

* Prometheus configuration file:
```
/etc/prometheus $ cat prometheus.yml
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.                             
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.                                     
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.                                  
rule_files:                
- "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:                                                              
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.                                
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

```
/etc/prometheus $ cat first_rules.yml 
groups:
- name: testgroup
  rules:
  - record: test
    expr: 11111
    labels:
      name: my-first
  - record: test
    expr: 22222
    labels:
      name: my-second
```

* Logs:
```
level=info ts=2019-02-08T10:28:36.906865554Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2019-02-08T10:28:36.907330758Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=warn ts=2019-02-08T10:28:43.395453805Z caller=manager.go:514 component="rule manager" group=testgroup msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1  
```

* Logs with debug on:
```
level=info ts=2019-02-08T13:55:49.17010164Z caller=main.go:695 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=debug ts=2019-02-08T13:55:49.171150335Z caller=manager.go:217 component="discovery manager scrape" msg="Starting provider" provider=string/0 subs=[prometheus]
level=debug ts=2019-02-08T13:55:49.171307068Z caller=manager.go:217 component="discovery manager notify" msg="Starting provider" provider=string/0 subs=[defc8654e1f8780ce80f9010266ce592]
level=debug ts=2019-02-08T13:55:49.171393607Z caller=manager.go:235 component="discovery manager scrape" msg="discoverer channel closed" provider=string/0
level=debug ts=2019-02-08T13:55:49.171422194Z caller=manager.go:235 component="discovery manager notify" msg="discoverer channel closed" provider=string/0
level=info ts=2019-02-08T13:55:49.171924503Z caller=main.go:722 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=debug ts=2019-02-08T13:55:53.394962189Z caller=manager.go:502 component="rule manager" group=testgroup msg="Rule evaluation result discarded" err="duplicate sample for timestamp" sample="{__name__=\"test\", instance=\"my-second\"} => 22222 @[1549634153394]"
level=warn ts=2019-02-08T13:55:53.395017411Z caller=manager.go:514 component="rule manager" group=testgroup msg="Error on ingesting results from rule evaluation with different value but same timestamp" numDropped=1
```
