### ISSUE TITLE
Getting error "expected label name, got \"BCLOSE\""

### ISSUE THREAD

**Issue by wraithfive** [prometheus/prometheus#5196]
## Bug Report
I have a spring application that exposes metrics via micrometer. After upgrading to Prometheus 2.7.1 (from a 2.6.x release) when scrapping that application I now get the error "expected label name, got "BCLOSE""

**Environment**

* System information:

	Linux 3.10.0-957.1.3.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5

* Prometheus configuration file:
```
global:
  scrape_interval:     1m  # Set the scrape interval. Default is every 1 minute. Can be specified in seconds.
  evaluation_interval: 1m  # Evaluate rules every 1 minute. The default is every 1 minute. Can be specified in seconds.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'client'
    metrics_path: /service/metrics
    static_configs:
      - targets: ["host.docker.internal:8080"]

```

* Logs:
```
level=warn ts=2019-02-08T21:33:50.763146989Z caller=scrape.go:835 component="scrape manager" scrape_pool=client target=http://host.docker.internal:8080/service/metrics msg="append failed" err="expected label name, got \"BCLOSE\""

```
