### ISSUE TITLE
service discovery by exec

### ISSUE THREAD

**Issue by genofire** [prometheus/prometheus#5212]
## Proposal
It would be nice that prometheus runs itself an application and use the output from stdout.
Instead of running a cronjob or something else to write contains files and fetch them again by custom service discovery like on `file_sd_config`.

### Idea of configuration
It could be very similar to: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#file_sd_config
```yml
scrape_configs:
- job_name: prometheus

  honor_labels: true

  execs_sd_configs:
    - execs:
      - "/opt/sd-mysql.py"
      - "curl https://example.org/prometheus-services.json"
      - "cat single/file.yml"
      refresh_interval: 10m
```

### Transformated example of Blogpost
https://prometheus.io/blog/2015/06/01/advanced-service-discovery/#custom-service-discovery
_(untested)_
```python
import json

from itertools import groupby
from MySQLdb import connect

cur = connect('localhost', 'root', '', 'test')

# Fetch all rows.
cur.execute("SELECT address, job, zone FROM instances")

tgs = []
# Group all instances by their job and zone values.
for key, vals in groupby(cur.fetchall(), key=lambda r: (r[1], r[2])):
  tgs.append({
    'labels': dict(zip(['job', 'zone'], key)),
    'targets': [t[0] for t in vals],
  })

print(json.dump(tgs))
```
