### ISSUE TITLE
'Unhealthy' Targets filter not filtering out all 'Healthy' Targets

### ISSUE THREAD

**Issue by ghost** [prometheus/prometheus#5219]
## Proposal
**Use case. Why is this important?**
When selecting 'Unhealthy' on the Targets Page, Jobs are only hidden if all the Targets within that Job are 'Healthy'. If a Job contains many Targets but only contains one 'Unhealthy' Target, all the 'Healthy' Targets will still be visible. 
It would be more manageable and user friendly, in particular when there are many Targets, to only show the 'Unhealthy' Targets.

This was touched upon in #4319.

I have coded a fix for this, if seen as beneficial, I will submit a Pull Request for review.

## Bug Report
**What did you do?**
Filter the Targets by 'Unhealthy' on the Targets Page.

![all](https://user-images.githubusercontent.com/47104231/52793586-f3b3fc80-3065-11e9-8ee7-fa8b2b5fe75a.png)

**What did you expect to see?**
Only 'Unhealthy' Targets visible (Prometheus job gets hidden).

![hidinghealthy](https://user-images.githubusercontent.com/47104231/52793661-1f36e700-3066-11e9-91f6-a14c8d3de07e.png)

**What did you see instead? Under which circumstances?**
All the other 'Healthy' Targets within a Job that contains 'Unhealthy' Targets (Prometheus job is hidden, but still the 'Healthy' Targets in example-random are visible).

![nothidinghealthy](https://user-images.githubusercontent.com/47104231/52793751-4beafe80-3066-11e9-8b1e-e688e1ee96c0.png)

**Environment**

* System information:
```
Linux 3.10.0-957.5.1.el7.x86_64 x86_64
```
* Prometheus version:
```
prometheus, version 2.7.1 (branch: master, revision: fd964426a77a5fc64db02b2ff5b757045b80be7a)
build date:       20190205-13:26:52
go version:       go1.11.4
```
* Prometheus configuration file:
```

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']


  - job_name: 'example-random'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
        - targets: ['localhost:8080', 'localhost:8081', 'localhost:8082', 'localhost:8083']
          labels:
            group: 'production'

        - targets: ['localhost:8084', 'localhost:8085', 'localhost:8086', 'localhost:8087']
          labels:
            group: 'canary'

```
