### ISSUE TITLE
Record rules results shifted in time 

### ISSUE THREAD

**Issue by alex-k** [prometheus/prometheus#5307]
## Bug Report
**What did you do?**

I have two recording rules

```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s


record: sli:metric:good_events 
expr: sum   by(product, journey, step) (splunk_journey{data="good_events"}) 
labels:   metric: splunk_journey

record: sli:metric:valid_events 
expr: sum   by(product, journey, step) (splunk_journey{data="valid_events"}) 
labels:   metric: splunk_journey


```

**What did you expect to see?**

I expect to see in result same values as in target metrics grouped by labels

**What did you see instead? Under which circumstances?**

Sometimes I see values shifted in time by 15sec

Expected:

![image](https://user-images.githubusercontent.com/1177310/53801334-f3659d80-3f4f-11e9-8773-880798c5b33e.png)

Got:

![image](https://user-images.githubusercontent.com/1177310/53801073-44c15d00-3f4f-11e9-81ba-e08b272b5bcd.png)

**Environment**

Not applicable
* System information:

Not applicable

* Prometheus version:

Version  2.6.1
Revision b639fe140c1f71b2cbad3fc322b17efe60839e7e

* Alertmanager version:

Not applicable

* Prometheus configuration file:

* Alertmanager configuration file:

* Logs:
