### ISSUE TITLE
template function "humanizeNoSmallPrefix" is not recognize with promTool 2.7.1

### ISSUE THREAD

**Issue by Nexucis** [prometheus/prometheus#5357]
## Bug Report
**What did you do?**
I have the following alert rule that use the template function "humanizeNoSmallPrefix"

```yaml
  - alert: AlertExample
    expr: vector(1) == 1
    for: 1m
    annotations:
      description: '{{ $value | humanizeNoSmallPrefix }} > 0 for last minute'
```

And the promTool 2.7.1 says it doesn't know the function `humanizeNoSmallPrefix`. It works using promTool 2.5.0

**What did you expect to see?**
I expected that promTool was ok with this rule

**What did you see instead? Under which circumstances?**
Running promTool 2.7.1, it returns the following error:

```bash
"AlertExample": msg=template: __alert_AlertExample:1: function "humanizeNoSmallPrefix" not defined
```

**Environment**

* System information:

  Testing on :
    * windows
	* Linux

* Prometheus version:
  * 2.7.1
