### ISSUE TITLE
How to configure kubernetes_sd_configs to discover services in a different cluster

### ISSUE THREAD

**Issue by ahmed282828** [prometheus/prometheus#5360]
I created a job in prometheus with kubernetes_sd_configs to discover services automatically without the need to declare them manually(Cadvisor, nodeexporter, KubeStateMetrics). i am using helm chart for prometheus. i tried this job and it can only discover the services in the cluster itself(same cluster with prometheus server installed) but not the other clusters

this is the job that i created. in prometheus the $1 takes the names of the old cluster and the error displayed is  server returned HTTP status 401 Unauthorized

```
-job_name: 'kubernetes-nodes-cadvisor-aks-NEWUATBACK'
scheme: https
tls_config:
  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

  insecure_skip_verify: true
bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

kubernetes_sd_configs:
  - role: node

relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: ks-ba4cf716.hcp.northeurope.azmk8s.io:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

```

anybody has an idea about this ? i really need your help guys  am really struggling with this and i didnt find a solution
