### ISSUE TITLE
Getting many compaction failed with invalid argument error in prometheus server log

### ISSUE THREAD

**Issue by dcvtruong** [prometheus/prometheus#5362]
## Bug Report
**What did you do?**
I notice the many compaction error Prometheus server pod get scheduled over to a different k8s worker node
**What did you expect to see?**
Not so many compaction error in prometheus server log
**What did you see instead? Under which circumstances?**
Repeated compaction error with with invalid argument
**Environment**

* System information:

	Linux 3.10.0-957.1.3.el7.x86_64 x86_64

* Prometheus version:

	2.6.1

* Prometheus configuration file:
```
      global:
        scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
        evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
        # scrape_timeout is set to the global default (10s).

      # Alertmanager configuration
      alerting:
        alertmanagers:
        - static_configs:
          - targets:
            # - alertmanager:9093

      # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
      rule_files:
        # - "first_rules.yml"
        # - "second_rules.yml"

      # A scrape configuration containing exactly one endpoint to scrape:
      # Here it's Prometheus itself.
      scrape_configs:
        # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
        - job_name: 'prometheus'

          # metrics_path defaults to '/metrics'
          # scheme defaults to 'http'.

          static_configs:
          - targets: ['localhost:9090']
```

* Logs:
```
          level=info ts=2019-03-14T01:54:50.533936079Z caller=main.go:243 msg="Starting Prometheus" version="(version=2.6.1, branch=HEAD, revision=b639fe140c1f71b2cbad3fc322b17efe60839e7e)"
          level=info ts=2019-03-14T01:54:50.534059479Z caller=main.go:244 build_context="(go=go1.11.4, user=root@4c0e286fe2b3, date=20190115-19:12:04)"
          level=info ts=2019-03-14T01:54:50.534131879Z caller=main.go:245 host_details="(Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 prometheus-server-844f844bf8-vtdk6 (none))"
          level=info ts=2019-03-14T01:54:50.534159179Z caller=main.go:246 fd_limits="(soft=1048576, hard=1048576)"
          level=info ts=2019-03-14T01:54:50.534194279Z caller=main.go:247 vm_limits="(soft=unlimited, hard=unlimited)"
          level=info ts=2019-03-14T01:54:50.535053582Z caller=main.go:561 msg="Starting TSDB ..."
          level=info ts=2019-03-14T01:54:50.535301382Z caller=web.go:429 component=web msg="Start listening for connections" address=0.0.0.0:9090
          level=info ts=2019-03-14T01:55:16.467744497Z caller=main.go:571 msg="TSDB started"
          level=info ts=2019-03-14T01:55:16.467867997Z caller=main.go:631 msg="Loading configuration file" filename=/etc/config/prometheus.yml
          level=info ts=2019-03-14T01:55:16.471057806Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2019-03-14T01:55:16.47246501Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2019-03-14T01:55:16.473748513Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2019-03-14T01:55:16.474883016Z caller=kubernetes.go:201 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2019-03-14T01:55:16.476965822Z caller=kubernetes.go:201 component="discovery manager notify" discovery=k8s msg="Using pod service account via in-cluster config"
          level=info ts=2019-03-14T01:55:16.479123528Z caller=main.go:657 msg="Completed loading of configuration file" filename=/etc/config/prometheus.yml
          level=info ts=2019-03-14T01:55:16.479218928Z caller=main.go:530 msg="Server is ready to receive web requests."
          level=error ts=2019-03-14T01:55:43.025096323Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYJEEX59YRGA29BPE8WAXY.tmp: invalid argument"
          level=error ts=2019-03-14T01:55:48.766084444Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYK48SCPZCB83G3VV6VSFK.tmp: invalid argument"
          level=error ts=2019-03-14T01:55:49.022951547Z caller=federate.go:184 component=web msg="federation failed" err="write tcp 10.233.108.33:9090->10.233.108.0:52696: write: broken pipe"
          level=error ts=2019-03-14T01:57:27.830604926Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYKAVEYZP90XZ45SC9BZ5F.tmp: invalid argument"
          level=error ts=2019-03-14T01:59:28.531418658Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYPDHP3GRAAVCC3ZDBZG5W.tmp: invalid argument"
          level=error ts=2019-03-14T02:01:29.327471451Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYT7AKK66SAPJW3C92V66V.tmp: invalid argument"
          level=error ts=2019-03-14T02:03:30.1805298Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WYY53F5BYS095Q4PBZCGTY.tmp: invalid argument"
          level=error ts=2019-03-14T02:05:31.049499893Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZ2AR42R59P33A7439264X.tmp: invalid argument"
          level=error ts=2019-03-14T02:07:31.713056789Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZ6W49WP23BAR2Z8TQ8V32.tmp: invalid argument"
          level=error ts=2019-03-14T02:09:32.49053092Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZAHZ13XYQNJ9HY2CN3464.tmp: invalid argument"
          level=error ts=2019-03-14T02:11:33.16561207Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZE7XABXD41FC83PNPJ5ER.tmp: invalid argument"
          level=error ts=2019-03-14T02:13:33.870413801Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZHXRER4A1N97CW05ZTEXJ.tmp: invalid argument"
          level=error ts=2019-03-14T02:15:34.520194682Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZNKMEVP1DGZHDW3R7G0W8.tmp: invalid argument"
          level=error ts=2019-03-14T02:17:35.354180368Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZS9ERCBRE36SAMH39JC5T.tmp: invalid argument"
          level=error ts=2019-03-14T02:19:36.082133862Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5WZWZETN1T238CAKQ2SW49M.tmp: invalid argument"
          level=error ts=2019-03-14T02:21:36.810232358Z caller=db.go:324 component=tsdb msg="compaction failed" err="persist head block: open index writer: sync dir: sync /data/01D5X00NBJXWJBCM2N2EG5NH9T.tmp: invalid argument"
```
