### ISSUE TITLE
upgrade from 2.7.1 to 2.8.0 provokes consistently ~ 30% loss of metrics passing through remote_write

### ISSUE THREAD

**Issue by beorn-** [prometheus/prometheus#5389]
## Bug Report
**What did you do?**
After an upgrade from prometheus 2.7.1 to prometheus 2.8.0 i faced a a big metric loss with the remote_write rewrite.

**What did you expect to see?**
Nothing special.

**What did you see instead? Under which circumstances?**
loosing roughly 30% of metrics because of "dropped sample for series that was not explicitly dropped via relabelling"

**Environment**
Debian stretch with github release binary.

* System information:

Linux 4.18.0-0.bpo.1-amd64 x86_64

* Prometheus version:

prometheus, version 2.8.0 (branch: HEAD, revision: 59369491cfdfe8dcb325723d6d28a837887a07b9)
  build user:       root@4c4d5c29b71f
  build date:       20190312-07:46:58
  go version:       go1.11.5

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'prometheus'

rule_files:
  - "rules/*.yml"
  - "rules/app/*.yml"

scrape_configs:

[..]

remote_write:
  - url: "http://<redacted>:8000/write"
    queue_config:
      capacity: 1000000
      max_shards: 2000
```

* Logs:

[prom28.txt](https://github.com/prometheus/prometheus/files/2991311/prom28.txt)

* Rollback:

went fine. back to normal with 2.7.1 version.
