### ISSUE TITLE
Job relabeling stops working after v2.4.3 

### ISSUE THREAD

**Issue by mattalberts** [prometheus/prometheus#5404]
## Bug Report
Relabeling a job stoped working after v2.4.3.

**What did you do?**
Set scrape config to relabel job based on `__meta_kubernetes_namespace`
```yaml
      relabel_configs:
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        regex: (.+)
        replacement: $1
        target_label: job
```

**What did you expect to see?**
I expected to see the `job` label replaced by the value of `__meta_kubernetes_namespace`. the expected behavior occurs on v2.4.3 and prior.

<img width="1132" alt="prom-job-namespace" src="https://user-images.githubusercontent.com/6054865/54935158-f6afd180-4edc-11e9-864e-85f5e5071b76.png">

**What did you see instead? Under which circumstances?**
However, relabeling `job` using the same mechanism in version v2.5.0, v2.6.1, v2.7.2, and v2.8.0 does not work.  All jobs remain defaulted to the value of `job_name`

<img width="1171" alt="prom-job-defaulted" src="https://user-images.githubusercontent.com/6054865/54935248-23fc7f80-4edd-11e9-9425-8fb2443f4b0b.png">

**Environment**
 - kubernetes v1.10.11
 - docker v17.0.3-1

* Prometheus version:
 - v2.4.3 - 167a4b4e73a8eca8df648d2d2043e21bdb9a7449 - job relabels
 - v2.5.0 - 67dc912ac8b24f94a1fc478f352d25179c94ab9b - job remains defaulted
 - v2.6.1 - b639fe140c1f71b2cbad3fc322b17efe60839e7e - job remains defaulted
 - v2.7.2 - 82f98c825a1437c0a24056eb4dc986d9a3fc7fae - job remains defaulted
 - v2.8.0 - 59369491cfdfe8dcb325723d6d28a837887a07b9 - job remains defaulted

* Prometheus configuration file:
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf-v0
  namespace: monitoring-system
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 5s
      evaluation_interval: 15s
    rule_files:
    - /etc/prometheus/rules.d/alerting-rules
    - /etc/prometheus/rules.d/recording-rules
    - /etc/prometheus/rules.d/alerting-rules-canary
    - /etc/prometheus/rules.d/recording-rules-canary
    - /etc/cloudflare/rules.d/*.rules
    scrape_configs:
    - job_name: ~prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: ~prometheus-all
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: monitoring-system;prometheus-server;http
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
        replacement: service_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: pod_$1
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: pod_node
    - job_name: ~prometheus-loader
      static_configs:
      - targets: ['localhost:8080']
        labels:
          sidecar: rule-loader
      relabel_configs:
      - replacement: ~prometheus-sidecars
        target_label: job
    - job_name: ~kubernetes-apiservers
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
        replacement: service_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: pod_$1
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: pod_node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - job_name: ~kubernetes-nodes
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    - job_name: ~kubernetes-nodes-cadvisor
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
    # Maintaining prometheus scrapes for backward compatibility
    - job_name: ~kubernetes-service-endpoints
      kubernetes_sd_configs:
      - role: endpoints
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_format
        target_label: __param_format
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
        replacement: service_$1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: pod_$1
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: pod_node
      tls_config:
        insecure_skip_verify: true
    - job_name: ~kubernetes-services
      kubernetes_sd_configs:
      - role: service
      metrics_path: /probe
      params:
        module:
        - http_2xx
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_probe
      - source_labels:
        - __address__
        target_label: __param_target
      - replacement: blackbox
        target_label: __address__
      - source_labels:
        - __param_target
        target_label: instance
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
        replacement: service_$1
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        regex: (.+);(.+)
        replacement: $1/$2
        target_label: job
    - job_name: ~kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_format
        target_label: __param_format
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        replacement: pod_$1
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_controller_name
        regex: (.*)(?:-.*)
        replacement: $1
        target_label: kubernetes_name
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: pod_node
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        regex: (.+)
        replacement: $1
        target_label: job
      tls_config:
        insecure_skip_verify: true
---
```

* Logs:
```
level=info ts=2019-03-25T16:18:54.563858517Z caller=main.go:324 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-03-25T16:18:54.563877897Z caller=main.go:325 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-03-25T16:18:54.564497109Z caller=main.go:640 msg="Starting TSDB ..."
level=info ts=2019-03-25T16:18:54.564552513Z caller=web.go:418 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-03-25T16:18:54.571051524Z caller=main.go:655 msg="TSDB started"
level=info ts=2019-03-25T16:18:54.571167146Z caller=main.go:724 msg="Loading configuration file" filename=/etc/prometheus/conf/prometheus.yaml
level=info ts=2019-03-25T16:18:54.575622448Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:54.5770268Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:54.57823994Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:54.57937525Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:54.696921408Z caller=main.go:751 msg="Completed loading of configuration file" filename=/etc/prometheus/conf/prometheus.yaml
level=info ts=2019-03-25T16:18:54.696969869Z caller=main.go:609 msg="Server is ready to receive web requests."
level=info ts=2019-03-25T16:18:55.255975995Z caller=main.go:724 msg="Loading configuration file" filename=/etc/prometheus/conf/prometheus.yaml
level=info ts=2019-03-25T16:18:55.258432271Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.259244949Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.259993149Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.260784327Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.486117788Z caller=main.go:751 msg="Completed loading of configuration file" filename=/etc/prometheus/conf/prometheus.yaml
level=info ts=2019-03-25T16:18:55.486591971Z caller=main.go:724 msg="Loading configuration file" filename=/etc/prometheus/conf/prometheus.yaml
level=error ts=2019-03-25T16:18:55.488777474Z caller=endpoints.go:130 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2019-03-25T16:18:55.488812409Z caller=pod.go:85 component="discovery manager scrape" discovery=k8s role=pod msg="pod informer unable to sync cache"
level=info ts=2019-03-25T16:18:55.488936287Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.489628732Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.490315703Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.490956702Z caller=kubernetes.go:191 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-03-25T16:18:55.687249852Z caller=main.go:751 msg="Completed loading of configuration file" filename=/etc/prometheus/conf/prometheus.yaml
```
> *note*: nothing relevant, but included it anyway.
