### ISSUE TITLE
Labels in alert can't be used in annotation

### ISSUE THREAD

**Issue by freeseacher** [prometheus/prometheus#5405]
## Proposal
I'm mocking alert to make better templates for opsgenie. I do not have any data in prometheus and no plans to have it in on my laptop. While doing templates i want to build several alerts and make sure that my pretty complex templates works as expected. Especially grouping and selection which annotation will win after grouping and inhibit rules.
I'm extremely frustrated that i can't mock alert info with `vector(1)` and added alert labels. 

## Bug Report
**What did you do?**
Mocking templates and sending them to fake opsgenie receiver

**What did you expect to see?**
Summary field templates well. 

**What did you see instead? Under which circumstances?**
My label data was not rendered at all.

**Environment**
Laptop with linux

* System information:
NA

* Prometheus version:
```
prometheus, version 2.7.1 (branch: HEAD, revision: 62e591f928ddf6b3468308b7ac1de1c63aa7fcf3)
  build user:       root@f9f82868fc43
  build date:       20190131-11:16:59
  go version:       go1.11.5
```

**Comment by brian-brazil** [comment]
I'm afraid this is not something that can be done, all labels/annotations are evaluated independently with no ordering as there is no sane ordering. I'd suggest creating a recording rule for the time series with the labels you need.

**Comment by roidelapluie** [comment]
While technically that would be possible, I think for those small niches, you can follow @brian-brazil suggestion:

```
groups:
- name: test
  rules:
      - record: node_filesystem_files_free
        expr: vector(0)
        labels:
          mountpoint: /foo
          instance: 127.0.0.1:9100
      - record: node_filesystem_files
        expr: vector(3241234123)
        labels:
          mountpoint: /foo
          instance: 127.0.0.1:9100
      - alert: filesystem full
        expr: 1-node_filesystem_files_free/node_filesystem_files > 0.9
        annotations:
          text: "{{$labels.mountpoint}} has no inodes"
```

I think this issue can be closed. If you have more questions on this topic, I suggest you move this over to our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users).
