### ISSUE TITLE
metric path not allowing a format like /metrics?&b1234

### ISSUE THREAD

**Issue by samanta1983** [prometheus/prometheus#5488]
Hello All,

We are trying to scrape targets using urls like following:

http://example.com:1234/service/metrics?&b1234

sample config:

```
- job_name: test-1
    metrics_path: /service/metrics?&b1234
    scheme: http
    static_configs:
    - targets:
      - example.com:1234
```

Here example.com is a VIP url which load balances across multiple JVMs. In order to connect to a specific JVM, an affinity url is constructed using "&b1234". The load balancer uses this to identify which JVM to connect.
However, Prometheus converts "?" to "%3F" while scraping and as a result gets 404.
Can you help us in identifying a solution for this. I tried using params, but it needs a key, value structure.

Note: Due to security reasons, we cannot directly connect to the individual JVM ports.

**Comment by simonpasquier** [comment]
AFAICT your only option is using the `params` option which should generate `http://example.com:1234/service/metrics?b1234=`. There's no way to get rid of the trailing equal sign.

```
- job_name: test-1
    metrics_path: /service/metrics
    scheme: http
    params:
      b1234: []
    static_configs:
    - targets:
      - example.com:1234
```

I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.
