### ISSUE TITLE
Duplicate data collected

### ISSUE THREAD

**Issue by SteveYf** [prometheus/prometheus#5489]
Hey, Dear developer，I was in trouble when I used prometheus to monitor the many apis.  
prometheus version: 2.9.0
export : prometheus_client

I have a server with four services running on it, and each service is independent. I need to monitor these four services at the same time.

Scrape_configs configuration in prometheus.yml:
```
......
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  #- job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

  #  static_configs:
  #  - targets: ['localhost:9090']

  # target
  - job_name: 'test1'
    static_configs:
    - targets: ['192.168.175.22:29090']

  # target
  - job_name: 'test2'
    static_configs:
    - targets: ['192.168.175.22:29016']

  # target
  - job_name: 'test3'
    static_configs:
    - targets: ['192.168.175.22:29008']

  # target
  - job_name: 'test4'
    static_configs:
    - targets: ['192.168.175.22:29009']
```

I am configured to run normally and collect metrics,  but the metrics collected are four, no matter what type of metrics, this situation is very bad for me, because I want to use the aggregation operation to process the data.

I read the relevant documents,  as follows:

> A scrape_config section specifies a set of targets and parameters describing how to scrape them. In the general case, one scrape configuration specifies a single job. In advanced configurations, this may change.

What is the so-called advanced configuration? Is it possible to monitor multiple services on a single machine? And the data is not repeated.
I also checked the configuration file dynamic management, I don't think it can solve this problem. 
What I expected was to monitor multiple services on a single machine separately, and the metrics obtained were independent of each other.
Is my configuration file wrong? Or is the current prometheus temporarily not supporting this feature?
thank you very much for your help.
Steve Bailey.
