### ISSUE TITLE
Prometheus 2.5.0 consuming higher RAM than expected

### ISSUE THREAD

**Issue by arunkumarpro1** [prometheus/prometheus#5510]
## Proposal
**Use case. Why is this important?**
To make Prometheus stable in memory-limited devices.

## Bug Report
**What did you do?**
Created around 300 Time Series and populated the metrics continuously.

**What did you expect to see?**
Prometheus consuming less memory

**What did you see instead? Under which circumstances?**
Prometheus consuming around 1.1 GB within a day for just 300 TimeSeries.
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/23283801/56686115-34447d80-6688-11e9-8514-a4065438ede6.png">

This is how go_memstats_alloc_bytes changes
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/23283801/56686396-bd5bb480-6688-11e9-8857-fa66333d99ec.png">

Generating pprof memory profiles did not help much as it just showed 16 MB of the total 1.1 GB. Here is the complete insuse memory profile
https://ibb.co/30nCXBV

This is not the usual behavior as we have seen Prometheus taking around 150 MB even under more stressful conditions.

**Environment**
A device which has a limited memory capacity of around 8 GB

* System information:
Linux 4.9.119-yocto-standard x86_64

* Prometheus version:
```
prometheus, version 2.5.0 (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.11.6
```

* Alertmanager version:
insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 5s
  external_labels:
      monitor: 'codelab-monitor'

rule_files:
  - '/var/run/prometheus/alerts/*.yml'

scrape_configs:
  - job_name: 'tsdbd'

    scrape_interval: 5s

    static_configs:
      - targets: ['127.0.0.1:9091']

  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['127.0.0.1:9090']

    metrics_path: '/prom/metrics'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9091
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
