### ISSUE TITLE
Some alerting rules stopped working after upgrading to v2.5.0 and above

### ISSUE THREAD

**Issue by lichuan0620** [prometheus/prometheus#5517]
## Bug Report
**What did you do?**

Upgraded Alertmanager from `v0.6.2` to `v0.16.2` and Prometheus from `v2.4.3` to `v2.5.0`.

**What did you expect to see?**

Everything work as before

**What did you see instead? Under which circumstances?**

2 out of 5 alerting rules stopped working and, judging from its log, the alertmanager never received them. Not sure if it was a coincidence, but the two that stopped working were the only two that were supposed to produce multiple alerts; the others would produce exactly one.

* Prometheus version:

I have tried `v2.1.0`, `v.2.4.3`, `v2.5.0`, `v2.6.1`, `v2.7.2`, and the symptom would appear on `v2.5.0` and above.

* Alertmanager version:

`v0.16.2`

* Prometheus configuration file:

Just the alerting rule part, ask me if you need the whole thing. The rules that were having problems were marked with comments.

```
groups:
- name: default.alerting
  interval: 30s
  rules:
  - alert: lctest-partition-X5LjR
    expr: sum(kube_pod_status_phase{phase="Running", namespace="default"} or up * 0) > 0.00000000
    for: 5s
    labels:
      caicloud_cluster_id: compass-stack
      caicloud_resource_version: X5LjR
      caicloud_rule_id: 5cc129c60660c500016cf580
    annotations:
      caicloud_cluster_id: compass-stack
      caicloud_comparable: partition.pod_count
      caicloud_compare_op: '>'
      caicloud_duration: 5s
      caicloud_node: '{{ $labels.cps_node_name }}'
      caicloud_partition: default
      caicloud_release: '{{ $labels.release }}'
      caicloud_resource_kind: partition
      caicloud_rule_id: 5cc129c60660c500016cf580
      caicloud_tenant_id: system-tenant
      caicloud_threshold: "0"
      caicloud_value: '{{ $value }}'
  - alert: lctest-partition-app-18DsP # stop working after upgrading to v2.5.0 and above
    expr: sum(app:container_cpu_usage_seconds_total:rate:1m{ namespace="default" }) by (release) < 1.00000000
    for: 5s
    labels:
      caicloud_cluster_id: compass-stack
      caicloud_resource_version: 18DsP
      caicloud_rule_id: 5cc1a2640660c500016cf583
    annotations:
      caicloud_cluster_id: compass-stack
      caicloud_comparable: app.total_cpu_usage
      caicloud_compare_op: <
      caicloud_duration: 5s
      caicloud_node: '{{ $labels.cps_node_name }}'
      caicloud_partition: default
      caicloud_release: '{{ $labels.release }}'
      caicloud_resource_kind: partition
      caicloud_rule_id: 5cc1a2640660c500016cf583
      caicloud_tenant_id: system-tenant
      caicloud_threshold: "1"
      caicloud_value: '{{ $value }} core'
  - alert: lctest-cluster-l0XnE
    expr: sum(rate(container_cpu_usage_seconds_total{id="/"}[1m])) / sum(machine_cpu_cores) > 0.00001000
    for: 5s
    labels:
      caicloud_cluster_id: compass-stack
      caicloud_resource_version: l0XnE
      caicloud_rule_id: 5cc1a7c40660c500016cf584
    annotations:
      caicloud_cluster_id: compass-stack
      caicloud_comparable: cluster.cpu_utilized
      caicloud_compare_op: '>'
      caicloud_duration: 5s
      caicloud_node: '{{ $labels.cps_node_name }}'
      caicloud_partition: '{{ $labels.namespace }}'
      caicloud_release: '{{ $labels.release }}'
      caicloud_resource_kind: cluster
      caicloud_rule_id: 5cc1a7c40660c500016cf584
      caicloud_tenant_id: system-tenant
      caicloud_threshold: "0.00001"
      caicloud_value: '{{ $value }} percentage'
  - alert: lctest-node-FMpJ8
    expr: sum (node_cpu:irate:1m{ mode!="idle", cps_node_name="kube-master-1"  }) by (cps_node_name) > 0.01000000
    for: 5s
    labels:
      caicloud_cluster_id: compass-stack
      caicloud_resource_version: FMpJ8
      caicloud_rule_id: 5cc1a7fb0660c500016cf585
    annotations:
      caicloud_cluster_id: compass-stack
      caicloud_comparable: node.cpu_usage
      caicloud_compare_op: '>'
      caicloud_duration: 5s
      caicloud_node: kube-master-1
      caicloud_partition: '{{ $labels.namespace }}'
      caicloud_release: '{{ $labels.release }}'
      caicloud_resource_kind: node
      caicloud_rule_id: 5cc1a7fb0660c500016cf585
      caicloud_tenant_id: system-tenant
      caicloud_threshold: "0.01"
      caicloud_value: '{{ $value }} core'
  - alert: lctest-node-app-NfUOY # stop working after upgrading to v2.5.0 and above
    expr: app:container_cpu_usage_seconds_total:rate:1m{ cps_node_name="kube-master-1"} > 0.01000000
    for: 5s
    labels:
      caicloud_cluster_id: compass-stack
      caicloud_resource_version: NfUOY
      caicloud_rule_id: 5cc26b890660c500016cf586
    annotations:
      caicloud_cluster_id: compass-stack
      caicloud_comparable: app.cpu_usage
      caicloud_compare_op: '>'
      caicloud_duration: 5s
      caicloud_node: kube-master-1
      caicloud_partition: '{{ $labels.namespace }}'
      caicloud_release: '{{ $labels.release }}'
      caicloud_resource_kind: node
      caicloud_rule_id: 5cc26b890660c500016cf586
      caicloud_tenant_id: system-tenant
      caicloud_threshold: "0.01"
      caicloud_value: '{{ $value }} core'

```

* Alertmanager configuration file:

```
global:
  resolve_timeout: 5m
  http_config: {}
  smtp_hello: localhost
  smtp_require_tls: true
  pagerduty_url: https://events.pagerduty.com/v2/enqueue
  hipchat_api_url: https://api.hipchat.com/
  opsgenie_api_url: https://api.opsgenie.com/
  wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
  victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
route:
  receiver: alert-notifier
  group_by:
  - caicloud_rule_id
  - caicloud_resource_version
  group_wait: 15s
  group_interval: 3m
  repeat_interval: 3h
receivers:
- name: alert-notifier
  webhook_configs:
  - send_resolved: true
    http_config: {}
    url: http://alert-notifier:5001/api/v0.1/alerts
templates: []
```
