### ISSUE TITLE
Example graph seems wrong

### ISSUE THREAD

**Issue by blairg23** [prometheus/prometheus#5538]
## Proposal
**Use case. Why is this important?**
Trying to run example tutorial.

## Bug Report
**What did you do?**
1. Go through Prometheus example steps until you get to the last one where you set up the command `job_service:rpc_durations_seconds_count:avg_rate5m`.
2. Switch between "stacked" and "unstacked"
3. The legend remains the same, but the colors switch places in the graph and don't match their values.

**What did you expect to see?**
The stacked version of this correct graph:
![image](https://user-images.githubusercontent.com/6225764/57245338-dbfe6b80-6ff7-11e9-9f74-be926720dba4.png)

**What did you see instead? Under which circumstances?**
This incorrect graph: 
![image](https://user-images.githubusercontent.com/6225764/57245317-cab55f00-6ff7-11e9-8ccf-f5630d6a80bc.png)

**Environment**
Ubuntu Linux 18.04 LTS

* System information:

Linux 4.15.0-46-generic x86_64

* Prometheus version:

prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'prometheus.rules.yml'
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'example-random'

    # Override the global default and scrape targets from this job every 5 seconds.
    
    scrape_interval: 5s

    static_configs:
    - targets: ['localhost:8080', 'localhost:8081']
      labels:
        group: 'production'

    - targets: ['localhost:8082']
      labels:
        group: 'canary'

```
