### ISSUE TITLE
Data must be removed after service restart

### ISSUE THREAD

**Issue by alexseys** [prometheus/prometheus#5541]
Hi
Every time i restart prometheus service I have to remove contents existing data directory otherwize prometheus starts but outputs 
Service Unavailable

Once I remove /data/prometheus/*, service starts and collects data, allows grafana access etc...

**Environment**
Centos 7
* System information:

Linux 3.10.0-957.5.1.el7.x86_64 x86_64

* Prometheus version:

prometheus --version
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

* Alertmanager version:

alertmanager --version
alertmanager, version 0.16.1 (branch: HEAD, revision: 571caec278be1f0dbadfdf5effd0bbea16562cfc)
  build user:       root@3000aa3a06c5
  build date:       20190131-15:05:40
  go version:       go1.11.5

* Prometheus configuration file:
```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: 'json config files'  # This is a default value, it is mandatory.
    file_sd_configs:
      - files:
        - json/*.json

rule_files:
  - alert.rules.yml

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"
```

* Alertmanager configuration file:
```
global:
  slack_api_url: "https://hooks.slack.com/services/SlackWebhookAPI"

route:
  group_by: ['instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - match:
      alertname: InstanceDown
  receiver: 'alert-team'

receivers:
- name: 'alert-team'
  slack_configs:
  - channel: "#webhook-test"
    text: "summary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"

```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
