### ISSUE TITLE
azure service discovery does not report public IP 

### ISSUE THREAD

**Issue by dmitsh** [prometheus/prometheus#5588]
## Bug Report
**What did you do?**
Run azure service discovery

**What did you expect to see?**
A label with VM's public IP should be added to the target VMs

**What did you see instead? Under which circumstances?**
The label with public IP was missing

**Environment**

* System information:

	Linux 4.15.0-50-generic x86_64

* Prometheus version:

	prometheus, version 2.9.2 (branch: upstream-master, revision: d6a4daa26a861c8642dca467cc6afc450bbc6b2f)
	go version:       go1.12.4

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: service-azure
  azure_sd_configs:
    - environment: AzurePublicCloud
      authentication_method: OAuth
      subscription_id: xxxxxx
      tenant_id: xxxxxx
      client_id: xxxxxx
      client_secret: xxxxxx
      port: 9100
```
