### ISSUE TITLE
Prometheus not showing metrics for terminated Pods

### ISSUE THREAD

**Issue by vivekj11** [prometheus/prometheus#5611]
I am using kubelet cadvisor for collecting container/pods metrics. 
 
 In my prometheus.yml target, I have mentioned "myclusterip:10255/metrics/cadvisor". and I can see metrics for running containers/Pods but no details available for Pods which got terminated earlier. I have a retention period of 14 days.
 
 I need metrics for old (terminated/deleted) containers for performance analysis.

**Comment by vivekj11** [comment]
a part of my prometheus config from compose-file

```
prometheus:
    image: prom/prometheus:v2.8.1
    networks:
      - monitor
#    ports:
#      - '9090:9090'
    volumes:
      - /promstack/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /promstack/prom_data:/prometheus:rw
      - /promstack/alert.rules:/etc/prometheus/alert.rules:ro
    user: "0"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=14d'
```

and my prometheus.yml looks like this- 

```
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  scrape_timeout: 30s #scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - serverip:9093
    timeout: 30s
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/alert.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'Prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets:
      - localhost:9090
```


Can someone pls tell, what is missing here due to which the old container details (which got terminated an hour back) not available in Prometheus.
