### ISSUE TITLE
Use kubernetes_sd_configs in conjunction with consul_sd_config

### ISSUE THREAD

**Issue by Neru007** [prometheus/prometheus#5615]
I'm monitoring kubernetes clusters that are getting created dynamically and API servers are registered at consul. My Question is can I use kubernetes_sd_configs and consul_sd_configs together in conjunction 

* Prometheus configuration file:
```
- job_name: 'kubernetes-kubelet'
  kubernetes_sd_configs:
  - api_server: http://cluster01
    role: node
    bearer_token: xxxx
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - source_labels: [__address__]
    regex: '(.*):10250'
    replacement: '${1}:10255'
    target_label: __address__
```

In the above configuration I want **api_server** to be discovered via consul. Is there a way I can discover an api server address via consul_sd_config and use it with kubernetes_sd_configs.
