### ISSUE TITLE
Scrape job does not work with 2.10.0 anymore

### ISSUE THREAD

**Issue by weeco** [prometheus/prometheus#5620]
## Bug Report
**What did you do?**

After upgrading from Prometheus v2.9.2 to v2.10.0 my scrape job did not work anymore. I tried a couple different relabel_configs because I thought these were causing it, but that did not help.

**What did you expect to see?**

I expected Prometheus to ingest metrics from my pods with the app label `cortex` in the namespace `monitoring` and show these targets in the UI.

**What did you see instead? Under which circumstances?**

In the prometheus UI I saw prometheus did not discover any of the targets. After changing the version back from v2.10.0 to v2.9.2 it worked as intended.

**Environment**

Kubernetes + Docker image

* Prometheus configuration file:
```
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'cortex'
    tls_config:
      insecure_skip_verify: true
    params:
      format: ['prometheus']
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - monitoring
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_label_app,__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: cortex;true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```

* Logs:

There were no suspicious logs in the 2.10.0 version. No warnings, errors or similiar. Just the common, to be expected info logs.
