### ISSUE TITLE
Snapshot failed with permission denied error

### ISSUE THREAD

**Issue by rjshrjndrn** [prometheus/prometheus#5628]
## Bug Report
**What did you do?**
` curl -XPOST http://localhost:29090/prometheus/api/v1/admin/tsdb/snapshot?skip_head=false`

**What did you expect to see?**
snapshot success full with id

**What did you see instead? Under which circumstances?**
```
{"status":"error","errorType":"internal","error":"create snapshot: error snapshotting block: /prometheus/01DC948VGSY74MR6WQR4RDQXK9: create snapshot meta.json: link /prometheus/01DC948VGSY74MR6WQR4RDQXK9/meta.json /prometheus/snapshots/20190604T061600Z-7008746200a49d0b/01DC948VGSY74MR6WQR4RDQXK9/meta.json: operation not permitted"}

```
**Environment**

Ubuntu 16.04 
Docker version 18.03.1-ce, build 9ee9f40

* System information:

Linux 4.15.0-1041-azure x86_64

* Prometheus version:

```
rajeshr@kibana-grafana:~$ docker exec prometheus_fed_prometheus.1.e8drqrspwc69zaqpm6veawhsb prometheus --version
prometheus, version 2.8.1 (branch: HEAD, revision: 4d60eb36dcbed725fcac5b27018574118f12fffb)
  build user:       root@bfdd6a22a683
  build date:       20190328-18:04:08
  go version:       go1.11.6
```

* Alertmanager version:

	No alertmanager

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  # Clustername is defined for multi swarm cluster
  # can name first cluster as DS1 and 2nd as DS2 ... DSn
  # all metrics will have label as cluster: < value >
  # This value won't be accessible from GUI but for external tools like
  # federation or alertmanager
  external_labels:
    federation: fed1


scrape_configs:

    # This empty line ensures indentation is correct after ansible jinja2 template is materialized
  - job_name: 'docker'
    static_configs:
      - targets: ['11.3.0.26:2377']

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'grpc_.*'
        action: drop


  - job_name: 'federate'
    metrics_path: /prometheus/federate
    honor_labels: true
    params:
      match[]:
        - '{__name__=~"nginx_.*"}'
        - '{__name__=~"kong_.*"}'
        - '{__name__=~"node_.*"}'
    static_configs:
                  # This empty line make sure the indentation is correct
      - targets: [ '11.3.1.4:9090', '11.3.0.26:9090', '11.3.0.29:9090', '11.3.3.23:19090' ]

  - job_name: 'vm-node-exporter'
    static_configs:
      - targets: ["11.3.3.23:9100"]


```

* Alertmanager configuration file:
```
None
```

* Logs:
```
prometheus_fed_prometheus.1.e8drqrspwc69@kibana-grafana    | level=info ts=2019-06-04T06:25:28.493275071Z caller=db.go:910 component=tsdb msg="snapshotting block" block=01DC948VGSY74MR6WQR4RDQXK9
```
