### ISSUE TITLE
Intermediate rule evaluation results

### ISSUE THREAD

**Issue by carlpett** [prometheus/prometheus#5629]
## Proposal
I commonly find teams having to do multiple recording rules in order to arrive at the final result they need, for example due to needing to do range queries on the result in the next step. Contrieved example:

```yaml
groups:
- name: example
  rules:
  - record: step1
    expr: histogram_quantile(0.9, sum by (le) (rate(duration_seconds_bucket[5m])))
  - record: step2
    expr: max(step1)
  - record: step3
    expr: step2 > bool 5
  - record: step4
    expr: avg_over_time(step3[7d])
```

In this case, we don't really care about saving steps 1-2 (step 3 would need to be kept since we do a range on it). This both leads to unnecessary storage and "worthless" metrics floating around.
Could we add a new directive, maybe `discard: true`, to instruct Prometheus not to persist the result but instead drop it after the group has finished?
