### ISSUE TITLE
Using remote_read, an "OR" query will fail with offsets older than retention time.

### ISSUE THREAD

**Issue by czert** [prometheus/prometheus#5639]
## Bug Report
**What did you do?**
`promtool query instant http://localhost:9090 'node_forks offset 26d or node_forks_total offset 26d'`

**What did you expect to see?**
Output similar to running the same command with a 6 day offset instead:
`promtool query instant http://localhost:9090 'node_forks offset 6d or node_forks_total offset 6d'`

**What did you see instead? Under which circumstances?**
No output. When the offset is larger than the retention time (15d in my case), this query will return no data. When the offset is smaller, data is returned. When I don't "or" the two subqueries, everything works fine, even with large offsets:

`promtool query instant http://localhost:9090 'node_forks_total offset 26d'`

Note that I write all data into influxdb and read it from there as well. I tried setting the `read_recent` setting to `true` on the remote_read, but this doesn't affect this issue in any way. 

**Environment**

* System information:

	Linux 4.13.0-37-generic x86_64

* Prometheus version:
```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

* Prometheus configuration file:
```
(...)
remote_write:
  - url: 'http://localhost:8086/api/v1/prom/write?db=prometheus'

remote_read:
  - url: 'http://localhost:8086/api/v1/prom/read?db=prometheus'
    read_recent: true  # tried with false, doesn't matter
```
