### ISSUE TITLE
Remote writing only Prometheus consumes more than 10Gb of RAM

### ISSUE THREAD

**Issue by weeco** [prometheus/prometheus#5666]
## Bug Report
**What did you do?**

I am running Prometheus v2.10.0 which is configured to remote write all metrics to my Cortex cluster. This prometheus instance is not used for any reads. However this instance consumes more than 10GB of RAM.

**What did you expect to see?**

I expected the remote writing prometheus only takes like 1-2 GB RAM max as I don't see why it would need to keep so much data in memory.

**What did you see instead? Under which circumstances?**

Prometheus takes 10.5GB RAM and is pretty stable around this.

Prometheus metrics: 

![Bildschirmfoto 2019-06-14 um 14 25 01](https://user-images.githubusercontent.com/23424570/59509231-bc891700-8eb0-11e9-809b-65f8acd17b6f.png)

**Environment**

Kubernetes / Docker + Persistent Volume for the prometheus data directory

* Prometheus version:

v2.10.0

**Prometheus Flags**

```
          args = [
            "--config.file=/etc/prometheus/prometheus.yml",
            "--storage.tsdb.path=/data",
            "--storage.tsdb.no-lockfile",
            "--storage.tsdb.min-block-duration=2h",
            "--storage.tsdb.max-block-duration=2h",
            "--storage.tsdb.retention.time=1d",
            "--web.enable-lifecycle",
            "--web.console.libraries=/etc/prometheus/console_libraries",
            "--web.console.templates=/etc/prometheus/consoles",
          ]
```

Why does it take so much RAM? Is it supposed to be like this or is this a bug / configuration issue?

**Comment by cstyan** [comment]
Can you show us your config file? Specifically the remote write/queue config?

**Comment by weeco** [comment]
Sure:

```
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
remote_write:
  - url: ${remote_write_url}
    bearer_token_file: "/etc/secrets/bearer_token.txt"
    queue_config:
      max_shards: 250
      max_samples_per_send: 500
```

I omitted the scrape configs which are just some kubernetes entities (pods, services, endpoints)
