### ISSUE TITLE
Sudden increase in disk space usage after/while running compaction (filling entire disk)

### ISSUE THREAD

**Issue by bullboa** [prometheus/prometheus#5683]
## Bug Report
**What did you do?**
Ran two Prometheus "master/parent" instances with identical config, federating metrics from four other "child" Prometheus instances + scraping two Cloudwatch exporters

**What did you expect to see?**
Free disk space slowly decreasing

**What did you see instead? Under which circumstances?**
All disk space being used up in 30 mins on both instances at the same time, twice.
Four weeks ago from slow and steady increase up to 30 GiB and then within 30 minutes both instances had used up an additional 65 GiB for a total of 95 GiB.
Again during the past weekend, slow and steady up to 60 GiB and suddenly within 30 minutes both had used an additional 50 GiB for a total of 110 GiB.

**Environment**

* System information:

AWS EC2 instance, Linux 4.9.0-7-amd64 x86_64

* Prometheus version:

All six instances:

prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s
  external_labels:
    kubernetes_master_cluster_name: eu-west-1-ci
alerting:
  alertmanagers:
  - kubernetes_sd_configs:
    - role: pod
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecure_skip_verify: false
    scheme: http
    timeout: 10s
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      separator: ;
      regex: monitoring
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      separator: ;
      regex: prometheus
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      separator: ;
      regex: alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      separator: ;
      regex: null
      replacement: $1
      action: drop
rule_files:
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: federate
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{__name__="kube_namespace_labels"}'
    - '{__name__="container_spec_cpu_quota"}'
    - '{__name__="container_spec_cpu_period"}'
    - '{__name__="container_cpu_usage_seconds_total"}'
    - '{__name__="container_memory_usage_bytes"}'
    - '{__name__="kube_pod_container_resource_limits_memory_bytes"}'
    - '{__name__="container_network_receive_bytes_total"}'
    - '{__name__="container_network_transmit_bytes_total"}'
    - '{__name__="kubelet_volume_stats_capacity_bytes"}'
    - '{__name__="kubelet_volume_stats_available_bytes"}'
    - '{__name__="kube_pod_container_info"}'
    - '{__name__="kube_pod_container_status_ready"}'
    - '{__name__="node_memory_MemAvailable_bytes"}'
    - '{__name__="node_memory_MemTotal_bytes"}'
    - '{__name__="kube_node_labels"}'
    - '{__name__="node_filesystem_free_bytes"}'
    - '{__name__="node_filesystem_size_bytes"}'
    - '{__name__="node_cpu_seconds_total"}'
    - '{__name__="kube_cronjob_next_schedule_time"}'
    - '{__name__="kube_pod_container_status_restarts_total"}'
    - '{__name__="kube_deployment_spec_replicas"}'
    - '{__name__="kube_deployment_status_replicas_available"}'
    - '{__name__="kube_node_status_condition"}'
    - '{__name__="elasticsearch_cluster_health_status"}'
    - '{__name__="container_memory_working_set_bytes"}'
    - '{__name__="kube_pod_container_resource_limits_memory_bytes"}'

  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  static_configs:
  - targets:
    - monitoring-prometheus-server.monitoring.svc.cluster.local:80
- job_name: inter-cluster-federate
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{__name__="kube_namespace_labels"}'
    - '{__name__="container_spec_cpu_quota"}'
    - '{__name__="container_spec_cpu_period"}'
    - '{__name__="container_cpu_usage_seconds_total"}'
    - '{__name__="container_memory_usage_bytes"}'
    - '{__name__="kube_pod_container_resource_limits_memory_bytes"}'
    - '{__name__="container_network_receive_bytes_total"}'
    - '{__name__="container_network_transmit_bytes_total"}'
    - '{__name__="kubelet_volume_stats_capacity_bytes"}'
    - '{__name__="kubelet_volume_stats_available_bytes"}'
    - '{__name__="kube_pod_container_info"}'
    - '{__name__="kube_pod_container_status_ready"}'
    - '{__name__="node_memory_MemAvailable_bytes"}'
    - '{__name__="node_memory_MemTotal_bytes"}'
    - '{__name__="kube_node_labels"}'
    - '{__name__="node_filesystem_free_bytes"}'
    - '{__name__="node_filesystem_size_bytes"}'
    - '{__name__="node_cpu_seconds_total"}'
    - '{__name__="kube_cronjob_next_schedule_time"}'
    - '{__name__="kube_pod_container_status_restarts_total"}'
    - '{__name__="kube_deployment_spec_replicas"}'
    - '{__name__="kube_deployment_status_replicas_available"}'
    - '{__name__="kube_node_status_condition"}'
    - '{__name__="elasticsearch_cluster_health_status"}'
    - '{__name__="container_memory_working_set_bytes"}'
    - '{__name__="kube_pod_container_resource_limits_memory_bytes"}'
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: https
  static_configs:
  - targets:
    - prometheus.example1.com
    - prometheus.example2.com
    - prometheus.example3.com
- job_name: cloudwatch-exporters
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - monitoring-cloudwatch-exporter-eu-west-1-prometheus-cloudwatch.monitoring.svc.cluster.local:9106
    - monitoring-cloudwatch-exporter-us-east-1-prometheus-cloudwatch.monitoring.svc.cluster.local:9106

```

* Logs:
Logs for both instances when the issue occurred this weekend. Unfortunately no logs from four weeks ago.
[master-0.txt](https://github.com/prometheus/prometheus/files/3300016/master-0.txt)
[master-1.txt](https://github.com/prometheus/prometheus/files/3300017/master-1.txt)

Files on both instances on monday morning. 01DBTZ974QWPC653S1VJ2XDG64.tmp on master-1 is from four weeks ago and was preserved for troubleshooting.

master-0:
```
ls -lah
total 88K
drwxr-xr-x 19 nobody nogroup 4.0K Jun 17 05:00 .
drwxr-x---  3 root   root    4.0K Jun 11 14:59 ..
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:26 01DA71D9Q0ZD39MBCWRX5WCPPH
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:26 01DAR6RXJTEB3ETWP0JMM75TRY
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:26 01DB9JZ3N8QZQAPRV7NCZK0J9T
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:26 01DBTZ4SXBTE03QY4FFNCJCV7W
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:30 01DCCBB65Y22TX5TK6AWY49DY2
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:30 01DCXQH16EJQP1FZRETXB88SWA
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:30 01DDF3Q1A6TDWK9EGHXT0PQKRX
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:04 01DDF3W6YFPPQHZWT25EXKSC78.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:09 01DDF45ZNW0RQCKRYEP0W4RJAH.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:15 01DDF4GV7ZG11HW38VVDN95E88.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:21 01DDF4W0Y49ET28NJFXZV9P6TP.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 21:00 01DDH1EKM24PA20WXZBXG3PQTQ
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 03:00 01DDHP15PQZBXYPJ5HHTC16G1D
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 03:00 01DDHP1HP3BCW8RW7CE9ETVACQ
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 05:00 01DDHWWWXP0EEWYKW7TDB2DMCT
-rw-r--r--  1 nobody nogroup    0 May  3 10:39 lock
drwx------  2 nobody nogroup  16K May  3 10:39 lost+found
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:41 wal

du -sh *
2.5G    01DA71D9Q0ZD39MBCWRX5WCPPH
6.5G    01DAR6RXJTEB3ETWP0JMM75TRY
7.5G    01DB9JZ3N8QZQAPRV7NCZK0J9T
7.6G    01DBTZ4SXBTE03QY4FFNCJCV7W
8.5G    01DCCBB65Y22TX5TK6AWY49DY2
8.8G    01DCXQH16EJQP1FZRETXB88SWA
8.6G    01DDF3Q1A6TDWK9EGHXT0PQKRX
13G    01DDF3W6YFPPQHZWT25EXKSC78.tmp
14G    01DDF45ZNW0RQCKRYEP0W4RJAH.tmp
14G    01DDF4GV7ZG11HW38VVDN95E88.tmp
15G    01DDF4W0Y49ET28NJFXZV9P6TP.tmp
987M    01DDH1EKM24PA20WXZBXG3PQTQ
124M    01DDHP15PQZBXYPJ5HHTC16G1D
339M    01DDHP1HP3BCW8RW7CE9ETVACQ
124M    01DDHWWWXP0EEWYKW7TDB2DMCT
0    lock
16K    lost+found
2.5G    wal
```

master-1
```
ls -lah
total 84K
drwxr-xr-x 18 nobody nogroup 4.0K Jun 17 06:09 .
drwxr-x---  3 root   root    4.0K Jun 11 14:52 ..
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DA71D7S7J5C9CGY7ZMFQDPQC
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DAR6RZJPT2JV8A4B98JZSE53
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DB9JZ4GQ6EX9CF351SNRCF8Y
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DBTZ4W51A05ZWP4GFGZN76HN
drwxr-xr-x  3 nobody nogroup 4.0K May 26 21:03 01DBTZ974QWPC653S1VJ2XDG64.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DCCBB4HB229R0NH6AG0DRC3S
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DCXQH270Z50Y3PTQD75N51YJ
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:07 01DDF3PZ70AHJK61R1K0M1KZE1
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:04 01DDF3W39DXMXK9X31TPRBKZ6N.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:08 01DDF44KEKZKB1M2ZJ88CJTB8W.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 16 03:14 01DDF4FDQW802JWWD42KT06FRC.tmp
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:08 01DDJ0TK2FEQXGTATF04CAA7A8
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:08 01DDJ0V239XTTXN9F51MD9PX9D
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:09 01DDJ0W9P63FYS4EV1WC7RYBWS
-rw-r--r--  1 nobody nogroup    0 May  3 10:40 lock
drwx------  2 nobody nogroup  16K May  3 10:40 lost+found
drwxr-xr-x  3 nobody nogroup 4.0K Jun 17 06:43 wal

du -sh *
2.5G    01DA71D7S7J5C9CGY7ZMFQDPQC
6.4G    01DAR6RZJPT2JV8A4B98JZSE53
7.5G    01DB9JZ4GQ6EX9CF351SNRCF8Y
7.6G    01DBTZ4W51A05ZWP4GFGZN76HN
21G    01DBTZ974QWPC653S1VJ2XDG64.tmp
8.5G    01DCCBB4HB229R0NH6AG0DRC3S
8.8G    01DCXQH270Z50Y3PTQD75N51YJ
8.6G    01DDF3PZ70AHJK61R1K0M1KZE1
11G    01DDF3W39DXMXK9X31TPRBKZ6N.tmp
14G    01DDF44KEKZKB1M2ZJ88CJTB8W.tmp
14G    01DDF4FDQW802JWWD42KT06FRC.tmp
124M    01DDJ0TK2FEQXGTATF04CAA7A8
71M    01DDJ0V239XTTXN9F51MD9PX9D
333M    01DDJ0W9P63FYS4EV1WC7RYBWS
0    lock
16K    lost+found
957M    wal
```

Is this behavior to be expected of Prometheus?
Why / how can it occur at the same time on both instances, twice, within a month?
Can I do anything to prevent it from happening again?
Both times this has happened I have increased the disk space after a while and then everything has worked fine except for big .tmp files laying around.
I am grateful for any help. If more info could help anyone understand I would be glad to provide it. 
I was adviced here: https://groups.google.com/d/msg/prometheus-users/aYFrqsP__X4/lj6TDnw7AgAJ to create an issue.

Kind regards,
Jonatan
