### ISSUE TITLE
Prometheus snapshot fails with compaction error

### ISSUE THREAD

**Issue by rjshrjndrn** [prometheus/prometheus#5686]
## Bug Report
**What did you do?**
Tried to take a snapshot
`curl -XPOST http://localhost:19090/prometheus/api/v1/admin/tsdb/snapshot?skip_head=false`

**What did you expect to see?**
Successful snapshot with id

**What did you see instead? Under which circumstances?**
`{"status":"error","errorType":"internal","error":"create snapshot: snapshot head block: write compaction: found chunk with minTime: 1560909659910 maxTime: 1560914939910 outside of compacted minTime: 1560909600000 maxTime: 1560914938302"}`

**Environment**

* System information:

	insert output of `uname -srm` here  :  Linux 4.18.0-1018-azure x86_64

* Prometheus version:

	insert output of `prometheus --version` here

```
prometheus, version 2.8.1 (branch: HEAD, revision: 4d60eb36dcbed725fcac5b27018574118f12fffb)
  build user:       root@bfdd6a22a683
  build date:       20190328-18:04:08
  go version:       go1.11.6

Docker container: quay.io/prometheus/prometheus:v2.8.1
```

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  # Clustername is defined for multi swarm cluster
  # can name first cluster as DS1 and 2nd as DS2 ... DSn
  # all metrics will have label as cluster: < value >
  # This value won't be accessible from GUI but for external tools like
  # federation or alertmanager
  external_labels:
    federation: fed1


scrape_configs:

    # This empty line ensures indentation is correct after ansible jinja2 template is materialized
  - job_name: 'docker'
    static_configs:
      - targets: ['11.4.1.4:2377', '11.4.1.5:2377', '11.4.1.6:2377']

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'grpc_.*'
        action: drop


  - job_name: 'federate'
    metrics_path: /prometheus/federate
    honor_labels: true
    params:
      match[]:
        - '{__name__=~"nginx_.*"}'
        - '{__name__=~"kong_.*"}'
        - '{__name__=~"node_.*"}'
    static_configs:
                  # This empty line make sure the indentation is correct
      - targets: [ '11.4.1.4:9090', '11.4.1.7:9090', '11.4.3.40:19090' ]

  - job_name: 'vm-node-exporter'
    static_configs:
      - targets: ["11.4.3.40:9100"]

```
This will resolve if I try 
1. `curl -XPOST http://localhost:19090/prometheus/api/v1/admin/tsdb/snapshot`
2. `curl -XPOST http://localhost:19090/prometheus/api/v1/admin/tsdb/snapshot?skip_head=false`
