### ISSUE TITLE
CPU on 100% load when job sample_limit is breached

### ISSUE THREAD

**Issue by shivas** [prometheus/prometheus#5690]
## Bug Report
**What did you do?**
running prometheus with `sample_limit` configured for jobs

**What did you expect to see?**
business as usual if `sample_limit` is breached

**What did you see instead? Under which circumstances?**
if `sample_limit` is breached all CPU cores are 100% loaded

**Environment**

* System information:

	Linux 4.15.0-1040-aws x86_64

* Prometheus version:

prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5

* Alertmanager version:

	not related

* Prometheus configuration file:
```
- job_name: failingjob
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  sample_limit: 5000
  static_configs:
  - targets:
    - 10.50.2.118:8294
    - 10.50.1.179:8294
    - 10.50.5.219:8294
    - 10.50.0.191:8294
    - 10.50.1.93:8294
    - 10.50.1.56:8294

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

level=warn ts=2019-06-20T07:02:19.971Z caller=scrape.go:937 component="scrape manager" scrape_pool=failingjob target=http://10.50.1.56:8294/metrics msg="append failed" err="sample limit exceeded
