### ISSUE TITLE
Working set size increase on startup when remote write enabled

### ISSUE THREAD

**Issue by bismarck** [prometheus/prometheus#5709]
## Bug Report
**What did you do?**
I enabled remote write, restarted the prometheus pod and it OOMed because the working set size increased 3x.

**What did you expect to see?**
Here's what `container_memory_working_set_bytes`, `process_resident_memory_bytes` and `go_memstats_alloc_bytes` looked like before enabling remote write:

![prom-2 10 0-mem](https://user-images.githubusercontent.com/1072760/60206376-5e99ef00-9821-11e9-8079-741e2255d5ef.png)

**What did you see instead? Under which circumstances?**
Here's after enabling remote write:

![prom-2 10 0-mem-rw](https://user-images.githubusercontent.com/1072760/60206515-b6d0f100-9821-11e9-872b-8f230e25da03.png)

After ~4 hours, working set size goes back to expected level:

![prom-2 10 0-mem-rw-4hr](https://user-images.githubusercontent.com/1072760/60206555-d9630a00-9821-11e9-92a2-b23f3938aa17.png)

**Environment**

* System information:
```
Linux 4.15.0-1037-azure x86_64
```
* Prometheus version:
```
prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
  build user:       root@a49185acd9b0
  build date:       20190525-12:28:13
  go version:       go1.12.5
```
* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    datacenter: eastus2
    environment: dev
    prometheus: kubernetes
    prometheus_replica: "0"
alerting:

... alerting configs ...

rule_files:
- /etc/prometheus/rules/prometheus-prometheus-kube-prometheus-rulefiles-0/*.yaml
scrape_configs:

... lots of scrape configs ...

remote_write:
- url: http://REDACTED:7201/api/v1/prom/remote/write
  remote_timeout: 30s
  queue_config:
    capacity: 10
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    max_retries: 3
    min_backoff: 30ms
    max_backoff: 100ms
```
