### ISSUE TITLE
Check for duplicate label names in remote read response

### ISSUE THREAD

**Issue by xinyu7git** [prometheus/prometheus#5731]
## Bug Report
**What did you do?**
Using remote_read and remote_write config, but Prometheus did not merge data from local storage and remote storage , i get two same points. so many function can't be used.

![image](https://user-images.githubusercontent.com/3701997/60559780-23973e80-9d80-11e9-86df-98072060bdd2.png)

**What did you expect to see?**
Prometheus should merge same points to one point.

**What did you see instead? Under which circumstances?**

**Environment**
   Start Command: /data/prometheus/prometheus --config.file=/data/prometheus/prometheus.yml --storage.tsdb.retention.time=2h --storage.tsdb.retention.size=2MB --log.level=debug

* System information:

	insert output of `uname -srm` here

         Linux 5.1.5-1.el7.elrepo.x86_64 x86_64
* Prometheus version:

	insert output of `prometheus --version` here
        `[root@10-0-0-14 prometheus]# ./prometheus --version
          prometheus, version 2.10.0 (branch: HEAD, revision: d20e84d0fb64aff2f62a977adc8cfb656da4e286)
          build user:       root@a49185acd9b0
          build date:       20190525-12:28:13
          go version:       go1.12.5`

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['10.0.0.14:9090']

  - job_name: 'node_exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'shanks-test'
    static_configs:
    - targets: ['10.0.0.14:9273']

remote_write:
  - url: "http://10.0.3.2:8086/api/v1/prom/write?db=prometheus"
remote_read:
  - url: "http://10.0.3.2:8086/api/v1/prom/read?db=prometheus"
    read_recent: true
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
