### ISSUE TITLE
error creating new scrape pool

### ISSUE THREAD

**Issue by ridvankaratas** [prometheus/prometheus#5766]
hello,

I have upgraded Prometheus from 2.7.1 to 2.11.1 

my prometheus.conf looks like that:

```
global:
  scrape_interval: 20s
  scrape_timeout: 15s
scrape_configs:
  - job_name: node_exporter
    honor_labels: true
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/keys/node-exporter-ca.crt
      cert_file: /etc/prometheus/keys/node-exporter-client.crt
      key_file: /etc/prometheus/keys/node-exporter-client.key
      server_name: prometheus
      insecure_skip_verify: true
    file_sd_configs:
      - files:
	- /etc/prometheus/prometheus-srv-sd.json
```

that was working well when I had v2.7.1 but after the upgrade, I'm getting this error: 

```
prometheus[1477]: level=error ts=2019-07-15T17:47:59.608Z caller=manager.go:123 component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to use specified CA cert /etc/prometheus/keys/node-exporter-ca.crt" scrape_pool=node_exporter
```

scrape is not able to create HTTP client, so I'm not able to see targets on Prometheus. 

What should I do?

**Comment by ridvankaratas** [comment]
configuration file:

```
global:
  scrape_interval: 20s
  scrape_timeout: 15s
scrape_configs:
  - job_name: node_exporter
    honor_labels: true
    scheme: https
    tls_config:
      ca_file: /etc/prometheus/keys/node-exporter-ca.crt
      cert_file: /etc/prometheus/keys/node-exporter-client.crt
      key_file: /etc/prometheus/keys/node-exporter-client.key
      server_name: prometheus
      insecure_skip_verify: true
    file_sd_configs:
      - files:
	- /etc/prometheus/prometheus-srv-sd.json
```
