### ISSUE TITLE
storage.tsdb.retention.size exceeds storage

### ISSUE THREAD

**Issue by Armatorix** [prometheus/prometheus#5771]
## Proposal
Prometheus flag is not working as it should. When setting storage.tsdb.retention.size=X, I'm convinced that prometheus won't use more data then X.

## Bug Report
**What did you do?**
I've setup Prometheus with flag
```
      - "--storage.tsdb.retention.size=300MB"
```
left it for some time, next, I've changed scrape interval from 15s to 1s.
So I started to generate more metrics than previously.
**What did you expect to see?**
I expected to see the storage use of Prometheus below 300MB. So I would like to see that old data be deleted as used storage comes close to limit. 

**What did you see instead? Under which circumstances?**
I see that used space is exceeded a lot. It easily takes 750MB and still growing. 
It was caused by an extreme change of config.
It probably would have similar effect if I add more instances to scrape in my service discovery.
**Environment**

* System information:
`Linux 4.15.0-54-generic x86_64`

* Prometheus version:
docker image
`prom/prometheus:v2.11.1`

* Prometheus configuration file:
```
global:
  scrape_interval: 1s
  external_labels:
      monitor: 'local'

scrape_configs:

  - job_name: 'consul'
    consul_sd_configs:
      - server: "localhost:8500"
    relabel_configs:  
    - source_labels: [__meta_consul_service]
      separator: ;
      regex: (.*)_exporter
      target_label: job
      replacement: $1
      action: replace
```
