### ISSUE TITLE
external Prometheus monitoring kubernetes sends one HTTP-request between HTTPS-requests

### ISSUE THREAD

**Issue by zergar** [prometheus/prometheus#5785]
## Bug Report
**What did you do?**
+ installing prometheus with ansible on a VM and supplying a custom prometheus.yml to monitor a kubernetes-cluster
+ starting the corresponding node_exporter DaemonSet on the kubernetes cluster

**What did you expect to see?**
prometheus imports metrics provided by Kubernetes

**What did you see instead? Under which circumstances?**

prometheus tries to scrape the metrics of the kubernetes api-server but fails with an error. tcpdump suggests that this happens because the request to `GET /api/v1/services` gets sent via HTTP instead of HTTPS

**Environment**

* System information:

Linux 5.1.11-300.fc30.x86_64 x86_64

* Prometheus version:
  
  build user:       root@d94406f2bb6f
  build date:       20190710-13:51:17
  go version:       go1.12.7

* Prometheus configuration file:
```
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: localhost.localdomain


rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets:
    - kmaster.domain.de:9110
    - knode1.domain.de:9110
    - knode2.domain.de:9110
    - gfs1.domain.de:9110
    - gfs2.domain.de:9110
    - monitoring.domain.de:9090
      #- file_sd_configs:
      #  - files:
      #    - /etc/prometheus/file_sd/node.yml
      #  job_name: node


- job_name: 'kubernetes-apiserver'
  bearer_token_file: pki/prometheus.token
  tls_config:
    ca_file: /etc/prometheus/pki/api.ca
  scheme: https
  kubernetes_sd_configs:
  - api_server: "kmaster.domain.de:6443"
    role: endpoints
    bearer_token_file: /etc/prometheus/pki/prometheus.token
    tls_config:
      ca_file: /etc/prometheus/pki/api.ca
      insecure_skip_verify: true
      key_file: /etc/prometheus/pki/apiserver.key
      cert_file: /etc/prometheus/pki/apiserver.crt

  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: default;kubernetes;https


- job_name: 'kubernetes-nodes'
  bearer_token_file: /etc/prometheus/pki/prometheus.token
  tls_config:
    ca_file: /etc/prometheus/pki/api.ca
  scheme: https
  kubernetes_sd_configs:
  - api_server: "kmaster.domain.de:6443"
    role: node
    bearer_token_file: /etc/prometheus/pki/prometheus.token
    tls_config:
      ca_file: /etc/prometheus/pki/api.ca
      insecure_skip_verify: true
      key_file: /etc/prometheus/pki/apiserver.key
      cert_file: /etc/prometheus/pki/apiserver.crt

  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: "https://kmaster.domain.de:6443"
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics
  - source_labels: []
    action: replace
    target_label: kubernetes_cluster
    replacement: ise-kube


- job_name: 'kubernetes-pods'
  bearer_token_file: pki/prometheus.token
  tls_config:
    ca_file: /etc/prometheus/pki/api.ca
  scheme: https
  kubernetes_sd_configs:
  - api_server: "kmaster.domain.de:6443"
    role: endpoints
    bearer_token_file: /etc/prometheus/pki/prometheus.token
    tls_config:
      ca_file: /etc/prometheus/pki/api.ca
      insecure_skip_verify: true

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - target_label: __address__
    replacement: "https://kmaster.domain.de:6443"
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    regex: ^$
    replacement: http
    target_label: __meta_kubernetes_pod_annotation_prometheus_io_scheme
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    regex: (.+)
    replacement: ${1}
    target_label: __metrics_path__
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_pod_annotation_prometheus_io_scheme
    - __meta_kubernetes_pod_name
    - __meta_kubernetes_pod_annotation_prometheus_io_port
    - __metrics_path__
    regex: (.+);(.+);(.+);(.+);(.+)
    action: replace
    target_label: __metrics_path__
    replacement: /api/v1/namespaces/${1}/pods/${2}:${3}:${4}/proxy${5}
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)


- job_name: 'kubernetes-services'
  bearer_token_file: pki/prometheus.token
  tls_config:
    ca_file: /etc/prometheus/pki/api.ca
  scheme: https
  kubernetes_sd_configs:
  - api_server: "kmaster.domain.de:6443"
    role: endpoints
    bearer_token_file: /etc/prometheus/pki/prometheus.token
    tls_config:
      ca_file: /etc/prometheus/pki/api.ca
      insecure_skip_verify: true
      key_file: /etc/prometheus/pki/apiserver.key
      cert_file: /etc/prometheus/pki/apiserver.crt

  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - target_label: __address__
    replacement: "https://kmaster.domain.de:6443"
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    regex: ^$
    replacement: http
    target_label: __meta_kubernetes_service_annotation_prometheus_io_scheme
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    regex: (.+)
    replacement: ${1}
    target_label: __metrics_path__
  - source_labels:
    - __meta_kubernetes_namespace
    - __meta_kubernetes_service_annotation_prometheus_io_scheme
    - __meta_kubernetes_service_name
    - __meta_kubernetes_service_annotation_prometheus_io_port
    - __metrics_path__
    regex: (.+);(.+);(.+);(.+);(.+)
    action: replace
    target_label: __metrics_path__
    replacement: /api/v1/namespaces/${1}/services/${2}:${3}:${4}/proxy${5}
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)

```

* Logs:
```
level=error ts=2019-07-19T14:59:28.359Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:264: Failed to list *v1.Service: Unexpected error &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00575be30), Addr:(*net.TCPAddr)(0xc00575be60), Err:(*os.SyscallError)(0xc0057668e0)} when reading response body. Please retry."
level=error ts=2019-07-19T14:59:28.361Z caller=klog.go:102 component=k8s_client_runtime func=Errorf msg="Unexpected error when reading response body: &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577e480), Addr:(*net.TCPAddr)(0xc00577e4b0), Err:(*os.SyscallError)(0xc005766d40)}"
level=error ts=2019-07-19T14:59:28.361Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: Unexpected error &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577e480), Addr:(*net.TCPAddr)(0xc00577e4b0), Err:(*os.SyscallError)(0xc005766d40)} when reading response body. Please retry."
level=error ts=2019-07-19T14:59:28.361Z caller=klog.go:102 component=k8s_client_runtime func=Errorf msg="Unexpected error when reading response body: &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577e4e0), Addr:(*net.TCPAddr)(0xc00577e510), Err:(*os.SyscallError)(0xc0057671a0)}"
level=error ts=2019-07-19T14:59:28.361Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:265: Failed to list *v1.Pod: Unexpected error &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577e4e0), Addr:(*net.TCPAddr)(0xc00577e510), Err:(*os.SyscallError)(0xc0057671a0)} when reading response body. Please retry."
level=error ts=2019-07-19T14:59:28.363Z caller=klog.go:102 component=k8s_client_runtime func=Errorf msg="Unexpected error when reading response body: &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577f260), Addr:(*net.TCPAddr)(0xc00577f290), Err:(*os.SyscallError)(0xc005767600)}"
level=error ts=2019-07-19T14:59:28.363Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: Unexpected error &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577f260), Addr:(*net.TCPAddr)(0xc00577f290), Err:(*os.SyscallError)(0xc005767600)} when reading response body. Please retry."
level=error ts=2019-07-19T14:59:28.363Z caller=klog.go:102 component=k8s_client_runtime func=Errorf msg="Unexpected error when reading response body: &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577f200), Addr:(*net.TCPAddr)(0xc00577f230), Err:(*os.SyscallError)(0xc005767800)}"
level=error ts=2019-07-19T14:59:28.363Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:335: Failed to list *v1.Node: Unexpected error &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577f200), Addr:(*net.TCPAddr)(0xc00577f230), Err:(*os.SyscallError)(0xc005767800)} when reading response body. Please retry."
level=error ts=2019-07-19T14:59:28.365Z caller=klog.go:102 component=k8s_client_runtime func=Errorf msg="Unexpected error when reading response body: &net.OpError{Op:\"read\", Net:\"tcp\", Source:(*net.TCPAddr)(0xc00577fb90), Addr:(*net.TCPAddr)(0xc00577fbc0), Err:(*os.SyscallError)(0xc005767ca0)}"

```

**Comment by simonpasquier** [comment]
Can you try with `api_server: "https://kmaster.domain.de:6443"`?

**Comment by tawalaya** [comment]
Hi @simonpasquier, I work with @zergar and applied your sugjestion.
It also results in an error:
- Excerp of the Config:
```
- job_name: 'kubernetes-apiserver'
  bearer_token_file: pki/prometheus.token
  tls_config:
    ca_file: /etc/prometheus/pki/api.ca
  scheme: https
  kubernetes_sd_configs:
  - api_server: "https://kmaster.domain.de:6443"
    role: endpoints
    bearer_token_file: /etc/prometheus/pki/prometheus.token
    tls_config:
      ca_file: /etc/prometheus/pki/api.ca
      insecure_skip_verify: true
      key_file: /etc/prometheus/pki/apiserver.key
      cert_file: /etc/prometheus/pki/apiserver.crt
```
- Logs: 
```
level=error ts=2019-07-24T07:12:35.286Z caller=scrape.go:352 component="scrape manager" scrape_pool=kubernetes-services msg="creating targets failed" err="instance 0 in group endpoints/kube-system/kube-dns: \"https://kmaster.domain.de:6443\" is not a valid hostname"
`````
