### ISSUE TITLE
Prometheus subtracting 7 months from timestamp

### ISSUE THREAD

**Issue by apapsch** [prometheus/prometheus#5819]
## Bug Report

The ecommerce application Shopware has a plugin which exposes internal cronjob times. For example, these are the metrics of one cronjob in our system:

```
# HELP shopware_cronjob_end Unix timestamp of the crons end value
# TYPE shopware_cronjob_end counter
shopware_cronjob_end{cron="OrderCheckCronJob"} 1564653305
# HELP shopware_cronjob_next Unix timestamp of the crons next value
# TYPE shopware_cronjob_next counter
shopware_cronjob_next{cron="OrderCheckCronJob"} 1564653341
# HELP shopware_cronjob_start Unix timestamp of the crons start value
# TYPE shopware_cronjob_start counter
shopware_cronjob_start{cron="OrderCheckCronJob"} 1564653305
```

I'm only interested in the `shopware_cronjob_start` of the jobs and have alert rules like this:

```
time() - max(shopware_cronjob_start{cron="OrderCheckCronJob"}) > 660
```

**What did you expect to see?**

I have confirmed:

* that the cronjob really runs.
* that the metrics endpoint in the application returns a recent timestamp (time value not older than 660 seconds)
* that the instance in Prometheus is marked as up.

The alert should not fire, because the rule does not apply.

**What did you see instead? Under which circumstances?**

The alert fires.

Executing the expression `max(shopware_cronjob_start{cron="OrderCheckCronJob"})` in Prometheus frontend does not return the expected `1564653305`, but a much smaller integer which converts to a 7 month old date (e.g. `1546944905`).

I tried deleting the data directory, but the issue persists.

**Environment**

* System information:

	Linux 4.15.0-48-generic x86_64

* Prometheus version:

```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

* Prometheus configuration file:

```
rule_files:
  - /nfs/www/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'shopware'
    scrape_interval: 60s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: https
    basic_auth:
      username: xxx
      password: xxx
    static_configs:
      - targets: ['shop.xxx']
```

alert_rules.yml (excerpt, includes only the rule for the example job):

```
groups:
  - name: alert.rules
    rules:
      - alert: "CronjobNotWorking11"
        expr: "time() - max(shopware_cronjob_start{cron='OrderCheckCronJob'}) > 660"
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Cronjob OrderCheckCronJob not started"
          description: "Cronjob OrderCheckCronJob was not started in the last 11 minutes"
```
