### ISSUE TITLE
'POST' label in gathered data is not increased properly even if simple 'sum by' shows increase of metric.

### ISSUE THREAD

**Issue by amadeuszkryze** [prometheus/prometheus#5850]
## Bug Report
**What did you do?**
I'm using expression:
```
sum(increase(django_http_request_total{}[1m])) by (view, method, status)
```
on label defined in python:
```
request_total = Counter(
    'django_http_request_total',
    'Count of responses by status, view, method.',
    ['status', 'view', 'method'],
)
```
with sample from `/metrics`:
```
django_http_request_total{instance="10.0.1.56:1234",job="django-some-backend",method="POST",status="302",view="admin:accounts_user_change"} 1 1565374291412
django_http_request_total{instance="10.0.1.58:1234",job="django-some-backend",method="GET",status="200",view="admin:accounts_user_add"} 2 1565374290792
```
**What did you expect to see?**
Increase per minute of django_http_request_total with following labels: status, view, method.

**What did you see instead? Under which circumstances?**
Increase per minute of django_http_request_total with following labels: status, view, method. (ONLY GET METHOD IS INCREASED, POSTS ARE IGNORED)

**Environment**

* System information:
Ubuntu 19.04
`Linux 5.0.0-1008-aws x86_64`

* Prometheus version:
version: 2.11.1
sha: e5b22494857deca4b806f74f6e3a6ee30c251763

* Alertmanager version:
does not apply

* Prometheus configuration file:
Main:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'self'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'PROMETHEUS'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'django-ZZZ'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      match[]:
        - '{job=~"django.*"}'

    ec2_sd_configs:
      - region: ZZZ
        access_key: XXX
        secret_key: YYY
        port: 8104
        filters:
          - name: 'tag:Purpose'
            values:
              - '*MASTER'
    relabel_configs:
      - source_labels: [__address__, __meta_ec2_public_dns_name]
        action: replace
        regex: ([^:]+)(:\d+)?;([^:]+)
        replacement: $3$2
        target_label: __address__
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_instance_state]
        target_label: instance_state
      - source_labels: [__meta_ec2_instance_type]
        target_label: instance_type
      - source_labels: [__meta_ec2_private_dns_name]
        target_label: private_dns_name
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: public_dns_name
      - source_labels: [__meta_ec2_public_ip]
        target_label: public_ip
      - source_labels: [__meta_ec2_tag_Name]
        target_label: tag_Name
      - source_labels: [__meta_ec2_tag_Env]
        target_label: tag_Env
      - source_labels: [__meta_ec2_tag_Purpose]
        target_label: tag_Purpose
      - source_labels: [exported_job]
        target_label: job
```

Federated:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'PROMETHEUS'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'django-some-backend'
    dns_sd_configs:
    - names:
      - '{{ 'tasks.XXX_some-backend' }}'
      type: 'A'
      port: 1234
```

* Alertmanager configuration file:
does not apply 

* Logs:
does not apply

* Graphics:
What is shown:
![obraz](https://user-images.githubusercontent.com/37712172/62799442-17ba3d00-bae1-11e9-9f0b-c3e7a3c2b1ba.png)
What is shows without increase:
![obraz](https://user-images.githubusercontent.com/37712172/62799525-5819bb00-bae1-11e9-8627-e0ec3abf8007.png)
