### ISSUE TITLE
Promtool/Unit test issue

### ISSUE THREAD

**Issue by GuilhermeRizzottoLis** [prometheus/prometheus#5951]
## Proposal
**Use case. Why is this important?**

*Rate function in promtool unit test is not working.*

## Bug Report
**What did you do?**

I executed promtool:

`promtool test rules test.yaml`

Using this test.yml:
```
    - interval: 1m
      # Series data.
      input_series:
          - series: 'api_requests_total'
            values: '1+0x10'
      alert_rule_test:
          # Unit test 1.
          - eval_time: 1m
            alertname: LessRequestsSum
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      severity: critical
                  exp_annotations:
                        summary: "test"
                        description: "test"
```
And using this alerts.yml:
```
  - alert: LessRequestsSum
    expr: sum(rate(api_requests_total[1m])) < 10
    for: 1m
    labels:
      severity: "critical"
    annotations:
        summary: "test"
        description: "test" 
```
**What did you expect to see?**
```
Unit Testing:  test.yml
  SUCCESS
```
**What did you see instead? Under which circumstances?**
```
  FAILED:
    alertname:LessRequestsSum, time:1m0s, 
        exp:"[Labels:{alertname=\"LessRequestsSum\", severity=\"critical\"} Annotations:{description=\"test\", summary=\"test\"}]", 
        got:"[]"
```
Any ideas why is not running? I'm trying to run this since last week and did some other tests and I'm still getting the same response, I think it is a bug.
