### ISSUE TITLE
net_conntrack_dialer_conn_failed_total not correct for consul-discovery and local:9090

### ISSUE THREAD

**Issue by valdemarpavesi** [prometheus/prometheus#5968]
## Bug Report
**What did you do?**
consul enable and  static config for prometheus.

**What did you expect to see?**
should not have try tcp to prometheus with dialer_name="consul-discovery".

**What did you see instead? Under which circumstances?**

counter is wrong or should not try prometheus:9090 by consul
```
net_conntrack_dialer_conn_failed_total{dialer_name="consul-discovery",instance="localhost:9090",job="prometheus",reason="refused"} | 3081
```

**Environment**

* System information:

	insert output of `uname -srm` Linux 4.15.0-58-generic x86_64

* Prometheus version:

	insert output of `prometheus --version` prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.13beta1

* Prometheus configuration file:

```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
    - targets: ['localhost:9100']

  - job_name: consul-discovery
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    consul_sd_configs:
    - server: 'consul:8500'
      tag_separator: ','
      scheme: http
```
*Logs:

```
Service Discovery
consul-discovery (68/68 active targets)
node_exporter (1/1 active targets)
prometheus (1/1 active targets)
```
