### ISSUE TITLE
kubernetes_sd_config api_server with ip:port not vaild

### ISSUE THREAD

**Issue by wu0407** [prometheus/prometheus#5995]
## Proposal
**Use case. Why is this important?**
Special  api_server config not use default cluster env, that direct  in document is `<host>: a valid string consisting of a hostname or IP followed by an optional port number`

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
config like this：
```
kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - kube-system
    api_server: 192.168.0.13:443
```
this config is ok
```
kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - kube-system
    api_server: https://192.168.0.13:443
```

**What did you expect to see?**
config is ok
**What did you see instead? Under which circumstances?**
```
parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: parse 192.168.0.13:443: first path segment in URL cannot contain colon
```

**Environment**

* System information:

	Linux 4.15.0-33-generic x86_64

* Prometheus version:

  prometheus, version 2.12.0 (branch: HEAD, revision: 
  43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - kube-system
    api_server: 192.168.0.13:443
```

* Logs:
```
level=error ts=2019-09-07T03:53:50.439Z caller=main.go:584 msg="Error reloading config" err="couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): parsing YAML file /etc/prometheus/config_out/prometheus.env.yaml: parse 192.168.0.13:443: first path segment in URL cannot contain colon"
```
