### ISSUE TITLE
error creating HTTP client: unable to load specified CA cert

### ISSUE THREAD

**Issue by gokhandincer** [prometheus/prometheus#6015]
Hi everyone,
I'm trying to add etcd job to prometheus using consul. But i got error like below. When i try with curl is OK like this `curl -k --cacert /etc/ssl/etcd/ca.pem --cert /etc/ssl/etcd/cert.pem --key /etc/ssl/etcd/key.pem https://10.1.1.1:2379/metrics`

* System information:

	Linux 4.4.0-150-generic x86_64

* Prometheus version:

	prometheus, version 2.11.0 (branch: HEAD, revision: 4ef66003d9855ed2b7a41e987b33828ec36db34d)

* Prometheus configuration file:
```
  - job_name: ' etcd '
    scrape_interval: 30s
    metrics_path: /metrics
    honor_labels: true
    scheme: https
    tls_config:
      ca_file: /etc/ssl/etcd/ca.pem
      cert_file: /etc/ssl/etcd/cert.pem
      key_file: /etc/ssl/etcd/key.pem
      insecure_skip_verify: false
    consul_sd_configs:
      - server: '10.2.1.10:8500'
        services: ["etcd"]
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: '.*,env=([^,]+),.*'
        replacement: '${1}'
        target_label: 'env'
      - source_labels: [__meta_consul_tags]
        regex: '.*,cluster=([^,]+),.*'
        replacement: '${1}'
        target_label: 'cluster'
      - source_labels: [__meta_consul_tags]
        regex: '.*,etcd_member=([^,]+),.*'
        replacement: '${1}'
        target_label: 'etcd_member'
      - source_labels: [__meta_consul_tags]
        regex: '.*,app_name=([^,]+),.*'
        replacement: '${1}'
        target_label: 'app_name'
```

* Logs:
```
Sep 11 15:17:45 TT-PPMT-LSTFT01 prometheus[202120]: level=error ts=2019-09-11T12:17:45.511Z caller=manager.go:123 component="scrape manager" msg="error creating new scrape pool" err="error creating HTTP client: unable to load specified CA cert /etc/ssl/etcd/ca.pem
```
