### ISSUE TITLE
plot differences between record and expression

### ISSUE THREAD

**Issue by aesiliato** [prometheus/prometheus#6028]
**What did you do?**
Defined a Recording Rule:

groups:
- name: custom_metrics
  interval: 1m
  rules:
  - record: instance:spot_counter:delta
    expr: clamp_max(delta(up{lifecycle="spot",state="running"}[1m]),1)

**What did you expect to see?**
Expect to see same graph if I query the record "instance:spot_counter:delta" and the expression "clamp_max(delta(up{lifecycle="spot",state="running"}[1m]),1)" 

**What did you see instead? Under which circumstances?**
Instead I see different plots with different number of "Total time series"

![Screen Shot 2019-09-16 at 09 40 46](https://user-images.githubusercontent.com/33457435/64941726-b156d600-d867-11e9-8a61-c520d5518294.png)

![Screen Shot 2019-09-16 at 09 40 31](https://user-images.githubusercontent.com/33457435/64941743-b87de400-d867-11e9-8a4a-ea6d23492e75.png)

**Environment**

* System information:

	Linux 4.9.81-35.56.amzn1.x86_64 x86_64

* Prometheus version:

prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8

* Alertmanager version:
	NA

* Prometheus configuration file:
```
---
global:
  scrape_interval:     30s
  scrape_timeout:      30s
  evaluation_interval: 30s

  external_labels:
      monitor: ####

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "*.rules"

  - job_name: 'EMRcore_prod'
    scrape_interval: 30s
    ec2_sd_configs:
      - role_arn: #############
        region: eu-west-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Tier]
        target_label: type
      - source_labels: [__meta_ec2_tag_Tier]
        target_label: type
        regex: EMR
        action: keep
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: CORE
        action: keep
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        target_label: cluster_role
        replacement: 'core'       
      - source_labels: [__meta_ec2_instance_state]
        target_label: state
      - source_labels: [__meta_ec2_tag_Name]
        target_label: name
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: env
      - source_labels: [__meta_ec2_tag_Requester]
        target_label: requester
      - source_labels: [__meta_ec2_instance_type]
        target_label: size
      - source_labels: [__meta_ec2_private_ip]
        target_label: privateip
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_job_flow_id]
        target_label: jobflowid
      - source_labels: [__meta_ec2_tag_ApplicationName]
        target_label: project
      - source_labels: [__meta_ec2_availability_zone]
        target_label: az
      - source_labels: [__meta_ec2_tag_Scope]
        target_label: scope
      - source_labels: [__meta_ec2_tag_iCode]
        target_label: icode
      - source_labels: [__meta_ec2_tag_Lifecycle]
        target_label: lifecycle



* Alertmanager configuration file:
```
NA
```


* Logs:
```
no relevant logs
```

Thank you,
Antonio
