### ISSUE TITLE
Dynamic configuration variables in Prometheus Config

### ISSUE THREAD

**Issue by weeco** [prometheus/prometheus#6047]
Proposal
**Use case. Why is this important?**

I am setting up multiple prometheus instances to send samples to my remote write service (Cortex in that case). I need to add a variable in the `external_labels` which is unique for each prometheus instance. This is currently very cumbersome to resolve as I currently use a config map in Kubernetes. I'd be forced to create a new statefulset/deployment for each prometheus instance which then mounts a different config map for each one.

It would be nice if Prometheus supports the substitution of environment variables for that, like this:

```yaml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s
  evaluation_interval: 15s
  external_labels:
    __cluster__: cluster # This can be static as long as it's unique within the tenant's id
    __replica__: $POD_NAME
remote_write:
  - url: http://xy
    bearer_token_file: "/etc/secrets/bearer_token.txt"
    queue_config:
      capacity: 1000
      max_shards: 20
      max_samples_per_send: 1000
```

This has already been suggested in https://github.com/prometheus/prometheus/issues/2357 , but I hope this usecase and the clear community feedback given in #2375 makes a difference so that you reconsider this feature request.
