### ISSUE TITLE
log.level is set but not picked up #2

### ISSUE THREAD

**Issue by walterdolce** [prometheus/prometheus#6049]
## Bug Report
**What did you do?**
Run Prometheus within Kubernetes

**What did you expect to see?**
Prometheus to produce different log outputs depending on the flag used (`debug`, `info`, etc)

**What did you see instead? Under which circumstances?**
Prometheus logs stuff only when `info` is provided. Every other flag causes Prometheus to output the same thing.

**Environment**
GKE.
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.8-gke.10", GitCommit:"f53039cc1e5295eed20969a4f10fb6ad99461e37", GitTreeState:"clean", BuildDate:"2019-06-19T20:48:40Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

* System information:
```
/prometheus $ uname -srm
Linux 4.14.127+ x86_64
```

* Prometheus version:
```
/prometheus $ prometheus --version
prometheus, version 2.11.1 (branch: HEAD, revision: e5b22494857deca4b806f74f6e3a6ee30c251763)
  build user:       root@d94406f2bb6f
  build date:       20190710-13:51:17
  go version:       go1.12.7
```

* Alertmanager version:
N/A

* Prometheus configuration file:
```
---
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 60s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: alertmanager
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'alertmanager:9093'
  - job_name: kubernetes-cadvisor
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: https  # remove if you want to scrape metrics on insecure port
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    metric_relabel_configs:
      - action: replace
        source_labels: [id]
        regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
        target_label: rkt_container_name
        replacement: '${2}-${1}'
      - action: replace
        source_labels: [id]
        regex: '^/system\.slice/(.+)\.service$'
        target_label: systemd_service_name
        replacement: '${1}'
  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc.cluster.local:443
      - target_label: __scheme__
        replacement: https
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
```

* Alertmanager configuration file:
N/A

* Logs:
The following logs are produced regardless of the flag that is passed:
```
level=info ts=2019-09-24T11:18:53.438Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.1, branch=HEAD, revision=e5b22494857deca4b806f74f6e3a6ee30c251763)"
level=info ts=2019-09-24T11:18:53.438Z caller=main.go:330 build_context="(go=go1.12.7, user=root@d94406f2bb6f, date=20190710-13:51:17)"
level=info ts=2019-09-24T11:18:53.439Z caller=main.go:331 host_details="(Linux 4.14.127+ #1 SMP Tue Jun 18 23:08:40 PDT 2019 x86_64 prometheus-54c9f5d9b7-2tfkf (none))"
level=info ts=2019-09-24T11:18:53.439Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-09-24T11:18:53.439Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-09-24T11:18:53.440Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2019-09-24T11:18:53.440Z caller=web.go:448 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-09-24T11:18:53.467Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1568217587170 maxt=1568217600000 ulid=01DMGV4AD51ZG9YXGMQY8E4BC4
level=info ts=2019-09-24T11:18:53.479Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1568714400000 maxt=1568721600000 ulid=01DMZMXVFAQHM57XHX1JK9HSC9
level=info ts=2019-09-24T11:18:53.506Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1568721600000 maxt=1568728800000 ulid=01DMZVSJH3RRHVHRC40NEJF5P7
```

This is the deployment I am using:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  annotations:
    configmap.reloader.stakater.com/reload: prometheus-alerting-rules,prometheus-config
    kube-score/ignore: pod-networkpolicy,container-security-context
  labels:
    app_name: prometheus
    app_type: monitoring
    component: prometheus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app_name: prometheus
      app_type: monitoring
      component: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app_name: prometheus
        app_type: monitoring
        component: prometheus
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app_name: prometheus
                  app_type: monitoring
                  component: prometheus
      serviceAccountName: prometheus
      initContainers:
        - name: prometheus-data-folder-permissions-fixer
          image: prom/prometheus:v2.11.1
          imagePullPolicy: Always
          command:
            - "sh"
          args:
            - "-c"
            - "chown -R 10001:10002 /prometheus/data"
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 100m
              memory: 40Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - mountPath: /prometheus/data
              name: prometheus-data-disk
              readOnly: false
      containers:
        - name: prometheus
          image: prom/prometheus:v2.11.1
          imagePullPolicy: Always
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 10001
            runAsGroup: 10002
          readinessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 2
            timeoutSeconds: 1
            periodSeconds: 5
            httpGet:
              port: 9090
              path: /-/ready
          livenessProbe:
            initialDelaySeconds: 1
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              port: 9090
              path: /-/healthy
          command:
            - prometheus
          args:
            - "--alertmanager.notification-queue-capacity=10000"
            - "--alertmanager.timeout=10s"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--log.format=logfmt"
            - "--log.level=debug"
            - "--query.lookback-delta=5m"
            - "--query.max-concurrency=40"
            - "--query.max-samples=50000000"
            - "--query.timeout=2m"
            - "--rules.alert.for-grace-period=10m"
            - "--rules.alert.for-outage-tolerance=1h"
            - "--rules.alert.resend-delay=1m"
            - "--storage.remote.read-concurrent-limit=10"
            - "--storage.remote.read-sample-limit=5e7"
            - "--storage.tsdb.no-lockfile"
            - "--storage.tsdb.path=/prometheus/data/"
            - "--storage.tsdb.retention.time=365d"
            - "--web.console.libraries=/etc/prometheus/console_libraries"
            - "--web.console.templates=/etc/prometheus/consoles"
            - "--web.external-url=http://prometheus-frontend/"
            - "--web.max-connections=512"
            - "--web.read-timeout=1m"
            - "--web.route-prefix=/"
          resources:
            requests:
              cpu: 250m
              memory: 300Mi
            limits:
              cpu: 1
              memory: 3Gi
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - mountPath: /etc/prometheus/rules
              name: prometheus-alerting-rules
              readOnly: true
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config
              readOnly: true
              subPath: prometheus.yml
            - mountPath: /prometheus/data
              name: prometheus-data-disk
              readOnly: false
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: prometheus-alerting-rules
          configMap:
            name: prometheus-alerting-rules
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prometheus-data-disk
          persistentVolumeClaim:
            claimName: prometheus-data-disk
```

The disk is a GCP persistent disk. The alerting rules can be empty. The `prometheus-frontend` points to a reverse-proxy'd service. All of these can be removed and the end result should be the same.

This is the RBAC stuff that is in use:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
```

Any question or more info required please let me know. Thanks in advance!
