### ISSUE TITLE
rate() works unpredictably with monotonically increasing counters.

### ISSUE THREAD

**Issue by snawaz** [prometheus/prometheus#6091]
## Bug Report

I wrote few simple tests to understand the behavior of `rate()` so that I could write more complex tests for my actual use cases. However, `rate()` works unpredictably with input having [_monotonically increasing_][1] counters.

[1]: https://en.wiktionary.org/wiki/monotonic_increasing

```yaml
tests:
  - interval: 1m
    input_series:
        - series: my_requests_total
          values: 1 2 3 3 4 4 5  # monotonic increasing
                # 0 1 2 3 4 5 6  <- timestamps
    promql_expr_test:
        # - expr: rate(my_requests_total[5m]) 
        #   eval_time: 0m
        #   exp_samples: 
        #     - labels: '{}'
        #       value: 0.0033333333333333335   # my expection (1.0-0.0)/300, but promtool says it is `nil`.. but then if I use it, promtool fails as it cannot parse it as float64
        - expr: rate(my_requests_total[5m]) 
          eval_time: 1m
          exp_samples: 
            - labels: '{}'
              value: 0.006666666666666667      # (2.0-0.0)/300 = 0.006666666666666667
        - expr: rate(my_requests_total[5m]) 
          eval_time: 2m
          exp_samples: 
            - labels: '{}'
              value: 0.01                      # (3.0-0.0)/300 = 0.01
        - expr: rate(my_requests_total[5m]) 
          eval_time: 3m
          exp_samples: 
            - labels: '{}'
              #value: 0.01                     # this is what I had expected, as the value has not changed it should be 3.0/300. However, it fails! 
              value: 0.007777777777777778      # works, but how could I possibly compute this value? 
        - expr: rate(my_requests_total[5m]) 
          eval_time: 4m
          exp_samples: 
            - labels: '{}'
             #value: 0.013333333333333334      # I expected to be (4.0-0.0)/300 = 0.013333333333333334
              value: 0.0125                    # But this works, which I dont know how to compute
        - expr: rate(my_requests_total[5m]) 
          eval_time: 5m
          exp_samples: 
            - labels: '{}'
              value: 0.01                      # (4.0-1.0) = 3.0/300 = 0.01
        - expr: rate(my_requests_total[5m])   
          eval_time: 6m
          exp_samples: 
            - labels: '{}'
              value: 0.01                      # (5.0-2.0) = 3.0/300 = 0.01 
```

Save this in ` issue-test.yaml` and evaluate it using `promtool`:

```bash
$ promtool test rules issue-test.yaml
Unit Testing:  issue-test.yaml
  SUCCESS
$ 
``` 

However, as mentioned in the comments, I had expected different values corresponds to `evaI_time` = `0m`, `3m` and `4m`.   But they didn't work, so I took the values from the `promtool` errors and used them instead which of course worked. However, I can't justify these values, because I dont know how to compute them. It seems highly unpredictable, **and nowhere in the docs, any such gotchas has been explained**. 

**So what actually scares me is that if I can't reason about such simple tests, how could I possibly write the complex ones?** 

If I use _strictly increasing_ counters such as `values: 1 2 3 4 5 6`, then the way I carried out my computation works. 

---

### `promtool` version

```bash
$ promtool --version
promtool, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-14:00:28
  go version:       go1.12.8
$ 
```
