### ISSUE TITLE
promtool check config complains about missing region in EC2 SD config

### ISSUE THREAD

**Issue by guidodobboletta** [prometheus/prometheus#6092]
**Use case. Why is this important?**

I want to validate my prometheus configuration file

## Bug Report
**What did you do?**

I run `promtool check config` against my `prometheus.yml` and got an error saying:

```
Checking packer/files/prometheus/config/prometheus.yml
  FAILED: parsing YAML file packer/files/prometheus/config/prometheus.yml: EC2 SD configuration requires a region
```

**What did you expect to see?**

I expected to see no errors as not having a region in the EC2 SD configuration is supported. Per the documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config 

`# The AWS region. If blank, the region from the instance metadata is used.`

**Environment**

* System information:

	Linux 4.15.0-65-generic x86_64

* Prometheus version:
```
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```

* Prometheus configuration file:
```
global:
  scrape_interval: 10s

rule_files:
  - 'alerts/*.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - port: 9090
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: prometheus
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_tag_Environment]
        target_label: environment
```

**Comment by simonpasquier** [comment]
The reason is that the code deserializing the YAML data queries the EC2 metadata service to get the region thus it will fail if `promtool` isn't executed from an EC2 instance. One could argue that it shouldn't be done at this stage.

https://github.com/prometheus/prometheus/blob/53ea6d63901b96a13bb79ff598c96af4a979adce/discovery/ec2/ec2.go#L91-L102

**Comment by guidodobboletta** [comment]
Is it possible to add a workaround such as passing the region via a CLI flag? For my use case I want to validate the configuration before building our Prometheus AMI via `pre-commit` hooks. 

Right now I'm able to validate my Alertmanager configuration and Prometheus alert rules so this would be a very nice to have for our needs.

**Comment by farrellit** [comment]
The only thing I have come up with to solve this problem is to run a local webserver on 169.254.169.254 (on localhost interface) and have it serve an availability zone on the endpoint.

**Comment by gouthamve** [comment]
We went through this issue in our bug scrub and we're not sure how to best deal with this, one approach is to move this check out of the config check, and maybe print a warning. `Pmaybe` because the semantics are not obvious.

**Comment by guidodobboletta** [comment]
I would move the check outside of the configuration check. A small warning mentioning that no region is defined and maybe a link to the ec2_sd_config would be useful in my opinion @gouthamve

**Comment by brian-brazil** [comment]
That's pretty close to silently failing though.

**Comment by guidodobboletta** [comment]
How about adding the option to specify the region when invoking `promtool check config`. If no region is specified by the user then fail like we do right now @brian-brazil

**Comment by roidelapluie** [comment]
Can't you specify it with an env variable in this case?

**Comment by guidodobboletta** [comment]
How @roidelapluie ? I don't see any mentions of env variables on https://prometheus.io/docs/prometheus/latest/configuration/configuration/#ec2_sd_config

**Comment by roidelapluie** [comment]
I have checked the code and while we could possibly get the token from Env as a side effect of the imports, we explicitely check for a region indeed.

**Comment by guidodobboletta** [comment]
Should we close this issue then? @roidelapluie

**Comment by roidelapluie** [comment]
No, this feature request is valid. We should be able to validate the file. I will comment me in a few hours.

**Comment by michaelfward** [comment]
Not sure if this is related, but I have a region defined in my configuration and am getting the same error re: requiring a region. 

```
- job_name: 'flower'
  ec2_sd_configs:
    - region: 'us-west-2'
    - port: 5555
    - filters:
      - name: 'env'
      - values: 'celery'
```

**Comment by roidelapluie** [comment]
> Not sure if this is related, but I have a region defined in my configuration and am getting the same error re: requiring a region.
> 
> ```
> - job_name: 'flower'
>   ec2_sd_configs:
>     - region: 'us-west-2'
>     - port: 5555
>     - filters:
>       - name: 'env'
>       - values: 'celery'
> ```

Your configuration is invalid. Please see:

```
- job_name: 'flower'
  ec2_sd_configs:
    - region: 'us-west-2'
      port: 5555
      filters:
      - name: 'env'
        values: 'celery'
```

**Comment by DavidHe1127** [comment]
Any updates on this? I ran into the same issue when starting up Prometheus on a `IMDSv2` enabled EC2 instance.

**Comment by brian-brazil** [comment]
What we should do here is move this to inside the SD. We shouldn't be making network calls at the parsing a configuration file stage.

**Comment by DavidHe1127** [comment]
> > Any updates on this? I ran into the same issue when starting up Prometheus on a `IMDSv2` enabled EC2 instance.
> 
> Is your issue with `prometheus` or `promtool`? Are you able to provide more details and open a new issue if the problem is not the same as the one in this issue. Thanks.

@roidelapluie Hey. thanks for coming back to me. I've got my problem solved. Although it's the same issue as @guidodobboletta's, my one is caused by wrong syntax. However, the message is misleading...

❌
```
    ec2_sd_configs:
      - region: ap-southeast-2
      - filters:
        - name: "tag:aws:cloudformation:stack:name"
          values:
            - io-210-imds-prometheus*
```

✅
```
    ec2_sd_configs:
      - region: ap-southeast-2
        filters:
          - name: "tag:aws:cloudformation:stack:name"
            values:
              - io-210-imds-prometheus*
```
