### ISSUE TITLE
Prometheus cannot connect to Consul using consul_sd_configs

### ISSUE THREAD

**Issue by ILoveYaToo** [prometheus/prometheus#6131]
## Bug Report
**What did you do?**
Enabled Consul support on Prometheus inside Kubernetes

**What did you expect to see?**
Prometheus scraping using consul_sd_configs

**What did you see instead? Under which circumstances?**
Prometheus cannot reach Consul. If the docker container is entered, Consul can be reached, so this is not likely a networking issue.

**Environment**

* System information:

Running in k8s with EKS

* Prometheus version:

```
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```

* Prometheus configuration file:
```
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: <namespace>/prometheus-external-promet-prometheus
    prometheus_replica: prometheus-prometheus-external-promet-prometheus-0
rule_files:
- /etc/prometheus/rules/prometheus-prometheus-external-promet-prometheus-rulefiles-0/*.yaml
scrape_configs:
- job_name: <namespace>/prometheus-external-promet-grafana/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - <namespace>
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: grafana
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_release
    regex: prometheus-external
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: service
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: service
- job_name: <namespace>/prometheus-external-promet-prometheus/0
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - <namespace>
  metrics_path: /metrics
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_app
    regex: prometheus-operator-prometheus
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_release
    regex: prometheus-external
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: web
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Node;(.*)
    replacement: ${1}
    target_label: node
  - source_labels:
    - __meta_kubernetes_endpoint_address_target_kind
    - __meta_kubernetes_endpoint_address_target_name
    separator: ;
    regex: Pod;(.*)
    replacement: ${1}
    target_label: pod
  - source_labels:
    - __meta_kubernetes_namespace
    target_label: namespace
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: service
  - source_labels:
    - __meta_kubernetes_pod_name
    target_label: pod
  - source_labels:
    - __meta_kubernetes_service_name
    target_label: job
    replacement: ${1}
  - target_label: endpoint
    replacement: web
- consul_sd_configs:
  - datacenter: <consul dc>
    server: <loadbalancer pointing to multiple consul servers>:8500
    token: <token>
  job_name: Stats-test
  relabel_configs:
  - action: keep
    regex: .*scrape-.*
    source_labels:
    - __meta_consul_tags
  - replacement: ${1}:9273
    source_labels:
    - __meta_consul_address
    target_label: __address__
alerting:
  alert_relabel_configs:
  - action: labeldrop
    regex: prometheus_replica
  alertmanagers: []
```

* Logs:
```
level=info ts=2019-10-11T20:45:07.602Z caller=main.go:740 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-11T20:45:07.604Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2019-10-11T20:45:07.620Z caller=main.go:768 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-11T20:45:07.620Z caller=main.go:740 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2019-10-11T20:45:07.622Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2019-10-11T20:45:07.631Z caller=endpoints.go:131 component="discovery manager scrape" discovery=k8s role=endpoint msg="endpoints informer unable to sync cache"
level=error ts=2019-10-11T20:45:07.633Z caller=consul.go:361 component="discovery manager scrape" discovery=consul msg="Error refreshing service list" err="Get http://<loadbalancer pointing to multiple consul servers>:8500/v1/catalog/services?dc=<consul dc>&stale=&wait=30000ms: context canceled"
level=info ts=2019-10-11T20:45:07.669Z caller=main.go:768 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
```
