### ISSUE TITLE
ARMv7 nil pointer at startup

### ISSUE THREAD

**Issue by part1zan** [prometheus/prometheus#6147]
# Bug Report
**What did you do?**
Run docker container from prom/prometheus:v2.13.0 image
Run downloaded prometheus-2.13.0.linux-armv7

**What did you expect to see?**
Prometheus run normally

**What did you see instead? Under which circumstances?**
level=info ts=2019-10-16T21:41:24.596Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-10-16T21:41:24.596Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.0, branch=HEAD, revision=6ea4252299f542669aca11860abc2192bdc7bede)"
level=info ts=2019-10-16T21:41:24.597Z caller=main.go:333 build_context="(go=go1.13.1, user=root@f30bdad2c3fd, date=20191004-12:23:30)"
level=info ts=2019-10-16T21:41:24.597Z caller=main.go:334 host_details="(Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l onemanagement (none))"
level=info ts=2019-10-16T21:41:24.597Z caller=main.go:335 fd_limits="(soft=1024, hard=1048576)"
level=info ts=2019-10-16T21:41:24.598Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-10-16T21:41:24.614Z caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2019-10-16T21:41:24.614Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-10-16T21:41:24.661Z caller=head.go:512 component=tsdb msg="replaying WAL, this may take awhile"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x12464]

goroutine 207 [running]:
github.com/prometheus/prometheus/tsdb.(*Head).MinTime(...)
	/app/tsdb/head.go:1172
github.com/prometheus/prometheus/tsdb.(*Head).updateMinMaxTime(0x4742210, 0xffffffff, 0x7fffffff, 0x0, 0x80000000)
	/app/tsdb/head.go:306 +0x2c
github.com/prometheus/prometheus/tsdb.(*Head).processWALSamples(0x4742210, 0x0, 0x80000000, 0x48858c0, 0x4885840, 0x0, 0x0)
	/app/tsdb/head.go:299 +0x484
github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x4742210, 0x480a150, 0x480a160, 0x48858c0, 0x4885840)
	/app/tsdb/head.go:359 +0x3c
created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
	/app/tsdb/head.go:358 +0x160

**Environment**

* System information:

	Linux 4.19.66-v7+ armv7l

* Prometheus version:

	prometheus, version 2.13.0 (branch: HEAD, revision: 6ea4252299f542669aca11860abc2192bdc7bede)
  build user:       root@f30bdad2c3fd
  build date:       20191004-12:23:30
  go version:       go1.13.1

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rasp host' 
      static_configs:
        - targets: ['192.168.250.99:9100']

  - job_name: 'gitlab host'
      static_configs:
       - targets: ['192.168.250.98:9100']
```
