### ISSUE TITLE
Incorrect Data reported when querying Prometheus directly, but not when federated

### ISSUE THREAD

**Issue by Throckmortra** [prometheus/prometheus#6183]
## Bug Report
**What did you do?**
I have a prometheus server in a client environment that federates to a larger Prometheus that I intend to use for larger queries.

**What did you expect to see?**
I expect the data to be mostly consistent between these two Prometheus servers because it is the same data, but I understand that there is a margin of error because the smaller Prometheus is closer to the monitored servers.

**What did you see instead? Under which circumstances?**
When querying for CPU:
`(sum(irate(node_cpu_seconds_total{instance="xxx",job="aws"}[5m])) by (mode) * 100 / count(node_cpu_seconds_total{instance="xxx",job="aws"}) by (mode)or network`

I am getting incorrect(impossible) data from the smaller Prometheus. But the larger Prometheus gets correct data. The larger prometheus does not have any connectivity to the monitored servers. All of its queries are coming in from the /federate on the smaller Prometheus. 

when querying the small server and getting unreal data: 
[![Screen-Shot-2019-10-18-at-11-31-06-AM.png](https://i.postimg.cc/bwqPjbZx/Screen-Shot-2019-10-18-at-11-31-06-AM.png)](https://postimg.cc/SJ136n7R)

when querying the big server and getting correct data: 
[![Screen-Shot-2019-10-18-at-11-39-41-AM.png](https://i.postimg.cc/9MYSbgBs/Screen-Shot-2019-10-18-at-11-39-41-AM.png)](https://postimg.cc/WFtXbnC7)

What's more, with an aggregate grafana dashboard, I can actually see that the data is correct for a subset of servers on the small prometheus:
[![Screen-Shot-2019-10-18-at-11-43-38-AM.png](https://i.postimg.cc/Jh6KhwPr/Screen-Shot-2019-10-18-at-11-43-38-AM.png)](https://postimg.cc/2qWnHKsM)

big prometheus:
[![Screen-Shot-2019-10-18-at-11-44-45-AM.png](https://i.postimg.cc/Qxm7DQ6s/Screen-Shot-2019-10-18-at-11-44-45-AM.png)](https://postimg.cc/vc1TLVFS)

**Environment**

* System information:

small: Linux 4.14.138-114.102.amzn2.x86_64 x86_64
large: Linux 4.14.138-114.102.amzn2.x86_64 x86_64

* Prometheus version:
same for both: 

> prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
>   build user:       root@7a9dbdbe0cc7
>   build date:       20190818-13:53:16
>   go version:       go1.12.8

* Prometheus configuration file:
Small: 
```
#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: redacted

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - redacted
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

  - ec2_sd_configs:
      - region: us-east-2
        port: 9100
    job_name: aws
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: redacted
    metrics_path: /metrics
    ec2_sd_configs:
      - region: us-east-2
        port: 14040
        filters:
         - name: tag-key
           values:
             - redacted
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
```

Large: 
```
#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: global

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - redacted
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

  - job_name: aws
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: redacted
    metrics_path: /metrics
    ec2_sd_configs:
      - region: us-east-2
        port: 14040
        filters:
          - name: tag-key
            values:
              - redacted
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: 'federate'
    scheme: https
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="aws"}'
        - '{job="redacted"}'
        - '{__name__=~"job:.*"}'
    static_configs:
      - targets:
        - 'small-prometheus.redacted'
```
