### ISSUE TITLE
Unable to set the storage retention via config file

### ISSUE THREAD

**Issue by capttrousers** [prometheus/prometheus#6188]
## Proposal
I'd expect to be able to set the storage retention config via the file.
I'm running Prometheus via docker so to have to rebuild and run the image to get the right command with the CLI arguments is a pain. I can update the config file and copy it in and sighup the container easily. 

**Environment**
Docker
Prometheus latest image

* System information:
```
pi@raspberrypi:~/code/monitoring/prometheus $ uname -srm
Linux 4.19.57-v7l+ armv7l
```
* Prometheus version:
```
pi@raspberrypi:~/code/monitoring/prometheus $ docker exec prometheus-rpi /bin/prometheus --version
prometheus, version 2.11.1 (branch: HEAD, revision: e5b22494857deca4b806f74f6e3a6ee30c251763)
  build user:       root@d94406f2bb6f
  build date:       20190710-14:43:39
  go version:       go1.12.7
```

* Prometheus configuration file:
```
pi@raspberrypi:~/code/monitoring/prometheus $ cat prometheus.yml 
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

storage.tsdb.retention.time: 150d # i expected this to work

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'rpione'
    static_configs:
      - targets: ['192.168.0.11:9100']

```

**Comment by juliusv** [comment]
@capttrousers Why not just start the same Docker container with different retention flags? Normally there should be no rebuild required.

For background: all settings that Prometheus supports to change / reload during runtime are in the configuration file. All other settings for which this is not yet supported have to be flags.

**Comment by simonpasquier** [comment]
> I'm running Prometheus via docker so to have to rebuild and run the image to get the right command with the CLI arguments is a pain. 

As Julius already wrote, you should be able to do `docker run quay.io/prometheus/prometheus --storage.tsdb.retention.time=12d --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles`. Just make sure to pass all the flags specified in the upstream Dockerfile.

Changing the retention on the fly would require to stop most of the components (rule engine, query engine, scrapers ...), close/re-open the local TSDB and finally start again the components. It would complicate a lot the code IMO.

**Comment by krasi-georgiev** [comment]
yep I agree with Smon and Julius. Closing now, but feel free to reopen if you have anymore questions.

**Comment by farrellit** [comment]
as a user of the docker container, I have to duplicate the settings that were already provided to the container in the `CMD` entry of the Dockerfile, to be able to add them.  That's why I wish this setting - and every setting - could be specified in the config file.  

https://github.com/prometheus/prometheus/blob/master/Dockerfile#L26

**Comment by roidelapluie** [comment]
Hi there o/

Two rules would prevent us to do that:

1. What is in the config file is hot reloadable. Those settings are not.
2. We configure things at only one place and don't break existing users.

If you still have questions please refer to the prometheus-users mailing list.

**Comment by CristianT** [comment]
Alternatively if you are using compose you can specify the command line for the container, here is an example:

```
    prometheus:
      image: prom/prometheus:v2.17.2
      ports:
        - "9090:9090"
      container_name: prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=1y'
        - '--web.enable-lifecycle'
      hostname: prometheus
      volumes:
        - type: bind
          source: ./config/prometheus.yml
          target: /etc/prometheus/prometheus.yml
          read_only: true
        - prometheus:/prometheus
```
