### ISSUE TITLE
Prometheus drops samples with out-of-order timestamps.

### ISSUE THREAD

**Issue by mobidyc** [prometheus/prometheus#6241]
## Bug Report
**What did you do?**

Using /federate to scrape metrics on all prometheus instances .

Servers NTP synced.

Not using docker

Even with "honor_timestamps" set to True, it should not impact the order.

If it is recommended to disable honor_timestamps with Federation, This is something to add in the documentation.

**What did you expect to see?**

No errors concerning the timestamps.

**What did you see instead? Under which circumstances?**

```
prometheus_target_scrapes_sample_out_of_order_total{job="prometheus"}
--|--
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-conn-0:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-conn-1:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-conn-2:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-store-0:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-store-1:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-store-2:9090",job="prometheus"} | 0
prometheus_target_scrapes_sample_out_of_order_total{instance="prom-test-super:9090",job="prometheus"} | 109893
```

There is no noticeable difference between the prometheus instances (below millisecond).
```
abs(node_timex_offset_seconds)
-- | --
{instance="prom-test-conn-0:9100",job="node_exporter"} | 0.000217332
{instance="prom-test-conn-1:9100",job="node_exporter"} | 0.001760546
{instance="prom-test-conn-2:9100",job="node_exporter"} | 0.00124347
{instance="prom-test-store-0:9100",job="node_exporter"} | 0.000442501
{instance="prom-test-store-1:9100",job="node_exporter"} | 0.000077351
{instance="prom-test-store-2:9100",job="node_exporter"} | 0.000318905
{instance="prom-test-super:9100",job="node_exporter"} | 0
```

Servers are well NTP synced.
```
node_timex_sync_status
-- | --
node_timex_sync_status{instance="prom-test-conn-0:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-conn-1:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-conn-2:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-store-0:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-store-1:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-store-2:9100",job="node_exporter"} | 1
node_timex_sync_status{instance="prom-test-super:9100",job="node_exporter"} | 1
```

**Environment**

* System information:

	insert output of `uname -srm` here

`Linux 3.10.0-514.2.2.el7.x86_64 x86_64`

* Prometheus version:

	insert output of `prometheus --version` here
```
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1
```

* Prometheus configuration file:
```
# cat prometheus.yml 
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - prom-test-super:9093
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /home/prometheus/prometheus/rules/node.yml
- /home/prometheus/prometheus/rules/prometheus.yml
scrape_configs:
- job_name: f_prometheus
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{job="prometheus"}'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  file_sd_configs:
  - files:
    - /home/prometheus/prometheus/jobs/federate.yml
    refresh_interval: 10m
- job_name: prometheus
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /home/prometheus/prometheus/jobs/prometheus.yml
    refresh_interval: 10m
- job_name: f_node_exporter
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{job="node_exporter"}'
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /federate
  scheme: http
  file_sd_configs:
  - files:
    - /home/prometheus/prometheus/jobs/federate.yml
    refresh_interval: 10m
- job_name: node_exporter
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /home/prometheus/prometheus/jobs/node_exporter.yml
    refresh_interval: 10m
```

`/home/prometheus/prometheus/jobs/federate.yml` contains all hosts.

`/home/prometheus/prometheus/jobs/node_exporter.yml` and `/home/prometheus/prometheus/jobs/prometheus.yml` contain the local hostname of the host.

* Logs:
```
oct. 28 14:53:29 prom-test-super.localdomain prometheus[1022]: level=warn ts=2019-10-28T14:53:29.766Z caller=scrape.go:1164 component="scrape manager" scrape_pool=f_node_exporter target="http://prom-test-super:9090/federate?match%5B%5D=%7Bjob%3D%22node_exporter%22%7D" msg="Error on ingesting out-of-order samples" num_dropped=165
oct. 28 14:53:44 prom-test-super.localdomain prometheus[1022]: level=warn ts=2019-10-28T14:53:44.739Z caller=scrape.go:1164 component="scrape manager" scrape_pool=f_node_exporter target="http://prom-test-super:9090/federate?match%5B%5D=%7Bjob%3D%22node_exporter%22%7D" msg="Error on ingesting out-of-order samples" num_dropped=183
```
