### ISSUE TITLE
Prometeus drops offset parameter in alert rule.

### ISSUE THREAD

**Issue by amadeuszkryze** [prometheus/prometheus#6245]
## Bug Report
**What did you do?**
Created alert rule with offset parameter to compare metrics with 1 and 7days
**What did you expect to see?**
Alert with offset rule.
**What did you see instead? Under which circumstances?**
Alert without offset rule.
**Environment**

* System information:
```
official docker prometheus image
```
* Prometheus version:
` 2.13.0`
* Alertmanager version:
`0.19.0`
* Prometheus configuration file:
```
groups:  
  - name: AWS/SQS
    rules:
      - alert: SQS deviation from the average on consumptions between 1d                                                       
        expr: sum(avg_over_time(aws_sqs_number_of_messages_sent_sum{queue_name=~"parse-queue-[a-z]*"}[30m:])) by (queue_name) /
sum(avg_over_time(aws_sqs_number_of_messages_sent_sum{queue_name=~"parse-queue-[a-z]*"}[30m:] offset 1d)) by (queue_name) < 0.20
        for: 2m
        labels:
          severity: critical
          type: aws/sqs
          env: prod
        annotations:
          identifier: '{{ $labels.queue_name }}'
          value: '{{ $value | humanizeDuration }}'
      - alert: SQS deviation from the average on consumptions between 7d                                                       
        expr: sum(avg_over_time(aws_sqs_number_of_messages_sent_sum{queue_name=~"parse-queue-[a-z]*"}[30m:])) by (queue_name) /
sum(avg_over_time(aws_sqs_number_of_messages_sent_sum{queue_name=~"parse-queue-[a-z]*"}[30m:] offset 1d)) by (queue_name) < 0.20
        for: 2m
        labels:
          severity: critical
          type: aws/sqs
          env: prod
        annotations:
          identifier: '{{ $labels.queue_name }}'
          value: '{{ $value | humanizeDuration }}'
```

* Alertmanager configuration file:
```
---
```
No logs related to this issue
```
---
```

Image from prom alerts (lack of offset):
![image](https://user-images.githubusercontent.com/37712172/67764531-7d67f680-fa4a-11e9-99f5-889300724ebe.png)
