### ISSUE TITLE
alert stays always pending

### ISSUE THREAD

**Issue by izenk** [prometheus/prometheus#6258]
## Bug Report
**What did you do?**
Added alert rule for metric

**What did you expect to see?**
Alert should be generated acording to configuration

**What did you see instead? Under which circumstances?**
Alert is always pending

**Environment**
Ubuntu 16.04
docker image: prom/prometheus:v2.12.0
* Prometheus version:
```
prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
```

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - "alerting_rules/dev/*.rule"
```
Alert rule
```
groups:
- name: billing_lag
  rules:
  - alert: BillingLag
    expr: billing_lag_count{is_replica="0"} > 0
    for: 4h
    labels:
      severity_int: 1
      severity: warning
```

If I check metric directly in Prometheus GRAPH UI using expr: billing_lag_count{is_replica="0"}[8h]
I see this
![image](https://user-images.githubusercontent.com/6417697/68026108-ab09a580-fcbf-11e9-83dc-04ad127fcbde.png)

So it looks like in some periods metric was missed.
But if I use the same query (billing_lag_count{is_replica="0"}[8h]) in prometheus CONSOLE UI and then check missed periods - I can see that metrics is always presented. Every 15s (scrape interval) metric is there.

So two questions
1) Why prometheus graph shows missed intervals, but prometheus console no.
2) Why alert is always in pending state.
