### ISSUE TITLE
Testing alert rule brings about unexpected evaluation behaviour

### ISSUE THREAD

**Issue by walterdolce** [prometheus/prometheus#6260]
## Bug Report
**What did you do?**
I have the following test case (inspired by [RobustPerception's blog post](https://www.robustperception.io/get-alerted-before-your-ssl-certificates-expire)), which is bringing about unexpected behaviour.

```
groups:
- name: ssl-certificates
  rules:
  - alert: SSLCertificateExpiringIn2Weeks
    expr: ((probe_ssl_earliest_cert_expiry{domain=~"https.*"} - time()) < (86400 * 14))
    for: 1m
    labels:
      severity: warning
      environment: some_environment
    annotations:
      summary: The summary
      description: The description
```

And the relevant test file:
```
---
rule_files:
  - ../rules/ssl-certificates-alerts.yml
evaluation_interval: 1m
tests:
  - input_series:
      - series: probe_ssl_earliest_cert_expiry{domain="https://example.com"}
        # 1209660 triggers alert
        # 1209659 does not trigger alert
        values: '1209659'
    alert_rule_test:
      - eval_time: 2m
        alertname: SSLCertificateExpiringIn2Weeks
        exp_alerts:
        - exp_labels:
            severity: warning
            environment: some_environment
            domain: 'https://example.com'
          exp_annotations:
            summary: The summary
            description: The description
```

Unless I am missing something (which could easily be the case, I find the way one defines tests for alerting rules complex and a little bit cryptic; I am honestly never sure whether I'm doing it right or not), I don't understand why `1209660` triggers the alert and `1209659` does not.

Shouldn't I provide timestamp values? 

I was initially providing `1573464347`, which in relative unix timestamp means "in 10 days" (less than 2 weeks). But this does not bring about any alert and I fail to understand why.

**What did you expect to see?**
See above

**What did you see instead? Under which circumstances?**
See above

**Environment**
* System information:
```Darwin 19.0.0 x86_64```

* Prometheus version:
```
prometheus, version 2.13.1 (branch: non-git, revision: non-git)
  build user:       brew@Catalina.local
  build date:       20191018-01:35:32
  go version:       go1.13.1
```

And:
```
promtool, version 2.13.1 (branch: non-git, revision: non-git)
  build user:       brew@Catalina.local
  build date:       20191018-01:35:32
  go version:       go1.13.1
```

* Alertmanager version:
N/A

* Prometheus configuration file:
N/A

* Alertmanager configuration file:
N/A

* Logs:
N/A

**Comment by simonpasquier** [comment]
This is because of the `for` clause. If you set it to `59s` or evaluate the alert at `3m` then the alert fires. 
I'm closing it for now. If you have further questions, please use our [user mailing list](https://groups.google.com/forum/#!forum/prometheus-users), which you can also search.

**Comment by walterdolce** [comment]
@simonpasquier what exactly is "because of the `for` clause"? Can you please expand a bit more on this for everyone's future benefit?

The metric/query in question returns a unix timestamp value. But the values I reported setting above are not. They don't make sense in terms of unix timestamp values.

I'm mostly interested in the following:

> I don't understand why 1209660 triggers the alert and 1209659 does not. Shouldn't I provide timestamp values?

Thanks.

**Comment by simonpasquier** [comment]
As per https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#defining-alerting-rules

> The optional for clause causes Prometheus to wait for a certain duration between first encountering a new expression output vector element and counting an alert as firing for this element. In this case, Prometheus will check that the alert continues to be active during each evaluation for 10 minutes before firing the alert. Elements that are active, but not firing yet, are in the pending state.

I misread your initial description and thought that `1209659` triggered the alert at t0+2m while `1209660` didn't (because the alert is pending, not firing). FWIW this is what I'm observing locally so not sure what happens with your setup.

I think that when no firing alert matches, `promtool` could check whether a pending alert matches and surface it to the user.

**Comment by walterdolce** [comment]
@simonpasquier that still does not answer the question why I have to provide the non-unix timestamp values such as i.e. `1209659 ` (7 digits, which converted to to human readable date equates to `Thursday, 15 January 1970 00:00:59`) instead of i.e. `1572031521` (*10 digits*, which converted to to human readable date equates to `Friday, 25 October 2019 19:25:21`).

I'm also not really sure the `for` clause is the thing one ought to be focusing here. 

Is it because of a discrepancy between the `expr` defined and the `input_series` being used?
Does `promtool` expect the *entire* `expr` to be mocked, or just the _metric_?

**Comment by simonpasquier** [comment]
>  that still does not answer the question why I have to provide the non-unix timestamp values

the initial time for unit alert tests is 0, eg Jan 1 1970 so samples representing timestamps should be relative to the epoch.

I'm not sure what you call "discrepancy". In general I would recommend for consistency to have samples that span to the last rule evaluation time.

**Comment by walterdolce** [comment]
@simonpasquier thank you for your prompt replies on this! Please see below.

> I'm not sure what you call "discrepancy". In general I would recommend for consistency to have samples that span to the last rule evaluation time.

Let me explain a bit further. 

Given the following `expr`:
```
# If result is "less than 14 days", then notify/alert
expr: ((probe_ssl_earliest_cert_expiry{domain=~"https.*"} - time()) < (86400 * 14))
```
And the following `input_series`:
```
- series: probe_ssl_earliest_cert_expiry{domain="https://example.com"}
   values: '1573464347'  # GMT: Monday, 11 November 2019 09:25:47, Relative: In 5 days
```
Will Prometheus/promtool take the value defined in `values` and evaluate/apply it against the whole expression, including the `time()` function, etc? Or will whatever is defined in `series` actually *be the expression*?

In other words, given the above, will Prometheus/promtool do this?
```
(1573464347 - time()) < (86400 * 14))
```

Or do I need to write this?
```
- series: (probe_ssl_earliest_cert_expiry{domain="https://example.com"}  - time()) < (86400 * 14))
   values: '1573464347'  # GMT: Monday, 11 November 2019 09:25:47, Relative: In 5 days
```

If it's the latter, then this is what I define as "discrepancy". As one would have to define the whole expression instead of just mocking the metric used in the `expr` and its result.

Please let me know if it's not clearer after this.


> the initial time for unit alert tests is 0, eg Jan 1 1970 so samples representing timestamps should be relative to the epoch.

Hmmmm. That means one would have to specify i.e. `1573464347` and not `1209659 ` or `12096560`, then. Is that correct?

**Comment by simonpasquier** [comment]
> Will Prometheus/promtool take the value defined in values and evaluate/apply it against the whole expression, including the time() function, etc? Or will whatever is defined in series actually be the expression?

The former. `input_series` represents streams of datapoints where `series` represents a timeseries (metric name + a set of labels (key/value)) and `samples` the values at every `interval`.

Regarding `time()` it will return `0` when `eval_time: 0m`, `60` when `eval_time: 1m`, and so on.

**Comment by walterdolce** [comment]
> The former.

OK. Thanks for the clarification. It means only the metric query needs to be written (i.e. `probe_ssl_earliest_cert_expiry{domain="https://example.com"}`). That's good.

> `series` represents a timeseries (metric name + a set of labels (key/value)) and `samples` the values at every `interval`.

By `samples`, did you mean `values`? As defined as follows?
```
- input_series:
     - series: ...
        values: ...
```

> Regarding `time()` it will return `0` when `eval_time: 0m`, `60` when `eval_time: 1m`, and so on.

Oh. Does that mean that in order to test the following:
```
((probe_ssl_earliest_cert_expiry{domain=~"https.*"} - time()) < (86400 * 14))
```

Which, as I wanted to test, would translate to:
```
(1573464347 - 1573059143) < 1209600
```

I would need to write this?
```
  - input_series:
      - series: probe_ssl_earliest_cert_expiry{domain="https://example.com"}
        values: '1573464347' # GMT: Monday, 11 November 2019 09:25:47
    alert_rule_test:
      - eval_time: 1573059143s  # GMT: Wednesday, 6 November 2019 16:52:23
        alertname: SSLCertificateExpiringIn2Weeks
        exp_alerts:
```
Because if that's the case, it would take *ages* to run a test like this.
