### ISSUE TITLE
Define alerts using anchor and aliases for common parts

### ISSUE THREAD

**Issue by waberc** [prometheus/prometheus#6266]
## Proposal
**Use case. Why is this important?**
I am defining a lot of similar alerts but with different values thresholds per techno... This means I cannot use one alert for all and I need to split it into different alerts in my yaml "rule" file.

I am trying to use anchor and alias, but I don't find a place where I could define my anchor without breaking the `promtool` yaml validation against the pre-defined prometheus alert schema... Every name I would give to this "commonPart" will break not be accepted here.

Is there a way to go around this or would it be possible to allow some top-level bloc that would be ignored by the yaml validation?

Here is my trial for two alerts definition but I would have up to 10 different ones and I would like to avoid as much as possible repeating myself:

```yaml
.def: &commonPart
  for: 10m
  labels:
    priority: P4
    team: developers
  annotations:
    description: 'No new event for <b>{{ $labels.techno }}</b> came into application for a long time.'

groups:
  - name: silent-sources
    rules:
      - alert: no_liveness_event_for_techno1
        expr: time() > timestamp_of_latest_event{techno="techno1"} + 12*3600
        <<: *commonPart
        annotations:
          summary: 'No new {{ $labels.techno }} event for 12h'

      - alert: no_liveness_event_for_techno2
        expr: time() > timestamp_of_latest_event{techno="techno2"} + 5*24*3600
        <<: *commonPart
        annotations:
          summary: 'No new {{ $labels.techno }} event for 5d'
```

* Prometheus version:
```
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1
``` 
* Alertmanager version:

```
alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8
```

* Logs:

Log of promtool of above mentioned code gives:

```
Checking alerts/k8s/silent-sources.rules
  FAILED:
yaml: unmarshal errors:
  line 1: field .def not found in type rulefmt.RuleGroups
```

Different trials (depending on where I placed the definition bloc (tried inline in the first's alert definition

```
  FAILED:
yaml: unmarshal errors:
  line 2: field for not found in type rulefmt.RuleGroups
  line 3: field labels not found in type rulefmt.RuleGroups
  line 6: field annotations not found in type rulefmt.RuleGroups
```

```
  FAILED:
yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into rulefmt.RuleGroups
```
