### ISSUE TITLE
Prometheus'es consul_sd try to connect to localhost:9090

### ISSUE THREAD

**Issue by a0s** [prometheus/prometheus#6271]
## Bug Report
**What did you do?**
I can see strange data in my Grafana. It looks like prometheus'es consul_sd is trying to connect to localhost:9090. And drop connection after 30s timeout. What's going on?

<img width="1237" alt="Screenshot 2019-11-05 at 00 38 08" src="https://user-images.githubusercontent.com/418868/68161753-9cddb280-ff67-11e9-8da9-1272ab32c81d.png">

**What did you expect to see?**
It should not be present `job="prometheus"` and such words like a `service` and `catalog` on one line. Prometheus job is not about consul.

**What did you see instead? Under which circumstances?**
It should't shows any connection to localhost:9090 in prometheus_sd_consul_rpc_duration_seconds metric.

**Environment**

Prometheus started inside docker container. Consul agent started on host and binded to two interfaces:`"client_addr": "127.0.0.1 169.254.54.1"`. Second interface is a dummy interface accessible from containers (instead of using --host=net)

* System information:

	Linux 3.10.0-957.27.2.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

* Alertmanager version:
not relevant

* Prometheus configuration file:
```
global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090
  - consul_sd_configs:
    - datacenter: dc1
      server: 169.254.54.1:8500
      services:
      - node-exporter
    job_name: consul_dc1_services
    relabel_configs:
    - source_labels:
      - __meta_consul_node
      target_label: instance
    - source_labels:
      - __meta_consul_service
      target_label: consul_service
    - source_labels:
      - __address__
      target_label: exporter_address
    - source_labels:
      - __meta_consul_dc
      target_label: dc
```

* Alertmanager configuration file:
```
not relevant
```

* Logs:
multiple lines:
```
Nov 04 22:16:12 monitoring docker[23010]: level=debug ts=2019-11-04T22:16:12.360Z caller=consul.go:455 component="discovery manager scrape" discovery=consul msg="Watching service" service=node-exporter tags="unsupported value type"
```
