### ISSUE TITLE
Prometheus is ignoring the target hostname in Docker

### ISSUE THREAD

**Issue by averri** [prometheus/prometheus#6293]
Prometheus is showing the target as down, but it's not, I can access it via browser.

The issue is that Prometheus is ignoring my configuration, if I set target as `localhost:4000`, I want this to be the target. Prometheus is using the Docker container ID as the hostname instead of my target configuration.

See the evidence below.

![Screenshot from 2019-11-07 22-07-59](https://user-images.githubusercontent.com/1898447/68431917-3f39a800-01ab-11ea-80a2-651d1c75b39c.png)

prometheus.yml: 

```yml
global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:4000']
```
