### ISSUE TITLE
Feature Request: Recording rule that supports dropping source metrics.

### ISSUE THREAD

**Issue by mandarjog** [prometheus/prometheus#6352]
I work on the istio.io project.
We export a highly dimensioned metrics called `istio_requests_total`
This metrics is scraped directly from proxies. In a dynamic k8s environment tons of new `instance` labels are created. Most of the time these labels are not very useful. 

```yaml
groups:
  - name: requests_total
    rules:
    - record: istio_requests_total_sum
      expr: sum(istio_requests_total) by (source_workload, destination_workload, ...)
      drop: istio_requests_total
```
There are a few labels that we care about in the aggregate that are exposed on the grafana dashboard. It would be great if `istio_requests_total` metrics was never commited to disk and dropped after evaluating the recording rule.

`relabel_config:  drop` happens too early in the lifecycle to be useful.
