### ISSUE TITLE
Linux Docker Container on Windows fails to start (LCOW)

### ISSUE THREAD

**Issue by romerod** [prometheus/prometheus#6353]
## Bug Report

I tried running the prometheus container with LCOW (Linux Container on Windows) on a Windows Server 2019 with the following command:

docker run -v "$pwd\conf:/prom-conf"  "$pwd\data:/prometheus" -p 9090:9090  prom/prometheus --config.file=/prom-conf/prometheus.yml

The config file is the simplest one from https://prometheus.io/docs/prometheus/latest/getting_started/

**Environment**

* System information:

	Linux Container on Windows (LCOW)

* Prometheus version:

	docker prom/prometheus

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
```

* Logs:
First start, data/queries.active not existing:
```
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:334 host_details="(Linux 4.14.29-linuxkit #1 SMP Thu Mar 22 20:44:45 UTC 2018 x86_64 72ac6316fece (none))"
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:335 fd_limits="(soft=1024, hard=4096)"
level=info ts=2019-10-31T14:01:21.286Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2019-10-31T14:01:21.296Z caller=query_logger.go:97 component=activeQueryTracker msg="Failed to mmap" file=data/queries.active Attemptedsize=20001 err="invalid argument"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x245b389, 0x5, 0x14, 0x29db1e0, 0xc00051fc20, 0x29db1e0)
        /app/promql/query_logger.go:115 +0x48c
main.main()
        /app/cmd/prometheus/main.go:364 +0x5229
```

Second start, data/queries.active existing
```
level=info ts=2019-10-31T13:57:47.015Z caller=main.go:296 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2019-10-31T13:57:47.026Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-10-31T13:57:47.026Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-10-31T13:57:47.026Z caller=main.go:334 host_details="(Linux 4.14.29-linuxkit #1 SMP Thu Mar 22 20:44:45 UTC 2018 x86_64 0a4199f52e20 (none))"
level=info ts=2019-10-31T13:57:47.027Z caller=main.go:335 fd_limits="(soft=1024, hard=4096)"
level=info ts=2019-10-31T13:57:47.027Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2019-10-31T13:57:47.053Z caller=query_logger.go:97 component=activeQueryTracker msg="Failed to mmap" file=data/queries.active Attemptedsize=20001 err="invalid argument"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x245b389, 0x5, 0x14, 0x29db1e0, 0xc00064e3c0, 0x29db1e0)
        /app/promql/query_logger.go:115 +0x48c
main.main()
        /app/cmd/prometheus/main.go:364 +0x5229
```

No difference when using a volume instead of a bind mount (-v "/prometheus").

Tried looking for a similar issue with mmap on LCOW, but couldn't find anything.
