### ISSUE TITLE
expected timestamp or new record, got \"MNAME\"

### ISSUE THREAD

**Issue by geektcp** [prometheus/prometheus#6358]
## Bug Report
**What did you do?**
```
prometheus cant not scrape exporter metric ?
this exporter build with java 
```
**What did you expect to see?**
```
is is a bug? How to resolve it ?
```

**code**
```
@Slf4j
@Api("metrics")
@RestController
@RequestMapping("/")
public class MetricsController {

    @Autowired
    private MetricsService metricsService;

    @GetMapping("/metrics")
    public String metrics() {
        return "# HELP EXAMELE_KEY_1111 describe\n# TYPE EXAMELE_KEY_1111 gauge\nEXAMELE_KEY_1111 6738604032\n";
    }


}
```

metric:
```
curl http://localhost:30001/metrics
# HELP EXAMELE_KEY_1111 describe
# TYPE EXAMELE_KEY_1111 gauge
EXAMELE_KEY_1111 6738604032   
```
$ uname -srm
```
Linux 3.10.0-514.el7.x86_64 x86_64
```
* Prometheus version:

$ ./prometheus --version
```
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4
```

* Prometheus configuration file:
```
  - job_name: aliyun-log-exporter-thy
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 10.118.80.115:30001
```

* Logs:
```
level=warn ts=2019-11-22T10:24:15.295Z caller=scrape.go:937 component="scrape manager" scrape_pool=aliyun-log-exporter-thy target=http://10.118.80.115:30001/metrics msg="append failed" err="expected timestamp or new record, got \"MNAME\""
```
