### ISSUE TITLE
Strange behavior when querying for targets that have same instance label

### ISSUE THREAD

**Issue by Throckmortra** [prometheus/prometheus#6379]
## Bug Report
**What did you do?**
I have a prometheus server that relabels targets with the instance name tag in AWS EC2. I queried it via Grafana and Prometheus UI for metrics related to these instances with the same label.

**What did you expect to see?**
I expect Prometheus to give me data for all targets with the same label or to create an error.

**What did you see instead? Under which circumstances?**
Instead, it sends me metrics for only one of the targets. It is not clear which one.

**Environment**

* System information:
Linux 4.14.138-114.102.amzn2.x86_64 x86_64

* Prometheus version:
> prometheus, version 2.12.0 (branch: HEAD, revision: 43acd0e2e93f9f70c49b2267efa0124f1e759e86)
>   build user:       root@7a9dbdbe0cc7
>   build date:       20190818-13:53:16
>   go version:       go1.12.8

* Prometheus configuration file:

```
#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: global

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - redacted
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

  - job_name: aws
    ec2_sd_configs:
      - region: us-east-2
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: redacted
    metrics_path: /metrics
    ec2_sd_configs:
      - region: us-east-2
        port: 14040
        filters:
          - name: tag-key
            values:
              - redacted
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
  - job_name: 'federate'
    scheme: https
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="aws"}'
        - '{job="redacted"}'
        - '{__name__=~"job:.*"}'
    static_configs:
      - targets:
        - 'small-prometheus.redacted'
```
