### ISSUE TITLE
Domain name resolution error on mac when the port is 80

### ISSUE THREAD

**Issue by xuejianguo** [prometheus/prometheus#6388]
## Proposal
**Use case. Why is this important?**
if user's endpoint port happens to be "80" and their prometheus server is deployed on mac, they will get "not a valid token" error.
*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
I am trying to use prometheus to monitor my dubbo service, and i've already exposed an endpoint. i can directly browse the endpoint and get the right metric information.After that  i modify the prometheus.yml file to config my target path with "file-server.dasouche-fin.net:80". And then i start my prometheus server, but i got "err=\"INVALID\" is not a valid start token".
![image](https://user-images.githubusercontent.com/20455602/69788762-1df03880-11fa-11ea-969a-052c2c8f386a.png)
so i use promtool to check my metric, and i got nothing. finally i use wireshark to capture the http request and found the wrong host. 
![image](https://user-images.githubusercontent.com/20455602/69790235-12ead780-11fd-11ea-99f8-d6c1ef3dc5f9.png)
![image](https://user-images.githubusercontent.com/20455602/69789057-bdadc680-11fa-11ea-8eb4-d64d52c184a3.png)

**What did you expect to see?**
i think the host should not include the port number.
**What did you see instead? Under which circumstances?**
No matter i use "file-server.dasouche-fin.net:80" or just "file-server.dasouche-fin.net" , i got the same wrong  result. Occasionally i change it to "file-server.dasouche-fin.net:"(Pay attention to colon), and surpisingly it worked.
![image](https://user-images.githubusercontent.com/20455602/69789237-1b421300-11fb-11ea-836e-3f4f7c1dad49.png)

**Environment**

* System information:

	Darwin 18.6.0 x86_64

* Prometheus version:

	2.11.0 (actually i also tried 2.14, it didn't work either)

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    metrics_path: '/prometheus'
    # scheme defaults to 'http'.

    static_configs:
    # now it's the right config, but if i use "file-server.dasouche-fin.net" or "file-server.dasouche-fin.net:80" instead, and i will get the error above mentiond.
    - targets: ['file-server.dasouche-fin.net:']
 
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=warn ts=2019-11-28T06:16:46.658Z caller=scrape.go:937 component="scrape manager" scrape_pool=prometheus target=http://file-server.dasouche-fin.net:80/prometheus msg="append failed" err="\"INVALID\" is not a valid start token"
```
