### ISSUE TITLE
Template Expansion allocating large amounts of memory

### ISSUE THREAD

**Issue by raokrutarth** [prometheus/prometheus#6403]
## Proposal
**Use case. Why is this important?**

v2.8.1

Investigating device memory performance issue (OOM killer invoked) on a linux device with limited main memory. Swap disabled. Prometheus RSS is the biggest culprit. 

It is understood RSS is not an accurate measure of main memory usage. However, the system becomes sluggish once RSS comes close to system capacity.

Memory allocation in the rules package seems unexpectedly high.

It is understood allocation is not the same as in use. In use heap was 30% of RSS. 

## Bug Report
**What did you do?**

Monitoring 20k timeseries. 
![image](https://user-images.githubusercontent.com/8570223/70092550-61b8b880-15d3-11ea-990a-d0d8d82c697d.png)

15 rule evaluations per second
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/8570223/70092651-a2b0cd00-15d3-11ea-80ce-722d76278c70.png">

Peak of 150 notifications per second
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/8570223/70092693-b4927000-15d3-11ea-8c46-2f1e2d016087.png">

heap profile obtained with `http://localhost:9090/debug/pprof/heap?debug=0` with alloc_space shows over 591 GB allocated from the template expander. (not sure how to share raw profile)
<img width="794" alt="image" src="https://user-images.githubusercontent.com/8570223/70092835-fde2bf80-15d3-11ea-8a70-0b957ce7e44d.png">

allocations coming from this line: [template.go:301](https://github.com/prometheus/prometheus/blob/v2.8.1/template/template.go#L301)

![image](https://user-images.githubusercontent.com/8570223/70093499-64b4a880-15d5-11ea-8bfd-c4d0ea7608d5.png)

**What did you expect to see?**
If the go mem stats reported in use heap is low (e.g. 94 MB) then the RSS should be close. Can see RSS, `go_memstats_sys_bytes` and `process_resident_memory_bytes` all near the 340 MB mark at the same time.

**What did you see instead? Under which circumstances?**
Seeing a large unexplained gap in inuse memory and memory claimed from the system. Reducing allocations could help.

**Environment**

Linux 5454 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

* System information: Linux 4.4.0-166-generic x86_64

* Prometheus version: 2.8.1

* Alertmanager version: N/A

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 5s
  external_labels:
    monitor: codelab-monitor
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9091
    scheme: http
    timeout: 10s
rule_files:
- /var/run/prometheus/alerts/*.yml
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9091
```

* Alertmanager configuration file: N/A

* Logs: N/A

* Extra Info:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/8570223/70093425-3a62eb00-15d5-11ea-9c40-17800171cf9a.png">

![image](https://user-images.githubusercontent.com/8570223/70093467-52d30580-15d5-11ea-9b4c-ba9977f6c086.png)
