### ISSUE TITLE
Prometheus not cleaning up WAL files

### ISSUE THREAD

**Issue by walterdolce** [prometheus/prometheus#6408]
## Bug Report
**What did you do?**
Ran Prometheus for a while. At some point it got `Evicted`, then was unable to cleanup WAL files ever again.

**What did you expect to see?**
Prometheus to clean up the WAL files and move onto another checkpoint

**What did you see instead? Under which circumstances?**
Prometheus ran but stacked `000***` WAL files over time and got stuck on a fixed `checkpoint.00NNNN`. 

**Environment**
GKE

* System information:
Standard GKE nodes pool set

* Prometheus version:
```
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1
```

* Alertmanager version:
N/A

* Prometheus configuration file:
```
---
rule_files:
  - /etc/prometheus/rules/*.yml
global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 60s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: cadvisor
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_cloud_google_com_gke_nodepool
        replacement: nodepool
      - action: labelmap
        regex: __meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_(.+)
        replacement: $1
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    metric_relabel_configs:
      - action: replace
        source_labels: [id]
        regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
        target_label: rkt_container_name
        replacement: '${2}-${1}'
      - action: replace
        source_labels: [id]
        regex: '^/system\.slice/(.+)\.service$'
        target_label: systemd_service_name
        replacement: '${1}'
  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(app|team)
        replacement: $1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_helm_sh_chart
        replacement: helm_chart
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: kubernetes_name
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (https?)
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)(?::\d+);(\d+)
        replacement: $1:$2
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(app|team)
        replacement: $1
      - action: labelmap
        regex: __meta_kubernetes_pod_label_helm_sh_chart
        replacement: helm_chart
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_cloud_google_com_gke_nodepool
        replacement: nodepool
      - action: labelmap
        regex: __meta_kubernetes_node_label_failure_domain_beta_kubernetes_io_(.+)
        replacement: $1
      - target_label: __address__
        replacement: kubernetes.default.svc.cluster.local:443
      - target_label: __scheme__
        replacement: https
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
```

Prometheus Kubernetes deployment:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    kube-score/ignore: pod-networkpolicy,container-security-context
  labels:
    app: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: v2.13.1
    helm.sh/chart: prometheus-1.1.3
  name: prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: d2a860ef522ce24f2fd335162678ed7a7401f7a7a45ac37e14ac245f7245f302
        checksum/rules: c625c283c4fd8c900eb9a30542c4fca388de76b0b1c792213d62988174b215ae  3b3b53018fe62da2a850a6f49f1867922c4f36c162deadf2897d16608a05e22c
      creationTimestamp: null
      labels:
        app: prometheus
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/version: v2.13.1
        helm.sh/chart: prometheus-1.1.3
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: prometheus
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --alertmanager.notification-queue-capacity=10000
        - --alertmanager.timeout=10s
        - --config.file=/etc/prometheus/prometheus.yml
        - --log.format=logfmt
        - --log.level=info
        - --query.lookback-delta=5m
        - --query.max-concurrency=40
        - --query.max-samples=50000000
        - --query.timeout=2m
        - --rules.alert.for-grace-period=10m
        - --rules.alert.for-outage-tolerance=1h
        - --rules.alert.resend-delay=1m
        - --storage.remote.read-concurrent-limit=10
        - --storage.remote.read-sample-limit=5e7
        - --storage.tsdb.no-lockfile
        - --storage.tsdb.path=/prometheus/data/
        - --storage.tsdb.retention.time=30d
        - --storage.tsdb.wal-compression
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        - --web.max-connections=512
        - --web.read-timeout=1m
        - --web.route-prefix=/
        command:
        - prometheus
        image: prom/prometheus:v2.13.1
        imagePullPolicy: Always
        name: prometheus
        resources:
          requests:
            cpu: 250m
            memory: 300Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /etc/prometheus/rules
          name: prometheus-alerting-rules
          readOnly: true
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          readOnly: true
          subPath: prometheus.yml
        - mountPath: /prometheus/data
          name: prometheus-data-disk
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - -c
        - chown -R 10001:10002 /prometheus/data
        command:
        - sh
        image: prom/prometheus:v2.13.1
        imagePullPolicy: Always
        name: prometheus-data-folder-permissions-fixer
        resources:
          limits:
            cpu: 100m
            memory: 40Mi
          requests:
            cpu: 50m
            memory: 20Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /prometheus/data
          name: prometheus-data-disk
      nodeSelector:    # Prometheus runs in a different node pool with more resources available to it
        prometheusx2: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp-volume
      - configMap:
          defaultMode: 420
          name: prometheus-alerting-rules-helm
        name: prometheus-alerting-rules    # Alerting rules, feel free to remove for this
      - configMap:
          defaultMode: 420
          name: prometheus-config-helm
        name: prometheus-config   # The prometheus config specified above ends up here
      - name: prometheus-data-disk
        persistentVolumeClaim:
          claimName: prometheus-data-disk    # This is a normal Google Cloud persistent disk, 100GB
```

* Alertmanager configuration file:
N/A

* Logs:
Prometheus logs: https://gist.github.com/walterdolce/2a8b1990234d0641c7e960a45383f08e
WAL folder content:
```
/prometheus $ ls -lah data/wal
total 10G
drwxr-xr-x    3 10001    10002       4.0K Dec  4 12:29 .
drwxr-xr-x   24 10001    10002       4.0K Dec  4 12:28 ..
-rw-r--r--    1 10001    10002     128.0M Nov 27 14:19 00002288
-rw-r--r--    1 10001    10002     127.9M Nov 27 14:58 00002289
-rw-r--r--    1 10001    10002       4.8M Nov 27 15:00 00002290
-rw-r--r--    1 10001    10002     128.0M Nov 27 15:39 00002291
-rw-r--r--    1 10001    10002     128.0M Nov 27 16:19 00002292
-rw-r--r--    1 10001    10002     128.0M Nov 27 16:58 00002293
-rw-r--r--    1 10001    10002       6.3M Nov 27 17:00 00002294
-rw-r--r--    1 10001    10002      61.1M Nov 27 17:19 00002295
-rw-r--r--    1 10001    10002      23.0M Nov 27 17:24 00002296
-rw-r--r--    1 10001    10002      94.6M Nov 27 17:53 00002297
-rw-r--r--    1 10001    10002     128.0M Nov 27 18:33 00002298
-rw-r--r--    1 10001    10002     127.9M Nov 27 19:13 00002299
-rw-r--r--    1 10001    10002       4.9M Nov 28 13:48 00002300
-rw-r--r--    1 10001    10002     128.0M Nov 28 14:27 00002301
-rw-r--r--    1 10001    10002      10.3M Nov 29 06:24 00002302
-rw-r--r--    1 10001    10002     127.6M Nov 29 07:05 00002303
-rw-r--r--    1 10001    10002     127.9M Nov 29 07:45 00002304
-rw-r--r--    1 10001    10002     128.0M Nov 29 08:26 00002305
-rw-r--r--    1 10001    10002     128.0M Nov 29 09:06 00002306
-rw-r--r--    1 10001    10002     127.9M Nov 29 09:46 00002307
-rw-r--r--    1 10001    10002     127.9M Nov 29 10:26 00002308
-rw-r--r--    1 10001    10002     127.8M Nov 29 11:06 00002309
-rw-r--r--    1 10001    10002     128.0M Nov 29 11:46 00002310
-rw-r--r--    1 10001    10002     127.9M Nov 29 12:26 00002311
-rw-r--r--    1 10001    10002     128.0M Nov 29 13:06 00002312
-rw-r--r--    1 10001    10002     127.7M Nov 29 13:47 00002313
-rw-r--r--    1 10001    10002     128.0M Nov 29 14:27 00002314
-rw-r--r--    1 10001    10002     128.0M Nov 29 15:07 00002315
-rw-r--r--    1 10001    10002     128.0M Nov 29 15:48 00002316
-rw-r--r--    1 10001    10002     127.6M Nov 29 16:28 00002317
-rw-r--r--    1 10001    10002     128.0M Nov 29 17:09 00002318
-rw-r--r--    1 10001    10002     128.0M Nov 29 17:49 00002319
-rw-r--r--    1 10001    10002     128.0M Nov 29 18:29 00002320
-rw-r--r--    1 10001    10002     128.0M Nov 29 19:10 00002321
-rw-r--r--    1 10001    10002     127.6M Nov 29 19:50 00002322
-rw-r--r--    1 10001    10002     128.0M Nov 29 20:31 00002323
-rw-r--r--    1 10001    10002     128.0M Nov 29 21:11 00002324
-rw-r--r--    1 10001    10002      63.6M Nov 29 21:31 00002325
-rw-r--r--    1 10001    10002      68.6M Nov 29 22:08 00002326
-rw-r--r--    1 10001    10002     127.9M Nov 29 22:59 00002327
-rw-r--r--    1 10001    10002     128.0M Nov 29 23:39 00002328
-rw-r--r--    1 10001    10002     128.0M Nov 30 00:20 00002329
-rw-r--r--    1 10001    10002     128.0M Nov 30 01:00 00002330
-rw-r--r--    1 10001    10002     128.0M Nov 30 01:41 00002331
-rw-r--r--    1 10001    10002     127.6M Nov 30 02:21 00002332
-rw-r--r--    1 10001    10002     128.0M Nov 30 03:02 00002333
-rw-r--r--    1 10001    10002     128.0M Nov 30 03:43 00002334
-rw-r--r--    1 10001    10002     127.9M Nov 30 04:24 00002335
-rw-r--r--    1 10001    10002     128.0M Nov 30 05:06 00002336
-rw-r--r--    1 10001    10002     127.7M Nov 30 05:47 00002337
-rw-r--r--    1 10001    10002     128.0M Nov 30 06:28 00002338
-rw-r--r--    1 10001    10002     128.0M Nov 30 07:09 00002339
-rw-r--r--    1 10001    10002     127.9M Dec  3 12:19 00002340
-rw-r--r--    1 10001    10002     128.0M Dec  3 12:58 00002341
-rw-r--r--    1 10001    10002     128.0M Dec  3 13:37 00002342
-rw-r--r--    1 10001    10002     128.0M Dec  3 14:16 00002343
-rw-r--r--    1 10001    10002     127.9M Dec  3 14:55 00002344
-rw-r--r--    1 10001    10002     128.0M Dec  3 15:33 00002345
-rw-r--r--    1 10001    10002     127.9M Dec  3 16:12 00002346
-rw-r--r--    1 10001    10002     128.0M Dec  3 16:50 00002347
-rw-r--r--    1 10001    10002     128.0M Dec  3 17:30 00002348
-rw-r--r--    1 10001    10002      43.2M Dec  3 17:43 00002349
-rw-r--r--    1 10001    10002     127.9M Dec  3 18:40 00002350
-rw-r--r--    1 10001    10002      28.2M Dec  3 18:48 00002351
-rw-r--r--    1 10001    10002          0 Dec  3 18:49 00002352
-rw-r--r--    1 10001    10002      47.5M Dec  3 19:51 00002353
-rw-r--r--    1 10001    10002          0 Dec  3 19:52 00002354
-rw-r--r--    1 10001    10002     128.0M Dec  3 21:17 00002355
-rw-r--r--    1 10001    10002     127.9M Dec  3 21:56 00002356
-rw-r--r--    1 10001    10002     127.9M Dec  3 22:35 00002357
-rw-r--r--    1 10001    10002     128.0M Dec  3 23:13 00002358
-rw-r--r--    1 10001    10002     127.8M Dec  3 23:52 00002359
-rw-r--r--    1 10001    10002     127.9M Dec  4 00:31 00002360
-rw-r--r--    1 10001    10002     128.0M Dec  4 01:09 00002361
-rw-r--r--    1 10001    10002     127.9M Dec  4 01:48 00002362
-rw-r--r--    1 10001    10002     128.0M Dec  4 02:27 00002363
-rw-r--r--    1 10001    10002     127.7M Dec  4 03:06 00002364
-rw-r--r--    1 10001    10002     128.0M Dec  4 03:44 00002365
-rw-r--r--    1 10001    10002     128.0M Dec  4 04:23 00002366
-rw-r--r--    1 10001    10002     127.9M Dec  4 05:02 00002367
-rw-r--r--    1 10001    10002     128.0M Dec  4 05:40 00002368
-rw-r--r--    1 10001    10002     127.8M Dec  4 06:19 00002369
-rw-r--r--    1 10001    10002     128.0M Dec  4 06:58 00002370
-rw-r--r--    1 10001    10002     128.0M Dec  4 07:36 00002371
-rw-r--r--    1 10001    10002     128.0M Dec  4 08:15 00002372
-rw-r--r--    1 10001    10002     128.0M Dec  4 08:54 00002373
-rw-r--r--    1 10001    10002     128.0M Dec  4 09:34 00002374
-rw-r--r--    1 10001    10002     107.8M Dec  4 10:07 00002375
-rw-r--r--    1 10001    10002      46.8M Dec  4 10:52 00002376
-rw-r--r--    1 10001    10002      13.7M Dec  4 11:28 00002377
-rw-r--r--    1 10001    10002          0 Dec  4 11:28 00002378
-rw-r--r--    1 10001    10002          0 Dec  4 11:35 00002379
-rw-r--r--    1 10001    10002     105.7M Dec  4 12:28 00002380
-rw-r--r--    1 10001    root           0 Dec  4 12:29 00002381
drwxr-xr-x    2 10001    10002       4.0K Nov 27 17:00 checkpoint.002287
```
