### ISSUE TITLE
Expose select metrics through a proxy

### ISSUE THREAD

**Issue by jakubgs** [prometheus/prometheus#6441]
I'm trying to expose a selection of my Prometheus metrics. I have created a publicly accessible Grafana dashboard, but I don't want to point it at my normal Prometheus masters federating metrics from all of my infra because that would allow people to make custom queries.

Instead I created a "proxy" prometheus instance that federates only select metrics based on `__name__`. The issue with that approach is that it exposes only metrics from "proxy" creation into the future, not the historical data. I was wondering if there is a mode in which I could simply proxy prometheus queries for select metrics rather than doing a federation with filters.

I understand that there is ongoing work in https://github.com/prometheus/prometheus/pull/5887 on an  import tool which would definitely help in this case, but a proxy would make this even simpler, since it would eliminate the need for storage.

I'm aware of the https://github.com/pambrose/prometheus-proxy project but I think it covers a slightly different case.

**Comment by bwplotka** [comment]
Hi,!

It looks like what you want to achieve is something called `query multitenancy` (enforcing certain labels). One of the project that does it is: https://github.com/openshift/prom-label-proxy 

e.g in K8s:
```
    - name: prom-label-enforcer
        image: quay.io/coreos/prom-label-proxy:v0.1.0
        imagePullPolicy: Always
        args:
        - "--insecure-listen-address=127.0.0.1:8080"
        - "--upstream=http://prometheus-k8s.monitoring.svc:9090/"
        - "--label=namespace"
```

It might make more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided. (:
