### ISSUE TITLE
Rule discovery mechanism like service discovery

### ISSUE THREAD

**Issue by qudongfang** [prometheus/prometheus#6453]
## Proposal

Nice to have a dynamic **Rule Discovery** mechanism from sources other than local config files.

## Justification

**Think about why we supported**

- Service Discovery
- Notifier Discovery

**Comment by brian-brazil** [comment]
I don't think this is something that belongs in Prometheus, local files already provide a mechanism which you can build on top of.

**Comment by geektcp** [comment]
I think this is the the right answer:
```
exporter:
the exporter url: http://x.x.x.x:3000/metrics
```
```
global:
    scrape_interval: 30s
    scrape_timeout: 10s
    evaluation_interval: 30s
alerting:
    alertmanagers:
    - static_configs:
      - targets:
        - x.x.x.x:9093
      scheme: http
      timeout: 10s
rule_files:
  - rules.yml

scrape_configs:
  - job_name: 'agent-inquiry'
    kubernetes_sd_configs:
    - role: pod
      api_server: http://x.x.x.x:6443
      tls_config:
        insecure_skip_verify: true
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      regex: inquiry
      action: keep
    - source_labels: [__metrics_path__]
      action: replace
      replacement: /metrics
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__,__meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: (.*);(.*)
      replacement: ${1}:3300
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```
