### ISSUE TITLE
`promtool check rules` should expand templates before inspecting rules

### ISSUE THREAD

**Issue by spads-spads** [prometheus/prometheus#6467]
## Proposal
**Use case. Why is this important?**

Since alertmanager supports golang templating, it should not parse the YAML until it has at least tried to render the templates into the target rules file.  Currently any inline template definition or use that involves newlines or indentation changes will generate an error.

## Bug Report
**What did you do?**

I created a rules file with a `{{define "macro-name"}}` section, per the docs.

**What did you expect to see?**

Either a warning that the template could not be expanded without more context, or a successfully linted rules file complete with rendered resulting checks.

**What did you see instead? Under which circumstances?**

```
  FAILED:
yaml: line 10: could not find expected ':'
```

**Environment**

* System information:

```
Linux 4.15.0-72-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.1.0+ds (branch: debian/sid, revision: 2.1.0+ds-1)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20180121-21:30:42
  go version:       go1.9.2
```

* Alertmanager rules file:
```
groups:
- name: test
  rules:
  - alert: Test Alert
    expr:  time() > 0
    annotations:
      description: This is a test alert that should always fire
    labels:
      severity: warning
{{define "test-macro" (args 1)}}
    expr:  time() > {{arg0}}
{{end}}
```

**Comment by brian-brazil** [comment]
I thought we'd added this to the general reload a good while back, if not we should do so and ensure that promtool is also running that code.

**Comment by spads-spads** [comment]
Do you know where the code to do this lives?  I'd be happy to build a custom version of promtool for my own linting purposes in the short term.

**Comment by brian-brazil** [comment]
Not offhand, but see where `template` is referenced.

To be clear we can only check that a template parses, not that it'll subsequently evaluate.

**Comment by roidelapluie** [comment]
Your exemple, a *prometheus* rule file, is invalid. The error message is correct, this file is not yaml valid.

We support go template only in two locations: label value and annotation value ( https://prometheus.io/docs/prometheus/latest/configuration/recording_rules/ look for tmpl_string  )

My experience tells me that those templates are correctly checked during validation.


Here is what you could do:

```
groups:
- name: test
  rules:
  - alert: Test Alert
    expr:  time() > 0
    annotations:
      description: '{{"go template"}}'
    labels:
      severity: '{{"go template"}}'
```

From this point, I assume that this is an usage question, which would better be answered on the [mailing list](https://prometheus.io/community/).
