### ISSUE TITLE
Unit test does not work for interval>=15m

### ISSUE THREAD

**Issue by skadem07** [prometheus/prometheus#6498]
Issue 
I tried to create an alert and unit test. The unit test fails when the interval is 15m and 30m. It seems to be a bug, since when i used pat tool I was able to test it and it works.
Also it works for 1m, 5m 

Alert:
```
groups:
- name: spark.rules
  rules:
##### ALERTS #####
  - alert: foo
    expr: spark_streaming_total_lag > 5000
    for: 30m
    labels:
      service: spark
      severity: warning
      source: spark
      symptom:
```

Unit test 

```
rule_files:
  - ../rules/spark.rules.yml
evaluation_interval: 1m

tests:
  - interval: 15m
    input_series:
      - series: 'spark_streaming_total_lag{application_id="amp_mongo_episode"}'
        values: '60000 60000 60000' # 15min duration fails
    alert_rule_test:
      - eval_time: 30m
        alertname: foo
        exp_alerts:
          - exp_labels:
              application_id: amp_mongo_episode
              service: spark
              severity: warning
              source: spark
    promql_expr_test:
      # Unit test 1.
      - expr: 'spark_streaming_total_lag'
        eval_time: 30m
        exp_samples:
          - labels: 'spark_streaming_total_lag{application_id="amp_mongo_episode"}'
            value: 60000
```

Error:

Unit Testing:  ./prometheus/tests/spark.test.yml
  FAILED:
    alertname:foo, time:30m0s,
        exp:"[Labels:{alertname=\"foo\", application_id=\"amp_mongo_episode\", service=\"spark\", severity=\"warning\", source=\"spark\"} Annotations:{}]",
        got:"[]"

Version

```
promtool --version
promtool, version  (branch: , revision: )
  build user:
  build date:
  go version:       go1.12.8
```
