### ISSUE TITLE
Prometheus Error reading file, unexpected end of JSON input

### ISSUE THREAD

**Issue by timurridjanovic** [prometheus/prometheus#6500]
## Bug Report
**What did you do?**
Running prometheus on AWS ECS fargate where one container writes to a shared volume /var/scratch/fileSdConfig.json

The Prometheus config looks like:
```
global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
scrape_configs:
- job_name: aws_mgapps
  metrics_path: /i/apps/appservices-metrics/metrics
  scheme: https
  file_sd_configs:
  - files:
    - /var/scratch/fileSdConfig.json
  tls_config:
    insecure_skip_verify: true
```

**What did you expect to see?**
Locally I see 
level=info ts=2019-12-20T16:33:50.4314081Z caller=main.go:589 msg="Server is ready to receive web requests."

**What did you see instead? Under which circumstances?**
on ECS I see this error (can't reproduce this locally):
level=error ts=2019-12-20T20:09:11.55414557Z caller=file.go:321 component="discovery manager scrape" discovery=file msg="Error reading file" path=/var/scratch/fileSdConfig.json err="unexpected end of JSON input"

**Environment**

AWS ECS Fargate

* Prometheus version:

	2.7.1

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s
scrape_configs:
- job_name: aws_mgapps
  metrics_path: /i/apps/appservices-metrics/metrics
  scheme: https
  file_sd_configs:
  - files:
    - /var/scratch/fileSdConfig.json
  tls_config:
    insecure_skip_verify: true
```

* Logs:
```
level=error ts=2019-12-20T20:19:03.958992079Z caller=file.go:321 component="discovery manager scrape" discovery=file msg="Error reading file" path=/var/scratch/fileSdConfig.json err="unexpected end of JSON input"
```
