### ISSUE TITLE
prometheus 2.15.0 throwing many 422 response codes

### ISSUE THREAD

**Issue by gbolo** [prometheus/prometheus#6516]
## Bug Report
**What did you do?**
ran prometheus 2.15.0 docker image with local mount volume. Stored some data via node_exporter for a few days. When using grafana to view last 2 days of data, I noticed that some graphs were randomly not showing up. After some investigation, I traced the issue down to prometheus randomly throwing 422 responses when request load is high. Turning on `--log.level=debug` revealed no additional information as to why this is happening. I decided to downgrade docker image from latest (which was `2.15.0` at the time) to a lesser version starting at `2.13.0` and moving upwards. Both `2.13.0` and `2.14.0` worked without this issue. Only the docker image was changed and nothing else (same mounts and configs). I confirmed that specifying the docker image `2.15.0` caused the issue. using `master` also has the same issue (so this bug still exists in master).

all observed 422 responses are commig from these type of calls:
```
GET /api/v1/query_range
** no corelation in series/metric names, seems to be random ** 
```
when doing the same request manually via curl or browser, the response is fine. This seems to only happen when using something like grafana to launch many simontanouse API calls.

**What did you expect to see?**
no 422 responses

**What did you see instead? Under which circumstances?**
many 422 responses when date range is high and request count is high (many graphs in same page)

**Environment**

* System information:

	`Linux 4.15.0-72-generic x86_64`

* Prometheus version:

```
prometheus, version 2.15.0 (branch: HEAD, revision: ec1868b0267d13cb5967286fd5ec6afff507905b)
  build user:       root@240f2f89177f
  build date:       20191223-12:03:32
  go version:       go1.13.5
```

* Alertmanager version:

	N/A

* Prometheus configuration file:
```
# /etc/prometheus/prometheus.yml
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 1m
  external_labels:
    environment: <REMOVED_FOR_PRIVACY>
  scrape_interval: 1m
  scrape_timeout: 10s


# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093


# Prometheus uses rules to create new time series and to generate alerts.
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files specifies a list of filepath globs. Rules and alerts are read from all matching files.
rule_files:
   - "/etc/prometheus/rules/*.yml"


# A scrape configuration containing endpoints to scrape:
# Prometheus expects metrics to be available on targets on a path of /metrics
scrape_configs:
  - job_name: node_exporter
    metrics_path: /metrics
    scheme: http
    scrape_interval: 10s
    scrape_timeout: 3s
    static_configs:
    - labels:
        instance: <REMOVED_FOR_PRIVACY>
      targets:
      - <REMOVED_FOR_PRIVACY>

```

* Alertmanager configuration file:
       N/A

* Logs:
```
nothing useful in logs
```
