### ISSUE TITLE
err="opening storage failed: unexpected corrupted block: map :open /data

### ISSUE THREAD

**Issue by ramakrishnateja** [prometheus/prometheus#6522]
## Bug Report
**What did you do?**
Installed prometheus through helm chart and added thanos side car containers 
**What did you expect to see?**
Expect to see:
I expect to see the prometheus pod running

**What did you see instead? Under which circumstances?**
It crashes around every 2 hours.

**Environment**
Linux VMs with Azure Managed Disks for storage

* System information:

	insert output of `uname -srm` here

* Prometheus version:
2.13.1
	insert output of `prometheus --version` here

* Prometheus configuration file:
```
server:
  ## Prometheus server container name
  ##
  enabled: true
  name: server
  sidecarContainers:
    - name: thanos-sidecar
      image: thanosio/thanos:v0.9.0
      args:
      - sidecar
      - --tsdb.path=/data
      - --prometheus.url=http://localhost:9090
      - --objstore.config-file=/etc/thanos/bucket.yml
      - --grpc-address=0.0.0.0:10901
      - --http-address=0.0.0.0:10902
      ports:
      - name: http-sidecar
        containerPort: 10902
      - name: grpc
        containerPort: 10901
      resources:
        requests:
          cpu: 1.0
          memory: 2Gi
        limits:
          cpu: 2.0
          memory: 3Gi
      volumeMounts:
      - mountPath: /data
        name: storage-volume
      - mountPath: /etc/config
        name: config-volume
        readOnly: true
      - mountPath: /etc/thanos
        name: thanos-config
        readOnly: true
    - name: thanos-store
      image: thanosio/thanos:v0.9.0
      args:
      - store
      - --data-dir=/data
      - --objstore.config-file=/etc/thanos/bucket.yml
      - --grpc-address=0.0.0.0:10911
      - --http-address=0.0.0.0:10912
      - --index-cache-size=500MB
      - --chunk-pool-size=500MB
      ports:
      - name: store-http
        containerPort: 10912
      - name: store-grpc
        containerPort: 10911
      volumeMounts:
      - mountPath: /data
        name: storage-volume
      - mountPath: /etc/thanos
        name: thanos-config
        readOnly: true

  ## Path to a configuration file on prometheus server container FS
  configPath: /etc/config/prometheus.yml

  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 15s
    external_labels:
      clusterName: US-PLATFORM-LOWER-PROM

  ## Additional Prometheus server container arguments
  ##
  extraArgs:
    storage.tsdb.max-block-duration: 2h
    storage.tsdb.min-block-duration: 2h
 
  retention: "6h"
```

*Kubectl Describe:

```
Containers:
   prometheus-server-configmap-reload:
    Image:      jimmidyson/configmap-reload:v0.2.2
    Port:       <none>
    Host Port:  <none>
    Args:
      --volume-dir=/etc/config
      --webhook-url=http://127.0.0.1:9090/-/reload
    Environment:  <none>
    Mounts:
      /etc/config from config-volume (ro)
   prometheus-server:
    Image:      prom/prometheus:v2.13.1
    Port:       9090/TCP
    Host Port:  0/TCP
    Args:
      --storage.tsdb.retention.time=6h
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
      --storage.tsdb.max-block-duration=2h
      --storage.tsdb.min-block-duration=2h
    Limits:
      cpu:     2
      memory:  3Gi
    Requests:
      cpu:        1
      memory:     2Gi
    Liveness:     http-get http://:9090/-/healthy delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:    http-get http://:9090/-/ready delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/config from config-volume (rw)
   thanos-sidecar:
    Image:       thanosio/thanos:v0.9.0
    Ports:       10902/TCP, 10901/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      sidecar
      --tsdb.path=/data
      --prometheus.url=http://localhost:9090
      --objstore.config-file=/etc/thanos/bucket.yml
      --grpc-address=0.0.0.0:10901
      --http-address=0.0.0.0:10902
    Limits:
      cpu:     2
      memory:  3Gi
    Requests:
      cpu:        1
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/config from config-volume (ro)
      /etc/thanos from thanos-config (ro)
   thanos-store:
    Image:       thanosio/thanos:v0.9.0
    Ports:       10912/TCP, 10911/TCP
    Host Ports:  0/TCP, 0/TCP
    Args:
      store
      --data-dir=/data
      --objstore.config-file=/etc/thanos/bucket.yml
      --grpc-address=0.0.0.0:10911
      --http-address=0.0.0.0:10912
      --index-cache-size=500MB
      --chunk-pool-size=500MB
    Environment:  <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/thanos from thanos-config (ro)
  Volumes:
   config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-server
    Optional:  false
   storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus-server
    ReadOnly:   false
   thanos-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      thanos-config
    Optional:  false
```

* Logs:
```
level=info ts=2019-12-26T03:55:23.298Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2019-12-26T03:55:23.298Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2019-12-26T03:55:23.299Z caller=main.go:334 host_details="(Linux 4.15.0-1055-azure #60-Ubuntu SMP Thu Aug 8 18:29:07 UTC 2019 x86_64 prometheus-server-5dd6459946-mx9d9 (none))"
level=info ts=2019-12-26T03:55:23.299Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2019-12-26T03:55:23.299Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2019-12-26T03:55:23.302Z caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2019-12-26T03:55:23.302Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2019-12-26T03:55:23.302Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1574215200000 maxt=1574899200000 ulid=01DTR8HS5BRVD6X673J5QHKG9R
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1574215200000 maxt=1574899200000 ulid=01DV2BZ9YV60S4N32CMXZAXWWE
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1574899200000 maxt=1576108800000 ulid=01DVZMGVK53P5DTMY2DXDE2FGM
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576108800000 maxt=1576281600000 ulid=01DW17KQ2JKP2ESRHARBBDEAJC
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576281600000 maxt=1576454400000 ulid=01DW6CFJS1HNBC0NQ2TJ634CNH
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576454400000 maxt=1576627200000 ulid=01DWBHET44BACZA7MDB1WEVMK3
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576627200000 maxt=1576800000000 ulid=01DWZF2BXW5VV7KWP1P4EF3QJM
level=info ts=2019-12-26T03:55:23.303Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576800000000 maxt=1576972800000 ulid=01DWZFB4361MQK9CEHQ7FSF10R
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576972800000 maxt=1577145600000 ulid=01DWZFKF7HMEARWJX3N23HMXVA
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1574899200000 maxt=1576108800000 ulid=01DWZGJN9TRG1KVWW2T2FQPR4X
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576108800000 maxt=1576281600000 ulid=01DWZJ4FW244AS8VDCCC0PP1Q0
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576281600000 maxt=1576454400000 ulid=01DWZJCXB5CQWWSSN51FJTJFAB
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576454400000 maxt=1576627200000 ulid=01DWZJNJ5PXPYPTGG3KQQ07A5Z
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576627200000 maxt=1576800000000 ulid=01DWZJXH1XST8FPGX920TJQ2ZJ
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576800000000 maxt=1576972800000 ulid=01DWZK63VSBXGW6E7NBVPHPG4Z
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1576972800000 maxt=1577145600000 ulid=01DWZKDRCJ1CDFWF8C5V17HT50
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1574899200000 maxt=1576108800000 ulid=01DWZKNK01SQMD2V4PDKBK2C2Z
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1577318400000 maxt=1577325600000 ulid=01DX028X3Z75ZKTS03G5NGVBA0
level=info ts=2019-12-26T03:55:23.304Z caller=repair.go:59 component=tsdb msg="found healthy block" mint=1577145600000 maxt=1577318400000 ulid=01DX04866V989V51KX34AQ7TVY
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:526 msg="Stopping scrape discovery manager..."
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:540 msg="Stopping notify discovery manager..."
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:562 msg="Stopping scrape manager..."
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:536 msg="Notify discovery manager stopped"
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:522 msg="Scrape discovery manager stopped"
level=info ts=2019-12-26T03:55:23.313Z caller=manager.go:814 component="rule manager" msg="Stopping rule manager..."
level=info ts=2019-12-26T03:55:23.313Z caller=manager.go:820 component="rule manager" msg="Rule manager stopped"
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:556 msg="Scrape manager stopped"
level=info ts=2019-12-26T03:55:23.313Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2019-12-26T03:55:23.313Z caller=main.go:727 msg="Notifier manager stopped"
level=error ts=2019-12-26T03:55:23.313Z caller=main.go:736 err="opening storage failed: unexpected corrupted block:map[01DTR8HS5BRVD6X673J5QHKG9R:open /data/01DTR8HS5BRVD6X673J5QHKG9R/chunks: no such file or directory 01DV2BZ9YV60S4N32CMXZAXWWE:open /data/01DV2BZ9YV60S4N32CMXZAXWWE/chunks: no such file or directory 01DVZMGVK53P5DTMY2DXDE2FGM:open /data/01DVZMGVK53P5DTMY2DXDE2FGM/chunks: no such file or directory 01DW17KQ2JKP2ESRHARBBDEAJC:open /data/01DW17KQ2JKP2ESRHARBBDEAJC/chunks: no such file or directory 01DW6CFJS1HNBC0NQ2TJ634CNH:open /data/01DW6CFJS1HNBC0NQ2TJ634CNH/chunks: no such file or directory 01DWBHET44BACZA7MDB1WEVMK3:open /data/01DWBHET44BACZA7MDB1WEVMK3/chunks: no such file or directory 01DWZF2BXW5VV7KWP1P4EF3QJM:open /data/01DWZF2BXW5VV7KWP1P4EF3QJM/chunks: no such file or directory 01DWZFB4361MQK9CEHQ7FSF10R:open /data/01DWZFB4361MQK9CEHQ7FSF10R/chunks: no such file or directory 01DWZFKF7HMEARWJX3N23HMXVA:open /data/01DWZFKF7HMEARWJX3N23HMXVA/chunks: no such file or directory 01DWZGJN9TRG1KVWW2T2FQPR4X:open /data/01DWZGJN9TRG1KVWW2T2FQPR4X/chunks: no such file or directory 01DWZJ4FW244AS8VDCCC0PP1Q0:open /data/01DWZJ4FW244AS8VDCCC0PP1Q0/chunks: no such file or directory 01DWZJCXB5CQWWSSN51FJTJFAB:open /data/01DWZJCXB5CQWWSSN51FJTJFAB/chunks: no such file or directory 01DWZJNJ5PXPYPTGG3KQQ07A5Z:open /data/01DWZJNJ5PXPYPTGG3KQQ07A5Z/chunks: no such file or directory 01DWZJXH1XST8FPGX920TJQ2ZJ:open /data/01DWZJXH1XST8FPGX920TJQ2ZJ/chunks: no such file or directory 01DWZK63VSBXGW6E7NBVPHPG4Z:open /data/01DWZK63VSBXGW6E7NBVPHPG4Z/chunks: no such file or directory 01DWZKDRCJ1CDFWF8C5V17HT50:open /data/01DWZKDRCJ1CDFWF8C5V17HT50/chunks: no such file or directory 01DWZKNK01SQMD2V4PDKBK2C2Z:open /data/01DWZKNK01SQMD2V4PDKBK2C2Z/chunks: no such file or directory 01DX028X3Z75ZKTS03G5NGVBA0:open /data/01DX028X3Z75ZKTS03G5NGVBA0/chunks: no such file or directory 01DX04866V989V51KX34AQ7TVY:open /data/01DX04866V989V51KX34AQ7TVY/chunks: no such file or directory]"
```
