### ISSUE TITLE
"Error on ingesting samples that are too old or are too far into the future" when scraping metrics WITHOUT timestamps

### ISSUE THREAD

**Issue by pawadski** [prometheus/prometheus#6554]
It appears that Prometheus does not accept my metrics. The metrics I am trying to scrape do not include timestamps. This seems to be allowed in the documentation:
```
# Minimalistic line:
metric_without_timestamp_and_labels 12.47
```
My metrics that are failing:
```
# HELP cpanel_resellers Number of cPanel users with Reseller privileges
# TYPE cpanel_resellers gauge
cpanel_resellers 0
# HELP cpanel_domains_remote Number of Remote domains
# TYPE cpanel_domains_remote gauge
cpanel_domains_remote 1
# HELP cpanel_domains_local Number of Local domains
# TYPE cpanel_domains_local gauge
cpanel_domains_local 40
# HELP cpanel_domains_total Total number of domains
# TYPE cpanel_domains_total gauge
cpanel_domains_total 41
# HELP cpanel_users Number of cPanel users
# TYPE cpanel_users gauge
cpanel_users 11
# HELP cpanel_mailq_queue_frozen Number of frozen messages in the mail queue
# TYPE cpanel_mailq_queue_frozen gauge
cpanel_mailq_queue_frozen 0
# HELP cpanel_mailq_queue_total Number of messages in the mail queue
# TYPE cpanel_mailq_queue_total gauge
cpanel_mailq_queue_total 0
```
These metrics validate within promtool (with warnings regarding _total suffix of course, but that is to be fixed later - for now I'd appreciate the metrics importing)

I have another box running version 2.7.2 and it has no problem importing these metrics.

## Bug Report
**What did you do?**
Setup metrics scraping
**What did you expect to see?**
Metrics being scraped
**What did you see instead? Under which circumstances?**
```
Error on ingesting samples that are too old or are too far into the future
```

**Environment**

* System information:

	Linux 3.10.0-693.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.15.1 (branch: HEAD, revision: 8744510c6391d3ef46d8294a7e1f46e57407ab13)
  build user:       root@4b1e33c71b9d
  build date:       20191225-01:04:15
  go version:       go1.13.5

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 30s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "monitoring.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'cpanel'
    static_configs:
      - targets:
        - 'target_host:2089'
```

* Logs:
```
Jan  4 20:32:46 box prometheus: level=warn ts=2020-01-04T19:32:46.888Z caller=scrape.go:1170 component="scrape manager" scrape_pool=cpanel target=http://target_host:2089/metrics msg="Error on ingesting samples that are too old or are too far into the future" num_dropped=7
Jan  4 20:32:46 box prometheus: level=warn ts=2020-01-04T19:32:46.889Z caller=scrape.go:945 component="scrape manager" scrape_pool=cpanel target=http://target_host:2089/metrics msg="appending scrape report failed" err="out of bounds"
```
