### ISSUE TITLE
Labels with newline characters cannot be used for relabeling

### ISSUE THREAD

**Issue by jutley** [prometheus/prometheus#6568]
## Bug Report
**What did you do?**
Prometheus seems to flatten multi-line label values into single-line values. When we create a relabel_configs rule that tries to use such a label as a source, it does not work. Here is an example job I created in Prometheus v2.15.1.

```yaml
- job_name: demonstrate-relabel-newline-bug
  honor_labels: true
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names: [prometheus]
  relabel_configs:
  - action: replace
    source_labels: [__address__]
    target_label: source_label_single_line
    replacement: source label single line
  - action: replace
    source_labels: [__address__]
    target_label: source_label_multi_line
    replacement: |
      source label
      multi line
  - action: replace
    source_labels: [source_label_single_line]
    target_label: destination_label_single_line
    replacement: destination label single line
  - action: replace
    source_labels: [source_label_multi_line]
    target_label: destination_label_multi_line
    replacement: |
      destination label
      multi line
```

Here, we create both a single-line label and a multi-line label. I then try to use each as a source in the next relabel steps, and we can see in the result that the multi-line label doesn't seem to work.

![image](https://user-images.githubusercontent.com/5660346/71843757-6ca2b500-3079-11ea-9ceb-7b9c88be62f2.png)

**What did you expect to see?**

I expected that I would be able to use this multi-line label as a source label, as it ultimately appears in the "targets" page of the ui: a flattened single line.

**What did you see instead? Under which circumstances?**

The new label created based on the multi-line label simply does not appeat.

**Environment**

* System information:

```
$ uname -srm
Linux 4.19.43-coreos x86_64
```

* Prometheus version:

```
$ prometheus --version
prometheus, version 2.15.1 (branch: HEAD, revision: 8744510c6391d3ef46d8294a7e1f46e57407ab13)
  build user:       root@4b1e33c71b9d
  build date:       20191225-01:04:15
  go version:       go1.13.5
```

* Prometheus configuration file:

* Logs:

At the info label, there are no relevant logs.
