### ISSUE TITLE
Prometheus configuration fails after adding basic_auth fields

### ISSUE THREAD

**Issue by rajputvishwas** [prometheus/prometheus#6571]
## Proposal

**Use case. Why is this important?**
I am using Prometheus and Grafana on OKD(3.11) all in one cluster. I want to integrate  prometheus to grafana. While configuring data source for prometheus in grafana, It requires some authentication mechanism. Here, I have decided to go with basic auth mechanism and hence added basic_auth to prometheus configuration file as mentioned below. After adding username and password prometheus deployment fails. It doesn't recognize username and password field.

*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
 I have added this under scrape_config: section /etc/prometheus/prometheus.yaml
   basic_auth:                                                                             
    username: 'admin'                                                                       
    password: 'admin'
 
**What did you expect to see?**
    Configuration should load successfully 
 
**What did you see instead? Under which circumstances?**
   It ends up with error and doesn't recognize username and password field

**Environment**
  
 Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

 oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.65.117.148:8443
kubernetes v1.11.0+d4cacc0

* System information:

   Linux 4.4.0-1083-aws x86_64
	insert output of `uname -srm` here

* Prometheus version:
    
       prometheus 2.4.1
	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
I am using default configuration with basic_auth.
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
   
    static_configs:
    - targets: ['localhost:9090']
    
    basic_auth:                                                                             
    username: 'admin'                                                                       
    password: 'admin'       
    


```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
caller=main.go:736 err="error loading config from \"/etc/prometheus/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/prometheus/prometheus.yml\"): parsing YAML file /etc/prometheus/prometheus.yml: yaml: unmarshal errors:\n  line 42: field username not found in type config.plain\n  line 43: field password not found in type config.plain"

```
insert Prometheus and Alertmanager logs relevant to the issue here
```
