### ISSUE TITLE
Exposing Prometheus over nginx ingress fanout approach

### ISSUE THREAD

**Issue by gopurx** [prometheus/prometheus#6654]
## Proposal
**Use case. Why is this important?**
Leveraging one IP to expose all apps related to operations using ingress fanout routing
*“Nice to have” is not a good use case. :)*

## Bug Report
**What did you do?**
Trying to add Prometheus which is installed to existing ingress controller using ingress fanout routing.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - path: /prometheus(/|$)(.*)
        backend:
          serviceName: prometheus-server
          servicePort: 80
```
**What did you expect to see?**
expecting to see Prometheus web frontend exposed on ingress controller using fanout approach
**What did you see instead? Under which circumstances?**
Receiving 404 error, with above ingress definition in place, url “http://<>/prometheus/ getting redirected to http://<>/graph/ and then 404 error page getting rendered. When url adjusted to http://<>/prometheus/graph some of webcontrols gets rendered with lots of errors on browser console.

**Environment**
Azure Kubernetes Service, Kubernetes version 1.13.12

* System information: Linux 4.15.0-1060-azure x86_64

* Prometheus version: 2.13.1

* Alertmanager version: Not enabled

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

* Alertmanager configuration file:

* Logs:
