### ISSUE TITLE
[feateure]  Filter consul_sd_configs by ServiceMeta

### ISSUE THREAD

**Issue by dekimsey** [prometheus/prometheus#6680]
## Proposal
**Use case. Why is this important?**

I would like to see `consul_sd_configs` support ServiceMeta kv filtering in addition to the built-in NodeMeta. We have services which must not be scraped and dropped after the fact as the act of scraping them causes functional problems. Or services whose prometheus exports are just slightly different. As different Teams have different configuration needs in prometheus.

We have a large number of services, and we attach Consul ServiceMeta to indicate information like team/project ownership and what functional clusters they are apart of. We'd like to be able to have jobs be specific to the projects (allowing for a more coarse enrollment in prometheus).
Right now, our only choice is to template out the prometheus.yml and enumerate the list of eligible services which is kind of clunky.

## Bug Report

n/a

**Environment**

* System information:

	Linux 3.10.0-1062.9.1.el7.x86_64 x86_64

* Prometheus version:

```
prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5
```

* Prometheus configuration file:

```
- job_name: pa-via-jmx
   consul_sd_configs:
      - server: 'http://localhost:8500'
        service_meta:
            job: pa
            prom_exporter: jmx

- job_name: pa-via-jmetrics
   consul_sd_configs:
      - server: 'http://localhost:8500'
        service_meta:
            job: pa
            prom_exporter: jmetrics
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by brian-brazil** [comment]
This is already possible via relabelling.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by dekimsey** [comment]
Thanks @brian-brazil, I tried to indicate out that relabeling didn't solve the issue. Currently I *have* to avoid triggering the scrape in the first-place. There's also some advantage for us in being able to configure the scrapes behavior per project.

**Comment by roidelapluie** [comment]
Please use the mailing list.

You should look at relabel_configs, not metrics_relabel_configs.

**Comment by dekimsey** [comment]
Thank you @roidelapluie, I'll post on the forums and see if others are interested in it. I'd be happy to contribute as the code changes look like they'd be pretty sane.

For what it's worth, I am using relabel_configs with the keep/drop actions to filter by ServiceMeta. I was just noticing the # of blocking calls on Consul is quite high since the catalog is scanned for updates before relabel_configs takes effect.

**Comment by roidelapluie** [comment]
Thank you for your reply.

I would like to let you know that I did have a deeper look at your issue.

It is not possible, at the API level, to get a catalog of services that match ServiceNodes.

I would propose instead that you look at the "tags" parameter in the consul_sds_config:

```
  - job_name: 'web'
    scrape_interval: 30s
    consul_sd_configs:
      - tags: ["prometheus", "scrape-30s"]
    relabel_configs:
    - regex: "__meta_consul_service_metadata_(.+)"
        action: labelmap
  - job_name: 'web'
    scrape_interval: 60s
    consul_sd_configs:
      - tags: ["prometheus", "scrape-60s"]
    relabel_configs:
    - regex: "__meta_consul_service_metadata_(.+)"
        action: labelmap
```

If you have a servicemeta team it will be assigned as a team label, too.

The prometheus tag would ensure only relevant services are watched and we add another tag for the duration of the scrape.
