### ISSUE TITLE
Error on ingesting out-of-order samples, with HA Alertmanager configured

### ISSUE THREAD

**Issue by whoamiUNIX** [prometheus/prometheus#6688]
## Proposal
**Use case. Why is this important?**
Because it looks like that federation and external labels and then together with HA Alertmanager there is issue.

## Bug Report
**What did you do?**
There is one k8s prometheus which contain also replica(prometheus-k8s-0, prometheus-k8s-1). Then there are 2 Prometheus installed on VM. This prometheus VM are located in different datacenters. On this prometheus VM(prometheus1, prometheus2) is also configured HA alertmanager(alertmanager1, alertmanager2). I'm getting metrics from federation which is configured exactly same on both Prometheus to get metrics from prometheus-k8s-* . Right now not getting any duplicate alert/firing as I configured labels to be same from both prometheus then duplicate firing issue is solved but I'm getting right now "ingesting out-of-order"
Time sync is working properly!

Alertmanager use group_by alertname.

I'm using the following because I need to have exact labels as prevention for duplicate firing from federation. Because if I disable this then one alertmanager get "prometheus-k8s-1" and second one "prometheus-k8s-0" and then instead of firing1 I got firing2.

If you need more information please let me know.

```
    metric_relabel_configs:
     - source_labels: [prometheus_replica]
       regex: 'prometheus-k8s-.*'
       target_label: 'prometheus_replica'
       replacement: 'replicated'
```

**What did you expect to see?**
I just want to solve issue with "out-of-order" and keep this configuration because we do not get any duplicate firing what is perfect.

**What did you see instead? Under which circumstances?**
I see out-of-order warning message in log but not getting any duplicate firing what is correct.

**Environment**

* System information:
Linux 3.10.0-1062.9.1.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

* Alertmanager version:
alertmanager, version 0.19.0 (branch: HEAD, revision: 7aa5d19fea3f58e3d27dbdeb0f2883037168914a)
  build user:       root@587d0268f963
  build date:       20190903-15:01:40
  go version:       go1.12.8

* Prometheus configuration file:
I have same configuration on second prometheus VM just external label is "DC: Europe2"
```
global:
  scrape_interval:     60s
  evaluation_interval: 60s
  external_labels:
    DC: Europe1
# Alertmanager configuration + relabel
alerting:
  alert_relabel_configs:
  - source_labels: [DC]
    regex: (.+)\d+
    target_label: DC
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager1:9093', 'alertmanager2:9093']
rule_files:
  - "alerts/*.yml"
scrape_configs:
  - job_name: 'ocp_federation'
    honor_timestamps: true
    honor_labels: true
    metrics_path: '/federate'
    scheme: https
    params:
      'match[]':
        - '{job="node-exporter"}'
        - '{job="etcd"}'
        - '{job="alertmanager-main"}'
        - '{job="api"}'
        - '{job="apiserver"}'
        - '{job="catalog-operator-metrics"}'
        - '{job="cluster-autoscaler-operator"}'
        - '{job="cluster-monitoring-operator"}'
        - '{job="cluster-version-operator"}'
        - '{job="controller-manager"}'
        - '{job="dns-default"}'
        - '{job="grafana"}'
        - '{job="image-registry"}'
        - '{job="kube-controller-manager"}'
        - '{job="kubelet"}'
        - '{job="kube-state-metrics"}'
        - '{job="machine-api-operator"}'
        - '{job="marketplace-operator-metrics"}'
        - '{job="metrics"}'
        - '{job="oauth-openshift"}'
        - '{job="olm-operator-metrics"}'
        - '{job="openshift-state-metrics"}'
        - '{job="prometheus-k8s"}'
        - '{job="prometheus-operator"}'
        - '{job="router-internal-default"}'
        - '{job="scheduler"}'
        - '{job="sdn"}'
        - '{job="telemeter-client"}'
    metric_relabel_configs:
     - source_labels: [prometheus_replica]
       regex: 'prometheus-k8s-.*'
       target_label: 'prometheus_replica'
       replacement: 'replicated'

    static_configs:
    - targets: ['myTargetURL']

```

* Logs:
I see this issue on both prometheus VM.
```
    Jan 24 09:39:30 prometheus1 prometheus[1243]: level=warn ts=2020-01-24T09:39:30.702Z caller=scrape.go:1164 component="scrape manager" scrape_pool=ocp_federation target="https://myurlishere" msg="Error on ingesting out-of-order samples" num_dropped=26
    Jan 24 10:01:33 prometheus1 prometheus[1243]: level=warn ts=2020-01-24T10:01:33.755Z caller=scrape.go:1164 component="scrape manager" scrape_pool=ocp_federation target="https://myurlishere" msg="Error on ingesting out-of-order samples" num_dropped=101
```
