### ISSUE TITLE
React UI: Targets page doesn't work if there job name with special characters

### ISSUE THREAD

**Issue by eugbaranov** [prometheus/prometheus#6732]
**What did you do?**

Opened `/new/targets` page

**What did you expect to see?**

List of targets

**What did you see instead? Under which circumstances?**

Blank page. Every time.
Opening Chrome console reveal JavaScript error:
```
react-dom.production.min.js:4482 DOMException: Failed to execute 'querySelectorAll' on 'Document': 'series-labels-prometheus/test' is not a valid selector.
```

**Environment**

* Prometheus version:
prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5

* Prometheus configuration file:
Just have a job with name containing e.g. forward slash:

```
scrape_configs:
  - job_name: 'prometheus/test'
    static_configs:
      - targets: ['docker.for.win.localhost:9090']
```
