### ISSUE TITLE
azure_sd_configs environment default not being applied 

### ISSUE THREAD

**Issue by szymon3** [prometheus/prometheus#6758]
**What did you do?**
I have created system managed identity in Azure on my Prometheus VM and assigned _Contributor_ permission on target Resource Group where is my second VM with node-exporter (configured on port 9100). 

**What did you expect to see?**
Properly discovered second VM in Prometheus SD

**What did you see instead? Under which circumstances?**
I see error in Prometheus logs.

**Environment**
I run Prometheus on Azure VM.

* System information:

Linux 5.0.0-1029-azure x86_64

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

* Prometheus version:

prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5

* Alertmanager version:

I don't have alertmanager

* Prometheus configuration file:
```
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s

  external_labels:
    environment: prometheus.mydomain.com

rule_files:
  - /etc/prometheus/rules/*.rules

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - localhost:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
  - job_name: bi
    metrics_path: /metrics
    static_configs:
    - targets:
      - 'working target here'
  - job_name: azure_service_discovery
    azure_sd_configs:
      - authentication_method: ManagedIdentity
        port: 9100
        subscription_id:  XXXXXXX

```

* Logs:
```
level=error ts=2020-02-05T15:08:05.636Z caller=azure.go:317 component="discovery manager scrape" discovery=azure msg="Unable to get network interface" name=/subscriptions/XXX/resourceGroups/magenes-ccc/providers/Microsoft.Network/networkInterfaces/target-nic-name-here err="network.InterfacesClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code=\"AuthorizationFailed\" Message=\"The client 'XXXXXXXXX' with object id 'XXXXXXXXXX' does not have authorization to perform action 'Microsoft.Network/networkInterfaces/read' over scope '/subscriptions/XXXXXXXXX/resourceGroups/magenes-ccc/providers/Microsoft.Network/networkInterfaces/target-nic-name-here' or the scope is invalid. If access was recently granted, please refresh your credentials.\""
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by szymon3** [comment]
@brian-brazil it's not a question, but bug report in my opinion.

**Comment by brian-brazil** [comment]
This looks like a permissions issue on your end, not a bug in Prometheus itself.

**Comment by szymon3** [comment]
I solved it. `environment` parameter in azure_sd_config is actually required. I thought it's optional since it has default value = AzurePublicCloud.

**Comment by brian-brazil** [comment]
Are you saying you explicitly needed to provide `AzurePublicCloud` as the value?

**Comment by szymon3** [comment]
Exactly. Here's how my config looks like now:
```
- azure_sd_configs:
    - authentication_method: ManagedIdentity
      environment: AzurePublicCloud
      port: 9100
      subscription_id: 147faf87-d87f-4b62-bf0c-a004924c652f
    job_name: azure_service_discovery
``

**Comment by szymon3** [comment]
Exactly.
Here's my fixed config:
```
- azure_sd_configs:
    - authentication_method: ManagedIdentity
      environment: AzurePublicCloud
      port: 9100
      subscription_id: XXXXX
    job_name: azure_service_discovery
```

**Comment by brian-brazil** [comment]
That would be a bug then.

**Comment by simonpasquier** [comment]
I can't reproduce this.

**Comment by simonpasquier** [comment]
@szymon3 can you share the copy of the configuration as displayed in the UI when you don't define the `environment` field?

**Comment by szymon3** [comment]
@simonpasquier 
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    environment: prometheus.XXXXX.eu
rule_files:
- /etc/prometheus/rules/*.rules
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/prometheus/file_sd/node.yml
    refresh_interval: 5m
- job_name: azure_service_discovery
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  azure_sd_configs:
  - authentication_method: ManagedIdentity
    port: 9100
    subscription_id: XXXXXXXXXXXXX
    refresh_interval: 5m
 ```

**Comment by roidelapluie** [comment]
Just like @simonpasquier I can not reproduce this.

When I explicitely set it to empty, I get another error:

```
level=error ts=2020-02-09T14:15:33.074Z caller=refresh.go:79 component="discovery manager scrape" discovery=azure msg="Unable to refresh target groups" err="could not create Azure client: autorest/azure: There is no cloud environment matching the name \"\""
```

The error you pasted says:
```
If access was recently granted, please refresh your credentials.
```
Maybe you tried too soon?

**Comment by simonpasquier** [comment]
Hmm, I tried this configuration locally and `environment` defaults to `AzurePublicCloud` for me.

```yaml
# This is my original configuration file
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    environment: prometheus.XXXXX.eu
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: azure_service_discovery
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  azure_sd_configs:
  - authentication_method: ManagedIdentity
    port: 9100
    subscription_id: XXXXXXXXXXXXX
    refresh_interval: 5m
```

![image](https://user-images.githubusercontent.com/2587585/74140086-ba6c8900-4bf4-11ea-9691-1ab0b5f94bf4.png)
