### ISSUE TITLE
Support "data" and/or "file" scheme for scrapes

### ISSUE THREAD

**Issue by candlerb** [prometheus/prometheus#6791]
## Proposal
Prometheus scraping currently supports schemes "http" and "https".  The suggestion is to add "[data](https://en.wikipedia.org/wiki/Data_URI_scheme)" and/or "[file](https://en.wikipedia.org/wiki/File_URI_scheme)" schemes.

## scheme: data
Use case: using service discovery metadata to create per-instance timeseries containing metadata labels, in the spirit of [how to have labels for machine roles](https://www.robustperception.io/how-to-have-labels-for-machine-roles).

```
- job: ec2
  ec2_sd_configs: ...
  ... normal endpoint scrape

- job: ec2_meta
  ec2_sd_configs: ...
  scheme: data
  metrics_path: ",ec2_meta{} 1"
  relabel_configs:
    - source_labels: [__meta_ec2_platform]
      target_label: platform
    - source_labels: [__meta_ec2_vpc_id]
      target_label: vpc_id
    ... etc
```

You will then end up with one additional metric per target, of the form

```
ec2_meta{instance="foo", platform="x1", vpc_id="y2"...} 1
ec2_meta{instance="bar", platform="x2", vpc_id="y2"...} 1
```

This can be done today by relabelling `__address__` to point to a dummy local webserver which is configured so that it always returns `ec2_meta{} 1`.  However if you have 1,000 targets this means 1,000 http scrapes.  The above example also neatly encapsulates the configuration in one place.

## scheme: file

Use case: creating static timeseries to join on in alerting rules.  Example:

```
# prometheus scrape job
- job: alert_config
  scheme: file
  metrics_path: /etc/prometheus/alert_interfaces.prom
  static_configs:
    - targets: [localhost]  # ignored?
  honor_labels: true

# alert_interfaces.prom
ifIsCritical{instance="sw1",ifName="GigabitEthernet0/24"} 1
ifIsCritical{instance="sw2",ifName="GigabitEthernet0/1"} 1
ifIsCritical{instance="sw2",ifName="GigabitEthernet0/23"} 1

# alerting rule
- name: InterfaceRules
  rules:
  - alert: criticalInterfaceError
    expr: (ifOperStatus != 1) * on (instance, ifName) group_left ifIsCritical
```

This use case is less important, since (a) it's fairly easy to set up a http server for this purpose, e.g. by running node_exporter with textfile_collector, and (b) a single scrape collects all the metrics in one pass, so it's efficient.

**Comment by roidelapluie** [comment]
This sounds like abusing Prometheus as a general service discovery mechanism. You could do this by combining relabel config. e.g by scraping a fake endpoint by changing __address__. You would have a metric up with value 0 but that would provide the same labels as this.

**Comment by candlerb** [comment]
> You could do this by combining relabel config. e.g by scraping a fake endpoint by changing `__address__`.

Yes, that's what I meant as the alternative.  It would be something like this:

```
- job: ec2_meta
  ec2_sd_configs: ...
  metrics_path: /static/ec2_meta
  relabel_configs:
    - source_labels: [__meta_ec2_platform]
      target_label: platform
    - source_labels: [__meta_ec2_vpc_id]
      target_label: vpc_id
    ... etc
    - target_label: __address__
      replacement: 127.0.0.1:8080
```

Then you have to run a webserver on port 8080, configured so that `/static/ec2_meta` returns a static page containing "`ec2_meta{} 1`"

Apart from being somewhat fiddly to configure, the main issue is that this dumb endpoint will be scraped N times the number of targets from the SD mechanism.  (Unless prometheus caches the results when scraping the exact same target+params?)

As for "abusing Prometheus as a general service discovery mechanism": what I'm actually trying to do is to use the existing Prometheus SD mechanisms as intended. but to separate out those labels which might be changing over time into their own timeseries so that the main metrics become long-lived timeseries.  This is better explained at:

* https://www.robustperception.io/target-labels-are-for-life-not-just-for-christmas/
* https://www.robustperception.io/how-to-have-labels-for-machine-roles/
* https://www.robustperception.io/exposing-the-software-version-to-prometheus/

**Comment by roidelapluie** [comment]
My point is that you don't need the web server.

```
- job: ec2_meta
  ec2_sd_configs: ...
  metrics_path: /static/ec2_meta
  relabel_configs:
    - source_labels: [__meta_ec2_platform]
      target_label: platform
    - source_labels: [__meta_ec2_vpc_id]
      target_label: vpc_id
    ... etc
    - target_label: __address__
      replacement: 127.0.0.1:1777
```

and then the only difference between this and your proposal is that the metric is named up. The http requests should not affect your prom server. You could make a recording rule if you really want ec2_meta as metric name.
