### ISSUE TITLE
[WAL CORRUPT]checkpoint data not produce

### ISSUE THREAD

**Issue by bugme1024** [prometheus/prometheus#6813]
**What did you do?**
server disk is full

**What did you expect to see?**
delete some data in disk and make room for prometheus, it will make checkpoint data again

**What did you see instead? Under which circumstances?**

it just print error log and can not pass the corrupt wal.

and it just keep 6 hour data in memory.

**Environment**

* System information:

	insert output of `uname -srm` here
Linux 3.10.107-1-tlinux2-0046 x86_64
* Prometheus version:

	insert output of `prometheus --version` here
  build user:       root@7a9dbdbe0cc7
  build date:       20190818-13:53:16
  go version:       go1.12.8
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)
 not alermanager
* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)

# my global config
#webport=9.37.141.242:4009
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['ip1:port']



  - job_name: "tikv"
    honor_labels: true # don't overwrite job & instance labels
    static_configs:
    - targets:

      - ''ip2:port'
```

* Logs:
```

insert Prometheus and Alertmanager logs relevant to the issue here

level=warn ts=2019-11-25T18:08:34.610Z caller=scrape.go:945 component="scrape manager" scrape_pool=tidb target=http://ip:15021/metrics msg="appending scrape report failed" err="write to WAL: log samples: write data/wal/00000640: no space left on device"

level=error ts=2019-11-27T08:34:10.927Z caller=db.go:561 component=tsdb msg="compaction failed" err="head truncate failed (in compact): create checkpoint: read segments: corruption in segment data/wal/00000640 at 92284877: unexpected checksum ab7d541d, expected da5de297"
```
