### ISSUE TITLE
prometheus fails due to too many open files

### ISSUE THREAD

**Issue by cjsin** [prometheus/prometheus#6828]
**What did you do?**

regular system started (booted) after a power outage.
prometheus service was enabled for the multi-user systemd runlevel/target.

**What did you expect to see?**

prometheus service started successfully after a power event. 

Additionally an administrator should be able to start the service without worrying that they are deleting data by removing files (because the service will not start with 'too many files').

**What did you see instead? Under which circumstances?**

prometheus did not start, it instead failed with an error, seemingly due to many xxxx.tmp directories in the /var/lib/promethus directory (though, many less than the system open file limit)

- The failure occurred after the host was powered up, after being shut down for a local power supply work by the electricty company. The service was expected to start as normal and run as normal but instead appears to have failed within 30 seconds, due to a number of existing temporary files from the prior running of the service before the power outage and associated service restart.

- The number of /var/lib/prometheus/XXXXXXXXXXXXXXXXXXXXXXXXXX.tmp  empty directories far exceeds the number of populate directories, and on my system there are 118717 of these 'xxxx.tmp' directories. (which exceeds the ulimit -n limit by a factor of 10). 

The number of '.tmp' directories is quite large with respect to the open-file limit., many '.tmp' directories contain a 'chunks' file.

error message example:

```
open block /var/lib/prometheus/XXXXXXXXXXXXXXXXXXXXXXX: open /var/lib/prometheus/XXXXXXXXXXXXXXXXXXXXXXXX/tombstones: too many open files
```

(the XXXXX values are substituted)

**Environment** 

ulimit command for open files limit:

```
# ulimit -n
16385
```

count of files in the data directory:

```
# find  /var/lib/prometheus/ -type f|wc -l
2895
```

The prometheus service should either not leave around thousands of temporary files, or else it should be able to cope with the thousands of files that it leaves around.

The files within /var/lib/prometheus are mostly of the form:

```
    /var/lib/prometheus/<26-character-string>/index
    /var/lib/prometheus/<26-character-string>/meta.json
    /var/lib/prometheus/<26-character-string>/tombstones
    /var/lib/prometheus/<26-character-string>/chunks/<6-character-number>
```

A few directories have the form:

```
    /var/lib/prometheus/<26-character-string>.tmp
```

this is a prometheus service being started by a very simple systemd unit file, with the following contents:

/lib/systemd/system/prometheus.service:

```
    [Unit]
    Description=Prometheus
    [Service]
    User=prometheus
    EnvironmentFile=/etc/sysconfig/prometheus
    ExecStart=/opt/prometheus/prometheus $OPTIONS
   [Install]
   WantedBy=multi-user.target
 ```

service options file (RedHat/Centos/Fedora):

```
$> egrep -v "^#" /etc/sysconfig/prometheus 
OPTIONS="--config.file=/etc/prometheus/prometheus.yml --web.listen-address=A.B.C.D:9090 --storage.tsdb.path=/var/lib/prometheus --storage.tsdb.retention=900d"
```

Yaml configuration file (hostnames changed):

```
# cat /etc/prometheus/prometheus.yml 
global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: node
    static_configs:
    - targets:
      - x:9100
      - y:9100
      - z:9100
      - a:9100

  - job_name: crypto-prices
    static_configs:
    - targets:
      - x:9101
    scrape_interval: 60s
    scrape_timeout:  55s

  - job_name: anotherjob
    static_configs:
    - targets:
      - x:9102
    scrape_interval: 30s
    scrape_timeout:  25s

  - job_name: sensors
    static_configs:
    - targets:
      - x:9103
      - ys:9103
      - z:9103
```

* System information:
  
```
    fedora 30
```

* insert output of `uname -srm` here

```
Linux 5.1.15-300.fc30.x86_64 x86_64
```

* Prometheus version: 

```
    $> /opt/prometheus/prometheus  --version
    prometheus, version 2.0.0 (branch: HEAD, revision:     0a74f98628a0463dddc90528220c94de5032d1a0)
      build date:       20171108
      go version:       go1.9.2
```

* Alertmanager version:
  not installed

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: node
   (at this point it has regular targets, I won't include the host names)
```

* Alertmanager configuration file:

- no alertmanager configuration as far as I know, it is not in use

* Logs:

hostnames etc redacted

```
Feb 17 06:00:56 XXXXXXX.ZZZZZZZ prometheus[11792]: level=info ts=2020-02-16T19:30:56.686437Z caller=targetmanager.go:71 component="target manager" msg="Starting target manager..."
Feb 17 06:01:00 XXXXXXX.ZZZZZZZ prometheus[11792]: level=error ts=2020-02-16T19:31:00.627849002Z caller=main.go:323 msg="Opening storage failed" err="open block /var/lib/prometheus/XXXXXXXXXXXXXXXXXXXXXX: open /var/lib/prometheus/XXXXXXXXXXXXXXXXXXXxx/tombstones: too many open files"

```

Other information:

System ulimits are larger than the number of files here:

```
$> ulimit -n
16385
```

The number of files in /var/lib/prometheus is less than a quarter of the file handle limit:

```
$> find /var/lib/prometheus/ -type f  | wc -l
2895
```

The directory /var/prometheus DOES contain *many* directories 
of the form /var/lib/prometheus/<XXXXXXXXXXXXXXXXXX>.tmp, 
many containing a file called 'chunks'.

Potential work-around: 

  - delete the 'chunks' files within the '.tmp' directories.
  - it is not at all clear that these files can be deleted without losing data.
  - however you can run:  find /var/lib/prometheues -iwholename "*.tmp/chunks" -delete

I have not yet verified whether I have lost any historical data by deleting these files.

Even this did not help the service to start successfully for me.

Instead, try setting LimitNOFILE in the systemd service file (shitty systemd ignores ulimit settings).

example systemd unit file changes:

```
[Service]
LimitNOFILE=49152
```
