### ISSUE TITLE
Labeldrop caused ingested value different

### ISSUE THREAD

**Issue by ShiningRush** [prometheus/prometheus#6851]
**What did you do?**
using labeldrop to drop some labels  before ingest

**What did you expect to see?**
ingested value not change after drop label
the data before drop bale as below
![image](https://user-images.githubusercontent.com/24238012/74916991-c2e96e80-5401-11ea-9bf4-377ea499b242.png)

**What did you see instead? Under which circumstances?**
ingested value is unexpected
![image](https://user-images.githubusercontent.com/24238012/74917277-3db28980-5402-11ea-89a8-958947b9579e.png)

**Environment**
k8s

* System information:

	Linux 3.10.104-1-tlinux2-0041.tl1 x86_64

* Prometheus version:

prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
  build user:       root@88e419aa1676
  build date:       20191017-13:15:01
  go version:       go1.13.1

* Alertmanager version:
no Alertmanager

* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  external_labels:
    monitor: 'sholdmix-4'
    k8s: 'sholdmix'
scrape_configs:
  - job_name: 'm3coordinator'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:7203']
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: cadvisor 
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
    - api_server: null
      role: node
      namespaces:
        names: []
    relabel_configs:
    - source_labels: [__address__]
      modulus:       5
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^4$
      action:        keep
    - source_labels: [__address__]
      separator: ;
      regex: (.*):10250
      target_label: __address__
      replacement: ${1}:10255
      action: replace
    - source_labels: [__address__]
      separator: ;
      regex: (.*):10251
      target_label: __address__
      replacement: ${1}:10255
      action: replace
    metric_relabel_configs:
    - source_labels: [container_label_io_kubernetes_container_name]
      separator: ;
      regex: POD
      replacement: $1
      action: drop
    - source_labels: [__name__]
      separator: ;
      regex: (container_tasks_state|container_start_time_seconds|container_last_seen)
      replacement: $1
      action: drop
    - separator: ;
      regex: (container_label_(.+)|id|image|name)
      replacement: $1
      action: labeldrop
  - job_name: 'kubernetes-pods'
    metrics_path: /metrics
    scheme: http
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__address__]
      modulus:       5
      target_label:  __tmp_hash
      action:        hashmod
    - source_labels: [__tmp_hash]
      regex:         ^4$
      action:        keep
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: metrics
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__]
      action: replace
      target_label: nodeIp
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\\d+)?;(\\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
  - job_name: 'file-exporters'
    file_sd_configs:
    - files:
      - /etc/prometheus-sd/*.json
remote_read:
  - url: "http://localhost:7201/api/v1/prom/remote/read"
    read_recent: true
remote_write:
  - url: "http://localhost:7201/api/v1/prom/remote/write"
```

* Exe Command
```
/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --storage.tsdb.max-block-duration=2h --storage.tsdb.min-block-duration=2h --storage.tsdb.retention=1d
```

* Logs:
no error logs, just warn log as below
```
...
level=warn ts=2020-02-20T08:51:39.295Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.27.223:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=60
level=warn ts=2020-02-20T08:51:39.304Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.13.97:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=237
level=warn ts=2020-02-20T08:51:39.311Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.109.132.30:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=262
level=warn ts=2020-02-20T08:51:39.330Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://10.51.78.198:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=459
level=warn ts=2020-02-20T08:51:39.333Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.95.27.66:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=184
level=warn ts=2020-02-20T08:51:39.355Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.13.22:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=139
level=warn ts=2020-02-20T08:51:39.514Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.13.96:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=66
level=warn ts=2020-02-20T08:51:39.760Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.26.151:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=130
level=warn ts=2020-02-20T08:51:39.934Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.4.16:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=258
level=warn ts=2020-02-20T08:51:40.097Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.26.90:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=54
level=warn ts=2020-02-20T08:51:40.114Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://10.239.236.214:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=118
level=warn ts=2020-02-20T08:51:40.169Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.3.211:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=119
level=warn ts=2020-02-20T08:51:40.230Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.26.165:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=155
level=warn ts=2020-02-20T08:51:40.394Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.29.212:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=62
level=warn ts=2020-02-20T08:51:40.540Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.95.13.202:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=78
level=warn ts=2020-02-20T08:51:40.744Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.16.91:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=74
level=warn ts=2020-02-20T08:51:40.866Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.109.131.137:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=203
level=warn ts=2020-02-20T08:51:41.177Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://10.239.238.209:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=58
level=warn ts=2020-02-20T08:51:41.185Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.2.203:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=128
level=warn ts=2020-02-20T08:51:41.424Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.117.155.40:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=259
level=warn ts=2020-02-20T08:51:41.528Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.95.29.12:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=202
level=warn ts=2020-02-20T08:51:41.566Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.16.142:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=67
level=warn ts=2020-02-20T08:51:41.617Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.16.137:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=206
level=warn ts=2020-02-20T08:51:41.808Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.117.132.82:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=132
level=warn ts=2020-02-20T08:51:41.883Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.15.221:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=140
level=warn ts=2020-02-20T08:51:41.910Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.109.132.135:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=228
level=warn ts=2020-02-20T08:51:41.995Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.27.224:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=93
level=warn ts=2020-02-20T08:51:42.132Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.3.210:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=142
level=warn ts=2020-02-20T08:51:42.185Z caller=scrape.go:1164 component="scrape manager" scrape_pool=cadvisor target=http://100.96.26.152:10255/metrics msg="Error on ingesting out-of-order samples" num_dropped=277
...
```
