### ISSUE TITLE
cannot scrape openShift 3.11 routes

### ISSUE THREAD

**Issue by shalberd** [prometheus/prometheus#6854]
What did you do?
Trying to scrape edge-terminated, HAProxy openShift routes (not Kubernetes ingresses) with Prometheus on port 443. The idea is to have one port (443) for scraping and not having to apply networkpolicies to openshift services' ports.

I consulted this, with no result so far
https://prometheus.io/docs/prometheus/latest/configuration/configuration/

What did you expect to see?
I expected to see routes that I tagged with prometheus.io/path: /auth/realms/master/metrics in ServiceDiscovery Section of Prometheus.

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    description: The route for the sample application ..
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"route.openshift.io/v1","kind":"Route","metadata":{"annotations": "spec":{"host":"application.mydomain.com","port":{"targetPort":"8080-tcp"},"tls":{"termination":"edge"},"to":{"kind":"Service","name":"application-service"}}}
    prometheus.io/path: /auth/realms/master/metrics
```

I also applied a clusterrole and clusterrolebinding to the prometheus service account in my dedicated monitoring namespace
```
apiVersion: authorization.openshift.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"authorization.openshift.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"creationTimestamp":null,"name":"prometheus-mon-clusterrole","namespace":""},"rules":[{"apiGroups":[""],"att$
  creationTimestamp: null
  name: prometheus-mon-clusterrole
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "pods", "ingresses", "routes", "routes/status"]
  verbs: ["get", "watch", "list"]
- apiGroups: [ "extensions" ]
  resources: [ "ingresses", "ingresses/status" ]
  verbs: ["get", "watch", "list"]
```

Prometheus config:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
rule_files:
- /etc/prometheus/prometheus.rules
scrape_configs:
- job_name: kubernetes-routes
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: ingress
    namespaces:
      names:
      - prometheus-mon
      - namespace_project_1
      - namespace_project_2
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    insecure_skip_verify: true
  relabel_configs:
  - source_labels: [__meta_kubernetes_ingresses_annotation_prometheus_io_scheme]
    separator: ;
    regex: (https?)
    target_label: __scheme__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_ingresses_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_ingresses_annotation_prometheus_io_username]
    separator: ;
    regex: (.+)
    target_label: __basic_auth_username__
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_ingesses_annotation_prometheus_io_password]
    separator: ;
    regex: (.+)
    target_label: __basic_auth_password__
    replacement: $1
    action: replace
  - separator: ;
    regex: __meta_kubernetes_route_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_ingresses_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_name
    replacement: $1
    action: replace
```

What did you see instead? 
As you can see, my problem is I do not see how I can get Prometheus to pick up the openShift routes.

Under which circumstances?
Prometheus itself and altertmanager are healthy.

Environment

    RHEL/OpenShift 3.11.153

    System information:
    Red Hat Enterprise Linux Server release 7.6 (Maipo)
    Linux  3.10.0-957.el7.x86_64

    Prometheus version:
    prometheus:v2.3.2
    registry.redhat.io/openshift3/prometheus:v3.11.153
