### ISSUE TITLE
kubernetes_sd_config role for istio virtual services

### ISSUE THREAD

**Issue by mlushpenko** [prometheus/prometheus#6866]
## Proposal
**Use case. Why is this important?**
We are using Istio and want to monitor endpoints with blackbox exporter.  Currently, we are using static config like this:
```
- job_name: blackbox-monitor
  metrics_path: /probe
  params:
     module: [http_monitor]
  scrape_timeout: 30s # must be >= timeout settings in blackbox exporter
  static_configs:
  - targets:
     - https://app1.customer1.exmaple.com
     - https://app1.customer2.exmaple.com
     - https://app2.customer2.exmaple.com
```
As the number of our applications and customers grows, it becomes quite painful to maintain such lists. So, having kubernetes discovery would help a lot. I understand this problem is useful for other kinds of ingresses like Ambassador/Kong and whatever others are out there.

So, I am curious if this is something you are considering to support, perhaps as part of ingress role or separately or it's totally out of scope for Prometheus to support different ingresses discovery?
