### ISSUE TITLE
Prometheus doesn't put Application Layer Protocol Negotiation (ALPN) Extension to TLS Client Hello packet.

### ISSUE THREAD

**Issue by yucelalbar** [prometheus/prometheus#6910]
**What did you do?**
Executed Prometheus to scrape metrics from my application over HTTP/2

**What did you expect to see?**
Successful TLS connection between Prometheus and Target. And then HTTP/2 GET query message Prometheus to the target application.

**What did you see instead? Under which circumstances?**
TLS connection can not be established between Prometheus and target. Target is a Nghttp2 server. Nghttp2 server discards the TLS Client Hello packet if it doesn't include ALPN extension header ("Extension: application_layer_protocol_negotiation") equal to "h2".  And I couldn't see this extension header in the TLS Client Hello packet from Prometheus.

**Environment**
Ubuntu 16.04.6 LTS

* System information:

Linux 4.4.0-174-generic x86_64

* Prometheus version:

2.16.0

* Alertmanager version:

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: My Service
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['localhost:7002']
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
I attached screen shot of pcap about this subject.
![image](https://user-images.githubusercontent.com/41573828/75627465-647e7600-5be1-11ea-8c6c-b81043ad8049.png)

Tutorial of nghttp2:
![image](https://user-images.githubusercontent.com/41573828/75627431-1e291700-5be1-11ea-8841-6b1a1f549514.png)
![image](https://user-images.githubusercontent.com/41573828/75627435-27b27f00-5be1-11ea-8365-ca01df9e7076.png)

```
