### ISSUE TITLE
Can't start oficial docker container on arm64

### ISSUE THREAD

**Issue by h2xtreme** [prometheus/prometheus#6943]
**What did you do?**

docker-compose to run the docker container on a arm64 device

**What did you expect to see?**

prometheus up and running

**What did you see instead? Under which circumstances?**

The container crashes

**Environment**

Docker-CE 

* System information:

Ubuntu 20.04

Linux 5.6.0-rc4-arm-64 aarch64

* Prometheus version:

	2.16.0

go version: 1.13.8 on the container
go version: 1.14 on the OS

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

* Logs:
```
level=info ts=2020-03-08T23:43:10.092Z caller=main.go:295 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-03-08T23:43:10.093Z caller=main.go:331 msg="Starting Prometheus" version="(version=2.16.0, branch=HEAD, revision=b90be6f32a33c03163d700e1452b54454ddce0ec)"
level=info ts=2020-03-08T23:43:10.093Z caller=main.go:332 build_context="(go=go1.13.8, user=root@7ea0ae865f12, date=20200214-00:59:16)"
level=info ts=2020-03-08T23:43:10.093Z caller=main.go:333 host_details="(Linux 5.6.0-rc4-arm-64 #20.05.0 SMP PREEMPT Tue Mar 3 16:58:21 MSK 2020 aarch64 6253d342969a (none))"
panic: syscall.Getrlimit failed: operation not permitted

goroutine 1 [running]:
github.com/prometheus/prometheus/pkg/runtime.getLimits(0x7, 0x0, 0x0, 0x2, 0x2)
        /app/pkg/runtime/limits_default.go:39 +0x2b4
github.com/prometheus/prometheus/pkg/runtime.FdLimits(...)
        /app/pkg/runtime/limits_default.go:46
main.main()
        /app/cmd/prometheus/main.go:334 +0x3fe4
level=info ts=2020-03-08T23:43:13.384Z caller=main.go:295 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-03-08T23:43:13.385Z caller=main.go:331 msg="Starting Prometheus" version="(version=2.16.0, branch=HEAD, revision=b90be6f32a33c03163d700e1452b54454ddce0ec)"
level=info ts=2020-03-08T23:43:13.385Z caller=main.go:332 build_context="(go=go1.13.8, user=root@7ea0ae865f12, date=20200214-00:59:16)"
level=info ts=2020-03-08T23:43:13.386Z caller=main.go:333 host_details="(Linux 5.6.0-rc4-arm-64 #20.05.0 SMP PREEMPT Tue Mar 3 16:58:21 MSK 2020 aarch64 6253d342969a (none))"
panic: syscall.Getrlimit failed: operation not permitted

goroutine 1 [running]:
github.com/prometheus/prometheus/pkg/runtime.getLimits(0x7, 0x0, 0x0, 0x2, 0x2)
        /app/pkg/runtime/limits_default.go:39 +0x2b4
github.com/prometheus/prometheus/pkg/runtime.FdLimits(...)
        /app/pkg/runtime/limits_default.go:46
main.main()
        /app/cmd/prometheus/main.go:334 +0x3fe4
level=info ts=2020-03-08T23:43:16.827Z caller=main.go:295 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-03-08T23:43:16.828Z caller=main.go:331 msg="Starting Prometheus" version="(version=2.16.0, branch=HEAD, revision=b90be6f32a33c03163d700e1452b54454ddce0ec)"
level=info ts=2020-03-08T23:43:16.828Z caller=main.go:332 build_context="(go=go1.13.8, user=root@7ea0ae865f12, date=20200214-00:59:16)"
level=info ts=2020-03-08T23:43:16.829Z caller=main.go:333 host_details="(Linux 5.6.0-rc4-arm-64 #20.05.0 SMP PREEMPT Tue Mar 3 16:58:21 MSK 2020 aarch64 6253d342969a (none))"
panic: syscall.Getrlimit failed: operation not permitted

goroutine 1 [running]:
github.com/prometheus/prometheus/pkg/runtime.getLimits(0x7, 0x0, 0x0, 0x2, 0x2)
        /app/pkg/runtime/limits_default.go:39 +0x2b4
github.com/prometheus/prometheus/pkg/runtime.FdLimits(...)
        /app/pkg/runtime/limits_default.go:46
main.main()
        /app/cmd/prometheus/main.go:334 +0x3fe4
```
