### ISSUE TITLE
prometheus_remote_storage_pending_samples are drastically increasing over time.

### ISSUE THREAD

**Issue by Seitanas** [prometheus/prometheus#6952]
**What did you do?**
Using 3 standalone victoria-metrics as LTS storage for prometheus.

**What did you expect to see?**
`prometheus_remote_storage_pending_samples` should not increase over time.

**What did you see instead? Under which circumstances?**
Increase on `prometheus_remote_storage_pending_samples` metric.
It does not look that there is a metric lag on victoria-metrics site though.

**Environment**
Centos 7. Prometheus 2.16.0 (same issue on older versions). Victoria-metrics 1.32.6
About 1.5k scrape targets.

* System information:

	`Linux 3.10.0-957.21.3.el7.x86_64 x86_64`

* Prometheus version:
```
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
```

* Prometheus configuration file:
```
---
global:
  scrape_interval: 30s
  scrape_timeout: 5s
rule_files:
- "/etc/prometheus/rules/*"
remote_write:
- url: http://victoria-metrics1:8428/api/v1/write
  queue_config:
    max_shards: 50
    min_shards: 2
    capacity: 1500000
    max_samples_per_send: 150000
    batch_send_deadline: 2s
- url: http://victoria-metrics2:8428/api/v1/write
  queue_config:
    max_shards: 50
    min_shards: 2
    capacity: 1500000
    max_samples_per_send: 150000
    batch_send_deadline: 2s
- url: http://victoria-metrics3:8428/api/v1/write
  queue_config:
    max_shards: 50
    min_shards: 2
    capacity: 1500000
    max_samples_per_send: 150000
    batch_send_deadline: 2s
```

Prometheus seems to work fine for some time, but then it will start drastically increse `prometheus_remote_storage_pending_samples` metrics. It does not seem, that there's any lag in metrics, which are written to remote storage.
It also appears, that `prometheus_remote_storage_pending_samples` begins to increase right after `WAL checkpoint`.  You can see that during checkpoint, prometheus begins increasing shard count and  also `pending_samples` begins to grow:

`prometheus_remote_storage_shards`:
<img width="1552" alt="Screenshot 2020-03-10 08 28 08" src="https://user-images.githubusercontent.com/6713389/76285732-1df7de00-62a9-11ea-92c1-7386bffdff92.png">
`prometheus_remote_storage_pending_samples`:
<img width="1552" alt="Screenshot 2020-03-10 08 28 53" src="https://user-images.githubusercontent.com/6713389/76285767-336d0800-62a9-11ea-924b-a9c392c34577.png">

What could be causing this?
Thank you.
