### ISSUE TITLE
Support complex matcher types like NEQ, RE, NRE in remote read config

### ISSUE THREAD

**Issue by garrettlish** [prometheus/prometheus#6978]
## Proposal
Support complex matcher types like NEQ, RE, NRE in remote read config

Right now remote read config required matchers (`RemoteReadConfig.RequiredMatchers`) is a simple map which doesn't support complex matcher types like NEQ, RE, NRE. Actually we had already support the complex matcher types like NEQ, RE, NRE in remote read request (`prometheus.Query.matchers` - `prometheus.LabelMatcher`). Is it good to use the same complex matchers in remote read config? 

Current remote read config sample:
```
remote_read:
- url: http://host/read
  bearer_token: <secret>
  required_matchers:
    app: test
```

Proposed remote read config sample:
```
remote_read:
- url: http://host/read
  bearer_token: <secret>
  required_matchers:
    - type: EQ
      name: app
      value: test
```

With this proposed remote read config format, we are able to use not equal and regex. 
Sample (only use this remote read data source if the query filter app!=test):
```
remote_read:
- url: http://host/read
  bearer_token: <secret>
  required_matchers:
    - type: NEQ
      name: app
      value: test
```

Any thoughts, please advise.
