### ISSUE TITLE
__meta_ec2_instance_lifecycle tag not present for relabelling for EC2 even though it is prsent on console

### ISSUE THREAD

**Issue by djmgit** [prometheus/prometheus#7001]
**What did you do?**

Tried discovering EC2 instances by filtering via ASG name __meta_ec2_tag_aws_autoscaling_groupName and relabelling.
Then I tried relabeling __meta_ec2_instance_lifecycle source lable to a custom target lablel. 

**What did you expect to see?**
The custom target label with the value set to lifecyle type that is **spot** or **normal**

**What did you see instead? Under which circumstances?**
The target label was missing

**Environment**
Ubuntu 18.04

* System information:

	Linux 4.15.0-88-generic x86_64

* Prometheus version:

	prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

* Prometheus configuration file:
```
insert configuration here
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'c12-nv-templateapi-test'
    ec2_sd_configs:
    - region: us-east-1
      access_key: 
      secret_key:
      port: 9100
    relabel_configs:
    - source_labels: [__meta_ec2_tag_aws_autoscaling_groupName]
      regex: asg_1
      action: keep
    - source_labels: [__meta_ec2_instance_lifecycle]
      target_label: "lifecycle"
```
