### ISSUE TITLE
log.level is set but not picked up (still !)

### ISSUE THREAD

**Issue by squalou** [prometheus/prometheus#7087]
Note that this *may* seem a dupe from https://github.com/prometheus/prometheus/issues/2632

which is 3 year old and has not been solved

I need logs :-)

**What did you do?**
Trying t track down a curious behaviour on one of my environments, I tried to set `--log.level=debug` command line flag.

it is displayed in `/flags` uri

but there are no more logs at all.

**What did you expect to see?**

.... prometheus sever logs detailed ?
(more specifically webs erver part, since I have an error in IU loading metrics)

**What did you see instead? Under which circumstances?**

Usual silent logs...

**Environment**

* System information:

Docker on Linux 4.14.171-105.231.amzn1.x86_64 x86_64

* Prometheus version:

version 2.17.1
build info ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69

using docker image

* Prometheus configuration file:
```
global:
  scrape_interval:     60s
  evaluation_interval: 120s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /actuator/prometheus
    scheme: http
    dns_sd_configs:
    - refresh_interval: 30s
      names:
        - all.services.mydns


```

* Logs:
```
I WISH I HAD SOME
```
