### ISSUE TITLE
Error loading available metrics!

### ISSUE THREAD

**Issue by squalou** [prometheus/prometheus#7088]
**What did you do?**

I'm starting prometheus from docker image (2.17.1) on an empty server, (meaning, no prometheus data at all)

I have a scraper configured.

I go to web UI (classic or new)

Note that I do have the exact same setup on another envoronment that works like a charm, I cannot track any difference.

**What did you expect to see?**

something :) 
available metrics

**What did you see instead? Under which circumstances?**

`Error loading available metrics!`

and also sometimes (but not always) `Error loading time`

No metrics in the dropdown.

Additional info : these endpoints report things that looks good

- `/targets`  => one endpoint UP, scrape duration 18 ms
- `/service-discovery` => 1 service, some discovered labels, some targe labels, the same as on the working example
- `/status` seems sane,  with for instance

```Highest Cardinality Metric Names
Name	Count
jvm_threads_states_threads	6
jvm_memory_committed_bytes	6
jvm_memory_max_bytes	6
jvm_memory_used_bytes	6

```

I have **absolutely no logs** on prometheus side, even when setting `--log.level=debug` (an it's picked up in `/flags` but has no effect)

Finally

```
curl -i "https://prometheus.mycompany.org/api/v1/label/__name__/values"               
HTTP/2 404 
date: Sat, 04 Apr 2020 08:06:21 GMT
content-type: application/json;charset=UTF-8

{"timestamp":1585987581883,"status":404,"error":"Not Found","message":"No message available","path":"/api/v1/label/__name__/values"}%                                                      

```

**Environment**

* System information:

	`Linux 4.14.171-105.231.amzn1.x86_64 x86_64`

running docker 

* Prometheus version:

```
  prometheus, version 2.17.1 (branch: HEAD, revision: ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69)
  build user:       root@806b02dfe114
  build date:       20200326-16:18:19
  go version:       go1.13.9

```

* Prometheus configuration file:

insert configuration here

```

global:
  scrape_interval:     60s
  evaluation_interval: 120s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /actuator/prometheus
    scheme: http
    dns_sd_configs:
    - refresh_interval: 30s
      names:
        - all.services.mydns

```
