### ISSUE TITLE
Additional control of remote_read labels

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus/prometheus#7149]
## Proposal
Consider a scenario where there are two remote databases: one (duplicated) contains metrics from a replicated source, with a `prometheus_replica` on all series and another (un-duplicated) containing data without it. In this set-up it is not possible to query across both data sets at the same time, without exposing the `prometheus_replica` label in the query results.

We are currently solving this internally with a proxy, but this adds a not-insignificant amount of lag, especially to queries that return a lot of data.

To solve this, the remote_read configuration could be expanded to add certain labels to remote read requests for certain endpoints and not others.

For example
```yaml
remote_read:
  - url: http://duplicated:9090
    read_recent: true
    labels:
      prometheus_replica: '0'
  - url: http://unduplicated:9090
    read_recent: true
```
