### ISSUE TITLE
Label_replace regex doesn't match correctly

### ISSUE THREAD

**Issue by GuillaumeMiralles** [prometheus/prometheus#7153]
**What did you do?**
I tried to replace a long string of a label value into a short one (10 chars). For that I used this
![image](https://user-images.githubusercontent.com/23481418/79989118-c5bf1900-84af-11ea-8174-665774564579.png)

You can see the metrics that I have on the bottom

**What did you expect to see?**
I expect to have a brand new label called "test" with a value that equals the first 10 chars of the pubkey values.

**What did you see instead? Under which circumstances?**
I don't see anything in this specific case, but I'm gonna show you something that I found out, but I can't explain why.
![image](https://user-images.githubusercontent.com/23481418/79989432-2189a200-84b0-11ea-9516-cbe6d0eabf62.png)

Here I got the 8 last chars of the pubkey string. I manipulated the regexp so much so I ended up here... I really can't explain why does it behave like that. 

**Environment**
Running prometheus.exe under windows 10 Home

* Prometheus version:

	prometheus, version 2.17.1 (branch: HEAD, revision: ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69)
  build user:       root@806b02dfe114
  build date:       20200326-16:36:14
  go version:       go1.13.9

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'validator'
    static_configs:
      - targets: ['localhost:8081']
  - job_name: 'beacon node'
    static_configs:
      - targets: ['localhost:8080']
```
