### ISSUE TITLE
silent appearance of compaction.failed blocks

### ISSUE THREAD

**Issue by belm0** [prometheus/prometheus#7155]
**What did you do?**

Prometheus created several compaction blocks with `compaction.failed: true` marker (3 x 6h and 6 x 54h blocks).  The marker prevented higher order compactions.  (Also, these blocks were subsequently migrated to Thanos and prevented downsampling due to minimum size threshold.  This is how we discovered the failed blocks.)

**What did you expect to see?**

If prometheus had compaction failures, I expect to see warnings or errors in the logs.

Also I expect prometheus to delete the failed output block (assuming it is unusable), and preserve the underlying blocks.  If the data is usable, then the marker should not be present.

**What did you see instead? Under which circumstances?**

  * I could not find anything in the logs about the compaction failures
  * prometheus kept the failed block
  * the blocks seem to be otherwise usable (data can be accessed, and after removing the flags higher-order compaction was successful)
  * (I haven't yet investigated whether Prometheus deleted the child blocks of the failed compaction.)

I don't know what caused the failed compactions.  We had a few incidences of no space left on the prometheus data volume.  Likely related to disk-full events, we have prometheus reporting 4 WAL corruptions over the last 2 months.

**Environment**

* System information:
```
/prometheus # uname -srm
Linux 4.14.138+ x86_64
```

* Prometheus version:
```
/prometheus # prometheus --version
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
```

* Prometheus configuration file:
<details>
<p>

```
global:
  evaluation_interval: 1m
  external_labels:
    replica: main
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- dns_sd_configs:
  - names:
    - _http._tcp.prometheus-pushgateway-headless.default.svc.cluster.local
  honor_labels: true
  honor_timestamps: true
  job_name: prometheus-pushgateway
  relabel_configs:
  - replacement: pushgateway
    source_labels:
    - __name__
    target_label: category
- job_name: thanos-sidecar
  static_configs:
  - targets:
    - localhost:10902
- job_name: thanos-store
  static_configs:
  - targets:
    - thanos-store-http:10902
- job_name: thanos-query
  static_configs:
  - targets:
    - thanos-query-http:10902
- job_name: thanos-compact
  static_configs:
  - targets:
    - thanos-compact:10902

alerting:
  alertmanagers:
  - kubernetes_sd_configs:
      - role: pod
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      regex: default
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      regex: prometheus
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_component]
      regex: alertmanager
      action: keep
    - source_labels: [__meta_kubernetes_pod_container_port_number]
      regex:
      action: drop
```

</p>
</details>
