### ISSUE TITLE
rule group parameter to reduce label boilerplate

### ISSUE THREAD

**Issue by sev3ryn** [prometheus/prometheus#7156]
## Proposal
**Use case. Why is this important?**
We are using Prometheus together with Promethues operator on k8s.  Each time someone adds prometheus rules in their k8s namespace they need to make sure that every single metric has "namespace" label added. Without it - if there are metrics with same name within other namespace - you'll get confusing results and some times it is not noticeable until incident on production when because of missing label alert didn't fire as it was expected.

I suggest adding parameter on `<rule_group>` level - let's call it `with_labels`. If it is not specified - everything should work as is right now. If it is set each metric within rule_group will add those labels specified in `with_labels` field to itself. E.g.
```
groups:
  - name: example
     with_labels:
       namespace: myns
       app: myapp
    rules:
      - alert: Low success rate
         expr: sum(rate(http_requests_total{code="200"}[5m])) / sum(rate(http_requests_total[5m])) < 0.95
```
Prometheus will interpret this expression as
```
sum(rate(http_requests_total{code="200", namespace="myns", app="myapp"}[5m])) / sum(rate(http_requests_total{namespace="myns", app="myapp"}[5m])) )  < 0.95
```

Additionally for convenience when querying Prometheus -  PromQL function could be added 
```
with_labels(namespace="myns", app="myapp")( ... ) 
```

This will add convenience not only to running Prometheus on k8s but also to other use cases - like  filtering by host or by job.

**N.B.** I'm not expecting this to do some smart logic with priorities - if labels are conflicting in  with_labels and metric itself - they just will be merged and its up to user to fix it. E.g
```
with_labels(app="A")up{app="B"} => up{app="A", app="B"}
```
**EDIT**: Adding a better problem statement - I want to be able to provide my k8s tenants same level of isolation by default in Prometheus(using namespace label) as it is in Kubernetes (by namespace).
