### ISSUE TITLE
Prometheus container - nslookup not working properly

### ISSUE THREAD

**Issue by jfcgaspar** [prometheus/prometheus#7177]
This issue may be related to this [busybox issue](https://github.com/docker-library/busybox/issues/48) / [busybox bug](https://bugs.busybox.net/show_bug.cgi?id=11161) or may be something else entirely. Though that busybox bug has apparently been closed as "fixed" ...
Since the prometheus image seems to be based on the latest busybox image, which also experiences this issue, could this be the origin ?

It might be something else because specificying the nslookup -type doesn't help.

**P.S.:** Kubernetes' coreDNS pod is working fine.

**What did you do?**
`kubectl exec -ti prometheus-pod -- nslookup kubernetes.default`

**What did you expect to see?**
```
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

**What did you see instead? Under which circumstances?**
```
Server:         10.96.0.10
Address:        10.96.0.10:53

** server can't find kubernetes.default: NXDOMAIN

*** Can't find kubernetes.default: No answer

command terminated with exit code 1
```

**Environment**
```
NAME         STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
master       Ready    master   3d22h   v1.18.2   172.50.10.87   <none>        CentOS Linux 7 (Core)   3.10.0-1062.18.1.el7.x86_64   containerd://1.2.13
worker1      Ready    <none>   3d22h   v1.18.2   172.50.10.88   <none>        CentOS Linux 7 (Core)   3.10.0-1062.18.1.el7.x86_64   containerd://1.2.13
worker2      Ready    <none>   3d22h   v1.18.2   172.50.10.86   <none>        CentOS Linux 7 (Core)   3.10.0-1062.18.1.el7.x86_64   containerd://1.2.13
```

* System information:

`Linux 3.10.0-1062.18.1.el7.x86_64 x86_64`

* Prometheus version:

```
prometheus, version 2.17.2 (branch: HEAD, revision: 18254838fbe25dcc732c950ae05f78ed4db1292c)
  build user:       root@9cb154c268a2
  build date:       20200420-08:27:08
  go version:       go1.13.10
```

* Alertmanager version:

`not relevant to the issue`

* Prometheus configuration file:
```
prometheus.yml:
----
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']
```

* Alertmanager configuration file:
```
not relevant to the issue
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
