### ISSUE TITLE
kubernetes_sd_configs selectors not working as expected

### ISSUE THREAD

**Issue by filipepinheiro** [prometheus/prometheus#7185]
**What did you do?**
Configured prometheus.yaml with the following:
```
[redacted]
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - default
          selectors:
            - role: pod
              label: "app:abc-123"
[redacted]
```

**What did you expect to see?**
Success boot, since I followed the documentation available [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config)

**What did you see instead? Under which circumstances?**
While booting up prometheus I get the following error:
> level=error ts=2020-04-29T14:53:46.508Z caller=main.go:740 err="error loading config from \"/etc/config/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/config/prometheus.yml\"): parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:
>  line 17: field selectors not found in type kubernetes.plain"

**Environment**

* Prometheus version:
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: 'kubernetes-pods'
    metrics_path: /metrics
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
          - default
      selectors:
        - role: pod
          label: "app:abc-123"
```

* Logs:
```
level=error ts=2020-04-29T14:53:46.508Z caller=main.go:740 err="error loading config from \"/etc/config/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/config/prometheus.yml\"): parsing YAML file /etc/config/prometheus.yml: yaml: unmarshal errors:\n  line 17: field selectors not found in type kubernetes.plain"
```
