### ISSUE TITLE
Run Prometheus on my own ibft2 network

### ISSUE THREAD

**Issue by yehia67** [prometheus/prometheus#7200]
Hello,

I have an ibft2 network, with two bootnodes and six validators. I create them manually using the documentation [tutorial](https://besu.hyperledger.org/en/latest/Tutorials/Private-Network/Create-IBFT-Network/) 

then I used this `docker-compose.yml` file:
```
---
version: '3.4'
services:
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090/tcp

  grafana:
    image: "grafana/grafana"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

volumes:
      
  prometheus:
      
  grafana:
```
then I use `/monitoring/prometheus/prometheus.yml` [file](https://github.com/PegaSysEng/besu-sample-networks/blob/master/monitoring/prometheus/prometheus.yml).

When I run the docker-compose file it gave me this error:

```
prometheus_1  | level=warn ts=2020-05-04T19:06:11.798Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:34582->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:06:11.799Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:06:41.821Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:52122->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:06:41.821Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:07:11.855Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:57586->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:07:11.855Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:07:41.796Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:46264->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:07:41.796Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:08:11.792Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:45671->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:08:11.792Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:08:41.919Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:47377->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:08:41.919Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:09:11.791Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:50478->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:09:11.791Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:09:41.808Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:59719->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:09:41.808Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
prometheus_1  | level=warn ts=2020-05-04T19:10:11.796Z caller=dns.go:299 component="discovery manager scrape" discovery=dns msg="DNS resolution failed" server=127.0.0.11 name=node.domain.name. err="read udp 127.0.0.1:35164->127.0.0.11:53: i/o timeout"
prometheus_1  | level=error ts=2020-05-04T19:10:11.796Z caller=dns.go:155 component="discovery manager scrape" discovery=dns msg="Error refreshing DNS targets" err="could not resolve \"node\": all servers responded with errors to at least one search domain"
```
What its mean by this error and how to solve it? Thanks.
