### ISSUE TITLE
Configuration - allow usage of regex for source_labels in relabel_configs

### ISSUE THREAD

**Issue by mordowiciel** [prometheus/prometheus#7203]
In current version of Prometheus, if I would like to rewrite source meta labels to persistent target labels, I would have to do something like this:
```
- source_labels:
    - __meta_ec2_tag_Name
  target_label: instance_name
- source_labels:
    - __meta_ec2_tag_component
  target_label: component
- source_labels:
    - __meta_ec2_tag_environment
  target_label: environment
- source_labels:
    - __meta_ec2_tag_project
  target_label: project
```
The config can become quite long and messy for many tags. It would be nice if I could capture a regex group in source label name and use it as the name of target label:

```
- source_labels:
    - __meta_ec2_tag_(.*)
  target_label: $1
```

By doing that in this way, I could avoid rewriting multiple source labels with similar names, and also avoid manually adding new source_labels rewrites every time a new `__meta_ec2_tag_(.*)` appears.
