### ISSUE TITLE
Impossible to start Prometheus with storage.tsdb.path on a SeaweedFS mount

### ISSUE THREAD

**Issue by tcassaert** [prometheus/prometheus#7223]
**What did you do?**
I have a SeaweedFS setup, where I'd like to store my persistent data. When I start Prometheus, with the `--storage.tsdb.path="/nomad/prometheus"`, it errors. This `/nomad` is a seaweedfs mount point.
 
**What did you expect to see?**
Prometheus should just start-up fine, and store the metrics in `/nomad/prometheus`.

**What did you see instead? Under which circumstances?**
Prometheus failed to start with all the default configuration, except for the `--storage.tsdb.path` option. 

**Environment**

* System information:
Linux 3.10.0-957.12.2.el7.x86_64 x86_64

* Prometheus version:
```
prometheus, version 2.18.0 (branch: HEAD, revision: a12e96299dcd159ea09b260f1a21e7e4b86e011d)
  build user:       root@7fbcff55abdb
  build date:       20200505-14:26:04
  go version:       go1.14.2
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

* Logs:
```
[root@server1 prometheus-2.18.0.linux-amd64]# ./prometheus --storage.tsdb.path=/nomad/prometheus
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:302 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:337 msg="Starting Prometheus" version="(version=2.18.0, branch=HEAD, revision=a12e96299dcd159ea09b260f1a21e7e4b86e011d)"
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:338 build_context="(go=go1.14.2, user=root@7fbcff55abdb, date=20200505-14:26:04)"
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:339 host_details="(Linux 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 server1.homelab (none))"
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:340 fd_limits="(soft=1024, hard=4096)"
level=info ts=2020-05-07T16:12:09.995Z caller=main.go:341 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-05-07T16:12:09.996Z caller=query_logger.go:71 component=activeQueryTracker msg="Failed to read query log file" err=EOF
unexpected fault address 0x7fe0d51a2000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fe0d51a2000 pc=0x4687e8]

goroutine 1 [running]:
runtime.throw(0x26b4471, 0x5)
        /usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0008c7340 sp=0xc0008c7310 pc=0x434af2
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:692 +0x443 fp=0xc0008c7370 sp=0xc0008c7340 pc=0x44b5e3
runtime.memmove(0x7fe0d51a2000, 0x26b1946, 0x1)
        /usr/local/go/src/runtime/memmove_amd64.s:148 +0x108 fp=0xc0008c7378 sp=0xc0008c7370 pc=0x4687e8
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe88d11723, 0x11, 0x14, 0x2e940a0, 0xc00062ff50, 0x2e940a0)
        /app/promql/query_logger.go:120 +0x3a3 fp=0xc0008c74d0 sp=0xc0008c7378 pc=0x1dbb573
main.main()
        /app/cmd/prometheus/main.go:368 +0x4ed8 fp=0xc0008c7f88 sp=0xc0008c74d0 pc=0x1f59888
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x212 fp=0xc0008c7fe0 sp=0xc0008c7f88 pc=0x437172
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0008c7fe8 sp=0xc0008c7fe0 pc=0x467521

goroutine 36 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000093bd0)
        /app/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /app/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 39 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x42271e0)
        /app/vendor/k8s.io/klog/v2/klog.go:1107 +0x8b
created by k8s.io/klog/v2.init.0
        /app/vendor/k8s.io/klog/v2/klog.go:416 +0xd6

goroutine 78 [select]:
github.com/prometheus/prometheus/pkg/logging.(*Deduper).run(0xc00012afc0)
        /app/pkg/logging/dedupe.go:75 +0x1db
created by github.com/prometheus/prometheus/pkg/logging.Dedupe
        /app/pkg/logging/dedupe.go:61 +0xcf

goroutine 98 [chan receive]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0xc00043b030)
        /app/storage/remote/write.go:84 +0xb2
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
        /app/storage/remote/write.go:77 +0x1a9
```
