### ISSUE TITLE
Wrong value reported on alert resolution

### ISSUE THREAD

**Issue by mveroone** [prometheus/prometheus#7224]
**What did you do?**
I have an alert set up : 
```
  - alert: MyAlert
    expr: sum by (label) (metric{label=~"regexp"}) < 1
    for: 1m
    annotations:
     (...)
      resolvedDescription: "{{ $labels.label}} now is {{ $value }}"
```
(Note : value will always be an integer)

**What did you expect to see?**
The resolution notification contains a velue greater or equal to 1

**What did you see instead? Under which circumstances?**
The resolution notification contains value "0" which is the pre-resolution value (since resolved means ">=1")

**Environment**

* System information:

	`Linux 3.10.0-957.5.1.el7.x86_64 x86_64`

* Prometheus version:

```
prometheus, version 2.17.1 (branch: HEAD, revision: ae041f97cfc6f43494bed65ec4ea4e3a0cf2ac69)
  build user:       root@806b02dfe114
  build date:       20200326-16:18:19
  go version:       go1.13.9
```

* Alertmanager version:

	latest docke rimage from dockerhub :
```
alertmanager, version 0.20.0 (branch: HEAD, revision: f74be0400a6243d10bb53812d6fa408ad71ff32d)
  build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5
```

* Prometheus configuration file:
```
global:
 scrape_interval: 10s
 evaluation_interval: 10s
```
(scrape config and alertmanager config are pretty straightforward)

* Alertmanager configuration file:
```
global:

templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: slack
  routes:
    (...)
receivers:
  - name: slack
    slack_configs:
    - api_url: '...'
      title: "{{ if eq .Status \"firing\" }}{{ .CommonAnnotations.firingSummary }}\n{{else}}{{ .CommonAnnotations.resolvedSummary }}\n{{ end }}"
      text: "{{ if eq .Status \"firing\" }}{{ range .Alerts }}{{ .Annotations.firingDescription }}\n{{ end }}{{else}}{{ range .Alerts }}{{ .Annotations.resolvedDescription }}{{ end }}{{ end }}"
      title_link: "...'
      username: "..."
      send_resolved: true
```

* Logs:
No relevant logs either way
