### ISSUE TITLE
How to put blackbox config in a file in  file_sd_configs

### ISSUE THREAD

**Issue by hedeesa** [prometheus/prometheus#7234]
I'm trying to have more clear and modular prometheus.yml and I want to move my black box exporter to file_sd_configs.
which is now look like this
```
- job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://xxx.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 
```
and I want to move the whole thing to a file and address it like this:
```
  - job_name: 'other'
    file_sd_configs:
    - files:
      - '/etc/prometheus/blackbox.yml'
```
but I'm experiencing a hard time in transforming relabeling_config part into something which prometheus can read it through file_sd_configs. How can I do that? 
(since I haven't found a solution yet, I thought It could be a good feature )
