### ISSUE TITLE
Add the Alerting Group Name as Label

### ISSUE THREAD

**Issue by thewilli** [prometheus/prometheus#7240]
## Proposal

Add the Alerting Group Name as Label.

I have several Alerting Groups, where each group represents a certain service or use-case. Consider a group with rules for some application like

```yaml
groups:
- name: ApplicationX
  rules:
  - alert: ApplicationXOddBehavior1
    expr: appx_metric1 > 42
  - alert: ApplicationXExpectedValue1
    expr: appx_metric77 == 3
  # way more rules
```

What I would like to do is to group those alerts. I could manually add a label to each of them, but that's against DRY; they are already grouped together. So I'd like to have the group name (`ApplicationX` in this case) added as label to each of the alerts, so the AlertManager is able to group by this label.

**Use case. Why is this important?**

* DRY
* Having to add the information to each of the rules not only adds redundancy and is therefore prone to errors.
* We do already have this information, why shouldn't we use them (outside the UI)?
