### ISSUE TITLE
Add metrics around remote_read queries

### ISSUE THREAD

**Issue by amitabh91** [prometheus/prometheus#7242]
I have integrated M3DB as remote storage for Prometheus as a long term storage solution. Where M3coordinator runs as a side along with Prometheus which pushes the data to the M3DB cluster. I am able to write the metrics data into M3DB successfully. 

On executing the query prometheus_remote_storage_sent_bytes_total from Prom UI we see some incremental values, unlike prometheus_remote_storage_remote_read_queries. 

I am attaching the screenshot below for the quick reference 

**Write Data Logs**
![image](https://user-images.githubusercontent.com/7939820/81582108-41382a00-93cd-11ea-8a5d-eb67582e3894.png)

**Read Data Logs**
![image](https://user-images.githubusercontent.com/7939820/81582208-6167e900-93cd-11ea-8e68-d62b13956f32.png)

**Environment**
* System information:

   Linux 3.10.0-957.el7.x86_64 x86_64

* Prometheus version:

  prometheus, version 2.15.2 
  build user:       root@688433cf4ff7
  build date:       20200106-14:50:51
  go version:       go1.13.5

* Prometheus configuration file:
```
remote_write:
- url: http://localhost:7201/api/v1/prom/remote/write
  remote_timeout: 30s
  queue_config:
    capacity: 500
    max_shards: 1000
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
remote_read:
- url: http://localhost:7201/api/v1/prom/remote/read
  remote_timeout: 1m
  read_recent: true
```
Whenever we have mismatch in the  namespace value of  m3coordinator and M3DB cluster we see the below error while reading.

**m3coordinaor config**
```
clusters:
  - namespaces:
      - namespace: default
        retention: 48h
        type: unaggregated
    client:
      config:
        service:
          env: default_env
          zone: embedded
          service: m3db
          cacheDir: /var/lib/m3kv
          etcdClusters:
            - zone: embedded
              endpoints:
                - http://etcd.infra.svc.cluster.local:2379
```
**Error** 
![image](https://user-images.githubusercontent.com/7939820/81577182-c409b680-93c6-11ea-89e2-05cbe9bbec2f.png)

And with the correct namespace we don't see the error but prometheus_remote_storage_remote_read_queries still remains empty. So I believe this is a bug that needs a fix.

**Note**:- I have added m3query as datasource in Grafana and able to read the data stored in M3DB cluster.
