### ISSUE TITLE
Slow to retrieve static js files for webui on Alpine and Musl

### ISSUE THREAD

**Issue by wesleyParriott** [prometheus/prometheus#7253]
**What did you do?**
Installed prometheus from apk

**What did you expect to see?**
When we run `curl http://127.0.0.1:9090/static/vendor/js/popper.min.js.map` we expect to get an answer back instantly

**What did you see instead? Under which circumstances?**
the call would timeout or take way too long

**Environment**
 
* System information:
Linux 5.4.34-0-virt x86_64
Alpine Linux
VERSION_ID=3.12_alpha20200428
[link to that patch](https://git.alpinelinux.org/aports/commit/?id=9f965f34d06d3ae0f7cd5f7a8f5f8c8bc4f3c65e)

* Prometheus version:
Linux 5.4.34-0-virt x86_64

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
````
