### ISSUE TITLE
There are some series looks like LOST by prometheus after relabel

### ISSUE THREAD

**Issue by dablyo** [prometheus/prometheus#7280]
**What did you do?**
scrape same metrics with different label, then relabel one mtric and  merge them to one 
**What did you expect to see?**
just looks like one metric 
**What did you see instead? Under which circumstances?**
looks like some data LOST, or problem with series connection when labels are consistent
**Environment**
* System information:
Linux 3.10.0-957.27.2.el7.x86_64 x86_64
* Prometheus version:
prometheus, version 2.9.2 (branch: HEAD, revision: d3245f15022551c6fc8281766ea62db4d71e2747)
  build user:       root@1d43b6951e8f
  build date:       20190424-15:32:31
  go version:       go1.12.4

* Alertmanager version:

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 10s
scrape_configs:
- job_name: anp
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:35003
- job_name: instant
  honor_timestamps: true
  scrape_interval: 2s
  scrape_timeout: 2s
  metrics_path: /instantmetrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:35003
  metric_relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: instant
    target_label: job
    replacement: anp
    action: replace
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
I've attach some screenshot and description in
https://groups.google.com/forum/#!topic/prometheus-users/NQQEmwyQqH8

is this  an issue ? or just a wrong configuration?
