### ISSUE TITLE
promtool doesn't validate rule_group keys

### ISSUE THREAD

**Issue by SuperQ** [prometheus/prometheus#7283]
**What did you do?**

Accidentally created an invalid rule group

```yaml
groups:
- name: Alerts
  rules:
  - alert: SnitchHeartBeat
    expr: vector(1)
  labels:
  - alert: TargetDown
    expr: up == 0
```

**What did you expect to see?**

That `promtool check rules` rejects rule file as invalid.

**What did you see instead? Under which circumstances?**

Valid rules file

**Environment**

* Prometheus version:

2.18.1
