### ISSUE TITLE
The new UI doesn't show stacked graphs properly when series go on and off

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/prometheus#7302]
**What did you do?**

Running Prometheus with 3 targets: prometheus, alertmanager and node-exporter.
Initially only prometheus and alertmanager are up, then node-exporter comes up, then alertmanager goes down. Eventually alertmanager comes up again.

After that I've queried `process_virtual_memory_bytes` with the stacked graph in the new UI.

**What did you expect to see?**

Properly stacked graphs.

**What did you see instead? Under which circumstances?**

![image](https://user-images.githubusercontent.com/2587585/83040215-50f77580-a03f-11ea-8d53-b0d0b63fff2e.png)

**Environment**

* Prometheus version:

7a541bd9a73671c0233db1928106d8b839053d7a

* Prometheus configuration file:

```
scrape_configs:
- job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']
- job_name: 'node'
  static_configs:
    - targets: ['localhost:9100']
- job_name: 'alertmanager'
  static_configs:
    - targets: ['localhost:9093']
```
