### ISSUE TITLE
Prometheus keeps restarting without obvious error message

### ISSUE THREAD

**Issue by sachinmyneni** [prometheus/prometheus#7303]
**What did you do?**
I had added a new node to monitor and restarted prometheus. Prometheus keeps restarting every few minutes and never shows up as 'ready'. The host:9090/-/healthy shows _Prometheys is Healthy_.

**What did you expect to see?**
I expected Prometheus to start and remain in running state. While I just added a new target (specifically ca-osqa-dbs:9100) I don't expect that to cause issues with Prometheus itself. 

**What did you see instead? Under which circumstances?**
I see only "Service Unavailable" when I go to _http://hostname:9090/graph_ 
Restarting the container did not help. Every few minutes prometheus seems to crash silently. The attached log shows then it restarts. I am setting the UID/GID in the docker-compose.yml to ensure proper ownership and I don't see any errors about permissions.

**Environment**

* System information:

Linux 3.10.0-327.36.3.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8

Running docker-compose:

```
  prometheus:
     image: prom/prometheus
     container_name: prometheus
     ports:
       - "9090:9090"
     volumes:
       - /scratch/monitoring/prometheus/etc:/etc/prometheus
       - /scratch/monitoring/prometheus/data:/prometheus
       - /etc/localtime:/etc/localtime:ro
     restart: always
     networks:
       - monitoring
     user: "65534:65534"


```

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
[prometheus_yml.txt](https://github.com/prometheus/prometheus/files/4691499/prometheus_yml.txt)

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
[prometheus.log](https://github.com/prometheus/prometheus/files/4691111/prometheus.log)
