### ISSUE TITLE
chunks_head folder consumes my disk

### ISSUE THREAD

**Issue by SimonHu-HN** [prometheus/prometheus#7304]
I download the Prometheus source code from GITHUB, and followed by the tutorial to make build this project. Fortunately, I get the executable file. But I immediately encounter the terrible thing that the usage of my disk is 100% after I run the Prometheus for a while.

Next, I found the reason is the `data/chuns_head` folder generates many files, named by 0000xx. I just run the `./prom --config.file=prome.yml` and do nothing after that. However, the Prometheus continuously depletes my disk.

Here is my `prome.yml`
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'tsdbtest'

    static_configs:
    - targets: ['localhost:9090']

```

Here is the picutres of chunks_head and my disk(only 15% at the very beginning).
[![enter image description here][1]][1]
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/mmS7i.png
  [2]: https://i.stack.imgur.com/exkHc.png
