### ISSUE TITLE
WAL Compaction Issues - File Not Found error

### ISSUE THREAD

**Issue by zkhcohen** [prometheus/prometheus#7327]
**What did you do?**

N/A

**What did you expect to see?**

Prometheus fails to compact data beyond the threshold of ~4 hours (2 blocks). It appears to be retained:

[PIC](https://i.imgur.com/3XGYJRp.png)

I have already attempted deleting the storage folder and allowing it to be recreated. The issue persists.

**What did you see instead? Under which circumstances?**

Prometheus fails to compact the data because of a file location issue, thus creating gaps in the data displayed in both the Prometheus console and Grafana. In other words, the data is still retained, but not accessible.

**Environment**

* System information:

Linux 4.19.76-linuxkit x86_64
(Docker Desktop (win x64) 2.3.0.3 (45519))

* Prometheus version:

prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2

* Prometheus configuration file:
```
version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - management
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - ../share/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../share/prometheus/storage:/prometheus
    depends_on:
      - cadvisor
      - node-exporter
```

* Logs:
```
level=info ts=2020-06-02T15:00:04.053Z caller=compact.go:495 component=tsdb msg="write block" mint=1591099200000 maxt=1591106400000 ulid=01E9TRQV040S0940P3JKS112RE duration=336.374701ms


level=info ts=2020-06-02T15:00:04.180Z caller=head.go:662 component=tsdb msg="Head GC completed" duration=79.7005ms


level=error ts=2020-06-02T15:00:04.776Z caller=db.go:667 component=tsdb msg="compaction failed" err="reload blocks: head truncate failed: create checkpoint: rename checkpoint directory: rename /prometheus/wal/checkpoint.00000006.tmp /prometheus/wal/checkpoint.00000006: no such file or directory"
```
