### ISSUE TITLE
Labeling Targets in the same Job

### ISSUE THREAD

**Issue by Simeda** [prometheus/prometheus#7329]
## Proposal
**Use case. Why is this important?**
With current available features, Prometheus allows us to create labels for targets after scrape, which gives good control over targets. However, labeling each target in the same Job is not possible. Ability to group targets under one Job by labels gives powerful control; especially when you think about it from Grafana visualization perspective. 
Think of An application that has multiple-jvm running in a single host?
*******
Proposed feature:

scrape_configs:
  - job_name: "PlanningServices-v1"
    - targets: 
       - localhost:9403
         labels:
              jvmName: 'jvm-1'
              env: 'dev'
       - localhost:9404
          labels:
              jvmName: 'jvm-2'
              env: 'dev'
********
It is true that we can have multiple job to achieve this but It is not efficient to have multiple jobs for same application names in an environment that might consist up to 10,000 servers.
*“Nice to have” is not a good use case. :)*

**Comment by roidelapluie** [comment]
This is possible.

```yaml
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
    - targets: ['1.2.3.4:9090']
      labels:
        datacenter: zurich
    - targets: ['4.5.6.8:9091']
      labels:
        datacenter: munich
```
