### ISSUE TITLE
UI does not 

### ISSUE THREAD

**Issue by lowellmower** [prometheus/prometheus#7333]
**What did you do?**
New install of prometheus using:
```
$ GO15VENDOREXPERIMENT=1 go get github.com/prometheus/prometheus/cmd/...
```
Simple config file under `prom.conf.yml`:
```
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
```
Ran `prometheus` with no error:
```
$ prometheus --config.file=prom.conf.yml
... redacted ...
level=info ts=2020-06-03T15:44:04.147Z caller=main.go:799 msg="Loading configuration file" filename=prom.conf.yml
level=info ts=2020-06-03T15:44:04.148Z caller=main.go:827 msg="Completed loading of configuration file" filename=prom.conf.yml
level=info ts=2020-06-03T15:44:04.148Z caller=main.go:646 msg="Server is ready to receive web requests."
```
Navigate to localhost:9090 and the following error for the UI occurs:
```
error reading base template: open templates/_base.html: no such file or directory
```
**What did you expect to see?**

The UI

**What did you see instead? Under which circumstances?**

A file/dir error.

**Environment**
sys
```
$ uname -a
Linux ubuntu-bionic 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
go
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build181791144=/tmp/go-build -gno-record-gcc-switches"
```
* System information:
```
$ uname -srm
Linux 4.15.0-96-generic x86_64
```

* Prometheus version:
```
root@ubuntu-bionic:~# prometheus --version
prometheus, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.14
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
```

* Logs:
Nothing appears in the logs

Note: [This hard coded path](https://github.com/prometheus/prometheus/blob/master/web/web.go#L387) seems like the possible issue - I do not see a path `prometheus/web/ui/static/react/index.html`
