### ISSUE TITLE
Problem with relabelling regex

### ISSUE THREAD

**Issue by antonionappi88** [prometheus/prometheus#7344]
Hello,
I'm trying to relabelling a label set by Kubernetes Service discovery but I'm having quite some trouble, maybe i'm doing something really stupid.

I'm using the Prometheus Operator with ServiceMonitor.

This is my configuration in my prometheus instance:

```yaml
  - source_labels:                                   
    - __meta_kubernetes_service_label_k8sCluster     
    target_label: kubernetes_cluster                
  - source_labels:                                          
    - __meta_kubernetes_service_label_k8sCluster                  
    target_label: availability_zone                  
    regex: -?([abc])(-|$)                                    
    replacement: ${1}                               
  - source_labels:                                          
    - __meta_kubernetes_service_label_k8sCluster            
    target_label: test                
    regex: (.*)                                             
    replacement: ${1}              
```

The value of `__meta_kubernetes_service_label_k8sCluster` is `k8s-whatever-dev-a-v15`.

The first and third do the same thing and work as expected but the second one with regex `-?([abc])- ` doesn't work. I don't get the new label `availability_zone`

I've tested the regex with a simple go program like this one:
```go
package main

import (
        "fmt"
        "regexp"
        "os"
        "gopkg.in/ini.v1"
)

func main() {
        cfg, err := ini.Load("parameters.ini")
    if err != nil {
        fmt.Printf("Fail to read file: %v", err)
        os.Exit(1)
        }
        regex := cfg.Section("").Key("regex").String()
        string := cfg.Section("").Key("string").String()

        fmt.Printf("Regex set to: %q\n", regex)
        fmt.Printf("String evaluated: %q\n", string)
        fmt.Printf("******************************** \n")

        re := regexp.MustCompile(regex)
        sm := re.FindStringSubmatch(string)
        for idx, group := range sm {
                fmt.Printf("Matched Group %d: %q\n", idx, group)
        }

}
```

and the output is 

```bash
Regex set to: "-?([abc])(-|$)"
String evaluated: "k8s-whatever-dev-a-v15"
******************************** 
Matched Group 0: "-a-"
Matched Group 1: "a"
Matched Group 2: "-"
```

Do you have any clue ?

Thanks,
Antonio
