### ISSUE TITLE
The query got a bad result in V2.18.1

### ISSUE THREAD

**Issue by lixy529** [prometheus/prometheus#7349]
```
remote_write:
  - url: "http://127.0.0.1:9201/write"
remote_read:
  - url: "http://127.0.0.1:9201/read"
  read_recent: true
```

In v2.18.1, remote_storage is used to read data. When merging data, value is always the last value.
for example:
input:
badtestprom{cluster="h01"} 3
badtestprom{cluster="h02"} 4
got:
badtestprom{cluster="h01",job="lixytest"} 4
badtestprom{cluster="h02",job="lixytest"} 4
expect:
badtestprom{cluster="h01",job="lixytest"} 3
badtestprom{cluster="h02",job="lixytest"} 4
