### ISSUE TITLE
Why still scraping metrics when pod completed, how to stop scrap

### ISSUE THREAD

**Issue by WYmindsky** [prometheus/prometheus#7357]
**What did you do?**
get metrics from prometheus and display in grafana

**What did you expect to see?**
when pod completed, prometheus should stop scrap metrics

**What did you see instead? Under which circumstances?**
it continue display

**Environment**
kubernetes:1.14
centos: 7.7.1908

* System information:
Linux 3.10.0-1062.el7.x86_64 x86_64

* Prometheus version:
2.15.2

* Alertmanager version:
0.20.0

* Prometheus configuration file:
```
      - job_name: kubernetes-pods
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        kubernetes_sd_configs:
        - api_server: null
          role: pod
          namespaces:
            names: []
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_status]
          regex: "Completed"
          action: drop
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          separator: ;
          regex: "true"
          replacement: $1
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          separator: ;
          regex: (.+)
          target_label: __metrics_path__
          replacement: $1
          action: replace

```

* Alertmanager configuration file:
```
ignore
```

* Logs:
```
evel=info ts=2020-06-08T02:23:41.500Z caller=main.go:664 msg="TSDB started"
level=info ts=2020-06-08T02:23:41.500Z caller=main.go:734 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-06-08T02:23:41.504Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-08T02:23:41.506Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-08T02:23:41.507Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-08T02:23:41.509Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-08T02:23:41.510Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-06-08T02:23:41.513Z caller=main.go:762 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-06-08T02:23:41.513Z caller=main.go:617 msg="Server is ready to receive web requests."
level=info ts=2020-06-08T03:00:06.642Z caller=compact.go:496 component=tsdb msg="write block" mint=1591574400000 maxt=1591581600000 ulid=01EA8XXS0W8N3H5V5Y2W10TKM3 duration=3.413249729s
level=info ts=2020-06-08T03:00:06.977Z caller=head.go:668 component=tsdb msg="head GC completed" duration=99.534048ms
level=info ts=2020-06-08T03:00:11.489Z caller=head.go:738 component=tsdb msg="WAL checkpoint complete" first=2294 last=2300 duration=4.511867503s
level=info ts=2020-06-08T03:00:18.373Z caller=compact.go:441 component=tsdb msg="compact blocks" count=3 mint=1591552800000 maxt=1591574400000 ulid=01EA8XY1562BGAVC4XTPX8DEW3 sources="[01EA89AHQ8EQ4QR3JFFTWEV9ED 01EA8G68Z0JEMHP4GSE38VMR86 01EA8Q2079HNX7D3D75V5PRQ00]" duration=6.815046846s

```

prometheus:
![image](https://user-images.githubusercontent.com/20678602/83989944-950d4300-a97a-11ea-98a3-781b4537ca92.png)

But only one is running:
![image](https://user-images.githubusercontent.com/20678602/83989970-a5252280-a97a-11ea-94ec-7b3f17a2de53.png)

help please
