### ISSUE TITLE
aggregation rule results do not match raw data

### ISSUE THREAD

**Issue by miclando** [prometheus/prometheus#7383]
**What did you do?**
in order to improve the query time we setup an aggregation rule,
record: fastly:rt_requests_total:no_dc:5m_rate
```
record: fastly:rt_requests_total:no_dc:5m_rate
expr: sum without(datacenter) (rate(fastly_rt_requests_total[5m]))
```

**What did you expect to see?**
we expected the results of the aggregation to be a close match to the raw metric result.

**What did you see instead? Under which circumstances?**
we saw that there is a big difference between the results.
the graphs trend looks correct but the total is off
![image](https://user-images.githubusercontent.com/26199476/84378497-ed4b7b80-abec-11ea-8923-665d067607f1.png)

**Environment**

* System information:

	Linux 3.10.0-693.el7.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.18.1 (branch: HEAD, revision: 
        ecee9c8abfd118f139014cb1b174b08db3f342cf)
        build user:       root@2117a9e64a7e
        build date:       20200507-16:51:47
        go version:       go1.14.2

* Prometheus configuration file:
```

global:
  scrape_interval: 1m
  scrape_timeout: 55s
  evaluation_interval: 1m
  external_labels:
    fqdn: prometheus004.xxx.com
    monitor: master
alerting:
  alertmanagers:
  - consul_sd_configs:
    - server: consul.service.consul:8500
      tag_separator: ','
      scheme: http
      allow_stale: true
      refresh_interval: 30s
      services:
      - alertmanager
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /etc/prometheus/rules/*
scrape_configs:
- job_name: fastly_k8s_federation
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{job="fastly-exporter"}'
  scrape_interval: 1m
  scrape_timeout: 55s
  metrics_path: /federate
  scheme: http
  static_configs:
  - targets:
    - prometheus-operated.monitoring.svc.kube.xxx.com:9090
```

* *additional info**
the raw metric is federated from a different Prometheus server whos scraping interval is 30s.
we also tested the the aggregation rule but with out the sum on it
```
record: fastly:rt_requests_total:5m_rate
expr: rate(fastly_rt_requests_total[5m])
``` 

in this case the result did match to the raw data.

the raw metric looks so :

```
fastly_rt_requests_total{datacenter="xxx",endpoint="fastly-1",instance="xxx:8081",job="fastly-exporter",namespace="xxx",pod="fastly-exporter-5db8fbb54f-jdh4g",prometheus="monitoring/prometheus-operator-prometheus",prometheus_replica="prometheus-prometheus-operator-prometheus-0",service="fastly-exporter",service_id="xxx",service_name="xxx"}
```
