### ISSUE TITLE
The query log contains only the execution record of the rule engine

### ISSUE THREAD

**Issue by biuboombiuboom** [prometheus/prometheus#7395]
**What did you do?**

open query log

**What did you expect to see?**

PromQL queries are logged

**What did you see instead? Under which circumstances?**

The query log only records the part of the rule engine. Isn't the webapi query log recorded?

**Environment**

* System information:

iLinux 4.4.192-1.el7.elrepo.x86_64 x86_64

* Prometheus version:

prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  query_log_file: /data/prometheus/query.log

```
