### ISSUE TITLE
How to use Prometheus EC2 SD with Multiple AWS EC2 interfaces

### ISSUE THREAD

**Issue by silazare** [prometheus/prometheus#7406]
Need some help with Prometheus EC2 SD use case.

I have multiple VPCs setup with VPC peering and EC2 with several Private interfaces and no Public interfaces/Public access available.

Setup example:
VPC1 - EC2 which needs to be monitored
VPC2 - Prometheus server

EC2 IPs (order is preserved):
 - 192.168.1.10 (does not have routing outside VPC1) 
 - 192.168.2.10 (does not have routing outside and peered with VPC2)

Prometheus IP:
 - 192.168.2.9 (VPC2)

Prometheus simple config with ec2_sd and node_exporter:
```
    - job_name: 'test'
      ec2_sd_configs:
        - region: <region_name>
          port: 9100
      relabel_configs:
        - source_labels: [__meta_ec2_tag_Name]
          regex: 'test-instance'
          action: keep
```

As a result EC2 is being discovered but *__address__* and *__meta_ec2_private_ip* are always take first IP from preserved order - *192.168.1.10* and hence target not able to communicate with Prometheus and down.

## Proposal
**Use case: Monitor EC2 with multiple interfaces and VPCs with peering on single prometheus server**
