### ISSUE TITLE
Prometheus not picking up custom kubernetes service metric target

### ISSUE THREAD

**Issue by jsjain** [prometheus/prometheus#7422]
**What did you do?**
Added section for custom metrics target on top of default prometheus file from helm stable/prometheus

```
...DEFAULT
    - job_name: my_app_metrics
      scrape_interval: 5m
      scrape_timeout: 10s
      honor_labels: true
      metrics_path: /api/metrics
      kubernetes_sd_configs:
      - role: service
        selectors:
          - role:  "service"
            label: "name=myapp"
...DEFAULT 
```

To target my service configured as 

```
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: production
spec:
  selector:
    name: myapp
    deployment: production
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
```

**What did you expect to see?**
My custom metric target to be listed in /targets of prometheus

**Environment**
chart=prometheus-11.3.0
component=server
heritage=Helm
pod-template-hash=6567ccd7bb
 release=prometheus

* Prometheus version:
	11.3.0

Is there something wrong with the way I have setup for custom metrics ?
