### ISSUE TITLE
Remote-Write relabeling rules partially applied after configuration change and reload

### ISSUE THREAD

**Issue by vsliouniaev** [prometheus/prometheus#7457]
This issue is not easily reproducible - we have many prometheus setups running in this exact configuration fine, and this instance was also running fine until this issue was observed.

Prometheus appears to have only partially applied a remote-write relabelling configuration. The entire config yaml was parsed and loaded (as could be seen from `/config`), but was missing two relabelling rule applications from the metrics that were remote-written.

We were able to isolate this behaviour because we are running two replicas and the behaviour was identical on both. Restarting replica-1 caused it to correctly apply the relabelling rules for the same configuration, while the other one continued to exhibit the same behaviour. The configuration was confirmed to be identical between both instances, save for the `prometheus_replica` external label.

Several alterations to the relabelling rules that were not being applied - such as altering the regex to make it more explicit - had no effect on behaviour on the bad replica-0 instance. Eventually removing a large chunk of configuration and re-adding it back seemed to do the trick.

We use the rules as a way to whitelist metrics for remote-write, the general format is as follows:
```yaml
remote_write:
- url: http://remote-write:7201/api/v1/prom/remote/write
  remote_timeout: 4m
  write_relabel_configs:
  -
  - approx 500 rules total
  -
  - source_labels: [__name__]
    separator: ;
    regex: kep_mpe_uploads_success
    target_label: __mms_ingop
    replacement: streaming/media-processing-platform
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: onvif_fail_total_count
    target_label: __mms_ingop
    replacement: streaming/media-processing-platform
    action: replace
  - source_labels: [__name__]
    separator: ;
    regex: onvif_success_total_count
    target_label: __mms_ingop
    replacement: streaming/media-processing-platform
    action: replace
  - source_labels: [__mms_ingop]
    separator: ;
    regex: .+
    replacement: $1
    action: keep
  - separator: ;
    regex: __mms_ingop
    replacement: $1
    action: labeldrop
  queue_config:
    capacity: 10000
    max_shards: 10
    min_shards: 2
    max_samples_per_send: 5000
    batch_send_deadline: 30s
    min_backoff: 50ms
    max_backoff: 1s
```

The inserted configuration was as follows, but were interspersed between other entires:
```yaml
  - source_labels: [__name__]
    separator: ;
    regex: kep_se_http_requests_total
    target_label: __mms_ingop
    replacement: monitoring/sca-enr
    action: replace
  - source_labels: [__name__]
      separator: ;
      regex: kep_se_queued_messages_total
      target_label: __mms_ingop
      replacement: monitoring/sca-enr
      action: replace
  - source_labels: [__name__]
      separator: ;
      regex: kep_se_queueing_delay_seconds_bucket
      target_label: __mms_ingop
      replacement: monitoring/sca-enr
      action: replace
  - source_labels: [__name__]
      separator: ;
      regex: kep_se_queueing_delay_seconds_count
      target_label: __mms_ingop
      replacement: monitoring/sca-enr
      action: replace
  - source_labels: [cluster_name, __name__]
    separator: ;
    regex: .*sca-enr.*;envoy_cluster_upstream_rq_time_bucket
    target_label: __mms_ingop
    replacement: monitoring/sca-enr
    action: replace
  - source_labels: [cluster_name, __name__]
    separator: ;
    regex: .*sca-enr.*;envoy_cluster_upstream_rq
    target_label: __mms_ingop
    replacement: monitoring/sca-enr
```

Of these, the `envoy_cluster_upstream_rq_time_bucket` and `envoy_cluster_upstream_rq` metrics were not remote-written, while the rest were.

**What did you do?**
- Added 6 entries to prometheus remote-write relabelling configuration
- Reloaded prometheus

**What did you expect to see?**
- Entire set of relabelling configurations applied for remote-written metrics

**What did you see instead? Under which circumstances?**
- Only 4 of the 6 entries were applied

**Environment**

* System information:
```
Linux 5.3.0-59-generic x86_64
```

* Prometheus version:
```
prometheus, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
```

* Timeline:

| Time                                        | Observation |
| ---------------------------- |-------------|
| 2020-06-24T20:21Z | Initial configuration is loaded, only partial results are observed |
| 2020-06-24T20:36Z | Partial metrics are available in remote-written database. |
| 2020-06-24T21:15Z  |  We start playing with the configuration to try to determine the issue. |
| 2020-06-24T22:40Z | Replica-1 is restarted and we get metrics in remote-written database |
| 2020-06-24T23:23Z | Dropped a large section of configuration |
| 2020-06-24T23:29Z | Added back configuration |
| 2020-06-24T23:30Z | Metrics from replica-0 replicas now available in remote-written db |

* Logs:

_The behaviour of the WAL watcher seems suspicious here, I would expect to see more occurrences during other reloads, since at least one contained changes to the relabelling rules._

```json
{"caller":"head.go:731","component":"tsdb","duration":"3.766783368s","first":522,"last":524,"level":"info","msg":"WAL checkpoint complete","ts":"2020-06-24T19:00:14.677Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T20:21:33.017Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T20:21:33.299Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T20:23:01.318Z"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Stopping remote storage...","remote_name":"aff0cf","ts":"2020-06-24T20:23:01.354Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"WAL watcher stopped","queue":"aff0cf","remote_name":"aff0cf","ts":"2020-06-24T20:23:02.863Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Remote storage stopped.","remote_name":"aff0cf","ts":"2020-06-24T20:23:02.962Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"starting WAL watcher","queue":"1645c0","remote_name":"1645c0","ts":"2020-06-24T20:23:02.962Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"replaying WAL","queue":"1645c0","remote_name":"1645c0","ts":"2020-06-24T20:23:02.962Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T20:23:03.201Z"}
{"caller":"dedupe.go:112","component":"remote","duration":"1m55.599243324s","level":"info","msg":"done replaying WAL","remote_name":"1645c0","ts":"2020-06-24T20:24:58.562Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T20:48:36.049Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T20:48:36.315Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T20:50:01.485Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T20:50:02.172Z"}
{"caller":"compact.go:496","component":"tsdb","duration":"8.866740271s","level":"info","maxt":1593028800000,"mint":1593021600000,"msg":"write block","ts":"2020-06-24T21:00:09.029Z","ulid":"01EBM22Q92JXPWG63JFXFYSNDY"}
{"caller":"head.go:661","component":"tsdb","duration":"391.516337ms","level":"info","msg":"head GC completed","ts":"2020-06-24T21:00:10.399Z"}
{"caller":"head.go:731","component":"tsdb","duration":"3.9312373s","first":525,"last":527,"level":"info","msg":"WAL checkpoint complete","ts":"2020-06-24T21:00:14.330Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T22:29:01.318Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T22:29:01.609Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T22:32:01.319Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T22:32:01.611Z"}
{"caller":"compact.go:496","component":"tsdb","duration":"9.265954394s","level":"info","maxt":1593036000000,"mint":1593028800000,"msg":"write block","ts":"2020-06-24T23:00:09.427Z","ulid":"01EBM8YEH1RYFRGEW7SG8V0X1D"}
{"caller":"head.go:661","component":"tsdb","duration":"411.745914ms","level":"info","msg":"head GC completed","ts":"2020-06-24T23:00:11.002Z"}
{"caller":"head.go:731","component":"tsdb","duration":"3.733722625s","first":528,"last":530,"level":"info","msg":"WAL checkpoint complete","ts":"2020-06-24T23:00:14.736Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T23:23:01.318Z"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Stopping remote storage...","remote_name":"1645c0","ts":"2020-06-24T23:23:01.354Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"WAL watcher stopped","queue":"1645c0","remote_name":"1645c0","ts":"2020-06-24T23:23:02.059Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Remote storage stopped.","remote_name":"1645c0","ts":"2020-06-24T23:23:02.122Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"starting WAL watcher","queue":"a7f4af","remote_name":"a7f4af","ts":"2020-06-24T23:23:02.123Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"replaying WAL","queue":"a7f4af","remote_name":"a7f4af","ts":"2020-06-24T23:23:02.123Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T23:23:02.362Z"}
{"caller":"dedupe.go:112","component":"remote","duration":"1m43.78021913s","level":"info","msg":"done replaying WAL","remote_name":"a7f4af","ts":"2020-06-24T23:24:45.903Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-24T23:29:01.318Z"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Stopping remote storage...","remote_name":"a7f4af","ts":"2020-06-24T23:29:01.362Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"WAL watcher stopped","queue":"a7f4af","remote_name":"a7f4af","ts":"2020-06-24T23:29:02.869Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"Remote storage stopped.","remote_name":"a7f4af","ts":"2020-06-24T23:29:02.933Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"starting WAL watcher","queue":"1645c0","remote_name":"1645c0","ts":"2020-06-24T23:29:02.934Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"dedupe.go:112","component":"remote","level":"info","msg":"replaying WAL","queue":"1645c0","remote_name":"1645c0","ts":"2020-06-24T23:29:02.934Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-24T23:29:03.981Z"}
{"caller":"dedupe.go:112","component":"remote","duration":"1m50.384327977s","level":"info","msg":"done replaying WAL","remote_name":"1645c0","ts":"2020-06-24T23:30:53.318Z","url":"http://remote-write:7201/api/v1/prom/remote/write"}
{"caller":"compact.go:496","component":"tsdb","duration":"8.659843152s","level":"info","maxt":1593043200000,"mint":1593036000000,"msg":"write block","ts":"2020-06-25T01:00:08.821Z","ulid":"01EBMFT5S1ARMVFJ4ZRBDNZPEZ"}
{"caller":"head.go:661","component":"tsdb","duration":"325.401756ms","level":"info","msg":"head GC completed","ts":"2020-06-25T01:00:10.105Z"}
{"caller":"head.go:731","component":"tsdb","duration":"3.826068766s","first":531,"last":533,"level":"info","msg":"WAL checkpoint complete","ts":"2020-06-25T01:00:13.931Z"}
{"caller":"main.go:747","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Loading configuration file","ts":"2020-06-25T02:27:04.054Z"}
{"caller":"main.go:775","filename":"/etc/prometheus/config_out/prometheus.env.yaml","level":"info","msg":"Completed loading of configuration file","ts":"2020-06-25T02:27:04.331Z"}
```
