### ISSUE TITLE
Alerts still pending

### ISSUE THREAD

**Issue by mohamed-amine-haine** [prometheus/prometheus#7467]
**What did you do?**

i had a bug in prod and i reproduce it in dev. i configure prometheus with blackbox to alert me when httpd doesn't answer me correctly (good response only 200).

in my server httpd + php, i wrote simple code : a sleep loop for 1 minute to explicitly not answer prometheus in time. (scrape timeout : 40s)

**What did you expect to see?**

i expect to see two firing alerts with severity warning and critical after 10 and 15 minutes. (see prometheus.yml below)

**What did you see instead? Under which circumstances?**

alerts with severity warning and critical still pending. when i go in prometheus graph and visualize ALERTS metric i see a discontinuous curve :

<img width="731" alt="Screenshot_1" src="https://user-images.githubusercontent.com/26899257/85845026-e2274c80-b7a3-11ea-9a62-1e5d9a6a5246.png">

but probe_succes metric still correct and not discontinuous curve :

![InkedScreenshot](https://user-images.githubusercontent.com/26899257/85845472-97f29b00-b7a4-11ea-895c-f8f8790d4bc4.jpg)

**Environment**

* System information:

	Linux 4.19.76-linuxkit x86_64

* Prometheus version:

	2.16.0

* Prometheus configuration file:

```
# /etc/prometheus/prometheus.yml
global:
  scrape_interval: 5m 
  evaluation_interval: 15s
  scrape_timeout: 40s

rule_files:
  - 'rules/*'

scrape_configs:
  - job_name: 'blackbox_2'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
    - targets:
      - http://httpd_2:80    # Target to probe with http.
      labels:
        app_name: httpd
        org_name: morito
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115  # The blackbox exporter's real hostname:port
```

* Prometheus rules file:

```
# /etc/prometheus/rules/httpd_rules.yml

groups:
  - name: httpd
    rules:
    - alert: lifetesting
      expr: probe_success{app_name="httpd"} < 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "lifetesting"
        description: "Egregore a détecté une intrerruption de service de votre application. Merci de vérifier son fonctionnement."
        source: "{{ $labels.instance }}"
    - alert: lifetesting
      expr: probe_success{app_name="httpd"} < 1
      for: 15m
      labels:
        severity: critical
      annotations:
        summary: "lifetesting"
        description: "Votre application est hors service, Merci de procéder à sa remise en service."
        source: "{{ $labels.instance }}"
```

* Logs:

```
# blackbox log

Logs for the probe:
ts=2020-06-26T09:22:32.228610161Z caller=main.go:304 module=http_2xx target=http://httpd_2:80 level=info msg="Beginning probe" probe=http timeout_seconds=39.5
ts=2020-06-26T09:22:32.228863461Z caller=http.go:318 module=http_2xx target=http://httpd_2:80 level=info msg="Resolving target address" ip_protocol=ip6
ts=2020-06-26T09:22:32.229529462Z caller=http.go:318 module=http_2xx target=http://httpd_2:80 level=info msg="Resolved target address" ip=172.30.0.4
ts=2020-06-26T09:22:32.229590062Z caller=client.go:250 module=http_2xx target=http://httpd_2:80 level=info msg="Making HTTP request" url=http://172.30.0.4:80 host=httpd_2:80
ts=2020-06-26T09:23:11.729083856Z caller=main.go:119 module=http_2xx target=http://httpd_2:80 level=error msg="Error for HTTP request" err="Get http://172.30.0.4:80: context deadline exceeded"
ts=2020-06-26T09:23:11.729148056Z caller=main.go:119 module=http_2xx target=http://httpd_2:80 level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-06-26T09:22:32.229781962Z dnsDone=2020-06-26T09:22:32.229781962Z connectDone=2020-06-26T09:22:32.229968462Z gotConn=2020-06-26T09:22:32.230015763Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-06-26T09:23:11.729206956Z caller=main.go:304 module=http_2xx target=http://httpd_2:80 level=error msg="Probe failed" duration_seconds=39.500547795

```

when i change the scrape interval to 2 minutes no error occured. please test with all this specifications.
