### ISSUE TITLE
Prometheus losing data with 'unexpected non-zero byte in page term bytes`

### ISSUE THREAD

**Issue by jakubgs** [prometheus/prometheus#7506]
# Issue
My container started showing these errors:
```
msg="error tailing WAL" err="readCheckpoint: readSegment: unexpected non-zero byte in page term bytes"
```
And it appears I'm losing metrics. There's a growing gap in metrics visible.

Based on what I read in https://github.com/prometheus/prometheus/issues/7299 and my previous experiences my understanding is that I need to remove the corrupted WAL file and all the ones after it. But the logs don't tell me which one is corrupted. What am I supposed to do?

# Info
Using Docker image `prom/prometheus:v2.19.2` on Ubuntu 18.04 LTS.

# Config
```yaml
global:
  scrape_interval:     30s
  scrape_timeout:      20s
  evaluation_interval: 30s
  external_labels:
    source: my-metrics-master

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    static_configs:
      - targets:
          - '10.1.1.1:1234'
    params:
      'match[]':
        - '{job=~".+"}'
```

# Logs
```
caller=dedupe.go:112 component=remote level=info remote_name=69e3e5 url= msg="Replaying WAL" queue=69e3e5
caller=dedupe.go:112 component=remote level=error remote_name=69e3e5 url= msg="error tailing WAL" err="readCheckpoint: readSegment: unexpected non-zero byte in page term bytes"
caller=dedupe.go:112 component=remote level=info remote_name=69e3e5 url= msg="Replaying WAL" queue=69e3e5
caller=dedupe.go:112 component=remote level=error remote_name=69e3e5 url= msg="error tailing WAL" err="readCheckpoint: readSegment: unexpected non-zero byte in page term bytes"
caller=dedupe.go:112 component=remote level=info remote_name=69e3e5 url= msg="Replaying WAL" queue=69e3e5
caller=dedupe.go:112 component=remote level=error remote_name=69e3e5 url= msg="error tailing WAL" err="readCheckpoint: readSegment: unexpected non-zero byte in page term bytes"
```
