### ISSUE TITLE
CPU Usage steadily increasing. 

### ISSUE THREAD

**Issue by andrew-pickin-epi** [prometheus/prometheus#7510]
**What did you do?**

Installed Prometheus on AWS EKS via https://github.com/helm/charts/blob/master/stable/prometheus-operator

**What did you expect to see?**

Steady CPU/Memory usage give the target count is static.

**What did you see instead? Under which circumstances?**

Continued increase in CPU usage.

**Environment**

 AWS EKS via https://github.com/helm/charts/blob/master/stable/prometheus-operator

* System information:

VERSION                    OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME
v1.16.8-eks-e16311   Amazon Linux 2   4.14.181-140.257.amzn2.x86_64   docker://19.3.6

prometheus op v 2.18.1

* Prometheus version:

/bin/prometheus --version
prometheus, version 2.18.1 (branch: HEAD, revision: ecee9c8abfd118f139014cb1b174b08db3f342cf)
  build user:       root@2117a9e64a7e
  build date:       20200507-16:51:47
  go version:       go1.14.2

* Alertmanager version:

n/a

* Prometheus configuration file:
```
From values.yml

prometheus:
  annotations: {}
  enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    enabled: true
    hosts:
    - prometheus-ea.epimorphics.net
    labels: {}
    paths:
    - /
  ingressPerReplica:
    enabled: false
  nodeSelector:
    role: worker
  prometheusSpec:
    retention: 14d
    serviceMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    annotations: {}
    labels: {}
    port: 9090
    targetPort: 9090
    type: ClusterIP
  serviceAccount:
    create: true
  servicePerReplica:
    enabled: false
prometheus-node-exporter:
  extraArgs:
  - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
  - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
  podLabels:
    jobLabel: node-exporter
prometheusOperator:
  enabled: true
  kubeletService:
    enabled: true
    namespace: kube-system
```

* Alertmanager configuration file:
```
n/a
```

* Logs:
```
Nothing obviously relevant. 
```
![image](https://user-images.githubusercontent.com/60097451/86462002-c8958000-bd22-11ea-957e-8d291a3846b4.png)
![image](https://user-images.githubusercontent.com/60097451/86462038-d8ad5f80-bd22-11ea-8908-cdc297e575fc.png)
