### ISSUE TITLE
prometheus remote_read doesn't work if external_labels added after metric wrote to influxdb 

### ISSUE THREAD

**Issue by whaike** [prometheus/prometheus#7520]
my question: **thanos can't query prometheus old data which have to read from influxdb by  remote_read**

env:
    prometheus version=2.6.0
    thanos, version 0.12.2

config:

```
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{__name__=~".+"}'

    static_configs:
      - targets:
        - '10.10.44.20:9090'
```

## Things come from this
I made a new prometheus cluster with thanos ,but i don't want to delete my historical data which stored in influxdb. So i added thanos-sidecar for my old prometheus ,also with external_labels configs. but it doesn't work. 
I found the reason was **prometheus query influxdb with the label external_labels ,if i removed external_labels, it work, but if to,the thanos query will not deduplicat for this prometheus.**

link to https://github.com/thanos-io/thanos/issues/2843
