### ISSUE TITLE
prometheus target DNS update is not updating

### ISSUE THREAD

**Issue by yasharne** [prometheus/prometheus#7552]
**What did you do?**
We had DNS records like `one-01.x.y.z` pointing to a machine with IP `172.16.76.20` and `one-02.x.y.z` pointing to `172.16.76.21`.
We add a job in our Prometheus configuration file to scrape metrics from the targets using the names `one-01.x.y.z` and `one-02.x.y.z`.
Now we have updated the DNS record so now `one-01.x.y.z` points to another machine with IP `172.16.76.22` (the new machine has no exporters on in).
We have also deleted the `one-02.x.y.z` record from our DNS (the machine still accessible via the IP address).
Using the `dig` command we made sure that `one-01.x.y.z` is pointing to `172.16.76.22` and `one-02.x.y.z` is not pointing to any hosts.

**What did you expect to see?**
Two unhealthy targets since one of them are pointing to a new machine which has no exporter on it and the other one's name cannot be resolved using DNS since we have deleted the DNS record

**What did you see instead? Under which circumstances?**
We saw both targets are working and gathering metrics, apparently, Prometheus is not trying to resolve the name on each scrape and only resolves the name on the first run.
removing the targets from `file_sd` and adding them again didn't solve the problem

**Environment**

* System information:

	Linux 4.15.0-88-generic x86_64

* Prometheus version:

	prometheus, version 2.15.2 (branch: HEAD, revision: d9613e5c466c6e9de548c4dae1b9aabf9aaf7c57)
        build user:       root@688433cf4ff7
        build date:       20200106-14:50:51
        go version:       go1.13.5

* Prometheus configuration file:
```
scrape_configs:

  - job_name: exporter
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: /metrics
    scheme: http
    file_sd_configs:
      - files:
        - 'file_sd/exporter.yml'

```
