### ISSUE TITLE
Add null/no value to input_series for rules unit tests

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#7680]
## Proposal
Sometimes alerts depend on a time series being there, or not, and it would be great to be able to test what happens if the time series disappears.
For example, we have this alert for our Postgres instances:
```
- alert: postgres_invalid_indices
  expr: count(pg_index_bloat_bloat_size{idxname=~".*_cc(new|old)"}) by (cluster, instance, team, datname) > 0
  for: 4h
```
Basically this alert tells us if any indices that match the regex pattern `.*_cc(new|old)` exist for more than 4 hours.

I could test this alert by timeseries like this:
```
tests:
  - interval: 1m
    input_series:
      - series: pg_index_bloat_bloat_size{idxname="my_index", team="team1", cluster="cluster1", datname="db1"}
        values: '1+0x1440' # (1 for 24h)
      - series: pg_index_bloat_bloat_size{idxname="my_index_ccnew", team="team1", cluster="cluster1", datname="db1"}
        values: '1+0x240' # (1 for 4h)
      - series: pg_index_bloat_bloat_size{idxname="my_index_ccold", team="team1", cluster="cluster1", datname="db1"}
        values: '1+0x120' # (1 for 2h)

    # Unit tests for alerting rules
    alert_rule_test:
        # Alert should not be triggered after 10 minutes.
      - eval_time: 10m
        alertname: postgres_invalid_indices
        exp_alerts: []

        # Alert should not be triggered after 2h minutes.
      - eval_time: 2h
        alertname: postgres_invalid_indices
        exp_alerts: []

        # Alert should not be triggered after 3h and 59m
      - eval_time: 239m
        alertname: postgres_invalid_indices
        exp_alerts: []

        # Alert should trigger after 4h
      - eval_time: 4h
        alertname: postgres_invalid_indices
        exp_alerts:
          - exp_labels:
              severity: low
              team: team1
              cluster: cluster1
              datname: db1

        # Alert should not be triggered after 4h and 6m (because of staleness)
      - eval_time: 246m
        alertname: postgres_invalid_indices
        exp_alerts: []
```
Now if I wanted to test if `_ccold` would trigger this alert I would have to create a new set of tests and input_series because the input_series doesn't support null.

`input_series` could support something like this:
```
- interval: 1m
  input_series:
    - series: pg_index_bloat_bloat_size{idxname="my_index_ccold", team="team1", cluster="cluster1", datname="db1"}
      values: 'NULL+NULLx60 1+0x240' # (no value for 1h, then 1 for 4h)
```
