### ISSUE TITLE
Add human-readable eval_time to rules unit tests

### ISSUE THREAD

**Issue by kustodian** [prometheus/prometheus#7681]
## Proposal
Rules unit tests would be much easier to read if the `eval_time` supported human-readable times like this:
```
    alert_rule_test:
        # Alert should not be triggered after 3h and 59m
      - eval_time: 3h59m  # instead of 239m
        alertname: postgres_invalid_indices
        exp_alerts: []

        # Alert should not be triggered after 4h and 6m (because of staleness)
      - eval_time: 4h6m  # instead of 246m
        alertname: postgres_invalid_indices
        exp_alerts: []
```
If something needs to be triggered after 4 hours and if we want to test will it be triggered at 3 hours and 59 minutes, it's easier to read `3h59m`, then `239m`. Samo goes for `4h6m` instead of `246m`.
