### ISSUE TITLE
promtool rule test flaky (not deterministic) when eval_times are far apart

### ISSUE THREAD

**Issue by rudo-thomas** [prometheus/prometheus#7699]
# promtool is flaky when eval_times are far apart in a rule test

## What did you do?

Ran `promtool test rules bug.testall.flaky.yaml` and got different results:
```
$ promtool-2.20.0 test rules bug.testall.flaky.yaml 
Unit Testing:  bug.testall.flaky.yaml
  FAILED:
    expr: "some_metric", time: 1h,
        exp:"{__name__=\"some_metric\"} 0E+00"
        got:"nil"

$ promtool-2.20.0 test rules bug.testall.flaky.yaml 
Unit Testing:  bug.testall.flaky.yaml
  SUCCESS
```
I used a script tun run promtool many times in succession to observe the flakiness.

The test has a single `promql_expr_test` against a trivial metric, but the `eval_time` of the two `<promql_test_case>`s are many `evaluation_interval`s apart. See the full file below.

## What did you expect to see?

It appears that under some circumstances, the test tool drops old data (see the failure above).

I expect the test tool not to drop any old data under any circumstances and, in this case, the test should consistently succeed.

* versions that exhibit the correct behaviour: `2.15.2`, `2.16.0`
* versions that exhibit the bug: `2.17.0`, ..., `2.20.0`

## What did you see instead? Under which circumstances?

I was unable to pinpoint to a particular reason for a failed vs successful run.

If you are getting consistent results, try running the tool 100 times and/or tweaking the later `eval_time`.
The value posted below (`30000h`) worked reasonably fine to trigger the flakiness on my system.

## Workaround

In my case the easiest workaround was to place the tests with different `eval_time` into separate files (see `bug.test1.ok.yaml` and `bug.test2.ok.yaml` in the attached archive).

Note that making these a separate `<test_group>` in a single file didn't help.

## Files for reproducing the bug
[promtool_flakiness.tar.gz](https://github.com/prometheus/prometheus/files/5001148/promtool_flakiness.tar.gz)

### `bug.rules.yaml`
```
groups:
- name: group
  interval: 1m  # irrelevant
  rules:
  - record: some_metric
    expr: 0
```
### bug.testall.flaky.yaml
```
rule_files:
- bug.rules.yaml
evaluation_interval: 30m
tests:
- promql_expr_test:
  - expr: some_metric
    eval_time: 1h
    exp_samples:
    - labels: some_metric{}
      value: 0
  - expr: some_metric
    # Tweak the following eval_time to get flaky behaviour.
    # Value too low => test always succeeds; too high => test always fails.
    eval_time: 30000h
    exp_samples:
    - labels: some_metric{}
      value: 0
```
Since `2.17.0` `promtool test rules bug.testall.flaky.yaml` is flaky.

## System information:

```
$ uname -srmpi
Linux 5.4.0-42-generic x86_64 x86_64 x86_64
```

## promtool version:

Downloaded for `linux-amd64` from the official github releases.

```
promtool, version 2.16.0 (branch: HEAD, revision: b90be6f32a33c03163d700e1452b54454ddce0ec)
  build user:       root@7ea0ae865f12
  build date:       20200213-23:50:02
  go version:       go1.13.8
promtool, version 2.17.0 (branch: HEAD, revision: 39e01b369dbd78278ca63e54f4976dff3b41df98)
  build user:       root@604d4517e800
  build date:       20200324-17:04:11
  go version:       go1.13.9
promtool, version 2.20.0 (branch: HEAD, revision: e5a06b483527d4fe0704b8fa3a2b475b661c526f)
  build user:       root@ac954b6d5c6e
  build date:       20200722-18:51:45
  go version:       go1.14.6
```
