### ISSUE TITLE
[feature] Ability to specify consul_sd service with tag

### ISSUE THREAD

**Issue by MrMMorris** [prometheus/prometheus#771]
Would it be possible to have the ability to specify tags along with consul services? something like:

```yaml
scrape_configs:
  - job_name: 'node'

    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        datacenter: 'ec2'

        services:
          - 'monitoring:node'

scrape_configs:
  - job_name: 'container'

    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        datacenter: 'ec2'

        services:
          - 'monitoring:container'
```

As opposed to having to have separate service names like this:

```yaml
scrape_configs:
  - job_name: 'node'

    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        datacenter: 'ec2'

        services:
          - 'monitoring-node'

scrape_configs:
  - job_name: 'container'

    consul_sd_configs:
      - server: 'consul.service.consul:8500'
        datacenter: 'ec2'

        services:
          - 'monitoring-container'
```

Or maybe

```yaml
services:
  - 'monitoring'

tags: 
  - 'node'
```

Does this make sense?

**Comment by MrMMorris** [comment]
Or somewhat related: where do consul tags show up? there is tag_separator in the config, but I haven't seem them anywhere in the metadata labels

**Comment by fabxc** [comment]
The Consul tags are in the `__meta_consul_tags` label. With a [relabeling rule](http://prometheus.io/docs/operating/configuration/#relabeling-relabel_config) you can  filter the targets you want to scrape based on whether 'container' or 'tags' show up in there.

```
scrape_configs:
- job_name: 'monitoring'
 
  consul_sd_configs:
  - server: 'consul.service.consul:8500'
    datacenter: 'ec2'
    services:
    - 'monitoring'

  relabel_configs:
  - source_labels: ['__meta_consul_tags']
    regex: '(container|node)`
    action: keep
```
