### ISSUE TITLE
PromConsole area renderer elevates a time series unexpectedly

### ISSUE THREAD

**Issue by staschuk-bungalow** [prometheus/prometheus#7711]
**What did you do?**

I used PromConsole.Graph with `renderer: "area"`, and often see time series elevated more than they should be, as if they were stacked on other time series which are not actually under them.  I attach a screenshot.

See https://github.com/livebungalow/promconsole-rendering-example for a small working example (well, non-working, which is the point).  For the purposes of that example, I monkey-patch `PromConsole.Graph.prototype.buildQueryUrl` to inject data which provokes the issue -- I copied this data from an actual `query_range` response, formatted it, and reduced it to a manageable size.

**What did you expect to see?**

Time series resting on the x-axis.

**What did you see instead? Under which circumstances?**

Time series elevated off the x-axis.  The linked example repo has sample data that provokes the problem.

**Environment**

The linked example uses the docker image `prom/prometheus:v2.19.3` with its standard configuration file.

**Comment by staschuk-bungalow** [comment]
<img width="495" alt="screenshot" src="https://user-images.githubusercontent.com/57634948/89080891-1fa96780-d358-11ea-914d-fbff3092d967.png">
the promised screenshot

**Comment by staschuk-bungalow** [comment]
Oh, and my browser is Chrome Version 84.0.4147.89 (Official Build) (64-bit) on macOS 10.15.6 (19G73).

**Comment by staschuk-bungalow** [comment]
Oh, and: I do _not_ see this behaviour in the expression browser, even for the same queries.  That is, if I click on the little plus sign of a console graph that has the wrong elevations, the resulting expression browser graph does not have wrong elevations.

**Comment by brian-brazil** [comment]
What is the query that's using? Based on the timestamps that looks like a range vector from query, rather than from query range - which Rickshaw may not like.

**Comment by staschuk-bungalow** [comment]
@brian-brazil The query that produced that data is `sum by (code_version) (info)`

**Comment by brian-brazil** [comment]
Can you share the full query_range URL? The sample data you have didn't come from a Prometheus query_range - the timestamps are all wrong.

**Comment by staschuk-bungalow** [comment]
@brian-brazil : verbatim from chrome developer tools, on a console where I'm seeing this issue in production:
```
:path: /api/v1/query_range?query=sum%20by%20(ecs_service)%20(up%7Bjob%3D%22ecs-task%22%2Cservice%3D%22metrics-web%22%7D)&step=5.3097345132743365&start=1596576860.673&end=1596580460.673
```
The first thousand characters of the response:
```
{"status":"success","data":{"resultType":"matrix","result":[{"metric":{},"values":[[1596576860.673,"0"],[1596576865.982,"0"],[1596576871.291,"0"],[1596576876.600,"0"],[1596576881.909,"0"],[1596576887.218,"0"],[1596576892.527,"0"],[1596576897.836,"0"],[1596576903.145,"0"],[1596576908.454,"0"],[1596576913.763,"0"],[1596576919.072,"0"],[1596576924.381,"0"],[1596576929.690,"0"],[1596576934.999,"0"],[1596576940.308,"0"],[1596576945.617,"0"],[1596576950.926,"0"],[1596576956.235,"0"],[1596576961.544,"0"],[1596576966.853,"0"],[1596576972.162,"0"],[1596576977.471,"0"],[1596576982.780,"0"],[1596576988.089,"0"],[1596576993.398,"0"],[1596576998.707,"0"],[1596577004.016,"0"],[1596577009.325,"0"],[1596577014.634,"0"],[1596577019.943,"0"],[1596577025.252,"0"],[1596577030.561,"0"],[1596577035.870,"0"],[1596577041.179,"0"],[1596577046.488,"0"],[1596577051.797,"0"],[1596577057.106,"0"],[1596577062.415,"0"],[1596577067.724,"0"],[1596577073.033,"0"],[1596577078.342,"0"],[1596577083.651,"0"],[1596577088.96
```
(lmk if you want more).

Since we seem to suspect that the data is wrong, here's details about the server that produced it.  (I omitted this information before because I believed it was a front-end issue.)

System information:

```
$ uname -srm
Linux 4.14.181-140.257.amzn2.x86_64 x86_64
```

Prometheus version:

```
$ prometheus --version
prometheus, version 2.15.1 (branch: HEAD, revision: 8744510c6391d3ef46d8294a7e1f46e57407ab13)
  build user:       root@4b1e33c71b9d
  build date:       20191225-01:04:15
  go version:       go1.13.5
```

Prometheus configuration file:

```
global:
  external_labels:
    export_prefix: productionfieldstone
scrape_configs:
  - job_name: ecs-task
    scrape_interval: 10s
    scheme: http
    file_sd_configs:
    - files:
      - /etc/prometheus/ecs-list.json
  - job_name: recent-commits
    scrape_interval: 60s
    scheme: https
    metrics_path: /github-recent-commits/recent-commits
    params:
      repo:
      - fieldstone
    bearer_token: [redacted]
    static_configs:
    - targets:
      - botler.bungalow.com
  - job_name: pushgateway
    scrape_interval: 1m
    scheme: http
    honor_labels: true
    static_configs:
      - targets:
          - 'localhost:9091'
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'localhost:9093'
rule_files:
  - rules/*.yaml
```

I omit the rules files; they specify alerts (no recording rules).  Let me know if you think they might be relevant.
