### ISSUE TITLE
Prometheus can ingest bad metrics name via recording rules

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#7762]
The following recording rule:

```
groups:
  - name: test
    evaluation_interval: 1s
    rules:
      - record: "a1"
        expr: vector(1)
        labels:
          __name__: -1
```
Creates a metric named -1. You can also create 1a, 1m, etc.

Tested on prometheus 2.20.
