### ISSUE TITLE
grafana got error data of future from Prometheus

### ISSUE THREAD

**Issue by husoule** [prometheus/prometheus#7765]
**What did you do?**
I adjusted the parameters --query.lookback-delta=10s, and If I play with Prometheus directly, I  see the latest result being less then now + lookback-delta. This is as expected。 but the grafana still get data from future 5m.

play with Prometheus directly:
![image](https://user-images.githubusercontent.com/5336915/89648408-be523d00-d8f1-11ea-86c2-49e5d11b2e3f.png)

the url is from grafana query Inspector:
![image](https://user-images.githubusercontent.com/5336915/89648548-f48fbc80-d8f1-11ea-8521-68f288c202e0.png)

but grafana still display data of future 5m。
![image](https://user-images.githubusercontent.com/5336915/89648600-0bceaa00-d8f2-11ea-9eaa-482746880d24.png)

This is very confusing。the same url get difrrent date.

**What did you expect to see?**

The graph of grafana shows the same data as directly requesting prometheus

**What did you see instead? Under which circumstances?**
The graph got data of future 5m

**Environment**
prometheus: v2.18.1 
grafana：v6.5.2

* Prometheus configuration file:
```
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.18.1
        args:
        - --config.file=/etc/prometheus/config_out/prometheus.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=1d
        - --web.route-prefix=/
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --storage.tsdb.min-block-duration=2h
        - --storage.tsdb.max-block-duration=2h
        - --log.level=debug
        - --query.lookback-delta=5s
```
