### ISSUE TITLE
prometheus connection reset by peer

### ISSUE THREAD

**Issue by abelal83** [prometheus/prometheus#7785]
**What did you do?**

Configured promethues to scrape blackbox exporter behind F5 load balancer 
```yaml
  - job_name: 'prometheus-blackbox-exporter-lon-internal'
    scrape_interval: 20s
    scrape_timeout: 10s
    metrics_path: /probe
    scheme: https
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://gain.uat.clarksons.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: promblackbox-lon.sea.live
```
**What did you expect to see?**
Promethues to succesfully scrape target

**What did you see instead? Under which circumstances?**

Error in target
```
Get "https://promblackbox-lon.sea.live:443/probe?module=http_2xx&target=https%3A%2F%2Fgain.uat.clarksons.com": read tcp 10.26.194.224:43898->10.53.10.244:443: read: connection reset by peer
--

using wget on promethues pod I can succesffully reach target
wget "https://promblackbox-lon.sea.live/probe?module=http_2xx&target=https%3A%2F%2Fgain.uat.clarksons.com"

I've searched user forum but no answers from anyone so I'm assuming this is a bug.
```
**Environment**

Azure Kubernetes

I;m using the helm chart for promethues appVersion: 2.19.0

* System information:

Linux 4.15.0-1089-azure x86_64

* Prometheus version:
```
prometheus, version 2.19.2 (branch: HEAD, revision: c448ada63d83002e9c1d2c9f84e09f55a61f0ff7)
  build user:       root@dd72efe1549d
  build date:       20200626-09:02:20
  go version:       go1.14.4
```

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    cluster: pltfrmaks1-stg-ne
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - redalert-we.pltfrmaks-stg.sea.live
      - redalert-ne.pltfrmaks-stg.sea.live
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /etc/config/recording_rules.yml
- /etc/config/alerting_rules.yml
- /etc/config/rules
- /etc/config/alerts
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: prometheus-blackbox-exporter-lon-internal
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 20s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: https
  static_configs:
  - targets:
    - https://gain.uat.clarksons.com
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: promblackbox-lon.sea.live
    action: replace
```
