### ISSUE TITLE
add a feature that can support reading rule from the database

### ISSUE THREAD

**Issue by chaimch** [prometheus/prometheus#7786]
## Proposal
**Use case. Why is this important?**

Promethues are deployed in EC2, ECS, EKS. 
At this point, the management of rule is not convenient.

If you support reading rule from the database, it is convenient to manage rule.

In fact, I have already made extensions to support reading rules from both files and databases.

Can this feature be merged?

If not, can you tell me why?

**Comment by roidelapluie** [comment]
Prometheus rules are purposedly only found in files and then kept in memory. Having them in a database would be another way to deal with them, and that raises many operability concerns: how to refresh them, what to do when the db is down, how to manage the schemas.

So far we do not want to add that ability and complexity to prometheus. If you have an extension it is probably easy to make it write rules to files then reload prometheus.

**Comment by chaimch** [comment]
The promethues configuration can be shown as follows：
```
global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    cluster: pltfrmaks1-stg-ne
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - redalert-we.pltfrmaks-stg.sea.live
      - redalert-ne.pltfrmaks-stg.sea.live
    scheme: http
    timeout: 10s
    api_version: v1
rule_files:
- /etc/config/rules
- /etc/config/alerts
rule_db:
- "root:root@tcp(localhost:3306)/prometheus"
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
```
