### ISSUE TITLE
Recording rule displaying different results than ad-hoc querying

### ISSUE THREAD

**Issue by perlun** [prometheus/prometheus#7852]
**What did you do?**
Created a recording rule and used it in a Grafana dashboard

**What did you expect to see?**
Similar query results as when using ad-hoc querying

**What did you see instead? Under which circumstances?**
### Querying recording rule

(See included recording rules config later down in this issue.)

![image](https://user-images.githubusercontent.com/630613/91270551-7a7c8600-e781-11ea-9419-cfec3eac4b0e.png)

### Querying with ad-hoc query

Copy-pasting the recording rule and running it as ad-hoc instead gives me a completely different picture:

![image](https://user-images.githubusercontent.com/630613/91270597-8f591980-e781-11ea-9540-02f25dd19687.png)

### Conclusions

It's hard to know for us which one of these are correct, but I surely _hope_ that the ad-hoc picture is the correct one... i.e. that our application has spikes in terms of 5-10 second requests rather than 60 second requests. :sweat_smile: 

Are we doing something wrong here, or what could be causing this? Could it be a bug in Prometheus or something else?

**Environment**

* System information:

	  Linux 4.19.0-6-amd64 x86_64

* Prometheus version:

      prometheus, version 2.13.1 (branch: HEAD, revision: 6f92ce56053866194ae5937012c1bec40f1dd1d9)
        build user:       root@88e419aa1676
        build date:       20191017-13:15:01
        go version:       go1.13.1

    (Also tested with v2.18.1 in Docker, with similar results.)

* Prometheus configuration file:
```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

rule_files:
  - /opt/hibox/prometheus/etc/*_rules.yaml
```

### custom_recording_rules.yml

```yaml
  - name: hbx_controller_action_global
    rules:
      - record: global:hbx_controller_action_seconds:histogram_quantile_50p_rate_1m
        expr: histogram_quantile(0.5, sum by (le)(rate(hbx_controller_action_seconds_bucket[1m])))
      - record: global:hbx_controller_action_seconds:histogram_quantile_75p_rate_1m
        expr: histogram_quantile(0.75, sum by (le)(rate(hbx_controller_action_seconds_bucket[1m])))
      - record: global:hbx_controller_action_seconds:histogram_quantile_95p_rate_1m
        expr: histogram_quantile(0.95, sum by (le)(rate(hbx_controller_action_seconds_bucket[1m])))
      - record: global:hbx_controller_action_seconds:histogram_quantile_99p_rate_1m
        expr: histogram_quantile(0.99, sum by (le)(rate(hbx_controller_action_seconds_bucket[1m])))
```
