### ISSUE TITLE
blackbox probe : x509: certificate signed by unknown authority even with insecure_skip_verify set to true

### ISSUE THREAD

**Issue by mguthmuller** [prometheus/prometheus#7854]
**What did you do?**

Hello!

I'm trying to monitor a website with prometheus and blackbox exporter. Each of them are running inside a docker (images pulled from official docker hub https://hub.docker.com/r/prom/prometheus and https://hub.docker.com/r/prom/blackbox-exporter/).

My blackbox config:

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
      tls_config:
        insecure_skip_verify: true
      no_follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: true
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
```

My issue: the target that I'm trying to monitor is using a self-signed certificate. That's why I tried to set insecure_skip_verify: true but it doesn't seem to handle it. I have the following error in the probe debug:

```
ts=2020-08-26T10:09:33.988405182Z caller=main.go:119 module=http_2xx target=https://example.com level=error msg="Error for HTTP request" err="Get \"https://x.x.x.x\": x509: certificate signed by unknown authority"
```

**What did you expect to see?**

probe_success 1 with metrics 

**What did you see instead? Under which circumstances?**

probe_success 0 with the error previously copied in debug mode.

**Environment**

* System information:

	n/a

* Prometheus version:

	docker image v2.20.1

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
  external_labels:
    env: 'my-supervision'

scrape_configs:

  - job_name: 'blackbox-http-2xx'
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
      - source_labels: [__address__]
        regex: ([^,]*),(.*)
        replacement: $1
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # The blackbox exporter's real hostname:port.
    static_configs:
      - targets: 
        - https://example.com,example # replaced the real target for the issue creation
```
