### ISSUE TITLE
metric returned to prometheus but not added to prometheus db

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [prometheus/prometheus#7893]
**What did you do?**
Simple configuration to ping host

**What did you expect to see?**
i expect to see probe_success in query

**What did you see instead? Under which circumstances?**

i see "no data" as query result for query "probe_success"

* Prometheus version:
Version | 2.20.1
983ebb4a513302315a8117932ab832815f85e3d2
HEAD
root@7cbd4d1c15e0
20200805-17:26:58
go1.14.6

* Prometheus configuration file:
```
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'icmp'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 1s
    params:
      module: [icmp_ping]

    file_sd_configs:
      - files:
        - icmp_check/nl.yml
        refresh_interval: 10m

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

```
nl.yml
```
[
 {
    "targets": ["10.111.111.1"],
    "labels": {
                "location": "nl",
                "checktype": "icmp",
                "simplename": "routernl",
              }
  },
]
```

* Blackbox configuration file:
```
modules:
  tcp_connect:
    prober: tcp
    timeout: 2s
  icmp_ping:
    prober: icmp
    timeout: 1s
    icmp:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false

```

* Result of opening url directly in browser "http://10.111.111.29:9115/probe?target=10.111.111.1&module=icmp_ping":
```
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 2.4636e-05
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.001183696
# HELP probe_icmp_duration_seconds Duration of icmp request by phase
# TYPE probe_icmp_duration_seconds gauge
probe_icmp_duration_seconds{phase="resolve"} 2.4636e-05
probe_icmp_duration_seconds{phase="rtt"} 0.000506051
probe_icmp_duration_seconds{phase="setup"} 0.000406057
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 2.534418624e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1

```
probe_success returned 1 but not added to promdb
![Screenshot_20200903_142927](https://user-images.githubusercontent.com/22169129/92115015-13e71000-edf2-11ea-83b1-9419253863ff.png)
