### ISSUE TITLE
 I wrote a webhook API interface, but I can't recive data.

### ISSUE THREAD

**Issue by huzhou520** [prometheus/prometheus#7917]
The Alertmanager will send HTTP POST requests in the following JSON format to the configured endpoint:
reference: https://prometheus.io/docs/alerting/latest/configuration/

SO I wrote a webhook API interface, but I can't recive data.
<QueryDict: {}> <class 'django.http.request.QueryDict'>
[09/Sep/2020 12:41:39] "POST /hook/send HTTP/1.1" 200 2
POST
no post data..

alert version:
alertmanager, version 0.21.0

Linux version:
centos 7.8
Linux 3.10.0-1127.10.1.el7.x86_64 x86_64

Prometheus version:
prometheus, version 2.19.2 (branch: HEAD, revision: c448ada63d83002e9c1d2c9f84e09f55a61f0ff7)

Alertmanager configuration file:
```
global:
  resolve_timeout: 5m

route:
  #group_by: ['instance']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4m
  receiver: 'webhook'
receivers:
- name: 'webhook'
  webhook_configs:
    - url: 'http://10.100.93.117:8009/hook/send'
```
Prometheus configuration file:
```
global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: prometheus

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 10.100.93.23:9093


rule_files:
  - /etc/prometheus/rules/*.rules
  - /etc/prometheus/rules/*.yml


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - prometheus:9090
  - job_name: node2
    static_configs:
    - targets: ["10.100.93.117:9100"]
    params:
      collect[]:
        - cpu
        - meminfo
        - diskstats
        - meminfo
        - diskstats
        - netdev
        - filefd
        - filesystem
  - job_name: docker
    static_configs:
    - targets: ["120.131.2.113:8010"]
    metric_relabel_configs:
      - source_labels: [id]
        regex: '/docker/([a-z0-9]+)'
        replacement: '$1'
        target_label: container_id
      - source_labels: [__name__]
        separator: ','
        regex: "(container_tasks_state|container_memory_failures_total)"
        #regex: "(container_memory_failures_total)"
        action: drop
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node

  - job_name: alertmanager
    static_configs:
    - targets: ["10.100.93.23:9093"]
```
Logs:
/var/log/messages
```
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.974Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=475 maxSegment=476
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.974Z caller=head.go:706 component=tsdb msg="WAL segment loaded" segment=476 maxSegment=476
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.974Z caller=head.go:709 component=tsdb msg="WAL replay completed" duration=188.404939ms
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.982Z caller=main.go:694 fs_type=EXT4_SUPER_MAGIC
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.982Z caller=main.go:695 msg="TSDB started"
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.982Z caller=main.go:799 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.993Z caller=main.go:827 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
Sep  9 20:36:02 prometheus prometheus: level=info ts=2020-09-09T12:36:02.993Z caller=main.go:646 msg="Server is ready to receive web requests."
```
alertmanager log
```
level=debug ts=2020-09-09T12:57:39.618Z caller=dispatch.go:473 component=dispatcher aggrGroup={}:{} msg=flushing alerts="[instancedown[48f8bc1][active] InstanceDown[2c6323b][active] InstancesDown[717e6b2][active] InstanceDown2[0565fad][active] HighNodeCPU[9b36b7b][active] Watchdog[29b1d11][active]]"
level=debug ts=2020-09-09T12:57:44.614Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=instancedown[48f8bc1][active]
level=debug ts=2020-09-09T12:57:44.615Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=InstanceDown2[0565fad][active]
level=debug ts=2020-09-09T12:57:44.615Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=InstancesDown[717e6b2][active]
level=debug ts=2020-09-09T12:57:59.320Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=Watchdog[29b1d11][active]
level=debug ts=2020-09-09T12:57:59.614Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=HighNodeCPU[9b36b7b][active]
level=debug ts=2020-09-09T12:58:39.618Z caller=dispatch.go:473 component=dispatcher aggrGroup={}:{} msg=flushing alerts="[instancedown[48f8bc1][active] InstanceDown[2c6323b][active] InstancesDown[717e6b2][active] InstanceDown2[0565fad][active] HighNodeCPU[9b36b7b][active] Watchdog[29b1d11][active]]"
level=debug ts=2020-09-09T12:58:44.321Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=InstanceDown[2c6323b][active]
level=debug ts=2020-09-09T12:58:59.614Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=instancedown[48f8bc1][active]
level=debug ts=2020-09-09T12:58:59.615Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=InstanceDown2[0565fad][active]
level=debug ts=2020-09-09T12:58:59.615Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=InstancesDown[717e6b2][active]
level=debug ts=2020-09-09T12:59:14.320Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=Watchdog[29b1d11][active]
level=debug ts=2020-09-09T12:59:14.614Z caller=dispatch.go:138 component=dispatcher msg="Received alert" alert=HighNodeCPU[9b36b7b][active]

```
