### ISSUE TITLE
negative matching expression on alertrules ?

### ISSUE THREAD

**Issue by KlavsKlavsen** [prometheus/prometheus#7923]
We want to monitor diskspace on ALL our servers - and alert on 80% used disk space.
BUT we have certain partitions, where we want to alert differently on a few servers.

This CAN be done by modifying the rule with a lot of negations.. it just quickly becomes very ugly.

Others have implemented this, so you have "override rules" - which behind the scenes builds those (quickly huge) negation filters - see https://www.lablabs.io/2020/04/19/how-we-solved-our-need-to-override-prometheus-alerts/

I would propose an override expr. support was added - so it would take all matches - and then check against override, before proceeding with generating an alert.

This would perform much better (I think - have not tested) than the huge negative filter expressions that this otherwise quicly becomes, and it would be much more readable config.

**Comment by roidelapluie** [comment]
On 10 Sep 02:26, Klavs Klavsen wrote:
> We want to monitor diskspace on ALL our servers - and alert on 80% used disk space.
> BUT we have certain partitions, where we want to alert differently on a few servers.
> 
> This CAN be done by modifying the rule with a lot of negations.. it just quickly becomes very ugly.
> 
> Others have implemented this, so you have "override rules" - which behind the scenes builds those (quickly huge) negation filters - see https://www.lablabs.io/2020/04/19/how-we-solved-our-need-to-override-prometheus-alerts/
> 
> I would propose an override expr. support was added - so it would take all matches - and then check against override, before proceeding with generating an alert.
> 
> This would perform much better (I think - have not tested) than the huge negative filter expressions that this otherwise quicly becomes, and it would be much more readable config.

Can you try such an approach?

- record: diskspace_override
  expr: vector(1)
  labels:
    mountpoint: /mnt/foo
- alert: disk full
  expr: disk_space_used > 0.8 unless on (mountpoint) diskspace_override


> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/prometheus/prometheus/issues/7923

-- 
 (o-    Julien Pivotto
 //\    Open-Source Consultant
 V_/_   Inuits - https://www.inuits.eu

**Comment by roidelapluie** [comment]
We have looked at this issue during our bug scrub. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by KlavsKlavsen** [comment]
@roidelapluie Thank you very much for suggesting a way this is actually supported. I could not find any example of this being possible already. I tried the approach you suggest - and it didn't work.. Did I do something wrong, or ?
```
    - record: haproxy_backend_response_time_override
      expr: vector(1)
      labels:
        instance: jaina.example.org
 
     - alert: haproxy_backend_response_time
      expr: irate(netdata_haproxy_b_rtime_milliseconds_average{chart="haproxy_via_url.brtime",family="backend"}[10m]) > 0.5 unless on (instance) haproxy_backend_response_time_override
```
