### ISSUE TITLE
Remote storage queue full Error occured.

### ISSUE THREAD

**Issue by tr2vil** [prometheus/prometheus#7945]
**What did you do?**
I was set remote_write config in the configuration, prometheus.yml, like this 
```
remote_write:
  - url: "http://{influxdb hostname}:8086/api/v1/prom/write?db=prometheus"
remote_read:
  - url: "http://{influxdb hostname}:8086/api/v1/prom/read?db=prometheus"
```

**What did you expect to see?**
Using prometheus and influxdb, I was expected prometheus scraped metric will store into the tsdb(influx).

**What did you see instead? Under which circumstances?**

In the test-bed, fewer target exporter, it is work well, but In the real circumstances, 3000 node_exporter targets and other exporters too, it is not work propely with this error log messages

```
level=warn ts=2020-09-17T06:03:33.194867868Z caller=queue_manager.go:230 component=remote queue="0:http://p8s-int-015.hanpda.com:8086/api/v1/prom/write?db=prometheus" msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
``` 

As a result, the metrics was inserted sparingly like this 
![image](https://user-images.githubusercontent.com/5829306/93427135-461b6600-f8f8-11ea-809d-3c2ec3fdb6ae.png)

I have no idea, which component, prometheus or influx, has problem. 

**Environment**

* System information:

   Linux 3.10.0-862.14.4.el7.x86_64 x86_64

* Prometheus version:

prometheus, version 2.4.3 (branch: HEAD, revision: 167a4b4e73a8eca8df648d2d2043e21bdb9a7449)
  build user:       root@1e42b46043e9
  build date:       20181004-08:42:02
  go version:       go1.11.1

* Prometheus configuration file:
```
remote_write:
  - url: "http://p8s-int-015.hanpda.com:8086/api/v1/prom/write?db=prometheus"
    #queue_config:
    #  capacity: 5000
    #  max_samples_per_send: 1000

remote_read:
  - url: "http://p8s-int-015.hanpda.com:8086/api/v1/prom/read?db=prometheus"
```

* Logs:
```
level=warn ts=2020-09-17T06:03:02.818522525Z caller=queue_manager.go:230 component=remote queue="0:http://p8s-int-015.hanpda.com:8086/api/v1/prom/write?db=prometheus" msg="Remote storage queue full, discarding sample. Multiple subsequent messages of this kind may be suppressed."
```
