### ISSUE TITLE
Add refresh_interval to static_configs

### ISSUE THREAD

**Issue by IgorOhrimenko** [prometheus/prometheus#7974]
## Proposal
**Use case. Why is this important?**
Add refresh_interval to static_configs.

Now the logic behind static_configs is as follows:
- if DNS is not available, then request a new IP
- never again refresh IP from DNS

Now I have done on dns_sd_configs with relabel_configs, but this method seems redundant to me, periodically re-reading the DNS in static_configs seems logical and simple to me. Or do how to re-read in nginx with command nginx -s reload. Prometheus currently only rereads DNS on restart.

 
```
- job_name: swarm
  dns_sd_configs:
  - names:
    - host.lan
    type: A
    port: 9100
  relabel_configs:
    - source_labels: [__meta_dns_name]
      replacement: $1:9100
      target_label: instance
```
