### ISSUE TITLE
rate [1m] and 1m scraping interval == no data

### ISSUE THREAD

**Issue by ldemailly** [prometheus/prometheus#8001]
**What did you do?**
helm install --namespace istio-system prometheus \
	 --set server.nodeSelector.node_type=unity-autoscaler \
	 --set server.fullnameOverride=prometheus \
	 --set server.service.servicePort=9090 \
	 prometheus-community/prometheus
(installs prom/prometheus:v2.20.1)

This is with istio grafana dashboard and kiali but is not specific to them

Look at any 1minute or rate [1m] metrics in query:
"no data"
 2+ minutes gives data

**What did you expect to see?**

data because with 1 min scrape there is data < 1min 99.99% of the time (avg scrape is 30s old from status url)
and even if there is no data I expect extrapolation from the last time there is data (wrong expectation?)

**What did you see instead? Under which circumstances?**

no data, always for [1m] rate

**Environment**

kubernetes 1.17, istio 1.7.3

* Prometheus version:

prom/prometheus:v2.20.1

* Prometheus configuration file:
```
# default config map, relevant part:
apiVersion: v1
data:
  alerting_rules.yml: |
    {}
  alerts: |
    {}
  prometheus.yml: |
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
```
