### ISSUE TITLE
prometheus pod CrashBackOff

### ISSUE THREAD

**Issue by lcfang** [prometheus/prometheus#8052]
**What did you do?**
Installed the prometheus with thanos-sidecar, thanos-query, and 100G pvc(using [longhorn](https://longhorn.io/docs) )
**What did you expect to see?**
all the prometheus pod running
**What did you see instead? Under which circumstances?**
I apply the yamls for deploying, they are  all running, but two days later, all the prometheus become CashBackOff with these errors:
```
# kubectl  get po -nmonitoring -owide
NAME                              READY   STATUS             RESTARTS   AGE   IP               NODE     NOMINATED NODE   READINESS GATES
prometheus-0                      1/2     CrashLoopBackOff   176        42h   10.233.64.113    node-1   <none>           <none>
prometheus-1                      1/2     CrashLoopBackOff   177        42h   10.233.65.145    node-2   <none>           <none>
prometheus-2                      1/2     CrashLoopBackOff   180        42h   10.233.66.152    node-3   <none>           <none>
```
**Environment**

* System information:

        Linux 4.4.230-1.el7.elrepo.x86_64 x86_64

* Prometheus version:

	v2.20.1(the image)

* Alertmanager version:

	no use

* Prometheus configuration file:
```
 args:
            - "--config.file=/etc/prometheus-shared/prometheus.yaml"
            - "--storage.tsdb.path=/prometheus/"
            - "--storage.tsdb.retention.time=15d"
            - "--web.enable-admin-api"
            - "--web.enable-lifecycle"
            - "--storage.tsdb.no-lockfile"
# cat prome-server-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yaml.tmpl: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      external_labels:
        cluster: prometheus-ha
        replica: $(POD_NAME)

    rule_files:
      - /etc/prometheus/rules/*rules.yaml

    alerting:
      alert_relabel_configs:
      - regex: replica
        action: labeldrop

      alertmanagers:
        - scheme: http
          path_prefix: /
          static_configs:
            - targets: ['alertmanager:9093']

    scrape_configs:
    - job_name: kubernetes-nodes-cadvisor
      scrape_interval: 10s
      scrape_timeout: 10s
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      metric_relabel_configs:
        - action: replace
          source_labels: [id]
          regex: '^/machine\.slice/machine-rkt\\x2d([^\\]+)\\.+/([^/]+)\.service$'
          target_label: rkt_container_name
          replacement: '${2}-${1}'
        - action: replace
          source_labels: [id]
          regex: '^/system\.slice/(.+)\.service$'
          target_label: systemd_service_name
          replacement: '${1}'
```

* Alertmanager configuration file:
no use

* Logs:
```
# kubectl logs prometheus-0 -nmonitoring -c prometheus
level=info ts=2020-10-14T01:34:29.190Z caller=main.go:343 msg="Starting Prometheus" version="(version=2.20.1, branch=HEAD, revision=983ebb4a513302315a8117932ab832815f85e3d2)"
level=info ts=2020-10-14T01:34:29.190Z caller=main.go:344 build_context="(go=go1.14.6, user=root@7cbd4d1c15e0, date=20200805-17:26:58)"
level=info ts=2020-10-14T01:34:29.190Z caller=main.go:345 host_details="(Linux 4.4.230-1.el7.elrepo.x86_64 #1 SMP Tue Jul 7 18:27:40 EDT 2020 x86_64 prometheus-0 (none))"
level=info ts=2020-10-14T01:34:29.191Z caller=main.go:346 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-14T01:34:29.191Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-10-14T01:34:29.195Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/prometheus/queries.active err="open /prometheus/queries.active: input/output error"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffc0f80fc9d, 0xc, 0x14, 0x30898a0, 0xc0001a6c00, 0x30898a0)
        /app/promql/query_logger.go:117 +0x4cd
main.main()
        /app/cmd/prometheus/main.go:374 +0x4f08

# kubectl logs prometheus-1 -nmonitoring -c prometheus
level=info ts=2020-10-14T01:36:08.430Z caller=main.go:343 msg="Starting Prometheus" version="(version=2.20.1, branch=HEAD, revision=983ebb4a513302315a8117932ab832815f85e3d2)"
level=info ts=2020-10-14T01:36:08.430Z caller=main.go:344 build_context="(go=go1.14.6, user=root@7cbd4d1c15e0, date=20200805-17:26:58)"
level=info ts=2020-10-14T01:36:08.431Z caller=main.go:345 host_details="(Linux 4.4.230-1.el7.elrepo.x86_64 #1 SMP Tue Jul 7 18:27:40 EDT 2020 x86_64 prometheus-1 (none))"
level=info ts=2020-10-14T01:36:08.431Z caller=main.go:346 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-14T01:36:08.431Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-10-14T01:36:08.433Z caller=main.go:684 msg="Starting TSDB ..."
level=info ts=2020-10-14T01:36:08.433Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:553 msg="Stopping scrape discovery manager..."
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:567 msg="Stopping notify discovery manager..."
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:589 msg="Stopping scrape manager..."
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:563 msg="Notify discovery manager stopped"
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:549 msg="Scrape discovery manager stopped"
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:583 msg="Scrape manager stopped"
level=info ts=2020-10-14T01:36:08.464Z caller=manager.go:888 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-10-14T01:36:08.464Z caller=manager.go:898 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-10-14T01:36:08.464Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-10-14T01:36:08.464Z caller=main.go:755 msg="Notifier manager stopped"
level=error ts=2020-10-14T01:36:08.465Z caller=main.go:764 err="opening storage failed: list block dirs in \"/prometheus/\": lstat /prometheus//01EMEW421S1JNENM1AWJAWS0G7: bad message"

# kubectl logs prometheus-2 -nmonitoring -c prometheus
level=info ts=2020-10-14T01:34:40.537Z caller=main.go:343 msg="Starting Prometheus" version="(version=2.20.1, branch=HEAD, revision=983ebb4a513302315a8117932ab832815f85e3d2)"
level=info ts=2020-10-14T01:34:40.537Z caller=main.go:344 build_context="(go=go1.14.6, user=root@7cbd4d1c15e0, date=20200805-17:26:58)"
level=info ts=2020-10-14T01:34:40.537Z caller=main.go:345 host_details="(Linux 4.4.230-1.el7.elrepo.x86_64 #1 SMP Tue Jul 7 18:27:40 EDT 2020 x86_64 prometheus-2 (none))"
level=info ts=2020-10-14T01:34:40.537Z caller=main.go:346 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-14T01:34:40.537Z caller=main.go:347 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-10-14T01:34:40.540Z caller=main.go:684 msg="Starting TSDB ..."
level=info ts=2020-10-14T01:34:40.540Z caller=web.go:524 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-10-14T01:34:40.540Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1602488475657 maxt=1602504000000 ulid=01EMEW2WYCTTBGEHR0VX302CH2
level=info ts=2020-10-14T01:34:40.540Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1602568800000 maxt=1602576000000 ulid=01EMGK04WWF863JNBKF5XPQ38T
level=info ts=2020-10-14T01:34:40.540Z caller=repair.go:59 component=tsdb msg="Found healthy block" mint=1602504000000 maxt=1602568800000 ulid=01EMGKCNPYCZVD83N7AR18CJ3R
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:553 msg="Stopping scrape discovery manager..."
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:567 msg="Stopping notify discovery manager..."
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:589 msg="Stopping scrape manager..."
level=info ts=2020-10-14T01:34:40.549Z caller=manager.go:888 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-10-14T01:34:40.549Z caller=manager.go:898 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-10-14T01:34:40.549Z caller=notifier.go:601 component=notifier msg="Stopping notification manager..."
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:755 msg="Notifier manager stopped"
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:549 msg="Scrape discovery manager stopped"
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:563 msg="Notify discovery manager stopped"
level=info ts=2020-10-14T01:34:40.549Z caller=main.go:583 msg="Scrape manager stopped"
level=error ts=2020-10-14T01:34:40.549Z caller=main.go:764 err="opening storage failed: /prometheus/chunks_head/000024: invalid magic number 0"
```
I am not sure the reason is prometheus or longhorn? or is prometheus not support longhorn?
