### ISSUE TITLE
Kubernetes pod service discovery incorrectly creates targets for all containers within a pod when __meta_kubernetes_pod_container_name is relabeled

### ISSUE THREAD

**Issue by thom-sd** [prometheus/prometheus#8069]
**What did you do?**
Added the following to my prometheus.yml with kubernetes pod SD:
```
      - action: replace
        source_labels: [__meta_kubernetes_pod_container_name]
        target_label: pod_container_name
```

**What did you expect to see?**
Metrics only from the relevant pod/container with pod_container_name set to the name of the only container listening to the target port.

**What did you see instead? Under which circumstances?**
3 Sets of identical metrics, with pod_container_name set to the names of each of the containers within the pod. (Only one of those containers has the target port listed).

The pod was the kube-dns pod with containers named kubedns, dnsmasq and sidecar. Out of those, only kubedns has port 10055 listed.

**Environment**
Kubernetes 1.16.13 cluster on AWS, created with kops

* System information:
Linux 4.9.0-13-amd64 x86_64

* Prometheus version:
version="(version=2.22.0, branch=HEAD, revision=0a7fdd3b76960808c3a91d92267c3d815c1bc354)"

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
scrape_configs:
- job_name: 'k8s-pods'
  tls_config:
    insecure_skip_verify: true
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    regex: true
  - action: replace
    source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
    target_label: __scheme__
    regex: (https?)
  - action: replace
    source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    target_label: __metrics_path__
    regex: (.+)
  - action: replace
    source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__

  - action: replace
    source_labels: [__meta_kubernetes_pod_container_name]
    target_label: pod_container_name
```

* Logs:
```
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:315 msg="No time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:353 msg="Starting Prometheus" version="(version=2.22.0, branch=HEAD, revision=0a7fdd3b76960808c3a91d92267c3d815c1bc354)"
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:358 build_context="(go=go1.15.3, user=root@6321101b2c50, date=20201015-12:29:59)"
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:359 host_details="(Linux 4.9.0-13-amd64 #1 SMP Debian 4.9.228-1 (2020-07-05) x86_64 prometheus-deployment-6b99796bdb-khhfk (none))"
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:360 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-10-16T03:03:05.770Z caller=main.go:361 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-10-16T03:03:05.773Z caller=web.go:516 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-10-16T03:03:05.773Z caller=main.go:712 msg="Starting TSDB ..."
level=info ts=2020-10-16T03:03:05.777Z caller=head.go:642 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2020-10-16T03:03:05.777Z caller=head.go:656 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=3.387µs
level=info ts=2020-10-16T03:03:05.777Z caller=head.go:662 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2020-10-16T03:03:05.777Z caller=head.go:714 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2020-10-16T03:03:05.777Z caller=head.go:719 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=39.32µs wal_replay_duration=275.817µs total_replay_duration=336.297µs
level=info ts=2020-10-16T03:03:05.779Z caller=main.go:732 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-10-16T03:03:05.779Z caller=main.go:735 msg="TSDB started"
level=debug ts=2020-10-16T03:03:05.779Z caller=main.go:736 msg="TSDB options" MinBlockDuration=2h MaxBlockDuration=1d12h MaxBytes=0B NoLockfile=false RetentionDuration=15d WALSegmentSize=0B AllowOverlappingBlocks=false WALCompression=true
level=info ts=2020-10-16T03:03:05.779Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-10-16T03:03:05.780Z caller=kubernetes.go:263 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=debug ts=2020-10-16T03:03:05.781Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=kubernetes/0 subs=[k8s-pods]
level=info ts=2020-10-16T03:03:05.781Z caller=main.go:892 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=2.201419ms remote_storage=1.695µs web_handler=978ns query_engine=963ns scrape=270.014µs scrape_sd=1.434526ms notify=1.05µs notify_sd=2.084µs rules=791ns
level=info ts=2020-10-16T03:03:05.781Z caller=main.go:684 msg="Server is ready to receive web requests."
level=debug ts=2020-10-16T03:03:05.782Z caller=klog.go:55 component=k8s_client_runtime func=Verbose.Infof msg="Starting reflector *v1.Pod (10m0s) from /app/discovery/kubernetes/kubernetes.go:450"
level=debug ts=2020-10-16T03:03:05.782Z caller=klog.go:55 component=k8s_client_runtime func=Verbose.Infof msg="Listing and watching *v1.Pod from /app/discovery/kubernetes/kubernetes.go:450"
level=debug ts=2020-10-16T03:03:05.789Z caller=klog.go:72 component=k8s_client_runtime func=Infof msg="GET https://100.64.0.1:443/api/v1/pods?limit=500&resourceVersion=0 200 OK in 7 milliseconds"
level=debug ts=2020-10-16T03:03:05.813Z caller=klog.go:72 component=k8s_client_runtime func=Infof msg="GET https://100.64.0.1:443/api/v1/pods?allowWatchBookmarks=true&resourceVersion=86637&timeout=8m1s&timeoutSeconds=481&watch=true 200 OK in 1 milliseconds"
level=debug ts=2020-10-16T03:03:05.882Z caller=klog.go:55 component=k8s_client_runtime func=Verbose.Infof msg="caches populated"
```
