### ISSUE TITLE
Error using Eureka SD with basic_auth

### ISSUE THREAD

**Issue by chen-jie** [prometheus/prometheus#8079]
**What did you do?**

I am trying to use Prometheus 2.22.0 with Spring Cloud Netflix Eureka SD.

I have to use basic_auth because it requires. [jhipster-registry](https://github.com/jhipster/jhipster-registry)

I followed the documentation [eureka_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#eureka_sd_config)  but it doesn't work.

**What did you expect to see?**

Successfully refreshed targets from Eureka SD.

**What did you see instead? Under which circumstances?**

with configuration 1:
```
  - job_name: 'eureka'

    eureka_sd_configs:

      - server: http://localhost:8761/eureka
      
      - basic_auth:

          username: admin

          password: admin
```
i got this , and prometheus fails to start 
```
level=error ts=2020-10-19T08:42:08.871Z caller=main.go:290 msg="Error loading config (--config.file=prometheus.yml)" err="parsing YAML file prometheus.yml: eureka_sd: empty or null eureka server"```
```

with configuration 2:

```
  - job_name: 'eureka'

    eureka_sd_configs:

      - server: http://localhost:8761/eureka
      
```
this time prometheus starts successfully but it can't get anything from eureka because authorization is needed 
```
level=error ts=2020-10-19T09:20:18.799Z caller=refresh.go:79 component="discovery manager scrape" discovery=eureka msg="Unable to refresh target groups" err="non 2xx status '401' response during eureka service discovery"
```
**Environment**

* System information:

	Linux 3.10.0-862.el7.x86_64 x86_64

* Prometheus version:
  ```
  prometheus, version 2.22.0 (branch: HEAD, revision: 0a7fdd3b76960808c3a91d92267c3d815c1bc354)
  build user:       root@6321101b2c50
  build date:       20201015-12:34:05
  go version:       go1.15.3
  platform:         linux/386

**Comment by roidelapluie** [comment]
Please use:

```
   - job_name: 'eureka'
     eureka_sd_configs:
       - server: http://localhost:8761/eureka
         basic_auth:
           username: admin
           password: admin
```
You had an extra `-`
