### ISSUE TITLE
promtool: Tests do not test full input series

### ISSUE THREAD

**Issue by dgl** [prometheus/prometheus#8105]
In #8096 I wrote: [...]"tests would catch errors evaluating rules elsewhere in the file". Digging into that a bit further there's a rather contrived bug lurking:

```yaml
rule_files:
  - bad-rules-error.yml

tests:
  - interval: 1m
    input_series:
      - series: 'join_1{a="1",b="2"}'
        values: 'stale 1'
      - series: 'join_2{a="1",b="3"}'
        values: 'stale 2'
      - series: 'join_2{a="1",b="4"}'
        values: 'stale 3'

    promql_expr_test:
      - eval_time: 0m
        expr: 1
        exp_samples:
          - value: 1
```

Use this with the rules added under cmd/promtool/testdata in commit 4983ac9, it passes; but change `eval_time` to 1m and it fails.

This means unless users have an eval_time specified in their tests that is at the end of their input series, they could miss errors in their rules that the input data would trigger. Given how PromQL works there aren't too many errors that manifest in the middle of a timeseries and I had to force it here with `stale`. However it seems like tests should catch the rare issue like this.

Essentially `maxEvalTime` should also take `input_series` values into account. This is a little tricky as the parsing for these strings is outside promtool itself.
