### ISSUE TITLE
Prometheus 2.19.0-2.20.0 scrapes hanging on _all_ targets, some time after network partition of a _single_ host

### ISSUE THREAD

**Issue by gburek-fastly** [prometheus/prometheus#8143]
This is a bug report for an issue we encountered with Prometheus versions 2.19.0, 2.19.1, 2.19.2 and 2.20.0 It appears to have been fixed in 2.21.0 and 2.22.0. However, we wish to leave a record of this error in case others may encounter something similar. 

**What did you do?**

Upgraded Prometheus from 2.18.1 to 2.19.0. Saw metrics gaps and frozen scrapes for targets using TLS client certs for scrapes shortly after a single host began timing out due to hardware, load or network reasons. 

Freeze behavior was present in 2.19.0, 2.19.1, 2.19.2 and 2.20.0. Unable to reproduce in 2.18.2, 2.21.0 and 2.22.0

**What did you expect to see?**

Scrape timeout setting being honored and a single host's scrape timeouts not interrupting the scrapes of other targets and hosts. 

**What did you see instead? Under which circumstances?**

Starting with prometheus 2.19.0, we saw a rare and odd behavior where a single unresponsive host among Prometheus's target list would initially manifest as all scrapes against that host timing out at the configured scrape_timeout of 10s, but, 7-15m after the single host went offline, *all* scrapes on that interval and type for *all hosts* would freeze for far longer than the scrape_timeout. In some environments, we observed peak scrape_duration_seconds of ~32s and other envs, ~550s. To a user of our Prometheus infra, this manifested as a 30s-10m gap in data collected. 

We were able to trigger this fault with a `sudo iptables  -I INPUT -s x.x.x.x -j DROP` on the Prometheus host and by monitoring `scrape_duration_seconds`, be able to see the initial timeout for targets on the blocked host, with a long gap before scrapes timed out and were able to continue:

![image](https://user-images.githubusercontent.com/49920412/97238653-243eba00-17a7-11eb-9451-fad25f491e05.png) 

In the above screenshot, the small bump at 21:47 was a 10s timeout for all 'targets' against a single host going offline as the iptables rule was applied. The large cliff at 23:54 is the freeze of all scrapes using tls_config with client certs for far longer than the configured scrape_timeout. Scrapes succeeded and data returned at 00:03 and the iptables rule was removed at 00:05. 

Of note, targets that used https, without a client cert and targets over http against local exporters were unaffected by this freeze behavior, but jobs with `tls_config` froze. In the attached config, the `switches`, `ipmi_exporter`, `snmp_exporter`, and `blackbox` jobs were not interrupted, but the `promsd` jobs were. 

We were able to downgrade our fleet to 2.18.2 to stop production freezes from occurring. Testing in a semi-production env with the iptables reproduction showed the freeze was present in 2.19.0, 2.19.1, 2.19.2 and 2.20.0. We were unable to reproduce in 2.21.0 and 2.22.0 and the fleet running 2.22.0 has not encountered any other freezes or hangs in scraping either through iptables triggers or hardware failures. 

Unfortunately, we were unable to reproduce this bug on a laptop or by using docker on a single host for a local reproduction case. Only Prometheus, running on hardware or on a gcp instance, scraping remote targets on other hosts/instances, exhibited this freeze behavior.

**Environment**

* System information:

Linux 4.15.0-1086-gcp x86_64

* Prometheus version:
```
prometheus, version 2.19.0 (branch: HEAD, revision: 5d7e3e970602c755855340cb190a972cebdd2ebf)
  build user:       root@d4cf5c7e268d
  build date:       20200609-10:29:59
  go version:       go1.14.4

prometheus, version 2.19.1 (branch: HEAD, revision: eba3fdcbf0d378b66600281903e3aab515732b39)
  build user:       root@62700b3d0ef9
  build date:       20200618-16:35:26
  go version:       go1.14.4

prometheus, version 2.20.0 (branch: HEAD, revision: e5a06b483527d4fe0704b8fa3a2b475b661c526f)
  build user:       root@ac954b6d5c6e
  build date:       20200722-18:51:45
  go version:       go1.14.6
```
* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    replica: xxx
    site: xxx
alerting:
  alert_relabel_configs:
  - separator: ;
    regex: ^replica$
    replacement: $1
    action: labeldrop
  alertmanagers:
  - tls_config:
      ca_file: /etc/prometheus/ca.crt
      cert_file: /etc/prometheus/alertmanager_client.crt
      key_file: /etc/prometheus/alertmanager_client.key
      server_name: alertmanager
      insecure_skip_verify: false
    scheme: https
    path_prefix: /alertmanager
    timeout: 10s
    api_version: v1
    static_configs:
    - targets:
      - x.x.x.x
rule_files:
- /var/db/prometheus/recording_rules/*.yml
- /var/db/prometheus/alerting_rules/*.yml

scrape_configs:
- job_name: switches
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - xx.xx.xx.xx
    labels:
      hostname: xxx
      site: xxx

- job_name: blackbox
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [module]
    separator: ;
    regex: (.*)
    target_label: __param_module
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 127.0.0.1:9115
    action: replace
  file_sd_configs:
  - files:
    - /etc/prometheus/blackbox/blackbox_targets.yml
    refresh_interval: 5m
- job_name: snmp_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /snmp
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [module]
    separator: ;
    regex: (.*)
    target_label: __param_module
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 127.0.0.1:9116
    action: replace
  file_sd_configs:
  - files:
    - /etc/prometheus/snmp/snmp_targets.yml
    refresh_interval: 5m
- job_name: ipmi_exporter
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /ipmi
  scheme: http
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [module]
    separator: ;
    regex: (.*)
    target_label: __param_module
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: 127.0.0.1:9290
    action: replace
  file_sd_configs:
  - files:
    - /etc/prometheus/ipmi/ipmi_targets.yml
    refresh_interval: 5m

- job_name: promsd
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: https
  tls_config:
    ca_file: /etc/prometheus/ca.crt
    cert_file: /etc/prometheus/promsd_exporter_client.crt
    key_file: /etc/prometheus/promsd_exporter_client.key
    server_name: promsd_exporter
    insecure_skip_verify: false
  file_sd_configs:
  - files:
    - /etc/prometheus/file_sd_config.json
    refresh_interval: 1m
```
