### ISSUE TITLE
Prometheus is failing with connection refused error

### ISSUE THREAD

**Issue by munjalpatel** [prometheus/prometheus#8165]
**What did you do?**

Create the following `prometheus.yaml` file:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
  labels:
    role: openfaas-system
    access: openfaas-system
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  labels:
    istio-injection: enabled
    role: openfaas-fn
---
# Source: openfaas/templates/psp.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
    name: openfaas-psp
    labels:
        app: openfaas
        chart: openfaas-6.0.4
        heritage: Helm
        release: openfaas
    annotations:
        seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
    privileged: false
    hostIPC: false
    hostNetwork: false
    hostPID: false
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    allowedCapabilities:
        - NET_ADMIN
        - NET_RAW
    fsGroup:
        rule: RunAsAny
    hostPorts:
        - max: 65535
          min: 1
    runAsUser:
        rule: RunAsAny
    seLinux:
        rule: RunAsAny
    supplementalGroups:
        rule: RunAsAny
    volumes:
        - '*'
---
# Source: openfaas/templates/prometheus-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-prometheus
  namespace: "openfaas"
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
---
# Source: openfaas/templates/alertmanager-cfg.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: alertmanager-config
    heritage: Helm
    release: openfaas
  name: alertmanager-config
  namespace: "openfaas"
data:
  alertmanager.yml: |
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 30s
      receiver: scale-up
      routes:
      - match:
          service: gateway
          receiver: scale-up
          severity: major

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'scale-up'
      webhook_configs:
        - url: http://gateway.openfaas:8080/system/alert
          send_resolved: true
          http_config:
            basic_auth:
              username: admin
              password_file: /var/secrets/basic-auth-password
---
# Source: openfaas/templates/prometheus-cfg.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus-config
    heritage: Helm
    release: openfaas
  name: prometheus-config
  namespace: "openfaas"
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'faas-monitor'

    rule_files:
        - 'alert.rules.yml'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-pods'
        scrape_interval: 5s
        honor_labels: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - openfaas
                - openfaas-fn
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

  alert.rules.yml: |
    groups:
      - name: openfaas
        rules:
        - alert: service_down
          expr: up == 0
        - alert: APIHighInvocationRate
          expr: sum(rate(gateway_function_invocation_total{code="200"}[10s])) BY (function_name) > 5
          for: 5s
          labels:
            service: gateway
            severity: major
          annotations:
            description: High invocation total on "{{$labels.function_name}}"
            summary: High invocation total on "{{$labels.function_name}}"
---
# Source: openfaas/templates/prometheus-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openfaas-prometheus
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
rules:
- apiGroups: [""]
  resources:
    - services
    - endpoints
    - pods
  verbs: ["get", "list", "watch"]
---
# Source: openfaas/templates/psp.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: openfaas-psp
    labels:
        app: openfaas
        chart: openfaas-6.0.4
        heritage: Helm
        release: openfaas
rules:
    - apiGroups: ['policy']
      resources: ['podsecuritypolicies']
      verbs:     ['use']
      resourceNames:
          - openfaas-psp
---
# Source: openfaas/templates/prometheus-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-prometheus
  namespace: "openfaas"
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-prometheus
subjects:
- kind: ServiceAccount
  name: openfaas-prometheus
  namespace: "openfaas"
---
# Source: openfaas/templates/prometheus-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-prometheus
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-prometheus
subjects:
- kind: ServiceAccount
  name: openfaas-prometheus
  namespace: "openfaas"
---
# Source: openfaas/templates/psp.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: openfaas-psp
    namespace: "openfaas"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: openfaas-psp
subjects:
    # bind the PSP cluster role to all service accounts in the OF namespace
    - apiGroup: rbac.authorization.k8s.io
      kind: Group
      name: system:serviceaccounts:openfaas
      namespace: openfaas
---
# Source: openfaas/templates/alertmanager-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: alertmanager
    heritage: Helm
    release: openfaas
  name: alertmanager
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 9093
      protocol: TCP
  selector:
    app: alertmanager
---
# Source: openfaas/templates/prometheus-svc.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
  name: prometheus
  namespace: "openfaas"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
  selector:
    app: prometheus
---
# Source: openfaas/templates/alertmanager-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: alertmanager
    heritage: Helm
    release: openfaas
  name: alertmanager
  namespace: "openfaas"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
      annotations:
        sidecar.istio.io/inject: "true"
        checksum/alertmanager-config: "d11068803eeb977273e116dc044c25fb39b03295446b1251b7f1fbc26104ed04"
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.18.0
        imagePullPolicy: Always
        command:
          - "alertmanager"
          - "--config.file=/alertmanager.yml"
          - "--storage.path=/alertmanager"
          - "--cluster.listen-address="
        livenessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          timeoutSeconds: 30
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
        - name: auth
          readOnly: true
          mountPath: "/var/secrets"
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644
        - name: auth
          secret:
            secretName: basic-auth
---
# Source: openfaas/templates/prometheus-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: prometheus
    heritage: Helm
    release: openfaas
  name: prometheus
  namespace: "openfaas"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
      annotations:
        sidecar.istio.io/inject: "true"
        checksum/prometheus-config: "833784fe79824d5a9adfaf93561abc4dabbf746669235c5ac020e85a9a563510"
    spec:
      serviceAccountName: openfaas-prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.11.0
        command:
          - "prometheus"
          - "--config.file=/etc/prometheus/prometheus.yml"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          timeoutSeconds: 30
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          subPath: prometheus.yml
        - mountPath: /etc/prometheus/alert.rules.yml
          name: prometheus-config
          subPath: alert.rules.yml
        - mountPath: /prometheus/data
          name: prom-data
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
                mode: 0644
              - key: alert.rules.yml
                path: alert.rules.yml
                mode: 0644
        - name: prom-data
          emptyDir: {}
---
# Source: openfaas/templates/istio-mtls.yaml
# enforce mTLS to openfaas control plane
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: default
    namespace: openfaas
spec:
    host: "*.openfaas.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: ISTIO_MUTUAL
---
# Source: openfaas/templates/istio-mtls.yaml
# enforce mTLS to functions
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: default
    namespace: "openfaas-fn"
spec:
    host: "*.openfaas-fn.svc.cluster.local"
    trafficPolicy:
        tls:
            mode: ISTIO_MUTUAL
---
# Source: openfaas/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth
  namespace: "openfaas"
  labels:
    app: openfaas
    chart: openfaas-6.0.4
    component: gateway
    heritage: Helm
    release: openfaas
  annotations:
    "helm.sh/hook": "pre-install"
data:
  basic-auth-user: "YWRtaW4="
  # kubectl -n openfaas get secret basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode
  basic-auth-password: "dEtuRzQ5cVNqYzFP"
```

Run `kubectl apply -f ./prometheus.yaml` and wait for `Prometheus` pod to come online.

**What did you expect to see?**
No error message in the logs of the `Prometheus` pod.

**What did you see instead? Under which circumstances?**
Connection refused error in logs of the `Prometheus` pod.

Notice errors related to `connection refused`

**Environment**

* System information:
```
Linux 4.15.0-1096-azure x86_64
```
* Prometheus version:
```
prometheus, version 2.11.0 (branch: HEAD, revision: 4ef66003d9855ed2b7a41e987b33828ec36db34d)
    build user:       root@0dc27cf95f36
    build date:       20190709-09:54:35
    go version:       go1.12.7
```

* Alertmanager version:
```
alertmanager, version 0.18.0 (branch: HEAD, revision: 1ace0f76b7101cccc149d7298022df36039858ca)
  build user:       root@868685ed3ed0
  build date:       20190708-14:31:49
  go version:       go1.12.6
```

* Prometheus configuration file:
**prometheus.yml**
```yaml
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'faas-monitor'

    rule_files:
        - 'alert.rules.yml'

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubernetes-pods'
        scrape_interval: 5s
        honor_labels: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - openfaas
                - openfaas-fn
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093
```
**alert.rules.yml**
```yaml
    groups:
      - name: openfaas
        rules:
        - alert: service_down
          expr: up == 0
        - alert: APIHighInvocationRate
          expr: sum(rate(gateway_function_invocation_total{code="200"}[10s])) BY (function_name) > 5
          for: 5s
          labels:
            service: gateway
            severity: major
          annotations:
            description: High invocation total on "{{$labels.function_name}}"
            summary: High invocation total on "{{$labels.function_name}}"
```

* Alertmanager configuration file:
```yaml
route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 30s
      receiver: scale-up
      routes:
      - match:
          service: gateway
          receiver: scale-up
          severity: major

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'scale-up'
      webhook_configs:
        - url: http://gateway.openfaas:8080/system/alert
          send_resolved: true
          http_config:
            basic_auth:
              username: admin
              password_file: /var/secrets/basic-auth-password
```

* Logs:
```
level=info ts=2020-11-09T19:33:49.233Z caller=main.go:293 msg="no time or size retention was set so using the default time retention" duration=15d
level=info ts=2020-11-09T19:33:49.233Z caller=main.go:329 msg="Starting Prometheus" version="(version=2.11.0, branch=HEAD, revision=4ef66003d9855ed2b7a41e987b33828ec36db34d)"
level=info ts=2020-11-09T19:33:49.233Z caller=main.go:330 build_context="(go=go1.12.7, user=root@0dc27cf95f36, date=20190709-09:54:35)"
level=info ts=2020-11-09T19:33:49.233Z caller=main.go:331 host_details="(Linux 4.15.0-1096-azure #106~16.04.1-Ubuntu SMP Thu Sep 10 18:51:54 UTC 2020 x86_64 prometheus-64d5877fc9-s5nwq (none))"
level=info ts=2020-11-09T19:33:49.234Z caller=main.go:332 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-11-09T19:33:49.234Z caller=main.go:333 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2020-11-09T19:33:49.432Z caller=main.go:652 msg="Starting TSDB ..."
level=info ts=2020-11-09T19:33:49.432Z caller=web.go:448 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-11-09T19:33:49.935Z caller=main.go:667 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-11-09T19:33:50.032Z caller=main.go:668 msg="TSDB started"
level=info ts=2020-11-09T19:33:50.032Z caller=main.go:738 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-11-09T19:33:50.132Z caller=kubernetes.go:192 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=error ts=2020-11-09T19:33:50.333Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:283: Failed to list *v1.Pod: Get https://10.10.10.1:443/api/v1/namespaces/openfaas/pods?limit=500&resourceVersion=0: dial tcp 10.10.10.1:443: connect: connection refused"
level=info ts=2020-11-09T19:33:50.433Z caller=main.go:766 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2020-11-09T19:33:50.433Z caller=main.go:621 msg="Server is ready to receive web requests."
level=error ts=2020-11-09T19:33:50.532Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:283: Failed to list *v1.Pod: Get https://10.10.10.1:443/api/v1/namespaces/openfaas-fn/pods?limit=500&resourceVersion=0: dial tcp 10.10.10.1:443: connect: connection refused"
level=error ts=2020-11-09T19:33:51.334Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:283: Failed to list *v1.Pod: Get https://10.10.10.1:443/api/v1/namespaces/openfaas/pods?limit=500&resourceVersion=0: dial tcp 10.10.10.1:443: connect: connection refused"
level=error ts=2020-11-09T19:33:51.533Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:283: Failed to list *v1.Pod: Get https://10.10.10.1:443/api/v1/namespaces/openfaas-fn/pods?limit=500&resourceVersion=0: dial tcp 10.10.10.1:443: connect: connection refused"
```
