### ISSUE TITLE
Implement service discovery directly from Docker (not Docker swarm)

### ISSUE THREAD

**Issue by vitalets** [prometheus/prometheus#8173]
## Proposal
I'm running single server with several Docker containers. They all are small applications (chat bots) that I'd like to monitor with Prometheus. As there are many containers, managing Prometheus static config is tedious.
It would be great if Prometheus can listen to local docker.sock and discover newly added containers on the fly by label.
E.g.:
```yml
scrape_configs:
  - job_name: docker
    docker_sd_config:
      host: /var/run/docker.sock
      labels:
          - scrapable

```

Is it possible to add?
