### ISSUE TITLE
Label is not beeing removed by setting value to empty string when using regex capture group as target_label

### ISSUE THREAD

**Issue by iceman91176** [prometheus/prometheus#8186]
**What did you do?**
We want remove labels based on values present in service-discovery. We are using a technique like the one described here (https://www.robustperception.io/extracting-full-labels-from-consul-tags) to extract all labels that should be removed fom a comma-separated-string. This string comes from our consul service-discovery.  We apply those relabeling in metric_relabel_configs. To remove the labels we set the value to ''
```
    metric_relabel_configs:
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){0}([^,]+).*'
      replacement: ''
      target_label: ${1}
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){1}([^,]+).*'
      replacement: ''
      target_label: ${1}
   and so on
```

**What did you expect to see?**
All labels that are listed in the string should be removed.

**What did you see instead? Under which circumstances?**
Labels are still there. So i tried to narrow it down. If not setting the replacement value to an empty-string, all labels in the "list" get that value.

```
    metric_relabel_configs:
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){0}([^,]+).*'
      replacement: 'static'
      target_label: ${1}
```

If not using the regex capture-group in the target-label, but a hardcoded label, it removes the value. E.g. if one of the labels in our list is named funnylabel and we do it like this

```
    - replacement: ''
      regex: '.*(funnylabel).*'
      target_label: funnylabel
      source_labels: [labeldrop]
```

then the funnylabel gets removed.

So it looks like there is a problem when using regex-capture-goups and an empty replacement-string

**Environment**

* System information:

	Linux 3.10.0-862.el7.x86_64

* Prometheus version:

```
prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
  build user:       root@516b109b1732
  build date:       20201105-14:02:25
  go version:       go1.15.3
  platform:         linux/amd64
```

* Prometheus configuration file:
```
  - job_name: 'ping_exporter'
    scrape_interval: 10s
    metrics_path: /ping
    consul_sd_configs:
      - server: '***'
        token: '***'
        datacenter: ***
        scheme: https
        tags:
          - ping_exporter
    relabel_configs:
    - action: labelmap
      regex: __meta_consul_service_metadata_label_(.+)
    - source_labels: [__meta_consul_service_metadata_labeldrop]
      target_label: 'labeldrop'
    - source_labels: [__meta_consul_service_address,__meta_consul_address]
      action: replace
      separator: ";"
      regex: ;(.*)
      replacement: $1
      target_label: __meta_consul_service_address
    - source_labels: [__meta_consul_service_address]
      target_label: __param_target
    - source_labels: [__meta_consul_service_metadata_job]
      target_label: job
# set Metrics-Path default
    - target_label: __tmp_metrics_path
      replacement: /ping
# overwirte with values from consul sd
    - source_labels: [__meta_consul_service_metadata_metrics_path]
      target_label: __tmp_metrics_path
      regex: (\/.*)
# Relabel metric path
    - source_labels: [__tmp_metrics_path]
      target_label: __metrics_path__
    - target_label: exporter
      replacement: ping_exporter
    - source_labels: [__meta_consul_service_metadata_exporter]
      replacement: '${1}'
      target_label: __address__
    metric_relabel_configs:
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){0}([^,]+).*'
      replacement: ''
      target_label: ${1}
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){1}([^,]+).*'
      replacement: ''
      target_label: ${1}
    - source_labels: [labeldrop]
      regex: '(?:[^,]+,){2}([^,]+).*'
      replacement: ''
      target_label: ${1}
    - action: labeldrop
      regex: 'labeldrop'

```

* Logs:
```
nothing related to problem logged
```

Thank you for looking at this
