### ISSUE TITLE
Configuration reload bug

### ISSUE THREAD

**Issue by jeeyshe** [prometheus/prometheus#8202]
**What did you do?**

I used "POST /-/reload" api or "SIGHUP" signal to host reload prometheus's configuration, but failed. I tried some cases, It only occurred when I want to cleanup target, and only in prometheus2.x version. The detail below.

**What did you expect to see?**

Expect to see prometheus's job has a empty target list.

**What did you see instead? Under which circumstances?**

Please see the configuration below.

**Environment**

* System information:

	Linux 3.10.0-862.el7.x86_64 x86_64

* Prometheus version:

	all 2.x version

* Alertmanager version:

	Only prometheus, nothing to do with Alertmanager.

* Prometheus configuration file:
```
# 全局配置
global:
  evaluation_interval: 15s
  scrape_timeout: 50s
  external_labels:
    monitor: QFlame
  scrape_interval: 1m

# 告警规则
rule_files:
  - cloud.rule.yml
  - host.rule.yml
  - oracle.rule.yml
  - snmp.rule.yml
  - vm.rule.yml
  - redfish.rule.yml
  - bulkping.rule.yml
  - hardware.rule.yml
  - etcd.rule.yml

# 告警配置
alerting:
  alert_relabel_configs:
    - source_labels: [ product_type, ip ]
      separator: ;
      regex: (.*);(.*)
      target_label: routing_key
      replacement: ${1}__${2}
      action: replace
    - source_labels: [ tid, exporter ]
      separator: ;
      regex: (.*);oracle
      target_label: routing_key
      replacement: ${1}oracle
      action: replace
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:10012
      scheme: http
      path_prefix: alertmanager
      timeout: 10s

# 周期任务配置
scrape_configs:

  - job_name: prometheus    # prometheus it self
    scrape_interval: 1m
    scrape_timeout: 50s
    metrics_path: /prometheus/metrics
    scheme: http
    static_configs:
      - targets:
          - 127.0.0.1:10011
- job_name: Host    # qflame_exporter for node metrics
    scrape_interval: 1m
    scrape_timeout: 50s
    metrics_path: /node_metrics
    scheme: http
    file_sd_configs:
      - files:
          - /etc/prometheus/host.yml
        refresh_interval: 5m

  - job_name: IO    # qflame_exporter for io metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    metrics_path: /io_metrics
    scheme: http
    file_sd_configs:
      - files:
          - /etc/prometheus/host.yml
        refresh_interval: 5m

```

The file host.yml  in file_sd_configs:

```
- labels:
    __param_auth: eyJ1c2VyIjoic2VuZG9oIiwicGFzc3dvcmQiOiJjbGpzbHJsMDYyMCIsImtleV9maWxlIjoiIn0=
    __param_port: "22"
    __param_target: 10.10.100.5
    cluster_id: "3"
    cluster_type: Three-tier
    exporter: host
    ip: 10.10.100.5
    node_type: compute
    product_type: qdata
    tid: "9"
  targets:
  - 10.10.100.5:10001
- labels:
    __param_auth: eyJ1c2VyIjoic2VuZG9oIiwicGFzc3dvcmQiOiJjbGpzbHJsMDYyMCIsImtleV9maWxlIjoiIn0=
    __param_port: "22"
    __param_target: 10.10.100.6
    cluster_id: "3"
    cluster_type: Three-tier
    exporter: host
    ip: 10.10.100.6
    node_type: compute
    product_type: qdata
    tid: "11"
  targets:
  - 10.10.100.6:10001
- labels:
    __param_auth: eyJ1c2VyIjoic2VuZG9oIiwicGFzc3dvcmQiOiJjbGpzbHJsMDYyMCIsImtleV9maWxlIjoiIn0=
    __param_port: "22"
    __param_target: 10.10.100.23
    cluster_id: "3"
    cluster_type: Three-tier
    exporter: host
    ip: 10.10.100.23
    node_type: storage
    product_type: qdata
    tid: "13"
  targets:
  - 10.10.100.23:10001
- labels:
    __param_auth: eyJ1c2VyIjoic2VuZG9oIiwicGFzc3dvcmQiOiJjbGpzbHJsMDYyMCIsImtleV9maWxlIjoiIn0=
    __param_port: "22"
    __param_target: 10.10.100.24
    cluster_id: "3"
    cluster_type: Three-tier
    exporter: host
    ip: 10.10.100.24
    node_type: storage
    product_type: qdata
    tid: "15"
  targets:
  - 10.10.100.24:10001

```

Like the host.yml, while I cleanup the host. host.yml changed to a empty list

```
[]
```

Whether I tried '/-/reload' or 'SIGHUP',  the four target always exist,  but when I tried to restart prometheus with the sime conf, targets were removed from the job.

* Alertmanager configuration file:

Nothing to do with Alertmanager.

* Logs:

When I tried to reload with '/-/reload' api or 'SIGHUP' signal, prometheus's log like this:

```
prometheus              | level=info ts=2020-11-19T12:01:40.925Z caller=main.go:861 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/host.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/cloud.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/oracle.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/etcd.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/bulkping.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/snmp.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/0 subs="[Cloud_PS Cloud_FS]"
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/vm.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/1 subs=[Snmp]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/hardware.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/2 subs=[Redfish]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/3 subs=[HostHardware]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/4 subs=[VM]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:305 component="discovery manager scrape" discovery=file msg="Stopping file discovery..." paths=[/etc/prometheus/redfish.yml]
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/5 subs="[Host Host_SSH IO]"
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/6 subs="[OracleStorage OracleLog Oracle OracleAvailable]"
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=static/7 subs=[prometheus]
prometheus              | level=debug ts=2020-11-19T12:01:40.932Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/8 subs=[etcdcluster]
prometheus              | level=debug ts=2020-11-19T12:01:40.932Z caller=manager.go:195 component="discovery manager scrape" msg="Starting provider" provider=file/9 subs=[BulkPing]
prometheus              | level=debug ts=2020-11-19T12:01:40.932Z caller=manager.go:195 component="discovery manager notify" msg="Starting provider" provider=static/0 subs=[config-0]
prometheus              | level=debug ts=2020-11-19T12:01:40.932Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.932Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.931Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.933Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.942Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.943Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.944Z caller=manager.go:213 component="discovery manager notify" msg="Discoverer channel closed" provider=static/0
prometheus              | level=info ts=2020-11-19T12:01:40.944Z caller=main.go:892 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=18.568354ms remote_storage=3.453µs web_handler=689ns query_engine=1.201µs scrape=303.589µs scrape_sd=638.216µs notify=23.204µs notify_sd=51.966µs rules=12.082736ms
prometheus              | level=debug ts=2020-11-19T12:01:40.944Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
prometheus              | level=debug ts=2020-11-19T12:01:40.944Z caller=manager.go:213 component="discovery manager scrape" msg="Discoverer channel closed" provider=static/7
prometheus              | level=debug ts=2020-11-19T12:01:40.944Z caller=file.go:328 component="discovery manager scrape" discovery=file msg="File discovery stopped"
```
