### ISSUE TITLE
gce_sd_configs cannot filter on tags

### ISSUE THREAD

**Issue by symbiont-ji** [prometheus/prometheus#8233]
**What did you do?**
In `/etc/prometheus/prometheus.yml`, I have the following snippet:

```
scrape_configs:
  - job_name: mytargets
    gce_sd_configs:
      - project: my-project-id
        zone: us-central1-b
        port: 9100
        filter: "tags.items = mytargets"
      - project: my-project-id
        zone: us-central1-b
        port: 9100
        filter: "name ~ ^targ"
```

**What did you expect to see?**
I was expecting this to work as a filter. The documentation https://prometheus.io/docs/prometheus/latest/configuration/configuration/#gce_sd_config says:
```
# Syntax of this filter string is described here in the filter query parameter section:
# https://cloud.google.com/compute/docs/reference/latest/instances/list
```
and sure enough, `gcloud compute instances list --filter 'tags.items = mytargets` works, as does  `gcloud compute instances list --filter 'name ~ ^targ`.

**What did you see instead? Under which circumstances?**
When starting prometheus, I get the following error:
```
level=error ts=2020-11-27T22:16:41.839Z caller=refresh.go:79 component="discovery manager scrape" discovery=gce msg="Unable to refresh target groups" err="error retrieving refresh targets from gce: googleapi: Error 400: Invalid value for field 'filter': 'tags.items=mytargets'. Invalid list filter expression., invalid"
```
Note that the error comes from the Google API, which means that something along the way mangles the filter. 

**Environment**

* System information:

`Linux 5.4.0-1029-gcp x86_64`

* Prometheus version:

```
$ prometheus --version
prometheus, version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20200113-10:10:54
  go version:       go1.13.7
```
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
