### ISSUE TITLE
Could we export the target status in detail to the /metrics 

### ISSUE THREAD

**Issue by jeffrey4l** [prometheus/prometheus#8246]
**What did you do?**

Now, when a target is not accessible, we only have two ways to found this.

* on the webui `/targets` page, to check which one is unhealthy
* through prometheus api `/api/v1/targets` to filter the **down** targets
* through the current `net_conntrack_dialer_conn_failed_total` metric from prometheus

But the `net_conntrack_dialer_conn_failed_total` only report job group failure, it isn't include every target scrape status in the job groups.

**What did you expect to see?**

Prometheus should exports every target scrape status, which will be easy to write alert rule to tell which target is unhealthy. Maybe something like below

```
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.1",reason="refused"} 23
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.1",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.1",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.1",reason="unknown"} 23

net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.2",reason="refused"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.2",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.2",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter", target="192.168.1.2",reason="unknown"} 0

```

**What did you see instead? Under which circumstances?**

```
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter",reason="refused"} 23
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter",reason="resolution"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter",reason="timeout"} 0
net_conntrack_dialer_conn_failed_total{dialer_name="node_exporter",reason="unknown"} 23

```

**Environment**

* System information:

```
Linux t470p 5.4.79-1-lts #1 SMP Sun, 22 Nov 2020 14:22:21 +0000 x86_64 GNU/Linux
```

* Prometheus version:

```
prometheus --version
prometheus, version 2.23.0 (branch: tarball, revision: 2.23.0)
  build user:       someone@builder
  build date:       20201126-18:32:01
  go version:       go1.15.5
  platform:         linux/amd64
```

* Prometheus configuration file:
```
---
global:
  scrape_interval: 300s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 192.168.1.1:9100
          - 192.168.1.2:9100
```

* Logs:
```
no log
```
