### ISSUE TITLE
Allow iterating labels in alert rules avoid duplicate series in join

### ISSUE THREAD

**Issue by finkr** [prometheus/prometheus#8247]
## Proposal

Allow iterating labels in alert rules to **avoid *"duplicate series for the match group"*** error.

So far, the workaround to the problem described below involves using some external templating tools (or scripts) to iterate those labels. That's tedious. There is a risk that the script is lagging and that some alerts doesn't exist for new label values.

It would be nice if prometheus could iterate the label values without having to use external tool:
```yaml
rules:
- alert: TestIterate
  expr: up * on  (job,instance)  group_left(mountpoint) node_filesystem_files{device="$device"} < 1
  iterate: node_filesystem_files:device
  for: 1m
```

# Problem

We have implemented [machine roles](https://www.robustperception.io/how-to-have-labels-for-machine-roles) metrics with labels, where one machine can have multiple roles.
 
    node_text_role_info{instance="node1.exemple.com:9100",, softInstance="foo", role="role1"}
    node_text_role_info{instance="node1.exemple.com:9100",, softInstance="foo", role="role2"}
    node_text_role_info{instance="node2.exemple.com:9100",, softInstance="bar", role="role3"}

We also have a some metrics which we want to use for alerting.

      process_cpu_seconds_total{instance="node1.exemple.com:9999", softInstance="foo"}

We want to alert when process consume too much cpu (the rule is simplified for clarity). The alert should have the machine role as label.

```yaml
rules:
- alert: TestTest
  expr: rate(process_cpu_seconds_total[1m]) * on (instance) group_left (role) node_text_role_info < 0.8 
  for: 1m
```

To make this issue easier to reproduce we will use a node_exporter standard metrics from now, but that's similar issue:

    up * on  (job,instance)  group_left(mountpoint)  node_filesystem_files

This PromQL query fails with error:

```
Error executing query: found duplicate series for the match group
found duplicate series for the match group {instance="demo.robustperception.io:9100", job="node"} on the right hand-side of the operation: [
{__name__="node_filesystem_files", device="/dev/vda15", fstype="vfat", instance="demo.robustperception.io:9100", job="node", mountpoint="/boot/efi"},
{__name__="node_filesystem_files", device="/dev/vda1", fstype="ext4", instance="demo.robustperception.io:9100", job="node", mountpoint="/"}
];many-to-many matching not allowed: matching labels must be unique on one side"
```

The current workaround to avoid the *many-to-many* error is to filter on labels to make metrics unique unique again. We would need many rules like this:

```yaml
rules:
- alert: TestVda1
  expr: up * on  (job,instance)  group_left(mountpoint) node_filesystem_files{device="/dev/vda1"} < 1
  for: 1m
- alert: TestVda15
  expr: up * on  (job,instance)  group_left(mountpoint) node_filesystem_files{device="/dev/vda15"} < 1
  for: 1m
```
