### ISSUE TITLE
2.23.0 Getting:  x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0

### ISSUE THREAD

**Issue by hartman17** [prometheus/prometheus#8260]
**What did you do?**
Upgraded Prometheus instance from 2.17.1 to 2.23.0
**What did you expect to see?**
Configured jobs to run with TLS and self signed cert. 
**What did you see instead? Under which circumstances?**
Prometheus reporting: Get "<REMOVED>": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
**Environment**
Producation
* System information:

Linux 4.14.138-rancher x86_64

* Prometheus version:

prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
  build user:       root@37609b3a0a21
  build date:       20201126-10:56:17
  go version:       go1.15.5
  platform:         linux/amd64

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
- job_name: ScrapeJob
  file_sd_configs:
  - files:
    - /etc/prometheus/configmaps/test/file.json
  scrape_interval: 1m
  metrics_path: /metrics
  scheme: https
  basic_auth:
    username: <removed>
    password: <removed>
  tls_config:
    ca_file: /etc/prometheus/secrets/ca/ca.pem
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
Seeing this on job status page: Get "<REMOVED>": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
