### ISSUE TITLE
prometheus config kubernetes endpoints can't get label

### ISSUE THREAD

**Issue by like-inspur** [prometheus/prometheus#8263]
**What did you do?**
I create endpoints config external host and config prometheus endpoints sd to find these target

**What did you expect to see?**
the target of prometheus can be found with endpoints label

**What did you see instead? Under which circumstances?**
the target of prometheus can be found but no endpoints label
![image](https://user-images.githubusercontent.com/18571465/101456624-4d8a6280-396f-11eb-8f30-9556b02b541c.png)

**Environment**
docker

* Prometheus version:
2.22.0

* Prometheus configuration file:
```
    - job_name: 'static-host'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - monitoring
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoints_name
        regex: '.*-host'
      - action: keep
        source_labels:
        - __meta_kubernetes_endpoint_port_name
        regex: http-metrics
```

* kubernetes endpoint configuration file:
```
apiVersion: v1
kind: Endpoints
metadata:
  name: infra-host
  namespace: monitoring
  labels:
    host_type: infra
  subsets:
subsets:
- addresses:
  - ip: 10.110.19.91
  - ip: 10.110.19.92
  - ip: 10.110.19.93
  ports:
  - name: http-metrics
    port: 9126
```
