### ISSUE TITLE
Read remote influxdb empty data,No datapoints found. But start by manual  command no problem

### ISSUE THREAD

**Issue by tonyjia87** [prometheus/prometheus#8267]
use command start prometheus work on centos 7 , I can see data in UI . command:

```
 /opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.retention=60d --web.console.libraries=/opt/prometheus/console_libraries --web.console.templates=/opt/prometheus/consoles --web.enable-lifecycle --web.enable-admin-api
```

But use `systemctl` start, can not see data in UI , systemctl config  : 

```
[root@HZ-11859-6:system]11:30:18# cat /etc/systemd/system/prometheus.service

[Unit]
Description=Prometheus Server
Documentation=https://prometheus.io/docs/introduction/overview/
After=network-online.target

[Service]
User=root
#Restart=on-failure
Type=simple
ExecStart= /opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.retention=60d --web.console.libraries=/opt/prometheus/console_libraries --web.console.templates=/opt/prometheus/consoles --web.enable-lifecycle --web.enable-admin-api

[Install]
WantedBy=multi-user.target
```
 
prometheus config: 

```
# my global config
global:
  # scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /opt/prometheus/rules/*.yaml

remote_write:
  - url: "http://localhost:9201/write"

remote_read:
  - url: "http://localhost:9201/read"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
```

remote_storage_adapter config:

```
[root@xxxx:system]11:03:49# cat remote_storage_adapter.service
[Unit]
Description=remote_storage_adapter
After=network-online.target

[Service]
Type=simple
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/opt/prometheus-adapt/remote_storage_adapter  --influxdb-url=http://172.21.219.98:8086/ --influxdb.database=aitutor_aggregation --influxdb.retention-policy=autogen
LimitNOFILE=65000

Restart=always

[Install]
WantedBy=multi-user.target
```

prometheus version:

```
[root@xxxx:system]11:05:39# /opt/prometheus/prometheus --version
prometheus, version 2.22.1 (branch: HEAD, revision: 00f16d1ac3a4c94561e5133b821d8e4d9ef78ec2)
  build user:       root@516b109b1732
  build date:       20201105-14:02:25
  go version:       go1.15.3
  platform:         linux/amd64
```

Effect picture， start by manual command ：

![image](https://user-images.githubusercontent.com/5828609/101569141-dd331e00-3a0e-11eb-93ab-9a6871b73b45.png)

start by systemctl：

![image](https://user-images.githubusercontent.com/5828609/101569231-0653ae80-3a0f-11eb-9163-540de9eb3a0a.png)
