### ISSUE TITLE
Log errors compaction failed rename block dir Access is denied running on Windows

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [prometheus/prometheus#8270]
**What did you do?**

On Fri, 04 Dec 2020 I deleted all prometheus data (more on that below) to start "clean" with an empty data directory.
After a few days I checked metrics and logs and noticed errors (`Access is denied.`) occuring during tsdb compaction (see below).

The directories mentioned in logs do not exist afterwards (neither the .tmp-for-creation nor the other one).
I will continue to monitor and check if the 15 day retention period is working correctly.

This machine is on premises at a customer site and I am no windows admin... but **our user has administrator privileges on the machine**. I tried running prometheus from powershell running als admin with the same result.

It tried setting more permissive file permissions for the prometheus data directory (`Owner` for dir and all files for our windows user) but that did not do anything.

**Is it possible the virus scanner is blocking prometheus temporarily from renaming the directory?
McAfee is running on this machine.**

EDIT: Added Debug Log, but not much more information I think.

Related: #4648

**What did you expect to see?**

No errors.

**What did you see instead? Under which circumstances?**

metric `prometheus_tsdb_compactions_failed_total` is equal to `prometheus_tsdb_compactions_triggered_total` , both 183 after restart a few hours ago.

Log errors, every minute:
```
caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4G3S3CVDHQZ4XYXJ2PGSCQ.tmp-for-creation data\\01ES4G3S3CVDHQZ4XYXJ2PGSCQ: Access is denied."
```
(more below)

Interestingly, it looks like there have been brief periods without compaction errors:
![grafik](https://user-images.githubusercontent.com/33002073/101681587-a850b680-3a62-11eb-9999-84e5bf1f0c5e.png)

Prometheus was running / is supposed to run using `nssm.exe`, the errors also happen when running prometheus from powershell.

* Current data directory content:
```
Mode                LastWriteTime         Length Name                                                                                                                                          
----                -------------         ------ ----                                                                                                                                          
d-----        7/12/2020     10:59                01ERRPEXGQBW5T8XGZBEHNC5MA                                                                                                                    
d-----        7/12/2020     10:59                01ERSFC2GEVTEG3A6V1P5NSVPK                                                                                                                    
d-----        7/12/2020     11:00                01ERSQYTCXHT2BA773G1SW0EY9                                                                                                                    
d-----        7/12/2020     11:00                01ERT8PX4CG7GMJFCWTP7FZZ16                                                                                                                    
d-----        7/12/2020     11:00                01ERTJBMCKCPP3CQMW2HKJ2XM2                                                                                                                    
d-----        7/12/2020     11:03                01ERTKN3838SK345DWD9ADE1GZ                                                                                                                    
d-----        7/12/2020     11:03                01ERTWBSNT1PAMTXBVT5NT8GJR                                                                                                                    
d-----        7/12/2020     11:03                01ERV3DJ0SDKDEN0G1P2QK1E1J                                                                                                                    
d-----        7/12/2020     11:06                01ERWJZK6QHG9T69W9ST78TR51                                                                                                                    
d-----        7/12/2020     11:06                01ERX53CB5F9ZRM887RNC4GDR0                                                                                                                    
d-----        7/12/2020     11:06                01ERX577H8J9C2PRYRF7PKP5ZY                                                                                                                    
d-----        7/12/2020     11:09                01ERX84A9F4M2C3MMC75Z1HTEJ                                                                                                                    
d-----        7/12/2020     11:09                01ERX8WFDZCMA6Q5G5QHMY0FD4                                                                                                                    
d-----        7/12/2020     11:09                01ERX9PPVN87ENEG7HNSYV26WE                                                                                                                    
d-----        7/12/2020     11:12                01ERXCA2FG6F8G0XFXJTP3FYH2                                                                                                                    
d-----        7/12/2020     11:12                01ERXS3MM609S1MV7KTJGEW2R9                                                                                                                    
d-----        7/12/2020     11:12                01ERXWW23GW0YAZSV6M41HR3DH                                                                                                                    
d-----        7/12/2020     11:15                01ERXWY4EE9WMF27QYH774ZYXY                                                                                                                    
d-----        7/12/2020     11:15                01ERXXZFMSBDCSAB2JFWQSNCX6                                                                                                                    
d-----        7/12/2020     11:15                01ERXYVG1GTHRZKB7DGJSGN6VC                                                                                                                    
d-----        7/12/2020     11:18                01ERY2KYFMYP4SZCV1YQE6X3W1                                                                                                                    
d-----        7/12/2020     11:18                01ERY2KZE6630VXMVVZ05B94BW                                                                                                                    
d-----        7/12/2020     11:18                01ERY468S0Y9W1ASQDNDXZYWVW                                                                                                                    
d-----        7/12/2020     11:21                01ERY5GY02NQ5F1NSYG77T7Q40                                                                                                                    
d-----        7/12/2020     11:21                01ERY5MT2DRB725QZ211VDE01K                                                                                                                    
d-----        7/12/2020     11:21                01ERY5RHVG8C2JGYA1SAN5NJTD                                                                                                                    
d-----        7/12/2020     11:24                01ERY5WD9HR5WWWN2QB7BAQZYB                                                                                                                    
d-----        7/12/2020     11:24                01ERY92B0DNPK2D0PH9TNQCZGC                                                                                                                    
d-----        7/12/2020     11:24                01ERY949MQ6Q6C2VTQ5HPHN2C9                                                                                                                    
d-----        7/12/2020     16:00                01ERYA7J7YFDC8B1XPSBWFCX28                                                                                                                    
d-----        7/12/2020     16:00                01ERYE0WRS28AAZTS9229A69NW                                                                                                                    
d-----        7/12/2020     16:00                01ERYNBG6KZ6M79BGBES3EGJJH                                                                                                                    
d-----        7/12/2020     22:00                01ERYVEVMSWH2EP8SAJCT141EB                                                                                                                    
d-----        7/12/2020     22:00                01ERZ4BS3VSJJDN0SBG7SRRQB6                                                                                                                    
d-----        7/12/2020     22:00                01ERZ97CWGMVB09T7J3DCAFTZQ                                                                                                                    
d-----        8/12/2020      4:00                01ERZG2BJTY95HY4B5W6WQGZM9                                                                                                                    
d-----        8/12/2020      4:00                01ERZWSFJQRSNZJRX6F7ZTV8JC                                                                                                                    
d-----        8/12/2020      4:00                01ES007N75DFQH4FRSPGMRAGE4                                                                                                                    
d-----        8/12/2020     10:02                01ES04P9X7EZJAQG1QTQDKN0GS                                                                                                                    
d-----        8/12/2020     10:02                01ES0DEEJ04NMS3SZXHH6EHS9H                                                                                                                    
d-----        8/12/2020     10:02                01ES0KZ2CSD453QPMH34V90JHP                                                                                                                    
d-----        8/12/2020     10:02                01ES0SCBNQ0QAC62PVV7GS2APQ                                                                                                                    
d-----        8/12/2020     17:42                01ES1KQFRKGVAPAQ1Y49EAB153                                                                                                                    
d-----        8/12/2020     18:02                01ES1MWQ4BJF7GJ0B5DZ43M3GM                                                                                                                    
d-----        8/12/2020     19:55                01ES1VB6VBHY7X6DQKNV60Y0ZA                                                                                                                    
d-----        8/12/2020     23:49                01ES28QANWW46N7T196RZ4ZBCG                                                                                                                    
d-----        9/12/2020      8:30                01ES36GEZ4F8NB89TBX8ZTDKG1                                                                                                                    
d-----        9/12/2020     10:51                01ES3EKFWWP6BJ7B4SBT98EJGA                                                                                                                    
d-----        9/12/2020     11:55                01ES3J90F8ATPRHRMVYQKJGAE9                                                                                                                    
d-----        9/12/2020     12:18                01ES3KJ85A43K7ZWC46G1TYS2J                                                                                                                    
d-----        9/12/2020     17:51                chunks_head                                                                                                                                   
d-----        9/12/2020     17:46                wal                                                                                                                                           
-a----        9/12/2020     17:46              0 lock                                                                                                                                          
-a----        9/12/2020     17:46          20001 queries.active                                                                                                                                
```

`wal`:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/12/2020     21:33                checkpoint.00000060
-a----        9/12/2020     17:45         163840 00000061
-a----        9/12/2020     21:22      117800960 00000062
-a----        9/12/2020     21:26         950272 00000063
-a----        9/12/2020     21:27          11668 00000064
-a----        9/12/2020     21:33         491520 00000065
-a----        9/12/2020     21:37        2046986 00000066
```

`chunks_head`:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        9/12/2020      8:30      134217728 000041
-a----        9/12/2020     10:51      134217728 000042
-a----        9/12/2020     11:55      134217728 000043
-a----        9/12/2020     12:18      134217728 000044
-a----        9/12/2020     17:36      134217728 000045
-a----        9/12/2020     17:40      134217728 000046
-a----        9/12/2020     21:22      134217728 000047
-a----        9/12/2020     21:33      134217728 000048
-a----        9/12/2020     21:33      134217728 000049
-a----        9/12/2020     21:37              0 debugout.txt
```

**Why did I delete all my data in the first place?**

This server had some issues in the past (several windows crashes, causing prometheus to not start anymore because of data corruption. After several prometheus upgrades (including various bugfixes) the hard disk space ran out, there where > 30 GB of WAL files, many checkpoints that could not be deleted it seemed). I dont know if the Access denied behavior did cause the full disk space.
So I decided to nuke all the data and start fresh.

**Environment**

* System information:

Windows Server 2016 `Version 1607 OS Build 14393.3930` running in an virtual machine.

* Prometheus version:

```
prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
  build user:       root@37609b3a0a21
  build date:       20201126-11:08:32
  go version:       go1.15.5
  platform:         windows/amd64
```

* Start params: `--web.enable-lifecycle --storage.tsdb.retention.time=15d --storage.tsdb.wal-compression`

* Prometheus configuration file:
```yaml
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  
  # scrape_timeout global default is 10s.
  scrape_timeout:      20s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'MYSERVERXX1'
    scrape_interval: 60s
    static_configs:
    - targets: ['MYSERVERXX1:9182','MYSERVERXX1:18086','MYSERVERXX1:18087']
    
  - job_name: 'MYSERVERXX2'
    scrape_interval: 60s
    static_configs:
    - targets: ['MYSERVERXX2:9182','MYSERVERXX2:18086','MYSERVERXX2:18087']
    
  - job_name: 'MYSERVERXX3'
    scrape_interval: 60s
    static_configs:
    - targets: ['MYSERVERXX3:9182']

  - job_name: 'XXXXSQL1'
    scrape_interval: 60s
    static_configs:
    - targets: ['XXXXSQL1:9182']
    
  - job_name: 'XXXXSQL2'
    scrape_interval: 60s
    static_configs:
    - targets: ['XXXXSQL2:9182']

  - job_name: 'XXXXSCADA1'
    scrape_interval: 60s
    static_configs:
    - targets: ['XXXXSCADA1:9182','XXXXSCADA1:18086','XXXXSCADA1:18087']
    
  - job_name: 'XXXXSQL1'
    scrape_interval: 60s
    static_configs:
    - targets: ['XXXXSQL1:9182']
 
  - job_name: 'probe-xxxxxx'
  
    scrape_interval: 5m
    scrape_timeout: 5s

    metrics_path: /probe
    params:
      module: [tcp_connect]

    file_sd_configs:
      - files:
        - ./targets/blackbox/*.json

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 # The blackbox exporter's real hostname:port.
 
  - job_name: 'grok'

    scrape_interval: 15s
    scrape_timeout:   5s

    file_sd_configs:
      - files:
        - ./targets/grok/*.yml
```

* Logs:

```
2020-12-09 19:32:04.807: level=error ts=2020-12-09T19:32:04.807Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4FTEDA3DZ0V2T2ZVSFWB5T.tmp-for-creation data\\01ES4FTEDA3DZ0V2T2ZVSFWB5T: Access is denied."
2020-12-09 19:33:05.950: level=error ts=2020-12-09T19:33:05.950Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4FWA5ER1AEFGM3ECK7WBRV.tmp-for-creation data\\01ES4FWA5ER1AEFGM3ECK7WBRV: Access is denied."
2020-12-09 19:34:07.159: level=error ts=2020-12-09T19:34:07.159Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4FY5W8J8RBPYXVT70B74E6.tmp-for-creation data\\01ES4FY5W8J8RBPYXVT70B74E6: Access is denied."
2020-12-09 19:35:08.312: level=error ts=2020-12-09T19:35:08.312Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4G01MPVAFRQ8QR6FBKT38C.tmp-for-creation data\\01ES4G01MPVAFRQ8QR6FBKT38C: Access is denied."
2020-12-09 19:36:09.484: level=error ts=2020-12-09T19:36:09.484Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4G1XBRQ7Q0J4DH7XDXC18V.tmp-for-creation data\\01ES4G1XBRQ7Q0J4DH7XDXC18V: Access is denied."
2020-12-09 19:37:10.670: level=error ts=2020-12-09T19:37:10.670Z caller=db.go:746 component=tsdb msg="compaction failed" err="compact head: persist head block: rename block dir: rename data\\01ES4G3S3CVDHQZ4XYXJ2PGSCQ.tmp-for-creation data\\01ES4G3S3CVDHQZ4XYXJ2PGSCQ: Access is denied."
```
250 errors like these and counting from `2020-12-09 16:46:30.118: level=info ts=2020-12-09T16:46:30.118Z caller=main.go:694 msg="Server is ready to receive web requests."` until now.

Full stdout log attached: 
[prometheus-stdout.txt](https://github.com/prometheus/prometheus/files/5668252/prometheus-stdout.txt)

Debug Log: 
[prometheus-debug-log.txt](https://github.com/prometheus/prometheus/files/5668506/prometheus-debug-log.txt)
