### ISSUE TITLE
Update docker swarm SD

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8272]
A new release of Docker is out.

The new release must be implemented in the swarm SD, and at first sight that will bring us more discovery labels.

**Comment by 131** [comment]
nw, i was wrong and everything works just fine. I just did not understood the difference between container specs and service/tasks specs in my docker stack file

```
version: "3.8"

services:
  redis_exporter:
    image: registry.hub.docker.com/oliver006/redis_exporter:v1.22.0

    labels:
     #this is for containers, and useless
      jeanlebon: jambon

    deploy:
      labels:
      # this is discovered by dockerswarm_sd
        foodebar: "This lab"

```

✨ ❤️ 👍 🥳
