### ISSUE TITLE
K8s SD: valid label selector causes "incorrect config" error

### ISSUE THREAD

**Issue by ashumkin** [prometheus/prometheus#8284]
**What did you do?**
Fill a valid k8s SD label selector:
```
...
    kubernetes_sd_configs:
      - role: pod
        selectors:
          - role:  "pod"
            label: "foo in (bar,baz)"
...
```
N.B. `foo in (bar,baz)` is a valid label selector
E.g. command
`kubectl get pods -n ... --selector "foo in (bar,baz)"`
lists pods with the label `foo` equals `bar` or `baz`

**What did you expect to see?**
Prometheus starts without an error.

**What did you see instead? Under which circumstances?**
Prometheus does not start with the "unexpected error: parsing YAML file ... invalid selector: 'foo in (bar,baz)'; can't understand 'baz)'" error

**Environment**

* Prometheus version:
v2.23.0

* Prometheus configuration file:
```
scrape_configs:
  - job_name: prometheus
    kubernetes_sd_configs:
      - role: pod
        selectors:
          - role:  "pod"
            label: "foo in (bar,baz)"
            field: "metadata.status=Running"
```

P.S. The fix will follow in a PR.
