### ISSUE TITLE
fatal error: index out of range -- Prometheus docker container exits after it started in seconds.

### ISSUE THREAD

**Issue by iridiumcao** [prometheus/prometheus#8326]
**What did you do?**
run Prometheus docker container

**What did you expect to see?**
the container is running

**What did you see instead? Under which circumstances?**
The container has run for seconds and exited unexpectedly.

**Environment**
host: a VM with CentOS 7
Prometheus: prom/prometheus:v2.23.0

* System information:
Linux 3.10.0-1160.11.1.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
  build user:       root@37609b3a0a21
  build date:       20201126-10:56:17
  go version:       go1.15.5
  platform:         linux/amd64

* Prometheus configuration file:
```
# https://prometheus.io/docs/prometheus/latest/getting_started/
# https://prometheus.io/docs/guides/node-exporter/
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: [ '192.168.100.88:9090' ]

  - job_name: 'node_exporter'
    scrape_interval: 15s
    static_configs:
      - targets:
        - '192.168.100.2:9100'
        - '192.168.100.3:9100'
        - '192.168.100.5:9100'
        - '192.168.100.7:9100'
        - '192.168.100.8:9100'
        - '192.168.100.11:9100'
        - '192.168.100.83:9100'
        - '192.168.100.88:9100'
```

* Logs:
[prometheus-docker-container-start-failed-log1.txt](https://github.com/prometheus/prometheus/files/5750001/prometheus-docker-container-start-failed-log1.txt)
