### ISSUE TITLE
Histogram bucket label value gets converted to float somehow

### ISSUE THREAD

**Issue by SteffenDE** [prometheus/prometheus#8367]
**What did you do?**
I'm tracking Caddy metrics (https://caddyserver.com/) with prometheus (latest docker image) and am experiencing a strange problem: I've got three instances reporting metrics and for one instance the bucket label le="1" is saved as le="1.0":
![image](https://user-images.githubusercontent.com/4116351/104630523-23793e00-569b-11eb-9eeb-8229dc40acce.png)
(query: `sum(increase(caddy_http_request_duration_seconds_bucket{handler=~"reverse_proxy", server="srv0", le=~"1|1.0"}[5m])) by (le, instance)`)

I've checked the http output of the specific caddy instance and every "le" label is correctly formatted as int. Only when querying prometheus I get a float value:

```
# curl -s http://10.100.16.9:8080/metrics|grep seconds_bucket|grep 200|grep GET|grep reverse_proxy|grep request
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.005"} 364
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.01"} 1101
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.025"} 1773
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.05"} 2253
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.1"} 2757
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.25"} 3147
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="0.5"} 3847
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="1"} 4390
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="2.5"} 4490
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="5"} 4506
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="10"} 4511
caddy_http_request_duration_seconds_bucket{code="200",handler="reverse_proxy",method="GET",server="srv0",le="+Inf"} 4512
# curl -s http://10.100.16.9:8080/metrics|grep seconds_bucket|grep "le=\"1.0\""
# 
```

It also happens to the other buckets (le="5", le="10").

(This really messes up the grafana heatmap when the affected instance is included:
![image](https://user-images.githubusercontent.com/4116351/104630726-7226d800-569b-11eb-9c4e-3f8f1a47b41e.png)
vs
![image](https://user-images.githubusercontent.com/4116351/104630760-7ce16d00-569b-11eb-8320-67a93f05d448.png)
)

**What did you expect to see?**
The value should be the same le="1" as with the other instances.

**What did you see instead? Under which circumstances?**
The value is a float instead of an integer.

**Environment**

* System information:

```
Linux 4.15.0-115-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.24.0 (branch: HEAD, revision: 02e92236a8bad3503ff5eec3e04ac205a3b8e4fe)
  build user:       root@d9f90f0b1f76
  build date:       20210106-13:48:37
  go version:       go1.15.6
  platform:         linux/amd64
```

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'caddy'

    hetzner_sd_configs:
     - bearer_token: "***"
       role: "hcloud"
    relabel_configs:
     - source_labels: [__meta_hetzner_hcloud_label_prometheus]
       regex: true.*
       action: keep
     - source_labels: [__meta_hetzner_hcloud_label_caddy]
       regex: true:*
       action: keep
     - source_labels: [__meta_hetzner_server_name]
       target_label: server_name
       replacement: '$1'
     - source_labels: [__meta_hetzner_hcloud_private_ipv4_net]
       target_label: __address__
       replacement: '$1:8080'
```
