### ISSUE TITLE
High continuous CPU usage if many targets cannot be scraped

### ISSUE THREAD

**Issue by hendrikmaus** [prometheus/prometheus#8392]
**What did you do?**
Deployed Prometheus via Helm Chart kube-prometheus-stack and Prometheus Operator.
The cluster contains about 700 pods which are mostly all scraped at an interval of 15-60s.
I wasn't aware of any fault scraping endpoints yet.

**What did you expect to see?**
Prometheus being able to operate with 2-4 CPU cores.

**What did you see instead? Under which circumstances?**
Prometheus' CPU usage was continuously at the limit of 14 cores while metrics reported it being throttled by 70%.
It was operational in that state, i.e. I was able to query metrics.

I found that the reason were ~450 workloads which returned 404 on a 60s scrape interval. As soon as I removed those unavailable endpoints, the CPU went down to 0.5 CPU cores.

**Environment**

* System information:

	insert output of `uname -srm` here

```txt
Linux 4.19.150+ x86_64
```

* Prometheus version:

	insert output of `prometheus --version` here

```txt
prometheus, version 2.24.1 (branch: HEAD, revision: e4487274853c587717006eeda8804e597d120340)
  build user:       root@0b5231a0de0f
  build date:       20210120-00:09:36
  go version:       go1.15.6
  platform:         linux/amd64
```

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:

```yaml
# prometheus operator spec for the prometheus pod
prometheusSpec:
  image:
    tag: v2.24.1
  externalUrl: "" # set by the deployment process
  ruleNamespaceSelector:
    matchLabels:
      prometheus/ruleMonitor: 'true'
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus/serviceMonitor: 'true'
  podMonitorNamespaceSelector:
    matchLabels:
      prometheus/podMonitor: 'true'
  probeNamespaceSelector:
    matchLabels:
      prometheus/probeMonitor: 'true'
  ruleSelector:
    matchLabels:
      prometheus.monitoring: enabled
  serviceMonitorSelector:
    matchLabels:
      prometheus.monitoring: enabled
  podMonitorSelector:
    matchLabels:
      prometheus.monitoring: enabled
  probeSelector:
    matchLabels:
      prometheus.monitoring: enabled
  resources:
    requests:
      cpu: '14' # < started out with 2 cores
      memory: '24Gi'
    limits:
      cpu: '14' # < started out with 4 cores
      memory: '24Gi'
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: hdd
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 200Gi
  retention: 3d
  thanos:
    baseImage: thanosio/thanos
      objectStorageConfig:
        key: object-store.yaml
        name: thanos-object-store-config
    version: v0.17.1
```

```
# config is generated by prometheus-operator, so the following is just repeated many times.

  - job_name: some-namespace/some-workload/0
    honor_labels: false
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - tools
    scrape_interval: 60s
    metrics_path: /prometheus
    relabel_configs:
      - action: keep
        source_labels:
          - __meta_kubernetes_service_label_app
        regex: static-link
      - action: keep
        source_labels:
          - __meta_kubernetes_endpoint_port_name
        regex: http-metrics
      - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Node;(.*)
        replacement: ${1}
        target_label: node
      - source_labels:
          - __meta_kubernetes_endpoint_address_target_kind
          - __meta_kubernetes_endpoint_address_target_name
        separator: ;
        regex: Pod;(.*)
        replacement: ${1}
        target_label: pod
      - source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - source_labels:
          - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
          - __meta_kubernetes_pod_container_name
        target_label: container
      - source_labels:
          - __meta_kubernetes_service_name
        target_label: job
        replacement: ${1}
      - target_label: endpoint
        replacement: http-metrics
      - source_labels:
          - __address__
        target_label: __tmp_hash
        modulus: 1
        action: hashmod
      - source_labels:
          - __tmp_hash
        regex: 0
        action: keep
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=info ts=2021-01-21T13:07:26.989Z caller=main.go:364 msg="Starting Prometheus" version="(version=2.24.1, branch=HEAD, revision=e4487274853c587717006eeda8804e597d120340)"
level=info ts=2021-01-21T13:07:26.989Z caller=main.go:369 build_context="(go=go1.15.6, user=root@0b5231a0de0f, date=20210120-00:09:36)"
level=info ts=2021-01-21T13:07:26.989Z caller=main.go:370 host_details="(Linux 4.19.150+ #1 SMP Sat Oct 24 07:57:26 PDT 2020 x86_64 prometheus-monitoring-main-prometheus-0 (none))"
level=info ts=2021-01-21T13:07:26.989Z caller=main.go:371 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-01-21T13:07:26.989Z caller=main.go:372 vm_limits="(soft=unlimited, hard=unlimited)"
level=info ts=2021-01-21T13:07:26.996Z caller=web.go:530 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2021-01-21T13:07:26.996Z caller=main.go:738 msg="Starting TSDB ..."
level=info ts=2021-01-21T13:07:26.998Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
level=info ts=2021-01-21T13:07:27.026Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1611217760241 maxt=1611223200000 ulid=01EWJB9FGA1C3VZCG1GG56K8N1
level=info ts=2021-01-21T13:07:27.027Z caller=repair.go:57 component=tsdb msg="Found healthy block" mint=1611223200000 maxt=1611230400000 ulid=01EWJGFF78AP7QES7YCD4JYQG6
level=info ts=2021-01-21T13:07:27.997Z caller=head.go:645 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-01-21T13:07:32.260Z caller=head.go:659 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=4.262754002s
level=info ts=2021-01-21T13:07:32.260Z caller=head.go:665 component=tsdb msg="Replaying WAL, this may take a while"
level=info ts=2021-01-21T13:07:41.501Z caller=head.go:691 component=tsdb msg="WAL checkpoint loaded"
level=info ts=2021-01-21T13:07:44.218Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=19 maxSegment=25
level=info ts=2021-01-21T13:07:46.027Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=20 maxSegment=25
level=info ts=2021-01-21T13:07:49.380Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=21 maxSegment=25
level=info ts=2021-01-21T13:07:49.423Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=22 maxSegment=25
level=info ts=2021-01-21T13:07:51.212Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=23 maxSegment=25
level=info ts=2021-01-21T13:07:51.459Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=24 maxSegment=25
level=info ts=2021-01-21T13:07:51.459Z caller=head.go:717 component=tsdb msg="WAL segment loaded" segment=25 maxSegment=25
level=info ts=2021-01-21T13:07:51.459Z caller=head.go:722 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=9.241412456s wal_replay_duration=9.957833937s total_replay_duration=23.462115786s
level=info ts=2021-01-21T13:07:52.535Z caller=main.go:758 fs_type=EXT4_SUPER_MAGIC
level=info ts=2021-01-21T13:07:52.535Z caller=main.go:761 msg="TSDB started"
level=info ts=2021-01-21T13:07:52.535Z caller=main.go:887 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-01-21T13:07:52.543Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.544Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.544Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.545Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.546Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.547Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.547Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.603Z caller=main.go:918 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=67.338633ms remote_storage=3.2µs web_handler=940ns query_engine=1.93µs scrape=379.161µs scrape_sd=5.3516ms notify=1.591µs notify_sd=2.169µs rules=54.835483ms
level=info ts=2021-01-21T13:07:52.603Z caller=main.go:710 msg="Server is ready to receive web requests."
level=info ts=2021-01-21T13:07:52.603Z caller=main.go:887 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2021-01-21T13:07:52.611Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=warn ts=2021-01-21T13:07:52.611Z caller=klog.go:88 component=k8s_client_runtime func=Warningf msg="/app/discovery/kubernetes/kubernetes.go:428: watch of *v1.Service ended with: an error on the server (\"unable to decode an event from the watch stream: context canceled\") has prevented the request from succeeding"
level=info ts=2021-01-21T13:07:52.612Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.613Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.614Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.614Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.615Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.616Z caller=kubernetes.go:264 component="discovery manager scrape" discovery=kubernetes msg="Using pod service account via in-cluster config"
level=info ts=2021-01-21T13:07:52.687Z caller=main.go:918 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml totalDuration=83.964843ms remote_storage=5.09µs web_handler=880ns query_engine=1.781µs scrape=103.23µs scrape_sd=6.191561ms notify=2µs notify_sd=1.929µs rules=70.370214ms
```
