### ISSUE TITLE
looks like rate/irate/delta/increase are not calculating consistent

### ISSUE THREAD

**Issue by DEvil0000** [prometheus/prometheus#8413]
**What did you do?**
I have a counter series on a 30s scrape interval. On that series I query rate().

**What did you expect to see?**
For a counter increase by 1 I expect a rate() result/value of 1/60 = 0.01666666666.
(No matter if I set a specific resolution in the range and what resolution I give)

**What did you see instead? Under which circumstances?**
Depending on the used range/resolution in the query it may calculate the expected result or not. (rate/irate/delta/increase act in the same strange way). This issue is not within grafana - plain prometheus queries on 9090 return the same results. The values are visualised in grafana hard steped curves so it is more readable. Have a close look at the value on the right axis, the width and the right shift of the green line to see the issue.
Full query:
```
yellow: some_series_counter
green: rate(some_series_counter[see below])
```
* [1m] // wrong value (and unexpected resolution)
* [1m:] // correct value and resolution (not sure why it is shifted to the right by one sample) - why is this different to the first case?!
* [1m:15s] // correct value and resolution (I would say)
* [1m:30s] // wrong everything (I would say)
* [1m:45s] // wrong value and resolution (I would say)
* [1m:1m] // correct value and resolution (not sure why it is shifted to the right by one sample)
![Bildschirmfoto_2021-01-27_16-53-05](https://user-images.githubusercontent.com/3344302/106029335-44935300-60cd-11eb-9f65-e29a2b047706.png)

This may actually be the same thing as reported in #5591 but since I am not sure about that I opened this one.

Do I misunderstand how this should work?
But even then the first two cases should act the same - right?
Also I would expect the other cases to act more consistent..

**Environment**
telegraf -> prometheus -> thanos -> grafana

* System information:
ubuntu 20.04

* Prometheus version:
2.24.1
and
2.14.0

* Alertmanager version:
none

* Prometheus configuration file:
```
global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    environment: testmachine
rule_files:
  - /etc/prometheus/rules/*.rules
scrape_configs:
  - job_name: telegraf
    static_configs:
    - targets:
      - localhost:9273
```

* Logs:
no special log lines found
