### ISSUE TITLE
configure CMD-SHELL commands in the Prometheus scrape target 

### ISSUE THREAD

**Issue by gowrisankar22** [prometheus/prometheus#8419]
Hello,

I have a health check configured in the docker-compose. I am also using Blackbox to export the metrics to Prometheus. I am not sure how to configure in the black box config for the cmd_shell based commends?

Can you give me an example of BlackBox config and target to be configured in the Prometheus scrape for the below case ??
```
version: '2.1'
services:
  test-database:
    image: postgres:9.5
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=db
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
```
