### ISSUE TITLE
SD: Need error counter in case the creation of targets fails, and reconsider target drop strategy

### ISSUE THREAD

**Issue by frafranck** [prometheus/prometheus#8438]
**What did you do?**

Consul service discovery Job for wmi and node exporters

**What did you expect to see?**

Expected to have all targets discovered and scraped

**What did you see instead? Under which circumstances?**

Node exporters were fine but nothing in discovery page and nothing scraped for wmi
Got error in log prometheus (see log)
Only one server had a wrong IP address but the whole discovery job failed. (249 IP were OK and 1 was wrong ==> no scrape at all)

Didnt find any metrics that reflect this error, impossible to monitor
sd shouldnt discard all targets if only one is wrong

**Environment**

* System information:

	Linux 3.10.0-1127.18.2.el7.x86_64 x86_64

* Prometheus version:

	version 2.23.0

* Prometheus configuration file:
```
- job_name: 'generic-exporter-consul'
  scrape_timeout: 30s
  consul_sd_configs:
    - server: 'ipconsul:8500'
      token : 'token'
      datacenter: 'dc1'
      tag_separator: ';'
      services:
        - node-exporter
        - wmi-exporter
 
  relabel_configs:

    - source_labels: ['__meta_consul_service']
      target_label:  'job'

    - source_labels: ['__meta_consul_node']
      target_label:  'info_fqdn'
      replacement:   '$1'
```

* Logs:
```
level=error ts=2021-02-03T15:13:20.828Z caller=scrape.go:421 component="scrape manager" scrape_pool=generic-exporter-consul msg="creating targets failed" err="instance 564 in group wmi-exporter: \"172.x.x.x/172.x.x.x:9182\" is not a valid hostname",
```
