### ISSUE TITLE
Ruler: Alert not firing when using a recording rule from the same group, works with both in different groups

### ISSUE THREAD

**Issue by simonswine** [prometheus/prometheus#8467]
**What did you do?**

Created an alert that evaluates depending on a recording rule in the same rule group

**What did you expect to see?**

Alert does fire as it does when recording/alerting rule are in different rule groups

**What did you see instead? Under which circumstances?**

Alert doesn't fire with this particular expression. This is what you can see after 1m:

![scrn-2021-02-10-09-48-16](https://user-images.githubusercontent.com/223048/107493127-304b5d80-6b85-11eb-8bdd-ac71e1ae7a0a.png)

**Environment**

* System information: `Linux 5.10.13 x86_64`
* Prometheus version: 
  <details>
    <summary>head (6bc678) also on v2.24.1</summary>

  ```
  prometheus, version 2.24.1 (branch: master, revision: 6bc67805332dad9345f9d11069f321203bf89f8d)
    build user:       christian@christian-x1
    build date:       20210210-09:36:27
    go version:       go1.15.5
    platform:         linux/amd64
   ```
  </details>

* Prometheus configuration file:
```yaml
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
 - {"job_name":"prometheus","scrape_interval":"5s","static_configs":[{"targets":["localhost:9090"]}]}

rule_files:
 - 'rules.yaml'
```

* `rules.yaml`
```yaml
---
groups:
- name: bug
  rules:
  - record: my_time
    expr: time()
  - alert: MyAlertNotWorkingSameRuleGroup
    expr: |
      max_over_time(my_time[30s] offset 30s) - min_over_time(my_time[30s]) < 0
    for: 30s

- name: working-split-recording
  rules:
  - record: my_time_2
    expr: time()
- name: working-split-alerting
  rules:
  - alert: MyAlertWorking
    expr: |
      max_over_time(my_time_2[30s] offset 30s) - min_over_time(my_time_2[30s]) < 0
    for: 30s
```

* Logs:
  <details>
    <summary>Nothing relevant is logged</summary>

  ```
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:366 msg="No time or size retention was set so using the default time retention" duration=15d
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:404 msg="Starting Prometheus" version="(version=2.24.1, branch=master, revision=6bc67805332dad9345f9d11069f321203bf89f8d)"
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:409 build_context="(go=go1.15.5, user=christian@christian-x1, date=20210210-09:36:27)"
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:410 host_details="(Linux 5.10.13 #1-NixOS SMP Wed Feb 3 22:28:52 UTC 2021 x86_64 christian-x1 (none))"
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:411 fd_limits="(soft=1024, hard=524288)"
  level=info ts=2021-02-10T09:41:04.922Z caller=main.go:412 vm_limits="(soft=unlimited, hard=unlimited)"
  level=info ts=2021-02-10T09:41:04.924Z caller=web.go:532 component=web msg="Start listening for connections" address=0.0.0.0:9090
  level=info ts=2021-02-10T09:41:04.924Z caller=main.go:779 msg="Starting TSDB ..."
  level=info ts=2021-02-10T09:41:04.925Z caller=tls_config.go:191 component=web msg="TLS is disabled." http2=false
  level=info ts=2021-02-10T09:41:04.927Z caller=head.go:668 component=tsdb msg="Replaying on-disk memory mappable chunks if any"
  level=info ts=2021-02-10T09:41:04.928Z caller=head.go:682 component=tsdb msg="On-disk memory mappable chunks replay completed" duration=731.51µs
  level=info ts=2021-02-10T09:41:04.928Z caller=head.go:688 component=tsdb msg="Replaying WAL, this may take a while"
  level=info ts=2021-02-10T09:41:04.928Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=10
  level=info ts=2021-02-10T09:41:04.931Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=1 maxSegment=10
  level=info ts=2021-02-10T09:41:04.932Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=2 maxSegment=10
  level=info ts=2021-02-10T09:41:04.939Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=3 maxSegment=10
  level=info ts=2021-02-10T09:41:04.940Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=4 maxSegment=10
  level=info ts=2021-02-10T09:41:04.940Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=5 maxSegment=10
  level=info ts=2021-02-10T09:41:04.945Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=6 maxSegment=10
  level=info ts=2021-02-10T09:41:04.946Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=7 maxSegment=10
  level=info ts=2021-02-10T09:41:04.946Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=8 maxSegment=10
  level=info ts=2021-02-10T09:41:04.946Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=9 maxSegment=10
  level=info ts=2021-02-10T09:41:04.946Z caller=head.go:740 component=tsdb msg="WAL segment loaded" segment=10 maxSegment=10
  level=info ts=2021-02-10T09:41:04.946Z caller=head.go:745 component=tsdb msg="WAL replay completed" checkpoint_replay_duration=70.19µs wal_replay_duration=18.124511ms total_replay_duration=19.25718ms
  level=info ts=2021-02-10T09:41:04.948Z caller=main.go:799 fs_type=2fc12fc1
  level=info ts=2021-02-10T09:41:04.948Z caller=main.go:802 msg="TSDB started"
  level=info ts=2021-02-10T09:41:04.948Z caller=main.go:928 msg="Loading configuration file" filename=prometheus.yaml
  level=info ts=2021-02-10T09:41:04.949Z caller=main.go:959 msg="Completed loading of configuration file" filename=prometheus.yaml totalDuration=1.564764ms remote_storage=3.437µs web_handler=1.426µs query_engine=2.385µs scrape=445.741µs scrape_sd=48.89µs notify=660ns notify_sd=2.401µs rules=637.821µs
  level=info ts=2021-02-10T09:41:04.949Z caller=main.go:751 msg="Server is ready to receive web requests."
   ```
  </details>
