### ISSUE TITLE
count_over_time of empty result doesn't return zero

### ISSUE THREAD

**Issue by Jan-Eric-Babula** [prometheus/prometheus#8532]
**What did you do?**
Trying to determine the aggregate:
`count_over_time( ( probe_success{ instance="192.168.192.1" } == 0 )[1m:] )`

**What did you expect to see?**
Successful response, returning the number of entries.
If the number of entries is zero (0), that value should be returned.
Comparison [/container/list/list](https://golang.org/src/container/list/list.go#L57) - default length without entries is 0 (zero), not null/nil.

**What did you see instead? Under which circumstances?**
When the underlying object returns an empty result...
`( probe_success{ instance="192.168.192.1" } == 0 )[1m:]` => `"response": { "status": "success", "data": { "resultType": "matrix", "result": [] } }`
Instead of counting zero (0) entries, the empty result cascades upwards:
`count_over_time( ( probe_success{ instance="192.168.192.1" } == 0 )[1m:] )` => `response": { "status": "success", "data": { "resultType": "matrix", "result": [] } }`

**Environment**

* System information:

	Linux 5.10.11-v7l+ armv7l

* Prometheus version:

	prometheus, version 2.23.0 (branch: HEAD, revision: 26d89b4b0776fe4cd5a3656dfa520f119a375273)
	  build user:       root@37609b3a0a21
	  build date:       20201126-11:53:03
	  go version:       go1.15.5
	  platform:         linux/arm

* Alertmanager version: -

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     2s
  evaluation_interval: 10s
  scrape_timeout:      2s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'netmon'
    metrics_path: /probe
    params:
      module: [icmp_v4]  # Look for a IPv4 IMCP Echo of 32 bytes
    static_configs:
      - targets:
        - 192.168.192.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```

* Alertmanager configuration file: -
* Logs: -
