### ISSUE TITLE
Load scrape configs from multiple files

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8543]
This issue is about providing the ability to split Prometheus scrape configs into multiple files.

Design doc: https://docs.google.com/document/d/1bSehbL_Rzx9_guVgISmara-Ft_FB57q_YxEZtwxE3C8/edit#heading=h.bupciudrwmna

Add a new parameter `scrape_config_files: [ - <filepath_glob> ... ]`.

The files in the scrape_config_files are read, and may contain one or multiple files. The filenames can contain globs (scrape_configs.d/*.yml). Relative paths are relative to the main config file.

The files are re-read on every reload. Wrong scrape configs make the reload fail, and scrape configs as applied before apply. Errors reading scrape configs prevent Prometheus to start.

Scrape config names must be unique between prometheus.yml and imported files, otherwise reload/start fail.

Scrape configs are never merged together.

Exemple scrape config file:

Prometheus.yml

```
global: 
   scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
scrape_config_files:
  - blackbox.yml
```

blackbox.yml

```
scrape_configs:
 - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://prometheus.io
        - https://prometheus.io
        - http://example.com:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```

**Comment by lonewolf3739** [comment]
@roidelapluie I would like to pick this up.

**Comment by roidelapluie** [comment]
Welcome! Right, I will assign it to you. If you seek help, please reach out to https://prometheus.io/community/ ; we have  multiple channels / mailing list, and also contributors office hours accross multiple timezones. Also happy to help here on github.

**Comment by RichiH** [comment]
We are exploring similar in prometheus/snmp_exporter and would like to keep the approaches aligned. Ben and my current thinking there was to go through CLI parameters. We will think about this and update.

For reference, see
* https://github.com/prometheus/snmp_exporter/issues/628
* https://github.com/prometheus/snmp_exporter/issues/625
* https://docs.google.com/document/d/1McJJIiJfHgoecVrVNXx4ABJmI5M21e-6O9IgMNbVnvw/edit

**Comment by roidelapluie** [comment]
I have added the "flag" alternative to the considered options in our design doc.

**Comment by SuperQ** [comment]
One question, do we need a top-level `scrape_configs:` key in the example of the `blackbox.yml`? The top-level of the file could simply be a list.

**Comment by roidelapluie** [comment]
> One question, do we need a top-level `scrape_configs:` key in the example of the `blackbox.yml`? The top-level of the file could simply be a list.

We have a top level `groups` in the rules, that is why I ketps the top level scrape_configs, for consistency.

**Comment by SuperQ** [comment]
Maybe it would be simpler to make this a much more generic `include_files:` directive, then included files could contain `scrape_configs` and/or `rules`.

We would need a recursive depth handler, but it would be much more generic.

**Comment by RichiH** [comment]
Julien, look into IRC, we shared a Meet URL :p

**Comment by RichiH** [comment]
Our current thinking is at https://docs.google.com/document/d/1BK_Gc3ixoWyxr9F5qGC07HEcfDPtb6z96mfqoGyz52Y and I will open a thread on prometheus-developers to make people aware of it, as well.

**Comment by skupjoe** [comment]
VictoriaMetrics' vmagent does this perfectly:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/docs/vmagent.md#loading-scrape-configs-from-multiple-files

Can this please be supported in the native prometheus client as well?

**Comment by b00ga** [comment]
I'm just getting started with Prometheus, but we use a lot of Ansible for provisioning. I'd like to have an Ansible role (Ansible's concept of libraries) that sets up the prometheus server and base config. Then have roles for exporters that can just drop a file with their job/target/labels and that prometheus base config would be configured with a wildcard to slurp up any new configs dropped there. I feel like the implementation discussed here would fit this use case well.

**Comment by fsiler** [comment]
If I made a PR with the `scrape_config_files` option, is there inclination to accept it?

**Comment by freak12techno** [comment]
I have a usecase for it: I maintain a public repo with my ansible playbooks. I want to share some jobs, but keep others private, so it'd be extra handy if I can split it into multiple files and commit some files but put others into `.gitignore`. Guess it would be helpful for others who are trying to automate provisioning their Prometheus configs as well.

**Comment by mdebord-dlr** [comment]
Has anyone devised a workaround for this at all? I have a tricky automation scenario that I'm unable to find a viable solution to right now with the singular config file. I am going to have to template out different parts of the file and it's going to get messy. Would really appreciate this functionality or even an alternative method to get a similar effect of modular config.

**Comment by tuaris** [comment]
If I may chime in ;)
Rather than list each file you wanat to load, it would be much more efficient to point to a directory and have it auto load anything that ends in `*.yml`.  

For example, you could have `/usr/local/etc/prometheus/scrapes.yml.d/`  and inside that folder have `blackbox.yml`, `another.yml`, and so on.

**Comment by albttx** [comment]
Any update on this ? I don't want to switch to VictoriaMetrics just for this feature ! 😅

**Comment by roidelapluie** [comment]
See #12019

**Comment by roidelapluie** [comment]
This topic of importing multiple scrape configs has been a frequent request for the past two years. It is important to note that users are not simply asking to include any files, but rather to import multiple scrape configs.

My design document was marked as deprecated, however, I disagree with this. I strongly believe that we should uphold the original principle of Prometheus, which is to not do configuration management. Merging YAML, keys, lists, etc., can be complex, difficult to implement, and can lead to various expectations about how merging works. Additionally, this can create problems for system administrators and those who support Prometheus users on a daily basis.

Therefore, I have implemented my original design document, which is an include mechanism similar to the one we have for rule files. We simply include scrape_configs in the same way we include rule groups. Overall, this meets the needs of the vast majority of users, and I believe that this is a necessary feature.

As for the YAML include issue, I do not believe it is worth implementing and supporting. Instead, we should allow config management tools to handle their job and let each user choose their own way to recompose the YAML files with the rules they prefer.

To conclude this specific issue, I have implemented scrape config includes in #12019, and I hope that we can reach lazy consensus to implement this feature over the next few days.

**Comment by roidelapluie** [comment]
> If I may chime in ;)
> 
> Rather than list each file you want to load, it would be much more efficient to point to a directory and have it auto load anything that ends in `*.yml`.
> 
> For example, you could have `/usr/local/etc/prometheus/scrapes.yml.d/` and inside that folder have `blackbox.yml`, `another.yml`, and so on.

This is possible with the PR: /usr/local/etc/prometheus/scrapes.yml.d/*.yml`

**Comment by gjrtimmer** [comment]
When could this be implemented ?

**Comment by diegoclair** [comment]
Is this already implemented? I tried the last version of docoker image and I could not use the feature. 
Example:
```
global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_config_files:
  - /etc/prometheus/scrape_configs/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
```
Error loading config (--config.file=/etc/prometheus/prometheus-global.yml)" file=/etc/prometheus/prometheus-global.yml err="parsing YAML file /etc/prometheus/prometheus-global.yml: yaml: unmarshal errors:\n  line 5: field scrape_config_files not found in type config.plain"
