### ISSUE TITLE
Remote read: The remote endpoint is down, causing the overall query to use timeout blocking

### ISSUE THREAD

**Issue by fcddk** [prometheus/prometheus#8567]
**What did you do?**
   Remote read is configured for rules evaluation and queries.

  **What did you expect to see?**
    Once the remote enpoint is unavailable once, the endpoint will be marked as unavailable and ignored within a certain period of time
  **What did you see instead? Under which circumstances?**
   When a remote endpoint is unavailable, it will increase the time consumption for subsequent queries and rules evaluation.
  **Environment**

  * Prometheus version:

      2.22.0

  * Prometheus configuration file:
  ```
remote_read:
  - url: http://10.110.19.80:9094/api/v1/read
    remote_timeout: 15s
    read_recent: true
  - url: http://prometheus:9090/api/v1/read
    remote_timeout: 15s
    read_recent: true
  - url: http://10.110.64.58:9090/api/v1/read
    remote_timeout: 15s
    read_recent: true
  ```

  * Logs:
  ```
  web ui log:
    remote_read: error sending request: Post "http://10.110.19.80:9094/api/v1/read": context deadline exceeded

  ```
