### ISSUE TITLE
promtool test rules: nil pointer dereference on range w/o resolution

### ISSUE THREAD

**Issue by AdamSLevy** [prometheus/prometheus#8568]
**What did you do?**

Try to use `promtool test rules` on the following rules:

alerts.yaml
```
groups:
- name: rules
  rules:
  - alert: NoResolution
    expr: delta(sum(up)[3m:])/sum(up)
  - alert: SetResolution
    expr: delta(sum(up)[3m:1m])/sum(up)
```

test.yaml
```
rule_files:
    - alerts.yaml

evaluation_interval: 1m

tests:
    # Test 1.
    - interval: 1m
      # Series data.
      input_series:
          - series: 'up{a="a"}'
            values: '1+0x6 0+0x6'
          - series: 'up{b="b"}'
            values: '1+0x6 0+0x6'
```

**What did you expect to see?**

```
$ promtool test rules ./test.yaml
Unit Testing:  ./test.yaml
  SUCCESS
```

**What did you see instead? Under which circumstances?**

```
$ promtool test rules ./test.yaml
Unit Testing:  ./test.yaml
  FAILED:
    rule: NoResolution, time: 0s, err: unexpected error: runtime error: invalid memory address or nil pointer dereference
```
Please note that only NoResolution has an error. If I explicitly set a resolution it goes away.
**Environment**

* System information:
```
$ uname -srm
Darwin 19.6.0 x86_64
```

* Prometheus version:

```
$ prometheus --version
prometheus, version 2.25.0 (branch: non-git, revision: non-git)
  build user:       macports@REML0687
  build date:       20210225-00:02:14
  go version:       go1.15.6
  platform:         darwin/amd64
```
