### ISSUE TITLE
Unit testing for relabeling rules

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#8606]
## Proposal
**Use case. Why is this important?**

It would be great to have unit testing for relabeling configs.

We already have unit testing for rules, but I'd like to have something to test relabeling rules inside promtool.

Ideas welcome.

**Comment by LeviHarrison** [comment]
I think this could be pretty easily added to the existing test file by doing the following:

- Adding a `config_files` field, where a user could specify the Prometheus config file their relabeling configs are in.
- Adding an `input_labels` field, which holds further labels and their values, besides the ones that can already be gathered from `input_series`.
- Then we could add a `relabel_rule_test` field, which accepts the name of the job that the relabeling configs belong to, and tests the configs for that job using the labels from `input_series` and `input_labels`.

Example:
```yaml
# rule.yaml
config_files:
 - prometheus.yml

tests:
 - interval: 1m

   input_series:
    - series: 'up{job="prometheus", instance="localhost:9090"}'
      values: '0'

    - input_labels:
       - name: 'foo'
         value: 'bar'

    - relabel_rule_test:
     # Given the labels 'prometheus', 'instance' and 'foo'
     - name: prometheus
       exp_labels:
         - name: 'foo'
           value: 'car'
```
```yaml
# prometheus.yml
...
scrape_configs:
 - job_name: 'prometheus'
   ...
   relabel_configs:
      # This is probably wrong
    - source_labels: ['foo']
      replacement: 'car'
      target_label: 'foo'
```

A possible thing to consider is if we should keep the changed label set and pass it to the `alert` and `promql` tests in the same test group.

**Comment by roidelapluie** [comment]
cc @dgl you are better placed to comment on this

**Comment by dgl** [comment]
Something like this approach could work for _metric_ relabels. Maybe that would be an interesting thing to prototype first...

However I think the real value is something that could test service discovery relabelling configs, as those are usually more complex. The tricky bit is it wouldn't necessarily be possible to infer the job as proposed, as that could be changed by relabelling.

In fact your example nicely shows how the unit tests currently get away without caring about the source of timeseries (internal vs user metrics), but per the docs on metric relabelling:

```
Metric relabeling does not apply to automatically generated timeseries such as `up`.
```

So we'd need to know which series those are, so as not to apply metric relabelling to them. This leads to a potential design: mark series as either processed by service discovery, or from a particular job.

```
- input_series:
    # Series has no labels, as those will be provided by service discovery (or
    # user can override them?)
    - series: 'up{}'
      values: '0x200'
      sd:
        source_job: "a-job-defined-in-config"
        labels:
          __meta_consul_node: node1
          instance: "..."
```

or for a metric_relabel_configs test:


```
- input_series:
    - series: 'something_total{job="a-job"}'
      values: '0+1x200'
      metric_relabel_source_job: "a-job-defined-in-config"
```


> A possible thing to consider is if we should keep the changed label set and
> pass it to the alert and promql tests in the same test group.

It definitely should, in the same way it would in the real system. I suspect actually making that happen may be challenging due to how the promtool unit tests currently pass the series straight to the promql testing code.

I think if that can be done then there's no need for `relabel_config_test`, just let the user match labels normally on their series, rather than making relabels special.
