### ISSUE TITLE
The sampling frequency is changed

### ISSUE THREAD

**Issue by iwctwbai** [prometheus/prometheus#8625]
**What did you do?**
The sampling frequency is changed and automatically resumes after a day
The frequency was set at 1 minute, which suddenly changed to 5 minutes after a few days of operation, and then resumed a day later. This happened twice in 10 days, both of which were automatically resumed one day after the sampling frequency was changed

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	insert output of `uname -srm` here

* Prometheus version:

	insert output of `prometheus --version` here

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```

**Comment by roidelapluie** [comment]
Can you please provide:

- More information about the issue (what is sampling?, why do you think it has changed?)
- The information requested in the message above (prometheus version, relevant logs, platform)

**Comment by iwctwbai** [comment]
I'm sorry I didn't express myself correctly
"sampling frequency" means scrape interval
I use remote writes, where data is written to the data warehouse synchronously.
I observed the data and found that the frequency of data insertion would suddenly change from 1 minute I set to 5 minutes. A day later, it would automatically change to 1 minute (the frequency of data insertion was all 5 minutes this day, I think it is not data loss).

prometheus version：
2.25.0

platform info：
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 8.2.2004 (Core) 
Release:        8.2.2004
Codename:       Core

logs:
How do I get logs

**Comment by roidelapluie** [comment]
What is your prometheus config?

**Comment by iwctwbai** [comment]
@roidelapluie 
```
global:
  scrape_timeout: 60s
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'snmp'
    metrics_path: /snmp
    params:
      module: [if_mib]
    consul_sd_configs:
      - server: '127.0.0.1:8500'
    relabel_configs:
      - source_labels: [__meta_consul_tags]
        regex: .*,switch_snmp,.*
        action: keep
      - source_labels: [__meta_consul_tags]
        regex: .*,module:([^,]+),.*
        replacement: '${1}'
        target_label: __param_module
      - source_labels: [__param_module]
        target_label: job
      - source_labels: [__meta_consul_tags]
        regex: .*,snmp:([^,]+),.*
        replacement: '${1}'
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
    metric_relabel_configs:
      - source_labels: ['instance', 'ifDescr']
        separator: ':'
        target_label: instanceIfDesc

remote_write:
  - url:  "http://localhost:9090/write/"
    write_relabel_configs:
    - source_labels: [__name__]
      regex: '(ifHCInOctets|ifHCOutOctets)'
      action: keep
    queue_config:
      max_samples_per_send: 500
      capacity: 10000
      max_shards: 96

remote_read:
  - url:  "http://localhost:9090/read/"
    read_recent: true
```
