### ISSUE TITLE
The number of series returned by up or probe_success queries do not match the number of targets

### ISSUE THREAD

**Issue by jasonrosy** [prometheus/prometheus#8677]
**What did you do?**

I am running blackbox_icmp checks against 3279 targets.   All checks are running fine and all targets state are showing as "UP".

    blackbox_icmp (3279/3279 up)

**What did you expect to see?**

When I run the query "up" or "probe_success" it should return all 3279 entries.

**What did you see instead? Under which circumstances?**

Queries only return +- 600 entries:

    curl -s "$URL/api/v1/query?query=up" | jq |grep instance  | wc -l
    537

    curl -s "$URL/api/v1/query?query=probe_success" | jq | grep instance  | wc -l
    534

From /tsdb-status:

Name | Count
-- | --
instance | 3279

Top 10 series count by metric names
Name | Count
-- | --
probe_icmp_duration_seconds | 9837
probe_duration_seconds | 3279
probe_ip_protocol | 3279
probe_success | 3279
scrape_duration_seconds | 3279
scrape_samples_post_metric_relabeling | 3279
probe_dns_lookup_time_seconds | 3279
scrape_series_added | 3279
probe_ip_addr_hash | 3279
up | 3279

**Environment**

* System information:

```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", 
GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", 
GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Linux 4.15.0-128-generic x86_64
```

* Prometheus version:

```
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", 
GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", 
GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

 {"status":"success","data":{"startTime":"2021-03-31T07:47:56.541663155Z","CWD":"/prometheus","reloadConfigSuccess":true,"lastConfigTime":"2021-03--31T07:47:58Z","corruptionCount":0,"goroutineCount":3317,"GOMAXPROCS":80,"GOGC":"","GODEBUG":"","storageRetention":"30GiB"}}

```

* Prometheus configuration file:

```
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: 'node'
    file_sd_configs:
    - files:
      - '/etc/prometheus/node-targets.yaml'
    relabel_configs:
    - source_labels: [__address__]
      regex: "([^:]+):\\d+"
      target_label: instance

  - job_name: 'blackbox_icmp'
    scrape_interval: 30m
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
    - files:
      - '/etc/prometheus/icmp-targets.yaml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
```

* Logs:

     No errors found in the log file
