### ISSUE TITLE
$labels.__name__  not work

### ISSUE THREAD

**Issue by chrishyc** [prometheus/prometheus#8703]
in alertmanager my-rule.yaml
```
groups:
- name: svc-alert-rule
  rules:
  - alert: order_amount_sum_total # 订单总额超过100
    expr: order_amount_sum_total>1
    for: 5s
    labels:
      metricsName: '{{$labels.__name__}}'

  - alert: dubbo_invoke_exception
    expr: "rate({__name__=~'dubbo_.*_fail_.*'}[5m])>0"
    for: 5s
    labels:
      metricsName: "{{$labels.__name__}}"
```
order_amount_sum_total.'{{$labels.\_\_name\_\_}}' can get the metric name,but
dubbo_invoke_exception can not get {{ $labels.\_\_name\_\_ }} the metric name

but all can get series
```
curl -g 'http://localhost:9090/api/v1/series?' --data-urlencode 'match[]=order_amount_sum_total'                 
{"status":"success","data":[{"__name__":"order_amount_sum_total","application":"mifi-alert-notice","instance":"localhost:8010","job":"springboot"}]}%
```
```
curl -g 'http://localhost:9090/api/v1/series?' --data-urlencode 'match[]=dubbo_NoticeController_order_fail_total'
{"status":"success","data":[{"__name__":"dubbo_NoticeController_order_fail_total","application":"mifi-alert-notice","instance":"localhost:8010","job":"springboot"}]}% 
```
