### ISSUE TITLE
False Duplicate Rules

### ISSUE THREAD

**Issue by julienmary** [prometheus/prometheus#8704]
promtool find some duplicates rules, which indeed are not.

The example of rules.yml file below will help to reproduce the problem : The label site is fixed at different values, however, rules are detected as duplicated.

**What did you do?**
promtool check rules rules.yml
**What did you expect to see?**
  SUCCESS: 2 rules found
**What did you see instead? Under which circumstances?**
1 duplicate rule(s) found.
Metric: RT_Storm_apple
Label(s):
	severity: ok
Might cause inconsistency while recording expressions.
  SUCCESS: 2 rules found

**Environment**
Ubuntu 18.04
* System information:

	Linux 5.4.0-67-generic x86_64

* Prometheus version:

  promtool --version
  promtool, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64

* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)

* Alertmanager configuration file:
rules.yml
```
- name: RT_Storm
  rules:
  - alert: RT_Storm_apple
    expr: avg(notif_applications_RTT{site="xxxx"}) < 200
    for: 5m
    labels:
      severity: ok
    annotations:
      summary: 1. MXPUSH RTT OK at  {{ $labels.site }}
  - alert: RT_Storm_apple
    expr: avg(notif_applications_RTT{site="yyyy"}) < 200
    for: 5m
    labels:
      severity: ok
    annotations:
      summary: 2. MXPUSH RTT OK at {{ $labels.site }}
```
