### ISSUE TITLE
Service Discovery not displaying correct informations 

### ISSUE THREAD

**Issue by rizerzero** [prometheus/prometheus#8705]
**What did you do?**
Installed prometheus (docker)  but did not yet install the nodeexporter,
when go the prometheus interface if I click on Service Direcotry I can't see that nodeexporter is not up, but when I go to target I get the correct information 
nodeexporter (0/1 up)
**What did you expect to see?**

Service Discovery
nodeexporter (**0 / 1**active targets)
prometheus (1 / 1 active targets)

**What did you see instead? Under which circumstances?**
Service Discovery
nodeexporter (**1 / 1** active targets)
prometheus (1 / 1 active targets)
**Environment**

* System information:

	insert output of `uname -srm` here
Linux 3.10.0-1160.21.1.el7.x86_64 x86_64
* Prometheus version:

	insert output of `prometheus --version` here
v2.26.0
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)
not yet installed 
* Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'docker-host'

rule_files:
  - "alert.rules"
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['nodeexporter:9100']
      
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
```
