### ISSUE TITLE
Hide target's basic_auth from Prometheus Web UI

### ISSUE THREAD

**Issue by Drugoy** [prometheus/prometheus#8715]
**What did you do?**
I've created a json_exporter job with a target with `basic_auth` block (for target, not for exporter!).

**What did you expect to see?**
I expect Web UI NOT to expose target's basic_auth access.

**What did you see instead? Under which circumstances?**
Prometheus Web UI (`/targets` endpoint) exposed target's host in `uri://login:password@host/` format as the value for label `target`.

**Environment**

* System information: Linux 3.10.0-1160.11.1.el7.x86_64 x86_64

* Prometheus version:
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64

* Prometheus configuration file:
```
  - job_name: json_exporter
    scheme: http
    metrics_path: /probe
    scrape_interval: 30s
    static_configs:
      - targets:
        - http://host-1.foobar.com/dummy/data.json
          basic_auth:
            username: mylogin
            password: mypassword
```
