### ISSUE TITLE
Implicit proxies are not respected in remote_write and remote_read configuration

### ISSUE THREAD

**Issue by c16a** [prometheus/prometheus#8720]
**What did you do?**
Passed HTTP_PROXY, HTTPS_PROXY, and NO_PROXY to Prometheus docker container on EC2. 

**What did you expect to see?**
Outbound proxy is enabled for service discovery of targets. Outbound proxy should not be enabled for remote write storage since it's an another ELB in the same VPC.

**What did you see instead? Under which circumstances?**
Outbound proxy is enabled for both target service discovery, and remote write

**Environment**
Prometheus is running as a Podman container on EC2

* System information:
Host: Linux 3.10.0-1160.21.1.el7.x86_64 x86_64
Container: Linux 3.10.0-1160.21.1.el7.x86_64 x86_64

* Prometheus version:

```
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@a67cafebe6d0
  build date:       20210331-11:56:23
  go version:       go1.16.2
  platform:         linux/amd64
```

* Prometheus configuration file:

Container run
```
podman run -d -p 9090:9090 --name=prometheus -v /var/config/prometheus:/etc/prometheus -e HTTP_PROXY="$HTTP_PROXY" -e HTTPS_PROXY="$HTTPS_PROXY" -e NO_PROXY="$NO_PROXY" prom/prometheus:latest --config.file=/etc/prometheus/prometheus.yml
```
Relevant section of configuration
```
scrape_configs:
  - job_name: platform
    scrape_interval: 5s
    ec2_sd_configs:
     - region: es-west-1
       port: 9100
       filters:
       - name: "tag:Name"
         values: ["my-app"]
remote_write:
  - url: ${cortex_url}/api/v1/push
```
* Logs
```
ts=2021-04-14T04:49:25.991Z caller=dedupe.go:112 component=remote level=warn remote_name=823436 url={cortex_url}/cortex/api/v1/push msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: rpc error: code = Unavailable desc = connection error: desc = "{forbidden_error_from_outbound_proxy}"
```
