### ISSUE TITLE
Recording rule adds an empty 'instance' label.

### ISSUE THREAD

**Issue by BeniaminK** [prometheus/prometheus#8726]
**What did you do?**

1. Edit `prometheus.yaml` file:
```
rule_files:
  - "rules_1.yml"
```
2. Edit `rules_1.yml` file
```
groups:
  - name: rule_1
    rules:
      - record: rule:by_slice
        expr: sum by (slice) (prometheus_engine_query_duration_seconds)

```
3. Run prometheus
4. Go into ```http://localhost:9090/federate?match[]={__name__=~%22rule:.*%22}```

**What did you expect to see?**
```
# TYPE rule:by_slice untyped
rule:by_slice{slice="result_sort"} NaN 1618495765341
rule:by_slice{slice="inner_eval"} 0.000783172 1618495765341
rule:by_slice{slice="prepare_time"} 0.000325392 1618495765341
rule:by_slice{slice="queue_time"} 0.00022714099999999999 1618495765341
```

**What did you see instead? Under which circumstances?**
```
# TYPE rule:by_slice untyped
rule:by_slice{slice="result_sort",instance=""} NaN 1618495765341
rule:by_slice{slice="inner_eval",instance=""} 0.000783172 1618495765341
rule:by_slice{slice="prepare_time",instance=""} 0.000325392 1618495765341
rule:by_slice{slice="queue_time*,instance=""} 0.00022714099999999999 1618495765341
```

Problem is with additional instance label that shouldn't be there and is added.
rule:by_slice{slice="result_sort"**,instance=""**} NaN 1618495765341
rule:by_slice{slice="inner_eval"**,instance=""**} 0.000783172 1618495765341
rule:by_slice{slice="prepare_time"**,instance=""**} 0.000325392 1618495765341
rule:by_slice{slice="queue_time"**,instance=""**} 0.00022714099999999999 1618495765341

**Environment**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
* System information:

```
Linux 5.4.0-65-generic x86_64
```

* Prometheus version:

```
prometheus, version 2.25.0 (branch: HEAD, revision: a6be548dbc17780d562a39c0e4bd0bd4c00ad6e2)
  build user:       root@615f028225c9
  build date:       20210217-14:17:24
  go version:       go1.15.8
  platform:         linux/amd64
```

I checked the version `2.20.1` - the same issue occurs.

* Alertmanager version:
non relevant

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules_1.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

* Alertmanager configuration file:
non relevant

* Logs:
normal logs - the recording rules load correctly
