### ISSUE TITLE
consul_sd_configs "tags" requires restart before taking effect

### ISSUE THREAD

**Issue by Nick-Triller** [prometheus/prometheus#8727]
**What did you do?**

I added "tags" to `consul_sd_configs` items to filter the discovered targets. Afterwards, I triggered a config reload with `kill -s SIGHUP`. The updated config was visible in the Prometheus UI.

**What did you expect to see?**

I expected the number of discovered targets for this job to be reduced to the consul services with the tag "PrometheusSlowScrape". There were no services with this tag in my case, therefore the job should have been removed from the /targets page.

**What did you see instead? Under which circumstances?**

The discovered targets did not change until Prometheus was restarted.

**Environment**

* System information:

Host: Linux 4.19.0-9-amd64 x86_64
Prometheus itself runs in a Docker container.

* Prometheus version:

Docker image prom/prometheus:v2.18.1

* Prometheus configuration file:

Before reload:
```yaml
- job_name: example
  scrape_interval: 45s
  scrape_timeout: 40s
  scheme: http
  consul_sd_configs:
  - server: consul-001.example.com:8500
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
```

After reload:
```yaml
- job_name: example
  scrape_interval: 45s
  scrape_timeout: 40s
  scheme: http
  consul_sd_configs:
  - server: consul-001.example.com:8500
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
    tags:
    - PrometheusSlowScrape
```
