### ISSUE TITLE
Promtool test rule failing on expression with `group()` function. 

### ISSUE THREAD

**Issue by vanugrah** [prometheus/prometheus#8730]
Hey folks, ran into a small issue with promtool when testing rules using the `group()` function. 

**What did you do?**
I created the following alert rule (alert.yaml): 
```
groups:
  - name: some/logical/grouping
    rules:
      - alert: deadman
        expr: group by (dc, job) (up{job="octopus"}) == 0
        for: 10m
        labels:
          severity: "critical"
          service: "octopus"
        annotations:
          summary: "Octopus deadman alert"
          description: 'Octopus [{{$labels.dc}}] is down.'
```

I created the following test file (test.yaml): 
```
rule_files:
  - alert.yaml
tests:
  - interval: 1m
    input_series:
      - series: 'up{dc="den", job="octopus", prom="other_labels"}'
        values: '0x50' 
    alert_rule_test:
      - alertname: deadman
        eval_time: 30m 
        exp_alerts:
          - exp_labels:
              severity: "critical"
              service: "octopus"
              dc: "den"
              job: "octopus"
            exp_annotations:
              summary: "Octopus deadman alert"
              description: 'Octopus [den] is down.'
```

**What did you expect to see?**
When running the unit test I expected the test to pass: 
```
➜  promtool test rules test.yaml
Unit Testing:  test.yaml
  SUCCESS
```

**What did you see instead? Under which circumstances?**
Running the follow command I expected to see the unit test to pass, however no alert was fired: 
```
➜  promtool test rules test.yaml
Unit Testing:  test.yaml
  FAILED:
    alertname:deadman, time:30m,
        exp:"[Labels:{alertname=\"deadman\", dc=\"den\", job=\"octopus\", service=\"octopus\", severity=\"critical\"} Annotations:{summary=\"Octopus deadman alert\"}]",
        got:"[]"
```

However, If I update the expression to do the equality check prior to grouping, then the unit test passes: 

```
groups:
  - name: some/logical/grouping
    rules:
      - alert: deadman
        expr: group by (dc, job) (up{job="octopus"} == 0) 
        for: 10m
        labels:
          severity: "critical"
          service: "octopus"
        annotations:
          summary: "Octopus deadman alert"
          description: 'Octopus [{{$labels.dc}}] is down.'
```          
```
➜  promtool test rules test.yaml
Unit Testing:  test.yaml
  SUCCESS
```
  

**Environment**
Localhost

* Promtool version:
```
promtool, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@10ecdb179ff4
  build date:       20210331-11:51:30
  go version:       go1.16.2
  platform:         darwin/amd64
```
