### ISSUE TITLE
Getting rid of default metrics

### ISSUE THREAD

**Issue by BentCoder** [prometheus/prometheus#8739]
Hi,

I am not sure if I am missing something in the documentation but is there a way of getting rid of default metrics such as `coredns_*`, `go_*`, `process_*` and `scrape_*` while using Prometheus in Kubernetes? My current config is below as follows.

Thanks

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: monitoring

rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints"]
    verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
```

```yaml
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 1m
scrape_configs:
- job_name: application-metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - separator: ;
    regex: __meta_kubernetes_service_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service
    replacement: $1
    action: replace
  kubernetes_sd_configs:
  - role: endpoints
    follow_redirects: true
```
