### ISSUE TITLE
Add support for environment variable expansion inside tls_config

### ISSUE THREAD

**Issue by isodude** [prometheus/prometheus#8741]
## Proposal
Add support for environment variable expansion inside tls_config

**Use case. Why is this important?**
To add support for SystemD's LoadCredential directive. This means that one can safely put the certificates in a directory with root-permissions but still run Prometheus with DynamicUser=true.

With DynamicUser=true, there will be a user created for Prometheus that can be quite limited, thus able to secure the whole unit (visible with systemd-analyze security prometheus.service).

Sadly, there is a bug in v237 of SystemD that make it impossible to use ExecPreStart along with LoadCredential. It will most likely stay that way until distros catch up.

Code:

(SystemD)
```
[Unit]
LoadCredential=ca:/etc/prometheus/ssl/host_client.ca
LoadCredential=cert:/etc/prometheus/ssl/host_client.pem
LoadCredential=key:/etc/prometheus/ssl/host_client.key
DynamicUser=true
ConfigurationDirectory=prometheus
StateDirectory=prometheus
ExecStart=/usr/bin/prometheus --config.file="${CONFIGURATION_DIRECTORY}/prometheus.yml" --storage.tsdb.path="${STATE_DIRECTORY}/metrics"
```

(Prometheus)
```
scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
    - files:
      - '/etc/prometheus/json.d/*.json'
    metrics_path: /metrics
    scheme: https
    tls_config:
      'ca_file': "%{CREDENTIALS_DIRECTORY}/ca"
      'cert_file': "%{CREDENTIALS_DIRECTORY}/cert"
      'key_file': "%{CREDENTIALS_DIRECTORY}/key"
```
