### ISSUE TITLE
[feature] Complex filters for Consul discovery

### ISSUE THREAD

**Issue by alexandrovas** [prometheus/prometheus#8749]
## Proposal

In current Consul SD configuration there ability to filter services by tags or node metadata. Fragment of docs:
```
# An optional list of tags used to filter nodes for a given service. Services must contain all tags in the list.
tags:
  [ - <string> ]

# Node metadata key/value pairs to filter nodes for a given service.
[ node_meta:
  [ <string>: <string> ... ] ]
```

I have some metadata keys on which I want to do discovery at the same time. For example, I have key `env` with values `dev` and `stage`. How I can filter this services in one Prometheus job? I am forced to use 2 jobs with different filters.

First job:
```yaml
node_meta:
  env: stage
```

Second job:
```yaml
node_meta:
  env: dev
```

It would be more convenient to add the ability to use more complex filters. Consul API already supports filters with multiple operators: https://www.consul.io/api-docs/features/filtering

**Comment by roidelapluie** [comment]
Prometheus enables you to do this in multiple ways. Can you please provide me the relevant part of your config so I can help you and explain.

**Comment by alexandrovas** [comment]
```yaml
- job_name: stage-exporters
    consul_sd_configs:
      - server: localhost:8500
        node_meta:
          env: stage
        services:
          - haproxy_exporter
          - node_exporter
        refresh_interval: 15s
    relabel_configs:
       ...
```

```yaml
- job_name: dev-exporters
    consul_sd_configs:
      - server: localhost:8500
        node_meta:
          env: dev
        services:
          - haproxy_exporter
          - node_exporter
        refresh_interval: 15s
    relabel_configs:
       ...
```

**Comment by roidelapluie** [comment]
## Option 1

```yaml
- job_name: stage-exporters
    consul_sd_configs:
      - server: localhost:8500
        node_meta:
          env: stage
        services:
          - haproxy_exporter
          - node_exporter
        refresh_interval: 15s
      - server: localhost:8500
        node_meta:
          env: dev
        services:
          - haproxy_exporter
          - node_exporter
        refresh_interval: 15s
    relabel_configs:
       ...
```

## Option 2

```yaml
- job_name: stage-exporters
    consul_sd_configs:
      - server: localhost:8500
        services:
          - haproxy_exporter
          - node_exporter
        refresh_interval: 15s

    relabel_configs:
       - source_labels: [__meta_consul_node_metadata_env]
         regex: 'dev|prod'
         action: keep
       ....
```


Oooops

The prefered way would be option 2 but we do not expose the node metadata as labels. I think we should look into supporting that if that does not require new API calls.

**Comment by roidelapluie** [comment]
So option 2 was what I was mainly thinking about but we miss some labels :)

**Comment by alexandrovas** [comment]
@roidelapluie 
Thank you very much! I will use option 2 :)

**Comment by roidelapluie** [comment]
But it does need not work. I think we do not have the labels required yet.

**Comment by alexandrovas** [comment]
It,s working :) You have a typo in the label name.
My config:
```yaml
scrape_configs:
  - job_name: exporters
    consul_sd_configs:
      - server: localhost:8500
        services:
          - haproxy_exporter
          - node_exporter
    relabel_configs:
      - source_labels: [__meta_consul_metadata_env]
        regex: ^(stage|dev)$
        action: keep
```
