### ISSUE TITLE
Extend gce_sd_config for Managed Services

### ISSUE THREAD

**Issue by tpoindessous** [prometheus/prometheus#8776]
## Proposal
**Use case. Why is this important?**

We use prometheus on GCP. We have exporters which support multi-targets pattern.
For example, we use redis-exporter for GCP Memorystore Redis (Managed Redis).

We would like to have automatic discover of all Memorystore instances and use this information for multi-targets configuration of redis-exporter.

For the moment, we must configure like this (from redis-exporter documentation) : 
```
scrape_configs:
  ## config for the multiple Redis targets that the exporter will scrape
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://first-redis-host:6379
        - redis://second-redis-host:6379
        - redis://second-redis-host:6380
        - redis://second-redis-host:6381
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: <<REDIS-EXPORTER-HOSTNAME>>:9121
```

Maybe the HTTP Generic SD could also be a future solution ?

Thanks !
