### ISSUE TITLE
Suggestion: HTTP based Service Discovery

### ISSUE THREAD

**Issue by seantheyahn** [prometheus/prometheus#8810]
## Proposal
For custom environments, it is very useful to have some sort of HTTP-Request based service discovery, kind of like the scraping itself. In this case it would be pretty easy to implement small helper services (like exporters for metrics) or just dedicate an API route in the services themselves, like the metrics.

Currently, it is almost possible to make such helper services with DNS-based discovery (we could implement helper DNS server services) but they are not as common and easy to implement as the HTTP-based services. Additionally, since the nameserver is not easily configurable in the prometheus.yml per job or per domain, this makes it even harder to configure for multiple helper DNS server services.

Example:

Conifg:
```yaml
- job_name: my_job
  metrics_path: '/metrics'    
  http_sd_configs:
    - urls: ['http://localhost:8080/services', 'https://myusername:mypassword@my.awesomeservice.io/list-services']
```
Request:
`GET /services`
Response:
```json
[{
    "instance": "INSTANCE_A",
    "address": "1.2.3.4:8080"
},{
    "instance": "INSTANCE_B",
    "address": "1.2.3.5:8080"
}]
```
