### ISSUE TITLE
prometheus_sd_discovered_target only shows values from single data center (consul sd)

### ISSUE THREAD

**Issue by m1keil** [prometheus/prometheus#8812]
**What did you do?**
Looking at the value of `prometheus_sd_discovered_target` I noticed that the values for the discovered services are way lower than expected.

**What did you expect to see?**
The same numbers I see under the `/service-discovery` page.
![image](https://user-images.githubusercontent.com/1589008/117760199-8f923a00-b268-11eb-8c60-13e3fd4b15ee.png)

**What did you see instead? Under which circumstances?**
It looks like the numbers I'm getting back are only for one of the Consul datacenters:

![image](https://user-images.githubusercontent.com/1589008/117760318-c8321380-b268-11eb-9e61-2c72e885d222.png)

**Environment**

* System information:

	Linux 4.4.0-64-generic x86_64

* Prometheus version:

	prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
	build user:       root@a67cafebe6d0
	build date:       20210331-11:56:23
	go version:       go1.16.2
	platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'cadvisor'
    consul_sd_configs:
    - datacenter: 'ap-southeast-1'
      services: ['cadvisor']
    - datacenter: 'eu-west-1'
      services: ['cadvisor']
    - datacenter: 'us-west-2'
      services: ['cadvisor']
    - datacenter: 'us-east-1'
      services: ['cadvisor']
    - datacenter: 'ap-southeast-2'
      services: ['cadvisor']

    relabel_configs:
      <omitted for clarity>
<additional scrape configs omitted for clarity>
```
