### ISSUE TITLE
prometheus sometimes irate() is calculated incorrectly

### ISSUE THREAD

**Issue by gupf0719** [prometheus/prometheus#8823]
**What did you do?**

I created two prometheus, the targets they scraped are the same

* Prometheus version:

	prometheus version 2.19.3

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  scrape_timeout: 30s
  evaluation_interval: 1m
  external_labels:
    area: nanjing
    cid: c100
    prometheus: prometheusN2
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager1:9093
    scheme: http
    timeout: 20s
    api_version: v1
rule_files:
- /storage/prometheus/rules/*.yml
- /alert-rule/*.yml
scrape_configs:
- job_name: consul-bm
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{mtype="sys"}'
    - '{__name__="up"}'
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /federate
  scheme: http
  consul_sd_configs:
  - server: http://consul:8500
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
    services:
    - prometheus2BareMetalCluster
  relabel_configs:
  - separator: ;
    regex: __meta_consul_service_metadata_(.+)
    replacement: $1
    action: labelmap
- job_name: consul-k8s
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - '{mtype="sys"}'
    - '{__name__="up"}'
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /federate
  scheme: https
  consul_sd_configs:
  - server: http://consul:8500
    tag_separator: ','
    scheme: http
    allow_stale: true
    refresh_interval: 30s
    services:
    - prometheus2K8sCluster
  tls_config:
    ca_file: /conf/pem/ca.pem
    cert_file: /conf/pem/client.pem
    key_file: /conf/pem/client-key.pem
    insecure_skip_verify: true
  relabel_configs:
  - separator: ;
    regex: __meta_consul_service_metadata_(.+)
    replacement: $1
    action: labelmap
- job_name: paasmgr
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 30s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prom_scrape]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    separator: ;
    regex: (.+)
    target_label: __metrics_path__
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    separator: ;
    regex: ([^:]+)(?::\d+)?;(\d+)
    target_label: __address__
    replacement: $1:$2
    action: replace
  - separator: ;
    regex: __meta_kubernetes_pod_label_(.+)
    replacement: $1
    action: labelmap
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: kubernetes_namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: kubernetes_pod_name
    replacement: $1
    action: replace
```

* Logs:

abnormal prometheus 

![image](https://user-images.githubusercontent.com/10015549/118107214-0f5b0880-b411-11eb-9902-2dd48956ea8a.png)

host_cpu_used_cores: (irate(node_cpu_seconds_total{mode!="idle",clusterId="130000000380"}[5m]))

![image](https://user-images.githubusercontent.com/10015549/118107298-2994e680-b411-11eb-923e-0d48746fd7bf.png)

![image](https://user-images.githubusercontent.com/10015549/118105591-28fb5080-b40f-11eb-9108-a122baa685b7.png)

normal prometheus 

![image](https://user-images.githubusercontent.com/10015549/118106953-c440f580-b410-11eb-8312-1315f5043262.png)

![image](https://user-images.githubusercontent.com/10015549/118107028-dde23d00-b410-11eb-8d17-50ef9bc7dcc4.png)

These two prometheus are exactly the same，but when irate() was calculated, there was a problem
