### ISSUE TITLE
Feature: implement scrape_align_interval and scrape_offset equivalents

### ISSUE THREAD

**Issue by samsk** [prometheus/prometheus#8840]
## Proposal
I have multiple prometheuses scraping the same sources, and I would like to _un-synchronize_ them, so each of them makes the scrape at different, but configurable time point. VictiorMetrics vmagent has interesting options to achieve this:
* scrape_offset
* scrape_align_interval 

Using _hypothetical_ scrape_offset option I could configure my 3 prometheuses, to have each scrape_interval 60s and `scrape_offset` 0s,20s,40s, so every prometheus would scrape the sources at different, but exactly given time point, thus possibly seeing different values and achieve higher granularity without using small scrape_interval.

From vmagent docs:

```


By default vmagent evenly spreads scrape load in time. If a particular scrape target must be scraped at the beginning of some interval, then scrape_align_interval option must be used. For example, the following config aligns hourly scrapes to the beginning of hour:

scrape_configs:
- job_name: foo
  scrape_interval: 1h
  scrape_align_interval: 1h

By default vmagent evenly spreads scrape load in time. If a particular scrape target must be scraped at specific offset, then scrape_offset option must be used. For example, the following config instructs vmagent to scrape the target at 10 seconds of every minute:

scrape_configs:
- job_name: foo
  scrape_interval: 1m
  scrape_offset: 10s

```
