### ISSUE TITLE
Annotations is placed under labels

### ISSUE THREAD

**Issue by RobbanHoglund** [prometheus/prometheus#8864]
**What did you do?**

I added a new alert-rule in prometheus:
cache_alerts.yml

````
groups:
- name: Caches
  rules:  
  - alert: Cache overflow
    expr: ((sum(CACHE_CacheSize{name="MyCache"}) by (name, process) / sum(CACHE_MaxCacheSize{name="MyCache"}) by (name, process)) *100)>100
    for: 10m
    labels:
      severity: warning
      instance: App/{{ $labels.process }}/{{ $labels.name}}
      ci: '{{ $labels.name}}'
      service: App Infrastructure
      tags:  Cache, {{ $labels.name}}
    annotations:
      summary: 'Cache for {{ $labels.name}} has overflowed.'
      description: 'Cache for {{ $labels.name}} has overflowed. Current percentage is {{ $value }} '
      value: '{{ $labels.name}} '
  - alert: Cache overflow
    expr: ((sum(CACHE_CacheSize{name="MyOtherCache"}) by (name, process) / sum(CACHE_MaxCacheSize{name="MyOtherCache"}) by (name, process)) *100)>100
    for: 10m
    labels:
      severity: warning
      instance: App/{{ $labels.process }}/{{ $labels.name}}
      ci: '{{ $labels.name}}'
      service: App Infrastructure
      tags:  Cache, {{ $labels.name}}
    annotations:
      summary: 'Cache for {{ $labels.name}} has overflowed.'
      description: 'Cache for {{ $labels.name}} has overflowed. Current percentage is {{ $value }} '
      value: '{{ $labels.name}} '

````

**What did you expect to see?**

I expected to see this in prometheus alert view when "pending":

````
groups:
- name: Caches
  rules:  
  - alert: Cache overflow
    expr: ((sum(CACHE_CacheSize{name="MyCache"}) by (name, process) / sum(CACHE_MaxCacheSize{name="MyCache"}) by (name, process)) *100)>100
    for: 10m
    labels:
      severity: warning
      instance: App/{{ $labels.process }}/{{ $labels.name}}
      ci: '{{ $labels.name}}'
      service: App Infrastructure
      tags:  Cache, {{ $labels.name}}
    annotations:
      summary: 'Cache for {{ $labels.name}} has overflowed.'
      description: 'Cache for {{ $labels.name}} has overflowed. Current percentage is {{ $value }} '
      value: '{{ $labels.name}} '

````

**What did you see instead? Under which circumstances?**

First alert is "stuck" in pending:
````
name: Cache overflow
expr: ((sum(CACHE_CacheSize{name="MyCache"}) by (name, process) / sum(CACHE_MaxCacheSize{name="MyCache"}) by (name, process)) *100)>100
for: 10m
labels:
annotations: 
ci: {{ $labels.name}}
description: Cache for {{ $labels.name}} has overflowed. Current percentage is {{ $value }} 
instance: App/{{ $labels.process }}/{{ $labels.name}}
service: App Infrastructure
severity: warning
summary: Cache for {{ $labels.name}} has overflowed.
tags: Cache, {{ $labels.name}}
value: {{ $labels.name}} 
````

Second alert is also "stuck" in pending:
````
name: Cache overflow
expr: ((sum(CACHE_CacheSize{name="MyCache"}) by (name, process) / sum(CACHE_MaxCacheSize{name="MyCache"}) by (name, process)) *100)>100
for: 10m
labels:
annotations: 
ci: {{ $labels.name}}
description: Cache for {{ $labels.name}} has overflowed. Current percentage is {{ $value }} 
instance: App/{{ $labels.process }}/{{ $labels.name}}
service: App Infrastructure
severity: warning
summary: Cache for {{ $labels.name}} has overflowed.
tags: Cache, {{ $labels.name}}
value: {{ $labels.name}} 
````

The alerts will be "stuck in pending" because the annotations resides "inside" the "labels" and are treated as "labels". Since the annotations has the value the which is updated for every update these alerts will never goto "firing" state 

**Environment**

* System information:

	Linux 3.10.0-1160.24.1.el7.x86_64 x86_64

* Prometheus version:

	
prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

* Alertmanager version:

build user:       root@00c3106655f8
  build date:       20191211-14:13:14
  go version:       go1.13.5

* Prometheus configuration file:
```

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
