### ISSUE TITLE
Web UI unusable, throws warnings like "JSON.parse: unexpected character at line 1 column 1 of the JSON data" despite working perfectly through API

### ISSUE THREAD

**Issue by Gadiguibou** [prometheus/prometheus#8874]
**What did you do?**

Prometheus is installed on one of our servers. I was tasked with finding the source of errors in the web interface that make it (the UI) unusable despite the API endpoints working perfectly (Alertmanager/Grafana use it with no problem whatsoever).

**What did you expect to see?**

Being able to execute queries, see graphs, alerts and runtime information on the web UI (e.g. localhost:9090).

**What did you see instead? Under which circumstances?**

Under all circumstances, I see error messages each and every time I try to execute a query/see information about the server, etc. except for a few cases when I use the classic UI.

Pages not working in the new UI:

- All of them => failing with errors citing "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

Pages not working in the classic UI:

- Graph => Error loading available metrics!

Screenshot:

![image](https://user-images.githubusercontent.com/34945306/120020434-b0bc8f80-bfb7-11eb-8ead-2f4724030843.png)

**Environment**

* System information:

	Linux 4.19.0-10-amd64 x86_64

* Prometheus version:

	prometheus, version 2.25.2 (branch: HEAD, revision: bda05a23ada314a0b9806a362da39b7a1a4e04c3)
  build user:       root@de38ec01ef10
  build date:       20210316-18:07:52
  go version:       go1.15.10
  platform:         linux/amd64

* Alertmanager version:

	Although Alertmanager is now up and running, it wasn't set up when the bug started

* Prometheus configuration file:
```
global:
  scrape_interval: 1m
  evaluation_interval: 1m
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    scrape_timeout: 30s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: operations-dashboard

    scheme: https
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    static_configs:
      - targets:
          - ops-dashboard.example.com
        labels: { "host": "operations-dashboard" }

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    #   [scheme http]
    static_configs:
      # BEGIN ANSIBLE MANAGED BLOCK example_host
      - targets: ["example_host_name:9100"]
        labels:
          host: "example_host_name"
          team: "IT"
      # END ANSIBLE MANAGED BLOCK example_host
      ... a few more blocks almost identical to this one irrelevant to the bug
```

* Logs: No logs reporting errors/warning. Everything "working as expected".
