### ISSUE TITLE
Broken consoles CSS layout

### ISSUE THREAD

**Issue by bibo38** [prometheus/prometheus#8876]
**What did you do?**

- Downloaded and unpacked prometheus-2.27.1.linux-amd64
- Downloaded and unpacked node_exporter-1.1.2.linux-amd64
- Started the node exporter `./node_exporter`
- Appended the following lines to the `prometheus.yml` (for the node exporter):
```yaml
  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']
```
- Started Prometheus: `./prometheus`
- Navigated to http://localhost:9090/consoles/index.html.example in the browser

**What did you expect to see?**

Some nice dashboards for my jobs.

**What did you see instead? Under which circumstances?**

The layout works kinda (the short menu looks strange) in the Prometheus instance overview:
![Acceptable layout for an dashboard](https://user-images.githubusercontent.com/1812304/120077387-81d31600-c0aa-11eb-8ea1-a5b36775fcd2.png)

But at the node exporter example, the layout falls completely apart, as the first graph got pushed to the right and **the overview table is now at the bottom of the page after all graphs**:
![The right column not shown](https://user-images.githubusercontent.com/1812304/120077422-a7f8b600-c0aa-11eb-87f6-d32fd4c190fa.png)

**Environment**

* System information:

Linux 5.12.6-arch1-1 x86_64
Firefox 88.0.1 (also tested with Chromium 91.0.4472.77)

* Prometheus version:

prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

* Alertmanager version:

not used 

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9100']
```

* ~~Alertmanager configuration file:~~

* Logs: No useful logs
