### ISSUE TITLE
Prometheus 2.24.1 on OpenBSD and database corruption

### ISSUE THREAD

**Issue by precurse** [prometheus/prometheus#8877]
Prometheus 2.24.1 on OpenBSD is failing to compact data into blocks, resulting in a `compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum` error message.

After enough time, Prometheus will crash entirely and panic due to the checksum errors.

I've tested this multiple times using an empty Prometheus data directory, but the same issue recurs. I have validated this on 2 separate OpenBSD 6.9 installs, which rules out any disk corruption issues.

I believe #8799 is related, but I wanted to open a formal bug report for this issue.

**Environment**

* System information:

`OpenBSD 6.9 amd64`

* Prometheus version:
```
prometheus, version 2.24.1 (branch: non-git, revision: non-git)
  build user:       OpenBSD
  build date:       20210419-21:27:27
  go version:       go1.16.2
  platform:         openbsd/amd64

```

* Alertmanager version:

N/A

* Prometheus configuration file:
```
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090','localhost:9100']

```

* Alertmanager configuration file:
N/A

* Logs:
The following error repeats every minute:
```
prometheus[45178]: level=error ts=2021-05-30T16:28:18.965Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
prometheus[45178]: level=error ts=2021-05-30T16:29:19.014Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
prometheus[45178]: level=error ts=2021-05-30T16:30:19.059Z caller=db.go:745 component=tsdb msg="compaction failed" err="compact head: persist head block: 2 errors: populate block: add series: read symbols: invalid checksum; read symbols: invalid checksum"
```

Eventually Prometheus will panic with the following error:
```
panic: corruption in head chunk file /var/prometheus/chunks_head/000001: checksum mismatch expected:00000000, actual:d096d996
```
