### ISSUE TITLE
How to config <headers> in prometheus

### ISSUE THREAD

**Issue by xxj123go** [prometheus/prometheus#8888]
**when I use prometheus <remote_write> with InfluxDB 2.0.6 ，I need to transfor token use headers in**
**prometheus configuration file，but after check config，return a  confusing information**

* System information:

	Linux 4.4.165-1.el6.elrepo.x86_64 x86_64

* Prometheus version:

	prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
  build user:       root@fd804fbd4f25
  build date:       20210518-14:17:54
  go version:       go1.16.4
  platform:         linux/amd64

* Alertmanager version:

	alertmanager, version  (branch: , revision: )
  build user:       
  build date:       
  go version:       go1.9.4

* Prometheus configuration file:
```
#for InfluxDB 2.0.6
remote_write:
  - url: "http://localhost:8086/api/v2/write?org=demo&bucket=demo"
    headers:
      Authorization: Token M33EMR0Kls2miAh3pfqYb7hm9U-xx8ToYGHT
```

* Alertmanager configuration file:
```

```

* Logs:
```
$promtool  check config prometheus.yml 
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: authorization header must be changed via the basic_auth, authorization, oauth2, or sigv4 parameter

```

**Comment by roidelapluie** [comment]
```
remote_write:
  - url: "http://localhost:8086/api/v2/write?org=demo&bucket=demo"
    authorization:
      credentials: M33EMR0Kls2miAh3pfqYb7hm9U-xx8ToYGHT
      type: Token
```

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
