### ISSUE TITLE
Using `time()` in unit tests leads to inconsistent results depending on `for`

### ISSUE THREAD

**Issue by lutzky** [prometheus/prometheus#8892]
Using `time()` in an alert leads to surprising unit-test results. Although I have a [full writeup of my usecase][writeup], I've narrowed the problem down to a minimal failing test case here.

[writeup]: https://stackoverflow.com/questions/67835221/prometheus-unit-test-failing-when-adding-for-to-alert

**What did you do?**

Ran `promtool test rules` on a file with this `test.yml`:

```yaml
rule_files:
  - alert.rules

evaluation_interval: 1s

tests:
  - name: simple
    interval: 1s
    promql_expr_test:
      - expr: time() > bool 5
        eval_time: 1s
        exp_samples:
          - value: 0
      - expr: time() > bool 5
        eval_time: 10s
        exp_samples:
          - value: 1
    alert_rule_test:
      - eval_time: 1s
        alertname: SimpleAlert
        exp_alerts: []
      - eval_time: 10s
        alertname: SimpleAlert
        exp_alerts:
          - exp_labels:
              severity: critical
```

The contents of `alert.rules` are:

```yaml
groups:
  - name: simple
    rules:
      - alert: SimpleAlert
        expr: time() > bool 5
        labels:
          severity: critical
```

**What did you expect to see?**

Either all tests should succeed, or - if the `alert_rule_test` with `eval_time: 1s` fails, so should the `promql_expr_test` at the same time, as they would appear to be testing the same condition.

Furthermore, modifying the alert rule to have `for: 1s` should not change the outcome.

**What did you see instead? Under which circumstances?**

As-is, I get the following failure (note that the `promql_expr_test` does *not* fail):

```
Unit Testing:  /etc/prometheus/test2.yml
  FAILED:
    name: simple,
    alertname:SimpleAlert, time:1s,
        exp:"[]",
        got:"[Labels:{alertname=\"SimpleAlert\", severity=\"critical\"} Annotations:{}]"
```

Furthermore, if I add the line `for: 1s` to the alert rule, the failure changes to this:

```
Unit Testing:  /etc/prometheus/test2.yml
  FAILED:
    name: simple,
    alertname:SimpleAlert, time:10s,
        exp:"[Labels:{alertname=\"SimpleAlert\", severity=\"critical\"} Annotations:{}]",
        got:"[]"
```

**Environment**

* System information:

	Linux 5.4.0-74-generic x86_64

* Prometheus version:

	```
	prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
	  build user:       root@fd804fbd4f25
	  build date:       20210518-14:17:54
	  go version:       go1.16.4
	  platform:         linux/amd64
	```
