### ISSUE TITLE
Consul namespace support

### ISSUE THREAD

**Issue by optiz0r** [prometheus/prometheus#8894]
## Proposal

Consul service discovery only appears to discover services from the default namespace in a multi-namespace consul enterprise. In order to discover services from a namespace, it is necessary to add the query parameter `?ns=namespace_name` or the header `X-Consul-Namespace: namespace_name` to the `/v1/catalog/services` and `/v1/catalog/service/service_name` API calls. Currently there doesn't seem to be a way to do either of these things in the `consul_sd_configs` configuration. 

An additional top-level option in the `consul_sd_configs` to pass along with the query (only if set to preserve existing behaviour and compatibility with consul <1.7) would make it it possible to discover services from consul namespaces.

**Comment by roidelapluie** [comment]
Thank you. That sounds valid to me. however we would handle the technical details about if we use the query parameter or the http header to the underlying consul API we use.

**Comment by fhemberger** [comment]
I'm currently looking into this.

Required code changes seem to be minimal, I just need to check that I'm getting the whole discovery right and everything works for enterprise and open source Consul versions.

**Comment by optiz0r** [comment]
If you need a tester for any code you write, I'm happy to try running from a git branch against namespaces and confirm if working.

**Comment by fhemberger** [comment]
Branch: https://github.com/fhemberger/prometheus/tree/feat/consul_sd_namespace
Commit: https://github.com/fhemberger/prometheus/commit/ddcdd7979cc595eca45f7dd94f6ae2bb44ec57db

prometheus.yml
```yaml
global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "consul"
    consul_sd_configs:
      - server: "localhost:8500"
        namespace: default
    relabel_configs:
      # The "consul" service itself (http://127.0.0.1:8300/metrics) has no prometheus endpoint.
      # https://github.com/hashicorp/consul/issues/764#issuecomment-522225946
      - source_labels: [__meta_consul_service]
        # drop consul self service
        regex: '^consul$'
        action: drop
      - source_labels: [__meta_consul_tags]
        separator: ','
        regex: label:([^=]+)=([^,]+)
        target_label: ${1}
        replacement: ${2}
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_service]
        target_label: service
```

Consul dev setup (open source version):

```bash
mkdir consul.d

echo '{
  "service": {
    "name": "prometheus",
    "tags": [
      "prometheus"
    ],
    "port": 9090
  }
}' > ./consul.d/prometheus.json

consul agent -dev -bind 127.0.0.1 -ui -enable-script-checks -config-dir=./consul.d
```

Trying to add the `namespace` parameter in `prometheus.yml` for the **open source** version will return the following error (as expected):

```
caller=consul.go:390 component="discovery manager scrape" discovery=consul msg="Error refreshing service list" err="Unexpected response code: 400 (Bad request: Invalid query parameter: \"ns\" - Namespaces are a Consul Enterprise feature)"
```
