### ISSUE TITLE
Kubernetes ingress discovery sets invalid scheme when using wildcard certs

### ISSUE THREAD

**Issue by arnisoph** [prometheus/prometheus#8902]
#4329 introduced better ingress scheme detection but doesn't work if the TLS cert is a wildcard cert.

host lookup fails in 
 https://github.com/prometheus/prometheus/blob/7bc11dcb06640ce22b4e15eb52b2c065f97cf79a/discovery/kubernetes/ingress.go#L204 .

Example Ingress Resource

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    prometheus.io/probe: "true"
  name: myingress
  namespace: mynamespace
spec:
  rules:
  - host: foo.example.com
    http:
      paths:
      - backend:
          serviceName: mysvcapp
          servicePort: mysvcport
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '*.example.com'
    secretName: myingress-tls
```

![image](https://user-images.githubusercontent.com/1507504/121154665-6ce34900-c847-11eb-8730-ec149a3719d8.png)
