### ISSUE TITLE
delta([1d]) unexpected result when target switched from server1 to server2

### ISSUE THREAD

**Issue by renchili** [prometheus/prometheus#8905]
**What did you do?**
delta(job:node_filesystem_usage_percent_cmdb:by_mountpoint{cmdb_service_name="xxxxxxxxx",instance="xxxxx:9100"}[1d]) * 100 
![image](https://user-images.githubusercontent.com/33677006/121290578-74732280-c919-11eb-8e27-b65a5a7936c4.png)

**What did you expect to see?**
during this changing period, there should not have any value
**What did you see instead? Under which circumstances?**
on prometheus server 1 there not have datapoint older than June 7 12:30 but  still have delta till June 8 12:30
on prometheus server 2 there not have datapoint earlier than June 7 12:30 but still have delta before June 8 12:30 
**Environment**

* System information:

	Linux 4.15.0-42-shopee-generic x86_64

* Prometheus version:

  prometheus, version 2.19.3 (branch: HEAD, revision: 657ba532e42f1db8d7c77bf802378643da0d3118)
  build user:       root@b99e50bced7c
  build date:       20200724-12:20:53
  go version:       go1.14.6

* Prometheus configuration file:
```
# global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

  # scrape_timeout is set to the global default (10s).
  scrape_timeout:      14s

  external_labels:
      datacenter: "sg"
      prom_cluster: "main"
      prom_role: "raw"
      group: "2"
      replica: "0"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules_*.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

- job_name: "icmp"
  metrics_path: "/probe"
  params:
    module: ["icmp_check"]
  file_sd_configs:
    - files: ["/etc/prometheus/targets_icmp.json"]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115
- job_name: "tcp"
  metrics_path: "/probe"
  params:
    module: ["tcp_check"]
  file_sd_configs:
    - files: ["/etc/prometheus/targets_tcp.json"]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115
- job_name: "dns"
  metrics_path: "/probe"
  params:
    module: ["dns_check"]
  file_sd_configs:
    - files: ["/etc/prometheus/targets_dns.json"]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115

- job_name: 'default'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  metric_relabel_configs:
    - source_labels: [job,tracking_id]
      regex: 'core;\S+'
      action: 'drop'
  file_sd_configs:
    - files: ["/etc/prometheus/targets.json"]
- job_name: 'spex'
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
  metrics_path: '/metrics2'
  honor_labels: true
  file_sd_configs:
    - files: ["/etc/prometheus/targets_spex.json"]
- job_name: 'interval_60s'
  scrape_interval: 60s
  scrape_timeout: 59s
  file_sd_configs:
    - files: ["/etc/prometheus/targets_60s.json"]
- job_name: 'targets_proxy'
  file_sd_configs:
    - files: ["/etc/prometheus/targets_proxy.json"]


- job_name: 15s:http:/metrics
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/prometheus/targets_15s_http__metrics.yml
    refresh_interval: 30s
  tls_config:
    insecure_skip_verify: true
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: sp_xxxx_distr_(client|service)_rpc_flow(in|out)_h_bucket
    replacement: $1
    action: drop
- job_name: 15s:http:/metrics2
  honor_labels: true
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 15s
  metrics_path: /metrics2
  scheme: http
  file_sd_configs:
  - files:
    - /etc/prometheus/targets_15s_http__metrics2.yml
    refresh_interval: 30s
  tls_config:
    insecure_skip_verify: true
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: sp_xxx_distr_(client|service)_rpc_flow(in|out)_h_bucket
    replacement: $1
    action: drop


# Alerting configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - xxxxxxxxxxxx:9093

# "disalbe remote-write temp,if want enable, can delete env condition"
# remote write
remote_write:
  - url: http://localhost:19211/api/v1/receive
    write_relabel_configs:
    - source_labels: [__name__]
      regex: ^job:.+$
      action: drop
    remote_timeout: 90s
    queue_config:
      capacity: 100000
      max_shards: 120
      min_shards: 60 # some new workers loads are very lower, if this value set too large, will delay
      max_samples_per_send: 40000 # if increase will get spikes on latency
      batch_send_deadline: 10s
      min_backoff: 100ms
      max_backoff: 1000ms
```
