### ISSUE TITLE
Prometheus does not send Authorization header to alert manager

### ISSUE THREAD

**Issue by brittandeyoung** [prometheus/prometheus#8910]
**What did you do?**
I implemented basic authenticaiton within the IIS Site to reverse proxy to Alertmanager. I then added Basic Auth configuration as specified in the documentation to the section:

```
alerting:
  alertmanagers:
```

**What did you expect to see?**

I expected to see the authorization header be built and sent to Alert Manager when sending an alert. 

**What did you see instead? Under which circumstances?**

The Authorization header was not being sent by the prometheus server at all to the Alert Manager server. This was verified by adding the `Authorization` header to the IIS logging and seeing that it was missing entirely. 

I also found the following in the error logs for prometheus server:
```
level=error ts=2021-06-08T19:01:28.700Z caller=notifier.go:527 component=notifier alertmanager=http://Servername/api/v2/alerts count=9 msg=“Error sending alert” err=“bad response status 401 Unauthorized”
```
**Environment**

* System information:

I am currently running prometheus on a windows server:

```
System Information report written at: 06/09/21 15:07:27
System Name: VDCPROMPD01
[System Summary]

Item	Value	
OS Name	Microsoft Windows Server 2019 Datacenter	
Version	10.0.17763 Build 17763	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	VDCPROMPD01	
System Manufacturer	VMware, Inc.	
System Model	VMware Virtual Platform	
System Type	x64-based PC	
System SKU		
Processor	Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz, 2295 Mhz, 2 Core(s), 2 Logical Processor(s)	
BIOS Version/Date	Phoenix Technologies LTD 6.00, 12/12/2018	
```

* Prometheus version:
```
prometheus, version 2.26.0 (branch: HEAD, revision: 3cafc58827d1ebd1a67749f88be4218f0bab3d8d)
  build user:       root@086478f2a550
  build date:       20210331-11:56:24
  go version:       go1.16.2
  platform:         windows/amd64
```
* Alertmanager version:

```
c:\tools\alertmanager>alertmanager.exe --version
alertmanager, version 0.21.0 (branch: HEAD, revision: 4c6c03ebfe21009c546e4d1e9b92c371d67c021d)
  build user:       root@dee35927357f
  build date:       20200617-08:59:53
  go version:       go1.14.4
```

* Prometheus configuration file:
```
# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - scheme: https
      basic_auth:
        username: prometheus_svc
        password: '#{PROMETHEUS_SVC_PASSWORD}#'
    - static_configs:
      - targets:
        - 'vdcalrtmpd01.hagerty.com'

```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
level=error ts=2021-06-08T19:01:28.700Z caller=notifier.go:527 component=notifier alertmanager=http://Servername/api/v2/alerts count=9 msg=“Error sending alert” err=“bad response status 401 Unauthorized”
```

**Comment by juliusv** [comment]
Hi,

The issue here is a YAML one: in your list of Alertmanagers, you have one Alertmanager entry which contains only the auth information (but not Alertmanager targets), and you have a second entry which contains no auth information, but has an Alertmanager target. You probably want:

```yaml
# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - scheme: https
      basic_auth:
        username: prometheus_svc
        password: '#{PROMETHEUS_SVC_PASSWORD}#'
      static_configs:
      - targets:
        - 'vdcalrtmpd01.hagerty.com'
```

I'm closing the issue as this is most likely the issue here, but please reopen it if there's a problem beyond that.
