### ISSUE TITLE
rate function tailing bug

### ISSUE THREAD

**Issue by rocdove** [prometheus/prometheus#8938]
**What did you do?**

Some devices take a long time to collect SNMP. Here, a relatively long timeout time 'scrape_timeout: 3m' is configured.When 'rate' was used to calculate 'ifHCInOctets', serious tailings were found.

![image](https://user-images.githubusercontent.com/8022710/121986085-839a1a80-cdc8-11eb-84e5-5ee81f03bb46.png)
View current data:
![image](https://user-images.githubusercontent.com/8022710/121986390-fe633580-cdc8-11eb-848d-891fdeecd693.png)

The data seen after the tail disappears:
![image](https://user-images.githubusercontent.com/8022710/121986489-26529900-cdc9-11eb-9a32-c1226e266479.png)

Look at the source code, found that there is a Bug. https://github.com/prometheus/prometheus/blob/ba76bceb6b09eaa4fa1f9744ac164d684e348886/promql/functions.go#L125

`extrapolateToInterval` should be used here instead of `ms.Range.Seconds()`.

**Environment**

* Prometheus version:

	v2.27.1

prometheus job config:
```
  - job_name: 'snmp_h3c'
    scrape_interval: 4m
    scrape_timeout: 3m
    file_sd_configs:
      - refresh_interval: 5m
        files:
          - /etc/prometheus/targets/snmp_h3c.yml
    metrics_path: /snmp
    params:
      module: [hh3c]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9116
```
