### ISSUE TITLE
Hetzner discovery doesn't discover labels with empty values.

### ISSUE THREAD

**Issue by jonathantullett** [prometheus/prometheus#9023]
**What did you do?**
Hetzner supports servers having labels with keys, but optional values.  I added a label which contains a key and empty value. This works as expected on the Hetzner site.

**What did you expect to see?**

Within 'Discovered Labels' on the service-discovery tab, I expected to see a label for this key.

**What did you see instead? Under which circumstances?**

No label for the key with an empty value. Other keys which have values work as expected,
i.e. ` __meta_hetzner_hcloud_label_env="staging"`

**Environment**

* System information:

Official docker images

* Prometheus version:

	v2.28.0 from hub.docker.com

* Prometheus configuration file:
Relevant section:
```
  - job_name: node_exporter_hetzner
    hetzner_sd_configs:
      - bearer_token: xxxxxx
        role: hcloud
    relabel_configs:
      - source_labels: [ __meta_hetzner_hcloud_label_env ]
        regex: staging
        action: keep
      - source_labels: [ __meta_hetzner_server_name ]
        target_label: __address__
        replacement: '$1:9100'
      - source_labels: [ __address__ ]
        target_label: instance
        regex: ([[:alnum:]-]+)[.:].*
        replacement: $1
      - source_labels: [ job ]
        target_label: job
        replacement: node_exporter
```

* Logs:
```
No useful logs output by the container with log.level=debug
```
