### ISSUE TITLE
The configuration file will not change after reload

### ISSUE THREAD

**Issue by ktpktr0** [prometheus/prometheus#9029]
I use docker swarm to run the latest Prometheus, and I've added -- web. Enable life.
```
version: '3.5'

services:
  prometheus:
    image: prom/prometheus:v2.28.0
    hostname: prometheus
    networks:
      - monitor
    ports:
      - 9090:9090
    volumes:
      - /data/conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/conf/prometheus/rules:/etc/prometheus/rules
      - /data/conf/prometheus/targets:/etc/prometheus/targets
      - /data/data/prometheus1:/prometheus1
      - /data/data/prometheus2:/prometheus2
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=7d'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
```

When I modify the Prometheus configuration file, I execute curl - xpost http://127.0.0.01 : 9090 / - / reload, the log is as follows
```
level=info ts=2021-07-01T09:34:47.853Z caller=main.go:964 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2021-07-01T09:34:47.865Z caller=main.go:995 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=11.321601ms remote_storage=103.371µs web_handler=452ns query_engine=1.321µs scrape=96.991µs scrape_sd=94.504µs notify=48.383µs notify_sd=17.444µs rules=10.444654ms
level=info ts=2021-07-01T09:36:05.519Z caller=main.go:964 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2021-07-01T09:36:05.529Z caller=main.go:995 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=9.900864ms remote_storage=104.986µs web_handler=585ns query_engine=1.598µs scrape=83.833µs scrape_sd=65.836µs notify=9.738µs notify_sd=17.339µs rules=9.158064ms
```
But I went into the container and found that the content of Prometheus. YML had not changed
