### ISSUE TITLE
Kubernetes scraping does not use kubeconfig auth for endpoints discovered

### ISSUE THREAD

**Issue by jbgachot** [prometheus/prometheus#9052]
**What did you do?**
I used the "new" kubernetes discovery with a kubeconfig file to access cadvisor endpoints

**What did you expect to see?**
Prometheus discover all the nodes endpoints correctly and access to them.

**What did you see instead? Under which circumstances?**

Prometheus indeed discover the nodes correctly. But can't access the cadvisor endpoint receiving a `403 Forbidden` because prometheus tries to connect with an anonymous user.

* Prometheus version: 2.28.0

* Alertmanager version: N/A

* Prometheus configuration file:
```yml
  - job_name: cadvisor
    kubernetes_sd_configs:
    - role: node
      kubeconfig_file: /var/lib/prometheus/.kube/config
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - replacement: $EKS_API_ENDPOINT:443
      target_label: __address__
    - regex: (.+)
      replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
      source_labels:
      - __meta_kubernetes_node_name
      target_label: __metrics_path__
    scheme: https
    tls_config:
      insecure_skip_verify: true
```

* Logs:

Prometheus log :
```
Jul 05 16:58:42 ip-1-2-3-4 prometheus[31195]: level=debug ts=2021-07-05T14:58:42.877Z caller=scrape.go:1236 component="scrape manager" scrape_pool=cadvisor target=https://xxxxxx.eks.amazonaws.com:443/api/v1/nodes/ip-1-2-3-4.eu-west-X.compute.internal/proxy/metrics/cadvisor msg="Scrape failed" err="server returned HTTP status 403 Forbidden"
```

Kubernetes log :
```json
{
    "kind": "Event",
    "apiVersion": "audit.k8s.io/v1",
    "level": "Request",
    "auditID": "223b12f1-aaba-408f-b2fc-7a292606c946",
    "stage": "ResponseStarted",
    "requestURI": "/api/v1/nodes/ip-1-2-3-4.eu-west-X.compute.internal/proxy/metrics/cadvisor",
    "verb": "get",
    "user": {
        "username": "system:anonymous",
        "groups": [
            "system:unauthenticated"
        ]
    },
    "sourceIPs": [
        "4.3.2.1"
    ],
    "userAgent": "Prometheus/2.28.0",
    "objectRef": {
        "resource": "nodes",
        "name": "ip-1-2-3-4.eu-west-X.compute.internal",
        "apiVersion": "v1",
        "subresource": "proxy"
    },
    "responseStatus": {
        "metadata": {},
        "status": "Failure",
        "reason": "Forbidden",
        "code": 403
    },
    "requestReceivedTimestamp": "2021-07-05T14:08:25.734129Z",
    "stageTimestamp": "2021-07-05T14:08:25.734334Z",
    "annotations": {
        "authorization.k8s.io/decision": "forbid",
        "authorization.k8s.io/reason": ""
    }
}
```

As we can see here, the user used is system:anonymous for the metrics retrieval. Except that the user from kubeconfig is not system:anonymous and for service discovery, the user seems to be the one I have set up in the kubeconfig.
