### ISSUE TITLE
Allow scrape basic_auth password as a bcryp hash like in the web.yml

### ISSUE THREAD

**Issue by ggregoire** [prometheus/prometheus#9062]
## Proposal

It seems like `basic_auth.password` in the `prometheus.yml` accepts only passwords in clear.

Could it be possible to allow a bcrypt hash like in the `web.yml`?

web.yml:

```yml
basic_auth_users:
  admin: $2y$12$c5H2g88o6KjelhUxOPFJ8eaF5L26XZOKM619XaK5c/SZEuWB0SE42
```

prometheus.yml:

```yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: ["prometheus:9090"]
    basic_auth:
      username: admin
      password: $2y$12$c5H2g88o6KjelhUxOPFJ8eaF5L26XZOKM619XaK5c/SZEuWB0SE42
```
