### ISSUE TITLE
Enable the use of proxy_url per target

### ISSUE THREAD

**Issue by Soprano74** [prometheus/prometheus#9074]
## Proposal

make the proxy_url option available in a file_sd_config file.
If you have a need for proxy_url, you can currently only define this per job as such:

```
job_name: 'generated-files'
 proxy_url: "http://somehost.local:8080"
 file_sd_configs:
 - files:
   - 'generated-*.yml'
```

but if you generate these files on a per host basis, they now all share the same proxy_url.
if we can put the proxy_url in the target file as such:

```
- targets:
  - "shared2.kobalt.cyso.net:9100"
- proxy_url: "http://somehost.local:8080
```

then that would solve this and we can generate the 'generated-*.yml' files and specifc a proxy_url if needed
