### ISSUE TITLE
Static labels for scape jobs

### ISSUE THREAD

**Issue by mattkanwisher** [prometheus/prometheus#908]
We do discovery of our scrape jobs by using dns_sd_configs, however whats really awkward is we have some static labels that we want to apply to all the machines in the group. We end up having to do relabeling with some strange regexes when all we wanted was just labels. Would you guys be open to taking a pull request in the future that introduces labels at the job level? Or is the are reason you don't do it?

**Comment by beorn7** [comment]
The domain expert here is @fabxc (currently on vacation).

However, why do you have to do "strange" regexps? `.*` against a label that is always there (e.g. `__name__`) should just work. Sure, it's a bit of syntactic noise, but it avoids introducing yet another layer of labeling (there are so many already, and the `labels` statement in the `target_group` is arguably historically grown...).

But definitely something to discuss with @fabxc and @juliusv once they are back.

**Comment by mattkanwisher** [comment]
For example I want 2 static labels one is region: "new york", other is service: "abc service", however there is no way for me to put that in each scrape group. Either I have to do it at the global level or I have to do relabeling. Global won't work, I have many different service groups and regions. Target groups aren't useful if your using DNS or other discovery methods. Not sure what your getting at __name__, not sure its going to do anything in my usecase, I tried it with no effect. Let me show you the config section


```
scrape_configs:
  - job_name: clusterxyx-apiname1
    labels:
    target_groups:
    dns_sd_configs:
    - names:
      - _clusterxyz._tcp.apiname1
    scrape_interval:
    scrape_timeout:
    metrics_path: /metrics
    relabel_configs:
    - source_labels:
      - __address__
      target_label: region
      regex: .*\.(\w+)\.test\.somewebsite\.com.*
      replacement: $1
      action: replace
    - source_labels:
      - job
      target_label: service
      regex: (.*)
      replacement: $2
      action: replace

```

What would be nice is a labels section under the -job_name section instead of relabeling

**Comment by matthiasr** [comment]
@beorn7 I think this makes sense from a usage perspective. If you have an SD mechanism that can discover everything and knows what is what (e.g. location, other tags) you should be able to transport this through. The "old school" way we currently do is having long lists of jobs, but I'd consider that a workaround.

**Comment by beorn7** [comment]
@mattkanwisher Just for my understanding: Is your problem that something in your config doesn't work as expected, or are you just dissatisfied with the syntactic noise?

What I meant, there is no need to extract your new label from the regexp. `replacement` could be static. You could do:

```
scrape_configs:
  - job_name: clusterxyx-apiname1
    labels:
    target_groups:
    dns_sd_configs:
    - names:
      - _clusterxyz._tcp.apiname1
    scrape_interval:
    scrape_timeout:
    metrics_path: /metrics
    relabel_configs:
    - source_labels:
      - __address__ # always exists
      target_label: region
      regex: .* # always matches
      replacement: new york
      action: replace
    - source_labels:
      - __address__ # always exists
      target_label: service
      regex: .* # always matches
      replacement: abc service
      action: replace
```
