### ISSUE TITLE
Recording rules missing some time series

### ISSUE THREAD

**Issue by omron93** [prometheus/prometheus#9092]
**What did you do?**

We have network devices and from those devices we scrape every 5 min data via snmp exporter. We have recording rules to compute 5min increase .
We have two prometheus nodes, configured the same (with ansible) - so running the scrapes and rules evaluation on each of those.

**What did you expect to see?**

Recording rules producing correct time series. And we can rely that prometheus will evaluates the rules correctly.

**What did you see instead? Under which circumstances?**

The issue we see is that for some instances (network devices) the rule produces no data. When I run exactly the same query in grafana against that node, the data looks correct. Also the second prometheus node is producing the correct data.

Originally we had slightly different version of the rule and this rule on a different node was giving wrong results (again some instances missing), and the prometheus node failing with the current version was working fine. So not an sporadic failure.

**Environment**

* System information:

	Linux 4.15.0-144-generic x86_64

* Prometheus version:

	prometheus, version 2.27.1 (branch: HEAD, revision: db7f0bcec27bd8aeebad6b08ac849516efa9ae02)
	  build user:       root@fd804fbd4f25
	  build date:       20210518-14:17:54
	  go version:       go1.16.4
	  platform:         linux/amd64

* Prometheus configuration file:

Prometheus run as
```
/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --query.lookback-delta=9m --storage.tsdb.retention.time=10y --storage.tsdb.max-block-duration=10d --web.enable-admin-api --web.enable-lifecycle --storage.tsdb.allow-overlapping-blocks --storage.tsdb.path=/var/lib/prometheus/prometheus/data
```

Recording rule
```
groups:
  - name: stats_api_aggregate_snmp_xxxca
    interval: 300s
    rules:
    - record: ifHCInOctets:increase
      expr: increase(ifHCInOctets{network_key="xxx"}[10m])/2
      labels:
        'job': 'rule-v2'
```

* Logs:

Can't see anything in prometheus logs. Where to find more details?
