### ISSUE TITLE
Prometheus kuberentes-pods Get “https:// xx.xx.xx:443 /metrics”: dial tcp xx.xx.xx:443: connect: connection refused

### ISSUE THREAD

**Issue by tommy24b** [prometheus/prometheus#9110]
I have configured Prometheus on one of the kubernetes cluster node using this https://devopscube.com/install-configure-prometheus-linux/ after that I added following prometheus.yml file. I can list nodes and apiservers but for pods, all the pods shows down and error Get "https:// xx.xx.xx:443 /metrics": dial tcp xx.xx.xx:443: connect: connection refused and for some pods the status is unknown. when i can list the nodes and api servers? why it shows connection refused? is it a bug or some network issue on my end?

````
Cat prometheus.yml



global:
  scrape_interval: 1m
 
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: \['localhost:9090'\]
 
# metrics for default/kubernetes api's from the kubernetes master
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
      bearer_token_file: /dfgdjk/token
      api_server: https://masterapi.com:3343
      tls_config:
        insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /dfgdjk/token
    scheme: https
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: \[__meta_kubernetes_namespace\]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: \[__meta_kubernetes_pod_name\]
      action: replace
      target_label: kubernetes_pod_name
 
# metrics for default/kubernetes api's from the kubernetes master
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
      api_server: https://masterapi.com:3343
      bearer_token_file: /dfgdjk/token
      tls_config:
        insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /dfgdjk/token
    scheme: https
    relabel_configs:
    - source_labels: \[__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name\]
      action: keep
      regex: default;kubernetes;https][1]

````
![prometheus_target](https://user-images.githubusercontent.com/56851072/126691153-15c01fc7-963c-43f4-9445-e4b9ec7fecb9.jpg)
