### ISSUE TITLE
Out-of-order samples when relabeling metrics that contains timestamps.

### ISSUE THREAD

**Issue by skgsergio** [prometheus/prometheus#9113]
**What did you do?**
Create an scrape job that scrapes `cavisor` and drops the `id` label using metric relabeling.

(This is the minimal working example for reproducing the issue, I've found it scraping `cadvisor` pods in a k8s cluster using prometheus' Kubernetes SD for discovery.)

**What did you expect to see?**
The metrics are scraped with the label `id` dropped.

**What did you see instead? Under which circumstances?**
A lot of `Error on ingesting out-of-order samples` errors in the logs. However, when it doesn't fail the metric is scrapped with the label correctly removed.

**Environment**

* System information:
```
Linux 5.13.4-arch1-1 x86_64
```

* Prometheus version:
```
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64
```

* Prometheus configuration file:
```yaml
---
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metric_relabel_configs:
      - action: labeldrop
        regex: id
```

* Logs:
```
level=warn ts=2021-07-26T18:06:28.352Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=20
level=warn ts=2021-07-26T18:06:43.286Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=643
level=warn ts=2021-07-26T18:06:58.281Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=160
level=warn ts=2021-07-26T18:07:13.293Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=1017
level=warn ts=2021-07-26T18:07:28.489Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=877
level=warn ts=2021-07-26T18:07:43.288Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=572
level=warn ts=2021-07-26T18:07:58.319Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=767
level=warn ts=2021-07-26T18:08:13.353Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=1050
level=warn ts=2021-07-26T18:08:28.316Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=1070
level=warn ts=2021-07-26T18:08:43.470Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=1073
level=warn ts=2021-07-26T18:08:58.355Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=919
level=warn ts=2021-07-26T18:09:13.336Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=523
level=warn ts=2021-07-26T18:09:28.328Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=387
level=warn ts=2021-07-26T18:09:43.489Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=486
level=warn ts=2021-07-26T18:09:58.320Z caller=scrape.go:1501 component="scrape manager" scrape_pool=cadvisor target=http://cadvisor:8080/metrics msg="Error on ingesting out-of-order samples" num_dropped=509
```

**More info**
`cadvisor` adds the timestamp to its metrics and if you add `honor_timestamps: false` to the scrape job the errors stop.

This makes me think that what is happening is that when the sample is relabeled the sample timestamp is replaced with the current time and stored like that, then when the next scrape happens if the sample still has the previous timestamp Prometheus says that is out-of-order as the latest sample known by Prometheus has a greater timestamp than the one from the sample.

Something like this:

Scrape 1 at time `0000000030`:
- Sample: `patata{type="frita",id="1234"} 1337 0000000010`
- Is timestamp `0000000010` > timestamp of the last known sample by prometheus in `patata` series (no data in series yet)? No, continue.
- Relabel, drop `id`. Result: `patata{type="frita"} 1337 0000000030`
- Store: `patata{type="frita"} 1337 0000000030`

Scrape 2 at time `0000000045`:
- Sample: `patata{type="frita",id="1234"} 1337 0000000010`
- Is timestamp `0000000010` > timestamp of the last known sample by prometheus in `patata` series (`0000000030`)? Yes, drop sample and throw out-of-order sample ingestion error.

I created a docker-compose with a Prometheus config ready to go for reproducing this issue, just save this two files and run `docker-compose up`:

<details>
  <summary>docker-compose.yml</summary>

  ```yaml
  ---
  version: '3'
  services:
    cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.37.5
      ports:
        - 8080:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
    prometheus:
      image: quay.io/prometheus/prometheus:v2.28.1
      ports:
        - 9090:9090
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
  ```
</details>

<details>
  <summary>prometheus.yml</summary>

  ```yaml
  ---
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'cadvisor'
      # honor_timestamps: false
      static_configs:
        - targets: ['cadvisor:8080']
      metric_relabel_configs:
        - action: labeldrop
          regex: id
  ```
</details>
