### ISSUE TITLE
docker_sd: host network mode not supported

### ISSUE THREAD

**Issue by lod** [prometheus/prometheus#9116]
### Issue

docker_sd extracts the __address__ from docker's API NetworkSettings.Network.*.IPAddress

This is not set for clients that use the host network mode.

The __address__ ends up being ':80'

For host mode the ip address should be substituted with localhost  
(support for connecting to a remote host docker socket should also be considered)

Additionally, port specification is not supported in host network mode.

docker-compose does not allow ports to be specified.  
docker allows ports to be specified but ignores them, I don't know if they are accessible via the API

The port could be extracted from the labels

### Workaround

```
(in scrape_configs job section)
  relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_port]
        target_label: __address__
        replacement: 'localhost:${1}'
```

### Documentation

Given that a viable workaround exists using relabel_configs, updating the documentation to make the issue explicit and adding an example workaround to the sample config file may be a cleaner solution.

The workaround could be further enhanced by checking for the generated ipaddress label and using an explicit drop action. This could lead to two docker_sd_config discovery groups, one with host networking, one without.
