### ISSUE TITLE
`kuma_sd` does not report all targets

### ISSUE THREAD

**Issue by austince** [prometheus/prometheus#9155]
**What did you do?**

Use the new `kuma_sd` to discover scrape targets.

**What did you expect to see?**

5 targets.

**What did you see instead? Under which circumstances?**

Only 1 target, which changes when the discovery reports new targets.

It looks like they are just being overwritten, likely because of the "Source" of all the groups is `"kuma"`, which is used as a key for targets in the manager. 

We could solve this by namespacing group sources, i.e.: instead of `"kuma"`, `"kuma/{mesh}/{dataplane}" which is unique.

* Prometheus version: 2.29-rc.0

* Prometheus configuration file:
```
global:
  evaluation_interval: 1m
  scrape_interval: 10s
  scrape_timeout: 10s
scrape_configs:
  - honor_labels: true
    job_name: 'kuma-dataplanes'
    kuma_sd_configs:
      - server: "http://localhost:5676"
```

cc @roidelapluie 

I'll have a fix PR in shortly.
