### ISSUE TITLE
Option to disable security on Prometheus health endpoints, /-/healthy and /-/ready

### ISSUE THREAD

**Issue by amrit-35** [prometheus/prometheus#9166]
## Proposal
I am using Prometheus in kubernates, and recently enabled basic Auth with version 2.28. But it turn out Prometheus also enables security on health endpoints. Their is no way to safely provide credentials for liveness and readiness probe. Following works not really the safest option. I think we should have a option to disable security on these endpoints.

```
livenessProbe:
      httpGet:
        path: /-/healthy
        port: 9090
        httpHeaders:
        - name: Authorization
          value: Basic dXNlcjpwYXNz
```
