### ISSUE TITLE
Prometheus official prom/prometheus:latest container doesn't correctly substitute env variables.

### ISSUE THREAD

**Issue by ArKam** [prometheus/prometheus#9174]
## Description of the issue
When using a docker-compose that use both env_file and command directive to set and use inside container's variable, the container isn't able to correctly substitute variable.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.2, build unknown (pip install)
```

**Output of `docker version`**
```
Docker version 20.10.8, build 3967b7d
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  prometheus:
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.listen-address=$${LISTEN_ADDRESS}:$${LISTEN_PORT}
    - --web.config.file=/etc/prometheus/web.yml
    container_name: prometheus
    environment:
      LISTEN_ADDRESS: 192.168.1.74
      LISTEN_PORT: '9090'
    image: prom/prometheus:latest
    network_mode: host
    volumes:
    - read_only: true
      source: /home/flint/services/prometheus/conf.d/prometheus.yml
      target: /etc/prometheus/prometheus.yml
      type: bind
    - read_only: true
      source: /home/flint/services/prometheus/conf.d/web.yml
      target: /etc/prometheus/web.yml
      type: bind
    - source: prometheus
      target: /prometheus
      type: volume

version: '3.8'
volumes:
  prometheus: {}
```

**Output of `prometheus.env` env_file**
```
LISTEN_ADDRESS=192.168.1.74
LISTEN_PORT=9090
```

## Steps to reproduce the issue

1. do a `docker-compose up -d prometheus`
2. do a `docker logs -f prometheus` and get the error message:
```
(docker) flint@cmc01:~/services$ docker logs -f prometheus
parse external URL "": parse "http://cmc01.flint.net:${LISTEN_PORT}/": invalid port ":${LISTEN_PORT}" after host
```

### Observed result
The container correctly substitute the first part of the command using escaped variable but doesn't do it for the port variable.
I even tried to have only one variable such as: 
`LISTEN_ADDRESS=192.168.1.74:9090`
or
`LISTEN_ADDRESS="192.168.1.74:9090"`
using these format the container is complaining as:
```
(docker) flint@cmc01:~/services$ docker logs -f prometheus
parse external URL "": address ${LISTEN_ADDRESS}: missing port in address
```
What's really annoying is that docker-compose config shows that docker-compose did created the appropriate environment variables.
Even a `docker-inspect prometheus` do confirm than the OS env variable is fully filled:

```
[...]
        "Config": {
            "Hostname": "cmc01.bitswalk.net",
            "Domainname": "",
            "User": "nobody",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9090/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "LISTEN_ADDRESS=192.168.1.74:9090",
                "affinity:container==f0832401567e76bd6daa74bbd9cfd66a081aab4f2faba6c00e51cb379a97395d",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "--config.file=/etc/prometheus/prometheus.yml",
                "--storage.tsdb.path=/prometheus",
                "--web.console.libraries=/usr/share/prometheus/console_libraries",
                "--web.console.templates=/usr/share/prometheus/consoles",
                "--web.listen-address=${LISTEN_ADDRESS}",
                "--web.config.file=/etc/prometheus/web.yml"
            ],
            "Image": "prom/prometheus:latest",
            "Volumes": {
                "/prometheus": {}
            },
            "WorkingDir": "/prometheus",
            "Entrypoint": [
                "/bin/prometheus"
            ],
[...]
```

At first I thought it was a docker-compose issue but it work with any other container such as a simple hello container the just have the following command directive:
```
command: [
  'bash',
  '-c',
  'echo "$$LISTEN_ADDRESS:$$LISTEN_PORT"'
```

### Expected result
prometheus container should start with the command correctly substituted as: `--web.listen.address 192.168.1.74:9090`

## Additional information

**OS:** Ubuntu 21.04
**HW:** Raspberry PI 4 8GB.
**docker-compose installation method:** `pip install docker-compose`

I think you've got pretty much every information that I've got so far.
