### ISSUE TITLE
Prometheus reports an error EOF when sending alert to alertmanager

### ISSUE THREAD

**Issue by jialanli** [prometheus/prometheus#9176]
**Related background：**
prometheus version :  2.28.1
alertmanager version:  0.22.2   (They are the latest version)

I used docker to build an alertmanager cluster (started the alertmanager cluster consisting of two instances), and started two prometheus services at the same time. At the beginning, the environment was normal and the alert emails were also received. It didn't take long for me to start prompting EOF.

Tried: Replace other versions of prometheus and alertmanager, restart docker.service, etc., all of which are not resolved

**error info:**
prometheus report:
caller=notifier.go:527 component=notifier alertmanager=http://10.10.20.11:19194/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.10.20.11:19194/api/v2/alerts\": EOF                                                                         
caller=notifier.go:527 component=notifier alertmanager=http://10.10.20.11:19193/api/v2/alerts count=1 msg="Error sending alert" err="Post \"http://10.10.20.11:19193/api/v2/alerts\": EOF

alertmanager report:
component=cluster memberlist="2021/08/06 06:18:27 [ERR] memberlist: Received invalid msgType (80) from=172.17.0.1:51102\n"

The startup command is as follows:

**alertmanager-1：**
docker run -d -p 19093:9093 -p 19093:9093/udp -p 19193:19193 -p 19193:19193/udp --name alert1 --restart always -v /opt/prom_mappings/alert1:/etc/alertmanager  prom/alertmanager:0.22.2  --config.file=/etc/alertmanager/alertmanager.yml --cluster.listen-address=0.0.0.0:19193 --cluster.advertise-address=10.10.20.11:19193 --log.level=debug --cluster.peer-timeout=40s

**alertmanager-2：**
docker run -d -p 19094:9093 -p 19094:9093/udp  -p 19194:19194 -p 19194:19194/udp --name alert2 --restart always -v /opt/prom_mappings/alert2:/etc/alertmanager prom/alertmanager:0.22.2  --config.file=/etc/alertmanager/alertmanager.yml --cluster.listen-address=0.0.0.0:19194 --cluster.advertise-address=10.10.20.11:19194 --cluster.peer=10.10.20.11:19193 --log.level=debug --cluster.peer-timeout=40s

**prometheus config:**
<img width="636" alt="企业微信截图_1628499820569" src="https://user-images.githubusercontent.com/76472970/128682854-df1c726f-69fb-4fda-bdf9-982f5d841c57.png">

It's urgent!!!    I hope to get help and solutions from friends, If there is any possible solution, please reply. thanks

**Comment by roidelapluie** [comment]
Would you be able to teel us how many file descriptors are used by both processes?

**Comment by jialanli** [comment]
> Would you be able to teel us how many file descriptors are used by both processes?

node_exporter, prometheus, alertmanager occupy a total of 51 file descriptors

**Comment by jialanli** [comment]
> Would you be able to teel us how many file descriptors are used by both processes?

![image](https://user-images.githubusercontent.com/76472970/128690556-37d90927-ec2d-4f5a-803e-488d1a77bf3e.png)
node_exporter, prometheus, alertmanager occupy a total of 63 file descriptors

**Comment by morvencao** [comment]
You don't have proxy between prometheus and alertmanager, right?
Have you tried to make the `evaluation_interval` to be larger value, for example `60s`?

**Comment by jialanli** [comment]
<img width="580" alt="企业微信截图_16285044752474" src="https://user-images.githubusercontent.com/76472970/128692600-2a261bb6-b2a0-4f3c-af5e-563d0b58815c.png">
The upper limit of the file descriptor is much larger than the current 63

**Comment by jialanli** [comment]
> You don't have proxy between prometheus and alertmanager, right?
> Have you tried to make the `evaluation_interval` to be larger value, for example `60s`?

I don't set proxy between prometheus and alertmanager； The same error remains after changing evaluation_interval to 60s

**Comment by jialanli** [comment]
> You don't have proxy between prometheus and alertmanager, right?
> Have you tried to make the `evaluation_interval` to be larger value, for example `60s`?

I don't set proxy between prometheus and alertmanager，all operations are in https://github.com/prometheus/prometheus/issues/9176； The same error remains after changing evaluation_interval to 60s

**Comment by jialanli** [comment]
> Would you be able to teel us how many file descriptors are used by both processes?
<img width="1241" alt="企业微信截图_16285631355736" src="https://user-images.githubusercontent.com/76472970/128800639-a91167c6-e060-4533-ae62-edd792370898.png">
<img width="1254" alt="企业微信截图_16285630423186" src="https://user-images.githubusercontent.com/76472970/128800638-df85b18f-14fa-43d8-873e-13e6860f1b37.png">

I modified the notifier.go code and re-compiled and run it with the new code. The change is to add the printing of alerts and payload variables (as shown in the figure). The payload variable looks normal, but the alert value is unsupported value type, which is some New information, is there any help in solving this problem?
I don’t know what to do next to make it normal.   bad mood~~

**Comment by roidelapluie** [comment]
10596 seems the user id, not the process ID, so 63 is not the number of files of the processes. Can you provide the accurate number? I think your issue is more related to docker-proxy or docker, because you do not seem to have the same scale as #9057.

**Comment by roobalimsab** [comment]
Hi @roidelapluie ,

We are running cortex and getting the same error mentioned in this issue.

Ruler logs: 
```
level=error ts=2022-09-13T16:37:20.663333971Z caller=notifier.go:527 user=something-else-for-testing alertmanager=http://cortex-aggregator-v2-alertmanager-0.cortex-aggregator-v2-alertmanager-headless.cortex-2.svc.cluster.local:9094/api/prom/alertmanager/api/v1/alerts count=1 msg="Error sending alert" err="Post \"http://cortex-aggregator-v2-alertmanager-0.cortex-aggregator-v2-alertmanager-headless.cortex-2.svc.cluster.local:9094/api/prom/alertmanager/api/v1/alerts\": EOF"
```

Alertmanager logs:
```
level=debug ts=2022-09-13T16:33:23.849663134Z caller=cluster.go:329 component=cluster memberlist="2022/09/13 16:33:23 [ERR] memberlist: Received invalid msgType (80) from=10.115.16.92:58804\n"
```

**Ruler config:**
```
ruler:
  external_url: ""
  ruler_client:
    max_recv_msg_size: 104857600
    max_send_msg_size: 16777216
    grpc_compression: ""
    rate_limit: 0
    rate_limit_burst: 0
    backoff_on_ratelimits: false
    backoff_config:
      min_period: 100ms
      max_period: 10s
      max_retries: 10
    tls_enabled: false
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
  evaluation_interval: 30s
  poll_interval: 1m0s
  storage:
    type: configdb
    configdb:
      configs_api_url: http://cortex-aggregator-v2-configs.cortex-2.svc.cluster.local:80
      client_timeout: 5s
      tls_cert_path: ""
      tls_key_path: ""
      tls_ca_path: ""
      tls_server_name: ""
      tls_insecure_skip_verify: false
  rule_path: /data/rules
  alertmanager_url: http://_cluster._tcp.cortex-aggregator-v2-alertmanager-headless/api/prom/alertmanager
  enable_alertmanager_discovery: true
  alertmanager_refresh_interval: 1m0s
  enable_alertmanager_v2: false
  notification_queue_capacity: 10000
  notification_timeout: 10s
  alertmanager_client:
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
    basic_auth_username: ""
    basic_auth_password: ""
  for_outage_tolerance: 1h0m0s
  for_grace_period: 10m0s
  resend_delay: 1m0s
  enable_sharding: true
  sharding_strategy: default
  search_pending_for: 5m0s
  ring:
    kvstore:
      store: consul
      prefix: rulers/
      consul:
        host: consul:8500
        acl_token: ""
        http_client_timeout: 20s
        consistent_reads: false
        watch_rate_limit: 1
        watch_burst_size: 1
      etcd:
        endpoints: []
        dial_timeout: 10s
        max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        username: ""
        password: ""
      multi:
        primary: ""
        secondary: ""
        mirror_enabled: false
        mirror_timeout: 2s
    heartbeat_period: 5s
    heartbeat_timeout: 1m0s
    instance_id: cortex-aggregator-v2-ruler-6c8b4b988f-4t96b
    instance_interface_names:
    - eth0
    - en0
    instance_port: 0
    instance_addr: ""
    num_tokens: 128
  flush_period: 1m0s
  enable_api: true
  enabled_tenants: ""
  disabled_tenants: ""
```

**Alertmanager cluster config:**
```
alertmanager:
  data_dir: data/
  retention: 120h0m0s
  external_url: /api/prom/alertmanager
  poll_interval: 15s
  max_recv_msg_size: 16777216
  sharding_enabled: false
  sharding_ring:
    kvstore:
      store: consul
      prefix: alertmanagers/
      consul:
        host: localhost:8500
        acl_token: ""
        http_client_timeout: 20s
        consistent_reads: false
        watch_rate_limit: 1
        watch_burst_size: 1
      etcd:
        endpoints: []
        dial_timeout: 10s
        max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        username: ""
        password: ""
      multi:
        primary: ""
        secondary: ""
        mirror_enabled: false
        mirror_timeout: 2s
    heartbeat_period: 15s
    heartbeat_timeout: 1m0s
    replication_factor: 3
    zone_awareness_enabled: false
    instance_id: cortex-aggregator-v2-alertmanager-0
    instance_interface_names:
    - eth0
    - en0
    instance_port: 0
    instance_addr: ""
    instance_availability_zone: ""
  fallback_config_file: ""
  auto_webhook_root: ""
  storage:
    type: configdb
    configdb:
      configs_api_url: http://cortex-aggregator-v2-configs.cortex-2.svc.cluster.local:80
      client_timeout: 5s
      tls_cert_path: ""
      tls_key_path: ""
      tls_ca_path: ""
      tls_server_name: ""
      tls_insecure_skip_verify: false
  cluster:
    listen_address: 0.0.0.0:9094
    advertise_address: ""
    peers: cortex-aggregator-v2-alertmanager-headless.cortex-2.svc.cluster.local:9094
    peer_timeout: 15s
    gossip_interval: 200ms
    push_pull_interval: 1m0s
  enable_api: false
  alertmanager_client:
    remote_timeout: 2s
    tls_enabled: false
    tls_cert_path: ""
    tls_key_path: ""
    tls_ca_path: ""
    tls_server_name: ""
    tls_insecure_skip_verify: false
  persist_interval: 15m0s
```

Can you provide some pointers on how I can fix this?
