### ISSUE TITLE
Local storage limits are not working when using remote_write as primary persistent store

### ISSUE THREAD

**Issue by akamensky** [prometheus/prometheus#9217]
**What did you do?**
Running Prometheus 2.29.1 (same happens in 2.25.0) with InfluxDB as primary persistent store. CLI arguments (see below) limit local storage to 250 MB or 30 minutes.

**What did you expect to see?**
Local storage grows to **maximum** of 250 MB.

**What did you see instead? Under which circumstances?**
Prometheus used all disk space in designated partition (say /data), then it used all disk space in `/var` partition by spamming logs reporting it ran out of disk space (multiple entries every second).
Local storage keeps growing indefinitely. Mostly space consumed by WAL segments, 2nd in disk usage is chunks_head.

Below example is **after the cleanup post the above described outage**:
```
# ps faux | grep -v grep | grep "tsdb.retention" && du -sh /data/prometheus/*
user  23155 47.6 27.2 8046840 6678468 ?     Ssl  10:49  21:56 /opt/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus/ --storage.tsdb.retention.time=30m --storage.tsdb.retention.size=250MB --web.console.templates=/opt/prometheus/consoles --web.console.libraries=/opt/prometheus/console_libraries
248M	/data/prometheus/chunks_head
0	/data/prometheus/lock
20K	/data/prometheus/queries.active
1.4G	/data/prometheus/wal
```

From metrics it looks like after a few hours of running the storage cleanup/compaction (whatever else it is called) did not run even once:

```
# curl -s localhost:9090/metrics | egrep 'wal|retention' | grep -v "#"
prometheus_tsdb_retention_limit_bytes 2.62144e+08
prometheus_tsdb_size_retentions_total 0
prometheus_tsdb_time_retentions_total 0
prometheus_tsdb_wal_completed_pages_total 15504
prometheus_tsdb_wal_corruptions_total 0
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.5"} NaN
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.9"} NaN
prometheus_tsdb_wal_fsync_duration_seconds{quantile="0.99"} NaN
prometheus_tsdb_wal_fsync_duration_seconds_sum 48.380230839999996
prometheus_tsdb_wal_fsync_duration_seconds_count 3
prometheus_tsdb_wal_page_flushes_total 25864
prometheus_tsdb_wal_segment_current 14
prometheus_tsdb_wal_truncate_duration_seconds_sum 0
prometheus_tsdb_wal_truncate_duration_seconds_count 0
prometheus_tsdb_wal_truncations_failed_total 0
prometheus_tsdb_wal_truncations_total 0
prometheus_tsdb_wal_writes_failed_total 0
prometheus_wal_watcher_current_segment{consumer="influxdb"} 14
prometheus_wal_watcher_record_decode_failures_total{consumer="influxdb"} 0
prometheus_wal_watcher_records_read_total{consumer="influxdb",type="samples"} 28299
prometheus_wal_watcher_records_read_total{consumer="influxdb",type="series"} 589
prometheus_wal_watcher_samples_sent_pre_tailing_total{consumer="influxdb"} 0
```

**Environment**

* System information:
```
# uname -srm
Linux 3.10.0-862.el7.x86_64 x86_64
```

* Prometheus version:
```
# /opt/prometheus/prometheus --version
prometheus, version 2.29.1 (branch: HEAD, revision: dcb07e8eac34b5ea37cd229545000b857f1c1637)
  build user:       root@364730518a4e
  build date:       20210811-14:48:27
  go version:       go1.16.7
  platform:         linux/amd64
```

* Prometheus CLI options:
```
# ps faux | grep prometheus
user  23155 49.3 27.2 8046840 6689004 ?     Ssl  10:49  19:04 /opt/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/data/prometheus/ --storage.tsdb.retention.time=30m --storage.tsdb.retention.size=250MB --web.console.templates=/opt/prometheus/consoles --web.console.libraries=/opt/prometheus/console_libraries
```

* Prometheus configuration file:
```yaml
# my global config
global:
  scrape_interval:     30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout:      30s  # scrape_timeout is set to the global default (10s).
  evaluation_interval: 30s # Evaluate rules every 10 seconds. The default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
    - "..."

remote_write:
  - name: "influxdb"
    url: "http://redacted:8086/api/v1/prom/write?db=prometheus_staging"
    remote_timeout: "300s"

remote_read:
  - name: "influxdb"
    url: "http://redacted:8086/api/v1/prom/read?db=prometheus_staging"
    remote_timeout: "300s"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
...
```

* Logs:
Not applicable
