### ISSUE TITLE
metric disappear after few time

### ISSUE THREAD

**Issue by FStefanni** [prometheus/prometheus#9250]
Hi,

I am having a strange behavior, which looks like a bug.

I am using Prometheus v2.29.1.

This is part of my Prometheus config:
```
# ##############################################################################
# General configuration
# ##############################################################################

global:
  # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_interval:     15s
  # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - path_prefix: "/alertmanager"
    static_configs:
    - targets:
      - shared-alertmanager:9093

# Load rules once and periodically evaluate them according to the global
# 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/alerts/alerts-*.yml"

# ##############################################################################
# Jobs
# ##############################################################################
scrape_configs:
  # ############################################################################
  - job_name: 'cloud-prometheus'

    static_configs:
    - targets: ['shared-prometheus:9090']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [job]
      target_label: job
      replacement: cloud
    - source_labels: [job]
      regex: cloud-prometheus
      action: drop
    metric_relabel_configs:
    - source_labels: [job]
      target_label: job
      replacement: cloud
    - source_labels: [job]
      regex: cloud-prometheus
      action: drop

... # other stuff here

  # ############################################################################

  - job_name: 'smart-prometheus'

    scheme: 'https'
    scrape_interval: 30m

    static_configs:
    - targets: ['my.super-server.com']
    metrics_path: '/metrics'
    relabel_configs:
    - source_labels: [job]
      target_label: job
      replacement: smart
    - source_labels: [job]
      regex: smart-prometheus
      action: drop
    metric_relabel_configs:
    - source_labels: [job]
      target_label: job
      replacement: smart
    - source_labels: [job]
      regex: smart-prometheus
      action: drop

... # other stuff here
```

The strange behaviour is the following.

1. After about 30 min from start, in the `Targets` tab of Prometheus, I finally see all services as successfully "up" (so far so good)
2. If the I go to the `Graph` tab, and I execute the simple metric query "up", the I see listed all the `instance/job` couples (again, so far so good)
3. After some time, if I run again the metric query "up", the couple `smart/my.super-server.com` disappears.
4. So I check the `Targets` tab, but it still says everything is fine.

I am ***supposing*** that it depends on the (wrong) relation between `evaluation_time` and `scrape_interval`.
In fact, the `scrape_interval` of the disappearing metric is the only which is overwritten with a slower time (30m),
which is slower than the  `evaluation_time`.

If this is the case, I consider this at least strange (if not a bug), since what I expect is to run the evaluation when it timeouts, 
but to keep the last scraped values, as long as the target has not timed out.
What I am meaning is something as the following (just to make an example, which could not be 100% correct):
```
at_each_evaluation_timeout:
    if current_time - target_last_scrape_execution > target_scrape_interval:
       target_last_scrape_execution  = current_time 
       evaluate_target
```
Something as this should ensure that, even if the metrics are evaluated each 15s, the metric value is updated only when we
are expecting to have a new value.

Finally, just to complete the stuff,  another useful option in this context could be allow a per-target `evaluation_time` specification.

Could you please confirm this strange behavior? Is it truly caused by the slower `scrape_interval`?

Thanks.
Regards.
