### ISSUE TITLE
Some Environment Variables are not detected correctly

### ISSUE THREAD

**Issue by Th0masL** [prometheus/prometheus#9279]
**What did you do?**
I have an Environment Variable file that contains multiple Environment Variable, and I want use those Environment Variables inside Prometheus config.

The problem is that Prometheus is detecting some of the Environment Variaibles, but is not detecting the `Targets` Arrays from the Environment variable.

**What did you expect to see?**

The `Targets` Environment Variable to be populated correctly.

**What did you see instead? Under which circumstances?**

The `Targets` Environment Variable are not populated correctly.

Overview of the configuration, from the Prometheus UI:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    test_variable: test123     <---- populated correctly from Env Vars
scrape_configs:
- job_name: haproxy
  honor_timestamps: true
  scrape_interval: 5s
  scrape_timeout: 5s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - $HAPROXY_TARGETS    <---- not populated correctly from Env Vars
```

**Environment**

* System information:

```
Ubuntu 20 LTS
# uname -srm
Linux 5.4.0-81-generic x86_64
```

* Prometheus version:

```
# prometheus --version
prometheus, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64
  ```

* Alertmanager version:

```
Not using Alertmanager
```

* Prometheus Environment Variable file :
```
# /etc/prometheus/prometheus.env
TEST_VARIABLE='test123'
HAPROXY_TARGETS='"haproxy1:8008","haproxy2:8008"'
```

* Prometheus SYSTEMD Service file :
```
# /etc/systemd/system/prometheus.service
<....>

[Service]
<...>
EnvironmentFile=/etc/prometheus/prometheus.env
ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yml \
  --enable-feature=expand-external-labels \
  --storage.tsdb.path=/var/lib/prometheus \
  --web.console.templates=/etc/prometheus/consoles \
  --web.console.libraries=/etc/prometheus/console_libraries \
  --web.listen-address=0.0.0.0:9090 \
  --web.external-url=
<...>
```

* Prometheus configuration file:
```
# /etc/prometheus/prometheus.yml
global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  external_labels:
    test_variable: $TEST_VARIABLE

scrape_configs:

  - job_name: 'haproxy'
    metrics_path: "/metrics"
    scheme: "http"
    scrape_interval: 5s
    static_configs:
      # The HAProxy targets should be defined as: ["haproxy1:8008", "haproxy2:8008", ...]
      - targets: [$HAPROXY_TARGETS]
```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
