### ISSUE TITLE
"promtool tsdb create-blocks-from rules" backfilled data is duplicated

### ISSUE THREAD

**Issue by Lingx9** [prometheus/prometheus#9288]
**Overview**
 I use promtool to backfill the data of the rules.  After the backfill was completed, it was found that the data was duplicated, and every 2 hours was regarded as an independent metric. (Although their labels are exactly the same)
1. my recording rule
```
groups:
  - name: saas_bandwidth
    interval: 1m
    rules:
    - record: job:saas_tx_bandwidth
      expr: rate(collectd_saas_transmit_bytes_total{}[2m]) * 8
    - record: saas_rx_bandwidth
      expr: rate(collectd_saas_receive_bytes_total{}[2m]) * 8
```
2. Duplicate data, 
command: `./promtool query range http://127.0.0.1:9099 'saas_rx_bandwidth{neId="320"}'  --start=1630342949 --end=1630374911 --step=300s`
![image](https://user-images.githubusercontent.com/89964135/131835025-f95b6b35-5cb4-4178-b923-8c2e7cb409c0.png)
3. every 2 hours are regarded as different metrics
   ![image](https://user-images.githubusercontent.com/89964135/131825768-06e5e6ea-53ce-483f-ad84-fc890d4b5588.png) 
![image](https://user-images.githubusercontent.com/89964135/131826027-945d0813-3549-4ad3-bb8b-dbfa133ef311.png)
![image](https://user-images.githubusercontent.com/89964135/131826054-533cd7d5-5637-413b-84e4-618331a30eef.png)

**Environment**
```
  prometheus, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64

promtool, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64
```

**I want to know if my usage is incorrect? How to solve it? **
