### ISSUE TITLE
Domain name and IP do not match

### ISSUE THREAD

**Issue by mokitoo** [prometheus/prometheus#9305]
**What did you do?**
I configure the domain name in the configuration file of Prometheus as a monitoring item. Then replace the IP pointed to the domain name with a new one in the DNS server, but Prometheus still obtains the data of the old IP after a long time . How can I get the data of the new IP in Prometheus immediately?

I tried the following commands to clean up the old data, but none of them worked
```shell
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/delete_series?match[]={__name__=~".+"}'
curl -X POST -g 'http://localhost:9090/api/v1/admin/tsdb/clean_tombstones'
```

**Environment**
centos 7    docker

* Prometheus version:

2.25.1

* Prometheus configuration file:
```yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'name'

scrape_configs:
    - job_name: 'VPS'
      basic_auth:      
           username: ***
           password: ***
      static_configs:
          - targets:
                - 'domain_name:9100'
            labels:
                instance: instance_name
```
