### ISSUE TITLE
Discovery for ECS

### ISSUE THREAD

**Issue by rakyll** [prometheus/prometheus#9310]
In an earlier evaluation, ECS discovery was rejected due to API rate limiting issues described at the [discovery](https://github.com/prometheus/prometheus/blob/60918b8415d928363ea4bc766d450e707035abe0/discovery/README.md) section.  As of today, there are ECS users that are publishing Prometheus metrics and using CloudWatch Agent's Prometheus scraping capabilities. They configure the agent with task selection mechanism to shard the load among multiple clusters. Influenced by what the users already do, we think we can tackle the problem in a couple of ways:

* Asking users to configure the discovery to discover a set of matching tasks from a cluster, cache metadata in memory where possible.
* Querying the initial data with the ECS API and then relying on ECS events to identify new and terminated tasks.
* Asking users to run Prometheus as a sidecar in their ECS tasks as a last resort.

Given we have this functionality in the CW Agent, not having a similar capability in Prometheus is confusing the ECS users. We would like to fill this gap by contributing an ECS discovery agent to Prometheus and want to switch to the discovery mechanism provided here in all our other collection agents (CW Agent, OpenTelemetry Prometheus Receiver, etc)

## Goals
* Discovery will only discover metric endpoints from a single cluster.
* We will allow users to filter the tasks by the Cluster Query language and ECS tags.
* Users should be able to specify ports and metrics path where the Prometheus metrics are published from the task. (See the config for more.)
* ECS discovery will support both ECS on EC2 and ECS on Fargate.

## Config
Once implemented, ECS discovery will be supported in the Prometheus config. The example below will query the cluster to discover ECS tasks/containers matching the given task selectors.

```
scrape_configs:
  - job_name: ecs-job
    ecs_sd_configs:
      - refresh_interval: 720s # optional
        cluster: "ecs-cluster1"
        region: "us-west-2" # optional, automatically detected
        task_selectors:
          - service: "prometheus-example-service" # optional
            family: "prometheus-example" # optional
            revisions: 1  # optional, matches all revision if not set
            launch_type: "fargate" # optional, “fargate” or “ec2”
            query: "" # optional
            tags:  # optional
               - prometheus_scrape: "true"
            port_path: # optional, by default [":9090/metrics"]
                - ":9001/metrics"
                - ":9090/metrics"
```

The returned results contain targets from the matched tasks. The ports and the metrics path will be appended to the discovered IPs. For example, if task’s public IP is 34.213.73.249, the returned targets will be:
* 34.213.73.249:9001/metrics
* 34.213.73.249:9090/metrics

## Discovery
Discovery is done by periodically pulling the ListTasks API. Discovery will only return the ACTIVE tasks.

As an improvement, we will switch to a model where we will listen to ECS events to be notified about the task start and terminations in the future. This will allow us to call the ListTasks for once and rely on the events for the changes as an optimization.

## Labels
Prometheus discovery can automatically add ECS task/container labels to the scraped metrics. The discovery will add the following labels:

Label | Source | Type | Description
-- | -- | -- | --
__meta_ecs_cluster | ECS Cluster | string | ECS cluster name.
__meta_ecs_task_launch_type | ECS Task | string | “ec2” or “fargate”.
__meta_ecs_task_family | ECS Task | string | ECS task family.
__meta_ecs_task_family_revision | ECS Task | string | ECS task family revision.
__meta_ecs_task_container | ECS Task | string | Name of the container.
__meta_ecs_task_network_interface | ECS Task | string | Network interface name, e.g. eth1.
__meta_ecs_task_az | ECS Task | string | Availability zone
__meta_ecs_ec2_instance_id | EC2 | string | EC2 instance id for EC2 launch type. Otherwise “fargate”.

## Authentication & IAM
We will use the default credential provider chain, the following permissions are required:
* ec2:DescribeInstances
* ecs:ListTasks
* ecs:DescribeContainerInstances
* ecs:DescribeTasks
