### ISSUE TITLE
Follow-up on limiting the number of alerts / rules

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/prometheus#9342]
This is a followup on the PR #9260.

I think we would benefit from a small dedicated section in the docs, that explains the semantics behind this. In particular:

- How to monitor this (evaluation failed metric)
- What happens when you hit the limit
  - alert is not seen as active or pending, they just disappear)
  - this is an error in evaluation, no stale markers are written for rules
- What happens when you recover (alerts go back to pending state)
- some caveats (**I think** the recently closed alerts count in the limit <state=inactive>)

**Comment by LeviHarrison** [comment]
(from https://github.com/prometheus/prometheus/pull/9260#issuecomment-919782079)
> Mmh this pull request takes into consideration the "inactive alerts", which are not pending and not firing. I feel like they should not count, WDYT?

In the original issue (#9225), the problem was `/api/v1/rules` becoming unusable. I'm pretty sure that endpoint returns inactive rules, so if we didn't include them in the count, there could still be overload.

**Comment by LeviHarrison** [comment]
We should definitely be explicit about this though.

**Comment by Rudy167** [comment]
@roidelapluie @LeviHarrison 
After observing this thread, I tried to write a rule file:
```
groups:
- name: my-project
  limit: 5
  rules:
  # Alert for any instance that is unreachable for >1 s.
  - alert: InstanceDown
    expr: up == 0
    for: 1s
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
```
but there is some issue with the syntax here for the limit, as the prometheus server keeps exiting on start after adding the limit property.

Would appreciate your guidance, really keen on contributing more!
