### ISSUE TITLE
prometheus-2.30.0 not support http_sd_configs

### ISSUE THREAD

**Issue by MrYueQ** [prometheus/prometheus#9345]
hai. prometheus-2.30.0 not support http_sd_configs
config example
```yaml
scrape_configs:
  - job_name: http
    metrics_path: /probe

    http_sd_configs:
    - url: https://domain/v1/network/icmp/global
      refresh_interval: 60s
      basic_auth:
        username: op_mon_pm_r
        password:  aaaa

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [ __meta_blackbox_instance ]
        target_label: __address__
      - source_labels: [ __meta_params_module ]
        target_label: __param_module
      - source_labels: [ __meta_zone  ]
        target_label: zone
      - source_labels: [ __meta_blackbox_instance ]
        target_label: src
```

prometheus-2.29.2
```yaml
promtool check config prometheus.yml
Checking prometheus.yml
  SUCCESS: 0 rule files found

prometheus --version
prometheus, version 2.29.2 (branch: HEAD, revision: 752c4f11ae86effa9a46f017f2feb66730c67ed8)
  build user:       root@61bcc9848ade
  build date:       20210827-09:44:22
  go version:       go1.16.7
  platform:         linux/amd64
```

prometheus-2.30.0

```yaml
prometheus --version
prometheus, version 2.30.0 (branch: HEAD, revision: 37468d88dce85ac507f3fb7864c7d1c078e3e27d)
  build user:       root@e913c65aa170
  build date:       20210914-09:49:24
  go version:       go1.17.1
  platform:         linux/amd64

promtool check config prometheus.yml
Checking prometheus.yml
  FAILED: parsing YAML file prometheus.yml: yaml: unmarshal errors:
  line 16: field http_sd_configs not found in type config.ScrapeConfig
```
