### ISSUE TITLE
label_replace doesn't work on some metrics

### ISSUE THREAD

**Issue by ersoyugur** [prometheus/prometheus#9389]
**Problem Description**
label_replace doesn't work on some metrics, tried relabelling in configuration file which also didn't work.

**Base query**
`sum without (job) ((up* on (instance) group_left(sysName)  gtlan:sysName) * on (instance) group_left(sysDescr) sysDescr)`

*result*
```
{instance="1.1.1.1", sysDescr="Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 12.2(55)SE9, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2014 by Cisco Systems, Inc. Compiled Mon 03-Mar-14 22:16 by prod_rel_team", sysName="ABC-SW-1"}
{instance="2.2.2.2", sysDescr="Cisco NX-OS(tm) nxos.7.0.3.I7.8.bin, Software (nxos), Version 7.0(3)I7(8), RELEASE SOFTWARE Copyright (c) 2002-2020 by Cisco Systems, Inc. Compiled 3/3/2020 19:00:00", sysName="XYZ-SW"}
```

**second query that appends label software by parsing sysDescr:**

`label_replace(sum without (job) ((up* on (instance) group_left(sysName)  gtlan:sysName) * on (instance) group_left(sysDescr) sysDescr), "software", "$1", "sysDescr", "Cisco (IOS|NX-OS).*")`

*exptected result*

```
{instance="1.1.1.1", software="IOS", sysDescr="Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 12.2(55)SE9, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2014 by Cisco Systems, Inc. Compiled Mon 03-Mar-14 22:16 by prod_rel_team", sysName="ABC-SW-1"}
{instance="2.2.2.2", software="NX-OS", sysDescr="Cisco NX-OS(tm) nxos.7.0.3.I7.8.bin, Software (nxos), Version 7.0(3)I7(8), RELEASE SOFTWARE Copyright (c) 2002-2020 by Cisco Systems, Inc. Compiled 3/3/2020 19:00:00", sysName="XYZ-SW"}
```

*actual result*

```
{instance="1.1.1.1", sysDescr="Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 12.2(55)SE9, RELEASE SOFTWARE (fc1) Technical Support: http://www.cisco.com/techsupport Copyright (c) 1986-2014 by Cisco Systems, Inc. Compiled Mon 03-Mar-14 22:16 by prod_rel_team", sysName="ABC-SW-1"}
{instance="2.2.2.2", software="NX-OS", sysDescr="Cisco NX-OS(tm) nxos.7.0.3.I7.8.bin, Software (nxos), Version 7.0(3)I7(8), RELEASE SOFTWARE Copyright (c) 2002-2020 by Cisco Systems, Inc. Compiled 3/3/2020 19:00:00", sysName="XYZ-SW"}
```

**Environment**

containerized prometheus

/prometheus $ /bin/prometheus --version
prometheus, version 2.25.2 (branch: HEAD, revision: bda05a23ada314a0b9806a362da39b7a1a4e04c3)
  build user:       root@de38ec01ef10
  build date:       20210316-18:07:52
  go version:       go1.15.10
  platform:         linux/amd64

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "172.18.0.9:9093"

rule_files:
  - /etc/prometheus/prometheus-data/rules/gtlan.rules.yml
  - /etc/prometheus/prometheus-data/rules/alert.rules.yml

scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http 
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'telegraf for syslog'
    scrape_interval: 5s
    static_configs:
    - targets: 
      - "172.18.0.6:9012"
        
  - job_name: 'gtlansnmp_ios'
    scrape_interval: 60s
    scrape_timeout: 59s
    metrics_path: /snmp
    params:
      module: [gtlan_ios]
    file_sd_configs:
      - files:
        - /etc/prometheus/prometheus-data/targets/ios_targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.8:9116  # SNMP exporter.

  - job_name: 'gtlansnmp_cbqos'
    scrape_interval: 60s
    scrape_timeout: 59s
    metrics_path: /snmp
    params:
      module: [cbQos]
    file_sd_configs:
      - files:
        - /etc/prometheus/prometheus-data/targets/cbqos.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.18.0.10:9116  # SNMP exporter.

  - job_name: gtlanNodeMetrics
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 29s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - 172.18.0.2:9100
```
