### ISSUE TITLE
promtool backfill does not delete labels in generated data

### ISSUE THREAD

**Issue by leonerd** [prometheus/prometheus#9419]
I have a recording rule which deletes a label:

```yaml
      - record: 'weather:temperature:avg5m'
        expr: 'avg_over_time(sensor_temperature_degreesC{chip="BME280"}[5m])'
        labels:
          chip: ""
```

The generated data created "live" deletes the chip label here, e.g.:

```
weather:temperature:avg5m{instance="ina.leo:9098", job="sensors"} | 15.646500000000001
```

I have followed the steps [https://jessicagreben.medium.com/prometheus-fill-in-data-for-new-recording-rules-30a14ccb8467](https://jessicagreben.medium.com/prometheus-fill-in-data-for-new-recording-rules-30a14ccb8467) to backfill this. It has created data, but it hasn't deleted the chip label; e.g. providing:

```
weather:temperature:avg5m{chip="BME280", instance="ina.leo:9098", job="sensors"} | 8.818000000000001
```
