### ISSUE TITLE
Accept header mismatch for OpenMetrics

### ISSUE THREAD

**Issue by jonatan-ivanov** [prometheus/prometheus#9430]
**What did you do?**
Scraping the Prometheus endpoint of a service.

**What did you expect to see?**
Prometheus uses the following `Accept` header:
`Accept: application/openmetrics-text; version=1.0.0,text/plain;version=0.0.4;q=0.5,*/*;q=0.1`
Please notice that the version is `1.0.0` for `application/openmetrics-text`.

**What did you see instead? Under which circumstances?**
`Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1`
Please notice that the version is `0.0.1` for `application/openmetrics-text`.

As @fstab pointed out in a connected issue(https://github.com/prometheus/client_java/issues/702#issuecomment-932045566), Prometheus should use `1.0.0` according to OpenMetrics specs.

**Environment**
My locally built prometheus instance or using the latest Docker image.

* System information:
`Darwin 20.6.0 x86_64` or latest Docker image

* Prometheus version:
`2.30.0` (latest docker image) or locally build instance from `main`

* Alertmanager version:
I don't think it is relevant.

* Prometheus configuration file:
```yaml
global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'webservices'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['localhost:8080']
```

* Alertmanager configuration file:
I don't think it is relevant.

* Logs:
I don't think it is relevant.
