### ISSUE TITLE
Prometheus not providing the right metric value for a metric

### ISSUE THREAD

**Issue by usmansharifkhan** [prometheus/prometheus#9441]
**What did you do?**
We have been running Prometheus in Production for more than a year. We saw irregularity in specific metrics on 2 different Prometheus instances on scraping from the same target. 

**What did you expect to see?**
I expected to see similar trends of the same metric on 2 different Prometheus instances deployed as docker containers in AWS EC2 with the same configuration.

**What did you see instead? Under which circumstances?**
The trend of the metric can be seen in the screenshots added below, where for the same target being scraped has different trends on each of the Prometheus replica. 
<img width="1717" alt="Screenshot 2021-10-05 at 1 01 25 AM" src="https://user-images.githubusercontent.com/34530628/135916605-c5a47fbc-e8b2-4f64-bca7-32cc59595d4c.png">
The trend of `argus1` datasource was seen when manually executing curl requests from within `argus0` EC2 instance, where prometheus in itself was verified to record the metric differently for some reason. 

`process_cpu_usage` another metric of the same target shows the same trend,
<img width="1717" alt="Screenshot 2021-10-05 at 1 36 01 AM" src="https://user-images.githubusercontent.com/34530628/135921205-4277124e-f958-4a5c-b3c8-92672f43c762.png">

The same behaviour was seen for a different target but on the opposite Prometheus replica, where `argus0` datasource shows the right value and `argus1` showing a trend where it goes from 0 - 100 and vice versa time to time.
<img width="1717" alt="Screenshot 2021-10-05 at 1 00 00 AM" src="https://user-images.githubusercontent.com/34530628/135916590-c1bf94e5-1b4c-44bd-b511-3de570ad3233.png">

This is happening for 2 instances out of 800 instances deployed in production with the same micrometer spring library configured. 
We as a team, cannot make sense of why this is happening. We tried restarting the containers and also updating the prometheus version to the latest v2.30.0, but to no avail. 

**Environment**

* Prometheus Client library:
        I added this extra field of client library as this experience only happened for the `system_cpu_usage` and `process_cpu_usage` metrics
        Micrometer Spring Library: https://github.com/micrometer-metrics/micrometer

* System information:
	Linux 4.14.171-136.231.amzn2.x86_64 x86_64

* Prometheus version:
        Prometheus version = v2.21.0
        The above scenario was also seen even after upgrading the Prometheus version to the latest v2.30.0

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: prod
    replica: 0

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager0.*******:9093
           - alertmanager1.*******:9093

rule_files:
  - '/etc/prometheus/*alerts.yml'
  - '/etc/prometheus/alerts/*alerts.yml'
  - '/etc/prometheus/*rules.yml'
  - '/etc/prometheus/alerts/*rules.yml'

scrape_configs:
  - job_name: "argus components"
    metrics_path: /metrics
    file_sd_configs:
      - files: [ "/etc/prometheus/argus-components-targets.yml" ]
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: metrics_endpoint
  - job_name: "app metrics"
    metrics_path: /prometheus
    sample_limit: 50000
    file_sd_configs:
      - files: [ "/etc/prometheus/application_instance.yml" ]
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: metrics_endpoint
    metric_relabel_configs:
      - regex: 'aws_autoscaling_groupName|aws_cloudformation_logical_id|aws_cloudformation_stack_id|aws_cloudformation_stack_name|elasticbeanstalk_environment_id'
        action: labeldrop
  - job_name: "node"
    file_sd_configs:
      - files: [ "/etc/prometheus/node_exporter.yml" ]
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: metrics_endpoint
    metric_relabel_configs:
      - regex: 'aws_autoscaling_groupName|aws_cloudformation_logical_id|aws_cloudformation_stack_id|aws_cloudformation_stack_name|elasticbeanstalk_environment_id'
        action: labeldrop
```

* Logs:
May not be relevant but adding it for completeness, any other error was not seen
```
{"caller":"file.go:278","component":"discovery manager scrape","discovery":"file","err":"fsnotify queue overflow","level":"error","msg":"Error watching file","ts":"2021-10-04T21:01:02.547Z"}
```
