### ISSUE TITLE
remote.DecodeWriteRequest: returns "snappy: corrupt input"

### ISSUE THREAD

**Issue by Dentrax** [prometheus/prometheus#9474]
**What did you do?**

I was playing with the [remote write adapter demo server](https://github.com/prometheus/prometheus/blob/release-2.30/documentation/examples/remote_storage/example_write_adapter/server.go) and I'm getting lots of following errors that spams my stdout:

```
snappy: corrupt input
```

It seems `remote.DecodeWriteRequest(r.Body)` could not decode the body properly. 

My `go.mod` file:
```
go 1.17

require (
 ...
 github.com/prometheus/prometheus v1.8.2-0.20211006110246-b878527151e6
)
```

**What did you expect to see?**

Snappy should decode the write request?

**What did you see instead? Under which circumstances?**

```
snappy: corrupt input
```

**Environment**

* System information:

```
Linux 5.11.0-34-generic x86_64
```

* Prometheus version:

```
NAME               	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                       	APP VERSION
prometheus-operator	monitoring	16      	2021-10-07 15:30:12.761238426 +0000 UTC	deployed	kube-prometheus-stack-18.0.5	0.50.0
```

`v2.28.1`

* Prometheus configuration file:
```
insert configuration here
```

* Alertmanager configuration file:

<details>
  <summary>Click to expand!</summary>
  
  ```
enabled: true
  prometheusSpec:
    additionalAlertManagerConfigs:
    - consul_sd_configs:
      - datacenter: mars
        server: consul-api.external
        services:
        - alertmanager
    additionalScrapeConfigs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: kubernetes_pod_name
    disableCompaction: true
    enableAdminAPI: true
    externalLabels:
      _cluster: foo
      _environment: bar
      _federation: baz
      _provider: qux
      _region: quux
      _team: platform
    image:
      repository: $(PROMETHEUS_REPOSITORY)
    logFormat: json
    nodeSelector:
      floor: monitoring
    podMonitorSelectorNilUsesHelmValues: false
    query: {}
    remoteRead: []
    remoteWrite: []
    resources:
      requests:
        memory: 400Mi
    retention: 6h
    ruleSelectorNilUsesHelmValues: false
    secrets:
    - etcd-certs
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
          storageClassName: manual
          volumeName: prometheus
    thanos:
      baseImage:  $(THANOS_REPOSITORY)
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
      tracingConfig:
        key: thanos.yaml
        name: thanos-tracing-config
      version: v0.22.0
    tolerations:
    - key: floor
      operator: Equal
      value: monitoring
    walCompression: false
  service:
    additionalPorts:
    - name: thanos
      nodePort: 30091
      port: 10901
      protocol: TCP
      targetPort: 10901
    annotations:
      consul.hashicorp.com/service-name: thanos-store-api
      consul.hashicorp.com/service-port: thanos
      consul.hashicorp.com/service-sync: "true"
    nodePort: 30090
    type: NodePort
  serviceAccount:
    create: true
  serviceMonitor:
    selfMonitor: true
  ```
</details>
