### ISSUE TITLE
Data Retention not working as was expected

### ISSUE THREAD

**Issue by aquaeye** [prometheus/prometheus#9503]
**What did you do?**
Run prometheus server in docker,  and add command line --storage.tsdb.retention.time = 180d 

cmd="sudo docker run  --restart=always  -u 0 -d -p ${svrport}:9090 --name ${podname} \
           -v $(pwd)/${DEPLOY}-prometheus-fed.yml:/etc/prometheus/prometheus.yml \
           -v $(pwd)/${DEPLOY}-rules.yml:/etc/prometheus/rules.yml \
           -v $(pwd)/web-config.yml:/etc/prometheus/web-config.yml \
           -v /data/prometheus-fed:/prometheus/data \
           -v $(pwd)/pswdfile:/etc/prometheus/.pswdfile \
           "${image}" \
           --config.file=/etc/prometheus/prometheus.yml \
           --web.config.file=/etc/prometheus/web-config.yml \
           --web.enable-lifecycle \
           --web.external-url=http://${hostip}:${svrport}/prometheus \
           --web.route-prefix="/" \
           --storage.tsdb.retention.time=180d \
           "

**What did you expect to see?**

180d long of data reserved on disk

**What did you see instead? Under which circumstances?**

only about 60d of data existed, either searching from web or listing in file system.

**Environment**
centos 7.6
docker 2.
prometheus 2.29.1, 2.30.0

* System information:

	insert output of `uname -srm` here
Linux 3.10.0-957.el7.x86_64 x86_64

* Prometheus version:

	insert output of `prometheus --version` here
2.29.1
2.30.0
* Alertmanager version:

	insert output of `alertmanager --version` here (if relevant to the issue)
v0.22.2

* Prometheus configuration file:
```

global:
  scrape_interval: 20s 
  scrape_timeout: 15s
  evaluation_interval: 20s 

alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - 'alert.xxxx.com'

rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: 
      - 'localhost:9090'

  - job_name: 'federal_k8s_nodeexpo'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="node-exporter"}'
    static_configs:
      - targets:
        - 'k8s.xxxx.com'
    
  - job_name: 'federal_vir'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job=~".+"}'
    static_configs:
    - targets: 
      - 'xxxxx:xxxx'
 
remote_write:
  - url: "http://xxx:xxx/write"
remote_read:
  - url: "http://xxx:xxx/read"


```

* Alertmanager configuration file:
```
insert configuration here (if relevant to the issue)
n.a
```

* Logs:
```

ts=Z caller=db.go:1293 component=tsdb msg="Deleting obsolete block" block=01FHXGD3YATAKJY6RM6R3ETKHG
ts=Z caller=db.go:1293 component=tsdb msg="Deleting obsolete block" block=01FHX9HCPCXFJ76C50QDD7ABQ9
ts=Z caller=db.go:1293 component=tsdb msg="Deleting obsolete block" block=01FHX2NNEBV7PFPHZPYBHNXKB0
ts=Z caller=compact.go:518 component=tsdb msg="write block" mint=1634162400006 maxt=1634169600000 ulid=01FHY509PDNCVMZDH5AQZHAQ1J duration=10.482782426s
```
