### ISSUE TITLE
metrics requests add default :443 to request

### ISSUE THREAD

**Issue by kkretsch** [prometheus/prometheus#9507]
I am getting silly redirects from my monitored discourse site like these:

```
[14/Oct/2021:10:40:32 +0000] "talk.somesite.abc:443" 172.17.0.1 "GET /metrics HTTP/1.1" "Prometheus/2.15.2+ds" "-" 301 414 "-" - 0.000 "-" "-" "-" "-" "-" "-" "-"
[14/Oct/2021:10:40:32 +0000] "talk.somesite.abc" 172.17.0.1 "GET /metrics HTTP/1.1" "Prometheus/2.15.2+ds" "-" 200 30781 "https://talk.somesite.abc:443/metrics" 0.016 0.018 "-" "-" "-" "-" "-" "-" "-"
```

so it seems not to like the extra :443 which indeed is at least not needed.
I configured in prometheus these lines:

```
  - job_name: "discourse"
    scheme: https
    static_configs:
      - targets: ["talk.somesite.abc"]
```

Is it really needed to add the default ":443" port to the url?

I'm running Ubuntu 20.04.2 LTS with included prometheus.
