### ISSUE TITLE
prometheus_sd_discovered_targets contains non existent config named config-0

### ISSUE THREAD

**Issue by freeseacher** [prometheus/prometheus#9508]
**What did you do?**
We add self-written http_sd and add it to prometheus as single source of target configs.
Also we've added alert for like `prometheus_sd_discovered_targets == 0` to know if our datasource working ok. 
And then get metrics page for tht prometheus instance with one and only job with one 

**What did you expect to see?**
```
# HELP prometheus_sd_discovered_targets Current number of discovered targets.
# TYPE prometheus_sd_discovered_targets gauge
prometheus_sd_discovered_targets{config="netbox-sd",name="scrape"} 2
```

**What did you see instead? Under which circumstances?**
```
# HELP prometheus_sd_discovered_targets Current number of discovered targets.
# TYPE prometheus_sd_discovered_targets gauge
prometheus_sd_discovered_targets{config="config-0",name="notify"} 0
prometheus_sd_discovered_targets{config="netbox-sd",name="scrape"} 2
```

* Prometheus version:
```
/prometheus $ prometheus --version
prometheus, version 2.30.0 (branch: HEAD, revision: 37468d88dce85ac507f3fb7864c7d1c078e3e27d)
  build user:       root@e913c65aa170
  build date:       20210914-09:49:24
  go version:       go1.17.1
  platform:         linux/amd64
```

* Prometheus configuration file:

```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    dc: xxxx
alerting:
  alertmanagers:
  - follow_redirects: true
    scheme: http
    path_prefix: /
    timeout: 10s
    api_version: v2
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      separator: ;
      regex: prometheus-operator-kube-p-alertmanager
      replacement: $1
      action: keep
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      separator: ;
      regex: web
      replacement: $1
      action: keep
    kubernetes_sd_configs:
    - role: endpoints
      kubeconfig_file: ""
      follow_redirects: true
      namespaces:
        names:
        - infra
rule_files:
- /etc/prometheus/rules/prometheus-sre-rulefiles-0/*.yaml
scrape_configs:
- job_name: netbox-sd
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  relabel_configs:
  - source_labels: [__meta_netbox_team]
    separator: ;
    regex: (.*)
    target_label: team
    replacement: $1
    action: replace
  - source_labels: [__meta_netbox_tier]
    separator: ;
    regex: (.*)
    target_label: tier
    replacement: $1
    action: replace
  - source_labels: [__meta_netbox_job_name]
    separator: ;
    regex: (.*)
    target_label: job
    replacement: $1
    action: replace
  - source_labels: [__meta_netbox_name]
    separator: ;
    regex: (.*)
    target_label: devicename
    replacement: $1
    action: replace
  - source_labels: [__meta_netbox_rack]
    separator: ;
    regex: (.*)
    target_label: rack
    replacement: $1
    action: replace
  - source_labels: [__meta_netbox_dc]
    separator: ;
    regex: (.*)
    target_label: dc
    replacement: $1
    action: replace
  http_sd_configs:
  - follow_redirects: false
    refresh_interval: 1m
    url: https://netbox-sd-xxx/api/v1/sd/node-exporter?team=sre
remote_write:
...
```
