### ISSUE TITLE
OK in the API but on the GUI : "Error executing query: Failed to fetch"

### ISSUE THREAD

**Issue by Foxinou35** [prometheus/prometheus#9530]
**What did you do?**
Trying to see my metrics on the GUI
**What did you expect to see?**
My metrics
**What did you see instead? Under which circumstances?**
An error message "Error executing query: Failed to fetch"
Some of the metrics are ok, but some on the same exporter, produce errors.
Examples of metrics not working
```
# HELP uwsgi_listen_queue_errors Number of listen queue errors.
# TYPE uwsgi_listen_queue_errors gauge
uwsgi_listen_queue_errors{stats_uri="http://localhost:1717"} 0
# HELP uwsgi_listen_queue_length Length of listen queue.
# TYPE uwsgi_listen_queue_length gauge
uwsgi_listen_queue_length{stats_uri="http://localhost:1717"} 0
# HELP uwsgi_signal_queue_length Length of signal queue.
# TYPE uwsgi_signal_queue_length gauge
uwsgi_signal_queue_length{stats_uri="http://localhost:1717"} 0
# HELP uwsgi_socket_max_queue_length Max length of socket queue.
# TYPE uwsgi_socket_max_queue_length gauge
uwsgi_socket_max_queue_length{name="127.0.0.1:45335",proto="uwsgi",stats_uri="http://localhost:1717"} 180
# HELP uwsgi_socket_queue_length Length of socket queue.
# TYPE uwsgi_socket_queue_length gauge
uwsgi_socket_queue_length{name="127.0.0.1:45335",proto="uwsgi",stats_uri="http://localhost:1717"} 0
# HELP uwsgi_worker_signal_queue_length Length of signal queue.
# TYPE uwsgi_worker_signal_queue_length gauge
uwsgi_worker_signal_queue_length{stats_uri="http://localhost:1717",worker_id="1"} 0
uwsgi_worker_signal_queue_length{stats_uri="http://localhost:1717",worker_id="2"} 0
```
the none working metrics are displayed on the drop down list on the GUI.

For example this one is working
```
# HELP uwsgi_up Whether the uwsgi server is up.
# TYPE uwsgi_up gauge
uwsgi_up 1
```
or this
```
# HELP uwsgi_worker_app_exceptions_total Total number of exceptions.
# TYPE uwsgi_worker_app_exceptions_total counter
uwsgi_worker_app_exceptions_total{app_id="0",chdir="",mountpoint="",stats_uri="http://localhost:1717",worker_id="1"} 0
uwsgi_worker_app_exceptions_total{app_id="0",chdir="",mountpoint="",stats_uri="http://localhost:1717",worker_id="2"} 0
# HELP uwsgi_worker_exceptions_total Total number of exceptions.
# TYPE uwsgi_worker_exceptions_total counter
uwsgi_worker_exceptions_total{stats_uri="http://localhost:1717",worker_id="1"} 0
uwsgi_worker_exceptions_total{stats_uri="http://localhost:1717",worker_id="2"} 0
```

It is working fine with the API : 
```
curl 'http://localhost:9090/api/v1/query?query=uwsgi_listen_queue_length'
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"uwsgi_listen_queue_length","instance":"10.216.184.160:9117","job":"yel-prolive-ppd-kub-sirius-uwsgi","stats_uri":"http://localhost:1717"},"value":[1634566267.926,"0"]},{"metric":{"__name__":"uwsgi_listen_queue_length","instance":"10.216.184.161:9117","job":"yel-prolive-ppd-kub-sirius-uwsgi","stats_uri":"http://localhost:1717"},"value":[1634566267.926,"0"]},{"metric":{"__name__":"uwsgi_listen_queue_length","instance":"10.216.184.162:9117","job":"yel-prolive-ppd-kub-sirius-uwsgi","stats_uri":"http://localhost:1717"},"value":[1634566267.926,"0"]},{"metric":{"__name__":"uwsgi_listen_queue_length","instance":"10.216.184.26:9117","job":"yel-prolive-ppd-kub-sirius-uwsgi","stats_uri":"http://localhost:1717"},"value":[1634566267.926,"0"]},{"metric":{"__name__":"uwsgi_listen_queue_length","instance":"10.216.184.27:9117","job":"yel-prolive-ppd-kub-sirius-uwsgi","stats_uri":"http://localhost:1717"},"value":[1634566267.926,"0"]}]}}
```

**Environment**

* System information:

	Linux 4.15.0-1098-gcp x86_64 (Ubuntu 16.04)

* Prometheus version:

	prometheus, version 2.30.3 (branch: HEAD, revision: f29caccc42557f6a8ec30ea9b3c8c089391bd5df)

* Alertmanager version:

	

* Prometheus configuration file:
```
# prometheus global config
global:
  scrape_interval:     10s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: "prometheus-gcp-yel-prd-gke"
    environment: "kubernetes"
    k8s_cluster: "yel-spr-prd-kub-cluster"
    service: Prometheus
    region: eu-west-1
    dc: eu-west-1-b

rule_files:
 - "alerts/*.rules"

scrape_configs:
  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.
- job_name: prometheus
  honor_labels: true
  static_configs:
  - targets: ['localhost:9090']



## Prolive PRD pods
- job_name: 'yel-prolive-prd-kub-sirius-pods'
  #
  kubernetes_sd_configs:
  - api_server: https://(maskedIP)
    role: pod

    tls_config:
      ca_file: /etc/prometheus/certs/ca_yel-prolive-prd-kub-sirius.crt
    bearer_token_file: /etc/prometheus/tokens/yel-prolive-prd-kub-sirius_token
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__address__]
    target_label: cluster_entity
    replacement: "yel-prolive"
  - source_labels: [__address__]
    target_label: cluster_name
    replacement: "yel-prolive-prd-kub-sirius"



## Prolive PRD service

- job_name: 'yel-prolive-prd-kub-sirius-service-endpoints'

  kubernetes_sd_configs:
  - api_server: https://(maskedIP)
    role: endpoints

    tls_config:
      ca_file: /etc/prometheus/certs/ca_yel-prolive-prd-kub-sirius.crt
    bearer_token_file: /etc/prometheus/tokens/yel-prolive-prd-kub-sirius_token 

  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name
  - source_labels: [__address__]
    target_label: cluster_entity
    replacement: "yel-prolive"
  - source_labels: [__address__]
    target_label: cluster_name
    replacement: "yel-prolive-prd-kub-sirius"

## Prolive PPD uwsgi

- job_name: 'yel-prolive-ppd-kub-sirius-uwsgi'
  kubernetes_sd_configs:
  - api_server: https://(maskedIP)
    role: pod

    tls_config:
      ca_file: /etc/prometheus/certs/ca_yel-prolive-ppd-kub-sirius.crt
    bearer_token_file: /etc/prometheus/tokens/yel-prolive-ppd-kub-sirius_token
  relabel_configs:
#  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
#    action: keep
#    regex: true
#  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
#    action: replace
#    target_label: __metrics_path__
#    regex: (.+)
#  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
#    action: replace
#    regex: ([^:]+)(?::\d+)?;(\d+)
#    replacement: $1:$2
#    target_label: __address__
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    action: keep
    regex: 9117

```

* Logs:
No log when error occurs
