### ISSUE TITLE
when increased scrape_timeout for slow target it is not applied

### ISSUE THREAD

**Issue by ahsanashraf918** [prometheus/prometheus#9549]
**What did you do?**
I increased scrape_timeout for 1 of my slow target (15s) but it is not applied. default/global value (10s) is applied instead

**What did you expect to see?**
the request should timeout at 15s

**What did you see instead? Under which circumstances?**

**Environment**

System information:

Linux 4.14.171-136.231.amzn2.x86_64 x86_64

Prometheus version:

2.30.0

* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    cluster: qa
    replica: "0"
scrape_configs:
- job_name: app metrics
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /prometheus
  scheme: http
  sample_limit: 50000
  follow_redirects: true
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: metrics_endpoint
    replacement: $1
    action: replace
  metric_relabel_configs:
  - separator: ;
    regex: aws_autoscaling_groupName|aws_cloudformation_logical_id|aws_cloudformation_stack_id|aws_cloudformation_stack_name|elasticbeanstalk_environment_id
    replacement: $1
    action: labeldrop
  file_sd_configs:
  - files:
    - /etc/prometheus/application_instance.yml
    refresh_interval: 1m


# /etc/prometheus/application_instance.yml
- labels:
    name: qa-green-argus-broker-service
    instance: 12345
    __scrape_timeout__: 15s
    private_ip: xxxxx
    c_domain: monitoring
  targets:
  - xxxxxx:80

```

* Logs:
```
insert Prometheus and Alertmanager logs relevant to the issue here
```
