### ISSUE TITLE
Cannot Scrape exposed Docker Metrics from Prometheus container on Linux

### ISSUE THREAD

**Issue by petef19** [prometheus/prometheus#9613]
Apologies if this is the incorrect forum, but I've searched and tested and cannot find a solution to the strange behavior I'm experiencing.

On our **Linux** host, latest `Prometheus 2.30.3` container is unable to scrape exposed Docker metrics. Everything works in our local dev environment on Win 10, and other containers on the same Linux host also can access the Docker metrics, but not the Prometheus container.

OS: Ubuntu 18.04.1 LTS
Prometheus: 2.30.3 (latest)
Docker: 20.10.10 (latest, allows to add extra hosts to container, see below)
Docker-compose: 2.0.1

docker metrics config in `/etc/docker/daemon.json`
```
{
  "experimental": true,
  "metrics-addr": "0.0.0.0:9933"
}
```

config in `/prometheus.yml`:
```
...
 - job_name: 'docker_metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:9933']
...
```

`docker-compose` config for Prometheus container:
```
prometheus:
    container_name: prom_test
    image: prom/prometheus:v2.30.3
    restart: unless-stopped
    command: "--config.file=/etc/prometheus/prometheus.yml
                  --storage.tsdb.path=/prometheus
                  --storage.tsdb.retention.time=45d"
    ports:
      - 9090:9090
    volumes:
      - ./data/prometheus:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      host.docker.internal: host-gateway
```

As you can see the container is NOT running in a custom Docker network (I removed this for now). With Docker version `20.10.x` and higher we can now add `extra hosts` to the container config via `host.docker.internal: host-gateway`.

When I access `https://<my_ip>:9090/targets` to inspect the status of the scrape targets, Prometheus ultimately then states:

![image](https://user-images.githubusercontent.com/67035258/139490300-f23d46c6-a934-407c-9dab-2a38d841115a.png)

But, clicking on the `http://host.docker.internal:9933/metrics` link provided in the scrape target endpoint block actually lists the Docker metrics

![image](https://user-images.githubusercontent.com/67035258/139490415-7af4a4e8-0eab-4ecd-89de-fe9c4beadb20.png)

jumping into the running Prometheus container and running `cat /etc/hosts` inside the container shows that the `extra host` was added correctly
```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.17.0.1      host.docker.internal
172.22.0.2      fa87b35d3923
```

running `wget` inside the `Prometheus` container (since `curl` is not available and I cannot install it since `apk`, `apt-get` or `yum` are all not available) on the Docker metrics endpoint results in a timeout:

```
/prometheus $ wget host.docker.internal:9933/metrics
Connecting to host.docker.internal:9933 (172.17.0.1:9933)
wget: can't connect to remote host (172.17.0.1): Connection timed out
```

Further test reveals that other containers can access the Docker metrics just fine:
```
docker run --rm --add-host=host.docker.internal:host-gateway curlimages/curl host.docker.internal:9933/metrics
```
outputs the Docker metrics
```
...
# HELP go_info Information about the Go environment.
# TYPE go_info gauge
go_info{version="go1.16.9"} 1
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 1.827868e+07
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 4.70965336e+08
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.593084e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 6.459241e+06
# HELP go_memstats_gc_cpu_fraction The fraction of this program's available CPU time used by the GC since the program started.
# TYPE go_memstats_gc_cpu_fraction gauge
go_memstats_gc_cpu_fraction 7.688000007498586e-06
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 6.273224e+06
...
```

I've also added these firewall rules
```
sudo iptables -A INPUT -i docker0 -j ACCEPT
sudo iptables -A INPUT -i docker_gwbridge -j ACCEPT
```

What am I missing ? Why can the Prometheus container not access the exposed Docker metrics on Linux ?

Any pointers appreciated.

Thanks !
