### ISSUE TITLE
Support `int` and `uint` as a valid data type for `humanize` functions

### ISSUE THREAD

**Issue by jebeaudet** [prometheus/prometheus#9679]
Related discussions at the end of https://github.com/prometheus/prometheus/issues/8303
## Proposal
**Support infered `int` in yaml templating functions such as humanize, humanize1024, humanizeDuration, etc.**
Go templating treats round numbers as `int` in YAML. When trying to use the `humanize` functions, it fails because it only support `float64` or `string`. So, a template like this will fail : 
```
      expr: some_expression
      annotations:
        description: You are approaching the maximum value of {{ 123456789 | humanize}}
        summary: Some summary
 ```
`int` should be supported out of the box without having to put `123456789.0`.

I'll follow up with a PR shortly. 

Thanks
