### ISSUE TITLE
promtool test rules is useless for simple expressions tests

### ISSUE THREAD

**Issue by piotrminkina** [prometheus/prometheus#9757]
I'm trying test the following YAML file by command `./promtool test rules nil.yaml`:

```yaml
# nil.yaml
evaluation_interval: 15s
tests:
  - interval: 15s
    input_series:
      - series: metric
        values: '_ 0 1 1 2 3 5 8'
    promql_expr_test:
      - expr: 'idelta(metric[30s])'
        eval_time: '0s'
        exp_samples:
          - labels: 'metric'
            value: ~
      - expr: 'idelta(metric[30s])'
        eval_time: '15s'
        exp_samples:
          - labels: 'metric'
            value: ~
      - expr: 'idelta(metric[30s])'
        eval_time: 30s
        exp_samples:
          - labels: 'metric'
            value: 1
      - expr: 'idelta(metric[30s])'
        eval_time: 45s
        exp_samples:
          - labels: 'metric'
            value: 0
      - expr: 'idelta(metric[30s])'
        eval_time: 1m
        exp_samples:
          - labels: 'metric'
            value: 1
      - expr: 'idelta(metric[30s])'
        eval_time: 1m15s
        exp_samples:
          - labels: 'metric'
            value: 1
```

I expect all test cases to be successful, but instead no test case is correct (same results for older promtool in version `2.29.1`).

```shell
$ ./promtool test rules nil.yaml 
Unit Testing:  nil.yaml
  FAILED:
    expr: "idelta(metric[30s])", time: 0s,
        exp:"{__name__=\"metric\"} 0E+00"
        got:"nil"
    expr: "idelta(metric[30s])", time: 15s,
        exp:"{__name__=\"metric\"} 0E+00"
        got:"nil"
    expr: "idelta(metric[30s])", time: 30s,
        exp:"{__name__=\"metric\"} 1E+00"
        got:"{} 1E+00"
    expr: "idelta(metric[30s])", time: 45s,
        exp:"{__name__=\"metric\"} 0E+00"
        got:"{} 0E+00"
    expr: "idelta(metric[30s])", time: 1m,
        exp:"{__name__=\"metric\"} 1E+00"
        got:"{} 1E+00"
    expr: "idelta(metric[30s])", time: 1m15s,
        exp:"{__name__=\"metric\"} 1E+00"
        got:"{} 1E+00"
```

**Environment**

* System information:

```shell
$ uname -srm
Linux 5.11.0-40-generic x86_64
```

* Promtool version:

```shell
$ ./promtool --version
promtool, version 2.31.1 (branch: HEAD, revision: 411021ada9ab41095923b8d2df9365b632fd40c3)
  build user:       root@9419c9c2d4e0
  build date:       20211105-20:35:02
  go version:       go1.17.3
  platform:         linux/amd64
# And also I'm using another version, installed globally
$ promtool --version
promtool, version 2.29.1 (branch: HEAD, revision: dcb07e8eac34b5ea37cd229545000b857f1c1637)
  build user:       root@364730518a4e
  build date:       20210811-14:48:27
  go version:       go1.16.7
  platform:         linux/amd64
```
