### ISSUE TITLE
Support target discovery in the same kubernetes namespace with prometheus pod without explicit namespace config

### ISSUE THREAD

**Issue by wangrzneu** [prometheus/prometheus#9782]
## Proposal
Support target discovery in the same kubernetes namespace with prometheus pod without explicit namespace config
With this feature, we can use the same prometheus config when deploying prometheus in different kubernetes namespace.
The namespace can be got from `/var/run/secrets/kubernetes.io/serviceaccount/namespace` file.
An config item need to be added, and the config file may be like following.
```
    scrape_configs:
     - job_name: 'kubernetes-pods'
       kubernetes_sd_configs:
        - role: pod
          in_cluster_namespace: true
```
