### ISSUE TITLE
Prometheus is failing with OOM after giving 22 Gi on eks cluster

### ISSUE THREAD

**Issue by harshal1605** [prometheus/prometheus#9813]
**What did you do?**

We are deploying Prometheus for monitoring purpose on eks cluster

**What did you expect to see?**

Pod should be running without giving OOM killed error. 

**What did you see instead? Under which circumstances?**

Pod is going in OOM exception even after giving 22 Gi and data is only 21 GB in TSDB. 

**Environment**

* Prometheus version:

	2.26.1-4

* Alertmanager version:

	0.22.2-4

* Prometheus configuration file:
```
prometheus:
  serviceAccount:
    create: true
  prometheusSpec:
    retention: 2d
    retentionSize: "100GB"
    ruleSelectorNilUsesHelmValues: true
    serviceMonitorSelectorNilUsesHelmValues: true
    secrets:
    #  - sidecar-certificate         # Add this only if SSL is enabled
    configMaps:
    #  - prometheus-sidecar-config   # Add this only if SSL is enabled
    readinessProbe:
      failureThreshold: 120
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 30
    resources:
      limits:
        cpu: 2
        memory: 22Gi
      requests:
        cpu: 2
        memory: 22Gi
    nodeSelector:
      node.kubernetes.io/Monitoring: "true"
    tolerations:
      - key: "designation"
        operator: "Equal"
        value: "Monitoring"
        effect: "NoSchedule"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: prometheus-volume
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Gi
```

* Alertmanager configuration file:
```

```

* Logs:
```

```
