### ISSUE TITLE
Prometheus cannot be reloaded when the HTTP_sd_config URL returns [] ?

### ISSUE THREAD

**Issue by hyingreborn** [prometheus/prometheus#9854]
**What did you do?**
I use http_sd_config to dynamically get the target to probe, I first let the url return 100 targets, like this:
```
[
	{
	    "targets": [ "192.168.1.1"],
	    "labels": {
	      "id": "1",
	      "name": "device 1"
	    }
	},
       .... other 99
]
```
At this point Prometheus is working properly and you can see the 100 targets on the "http://promethues:9090/targets"

Then I let the url to return an empty list like this:
```
[]
```
Next, I made a  post request to http://promethues:9090/-/reload

**What did you expect to see?**
Prometheus should display 0 for the number of targets in the job after reload due to reading the empty list；
But in fact, it still shows the previous 100 targets in http://promethues:9090/targets，that means it's still probe those 100 targets

**What did you see instead? Under which circumstances?**

**Environment**

* System information:

	Linux 3.10.0-1160.el7.x86_64 x86_64

* Prometheus version:

	2.23.1

* Alertmanager version:

	0.21.0

* Prometheus configuration file:
```
- job_name: 'blackbox_icmp_1'
    metrics_path: /probe
    params:
      module: [icmp]
    http_sd_configs:
      - url: http://localhost:9999/targetsProm?job=blackbox_icmp_1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
```

* Alertmanager configuration file:
```
...
```

* Logs:
```
level=info ts=2021-11-24T09:57:10.874Z caller=main.go:969 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2021-11-24T09:57:10.914Z caller=main.go:1006 msg="Completed loading of configuration file" filename=/etc/prometheus/prometheus.yml totalDuration=39.49526ms db_storage=1.1µs remote_storage=1.4µs web_handler=500ns query_engine=900ns scrape=338.305µs scrape_sd=731.611µs notify=8µs notify_sd=23.2µs rules=37.271029ms
```
