### ISSUE TITLE
Agent: all scrapes in error after exactly 2 hours `msg="Appending scrape report failed" err="not found"`

### ISSUE THREAD

**Issue by fatpat** [prometheus/prometheus#9875]
**What did you do?**
I configured a prometheus in `Agent` mode. 

It was previously working in standalone mode and was working perfectly with the same scrapes configured.

**What did you expect to see?**
not a total shutdown of all scrapes after 2 hours

**What did you see instead? Under which circumstances?**
all scrapes in error with `component="scrape manager" scrape_pool=xxxx target="http://xxxx:6161/stat?format=prometheus" msg="Appending scrape report failed" err="not found"`

all exporters are reported down in the interface as well

After a restart everything is fine

**Environment**

* System information:
`Linux 5.11.0-27-generic x86_64`

* Prometheus version:
```
prometheus, version 2.32.0-beta.0 (branch: HEAD, revision: c32725ba7873dbaa39c223410043430ffa5a26c0)
  build user:       root@da630543d231
  build date:       20211116-11:23:14
  go version:       go1.17.3
  platform:         linux/amd64
```
* Prometheus configuration file:
```
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    environment: test
scrape_configs:
- job_name: beanstalkd-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  metric_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ^(?:beanstalkd_)?(.*)$
    target_label: __name__
    replacement: beanstalkd_$1
    action: replace
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/beanstalkd-exporter.yml
    refresh_interval: 5m
- job_name: memcached-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/memcached-exporter.yml
    refresh_interval: 5m
- job_name: bbbb
  honor_timestamps: true
  params:
    format:
    - prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /v3.0/forward/stats
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/bbbb.yml
    refresh_interval: 5m
- job_name: ttttt
  honor_timestamps: true
  params:
    format:
    - prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/tttt.yml
    refresh_interval: 5m
- job_name: rrrr
  honor_timestamps: true
  params:
    format:
    - prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/rrrr.yml
    refresh_interval: 5m
- job_name: netdata
  honor_timestamps: true
  params:
    format:
    - prometheus_all_hosts
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /api/v1/allmetrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/netdata.yml
    refresh_interval: 5m
- job_name: dddd
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/dddd.yml
    refresh_interval: 5m
- job_name: ccc
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/ccc.yml
    refresh_interval: 5m
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/prometheus.yml
    refresh_interval: 5m
- job_name: bbb
  honor_timestamps: true
  params:
    format:
    - prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /stat
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/bbb.yml
    refresh_interval: 5m
- job_name: aaa
  honor_timestamps: true
  params:
    format:
    - prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /status
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/aaaa.yml
    refresh_interval: 5m
- job_name: redis-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/redis-exporter.yml
    refresh_interval: 5m
- job_name: redissentinel-exporter
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  follow_redirects: true
  file_sd_configs:
  - files:
    - /etc/prometheus/targets/redissentinel-exporter.yml
    refresh_interval: 5m
remote_write:
- url: http://xxxxxxxx:9090/api/v1/write
  remote_timeout: 30s
  follow_redirects: true
  queue_config:
    capacity: 2500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 500
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 5s
  metadata_config:
    send: true
    send_interval: 1m
    max_samples_per_send: 500
```

* Logs:
```
Nov 26 17:03:10 prometheus[36155]: ts=2021-11-26T17:03:10.957Z caller=scrape.go:1258 level=warn component="scrape manager" scrape_pool=rawx target="http://1.1.1.1:6161/stat?format=prometheus" msg="Appending scrape report failed" err="not found"
Nov 26 17:03:11 prometheus[36155]: ts=2021-11-26T17:03:11.027Z caller=scrape.go:1258 level=warn component="scrape manager" scrape_pool=netdata target="http://1.1.1.1:1505/api/v1/allmetrics?format=prometheus_all_hosts" msg="Appending scrape report failed" err="not found"
```
