### ISSUE TITLE
Record rules: Part of the data is lost after changed the `expr` of the record

### ISSUE THREAD

**Issue by Lingx9** [prometheus/prometheus#9887]
I modified the'expr' field of the record rule and found that part of the data was missing, as if it had not been calculated.
tried to restart Promethues, but it didn't solve

1. record rules
```
groups:
  - name: e2e_bandwidth
    interval: 1m
    rules:
    - record: e2e_tx_bandwidth
      expr: rate(collectd_destination_transmit_bytes_total{destination=~"0|1|2|3|4|5"}[2m]) * 8
    - record: e2e_rx_bandwidth
      expr: rate(collectd_destination_receive_bytes_total{destination=~"0|1|2|3|4|5"}[2m]) * 8

```
2. After changed expr,  the data of deviceId="GHB31001" is gone
![截屏2021-11-29 16 57 25](https://user-images.githubusercontent.com/89964135/143838275-01bef037-68a0-4cfb-b08d-41db1a49f570.jpg)

3. I re-added a record with the same `expr`, they only  different `record` name, the new rule is completely normal
expr config
![image](https://user-images.githubusercontent.com/89964135/143844490-8fd277f7-94ea-40de-99f4-5e4278701b53.png)

expr graph
![image](https://user-images.githubusercontent.com/89964135/143844694-35335020-636b-47af-b0e6-617f02efe57b.png)

* System information:
```
Linux 4.15.0-48-generic x86_64
```

* Prometheus version:
```
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
build user:       root@2915dd495090
build date:       20210701-15:20:10
go version:       go1.16.5
platform:         linux/amd64
```

**May I ask why such a situation occurs and how to solve it？**

**Comment by JessicaGreben** [comment]
We have not tried to reproduce this, but it sounds like a bug.

**Comment by Lingx9** [comment]
> We have not tried to reproduce this, but it sounds like a bug.

@JessicaGreben  Is there any way to temporarily fix this problem?

**Comment by roidelapluie** [comment]
Does collectd expose metrics with timestamps?

Could you try:

```
groups:
  - name: e2e_bandwidth
    interval: 1m
    rules:
    - record: e2e_tx_bandwidth
      expr: rate(collectd_destination_transmit_bytes_total{destination=~"0|1|2|3|4|5"}[2m] offset 1m) * 8
    - record: e2e_rx_bandwidth
      expr: rate(collectd_destination_receive_bytes_total{destination=~"0|1|2|3|4|5"}[2m] offset 1m) * 8
```

of change 2m by 5m?
