### ISSUE TITLE
Template functions request: strip domain, strip port

### ISSUE THREAD

**Issue by baryluk** [prometheus/prometheus#9932]
## Proposal
**Use case. Why is this important?**

Alerts should be concise, especially their summaries, yet many labels accessible during alert annotation construction will be long.

Example is `instance` or `target`, which usually will be a FQDN, often with port.

In our monitor system we also have a label `host` that is FQDN (it is used also for silencing). Often it is not derived from `instance`, but something else instead. This label is constructed in various ways using relabeling (often stripping port) or SD static labels.
But because we have about 30 different scrape jobs, there is a lot of repetitive relabeling rules to construct them.

Additionally to make alert summaries short, and help Grafana legend formating, and write alert silences quicker, we add `host_short`, which is `host` but only the host part, not FQDN. Again this is done using relabeling (with help of some regexp) or SD static labels for each target, depending on use case.

We use FQDNs for targets in SD, so DNS queries are correct, but 99% of the hosts are actually in the same domain, so there is no point of having the domain in alert annotations usually.

This approach has few downsides:

1) Stores more data in the TSDB and memory, which is arguably redundant data.

2) Relabeling rules for many targets are very repetitive and clutter the config file A LOT.

3) Grafana use case could be solved on Grafana side instead.

4) Because each time series now has `instance`, `host` and `host_short`, users are confused which one should be used for silence, or selectors, and `on` operators.

At the moment we do have 144 references to `host` and 102 `host_short` labels in our alerts, and it is just ugly.

The idea would be to not have these labels, but instead construct them during alert annotation rendering. However, this is even worse, and very tedious to do with just `reReplaceAll`. This could be workedaround by using pre-processor (in fact we use Python scripts to generate many alerting rules, for various reasons), but the generated yaml file as well viewing alerts definitions at `/alerts` will still be unreadable and very long.

So, I propose to add two helper string functions.

`stripPort` - removes colon and integer port parts after short or FQDN or IPv4 / IPv6 address, if any; and any trailing whitespaces

Example:

- "foo:123456" -> "foo"
- "foo" -> "foo"
- "foo.example.com:123456   " -> "foo.example.com"
- "foo.example.com." -> "foo.example.com."
- "127.0.0.1:33" -> "127.0.0.1"
- "127.0.0.1  " -> "127.0.0.1"
- "[::1]:9090" -> "[::1]"
- "[::1]" -> "[::1]"
- ":22" -> ""

`shortHostName` - if not IPv4 / IPv6, removes all the domain path elements, leaving only the first one; and any leading and trailing whitespaces in the output.

Example:

- "foo:123456" -> "foo"
- "  foo  " -> "foo"
- "foo.example.com:123456   " -> "foo"
- "foo.example.com." -> "foo"
- "127.0.0.1:33" -> "127.0.0.1"
- "127.0.0.1  " -> "127.0.0.1"
- "[::1]:9090" -> "[::1]"
- "[::1]" -> "[::1]"
- "" -> ""

Examples.

Instead of:

```yaml
...
# metric relabeling and target labels skipped
...
    - alert: NodeDown
      expr: 'up{job=~"node.*"} != 1'
      for: 2m
      labels:
        severity: critical
        dependency_level: machine
      annotations:
        summary: 'Network, machine or exporter issues for {{ $labels.host_short }}'
        description: '(location {{ $labels.location }}): Node exporter on {{ $labels.host }} is unreachable'
```

one could do this instead:

```yaml
...
# No metric relabeling or target labels
...

    - alert: NodeDown
      expr: 'up{job=~"node.*"} != 1'
      for: 2m
      labels:
        severity: critical
        dependency_level: machine
      annotations:
        summary: 'Network, machine or exporter issues for {{ $labels.instance | shortHostName }}'
        description: '(location {{ $labels.location }}): Node exporter on {{ $labels.instance | stripPort }} is unreachable'
```

More complex use cases, like extracting the domain name ("example.com") are rare, and specialized, that can be easily handled using `reReplaceAll` or metric relabeling.
