### ISSUE TITLE
Prometheus continuously re-discovers all existing targets.

### ISSUE THREAD

**Issue by darkl0rd** [prometheus/prometheus#9966]
**What did you do?**

Setup Prometheus with Docker Swarm Service Discovery using both Swarm basic filters and the workaround/solution provided by Brian Brazil in issue https://github.com/prometheus/prometheus/issues/8073 to ensure that the targets aren't constantly re-discovered 

```
  - job_name: 'alertmanager'
    dockerswarm_sd_configs:
      - host: http://proxy_swarm-socket:9090
        role: tasks
        port: 80
        filters:
          - name: desired-state
            values: ["running"]
          - name: label
            values: ["prometheus-job=alertmanager"]
    # Use static port above, to avoid re-discovery - see #8073 
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):80'
        target_label: __address__
        replacement: "${1}:9093"
```

**What did you expect to see?**

Services not being continuously rediscovered.

**What did you see instead? Under which circumstances?**

Services being continuously rediscovered, leading to an extremely high network load; snippet from the Caddy container (swarm api proxy):

```
{"level":"info","ts":1638891728.1137774,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"10.0.139.13:42320","proto":"HTTP/1.1","method":"GET","host":"prometheus_swarm-api:9090","uri":"/v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D","headers":{"User-Agent":["Prometheus/2.31.0"]}},"common_log":"10.0.139.13 - - [07/Dec/2021:15:42:08 +0000] \"GET /v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D HTTP/1.1\" 200 6293","user_id":"","duration":0.523735961,"size":6293,"status":200,"resp_headers":{"Api-Version":["1.40"],"Content-Type":["application/json"],"Docker-Experimental":["true"],"Ostype":["linux"],"Date":["Tue, 07 Dec 2021 15:42:08 GMT"],"Server":["Caddy","Docker/19.03.15 (linux)"]}}
{"level":"info","ts":1638891753.5051885,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"10.0.139.12:55914","proto":"HTTP/1.1","method":"GET","host":"prometheus_swarm-api:9090","uri":"/v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D","headers":{"User-Agent":["Prometheus/2.31.0"]}},"common_log":"10.0.139.12 - - [07/Dec/2021:15:42:33 +0000] \"GET /v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D HTTP/1.1\" 200 6293","user_id":"","duration":0.341778595,"size":6293,"status":200,"resp_headers":{"Api-Version":["1.40"],"Server":["Caddy","Docker/19.03.15 (linux)"],"Content-Type":["application/json"],"Docker-Experimental":["true"],"Ostype":["linux"],"Date":["Tue, 07 Dec 2021 15:42:33 GMT"]}}
{"level":"info","ts":1638891787.7132037,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"10.0.139.13:42320","proto":"HTTP/1.1","method":"GET","host":"prometheus_swarm-api:9090","uri":"/v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D","headers":{"User-Agent":["Prometheus/2.31.0"]}},"common_log":"10.0.139.13 - - [07/Dec/2021:15:43:07 +0000] \"GET /v1.40/tasks?filters=%7B%22desired-state%22%3A%7B%22running%22%3Atrue%7D%2C%22label%22%3A%7B%22prometheus-job%3Dalertmanager%22%3Atrue%7D%7D HTTP/1.1\" 200 6293","user_id":"","duration":0.122917304,"size":6293,"status":200,"resp_headers":{"Server":["Caddy","Docker/19.03.15 (linux)"],"Content-Type":["application/json"],"Docker-Experimental":["true"],"Ostype":["linux"],"Date":["Tue, 07 Dec 2021 15:43:07 GMT"],"Api-Version":["1.40"]}}
```

The example here has a 'small' response, in reality we're dealing with responses as big as "size":2995782" on the same interval as above causing unnecessary network pressure.

**Environment**

* Prometheus version:

	2.32.0-rc0, same problem exist in previous versions.
