### ISSUE TITLE
Prometheus + (addition) operator not working

### ISSUE THREAD

**Issue by AlbMor** [prometheus/prometheus#9972]
**What did you do?**
```
prometheus_http_requests_total{} + prometheus_http_requests_total{}
```

**What did you expect to see?**
The result vector with the sum of the values

**What did you see instead? Under which circumstances?**
```
Error executing query: invalid parameter "query": 1:36: parse error: unexpected identifier "prometheus_http_requests_total"
```
**Environment**

* System information:
OS: Windows 10 2004
Docker Desktop: 3.5.2

* Prometheus version:
Prometheus: Docker image 2.30.1

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"


# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

```
