### ISSUE TITLE
image: prom/prometheus:v2.3.1 Cannot use -- storage --storage.tsdb.retention.time

### ISSUE THREAD

**Issue by helloxz** [prometheus/prometheus#9993]
Hello, I'm using docker compose to deploy Prometheus. I want to use --storage.tsdb.retention.time=7d, but a problem was encountered:
unknown long flag '--storage.tsdb.retention.time'

My docker-compose.yaml content is as follows:

```yml
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.3.1
    container_name: prometheus
    restart: always
    user: "0"
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      - /data/apps/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - /data/apps/prometheus/data:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    network_mode: "mynet"
```

You can't start using the above template, but I modified the image to `prom/prometheus:latest` There is no such problem
