### ISSUE TITLE
maximum resolution of 11,000 is not applied to interpolated timeseries

### ISSUE THREAD

**Issue by sed-i** [prometheus/prometheus#9999]
**What did you do?**
I queried for an interpolated time series
```shell
$ curl -sg "http://localhost:9090/api/v1/query?query=rate(go_gc_duration_seconds_sum[5m])[60m:10ms]"
```

**What did you expect to see?**
I expected the "exceeded maximum resolution of 11,000 points per timeseries" error message.

**What did you see instead? Under which circumstances?**
More than 11k points were returned:
```
$ curl -sg "http://localhost:9090/api/v1/query?query=rate(go_gc_duration_seconds_sum[5m])[60m:10ms]" | jq '.data.result[].values | keys' | wc -l
217020
```

**Environment**

* System information:

```
Linux 5.11.0-1022-gcp x86_64
```

* Prometheus version:

```
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@lcy01-amd64-016
  build date:       20210724-22:57:51
  go version:       go1.16.6
  platform:         linux/amd64
```

* Alertmanager version: N/A

* Prometheus configuration file:
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
```

* Alertmanager configuration file: N/A

* Logs: None
